
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_INTERVENTI_CON_INDICATORI]'))
	DROP VIEW [dbo].[ELENCO_INTERVENTI_CON_INDICATORI]
GO

CREATE VIEW [dbo].[ELENCO_INTERVENTI_CON_INDICATORI]
AS

SELECT
	SUBSTRING(TT.ORD_DTPROGR,1,4) AS ANNO,
	SUBSTRING(TT.ORD_DTPROGR,6,2) AS MESE,
	DT.ORD_TECNICO AS COD_TECNICO,
	COALESCE(PT.DESCRI,'') AS DESCR_TECNICO,
	TT.ORD_DTPROGR AS DATA_INTERVENTO,
	TT.ORD_CCODSCHE AS IMPIANTO,
	DT.ORD_ATTIVITA AS COD_ATTIVITA,
	COALESCE(PA.DESCRI,'') AS DESCR_ATTIVITA,
	DT.ORD_ORAPARSEDE AS ORA_PARTENZA_DA_SEDE,
	DT.ORD_ORAINIINT AS ORA_ARRIVO_INIZIO_EFFETTIVO,
	DT.ORD_ORAFININT AS ORA_FINE_EFFETTIVA,
	DT.ORD_ORELAV AS TTEMPO_LAV_IN_ORE,
	CAST((DT.ORD_ORELAV * 60) AS INTEGER) AS TEMPO_LAV_IN_MINUTI,
	CASE
		WHEN DT.ORD_ORAPARSEDE <> '' AND DT.ORD_ORAPARSEDE <> '  :  :  ' AND DT.ORD_ORAPARSEDE <> '00:00:00' AND DT.ORD_ORAINIINT <> '' AND DT.ORD_ORAINIINT <> '  :  :  ' AND DT.ORD_ORAINIINT <> '00:00:00' THEN
			CAST(ROUND(CAST((DATEDIFF(MINUTE,CAST(SUBSTRING(TT.ORD_DTPROGR,1,4)+'-'+SUBSTRING(TT.ORD_DTPROGR,9,2)+'-'+SUBSTRING(TT.ORD_DTPROGR,6,2)+' '+DT.ORD_ORAPARSEDE+'.001' AS DATETIME),
				CAST(SUBSTRING(TT.ORD_DTPROGR,1,4)+'-'+SUBSTRING(TT.ORD_DTPROGR,9,2)+'-'+SUBSTRING(TT.ORD_DTPROGR,6,2)+' '+DT.ORD_ORAINIINT+'.001' AS DATETIME))) AS NUMERIC(10,2)) / 60,2) AS NUMERIC(10,2))
		ELSE 0.00
	END AS TEMPO_SPOST_IN_ORE,
	CASE
		WHEN DT.ORD_ORAPARSEDE <> '' AND DT.ORD_ORAPARSEDE <> '  :  :  ' AND DT.ORD_ORAPARSEDE <> '00:00:00' AND DT.ORD_ORAINIINT <> '' AND DT.ORD_ORAINIINT <> '  :  :  ' AND DT.ORD_ORAINIINT <> '00:00:00' THEN
			DATEDIFF(MINUTE,CAST(SUBSTRING(TT.ORD_DTPROGR,1,4)+'-'+SUBSTRING(TT.ORD_DTPROGR,9,2)+'-'+SUBSTRING(TT.ORD_DTPROGR,6,2)+' '+DT.ORD_ORAPARSEDE+'.001' AS DATETIME),
				CAST(SUBSTRING(TT.ORD_DTPROGR,1,4)+'-'+SUBSTRING(TT.ORD_DTPROGR,9,2)+'-'+SUBSTRING(TT.ORD_DTPROGR,6,2)+' '+DT.ORD_ORAINIINT+'.001' AS DATETIME))
		ELSE 0
	END AS TEMPO_SPOST_IN_MINUTI
FROM VENDITE_TT AS TT
LEFT OUTER JOIN VENDITE_DT AS DT ON DT.DAGGANCIO = TT.TAGGANCIO
LEFT OUTER JOIN PARA AS PT ON PT.CODICE = 'TEI'+DT.ORD_TECNICO
LEFT OUTER JOIN PARA AS PA ON PA.CODICE = 'ATT'+DT.ORD_ATTIVITA
WHERE TT.ORD_INTCLOSE = 1 AND COALESCE(DT.ORD_TECNICO,'') <> ''

GO

SELECT * FROM [ELENCO_INTERVENTI_CON_INDICATORI] ORDER BY ANNO,MESE,DATA_INTERVENTO,COD_TECNICO,COD_ATTIVITA