
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[STORICO_INTERVENTI]'))
	DROP VIEW [dbo].[STORICO_INTERVENTI]
GO

CREATE VIEW [dbo].[STORICO_INTERVENTI]
AS

SELECT
	SUBSTRING(TT.ORD_DTPROGR,1,4) AS ANNO,
	TT.ORD_DTPROGR AS DATA_INTERVENTO,
	TT.ORD_NUMORD AS NR_INTERVENTO,
	TT.ORD_DATORD AS DATA_REG,
	TT.ORD_CCODSCHE AS IMPIANTO,
	TT.ORD_NUMFAT AS NR_FATTURA,
	TT.ORD_DATFAT AS DATA_FATTURA,
	TT.ORD_RAGSOC AS CLIENTE,
	RTRIM(TT.ORD_INDIRI)+'  '+RTRIM(TT.ORD_CAP)+'  '+RTRIM(TT.ORD_LOCALI)+' ('+RTRIM(ORD_PROVIN)+')' AS INDIRIZZO,
	DT.ORD_TECNICO AS COD_TECNICO,
	COALESCE(PT.DESCRI,'') AS DESCR_TECNICO,
	DT.ORD_ATTIVITA AS COD_ATTIVITA,
	COALESCE(PA.DESCRI,'') AS DESCR_ATTIVITA,
	CAST(DT.ORD_RAPPORT AS VARCHAR(8000)) AS RELAZIONE_INTERVENTO
FROM VENDITE_TT AS TT
LEFT OUTER JOIN VENDITE_DT AS DT ON DT.DAGGANCIO = TT.TAGGANCIO
LEFT OUTER JOIN PARA AS PT ON PT.CODICE = 'TEI'+DT.ORD_TECNICO
LEFT OUTER JOIN PARA AS PA ON PA.CODICE = 'ATT'+DT.ORD_ATTIVITA
WHERE TT.ORD_INTCLOSE = 1 AND COALESCE(DT.ORD_TECNICO,'') <> ''

GO

SELECT * FROM [STORICO_INTERVENTI] ORDER BY DATA_INTERVENTO,IMPIANTO,COD_TECNICO,COD_ATTIVITA