
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_CLIENTI_PER_ANNO_CAT_IVA_CLI]'))
	DROP VIEW [dbo].[FATTURATO_CLIENTI_PER_ANNO_CAT_IVA_CLI]
GO

CREATE VIEW [dbo].[FATTURATO_CLIENTI_PER_ANNO_CAT_IVA_CLI]
AS

SELECT
	ANNO,
	COD_CATEG,
	COD_IVA,
	DESCR_IVA,
	COD_CLIENTE,
	RAG_SOCIALE,
	DESCR_CATEG,
	CAST(ROUND(SUM(VALORE),10,2) AS NUMERIC(10,2)) AS VALORE_ANNO
FROM (
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		COALESCE(CL.CLI_CATCLI,'') AS COD_CATEG,
		DD.ORD_IVA AS COD_IVA,
		RTRIM(COALESCE(P_IVA.DESCRI,'')) AS DESCR_IVA,
		TT.ORD_CODCLI AS COD_CLIENTE,
		RTRIM(TT.ORD_RAGSOC) AS RAG_SOCIALE,
		RTRIM(COALESCE(P_CAC.DESCRI,'')) AS DESCR_CATEG,
		CASE SUBSTRING(P_TOP.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_VALORE * TT.ORD_CAMBIO AS VALORE
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN U_FAT_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO AND DD.ORD_CODART <> '' AND DD.ORD_DESART <> '*** COMMENTO ***'
	LEFT OUTER JOIN U_ANA_CL AS CL ON CL.CLI_CODCLI = TT.ORD_CODCLI
	LEFT OUTER JOIN PARA AS P_CAC ON P_CAC.CODICE = 'CAC'+CL.CLI_CATCLI
	LEFT OUTER JOIN PARA AS P_IVA ON P_IVA.CODICE = 'IVA'+DD.ORD_IVA
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
) AS MAIN
GROUP BY
	ANNO,
	COD_CLIENTE,
	RAG_SOCIALE,
	COD_CATEG,
	DESCR_CATEG,
	COD_IVA,
	DESCR_IVA

GO

SELECT * FROM FATTURATO_CLIENTI_PER_ANNO_CAT_IVA_CLI ORDER BY ANNO,COD_CATEG,COD_IVA,COD_CLIENTE