
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LISTINI_MTZ]'))
	DROP VIEW [dbo].[LISTINI_MTZ]
GO

CREATE VIEW [dbo].[LISTINI_MTZ]
AS

SELECT 
	LI.LIS_CODLIS AS CODICE,
	LI.LIS_DATLIS AS VALIDO_DAL,
	LI.LIS_ALLIST AS VALIDO_AL,
	LI.LIS_CODRAG AS COD_RAGGRUPPAMENTO,
	LI.LIS_REVISI AS A_TARIFFA_REVISIONE_DAM,
	LI.LIS_ATTREV AS A_COD_ATTIVITA_REVISIONE_DAM,
	LI.LIS_IMPRVO AS A2_TARIFFA_REVISIONE_ORD,
	LI.LIS_ATTRVO AS A2_COD_ATTIVITA_REVISIONE_ORD,
	LI.LIS_IMPRFG AS A3_TARIFFA_RICERCA_PERDITE_FGAS,
	LI.LIS_ATTRFG AS A3_COD_ATTIVITA_RICERCA_PERDITE_FGAS,
	LI.LIS_ABBONSEMP AS B_TARIFFA_ABBONAMENTO_SEMPLICE,
	LI.LIS_ATTABBONSEMP AS B_COD_ATTIVITA_ABBONAMENTO_SEMPLICE,
	LI.LIS_ABBONCOMP AS C_TARIFFA_ABBONAMENTO_COMPLETO,
	LI.LIS_ATTABBONCOMP AS C_COD_ATTIVITA_ABBONAMENTO_COMPLETO,
	LI.LIS_IMPABT AS C2_TARIFFA_ABBONAM_TOP_SENZA_DAM,
	LI.LIS_ATTABT AS C2_COD_ATTIVITA_ABBONAM_TOP_SENZA_DAM,
	LI.LIS_PULIZIA AS TARIFFA_PULIZIA_CALDAIA,
	LI.LIS_ATTPULIZIA AS COD_ATTIVITA_PULIZIA_CALDAIA,
	LI.LIS_ANALCOMBU AS TARIFFA_ANALISI_COMBUSTIONE,
	LI.LIS_ATTANALCOMBU AS COD_ATTIVITA_ANALISI_COMBUSTIONE,
	LI.LIS_REVADC AS TARIFFA_REV_ADC,
	LI.LIS_ATTREVADC AS COD_ATTIVITA_REV_ADC,
	CAST(COALESCE(STUFF((SELECT '; da ' + CAST(CAST(ROUND(POTKWDA,2) AS NUMERIC(10,2)) AS VARCHAR(20)) + 'kW a ' + CAST(CAST(ROUND(POTKWAL,2) AS NUMERIC(10,2)) AS VARCHAR(20)) + 'kW ' + CAST(CAST(ROUND(IMPBOLLO,2) AS NUMERIC(10,2)) AS VARCHAR(20)) + '€'
							FROM IMPIANTI_LB AS LB
							WHERE LI.LIS_CODLIS = LB.CODLIS
							ORDER BY CODLIS, POTKWDA
                FOR XML PATH('')
            ),1,2,''),'') AS NVARCHAR(254)) AS BOLLINO,
	LI.LIS_NOTELIS AS NOTE
FROM IMPIANTI_LI AS LI

GO

SELECT * FROM LISTINI_MTZ ORDER BY VALIDO_DAL,CODICE