
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CONFRONTO_DAM_IMPIANTI_INTERVENTI]'))
	DROP VIEW [dbo].[CONFRONTO_DAM_IMPIANTI_INTERVENTI]
GO

CREATE VIEW [dbo].[CONFRONTO_DAM_IMPIANTI_INTERVENTI]
AS

SELECT * FROM (
	SELECT
		COD_IMPIANTO,
		--TIPO_INTERVENTO,
		MAX(DATA_ESECUZIONE_INTERVENTO_DAM) AS DATA_ULT_ESECUZIONE_INTERVENTO_DAM,
		DATA_ULTIMA_MANUTENZIONE_DAM_COMPONENTE,
		LINK_COMPONENTE
	FROM (
		SELECT
			ORD_CCODSCHE AS COD_IMPIANTO, 
			TIPO_INTERVENTO,
			ORD_DTPROGR AS DATA_ESECUZIONE_INTERVENTO_DAM, 
			DT_ULT_MAN AS DATA_ULTIMA_MANUTENZIONE_DAM_COMPONENTE, 
			COALESCE(ORD_LINKCOMP,'') AS LINK_COMPONENTE
		FROM (
			SELECT
				TT.ORD_CCODSCHE, 
				CASE WHEN DD.ORD_CODART = '2.AUT' THEN 'AUTOCERTIFICAZIONE DAM' WHEN DT.ORD_ATTIVITA = '003' THEN 'PRIMA ACCENSIONE' ELSE '' END AS TIPO_INTERVENTO,
				TT.ORD_DTPROGR, 
				COALESCE(ID.DT_ULT_MAN,'') AS DT_ULT_MAN, 
				ID.ORD_LINKCOMP
			FROM VENDITE_TT AS TT
			LEFT OUTER JOIN VENDITE_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO
			LEFT OUTER JOIN VENDITE_DT AS DT ON DT.DAGGANCIO = TT.TAGGANCIO
			LEFT OUTER JOIN VENDITE_DC AS DC ON DC.DAGGANCIO = TT.TAGGANCIO AND DC.TIPO_COMPONENTE = '001'
			LEFT OUTER JOIN IMPIANTI_DD AS ID ON ID.TIPO_COMPONENTE = '001' AND DC.LINKCOMP = ID.ORD_LINKCOMP
			WHERE (DD.ORD_CODART = '2.AUT' OR DT.ORD_ATTIVITA = '003' OR DT.ORD_ATTIVITA = '002') AND TT.ORD_INTCLOSE = 1
			) AS MAIN
			--WHERE ORD_CCODSCHE = 'TREV.C.REVELLINO'
		) AS MAIN2
	GROUP BY
		COD_IMPIANTO,
		--TIPO_INTERVENTO,
		DATA_ULTIMA_MANUTENZIONE_DAM_COMPONENTE,
		LINK_COMPONENTE
	) AS MAIN3
WHERE DATA_ULT_ESECUZIONE_INTERVENTO_DAM <> DATA_ULTIMA_MANUTENZIONE_DAM_COMPONENTE

GO

SELECT * FROM [CONFRONTO_DAM_IMPIANTI_INTERVENTI] ORDER BY COD_IMPIANTO