
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_FORNITORI_PER_ANNO_IVA_FOR]'))
	DROP VIEW [dbo].[FATTURATO_FORNITORI_PER_ANNO_IVA_FOR]
GO

CREATE VIEW [dbo].[FATTURATO_FORNITORI_PER_ANNO_IVA_FOR]
AS

SELECT
	ANNO,
	COD_IVA,
	DESCR_IVA,
	COD_FORNITORE,
	RAG_SOCIALE,
	CAST(ROUND(SUM(VALORE),10,2) AS NUMERIC(10,2)) AS VALORE_ANNO
FROM (
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		DD.ORD_IVA AS COD_IVA,
		RTRIM(COALESCE(P_IVA.DESCRI,'')) AS DESCR_IVA,
		TT.ORD_CODCLI AS COD_FORNITORE,
		RTRIM(TT.ORD_RAGSOC) AS RAG_SOCIALE,
		--CASE SUBSTRING(P_TOP.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_VALORE * TT.ORD_CAMBIO AS VALORE
		DD.ORD_VALORE * TT.ORD_CAMBIO AS VALORE  -- ERASMO - 15/04/2025 - IL CAMPO ORD_VALORE CONTIENE GIA' IL SEGNO NECESSARIO (FATTURA O NOTA DI CREDITO)
	FROM U_FAF_TT AS TT
	LEFT OUTER JOIN U_FAF_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO
	LEFT OUTER JOIN PARA AS P_IVA ON P_IVA.CODICE = 'IVA'+DD.ORD_IVA
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
) AS MAIN
GROUP BY
	ANNO,
	COD_FORNITORE,
	RAG_SOCIALE,
	COD_IVA,
	DESCR_IVA

GO

SELECT * FROM FATTURATO_FORNITORI_PER_ANNO_IVA_FOR WHERE ANNO = '2024' ORDER BY ANNO,COD_IVA,COD_FORNITORE