
 -- VISTA LOCALITA DI CONSEGNA
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[REGISTRO_ORDINI_FORNITORI]'))
	DROP VIEW [dbo].[REGISTRO_ORDINI_FORNITORI]
GO

CREATE VIEW [dbo].[REGISTRO_ORDINI_FORNITORI]
AS
	SELECT
		 SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO
		,TT.ORD_CHIUSO AS CHIUSO
		,TT.ORD_NUMORD AS NR_ORDINE
		,TT.ORD_DATORD AS DATA_ORDINE
		,TT.ORD_CODCLI AS COD_FORNITORE
		,TT.ORD_RAGSOC AS RAG_SOCIALE
		,TT.ORD_RIFERI AS RIFERIMENTO
		,COALESCE((SELECT TOP 1 RTRIM(ORD_NUMORD) + ' del ' + DBO.RIBALTA2(ORD_DATOR2) FROM U_BFO_TT WHERE TAGGANCIO IN (SELECT DAGGANCIO FROM U_BFO_DD WHERE ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)),'') AS RIF_DDT_FORN
		,TT.ORD_VARIE AS RIF_FATTURA
	FROM U_ORF_TT AS TT

GO

SELECT * FROM REGISTRO_ORDINI_FORNITORI WHERE ANNO = '2024'