
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI_CON_GIACENZE_PER_LISTINO_FORNITORE]'))
	DROP VIEW [dbo].[ARTICOLI_CON_GIACENZE_PER_LISTINO_FORNITORE]
GO

CREATE VIEW [dbo].[ARTICOLI_CON_GIACENZE_PER_LISTINO_FORNITORE]
AS

SELECT
	COD_LIST_FORN,
	DESCR_LIST_FORN,
	COD_ART,
	DESCR_ART,
	ESTENS_DESCR,
	COD_MAG,
	UM,
	SUM(GIACENZA) AS GIACENZA,
	COALESCE((SELECT TOP 1
			CASE RTRIM(RUL_FILA_X) WHEN '' THEN '' ELSE '' + RTRIM(RUL_FILA_X) END + 
			CASE RTRIM(RUL_PIAN_X) WHEN '' THEN '' ELSE ' - ' + RTRIM(RUL_PIAN_X) END + 
			CASE RTRIM(RUL_UBIC_X) WHEN '' THEN '' ELSE ' - ' + RTRIM(RUL_UBIC_X) END AS LOCAZ
			FROM LOC_RULES WHERE COD_MAG = RUL_CODMAG AND SUBSTRING(RUL_EXPRESSION,1,8000) LIKE '%ART_CODPRI = ''' + RTRIM(COD_ART) + '''' ORDER BY RUL_NOME),'') AS LOCAZ_PREDEF
FROM (
	SELECT
		AN.ART_CODLIS AS COD_LIST_FORN,
		COALESCE(P_TLF.DESCRI,'') AS DESCR_LIST_FORN,
		PR.ART_CODPRI AS COD_ART,
		COALESCE(PR.ART_DESCR,'') AS DESCR_ART,
		COALESCE(PR.ART_DESEST,'') AS ESTENS_DESCR,
		COALESCE(GG.MAG_CODMAG,'') AS COD_MAG,
		PR.ART_UMMAGA AS UM,
		COALESCE(GG.MAG_GIACEN,0) AS GIACENZA
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN U_MAG_GG AS GG ON GG.MAG_ANAART = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS P_TLF ON P_TLF.CODICE = 'TLF'+AN.ART_CODLIS
	) AS MAIN
GROUP BY 
	COD_LIST_FORN,
	DESCR_LIST_FORN,
	COD_ART,
	DESCR_ART,
	ESTENS_DESCR,
	COD_MAG,
	UM

GO

SELECT * FROM [ARTICOLI_CON_GIACENZE_PER_LISTINO_FORNITORE] ORDER BY COD_LIST_FORN,COD_ART,COD_MAG