USE [CARDIOLINE]
GO

/****** Object:  Table [dbo].[MOVCO]    Script Date: 07/10/2013 10:13:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CARD_MOVCO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CARD_MOVCO]
GO

CREATE TABLE [dbo].[CARD_MOVCO](
	[NUMERO] [char](7) NULL,
	[RIGA] [char](5) NULL,
	[ESEREGISTR] [char](4) NULL,
	[DATAREG] [char](8) NULL,
	[ESECOMPET] [char](4) NULL,
	[DATACOMPET] [char](8) NULL,
	[DATANEGOZ] [char](8) NULL,
	[DATAVALUTA] [char](8) NULL,
	[DATAMATURA] [char](8) NULL,
	[DATASCAD] [char](8) NULL,
	[DATADECORR] [char](8) NULL,
	[DATAPRESEN] [char](8) NULL,
	[DATAPROTOC] [char](8) NULL,
	[DATASALDAC] [char](8) NULL,
	[DATACAMBIO] [char](8) NULL,
	[DATAINIZIO] [char](8) NULL,
	[DATAFINE] [char](8) NULL,
	[DATAPRBANC] [char](8) NULL,
	[DATADOCUM] [char](8) NULL,
	[NUMDOCUM] [char](10) NULL,
	[NUMPROTOC] [char](7) NULL,
	[NUMRIFSALD] [char](7) NULL,
	[NUMDISTINT] [char](7) NULL,
	[NUMEFFETTO] [char](7) NULL,
	[NUMPRBANC] [char](7) NULL,
	[SOTTOCONTO] [char](10) NULL,
	[C_F] [char](1) NULL,
	[CONTROPART] [char](10) NULL,
	[SOTDISTINT] [char](10) NULL,
	[CAUSALE] [char](3) NULL,
	[DESCRAGG] [char](30) NULL,
	[DESLINGUA] [char](30) NULL,
	[SEGNO] [char](1) NULL,
	[IMPORTO] [float] NULL,
	[CODVALUTA] [char](3) NULL,
	[IMPVALUTA] [float] NULL,
	[CAMBIO] [float] NULL,
	[IMPRATEO] [float] NULL,
	[IMPRISCONT] [float] NULL,
	[NUMRATA] [float] NULL,
	[TOTRATE] [float] NULL,
	[IMPFATTURA] [float] NULL,
	[CODBANCA] [char](11) NULL,
	[CODBANCAPR] [char](11) NULL,
	[CCOSTO] [char](6) NULL,
	[REGIVA] [char](2) NULL,
	[TIPODOCIVA] [char](2) NULL,
	[CODPAGAM] [char](4) NULL,
	[AGENTE] [char](5) NULL,
	[CAPOZONA] [char](5) NULL,
	[NRIGGIORN] [char](7) NULL,
	[SOSPESO_SN] [char](1) NULL,
	[SIMULAZ_SN] [char](1) NULL,
	[COMPTER_SN] [char](1) NULL,
	[DISTCTERZ] [char](7) NULL,
	[SOLOANA_SN] [char](1) NULL,
	[TEMPORA_SN] [char](1) NULL,
	[SCADENZ_SN] [char](1) NULL,
	[ATT_PASSIV] [char](1) NULL,
	[TIPOEFFETT] [char](1) NULL,
	[PAGE_C_SN] [char](1) NULL,
	[INSOLUT_SN] [char](1) NULL,
	[ANTVALU_SN] [char](1) NULL,
	[CTRLBAN_SN] [char](1) NULL,
	[TIPOCAUSAL] [char](1) NULL,
	[STAMPAT_SN] [char](1) NULL,
	[CONSECB_SN] [char](1) NULL,
	[P_PAREG_SN] [char](1) NULL,
	[MOV_IVA_SN] [char](1) NULL,
	[MOV_VAL_SN] [char](1) NULL,
	[TIPONUMERA] [char](1) NULL,
	[AR74TER] [char](1) NULL,
	[INTERESSI] [float] NULL,
	[SPESE] [float] NULL,
	[DATADECINT] [char](8) NULL,
	[NUMLTSOLLE] [char](7) NULL,
	[DATLTSOLLE] [char](8) NULL,
	[FILELTSOLL] [char](8) NULL,
	[NUMSOLLECI] [float] NULL,
	[DATULTLT] [char](8) NULL,
	[IMPRICEVUT] [float] NULL,
	[SPPAGAT_SN] [char](1) NULL,
	[INTPAGA_SN] [char](1) NULL,
	[INSPAGA_SN] [char](1) NULL,
	[RIEMISS_SN] [char](1) NULL,
	[CODICEIVA] [char](4) NULL,
	[IMPORTOIVA] [float] NULL,
	[DTCOMPCONT] [char](8) NULL,
	[FILE1] [char](8) NULL,
	[CASO] [char](1) NULL,
	[STATO] [char](1) NULL,
	[ULT_AGG] [char](8) NULL,
	[UTENTE] [char](8) NULL,
	[RIFENUMERO] [char](7) NULL,
	[AVVOCATO] [char](10) NULL,
	[PRATICANUM] [char](7) NULL,
	[PRATICADAT] [char](8) NULL,
	[INSOLUTNUM] [char](7) NULL,
	[INSOLUTRIG] [char](5) NULL,
	[AGGIORN_SN] [char](1) NULL,
	[CONTCORR] [char](15) NULL,
	[EIMPORTO] [float] NULL,
	[EIMPFATTUR] [float] NULL,
	[ESPESE] [float] NULL,
	[EIMPRICEVU] [float] NULL,
	[EIMPORTOIV] [float] NULL,
	[ECAMBIO] [float] NULL,
	[ARROTOND] [char](1) NULL,
	[VALCONT_SN] [char](1) NULL,
	[DOCUM_DEST] [char](3) NULL,
	[EXTNUMBER] [char](20) NULL,
	[TRANSF_NR] [char](8) NULL,
	[TRANSF_DT] [char](8) NULL,
	[PROBPAGAM] [char](1) NULL,
	[MAG_NUMERO] [char](7) NULL,
	[MAG_RIGA] [char](5) NULL,
	[BLOCSCADE] [char](1) NULL,
	[CIN] [char](1) NULL,
	[BLOCSOLLE] [char](1) NULL,
	[MOTBLOCCO] [char](50) NULL,
	[IBAN] [char](34) NULL,
	[ESCBENSTR] [char](1) NULL,
	[CIG] [char](10) NULL,
	[CUP] [char](15) NULL,
	[CODEVENTO] [char](30) NULL,
	[IVACALC_SN] [char](1) NULL,
	[RIFXCASSA] [char](7) NULL,
	[IVAXCAS_SN] [char](1) NULL,
	[EIMPSLOR] [float] NULL,
	[TIPOSEQSDD] [char](1) NULL,
	[TPSQSDDANA] [char](1) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


