
/****** Object:  Table [dbo].[CFVEN]    Script Date: 20/06/2014 21:58:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARD_CFVEN](
	[TIPO] [char](1) NULL,
	[CODCF] [char](10) NULL,
	[CODINDSP] [char](3) NULL,
	[CODINDDOC] [char](3) NULL,
	[CODAG] [char](5) NULL,
	[CODPORTO] [char](3) NULL,
	[CODVETT1] [char](5) NULL,
	[CODVETT2] [char](5) NULL,
	[CODVETT3] [char](5) NULL,
	[ASSFIS] [char](4) NULL,
	[CODSCINC] [char](3) NULL,
	[CODLIST] [char](5) NULL,
	[SCONTOCL] [float] NULL,
	[CODABIPR] [char](5) NULL,
	[CODCABPR] [char](5) NULL,
	[SPEDIZ1] [char](5) NULL,
	[SPEDIZ2] [char](5) NULL,
	[SCONTO1] [float] NULL,
	[SCONTO2] [float] NULL,
	[SCONTO3] [float] NULL,
	[SCONTO4] [float] NULL,
	[SCONTO5] [float] NULL,
	[MAGGIORAZ1] [float] NULL,
	[MAGGIORAZ2] [float] NULL,
	[IVAOMAG_SN] [char](1) NULL,
	[IVACOMP_SN] [char](1) NULL,
	[IVARIDO_SN] [char](1) NULL,
	[RAGGDOC] [char](1) NULL,
	[TESNOTE1] [char](60) NULL,
	[TESNOTE2] [char](60) NULL,
	[PIENOTE1] [char](60) NULL,
	[PIENOTE2] [char](60) NULL,
	[ZONA] [char](4) NULL,
	[PERCIP_SN] [char](1) NULL,
	[COGNOME] [char](25) NULL,
	[NOME] [char](25) NULL,
	[SESSO] [char](1) NULL,
	[COD_IDENT] [char](21) NULL,
	[DATA_NASC] [char](8) NULL,
	[COMUN_NASC] [char](4) NULL,
	[STATO_NASC] [char](3) NULL,
	[TIPASS770] [char](1) NULL,
	[TIPDOCIVA] [char](1) NULL,
	[PFAX] [char](10) NULL,
	[FAX] [char](30) NULL,
	[TELEX] [char](30) NULL,
	[FIDO] [float] NULL,
	[CONTCORR] [char](15) NULL,
	[SC_RICAVO] [char](10) NULL,
	[SC_COSTO] [char](10) NULL,
	[CCOSTO] [char](6) NULL,
	[IMPPLAFOND] [float] NULL,
	[NUM_LETT] [float] NULL,
	[DATA_LETT] [char](8) NULL,
	[DATA_ARRIV] [char](8) NULL,
	[DATA_DECOR] [char](8) NULL,
	[DATA_FINE] [char](8) NULL,
	[CONTRPARSC] [char](10) NULL,
	[TIPCONTRPA] [char](3) NULL,
	[E_MAILL] [char](64) NULL,
	[INTERNETL] [char](64) NULL,
	[COD_CLIFO] [char](10) NULL,
	[CLIOCCASIO] [char](1) NULL,
	[NUMCOPFATT] [float] NULL,
	[RAGFATDEST] [char](1) NULL,
	[INDIRMULTI] [char](1) NULL,
	[GGPART] [char](2) NULL,
	[MSALTO1] [char](2) NULL,
	[MSALTO2] [char](2) NULL,
	[GGSALTO] [char](2) NULL,
	[CLIFORCORR] [char](10) NULL,
	[CARICA] [char](3) NULL,
	[FILE1] [char](8) NULL,
	[FILE2] [char](8) NULL,
	[FILE3] [char](8) NULL,
	[STATO] [char](1) NULL,
	[UTENTE] [char](8) NULL,
	[ULT_AGG] [char](8) NULL,
	[FATIVASOSP] [char](1) NULL,
	[PRBOLLA_SN] [char](1) NULL,
	[CLASSIFIC1] [char](5) NULL,
	[CLASSIFIC2] [char](5) NULL,
	[CLASSIFIC3] [char](5) NULL,
	[CLASSIFIC4] [char](5) NULL,
	[MSGDOCUM] [char](1) NULL,
	[TIPOPERCI] [char](1) NULL,
	[SEDEINPS] [char](5) NULL,
	[POSIINPS] [char](20) NULL,
	[CODMAGAZ] [char](3) NULL,
	[CAUSALE770] [char](1) NULL,
	[SOTDISTINT] [char](10) NULL,
	[EFIDO] [float] NULL,
	[EIMPPLAFON] [float] NULL,
	[VALSEC_SN] [char](1) NULL,
	[ADDSPVA_SN] [char](1) NULL,
	[ADDSPPA_SN] [char](1) NULL,
	[ADDSPBO_SN] [char](1) NULL,
	[IMPMORD] [float] NULL,
	[IMPMSPED] [float] NULL,
	[EIMPMORD] [float] NULL,
	[EIMPMSPED] [float] NULL,
	[NNOTE] [char](50) NULL,
	[DOMIPERC] [char](40) NULL,
	[CAP_PERC] [char](5) NULL,
	[LOC_PERC] [char](20) NULL,
	[PROV_PERC] [char](5) NULL,
	[COD_COMPER] [char](4) NULL,
	[MOD_SPEDI] [char](3) NULL,
	[CODIBAN] [char](34) NULL,
	[CIN] [char](1) NULL,
	[BIC] [char](11) NULL,
	[CARTWEB] [char](64) NULL,
	[PROVAGEN] [float] NULL,
	[PROVCAPO] [float] NULL,
	[USAPRVEN] [char](1) NULL,
	[DATACREAZ] [char](8) NULL,
	[NUMLETT] [char](16) NULL,
	[GG_MEDIPAG] [float] NULL,
	[CODDESTPA] [char](6) NULL,
	[FATTPA_SN] [char](1) NULL,
	[ALLEGA_SN] [char](1) NULL,
	[DT_AT_FTPA] [char](8) NULL,
	[RIF_AMM_PA] [char](20) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


