USE [CARDIOLINE]
GO

/****** Object:  Table [dbo].[ANAMAGA]    Script Date: 03/10/2013 12:46:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARD_ANAMAGA](
	[CODICE] [char](30) NULL,
	[DESCRIZION] [char](40) NULL,
	[CODICEALTE] [char](30) NULL,
	[TIPO] [char](1) NULL,
	[UNITAMIACQ] [char](3) NULL,
	[UNITAMIVEN] [char](3) NULL,
	[UNITAMITEC] [char](3) NULL,
	[COEFACQVEN] [float] NULL,
	[COEFTECVEN] [float] NULL,
	[VALUTAVEND] [char](3) NULL,
	[PREZZOVALU] [float] NULL,
	[DATACREAZI] [char](8) NULL,
	[VALORIZZAZ] [char](1) NULL,
	[LISTINOACQ] [char](5) NULL,
	[LISTINOVEN] [char](5) NULL,
	[GRUPPOMERC] [char](9) NULL,
	[RAGGRUPFIS] [char](5) NULL,
	[CODICEIVA] [char](4) NULL,
	[CODIVAOLD] [char](4) NULL,
	[CODIVARID] [char](4) NULL,
	[CODIVARIDB] [char](4) NULL,
	[DATVECALIQ] [char](8) NULL,
	[CONTRASIVA] [char](2) NULL,
	[CLASDOGANA] [char](10) NULL,
	[CODICEFORN] [char](10) NULL,
	[CONTROACQ] [char](10) NULL,
	[CONTROVEN] [char](10) NULL,
	[PRULTACQUI] [float] NULL,
	[DTULTACQUI] [char](8) NULL,
	[SCORTASICU] [float] NULL,
	[NUMPEZCONF] [float] NULL,
	[PUNTORIORD] [float] NULL,
	[QUANTRIORD] [float] NULL,
	[GIORNRIORD] [float] NULL,
	[PRSTANDARD] [float] NULL,
	[PESOKG] [float] NULL,
	[CODICEIMBA] [char](5) NULL,
	[NUMPEZIMBA] [float] NULL,
	[NUMPEZSTRA] [float] NULL,
	[NUMSTRATI] [float] NULL,
	[CODTAGLIA] [char](2) NULL,
	[CODICEVUOT] [char](30) NULL,
	[CATESCONTO] [char](3) NULL,
	[PAGLISTINO] [float] NULL,
	[PROGINTPAG] [float] NULL,
	[ASSORTIMEN] [char](1) NULL,
	[ESAURIMENT] [char](1) NULL,
	[INARRIVO] [char](1) NULL,
	[CODICEUBIC] [char](10) NULL,
	[ARROTONDAM] [float] NULL,
	[MARCHIO] [char](6) NULL,
	[LOTTO] [char](1) NULL,
	[CODMAGPROD] [char](3) NULL,
	[FILE1] [char](8) NULL,
	[FILE2] [char](8) NULL,
	[FILE3] [char](8) NULL,
	[FLAG1] [char](1) NULL,
	[FLAG2] [char](1) NULL,
	[FLAG3] [char](1) NULL,
	[FLAG4] [char](1) NULL,
	[FLAG5] [char](1) NULL,
	[STATO] [char](1) NULL,
	[UTENTE] [char](8) NULL,
	[ULT_AGG] [char](8) NULL,
	[CODICERICE] [char](30) NULL,
	[COEFINTRA] [float] NULL,
	[EPREZZOVAL] [float] NULL,
	[EPRULTACQU] [float] NULL,
	[EPRSTANDAR] [float] NULL,
	[EARROTONDA] [float] NULL,
	[CCOSTO] [char](6) NULL,
	[UBICAZ_SN] [char](1) NULL,
	[LOTTI_SN] [char](1) NULL,
	[TIP_OR_LOT] [char](1) NULL,
	[SOLOQT_SN] [char](1) NULL,
	[NOTASTD] [char](5) NULL,
	[PREZZOLIRE] [float] NULL,
	[SCACQ1] [float] NULL,
	[SCACQ2] [float] NULL,
	[SCACQ3] [float] NULL,
	[SCACQ4] [float] NULL,
	[SCACQ5] [float] NULL,
	[SCACQ6] [float] NULL,
	[SCACQ7] [float] NULL,
	[SCVEN1] [float] NULL,
	[SCVEN2] [float] NULL,
	[SCVEN3] [float] NULL,
	[SCVEN4] [float] NULL,
	[SCVEN5] [float] NULL,
	[SCVEN6] [float] NULL,
	[SCVEN7] [float] NULL,
	[PREZZOEURO] [float] NULL,
	[USAPRACQ] [char](1) NULL,
	[PRZLIRE2] [float] NULL,
	[SCACQ12] [float] NULL,
	[SCACQ22] [float] NULL,
	[SCACQ32] [float] NULL,
	[SCACQ42] [float] NULL,
	[SCACQ52] [float] NULL,
	[SCACQ62] [float] NULL,
	[SCACQ72] [float] NULL,
	[SCVEN12] [float] NULL,
	[SCVEN22] [float] NULL,
	[SCVEN32] [float] NULL,
	[SCVEN42] [float] NULL,
	[SCVEN52] [float] NULL,
	[SCVEN62] [float] NULL,
	[SCVEN72] [float] NULL,
	[PRZEURO2] [float] NULL,
	[DATAVALID] [char](8) NULL,
	[USAPRACQ2] [char](1) NULL,
	[MATRIC_SN] [char](1) NULL,
	[DTIGAR_SN] [char](1) NULL,
	[DTFGAR_SN] [char](1) NULL,
	[DTIMAN_SN] [char](1) NULL,
	[DTFMAN_SN] [char](1) NULL,
	[MATUSR1_SN] [char](1) NULL,
	[MATUSR2_SN] [char](1) NULL,
	[MATUSR3_SN] [char](1) NULL,
	[DESCRUSR1] [char](20) NULL,
	[DESCRUSR2] [char](20) NULL,
	[DESCRUSR3] [char](20) NULL,
	[DURGARANZ] [float] NULL,
	[SERVIZI_SN] [char](1) NULL,
	[COD_SERVIZ] [char](8) NULL,
	[EROGAZIONE] [char](1) NULL,
	[DESCRART01] [char](40) NULL,
	[DESCRART02] [char](40) NULL,
	[DESARCOMPL] [char](120) NULL,
	[NATURAPAG] [char](1) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


