USE [CARDIOLINE]
GO

/****** Object:  Table [dbo].[MOVIMAG]    Script Date: 30/10/2013 14:34:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARD_MOVIMAG](
	[ESERCIZIO] [char](4) NULL,
	[NUMERO] [char](7) NULL,
	[RIGA] [char](5) NULL,
	[TIPO] [char](2) NULL,
	[DATA] [char](8) NULL,
	[ESEDOC] [char](4) NULL,
	[NUMERODOC] [char](7) NULL,
	[RIGADOC] [char](5) NULL,
	[TIPODOC] [char](2) NULL,
	[DATADOC] [char](8) NULL,
	[ESERCIPROT] [char](4) NULL,
	[NUMEROPROT] [char](7) NULL,
	[RIGAPROT] [char](5) NULL,
	[TIPOPROT] [char](2) NULL,
	[DATAPROT] [char](8) NULL,
	[TIPOEFFET] [char](1) NULL,
	[ESERIF] [char](4) NULL,
	[NUMERORIF] [char](7) NULL,
	[RIGARIF] [char](5) NULL,
	[TIPORIF] [char](2) NULL,
	[DATARIF] [char](8) NULL,
	[ESECOLLEG] [char](4) NULL,
	[NUMCOLLEG] [char](7) NULL,
	[RIGACOLLEG] [char](5) NULL,
	[TIPOCOLLEG] [char](2) NULL,
	[DATACOLLEG] [char](8) NULL,
	[DATAPREEVA] [char](8) NULL,
	[ARTICOLO] [char](30) NULL,
	[VARIANTE] [char](10) NULL,
	[STAGIONE] [char](3) NULL,
	[MAGAZZINO] [char](3) NULL,
	[IMBALLO] [char](5) NULL,
	[UNIMISURA] [char](3) NULL,
	[MOVITAG_SN] [char](1) NULL,
	[TIPOTAGLIA] [char](2) NULL,
	[CALZATA] [char](2) NULL,
	[CAUSALE] [char](3) NULL,
	[DESCRAGG] [char](20) NULL,
	[C_F] [char](1) NULL,
	[CLI_FOR] [char](10) NULL,
	[CONTROPART] [char](10) NULL,
	[CODVALUTA] [char](3) NULL,
	[DATAVALUTA] [char](8) NULL,
	[CAMBIO] [float] NULL,
	[QUANTITA] [float] NULL,
	[QUANTCONFE] [float] NULL,
	[EVASO] [float] NULL,
	[PRNETTO] [float] NULL,
	[PRLORDO] [float] NULL,
	[PRIVACOMPR] [char](1) NULL,
	[IVAOMAGGI] [char](1) NULL,
	[PRLISTINO] [float] NULL,
	[BASERICAR] [float] NULL,
	[PERCRICAR] [float] NULL,
	[PRVALUTA] [float] NULL,
	[PRVALUTAN] [float] NULL,
	[SCONTO1] [float] NULL,
	[SCONTO2] [float] NULL,
	[SCONTO3] [float] NULL,
	[SCONTO4] [float] NULL,
	[SCONTO5] [float] NULL,
	[MAGGIOR1] [float] NULL,
	[MAGGIOR2] [float] NULL,
	[CODIVA] [char](4) NULL,
	[CODLISTIN] [char](5) NULL,
	[PESOKG] [float] NULL,
	[NUMCOLLI] [float] NULL,
	[NUMPARTITA] [float] NULL,
	[AGENTE] [char](5) NULL,
	[PROVAGENTE] [float] NULL,
	[CAPOZONA] [char](5) NULL,
	[PROVCAPOZO] [float] NULL,
	[SOSPESO_SN] [char](1) NULL,
	[NOTA_SN] [char](1) NULL,
	[COMM_SN] [char](1) NULL,
	[NETTO_SN] [char](1) NULL,
	[OMAGGIO_SN] [char](1) NULL,
	[DEFINIT_SN] [char](1) NULL,
	[PROVVIS_SN] [char](1) NULL,
	[MAGFISC_SN] [char](1) NULL,
	[EVASION_SN] [char](1) NULL,
	[DISTINT_SN] [char](1) NULL,
	[INVENTARIO] [char](1) NULL,
	[CARICO] [char](1) NULL,
	[SCARICO] [char](1) NULL,
	[ACARICO] [char](1) NULL,
	[ASCARICO] [char](1) NULL,
	[IMPEGNATO] [char](1) NULL,
	[ROTTAMATO] [char](1) NULL,
	[ORDCLI] [char](1) NULL,
	[ORDFORN] [char](1) NULL,
	[ATTCOLLAUD] [char](1) NULL,
	[ATTSPEDIZ] [char](1) NULL,
	[AVALORE] [char](1) NULL,
	[AQUANTITA] [char](1) NULL,
	[AGG_TOTALI] [char](1) NULL,
	[SELEZIONE] [char](50) NULL,
	[NUMCARTELL] [float] NULL,
	[NUMCOMMESS] [float] NULL,
	[FILE1] [char](8) NULL,
	[FILE2] [char](8) NULL,
	[FILE3] [char](8) NULL,
	[UTENTE] [char](8) NULL,
	[ULT_AGG] [char](8) NULL,
	[PRSTATISTI] [float] NULL,
	[PRSTATIST1] [float] NULL,
	[NUMPROTRIF] [char](7) NULL,
	[PRSTATIST2] [float] NULL,
	[CENTRCOSTO] [char](6) NULL,
	[REVISIO_SN] [char](1) NULL,
	[AGGIORN_SN] [char](1) NULL,
	[CHIAVE_EST] [char](30) NULL,
	[FORZEVA_SN] [char](1) NULL,
	[DESARTICOL] [char](40) NULL,
	[ECAMBIO] [float] NULL,
	[EPRNETTO] [float] NULL,
	[EPRLORDO] [float] NULL,
	[EPRLISTINO] [float] NULL,
	[EBASERICAR] [float] NULL,
	[UBICAZIONE] [char](10) NULL,
	[MOLOTTI_SN] [char](1) NULL,
	[QTACQUISTO] [float] NULL,
	[PRACQUISTO] [float] NULL,
	[UNITAMIACQ] [char](3) NULL,
	[NOTAIMP_SN] [char](1) NULL,
	[NOTASTA_SN] [char](1) NULL,
	[NOTARIP_SN] [char](1) NULL,
	[BARCODE] [char](21) NULL,
	[MATRIC_SN] [char](1) NULL,
	[NUM_MATR] [char](10) NULL,
	[RETSERV_SN] [char](1) NULL,
	[SEZDOGAN] [char](6) NULL,
	[PROTINVIO] [char](6) NULL,
	[PROGSEZIO] [char](5) NULL,
	[DATA_RET] [char](8) NULL,
	[NUMERO_RET] [char](15) NULL,
	[EIMPSRVRET] [float] NULL,
	[FBREV] [char](40) NULL,
	[FBRIGA] [char](5) NULL,
	[DESCRART01] [char](40) NULL,
	[DESCRART02] [char](40) NULL,
	[DESARCOMPL] [char](120) NULL,
	[CIG] [char](10) NULL,
	[CUP] [char](15) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


