
-- PRIMA DI ESEGUIRE LE QUERY SUL SERVER REMOTO, ASSICURARSI CHE IL SERVER REMOTO E LE CREDENZIALI SIANO MEMORIZZATE NEL SYS.SERVERS TRAMITE I SEGUENTI COMANDI:
--		exec sp_addlinkedserver '10.0.18.9'
--		exec sp_addlinkedsrvlogin '10.0.18.9', 'FALSE', NULL, 'project', 'cardioline'

DELETE FROM CARDIOLINE.[dbo].CARD_INTRA
INSERT INTO CARDIOLINE.[dbo].CARD_INTRA
	select * from [10.0.18.9].CARDIOLINE.[dbo].INTRA
