
-- VISTA ELENCO_UTILIZZO_BFO_CONTO_LAVORO
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_UTILIZZO_BFO_CONTO_LAVORO]'))
	DROP VIEW [dbo].[ELENCO_UTILIZZO_BFO_CONTO_LAVORO]
GO

CREATE VIEW [dbo].[ELENCO_UTILIZZO_BFO_CONTO_LAVORO]
AS
	SELECT
		SUBSTRING(COALESCE(MOS.MOV_DTDOCU,''),1,7) AS ANNO_MESE_DDT,
		COALESCE(MOS.MOV_NUMDOC,'') AS NR_DDT,
		COALESCE(MOS.MOV_DTDOCU,'') AS DATA_DDT,
		NUMBFO AS NR_DDT_CONTO_LAV,
		DATBFO AS DATA_DDT_CONTO_LAV,
		CODFOR AS COD_FORNITORE,
		COALESCE(FR.FOR_RAGSOC,'') AS RAG_SOCIALE,
		SUM(QTASCA) AS TOT_QTASCA
	FROM BFO_CLAV_COMP AS BF
	LEFT OUTER JOIN U_FOR_AN AS FR ON FR.FOR_CODCLI = BF.CODFOR
	OUTER APPLY (SELECT TOP 1 * FROM U_MAG_MO WHERE MOV_LEGSYS = BF.SYSPRD AND MOV_SEGNO = '+' ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MOC
	OUTER APPLY (SELECT * FROM U_MAG_MO WHERE MOV_LEGAME = MOC.MOV_LEGAME AND MOV_TOP = '005' AND MOV_DOCMOD = 0) AS MOS
	GROUP BY NUMBFO, DATBFO, CODFOR, FR.FOR_RAGSOC, MOS.MOV_NUMDOC, MOS.MOV_DTDOCU

GO

SELECT * FROM ELENCO_UTILIZZO_BFO_CONTO_LAVORO ORDER BY DATA_DDT, NR_DDT
