
-- VISTA ORDINI_COINVOLTI_PER_COMPONENTE_UTILIZZATO
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_INDIRETTI_PER_COMPONENTE_UTILIZZATO]'))
	DROP VIEW [dbo].[ORDINI_INDIRETTI_PER_COMPONENTE_UTILIZZATO]
GO
CREATE VIEW [dbo].[ORDINI_INDIRETTI_PER_COMPONENTE_UTILIZZATO]
AS
	WITH AlberoDIBA
	AS (
		SELECT 
			1 AS LIVELLO,
			DIS_GRUPPO AS PADRE,
			CAST(COALESCE('*'+RTRIM(DIS_CODART)+'*','') AS VARCHAR(1000)) AS GERARCHIA,
			CAST(DIS_QTA AS numeric(19,6)) AS QTATOT,
			U_DIS_DD.*
		FROM U_DIS_DD
		--WHERE DIS_CODART = 'F250NERF'
		UNION ALL
		SELECT 
			LIVELLO + 1,
			DD.DIS_GRUPPO AS PADRE,
			CAST(AlberoDIBA.GERARCHIA+' -> '+'*'+RTRIM(DD.DIS_CODART)+'*' AS VARCHAR(1000)) AS GERARCHIA,
			CAST((AlberoDIBA.DIS_QTA * DD.DIS_QTA) AS numeric(19,6)) AS QTATOT,
			DD.*
		FROM U_DIS_DD AS DD
		INNER JOIN AlberoDIBA
		ON DD.DIS_CODART = AlberoDIBA.DIS_GRUPPO
	)

	/*
	SELECT * FROM AlberoDIBA
	ORDER BY GERARCHIA
	*/

	SELECT
		DD.ORS_CODCLI AS COD_CLIENTE,
		DD.ORS_RAGSOC AS RAG_SOCIALE,
		DD.ORS_NUMORD AS NR_ORDINE,
		DD.ORS_DATORD AS DT_ORDINE,
		DD.ORD_CODART AS COD_ARTICOLO,
		DD.ORD_DESART AS DESCRIZIONE,
		AD.GERARCHIA AS GERARCHIA_DIBA,
		DD.ORD_UM AS UM,
		DD.ORD_QTAORD AS QTA_ORDINATA,
		DD.ORD_QTAEV AS QTA_EVASA,
		(DD.ORD_QTAORD - DD.ORD_QTAEV) AS QTA_DA_EVADERE,
		AD.QTATOT AS COEFF_IMPIEGO_TOTALE,
		(DD.ORD_QTAORD - DD.ORD_QTAEV) * AD.QTATOT AS QTA_NECESSARIA_COMP_SELEZ
	FROM U_ORD_DD AS DD
	INNER JOIN AlberoDIBA AS AD ON AD.PADRE = DD.ORD_CODART
	WHERE DD.ORD_CHIUSO = 0 AND DD.ORD_QTAEV <= DD.ORD_QTAORD AND DD.DAGGANCIO IN (SELECT TAGGANCIO FROM U_ORD_TT WHERE ORD_CHIUSO = 0)

GO

SELECT * FROM ORDINI_INDIRETTI_PER_COMPONENTE_UTILIZZATO ORDER BY DT_ORDINE,NR_ORDINE