
DELETE FROM PARA WHERE CODICE LIKE 'TSI%'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('TSIAD','ADESIVI','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('TSIPR','PROFESSIONAL','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('TSIJO','JOICO','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('TSIBE','BEAUTY','')

SELECT * FROM PARA WHERE CODICE LIKE 'TSI%' ORDER BY CODICE
