/**********************************************************
 INSERIMENTO FASI DI LAVORAZIONE PER PANNELLI TRUCIOLARI
**********************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'FAL%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FAL001','LAVORAZIONE','1','PMI')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FAL002','COLLAUDO','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FAL003','SPEDIZIONE','','')

SELECT * FROM PARA WHERE CODICE LIKE 'FAL%' ORDER BY CODICE
