/********************************************************************
 INSERIMENTO PARAMETRI DI DEFAULT PER PRODUZIONE MACCHINE INDUSTRIALI
********************************************************************/

DELETE FROM PARA WHERE CODICE = 'TOPCPR'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCPR','CARICO DA PRELIEVO DI PRODUZ.','CN      N                                M')

DELETE FROM PARA WHERE CODICE = 'TOPSPR'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSPR','CARICO PER PRELIEVO DI PRODUZ.','SN      N                                M')

DELETE FROM PARA WHERE CODICE = 'TOPCAP'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCAP','VERSAMENTO DA PRODUZIONE','CN      N                                M')

DELETE FROM PARA WHERE CODICE = 'TOPSCP'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSCP','SCARICO PER PRODUZIONE','SN      N                                M                9')


UPDATE U_AZI_PB SET AZI_CAPPMIPREL = 'CPR', AZI_SCPPMIPREL = 'SPR', AZI_CAPPMIVERS = 'CAP', AZI_SCPPMIVERS = 'SCP', AZI_PMILINPF = 'PF', AZI_PMILINSL = 'SE', AZI_PMILINSE = 'SX', AZI_MAGPMIPREL = 'WIP', AZI_MAGPMIVERS = 'SEDE'
UPDATE U_AZI_PA SET AZI_PGGCLS = 60


SELECT * FROM PARA WHERE CODICE = 'TOPCPR' OR CODICE = 'TOPSPR' OR CODICE = 'TOPCAP' OR CODICE = 'TOPSCP' ORDER BY CODICE

SELECT AZI_PGGCLS,* FROM U_AZI_PA
SELECT AZI_CAPPMIPREL, AZI_SCPPMIPREL, AZI_CAPPMIVERS, AZI_SCPPMIVERS, AZI_PMILINPF, AZI_PMILINSL, AZI_PMILINSE,* FROM U_AZI_PB

