/********************************************************************
 PARAMETRO STATO CONTROLLO QUALITA'
********************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'TOP001%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPVEN%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPORD%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPOFF%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPORF%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPBFO%'
DELETE FROM PARA WHERE CODICE LIKE 'TOPFAP%'



INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOP001','VENDITA ','SV      N  C                             M  ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPVEN','VENDITA ','DS      SNNC                            SC  ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPORD','ORDINE CLIENTE ','DN         N                             M    ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPOFF','OFFERTA CLIENTE ','DN      NNNC                             M   ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPORF','ORDINE A FORNITORE ','AN         F                             M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPBFO','CARICO DA FORNITORE ','CN      NNNN                    MORA-   NM  ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPFAP','FATTURA PROFORMA ','SN      NNNC                             M     ')







SELECT * FROM PARA WHERE CODICE LIKE 'TOP001%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPVEN%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPORD%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPOFF%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPORF%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPBFO%'
SELECT * FROM PARA WHERE CODICE LIKE 'TOPFAP%'