   
/* 
**********************************************************************************************
INSERIMENTO PARAMETRO "TIPOLOGIA LISTINI AZIENDA ARTICOLO DI VENDITA E ACQUISTO" IN PARA
**********************************************************************************************
*/

-- POPOLAMENTO AUTOMATICO TIPOLOGIA LISTINI AZIENDA ARTICOLO DI VENDITA
DELETE PARA WHERE SUBSTRING(CODICE,1,3) = 'TLV'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLV01','LISTINO ITALIA','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLV14','LISTINO USD','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLV15','15% ITALIA','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLV45','LISTINO 45%','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLV50','LISTINO 50%','','')

SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'TLV' ORDER BY CODICE

UPDATE U_LIS_AV SET LIS_DESLIS = COALESCE((SELECT RTRIM(DESCRI) FROM PARA WHERE CODICE = 'TLV'+U_LIS_AV.LIS_TIPOAZI),'')


-- POPOLAMENTO AUTOMATICO TIPOLOGIA LISTINI AZIENDA ARTICOLO DI ACQUISTO
DELETE PARA WHERE SUBSTRING(CODICE,1,3) = 'TLA'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLAACQ','Listino ACQ','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLAACQT','Listino ACQT','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLADOL','Listino DOL','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,NOTE) values ('TLARMB','Listino RMB','','')

SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'TLA' ORDER BY CODICE

UPDATE U_LIS_AA SET LIS_DESLIS = COALESCE((SELECT RTRIM(DESCRI) FROM PARA WHERE CODICE = 'TLA'+U_LIS_AA.LIS_TIPOAZI),'')


/*
-- POPOLAMENTO AUTOMATICO LISTINI DI VENDITA PER AZIENDA/ARTICOLO

INSERT INTO U_LIS_AV (LIS_CODSOC,LIS_TIPOAZI,LIS_DESLIS,LIS_CODART,LIS_DESART,LIS_DATLIS,LIS_ALLIST,LIS_PREZZO)

SELECT LIS_CODSOC,LIS_TIPOAZI,LIS_DESLIS,LIS_CODART,LIS_DESART,LIS_DATLIS,LIS_ALLIST,LIS_PREZZO FROM (
	SELECT 
		MAIN.*,
		CASE WHEN COALESCE(U_LIS_AV.LIS_CODART,'') = '' THEN 'NO' ELSE 'SI' END AS PRE_ESISTENTE
	FROM (
		SELECT
			'01' AS LIS_CODSOC,
			RTRIM(SUBSTRING(PARA.CODICE,4,10)) AS LIS_TIPOAZI,
			RTRIM(PARA.DESCRI) AS LIS_DESLIS,
			U_ART_PR.ART_CODPRI AS LIS_CODART,
			U_ART_PR.ART_DESCR AS LIS_DESART,
			'2015/01/01' AS LIS_DATLIS,
			'2999/12/31' AS LIS_ALLIST,
			0 AS LIS_PREZZO
		FROM U_ART_PR
		LEFT OUTER JOIN PARA ON SUBSTRING(PARA.CODICE,1,3) = 'TLV'
		WHERE U_ART_PR.ART_LINEA = 'MP'
		) AS MAIN
	LEFT OUTER JOIN U_LIS_AV ON MAIN.LIS_TIPOAZI = U_LIS_AV.LIS_TIPOAZI AND MAIN.LIS_CODART = U_LIS_AV.LIS_CODART
	) AS T1
WHERE T1.PRE_ESISTENTE = 'NO'
*/