

DELETE FROM PARA WHERE CODICE = 'MATMP'
DELETE FROM PARA WHERE CODICE = 'MATPF'
DELETE FROM PARA WHERE CODICE = 'MATPH'
DELETE FROM PARA WHERE CODICE = 'MATSE'
DELETE FROM PARA WHERE CODICE = 'MATSX'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MATMP','MATERIA PRIMA','0 UM_ACQUISTO:NR;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MATPF','PRODOTTO FINITO','0 UM_ACQUISTO:NR;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MATPH','SEMILAV. FANTASMA','0 UM_ACQUISTO:NR;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MATSE','SEMILAVORATO','0 UM_ACQUISTO:NR;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MATSX','SEMILAVORATO ESTERNO','0 UM_ACQUISTO:NR;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')

--SELECT * FROM PARA WHERE CODICE LIKE 'MAT%' ORDER BY CODICE

UPDATE U_ART_PR SET ART_CODMAT = ART_LINEA, ART_DESMAT = ART_DESLIN

--SELECT ART_CODMAT,ART_DESMAT,* FROM U_ART_PR WHERE ART_CODMAT NOT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'MAT%')

UPDATE U_ART_PR SET ART_CODMAT = '001', ART_DESMAT = 'ACQUISTI GENERICI' WHERE ART_CODMAT NOT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'MAT%')


