
-- ANAGRAFICA ARTICOLI
UPDATE U_ART_PR SET ART_CODPRI = 'SEVEN_R' WHERE ART_CODPRI = 'SEVEN R'
UPDATE U_ART_AN SET ART_CODPRI = 'SEVEN_R' WHERE ART_CODPRI = 'SEVEN R'

UPDATE U_ART_PR SET ART_CODPRI = 'SEVEN_R_SD' WHERE ART_CODPRI = 'SEVEN R SD'
UPDATE U_ART_AN SET ART_CODPRI = 'SEVEN_R_SD' WHERE ART_CODPRI = 'SEVEN R SD'

UPDATE U_ART_PR SET ART_CODPRI = 'SEVEN_SD_EVO' WHERE ART_CODPRI = 'SEVEN R SD EVO'
UPDATE U_ART_AN SET ART_CODPRI = 'SEVEN_SD_EVO' WHERE ART_CODPRI = 'SEVEN R SD EVO'

UPDATE U_ART_PR SET ART_CODPRI = 'SEVEN_TS' WHERE ART_CODPRI = 'SEVEN TS'
UPDATE U_ART_AN SET ART_CODPRI = 'SEVEN_TS' WHERE ART_CODPRI = 'SEVEN TS'

UPDATE U_ART_PR SET ART_CODPRI = 'SEVEN_4_1/2' WHERE ART_CODPRI = 'SEVEN EVO 4 1/2'
UPDATE U_ART_AN SET ART_CODPRI = 'SEVEN_4_1/2' WHERE ART_CODPRI = 'SEVEN EVO 4 1/2'


-- GIACENZE
UPDATE U_MAG_GG SET MAG_ANAART = 'SEVEN_R', MAG_CODART = 'SEVEN_R' WHERE MAG_ANAART = 'SEVEN R'
UPDATE U_MAG_GG SET MAG_ANAART = 'SEVEN_R_SD', MAG_CODART = 'SEVEN_R' WHERE MAG_ANAART = 'SEVEN R SD'
UPDATE U_MAG_GG SET MAG_ANAART = 'SEVEN_SD_EVO', MAG_CODART = 'SEVEN_R' WHERE MAG_ANAART = 'SEVEN R SD EVO'
UPDATE U_MAG_GG SET MAG_ANAART = 'SEVEN_TS', MAG_CODART = 'SEVEN_R' WHERE MAG_ANAART = 'SEVEN TS'
UPDATE U_MAG_GG SET MAG_ANAART = 'SEVEN_4_1/2', MAG_CODART = 'SEVEN_R' WHERE MAG_ANAART = 'SEVEN EVO 4 1/2'


-- MOVIMENTI
UPDATE U_MAG_MO SET MOV_ANAART = 'SEVEN_R', MOV_CODART = 'SEVEN_R' WHERE MOV_ANAART = 'SEVEN R'
UPDATE U_MAG_MO SET MOV_ANAART = 'SEVEN_R_SD', MOV_CODART = 'SEVEN_R_SD' WHERE MOV_ANAART = 'SEVEN R SD'
UPDATE U_MAG_MO SET MOV_ANAART = 'SEVEN_SD_EVO', MOV_CODART = 'SEVEN_SD_EVO' WHERE MOV_ANAART = 'SEVEN R SD EVO'
UPDATE U_MAG_MO SET MOV_ANAART = 'SEVEN_TS', MOV_CODART = 'SEVEN_TS' WHERE MOV_ANAART = 'SEVEN TS'
UPDATE U_MAG_MO SET MOV_ANAART = 'SEVEN_4_1/2', MOV_CODART = 'SEVEN_4_1/2' WHERE MOV_ANAART = 'SEVEN EVO 4 1/2'


-- ORDINI CLIENTI
UPDATE U_ORD_DD SET ORD_CODART = 'SEVEN_R', ORD_CDAPRD = 'SEVEN_R' WHERE ORD_CODART = 'SEVEN R'
UPDATE U_ORD_DD SET ORD_CODART = 'SEVEN_R_SD', ORD_CDAPRD = 'SEVEN_R_SD' WHERE ORD_CODART = 'SEVEN R SD'
UPDATE U_ORD_DD SET ORD_CODART = 'SEVEN_SD_EVO', ORD_CDAPRD = 'SEVEN_SD_EVO' WHERE ORD_CODART = 'SEVEN R SD EVO'
UPDATE U_ORD_DD SET ORD_CODART = 'SEVEN_TS', ORD_CDAPRD = 'SEVEN_TS' WHERE ORD_CODART = 'SEVEN TS'
UPDATE U_ORD_DD SET ORD_CODART = 'SEVEN_4_1/2', ORD_CDAPRD = 'SEVEN_4_1/2' WHERE ORD_CODART = 'SEVEN EVO 4 1/2'
