
-- CODICE FISCALE E PARTITA IVA VUOTI : PRIVATO
UPDATE U_ANA_CL SET CLI_PE_PRI = 1,CLI_PE_PRO = 0,CLI_PE_PA1 = 0,CLI_PE_PA2 = 0,CLI_PE_PA3 = 0  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  = '' AND CLI_PARIVA = '')

-- CODICE FISCALE E PARTITA IVA PIENI : PROFESSIONISTA
UPDATE U_ANA_CL SET CLI_PE_PRI = 0,CLI_PE_PRO = 1,CLI_PE_PA1 = 0,CLI_PE_PA2 = 0,CLI_PE_PA3 = 0  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  <> '' AND CLI_PARIVA <> '')

-- CODICE FISCALE PIENO E PARTITA IVA VUOTA : PRIVATO
UPDATE U_ANA_CL SET CLI_PE_PRI = 1,CLI_PE_PRO = 0,CLI_PE_PA1 = 0,CLI_PE_PA2 = 0,CLI_PE_PA3 = 0  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  <> '' AND CLI_PARIVA = '')

-- CODICE FISCALE VUOTO E PARTITA IVA PIENO : PROFESSIONISTA
UPDATE U_ANA_CL SET CLI_PE_PRI = 0,CLI_PE_PRO = 1,CLI_PE_PA1 = 0,CLI_PE_PA2 = 0,CLI_PE_PA3 = 0  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  = '' AND CLI_PARIVA <> '')


SELECT * FROM U_ANA_CL  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  = '' AND CLI_PARIVA = '')

SELECT * FROM U_ANA_CL  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  <> '' AND CLI_PARIVA <> '')

SELECT * FROM U_ANA_CL  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  <> '' AND CLI_PARIVA = '')

SELECT * FROM U_ANA_CL  WHERE CLI_CODCLI IN (SELECT CLI_CODCLI FROM U_CLI_AN WHERE CLI_CODFIS  = '' AND CLI_PARIVA <> '')
		
	

