
-- VISTA ESTRAZIONE_ANAGRAFICA_CLIENTI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ESTRAZIONE_ANAGRAFICA_CLIENTI]'))
	DROP VIEW [dbo].[ESTRAZIONE_ANAGRAFICA_CLIENTI]
GO
CREATE VIEW [dbo].[ESTRAZIONE_ANAGRAFICA_CLIENTI]  
AS
	SELECT
		AN.CLI_CODCLI AS COD_CLIENTE,
		AN.CLI_RAGSOC AS RAG_SOCIALE,
		AN.CLI_INDIR AS INDIRIZZO,
		AN.CLI_LOCALI AS LOCALITA,
		AN.CLI_PROVIN AS PROVINCIA,
		AN.CLI_CAP AS CAP,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		AN.CLI_NAZION AS COD_NAZIONE,
		COALESCE(PARA_STA.DESCRI,'') AS DES_NAZIONE,
		AN.CLI_CODFIS AS COD_FISCALE,
		AN.CLI_PARIVA AS PARTITA_IVA,
		AN.CLI_IVACEE AS PARTITA_IVA_CEE_EXTRACEE,
		AN.CLI_TELEFO AS TELEFONO,
		AN.CLI_FAX AS FAX,
		AN.CLI_EMAIL AS EMAIL,
		CL.CLI_IDSDI AS COD_DESTINATARIO,
		CL.CLI_EPEC AS PEC_EMAIL
	FROM U_CLI_AN AS AN
	LEFT OUTER JOIN U_ANA_CL AS CL ON CL.CLI_CODCLI = AN.CLI_CODCLI
	LEFT OUTER JOIN PARA AS PA_LNG ON 'LNG'+AN.CLI_LINGUA = PA_LNG.CODICE
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = AN.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+AN.CLI_NAZION

GO
