
-- VISTA GIACENZE_RAGGR_NOB_CON_PRZ_MED_VEND_2017

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GIACENZE_RAGGR_NOB_CON_PRZ_MED_VEND_2017]'))
	DROP VIEW [dbo].[GIACENZE_RAGGR_NOB_CON_PRZ_MED_VEND_2017]
GO

CREATE VIEW [dbo].[GIACENZE_RAGGR_NOB_CON_PRZ_MED_VEND_2017]
AS

	SELECT 
		GG.MAG_CODMAG AS CODMAG,
		GG.MAG_ANAART AS CODART,
		PR.ART_SPESSO AS SP,
		PR.ART_ALTEZZ AS LATO_1,
		PR.ART_LUNGHE AS LATO_2,
		PR.ART_UMMAGA AS UM,
		SUM(GG.MAG_GIACEN) AS GIACEN,
		COALESCE(DD.PRZ_MEDIO_VENDITA,0) AS PRZ_MEDIO_VENDITA_2017
	FROM U_MAG_GG AS GG
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = GG.MAG_ANAART
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = GG.MAG_ANAART
	OUTER APPLY (SELECT ORD_CODART, SUM(ORD_PRZNET) / COUNT(*) AS PRZ_MEDIO_VENDITA FROM U_FAT_DD 
		WHERE ORD_DESART <> '*** COMMENTO ***' AND SUBSTRING(ORS_DATORD,1,4) = '2017' AND ORD_CODART = GG.MAG_ANAART
		GROUP BY ORD_CODART) AS DD
	WHERE
		MAG_CODMAG <> 'SCA' AND PR.ART_CODMAT = '008' AND AN.ART_TIPON <> ''
	GROUP BY GG.MAG_CODMAG,GG.MAG_ANAART,PR.ART_UMMAGA,PR.ART_SPESSO,PR.ART_ALTEZZ,PR.ART_LUNGHE,DD.PRZ_MEDIO_VENDITA


