-- VISTA ECONOMICI_PER_CENTRO_COSTO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ECONOMICI_PER_CENTRO_COSTO]'))
	DROP VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO]
GO

CREATE VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO]  
AS

SELECT 
	ECO.MOV_ANNO AS ANNO,
	ECO.MOV_CONTO AS CONTO,
	CONECO.CON_DESCR AS DESCR_CONTO,
	ECO.MOV_CCO AS CENTRO_COSTO,
	COALESCE(CCO.CON_DESCR,'') AS DESCR_CDC,
	SUM(CASE WHEN MOV_TMOV='D' THEN ECO.MOV_IMP ELSE 0 END) AS DARE,
	SUM(CASE WHEN MOV_TMOV='A' THEN ECO.MOV_IMP ELSE 0 END) AS AVERE,
	SUM(CASE WHEN MOV_TMOV='D' THEN ECO.MOV_IMP ELSE -1 * ECO.MOV_IMP END) AS SALDO
FROM CONTI AS CONECO
LEFT OUTER JOIN MOV_CONT AS ECO ON ECO.MOV_CONTO=CONECO.CON_CONTO AND ECO.MOV_ANNO=CONECO.CON_ANNO
LEFT OUTER JOIN CCOSTO AS CCO ON ECO.MOV_CCO=CCO.CON_CONTO AND ECO.MOV_ANNO=CCO.CON_ANNO
WHERE CONECO.CON_POSBIL = 'E'
GROUP BY ECO.MOV_ANNO,ECO.MOV_CONTO,CONECO.CON_DESCR,ECO.MOV_CCO,CCO.CON_DESCR


GO