
-- VISTA ARTICOLI PANNELLI NOBILITATI SENZA DI.BA.

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PANNELLI_NOB_NO_DIBA]'))
	DROP VIEW [dbo].PANNELLI_NOB_NO_DIBA
GO

CREATE VIEW [dbo].PANNELLI_NOB_NO_DIBA
AS
	SELECT 
		PR.ART_DATVAR AS DATA_CREAZIONE, 
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		PR.ART_UMMAGA AS UM,
		PR.ART_ALTEZZ AS LATO1,
		PR.ART_LUNGHE AS LATO2
	FROM U_ART_PR AS PR 
	LEFT OUTER JOIN U_ART_AN AS AN
	ON AN.ART_CODPRI = PR.ART_CODPRI
	WHERE PR.ART_CODMAT = '008' 
		AND PR.ART_OBSOL <> 'S' 
		AND AN.ART_TIPOG = '' 
		AND AN.ART_TIPON <> '' 
		AND LEN(LTRIM(RTRIM(PR.ART_CODPRI))) = 16
		AND SUBSTRING(PR.ART_CODPRI,1,1) <> '0#' 
		AND SUBSTRING(PR.ART_CODPRI,1,1) <> '0*' 
		AND SUBSTRING(PR.ART_CODPRI,1,2) <> 'LM' 
		AND PR.ART_CODPRI NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT) 
		AND SUBSTRING(PR.ART_CODPRI,9,3) <> '000' 
		AND SUBSTRING(PR.ART_CODPRI,12,3) <> '000' 
GO

SELECT * FROM PANNELLI_NOB_NO_DIBA ORDER BY DATA_CREAZIONE,COD_ARTICOLO