/*
select * from para where codice like 'CPA%' order by codice

select len(libera) AS LUNG FROM PARA where codice like 'CPA%' order by LUNG DESC
*/


-- VISTA CPA_DUPLICATE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CPA_DUPLICATE]'))
	DROP VIEW [dbo].[CPA_DUPLICATE]
GO

CREATE VIEW [dbo].[CPA_DUPLICATE] 
AS
SELECT 
	CAST(MAIN.SCAFISS AS VARCHAR(3))+
	CAST(MAIN.PERIMPO AS VARCHAR(6))+
	CAST(MAIN.SCAFISS_1R AS VARCHAR(3))+
	MAIN.SOLOIMPIVA+
	SUBSTRING(MAIN.LIBERA,1,50) AS CHIAVE,
	COUNT(*) AS NR_CODICI_CON_STESSA_CHIAVE,
	P2.CODICE,RTRIM(P2.DESCRI) AS DESCRI
FROM PARA  AS MAIN
LEFT OUTER JOIN PARA AS P2 ON  P2.codice like 'CPA%' AND P2.LIBERA = MAIN.LIBERA AND P2.SCAFISS = MAIN.SCAFISS
					 AND P2.PERIMPO = MAIN.PERIMPO AND P2.SCAFISS_1R = MAIN.SCAFISS_1R AND P2.SOLOIMPIVA = MAIN.SOLOIMPIVA
where MAIN.codice like 'CPA%' 
GROUP BY MAIN.LIBERA,MAIN.SCAFISS,MAIN.PERIMPO,MAIN.SCAFISS_1R,MAIN.SOLOIMPIVA,P2.CODICE,P2.DESCRI
