
-- VISTA WEEKLY_REPORT

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[WEEKLY_REPORT]'))
	DROP VIEW [dbo].[WEEKLY_REPORT]
GO

CREATE VIEW [dbo].[WEEKLY_REPORT] 
AS

SELECT
	ANNO,
	SETTIMANA,
	'Ordini Acquisiti' AS TIPO_RECORD,
	TIPO_GN,
	TIPOLOGIA,
	SUM(ORD_QTAMC) AS QTAMC,
	SUM(ORD_QTAMQ) AS QTAMQ,
	SUM(ORD_VALORE) AS VALORE
FROM (
	SELECT ORD_CODART,
		SUBSTRING(DD.ORS_DATORD,1,4) AS ANNO,
		RIGHT('0'+CAST(DATEPART(week,CAST(DD.ORS_DATORD AS datetimeoffset)) AS VARCHAR(2)),2) AS SETTIMANA,
		DD.ORD_QTAMC,
		DD.ORD_QTAMQ,
		DD.ORD_VALORE,
		CASE AN.ART_TIPON WHEN '' THEN 'GREZZO' ELSE 'NOBILITATO' END AS TIPO_GN,
		CASE
			WHEN PR.ART_DESCR LIKE '%PIOPPO%' THEN 'PIOPPO' 
			WHEN PR.ART_DESCR LIKE '%STANDARD%' THEN 'STANDARD'
			WHEN PR.ART_DESCR LIKE '%STD%' THEN 'STANDARD'
			ELSE 'N/A'
		END AS TIPOLOGIA
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = DD.ORD_CODART
	WHERE PR.ART_CODMAT = '008' AND ORD_CODART <> '' AND ORD_DESART <> '*** COMMENTO ***' AND ORS_CODCLI <> '00000010'  --AND ORS_DATORD >= '2024/01/01'
	) AS MAIN
GROUP BY ANNO,SETTIMANA,TIPO_GN,TIPOLOGIA
UNION
SELECT
	ANNO,
	SETTIMANA,
	'Materiale Spedito' AS TIPO_RECORD,
	TIPO_GN,
	TIPOLOGIA,
	SUM(ORD_QTAMC) AS QTAMC,
	SUM(ORD_QTAMQ) AS QTAMQ,
	SUM(ORD_VALORE) AS VALORE
FROM (
	SELECT ORD_CODART,
		SUBSTRING(DD.ORS_DATORD,1,4) AS ANNO,
		RIGHT('0'+CAST(DATEPART(week,CAST(DD.ORS_DATORD AS datetimeoffset)) AS VARCHAR(2)),2) AS SETTIMANA,
		DD.ORD_QTAMC,
		DD.ORD_QTAMQ,
		DD.ORD_VALORE,
		CASE AN.ART_TIPON WHEN '' THEN 'GREZZO' ELSE 'NOBILITATO' END AS TIPO_GN,
		CASE
			WHEN PR.ART_DESCR LIKE '%PIOPPO%' THEN 'PIOPPO' 
			WHEN PR.ART_DESCR LIKE '%STANDARD%' THEN 'STANDARD'
			WHEN PR.ART_DESCR LIKE '%STD%' THEN 'STANDARD'
			ELSE 'N/A'
		END AS TIPOLOGIA
	FROM U_BOL_DD AS DD
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = DD.ORD_CODART
	WHERE PR.ART_CODMAT = '008' AND ORD_CODART <> '' AND ORD_DESART <> '*** COMMENTO ***' AND ORS_CODCLI <> '00000010'  --AND ORS_DATORD >= '2024/01/01'
	) AS MAIN
GROUP BY ANNO,SETTIMANA,TIPO_GN,TIPOLOGIA
UNION
SELECT
	ANNO,
	SETTIMANA,
	'Materiale Prodotto' AS TIPO_RECORD,
	TIPO_GN,
	TIPOLOGIA,
	SUM(QTAMCPROD) AS QTAMC,
	SUM(QTAMQPROD) AS QTAMQ,
	SUM(ORD_VALORE) AS VALORE
FROM (
	SELECT CODART,
		SUBSTRING(DD.DATAVA,1,4) AS ANNO,
		RIGHT('0'+CAST(DATEPART(week,CAST(DD.DATAVA AS datetimeoffset)) AS VARCHAR(2)),2) AS SETTIMANA,
		DD.QTAMCPROD,
		DD.QTAMQPROD,
		CASE PR.ART_UMMAGA
			WHEN 'MQ' THEN DD.QTAMQPROD
			WHEN 'MC' THEN DD.QTAMCPROD
			ELSE DD.QTAPROD
		END * COALESCE((SELECT TOP 1 ORD_PREZZO FROM U_FAT_DD WHERE ORD_CODART = DD.CODART ORDER BY ORS_DATORD),0) AS ORD_VALORE,
		CASE FASELA WHEN 'PRESSA' THEN 'GREZZO DA LEVIGARE (PRESSA)' ELSE
			CASE AN.ART_TIPON WHEN '' THEN 'GREZZO' ELSE 'NOBILITATO' END 
		END AS TIPO_GN,
		CASE
			WHEN PR.ART_DESCR LIKE '%PIOPPO%' THEN 'PIOPPO' 
			WHEN PR.ART_DESCR LIKE '%STANDARD%' THEN 'STANDARD'
			WHEN PR.ART_DESCR LIKE '%STD%' THEN 'STANDARD'
			ELSE 'N/A'
		END AS TIPOLOGIA
	FROM PROD_CARICHI AS DD
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.CODART
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = DD.CODART
	WHERE PR.ART_CODMAT = '008' AND FASELA IN ('LEVIGA','NOBILI','PRESSA') --AND DATAVA >= '2024/01/01'
	) AS MAIN
GROUP BY ANNO,SETTIMANA,TIPO_GN,TIPOLOGIA

GO

SELECT * FROM WEEKLY_REPORT WHERE ANNO = '2024' ORDER BY ANNO,SETTIMANA,TIPO_RECORD,TIPO_GN,TIPOLOGIA
