
-- VISTA CONFR_SALDI_CONT_PART_FOR

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CONFR_SALDI_CONT_PART_FOR]'))
	DROP VIEW [dbo].[CONFR_SALDI_CONT_PART_FOR]
GO

CREATE VIEW [dbo].[CONFR_SALDI_CONT_PART_FOR]  
AS

SELECT
	CON_CONTO AS CONTO_FORNITORE,
	CON_DESCR AS DESCRIZIONE,
	SALDO_CONTABILE,
	COALESCE(SALDO_PARTITE,0) AS SALDO_PARTITE,
	CASE
		WHEN COALESCE(SALDO_CONTABILE,0) = COALESCE(SALDO_PARTITE,0) THEN 'OK'
		ELSE 'KO'
	END AS CONFR_OK_KO
FROM (
	SELECT 
		CON_CONTO,
		SUBSTRING(CON_DESCR,1,30) AS CON_DESCR,
		COALESCE(SUM(CASE 
			WHEN MOV_TMOV='D' THEN MOV_IMP 
			ELSE  -1*MOV_IMP 
		END  ),0) AS SALDO_CONTABILE
	FROM CONTI 
	LEFT OUTER JOIN MOV_CONT AS MOV ON CON_CONTO=MOV.MOV_CONTO
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE='TOP'+MOV.MOV_TOP
	WHERE
		CON_TIPOCO='F' AND 
		CON_ANNO=CAST(YEAR(GETDATE()) AS NVARCHAR(4))
	GROUP BY CON_CONTO,SUBSTRING(CON_DESCR,1,30)
	) AS T1
LEFT OUTER JOIN (
	SELECT 
		PAR_CODCLI,
		SUM(CASE 
			WHEN PAR_TMOV='D' THEN PAR_FATT 
			ELSE  -1*PAR_FATT 
		END  ) AS SALDO_PARTITE
	FROM  PART_FOR 
	WHERE PAR_NPROG<>100
	GROUP BY PAR_CODCLI
	) AS T2 ON T1.CON_CONTO = T2.PAR_CODCLI

GO

--SELECT * FROM CONFR_SALDI_CONT_PART_FOR 
--WHERE SALDO_PARTITE <> SALDO_CONTABILE
--ORDER BY CONTO_FORNITORE
