
/****** Object:  View [dbo].[FATTURATO_XILOPAN]    Script Date: 24/01/2022 09:20:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_XILOPAN]'))
	DROP VIEW [dbo].[FATTURATO_XILOPAN]
GO
CREATE VIEW [dbo].[FATTURATO_XILOPAN]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		CAST(DATEPART(ISO_WEEK, CAST(DBO.RIBALTA2(TT.ORD_DATORD) AS DATETIME)) AS VARCHAR(2)) AS SETTIMANA,
		COALESCE(CAU.DESCRI,'') AS CAUSALE,
		TT.ORD_NUMORD AS NUM_FATTURA,
		TT.ORD_DATORD AS DATA_FATTURA,
		DD.ORS_NUMDDT AS NUM_DDT,
		DD.ORS_DATDDT AS DATA_DDT,
		TT.ORD_CODCLI AS CODICE_CLIENTE,
		CLI.CLI_RAGSOC AS RAGIONE_SOCIALE,	
		DD.ORD_CODART AS ARTICOLO,
		DD.ORD_DESART AS DES_ARTICOLO,
		DD.ORD_CDAPRD AS ARTICOLO_CLIENTE,
		DD.ORD_DSAPRD AS DES_ARTICOLO_CLIENTE,
		CASE SUBSTRING(COALESCE(CAU.LIBERA,''),11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_PREZZO AS PREZZO_LORDO,
		DD.ORD_SC1 AS SCONTO_1,
		DD.ORD_SC2 AS SCONTO_2,
		DD.ORD_SC3 AS SCONTO_3,
		DD.ORD_SC4 AS SCONTO_4,
		DD.ORD_SC5 AS SCONTO_5,
		CASE SUBSTRING(COALESCE(CAU.LIBERA,''),11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_PRZNET AS PREZZO_NETTO,
		DD.ORD_UM AS UM,
		DD.ORD_QTAORD AS QTA,
		CASE SUBSTRING(COALESCE(CAU.LIBERA,''),11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_VALORE AS VALORE,
		TT.ORD_VALUTA AS VALUTA,
		DD.ORD_NUMBOB AS NR_FOGLI,
		DD.ORD_QTAMC AS QTA_MC,
		DD.ORD_QTAMQ AS QTA_MQ,
		DD.ORD_SPESSO AS SP,
		DD.ORD_ALTEZZ AS LATO_1,
		DD.ORD_LUNGHE AS LATO_2,
		COALESCE(POR.DESCRI,'') AS PORTO,
		CASE COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')
			WHEN '6' THEN
				CASE AN.ART_TIPON WHEN '' THEN
					CASE AN.ART_TIPOG WHEN '' THEN '' ELSE 'GREZZO' END
				ELSE
					'NOBILITATO'
				END
			ELSE ''
		END AS TIPO_PANNELLO,
		TT.ORD_CODNAZ AS COD_NAZIONE,
		COALESCE(STA.DESCRI,'') AS DESCR_NAZIONE,
		TT.ORD_AGE AS COD_AGENTE,
		COALESCE(AGE.DESCRI,'') AS DESCR_AGENTE,
		COALESCE(TOP_BOL.DESCRI,'') AS CAUSALE_DDT,
		COALESCE(TOP_ORD.DESCRI,'') AS CAUSALE_ORD
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_CLI_AN AS CLI ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS CAU ON CAU.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS POR ON POR.CODICE = 'POR'+TT.ORD_PORTO
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = DD.ORD_CODART
	LEFT OUTER JOIN PARA AS MAT ON MAT.CODICE = 'MAT'+PR.ART_CODMAT
	LEFT OUTER JOIN PARA AS STA ON STA.CODICE = 'STA'+TT.ORD_CODNAZ
	LEFT OUTER JOIN PARA AS AGE ON AGE.CODICE = 'AGE'+TT.ORD_AGE
	LEFT OUTER JOIN U_BOL_TT AS BOL ON DD.ORS_NUMDDT = BOL.ORD_NUMORD AND DD.ORS_DATDDT = BOL.ORD_DATORD AND DD.ORS_NUMDDT <> '' AND DD.ORS_DATDDT <> ''
	LEFT OUTER JOIN PARA AS TOP_BOL ON TOP_BOL.CODICE = 'TOP'+BOL.ORD_CAUS
	LEFT OUTER JOIN U_ORD_TT AS ORD ON DD.ORS_NUMORC = ORD.ORD_NUMORD AND DD.ORS_DATORC = ORD.ORD_DATORD AND DD.ORS_NUMORC <> '' AND DD.ORS_DATORC <> ''
	LEFT OUTER JOIN PARA AS TOP_ORD ON TOP_ORD.CODICE = 'TOP'+ORD.ORD_CAUS
	WHERE DD.ORD_CODART <> ''

GO

--SELECT * FROM FATTURATO_XILOPAN WHERE ANNO = 2021