
-- VISTA STATISTICA FATTURATO PER AGENTE/ANNO/CLIENTE ULTIMI 5 ANNI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[STAT_FATTURATO_AGE_ANNO_CLI]'))
	DROP VIEW [dbo].STAT_FATTURATO_AGE_ANNO_CLI
GO

CREATE VIEW [dbo].STAT_FATTURATO_AGE_ANNO_CLI
AS
	SELECT
		STC.STC_CODAGE AS CODAGE,
		STC.STC_DESAGE AS DESAGE,
		STC.STC_CODCLI AS CODCLI,
		STC.STC_DESCLI AS RAGSOC,
		CLI.CLI_NAZION AS NAZIONE,
		CLI.CLI_PROVIN AS PROV,
		SUM(CASE SUBSTRING(STC.STC_DTDOC,1,4) WHEN SUBSTRING(convert(varchar, DATEADD(YEAR, -5, GETDATE()), 111),1,4) THEN STC.STC_VALORE ELSE 0 END) AS FATTURATO_5_ANNI_FA,
		SUM(CASE SUBSTRING(STC.STC_DTDOC,1,4) WHEN SUBSTRING(convert(varchar, DATEADD(YEAR, -4, GETDATE()), 111),1,4) THEN STC.STC_VALORE ELSE 0 END) AS FATTURATO_4_ANNI_FA,
		SUM(CASE SUBSTRING(STC.STC_DTDOC,1,4) WHEN SUBSTRING(convert(varchar, DATEADD(YEAR, -3, GETDATE()), 111),1,4) THEN STC.STC_VALORE ELSE 0 END) AS FATTURATO_3_ANNI_FA,
		SUM(CASE SUBSTRING(STC.STC_DTDOC,1,4) WHEN SUBSTRING(convert(varchar, DATEADD(YEAR, -2, GETDATE()), 111),1,4) THEN STC.STC_VALORE ELSE 0 END) AS FATTURATO_2_ANNI_FA,
		SUM(CASE SUBSTRING(STC.STC_DTDOC,1,4) WHEN SUBSTRING(convert(varchar, DATEADD(YEAR, -1, GETDATE()), 111),1,4) THEN STC.STC_VALORE ELSE 0 END) AS FATTURATO_1_ANNO_FA
	FROM U_STC_AN AS STC
	LEFT OUTER JOIN U_CLI_AN AS CLI ON CLI.CLI_CODCLI = STC.STC_CODCLI 
	GROUP BY STC.STC_CODAGE,STC.STC_DESAGE,STC.STC_CODCLI,STC.STC_DESCLI,CLI.CLI_NAZION,CLI.CLI_PROVIN
GO

SELECT * FROM STAT_FATTURATO_AGE_ANNO_CLI ORDER BY CODAGE,RAGSOC
