
-- VISTA DDT_CLIENTI_NOBILITATO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DDT_CLIENTI_NOBILITATO]'))
	DROP VIEW [dbo].[DDT_CLIENTI_NOBILITATO]
GO

CREATE VIEW [dbo].[DDT_CLIENTI_NOBILITATO]  
AS

SELECT 
	TT.ORD_NUMORD AS NUM_DDT,
	TT.ORD_DATORD AS DATA_DDT,
	DD.ORD_CODART AS COD_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE,
	DD.ORD_SPESSO AS SPESSORE,
	DD.ORD_ALTEZZ AS LATO_1,
	DD.ORD_LUNGHE AS LATO_2,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA,
	DD.ORD_NUMBOB AS NUM_PEZZI,
	DD.ORD_QTAMC AS QTA_MC
FROM U_BOL_TT AS TT
LEFT OUTER JOIN U_BOL_DD AS DD ON TT.TAGGANCIO = DD.DAGGANCIO
LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = DD.ORD_CODART
WHERE 
	DD.ORD_CODART <> '' AND 
	DD.ORD_DESART <> '*** COMMENTO ***' AND 
	PR.ART_CODMAT = '008' AND 
	AN.ART_TIPON <> ''

--ORDER BY ORD_DATORD,ORD_NUMORD