
-- VISTA FATTURE_FORNITORI_DA_PARTITARIO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_FORNITORI_DA_PARTITARIO]'))
	DROP VIEW [dbo].[FATTURE_FORNITORI_DA_PARTITARIO]
GO

CREATE VIEW [dbo].[FATTURE_FORNITORI_DA_PARTITARIO]  
AS

SELECT
	PAR_ANNO AS ANNO,
	PAR_CODCLI AS FORNITORE,
	PAR_RAGSOC AS RAG_SOCIALE,
	PAR_NUMFAT AS NR_FATTURA,
	PAR_DTFAT AS DATA_FATTURA,
	PAR_NPART AS NR_PARTITA,
	SUM(CASE PAR_TMOV WHEN 'D' THEN (-1)*PAR_FATT ELSE (CASE PAR_TMOV WHEN 'A' THEN PAR_FATT ELSE 0 END) END) AS TOT_IMPORTO
FROM (
	SELECT
		PAR_ANNO,
		PAR_CODCLI,
		PAR_RAGSOC,
		PAR_NUMFAT,
		PAR_DTFAT,
		PAR_NPART,
		PAR_TMOV,
		PAR_FATT
	FROM PART_FOR
	LEFT OUTER JOIN PARA ON PARA.CODICE = 'TOP'+PART_FOR.PAR_TIPFAT
	WHERE
		PAR_NPROG <> 100 AND 
		SUBSTRING(PARA.LIBERA,2,1) = 'S'
	) AS MAIN
GROUP BY PAR_ANNO,PAR_CODCLI,PAR_RAGSOC,PAR_NUMFAT,PAR_DTFAT,PAR_NPART

