
-- VISTA LIBRO_GIORNALE_MAG_2015

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LIBRO_GIORNALE_MAG_2015]'))
	DROP VIEW [dbo].[LIBRO_GIORNALE_MAG_2015]
GO

CREATE VIEW [dbo].[LIBRO_GIORNALE_MAG_2015]  
AS

	SELECT * FROM (
		SELECT 
			MO.MOV_CODMAG AS COD_MAG,
			COALESCE(PARA_MAG.DESCRI,'') AS DESCR_MAG,
			MO.MOV_ANAART AS ARTICOLO,
			PR.ART_DESCR AS DESCRIZIONE,
			'' AS TIPO_OP,
			'SALDO INIZIALE' AS DESCR_OP,
			'' AS SEGNO,
			PR.ART_UMMAGA AS UM,
			SUM(CASE WHEN MO.MOV_SEGNO = '+' THEN MO.MOV_QTAMOV ELSE -1*MO.MOV_QTAMOV END) AS QTA,
			'31/12/2014' AS DATA_OP,
			'2014/12/31' AS DATA_OP_AMG
		FROM 
			U_MAG_MO AS MO
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MO.MOV_ANAART
			LEFT OUTER JOIN PARA AS PARA_MAG ON PARA_MAG.CODICE = 'MAG'+MO.MOV_CODMAG
		WHERE 
			MO.MOV_CODMAG IN ('3','LEGNAM','SEDE','SCA','RIC','OFF') AND 
			MO.MOV_DTREGI <= '2014/12/31' AND 
			PR.ART_NONMOV = ''
		GROUP BY MO.MOV_CODMAG,COALESCE(PARA_MAG.DESCRI,''),MO.MOV_ANAART,PR.ART_DESCR,PR.ART_UMMAGA

		UNION

		SELECT 
			MO.MOV_CODMAG AS COD_MAG,
			COALESCE(PARA_MAG.DESCRI,'') AS DESCR_MAG,
			MO.MOV_ANAART AS ARTICOLO,
			PR.ART_DESCR AS DESCRIZIONE,
			MO.MOV_TOP AS TIPO_OP,
			COALESCE(PARA_TOP.DESCRI,'') AS DESCR_OP,
			MO.MOV_SEGNO AS SEGNO,
			PR.ART_UMMAGA AS UM,
			MO.MOV_QTAMOV AS QTA,
			DBO.RIBALTA2(MO.MOV_DTREGI) AS DATA_OP,
			MO.MOV_DTREGI AS DATA_OP_AMG
		FROM 
			U_MAG_MO AS MO
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MO.MOV_ANAART
			LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+MO.MOV_TOP
			LEFT OUTER JOIN PARA AS PARA_MAG ON PARA_MAG.CODICE = 'MAG'+MO.MOV_CODMAG
		WHERE 
			MO.MOV_CODMAG IN ('3','LEGNAM','SEDE','SCA','RIC','OFF') AND 
			SUBSTRING(MO.MOV_DTREGI,1,4) = '2015' AND 
			PR.ART_NONMOV = ''

		UNION

		SELECT 
			MO.MOV_CODMAG AS COD_MAG,
			COALESCE(PARA_MAG.DESCRI,'') AS DESCR_MAG,
			MO.MOV_ANAART AS ARTICOLO,
			PR.ART_DESCR AS DESCRIZIONE,
			'ZZZ' AS TIPO_OP,
			'SALDO FINALE' AS DESCR_OP,
			'' AS SEGNO,
			PR.ART_UMMAGA AS UM,
			SUM(CASE WHEN MO.MOV_SEGNO = '+' THEN MO.MOV_QTAMOV ELSE -1*MO.MOV_QTAMOV END) AS QTA,
			'31/12/2015' AS DATA_OP_AMG,
			'2015/12/31' AS DATA_OP_AMG
		FROM 
			U_MAG_MO AS MO
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MO.MOV_ANAART
			LEFT OUTER JOIN PARA AS PARA_MAG ON PARA_MAG.CODICE = 'MAG'+MO.MOV_CODMAG
		WHERE 
			MO.MOV_CODMAG IN ('3','LEGNAM','SEDE','SCA','RIC','OFF') AND 
			MO.MOV_DTREGI <= '2015/12/31' AND 
			PR.ART_NONMOV = ''
		GROUP BY MO.MOV_CODMAG,COALESCE(PARA_MAG.DESCRI,''),MO.MOV_ANAART,PR.ART_DESCR,PR.ART_UMMAGA

		) AS MAIN

	--ORDER BY
	--	COD_MAG,
	--	ARTICOLO,
	--	DATA_OP_AMG,
	--	TIPO_OP