-- VISTA ELENCO_PANNELLI_INVENTARIO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_PANNELLI_INVENTARIO]'))
	DROP VIEW [dbo].[ELENCO_PANNELLI_INVENTARIO]
GO

CREATE VIEW [dbo].[ELENCO_PANNELLI_INVENTARIO]  
AS

SELECT DISTINCT
	MOV_CODMAG AS MAGAZZINO,
	MOV_ANAART AS ARTICOLO,
	ART_DESCR AS DESCRIZIONE,
	CASE COALESCE(PARA_GRUPPO.CODICE,'') WHEN '' THEN 'NO' ELSE 'SI' END AS GREZZO_DA_LEVIGARE,
	COALESCE(PARA_TIG.DESCRI,'') AS TIPO_GREZZO,
	COALESCE(PARA_TNO.DESCRI,'') AS TIPO_NOBILITATO,
	COALESCE(PARA_FIN.DESCRI,'') AS FINITURA,
	COALESCE(PARA_COLF.DESCRI,'') AS COLORE_FRONTE,
	COALESCE(PARA_COLR.DESCRI,'') AS COLORE_RETRO,
	MOV_SPESSO AS SPESSORE,
	MOV_ALTEZZ AS LATO_1,
	MOV_LUNGHE AS LATO_2,
	0 AS NR_PANNELLI_RILEVATI,
	0.00 AS GIACENZA_RILEVATA
FROM U_MAG_MO
LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MOV_ANAART
LEFT OUTER JOIN U_ART_AN AS AN ON PR.ART_CODPRI = AN.ART_CODPRI
LEFT OUTER JOIN PARA AS PARA_TIG ON PARA_TIG.CODICE = 'TIG'+AN.ART_TIPOG
LEFT OUTER JOIN PARA AS PARA_TNO ON PARA_TNO.CODICE = 'TNO'+AN.ART_TIPON
LEFT OUTER JOIN PARA AS PARA_FIN ON PARA_FIN.CODICE = 'FIN'+AN.ART_FINI
LEFT OUTER JOIN PARA AS PARA_COLF ON PARA_COLF.CODICE = 'COL'+PR.ART_CODCOL
LEFT OUTER JOIN PARA AS PARA_COLR ON PARA_COLR.CODICE = 'COL'+AN.ART_CODCOLRET
LEFT OUTER JOIN PARA AS PARA_GRUPPO ON 'PRD'+MOV_ANAART = PARA_GRUPPO.CODICE
WHERE
	MOV_CODMAG = 'SEDE' AND 
	PR.ART_CODMAT = '008' AND
	MOV_DTREGI <= convert(varchar, GETDATE(), 111) AND MOV_DTREGI >= convert(varchar, DATEADD(day, -365, GETDATE()), 111)
--ORDER BY GREZZO_DA_LEVIGARE,TIPO_NOBILITATO,TIPO_GREZZO,ARTICOLO
