
-- VISTA ORDINI CLIENTI PER ANNO/TIPO PANNELLO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDCLI_ANNO_TIPO]'))
	DROP VIEW [dbo].ORDCLI_ANNO_TIPO
GO

CREATE VIEW [dbo].ORDCLI_ANNO_TIPO
AS
	SELECT 
		MAIN.ANNO,
		MAIN.TIPO,
		COALESCE(P_TIG.DESCRI,'') AS DESCRIZIONE,
		SUM(QTA_MC) AS QTA_MC,
		SUM(VALORE) AS VALORE
	FROM (
		SELECT 
			SUBSTRING(ORS_DATORD,1,4) AS ANNO,
			SUBSTRING(ORD_CODART,1,2) AS TIPO,
			ORD_QTAMC AS QTA_MC,
			ORD_VALORE AS VALORE
		FROM U_ORD_DD
		WHERE ORD_DESART <> '*** COMMENTO ***' AND ORD_CODART <> '' AND 
			ORD_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI)
		) AS MAIN
	LEFT OUTER JOIN PARA AS P_TIG ON P_TIG.CODICE = 'TIG'+MAIN.TIPO
	GROUP BY MAIN.ANNO, MAIN.TIPO, COALESCE(P_TIG.DESCRI,'')
GO

SELECT * FROM ORDCLI_ANNO_TIPO ORDER BY ANNO, TIPO
