
/****** Object:  View [dbo].[FORNITORI_ATTIVI_PER_ANNO] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FORNITORI_ATTIVI_PER_ANNO]'))
	DROP VIEW [dbo].[FORNITORI_ATTIVI_PER_ANNO]
GO
--CREATE VIEW [dbo].[FORNITORI_ATTIVI_PER_ANNO]  
--AS
--	SELECT * FROM (
--		SELECT
--			COALESCE((SELECT TOP 1 SUBSTRING(MOV_DTREG,1,4) FROM MOV_CONT WHERE 
--				MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = MOV_ANNO AND CON_CONTO = MOV_CONTO AND CON_TIPOCO = 'F')
--				AND MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
--				AND	SUBSTRING(MOV_CONTO,6,10) = AN.FOR_CODCLI ORDER BY MOV_DTREG DESC),'') AS ANNO_ULT_ATTIVITA,
--			AN.FOR_CODCLI AS COD_FORNITORE,
--			AN.FOR_RAGSOC AS RAG_SOCIALE,
--			AN.FOR_CONPAG AS COD_CPA,
--			COALESCE(CPA.DESCRI,'') AS DESCR_CPA,
--			COALESCE((SELECT SUM((CASE MOV_TMOV WHEN 'A' THEN 1 ELSE -1 END) * MOV_IMP) FROM MOV_CONT WHERE 
--				MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = MOV_ANNO AND CON_CONTO = MOV_CONTO AND CON_TIPOCO = 'F')
--				AND MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
--				AND	SUBSTRING(MOV_CONTO,6,10) = AN.FOR_CODCLI),'') AS TOTALE_FATTURATO
--		FROM U_FOR_AN AS AN
--		LEFT OUTER JOIN PARA AS CPA ON CPA.CODICE = 'CPA'+AN.FOR_CONPAG
		
--	) AS MAIN WHERE ANNO_ULT_ATTIVITA <> ''

CREATE VIEW [dbo].[FORNITORI_ATTIVI_PER_ANNO]  
AS
	SELECT
		SUBSTRING(MOV_DTREG,1,4) AS ANNO, 
		AN.FOR_CODCLI AS COD_FORNITORE,
		AN.FOR_RAGSOC AS RAG_SOCIALE,
		AN.FOR_CONPAG AS COD_CPA,
		COALESCE(CPA.DESCRI,'') AS DESCR_CPA,
		SUM((CASE MOV_TMOV WHEN 'A' THEN 1 ELSE -1 END) * MOV_IMP) AS TOTALE_FATTURATO_ANNO 
	FROM MOV_CONT
	LEFT OUTER JOIN U_FOR_AN AS AN ON AN.FOR_CODCLI = SUBSTRING(MOV_CONT.MOV_CONTO,6,10)
	LEFT OUTER JOIN PARA AS CPA ON CPA.CODICE = 'CPA'+AN.FOR_CONPAG
	WHERE MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = MOV_ANNO AND CON_CONTO = MOV_CONTO AND CON_TIPOCO = 'F')
	AND MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	GROUP BY SUBSTRING(MOV_DTREG,1,4),MOV_CONTO,AN.FOR_CODCLI,AN.FOR_RAGSOC,AN.FOR_CONPAG,CPA.DESCRI

GO

--SELECT * FROM FORNITORI_ATTIVI_PER_ANNO WHERE ANNO_ULT_ATTIVITA = 2022