
-- VISTA GIACENZE_PANNELLI_GREZZI_DA_LEVIGARE_RAGGR

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GIAC_PANN_GR_DA_LEVIGARE_RAGGR]'))
	DROP VIEW [dbo].[GIAC_PANN_GR_DA_LEVIGARE_RAGGR]
GO

CREATE VIEW [dbo].[GIAC_PANN_GR_DA_LEVIGARE_RAGGR]
AS

	SELECT
		MAG_CODMAG AS MAGAZZINO,
		MAG_ANAART AS COD_GRUPPO_PROD,
		ART_DESCR AS DESCRIZIONE,
		ART_UMMAGA AS UM,
		SUM(MAG_GIACEN) AS GIACENZA
	FROM (
		SELECT MAG_CODMAG,MAG_ANAART,ART_DESCR,ART_UMMAGA,MAG_GIACEN
		FROM U_MAG_GG, U_ART_PR WHERE
		U_MAG_GG.MAG_ANAART = U_ART_PR.ART_CODPRI
		AND MAG_ANAART IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRD%')
		) AS MAIN
	GROUP BY MAG_CODMAG,MAG_ANAART,ART_DESCR,ART_UMMAGA


--SELECT * FROM GIAC_PANN_GR_DA_LEVIGARE_RAGGR ORDER BY MAGAZZINO,COD_GRUPPO_PROD