-- VISTA SALDI PER ANNO COMPETENZA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SALDI_PER_MESE_COMPETENZA]'))
	DROP VIEW [dbo].SALDI_PER_MESE_COMPETENZA
GO

CREATE VIEW [dbo].SALDI_PER_MESE_COMPETENZA
AS

	SELECT 
		MOV_CONTO AS CONTO,
		COALESCE(CONTI.CON_DESCR,'') AS DESCRIZIONE,
		SUBSTRING(MOV_DTCOMP,1,7) AS MESE_COMP,
		SUM(CASE MOV_TMOV WHEN 'D' THEN MOV_IMP ELSE (-1)*MOV_IMP END) AS SALDO
	FROM MOV_CONT 
	LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = SUBSTRING(MOV_DTCOMP,1,4) AND CONTI.CON_CONTO = MOV_CONT.MOV_CONTO
	WHERE MOV_TOP <> 'CHI' AND SUBSTRING(MOV_DTCOMP,1,4) >= '2011'
	GROUP BY MOV_CONTO,SUBSTRING(MOV_DTCOMP,1,7),CON_DESCR

