-- VISTA FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]'))
	DROP VIEW [dbo].[FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
GO

CREATE VIEW [dbo].[FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
AS

	SELECT 
		--COALESCE(FAT_DD.ORD_CCODET,'') AS COD_CENTRO_COSTO,
		--COALESCE(CCOSTO.CON_DESCR,'') AS DESCR_CENTRO_COSTO,
		CASE
			WHEN COALESCE((SELECT AZI_CONTOSIMILCEE FROM U_AZI_PC),0) = 1 THEN
				RIGHT('0000000000' + RTRIM(REVERSE(LEFT(REVERSE(RIGHE_PART.PAR_CODCLI), CHARINDEX('.', REVERSE(RIGHE_PART.PAR_CODCLI)) -1))), COALESCE((SELECT AZI_CONTO FROM U_AZI_AN),9))
			ELSE SUBSTRING(RIGHE_PART.PAR_CODCLI,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10)
		END AS COD_CLIENTE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NPROT AS NUM_FATTURA,
		RIGHE_PART.PAR_DTFAT AS DATA_FATTURA,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS IMPORTO_SCAD_PAG,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) - ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS RESIDUO_SCAD_PAG,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		ROUND(FAT_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		ROUND(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO + FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,2) AS IMPONIBILE_IMPOSTA_TOT_FATTURA,
		ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		ROUND(COALESCE(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO,0),2) AS IMPONIBILE_TOT_FATTURA,
		ROUND(COALESCE(FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,0),2) AS IMPOSTA_TOT_FATTURA,
		--COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,1,3),'') AS CANALE_VENDITA_CLIENTE,
		--COALESCE(PARA_CVE_1.DESCRI,'') AS DESCR_CANALE_VENDITA_CLIENTE,
		--COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,4,3),'') AS MACROCLASSE_CLIENTE,
		--COALESCE(PARA_CVE_2.DESCRI,'') AS DESCR_MACROCLASSE_CLIENTE,
		--COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,7,3),'')	AS CLASSE_CLIENTE,
		--COALESCE(PARA_CVE_3.DESCRI,'') AS DESCR_CLASSE_CLIENTE,
		COALESCE(U_CLI_AN.CLI_NAZION,'') AS NAZIONE_CLIENTE,
		COALESCE(PARA_STA.DESCRI,'') AS DESCR_NAZIONE_CLIENTE,
		--COALESCE(U_CLI_AN.CLI_ZONA,'') AS AREA_GEOGRAFICA_CLIENTE,
		--COALESCE(PARA_ZON.DESCRI,'') AS DESCR_AREA_GEOGRAFICA_CLIENTE,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA2,
		CASE
			--WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) >= ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2)  
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0
				THEN COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN COALESCE(PAG_ULT.PAR_DTREG,'')
			ELSE ''
		END AS DATA_PAGAMENTO,
		CASE
			--WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) >= ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))) AS datetime))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_ULT.PAR_DTREG,'')) AS datetime))
			ELSE 0
		END AS NR_GIORNI_RITARDO,
		COALESCE(PAG_SCA.NR_GIORNI_RITARDO_MEDI_PONDERATI,0) AS NR_GIORNI_RITARDO_MEDI_PONDERATI
	FROM PART_CLI AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) <> 'S')  GROUP BY PAR_CODCLI, PAR_NPART) AS FAT_TOT ON FAT_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAT_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, COALESCE(MAX(PAR_DTREG),'') AS PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) AS IMPORTO_SCAD_PAG, CASE WHEN SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) <> 0 THEN (SUM(PAR_FATT * PAR_CAMBIO * CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END)) ELSE 0 END AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS ULT_IMPORTO_SCAD_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS PAG_ULT
		LEFT OUTER JOIN (SELECT DISTINCT ORD_CCODET, ORS_NUMORD, ORS_DATORD FROM U_FAT_DD WHERE ORD_DESART <> '*** COMMENTO ***') AS FAT_DD ON FAT_DD.ORS_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_DD.ORS_DATORD = RIGHE_PART.PAR_DTFAT
		RIGHT OUTER JOIN U_FAT_TT AS FAT_TT ON FAT_TT.ORD_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_TT.ORD_DATORD = RIGHE_PART.PAR_DTFAT
		LEFT OUTER JOIN CCOSTO ON CCOSTO.CON_ANNO = SUBSTRING(FAT_DD.ORS_DATORD,1,4) AND CCOSTO.CON_CONTO = FAT_DD.ORD_CCODET
		LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODCLI = FAT_TT.ORD_CODCLI
		--LEFT OUTER JOIN PARA AS PARA_CVE_1 ON PARA_CVE_1.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,3)
		--LEFT OUTER JOIN PARA AS PARA_CVE_2 ON PARA_CVE_2.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,6)
		--LEFT OUTER JOIN PARA AS PARA_CVE_3 ON PARA_CVE_3.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,9)
		LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION
		--LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+U_CLI_AN.CLI_ZONA
		--OUTER APPLY (SELECT (SUM(PAR_FATT * PAR_CAMBIO * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO)) AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD) AS MEDIA_PAG
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'D' AND COALESCE(SUBSTRING(PARA_TOP.LIBERA,2,1),'') IN ('S','F','A') AND SUBSTRING(PARA_TOP.LIBERA,11,1) <> 'S')
		AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAT_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))
		--AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)

GO


SELECT * FROM FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO ORDER BY DATA_FATTURA,NUM_FATTURA,RAG_SOCIALE