
-- VISTA ELENCO_ARTICOLI_CON_GIACENZA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_ARTICOLI_CON_GIACENZA]'))
	DROP VIEW [dbo].[ELENCO_ARTICOLI_CON_GIACENZA]
GO

CREATE VIEW [dbo].[ELENCO_ARTICOLI_CON_GIACENZA]
AS

SELECT
	ART_CODPRI AS COD_ARTICOLO,
	ART_DESCR AS DESCRIZIONE,
	ART_UMMAGA AS UM,
	COALESCE(MAG_CODMAG,'') AS MAG,
	COALESCE(SUM(MAG_GIACEN),0) AS GIACENZA,
	0 AS RILEVATA
FROM (
	SELECT
		PR.ART_CODPRI,
		PR.ART_DESCR,
		PR.ART_UMMAGA,
		GG.MAG_CODMAG,
		GG.MAG_GIACEN
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_MAG_GG AS GG ON GG.MAG_ANAART = PR.ART_CODPRI
	WHERE PR.ART_NONMOV = 0 and PR.ART_OBSOL <> 'S'
	) AS MAIN
GROUP BY
	ART_CODPRI,
	ART_DESCR,
	ART_UMMAGA,
	MAG_CODMAG

GO