insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI118','radaelli.gian.luigi','RADAELLI','GIAN LUIGI','radaelli.gian.luigi@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI117','moretti.massimo','MORETTI','MASSIMO','moretti.massimo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI110','filacchione.vincenzo','FILACCHIONE','VINCENZO','filacchione.vincenzo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI999','ghisoni.simone','GHISONI','SIMONE','ghisoni.simone@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI103','molari.luca','MOLARI','LUCA','molari.luca@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI203','paris.alessandra','PARIS','ALESSANDRA','paris.alessandra@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI205','consoli.roberto','CONSOLI','ROBERTO','consoli.roberto@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI116','villa.franco','VILLA','FRANCO','villa.franco@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI108','secchiero.massimo','SECCHIERO','MASSIMO','secchiero.massimo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI109','torresani.stefano','TORRESANI','STEFANO','torresani.stefano@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI112','calcagno.angelo','CALCAGNO','ANGELO','calcagno.angelo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI121','manuel.consoli','MANUEL','CONSOLI','manuel.consoli@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI111','r.m..snc.di.marziani.luca.&..c...sas','R.M','SNC di Marziani Luca &  C   SAS','r.m..snc.di.marziani.luca.&..c...sas@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI101','croda.carlo','CRODA','CARLO','croda.carlo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI204','cristina','CRISTINA','CRISTIN','cristina@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI113','bramati.mirko','BRAMATI','MIRKO','bramati.mirko@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI106','legorano.jacopo','LEGORANO','JACOPO','legorano.jacopo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI102','provesi.yuri.marco','PROVESI','YURI MARCO','provesi.yuri.marco@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI140','contini.michele','CONTINI','MICHELE','contini.michele@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI105','laborante.giuseppe','LABORANTE','GIUSEPPE','laborante.giuseppe@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI120','pronto.inter.elettr.-elettricista','PRONTO','INTER.ELETTR.-Elettricista','pronto.inter.elettr.-elettricista@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI114','strangio.maurizio','STRANGIO','MAURIZIO','strangio.maurizio@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI100','alessandra.paris','Alessandra','Paris','alessandra.paris@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI141','riboni.massimo','RIBONI','MASSIMO','riboni.massimo@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI119','manzotti.luca','MANZOTTI','LUCA','manzotti.luca@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI104','serve.alla.logica.del.programma','Serve','alla logica del programma','serve.alla.logica.del.programma@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI107','matti.manuel','MATTI','MANUEL','matti.manuel@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI115','riva.ezio','RIVA','EZIO','riva.ezio@trevicalor.it',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI000','assistenza','Assitenza','Tecnica','assistenza@projectsrl.net',1,'',0)
insert into utenti (codice_utente,username,cognome,nome,email,id_utente_ins,ts_ins,fl_disattivo) values ('TEI130','imeri..matteo','IMERI','MATTEO','imeri..matteo@trevicalor.it',1,'',0)


insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (3,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (4,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (5,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (6,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (7,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (8,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (9,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1 ,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (10,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (11,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (12,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (13,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (14,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (15,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (16,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (17,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (18,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (19,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (20,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (21,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (22,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (23,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (24,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (25,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (26,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (27,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (28,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (29,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (30,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (31,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')
insert into password (id_utente,password,dt_scadenza,fl_valida,ts_ins) values (32,'5baa61e4c9b93f3f68225b6cf8331b7ee68fd8','',1,'2023-01-01 01:01:01')

update password set DT_SCADENZA='2999/12/31' where id_utente>28



insert into aziende (codice,ragsoc,alias_azienda,fl_disattivo) values ('TRE','Trevicalor','trevicalor',0)


insert into utenti_aziende (id_utente,id_azienda) values (3,1)
insert into utenti_aziende (id_utente,id_azienda) values (4,1)
insert into utenti_aziende (id_utente,id_azienda) values (5,1)
insert into utenti_aziende (id_utente,id_azienda) values (6,1)
insert into utenti_aziende (id_utente,id_azienda) values (7,1)
insert into utenti_aziende (id_utente,id_azienda) values (8,1)
insert into utenti_aziende (id_utente,id_azienda) values (9,1)
insert into utenti_aziende (id_utente,id_azienda) values (10,1)
insert into utenti_aziende (id_utente,id_azienda) values (11,1)
insert into utenti_aziende (id_utente,id_azienda) values (12,1)
insert into utenti_aziende (id_utente,id_azienda) values (13,1)
insert into utenti_aziende (id_utente,id_azienda) values (14,1)
insert into utenti_aziende (id_utente,id_azienda) values (15,1)
insert into utenti_aziende (id_utente,id_azienda) values (16,1)
insert into utenti_aziende (id_utente,id_azienda) values (17,1)
insert into utenti_aziende (id_utente,id_azienda) values (18,1)
insert into utenti_aziende (id_utente,id_azienda) values (19,1)
insert into utenti_aziende (id_utente,id_azienda) values (20,1)
insert into utenti_aziende (id_utente,id_azienda) values (21,1)
insert into utenti_aziende (id_utente,id_azienda) values (22,1)
insert into utenti_aziende (id_utente,id_azienda) values (23,1)
insert into utenti_aziende (id_utente,id_azienda) values (24,1)
insert into utenti_aziende (id_utente,id_azienda) values (25,1)
insert into utenti_aziende (id_utente,id_azienda) values (26,1)
insert into utenti_aziende (id_utente,id_azienda) values (27,1)
insert into utenti_aziende (id_utente,id_azienda) values (28,1)
insert into utenti_aziende (id_utente,id_azienda) values (29,1)
insert into utenti_aziende (id_utente,id_azienda) values (30,1)
insert into utenti_aziende (id_utente,id_azienda) values (31,1)
insert into utenti_aziende (id_utente,id_azienda) values (32,1)


insert into lingue_iso (codice_iso,lingua) values ('it','Italiano')
insert into lingue_iso (codice_iso,lingua) values ('en','English')


insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (3 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (4 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (5 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (6 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (7 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (8 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (9 ,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (10,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (11,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (12,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (13,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (14,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (15,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (16,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (17,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (18,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (19,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (20,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (21,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (22,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (23,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (24,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (25,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (26,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (27,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (28,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (29,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (30,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (31,1,1)
insert into utenti_lingue (id_utente,fl_default,id_lingue_iso) values (32,1,1)


insert into profili (codice,descrizione) values ('TEC','Tecnico')
insert into profili (codice,descrizione) values ('ADM','Administrator')


insert into menu_profili (id_menu,id_profilo) values (1,1)
insert into menu_profili (id_menu,id_profilo) values (2,1)
insert into menu_profili (id_menu,id_profilo) values (3,1)
insert into menu_profili (id_menu,id_profilo) values (4,1)
insert into menu_profili (id_menu,id_profilo) values (1,2)
insert into menu_profili (id_menu,id_profilo) values (2,2)
insert into menu_profili (id_menu,id_profilo) values (3,2)
insert into menu_profili (id_menu,id_profilo) values (4,2)



insert into utenti_profili (id_utente,id_profilo) values (3 ,1)
insert into utenti_profili (id_utente,id_profilo) values (4 ,1)
insert into utenti_profili (id_utente,id_profilo) values (5 ,1)
insert into utenti_profili (id_utente,id_profilo) values (6 ,1)
insert into utenti_profili (id_utente,id_profilo) values (7 ,1)
insert into utenti_profili (id_utente,id_profilo) values (8 ,1)
insert into utenti_profili (id_utente,id_profilo) values (9 ,1)
insert into utenti_profili (id_utente,id_profilo) values (10,1)
insert into utenti_profili (id_utente,id_profilo) values (11,1)
insert into utenti_profili (id_utente,id_profilo) values (12,1)
insert into utenti_profili (id_utente,id_profilo) values (13,1)
insert into utenti_profili (id_utente,id_profilo) values (14,1)
insert into utenti_profili (id_utente,id_profilo) values (15,1)
insert into utenti_profili (id_utente,id_profilo) values (16,1)
insert into utenti_profili (id_utente,id_profilo) values (17,1)
insert into utenti_profili (id_utente,id_profilo) values (18,1)
insert into utenti_profili (id_utente,id_profilo) values (19,1)
insert into utenti_profili (id_utente,id_profilo) values (20,1)
insert into utenti_profili (id_utente,id_profilo) values (21,1)
insert into utenti_profili (id_utente,id_profilo) values (22,1)
insert into utenti_profili (id_utente,id_profilo) values (23,1)
insert into utenti_profili (id_utente,id_profilo) values (24,1)
insert into utenti_profili (id_utente,id_profilo) values (25,1)
insert into utenti_profili (id_utente,id_profilo) values (26,1)
insert into utenti_profili (id_utente,id_profilo) values (27,1)
insert into utenti_profili (id_utente,id_profilo) values (28,1)
insert into utenti_profili (id_utente,id_profilo) values (29,1)
insert into utenti_profili (id_utente,id_profilo) values (30,1)
insert into utenti_profili (id_utente,id_profilo) values (31,2)
insert into utenti_profili (id_utente,id_profilo) values (32,1)


update password set dt_scadenza='2999/12/31'