/******************************************
 INSERIMENTO FASI DI LAVORAZIONE PER LOGPRD
******************************************/

--DELETE FROM PARA WHERE CODICE LIKE 'FAL%' AND DESIVA = ''

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FALTAGL','TAGLIO','2','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FALAGGR','AGGRAFFATURA','3','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('FALASSI','ASSIEMAGGIO','4','')

SELECT * FROM PARA WHERE CODICE LIKE 'FAL%' ORDER BY LIBERA
