modi report report\1AGNLIST
modi report report\ACCSTA
modi report report\ACCSTAMP
modi report report\ADDAORD
modi report report\AGELIST
modi report report\AGGANC000
modi report report\AGG_CONTI_CODCES
modi report report\AGG_DETT_CESPITI
modi report report\AGNLIST
modi report report\ALLEBIL
modi report report\ALTCOMPA
modi report report\AMMCAT
modi report report\ammces
modi report report\AMMCES_DETT
modi report report\AMMLIST
modi report report\AMMLIST2
modi report report\AMMSITA
modi report report\AMMSITN
modi report report\AMMSITU
modi report report\ammspe
modi report report\AMMSTAGE
modi report report\ANAAZI000
modi report report\ANACES
modi report report\andamentogenerale
modi report report\ANDAMENTOGENERALE1
modi report report\ANDAMENTOGENERALE2
modi report report\ANDAMENTOGENERALE3_1
modi report report\ANDAMENTOGENERALE3_1_dett
modi report report\andamentogenerale3_2
modi report report\ANDAMENTOGENERALE3_2_dett
modi report report\ANDAMENTOGENERALE_RIEP
modi report report\ANDAMENTO_produzione_RIB
modi report report\ANDAMENTO_produzione_spa
modi report report\ANDAMENTO_produzione_TAG
modi report report\art000
modi report report\ARTBOLNOMAG
modi report report\ARTDATIN
modi report report\ARTKO00
modi report report\ARTPRZA
modi report report\ARTPRZE
modi report report\ARTPRZF
modi report report\ARTSITU
modi report report\ASS000
modi report report\asspjeur
modi report report\ASSSIT00
modi report report\ASSSIT01
modi report report\ASSSIT02
modi report report\ASSSIT03
modi report report\ASSSIT04
modi report report\AST000
modi report report\AST001
modi report report\ASTDOS
modi report report\ATT000
modi report report\AUT000
modi report report\BAN000
modi report report\benefat
modi report report\benefat1
modi report report\benefat2
modi report report\BENFOR
modi report report\BENFOR1
modi report report\benfor2
modi report report\bfodacaric
modi report report\BFOELEND
modi report report\BFOELEND1
modi report report\BFOELENDd
modi report report\bfoelendX
modi report report\BFOELENT
modi report report\bfoelent1
modi report report\bfoelentd
modi report report\BFOLIST
modi report report\BFOPJCOC
modi report report\BFOPJCON
modi report report\bfopjetc
modi report report\bfopjetc_resi
modi report report\BFOPJETC_RI2
modi report report\BFOPJETC_RIN
modi report report\bfopjeti
modi report report\BFOPJETI_ALT
modi report report\BFOPJETI_RI2
modi report report\BFOPJETI_RIN
modi report report\BFOPJITA
modi report report\BFOPJPLI
modi report report\BIAPEC
modi report report\BIAPPA
modi report report\BILCON1
modi report report\BILCON2
modi report report\bofconse
modi report report\bofconsi
modi report report\bofpjitp
modi report report\BOLLIST
modi report report\BOLNOFAD
modi report report\BOLNOFAT
modi report report\BOLNOFAX
modi report report\BOLPJITT
modi report report\BOLPJRES
modi report report\bolpjresfor
modi report report\BOLRITI
modi report report\BOLSTELE
modi report report\BUDLIST
modi report report\BUDRAG
modi report report\bud_am000
modi report report\CAL000
modi report report\Cam000
modi report report\campsta
modi report report\campsta01
modi report report\campsta02
modi report report\campsta03
modi report report\campsta04
modi report report\campsta0X
modi report report\campsta11
modi report report\campsta12
modi report report\campsta13
modi report report\campsta14
modi report report\campsta1X
modi report report\CAMPSTA_RIT
modi report report\CARSTA
modi report report\cas000
modi report report\casdos
modi report report\caslist
modi report report\caspjeur
modi report report\CCO000
modi report report\CCOGR000
modi report report\CCOSTA
modi report report\CCOSTA2
modi report report\CEA000
modi report report\CEA001
modi report report\CEA002
modi report report\CEALIST
modi report report\CEECORI
modi report report\CEERET
modi report report\CEERIC
modi report report\cei000
modi report report\cei001
modi report report\cei002
modi report report\CEILIST
modi report report\CERT_CONF
modi report report\cert_conf_ING
modi report report\CICCOMP
modi report report\CICPARZ
modi report report\CLI000
modi report report\CLIf000
modi report report\CLINOTE
modi report report\CLINOTIP
modi report report\CLISCHE
modi report report\CLIVER
modi report report\CLIVERPI
modi report report\CMP000
modi report report\CNTDD00
modi report report\CNTDD01
modi report report\CNTDD02
modi report report\CNTDD03
modi report report\CNTDD04
modi report report\CNTDD05
modi report report\CNTDET
modi report report\CNTDET1
modi report report\CNTDET2
modi report report\CNTDET3
modi report report\CNTDET4
modi report report\CNTDET5
modi report report\cntlist
modi report report\cntpr
modi report report\COMMESSA000
modi report report\COMPE
modi report report\COMUNI
modi report report\CON000
modi report report\conant000
modi report report\conantdetfa
modi report report\conantriefa
modi report report\CONF002
modi report report\CONFLIST
modi report report\conpjeur
modi report report\CONSIT00
modi report report\CONSIT01
modi report report\CONSIT02
modi report report\CONSIT03
modi report report\CONSIT04
modi report report\CONSITORDCLI
modi report report\crebolpor1
modi report report\CREORF
modi report report\creorfpor
modi report report\CREORFPOR1
modi report report\CREORFPOR2
modi report report\CTLPJEUR
modi report report\CTRLBFd
modi report report\CTRLBFd1
modi report report\CTRLBFT
modi report report\CTRLBFT1
modi report report\CTRLFAT
modi report report\ctrlprovvi
modi report report\CTRL_DOP
modi report report\daamm
modi report report\daamm1
modi report report\DDTTOFAT
modi report report\DICHIARA
modi report report\discbfo
modi report report\DISCBFO01
modi report report\DISCBFO02
modi report report\DISCREP
modi report report\DISDOVE1
modi report report\diselen1
modi report report\ela000
modi report report\elaan00
modi report report\elaer00
modi report report\ELAER001
modi report report\elaer01
modi report report\ELEBOLDAFAT
modi report report\ELEfatdacon
modi report report\ELEGIACE
modi report report\ELEMAGA
modi report report\ELENCOPRG
modi report report\elenprod
modi report report\ELESCHEA
modi report report\ERRINTRA
modi report report\ESTRDETC
modi report report\ESTRDETT
modi report report\estrdetts
modi report report\ETICCOLLA
modi report report\eticspalma
modi report report\eticspalma1
modi report report\ETICSPALMA2
modi report report\ETICSPALMA3
modi report report\eticspalma3_RESO
modi report report\ETICSPALMAR
modi report report\eticspalmat
modi report report\ETICSPALMAT1
modi report report\eticspalmatc
modi report report\eticspalme
modi report report\FABBISOGNI
modi report report\FABBISOGNI_MAN
modi report report\FABBISOGNI_RIEP
modi report report\fagfatag
modi report report\FAGLIST
modi report report\FAMLIST
modi report report\FAMLIST2
modi report report\FAMSTAGE
modi report report\FAPLIST
modi report report\FAPLIST2
modi report report\FAPMODE
modi report report\fappjeur_FAP
modi report report\fappjeur_FAT
modi report report\FAPSTAGE
modi report report\FAtLIST
modi report report\FATLIST2
modi report report\FATLISTC
modi report report\FATMAGA
modi report report\FATMODE
modi report report\FATMODI
modi report report\fatpjeut
modi report report\FATPJEXT
modi report report\fatPJitp
modi report report\FATSTA
modi report report\FATSTA00
modi report report\FATSTA01
modi report report\FATSTAGE
modi report report\FATTUCLI
modi report report\FIDELSTA
modi report report\FIDMOD
modi report report\FILEVA
modi report report\FILGIA
modi report report\FIN000
modi report report\finPJEUR
modi report report\finsit00
modi report report\finsit01
modi report report\finsit02
modi report report\finsit03
modi report report\finsit04
modi report report\fndaord
modi report report\FOR000
modi report report\FORARTI
modi report report\FORNOTE
modi report report\FORSCHE
modi report report\FORVER
modi report report\FORVERPI
modi report report\FPR000
modi report report\FTP000
modi report report\FTP001
modi report report\GCOCAP
modi report report\GCOCFIS
modi report report\GCOCITTA
modi report report\GCOCOD
modi report report\GCOCONT
modi report report\GCOCOSO
modi report report\GCODITTA
modi report report\GCODOPE
modi report report\GCOFABB
modi report report\GCOGROS
modi report report\GCOIDITT
modi report report\GCOIMB
modi report report\GCOKEY1
modi report report\GCOKEY2
modi report report\GCOMANMA
modi report report\GCOMAPRI
modi report report\GCOMARK
modi report report\GCONAZ
modi report report\GCOOCONT
modi report report\GCOPIVA
modi report report\GCOPRFIN
modi report report\GCOPROV
modi report report\GCOPRUF
modi report report\GCOREGIO
modi report report\GCORIST
modi report report\GCOSETAT
modi report report\GCOSUBCO
modi report report\GCOTELEF
modi report report\GCOTIPRO
modi report report\GCOTRASP
modi report report\GIAC000
modi report report\GIACSED
modi report report\giac_maginf
modi report report\GIASOFF
modi report report\gpe000
modi report report\GPP000
modi report report\GUADAGNO
modi report report\IMB000
modi report report\INTEMAG0
modi report report\INTEMAG1
modi report report\INTEMAG2
modi report report\INTEMAG3
modi report report\INTEMAG4
modi report report\INTEMAG5
modi report report\INTEMAG6
modi report report\INTEMAG7
modi report report\INVGIACE
modi report report\INVMODI
modi report report\IVACOPDV
modi report report\LAVOLIST
modi report report\LEA000
modi report report\LEAPJEUR
modi report report\leasit00
modi report report\leasit01
modi report report\leasit02
modi report report\leasit03
modi report report\leasit04
modi report report\LEGABFOD
modi report report\LEGABFOT
modi report report\LEGD000
modi report report\LEGDANN
modi report report\LEGDVIS
modi report report\LETTERA
modi report report\LIB000
modi report report\LICENZA
modi report report\LIFSTA
modi report report\LIG000
modi report report\LINGUE
modi report report\LIQUIDA
modi report report\LIQUIMM
modi report report\liquimm_rino
modi report report\LISLIART
modi report report\lispreli
modi report report\LISTAGE
modi report report\LISTAGE2
modi report report\LISTArt
modi report report\LISTARTALT
modi report report\LISTVEN
modi report report\LOC000
modi report report\LOCGIAC1
modi report report\LOCGIAC2
modi report report\LOCGIAC3
modi report report\LOCGIAC4
modi report report\LOCGIAC6
modi report report\LOCGIAC7
modi report report\LOCGIAC8
modi report report\LOCGIAC9
modi report report\LOG000
modi report report\logattivita
modi report report\logerror
modi report report\logimportxls
modi report report\LOGOPE
modi report report\LOGR000
modi report report\LOG_TRASMCNT
modi report report\lot000
modi report report\magafisc_giorn_01
modi report report\magafisc_giorn_02
modi report report\magafisc_giorn_03
modi report report\magafisc_scheda_01
modi report report\magafisc_scheda_02
modi report report\magafisc_scheda_03
modi report report\magaflag1
modi report report\magaflag1Q
modi report report\magaflag1_sal
modi report report\MAGAFLAG2
modi report report\MAGAFLAG3
modi report report\magaflag3_CSTAGG
modi report report\MAGAFLAG3_CSTAGG_RIEPARTI
modi report report\MAGAFLAG4
modi report report\MAGAFLAG5
modi report report\MAGAFLAG5_RIEP
modi report report\MAGAFLAGM1
modi report report\MAGAFLAGM11
modi report report\MAGAFLAGM2
modi report report\MAGAFLAGM22
modi report report\MAGAFLAGS1
modi report report\magaflags2
modi report report\MAGAFLAGS3
modi report report\MAGAFLAGS4
modi report report\MAGAFLAGS5
modi report report\MAGAFLAGS6
modi report report\MAGAFLAGS7
modi report report\MAGAFLAGS8
modi report report\MAGAFLAGS9
modi report report\MAGAFLAGSM1
modi report report\MAGAFLAGSM11
modi report report\MAGAFLAGSM2
modi report report\MAGAFLAGSM22
modi report report\MAGAGENSALDI_MOV
modi report report\MAGASTCO
modi report report\MAGAVACO
modi report report\MAGAVACO1
modi report report\MAGAVACO10
modi report report\MAGAVACO11
modi report report\MAGAVACO2
modi report report\MAGAVACO3
modi report report\magavaco4
modi report report\MAGAVACO5
modi report report\MAGAVACO6
modi report report\MAGAVACO7
modi report report\magavaco8
modi report report\MAGAVACO9
modi report report\MAGFONDE
modi report report\MAGGIA1
modi report report\MAGGIA11
modi report report\MAGGIA111
modi report report\maggia1111
modi report report\MAGGIA2
modi report report\MAGGIA22
modi report report\MAGGIA222
modi report report\MAGGIA3
modi report report\MAGGIA33
modi report report\MAGGIA333
modi report report\MAGGIA4
modi report report\MAGGIA44
modi report report\MAGGIA444
modi report report\MAGGIAC
modi report report\MAGGIAC1
modi report report\MAGGIAC9
modi report report\MAGGIACG
modi report report\MAGGIACM
modi report report\MAGGIAL
modi report report\MAGGIALM
modi report report\MAGLOG_GUI_01
modi report report\MAGLOG_GUI_02
modi report report\MAGMOVI
modi report report\MAGNOMOV
modi report report\MAGSOTSC
modi report report\manC00e
modi report report\manC01e
modi report report\manCune
modi report report\mand00e
modi report report\mand01e
modi report report\mand02e
modi report report\MANDRCOMP
modi report report\mandune
modi report report\mat000
modi report report\MESAGE
modi report report\MESCLI
modi report report\MESNAZ
modi report report\MESNAZ01
modi report report\MESNAZ02
modi report report\MONICASSE
modi report report\MONIVISIT
modi report report\MOVcontro
modi report report\MOVIMAGA_PDA
modi report report\MOVPART
modi report report\MOVSTCCO
modi report report\MOVSTCO1
modi report report\MOVSTCO2
modi report report\MOVSTCO3
modi report report\MOVSTORC
modi report report\MOVSTORI
modi report report\MOVSTORR
modi report report\MPACQ000_STAT
modi report report\MPALIST
modi report report\MPFCQ000_STAT01
modi report report\MPFCQ000_STAT02
modi report report\MPFLIST
modi report report\MRILIST
modi report report\MRIPJEUR
modi report report\MRIPJPER
modi report report\msg000
modi report report\MSGERR
modi report report\NDCLIST
modi report report\NOTE
modi report report\OFFLIST
modi report report\ORDCEVA
modi report report\ORDCLOSX
modi report report\ORDLEVA
modi report report\ORDLIST
modi report report\ordnosetpr
modi report report\ORDPJEUT
modi report report\ORDPJPER
modi report report\ordtra_sbloc
modi report report\ORF200
modi report report\orfdisimpordtes
modi report report\ORFLIST
modi report report\orfmod01
modi report report\PAFXCLI
modi report report\PAFXDET
modi report report\pafxfor
modi report report\PAFXNAZ
modi report report\PAFXSAL
modi report report\pagf000
modi report report\PAGF001
modi report report\PAGF002
modi report report\PAGF00E
modi report report\PAGF01E
modi report report\PAGF02E
modi report report\PAGFUNE
modi report report\PAGFUNO
modi report report\PAR000
modi report report\PARALIST
modi report report\PARASCAD
modi report report\parcqLIST
modi report report\PARFILIST
modi report report\PARMYLIST
modi report report\PARTICF
modi report report\PART_ALLEGATO_ANOMALIE
modi report report\PART_ALLEGATO_ANOMALIE_CLIENTI
modi report report\PARXAGE
modi report report\PARXCLI
modi report report\PARXDET
modi report report\PARXNAZ
modi report report\PARXRIE
modi report report\PARXSAL
modi report report\PCKNOSPE
modi report report\pckpj000
modi report report\PCKPJITA
modi report report\PCKsiSPE
modi report report\pdainvmodi01
modi report report\pdainvmodi02
modi report report\pdamovmodi
modi report report\PDAMOVMODI02
modi report report\PDC000_REL
modi report report\PDCELCO
modi report report\PDCSTA
modi report report\PDCSTA2
modi report report\PDCSTA3
modi report report\PDV000
modi report report\PDVCLOS1
modi report report\PDVCLOS2
modi report report\PDVCLOS3
modi report report\PDVCLOS4
modi report report\PDVCLOS5
modi report report\PDVCLOS6
modi report report\PDVCONTR
modi report report\PDVREG
modi report report\PDVTICAS
modi report report\PDVTIPAG
modi report report\PER000
modi report report\PER001
modi report report\PERSCHEDA
modi report report\PIANODD
modi report report\PJ_VIEW
modi report report\PKG000
modi report report\pkgcrea
modi report report\PKGCREANOEVA
modi report report\pkgdisimpord
modi report report\pkgdisimpordtes
modi report report\PKGGIACIMPE
modi report report\PKGGIACIMPI
modi report report\pkggiacimpo
modi report report\PKGSTAMPA
modi report report\PKLMAGCO
modi report report\PKLMAGLO
modi report report\PNCSTA
modi report report\portaford_age
modi report report\PORTAFORD_AGECLI
modi report report\PORTAFORD_ART
modi report report\PORTAFORD_NAZCLI
modi report report\portaford_nazriep
modi report report\PORTAFsuc_AGE
modi report report\PORTAFSUC_AGECLI
modi report report\portafsuc_ART
modi report report\PORTAFSUC_NAZCLI
modi report report\PRB000
modi report report\PRBELENDd
modi report report\PRBELENDS
modi report report\PRBELENtd
modi report report\PRBELENTS
modi report report\PRBLIST
modi report report\PRBPJITA
modi report report\PREMAGCO
modi report report\PRIMASI
modi report report\PRIMAVVA
modi report report\PRINRIBA
modi report report\PRNDOPPD
modi report report\PRNDOPPI
modi report report\PRNINCRO
modi report report\PRNPROT
modi report report\PRO000
modi report report\PROARTST
modi report report\PROCARI1
modi report report\PROCARI2
modi report report\PROCICCO
modi report report\PROCICPA
modi report report\PRODADORD
modi report report\PRODAOR1
modi report report\PRODAOR2
modi report report\prodbobi
modi report report\prodbobi1
modi report report\prodbobi2
modi report report\prodbobi_fatti
modi report report\prodbobi_fatti1
modi report report\prodbobi_fatti2
modi report report\PRODCOMP
modi report report\PRODFNORD
modi report report\PRODinmag
modi report report\PRODINORD_LANDI
modi report report\PRODmanca
modi report report\PRODMESCOLE_01
modi report report\PRODMESCOLE_02
modi report report\PRODMESCOLE_03
modi report report\prodmescole_04
modi report report\PRODNOPRG
modi report report\PRODNOPRG_landi
modi report report\PRODOVE
modi report report\PRODPEDAN3
modi report report\PRODPEDANA
modi report report\PRODRAPP
modi report report\prodrappCQ
modi report report\PRODRAPP_MAN
modi report report\prodrapp_NEW
modi report report\prodrapp_pre
modi report report\PRODRAPP_RAGGR
modi report report\PRODRAPR
modi report report\PRODRAPRCQ
modi report report\PRODRAPR_RAGGR
modi report report\PRODRAPT
modi report report\prodraptCQ
modi report report\prodraptr_raggr
modi report report\PRODRAPT_RAGGR
modi report report\PRODribo
modi report report\prodribobi_raggr
modi report report\PRODRIBOCQ
modi report report\prodRIB_riep
modi report report\prodsitordcli
modi report report\PRODSPAL
modi report report\prodspalcq
modi report report\prodspalm
modi report report\prodspal_NEW
modi report report\prodspal_riep
modi report report\PRODSPOSTA_TOP_PDA
modi report report\PRODTAGLIO
modi report report\prodtaglioCQ
modi report report\PRODTAGLIO_RAGGR
modi report report\PRODTAG_RIEP
modi report report\PROGIAST
modi report report\proINS
modi report report\PROLIST
modi report report\PROMACST
modi report report\PROPJEUC
modi report report\PROPJEUR
modi report report\PROPLIST
modi report report\PROSIMIL
modi report report\PROSITU1
modi report report\PROSITU2
modi report report\PROSITU3
modi report report\PROSTAR3
modi report report\PROVAGEN
modi report report\PROVINCE
modi report report\PRO_ERR
modi report report\prtpjeur
modi report report\PRTPOLIECO
modi report report\PRV000
modi report report\PRV001
modi report report\PRVD000
modi report report\PRVD001
modi report report\PRVD00C
modi report report\PRVD00CR
modi report report\QUADR_SC_PA
modi report report\quo_am_list
modi report report\RAAESTR
modi report report\RAAIRPEF
modi report report\RAASTA01
modi report report\RAASTA02
modi report report\RAASTA03
modi report report\RAASTA04
modi report report\RAASTA11
modi report report\RAASTA12
modi report report\RAASTA13
modi report report\RAASTA14
modi report report\raggbil
modi report report\raggbil2
modi report report\raggbiL3
modi report report\raggbil4
modi report report\raggrprgrib_sta
modi report report\raggrprgtag_sta
modi report report\RAPPROD_STAT
modi report report\rapsta
modi report report\RAPSTA_RIB
modi report report\RAPSTA_TAG
modi report report\REBANSCA
modi report report\rebpres
modi report report\rebprex
modi report report\RECLISCM
modi report report\REDSCAD
modi report report\REGCES
modi report report\REGCES1
modi report report\regioni
modi report report\REG_CESP_BOL_01
modi report report\REG_CESP_BOL_02
modi report report\REG_CESP_BOL_03
modi report report\REG_CESP_BOL_04
modi report report\RESELENDD
modi report report\RESELENTD
modi report report\RESPROD
modi report report\RETSTA
modi report report\RETTIF
modi report report\RIAESTR
modi report report\RIAIRPEF
modi report report\RIASTA01
modi report report\RIASTA02
modi report report\riasta02S
modi report report\RIASTA03
modi report report\riasta03S
modi report report\RIASTA04
modi report report\riasta04S
modi report report\RIASTA11
modi report report\RIASTA12
modi report report\RIASTA13
modi report report\RIASTA14
modi report report\RIBA000
modi report report\RIBASTAM
modi report report\RIBM000
modi report report\RIBPROG
modi report report\RICACLI
modi report report\RICART
modi report report\ricdetfa
modi report report\RICERR
modi report report\RICH000
modi report report\riconai
modi report report\ricriefa
modi report report\RID000
modi report report\RIDDISKE
modi report report\RIDDISKF
modi report report\RIEMAGCO
modi report report\riepconant1
modi report report\riepconant2
modi report report\RIEPCONTI
modi report report\riepdis1
modi report report\RIEPDIS2
modi report report\RIEPIVA
modi report report\RIMSTA
modi report report\RINO
modi report report\riorforn01
modi report report\riorforn02
modi report report\riorforn_sint
modi report report\riprov
modi report report\RISCLI
modi report report\risumana000
modi report report\ritenute
modi report report\RITIRI
modi report report\RITIRI1
modi report report\SALDI
modi report report\SALDI1
modi report report\SALDOC
modi report report\saldocc
modi report report\SCADXCLI
modi report report\scadxcliS
modi report report\SCADXCLI_AGE
modi report report\SCADXCLI_RIS
modi report report\SCADXFOR
modi report report\SCADXFORb
modi report report\scadxforS
modi report report\scarti_slpf
modi report report\scarti_slpf_01
modi report report\scarti_slpf_02
modi report report\SCARTI_SLPF_MOV
modi report report\SCARTI_SLPF_PERC
modi report report\SCARTI_SLPF_SAL
modi report report\scartprod
modi report report\scartprod1
modi report report\SCARXCLI
modi report report\SCARXFOR
modi report report\SCArXFORb
modi report report\SCASXCLI
modi report report\SCASXFOR
modi report report\SCAsXFORb
modi report report\SCAXBAN
modi report report\SCAXCLI
modi report report\SCAXTOP
modi report report\SCHECLI
modi report report\SckFor1
modi report report\sckfor2
modi report report\SCKFOR3
modi report report\SCORMI
modi report report\SCORMIN
modi report report\scormi_sta
modi report report\SIMCES
modi report report\SIMCES1
modi report report\SITFACFO
modi report report\SITFACFV
modi report report\SITFATCF
modi report report\SITFINAN
modi report report\SITINCPA
modi report report\SITUORDI
modi report report\slclist
modi report report\SLFLIST
modi report report\sms000
modi report report\sms001
modi report report\sms002
modi report report\sms003
modi report report\sms004
modi report report\sms005
modi report report\sms006
modi report report\sms007
modi report report\SOLLXCLI
modi report report\spc000
modi report report\SPELIST
modi report report\SPEPJEUR
modi report report\SPESTEL1
modi report report\SPESTELE
modi report report\SPOMAT
modi report report\STAARTDUPL
modi report report\STAFATT_01
modi report report\STAFATT_02
modi report report\stafatt_03
modi report report\STAFATT_04
modi report report\STAFATT_05
modi report report\STAFATT_06
modi report report\STAFATT_07
modi report report\stafatt_acq_dett
modi report report\stafatt_acq_dett_LEG
modi report report\stafatt_acq_riep
modi report report\STAFATT_ART
modi report report\STAFATT_RIEPMESI_QTA
modi report report\STAFATT_RIEPMESI_QTAVALPRZ
modi report report\STAFATT_RIEPMESI_QTAVALPRZ_TOT
modi report report\STAFATT_RIEPMESI_QTA_TOT
modi report report\STAFATT_RIEPMESI_VAL
modi report report\stafatt_riepmesi_val_tot
modi report report\stamas1
modi report report\STAMASS
modi report report\STAMAVVP
modi report report\STAMCOMP
modi report report\STAMDISB
modi report report\STAMESAZ
modi report report\stamesco
modi report report\STAMPACQ_01
modi report report\stampacq_02
modi report report\STAMPACQ_03
modi report report\stamPRE
modi report report\stamrita
modi report report\STATACQMOV
modi report report\STATACQMOV1
modi report report\STATAVAN
modi report report\STATAVANSP
modi report report\STATBFO
modi report report\STATCNT01
modi report report\STATCNT02
modi report report\STATCNT_PRAZ
modi report report\STATGENE
modi report report\statgene_graph1
modi report report\STATGENE_GRAPH2
modi report report\statgene_graph3
modi report report\statgene_graph4
modi report report\statgene_graph5
modi report report\STATGENE_itaexp
modi report report\STATGENE_mqfatt
modi report report\statmqa1
modi report report\statmqa11
modi report report\statmqa2
modi report report\statmqa22
modi report report\statmqa3
modi report report\statmqa33
modi report report\statmqa4
modi report report\statmqa44
modi report report\statmqa5
modi report report\statmqa55
modi report report\statmqa6
modi report report\statmqa66
modi report report\statmqa7
modi report report\statmqa77
modi report report\STATORDCLI_01
modi report report\STATORDCLI_02
modi report report\STATORDCLI_03
modi report report\STATORDCLI_04
modi report report\STATORDCLI_05
modi report report\STATORDCLI_06
modi report report\STATORDCLI_07
modi report report\STATORDCLI_08
modi report report\STATORDCLI_09
modi report report\STATORDCLI_10
modi report report\STATORDfor_01
modi report report\STATORDfor_02
modi report report\STATORDfor_03
modi report report\STATORDfor_04
modi report report\STATORDfor_06
modi report report\STATORDfor_07
modi report report\STATORDFOR_10
modi report report\STATORDMAG_01
modi report report\statordmag_02
modi report report\STATORDMAG_03
modi report report\STATORDTRA
modi report report\STATVENMOV
modi report report\STATVENMOV1
modi report report\STAT_CESP_COGE
modi report report\STAT_CESP_T
modi report report\STAT_CESP_TD
modi report report\STBI01
modi report report\STBI02
modi report report\STBICCO
modi report report\STBIEC
modi report report\STBIEC1
modi report report\STBIECO
modi report report\STBILCE1
modi report report\STBILCEE
modi report report\STBIlcer
modi report report\STBIPA
modi report report\STBIPA1
modi report report\STBIPAT
modi report report\STBIPEC
modi report report\STBIPPA
modi report report\STBOLLA1
modi report report\STBOLLA2
modi report report\stcnt
modi report report\STCNT00
modi report report\STCNT01
modi report report\STCNT02
modi report report\STCNT03
modi report report\STCNT04
modi report report\STCNT05
modi report report\STCNTDET
modi report report\STCNTDET1
modi report report\STCNTDET2
modi report report\STCNTDET3
modi report report\STCNTDET4
modi report report\STCNTDET5
modi report report\STCNTDT
modi report report\STFORPR00
modi report report\STFORPR01
modi report report\stoces
modi report report\stoces1
modi report report\STOCES2
modi report report\stoces3
modi report report\STprovvi
modi report report\TAGCOLG1
modi report report\TAGCOLG2
modi report report\TAGCOLGI
modi report report\TAGCOLID
modi report report\TAGCOLIR
modi report report\TAGCOLM1
modi report report\TAGCOLM2
modi report report\TAGCOLMO
modi report report\TES000
modi report report\TESCOMP
modi report report\tesfed
modi report report\TESfor
modi report report\TESPAR
modi report report\tesPJEUR
modi report report\TESRIS
modi report report\TES_RIEPILOGO
modi report report\TIMESHT000
modi report report\TOP000
modi report report\tracdoc
modi report report\TRASPCLASS
modi report report\traspclass_camp
modi report report\TRASPCONTRATTI
modi report report\traspcontratti1
modi report report\TRASPCOSTI
modi report report\traspcosti_camp
modi report report\trasppesi
modi report report\trloin
modi report report\TRLOIN_ANA
modi report report\TRLOIN_CERCAAVA
modi report report\TRLOIN_CERCALOTTO
modi report report\TRLOIN_MPACQ
modi report report\TRLOIN_MPfCQ
modi report report\trloin_slfcq
modi report report\txtgene
modi report report\util_numerazione_ddt
modi report report\util_numerazione_fat
modi report report\VALLIST
modi report report\VENABCQ
modi report report\VENABCQS
modi report report\VENABCV
modi report report\VENACLI
modi report report\VENAGE
modi report report\VENAGMED
modi report report\VENART
modi report report\VENBOL01
modi report report\venbol02
modi report report\VENCLI
modi report report\venfor00
modi report report\VENFOR00X
modi report report\venfor01
modi report report\venfor01X
modi report report\venfor02
modi report report\VENFOR02X
modi report report\venfor03
modi report report\VENFOR03X
modi report report\venfor04
modi report report\venfor04X
modi report report\venfor05
modi report report\venfor05X
modi report report\venfor06
modi report report\venfor06X
modi report report\venfor13
modi report report\venfor13X
modi report report\venfor14
modi report report\venfor14X
modi report report\venfor15
modi report report\venfor15X
modi report report\venfor16
modi report report\venfor16X
modi report report\VENGORA1
modi report report\VENGORA2
modi report report\VENLIN
modi report report\VENLINC
modi report report\VENMED
modi report report\VENMRI00
modi report report\VENMRI01
modi report report\VENMRI02
modi report report\VENMRI03
modi report report\VENMRI04
modi report report\VENMRI05
modi report report\VENMRI06
modi report report\VENMRI13
modi report report\VENMRI14
modi report report\VENMRI15
modi report report\VENMRI16
modi report report\VENMRIF0
modi report report\VENMRIM0
modi report report\VENMRIM1
modi report report\VENOFF00
modi report report\VENOFF01
modi report report\VENOFF02
modi report report\VENOFF03
modi report report\VENOFF04
modi report report\VENOFF05
modi report report\VENOFF06
modi report report\VENOFF13
modi report report\VENOFF14
modi report report\VENOFF15
modi report report\VENOFF16
modi report report\VENOFFM0
modi report report\VENOFFM1
modi report report\VENORD00
modi report report\VENORD01
modi report report\VENORD02
modi report report\VENORD03
modi report report\VENORD04
modi report report\VENORD05
modi report report\VENORD06
modi report report\VENORD13
modi report report\VENORD14
modi report report\VENORD15
modi report report\VENORD16
modi report report\VENORDM0
modi report report\VENORDM1
modi report report\VENPRO01
modi report report\venpro01X
modi report report\VENPRO02
modi report report\VENPRO03
modi report report\VENQTALI
modi report report\VENSOC1
modi report report\VENVALLI
modi report report\VERBOBSPA
modi report report\verifipdainv
modi report report\VERS000
modi report report\VETTFATT
modi report report\VVAVERIF



modi report report\BOLPJITA
modi report report\FATPJEUR
modi report report\OFFPJEUR
modi report report\ORDPJEUR
modi report report\ORFPJEUR
modi report report\FAPPJEUR