
-- TEST REGISTRAZIONE 1953

SELECT MOV_SYSDOC,* FROM INDICE WHERE MOV_ANNO = '2022' AND MOV_NREGIS = '1953'
SELECT * FROM ATTACHMENTS WHERE TIPO = 'CGE' AND IDDOCUMENTO = '_6CG0O9N9Y'

SELECT * FROM INDICE_XML WHERE MOV_SYSDOC = '_6CG0O9N9Y'

SELECT MOV_SYSDOC,* FROM INDICE WHERE MOV_SYSDOC = '_6CG0O9N9Y' ORDER BY MOV_NREGIS



SELECT * FROM ATTACHMENTS WHERE  TIPO = 'CGE' AND IDDOCUMENTO NOT IN (SELECT MOV_SYSDOC FROM INDICE)



-- TEST DI INSERIMENTO PRIME NOTE E SUCCEZZIVE MODIFICHE

SELECT MOV_NUMPRO,MOV_SYSDOC,* FROM INDICE WHERE MOV_ANNO < '2019' ORDER BY MOV_ANNO

SELECT MOV_NUMPRO,MOV_SYSDOC,* FROM INDICE WHERE MOV_DTREG = '2022/06/27' ORDER BY MOV_ANNO 


SELECT MOV_NUMPRO AS _NUMPRO,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6D80RFBID      ' ORDER BY MOV_NUMPRO,MOV_SEQUEN
SELECT MOV_NUMPRO,MOV_SYSDOC,* FROM INDICE WHERE MOV_NUMPRO = '_6D80RFBID      ' ORDER BY MOV_ANNO 
SELECT IDDOCUMENTO,* FROM ATTACHMENTS WHERE IDDOCUMENTO = '_6D80MNYHO'  

SELECT MOV_SYSDOC,* FROM INDICE WHERE MOV_SYSDOC = '_6D80MNYHO' ORDER BY MOV_NREGIS



SELECT MOV_NUMPRO AS _NUMPRO,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6D80XQJLJ' ORDER BY MOV_NUMPRO,MOV_SEQUEN
SELECT MOV_NUMPRO,MOV_SYSDOC,* FROM INDICE WHERE MOV_NUMPRO = '_6D80XQJLJ' ORDER BY MOV_ANNO 
SELECT IDDOCUMENTO,* FROM ATTACHMENTS WHERE IDDOCUMENTO = '_6D80XQHTM'  


SELECT MOV_NUMPRO AS _NUMPRO,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6D80XR8GA      ' ORDER BY MOV_NUMPRO,MOV_SEQUEN
SELECT MOV_NUMPRO,MOV_SYSDOC,* FROM INDICE WHERE MOV_NUMPRO = '_6D80XR8GA      ' ORDER BY MOV_ANNO 
SELECT IDDOCUMENTO,* FROM ATTACHMENTS WHERE IDDOCUMENTO = '_6D80XR8GA   '  