SELECT ART_DESRID,* FROM U_ART_PR WHERE ART_SHOWPES=1 ORDER BY ART_CODPRI
SELECT ART_CODGMI,* FROM U_ART_AN WHERE ART_CODGMI < '003001004' 
SELECT ART_CODGMI,* FROM U_ART_AN WHERE ART_CODGMI <> '' 

--UPDATE U_ART_AN SET ART_CODGMI = '' WHERE ID_UNIQUE = '09B5CEB5-ACC5-4759-8A13-C9308A735F5B' 
SELECT ART_CODGMI,* FROM U_ART_PR JOIN U_ART_AN ON U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND U_ART_AN.ART_CODGMI <> '' -- GROUP BY SUBSTRING(U_ART_AN.ART_CODGMI,1,3)
SELECT * FROM U_ART_PR JOIN U_ART_AN ON U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND U_ART_AN.ART_CODGMI <> ''  



	SELECT
		PR.ART_CODPRI AS ART_CODPRI,
		PR.ART_DESCR AS ART_DESCR,
		PR.ART_DESRID AS ART_DESRID,
		PR.ART_UNIMIS AS ART_UNIMIS,
		AN.ART_CODGMI AS ART_CODGMI
	FROM U_ART_PR AS PR
	JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	WHERE AN.ART_CODGMI <> ''
	ORDER BY AN.ART_CODGMI

--SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'GMI'
--SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'GMI' AND CODICE > 'GMI003001003'
--DELETE FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'GMI' AND CODICE > 'GMI003001003'
--DELETE FROM PARA WHERE SUBSTRING(CODICE,1,6) = 'GMI000'