SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD,
    PAR_TMOV,
    PAR_FATT 
FROM PART_CLI
WHERE PAR_NPROG <> '100' and par_codcli = '1010200000010' and par_npart = '97575'
ORDER BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD



SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD, 
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO
FROM (
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD, 
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_CLI
WHERE PAR_NPROG <> '100' and par_codcli = '1010200000001' and par_npart = '111003') AS T1
GROUP BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD
ORDER BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD




SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD, 
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO
FROM (
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD, 
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_CLI
WHERE PAR_NPROG <> '100' ) AS T1
GROUP BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD
ORDER BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD

