DELETE FROM U_MAG_AN
DELETE FROM U_MAG_AR
DELETE FROM U_MAG_CA
DELETE FROM U_MAG_CL
DELETE FROM U_MAG_CP
DELETE FROM U_MAG_DA
DELETE FROM U_MAG_DF
DELETE FROM U_MAG_DM
DELETE FROM U_MAG_DM 
DELETE FROM U_MAG_GG
DELETE FROM U_MAG_GS
DELETE FROM U_MAG_IN
DELETE FROM U_MAG_MA
DELETE FROM U_MAG_MF
DELETE FROM U_MAG_MO
DELETE FROM U_MAG_MS
DELETE FROM U_MAG_PR
DELETE FROM U_MAG_RI
DELETE FROM U_MAG_SA
DELETE FROM U_MAG_SS

DELETE FROM U_BFO_TT
DELETE FROM U_BFO_DD
DELETE FROM U_BFO_LE
DELETE FROM U_BFO_DL

DELETE FROM U_ORD_TT
DELETE FROM U_ORD_DD

DELETE FROM U_ORF_TT
DELETE FROM U_ORF_DD

DELETE FROM U_BOL_TT
DELETE FROM U_BOL_DD
DELETE FROM U_BOL_LE
DELETE FROM U_BOL_RE


DELETE FROM U_VEN_CL

DELETE FROM U_FOR_PR

DELETE FROM U_FAB_CL





