
-- ELIMINA TUTTO IL FATTURABILE PER STUDI PROFESSIONALI GENERATO, ALLINEANDO ANCHE LE TABELLE CORRELATE

DELETE FROM FATTURABST

UPDATE CONTRST_DL SET FLGFATTURAB = 0
UPDATE ATTIVITANC SET FLGFATTURAB = 0
UPDATE ATTIVEXCED SET FLGFATTURAB = 0
--UPDATE TELEFONATE SET FLGFATTURAB = 0