/* RIQUADRO 1 (MAG.001) */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '001' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG    

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_SA WHERE MAG_CODMAG = '001' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_SA WHERE MAG_CODMAG = '001' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* CARICHI SUL MAG. 001 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'BFO') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'BFA') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'BFO') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'BFA') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'BFO') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'BFA') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* SCARICHI SUL MAG. 001 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '20S' OR MOV_TOP = '30S' OR MOV_TOP = '19S' OR MOV_TOP = '21S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '20S' OR MOV_TOP = '30S' OR MOV_TOP = '19S' OR MOV_TOP = '21S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = '20S' OR MOV_TOP = '30S' OR MOV_TOP = '19S' OR MOV_TOP = '21S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI POSITIVE SUL MAG. 001 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI NEGATIVE SUL MAG. 001 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '001' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '001' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_GG WHERE MAG_CODMAG = '001' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_GG WHERE MAG_CODMAG = '001' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* RIQUADRO 1 (MAG.002) */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '002' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG    

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_SA WHERE MAG_CODMAG = '002' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_SA WHERE MAG_CODMAG = '002' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* CARICHI SUL MAG. 002 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '20C' OR MOV_TOP = '50C' OR MOV_TOP = '90C' OR MOV_TOP = '11C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '20C' OR MOV_TOP = '50C' OR MOV_TOP = '90C' OR MOV_TOP = '11C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '20C' OR MOV_TOP = '50C' OR MOV_TOP = '90C' OR MOV_TOP = '11C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* SCARICHI DAL MAG. 002 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '23S' OR MOV_TOP = '60S' OR MOV_TOP = '39S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '23S' OR MOV_TOP = '60S' OR MOV_TOP = '39S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '23S' OR MOV_TOP = '60S' OR MOV_TOP = '39S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI POSITIVE SUL MAG. 002 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI NEGATIVE SUL MAG. 002 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '002' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '002' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_GG WHERE MAG_CODMAG = '002' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_GG WHERE MAG_CODMAG = '002' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* RIQUADRO 2 (MAG.004) */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '004' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG    

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_SA WHERE MAG_CODMAG = '004' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_SA WHERE MAG_CODMAG = '004' AND MAG_AAAAMM = '2005/01' AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* CARICHI SUL MAG. 004 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '60C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '60C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '60C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* SCARICHI DAL MAG. 004 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '25S' OR MOV_TOP = '75S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '25S' OR MOV_TOP = '75S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = '25S' OR MOV_TOP = '75S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* CARICHI DA PRODUZ.SPALMATURA SUL MAG. 004 */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'SPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'AV-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'SPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'AV-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'SPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'AV-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* SCARICHI DA PRODUZ.SPALMATURA SUL MAG. 004 */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'SPS') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'AV+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'SPS') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'AV+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'SPS') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 
SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'AV+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI POSITIVE SUL MAG. 004 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* RETTIFICHE INVENTARIALI NEGATIVE SUL MAG. 004 NEL PERIODO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGBOB FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT <> '001' AND MOV_CODMAT <> '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

SELECT MOV_CODMAG,SUM(MOV_QTAKG) AS TOTKGADE FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '004' AND MOV_CODMAT = '004'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 


/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '004' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGBOB FROM U_MAG_GG WHERE MAG_CODMAG = '004' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT <> '001' AND MAG_CODMAT <> '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

SELECT MAG_CODMAG,SUM(MAG_QTAKG) AS TOTKGADE FROM U_MAG_GG WHERE MAG_CODMAG = '004' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0 AND MAG_CODMAT = '004'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 


/* RIQUADRO 3 */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '006' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG    

/* CARICHI SUL MAG. S.L. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '19C' OR MOV_TOP = '75C' OR MOV_TOP = '00C' OR MOV_TOP = '12C' OR MOV_TOP = '35C' OR MOV_TOP = '18C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI SUL MAG. S.L. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '26S' OR MOV_TOP = '13S' OR MOV_TOP = '28S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI POSITIVE SUL MAG. S.L. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI NEGATIVE SUL MAG. S.L. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '006' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

/* RIQUADRO 4 */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '008' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG   

/* CARICHI SUL REPARTO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '39C' OR MOV_TOP = '13C' OR MOV_TOP = '34C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI DAL REPARTO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '11S' OR MOV_TOP = '31S' OR MOV_TOP = '33S' OR MOV_TOP = '32S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE RIBOBINATURA (RPC) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'RPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE RIBOBINATURA (RA-) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'RA-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI DA PRODUZIONE RIBOBINATURA (RPS) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'RPS') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI DA PRODUZIONE RIBOBINATURA (RA+) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'RA+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE TAGLIO (TPC) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE TAGLIO (TA-) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TA-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI DA PRODUZIONE TAGLIO (TPS) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TPS') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI DA PRODUZIONE TAGLIO (TA+) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TA+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI POSITIVE SUL REPARTO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI NEGATIVE SUL REPARTO */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '008'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '008' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 

/* RIQUADRO 5 */-------------------------------------------------------------------------------------------

/* GIACENZA ALLA DATA DAL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_SA WHERE MAG_CODMAG = '010' AND MAG_AAAAMM = '2005/01'
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG  

/* CARICHI SUL MAG. P.F. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '28C' OR MOV_TOP = '33C') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SCARICHI SUL MAG. P.F. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '35S' OR MOV_TOP = '36S') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE TAGLIO (TPC) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TPC') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* CARICHI DA PRODUZIONE TAGLIO (TA-) */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'TA-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI POSITIVE SUL MAG. P.F. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN+') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI NEGATIVE SUL MAG. P.F. */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = 'IN-') AND MOV_DTREGI > '2005/01/31' AND MOV_DTREGI <= '2005/03/14' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* GIACENZA ALLA DATA AL */
SELECT MAG_CODMAG,SUM(MAG_QTAMQ) AS TOTMQ FROM U_MAG_GG WHERE MAG_CODMAG = '010' AND MAG_DATAGG <> space(10) AND MAG_GIACEN > 0
   GROUP BY MAG_CODMAG ORDER BY MAG_CODMAG 
