/* 
********************************************************************************
SCRIPT PER INIZIALIZZARE AGGANCIO E PROGRESSIVI NUMERO LOTTO INTERNO (ANNO 2006)
********************************************************************************
*/
SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'NUM' AND SUBSTRING(CODICE,7,2) = '  ' ORDER BY CODICE
SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,6) = 'NUMBOB' AND SUBSTRING(CODICE,7,1) <> ' ' AND SUBSTRING(CODICE,8,1) = ' ' ORDER BY CODICE
UPDATE PARA SET LIBERA = '6000000000' WHERE SUBSTRING(CODICE,1,3) = 'NUM' AND SUBSTRING(CODICE,7,2) = '  '
UPDATE PARA SET LIBERA = '      0' WHERE SUBSTRING(CODICE,1,6) = 'NUMBOB' AND SUBSTRING(CODICE,7,1) <> ' ' AND SUBSTRING(CODICE,8,1) = ' '
