select MOV_ORAMOV,MOV_CODMAG,mov_dtregi,mov_segno,MOV_UM,mov_qtamov,mov_qtamq,mov_qtakg,MOV_LUNGHE,MOV_ALTEZZ,mov_top,T2.ART_CODPRI,T2.ART_DESCR,T2.ART_CODIMB,T2.ART_DESIMB,T2.ART_UMMAGA,T2.ART_UNIMIS,T2.ART_PRZVEN,T2.ART_CSTMAT,T1.* FROM u_mag_mo AS T1 INNER join (SELECT ART_CODPRI,ART_DESCR,ART_CODIMB,ART_DESIMB,ART_UMMAGA,ART_UNIMIS,ART_PRZVEN,ART_CSTMAT FROM u_art_pr) AS T2 on T1.mov_anaart = T2.art_codpri where MOV_CODSOC = '01' AND MOV_CODMAT = MOV_CODMAT AND MOV_CODCOL = MOV_CODCOL AND MOV_SPESSO = MOV_SPESSO AND MOV_ALTEZZ = MOV_ALTEZZ AND MOV_LUNGHE = MOV_LUNGHE AND MOV_ANAART = MOV_ANAART AND MOV_NRLINT = MOV_NRLINT AND MOV_CODMAG = MOV_CODMAG AND MOV_FORNIT = MOV_FORNIT AND MOV_NUMIDE = MOV_NUMIDE  AND MOV_ANNO = MOV_ANNO AND MOV_NUMDOC = MOV_NUMDOC AND MOV_DTDOCU = MOV_DTDOCU AND MOV_TOP = MOV_TOP AND MOV_DTREGI <= '2005/05/31' AND MOV_CODART = 'FILM BL.15000931' order by mov_dtregi,mov_codmag,mov_codart,mov_oramov
select MAG_CODMAG,mag_aaaamm,mag_datsal,mag_giacen,mag_qtamq,mag_qtakg,MAG_LUNGHE,MAG_ALTEZZ,T2.ART_CODPRI,T2.ART_DESCR,T2.ART_CODIMB,T2.ART_DESIMB,T2.ART_UMMAGA,T2.ART_UNIMIS,T2.ART_PRZVEN,T2.ART_CSTMAT,T1.* FROM u_mag_sa AS T1 INNER join (SELECT ART_CODPRI,ART_DESCR,ART_CODIMB,ART_DESIMB,ART_UMMAGA,ART_UNIMIS,ART_PRZVEN,ART_CSTMAT FROM u_art_pr) AS T2 on T1.mag_anaart = T2.art_codpri where mag_codsoc = '01' and mag_codmat = mag_codmat AND mag_codcol = mag_codcol AND mag_spesso = mag_spesso AND mag_altezz = mag_altezz AND mag_lunghe = mag_lunghe AND mag_anaart = mag_anaart AND mag_nrlint = mag_nrlint AND mag_codmag = MAG_CODMAG AND mag_fornit = mag_fornit AND mag_numide = mag_numide AND mag_anno = mag_anno AND mag_aaaamm <= '2005/05' AND MAG_CODART = 'FILM BL.15000931' order by mag_aaaamm,mag_datsal,mag_codmag,mag_codart
SELECT MAG_CODART,MAG_CODMAG,MAG_DATAGG,MAG_GIACEN,MAG_QTAMQ,MAG_QTAKG,MAG_QTAML,MAG_SPESSO,MAG_ALTEZZ,MAG_LUNGHE,MAG_CODMAT,* FROM U_MAG_SA WHERE MAG_NRLINT = 15000931

UPDATE U_MAG_MO SET MOV_UM = 'MQ' WHERE MOV_CODART = 'FILM BL.15000931'
DELETE FROM U_MAG_MO WHERE ID_UNIQUE = 'A04DDB43-0F94-417B-8F5A-602C9DE6FCD7'
UPDATE U_MAG_MO SET MOV_QTAMOV = 8480 WHERE MOV_CODART = 'FILM BL.15000931' AND MOV_LUNGHE = 4000
UPDATE U_MAG_MO SET MOV_QTAMOV = 2120 WHERE MOV_CODART = 'FILM BL.15000931' AND MOV_LUNGHE = 1000
DELETE FROM U_MAG_MO WHERE ID_UNIQUE = '48884069-A0CC-45FE-97CF-02A46C6A2AAC'

UPDATE U_MAG_SA SET MAG_GIACEN = 0 WHERE MAG_CODART = 'FILM BL.15000931' AND MAG_DATSAL = '2005/03/31'
UPDATE U_MAG_SA SET MAG_GIACEN = MAG_QTAMQ WHERE MAG_CODART = 'FILM BL.15000931' AND MAG_DATSAL = '2005/04/30' AND MAG_CODMAG = '002'
UPDATE U_MAG_SA SET MAG_QTAMQ = 0,MAG_QTAKG = 0 WHERE MAG_CODART = 'FILM BL.15000931' AND MAG_DATSAL = '2005/04/30' AND MAG_CODMAG = '004'

DELETE FROM U_MAG_SA WHERE MAG_NRLINT = 15000931 AND MAG_DATAGG = '2005/03/31'
