SELECT ORD_NRBSPP,ORD_QTASPP,* FROM U_ORD_DD ORDER BY DAGGANCIO
SELECT ORD_NRBSPP,ORD_QTASPP,* FROM U_ORD_DL ORDER BY DAGGANCIO
UPDATE U_ORD_DD SET ORD_NRBSPP = 34 WHERE ORD_NRBSPP = 14
UPDATE U_ORD_DD SET ORD_QTASPP = 103020 WHERE ORD_QTASPP = 42420
UPDATE U_ORD_DL SET ORD_NRBSPP = 14 WHERE ORD_NRBSPP < 0
UPDATE U_ORD_DL SET ORD_QTASPP = 42420 WHERE ORD_QTASPP <0
