SELECT ART_UNIMIS,ART_UMMAGA,* FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,3) = 'AN.' ORDER BY ART_CODPRI
UPDATE U_ART_PR SET ART_UNIMIS = 'ML', ART_UMMAGA = 'NR' WHERE SUBSTRING(ART_CODPRI,1,3) = 'AN.' 

