SELECT MAG_CLIENT,MAG_NUMPED,* FROM U_MAG_GG WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50) ORDER BY MAG_DATAGG
UPDATE U_MAG_GG SET MAG_CLIENT = SPACE(50) WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT LIKE 'ISOLPA%'
UPDATE U_MAG_GG SET MAG_NUMORD = SPACE(06) WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_DATORD = SPACE(10) WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_SYSORD = SPACE(10) WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_DATORD = SPACE(10) WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_QTAIMP = 0 WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_GMLIMP = 0 WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)
UPDATE U_MAG_GG SET MAG_GKGIMP = 0 WHERE MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '010' AND MAG_NUMPED = 0 AND MAG_CLIENT = SPACE(50)






