/* CARICHI DI PRODUZIONE   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = '75C' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* ACQUISTI FILM   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = '19C' AND MOV_CODMAG = '006'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* BOLLE DI LAVORAZIONE   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE (MOV_TOP = '13C' AND MOV_CODMAG = '008') OR
                                                              (MOV_TOP = '27C' AND MOV_CODMAG = '009')
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RESI AL MAGAZZINO S.L.   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE ((MOV_TOP = '14C' OR MOV_TOP = '15C') AND MOV_CODMAG = '006') OR
                                                               (MOV_TOP = '17C' AND MOV_CODMAG = '006')
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SEMILAVORATO TAGLIATO SPC   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = 'SPC' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SEMILAVORATO TAGLIATO AV- ANNULLI DI AVANZAMENTO   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = 'AV-' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* SEMILAVORATO SPOSTATO   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE ((MOV_TOP = '33C' OR MOV_TOP = '18C') AND MOV_CODMAG = '010')
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI POSITIVE   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = 'IN+' AND (MOV_CODMAG = '006' OR
   MOV_CODMAG = '010' OR MOV_CODMAG = '007' OR MOV_CODMAG = '011') 
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* RETTIFICHE INVENTARIALI NEGATIVE   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = 'IN-' AND (MOV_CODMAG = '006' OR
   MOV_CODMAG = '010' OR MOV_CODMAG = '007' OR MOV_CODMAG = '011') 
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* VENDITE   */
SELECT MOV_CODMAG,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO WHERE MOV_TOP = '001' AND MOV_CODMAG = '010'
   GROUP BY MOV_CODMAG ORDER BY MOV_CODMAG 

/* TOP USATI   */
SELECT MOV_CODMAG,MOV_TOP,SUM(MOV_QTAMQ) AS TOTMQ FROM U_MAG_MO 
   GROUP BY MOV_CODMAG,MOV_TOP ORDER BY MOV_CODMAG,MOV_TOP 


