DELETE FROM U_OFF_TT
DELETE FROM U_OFF_DD
DELETE FROM U_ORD_TT
DELETE FROM U_ORD_DD
DELETE FROM U_ORF_TT
DELETE FROM U_ORF_DD
DELETE FROM U_BOL_TT
DELETE FROM U_BOL_DD
DELETE FROM U_FAT_TT
DELETE FROM U_FAT_DD
DELETE FROM U_FAP_TT
DELETE FROM U_FAP_DD
DELETE FROM U_BFO_TT
DELETE FROM U_BFO_DD
DELETE FROM U_PRB_TT
DELETE FROM U_PRB_DD
DELETE FROM U_ORF_PO
DELETE FROM U_ORF_DT
DELETE FROM U_ORF_CO
DELETE FROM U_BOL_RE
DELETE FROM U_CON_TR
DELETE FROM U_PDV_CA
DELETE FROM U_CAN_CA
DELETE FROM U_PDV_OP
DELETE FROM U_PDV_SA
DELETE FROM U_PDV_SC
DELETE FROM U_PNC_BU
DELETE FROM U_PNC_SA
DELETE FROM U_PDV_AU
DELETE FROM U_RIC_VA
DELETE FROM U_IVA_CO
DELETE FROM U_PDV_CN
DELETE FROM U_PDV_CD
DELETE FROM U_CNT_AN
DELETE FROM U_LEG_DO
DELETE FROM U_FOR_PR
DELETE FROM U_PRO_OR




