
--****** TABELLE PRODUZIONE *********************************
DELETE FROM U_PRD_D1
DELETE FROM U_PRD_D2
DELETE FROM U_PRD_D3
DELETE FROM U_PRD_D4
DELETE FROM U_PRD_D5
--DELETE FROM U_PRD_HY
DELETE FROM U_PRD_DR
DELETE FROM U_PRD_PK
DELETE FROM U_PRD_DS


--****** IMPEGNI ORDINI FORNITORI E BFO *********************************
UPDATE U_ORF_DD SET PR1_NUMPRG 	= ''
UPDATE U_ORF_DD SET PJ_PRGPRD1 	= '' 
UPDATE U_ORF_DD SET SAV_NUMPRG 	= ''
UPDATE U_ORF_DD SET SAV_PJ_PRD1	= '' 

UPDATE U_ORF_DL SET PR1_NUMPRG 	= ''
UPDATE U_ORF_DL SET PJ_PRGPRD1 	= '' 
UPDATE U_ORF_DL SET PJ_PRGPRD2 	= '' 
UPDATE U_ORF_DL SET PJ_PRGPRD3 	= '' 
UPDATE U_ORF_DL SET SAV_NUMPRG 	= ''
UPDATE U_ORF_DL SET SAV_PJ_PRD1	= '' 
UPDATE U_ORF_DL SET SAV_PJ_PRD2	= '' 
UPDATE U_ORF_DL SET SAV_PJ_PRD3	= '' 

UPDATE U_BFO_DL SET PR1_NUMPRG 	= ''
UPDATE U_BFO_DL SET PJ_PRGPRD1 	= '' 
UPDATE U_BFO_DL SET PJ_PRGPRD2 	= '' 
UPDATE U_BFO_DL SET PJ_PRGPRD3 	= '' 


--****** IMPEGNI ORDINI CLIENTI *********************************
UPDATE U_ORD_DD SET ORD_PRODOT 	= 0 
UPDATE U_ORD_DD SET ORD_INPROD 	= 0 
UPDATE U_ORD_DD SET ORD_DARIV 	= 0 
UPDATE U_ORD_DD SET ORD_DAPROD 	= 0 



--****** SPRENOTAZIONE GIACENZE *********************************
UPDATE U_MAG_GG SET MAG_PRENOT = 0