
        SELECT
                T1.CONTOCONT ,
                T2.DESRISORSA,
                T1.CODCAUSALE,
                T1.IMPORTO,
                T2.CODRISORSA ,
                T2.ABI,
                T2.CAB,
                T2.CC
        FROM    ((select CODCAUSALE,CODRIS_DA AS CONTOCONT ,SUM(IMPORTO) AS IMPORTO from (SELECT * FROM PIANOP_MO WHERE DAGGANCIO NOT IN (SELECT TAGGANCIO AS DAGGANCIO FROM PIANOP_TT WHERE PPA_FLGTRA=1)) AS T1 WHERE CODCAUSALE !='USC_TRAS'  AND CODRIS_DA !='' GROUP BY CODRIS_DA,CODCAUSALE)
                UNION
                (select CODCAUSALE,CODRIS_DA AS CONTOCONT  ,SUM(IMPORTO)*-1 AS IMPORTO from (SELECT * FROM PIANOP_MO WHERE DAGGANCIO NOT IN (SELECT TAGGANCIO AS DAGGANCIO FROM PIANOP_TT WHERE PPA_FLGTRA=1)) AS T1 WHERE CODCAUSALE ='USC_TRAS' AND  CODRIS_DA !='' GROUP BY CODRIS_DA,CODCAUSALE)
                UNION
                (select CODCAUSALE,CODRIS_A  AS CONTOCONT  ,SUM(IMPORTO) AS IMPORTO from (SELECT * FROM PIANOP_MO WHERE DAGGANCIO NOT IN (SELECT TAGGANCIO AS DAGGANCIO FROM PIANOP_TT WHERE PPA_FLGTRA=1)) AS T1 WHERE CODCAUSALE ='USC_TRAS' AND  CODRIS_DA !='' GROUP BY CODRIS_A,CODCAUSALE)) AS T1
        INNER JOIN (
        SELECT  CONTOCONT,
                CODRISORSA,
                DESRISORSA,
                ABI,
                CAB,
                CC
        FROM PIANOP_SA
        GROUP BY
                CONTOCONT,
                CODRISORSA,
                DESRISORSA,
                ABI,
                CAB,
                CC )AS T2
        ON T1.CONTOCONT= T2.CONTOCONT


