
SELECT PIANOP_TT.TNUMERO,CODFOR,DTSCAD,NPART FROM PIANOP_TT INNER JOIN PIANOP_DD ON TAGGANCIO = DAGGANCIO WHERE CODFOR+DTSCAD+STR(NPART) NOT IN ( SELECT
PAR_CODCLI+PAR_DTSCAD+STR(PAR_NPART) FROM PART_FOR) AND PPA_FLGTRA=0 AND CODFOR LIKE '02%'
ORDER BY NPART

