SELECT * FROM PART_CLI WHERE PAR_COSATRATTA IS NULL ORDER BY PAR_ANNO

UPDATE PART_CLI 
SET PAR_CODACQ = '',
	PAR_TIPOCONTRATTO = '',
	PAR_FORMAPAGAMENTO = '',
	PAR_GRADOIMPORTANZA = '',
	PAR_COSATRATTA = '',
	PAR_PRIPAGA = ''
WHERE PAR_COSATRATTA IS NULL