/*
*** NUOVO CAMPO PER GESTIONE RIFERIMENTI AMMINISTRATIVI PER LA FATTURAZIONE ELETTRONICA DA RIPORTARE SULLE FATTURE
*/


ALTER TABLE [DBO].[U_FAT_TT] ADD 
	ORD_RIFAMMFE varchar(150) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FAT_TT_ORD_RIFAMMFE] DEFAULT ('')
GO
