/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_MAG_MO] ADD 
	 MOV_CODMAT varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DESMAT varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SPESSO numeric(3) NULL,
	 MOV_ALTEZZ numeric(5) NULL,
	 MOV_LUNGHE numeric(6) NULL,
	 MOV_NRLINT numeric(6) NULL,
	 MOV_NRDBOB numeric(6) NULL,
	 MOV_QTAKG numeric(11,2) NULL,
	 MOV_QTAMQ numeric(11,2) NULL,
	 MOV_QTAML numeric(11,2) NULL,
	 MOV_CDAFOR varchar(20) COLLATE Latin1_General_CI_AS NULL,
	 MOV_OINFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_PINFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DTPFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_TRAFOR varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_NBAFOR numeric(11,2) NULL,
	 MOV_BDAFOR numeric(11,2) NULL,
	 MOV_BALFOR numeric(11,2) NULL,
	 MOV_PNKFOR numeric(11,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_CODMAT] DEFAULT ('') FOR [MOV_CODMAT],
	CONSTRAINT [DF_U_MAG_MO_MOV_DESMAT] DEFAULT ('') FOR [MOV_DESMAT],
	CONSTRAINT [DF_U_MAG_MO_MOV_SPESSO] DEFAULT (0) FOR [MOV_SPESSO],
	CONSTRAINT [DF_U_MAG_MO_MOV_ALTEZZ] DEFAULT (0) FOR [MOV_ALTEZZ],
	CONSTRAINT [DF_U_MAG_MO_MOV_LUNGHE] DEFAULT (0) FOR [MOV_LUNGHE],
	CONSTRAINT [DF_U_MAG_MO_MOV_NRLINT] DEFAULT (0) FOR [MOV_NRLINT],
	CONSTRAINT [DF_U_MAG_MO_MOV_NRDBOB] DEFAULT (0) FOR [MOV_NRDBOB],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAKG] DEFAULT (0) FOR [MOV_QTAKG],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAMQ] DEFAULT (0) FOR [MOV_QTAMQ],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAML] DEFAULT (0) FOR [MOV_QTAML],
	CONSTRAINT [DF_U_MAG_MO_MOV_CDAFOR] DEFAULT ('') FOR [MOV_CDAFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_OINFOR] DEFAULT ('') FOR [MOV_OINFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_PINFOR] DEFAULT ('') FOR [MOV_PINFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_DTPFOR] DEFAULT ('') FOR [MOV_DTPFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_TRAFOR] DEFAULT ('') FOR [MOV_TRAFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_NBAFOR] DEFAULT (0) FOR [MOV_NBAFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_BDAFOR] DEFAULT (0) FOR [MOV_BDAFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_BALFOR] DEFAULT (0) FOR [MOV_BALFOR],
	CONSTRAINT [DF_U_MAG_MO_MOV_PNKFOR] DEFAULT (0) FOR [MOV_PNKFOR]
go

UPDATE U_MAG_MO SET MOV_CODMAT = SPACE(3)
UPDATE U_MAG_MO SET MOV_DESMAT = SPACE(30)
UPDATE U_MAG_MO SET MOV_SPESSO = 0
UPDATE U_MAG_MO SET MOV_ALTEZZ = 0
UPDATE U_MAG_MO SET MOV_LUNGHE = 0
UPDATE U_MAG_MO SET MOV_NRLINT = 0
UPDATE U_MAG_MO SET MOV_NRDBOB = 0
UPDATE U_MAG_MO SET MOV_QTAKG = 0
UPDATE U_MAG_MO SET MOV_QTAMQ = 0
UPDATE U_MAG_MO SET MOV_QTAML = 0
UPDATE U_MAG_MO SET MOV_CDAFOR = SPACE(20)
UPDATE U_MAG_MO SET MOV_OINFOR = SPACE(10)
UPDATE U_MAG_MO SET MOV_PINFOR = SPACE(10)
UPDATE U_MAG_MO SET MOV_DTPFOR = SPACE(10)
UPDATE U_MAG_MO SET MOV_TRAFOR = SPACE(03)
UPDATE U_MAG_MO SET MOV_NBAFOR = 0
UPDATE U_MAG_MO SET MOV_BDAFOR = 0
UPDATE U_MAG_MO SET MOV_BALFOR = 0
UPDATE U_MAG_MO SET MOV_PNKFOR = 0


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_MAG_CA] ADD 
	 MOV_CODMAT varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DESMAT varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SPESSO numeric(3) NULL,
	 MOV_ALTEZZ numeric(5) NULL,
	 MOV_LUNGHE numeric(6) NULL,
	 MOV_NRLINT numeric(6) NULL,
	 MOV_NRDBOB numeric(6) NULL,
	 MOV_QTAKG numeric(11,2) NULL,
	 MOV_QTAMQ numeric(11,2) NULL,
	 MOV_QTAML numeric(11,2) NULL,
	 MOV_CDAFOR varchar(20) COLLATE Latin1_General_CI_AS NULL,
	 MOV_OINFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_PINFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DTPFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_TRAFOR varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_NBAFOR numeric(11,2) NULL,
	 MOV_BDAFOR numeric(11,2) NULL,
	 MOV_BALFOR numeric(11,2) NULL,
	 MOV_PNKFOR numeric(11,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CA_MOV_CODMAT] DEFAULT ('') FOR [MOV_CODMAT],
	CONSTRAINT [DF_U_MAG_CA_MOV_DESMAT] DEFAULT ('') FOR [MOV_DESMAT],
	CONSTRAINT [DF_U_MAG_CA_MOV_SPESSO] DEFAULT (0) FOR [MOV_SPESSO],
	CONSTRAINT [DF_U_MAG_CA_MOV_ALTEZZ] DEFAULT (0) FOR [MOV_ALTEZZ],
	CONSTRAINT [DF_U_MAG_CA_MOV_LUNGHE] DEFAULT (0) FOR [MOV_LUNGHE],
	CONSTRAINT [DF_U_MAG_CA_MOV_NRLINT] DEFAULT (0) FOR [MOV_NRLINT],
	CONSTRAINT [DF_U_MAG_CA_MOV_NRDBOB] DEFAULT (0) FOR [MOV_NRDBOB],
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAKG] DEFAULT (0) FOR [MOV_QTAKG],
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAMQ] DEFAULT (0) FOR [MOV_QTAMQ],
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAML] DEFAULT (0) FOR [MOV_QTAML],
	CONSTRAINT [DF_U_MAG_CA_MOV_CDAFOR] DEFAULT ('') FOR [MOV_CDAFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_OINFOR] DEFAULT ('') FOR [MOV_OINFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_PINFOR] DEFAULT ('') FOR [MOV_PINFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_DTPFOR] DEFAULT ('') FOR [MOV_DTPFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_TRAFOR] DEFAULT ('') FOR [MOV_TRAFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_NBAFOR] DEFAULT (0) FOR [MOV_NBAFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_BDAFOR] DEFAULT (0) FOR [MOV_BDAFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_BALFOR] DEFAULT (0) FOR [MOV_BALFOR],
	CONSTRAINT [DF_U_MAG_CA_MOV_PNKFOR] DEFAULT (0) FOR [MOV_PNKFOR]
go

UPDATE U_MAG_CA SET MOV_CODMAT = SPACE(3)
UPDATE U_MAG_CA SET MOV_DESMAT = SPACE(30)
UPDATE U_MAG_CA SET MOV_SPESSO = 0
UPDATE U_MAG_CA SET MOV_ALTEZZ = 0
UPDATE U_MAG_CA SET MOV_LUNGHE = 0
UPDATE U_MAG_CA SET MOV_NRLINT = 0
UPDATE U_MAG_CA SET MOV_NRDBOB = 0
UPDATE U_MAG_CA SET MOV_QTAKG = 0
UPDATE U_MAG_CA SET MOV_QTAMQ = 0
UPDATE U_MAG_CA SET MOV_QTAML = 0
UPDATE U_MAG_CA SET MOV_CDAFOR = SPACE(20)
UPDATE U_MAG_CA SET MOV_OINFOR = SPACE(10)
UPDATE U_MAG_CA SET MOV_PINFOR = SPACE(10)
UPDATE U_MAG_CA SET MOV_DTPFOR = SPACE(10)
UPDATE U_MAG_CA SET MOV_TRAFOR = SPACE(03)
UPDATE U_MAG_CA SET MOV_NBAFOR = 0
UPDATE U_MAG_CA SET MOV_BDAFOR = 0
UPDATE U_MAG_CA SET MOV_BALFOR = 0
UPDATE U_MAG_CA SET MOV_PNKFOR = 0

