
ALTER TABLE [DBO].[U_AZI_PA] ADD 
	AZI_DDTQTADOPPIE  BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_DDTQTADOPPIE] DEFAULT (0) FOR [AZI_DDTQTADOPPIE]
GO

UPDATE U_AZI_PA SET AZI_DDTQTADOPPIE = 1
