
ALTER TABLE [dbo].[L_BOL_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_BFO_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_BOL_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_FAP_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_OFF_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go

ALTER TABLE [dbo].[U_ORF_DD] ALTER COLUMN 
	ORD_SEQUEN numeric(10,0)
go
