
/* 
*********************************
CORREZIONE VINCOLI CAMPI U_ART_AN
*********************************
*/
ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_PRZVENWEB]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTMST]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTM1]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTM2]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTM3]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTM4]
go

ALTER TABLE [dbo].[U_ART_AN] DROP CONSTRAINT [DF_U_ART_AN_ART_LDTM5]
go


ALTER TABLE [dbo].[U_ART_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_AN_ART_PRZVENWEB] DEFAULT (0) FOR [ART_PRZVENWEB],
	CONSTRAINT [DF_U_ART_AN_ART_LDTMST] DEFAULT (0) FOR [ART_LDTMST],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM1] DEFAULT (0) FOR [ART_LDTM1],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM2] DEFAULT (0) FOR [ART_LDTM2],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM3] DEFAULT (0) FOR [ART_LDTM3],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM4] DEFAULT (0) FOR [ART_LDTM4],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM5] DEFAULT (0) FOR [ART_LDTM5]
go
