/*
*** NUOVI CAMPI PER GESTIONE INVIO PRIVACY GDPR
*/

ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_FLGDPR bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_FLGDPR] DEFAULT (0),
	CLI_DTGDPR varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_DTGDPR] DEFAULT ('')
GO
