
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_NUMPCK varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR5_DATPCK varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR5_ORAPCK varchar(8) COLLATE Latin1_General_CI_AS NULL,
	PR5_NUMBAN numeric(10) NULL,
	PR5_FLGDDT bit NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_NUMPCK] DEFAULT ('') FOR [PR5_NUMPCK],
	CONSTRAINT [DF_U_PRD_D5_PR5_DATPCK] DEFAULT ('') FOR [PR5_DATPCK],
	CONSTRAINT [DF_U_PRD_D5_PR5_ORAPCK] DEFAULT ('') FOR [PR5_ORAPCK],
	CONSTRAINT [DF_U_PRD_D5_PR5_NUMBAN] DEFAULT (0) FOR [PR5_NUMBAN],
	CONSTRAINT [DF_U_PRD_D5_PR5_FLGDDT] DEFAULT (0) FOR [PR5_FLGDDT]
go

UPDATE U_PRD_D5 SET PR5_NUMPCK = ''
UPDATE U_PRD_D5 SET PR5_DATPCK = ''
UPDATE U_PRD_D5 SET PR5_ORAPCK = ''
UPDATE U_PRD_D5 SET PR5_NUMBAN = 0
UPDATE U_PRD_D5 SET PR5_FLGDDT = 0