/*
*** NUOVO CAMPO PER GESTIONE ULTIMO FILE XML GENERATO SULLE FATTURE
*/


ALTER TABLE [DBO].[U_FAT_TT] ADD 
	ORD_FILEXML varchar(254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FAT_TT_ORD_FILEXML] DEFAULT ('')
GO
