

ALTER TABLE [dbo].[U_BOL_DD] ADD 
	 ORS_NUMDDT varchar(6) COLLATE Latin1_General_CI_AS NULL,
	 ORS_DATDDT varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORS_ANNDDT varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 ORS_AGGDDT varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_SYSDDT varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_NRBRES numeric(10) NULL,
	 ORD_QTARES numeric(10,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_BOL_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_DD_ORS_NUMDDT] DEFAULT ('') FOR [ORS_NUMDDT],
	CONSTRAINT [DF_U_BOL_DD_ORS_DATDDT] DEFAULT ('') FOR [ORS_DATDDT],
	CONSTRAINT [DF_U_BOL_DD_ORS_ANNDDT] DEFAULT ('') FOR [ORS_ANNDDT],
	CONSTRAINT [DF_U_BOL_DD_ORS_AGGDDT] DEFAULT ('') FOR [ORS_AGGDDT],
	CONSTRAINT [DF_U_BOL_DD_ORD_SYSDDT] DEFAULT ('') FOR [ORD_SYSDDT],
	CONSTRAINT [DF_U_BOL_DD_ORD_NRBRES] DEFAULT (0) FOR [ORD_NRBRES],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTARES] DEFAULT (0) FOR [ORD_QTARES]
go

UPDATE U_BOL_DD SET ORS_NUMDDT = SPACE(06)
UPDATE U_BOL_DD SET ORS_DATDDT = SPACE(10)
UPDATE U_BOL_DD SET ORS_ANNDDT = SPACE(04)
UPDATE U_BOL_DD SET ORS_AGGDDT = SPACE(10)
UPDATE U_BOL_DD SET ORD_SYSDDT = SPACE(10)
UPDATE U_BOL_DD SET ORD_NRBRES = 0
UPDATE U_BOL_DD SET ORD_QTARES = 0

