/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_ART_PR] ADD 
	 ART_CODPAC varchar(16) COLLATE Latin1_General_CI_AS NULL,
	 ART_DESPAC varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 ART_TIPCOM varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 ART_DESCOM varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 ART_SERNUM varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 ART_NOTCOM varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 ART_FLGMOD varchar(01) COLLATE Latin1_General_CI_AS NULL,
	 ART_LEGSYS varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ART_FLGMIM [bit] NULL,
	 ART_CODOPE varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ART_DESOPE varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_CODPAC] DEFAULT ('') FOR [ART_CODPAC],
	CONSTRAINT [DF_U_ART_PR_ART_DESPAC] DEFAULT ('') FOR [ART_DESPAC],
	CONSTRAINT [DF_U_ART_PR_ART_TIPCOM] DEFAULT ('') FOR [ART_TIPCOM],
	CONSTRAINT [DF_U_ART_PR_ART_DESCOM] DEFAULT ('') FOR [ART_DESCOM],
	CONSTRAINT [DF_U_ART_PR_ART_SERNUM] DEFAULT ('') FOR [ART_SERNUM],
	CONSTRAINT [DF_U_ART_PR_ART_NOTCOM] DEFAULT ('') FOR [ART_NOTCOM],
	CONSTRAINT [DF_U_ART_PR_ART_FLGMOD] DEFAULT ('') FOR [ART_FLGMOD],
	CONSTRAINT [DF_U_ART_PR_ART_LEGSYS] DEFAULT ('') FOR [ART_LEGSYS],
	CONSTRAINT [DF_U_ART_PR_ART_FLGMIM] DEFAULT (0) FOR [ART_FLGMIM],
	CONSTRAINT [DF_U_ART_PR_ART_CODOPE] DEFAULT ('') FOR [ART_CODOPE],
	CONSTRAINT [DF_U_ART_PR_ART_DESOPE] DEFAULT ('') FOR [ART_DESOPE]
go

UPDATE U_ART_PR SET ART_CODPAC = SPACE(16)
UPDATE U_ART_PR SET ART_DESPAC = SPACE(50)
UPDATE U_ART_PR SET ART_TIPCOM = SPACE(03)
UPDATE U_ART_PR SET ART_DESCOM = SPACE(30)
UPDATE U_ART_PR SET ART_SERNUM = SPACE(50)
UPDATE U_ART_PR SET ART_NOTCOM = SPACE(50)
UPDATE U_ART_PR SET ART_FLGMOD = SPACE(01)
UPDATE U_ART_PR SET ART_LEGSYS = SPACE(10)
UPDATE U_ART_PR SET ART_FLGMIM = 0
UPDATE U_ART_PR SET ART_CODOPE = SPACE(10)
UPDATE U_ART_PR SET ART_DESOPE = SPACE(50)
UPDATE U_ART_PR SET ART_FLGTRA = 1

