

ALTER TABLE [dbo].[MOV_CCO] ADD 
  MOV_NUMATRI numeric(20,0) NULL ,
  MOV_EFFETDA varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_INTEPER varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_NOTEFF [text] COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CCO] WITH NOCHECK ADD 
	CONSTRAINT [DF_MOV_CCO_MOV_NUMATRI] DEFAULT (0) FOR [MOV_NUMATRI],
	CONSTRAINT [DF_MOV_CCO_MOV_EFFETDA] DEFAULT ('') FOR [MOV_EFFETDA],
	CONSTRAINT [DF_MOV_CCO_MOV_INTEPER] DEFAULT ('') FOR [MOV_INTEPER],
	CONSTRAINT [DF_MOV_CCO_MOV_NOTEFF] DEFAULT ('') FOR [MOV_NOTEFF]
go

UPDATE MOV_CCO SET MOV_NUMATRI = 0
UPDATE MOV_CCO SET MOV_EFFETDA = ''
UPDATE MOV_CCO SET MOV_INTEPER = ''
UPDATE MOV_CCO SET MOV_NOTEFF = ''

