--- ALTERAZIONE DIMENSIONE DELLA GRAMMATURA (RICHIESTO UN DECIMALE)
ALTER TABLE [dbo].[U_PRD_D4] ALTER COLUMN
	 PR4_GRAMMA numeric(17,1) NULL
GO



--- AGGIUNTA NUOVI CAMPI 
---   1.DESCRIZIONE NON CONFORMITA (INSERITE DA UTENTE IN FASE DI SPALMATURA)
---   2.DESCRIZIONE NOTE FISSE PRESE DA INFORMAZIONI BARRE (per es. "DA RIBOBINARE", "DA MICROFORARE")
---     CHE DEVONO ESSERE STAMPATE IN ETICHETTA
ALTER TABLE [dbo].[U_PRD_D4] ADD 
 	PR4_NONCON VARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	PR4_NOTE   VARCHAR(100) COLLATE Latin1_General_CI_AS NULL	
go
-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_NONCON] DEFAULT ('') FOR [PR4_NONCON],
	CONSTRAINT [DF_U_PRD_D4_PR4_NOTE] DEFAULT ('') FOR [PR4_NOTE]
go

UPDATE U_PRD_D4 SET PR4_NONCON = ''
UPDATE U_PRD_D4 SET PR4_NOTE = ''
