
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_SP] ADD 
	 STA_UNIQU1 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB1 numeric(6) NULL,
	 STA_QTBOB1 numeric(6) NULL,
	 STA_UNIQU2 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB2 numeric(6) NULL,
	 STA_QTBOB2 numeric(6) NULL,
	 STA_UNIQU3 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB3 numeric(6) NULL,
	 STA_QTBOB3 numeric(6) NULL,
	 STA_UNIQU4 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB4 numeric(6) NULL,
	 STA_QTBOB4 numeric(6) NULL,
	 STA_UNIQU5 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB5 numeric(6) NULL,
	 STA_QTBOB5 numeric(6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_SP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_SP_STA_UNIQU1] DEFAULT ('') FOR [STA_UNIQU1],
	CONSTRAINT [DF_U_PRG_SP_STA_NRBOB1] DEFAULT (0) FOR [STA_NRBOB1],
	CONSTRAINT [DF_U_PRG_SP_STA_QTBOB1] DEFAULT (0) FOR [STA_QTBOB1],
	CONSTRAINT [DF_U_PRG_SP_STA_UNIQU2] DEFAULT ('') FOR [STA_UNIQU2],
	CONSTRAINT [DF_U_PRG_SP_STA_NRBOB2] DEFAULT (0) FOR [STA_NRBOB2],
	CONSTRAINT [DF_U_PRG_SP_STA_QTBOB2] DEFAULT (0) FOR [STA_QTBOB2],
	CONSTRAINT [DF_U_PRG_SP_STA_UNIQU3] DEFAULT ('') FOR [STA_UNIQU3],
	CONSTRAINT [DF_U_PRG_SP_STA_NRBOB3] DEFAULT (0) FOR [STA_NRBOB3],
	CONSTRAINT [DF_U_PRG_SP_STA_QTBOB3] DEFAULT (0) FOR [STA_QTBOB3],
	CONSTRAINT [DF_U_PRG_SP_STA_UNIQU4] DEFAULT ('') FOR [STA_UNIQU4],
	CONSTRAINT [DF_U_PRG_SP_STA_NRBOB4] DEFAULT (0) FOR [STA_NRBOB4],
	CONSTRAINT [DF_U_PRG_SP_STA_QTBOB4] DEFAULT (0) FOR [STA_QTBOB4],
	CONSTRAINT [DF_U_PRG_SP_STA_UNIQU5] DEFAULT ('') FOR [STA_UNIQU5],
	CONSTRAINT [DF_U_PRG_SP_STA_NRBOB5] DEFAULT (0) FOR [STA_NRBOB5],
	CONSTRAINT [DF_U_PRG_SP_STA_QTBOB5] DEFAULT (0) FOR [STA_QTBOB5]
go

UPDATE U_PRG_SP SET STA_UNIQU1 = 0
UPDATE U_PRG_SP SET STA_NRBOB1 = 0
UPDATE U_PRG_SP SET STA_QTBOB1 = 0
UPDATE U_PRG_SP SET STA_UNIQU2 = 0
UPDATE U_PRG_SP SET STA_NRBOB2 = 0
UPDATE U_PRG_SP SET STA_QTBOB2 = 0
UPDATE U_PRG_SP SET STA_UNIQU3 = 0
UPDATE U_PRG_SP SET STA_NRBOB3 = 0
UPDATE U_PRG_SP SET STA_QTBOB3 = 0
UPDATE U_PRG_SP SET STA_UNIQU4 = 0
UPDATE U_PRG_SP SET STA_NRBOB4 = 0
UPDATE U_PRG_SP SET STA_QTBOB4 = 0
UPDATE U_PRG_SP SET STA_UNIQU5 = 0
UPDATE U_PRG_SP SET STA_NRBOB5 = 0
UPDATE U_PRG_SP SET STA_QTBOB5 = 0

