/* 
********************************************************************************
AGGIUNTA CAMPI PER TRACCIATURA INSERIMENTI E MODIFICHE
AGGIUNTA CAMPi PER LEGAME CON SALESFORCE
********************************************************************************
*/

ALTER TABLE [dbo].[U_LOC_AN] ADD 
	REG_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_REG_CODOPE] DEFAULT (''),
	REG_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_REG_NOMOPE] DEFAULT (''),
	REG_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_REG_DATREG] DEFAULT (''),
	REG_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_REG_ORAREG] DEFAULT (''),
	MOD_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_MOD_CODOPE] DEFAULT (''),
	MOD_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_MOD_NOMOPE] DEFAULT (''),
	MOD_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_MOD_DATREG] DEFAULT (''),
	MOD_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_MOD_ORAREG] DEFAULT (''),
	SF_LOC_ID varchar(18) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_SF_LOC_ID] DEFAULT (''),
	SF_LASTMODIFIEDDATE varchar(28) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_LOC_AN_SF_LASTMODIFIEDDATE] DEFAULT ('')
go

UPDATE U_LOC_AN SET 
	REG_CODOPE = 'SER',
	REG_NOMOPE = 'ASS. - Assistenza Project',
	REG_DATREG = CASE LOC_DATINS WHEN '' THEN convert(varchar, GETDATE(), 111) ELSE LOC_DATINS END,
	REG_ORAREG = '00:00:00'
WHERE REG_CODOPE = '' AND REG_DATREG = ''
