--- CANCELLAZIONE DEL CAMPO PR2_DBARRE
ALTER TABLE [dbo].[U_PRD_D2] DROP
	 CONSTRAINT DF_U_PRD_D2_PR2_DBARRE 
GO

ALTER TABLE [dbo].[U_PRD_D2] DROP
	 COLUMN PR2_DBARRE 
GO


--- RICREAZIONE DEL CAMPO PR2_DBARRE IN FORMATO NUMERICO

ALTER TABLE [dbo].[U_PRD_D2] ADD 
 	 PR2_DBARRE numeric(5,0) NULL
go
-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D2_PR2_DBARRE] DEFAULT (0) FOR [PR2_DBARRE]
go

UPDATE U_PRD_D2 SET PR2_DBARRE = 0



