-- AGGIORNAMENTO TABELLA NAZIONI_UNICO PER DETERMINAZIONE PAESI IN BLACK LIST RELATIVAMENTE aLLA COMUNICAZIONE DEL 2017 (OPERAZIONI DEL 2016)

UPDATE NAZIONI_UNICO SET BLACK = ''

UPDATE NAZIONI_UNICO SET BLACK = 'X' WHERE DESCRI IN (
'Andorra', 
'BAHRAIN', 
'Bahamas', 
'Barbados', 
'Barbuda', 
'BRUNEI DARUSSALAM', 
'Gibuti', 
'Grenada', 
'Guatemala', 
'COOK ISOLE', 
'MARSHALL (ISOLE)', 
'VERGINI AMERICANE (ISOLE)', 
'Kiribati', 
'Libano', 
'Liberia', 
'Liechtenstein', 
'Macao', 
'PRINCIPATO DI MONACO', 
'Maldive', 
'Nauru', 
'Niue', 
'Nuova Caledonia', 
'Oman', 
'Polinesia francese', 
'Saint Kitts e Nevis', 
'ISOLE SALOMONE', 
'AMERICAN SAMOA ISOLE', 
'SAINTE LUCIA', 
'ST. VINCENTE E LE GRENADINE', 
'ST. HELENA', 
'SARK C.I.', 
'Seychelles', 
'Tonga', 
'Tuvalu', 
'Vanuatu',
'Angola', 
'ANTIGUA E BARBUDA', 
'Dominica', 
'Ecuador', 
'Giamaica', 
'KENYA', 
'PANAMA - ZONA DEL CANALE', 
'Portorico', 
'Svizzera', 
'Uruguay')
