
/* 
********************************************************************************
INSERIMENTO NUOVI CAMPI PER GESTIONE PIANIFICAZIONI IN AVANZAMENTI DI PRODUZIONE
********************************************************************************
*/
ALTER TABLE [dbo].[PROD_AVANZA] ADD 
	IDPIANIF varchar (10) COLLATE Latin1_General_CI_AS NULL,
	PERIODPIAN NUMERIC(2,0) NULL
go

ALTER TABLE [dbo].[PROD_AVANZA] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROD_AVANZA_IDPIANIF] DEFAULT ('') FOR [IDPIANIF],
	CONSTRAINT [DF_PROD_AVANZA_PERIODPIAN] DEFAULT (0) FOR [PERIODPIAN]
go

UPDATE PROD_AVANZA SET IDPIANIF = ''
UPDATE PROD_AVANZA SET PERIODPIAN = 0
