
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_PK] ADD
	PR5_LOTPRD varchar(10) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_PK] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_PK_PR5_LOTPRD] DEFAULT ('') FOR [PR5_LOTPRD]
go

UPDATE U_PRD_PK SET PR5_LOTPRD = ''
