

ALTER TABLE [dbo].[IMPIANTI_RI] ADD 
	ORD_DATREG varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_RI_ORD_DATREG] DEFAULT (''),
	ORD_ORAREG varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_RI_ORD_ORAREG] DEFAULT ('')
GO


