/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_CMP_CL] ADD 
	CMP_ORCM11 varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_ORCM12 varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_ORCM13 varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_ORCM14 varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_DISPLO text COLLATE Latin1_General_CI_AS NULL ,
	CMP_DTCM0X varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CMP_ORCM0X varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_CDOP0X varchar(3) COLLATE Latin1_General_CI_AS NULL ,
	CMP_DSOP0X varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CMP_DTCM1X varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CMP_ORCM1X varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CMP_DSOP1X varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_CMP_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM11] DEFAULT ('') FOR [CMP_ORCM11] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM12] DEFAULT ('') FOR [CMP_ORCM12] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM13] DEFAULT ('') FOR [CMP_ORCM13] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM14] DEFAULT ('') FOR [CMP_ORCM14] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_DISPLO] DEFAULT ('') FOR [CMP_DISPLO] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_DTCM0X] DEFAULT ('') FOR [CMP_DTCM0X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM0X] DEFAULT ('') FOR [CMP_ORCM0X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_CDOP0X] DEFAULT ('') FOR [CMP_CDOP0X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_DSOP0X] DEFAULT ('') FOR [CMP_DSOP0X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_DTCM1X] DEFAULT ('') FOR [CMP_DTCM1X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_ORCM1X] DEFAULT ('') FOR [CMP_ORCM1X] ,
	CONSTRAINT [DF_U_CMP_CL_CMP_DSOP1X] DEFAULT ('') FOR [CMP_DSOP1X]
go

UPDATE U_CMP_CL SET CMP_ORCM11 = CMP_ORCM01
UPDATE U_CMP_CL SET CMP_ORCM12 = CMP_ORCM02
UPDATE U_CMP_CL SET CMP_ORCM13 = CMP_ORCM03
UPDATE U_CMP_CL SET CMP_ORCM14 = CMP_ORCM04
UPDATE U_CMP_CL SET CMP_DISPLO = ''
UPDATE U_CMP_CL SET CMP_DTCM0X = ''
UPDATE U_CMP_CL SET CMP_ORCM0X = ''
UPDATE U_CMP_CL SET CMP_CDOP0X = ''
UPDATE U_CMP_CL SET CMP_DSOP0X = ''
UPDATE U_CMP_CL SET CMP_DTCM1X = ''
UPDATE U_CMP_CL SET CMP_ORCM1X = ''
UPDATE U_CMP_CL SET CMP_DSOP1X = ''