


 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_RICBILA  BIT NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_RICBILA] DEFAULT (0) FOR [AZI_RICBILA]
GO

UPDATE U_AZI_PB SET AZI_RICBILA  = 0