
ALTER TABLE [dbo].[AUTORIZZAZIONI] ADD 
	ANACLI_VIS [bit] NULL ,
	ANACLI_INS [bit] NULL ,
	ANACLI_MOD [bit] NULL ,
	ANACLI_ANN [bit] NULL ,
	ANAFOR_VIS [bit] NULL ,
	ANAFOR_INS [bit] NULL ,
	ANAFOR_MOD [bit] NULL ,
	ANAFOR_ANN [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[AUTORIZZAZIONI] WITH NOCHECK ADD 
	CONSTRAINT [ANACLI_VIS] DEFAULT (0) FOR [ANACLI_VIS],
	CONSTRAINT [ANACLI_INS] DEFAULT (0) FOR [ANACLI_INS],
	CONSTRAINT [ANACLI_MOD] DEFAULT (0) FOR [ANACLI_MOD],
	CONSTRAINT [ANACLI_ANN] DEFAULT (0) FOR [ANACLI_ANN],
	CONSTRAINT [ANAFOR_VIS] DEFAULT (0) FOR [ANAFOR_VIS],
	CONSTRAINT [ANAFOR_INS] DEFAULT (0) FOR [ANAFOR_INS],
	CONSTRAINT [ANAFOR_MOD] DEFAULT (0) FOR [ANAFOR_MOD],
	CONSTRAINT [ANAFOR_ANN] DEFAULT (0) FOR [ANAFOR_ANN]
go

UPDATE AUTORIZZAZIONI SET ANACLI_VIS = 0
UPDATE AUTORIZZAZIONI SET ANACLI_INS = 0
UPDATE AUTORIZZAZIONI SET ANACLI_MOD = 0
UPDATE AUTORIZZAZIONI SET ANACLI_ANN = 0
UPDATE AUTORIZZAZIONI SET ANAFOR_VIS = 0
UPDATE AUTORIZZAZIONI SET ANAFOR_INS = 0
UPDATE AUTORIZZAZIONI SET ANAFOR_MOD = 0
UPDATE AUTORIZZAZIONI SET ANAFOR_ANN = 0

go
