
ALTER TABLE [dbo].[U_FAT_DD] ADD 
	ORS_NORCLI varchar (20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FAT_DD_ORS_NORCLI] DEFAULT (''),
	ORS_DORCLI varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FAT_DD_ORS_DORCLI] DEFAULT ('')
GO
