/* 
********************************************************************************
AGGIUNTA CAMPI PER TRACCIATURA INSERIMENTI E MODIFICHE
AGGIUNTA CAMPO "SF_ACCOUNT_ID" IN ANAGRAFICA CLIENTI PER LEGAME CON SALESFORCE
********************************************************************************
*/

ALTER TABLE [dbo].[U_ANA_CL] ADD 
	REG_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_REG_CODOPE] DEFAULT (''),
	REG_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_REG_NOMOPE] DEFAULT (''),
	REG_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_REG_DATREG] DEFAULT (''),
	REG_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_REG_ORAREG] DEFAULT (''),
	MOD_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_MOD_CODOPE] DEFAULT (''),
	MOD_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_MOD_NOMOPE] DEFAULT (''),
	MOD_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_MOD_DATREG] DEFAULT (''),
	MOD_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_MOD_ORAREG] DEFAULT (''),
	SF_ACCOUNT_ID varchar(18) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_SF_ACCOUNT_ID] DEFAULT (''),
	SF_LASTMODIFIEDDATE varchar(28) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_SF_LASTMODIFIEDDATE] DEFAULT ('')
go

UPDATE CL SET REG_DATREG = COALESCE((SELECT TOP 1 CLI_DATINS FROM U_CLI_AN WHERE CLI_CODCLI = CL.CLI_CODCLI),'') FROM U_ANA_CL AS CL
UPDATE CL SET MOD_DATREG = COALESCE((SELECT TOP 1 CLI_DATNEW FROM U_CLI_AN WHERE CLI_CODCLI = CL.CLI_CODCLI),'') FROM U_ANA_CL AS CL
