ALTER TABLE ELENCO_VUOTI_DB ADD CODICE_ARTICOLO [varchar] (30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE ELENCO_VUOTI_DB ADD CODICE_CLIENTE [varchar] (10) COLLATE Latin1_General_CI_AS NULL

go

UPDATE ELENCO_VUOTI_DB SET CODICE_ARTICOLO=''
UPDATE ELENCO_VUOTI_DB SET CODICE_CLIENTE=''