
ALTER TABLE [dbo].[U_CLI_AN] ADD 
  CLI_ESTNAZ varchar(3) COLLATE Latin1_General_CI_AS NULL,
  CLI_ESTNAS varchar(10) COLLATE Latin1_General_CI_AS NULL,
  CLI_PRONAS varchar(2) COLLATE Latin1_General_CI_AS NULL,
  CLI_ESTCOM varchar(40) COLLATE Latin1_General_CI_AS NULL,
  CLI_ESTDOM varchar(3) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_CLI_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CLI_AN_CLI_ESTNAZ] DEFAULT ('') FOR [CLI_ESTNAZ],
	CONSTRAINT [DF_U_CLI_AN_CLI_ESTNAS] DEFAULT ('') FOR [CLI_ESTNAS],
	CONSTRAINT [DF_U_CLI_AN_CLI_PRONAS] DEFAULT ('') FOR [CLI_PRONAS],
	CONSTRAINT [DF_U_CLI_AN_CLI_ESTCOM] DEFAULT ('') FOR [CLI_ESTCOM],
	CONSTRAINT [DF_U_CLI_AN_CLI_ESTDOM] DEFAULT ('') FOR [CLI_ESTDOM]
go

UPDATE U_CLI_AN SET CLI_ESTNAZ = ''
UPDATE U_CLI_AN SET CLI_ESTNAS = ''
UPDATE U_CLI_AN SET CLI_PRONAS = ''
UPDATE U_CLI_AN SET CLI_ESTCOM = ''
UPDATE U_CLI_AN SET CLI_ESTDOM = ''

UPDATE U_CLI_AN SET CLI_RECCAT = 1 where (CLI_RECCAT != 1 and CLI_RECCAT != 2)

