
ALTER TABLE [DBO].[CASHFLOWFIN] ADD 
	SOMMAGG NUMERIC(1,0) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_SOMMAGG] DEFAULT (0),
	NOSCADMESE BIT NOT NULL CONSTRAINT [DF_CASHFLOWFIN_NOSCADMESE] DEFAULT (0)
GO
