/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PES_VE] ADD 
	PES_BANDA1 NUMERIC(3) NULL,
	PES_BANAL1 NUMERIC(3) NULL,
	PES_BANDA2 NUMERIC(3) NULL,
	PES_BANAL2 NUMERIC(3) NULL,
	PES_BANDA3 NUMERIC(3) NULL,
	PES_BANAL3 NUMERIC(3) NULL,
	PES_BANDA4 NUMERIC(3) NULL,
	PES_BANAL4 NUMERIC(3) NULL,
	PES_BANDA5 NUMERIC(3) NULL,
	PES_BANAL5 NUMERIC(3) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PES_VE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PES_VE_PES_BANDA1] DEFAULT (0) FOR [PES_BANDA1],	
	CONSTRAINT [DF_U_PES_VE_PES_BANAL1] DEFAULT (0) FOR [PES_BANAL1],	
	CONSTRAINT [DF_U_PES_VE_PES_BANDA2] DEFAULT (0) FOR [PES_BANDA2],	
	CONSTRAINT [DF_U_PES_VE_PES_BANAL2] DEFAULT (0) FOR [PES_BANAL2],	
	CONSTRAINT [DF_U_PES_VE_PES_BANDA3] DEFAULT (0) FOR [PES_BANDA3],	
	CONSTRAINT [DF_U_PES_VE_PES_BANAL3] DEFAULT (0) FOR [PES_BANAL3],	
	CONSTRAINT [DF_U_PES_VE_PES_BANDA4] DEFAULT (0) FOR [PES_BANDA4],	
	CONSTRAINT [DF_U_PES_VE_PES_BANAL4] DEFAULT (0) FOR [PES_BANAL4],	
	CONSTRAINT [DF_U_PES_VE_PES_BANDA5] DEFAULT (0) FOR [PES_BANDA5],
	CONSTRAINT [DF_U_PES_VE_PES_BANAL5] DEFAULT (0) FOR [PES_BANAL5]	
go

UPDATE U_PES_VE SET PES_BANDA1 = 0
UPDATE U_PES_VE SET PES_BANDA2 = 0
UPDATE U_PES_VE SET PES_BANDA3 = 0
UPDATE U_PES_VE SET PES_BANDA4 = 0
UPDATE U_PES_VE SET PES_BANDA5 = 0
UPDATE U_PES_VE SET PES_BANAL1 = 0
UPDATE U_PES_VE SET PES_BANAL2 = 0
UPDATE U_PES_VE SET PES_BANAL3 = 0
UPDATE U_PES_VE SET PES_BANAL4 = 0
UPDATE U_PES_VE SET PES_BANAL5 = 0


