ALTER TABLE [dbo].[U_ORD_DD] ADD 
	ORD_DARIV BIT NULL,
	ORD_DAPROD numeric (10,2) NULL
go

ALTER TABLE [dbo].[U_ORD_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORD_DD_ORD_DARIV] DEFAULT (0) FOR [ORD_DARIV],
	CONSTRAINT [DF_U_ORD_DD_ORD_DAPROD] DEFAULT (0) FOR [ORD_DAPROD]
go

UPDATE U_ORD_DD SET ORD_DARIV = 0
UPDATE U_ORD_DD SET ORD_DAPROD = 0