
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_PER_AN] ADD 
	 PER_CODPDV varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 PER_DESPDV varchar(50) COLLATE Latin1_General_CI_AS NULL,
         PER_NOTGEN [text] COLLATE Latin1_General_CI_AS NULL ,
	 PER_CODCON varchar(7) COLLATE Latin1_General_CI_AS NULL,
	 PER_DSCONT varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 PER_DATINI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 PER_DATFIN varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 PER_CONTO varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PER_COMLOR [numeric] (12,2) NULL ,
	 PER_RITACC [numeric] (6,2) NULL ,
	 PER_PERCON [numeric] (6,2) NULL ,
         PER_NOTCON [text] COLLATE Latin1_General_CI_AS NULL ,
	 PER_PFTCON varchar(2) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PER_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PER_AN_PER_CODPDV] DEFAULT ('') FOR [PER_CODPDV],
	CONSTRAINT [DF_U_PER_AN_PER_DESPDV] DEFAULT ('') FOR [PER_DESPDV],
	CONSTRAINT [DF_U_PER_AN_PER_NOTGEN] DEFAULT ('') FOR [PER_NOTGEN],
	CONSTRAINT [DF_U_PER_AN_PER_CODCON] DEFAULT ('') FOR [PER_CODCON],
	CONSTRAINT [DF_U_PER_AN_PER_CSCONT] DEFAULT ('') FOR [PER_DSCONT],
	CONSTRAINT [DF_U_PER_AN_PER_DATINI] DEFAULT ('') FOR [PER_DATINI],
	CONSTRAINT [DF_U_PER_AN_PER_DATFIN] DEFAULT ('') FOR [PER_DATFIN],
	CONSTRAINT [DF_U_PER_AN_PER_CONTO] DEFAULT ('') FOR [PER_CONTO],
	CONSTRAINT [DF_U_PER_AN_PER_COMLOR] DEFAULT (0) FOR [PER_COMLOR],
	CONSTRAINT [DF_U_PER_AN_PER_RITACC] DEFAULT (0) FOR [PER_RITACC],
	CONSTRAINT [DF_U_PER_AN_PER_PERCON] DEFAULT (0) FOR [PER_PERCON],
	CONSTRAINT [DF_U_PER_AN_PER_NOTCON] DEFAULT ('') FOR [PER_NOTCON],
	CONSTRAINT [DF_U_PER_AN_PER_PFTCON] DEFAULT ('') FOR [PER_PFTCON]
go

UPDATE U_PER_AN SET PER_CODPDV = SPACE(10)
UPDATE U_PER_AN SET PER_DESPDV = SPACE(50)
UPDATE U_PER_AN SET PER_NOTGEN = SPACE(10)
UPDATE U_PER_AN SET PER_CODCON = SPACE(07)
UPDATE U_PER_AN SET PER_DSCONT = SPACE(50)
UPDATE U_PER_AN SET PER_DATINI = SPACE(10)
UPDATE U_PER_AN SET PER_DATFIN = SPACE(10)
UPDATE U_PER_AN SET PER_CONTO = SPACE(13)
UPDATE U_PER_AN SET PER_COMLOR = 0
UPDATE U_PER_AN SET PER_RITACC = 0
UPDATE U_PER_AN SET PER_PERCON = 0
UPDATE U_PER_AN SET PER_NOTCON = SPACE(10)
UPDATE U_PER_AN SET PER_PFTCON = SPACE(02)