
/* 
**************************************************************
INSERIMENTO NUOVI CAMPI PER U_MAG_MO E U_MAG_MS
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_MO] ADD 
	 MOV_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DESCLI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 MST_DATAST varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MST_ORASTO varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 MST_CODOPE varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MST_DESOPE varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_CODCLI] DEFAULT ('') FOR [MOV_CODCLI],
	CONSTRAINT [DF_U_MAG_MO_MOV_DESCLI] DEFAULT ('') FOR [MOV_DESCLI],
	CONSTRAINT [DF_U_MAG_MO_MST_DATAST] DEFAULT ('') FOR [MST_DATAST],
	CONSTRAINT [DF_U_MAG_MO_MST_ORASTO] DEFAULT ('') FOR [MST_ORASTO],
	CONSTRAINT [DF_U_MAG_MO_MST_CODOPE] DEFAULT ('') FOR [MST_CODOPE],
	CONSTRAINT [DF_U_MAG_MO_MST_DESOPE] DEFAULT ('') FOR [MST_DESOPE]
go

UPDATE U_MAG_MO SET MOV_CODCLI = SPACE(10)
UPDATE U_MAG_MO SET MOV_DESCLI = SPACE(50)
UPDATE U_MAG_MO SET MST_DATAST = SPACE(10)
UPDATE U_MAG_MO SET MST_ORASTO = SPACE(08)
UPDATE U_MAG_MO SET MST_CODOPE = SPACE(10)
UPDATE U_MAG_MO SET MST_DESOPE = SPACE(50)

ALTER TABLE [dbo].[U_MAG_MS] ADD 
	 MOV_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DESCLI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 MST_DATAST varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MST_ORASTO varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 MST_CODOPE varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MST_DESOPE varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MS] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MS_MOV_CODCLI] DEFAULT ('') FOR [MOV_CODCLI],
	CONSTRAINT [DF_U_MAG_MS_MOV_DESCLI] DEFAULT ('') FOR [MOV_DESCLI],
	CONSTRAINT [DF_U_MAG_MS_MST_DATAST] DEFAULT ('') FOR [MST_DATAST],
	CONSTRAINT [DF_U_MAG_MS_MST_ORASTO] DEFAULT ('') FOR [MST_ORASTO],
	CONSTRAINT [DF_U_MAG_MS_MST_CODOPE] DEFAULT ('') FOR [MST_CODOPE],
	CONSTRAINT [DF_U_MAG_MS_MST_DESOPE] DEFAULT ('') FOR [MST_DESOPE]
go

UPDATE U_MAG_MS SET MOV_CODCLI = SPACE(10)
UPDATE U_MAG_MS SET MOV_DESCLI = SPACE(50)
UPDATE U_MAG_MS SET MST_DATAST = SPACE(10)
UPDATE U_MAG_MS SET MST_ORASTO = SPACE(08)
UPDATE U_MAG_MS SET MST_CODOPE = SPACE(10)
UPDATE U_MAG_MS SET MST_DESOPE = SPACE(50)
