

ALTER TABLE [DBO].[U_FAP_TT] ADD 
	T_NORAENPA BIT NULL
GO

ALTER TABLE [DBO].[U_FAP_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAP_TT_T_NORAENPA] DEFAULT (0) FOR [T_NORAENPA]
GO

UPDATE U_FAP_TT SET T_NORAENPA = 0
