ALTER TABLE [DBO].[VENDITE_TT] ADD
	ORD_TECNICO varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_TECNICO] DEFAULT (''),
	ORD_DTINIINT varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_DTINIINT] DEFAULT (''),
	ORD_ORAINIINT varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_ORAINIINT] DEFAULT (''),
	ORD_DTFINTNT varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_DTFINTNT] DEFAULT (''),
	ORD_ORAFININT varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_ORAFININT] DEFAULT (''),
	ORD_INASSIST bit NOT NULL CONSTRAINT [DF_VENDITE_TT_M.ORD_INASSIST] DEFAULT (0),
	ORD_PAGALTEC bit NOT NULL CONSTRAINT [DF_VENDITE_TT_ORD_PAGALTEC] DEFAULT (0)
GO

ALTER TABLE [dbo].[VENDITE_TT] ADD 
	 ORD_VALPRE numeric(17,3) NULL
go
ALTER TABLE [dbo].[VENDITE_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_VENDITE_TT_ORD_VALPRE] DEFAULT ('0') FOR [ORD_VALPRE]
go

UPDATE VENDITE_TT SET ORD_VALPRE = 0
