
ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_QTALT numeric(12,4) NOT NULL CONSTRAINT [DF_U_ART_AN_ART_QTALT] DEFAULT (0),
	ART_CODADR varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_ART_CODADR] DEFAULT ('')
go

