
/*         
***************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
***************************************************************
*/
ALTER TABLE [dbo].[CONTI] ADD 
	 CON_ANTICIPAZIONI BIT NOT NULL CONSTRAINT [DF_CONTI_CON_ANTICIPAZIONI] DEFAULT (0),
	 CON_PREVIDENZA BIT NOT NULL CONSTRAINT [DF_CONTI_CON_PREVIDENZA] DEFAULT (0),
	 CON_BOLLI BIT NOT NULL CONSTRAINT [DF_CONTI_CON_BOLLI] DEFAULT (0),
	 CON_SOGGETTORAP BIT NOT NULL CONSTRAINT [DF_CONTI_CON_SOGGETTORAP] DEFAULT (0),
	 CON_RAP BIT NOT NULL CONSTRAINT [DF_CONTI_CON_RAP] DEFAULT (0),
	 CON_SOGGETTOINPS BIT NOT NULL CONSTRAINT [DF_CONTI_CON_SOGGETTOINPS] DEFAULT (0),
	 CON_INPS BIT NOT NULL CONSTRAINT [DF_CONTI_CON_INPS] DEFAULT (0)
go

