--- AGGIUNTA NUOVI CAMPI 
---   1.STATO SEQUENZA PER FUNZIONE DI MODIFICA/RIPRISTINO STATO

ALTER TABLE [dbo].[U_PRD_D2] ADD 
 	PR2_SSQOLD VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D2_PR2_SSQOLD] DEFAULT ('') FOR PR2_SSQOLD
go

UPDATE U_PRD_D2 SET PR2_SSQOLD = ''