/*    
***********************************************************************
INSERIMENTO DATI LETTERA INTENTO IN ANAGRAFICA FORNITORI
***********************************************************************
*/


ALTER TABLE [dbo].[U_FOR_AN] ADD 

	 FOR_CLIES varchar(6) COLLATE Latin1_General_CI_AS NULL,
	 FOR_DTCLES varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 FOR_NSES varchar(6) COLLATE Latin1_General_CI_AS NULL,
	 FOR_DTNSES varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 FOR_UFFIVA varchar(25) COLLATE Latin1_General_CI_AS NULL,
	 FOR_ARTINTE varchar(3) COLLATE Latin1_General_CI_AS NULL,
     FOR_NOTEINT [text] COLLATE Latin1_General_CI_AS NULL,
	 FOR_INTUNO varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_INTDUE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_INTTRE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_ANNOPE varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 FOR_IMPINT numeric (17,3),
	 FOR_ANNOPE2 varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 FOR_GGINTD varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_MMINTD varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_GGINTA varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_MMINTA varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 FOR_DOGANA varchar(25) COLLATE Latin1_General_CI_AS NULL,
	 FOR_CLIAZI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_INDAZI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_CAPAZI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 FOR_COMUNEAZI varchar(35) COLLATE Latin1_General_CI_AS NULL,
	 FOR_PROVAZI varchar(3) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_FOR_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FOR_AN_FOR_CLIES] DEFAULT ('') FOR [FOR_CLIES],
	CONSTRAINT [DF_U_FOR_AN_FOR_DTCLES] DEFAULT ('') FOR [FOR_DTCLES],
	CONSTRAINT [DF_U_FOR_AN_FOR_NSES] DEFAULT ('') FOR [FOR_NSES],
	CONSTRAINT [DF_U_FOR_AN_FOR_DTNSES] DEFAULT ('') FOR [FOR_DTNSES],
	CONSTRAINT [DF_U_FOR_AN_FOR_UFFIVA] DEFAULT ('') FOR [FOR_UFFIVA],
	CONSTRAINT [DF_U_FOR_AN_FOR_ARTINTE] DEFAULT ('') FOR [FOR_ARTINTE],
	CONSTRAINT [DF_U_FOR_AN_FOR_NOTEINT] DEFAULT ('') FOR [FOR_NOTEINT],
	CONSTRAINT [DF_U_FOR_AN_FOR_INTUNO] DEFAULT ('') FOR [FOR_INTUNO],
	CONSTRAINT [DF_U_FOR_AN_FOR_INTDUE] DEFAULT ('') FOR [FOR_INTDUE],
	CONSTRAINT [DF_U_FOR_AN_FOR_INTTRE] DEFAULT ('') FOR [FOR_INTTRE],
	CONSTRAINT [DF_U_FOR_AN_FOR_ANNOPE] DEFAULT ('') FOR [FOR_ANNOPE],
	CONSTRAINT [DF_U_FOR_AN_FOR_IMPINT] DEFAULT (0) FOR [FOR_IMPINT],
	CONSTRAINT [DF_U_FOR_AN_FOR_ANNOPE2] DEFAULT ('') FOR [FOR_ANNOPE2],
	CONSTRAINT [DF_U_FOR_AN_FOR_GGINTD] DEFAULT ('') FOR [FOR_GGINTD],
	CONSTRAINT [DF_U_FOR_AN_FOR_MMINTD] DEFAULT ('') FOR [FOR_MMINTD],
	CONSTRAINT [DF_U_FOR_AN_FOR_GGINTA] DEFAULT ('') FOR [FOR_GGINTA],
	CONSTRAINT [DF_U_FOR_AN_FOR_MMINTA] DEFAULT ('') FOR [FOR_MMINTA],
	CONSTRAINT [DF_U_FOR_AN_FOR_DOGANA] DEFAULT ('') FOR [FOR_DOGANA],
	CONSTRAINT [DF_U_FOR_AN_FOR_CLIAZI] DEFAULT ('') FOR [FOR_CLIAZI],
	CONSTRAINT [DF_U_FOR_AN_FOR_INDAZI] DEFAULT ('') FOR [FOR_INDAZI],
	CONSTRAINT [DF_U_FOR_AN_FOR_CAPAZI] DEFAULT ('') FOR [FOR_CAPAZI],
	CONSTRAINT [DF_U_FOR_AN_FOR_COMUNEAZI] DEFAULT ('') FOR [FOR_COMUNEAZI],
	CONSTRAINT [DF_U_FOR_AN_FOR_PROVAZI] DEFAULT ('') FOR [FOR_PROVAZI]
go




UPDATE U_FOR_AN SET FOR_CLIES = ''
UPDATE U_FOR_AN SET FOR_DTCLES = ''
UPDATE U_FOR_AN SET FOR_NSES = ''
UPDATE U_FOR_AN SET FOR_DTNSES = ''
UPDATE U_FOR_AN SET FOR_UFFIVA = ''
UPDATE U_FOR_AN SET FOR_ARTINTE = ''
UPDATE U_FOR_AN SET FOR_NOTEINT = ''
UPDATE U_FOR_AN SET FOR_INTUNO = ''
UPDATE U_FOR_AN SET FOR_INTDUE = ''
UPDATE U_FOR_AN SET FOR_INTTRE = ''
UPDATE U_FOR_AN SET FOR_ANNOPE = ''
UPDATE U_FOR_AN SET FOR_IMPINT = 0
UPDATE U_FOR_AN SET FOR_ANNOPE2 = ''
UPDATE U_FOR_AN SET FOR_GGINTD = ''
UPDATE U_FOR_AN SET FOR_MMINTD = ''
UPDATE U_FOR_AN SET FOR_GGINTA = ''
UPDATE U_FOR_AN SET FOR_MMINTA = ''
UPDATE U_FOR_AN SET FOR_DOGANA = ''
UPDATE U_FOR_AN SET FOR_CLIAZI = ''
UPDATE U_FOR_AN SET FOR_INDAZI = ''
UPDATE U_FOR_AN SET FOR_CAPAZI = ''
UPDATE U_FOR_AN SET FOR_COMUNEAZI = ''
UPDATE U_FOR_AN SET FOR_PROVAZI = ''