/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[RES_OPER] ADD 
	 RES_CURRI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_RISOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_AULE  varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_CORSI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_SERVI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_PRODO varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_TIMES varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_TRACO varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_RICHI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_ATTIV varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 RES_EMAIL varchar(100) COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[RES_OPER] WITH NOCHECK ADD 
	CONSTRAINT [DF_RES_OPER_RES_CURRI] DEFAULT ('') FOR [RES_CURRI],
	CONSTRAINT [DF_RES_OPER_RES_RISOR] DEFAULT ('') FOR [RES_RISOR],
	CONSTRAINT [DF_RES_OPER_RES_AULE] DEFAULT ('') FOR [RES_AULE],
	CONSTRAINT [DF_RES_OPER_RES_CORSI] DEFAULT ('') FOR [RES_CORSI],
	CONSTRAINT [DF_RES_OPER_RES_SERVI] DEFAULT ('') FOR [RES_SERVI],
	CONSTRAINT [DF_RES_OPER_RES_PRODO] DEFAULT ('') FOR [RES_PRODO],
	CONSTRAINT [DF_RES_OPER_RES_TIMES] DEFAULT ('') FOR [RES_TIMES],
	CONSTRAINT [DF_RES_OPER_RES_TRACO] DEFAULT ('') FOR [RES_TRACO],
	CONSTRAINT [DF_RES_OPER_RES_RICHI] DEFAULT ('') FOR [RES_RICHI],
	CONSTRAINT [DF_RES_OPER_RES_ATTIV] DEFAULT ('') FOR [RES_ATTIV],
	CONSTRAINT [DF_RES_OPER_RES_EMAIL] DEFAULT ('') FOR [RES_EMAIL]
go

UPDATE RES_OPER SET RES_CURRI 	= ''
UPDATE RES_OPER SET RES_RISOR 	= ''
UPDATE RES_OPER SET RES_AULE 	= ''
UPDATE RES_OPER SET RES_CORSI 	= ''
UPDATE RES_OPER SET RES_SERVI 	= ''
UPDATE RES_OPER SET RES_PRODO 	= ''
UPDATE RES_OPER SET RES_TIMES 	= ''
UPDATE RES_OPER SET RES_TRACO 	= ''
UPDATE RES_OPER SET RES_RICHI 	= ''
UPDATE RES_OPER SET RES_ATTIV 	= ''
UPDATE RES_OPER SET RES_EMAIL 	= ''
