
ALTER TABLE [DBO].[DOCUMENTI] ADD 
	DOCD_NOSTP_PRN BIT NULL
GO

ALTER TABLE [DBO].[DOCUMENTI] WITH NOCHECK ADD 
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_PRN] DEFAULT (0) FOR [DOCD_NOSTP_PRN]
GO

UPDATE DOCUMENTI SET DOCD_NOSTP_PRN = 0
