/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	 MAG_NUMCAM varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 MAG_DATCAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_PRZFIS [numeric](17, 6) NULL,
	 MAG_DTCGMA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_DTIGMA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_DTFGMA varchar(10) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_GG_MAG_NUMCAM] DEFAULT ('') FOR [MAG_NUMCAM],
	CONSTRAINT [DF_U_MAG_GG_MAG_DATCAM] DEFAULT ('') FOR [MAG_DATCAM],
	CONSTRAINT [DF_U_MAG_GG_MAG_PRZFIS] DEFAULT (0) FOR [MAG_PRZFIS],
	CONSTRAINT [DF_U_MAG_GG_MAG_DTCGMA] DEFAULT ('') FOR [MAG_DTCGMA],
	CONSTRAINT [DF_U_MAG_GG_MAG_DTIGMA] DEFAULT ('') FOR [MAG_DTIGMA],
	CONSTRAINT [DF_U_MAG_GG_MAG_DTFGMA] DEFAULT ('') FOR [MAG_DTFGMA]
go

UPDATE U_MAG_GG SET MAG_NUMCAM = SPACE(06)
UPDATE U_MAG_GG SET MAG_DATCAM = SPACE(10)
UPDATE U_MAG_GG SET MAG_PRZFIS = 0
UPDATE U_MAG_GG SET MAG_DTCGMA = SPACE(10)
UPDATE U_MAG_GG SET MAG_DTIGMA = SPACE(10)
UPDATE U_MAG_GG SET MAG_DTFGMA = SPACE(10)
