
UPDATE U_AZI_PA SET AZI_SCRIT = '\BMP\AMBIENTE\SCRITTAAQUARIUS\AQ_SCRITTA.GIF'
UPDATE U_AZI_PA SET AZI_DESKTOP = '\BMP\AMBIENTE\SFONDI\SFONDO_AQUARIUS.JPG'
UPDATE U_AZI_PA SET AZI_PASS = '\BMP\AMBIENTE\SFONDI\SFONDO_AQUARIUS.JPG'
UPDATE U_AZI_PA SET AZI_PASS_SW = '\BMP\AMBIENTE\SFONDI\SFONDO_AQUARIUS.JPG'
UPDATE U_AZI_PA SET AZI_SUBMEN = '\BMP\AMBIENTE\SUBMENU\SFONDO_13_LARGE.PNG'

UPDATE U_AZI_PA SET AZI_AQUAR = 1
UPDATE U_AZI_PA SET AZI_SCRIT_B = 1
UPDATE U_AZI_PA SET AZI_SCRIT_N = 0
UPDATE U_AZI_PA SET AZI_SCRIT_R = 0


UPDATE U_AZI_PA SET AZI_PASS_B = 1
UPDATE U_AZI_PA SET AZI_PASS_N = 0

UPDATE U_AZI_PA SET AZI_PASS_R = 0



