/*
*** NUOVO CAMPO PER GESTIONE BOLLO VIRTUALE IN FATTURAZIONE ELETTRONICA
*/


ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_BOVIRT NUMERIC(10,2) NOT NULL CONSTRAINT [DF_U_ANA_CLI_BOVIRT] DEFAULT (0)
GO
