ALTER TABLE [dbo].[U_MAG_GG] ADD 
	 MAG_CSTFNU numeric(11,2) NULL,
	 MAG_CSTADE numeric(11,2) NULL,
	 MAG_CSTAMQ numeric(16,6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_GG_MAG_CSTFNU] DEFAULT (0) FOR [MAG_CSTFNU],
	CONSTRAINT [DF_U_MAG_GG_MAG_CSTADE] DEFAULT (0) FOR [MAG_CSTADE],
	CONSTRAINT [DF_U_MAG_GG_MAG_CSTAMQ] DEFAULT (0) FOR [MAG_CSTAMQ]
go

UPDATE U_MAG_GG SET MAG_CSTFNU = 0
UPDATE U_MAG_GG SET MAG_CSTADE = 0
UPDATE U_MAG_GG SET MAG_CSTAMQ = 0


ALTER TABLE [dbo].[U_MAG_CP] ADD 
	 MAG_CSTFNU numeric(11,2) NULL,
	 MAG_CSTADE numeric(11,2) NULL,
	 MAG_CSTAMQ numeric(16,6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_CP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CP_MAG_CSTFNU] DEFAULT (0) FOR [MAG_CSTFNU],
	CONSTRAINT [DF_U_MAG_CP_MAG_CSTADE] DEFAULT (0) FOR [MAG_CSTADE],
	CONSTRAINT [DF_U_MAG_CP_MAG_CSTAMQ] DEFAULT (0) FOR [MAG_CSTAMQ]
go

UPDATE U_MAG_CP SET MAG_CSTFNU = 0
UPDATE U_MAG_CP SET MAG_CSTADE = 0
UPDATE U_MAG_CP SET MAG_CSTAMQ = 0

