/* 
***************************************************************************************************
INSERIMENTO CAMPI PER GESTIONE SCONTI VENDITE AL BANCO: PRIVATI,PROFESSIONISTI,AZIENDE LIVELLO1/2/3
***************************************************************************************************
*/    

ALTER TABLE [dbo].[U_LIF_BA] ADD 
	LIS_SC_PRI NUMERIC(7,2) NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SC_PRI] DEFAULT (0),
	LIS_SC_PRO NUMERIC(7,2) NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SC_PRO] DEFAULT (0),
	LIS_SC_PA1 NUMERIC(7,2) NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SC_PA1] DEFAULT (0),
	LIS_SC_PA2 NUMERIC(7,2) NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SC_PA2] DEFAULT (0),
	LIS_SC_PA3 NUMERIC(7,2) NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SC_PA3] DEFAULT (0)
go

