
-- INSERIMENTO PARAMETRO NUMANF01 PER GESTIONE C/ANTICIPO ESTERO AUTOMATICO

INSERT INTO PARA	(CODICE,
			 DESCRI,
                         LIBERA,
			 PAR_DATINS)
VALUES           	('NUMANF01',
			 'N. C/ANTICIPO ESTERO AUTOMATICO',
                         '   0000',
			 '2006/12/01')
