
ALTER TABLE DOCUMENTI 
DROP CONSTRAINT DF_DOCUMENTI_DOCD_TIPO_TXT

ALTER TABLE DOCUMENTI 
DROP COLUMN DOCD_TIPO_TXT

ALTER TABLE [dbo].[DOCUMENTI] ADD 
	 DOCD_TIPO_TXT NUMERIC(1,0) NOT NULL CONSTRAINT [DF_DOCUMENTI_DOCD_TIPO_TXT] DEFAULT (1)
go
