
--- AGGIUNTA NUOVI CAMPI IN TABELLA licenze
ALTER TABLE [dbo].[U_LIC_AN] ADD
	AZI_AAVIS varchar(4) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_LIC_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_LIC_AN_AZI_AAVIS] DEFAULT ('') FOR [AZI_AAVIS]
go

UPDATE U_LIC_AN SET AZI_AAVIS = ''
