
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_CTRLCCO BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_CTRLCCO] DEFAULT (0) FOR [AZI_CTRLCCO]
GO

UPDATE U_AZI_PB SET AZI_CTRLCCO = 0
