
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[RICHIEST_DD] ADD 
	 SOG_STATO  [VARCHAR] (3) COLLATE Latin1_General_CI_AS NULL,
	 SOG_SEDELA [VARCHAR] (40) COLLATE Latin1_General_CI_AS NULL,
	 SOG_QTASOG [numeric] (3, 0)  NULL,
	 SOG_ANNOTA [TEXT] COLLATE Latin1_General_CI_AS NULL,
	 SOG_ANNRIS [TEXT] COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[RICHIEST_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_RICHIEST_DD_SOG_QTASOG] DEFAULT (0) FOR [SOG_QTASOG],
	CONSTRAINT [DF_RICHIEST_DD_SOG_STATO] DEFAULT ('') FOR [SOG_STATO],
	CONSTRAINT [DF_RICHIEST_DD_SOG_SEDELA] DEFAULT ('') FOR [SOG_SEDELA],
	CONSTRAINT [DF_RICHIEST_DD_SOG_ANNOTA] DEFAULT ('') FOR [SOG_ANNOTA],
	CONSTRAINT [DF_RICHIEST_DD_SOG_ANNRIS] DEFAULT ('') FOR [SOG_ANNRIS]
go

UPDATE RICHIEST_DD SET SOG_QTASOG = 0
UPDATE RICHIEST_DD SET SOG_STATO = ''
UPDATE RICHIEST_DD SET SOG_SEDELA = ''
UPDATE RICHIEST_DD SET SOG_ANNOTA = ''
UPDATE RICHIEST_DD SET SOG_ANNRIS = ''
