
ALTER TABLE [dbo].[U_PRD_DS] ADD
	PRS_CTRL01 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PRS_CTRL02 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PRS_CTRL03 varchar (2) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DS] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DS_PRS_CTRL01] DEFAULT ('') FOR [PRS_CTRL01],
	CONSTRAINT [DF_U_PRD_DS_PRS_CTRL02] DEFAULT ('') FOR [PRS_CTRL02],
	CONSTRAINT [DF_U_PRD_DS_PRS_CTRL03] DEFAULT ('') FOR [PRS_CTRL03]
go

UPDATE U_PRD_DS SET PRS_CTRL01 = ''
UPDATE U_PRD_DS SET PRS_CTRL02 = ''
UPDATE U_PRD_DS SET PRS_CTRL03 = ''




