/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_RAP_SP] ADD 
	RAP_NUMADD NUMERIC(7,2) NULL,
	RAP_NUMADM NUMERIC(7,2) NULL,
	RAP_NUMPHA NUMERIC(5,2) NULL,
	RAP_NUMRES NUMERIC(6,2) NULL,
	RAP_NUMVIS NUMERIC(6,2) NULL,
	RAP_NUMGRA NUMERIC(6,2) NULL,
	RAP_NUMSPN NUMERIC(6,2) NULL,
	RAP_NUMSPS NUMERIC(6,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_RAP_SP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMADD] DEFAULT (0) FOR [RAP_NUMADD],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMADM] DEFAULT (0) FOR [RAP_NUMADM],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMPHA] DEFAULT (0) FOR [RAP_NUMPHA],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMRES] DEFAULT (0) FOR [RAP_NUMRES],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMVIS] DEFAULT (0) FOR [RAP_NUMVIS],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMGRA] DEFAULT (0) FOR [RAP_NUMGRA],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMSPN] DEFAULT (0) FOR [RAP_NUMSPN],
	CONSTRAINT [DF_U_RAP_SP_RAP_NUMSPS] DEFAULT (0) FOR [RAP_NUMSPS]
go

UPDATE U_RAP_SP SET RAP_NUMADD = 0
UPDATE U_RAP_SP SET RAP_NUMADM = 0
UPDATE U_RAP_SP SET RAP_NUMPHA = 0
UPDATE U_RAP_SP SET RAP_NUMRES = 0
UPDATE U_RAP_SP SET RAP_NUMVIS = 0
UPDATE U_RAP_SP SET RAP_NUMGRA = 0
UPDATE U_RAP_SP SET RAP_NUMSPN = 0
UPDATE U_RAP_SP SET RAP_NUMSPS = 0



