
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_NOLOGO BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_NOLOGO] DEFAULT (0) FOR [AZI_NOLOGO]
GO

UPDATE U_AZI_PB SET AZI_NOLOGO = 0