
ALTER TABLE [dbo].[U_PRD_D3] ADD 
 	 PR3_INMAGA bit NULL
go
ALTER TABLE [dbo].[U_PRD_D3] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D3_PR3_INMAGA] DEFAULT (0) FOR [PR3_INMAGA]
go

UPDATE U_PRD_D3 SET PR3_INMAGA = 0
