/* 
**************************************************************
CAMPI PER LA GESTIONE DELLE DISTINTE RID
**************************************************************
*/



ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_FLRID BIT NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_FLRID] DEFAULT (0)
GO




ALTER TABLE [dbo].[U_ANA_CL] ADD 
	 CLI_CODDES varchar(15) COLLATE Latin1_General_CI_AS NULL,
	 CLI_DTMAND varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 CLI_CODRIF varchar(15) COLLATE Latin1_General_CI_AS NULL,
	 CLI_IDMAND varchar(25) COLLATE Latin1_General_CI_AS NULL,
	 CLI_NOTRID varchar(80) COLLATE Latin1_General_CI_AS NULL,
	 CLI_GGRID varchar(02) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ANA_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ANA_CL_CLI_CODDES] DEFAULT ('') FOR [CLI_CODDES],
	CONSTRAINT [DF_U_ANA_CL_CLI_DTMAND] DEFAULT ('') FOR [CLI_DTMAND],
	CONSTRAINT [DF_U_ANA_CL_CLI_CODRIF] DEFAULT ('') FOR [CLI_CODRIF],
	CONSTRAINT [DF_U_ANA_CL_CLI_IDMAND] DEFAULT ('') FOR [CLI_IDMAND],
	CONSTRAINT [DF_U_ANA_CL_CLI_NOTRID] DEFAULT ('') FOR [CLI_NOTRID],
	CONSTRAINT [DF_U_ANA_CL_CLI_GGRID] DEFAULT ('') FOR [CLI_GGRID]
go

UPDATE U_ANA_CL SET CLI_CODDES = ''
UPDATE U_ANA_CL SET CLI_DTMAND = ''
UPDATE U_ANA_CL SET CLI_CODRIF = ''
UPDATE U_ANA_CL SET CLI_IDMAND = ''
UPDATE U_ANA_CL SET CLI_NOTRID = ''
UPDATE U_ANA_CL SET CLI_GGRID = ''
