
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[MOV_CONT] ADD 
	 MOV_EXTRA_NUMDOC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_EXTRA_DATDOC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_EXTRA_IMPDOC [numeric](15, 3) NULL,
	 MOV_EXTRA_SYSDOC varchar(10) COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CONT] WITH NOCHECK ADD 
	CONSTRAINT [DF_MOV_CONT_MOV_EXTRA_NUMDOC] DEFAULT (0) FOR [MOV_EXTRA_NUMDOC],
	CONSTRAINT [DF_MOV_CONT_MOV_EXTRA_DATDOC] DEFAULT (0) FOR [MOV_EXTRA_DATDOC],
	CONSTRAINT [DF_MOV_CONT_MOV_EXTRA_IMPDOC] DEFAULT (0) FOR [MOV_EXTRA_IMPDOC],
	CONSTRAINT [DF_MOV_CONT_MOV_EXTRA_SYSDOC] DEFAULT (0) FOR [MOV_EXTRA_SYSDOC]
go

UPDATE MOV_CONT SET MOV_EXTRA_NUMDOC = 0
UPDATE MOV_CONT SET MOV_EXTRA_DATDOC = 0
UPDATE MOV_CONT SET MOV_EXTRA_IMPDOC = 0
UPDATE MOV_CONT SET MOV_EXTRA_SYSDOC = 0