
--- AGGIUNTA NUOVI CAMPI IN TABELLA CARICHI DI PRODUZIONE PER GESTIONE BANCALI
ALTER TABLE [dbo].[PROD_CARICHI] ADD
	NUMBAN numeric(10) NULL,
	IDBANC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	STABAN varchar(2) COLLATE Latin1_General_CI_AS NULL,
	ALTBAN numeric(10,0) NULL, 
	LARBAN numeric(10,0) NULL, 
	PESBAN numeric(19,3) NULL,
	NUMPCK varchar(10) COLLATE Latin1_General_CI_AS NULL,
	DATPCK varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ORAPCK varchar(8) COLLATE Latin1_General_CI_AS NULL,
	FLGDDT bit NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[PROD_CARICHI] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROD_CARICHI_NUMBAN] DEFAULT (0) FOR [NUMBAN],
	CONSTRAINT [DF_PROD_CARICHI_IDBANC] DEFAULT ('') FOR [IDBANC],
	CONSTRAINT [DF_PROD_CARICHI_STABAN] DEFAULT ('') FOR [STABAN],
	CONSTRAINT [DF_PROD_CARICHI_ALTBAN] DEFAULT (0) FOR [ALTBAN],
	CONSTRAINT [DF_PROD_CARICHI_LARBAN] DEFAULT (0) FOR [LARBAN],
	CONSTRAINT [DF_PROD_CARICHI_PESBAN] DEFAULT (0) FOR [PESBAN],
	CONSTRAINT [DF_PROD_CARICHI_NUMPCK] DEFAULT ('') FOR [NUMPCK],
	CONSTRAINT [DF_PROD_CARICHI_DATPCK] DEFAULT ('') FOR [DATPCK],
	CONSTRAINT [DF_PROD_CARICHI_ORAPCK] DEFAULT ('') FOR [ORAPCK],
	CONSTRAINT [DF_PROD_CARICHI_FLGDDT] DEFAULT (0) FOR [FLGDDT]
go

UPDATE PROD_CARICHI SET NUMBAN = 0
UPDATE PROD_CARICHI SET IDBANC = ''
UPDATE PROD_CARICHI SET STABAN = ''
UPDATE PROD_CARICHI SET ALTBAN = 0
UPDATE PROD_CARICHI SET LARBAN = 0
UPDATE PROD_CARICHI SET PESBAN = 0
UPDATE PROD_CARICHI SET NUMPCK = ''
UPDATE PROD_CARICHI SET DATPCK = ''
UPDATE PROD_CARICHI SET ORAPCK = ''
UPDATE PROD_CARICHI SET FLGDDT = 0
