/* 
******************************************
INSERIMENTO CAMPI PER MAGGIORAZIONI PREZZO
******************************************
*/
ALTER TABLE [dbo].[U_BOL_TT] ADD 
	ORD_RIFCTL numeric (7,0) NULL,
	ORD_PAGCTL numeric (7,0) NULL
go

ALTER TABLE [dbo].[U_BOL_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_TT_ORD_RIFCTL] DEFAULT (0) FOR [ORD_RIFCTL],
	CONSTRAINT [DF_U_BOL_TT_ORD_PAGCTL] DEFAULT (0) FOR [ORD_PAGCTL]
go

UPDATE U_BOL_TT SET ORD_RIFCTL = 0 
UPDATE U_BOL_TT SET ORD_PAGCTL = 0 