/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	ART_CODF4 VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	ART_CODF5 VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	ART_NOTA4 VARCHAR(40) COLLATE Latin1_General_CI_AS NULL,
	ART_NOTA5 VARCHAR(40) COLLATE Latin1_General_CI_AS NULL,
	ART_PRZCO4 NUMERIC (17,6)  NULL,
	ART_PRZCO5 NUMERIC (17,6)  NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_CODF4] DEFAULT ('') FOR [ART_CODF4],
	CONSTRAINT [DF_U_ART_PR_ART_CODF5] DEFAULT ('') FOR [ART_CODF5],
	CONSTRAINT [DF_U_ART_PR_ART_NOTA4] DEFAULT ('') FOR [ART_NOTA4],
	CONSTRAINT [DF_U_ART_PR_ART_NOTA5] DEFAULT ('') FOR [ART_NOTA5],
	CONSTRAINT [DF_U_ART_PR_ART_PRZCO4] DEFAULT (0) FOR [ART_PRZCO4],	
	CONSTRAINT [DF_U_ART_PR_ART_PRZCO5] DEFAULT (0) FOR [ART_PRZCO5]	
go

UPDATE U_ART_PR SET ART_CODF4 = SPACE(10)
UPDATE U_ART_PR SET ART_CODF5 = SPACE(10)
UPDATE U_ART_PR SET ART_NOTA4 = SPACE(40)
UPDATE U_ART_PR SET ART_NOTA5 = SPACE(40)
UPDATE U_ART_PR SET ART_PRZCO4 = 0
UPDATE U_ART_PR SET ART_PRZCO5 = 0
