/*
*** NUOVO CAMPO PER GESTIONE BOLLO VIRTUALE PER LA FATTURAZIONE ELETTRONICA DA RIPORTARE SULLE FATTURE
*/


ALTER TABLE [DBO].[U_FAT_TT] ADD 
	ORD_BOVIRT NUMERIC(10,2) NOT NULL CONSTRAINT [DF_U_FAT_TT_ORD_BOVIRT] DEFAULT (0)
GO
