/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_BFO_TT] ADD 
	ORD_DTUSCITA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ORD_ORAUSCITA varchar(5) COLLATE Latin1_General_CI_AS NULL,
	ORD_TSCARICO numeric(5,0) NULL,
	ORD_TARGA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ORD_SOLOMOTR [bit] NULL
go

ALTER TABLE [dbo].[U_BFO_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BFO_TT_ORD_DTUSCITA] DEFAULT ('') FOR [ORD_DTUSCITA],
	CONSTRAINT [DF_U_BFO_TT_ORD_ORAUSCITA] DEFAULT ('') FOR [ORD_ORAUSCITA],
	CONSTRAINT [DF_U_BFO_TT_ORD_TSCARICO] DEFAULT (0) FOR [ORD_TSCARICO],
	CONSTRAINT [DF_U_BFO_TT_ORD_TARGA] DEFAULT ('') FOR [ORD_TARGA],
	CONSTRAINT [DF_U_BFO_TT_ORD_SOLOMOTR] DEFAULT (0) FOR [ORD_SOLOMOTR] 
go


UPDATE U_BFO_TT SET ORD_DTUSCITA  = '' 
UPDATE U_BFO_TT SET ORD_ORAUSCITA = '' 
UPDATE U_BFO_TT SET ORD_TSCARICO  = 0
UPDATE U_BFO_TT SET ORD_TARGA 	  = '' 
UPDATE U_BFO_TT SET ORD_SOLOMOTR  = '' 

