/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_BOL_DD] ADD 
	 ORD_CODMAT varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DESMAT varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 ORD_SPESSO numeric(3) NULL,
	 ORD_ALTEZZ numeric(5) NULL,
	 ORD_LUNGHE numeric(6) NULL,
	 ORD_NUMBOB numeric(6) NULL,
	 ORD_QTAKG numeric(11,2) NULL,
	 ORD_QTAMQ numeric(11,2) NULL,
	 ORD_QTAML numeric(11,2) NULL,
	 ORD_QTAKG1 numeric(11,2) NULL,
	 ORD_QTAMQ1 numeric(11,2) NULL,
	 ORD_QTAML1 numeric(11,2) NULL,
	 ORD_NUMPED numeric(8) NULL,
	 ORD_DATPED varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_SYSPED varchar(10) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_BOL_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_DD_ORD_CODMAT] DEFAULT ('') FOR [ORD_CODMAT],
	CONSTRAINT [DF_U_BOL_DD_ORD_DESMAT] DEFAULT ('') FOR [ORD_DESMAT],
	CONSTRAINT [DF_U_BOL_DD_ORD_SPESSO] DEFAULT (0) FOR [ORD_SPESSO],
	CONSTRAINT [DF_U_BOL_DD_ORD_ALTEZZ] DEFAULT (0) FOR [ORD_ALTEZZ],
	CONSTRAINT [DF_U_BOL_DD_ORD_LUNGHE] DEFAULT (0) FOR [ORD_LUNGHE],
	CONSTRAINT [DF_U_BOL_DD_ORD_NUMBOB] DEFAULT (0) FOR [ORD_NUMBOB],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAKG] DEFAULT (0) FOR [ORD_QTAKG],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAMQ] DEFAULT (0) FOR [ORD_QTAMQ],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAML] DEFAULT (0) FOR [ORD_QTAML],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAKG1] DEFAULT (0) FOR [ORD_QTAKG1],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAMQ1] DEFAULT (0) FOR [ORD_QTAMQ1],
	CONSTRAINT [DF_U_BOL_DD_ORD_QTAML1] DEFAULT (0) FOR [ORD_QTAML1],
	CONSTRAINT [DF_U_BOL_DD_ORD_NUMPED] DEFAULT (0) FOR [ORD_NUMPED],
	CONSTRAINT [DF_U_BOL_DD_ORD_DATPED] DEFAULT ('') FOR [ORD_DATPED],
	CONSTRAINT [DF_U_BOL_DD_ORD_SYSPED] DEFAULT ('') FOR [ORD_SYSPED]
go

UPDATE U_BOL_DD SET ORD_CODMAT = SPACE(3)
UPDATE U_BOL_DD SET ORD_DESMAT = SPACE(30)
UPDATE U_BOL_DD SET ORD_SPESSO = 0
UPDATE U_BOL_DD SET ORD_ALTEZZ = 0
UPDATE U_BOL_DD SET ORD_LUNGHE = 0
UPDATE U_BOL_DD SET ORD_NUMBOB = 0
UPDATE U_BOL_DD SET ORD_QTAKG = 0
UPDATE U_BOL_DD SET ORD_QTAMQ = 0
UPDATE U_BOL_DD SET ORD_QTAML = 0
UPDATE U_BOL_DD SET ORD_QTAKG1 = 0
UPDATE U_BOL_DD SET ORD_QTAMQ1 = 0
UPDATE U_BOL_DD SET ORD_QTAML1 = 0
UPDATE U_BOL_DD SET ORD_NUMPED = 0
UPDATE U_BOL_DD SET ORD_DATPED = SPACE(10)
UPDATE U_BOL_DD SET ORD_SYSPED = SPACE(10)
