
      
ALTER TABLE [DBO].[IMPIANTI_DD] ADD 
	SELEZI bit NOT NULL CONSTRAINT [DF_IMPIANTI_DD_SELEZI] DEFAULT (0)
GO


ALTER TABLE [dbo].[IMPIANTI_DD] ADD 
	LINKINTE varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_DD_LINKINTE] DEFAULT ('')
GO


