
/**/
ALTER TABLE [dbo].[U_CLI_AN] ADD 
	[CLI_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_CLI_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CLI_AN_CLI_FLGTRA] DEFAULT (0) FOR [CLI_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	[ART_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_FLGTRA] DEFAULT (0) FOR [ART_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_PDV_CA] ADD 
	[CAS_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_PDV_CA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PDV_CA_CAS_FLGTRA] DEFAULT (0) FOR [CAS_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_PDV_OP] ADD 
	[CAS_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_PDV_OP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PDV_OP_CAS_FLGTRA] DEFAULT (0) FOR [CAS_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_CAN_CA] ADD 
	[CAS_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_CAN_CA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CAN_CA_CAS_FLGTRA] DEFAULT (0) FOR [CAS_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_MAG_MO] ADD 
	[MOV_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_FLGTRA] DEFAULT (0) FOR [MOV_FLGTRA]
go
/**/ALTER TABLE [dbo].[U_FAT_TT] ADD 
	[ORD_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_FAT_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAT_TT_ORD_FLGTRA] DEFAULT (0) FOR [ORD_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_BOL_TT] ADD 
	[ORD_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_BOL_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_TT_ORD_FLGTRA] DEFAULT (0) FOR [ORD_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_ORD_TT] ADD 
	[ORD_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_ORD_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORD_TT_ORD_FLGTRA] DEFAULT (0) FOR [ORD_FLGTRA]
go
/**/
ALTER TABLE [dbo].[U_ORF_TT] ADD 
	[ORD_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_ORF_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORF_TT_ORD_FLGTRA] DEFAULT (0) FOR [ORD_FLGTRA]
go
