
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_ORD_POLIEC	BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_ORD_POLIEC] DEFAULT (0) FOR [AZI_ORD_POLIEC]
GO

UPDATE U_AZI_PB SET AZI_ORD_POLIEC	= 0

