
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_NODDT BIT NULL,
	PR5_DATVAR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR5_ORAVAR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR5_CODOPV varchar(20) COLLATE Latin1_General_CI_AS NULL,
	PR5_DESOPV varchar(25) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_NODDT] DEFAULT (0) FOR [PR5_NODDT],
	CONSTRAINT [DF_U_PRD_D5_PR5_DATVAR] DEFAULT ('') FOR [PR5_DATVAR],
	CONSTRAINT [DF_U_PRD_D5_PR5_ORAVAR] DEFAULT ('') FOR [PR5_ORAVAR],
	CONSTRAINT [DF_U_PRD_D5_PR5_CODOPV] DEFAULT ('') FOR [PR5_CODOPV],
	CONSTRAINT [DF_U_PRD_D5_PR5_DESOPV] DEFAULT ('') FOR [PR5_DESOPV]
go

UPDATE U_PRD_D5 SET PR5_NODDT = 0
UPDATE U_PRD_D5 SET PR5_DATVAR = ''
UPDATE U_PRD_D5 SET PR5_ORAVAR = ''
UPDATE U_PRD_D5 SET PR5_CODOPV = ''
UPDATE U_PRD_D5 SET PR5_DESOPV = ''

