ALTER TABLE [dbo].[U_ART_PR] ADD 
	ART_FORMUL varchar(1) COLLATE Latin1_General_CI_AS NULL,
	ART_GRAMMA numeric(17,1) NULL,
	ART_TOLGRA numeric(17,1) NULL 
go

ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_FORMUL] DEFAULT ('') FOR [ART_FORMUL],
	CONSTRAINT [DF_U_ART_PR_ART_GRAMMA] DEFAULT (0)  FOR [ART_GRAMMA],
	CONSTRAINT [DF_U_ART_PR_ART_TOLGRA] DEFAULT (0)  FOR [ART_TOLGRA]
go

UPDATE U_ART_PR SET ART_FORMUL = ''
UPDATE U_ART_PR SET ART_GRAMMA = 0
UPDATE U_ART_PR SET ART_TOLGRA = 0