
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	MAG_CODCTL varchar(16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_GG_MAG_CODCTL] DEFAULT ('')
go

ALTER TABLE [dbo].[U_MAG_MO] ADD 
	MOV_CODCTL varchar(16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_MO_MOV_CODCTL] DEFAULT ('')
go
