/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA U_MAG_GG
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	 MAG_FLGCEL [bit] NULL,
	 MAG_SERBOL varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MAG_AAPROD numeric(04) NULL,
	 MAG_SERNUM varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MAG_NUMEDA numeric(09) NULL,
	 MAG_NUMEAL numeric(09) NULL,
	 MAG_CBFISC varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_GG_MAG_FLGCEL] DEFAULT (0) FOR [MAG_FLGCEL],
	CONSTRAINT [DF_U_MAG_GG_MAG_SERBOL] DEFAULT ('') FOR [MAG_SERBOL],
	CONSTRAINT [DF_U_MAG_GG_MAG_AAPROD] DEFAULT (0) FOR [MAG_AAPROD],
	CONSTRAINT [DF_U_MAG_GG_MAG_SERNUM] DEFAULT ('') FOR [MAG_SERNUM],
	CONSTRAINT [DF_U_MAG_GG_MAG_NUMEDA] DEFAULT (0) FOR [MAG_NUMEDA],
	CONSTRAINT [DF_U_MAG_GG_MAG_NUMEAL] DEFAULT (0) FOR [MAG_NUMEAL],
	CONSTRAINT [DF_U_MAG_GG_MAG_CBFISC] DEFAULT ('') FOR [MAG_CBFISC]
go

UPDATE U_MAG_GG SET MAG_FLGCEL = 0
UPDATE U_MAG_GG SET MAG_SERBOL = SPACE(03)
UPDATE U_MAG_GG SET MAG_AAPROD = 0
UPDATE U_MAG_GG SET MAG_SERNUM = SPACE(03)
UPDATE U_MAG_GG SET MAG_NUMEDA = 0
UPDATE U_MAG_GG SET MAG_NUMEAL = 0
UPDATE U_MAG_GG SET MAG_CBFISC = SPACE(50)

/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA U_MAG_CP
**************************************************************
*/

ALTER TABLE [dbo].[U_MAG_CP] ADD 
	 MAG_FLGCEL [bit] NULL,
	 MAG_SERBOL varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MAG_AAPROD numeric(04) NULL,
	 MAG_SERNUM varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MAG_NUMEDA numeric(09) NULL,
	 MAG_NUMEAL numeric(09) NULL,
	 MAG_CBFISC varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_CP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CP_MAG_FLGCEL] DEFAULT (0) FOR [MAG_FLGCEL],
	CONSTRAINT [DF_U_MAG_CP_MAG_SERBOL] DEFAULT ('') FOR [MAG_SERBOL],
	CONSTRAINT [DF_U_MAG_CP_MAG_AAPROD] DEFAULT (0) FOR [MAG_AAPROD],
	CONSTRAINT [DF_U_MAG_CP_MAG_SERNUM] DEFAULT ('') FOR [MAG_SERNUM],
	CONSTRAINT [DF_U_MAG_CP_MAG_NUMEDA] DEFAULT (0) FOR [MAG_NUMEDA],
	CONSTRAINT [DF_U_MAG_CP_MAG_NUMEAL] DEFAULT (0) FOR [MAG_NUMEAL],
	CONSTRAINT [DF_U_MAG_CP_MAG_CBFISC] DEFAULT ('') FOR [MAG_CBFISC]
go

UPDATE U_MAG_CP SET MAG_FLGCEL = 0
UPDATE U_MAG_CP SET MAG_SERBOL = SPACE(03)
UPDATE U_MAG_CP SET MAG_AAPROD = 0
UPDATE U_MAG_CP SET MAG_SERNUM = SPACE(03)
UPDATE U_MAG_CP SET MAG_NUMEDA = 0
UPDATE U_MAG_CP SET MAG_NUMEAL = 0
UPDATE U_MAG_CP SET MAG_CBFISC = SPACE(50)
