

ALTER TABLE [DBO].[U_OFF_TT] ADD 
	ORD_PROSPECT BIT NULL
GO

ALTER TABLE [DBO].[U_OFF_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_OFF_TT_ORD_PROSPECT] DEFAULT (0) FOR [ORD_PROSPECT]
GO

UPDATE U_OFF_TT SET ORD_PROSPECT = 0
