
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_BFO_LE] ADD 
	 LEG_CODSRI varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSRI numeric (18,2) NULL,
	 LEG_CODSPT varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSPT numeric (18,2) NULL,
	 LEG_CODSIN varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSIN numeric (18,2) NULL,
	 LEG_CODSME varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSME numeric (18,2) NULL,
	 LEG_CODSIM varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSIM numeric (18,2) NULL,
	 LEG_CODSBO varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSBO numeric (18,2) NULL,
	 LEG_CODSVA varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSVA numeric (18,2) NULL,
	 LEG_CODSCV varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALSCV numeric (18,2) NULL,
	 LEG_CODTRI varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALTRI numeric (18,2) NULL,
	 LEG_CODACQ varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 LEG_VALACQ numeric (18,2) NULL,
	 LEG_PERSCO numeric (14,3) NULL,
	 LEG_TIPRIP varchar(5) COLLATE Latin1_General_CI_AS NULL

	 
go
ALTER TABLE [dbo].[U_BFO_LE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSRI] DEFAULT ('') FOR [LEG_CODSRI],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSRI] DEFAULT ('0') FOR [LEG_VALSRI],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSPT] DEFAULT ('') FOR [LEG_CODSPT],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSPT] DEFAULT ('0') FOR [LEG_VALSPT],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSIN] DEFAULT ('') FOR [LEG_CODSIN],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSIN] DEFAULT ('0') FOR [LEG_VALSIN],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSME] DEFAULT ('') FOR [LEG_CODSME],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSME] DEFAULT ('0') FOR [LEG_VALSME],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSIM] DEFAULT ('') FOR [LEG_CODSIM],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSIM] DEFAULT ('0') FOR [LEG_VALSIM],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSBO] DEFAULT ('') FOR [LEG_CODSBO],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSBO] DEFAULT ('0') FOR [LEG_VALSBO],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSVA] DEFAULT ('') FOR [LEG_CODSVA],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSVA] DEFAULT ('0') FOR [LEG_VALSVA],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODSCV] DEFAULT ('') FOR [LEG_CODSCV],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALSCV] DEFAULT ('0') FOR [LEG_VALSCV],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODTRI] DEFAULT ('') FOR [LEG_CODTRI],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALTRI] DEFAULT ('0') FOR [LEG_VALTRI],
	CONSTRAINT [DF_U_BFO_LE_LEG_CODACQ] DEFAULT ('') FOR [LEG_CODACQ],
	CONSTRAINT [DF_U_BFO_LE_LEG_VALACQ] DEFAULT ('0') FOR [LEG_VALACQ],
	CONSTRAINT [DF_U_BFO_LE_LEG_TIPRIP] DEFAULT ('') FOR [LEG_TIPRIP],
	CONSTRAINT [DF_U_BFO_LE_LEG_PERSCO] DEFAULT ('0') FOR [LEG_PERSCO]
	

go


UPDATE U_BFO_LE SET LEG_CODSRI = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSRI = 0

UPDATE U_BFO_LE SET LEG_CODSPT = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSPT = 0

UPDATE U_BFO_LE SET LEG_CODSIN = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSIN = 0

UPDATE U_BFO_LE SET LEG_CODSME = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSME = 0

UPDATE U_BFO_LE SET LEG_CODSIM = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSIM = 0

UPDATE U_BFO_LE SET LEG_CODSBO = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSBO = 0

UPDATE U_BFO_LE SET LEG_CODSVA = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSVA = 0

UPDATE U_BFO_LE SET LEG_CODSCV = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALSCV = 0

UPDATE U_BFO_LE SET LEG_CODTRI = SPACE(13)
UPDATE U_BFO_LE SET LEG_VALTRI = 0

UPDATE U_BFO_LE SET LEG_TIPRIP = SPACE(13)
UPDATE U_BFO_LE SET LEG_PERSCO = 0
