
/*
*** Conti contabili di supporto per il CONFIGURATORE AQUARIUS
*/

ALTER TABLE [DBO].[CONFIGURATORE_AQUARIUS] ADD 
	AZI_CAUSSP varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONFIGURATORE_AQUARIUS_AZI_CAUSSP] DEFAULT ('')
GO

