--- AGGIUNTA NUOVI CAMPI 
---   1.PREVISTO TAGLIO (IL PRIMO TAGLIO PREVISTO A LIVELLO DI FASCIA)
---   2.PREVISTA CONSEGNA (LA PRIMA CONSEGNA PREVISTA A LIVELLO DI FASCIA)
---   3.RICHIESTA CONSEGNA (LA PRIMA CONSEGNA RICHIESTA DAL CLIENTE A LIVELLO DI FASCIA)

ALTER TABLE [dbo].[U_PRD_D2] ADD 
 	PR2_PRVTAG VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	PR2_PRVCON VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	PR2_RICCON VARCHAR(10) COLLATE Latin1_General_CI_AS NULL	
go

ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D2_PR2_PRVTAG] DEFAULT ('') FOR [PR2_PRVTAG],
	CONSTRAINT [DF_U_PRD_D2_PR2_PRVCON] DEFAULT ('') FOR [PR2_PRVCON],
	CONSTRAINT [DF_U_PRD_D2_PR2_RICCON] DEFAULT ('') FOR [PR2_RICCON]
go

UPDATE U_PRD_D2 SET PR2_PRVTAG = ''
UPDATE U_PRD_D2 SET PR2_PRVCON = ''
UPDATE U_PRD_D2 SET PR2_RICCON = ''
