
ALTER TABLE [dbo].[U_PRD_DR] ADD
	PRR_CTRLHS numeric(4,0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_PR4_CTRLHS] DEFAULT (0) FOR [PRR_CTRLHS]
go

UPDATE U_PRD_DR SET PRR_CTRLHS = 0


