/*    
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_PRD_HY] ADD 
 	 GRP_PROD varchar(10) COLLATE Latin1_General_CI_AS NULL,
 	 MICROFORATO varchar(1) COLLATE Latin1_General_CI_AS NULL,
 	 ADESIVO varchar(16) COLLATE Latin1_General_CI_AS NULL,
 	 DESADE varchar(50) COLLATE Latin1_General_CI_AS NULL,
 	 CODBOB varchar(16) COLLATE Latin1_General_CI_AS NULL,
 	 DESBOB varchar(50) COLLATE Latin1_General_CI_AS NULL,
 	 QTA_ADESIVO numeric(17,6) NULL,
 	 DTPRPR varchar(10) COLLATE Latin1_General_CI_AS NULL,
 	 DTCEFF varchar(10) COLLATE Latin1_General_CI_AS NULL,
 	 CODART varchar(30) COLLATE Latin1_General_CI_AS NULL,
 	 DESART varchar(50) COLLATE Latin1_General_CI_AS NULL,
 	 GGDIFF numeric(3)   NULL,
 	 MINUTI numeric(10)   NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRD_HY] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_HY_GRP_PROD] DEFAULT ('') FOR [GRP_PROD],
	CONSTRAINT [DF_U_PRD_HY_MICROFORATO] DEFAULT ('') FOR [MICROFORATO],
	CONSTRAINT [DF_U_PRD_HY_ADESIVO] DEFAULT ('') FOR [ADESIVO],
	CONSTRAINT [DF_U_PRD_HY_DESADE] DEFAULT ('') FOR [DESADE],
	CONSTRAINT [DF_U_PRD_HY_CODBOB] DEFAULT ('') FOR [CODBOB],
	CONSTRAINT [DF_U_PRD_HY_DESBOB] DEFAULT ('') FOR [DESBOB],
	CONSTRAINT [DF_U_PRD_HY_QTA_ADESIVO] DEFAULT (0) FOR [QTA_ADESIVO],
	CONSTRAINT [DF_U_PRD_HY_DTPRPR] DEFAULT ('') FOR [DTPRPR],
	CONSTRAINT [DF_U_PRD_HY_DTCEFF] DEFAULT ('') FOR [DTCEFF],
	CONSTRAINT [DF_U_PRD_HY_CODART] DEFAULT ('') FOR [CODART],
	CONSTRAINT [DF_U_PRD_HY_DESART] DEFAULT ('') FOR [DESART],
	CONSTRAINT [DF_U_PRD_HY_GGDIFF] DEFAULT (0) FOR [GGDIFF],
	CONSTRAINT [DF_U_PRD_HY_MINUTI] DEFAULT (0) FOR [MINUTI]
go

UPDATE U_PRD_HY SET GRP_PROD = ''
UPDATE U_PRD_HY SET MICROFORATO = ''
UPDATE U_PRD_HY SET ADESIVO = ''
UPDATE U_PRD_HY SET CODBOB = ''
UPDATE U_PRD_HY SET DESBOB = ''
UPDATE U_PRD_HY SET QTA_ADESIVO = 0
UPDATE U_PRD_HY SET DTPRPR = ''
UPDATE U_PRD_HY SET DTCEFF = ''
UPDATE U_PRD_HY SET CODART = ''
UPDATE U_PRD_HY SET DESART = ''
UPDATE U_PRD_HY SET GGDIFF = 0
UPDATE U_PRD_HY SET MINUTI = 0

