
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_CON_TR] ADD 
	 CON_ALTTRA [numeric](18, 0) NULL,
	 CON_ALTRIC [numeric](18, 0) NULL,
	 CON_FPRTRA [numeric](18, 0) NULL,
	 CON_FPRRIC [numeric](18, 0) NULL,
	 CON_GGGTRA [numeric](18, 0) NULL,
	 CON_GGGRIC [numeric](18, 0) NULL,
	 CON_GDATRA [numeric](18, 0) NULL,
	 CON_GDARIC [numeric](18, 0) NULL,
	 CON_GANTRA [numeric](18, 0) NULL,
	 CON_GANRIC [numeric](18, 0) NULL,
	 CON_GPRTRA [numeric](18, 0) NULL,
	 CON_GPRRIC [numeric](18, 0) NULL,
	 CON_CALTRA [numeric](18, 0) NULL,
	 CON_CALRIC [numeric](18, 0) NULL,
	 CON_CAMTRA [numeric](18, 0) NULL,
	 CON_CAMRIC [numeric](18, 0) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_CON_TR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CON_TR_CON_ALTTRA] DEFAULT (0) FOR [CON_ALTTRA],
	CONSTRAINT [DF_U_CON_TR_CON_ALTRIC] DEFAULT (0) FOR [CON_ALTRIC],
	CONSTRAINT [DF_U_CON_TR_CON_FPRTRA] DEFAULT (0) FOR [CON_FPRTRA],
	CONSTRAINT [DF_U_CON_TR_CON_FPRRIC] DEFAULT (0) FOR [CON_FPRRIC],
	CONSTRAINT [DF_U_CON_TR_CON_GGGTRA] DEFAULT (0) FOR [CON_GGGTRA],
	CONSTRAINT [DF_U_CON_TR_CON_GGGRIC] DEFAULT (0) FOR [CON_GGGRIC],
	CONSTRAINT [DF_U_CON_TR_CON_GDATRA] DEFAULT (0) FOR [CON_GDATRA],
	CONSTRAINT [DF_U_CON_TR_CON_GDARIC] DEFAULT (0) FOR [CON_GDARIC],
	CONSTRAINT [DF_U_CON_TR_CON_GANTRA] DEFAULT (0) FOR [CON_GANTRA],
	CONSTRAINT [DF_U_CON_TR_CON_GANRIC] DEFAULT (0) FOR [CON_GANRIC],
	CONSTRAINT [DF_U_CON_TR_CON_GPRTRA] DEFAULT (0) FOR [CON_GPRTRA],
	CONSTRAINT [DF_U_CON_TR_CON_GPRRIC] DEFAULT (0) FOR [CON_GPRRIC],
	CONSTRAINT [DF_U_CON_TR_CON_CALTRA] DEFAULT (0) FOR [CON_CALTRA],
	CONSTRAINT [DF_U_CON_TR_CON_CALRIC] DEFAULT (0) FOR [CON_CALRIC]
	CONSTRAINT [DF_U_CON_TR_CON_CAMTRA] DEFAULT (0) FOR [CON_CAMTRA],
	CONSTRAINT [DF_U_CON_TR_CON_CAMRIC] DEFAULT (0) FOR [CON_CAMRIC]
go

UPDATE U_CON_TR SET CON_ALTTRA = 0
UPDATE U_CON_TR SET CON_ALTRIC = 0
UPDATE U_CON_TR SET CON_FPRTRA = 0
UPDATE U_CON_TR SET CON_FPRRIC = 0
UPDATE U_CON_TR SET CON_GGGTRA = 0
UPDATE U_CON_TR SET CON_GGGRIC = 0
UPDATE U_CON_TR SET CON_GDATRA = 0
UPDATE U_CON_TR SET CON_GDARIC = 0
UPDATE U_CON_TR SET CON_GANTRA = 0
UPDATE U_CON_TR SET CON_GANRIC = 0
UPDATE U_CON_TR SET CON_GPRTRA = 0
UPDATE U_CON_TR SET CON_GPRRIC = 0
UPDATE U_CON_TR SET CON_CALTRA = 0
UPDATE U_CON_TR SET CON_CALRIC = 0
UPDATE U_CON_TR SET CON_CAMTRA = 0
UPDATE U_CON_TR SET CON_CAMRIC = 0
