
--- AGGIUNTA NUOVI CAMPI IN TABELLA CARICHI DI PRODUZIONE PER GESTIONE BANCALI
ALTER TABLE [dbo].[PROD_CARICHI] ADD
	INMAGA BIT NULL,
	PESPCK numeric(19,3) NULL,
	LOTPRD varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ALTPCK numeric(10,0) NULL,
	LARPCK numeric(10,0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[PROD_CARICHI] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROD_CARICHI_INMAGA] DEFAULT (0) FOR [INMAGA],
	CONSTRAINT [DF_PROD_CARICHI_PESPCK] DEFAULT (0) FOR [PESPCK],
	CONSTRAINT [DF_PROD_CARICHI_LOTPRD] DEFAULT ('') FOR [LOTPRD],
	CONSTRAINT [DF_PROD_CARICHI_ALTPCK] DEFAULT (0) FOR [ALTPCK],
	CONSTRAINT [DF_PROD_CARICHI_LARPCK] DEFAULT (0) FOR [LARPCK]
go

UPDATE PROD_CARICHI SET INMAGA = 0
UPDATE PROD_CARICHI SET PESPCK = 0
UPDATE PROD_CARICHI SET LOTPRD = ''
UPDATE PROD_CARICHI SET ALTPCK = 0
UPDATE PROD_CARICHI SET LARPCK = 0
