
ALTER TABLE [dbo].[U_CLI_AN] ALTER COLUMN
	 CLI_RAGLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO


ALTER TABLE [dbo].[U_CLI_AN] ALTER COLUMN
	 CLI_RGLEG2 varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_CLI_AN] ALTER COLUMN
	 CLI_INDLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_CLI_AN] ALTER COLUMN
	 CLI_LOCLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

