
ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAORD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTADEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAOLD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAFAT] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAKG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAMQ] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAML] NUMERIC(12,4) NULL
GO






ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAKG1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAMQ1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAML1] NUMERIC(12,4) NULL
GO



ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAKGI] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	 [ORD_QTAKGE] NUMERIC(12,4) NULL
GO




















