/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[AUTORIZZAZIONI] ADD 
	TES_CLIENTI   [bit]  NULL ,
	TES_FORNITORI [bit]  NULL ,
	TES_STIPENDI  [bit]  NULL , 
	TES_RIBA      [bit]  NULL ,    
	TES_F24       [bit]  NULL , 
	TES_CBI       [bit]  NULL 
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[AUTORIZZAZIONI] WITH NOCHECK ADD 
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_CLIENTI] DEFAULT (0) FOR [TES_CLIENTI],
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_FORNITORI] DEFAULT (0) FOR [TES_FORNITORI],
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_STIPENDI] DEFAULT (0) FOR [TES_STIPENDI],
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_RIBA] DEFAULT (0) FOR [TES_RIBA],
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_F24] DEFAULT (0) FOR [TES_F24],
	CONSTRAINT [DF_AUTORIZZAZIONI_TES_CBI] DEFAULT (0) FOR [TES_CBI]
go

UPDATE AUTORIZZAZIONI SET TES_CLIENTI = 0
UPDATE AUTORIZZAZIONI SET TES_FORNITORI = 0
UPDATE AUTORIZZAZIONI SET TES_STIPENDI = 0
UPDATE AUTORIZZAZIONI SET TES_RIBA = 0
UPDATE AUTORIZZAZIONI SET TES_F24 = 0
UPDATE AUTORIZZAZIONI SET TES_CBI = 0

go
