
/* 
******************************************
INSERIMENTO CAMPI PER MAGGIORAZIONI PREZZO
******************************************
*/
ALTER TABLE [dbo].[U_OFF_DD] ADD 
	ORD_EVASEL BIT NULL
go

ALTER TABLE [dbo].[U_OFF_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_OFF_DD_ORD_EVASEL] DEFAULT (0) FOR [ORD_EVASEL]
go

UPDATE U_OFF_DD SET ORD_EVASEL = 0


ALTER TABLE [dbo].[U_OFF_DD] ADD 
	ORD_TIPO varchar(1) COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[U_OFF_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_OFF_DD_ORD_TIPO] DEFAULT ('') FOR [ORD_TIPO]
go

UPDATE U_OFF_DD SET ORD_TIPO = ''

