--- ALTERAZIONE DIMENSIONE DELLA DATA
ALTER TABLE [dbo].[U_PRD_D4] ALTER COLUMN
	 PR4_DATAVA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO


--- ALTERAZIONE DIMENSIONE DELL'ORA
ALTER TABLE [dbo].[U_PRD_D4] ALTER COLUMN
	 PR4_ORAAVA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO


--- ALTERAZIONE DIMENSIONE DEL FORMATO TAGLIO
ALTER TABLE [dbo].[U_PRD_D4] ALTER COLUMN
	 PR4_FORTAG varchar(100) COLLATE Latin1_General_CI_AS NULL
GO
