

ALTER TABLE [DBO].[U_LIF_BA] ADD 
	LIS_SCONTI bit NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_SCONTI] DEFAULT (0),
	LIS_MAGGIOR bit NOT NULL CONSTRAINT [DF_U_LIF_BA_LIS_MAGGIOR] DEFAULT (0)
GO

UPDATE U_LIF_BA SET LIS_SCONTI =  0 
UPDATE U_LIF_BA SET LIS_MAGGIOR =  0 