--- CANCELLAZIONE  CAMPO
ALTER TABLE [dbo].[U_PRD_D3] DROP
	 CONSTRAINT DF_U_PRD_D3_PR3_CODART 
GO

ALTER TABLE [dbo].[U_PRD_D3] DROP
	 COLUMN PR3_CODART 
GO



--- CANCELLAZIONE  CAMPO
ALTER TABLE [dbo].[U_PRD_D3] DROP
	 CONSTRAINT DF_U_PRD_D3_PR3_DESART 
GO

ALTER TABLE [dbo].[U_PRD_D3] DROP
	 COLUMN PR3_DESART 
GO



--- CANCELLAZIONE  CAMPO
ALTER TABLE [dbo].[U_PRD_D3] DROP
	 CONSTRAINT DF_U_PRD_D3_PR3_UNIMIS 
GO

ALTER TABLE [dbo].[U_PRD_D3] DROP
	 COLUMN PR3_UNIMIS 
GO
