

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	azi_paratree bit NOT NULL CONSTRAINT [DF_U_AZI_PB_azi_paratree] DEFAULT (0)
GO

-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1 (TRUE)
UPDATE U_AZI_PB SET azi_paratree =  0 
