
-- AGGIORNAMENTO DIMENSIONE CAMPI PER LA QUANTITA' IN METRI CUBI

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMC1] NUMERIC(17,3) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMC] NUMERIC(17,3) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMCE] NUMERIC(17,3) NULL
GO
