
ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_COSLAI NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_COSLAE NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_COSMAT NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_COSATR NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_COSTO NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_RICLAI NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_RICLAE NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_RICMAT NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_RICATR NUMERIC(19,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_TT]  ALTER COLUMN  
	DIT_PREZZO NUMERIC(19,6) NULL
GO
