
ALTER TABLE [dbo].[STRUTTURA_LISTINI] ADD 
	LIS_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	LIS_RAGSOC varchar(150) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[STRUTTURA_LISTINI] WITH NOCHECK ADD
	CONSTRAINT [DF_STRUTTURA_LISTINI_LIS_CODCLI] DEFAULT ('') FOR [LIS_CODCLI],
	CONSTRAINT [DF_STRUTTURA_LISTINI_LIS_RAGSOC] DEFAULT ('') FOR [LIS_RAGSOC]

go

UPDATE STRUTTURA_LISTINI SET LIS_CODCLI = ''
UPDATE STRUTTURA_LISTINI SET LIS_RAGSOC = ''