
ALTER TABLE [dbo].[U_PRD_D4] ADD 
	PR4_DATVAR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR4_ORAVAR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR4_CODOPV varchar(20) COLLATE Latin1_General_CI_AS NULL,
	PR4_DESOPV varchar(25) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_DATVAR] DEFAULT ('') FOR [PR4_DATVAR],
	CONSTRAINT [DF_U_PRD_D4_PR4_ORAVAR] DEFAULT ('') FOR [PR4_ORAVAR],
	CONSTRAINT [DF_U_PRD_D4_PR4_CODOPV] DEFAULT ('') FOR [PR4_CODOPV],
	CONSTRAINT [DF_U_PRD_D4_PR4_DESOPV] DEFAULT ('') FOR [PR4_DESOPV]
go

UPDATE U_PRD_D4 SET PR4_DATVAR = ''
UPDATE U_PRD_D4 SET PR4_ORAVAR = ''
UPDATE U_PRD_D4 SET PR4_CODOPV = ''
UPDATE U_PRD_D4 SET PR4_DESOPV = ''

