
ALTER TABLE [dbo].[AUTORIZZAZIONI] ADD 
	DOC_TIPIDOC varchar(254) COLLATE Latin1_General_CI_AS NULL,
	DOC_DEFADOC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ANAART_VIS [bit] NULL ,
	ANAART_INS [bit] NULL ,
	ANAART_MOD [bit] NULL ,
	ANAART_ANN [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[AUTORIZZAZIONI] WITH NOCHECK ADD 
	CONSTRAINT [DF_AUTORIZZAZIONI_DOC_TIPIDOC] DEFAULT ('') FOR [DOC_TIPIDOC],
	CONSTRAINT [DF_AUTORIZZAZIONI_DOC_DEFADOC] DEFAULT ('') FOR [DOC_DEFADOC],
	CONSTRAINT [DF_AUTORIZZAZIONI_ANAART_VIS] DEFAULT (0) FOR [ANAART_VIS],
	CONSTRAINT [DF_AUTORIZZAZIONI_ANAART_INS] DEFAULT (0) FOR [ANAART_INS],
	CONSTRAINT [DF_AUTORIZZAZIONI_ANAART_MOD] DEFAULT (0) FOR [ANAART_MOD],
	CONSTRAINT [DF_AUTORIZZAZIONI_ANAART_ANN] DEFAULT (0) FOR [ANAART_ANN]
go

UPDATE AUTORIZZAZIONI SET DOC_TIPIDOC = ''
UPDATE AUTORIZZAZIONI SET DOC_DEFADOC = ''
UPDATE AUTORIZZAZIONI SET ANAART_VIS = 0
UPDATE AUTORIZZAZIONI SET ANAART_INS = 0
UPDATE AUTORIZZAZIONI SET ANAART_MOD = 0
UPDATE AUTORIZZAZIONI SET ANAART_ANN = 0
