ALTER TABLE MOVIMENTI_BOMBOLE ADD QTA [INTEGER] 
ALTER TABLE MOVIMENTI_BOMBOLE ADD CONFERMATO [varchar] (1) COLLATE Latin1_General_CI_AS NULL

go

UPDATE MOVIMENTI_BOMBOLE SET QTA=1
UPDATE MOVIMENTI_BOMBOLE SET CONFERMATO=''

