
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	MAG_TEMPER NUMERIC(10,2) NOT NULL CONSTRAINT [DF_U_MAG_GG_MAG_TEMPER] DEFAULT (0)
go

ALTER TABLE [dbo].[U_MAG_MO] ADD 
	MOV_TEMPER NUMERIC(10,2) NOT NULL CONSTRAINT [DF_U_MAG_MO_MOV_TEMPER] DEFAULT (0)
go
