/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

-- INSERISCO IL CAMPO AGE_IMPPRO
ALTER TABLE [dbo].[U_AGE_AN] ADD 
	 AGE_IMPPRO numeric(11,3) NULL,
	 AGE_PROVMAT numeric(11,3) NULL,
	 AGE_BADG1 numeric(11,3) NULL,
	 AGE_BADG2 numeric(11,3) NULL,
	 AGE_SCAPROV0 numeric(4,2) NULL,
	 AGE_SCAPROV1 numeric(4,2) NULL,
	 AGE_SCAPROV2 numeric(4,2) NULL,
	 AGE_SCAPROV3 numeric(4,2) NULL,
	 AGE_SCAPROV4 numeric(4,2) NULL,
	 AGE_SCAPROV5 numeric(4,2) NULL,
	 AGE_SCAPROV6 numeric(4,2) NULL,
	 AGE_SCAPROV7 numeric(4,2) NULL,
	 AGE_SCAPROV8 numeric(4,2) NULL,
	 AGE_SCAPROV9 numeric(4,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AGE_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AGE_AN_AGE_IMPPRO] DEFAULT ('0') FOR [AGE_IMPPRO],
	CONSTRAINT [DF_U_AGE_AN_AGE_PROVMAT] DEFAULT ('0') FOR [AGE_PROVMAT],
	CONSTRAINT [DF_U_AGE_AN_AGE_BADG1] DEFAULT ('0') FOR [AGE_BADG1],
	CONSTRAINT [DF_U_AGE_AN_AGE_BADG2] DEFAULT ('0') FOR [AGE_BADG2],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV0] DEFAULT ('0') FOR [AGE_SCAPROV0],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV1] DEFAULT ('0') FOR [AGE_SCAPROV1],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV2] DEFAULT ('0') FOR [AGE_SCAPROV2],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV3] DEFAULT ('0') FOR [AGE_SCAPROV3],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV4] DEFAULT ('0') FOR [AGE_SCAPROV4],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV5] DEFAULT ('0') FOR [AGE_SCAPROV5],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV6] DEFAULT ('0') FOR [AGE_SCAPROV6],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV7] DEFAULT ('0') FOR [AGE_SCAPROV7],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV8] DEFAULT ('0') FOR [AGE_SCAPROV8],
	CONSTRAINT [DF_U_AGE_AN_AGE_SCAPROV9] DEFAULT ('0') FOR [AGE_SCAPROV9]
go


