-- fabiano 05/03/2015 - NON VISUALIZZA I PARAMETRI DISATTIVATI IN ELENCO

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_ELNODISA	BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_ELNODISA] DEFAULT (0) FOR [AZI_ELNODISA]
GO

UPDATE U_AZI_PB SET AZI_ELNODISA	= 0

