
ALTER TABLE [DBO].[U_CNT_TT] ADD 
	CNT_RAGDUE varchar(80) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_CNT_TT_CNT_RAGDUE] DEFAULT (''),
	CNT_CCOSTO varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_CNT_TT_CNT_CCOSTO] DEFAULT ('')
GO
