
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_AZI_AN] ADD 
	[AZI_TIPCON] [bit] NULL,
	[AZI_PRZBAS] [bit] NULL,
	[AZI_DATOLD] [bit] NULL,
	[AZI_CAMCOS] [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AZI_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_AN_AZI_TIPCON] DEFAULT (0) FOR [AZI_TIPCON],
	CONSTRAINT [DF_U_AZI_AN_AZI_PRZBAS] DEFAULT (0) FOR [AZI_PRZBAS],
	CONSTRAINT [DF_U_AZI_AN_AZI_DATOLD] DEFAULT (0) FOR [AZI_DATOLD],
	CONSTRAINT [DF_U_AZI_AN_AZI_CAMCOS] DEFAULT (0) FOR [AZI_CAMCOS]
go

UPDATE U_AZI_AN SET AZI_TIPCON = 1
UPDATE U_AZI_AN SET AZI_PRZBAS = 1
UPDATE U_AZI_AN SET AZI_DATOLD = 1
UPDATE U_AZI_AN SET AZI_CAMCOS = 1
UPDATE U_AZI_AN SET AZI_GIAADF = 1
UPDATE U_AZI_AN SET AZI_FORPRE = 1
UPDATE U_AZI_AN SET AZI_LIS0A  = 1
UPDATE U_AZI_AN SET AZI_LIS08  = 1

UPDATE U_AZI_AN SET AZI_LIS01  = 0
UPDATE U_AZI_AN SET AZI_LIS02  = 0
UPDATE U_AZI_AN SET AZI_LIS03  = 0
UPDATE U_AZI_AN SET AZI_LIS04  = 0
UPDATE U_AZI_AN SET AZI_LIS05  = 0
UPDATE U_AZI_AN SET AZI_LIS06  = 0
UPDATE U_AZI_AN SET AZI_LIS07  = 0
UPDATE U_AZI_AN SET AZI_LIS09  = 0
