/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_MAG_AN] ADD 
	 MOV_DTINCQ varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_ORINCQ varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DTFICQ varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_ORFICQ varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 MOV_CDRECQ varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DSRECQ varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_AN_MOV_DTINCQ] DEFAULT ('') FOR [MOV_DTINCQ],
	CONSTRAINT [DF_U_MAG_AN_MOV_ORINCQ] DEFAULT ('') FOR [MOV_ORINCQ],
	CONSTRAINT [DF_U_MAG_AN_MOV_DTFICQ] DEFAULT ('') FOR [MOV_DTFICQ],
	CONSTRAINT [DF_U_MAG_AN_MOV_ORFICQ] DEFAULT ('') FOR [MOV_ORFICQ],
	CONSTRAINT [DF_U_MAG_AN_MOV_CDRECQ] DEFAULT ('') FOR [MOV_CDRECQ],
	CONSTRAINT [DF_U_MAG_AN_MOV_DSRECQ] DEFAULT ('') FOR [MOV_DSRECQ]
go

UPDATE U_MAG_AN SET MOV_DTINCQ = SPACE(10)
UPDATE U_MAG_AN SET MOV_ORINCQ = SPACE(08)
UPDATE U_MAG_AN SET MOV_DTFICQ = SPACE(10)
UPDATE U_MAG_AN SET MOV_ORFICQ = SPACE(08)
UPDATE U_MAG_AN SET MOV_CDRECQ = SPACE(03)
UPDATE U_MAG_AN SET MOV_DSRECQ = SPACE(50)
