
-- INSERIMENTO NUOVO CAMPO PER SALVARE IL NOME FILE XML FATTURA FORNITORE GENERATO
ALTER TABLE [dbo].[INDICE] ADD 
  MOV_FILEXML varchar(254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_INDICE_MOV_FILEXML] DEFAULT ('')
go
