
/*
*** Variabili gestite per scheda "RAP - INPS" in gestione parametri - Top
*/
        
ALTER TABLE [DBO].[PARANEW] ADD 
	FLAGRAP bit NOT NULL CONSTRAINT [DF_PARANEW_FLAGRAP] DEFAULT (0),
	CODICERAP varchar(4) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARANEW_CODICERAP] DEFAULT (''),
	SUBCODICERAP varchar(1) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARANEW_SUBCODICERAP] DEFAULT (''),
	ALIQUOTARAP numeric(5,2) NOT NULL CONSTRAINT [DF_PARANEW_ALIQUOTARAP] DEFAULT (0),
	PERCIMPONIBILERAP numeric(5,2) NOT NULL CONSTRAINT [DF_PARANEW_PERCIMPONIBILERAP] DEFAULT (0),
	FLAGINPS bit NOT NULL CONSTRAINT [DF_PARANEW_FLAGINPS] DEFAULT (0),
	ALIQUOTAINPS numeric(5,2) NOT NULL CONSTRAINT [DF_PARANEW_ALIQUOTAINPS] DEFAULT (0),
	PERCIMPONIBILEINPS numeric(5,2) NOT NULL CONSTRAINT [DF_PARANEW_PERCIMPONIBILEINPS] DEFAULT (0),
	QUOTACOMMITTENTE numeric(5,2) NOT NULL CONSTRAINT [DF_PARANEW_QUOTACOMMITTENTE] DEFAULT (0)

GO
