
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
		 ART_COSLAI numeric (17, 3)  NULL ,
	 	 ART_COSLAE numeric (17, 3)  NULL ,	
	 	 ART_COSMAT numeric (17, 3)  NULL ,
	 	 ART_COSATR numeric (17, 3)  NULL ,
		 ART_RICLAI numeric (17, 3)  NULL ,
	 	 ART_RICLAE numeric (17, 3)  NULL ,	
	 	 ART_RICMAT numeric (17, 3)  NULL ,	
 	 	 ART_RICATR numeric (17, 3)  NULL ,	
	 	 ART_ORELAV varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_OREATT varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_OREIMP varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_SECLAV numeric (8, 0)  NULL,
	 	 ART_SECATT numeric (8, 0)  NULL,
	 	 ART_SECIMP numeric (8, 0)  NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_COSLAI] DEFAULT (0) FOR [ART_COSLAI],
	CONSTRAINT [DF_U_ART_PR_ART_COSLAE] DEFAULT (0) FOR [ART_COSLAE],
	CONSTRAINT [DF_U_ART_PR_ART_COSMAT] DEFAULT (0) FOR [ART_COSMAT],
	CONSTRAINT [DF_U_ART_PR_ART_COSATR] DEFAULT (0) FOR [ART_COSATR],
	CONSTRAINT [DF_U_ART_PR_ART_RICLAI] DEFAULT (0) FOR [ART_RICLAI],
	CONSTRAINT [DF_U_ART_PR_ART_RICLAE] DEFAULT (0) FOR [ART_RICLAE],
	CONSTRAINT [DF_U_ART_PR_ART_RICMAT] DEFAULT (0) FOR [ART_RICMAT],
	CONSTRAINT [DF_U_ART_PR_ART_RICATR] DEFAULT (0) FOR [ART_RICATR],
	CONSTRAINT [DF_U_ART_PR_ART_ORELAV] DEFAULT ('') FOR [ART_ORELAV],
	CONSTRAINT [DF_U_ART_PR_ART_OREATT] DEFAULT ('') FOR [ART_OREATT],
	CONSTRAINT [DF_U_ART_PR_ART_OREIMP] DEFAULT ('') FOR [ART_OREIMP],
	CONSTRAINT [DF_U_ART_PR_ART_SECLAV] DEFAULT (0) FOR [ART_SECLAV],
	CONSTRAINT [DF_U_ART_PR_ART_SECATT] DEFAULT (0) FOR [ART_SECATT],
	CONSTRAINT [DF_U_ART_PR_ART_SECIMP] DEFAULT (0) FOR [ART_SECIMP]
	
go

UPDATE U_ART_PR SET ART_COSLAI 	= 0
UPDATE U_ART_PR SET ART_COSLAE 	= 0
UPDATE U_ART_PR SET ART_COSMAT 	= 0
UPDATE U_ART_PR SET ART_COSATR 	= 0
UPDATE U_ART_PR SET ART_RICLAI 	= 0
UPDATE U_ART_PR SET ART_RICLAE 	= 0
UPDATE U_ART_PR SET ART_RICMAT 	= 0
UPDATE U_ART_PR SET ART_RICATR 	= 0
UPDATE U_ART_PR SET ART_ORELAV 	= ''
UPDATE U_ART_PR SET ART_OREATT 	= ''
UPDATE U_ART_PR SET ART_OREIMP 	= ''
UPDATE U_ART_PR SET ART_SECLAV 	= 0
UPDATE U_ART_PR SET ART_SECATT 	= 0
UPDATE U_ART_PR SET ART_SECIMP 	= 0
