/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_AZI_PA] ADD 
	[AZI_NRSEBF] [bit] NULL,
	[AZI_NRSEBC] [bit] NULL,
	[AZI_PROTFA] numeric(6) NULL,
	[AZI_PROTCI] numeric(6) NULL,
	[AZI_AGGPRO] [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_NRSEBF] DEFAULT (0) FOR [AZI_NRSEBF],
	CONSTRAINT [DF_U_AZI_PA_AZI_NRSEBC] DEFAULT (0) FOR [AZI_NRSEBC],
	CONSTRAINT [DF_U_AZI_PA_AZI_PROTFA] DEFAULT (0) FOR [AZI_PROTFA],
	CONSTRAINT [DF_U_AZI_PA_AZI_PROTCI] DEFAULT (0) FOR [AZI_PROTCI],
	CONSTRAINT [DF_U_AZI_PA_AZI_AGGPRO] DEFAULT (0) FOR [AZI_AGGPRO]
go

UPDATE U_AZI_PA SET AZI_NRSEBF  = 0
UPDATE U_AZI_PA SET AZI_NRSEBC  = 0
UPDATE U_AZI_PA SET AZI_AGGPRO  = 0
UPDATE U_AZI_PA SET AZI_PROTFA  = -1
UPDATE U_AZI_PA SET AZI_PROTCI  = -1

UPDATE U_AZI_AN SET AZI_PROTFO  = -1
UPDATE U_AZI_AN SET AZI_PROTCO  = -1
UPDATE U_AZI_AN SET AZI_PROTCL  = -1
