ALTER TABLE [dbo].[U_MAG_GG] ADD 
	MAG_MATRICOLA varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_GG_MAG_MATRICOLA] DEFAULT ('')
go

ALTER TABLE [dbo].[U_MAG_MO] ADD 
	MOV_MATRICOLA varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_MO_MOV_MATRICOLA] DEFAULT ('')
go

ALTER TABLE [dbo].[U_BFO_SN] ADD 
	MATRICOLA varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_BFO_SN_MATRICOLA] DEFAULT ('')
go
