/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_CA] ADD 
	 MOV_LEGAME varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_PAGAME varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 MOV_NUMORF varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DATORF varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SC1    [numeric](6, 2) NULL,
	 MOV_SC2    [numeric](6, 2) NULL,
	 MOV_SC3    [numeric](6, 2) NULL,
	 MOV_CODACQ varchar(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_CA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CA_MOV_LEGAME] DEFAULT ('') FOR [MOV_LEGAME],
	CONSTRAINT [DF_U_MAG_CA_MOV_PAGAME] DEFAULT ('') FOR [MOV_PAGAME],
	CONSTRAINT [DF_U_MAG_CA_MOV_NUMORF] DEFAULT ('') FOR [MOV_NUMORF],
	CONSTRAINT [DF_U_MAG_CA_MOV_DATORF] DEFAULT ('') FOR [MOV_DATORF],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC1] DEFAULT (0) FOR [MOV_SC1],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC2] DEFAULT (0) FOR [MOV_SC2],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC3] DEFAULT (0) FOR [MOV_SC3],
	CONSTRAINT [DF_U_MAG_CA_MOV_CODACQ] DEFAULT ('') FOR [MOV_CODACQ]
go

UPDATE U_MAG_CA SET MOV_LEGAME = SPACE(10)
UPDATE U_MAG_CA SET MOV_PAGAME = SPACE(03)
UPDATE U_MAG_CA SET MOV_NUMORF = SPACE(10)
UPDATE U_MAG_CA SET MOV_DATORF = SPACE(10)
UPDATE U_MAG_CA SET MOV_SC1 = 0
UPDATE U_MAG_CA SET MOV_SC2 = 0
UPDATE U_MAG_CA SET MOV_SC3 = 0
UPDATE U_MAG_CA SET MOV_CODACQ = SPACE(03)
