 
/* 
NUOVA DECODIFICA CLIENTE
*/

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT
      DF_U_ANA_CL_CLI_PE_PRI,
      DF_U_ANA_CL_CLI_PE_PRO,
      DF_U_ANA_CL_CLI_PE_PA1,
      DF_U_ANA_CL_CLI_PE_PA2,
      DF_U_ANA_CL_CLI_PE_PA3
GO
ALTER TABLE [dbo].[U_ANA_CL] DROP COLUMN 
       CLI_PE_PRI,
       CLI_PE_PRO,
       CLI_PE_PA1,
       CLI_PE_PA2,
       CLI_PE_PA3
GO


ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_PE_PRI bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_PE_PRI] DEFAULT (0),
	CLI_PE_PRO bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_PE_PRO] DEFAULT (0),
	CLI_PE_PA1 bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_PE_PA1] DEFAULT (0),
	CLI_PE_PA2 bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_PE_PA2] DEFAULT (0),
	CLI_PE_PA3 bit NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_PE_PA3] DEFAULT (0)
GO

UPDATE U_ANA_CL SET CLI_PE_PRI =  0 
UPDATE U_ANA_CL SET CLI_PE_PRO =  0 
UPDATE U_ANA_CL SET CLI_PE_PA1 =  0 
UPDATE U_ANA_CL SET CLI_PE_PA2 =  0 
UPDATE U_ANA_CL SET CLI_PE_PA3 =  0 