
ALTER TABLE [dbo].[U_PRD_DR] ADD
	PRR_CTRL01 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PRR_CTRL02 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PRR_CTRL03 varchar (2) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_PRR_CTRL01] DEFAULT ('') FOR [PRR_CTRL01],
	CONSTRAINT [DF_U_PRD_DR_PRR_CTRL02] DEFAULT ('') FOR [PRR_CTRL02],
	CONSTRAINT [DF_U_PRD_DR_PRR_CTRL03] DEFAULT ('') FOR [PRR_CTRL03]
go

UPDATE U_PRD_DR SET PRR_CTRL01 = ''
UPDATE U_PRD_DR SET PRR_CTRL02 = ''
UPDATE U_PRD_DR SET PRR_CTRL03 = ''




