
ALTER TABLE [dbo].[U_PRD_D4] ADD 
	PR4_SCARTO numeric(5,0) NULL 
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_SCARTO] DEFAULT (0) FOR [PR4_SCARTO]
go

UPDATE U_PRD_D4 SET PR4_SCARTO = 0


