
ALTER TABLE [dbo].[U_ORD_TT] ADD
	ORD_DDTLCKADV bit NOT NULL CONSTRAINT [DF_U_ORD_TT_ORD_DDTLCKADV] DEFAULT (0),
	ORD_DDTLCKSER bit NOT NULL CONSTRAINT [DF_U_ORD_TT_ORD_DDTLCKSER] DEFAULT (0)
GO
