
ALTER TABLE [dbo].[U_PRD_D4] ADD
	PR4_CTRL01 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PR4_CTRL02 varchar (2) COLLATE Latin1_General_CI_AS NULL,
	PR4_CTRL03 varchar (2) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_CTRL01] DEFAULT ('') FOR [PR4_CTRL01],
	CONSTRAINT [DF_U_PRD_D4_PR4_CTRL02] DEFAULT ('') FOR [PR4_CTRL02],
	CONSTRAINT [DF_U_PRD_D4_PR4_CTRL03] DEFAULT ('') FOR [PR4_CTRL03]
go

UPDATE U_PRD_D4 SET PR4_CTRL01 = ''
UPDATE U_PRD_D4 SET PR4_CTRL02 = ''
UPDATE U_PRD_D4 SET PR4_CTRL03 = ''




