
-- ALLARGAMENTO CAMPO MOV_DESMOV PER DESCRIZIONE AGGIUNTIVA SU MOV_CONT

DROP INDEX [DESCRIZION] ON [dbo].[MOV_CONT]
GO
ALTER TABLE [dbo].[MOV_CONT] ALTER COLUMN MOV_DESMOV VARCHAR(254) COLLATE Latin1_General_CI_AS NOT NULL

CREATE NONCLUSTERED INDEX [DESCRIZION] ON [dbo].[MOV_CONT]
(
	[MOV_SOC] ASC,
	[MOV_DESMOV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- ALLARGAMENTO CAMPO MOV_DESMOV PER DESCRIZIONE AGGIUNTIVA SU INDICE
DROP INDEX [DESCRIZION] ON [dbo].[INDICE]
GO
DROP INDEX [INDICE_03] ON [dbo].[INDICE]
GO

ALTER TABLE [dbo].[INDICE] ALTER COLUMN MOV_DESMOV VARCHAR(254) COLLATE Latin1_General_CI_AS NOT NULL

CREATE NONCLUSTERED INDEX [DESCRIZION] ON [dbo].[INDICE]
(
	[MOV_SOC] ASC,
	[MOV_DESMOV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [INDICE_03] ON [dbo].[INDICE]
(
	[MOV_SOC] ASC,
	[MOV_ANNO] ASC,
	[MOV_DESMOV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- ALLARGAMENTO CAMPO MOV_DESMOV PER DESCRIZIONE AGGIUNTIVA SU MO_CONCA
DROP INDEX [DESCRIZION] ON [dbo].[MO_CONCA]
GO
ALTER TABLE [dbo].[MO_CONCA] ALTER COLUMN MOV_DESMOV VARCHAR(254) COLLATE Latin1_General_CI_AS NOT NULL

CREATE NONCLUSTERED INDEX [DESCRIZION] ON [dbo].[MO_CONCA]
(
	[MOV_SOC] ASC,
	[MOV_DESMOV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO