/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	 MAG_LEGAME varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_CODACQ varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_DESACQ varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 MAG_PRZUFF [numeric](17, 6) NULL,
	 MAG_DATINI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_DATFIN varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MAG_SC1    [numeric](6, 2) NULL,
	 MAG_SC2    [numeric](6, 2) NULL,
	 MAG_SC3    [numeric](6, 2) NULL,
	 MAG_SC4    [numeric](6, 2) NULL,
	 MAG_SC5    [numeric](6, 2) NULL,
	 MAG_PRZSCO [numeric](17, 6) NULL,
	 MAG_PAGAME varchar(10) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_GG_MAG_LEGAME] DEFAULT ('') FOR [MAG_LEGAME],
	CONSTRAINT [DF_U_MAG_GG_MAG_CODACQ] DEFAULT ('') FOR [MAG_CODACQ],
	CONSTRAINT [DF_U_MAG_GG_MAG_DESACQ] DEFAULT ('') FOR [MAG_DESACQ],
	CONSTRAINT [DF_U_MAG_GG_MAG_PRZUFF] DEFAULT (0) FOR [MAG_PRZUFF],
	CONSTRAINT [DF_U_MAG_GG_MAG_DATINI] DEFAULT ('') FOR [MAG_DATINI],
	CONSTRAINT [DF_U_MAG_GG_MAG_DATFIN] DEFAULT ('') FOR [MAG_DATFIN],
	CONSTRAINT [DF_U_MAG_GG_MAG_SC1] DEFAULT (0) FOR [MAG_SC1],
	CONSTRAINT [DF_U_MAG_GG_MAG_SC2] DEFAULT (0) FOR [MAG_SC2],
	CONSTRAINT [DF_U_MAG_GG_MAG_SC3] DEFAULT (0) FOR [MAG_SC3],
	CONSTRAINT [DF_U_MAG_GG_MAG_SC4] DEFAULT (0) FOR [MAG_SC4],
	CONSTRAINT [DF_U_MAG_GG_MAG_SC5] DEFAULT (0) FOR [MAG_SC5],
	CONSTRAINT [DF_U_MAG_GG_MAG_PRZSCO] DEFAULT (0) FOR [MAG_PRZSCO],
	CONSTRAINT [DF_U_MAG_GG_MAG_PAGAME] DEFAULT ('') FOR [MAG_PAGAME]
go

UPDATE U_MAG_GG SET MAG_LEGAME = SPACE(10)
UPDATE U_MAG_GG SET MAG_CODACQ = SPACE(03)
UPDATE U_MAG_GG SET MAG_DESACQ = SPACE(06)
UPDATE U_MAG_GG SET MAG_PRZUFF = 0
UPDATE U_MAG_GG SET MAG_DATINI = SPACE(10)
UPDATE U_MAG_GG SET MAG_DATFIN = SPACE(10)
UPDATE U_MAG_GG SET MAG_SC1 = 0
UPDATE U_MAG_GG SET MAG_SC2 = 0
UPDATE U_MAG_GG SET MAG_SC3 = 0
UPDATE U_MAG_GG SET MAG_SC4 = 0
UPDATE U_MAG_GG SET MAG_SC5 = 0
UPDATE U_MAG_GG SET MAG_PRZSCO = 0
UPDATE U_MAG_GG SET MAG_PAGAME = SPACE(03)
