
/* 
******************************************
INSERIMENTO CAMPI PER MAGGIORAZIONI PREZZO
******************************************
*/
ALTER TABLE [dbo].[U_FAT_DD] ADD 
	IDR_VALORE   numeric (17,6) NULL,
	IDR_PREZZO numeric (17,6) NULL,
	IDR_PRZNET numeric (17,6) NULL
go	

ALTER TABLE [dbo].[U_FAT_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAT_DD_IDR_VALORE  ] DEFAULT (0) FOR [IDR_VALORE  ],
	CONSTRAINT [DF_U_FAT_DD_IDR_PREZZO] DEFAULT (0) FOR [IDR_PREZZO],
	CONSTRAINT [DF_U_FAT_DD_IDR_PRZNET] DEFAULT (0) FOR [IDR_PRZNET]
go

UPDATE U_FAT_DD SET IDR_VALORE   = 0 
UPDATE U_FAT_DD SET IDR_PREZZO = 0 
UPDATE U_FAT_DD SET IDR_PRZNET = 0 
