
-- ALLARGAMENTO CAMPO CODICE OPERATORE A 20 CARATTERI
ALTER TABLE [dbo].[PART_FOR] ALTER COLUMN PAR_NUMFAT VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PART_CLI] ALTER COLUMN PAR_NUMFAT VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[MOV_CONT] ALTER COLUMN MOV_NDOC VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[INDICE] ALTER COLUMN MOV_NDOC VARCHAR(20) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[U_IVA_CL] ALTER COLUMN IVA_NUMDOC VARCHAR(20) COLLATE Latin1_General_CI_AS NULL 
ALTER TABLE [dbo].[U_IVA_CL] ALTER COLUMN IVA_NUMFAT VARCHAR(20) COLLATE Latin1_General_CI_AS NULL 
ALTER TABLE [dbo].[U_IVA_CL] ALTER COLUMN IVA_NUMCEE VARCHAR(20) COLLATE Latin1_General_CI_AS NULL 

ALTER TABLE [dbo].[U_IVA_CS] ALTER COLUMN IVA_NUMDOC VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_IVA_CS] ALTER COLUMN IVA_NUMFAT VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_IVA_CS] ALTER COLUMN IVA_NUMCEE VARCHAR(20) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[U_IVF_CL] ALTER COLUMN IVF_NUMFAT VARCHAR(20) COLLATE Latin1_General_CI_AS NULL 
