
ALTER TABLE [dbo].[U_MAG_GG] ADD 
	MAG_LOTPRD varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_GG_MAG_LOTPRD] DEFAULT ('')
go

ALTER TABLE [dbo].[U_MAG_MO] ADD 
	MOV_LOTPRD varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_MAG_MO_MOV_LOTPRD] DEFAULT ('')
go
