
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[PARA] ADD 
	 PAR_COSTCAD1	[numeric] (17,2) NULL ,
	 PAR_RICCAD1	[numeric] (17,2) NULL ,
	 PAR_FINOA		[numeric] (5,0) NULL ,
	 PAR_COSFINOA	[numeric] (17,2) NULL ,
	 PAR_RICFINOA	[numeric] (17,2) NULL ,
	 PAR_OLTREA		[numeric] (5,0) NULL ,
	 PAR_COSOLTRA	[numeric] (17,2) NULL ,
	 PAR_RICOLTRA	[numeric] (17,2) NULL 

go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[PARA] WITH NOCHECK ADD 
	CONSTRAINT [DF_PARA_PAR_COSTCAD1]	DEFAULT (0)  FOR [PAR_COSTCAD1],
	CONSTRAINT [DF_PARA_PAR_RICCAD1]	DEFAULT (0)  FOR [PAR_RICCAD1],
	CONSTRAINT [DF_PARA_PAR_FINOA]		DEFAULT (0)  FOR [PAR_FINOA],
	CONSTRAINT [DF_PARA_PAR_COSFINOA]	DEFAULT (0)  FOR [PAR_COSFINOA],
	CONSTRAINT [DF_PARA_PAR_RICFINOA]	DEFAULT (0)  FOR [PAR_RICFINOA],
	CONSTRAINT [DF_PARA_PAR_OLTREA]		DEFAULT (0)  FOR [PAR_OLTREA],
	CONSTRAINT [DF_PARA_PAR_COSOLTRA]	DEFAULT (0)  FOR [PAR_COSOLTRA],
	CONSTRAINT [DF_PARA_PAR_RICOLTRA]	DEFAULT (0)  FOR [PAR_RICOLTRA]

go



UPDATE PARA SET PAR_COSTCAD1 = 0
UPDATE PARA SET PAR_RICCAD1 = 0
UPDATE PARA SET PAR_FINOA = 0
UPDATE PARA SET PAR_COSFINOA = 0
UPDATE PARA SET PAR_RICFINOA = 0
UPDATE PARA SET PAR_OLTREA = 0
UPDATE PARA SET PAR_COSOLTRA = 0
UPDATE PARA SET PAR_RICOLTRA = 0