
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/


ALTER TABLE [dbo].[FATTURABILE_MDB] ADD 
	MDB_ANTECO numeric(17,2) NOT NULL CONSTRAINT [DF_FATTURABILE_MDB_MDB_ANTECO] DEFAULT (0)
go


ALTER TABLE [dbo].[FATTURABILE_MDB] ADD 
	MDB_BOECO numeric(4,0) NOT NULL CONSTRAINT [DF_FATTURABILE_MDB_MDB_BOECO] DEFAULT (0)
go


ALTER TABLE [dbo].[FATTURABILE_MDB] ADD 
	MDB_DTSCEC varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_FATTURABILE_MDB_MDB_DTSCEC] DEFAULT ('')
go



ALTER TABLE [dbo].[FATTURABILE_MDB] ADD 
	MDB_DTSCFO varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_FATTURABILE_MDB_MDB_DTSCFO] DEFAULT ('')
go
