

-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1
UPDATE U_AZI_PB SET AZI_TXTVARI = CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 1 ELSE 0 END
UPDATE U_AZI_PB SET AZI_CLSIOBBL = CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 1 ELSE 0 END

