
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_PERSFAT BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_PERSFAT] DEFAULT (0) FOR [AZI_PERSFAT]
GO

UPDATE U_AZI_PB SET AZI_PERSFAT = 0
