ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB1 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB2 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB3 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB4 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB5 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB6 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB7 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB8 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB9 [numeric](18, 2) NULL
GO

ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN
	 STA_QTBOB0 [numeric](18, 2) NULL
GO
