

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_SCAALT bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_SCAALT] DEFAULT (0),
	AZI_SCABAS bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_SCABAS] DEFAULT (0),
	AZI_SCVBAS bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_SCVBAS] DEFAULT (0)
GO

-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1 (TRUE)
UPDATE U_AZI_PB SET AZI_SCAALT =  0 
UPDATE U_AZI_PB SET AZI_SCABAS =  0 
UPDATE U_AZI_PB SET AZI_SCVBAS =  0 
