
ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_CATPROV varchar(4) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_ART_CATPROV] DEFAULT (''),
	ART_REPARTO varchar(4) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_ART_REPARTO] DEFAULT ('')
go

