
ALTER TABLE [DBO].[SCHEDULER] ADD 
	PARAMETRI  VARCHAR(254) COLLATE Latin1_General_CI_AS NULL 
GO

ALTER TABLE [DBO].[SCHEDULER] WITH NOCHECK ADD 
	CONSTRAINT [DF_SCHEDULER_PARAMETRI] DEFAULT ('') FOR [PARAMETRI]
GO

UPDATE SCHEDULER SET PARAMETRI  = ''
