
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_XCOORD0 numeric(5)  NULL,
	PR5_XCOORD1 numeric(5)  NULL,
	PR5_YCOORD0 numeric(5)  NULL,
	PR5_FLGVIEW BIT  NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_XCOORD0] DEFAULT (0) FOR [PR5_XCOORD0],
	CONSTRAINT [DF_U_PRD_D5_PR5_XCOORD1] DEFAULT (0) FOR [PR5_XCOORD1],
	CONSTRAINT [DF_U_PRD_D5_PR5_YCOORD0] DEFAULT (0) FOR [PR5_YCOORD0],
	CONSTRAINT [DF_U_PRD_D5_PR5_FLGVIEW] DEFAULT (0) FOR [PR5_FLGVIEW]
go

UPDATE U_PRD_D5 SET PR5_XCOORD0 = 0
UPDATE U_PRD_D5 SET PR5_XCOORD1 = 0
UPDATE U_PRD_D5 SET PR5_YCOORD0 = 0
UPDATE U_PRD_D5 SET PR5_FLGVIEW = 0


