/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[BUDGET_CONS] ADD 
	SPESEGG numeric(17,6) NULL,
	RIMBKM numeric(17,6) NULL,
	RIMBSPEFOR numeric(17,6) NULL,
	IMPTRASFGG numeric(17,6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[BUDGET_CONS] WITH NOCHECK ADD 
	CONSTRAINT [DF_BUDGET_CONS_SPESEGG] DEFAULT (0) FOR [SPESEGG],
	CONSTRAINT [DF_BUDGET_CONS_RIMBKM] DEFAULT (0) FOR [RIMBKM],
	CONSTRAINT [DF_BUDGET_CONS_RIMBSPEFOR] DEFAULT (0) FOR [RIMBSPEFOR],
	CONSTRAINT [DF_BUDGET_CONS_IMPTRASFGG] DEFAULT (0) FOR [IMPTRASFGG]
go

UPDATE BUDGET_CONS SET SPESEGG = 0
UPDATE BUDGET_CONS SET RIMBKM = 0
UPDATE BUDGET_CONS SET RIMBSPEFOR = 0
UPDATE BUDGET_CONS SET IMPTRASFGG = 0



