ALTER TABLE [dbo].[U_PRD_D2] ADD 
 	PR2_STASEQ VARCHAR(3) COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D2_PR2_STASEQ] DEFAULT ('') FOR [PR2_STASEQ]
go

---UPDATE PER CONSENTIRE FUNZIONAMENTO PROGRAMMI SENZA MODIFICA SUL TAPPETO
---CHE GESTISCE QUESTO NUOVO CAMPO
UPDATE U_PRD_D2 SET PR2_STASEQ = '002'