/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[PART_FOR] ADD 
	 	 PAR_CODACQ varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 	 PAR_TIPOCONTRATTO varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 PAR_FORMAPAGAMENTO varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 PAR_GRADOIMPORTANZA varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 PAR_COSATRATTA varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 PAR_PRIPAGA varchar(04) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[PART_FOR] WITH NOCHECK ADD 
	CONSTRAINT [DF_PART_PAR_PAR_CODACQ] DEFAULT ('   ') FOR [PAR_CODACQ],
	CONSTRAINT [DF_PART_PAR_PAR_TIPOCONTRATTO] DEFAULT ('     ') FOR [PAR_TIPOCONTRATTO],
	CONSTRAINT [DF_PART_PAR_PAR_FORMAPAGAMENTO] DEFAULT ('     ') FOR [PAR_FORMAPAGAMENTO],
	CONSTRAINT [DF_PART_PAR_PAR_GRADOIMPORTANZA] DEFAULT ('     ') FOR [PAR_GRADOIMPORTANZA],
	CONSTRAINT [DF_PART_PAR_PPAR_COSATRATTA] DEFAULT ('     ') FOR [PAR_COSATRATTA],
	CONSTRAINT [DF_PART_PAR_PAR_PRIPAGA] DEFAULT ('    ') FOR [PAR_PRIPAGA]

go

UPDATE PART_FOR SET PAR_COSATRATTA 	= '     '
UPDATE PART_FOR SET PAR_GRADOIMPORTANZA = '     '
UPDATE PART_FOR SET PAR_FORMAPAGAMENTO 	= '     '
UPDATE PART_FOR SET PAR_TIPOCONTRATTO 	= '     '
UPDATE PART_FOR SET PAR_CODACQ	 	= '   '
UPDATE PART_FOR SET PAR_PRIPAGA		= '    '