
ALTER TABLE [DBO].[VENDITE_DT] ADD 
	ORD_SYSCOMPONENTI varchar (10) COLLATE Latin1_General_CI_AS not NULL CONSTRAINT [DF_VENDITE_DT_ORD_SYSCOMPONENTI] DEFAULT (''),
	ORD_SYSCONTRATTO varchar (10) COLLATE Latin1_General_CI_AS not NULL CONSTRAINT [DF_VENDITE_DT_ORD_SYSCONTRATTO] DEFAULT ('')
GO
