/*
*** NUOVI CAMPI PER GESTIONE ACCETTAZIONE CONDIZIONI GENERALI DI ACQUISTO
*/

ALTER TABLE [DBO].[U_FOR_AN] ADD 
	FOR_FLACGA bit NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_FLACGA] DEFAULT (0),
	FOR_DTACGA varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_DTACGA] DEFAULT ('')
GO
