
/* 
**************************************************************
ELIMINAZIONE CAMPI SE ESISTENTI DA UNA TABELLA
**************************************************************
*/

if Exists(select * from syscolumns where Name = N'SPESEGG' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_SPESEGG]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN SPESEGG
END

if Exists(select * from syscolumns where Name = N'RIMBKM' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_RIMBKM]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN RIMBKM
END

if Exists(select * from syscolumns where Name = N'RIMBSPEFOR' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_RIMBSPEFOR]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN RIMBSPEFOR
END

if Exists(select * from syscolumns where Name = N'IMPTRASFGG' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_IMPTRASFGG]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN IMPTRASFGG
END

if Exists(select * from syscolumns where Name = N'KMPER' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_KMPER]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN KMPER
END

if Exists(select * from syscolumns where Name = N'KMVAL' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_KMVAL]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN KMVAL
END

if Exists(select * from syscolumns where Name = N'NOTETRASFERTA' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_NOTETRASFERTA]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN NOTETRASFERTA
END

if Exists(select * from syscolumns where Name = N'FLAGRIMBSPE' and ID = Object_ID(N'TIMESHT'))
BEGIN
	ALTER TABLE [dbo].[TIMESHT] DROP CONSTRAINT [DF_TIMESHT_FLAGRIMBSPE]
	ALTER TABLE [dbo].[TIMESHT] DROP COLUMN FLAGRIMBSPE
END

/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[TIMESHT] ADD 
	SPESEGG numeric(17,6) NULL,
	RIMBKM numeric(17,6) NULL,
	RIMBSPEFOR numeric(17,6) NULL,
	IMPTRASFGG numeric(17,6) NULL,
	KMPER numeric(6,1) NULL,
	KMVAL numeric(6,2) NULL,
	NOTETRASFERTA [TEXT] COLLATE Latin1_General_CI_AS NULL,
	FLAGRIMBSPE [bit] NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[TIMESHT] WITH NOCHECK ADD 
	CONSTRAINT [DF_TIMESHT_SPESEGG] DEFAULT (0) FOR [SPESEGG],
	CONSTRAINT [DF_TIMESHT_RIMBKM] DEFAULT (0) FOR [RIMBKM],
	CONSTRAINT [DF_TIMESHT_RIMBSPEFOR] DEFAULT (0) FOR [RIMBSPEFOR],
	CONSTRAINT [DF_TIMESHT_IMPTRASFGG] DEFAULT (0) FOR [IMPTRASFGG],
	CONSTRAINT [DF_TIMESHT_KMPER] DEFAULT (0) FOR [KMPER],
	CONSTRAINT [DF_TIMESHT_KMVAL] DEFAULT (0) FOR [KMVAL],
	CONSTRAINT [DF_TIMESHT_NOTETRASFERTA] DEFAULT ('') FOR [NOTETRASFERTA],
	CONSTRAINT [DF_TIMESHT_FLAGRIMBSPE] DEFAULT ('0') FOR [FLAGRIMBSPE]
go

UPDATE TIMESHT SET SPESEGG = 0
UPDATE TIMESHT SET RIMBKM = 0
UPDATE TIMESHT SET RIMBSPEFOR = 0
UPDATE TIMESHT SET IMPTRASFGG = 0
UPDATE TIMESHT SET KMPER = 0
UPDATE TIMESHT SET KMVAL   = 0
UPDATE TIMESHT SET NOTETRASFERTA = ''
UPDATE TIMESHT SET FLAGRIMBSPE = '0'