

ALTER TABLE IMPIANTI_TT DROP CONSTRAINT DF_IMPIANTI_TT_MEMO_1

ALTER TABLE [dbo].[IMPIANTI_TT] ALTER COLUMN MEMO_1 text COLLATE Latin1_General_CI_AS NOT NULL
GO

ALTER TABLE [dbo].[IMPIANTI_TT] WITH NOCHECK ADD CONSTRAINT [DF_IMPIANTI_TT_MEMO_1] DEFAULT ('') FOR [MEMO_1]
go

