
ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_CBOVUO varchar(16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_ART_CBOVUO] DEFAULT ('')
go

ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_DBOVUO varchar(40) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_ART_DBOVUO] DEFAULT ('')
go

ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_QTAMC numeric(12,4) NOT NULL CONSTRAINT [DF_U_ART_AN_ART_QTAMC] DEFAULT (0),
	ART_QTAKG numeric(12,4) NOT NULL CONSTRAINT [DF_U_ART_AN_ART_QTAKG] DEFAULT (0)
go
