
DROP INDEX [U_ORF_01] ON [dbo].[U_ORF_DL]
GO

DROP INDEX [U_ORF_02] ON [dbo].[U_ORF_DL]
GO


ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAKG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAMQ] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAML] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAKGE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAMQE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAMLE] NUMERIC(12,4) NULL
GO


ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAKGD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAMQD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN
	 [ORD_QTAMLD] NUMERIC(12,4) NULL
GO






CREATE NONCLUSTERED INDEX [U_ORF_01] ON [dbo].[U_ORF_DL]
(
	[DAGGANCIO] ASC,
	[DLEGAME] ASC,
	[ORD_QTAKGE] ASC,
	[ORD_QTAKG] ASC,
	[ORD_SALCON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [U_ORF_02] ON [dbo].[U_ORF_DL]
(
	[ORD_QTAMQ] ASC,
	[ORD_QTAMQE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
