
/*
*** Conti contabili di supporto per il CONFIGURATORE AQUARIUS
*/

ALTER TABLE [DBO].[CONFIGURATORE_AQUARIUS] ADD 
	AZI_ABBUONP varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONFIGURATORE_AQUARIUS_AZI_ABBUONP] DEFAULT ('')
GO

ALTER TABLE [DBO].[CONFIGURATORE_AQUARIUS] ADD 
	AZI_DIFFCAMP varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONFIGURATORE_AQUARIUS_AZI_DIFFCAMP] DEFAULT ('')
GO

ALTER TABLE [DBO].[CONFIGURATORE_AQUARIUS] ADD 
	AZI_QUADPNP varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONFIGURATORE_AQUARIUS_AZI_QUADPNP] DEFAULT ('')
GO
