/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_PCK_LE] ADD 
	 LEG_ANAART varchar(16) COLLATE Latin1_General_CI_AS NULL,
	 LEG_DESART varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 LEG_DATAGG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 LEG_CODFOR varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 LEG_DESFOR varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 LEG_PRZCON numeric(18,6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PCK_LE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PCK_LE_LEG_ANAART] DEFAULT ('') FOR [LEG_ANAART],
	CONSTRAINT [DF_U_PCK_LE_LEG_DESART] DEFAULT ('') FOR [LEG_DESART],
	CONSTRAINT [DF_U_PCK_LE_LEG_DATAGG] DEFAULT ('') FOR [LEG_DATAGG],
	CONSTRAINT [DF_U_PCK_LE_LEG_CODFOR] DEFAULT ('') FOR [LEG_CODFOR],
	CONSTRAINT [DF_U_PCK_LE_LEG_DESFOR] DEFAULT ('') FOR [LEG_DESFOR],
	CONSTRAINT [DF_U_PCK_LE_LEG_PRZCON] DEFAULT (0) FOR [LEG_PRZCON]
go

UPDATE U_PCK_LE SET LEG_ANAART = SPACE(16)
UPDATE U_PCK_LE SET LEG_DESART = SPACE(50)
UPDATE U_PCK_LE SET LEG_DATAGG = SPACE(10)
UPDATE U_PCK_LE SET LEG_CODFOR = SPACE(10)
UPDATE U_PCK_LE SET LEG_DESFOR = SPACE(50)
UPDATE U_PCK_LE SET LEG_PRZCON = 0
