
ALTER TABLE [dbo].[IMPIANTI_TT] DROP CONSTRAINT DF_IMPIANTI_TT_CNOTE
GO

ALTER TABLE [dbo].[IMPIANTI_TT] ALTER COLUMN CNOTE TEXT NOT NULL
GO

ALTER TABLE [dbo].[IMPIANTI_TT] WITH NOCHECK ADD CONSTRAINT [DF_IMPIANTI_TT_CNOTE] DEFAULT ('') FOR [CNOTE]
GO