
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_DIS_DD] ADD 
		 DIS_COSLAI numeric (17, 3)  NULL ,
	 	 DIS_COSLAE numeric (17, 3)  NULL ,	
	 	 DIS_COSMAT numeric (17, 3)  NULL ,
	 	 DIS_COSATR numeric (17, 3)  NULL ,
		 DIS_RICLAI numeric (17, 3)  NULL ,
	 	 DIS_RICLAE numeric (17, 3)  NULL ,	
	 	 DIS_RICMAT numeric (17, 3)  NULL ,	
 	 	 DIS_RICATR numeric (17, 3)  NULL ,	
	 	 DIS_TIPOPR varchar (1) COLLATE Latin1_General_CI_AS NULL,
	 	 DIS_ORELAV varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 DIS_OREATT varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 DIS_OREIMP varchar (8) COLLATE Latin1_General_CI_AS NULL,
	 	 DIS_SECLAV numeric (8, 0)  NULL,
	 	 DIS_SECATT numeric (8, 0)  NULL,
	 	 DIS_SECIMP numeric (8, 0)  NULL,
	 	 DIS_FASELA varchar (8) COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[U_DIS_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_DIS_DD_DIS_COSLAI] DEFAULT (0) FOR [DIS_COSLAI],
	CONSTRAINT [DF_U_DIS_DD_DIS_COSLAE] DEFAULT (0) FOR [DIS_COSLAE],
	CONSTRAINT [DF_U_DIS_DD_DIS_COSMAT] DEFAULT (0) FOR [DIS_COSMAT],
	CONSTRAINT [DF_U_DIS_DD_DIS_COSATR] DEFAULT (0) FOR [DIS_COSATR],
	CONSTRAINT [DF_U_DIS_DD_DIS_RICLAI] DEFAULT (0) FOR [DIS_RICLAI],
	CONSTRAINT [DF_U_DIS_DD_DIS_RICLAE] DEFAULT (0) FOR [DIS_RICLAE],
	CONSTRAINT [DF_U_DIS_DD_DIS_RICMAT] DEFAULT (0) FOR [DIS_RICMAT],
	CONSTRAINT [DF_U_DIS_DD_DIS_RICATR] DEFAULT (0) FOR [DIS_RICATR],
	CONSTRAINT [DF_U_DIS_DD_DIS_TIPOPR] DEFAULT ('') FOR [DIS_TIPOPR],
	CONSTRAINT [DF_U_DIS_DD_DIS_ORELAV] DEFAULT ('') FOR [DIS_ORELAV],
	CONSTRAINT [DF_U_DIS_DD_DIS_OREATT] DEFAULT ('') FOR [DIS_OREATT],
	CONSTRAINT [DF_U_DIS_DD_DIS_OREIMP] DEFAULT ('') FOR [DIS_OREIMP],
	CONSTRAINT [DF_U_DIS_DD_DIS_SECLAV] DEFAULT (0) FOR [DIS_SECLAV],
	CONSTRAINT [DF_U_DIS_DD_DIS_SECATT] DEFAULT (0) FOR [DIS_SECATT],
	CONSTRAINT [DF_U_DIS_DD_DIS_SECIMP] DEFAULT (0) FOR [DIS_SECIMP],
	CONSTRAINT [DF_U_DIS_DD_DIS_FASELA] DEFAULT ('') FOR [DIS_FASELA]

go

UPDATE U_DIS_DD SET DIS_COSLAI 	= 0
UPDATE U_DIS_DD SET DIS_COSLAE 	= 0
UPDATE U_DIS_DD SET DIS_COSMAT 	= 0
UPDATE U_DIS_DD SET DIS_COSATR 	= 0
UPDATE U_DIS_DD SET DIS_RICLAI 	= 0
UPDATE U_DIS_DD SET DIS_RICLAE 	= 0
UPDATE U_DIS_DD SET DIS_RICMAT 	= 0
UPDATE U_DIS_DD SET DIS_RICATR 	= 0
UPDATE U_DIS_DD SET DIS_TIPOPR 	= ''
UPDATE U_DIS_DD SET DIS_ORELAV 	= ''
UPDATE U_DIS_DD SET DIS_OREATT 	= ''
UPDATE U_DIS_DD SET DIS_OREIMP 	= ''
UPDATE U_DIS_DD SET DIS_SECLAV 	= 0
UPDATE U_DIS_DD SET DIS_SECATT 	= 0
UPDATE U_DIS_DD SET DIS_SECIMP 	= 0
UPDATE U_DIS_DD SET DIS_FASELA 	= ''