
ALTER TABLE [dbo].[U_PRD_DS] ADD
	PRS_CTRLHS numeric(4,0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DS] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DS_PR4_CTRLHS] DEFAULT (0) FOR [PRS_CTRLHS]
go

UPDATE U_PRD_DS SET PRS_CTRLHS = 0


