
/*
*** Variabile per l'opzione gestita nella scheda "Altro", sottoscheda "Documenti" , sottoschede dei relativi documenti dei parametri di sistema  nel "form\menu_azi000.scx":
***		- Non stampa il commento 'PESO NETTO' negli ordini clienti estero
***		- Non stampa il commento 'PESO NETTO' nelle bolle estero
***		- Non stampa il commento 'PESO NETTO' nelle fatture estero
***		- Non stampa il commento 'PESO NETTO' nelle fatture proforma estero
*/


ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_NOSTPCOMPESORDEXT BIT NULL,
	AZI_NOSTPCOMPESBOLEXT BIT NULL,
	AZI_NOSTPCOMPESFATEXT BIT NULL,
	AZI_NOSTPCOMPESFAPEXT BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_NOSTPCOMPESORDEXT] DEFAULT (0) FOR [AZI_NOSTPCOMPESORDEXT],
	CONSTRAINT [DF_U_AZI_PB_AZI_NOSTPCOMPESBOLEXT] DEFAULT (0) FOR [AZI_NOSTPCOMPESBOLEXT],
	CONSTRAINT [DF_U_AZI_PB_AZI_NOSTPCOMPESFATEXT] DEFAULT (0) FOR [AZI_NOSTPCOMPESFATEXT],
	CONSTRAINT [DF_U_AZI_PB_AZI_NOSTPCOMPESFAPEXT] DEFAULT (0) FOR [AZI_NOSTPCOMPESFAPEXT]
GO

UPDATE U_AZI_PB SET AZI_NOSTPCOMPESORDEXT = 0
UPDATE U_AZI_PB SET AZI_NOSTPCOMPESBOLEXT = 0
UPDATE U_AZI_PB SET AZI_NOSTPCOMPESFATEXT = 0
UPDATE U_AZI_PB SET AZI_NOSTPCOMPESFAPEXT = 0