
if exists(select * from sys.columns where name = 'LIS_ATTBOLLO' and object_id = object_id(N'[dbo].[IMPIANTI_LI]'))
BEGIN
	ALTER TABLE IMPIANTI_LI DROP CONSTRAINT DF_IMPIANTI_LI_LIS_ATTBOLLO
	ALTER TABLE IMPIANTI_LI DROP COLUMN LIS_ATTBOLLO
END


ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ARTBOLLO varchar(35) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ARTBOLLO] DEFAULT ('')
GO




