
ALTER TABLE [dbo].[PARAMETRI_SCHEDULER] ADD 
   GGDAORF numeric (8) NULL,
   GGAORF numeric (8) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[PARAMETRI_SCHEDULER] WITH NOCHECK ADD 
    CONSTRAINT [DF_PARAMETRI_SCHEDULER_GGDAORF] DEFAULT ('0')   FOR [GGDAORF],
    CONSTRAINT [DF_PARAMETRI_SCHEDULER_GGAORF] DEFAULT ('0')   FOR [GGAORF]
go

UPDATE PARAMETRI_SCHEDULER SET GGDAORF 	= 0
UPDATE PARAMETRI_SCHEDULER SET GGAORF 	= 0