
ALTER TABLE [DBO].[U_OFF_TT] ADD 
	ORD_PRORIT numeric(7,3) NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_PRORIT] DEFAULT (0),
	ORD_SC1T numeric(7,3) NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_SC1T] DEFAULT (0),
	ORD_SC2T numeric(7,3) NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_SC2T] DEFAULT (0),
	ORD_SC3T numeric(7,3) NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_SC3T] DEFAULT (0)
GO
