

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_NONREG bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_NONREG] DEFAULT (0),
	AZI_PROGUNI bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_PROGUNI] DEFAULT (0)
GO




-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 0 (TRUE)
UPDATE U_AZI_PB SET AZI_NONREG = CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 0 ELSE 1 END


-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1 (TRUE)
UPDATE U_AZI_PB SET AZI_PROGUNI = CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 1 ELSE 0 END

