
ALTER TABLE [DBO].[U_AZI_PA] ADD 
	AZI_BOLIVA1 BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_BOLIVA1] DEFAULT (0) FOR [AZI_BOLIVA1]
GO

UPDATE U_AZI_PA SET AZI_BOLIVA1 = 0
