
 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_FLCONF  BIT NULL,
	AZI_FLDTCON  BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_FLCONF] DEFAULT (0) FOR [AZI_FLCONF],
	CONSTRAINT [DF_U_AZI_PB_AZI_FLDTCON] DEFAULT (0) FOR [AZI_FLDTCON]
GO

UPDATE U_AZI_PB SET AZI_FLCONF  = 0
UPDATE U_AZI_PB SET AZI_FLDTCON  = 0