ALTER TABLE [dbo].[U_IVA_TO] ADD 
	[ITO_DEDUCIBILE] [bit] NULL
go
ALTER TABLE [dbo].[U_IVA_TO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_IVA_TO_ITO_DEDUCIBILE] DEFAULT (0) FOR [ITO_DEDUCIBILE]
go

UPDATE U_IVA_TO SET ITO_DEDUCIBILE = 0
