SELECT MAG_GIACEN,MAG_QTAMQ,MAG_QTAKG,MAG_QTAML,MAG_QTAIMP,MAG_GKGIMP,MAG_GMLIMP,MAG_CODART,MAG_ANAART,* FROM U_MAG_GG WHERE MAG_QTAIMP < 0
SELECT MAG_GIACEN,MAG_QTAMQ,MAG_QTAKG,MAG_QTAML,MAG_QTAIMP,MAG_GKGIMP,MAG_GMLIMP,MAG_CODART,MAG_ANAART,* FROM U_MAG_GG WHERE MAG_QTAIMP > MAG_GIACEN

UPDATE U_MAG_GG SET MAG_QTAIMP = 0, MAG_GKGIMP = 0, MAG_GMLIMP = 0 WHERE MAG_QTAIMP < 0
UPDATE U_MAG_GG SET MAG_GKGIMP = 0, MAG_QTAIMP = 0, MAG_GMLIMP = 0 WHERE MAG_GKGIMP < 0
UPDATE U_MAG_GG SET MAG_GMLIMP = 0, MAG_GKGIMP = 0, MAG_QTAIMP = 0 WHERE MAG_GMLIMP < 0
UPDATE U_MAG_GG SET MAG_QTAIMP = MAG_GIACEN, MAG_GKGIMP = MAG_QTAKG, MAG_GMLIMP = MAG_QTAML WHERE MAG_QTAIMP > MAG_GIACEN 
