
-- TABELLE PARTITARI
ALTER TABLE [PART_CLI] ALTER COLUMN	 PAR_TIPFAT varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [PART_FOR] ALTER COLUMN	 PAR_TIPFAT varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO


-- TABELLE MOV_CONT/INDICE/MOV_CCO
ALTER TABLE [MOV_CONT] ALTER COLUMN	 MOV_MODPAG varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [MOV_CCO] ALTER COLUMN	 MOV_MODPAG varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [INDICE] ALTER COLUMN	 MOV_MODPAG varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO






-- TABELLE CON RICERCA PER CAMPO TOP 

ALTER TABLE [dbo].[C_IVA_CL] ALTER COLUMN	iva_top varchar(10) COLLATE Latin1_General_CI_AS NULL
GO 
ALTER TABLE [dbo].[C_IVF_CL] ALTER COLUMN	IVF_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[INDICE] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[INTRASTAT] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[INTRASTAT] ALTER COLUMN	TOP_INTRA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[INTRASTAT] ALTER COLUMN	TOP_CLI_FOR varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[MO_CONCA] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[MOV_CCO] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[MOV_CONT] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[PRODUZIONE] ALTER COLUMN	TOPCAP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[PRODUZIONE] ALTER COLUMN	TOPSCP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[PROV_STO] ALTER COLUMN	ORD_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[PROVVI] ALTER COLUMN	ORD_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[S_MAG_MO] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[u_amm_ad] ALTER COLUMN	AMD_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_ANF_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PA] ALTER COLUMN	AZI_TOPINV varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PA] ALTER COLUMN	AZI_TOPCAM varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PA] ALTER COLUMN	azi_TOPPNC varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PA] ALTER COLUMN	azi_TOPTRI varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PB] ALTER COLUMN	AZI_ANTCLI_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_AZI_PB] ALTER COLUMN	AZI_TOPINT varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_BAN_AN] ALTER COLUMN	BAN_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_BFO_LE] ALTER COLUMN	LEG_TOPPRN varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_BOL_RE] ALTER COLUMN	ORF_TOPSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_CAN_CO] ALTER COLUMN	ORF_TOPSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_CAN_RE] ALTER COLUMN	ORF_TOPSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_CCO_LE] ALTER COLUMN	LEG_CODTOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_CLI_OP] ALTER COLUMN	CLI_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_CMP_TT] ALTER COLUMN	CMP_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_FOR_AN] ALTER COLUMN	FOR_TOPCGE varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_IVA_CL] ALTER COLUMN	iva_top varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_IVA_CS] ALTER COLUMN	iva_top varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_IVF_CL] ALTER COLUMN	IVF_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[u_lot_ri] ALTER COLUMN	LOT_DATOPE varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAC_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_CA] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_CL] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_DM] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_MO] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_MO_NEW] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAG_MS] ALTER COLUMN	MOV_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_MAN_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_ORF_CO] ALTER COLUMN	ORF_TOPSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_ORF_PO] ALTER COLUMN	ORF_TOPSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_PAP_AN] ALTER COLUMN	PAP_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_PDV_CA] ALTER COLUMN	CAS_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_PDV_IN] ALTER COLUMN	CGE_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_PFO_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_RIC_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_RIM_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_TOP_MO] ALTER COLUMN	TOP_CAUSCA varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_TOP_MO] ALTER COLUMN	TOP_CAUCAR varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [dbo].[U_VER_TT] ALTER COLUMN	RIC_TOP varchar(10) COLLATE Latin1_General_CI_AS NULL
GO

-- TABELLE CON RICERCA PER CAMPO ORD_CAUS 

ALTER TABLE [CONTRMDB] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [L_BOL_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AMM_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_BCL_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_BFO_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_BOF_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_BOL_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_BOL_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_CCO_DD] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_CEA_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_CEI_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_COM_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_CTL_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_FAM_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_FAP_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_FAT_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_FAT_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_MRI_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_NCR_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_OFF_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_OFF_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_ORD_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_ORD_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_ORF_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_ORF_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PCK_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PRB_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PRF_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PRO_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_RAA_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_RIA_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_RIN_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_SPE_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_STA_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_STA_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_TVE_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_TVE_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_WRK_ST] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_WRK_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [VENDITE_TT] ALTER COLUMN	ORD_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL

	
-- TABELLE CON RICERCA PER CAMPO CAUS


ALTER TABLE [PROD_PACKFOR] ALTER COLUMN	CAUSXDDT  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [PROD_PACKING] ALTER COLUMN	CAUSXDDT  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN	AZI_CAUSAL  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN	AZI_CAUSSP  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN	AZI_CAUSFA  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN	AZI_CAUSOS  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN	AZI_CAUSMP  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN	AZI_CAUSPR  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN	AZI_CAUSCL  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_AZI_PB] ALTER COLUMN	AZI_CAUSCG  varchar(10) COLLATE Latin1_General_CI_AS NULL							
GO
ALTER TABLE [U_FOR_TT] ALTER COLUMN	FOR_CAUS  varchar(10) COLLATE Latin1_General_CI_AS NULL							


-- TABELLE CON RICERCA PER CAMPO CAU

ALTER TABLE [U_AVA_CO] ALTER COLUMN	 AVA_CODCAU varchar(10) COLLATE Latin1_General_CI_AS NULL 
GO
ALTER TABLE [U_AVA_CO] ALTER COLUMN  AVA_CONCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AVA_MQ] ALTER COLUMN  AVA_CODCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUDIR varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUANT varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUAVA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUSAL varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUCFO varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUCSP varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUSSP varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUSFA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAULES varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUCMA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAURIF varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUREC varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUCAS varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUREF varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUPDV varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUTRA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_AN] ALTER COLUMN  AZI_CAUSOS varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUMOV varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUVBA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUGNE varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUSMP varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAURIM varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUSPR varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUCAL varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUSCL varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
--ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_PKNCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
--GO
ALTER TABLE [U_AZI_PA] ALTER COLUMN  AZI_CAUDEP varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PB] ALTER COLUMN  AZI_CAUEXC varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PB] ALTER COLUMN  AZI_CAUEXS varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_AZI_PB] ALTER COLUMN  AZI_CAUSCG varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_INC_AN] ALTER COLUMN  INC_CODCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_LOC_MO] ALTER COLUMN  LOC_CAUSAL varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_lot_ri] ALTER COLUMN  LOT_CODCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PAG_AN] ALTER COLUMN  PAG_CODCAU varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PDA_MO] ALTER COLUMN  INV_CAUSCA varchar(10) COLLATE Latin1_General_CI_AS NULL
GO
ALTER TABLE [U_PDA_MO] ALTER COLUMN  INV_CAUCAR varchar(10) COLLATE Latin1_General_CI_AS NULL
GO







	
