
/* 
*****************************************************************************
INSERIMENTO CAMPO ORD_PARENT PER LA GESTIONE DELLE RIGHE DOCUMENTO NIDIFICATE
*****************************************************************************
*/
ALTER TABLE [dbo].[U_OFF_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_U_OFF_DD_ORD_PARENT] DEFAULT (0)
go

ALTER TABLE [dbo].[U_ORD_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_U_ORD_DD_ORD_PARENT] DEFAULT (0)
go

ALTER TABLE [dbo].[U_BOL_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_U_BOL_DD_ORD_PARENT] DEFAULT (0)
go

ALTER TABLE [dbo].[L_BOL_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_L_BOL_DD_ORD_PARENT] DEFAULT (0)
go

ALTER TABLE [dbo].[U_FAT_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_U_FAT_DD_ORD_PARENT] DEFAULT (0)
go

ALTER TABLE [dbo].[U_FAP_DD] ADD 
	ORD_PARENT NUMERIC(10,0) NOT NULL CONSTRAINT [DF_U_FAP_DD_ORD_PARENT] DEFAULT (0)
go
