/*
ALLARGAMENTO CAMPI SCHEDA "CONDIZIONI DI FORNITURA" GESTITI IN MENU_OFF000.SCX
*/

ALTER TABLE [dbo].[U_OFF_TT] ALTER COLUMN ORD_NORME1 varchar(200) COLLATE Latin1_General_CI_AS
ALTER TABLE [dbo].[U_OFF_TT] ALTER COLUMN ORD_NORME2 varchar(200) COLLATE Latin1_General_CI_AS
ALTER TABLE [dbo].[U_OFF_TT] ALTER COLUMN ORD_COMMIS varchar(200) COLLATE Latin1_General_CI_AS
ALTER TABLE [dbo].[U_OFF_TT] ALTER COLUMN ORD_DESPES varchar(200) COLLATE Latin1_General_CI_AS
ALTER TABLE [dbo].[U_OFF_TT] ALTER COLUMN ORD_GGCONS varchar(200) COLLATE Latin1_General_CI_AS
