
/* 
**************************************************************
INSERIMENTO CAMPI PER QUANTITA' PRODOTTE IN PORTAFOGLIO ORDINI
**************************************************************
*/
ALTER TABLE [dbo].[U_OFF_DD] ADD 
	ORD_NUMBOD numeric (6,0) NULL,
	ORD_QTADEV2 numeric (17,4) NULL,
	ORD_NUMBOD2 numeric (6,0) NULL,
	ORD_QTADEV3 numeric (17,4) NULL,
	ORD_NUMBOD3 numeric (6,0) NULL
go

ALTER TABLE [dbo].[U_OFF_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_OFF_DD_ORD_NUMBOD] DEFAULT (0) FOR [ORD_NUMBOD],
	CONSTRAINT [DF_U_OFF_DD_ORD_QTADEV2] DEFAULT (0) FOR [ORD_QTADEV2],
	CONSTRAINT [DF_U_OFF_DD_ORD_NUMBOD2] DEFAULT (0) FOR [ORD_NUMBOD2],
	CONSTRAINT [DF_U_OFF_DD_ORD_QTAPRD3] DEFAULT (0) FOR [ORD_QTAPRD3],
	CONSTRAINT [DF_U_OFF_DD_ORD_NUMBOD3] DEFAULT (0) FOR [ORD_NUMBOD3]
go

UPDATE U_OFF_DD SET ORD_NUMBOD = 0
UPDATE U_OFF_DD SET ORD_QTADEV2 = 0
UPDATE U_OFF_DD SET ORD_NUMBOD2 = 0
UPDATE U_OFF_DD SET ORD_QTADEV3 = 0
UPDATE U_OFF_DD SET ORD_NUMBOD3 = 0




   