
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_DR] ADD
	PRR_FLGMOD BIT NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_PRR_FLGMOD] DEFAULT (0) FOR [PRR_FLGMOD]
go

UPDATE U_PRD_DR SET PRR_FLGMOD = 0
