/* 
********************************************************************************
AGGIUNTA CAMPI PER TRACCIATURA INSERIMENTI E MODIFICHE
********************************************************************************
*/

ALTER TABLE [dbo].[PARA] ADD 
	REG_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_REG_CODOPE] DEFAULT (''),
	REG_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_REG_NOMOPE] DEFAULT (''),
	REG_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_REG_DATREG] DEFAULT (''),
	REG_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_REG_ORAREG] DEFAULT (''),
	MOD_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_MOD_CODOPE] DEFAULT (''),
	MOD_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_MOD_NOMOPE] DEFAULT (''),
	MOD_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_MOD_DATREG] DEFAULT (''),
	MOD_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_PARA_MOD_ORAREG] DEFAULT ('')
go

UPDATE PARA SET REG_DATREG = (CASE PAR_DATINS WHEN '' THEN '1950/01/01' ELSE COALESCE(PAR_DATINS,'') END)
UPDATE PARA SET MOD_DATREG = (CASE PAR_DATINS WHEN '' THEN '1950/01/01' ELSE COALESCE(PAR_DATINS,'') END)
