

ALTER TABLE [DBO].[U_FAT_TT] ADD 
	T_NORAENPA BIT NULL
GO

ALTER TABLE [DBO].[U_FAT_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAT_TT_T_NORAENPA] DEFAULT (0) FOR [T_NORAENPA]
GO

UPDATE U_FAT_TT SET T_NORAENPA = 0
