
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D4] ADD
	PR4_FLGMOD BIT NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_FLGMOD] DEFAULT (0) FOR [PR4_FLGMOD]
go

UPDATE U_PRD_D4 SET PR4_FLGMOD = 0
