
ALTER TABLE [dbo].[U_FOR_AN] ALTER COLUMN
	 FOR_RAGLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO


ALTER TABLE [dbo].[U_FOR_AN] ALTER COLUMN
	 FOR_RGLEG2 varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_FOR_AN] ALTER COLUMN
	 FOR_INDLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_FOR_AN] ALTER COLUMN
	 FOR_LOCLEG varchar(80) COLLATE Latin1_General_CI_AS NULL
GO

