ALTER TABLE [dbo].[U_IVF_CL] ADD 
	[IVF_DL78] [bit] NULL
go
ALTER TABLE [dbo].[U_IVF_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_IVF_CL_IVF_DL78] DEFAULT (0) FOR [IVF_DL78]
go

UPDATE U_IVF_CL SET IVF_DL78 = 0
