ALTER TABLE [dbo].[U_MAG_MO] ADD 
	 MOV_FLGCEL [bit] NULL,
	 MOV_QTACON numeric(10,2) NULL,
	 MOV_SERBOL varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SERNUM varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MOV_NUMEDA numeric(9) NULL,
	 MOV_NUMEAL numeric(9) NULL,
	 MOV_CBFISC varchar(50) COLLATE Latin1_General_CI_AS NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_FLGCEL] DEFAULT (0) FOR [MOV_FLGCEL],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTACON] DEFAULT (0) FOR [MOV_QTACON],
	CONSTRAINT [DF_U_MAG_MO_MOV_SERBOL] DEFAULT ('') FOR [MOV_SERBOL],
	CONSTRAINT [DF_U_MAG_MO_MOV_SERNUM] DEFAULT ('') FOR [MOV_SERNUM],
	CONSTRAINT [DF_U_MAG_MO_MOV_NUMEDA] DEFAULT ('') FOR [MOV_NUMEDA],
	CONSTRAINT [DF_U_MAG_MO_MOV_NUMEAL] DEFAULT ('') FOR [MOV_NUMEAL],
	CONSTRAINT [DF_U_MAG_MO_MOV_CBFISC] DEFAULT ('') FOR [MOV_CBFISC]
go

UPDATE U_MAG_MO SET MOV_FLGCEL = 0
UPDATE U_MAG_MO SET MOV_QTACON = 0
UPDATE U_MAG_MO SET MOV_SERBOL = SPACE(03)
UPDATE U_MAG_MO SET MOV_SERNUM = SPACE(03)
UPDATE U_MAG_MO SET MOV_NUMEDA = 0
UPDATE U_MAG_MO SET MOV_NUMEAL = 0
UPDATE U_MAG_MO SET MOV_CBFISC = SPACE(50)
