
ALTER TABLE [dbo].[U_LOC_AN] ALTER COLUMN
	 LOC_VARIE varchar(150) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_LOC_AN] ALTER COLUMN
	 LOC_RAGSOC varchar(100) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_LOC_AN] ALTER COLUMN
	 LOC_LOCALI varchar(100) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_LOC_AN] ALTER COLUMN
	 LOC_INDIRI varchar(100) COLLATE Latin1_General_CI_AS NULL
GO

