


 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_STOPACQ  BIT NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_STOPACQ] DEFAULT (0) FOR [AZI_STOPACQ]
GO

UPDATE U_AZI_PB SET AZI_STOPACQ  = 0