ALTER TABLE [dbo].[U_MAG_MO] ADD 
	 MOV_QTAKGA numeric(11,2) NULL,
	 MOV_QTAMQA numeric(11,2) NULL,
	 MOV_QTAMLA numeric(11,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAKGA] DEFAULT (0) FOR [MOV_QTAKGA],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAMQA] DEFAULT (0) FOR [MOV_QTAMQA],
	CONSTRAINT [DF_U_MAG_MO_MOV_QTAMLA] DEFAULT (0) FOR [MOV_QTAMLA]
go

UPDATE U_MAG_MO SET MOV_QTAKGA = 0
UPDATE U_MAG_MO SET MOV_QTAMQA = 0
UPDATE U_MAG_MO SET MOV_QTAMLA = 0


ALTER TABLE [dbo].[U_MAG_CA] ADD 
	 MOV_QTAKGA numeric(11,2) NULL,
	 MOV_QTAMQA numeric(11,2) NULL,
	 MOV_QTAMLA numeric(11,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_CA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAKGA] DEFAULT (0) FOR [MOV_QTAKGA],
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAMQA] DEFAULT (0) FOR [MOV_QTAMQA],
	CONSTRAINT [DF_U_MAG_CA_MOV_QTAMLA] DEFAULT (0) FOR [MOV_QTAMLA]
go

UPDATE U_MAG_CA SET MOV_QTAKGA = 0
UPDATE U_MAG_CA SET MOV_QTAMQA = 0
UPDATE U_MAG_CA SET MOV_QTAMLA = 0
