
-- ALLARGAMENTO CAMPI PER CONTROLLO BOLLE/FATTURE

ALTER TABLE [dbo].[U_BFO_DD] ALTER COLUMN
	 CBF_NDOC varchar(20) COLLATE Latin1_General_CI_AS NOT NULL
GO

ALTER TABLE [dbo].[U_BFO_LE] ALTER COLUMN
	 LEG_NUMPRN varchar(20) COLLATE Latin1_General_CI_AS NOT NULL
GO


