
 
ALTER TABLE [DBO].[U_BFO_DD] ADD 
	ORD_PRSPOT  BIT NULL
GO

ALTER TABLE [DBO].[U_BFO_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BFO_DD_ORD_PRSPOT] DEFAULT (0) FOR [ORD_PRSPOT]
GO

UPDATE U_BFO_DD SET ORD_PRSPOT  = 0