/*
*** Variabili per le opzioni gestite nella scheda "LIPE Xml" per la gestione della liquidazione iva trimestrale (LIPE) 
*** dei parametri di sistema  nel "form\menu_azi000.scx":
*/

ALTER TABLE [DBO].[U_AZI_PC] ADD 
	AZI_FORNITURA varchar (254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_FORNITURA] DEFAULT (''),
	AZI_LIQUIDA_GRUPPO varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_LIQUIDA_GRUPPO] DEFAULT (''),
	AZI_CODFIS_DICHIAR varchar (16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_CODFIS_DICHIAR] DEFAULT (''),
	AZI_CARICA_DICHIAR varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_CARICA_DICHIAR] DEFAULT (''),
	AZI_FIRMA_DICHIAR varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_FIRMA_DICHIAR] DEFAULT (''),
	AZI_CODFIS_INTERM varchar (16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_CODFIS_INTERM] DEFAULT (''),
	AZI_IMPEGNO_CONTR varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_IMPEGNO_CONTR] DEFAULT (''),
	AZI_FIRMA_INTERM varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_FIRMA_INTERM] DEFAULT (''),
	AZI_FLAG_CONFERMA varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_FLAG_CONFERMA] DEFAULT (''),
	AZI_NUM_MODULO varchar (2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PC_AZI_NUM_MODULO] DEFAULT ('')
GO






