--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_TURNO varchar(3) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_TURNO] DEFAULT ('') FOR [PR5_TURNO]
go

UPDATE U_PRD_D5 SET PR5_TURNO = ''
