


 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_SICONS  BIT NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_SICONS] DEFAULT (0) FOR [AZI_SICONS]
GO

UPDATE U_AZI_PB SET AZI_SICONS  = 0