/*
*** NUOVO CAMPO PER OPZIONE "Inserisce sempre Partita IVA e Codice Fiscale" IN FATTURA ELETTRONICA
*/

ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_FEPICF BIT NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_FEPICF] DEFAULT (0)
GO
