
ALTER TABLE [dbo].[U_MAG_GG] ADD MAG_ORACAR varchar (8) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD CONSTRAINT [DF_U_MAG_GG_MAG_ORACAR] DEFAULT ('') FOR [MAG_ORACAR]
GO

UPDATE U_MAG_GG SET MAG_ORACAR = ''
GO
