ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAORD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTADEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAOLD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAFAT] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAPAR] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAORG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAORF] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAORP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTABOL] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTADAC] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAACC] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAKG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMQ] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAML] NUMERIC(12,4) NULL
GO


ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAKG1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMQ1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAML1] NUMERIC(12,4) NULL
GO


if exists (select * from sys.indexes where name = 'INDICE_01' and object_id = object_id(N'[dbo].[U_ORD_DL]'))
	DROP INDEX INDICE_01 ON U_ORD_DL
GO
ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAKGE] NUMERIC(12,4) NULL
GO


ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMQE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMLE] NUMERIC(12,4) NULL
GO




ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAKGD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMQD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTAMLD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTF] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTX] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTO] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTY] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTASPD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTASPP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTARID] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTARIP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTATGO] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTATGD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QTATGP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTR] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN
	 [ORD_QUANTT] NUMERIC(12,4) NULL
GO




