

ALTER TABLE [DBO].[U_FAP_TT] ADD 
	T_NORA BIT NULL
GO

ALTER TABLE [DBO].[U_FAP_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAP_TT_T_NORA] DEFAULT (0) FOR [T_NORA]
GO

UPDATE U_FAP_TT SET T_NORA = 0
