
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_MO] ADD 
	 MOV_PRZCAM [numeric](17, 6) NULL ,
	 MOV_NUMCAM varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DATCAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_INICAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_FINCAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SC1CAM [numeric](6, 2) NULL,
	 MOV_SC2CAM [numeric](6, 2) NULL,
	 MOV_SC3CAM [numeric](6, 2) NULL,
	 MOV_SC4CAM [numeric](6, 2) NULL,
	 MOV_SC5CAM [numeric](6, 2) NULL,
	 MOV_FISCAM [numeric](17, 6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_PRZCAM] DEFAULT (0) FOR [MOV_PRZCAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_NUMCAM] DEFAULT ('') FOR [MOV_NUMCAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_DATCAM] DEFAULT ('') FOR [MOV_DATCAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_INICAM] DEFAULT ('') FOR [MOV_INICAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_FINCAM] DEFAULT ('') FOR [MOV_FINCAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_SC1CAM] DEFAULT (0) FOR [MOV_SC1CAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_SC2CAM] DEFAULT (0) FOR [MOV_SC2CAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_SC3CAM] DEFAULT (0) FOR [MOV_SC3CAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_SC4CAM] DEFAULT (0) FOR [MOV_SC4CAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_SC5CAM] DEFAULT (0) FOR [MOV_SC5CAM],
	CONSTRAINT [DF_U_MAG_MO_MOV_FISCAM] DEFAULT (0) FOR [MOV_FISCAM]
go

UPDATE U_MAG_MO SET MOV_PRZCAM = 0
UPDATE U_MAG_MO SET MOV_NUMCAM = SPACE(06)
UPDATE U_MAG_MO SET MOV_DATCAM = SPACE(10)
UPDATE U_MAG_MO SET MOV_INICAM = SPACE(10)
UPDATE U_MAG_MO SET MOV_FINCAM = SPACE(10)
UPDATE U_MAG_MO SET MOV_SC1CAM = 0
UPDATE U_MAG_MO SET MOV_SC2CAM = 0
UPDATE U_MAG_MO SET MOV_SC3CAM = 0
UPDATE U_MAG_MO SET MOV_SC4CAM = 0
UPDATE U_MAG_MO SET MOV_SC5CAM = 0
UPDATE U_MAG_MO SET MOV_FISCAM = 0


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_MAG_CA] ADD 
	 MOV_PRZCAM [numeric](17, 6) NULL ,
	 MOV_NUMCAM varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 MOV_DATCAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_INICAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_FINCAM varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 MOV_SC1CAM [numeric](6, 2) NULL,
	 MOV_SC2CAM [numeric](6, 2) NULL,
	 MOV_SC3CAM [numeric](6, 2) NULL,
	 MOV_SC4CAM [numeric](6, 2) NULL,
	 MOV_SC5CAM [numeric](6, 2) NULL,
	 MOV_FISCAM [numeric](17, 6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_CA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_CA_MOV_PRZCAM] DEFAULT (0) FOR [MOV_PRZCAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_NUMCAM] DEFAULT ('') FOR [MOV_NUMCAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_DATCAM] DEFAULT ('') FOR [MOV_DATCAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_INICAM] DEFAULT ('') FOR [MOV_INICAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_FINCAM] DEFAULT ('') FOR [MOV_FINCAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC1CAM] DEFAULT (0) FOR [MOV_SC1CAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC2CAM] DEFAULT (0) FOR [MOV_SC2CAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC3CAM] DEFAULT (0) FOR [MOV_SC3CAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC4CAM] DEFAULT (0) FOR [MOV_SC4CAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_SC5CAM] DEFAULT (0) FOR [MOV_SC5CAM],
	CONSTRAINT [DF_U_MAG_CA_MOV_FISCAM] DEFAULT (0) FOR [MOV_FISCAM]
go

UPDATE U_MAG_CA SET MOV_PRZCAM = 0
UPDATE U_MAG_CA SET MOV_NUMCAM = SPACE(06)
UPDATE U_MAG_CA SET MOV_DATCAM = SPACE(10)
UPDATE U_MAG_CA SET MOV_INICAM = SPACE(10)
UPDATE U_MAG_CA SET MOV_FINCAM = SPACE(10)
UPDATE U_MAG_CA SET MOV_SC1CAM = 0
UPDATE U_MAG_CA SET MOV_SC2CAM = 0
UPDATE U_MAG_CA SET MOV_SC3CAM = 0
UPDATE U_MAG_CA SET MOV_SC4CAM = 0
UPDATE U_MAG_CA SET MOV_SC5CAM = 0
UPDATE U_MAG_CA SET MOV_FISCAM = 0
