/*
*** NUOVO CAMPO PER GESTIONE EMEIL PEC SULLE FATTURE
*/


ALTER TABLE [DBO].[U_FAT_TT] ADD 
	ORD_EPEC varchar(200) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FAT_TT_ORD_EPEC] DEFAULT ('')
GO
