
ALTER TABLE [dbo].[U_PRD_D4] ADD 
	PR4_NPRGTG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR4_DPRGTG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR4_OPRGTG varchar(8) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_NPRGTG] DEFAULT ('') FOR [PR4_NPRGTG],
	CONSTRAINT [DF_U_PRD_D4_PR4_DPRGTG] DEFAULT ('') FOR [PR4_DPRGTG],
	CONSTRAINT [DF_U_PRD_D4_PR4_OPRGTG] DEFAULT ('') FOR [PR4_OPRGTG]
go

UPDATE U_PRD_D4 SET PR4_NPRGTG = ''
UPDATE U_PRD_D4 SET PR4_DPRGTG = ''
UPDATE U_PRD_D4 SET PR4_OPRGTG = ''

