/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_IVA_CR] ADD 
	IVA_CLO01 BIT NULL,
	IVA_CLO02 BIT NULL,
	IVA_CLO03 BIT NULL,
	IVA_CLO04 BIT NULL,
	IVA_CLO05 BIT NULL,
	IVA_CLO06 BIT NULL,
	IVA_CLO07 BIT NULL,
	IVA_CLO08 BIT NULL,
	IVA_CLO09 BIT NULL,
	IVA_CLO10 BIT NULL,
	IVA_CLO11 BIT NULL,
	IVA_CLO12 BIT NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_IVA_CR] WITH NOCHECK ADD
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO01] DEFAULT (0) FOR [IVA_CLO01],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO02] DEFAULT (0) FOR [IVA_CLO02],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO03] DEFAULT (0) FOR [IVA_CLO03],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO04] DEFAULT (0) FOR [IVA_CLO04],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO05] DEFAULT (0) FOR [IVA_CLO05],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO06] DEFAULT (0) FOR [IVA_CLO06],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO07] DEFAULT (0) FOR [IVA_CLO07],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO08] DEFAULT (0) FOR [IVA_CLO08],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO09] DEFAULT (0) FOR [IVA_CLO09],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO10] DEFAULT (0) FOR [IVA_CLO10],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO11] DEFAULT (0) FOR [IVA_CLO11],
	CONSTRAINT [DF_U_IVA_CR_IVA_CLO12] DEFAULT (0) FOR [IVA_CLO12]
go

UPDATE U_IVA_CR SET IVA_CLO01 = 0
UPDATE U_IVA_CR SET IVA_CLO02 = 0
UPDATE U_IVA_CR SET IVA_CLO03 = 0
UPDATE U_IVA_CR SET IVA_CLO04 = 0
UPDATE U_IVA_CR SET IVA_CLO05 = 0
UPDATE U_IVA_CR SET IVA_CLO06 = 0
UPDATE U_IVA_CR SET IVA_CLO07 = 0
UPDATE U_IVA_CR SET IVA_CLO08 = 0
UPDATE U_IVA_CR SET IVA_CLO09 = 0
UPDATE U_IVA_CR SET IVA_CLO10 = 0
UPDATE U_IVA_CR SET IVA_CLO11 = 0
UPDATE U_IVA_CR SET IVA_CLO12 = 0

