
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PDV_AN] ADD 
	 PDV_CODSRI varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSRI varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSPT varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSPT varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSIN varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSIN varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSME varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSME varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSIM varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSIM varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSBO varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSBO varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSVA varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSVA varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODSCV varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESSCV varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODTRI varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESTRI varchar(40) COLLATE Latin1_General_CI_AS NULL,
	 PDV_CODACQ varchar(13) COLLATE Latin1_General_CI_AS NULL,
	 PDV_DESACQ varchar(40) COLLATE Latin1_General_CI_AS NULL
	 
go
ALTER TABLE [dbo].[U_PDV_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSRI] DEFAULT ('') FOR [PDV_CODSRI],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSRI] DEFAULT ('') FOR [PDV_DESSRI],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSPT] DEFAULT ('') FOR [PDV_CODSPT],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSPT] DEFAULT ('') FOR [PDV_DESSPT],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSIN] DEFAULT ('') FOR [PDV_CODSIN],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSIN] DEFAULT ('') FOR [PDV_DESSIN],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSME] DEFAULT ('') FOR [PDV_CODSME],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSME] DEFAULT ('') FOR [PDV_DESSME],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSIM] DEFAULT ('') FOR [PDV_CODSIM],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSIM] DEFAULT ('') FOR [PDV_DESSIM],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSBO] DEFAULT ('') FOR [PDV_CODSBO],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSBO] DEFAULT ('') FOR [PDV_DESSBO],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSVA] DEFAULT ('') FOR [PDV_CODSVA],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSVA] DEFAULT ('') FOR [PDV_DESSVA],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODSCV] DEFAULT ('') FOR [PDV_CODSCV],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESSCV] DEFAULT ('') FOR [PDV_DESSCV],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODTRI] DEFAULT ('') FOR [PDV_CODTRI],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESTRI] DEFAULT ('') FOR [PDV_DESTRI],
	CONSTRAINT [DF_U_PDV_AN_PDV_CODACQ] DEFAULT ('') FOR [PDV_CODACQ],
	CONSTRAINT [DF_U_PDV_AN_PDV_DESACQ] DEFAULT ('') FOR [PDV_DESACQ]
	

go


UPDATE U_PDV_AN SET PDV_CODSRI = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSRI = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSPT = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSPT = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSIN = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSIN = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSME = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSME = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSIM = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSIM = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSBO = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSBO = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSVA = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSVA = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODSCV = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESSCV = SPACE(40)

UPDATE U_PDV_AN SET PDV_CODTRI = SPACE(13)
UPDATE U_PDV_AN SET PDV_DESTRI = SPACE(40)

