
UPDATE PARA SET LIBERA = 'BFOPJETI_RI2.FRX   BFOPJETC_RI2.FRX    BFOPJETM_RI2.FRX' WHERE CODICE = 'EMP01'

SELECT * FROM PARA WHERE CODICE = 'EMP01'
SELECT SUBSTRING(LIBERA,1,16) AS REPORT_BOBINE_MP     FROM PARA WHERE CODICE = 'EMP01'
SELECT SUBSTRING(LIBERA,20,16) AS REPORT_ADESIVI_MP   FROM PARA WHERE CODICE = 'EMP01'
SELECT SUBSTRING(LIBERA,40,16) AS REPORT_MANICOTTI_MP FROM PARA WHERE CODICE = 'EMP01'