/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_AVA_SP] ADD 
	 AVA_FLGINT varchar(01) COLLATE Latin1_General_CI_AS NULL,
	 AVA_DATINT varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 AVA_ORAINT varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 AVA_OPEINT varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 AVA_MACOLD varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 AVA_DATOLD varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 AVA_ORAOLD varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 AVA_LUNOLD numeric(6) NULL,
	 AVA_ALTOLD numeric(5) NULL,
	 AVA_MACDIG varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 AVA_DATDIG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 AVA_ORADIG varchar(08) COLLATE Latin1_General_CI_AS NULL,
	 AVA_LUNDIG numeric(6) NULL,
	 AVA_ALTDIG numeric(5) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AVA_SP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AVA_SP_AVA_FLGINT] DEFAULT ('') FOR [AVA_FLGINT],
	CONSTRAINT [DF_U_AVA_SP_AVA_DATINT] DEFAULT ('') FOR [AVA_DATINT],
	CONSTRAINT [DF_U_AVA_SP_AVA_ORAINT] DEFAULT ('') FOR [AVA_ORAINT],
	CONSTRAINT [DF_U_AVA_SP_AVA_OPEINT] DEFAULT ('') FOR [AVA_OPEINT],
	CONSTRAINT [DF_U_AVA_SP_AVA_MACOLD] DEFAULT ('') FOR [AVA_MACOLD],
	CONSTRAINT [DF_U_AVA_SP_AVA_DATOLD] DEFAULT ('') FOR [AVA_DATOLD],
	CONSTRAINT [DF_U_AVA_SP_AVA_ORAOLD] DEFAULT ('') FOR [AVA_ORAOLD],
	CONSTRAINT [DF_U_AVA_SP_AVA_LUNOLD] DEFAULT (0) FOR [AVA_LUNOLD],
	CONSTRAINT [DF_U_AVA_SP_AVA_ALTOLD] DEFAULT (0) FOR [AVA_ALTOLD],
	CONSTRAINT [DF_U_AVA_SP_AVA_MACDIG] DEFAULT ('') FOR [AVA_MACDIG],
	CONSTRAINT [DF_U_AVA_SP_AVA_DATDIG] DEFAULT ('') FOR [AVA_DATDIG],
	CONSTRAINT [DF_U_AVA_SP_AVA_ORADIG] DEFAULT ('') FOR [AVA_ORADIG],
	CONSTRAINT [DF_U_AVA_SP_AVA_LUNDIG] DEFAULT (0) FOR [AVA_LUNDIG],
	CONSTRAINT [DF_U_AVA_SP_AVA_ALTDIG] DEFAULT (0) FOR [AVA_ALTDIG]
go

UPDATE U_AVA_SP SET AVA_FLGINT = SPACE(01)
UPDATE U_AVA_SP SET AVA_DATINT = SPACE(10)
UPDATE U_AVA_SP SET AVA_ORAINT = SPACE(08)
UPDATE U_AVA_SP SET AVA_OPEINT = SPACE(05)
UPDATE U_AVA_SP SET AVA_MACOLD = SPACE(03)
UPDATE U_AVA_SP SET AVA_DATOLD = SPACE(10)
UPDATE U_AVA_SP SET AVA_ORAOLD = SPACE(08)
UPDATE U_AVA_SP SET AVA_LUNOLD = 0
UPDATE U_AVA_SP SET AVA_ALTOLD = 0
UPDATE U_AVA_SP SET AVA_MACDIG = SPACE(03)
UPDATE U_AVA_SP SET AVA_DATDIG = SPACE(10)
UPDATE U_AVA_SP SET AVA_ORADIG = SPACE(08)
UPDATE U_AVA_SP SET AVA_LUNDIG = 0
UPDATE U_AVA_SP SET AVA_ALTDIG = 0
