
-- ALLARGAMENTO CAMPI TEMPI PRODUTTIVI A 11 CARATTERI
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_ORELAV VARCHAR(11) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_OREATT VARCHAR(11) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_OREIMP VARCHAR(11) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_SECLAV numeric(12,0) NULL
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_SECATT numeric(12,0) NULL
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_SECIMP numeric(12,0) NULL


UPDATE U_ART_PR SET ART_ORELAV = '000'+ART_ORELAV WHERE ART_ORELAV <> '' AND LEN(RTRIM(ART_ORELAV)) = 8
UPDATE U_ART_PR SET ART_OREATT = '000'+ART_OREATT WHERE ART_OREATT <> '' AND LEN(RTRIM(ART_OREATT)) = 8
UPDATE U_ART_PR SET ART_OREIMP = '000'+ART_OREIMP WHERE ART_OREIMP <> '' AND LEN(RTRIM(ART_OREIMP)) = 8

UPDATE U_ART_PR SET ART_ORELAV = '00000:00:00' WHERE ART_ORELAV = ''
UPDATE U_ART_PR SET ART_OREATT = '00000:00:00' WHERE ART_OREATT = ''
UPDATE U_ART_PR SET ART_OREIMP = '00000:00:00' WHERE ART_OREIMP = ''


--SELECT ART_OREIMP,ART_ORELAV,ART_OREATT,* FROM U_ART_PR