

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_STUDIPR bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_STUDIPR] DEFAULT (0)
GO

-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1 (TRUE)
UPDATE U_AZI_PB SET AZI_STUDIPR =  0 
