
if exists (select * from U_AZI_PC WHERE AZI_CONTOSIMILCEE = 1)
	UPDATE CNT SET CNT.CON_CODPADRE = COALESCE((SELECT TOP 1 CON_CONTO FROM CONTI WHERE CON_ANNO = CNT.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(CNT.CON_CONTO) AND 
		RTRIM(CNT.CON_CONTO) LIKE RTRIM(CON_CONTO)+'%' AND RIGHT(RTRIM(CON_CONTO),1) = '.' ORDER BY CON_CONTO DESC),'')
	FROM CONTI AS CNT

go