
ALTER TABLE [dbo].[U_ART_AN] ADD 
	REG_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_REG_CODOPE] DEFAULT (''),
	REG_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_REG_NOMOPE] DEFAULT (''),
	REG_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_REG_DATREG] DEFAULT (''),
	REG_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_REG_ORAREG] DEFAULT (''),
	MOD_CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_MOD_CODOPE] DEFAULT (''),
	MOD_NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_MOD_NOMOPE] DEFAULT (''),
	MOD_DATREG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_MOD_DATREG] DEFAULT (''),
	MOD_ORAREG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ART_AN_MOD_ORAREG] DEFAULT ('')
go

UPDATE AN SET REG_DATREG = COALESCE((SELECT TOP 1 ART_DATVAR FROM U_ART_PR WHERE ART_CODPRI = AN.ART_CODPRI),'') FROM U_ART_AN AS AN
UPDATE AN SET MOD_DATREG = COALESCE((SELECT TOP 1 ART_DATINS FROM U_ART_PR WHERE ART_CODPRI = AN.ART_CODPRI),'') FROM U_ART_AN AS AN