
ALTER TABLE [dbo].[RES_OPER] ADD 
	NEEDCREDS bit NOT NULL CONSTRAINT [DF_RES_OPER_NEEDCREDS] DEFAULT (0),
	USESSL bit NOT NULL CONSTRAINT [DF_RES_OPER_USESSL] DEFAULT (0)

go

UPDATE RES_OPER SET NEEDCREDS = 1 where mail = 3
