

ALTER TABLE [dbo].[VENDITE_TT] ADD 
	LINKINTE varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_LINKINTE] DEFAULT ('')
GO




ALTER TABLE [dbo].[VENDITE_TT] ADD 
	TIPO_MANU_PROGR varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_VENDITE_TT_TIPO_MANU_PROGR] DEFAULT ('')
GO
