ALTER TABLE [dbo].[U_PRD_D4] ADD
	PR4_SEQUEN numeric(3, 0) NULL,
	PR4_SEQPOS numeric(3, 0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_SEQUEN] DEFAULT (0) FOR [PR4_SEQUEN],
	CONSTRAINT [DF_U_PRD_D4_PR4_SEQPOS] DEFAULT (0) FOR [PR4_SEQPOS]
go

UPDATE U_PRD_D4 SET PR4_SEQUEN = 0
UPDATE U_PRD_D4 SET PR4_SEQPOS = 0




