/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[MOV_CONT] ADD 
	 	 MOV_SERV_INTRA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_IMPEUR_INTRA numeric (13,0) NULL,
	 	 MOV_IMPVAL_INTRA numeric (13,0) NULL,
	 	 MOV_IMPSTAT_INTRA numeric (13,0) NULL,
	 	 MOV_STATO_INTRA_PROV varchar(02) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_PARTITA_IVA_INTRA varchar(12) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_QTA_INTRA numeric (10,0) NULL,
	 	 MOV_COND_CONS_INTRA varchar(01) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_MEZZI_TRASP_INTRA varchar(01) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_NAZIONE_INTRA varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_PROVIN_DESTI_INTRA varchar(02) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CONT] WITH NOCHECK ADD 
	CONSTRAINT [DF_PART_MOV_MOV_SERV_INTRA] DEFAULT ('   ') FOR [MOV_SERV_INTRA],
    CONSTRAINT [DF_MOV_CONT_MOV_IMPEUR_INTRA] DEFAULT ('0')    FOR [MOV_IMPEUR_INTRA],
    CONSTRAINT [DF_MOV_CONT_MOV_IMPVAL_INTRA] DEFAULT ('0')    FOR [MOV_IMPVAL_INTRA],
    CONSTRAINT [DF_MOV_CONT_MOV_IMPSTAT_INTRA] DEFAULT ('0')   FOR [MOV_IMPSTAT_INTRA],
	CONSTRAINT [DF_PART_MOV_MOV_STATO_INTRA_PROV] DEFAULT ('     ') FOR [MOV_STATO_INTRA_PROV],
	CONSTRAINT [DF_PART_MOV_MOV_PARTITA_IVA_INTRA] DEFAULT ('     ') FOR [MOV_PARTITA_IVA_INTRA],
    CONSTRAINT [DF_MOV_CONT_MOV_QTA_INTRA] DEFAULT ('0')   FOR [MOV_QTA_INTRA],
	CONSTRAINT [DF_PART_MOV_PMOV_COND_CONS_INTRA] DEFAULT ('     ') FOR [MOV_COND_CONS_INTRA],
	CONSTRAINT [DF_PART_MOV_MOV_MEZZI_TRASP_INTRA] DEFAULT ('    ') FOR [MOV_MEZZI_TRASP_INTRA],
	CONSTRAINT [DF_PART_MOV_MOV_NAZIONE_INTRA] DEFAULT ('    ') FOR [MOV_NAZIONE_INTRA],
	CONSTRAINT [DF_PART_MOV_PROVIN_DESTI_INTRA] DEFAULT ('    ') FOR [MOV_PROVIN_DESTI_INTRA]
go

UPDATE MOV_CONT SET MOV_SERV_INTRA	 		= ''
UPDATE MOV_CONT SET MOV_IMPEUR_INTRA 		= 0
UPDATE MOV_CONT SET MOV_IMPVAL_INTRA 		= 0
UPDATE MOV_CONT SET MOV_IMPSTAT_INTRA 		= 0
UPDATE MOV_CONT SET MOV_STATO_INTRA_PROV 	= ''
UPDATE MOV_CONT SET MOV_PARTITA_IVA_INTRA	= ''
UPDATE MOV_CONT SET MOV_QTA_INTRA 			= 0
UPDATE MOV_CONT SET MOV_COND_CONS_INTRA 	= ''
UPDATE MOV_CONT SET MOV_MEZZI_TRASP_INTRA	= ''
UPDATE MOV_CONT SET MOV_NAZIONE_INTRA		= ''
UPDATE MOV_CONT SET MOV_PROVIN_DESTI_INTRA	= ''

