
ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	ORD_DESART varchar(100) COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN
	ORD_DES2 varchar(100) COLLATE Latin1_General_CI_AS NULL
GO

