-- FABIANO 02/03/2015 - GESTIONE ANTICIPI
 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_ANTCLI_REGAUT	BIT NULL,
	AZI_ANTCLI_CONTO	varchar (13) COLLATE Latin1_General_CI_AS NULL,
	AZI_ANTCLI_TOP		varchar (3) COLLATE Latin1_General_CI_AS NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
--	CONSTRAINT [DF_U_AZI_PB_AZI_ANTCLI_REGAUT] DEFAULT (0) FOR [AZI_ANTCLI_REGAUT],
	CONSTRAINT [DF_U_AZI_PB_AZI_ANTCLI_CONTO] DEFAULT ('') FOR [AZI_ANTCLI_CONTO],
	CONSTRAINT [DF_U_AZI_PB_AZI_ANTCLI_TOP] DEFAULT ('') FOR [AZI_ANTCLI_TOP]
GO

UPDATE U_AZI_PB SET AZI_ANTCLI_REGAUT	= 0
UPDATE U_AZI_PB SET AZI_ANTCLI_CONTO	= ''
UPDATE U_AZI_PB SET AZI_ANTCLI_TOP		= ''
