
ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTREV varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTREV] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTABBONSEMP varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTABBONSEMP] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTABBONCOMP varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTABBONCOMP] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTPULIZIA varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTPULIZIA] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTANALCOMBU varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTANALCOMBU] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTREVADC varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTREVADC] DEFAULT ('')
GO

ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_ATTBOLLO varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTBOLLO] DEFAULT ('')
GO




