ALTER TABLE [dbo].[U_PRD_DR] ADD 
	 	 PRR_TURNO varchar (3)  COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_PRR_TURNO] DEFAULT ('') FOR [PRR_TURNO]
go

UPDATE U_PRD_DR SET PRR_TURNO = ''
