
ALTER TABLE [dbo].[U_PRD_D4] ADD
	PR4_CTRLHS numeric(4,0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_CTRLHS] DEFAULT (0) FOR [PR4_CTRLHS]
go

UPDATE U_PRD_D4 SET PR4_CTRLHS = 0





