/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[MOV_CCO] ADD 
	 	 MOV_CODACQ varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_TIPOCONTRATTO varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_FORMAPAGAMENTO varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_GRADOIMPORTANZA varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_COSATRATTA varchar(05) COLLATE Latin1_General_CI_AS NULL,
	 	 MOV_PRIPAGA varchar(04) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CCO] WITH NOCHECK ADD 
	CONSTRAINT [DF_PART_MOV_MOV_CODACQ] DEFAULT ('   ') FOR [MOV_CODACQ],
	CONSTRAINT [DF_PART_MOV_MOV_TIPOCONTRATTO] DEFAULT ('     ') FOR [MOV_TIPOCONTRATTO],
	CONSTRAINT [DF_PART_MOV_MOV_FORMAPAGAMENTO] DEFAULT ('     ') FOR [MOV_FORMAPAGAMENTO],
	CONSTRAINT [DF_PART_MOV_MOV_GRADOIMPORTANZA] DEFAULT ('     ') FOR [MOV_GRADOIMPORTANZA],
	CONSTRAINT [DF_PART_MOV_PMOV_COSATRATTA] DEFAULT ('     ') FOR [MOV_COSATRATTA],
	CONSTRAINT [DF_PART_MOV_MOV_PRIPAGA] DEFAULT ('    ') FOR [MOV_PRIPAGA]

go

UPDATE MOV_CCO SET MOV_COSATRATTA 	= '     '
UPDATE MOV_CCO SET MOV_GRADOIMPORTANZA = '     '
UPDATE MOV_CCO SET MOV_FORMAPAGAMENTO 	= '     '
UPDATE MOV_CCO SET MOV_TIPOCONTRATTO 	= '     '
UPDATE MOV_CCO SET MOV_CODACQ	 	= '   '
UPDATE MOV_CCO SET MOV_PRIPAGA		= '    '