
ALTER TABLE [dbo].[U_FOR_AN] ADD 
	[FOR_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_FOR_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FOR_AN_FOR_FLGTRA] DEFAULT (0) FOR [FOR_FLGTRA]
go
/**/ALTER TABLE [dbo].[U_BFO_TT] ADD 
	[ORD_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_BFO_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BFO_TT_ORD_FLGTRA] DEFAULT (0) FOR [ORD_FLGTRA]
go
