
ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAORD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTADEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAOLD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAFAT] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAPAR] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAORG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAORF] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAORP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTABOL] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTADAC] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAACC] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAKG] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMQ] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAML] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAKG1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMQ1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAML1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAKGE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMQE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMLE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAKGD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMQD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMLD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTF] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTX] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTO] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QUANTY] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTASPD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTASPP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTARID] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTARIP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTATGO] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTATGD] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTATGP] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAPCK] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAKG1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAMQ1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAML1] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAKG] NUMERIC(12,4) NULL
GO
ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAMQ] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [VAR_QTAML] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [OLD_QTAEV] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMCE] NUMERIC(12,4) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMC1] NUMERIC(12,6) NULL
GO

ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN
	 [ORD_QTAMC] NUMERIC(12,4) NULL
GO