
 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_MAXACQ  NUMERIC(17,3) NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_MAXACQ] DEFAULT (0) FOR [AZI_MAXACQ]
GO

UPDATE U_AZI_PB SET AZI_MAXACQ  = 0