
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'FATTURABILE_A' AND COLUMN_NAME = 'SEQUEN')
BEGIN
	ALTER TABLE [dbo].[FATTURABILE_A] ADD 
		Sequen numeric(10,0) NOT NULL CONSTRAINT [DF_FATTURABILE_A_Sequen] DEFAULT (0)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'FATTURABILE_P' AND COLUMN_NAME = 'SEQUEN')
BEGIN
	ALTER TABLE [dbo].[FATTURABILE_P] ADD 
		Sequen numeric(10,0) NOT NULL CONSTRAINT [DF_FATTURABILE_P_Sequen] DEFAULT (0)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'FATTURABILE_S' AND COLUMN_NAME = 'SEQUEN')
BEGIN
	ALTER TABLE [dbo].[FATTURABILE_S] ADD 
		Sequen numeric(10,0) NOT NULL CONSTRAINT [DF_FATTURABILE_S_Sequen] DEFAULT (0)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'FATTURABILE_X' AND COLUMN_NAME = 'SEQUEN')
BEGIN
	ALTER TABLE [dbo].[FATTURABILE_X] ADD 
		Sequen numeric(10,0) NOT NULL CONSTRAINT [DF_FATTURABILE_X_Sequen] DEFAULT (0)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'FATTURABILE_R' AND COLUMN_NAME = 'SEQUEN')
BEGIN
	ALTER TABLE [dbo].[FATTURABILE_R] ADD 
		Sequen numeric(10,0) NOT NULL CONSTRAINT [DF_FATTURABILE_R_Sequen] DEFAULT (0)
END
