/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_BOL_RE] ADD 
	 ORF_MAGSCA varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 ORF_TOPSCA varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 ORF_PRZVEN [numeric](17, 6) NULL ,
	 ORF_PRZACQ [numeric](17, 6) NULL ,
	 ORF_LEGAME varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_PAGAME varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 ORF_CODACQ varchar(03) COLLATE Latin1_General_CI_AS NULL,
	 ORF_NUMORF varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 ORF_DATORF varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_SC1 [numeric](7, 2) NULL ,
	 ORF_SC2 [numeric](7, 2) NULL ,
	 ORF_SC3 [numeric](7, 2) NULL ,
	 ORF_DATSCA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_NUMIDE varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 ORF_CODBUN varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_ANNSCA varchar(04) COLLATE Latin1_General_CI_AS NULL,
	 ORF_LEGSYS varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_SYSGGG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_SYSGGS varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_SYSDAG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_SYSDAS varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_DATCAN varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORF_ORACAN varchar(08) COLLATE Latin1_General_CI_AS NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_BOL_RE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_RE_ORF_MAGSCA] DEFAULT ('') FOR [ORF_MAGSCA],
	CONSTRAINT [DF_U_BOL_RE_ORF_TOPSCA] DEFAULT ('') FOR [ORF_TOPSCA],
	CONSTRAINT [DF_U_BOL_RE_ORF_PRZVEN] DEFAULT (0) FOR [ORF_PRZVEN],
	CONSTRAINT [DF_U_BOL_RE_ORF_PRZACQ] DEFAULT (0) FOR [ORF_PRZACQ],
	CONSTRAINT [DF_U_BOL_RE_ORF_LEGAME] DEFAULT ('') FOR [ORF_LEGAME],
	CONSTRAINT [DF_U_BOL_RE_ORF_PAGAME] DEFAULT ('') FOR [ORF_PAGAME],
	CONSTRAINT [DF_U_BOL_RE_ORF_CODACQ] DEFAULT ('') FOR [ORF_CODACQ],
	CONSTRAINT [DF_U_BOL_RE_ORF_NUMORF] DEFAULT ('') FOR [ORF_NUMORF],
	CONSTRAINT [DF_U_BOL_RE_ORF_DATORF] DEFAULT ('') FOR [ORF_DATORF],
	CONSTRAINT [DF_U_BOL_RE_ORF_SC1] DEFAULT (0) FOR [ORF_SC1],
	CONSTRAINT [DF_U_BOL_RE_ORF_SC2] DEFAULT (0) FOR [ORF_SC2],
	CONSTRAINT [DF_U_BOL_RE_ORF_SC3] DEFAULT (0) FOR [ORF_SC3],
	CONSTRAINT [DF_U_BOL_RE_ORF_DATSCA] DEFAULT ('') FOR [ORF_DATSCA],
	CONSTRAINT [DF_U_BOL_RE_ORF_NUMIDE] DEFAULT ('') FOR [ORF_NUMIDE],
	CONSTRAINT [DF_U_BOL_RE_ORF_CODBUN] DEFAULT ('') FOR [ORF_CODBUN],
	CONSTRAINT [DF_U_BOL_RE_ORF_ANNSCA] DEFAULT ('') FOR [ORF_ANNSCA],
	CONSTRAINT [DF_U_BOL_RE_ORF_LEGSYS] DEFAULT ('') FOR [ORF_LEGSYS],
	CONSTRAINT [DF_U_BOL_RE_ORF_SYSGGG] DEFAULT ('') FOR [ORF_SYSGGG],
	CONSTRAINT [DF_U_BOL_RE_ORF_SYSGGS] DEFAULT ('') FOR [ORF_SYSGGS],
	CONSTRAINT [DF_U_BOL_RE_ORF_SYSDAG] DEFAULT ('') FOR [ORF_SYSDAG],
	CONSTRAINT [DF_U_BOL_RE_ORF_SYSDAS] DEFAULT ('') FOR [ORF_SYSDAS],
	CONSTRAINT [DF_U_BOL_RE_ORF_DATCAN] DEFAULT ('') FOR [ORF_DATCAN],
	CONSTRAINT [DF_U_BOL_RE_ORF_ORACAN] DEFAULT ('') FOR [ORF_ORACAN]
go

UPDATE U_BOL_RE SET ORF_MAGSCA = SPACE(06)
UPDATE U_BOL_RE SET ORF_TOPSCA = SPACE(03)
UPDATE U_BOL_RE SET ORF_PRZVEN = 0
UPDATE U_BOL_RE SET ORF_PRZACQ = 0
UPDATE U_BOL_RE SET ORF_LEGAME = SPACE(10)
UPDATE U_BOL_RE SET ORF_PAGAME = SPACE(03)
UPDATE U_BOL_RE SET ORF_CODACQ = SPACE(03)
UPDATE U_BOL_RE SET ORF_NUMORF = SPACE(06)
UPDATE U_BOL_RE SET ORF_DATORF = SPACE(10)
UPDATE U_BOL_RE SET ORF_SC1 = 0
UPDATE U_BOL_RE SET ORF_SC2 = 0
UPDATE U_BOL_RE SET ORF_SC3 = 0
UPDATE U_BOL_RE SET ORF_DATSCA = SPACE(10)
UPDATE U_BOL_RE SET ORF_NUMIDE = SPACE(06)
UPDATE U_BOL_RE SET ORF_CODBUN = SPACE(10)
UPDATE U_BOL_RE SET ORF_ANNSCA = SPACE(04)
UPDATE U_BOL_RE SET ORF_LEGSYS = SPACE(10)
UPDATE U_BOL_RE SET ORF_SYSGGG = SPACE(10)
UPDATE U_BOL_RE SET ORF_SYSGGS = SPACE(10)
UPDATE U_BOL_RE SET ORF_SYSDAG = SPACE(10)
UPDATE U_BOL_RE SET ORF_SYSDAS = SPACE(10)
UPDATE U_BOL_RE SET ORF_DATCAN = SPACE(10)
UPDATE U_BOL_RE SET ORF_ORACAN = SPACE(08)
