/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[BUDGET_PREV] ADD 
	SPESEGG numeric(17,6) NULL,
	RIMBKM numeric(17,6) NULL,
	RIMBSPEFOR numeric(17,6) NULL,
	IMPTRASFGG numeric(17,6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[BUDGET_PREV] WITH NOCHECK ADD 
	CONSTRAINT [DF_BUDGET_PREV_SPESEGG] DEFAULT (0) FOR [SPESEGG],
	CONSTRAINT [DF_BUDGET_PREV_RIMBKM] DEFAULT (0) FOR [RIMBKM],
	CONSTRAINT [DF_BUDGET_PREV_RIMBSPEFOR] DEFAULT (0) FOR [RIMBSPEFOR],
	CONSTRAINT [DF_BUDGET_PREV_IMPTRASFGG] DEFAULT (0) FOR [IMPTRASFGG]
go

UPDATE BUDGET_PREV SET SPESEGG = 0
UPDATE BUDGET_PREV SET RIMBKM = 0
UPDATE BUDGET_PREV SET RIMBSPEFOR = 0
UPDATE BUDGET_PREV SET IMPTRASFGG = 0



