
UPDATE U_AZI_PA SET AZI_PASS = '\BMP\AMBIENTE\SFONDI\SFONDO_PASS.JPG'
UPDATE U_AZI_PA SET AZI_PASS_SW = '\BMP\AMBIENTE\SFONDI\SFONDO_PASS.JPG'
UPDATE U_AZI_PA SET AZI_SUBMEN = '\BMP\AMBIENTE\SUBMENU\submenu_mondo.jpg'
