
 
ALTER TABLE [DBO].[U_MAG_MO] ADD 
	MOV_PRSPOT  BIT NULL
GO

ALTER TABLE [DBO].[U_MAG_MO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_MO_MOV_PRSPOT] DEFAULT (0) FOR [MOV_PRSPOT]
GO

UPDATE U_MAG_MO SET MOV_PRSPOT  = 0