 
UPDATE U_OFF_TT SET REG_CODOPE = ''
UPDATE U_OFF_DD SET ORD_QTAPRD1 = 0
UPDATE U_OFF_DD SET ORD_NPZPRD1 = 0
UPDATE U_OFF_DD SET ORD_QTAPRD2 = 0
UPDATE U_OFF_DD SET ORD_NPZPRD2 = 0
UPDATE U_OFF_DD SET ORD_QTAPRD3 = 0
UPDATE U_OFF_DD SET ORD_NPZPRD3 = 0