
ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_COSLAI NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_COSLAE NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_COSMAT NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_COSATR NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_COSTO NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_RICLAI NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_RICLAE NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_RICMAT NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_RICATR NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_DIS_DD]  ALTER COLUMN  
	DIS_PREZZO NUMERIC(17,6) NULL
GO
