
ALTER TABLE [DBO].[U_AZI_PA] ADD 
	AZI_PERIDR NUMERIC(3,0) NULL
GO

ALTER TABLE [DBO].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_PERIDR] DEFAULT (0) FOR [AZI_PERIDR]
GO

UPDATE U_AZI_PA SET AZI_PERIDR = 0

