ALTER TABLE BUDGET_SINT_TT 
DROP CONSTRAINT DF_BUDGET_SINT_TT_Valore_budget

ALTER TABLE BUDGET_SINT_TT 
DROP COLUMN VALORE_BUDGET

ALTER TABLE BUDGET_SINT_TT 
ADD VALORE_BUDGET NUMERIC(17,2)

