
ALTER TABLE [dbo].[U_BOL_TT] ADD 
	 ORD_NUMDDT varchar(6) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DATDDT varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_ANNDDT varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 ORD_AGGDDT varchar(10) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_BOL_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_BOL_TT_ORD_NUMDDT] DEFAULT ('') FOR [ORD_NUMDDT],
	CONSTRAINT [DF_U_BOL_TT_ORD_DATDDT] DEFAULT ('') FOR [ORD_DATDDT],
	CONSTRAINT [DF_U_BOL_TT_ORD_ANNDDT] DEFAULT ('') FOR [ORD_ANNDDT],
	CONSTRAINT [DF_U_BOL_TT_ORD_AGGDDT] DEFAULT ('') FOR [ORD_AGGDDT]
go

UPDATE U_BOL_TT SET ORD_NUMDDT = SPACE(06)
UPDATE U_BOL_TT SET ORD_DATDDT = SPACE(10)
UPDATE U_BOL_TT SET ORD_ANNDDT = SPACE(04)
UPDATE U_BOL_TT SET ORD_AGGDDT = SPACE(10)

