
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_QUOAMM varchar (3) COLLATE Latin1_General_CI_AS NULL 
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_QUOAMM] DEFAULT ('') FOR [AZI_QUOAMM]
GO

UPDATE U_AZI_PB SET AZI_QUOAMM = ''
