ALTER TABLE MOVIMENTI_BOMBOLE ADD DATA_CONFERMA [varchar] (10) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE MOVIMENTI_BOMBOLE ADD ORA_CONFERMA [varchar] (8) COLLATE Latin1_General_CI_AS NULL
go

UPDATE MOVIMENTI_BOMBOLE SET DATA_CONFERMA=''
UPDATE MOVIMENTI_BOMBOLE SET ORA_CONFERMA=''

