
ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_COSLAI NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_COSLAE NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_COSMAT NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_COSATR NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_RICLAI NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_RICLAE NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_RICMAT NUMERIC(17,6) NULL
GO

ALTER TABLE [dbo].[U_ART_PR]  ALTER COLUMN  
	ART_RICATR NUMERIC(17,6) NULL
GO
