
ALTER TABLE [DBO].[CASHFLOWFIN] ADD 
	OPZCPA NUMERIC(1,0) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_OPZCPA] DEFAULT (0),
	GIORNOAL NUMERIC(2,0) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_GIORNOAL] DEFAULT (0)
GO

ALTER TABLE [DBO].[CASHFLOWFIN] ADD 
	SCADSUCC BIT NOT NULL CONSTRAINT [DF_CASHFLOWFIN_SCADSUCC] DEFAULT (0)
GO