/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_AZI_PA] ADD 
	[AZI_CCOSTD] [bit] NULL,
	[AZI_CCOACLI] [bit] NULL,
	[AZI_CCOAART] [bit] NULL,
	[AZI_CCOPDC] [bit] NULL,
	[AZI_CCOCLI] [bit] NULL,
	[AZI_CCOFOR] [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOSTD] DEFAULT (0) FOR [AZI_CCOSTD],
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOACLI] DEFAULT (0) FOR [AZI_CCOACLI],
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOAART] DEFAULT (0) FOR [AZI_CCOAART],
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOPDC] DEFAULT (0) FOR [AZI_CCOPDC],
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOCLI] DEFAULT (0) FOR [AZI_CCOCLI],
	CONSTRAINT [DF_U_AZI_PA_AZI_CCOFOR] DEFAULT (0) FOR [AZI_CCOFOR]
go

UPDATE U_AZI_PA SET AZI_CCOSTD  = 0
UPDATE U_AZI_PA SET AZI_CCOACLI  = 0
UPDATE U_AZI_PA SET AZI_CCOAART  = 0
UPDATE U_AZI_PA SET AZI_CCOPDC  = 0
UPDATE U_AZI_PA SET AZI_CCOCLI  = 0
UPDATE U_AZI_PA SET AZI_CCOFOR  = 0
