ALTER TABLE [dbo].[U_PRD_D4] ADD 
	 	 PR4_PALLET varchar (6)  COLLATE Latin1_General_CI_AS NULL,
		 PR4_DATPAL varchar (10) COLLATE Latin1_General_CI_AS NULL,
		 PR4_ORAPAL varchar (8) COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_PALLET] DEFAULT ('') FOR [PR4_PALLET],
	CONSTRAINT [DF_U_PRD_D4_PR4_DATPAL] DEFAULT ('') FOR [PR4_DATPAL],
	CONSTRAINT [DF_U_PRD_D4_PR4_ORAPAL] DEFAULT ('') FOR [PR4_ORAPAL]
go

UPDATE U_PRD_D4 SET PR4_PALLET = ''
UPDATE U_PRD_D4 SET PR4_DATPAL = ''
UPDATE U_PRD_D4 SET PR4_ORAPAL = ''
