
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_STC_AN] ADD 					

		 ORD_QTAMQ numeric (13,3) NULL,
		 ORD_QTAMQ1 numeric (13,3) NULL,
		 ORD_QTAML numeric (13,3) NULL,
		 ORD_QTAML1 numeric (13,3) NULL,
		 ORD_QTAKG numeric (13,3) NULL,
		 ORD_QTAKG1 numeric (13,3) NULL,
		 ORD_CODMAT varchar(3) COLLATE Latin1_General_CI_AS NULL,
		 ORD_DESMAT varchar(30) COLLATE Latin1_General_CI_AS NULL,
		 ORD_SPESSO numeric (3) NULL, 
		 ORD_ALTEZZ numeric (5) NULL,
		 ORD_LUNGHE numeric (6) NULL,
		 ORD_NUMBOB numeric (6) NULL,
		 ORD_DATPED varchar(10) COLLATE Latin1_General_CI_AS NULL,
		 ORD_NOTEBO text COLLATE Latin1_General_CI_AS NULL ,
		 ORD_DESIMB varchar(30) COLLATE Latin1_General_CI_AS NULL,
		 ORD_LOTMIN numeric (6) NULL,
		 ORD_QTAKGI numeric (13,3) NULL,  
		 ORD_QTAKGE numeric (13,3) NULL,  
		 ORD_CDAPRD varchar(16) COLLATE Latin1_General_CI_AS NULL,
		 ORD_DSAPRD varchar(50) COLLATE Latin1_General_CI_AS NULL,
		 STC_ZONA   varchar(3) COLLATE Latin1_General_CI_AS NULL,
		 STC_SERIE  varchar(3) COLLATE Latin1_General_CI_AS NULL,
		 STC_DESZON varchar(30) COLLATE Latin1_General_CI_AS NULL,
		 STC_DESSER varchar(30) COLLATE Latin1_General_CI_AS NULL

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[U_STC_AN] WITH NOCHECK ADD 

        CONSTRAINT [DF_U_STC_AN_ORD_QTAMQ] DEFAULT ('0')	FOR [ORD_QTAMQ],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAMQ1] DEFAULT ('0')   	FOR [ORD_QTAMQ1],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAML] DEFAULT ('0')    	FOR [ORD_QTAML],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAML1] DEFAULT ('0')    	FOR [ORD_QTAML1],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAKG] DEFAULT ('0')    	FOR [ORD_QTAKG],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAKG1] DEFAULT ('0')    	FOR [ORD_QTAKG1],
	CONSTRAINT [DF_U_STC_AN_ORD_CODMAT] DEFAULT ('') 	FOR [ORD_CODMAT],
	CONSTRAINT [DF_U_STC_AN_ORD_DESMAT] DEFAULT ('') 	FOR [ORD_DESMAT],
        CONSTRAINT [DF_U_STC_AN_ORD_SPESSO] DEFAULT ('0')    	FOR [ORD_SPESSO],
        CONSTRAINT [DF_U_STC_AN_ORD_ALTEZZ] DEFAULT ('0')    	FOR [ORD_ALTEZZ],
        CONSTRAINT [DF_U_STC_AN_ORD_LUNGHE] DEFAULT ('0')    	FOR [ORD_LUNGHE],
        CONSTRAINT [DF_U_STC_AN_ORD_NUMBOB] DEFAULT ('0')    	FOR [ORD_NUMBOB],
	CONSTRAINT [DF_U_STC_AN_ORD_DATPED] DEFAULT ('') 	FOR [ORD_DATPED],
	CONSTRAINT [DF_U_STC_AN_ORD_NOTEBO] DEFAULT ('') 	FOR [ORD_NOTEBO],
	CONSTRAINT [DF_U_STC_AN_ORD_DESIMB] DEFAULT ('') 	FOR [ORD_DESIMB],
        CONSTRAINT [DF_U_STC_AN_ORD_LOTMIN] DEFAULT ('0')   	FOR [ORD_LOTMIN],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAKGI] DEFAULT ('0')   	FOR [ORD_QTAKGI],
        CONSTRAINT [DF_U_STC_AN_ORD_QTAKGE] DEFAULT ('0')   	FOR [ORD_QTAKGE],
	CONSTRAINT [DF_U_STC_AN_ORD_CDAPRD] DEFAULT ('') 	FOR [ORD_CDAPRD],
	CONSTRAINT [DF_U_STC_AN_ORD_DSAPRD] DEFAULT ('') 	FOR [ORD_DSAPRD],
	CONSTRAINT [DF_U_STC_AN_STC_ZONA  ] DEFAULT ('') 	FOR [STC_ZONA],
	CONSTRAINT [DF_U_STC_AN_STC_SERIE ] DEFAULT ('') 	FOR [STC_SERIE],
	CONSTRAINT [DF_U_STC_AN_STC_DESZON] DEFAULT ('') 	FOR [STC_DESZON],
	CONSTRAINT [DF_U_STC_AN_STC_DESSER] DEFAULT ('') 	FOR [STC_DESSER]

go


UPDATE U_STC_AN SET ORD_QTAMQ 	= 0 
UPDATE U_STC_AN SET ORD_QTAMQ1 	= 0 
UPDATE U_STC_AN SET ORD_QTAML 	= 0 
UPDATE U_STC_AN SET ORD_QTAML1 	= 0 
UPDATE U_STC_AN SET ORD_QTAKG 	= 0 
UPDATE U_STC_AN SET ORD_QTAKG1 	= 0 
UPDATE U_STC_AN SET ORD_CODMAT = SPACE(03)
UPDATE U_STC_AN SET ORD_DESMAT = SPACE(30)
UPDATE U_STC_AN SET ORD_SPESSO = 0
UPDATE U_STC_AN SET ORD_ALTEZZ = 0
UPDATE U_STC_AN SET ORD_LUNGHE = 0
UPDATE U_STC_AN SET ORD_NUMBOB = 0
UPDATE U_STC_AN SET ORD_DATPED = SPACE(10)
UPDATE U_STC_AN SET ORD_NOTEBO = SPACE(10)
UPDATE U_STC_AN SET ORD_DESIMB = SPACE(30)
UPDATE U_STC_AN SET ORD_LOTMIN = 0
UPDATE U_STC_AN SET ORD_QTAKGI = 0
UPDATE U_STC_AN SET ORD_QTAKGE = 0
UPDATE U_STC_AN SET ORD_CDAPRD = SPACE(30)
UPDATE U_STC_AN SET ORD_DSAPRD = SPACE(30)
UPDATE U_STC_AN SET STC_ZONA   = SPACE(3)
UPDATE U_STC_AN SET STC_SERIE  = SPACE(3)
UPDATE U_STC_AN SET STC_DESZON = SPACE(30)
UPDATE U_STC_AN SET STC_DESSER = SPACE(30)
