
/*
*** VariabilI gestite nella scheda "F.E. xlm", di "form\menu_azi000.scx"  per la fatturazione elettronica
***		- Login URL
*/

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_IDPAESE varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_IDPAESE] DEFAULT (''),
	AZI_CODEORI varchar(15) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_CODEORI] DEFAULT (''),
	AZI_ALBO varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_ALBO] DEFAULT (''),
	AZI_PRVALBO varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_PRVALBO] DEFAULT (''),
	AZI_DTALBO varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_DTALBO] DEFAULT (''),
	AZI_REGIMEFI varchar(06) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_REGIMEFI] DEFAULT (''),
	AZI_NRCIVICO varchar(15) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_NRCIVICO] DEFAULT (''),
	AZI_PROVINCIA varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_PROVINCIA] DEFAULT (''),
	AZI_NAZION varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_NAZION] DEFAULT (''),
	AZI_UFFICIO varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_UFFICIO] DEFAULT (''),
	AZI_NRREA varchar(15) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_NRREA] DEFAULT ('')

GO


ALTER TABLE [dbo].U_AZI_PB ADD 
	AZI_CAPITSO numeric (16,3) NULL
go

ALTER TABLE [dbo].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_CAPITSO] DEFAULT (0) FOR [AZI_CAPITSO]
go

UPDATE U_AZI_PB SET AZI_CAPITSO = 0 



ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_SOCIOU varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_SOCIOU] DEFAULT (''),
	AZI_STATOL varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_STATOL] DEFAULT (''),
	AZI_IDPAESEIN varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_IDPAESEIN] DEFAULT (''),
	AZI_PIVAIN varchar(11) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_PIVAIN] DEFAULT (''),
	AZI_RAGSOCIN varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_RAGSOCIN] DEFAULT (''),
	AZI_SOGGEMIN varchar(03) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_SOGGEMIN] DEFAULT ('')

GO