

ALTER TABLE [dbo].[MOV_CONT] ADD 
  MOV_NUMATRI numeric(20,0) NULL ,
  MOV_EFFETDA varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_INTEPER varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_NOTEFF [text] COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CONT] WITH NOCHECK ADD 
	CONSTRAINT [DF_MOV_CONT_MOV_NUMATRI] DEFAULT (0) FOR [MOV_NUMATRI],
	CONSTRAINT [DF_MOV_CONT_MOV_EFFETDA] DEFAULT ('') FOR [MOV_EFFETDA],
	CONSTRAINT [DF_MOV_CONT_MOV_INTEPER] DEFAULT ('') FOR [MOV_INTEPER],
	CONSTRAINT [DF_MOV_CONT_MOV_NOTEFF] DEFAULT ('') FOR [MOV_NOTEFF]
go

UPDATE MOV_CONT SET MOV_NUMATRI = 0
UPDATE MOV_CONT SET MOV_EFFETDA = ''
UPDATE MOV_CONT SET MOV_INTEPER = ''
UPDATE MOV_CONT SET MOV_NOTEFF = ''



ALTER TABLE [dbo].[INDICE] ADD 
  MOV_NUMATRI numeric(20,0) NULL ,
  MOV_EFFETDA varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_INTEPER varchar(30) COLLATE Latin1_General_CI_AS NULL,
  MOV_NOTEFF [text] COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[INDICE] WITH NOCHECK ADD 
	CONSTRAINT [DF_INDICE_MOV_NUMATRI] DEFAULT (0) FOR [MOV_NUMATRI],
	CONSTRAINT [DF_INDICE_MOV_EFFETDA] DEFAULT ('') FOR [MOV_EFFETDA],
	CONSTRAINT [DF_INDICE_MOV_INTEPER] DEFAULT ('') FOR [MOV_INTEPER],
	CONSTRAINT [DF_INDICE_MOV_NOTEFF] DEFAULT ('') FOR [MOV_NOTEFF]
go

UPDATE INDICE SET MOV_NUMATRI = 0
UPDATE INDICE SET MOV_EFFETDA = ''
UPDATE INDICE SET MOV_INTEPER = ''
UPDATE INDICE SET MOV_NOTEFF = ''



ALTER TABLE [dbo].[PART_CLI] ADD 
  PAR_NUMATRI numeric(20,0) NULL ,
  PAR_EFFETDA varchar(30) COLLATE Latin1_General_CI_AS NULL,
  PAR_INTEPER varchar(30) COLLATE Latin1_General_CI_AS NULL,
  PAR_NOTEFF [text] COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[PART_CLI] WITH NOCHECK ADD 
	CONSTRAINT [DF_PART_CLI_PAR_NUMATRI] DEFAULT (0) FOR [PAR_NUMATRI],
	CONSTRAINT [DF_PART_CLI_PAR_EFFETDA] DEFAULT ('') FOR [PAR_EFFETDA],
	CONSTRAINT [DF_PART_CLI_PAR_INTEPER] DEFAULT ('') FOR [PAR_INTEPER],
	CONSTRAINT [DF_PART_CLI_PAR_NOTEFF] DEFAULT ('') FOR [PAR_NOTEFF]
go

UPDATE PART_CLI SET PAR_NUMATRI = 0
UPDATE PART_CLI SET PAR_EFFETDA = ''
UPDATE PART_CLI SET PAR_INTEPER = ''
UPDATE PART_CLI SET PAR_NOTEFF = ''




ALTER TABLE [dbo].[PART_FOR] ADD 
  PAR_NUMATRI numeric(20,0) NULL ,
  PAR_EFFETDA varchar(30) COLLATE Latin1_General_CI_AS NULL,
  PAR_INTEPER varchar(30) COLLATE Latin1_General_CI_AS NULL,
  PAR_NOTEFF [text] COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[PART_FOR] WITH NOCHECK ADD 
	CONSTRAINT [DF_PART_FOR_PAR_NUMATRI] DEFAULT (0) FOR [PAR_NUMATRI],
	CONSTRAINT [DF_PART_FOR_PAR_EFFETDA] DEFAULT ('') FOR [PAR_EFFETDA],
	CONSTRAINT [DF_PART_FOR_PAR_INTEPER] DEFAULT ('') FOR [PAR_INTEPER],
	CONSTRAINT [DF_PART_FOR_PAR_NOTEFF] DEFAULT ('') FOR [PAR_NOTEFF]
go

UPDATE PART_FOR SET PAR_NUMATRI = 0
UPDATE PART_FOR SET PAR_EFFETDA = ''
UPDATE PART_FOR SET PAR_INTEPER = ''
UPDATE PART_FOR SET PAR_NOTEFF = ''
