/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_FAP_DD] ADD
	[ORD_PRZCON] [numeric](17, 6) NULL,
	[ORD_FORNIT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORD_CODACQ] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORD_QTAKG] [numeric](13, 3) NULL,
	[ORD_QTAMQ] [numeric](13, 3) NULL,
	[ORD_QTAML] [numeric](13, 3) NULL,
	[ORD_QTAKG1] [numeric](13, 3) NULL,
	[ORD_QTAMQ1] [numeric](13, 3) NULL,
	[ORD_QTAML1] [numeric](13, 3) NULL,
	[ORD_NUMPED] [numeric](8, 0) NULL,
	[ORD_DATPED] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORD_SYSPED] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORD_NOTEBO] [text] COLLATE Latin1_General_CI_AS NULL,
	[ORD_DESIMB] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
	[ORD_LOTMIN] [numeric](6, 0) NULL,
	[ORD_QTAKGI] [numeric](13, 3) NULL,
	[ORD_QTAKGE] [numeric](13, 3) NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_FAP_DD] WITH NOCHECK ADD
	CONSTRAINT [DF_U_FAP_DD_ORD_PRZCON] DEFAULT (0) FOR [ORD_PRZCON],
	CONSTRAINT [DF_U_FAP_DD_ORD_FORNIT] DEFAULT ('') FOR [ORD_FORNIT],
	CONSTRAINT [DF_U_FAP_DD_ORD_CODACQ] DEFAULT ('') FOR [ORD_CODACQ],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAKG] DEFAULT (0) FOR [ORD_QTAKG],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAMQ] DEFAULT (0) FOR [ORD_QTAMQ],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAML] DEFAULT (0) FOR [ORD_QTAML],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAKG1] DEFAULT (0) FOR [ORD_QTAKG1],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAMQ1] DEFAULT (0) FOR [ORD_QTAMQ1],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAML1] DEFAULT (0) FOR [ORD_QTAML1],
	CONSTRAINT [DF_U_FAP_DD_ORD_NUMPED] DEFAULT (0) FOR [ORD_NUMPED],
	CONSTRAINT [DF_U_FAP_DD_ORD_DATPED] DEFAULT ('') FOR [ORD_DATPED],
	CONSTRAINT [DF_U_FAP_DD_ORD_SYSPED] DEFAULT ('') FOR [ORD_SYSPED],
	CONSTRAINT [DF_U_FAP_DD_ORD_NOTEBO] DEFAULT ('') FOR [ORD_NOTEBO],
	CONSTRAINT [DF_U_FAP_DD_ORD_DESIMB] DEFAULT ('') FOR [ORD_DESIMB],
	CONSTRAINT [DF_U_FAP_DD_ORD_LOTMIN] DEFAULT (0) FOR [ORD_LOTMIN],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAKGI] DEFAULT (0) FOR [ORD_QTAKGI],
	CONSTRAINT [DF_U_FAP_DD_ORD_QTAKGE] DEFAULT (0) FOR [ORD_QTAKGE]
go


UPDATE U_FAP_DD SET ORD_PRZCON = 0
UPDATE U_FAP_DD SET ORD_FORNIT = ''
UPDATE U_FAP_DD SET ORD_CODACQ = ''
UPDATE U_FAP_DD SET ORD_QTAKG = 0
UPDATE U_FAP_DD SET ORD_QTAMQ = 0
UPDATE U_FAP_DD SET ORD_QTAML = 0
UPDATE U_FAP_DD SET ORD_QTAKG1 = 0
UPDATE U_FAP_DD SET ORD_QTAMQ1 = 0
UPDATE U_FAP_DD SET ORD_QTAML1 = 0
UPDATE U_FAP_DD SET ORD_NUMPED = 0
UPDATE U_FAP_DD SET ORD_DATPED = ''
UPDATE U_FAP_DD SET ORD_SYSPED = ''
UPDATE U_FAP_DD SET ORD_NOTEBO = ''
UPDATE U_FAP_DD SET ORD_DESIMB = ''
UPDATE U_FAP_DD SET ORD_LOTMIN = 0
UPDATE U_FAP_DD SET ORD_QTAKGI = 0
UPDATE U_FAP_DD SET ORD_QTAKGE = 0
