
ALTER TABLE [DBO].[PROGRAMMI_BATCH] ADD 
	PATH_PRG  VARCHAR(254) COLLATE Latin1_General_CI_AS NULL 
GO

ALTER TABLE [DBO].[PROGRAMMI_BATCH] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROGRAMMI_BATCH_PATH_PRG] DEFAULT ('') FOR [PATH_PRG]
GO

UPDATE PROGRAMMI_BATCH SET PATH_PRG  = ''
