

ALTER TABLE [dbo].[IMPIANTI_TT] ADD 
	NOTIFY_TYPE NUMERIC(1,0) NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_TYPE] DEFAULT (1),
	NOTIFY_WA varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_WA] DEFAULT (''),
	NOTIFY_SMS varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_SMS] DEFAULT (''),
	NOTIFY_EMAIL varchar(254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_EMAIL] DEFAULT (''),
	NOTIFY_TYPE_MTZ NUMERIC(1,0) NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_TYPE_MTZ] DEFAULT (1),
	NOTIFY_WA_MTZ varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_WA_MTZ] DEFAULT (''),
	NOTIFY_SMS_MTZ varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_SMS_MTZ] DEFAULT (''),
	NOTIFY_EMAIL_MTZ varchar(254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_TT_NOTIFY_EMAIL_MTZ] DEFAULT ('')
GO
