
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_IDBANC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	PR5_STABAN varchar(2) COLLATE Latin1_General_CI_AS NULL,
	PR5_ALTBAN numeric(10,0) NULL, 
	PR5_LARBAN numeric(10,0) NULL, 
	PR5_PESBAN numeric(19,3) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_IDBANC] DEFAULT ('') FOR [PR5_IDBANC],
	CONSTRAINT [DF_U_PRD_D5_PR5_STABAN] DEFAULT ('') FOR [PR5_STABAN],
	CONSTRAINT [DF_U_PRD_D5_PR5_ALTBAN] DEFAULT (0) FOR [PR5_ALTBAN],
	CONSTRAINT [DF_U_PRD_D5_PR5_LARBAN] DEFAULT (0) FOR [PR5_LARBAN],
	CONSTRAINT [DF_U_PRD_D5_PR5_PESBAN] DEFAULT (0) FOR [PR5_PESBAN]
go

UPDATE U_PRD_D5 SET PR5_IDBANC = ''
UPDATE U_PRD_D5 SET PR5_STABAN = ''
UPDATE U_PRD_D5 SET PR5_ALTBAN = 0
UPDATE U_PRD_D5 SET PR5_LARBAN = 0
UPDATE U_PRD_D5 SET PR5_PESBAN = 0
