/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[TIMESHT] ADD 
	ORE_ORDINA numeric(2,0) NULL,
	MIN_ORDINA numeric(2,0) NULL, 
	ORE_STRAOR numeric(2,0) NULL,
	MIN_STRAOR numeric(2,0) NULL, 
	ORE_ROL numeric(2,0) NULL,
	MIN_ROL numeric(2,0) NULL, 
	ORE_FERIE numeric(2,0) NULL,
	MIN_FERIE numeric(2,0) NULL, 
	ORE_MALATT numeric(2,0) NULL,
	MIN_MALATT numeric(2,0) NULL, 
	ORE_ALTRO numeric(2,0) NULL,
	MIN_ALTRO numeric(2,0) NULL, 
	VALNETTOGG numeric(17,6) NULL, 
	TOTVALNETT numeric(17,6) NULL, 
	TOTFOGLIOP numeric(17,6) NULL, 
	NOTEFOGLIOP TEXT COLLATE Latin1_General_CI_AS NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[TIMESHT] WITH NOCHECK ADD 
	CONSTRAINT [DF_TIMESHT_ORE_ORDINA] DEFAULT (0) FOR [ORE_ORDINA], 
	CONSTRAINT [DF_TIMESHT_MIN_ORDINA] DEFAULT (0) FOR [MIN_ORDINA], 
	CONSTRAINT [DF_TIMESHT_ORE_STRAOR] DEFAULT (0) FOR [ORE_STRAOR], 
	CONSTRAINT [DF_TIMESHT_MIN_STRAOR] DEFAULT (0) FOR [MIN_STRAOR], 
	CONSTRAINT [DF_TIMESHT_ORE_ROL] DEFAULT (0) FOR [ORE_ROL], 
	CONSTRAINT [DF_TIMESHT_MIN_ROL] DEFAULT (0) FOR [MIN_ROL], 
	CONSTRAINT [DF_TIMESHT_ORE_FERIE] DEFAULT (0) FOR [ORE_FERIE], 
	CONSTRAINT [DF_TIMESHT_MIN_FERIE] DEFAULT (0) FOR [MIN_FERIE], 
	CONSTRAINT [DF_TIMESHT_ORE_MALATT] DEFAULT (0) FOR [ORE_MALATT], 
	CONSTRAINT [DF_TIMESHT_MIN_MALATT] DEFAULT (0) FOR [MIN_MALATT], 
	CONSTRAINT [DF_TIMESHT_ORE_ALTRO] DEFAULT (0) FOR [ORE_ALTRO], 
	CONSTRAINT [DF_TIMESHT_MIN_ALTRO] DEFAULT (0) FOR [MIN_ALTRO], 
	CONSTRAINT [DF_TIMESHT_VALNETTOGG] DEFAULT (0) FOR [VALNETTOGG], 
	CONSTRAINT [DF_TIMESHT_TOTVALNETT] DEFAULT (0) FOR [TOTVALNETT], 
	CONSTRAINT [DF_TIMESHT_TOTFOGLIOP] DEFAULT (0) FOR [TOTFOGLIOP], 
	CONSTRAINT [DF_TIMESHT_NOTEFOGLIOP] DEFAULT ('') FOR [NOTEFOGLIOP]
go

UPDATE TIMESHT SET ORE_ORDINA = 0
UPDATE TIMESHT SET MIN_ORDINA = 0
UPDATE TIMESHT SET ORE_STRAOR = 0
UPDATE TIMESHT SET MIN_STRAOR = 0
UPDATE TIMESHT SET ORE_ROL = 0
UPDATE TIMESHT SET MIN_ROL = 0
UPDATE TIMESHT SET ORE_FERIE = 0
UPDATE TIMESHT SET MIN_FERIE = 0
UPDATE TIMESHT SET ORE_MALATT = 0
UPDATE TIMESHT SET MIN_MALATT = 0
UPDATE TIMESHT SET ORE_ALTRO = 0
UPDATE TIMESHT SET MIN_ALTRO = 0
UPDATE TIMESHT SET VALNETTOGG = 0
UPDATE TIMESHT SET TOTVALNETT = 0
UPDATE TIMESHT SET TOTFOGLIOP = 0
UPDATE TIMESHT SET NOTEFOGLIOP = ''