ALTER TABLE [dbo].[U_PRD_D4] ADD
	PR4_POSGRA varchar(10) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_POSGRA] DEFAULT ('') FOR [PR4_POSGRA]
go

UPDATE U_PRD_D4 SET PR4_POSGRA = ''