
-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_OFF_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BOL_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[L_BOL_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BOL_SD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FAP_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BFO_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BFO_DL] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BOL_SN] ALTER COLUMN CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AMM_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BCL_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_BOF_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_CTL_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_DIS_DD] ALTER COLUMN DIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FAM_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FAT_SD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FOR_DD] ALTER COLUMN FOR_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LEG_DD] ALTER COLUMN LEG_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIF_TT] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_AA] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_AG] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_AL] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_AV] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_LI] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_TT] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_VE] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_ZO] ALTER COLUMN LIS_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[CONTRMDB_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[ELENCO_VUOTI] ALTER COLUMN CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[ELENCO_VUOTI] ALTER COLUMN CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[INVENTARIO] ALTER COLUMN ART_CODPRI     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[INVENTORY] ALTER COLUMN CODINT     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[INVENTORY] ALTER COLUMN ANAART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[L_MAG_GG] ALTER COLUMN MAG_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_CARICHI] ALTER COLUMN CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_CARICHI] ALTER COLUMN CODINT     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_DISIMPEGNI] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_IMPEGNI] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_LEGAMI] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_ORDINI] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PACKFOR] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PACKING] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PACKING_DB] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PIANIF_DB] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PIANIF_DD] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PIANIF_OF] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PIANIF_SPALMA] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROD_PIANIF_SPALMA_LEGORD] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PRODUZIONE] ALTER COLUMN COMP    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[PROV_STO] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[S_COM_ED] ALTER COLUMN LCD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[S_MAG_MO] ALTER COLUMN MOV_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[S_ORF_ED] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AMM_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_GA] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_KO] ALTER COLUMN ART_CODPRI    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_LE] ALTER COLUMN LEG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_SP] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_CO] ALTER COLUMN AVA_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_MQ] ALTER COLUMN AVA_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_RI] ALTER COLUMN STA_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_SM] ALTER COLUMN ADE_CODICE    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_SM] ALTER COLUMN ADE_CODINT    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_SP] ALTER COLUMN STA_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_AVA_TG] ALTER COLUMN STA_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_COM_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_COM_ED] ALTER COLUMN LCD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_FOR_DD] ALTER COLUMN FOR_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_LIS_LO] ALTER COLUMN LIS_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MRI_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_NCR_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORD_DL] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORD_SD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORD_SN] ALTER COLUMN CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_DL] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_ED] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_EV] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_PO] ALTER COLUMN ORF_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ORF_SD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PCK_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PCK_LE] ALTER COLUMN LEG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PDA_CA] ALTER COLUMN MAG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PDA_MO] ALTER COLUMN MAG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PDA_TP] ALTER COLUMN MAG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PED_DT] ALTER COLUMN MAG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PED_PL] ALTER COLUMN MAG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PKG_LE] ALTER COLUMN LEG_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRB_DD] ALTER COLUMN ORD_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_D2] ALTER COLUMN PR2_CODART    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_D3] ALTER COLUMN PR3_CODBOB    VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_D3] ALTER COLUMN PR3_CODINT   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_D4] ALTER COLUMN PR4_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_D5] ALTER COLUMN PR5_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_DR] ALTER COLUMN PRR_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_DS] ALTER COLUMN PRS_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRD_PK] ALTER COLUMN PR5_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRF_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRG_DL] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRG_DO] ALTER COLUMN MAG_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRG_LT] ALTER COLUMN LEG_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRG_TG] ALTER COLUMN STA_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRO_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRO_OR] ALTER COLUMN PRO_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRO_PZ] ALTER COLUMN LIB_CODDA   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRO_PZ] ALTER COLUMN LIB_CODAL   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRO_ST] ALTER COLUMN STO_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRV_DD] ALTER COLUMN PRV_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_PRV_OR] ALTER COLUMN PRV_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_RAA_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_RIA_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_RIC_VA] ALTER COLUMN RIC_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_RIN_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_SIT_AN] ALTER COLUMN SIT_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_SLC_CQ] ALTER COLUMN SLC_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_SLF_CQ] ALTER COLUMN SLF_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_SPE_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_STA_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_STA_SD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_TVE_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_TVE_SD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_VEN_CL] ALTER COLUMN VEN_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_TVE_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_VEN_CL] ALTER COLUMN VEN_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[VALORE_MAGAZZINO] ALTER COLUMN CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[VENDITE_DD] ALTER COLUMN ORD_CODART   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL



---  ############################################# ULTERIORE CONTROLLO INCROCIATO IN BASE A SCRIPT CHE CERCA CODART,CODPRE,ANAART SU TUTTE LE TABELLE ##########################################





ALTER TABLE [dbo].[U_FOR_PR] ALTER COLUMN FPR_CODART   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL	
ALTER TABLE [dbo].[U_PKG_TD] ALTER COLUMN PKG_CODART	  	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[TAB_VEN_FA] ALTER COLUMN VEN_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[TAB_VEN_FP] ALTER COLUMN VEN_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[TAB_VEN_FPA] ALTER COLUMN VEN_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_POS_AN] ALTER COLUMN LIS_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_INV_MA] ALTER COLUMN INV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_INV_MA] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ALT_DA] ALTER COLUMN ALT_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_RA] ALTER COLUMN STA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_RI] ALTER COLUMN STA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_RR] ALTER COLUMN STA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_RT] ALTER COLUMN STA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_SP] ALTER COLUMN STA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PRG_SM] ALTER COLUMN SEL_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_LEG_DD] ALTER COLUMN LEG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_SA] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_LIS_TA] ALTER COLUMN LIS_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_LOC_GI] ALTER COLUMN LOC_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_LOC_MO] ALTER COLUMN LOC_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[L_BOL_LE] ALTER COLUMN LEG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[CHIUSURA_MAGAZZINO_DD] ALTER COLUMN CODART  VARCHAR(30) COLLATE Latin1_General_CI_AS NULL        
ALTER TABLE [dbo].[U_CLI_AR] ALTER COLUMN CODART	        VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_AN] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_AR] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_CA] ALTER COLUMN MOV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_CL] ALTER COLUMN MOV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BFO_SN] ALTER COLUMN CODART	        VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_CP] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_DA] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_DF] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_DM] ALTER COLUMN MOV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[STORICO_SCHEDE_SDS] ALTER COLUMN SDS_CODART	   VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_FO] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BOL_LE] ALTER COLUMN LEG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BOL_RE] ALTER COLUMN ORF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_GS] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_IN] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MA] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MF] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BUD_AM] ALTER COLUMN BUD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_SCA_AN] ALTER COLUMN SCA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MS] ALTER COLUMN MOV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_SCO_MI] ALTER COLUMN SCO_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_PR] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_RI] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_CAN_CA] ALTER COLUMN CAS_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_CAN_CO] ALTER COLUMN ORF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_SS] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_CAN_RE] ALTER COLUMN ORF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAR_AN] ALTER COLUMN MAR_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[RDA_DD] ALTER COLUMN CODART	           	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MEN_DD] ALTER COLUMN MEN_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_FAB_CL] ALTER COLUMN FAB_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_FAB_CL] ALTER COLUMN ORD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MPA_CQ] ALTER COLUMN MPA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MPF_CQ] ALTER COLUMN MPF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_CER_CO] ALTER COLUMN CER_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_OFF_SD] ALTER COLUMN ORD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[SITORDQTAMOV] ALTER COLUMN CODART  	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_WRK_DD] ALTER COLUMN ORD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_REG_FA] ALTER COLUMN CodArt_A	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_REG_FA] ALTER COLUMN CodArt_P	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_REG_FA] ALTER COLUMN CodArt_R	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_REG_FA] ALTER COLUMN CodArt_S	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_WRK_SD] ALTER COLUMN ORD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ORF_CO] ALTER COLUMN ORF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ORF_DT] ALTER COLUMN ORF_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[CARRELLO] ALTER COLUMN ORD_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_COM_ET] ALTER COLUMN LCT_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ORM_DD] ALTER COLUMN ORM_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_CON_AN] ALTER COLUMN SCA_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PAR_CQ] ALTER COLUMN PAR_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_DIS_AN] ALTER COLUMN DIS_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMMESSA_TT] ALTER COLUMN CodArt_A	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMMESSA_TT] ALTER COLUMN CodArt_P	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMMESSA_TT] ALTER COLUMN CodArt_R	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMMESSA_TT] ALTER COLUMN CodArt_S	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMMESSA_TT] ALTER COLUMN CodArt_X	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[COMPATIBGG] ALTER COLUMN CODART	        VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_DSB_AN] ALTER COLUMN DSB_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROVVI] ALTER COLUMN ORD_CODART	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MA] ALTER COLUMN INV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MA] ALTER COLUMN MAG_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MO] ALTER COLUMN INV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[GRUPPIART] ALTER COLUMN CODART		   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDV_CA] ALTER COLUMN CAS_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDV_PA] ALTER COLUMN PDV_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDV_SA] ALTER COLUMN SAL_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[ANAART] ALTER COLUMN CON_CODART	   		VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[S_COM_ET] ALTER COLUMN LCT_CODART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MO_NEW] ALTER COLUMN MOV_CODART  	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ORD_DG] ALTER COLUMN CODART		   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_INV_MA] ALTER COLUMN INV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_INV_MA] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MO] ALTER COLUMN MOV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_SA] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[LOG_NEW_MAG] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[L_BOL_LE] ALTER COLUMN LEG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_AN] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_CA] ALTER COLUMN MOV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_DA] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BOL_LE] ALTER COLUMN LEG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_GG] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_GS] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MS] ALTER COLUMN MOV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_SS] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[L_MAG_GG] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[S_MAG_MO] ALTER COLUMN MOV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PCK_LE] ALTER COLUMN LEG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_CA] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MA] ALTER COLUMN INV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MA] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MO] ALTER COLUMN INV_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_MO] ALTER COLUMN MAG_ANAART	  	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PDA_TP] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PED_DT] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PED_PL] ALTER COLUMN MAG_ANAART	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_MAG_MO_NEW] ALTER COLUMN MOV_ANAART	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_AMM_DD] ALTER COLUMN ord_codpri	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_AMM_TT] ALTER COLUMN ord_codpri	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_CODPRI	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ART_AN] ALTER COLUMN ART_CODPRI	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[WC_PRODUCTS] ALTER COLUMN ART_CODPRI	   	VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


---  ############################################# ULTERIORE CONTROLLO INCROCIATO IN BASE A SCRIPT CHE CERCA ORD_CDAPRD SU TUTTE LE TABELLE ##########################################

ALTER TABLE [dbo].[U_BOL_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[L_BOL_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[CONTRMDB_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_BCL_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_ORD_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[VENDITE_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_FAP_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_FAT_DD] ALTER COLUMN ORD_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PED_DT] ALTER COLUMN MAG_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_PED_PL] ALTER COLUMN MAG_CDAPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

---  ############################################# ULTERIORE CONTROLLO MANUALE ##########################################

ALTER TABLE [dbo].[U_DIS_TT] ALTER COLUMN DIT_GRUPPO VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[U_DIS_DD] ALTER COLUMN DIS_GRUPPO VARCHAR(30) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[PROD_AVANZA]			ALTER COLUMN COMP VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_DISIMPEGNI]		ALTER COLUMN CODINT VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_IMPEGNI]		ALTER COLUMN CODINT VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_LEGAMI]			ALTER COLUMN CODINT VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_ORDINI]			ALTER COLUMN GRUPRD VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PACKFOR]		ALTER COLUMN CODINT VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PACKING]		ALTER COLUMN CODINT VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PIANIF_DB]		ALTER COLUMN CODGRU VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PIANIF_DB]		ALTER COLUMN CODSUP VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PIANIF_SPALMA]	ALTER COLUMN SUPPORTO VARCHAR(30) COLLATE Latin1_General_CI_AS NULL
ALTER TABLE [dbo].[PROD_PIANIF_SPALMA]	ALTER COLUMN TIPADE VARCHAR(30) COLLATE Latin1_General_CI_AS NULL