
-- ALLARGAMENTO CAMVO MOV_DESMOV DA 45 A 100 CHR SU TABELLE MOV_CONT E INDICE

ALTER TABLE [dbo].[MOV_CONT]  ALTER COLUMN  
	[MOV_DESMOV] [varchar] (100) COLLATE Latin1_General_CI_AS NULL 
GO

ALTER TABLE [dbo].[INDICE]  ALTER COLUMN  
	[MOV_DESMOV] [varchar] (100) COLLATE Latin1_General_CI_AS NULL 
GO
