
--- AGGIUNTA NUOVI CAMPI
ALTER TABLE [dbo].[U_PRD_D5] ADD
	PR5_ALTPCK numeric(10,0) NULL,
	PR5_LARPCK numeric(10,0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_PR5_ALTPCK] DEFAULT (0) FOR [PR5_ALTPCK],
	CONSTRAINT [DF_U_PRD_D5_PR5_LARPCK] DEFAULT (0) FOR [PR5_LARPCK]
go

UPDATE U_PRD_D5 SET PR5_ALTPCK = 0
UPDATE U_PRD_D5 SET PR5_LARPCK = 0



