


 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_ALLDANG  BIT NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_ALLDANG] DEFAULT (0) FOR [AZI_ALLDANG]
GO

UPDATE U_AZI_PB SET AZI_ALLDANG  = 0