
ALTER TABLE [dbo].[U_AGE_AN] ALTER COLUMN
	 AGE_RAGSOC varchar(80) COLLATE Latin1_General_CI_AS NULL
GO


ALTER TABLE [dbo].[U_AGE_AN] ALTER COLUMN
	 AGE_INDIRI varchar(70) COLLATE Latin1_General_CI_AS NULL
GO
