


 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_CTRCLOF  BIT NULL,
	AZI_CTRCLOR  BIT NULL,
	AZI_CTRRISD  BIT NULL

GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_CTRCLOF] DEFAULT (0) FOR [AZI_CTRCLOF],
	CONSTRAINT [DF_U_AZI_PB_AZI_CTRCLOR] DEFAULT (0) FOR [AZI_CTRCLOR],
	CONSTRAINT [DF_U_AZI_PB_AZI_CTRRISD] DEFAULT (0) FOR [AZI_CTRRISD]
GO

UPDATE U_AZI_PB SET AZI_CTRCLOF  = 0
UPDATE U_AZI_PB SET AZI_CTRCLOR  = 0
UPDATE U_AZI_PB SET AZI_CTRRISD  = 0
