/************************************************************/
/* INSERIMENTO NUOVI CAMPI PER GESTIONE QUALIFICA FORNITORE */
/************************************************************/

ALTER TABLE [dbo].[U_FOR_AN] ADD
	FOR_STRATEGICO BIT NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_STRATEGICO] DEFAULT (0),
	FOR_DIVISIONE varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_DIVISIONE] DEFAULT (''),
	FOR_TIPOLOGIA varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_TIPOLOGIA] DEFAULT (''),
	FOR_TIPOQUALIF varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_TIPOQUALIF] DEFAULT (''),
	FOR_TIPOCONTR varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_TIPOCONTR] DEFAULT (''),
	FOR_SCADCONTR varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_SCADCONTR] DEFAULT (''),
	FOR_CLRISCHIO varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_FOR_AN_FOR_CLRISCHIO] DEFAULT ('')
GO
