

ALTER TABLE [dbo].[IMPIANTI_RI] ADD
	ORD_PROVIN varchar(25) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_RI_ORD_PROVIN] DEFAULT (''),
	ORD_TELEFO varchar(25) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_RI_ORD_TELEFO] DEFAULT (''),
	ORD_CELLU varchar(25) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_RI_ORD_CELLU] DEFAULT ('')
GO
