
ALTER TABLE [DBO].[U_OFF_TT] ADD 
	ORD_MOTIVAZ varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_MOTIVAZ] DEFAULT (''),
	ORD_NOTECF text COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_OFF_TT_ORD_NOTECF] DEFAULT ('')
GO
