/* 
**************************************************************
INSERIMENTO CAMPI PER SCHEDA WEB IN TABELLA COMPLEMENTARE ANAGRAFICA ARTICOLI:
	- ART_FLGOFF: Flag OFFERTA
	- ART_DTOFFDA: Data Offerta Dal
	- ART_DTOFFAL: Data Offerta Al
	- ART_FLGNEW: Flag NUOVO
	- ART_DTNEWDA: Data Nuovo Dal
	- ART_DTNEWAL: Data Nuovo Al
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_FLGOFF BIT NULL,
	ART_DTOFFDA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ART_DTOFFAL varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ART_FLGNEW BIT NULL,
	ART_DTNEWDA varchar(10) COLLATE Latin1_General_CI_AS NULL,
	ART_DTNEWAL varchar(10) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_AN] WITH NOCHECK ADD
	CONSTRAINT [DF_U_ART_AN_ART_FLGOFF] DEFAULT (0) FOR [ART_FLGOFF],
	CONSTRAINT [DF_U_ART_AN_ART_DTOFFDA] DEFAULT ('') FOR [ART_DTOFFDA],
	CONSTRAINT [DF_U_ART_AN_ART_DTOFFAL] DEFAULT ('') FOR [ART_DTOFFAL],
	CONSTRAINT [DF_U_ART_AN_ART_FLGNEW] DEFAULT (0) FOR [ART_FLGNEW],
	CONSTRAINT [DF_U_ART_AN_ART_DTNEWDA] DEFAULT ('') FOR [ART_DTNEWDA],
	CONSTRAINT [DF_U_ART_AN_ART_DTNEWAL] DEFAULT ('') FOR [ART_DTNEWAL]
go

UPDATE U_ART_AN SET ART_FLGOFF = 0
UPDATE U_ART_AN SET ART_DTOFFDA = ''
UPDATE U_ART_AN SET ART_DTOFFAL = ''
UPDATE U_ART_AN SET ART_FLGNEW = 0
UPDATE U_ART_AN SET ART_DTNEWDA = ''
UPDATE U_ART_AN SET ART_DTNEWAL = ''