/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_AZI_AN] ADD 
	 	 AZI_CARORF varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_CQUMPC varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_CQUMPN varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_SPAPRO varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_SPAMPR varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_SPACQS varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_CQUSLC varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_CQUSLN varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_RIBPRO varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_RIBSLR varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_RIBSLO varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_TAGPRO varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_TAGSLR varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 	 AZI_TAGPFO varchar(06) COLLATE Latin1_General_CI_AS NULL,
 		 AZI_ALTLUN [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[U_AZI_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_AN_AZI_CARORF] DEFAULT ('      ') FOR [AZI_CARORF],
	CONSTRAINT [DF_U_AZI_AN_AZI_CQUMPC] DEFAULT ('      ') FOR [AZI_CQUMPC],
	CONSTRAINT [DF_U_AZI_AN_AZI_CQUMPN] DEFAULT ('      ') FOR [AZI_CQUMPN],
	CONSTRAINT [DF_U_AZI_AN_AZI_SPAPRO] DEFAULT ('      ') FOR [AZI_SPAPRO],
	CONSTRAINT [DF_U_AZI_AN_AZI_SPAMPR] DEFAULT ('      ') FOR [AZI_SPAMPR],
	CONSTRAINT [DF_U_AZI_AN_AZI_SPACQS] DEFAULT ('      ') FOR [AZI_SPACQS],
	CONSTRAINT [DF_U_AZI_AN_AZI_CQUSLC] DEFAULT ('      ') FOR [AZI_CQUSLC],
	CONSTRAINT [DF_U_AZI_AN_AZI_CQUSLN] DEFAULT ('      ') FOR [AZI_CQUSLN],
	CONSTRAINT [DF_U_AZI_AN_AZI_RIBPRO] DEFAULT ('      ') FOR [AZI_RIBPRO],
	CONSTRAINT [DF_U_AZI_AN_AZI_RIBSLR] DEFAULT ('      ') FOR [AZI_RIBSLR],
	CONSTRAINT [DF_U_AZI_AN_AZI_RIBSLO] DEFAULT ('      ') FOR [AZI_RIBSLO],
	CONSTRAINT [DF_U_AZI_AN_AZI_TAGPRO] DEFAULT ('      ') FOR [AZI_TAGPRO],
	CONSTRAINT [DF_U_AZI_AN_AZI_TAGSLR] DEFAULT ('      ') FOR [AZI_TAGSLR],
	CONSTRAINT [DF_U_AZI_AN_AZI_TAGPFO] DEFAULT ('      ') FOR [AZI_TAGPFO],
	CONSTRAINT [DF_U_AZI_AN_AZI_ALTLUN] DEFAULT (0) FOR [AZI_ALTLUN]
go


UPDATE U_AZI_AN SET AZI_CARORF = '      '
UPDATE U_AZI_AN SET AZI_CQUMPC = '      '
UPDATE U_AZI_AN SET AZI_CQUMPN = '      '
UPDATE U_AZI_AN SET AZI_SPAPRO = '      '
UPDATE U_AZI_AN SET AZI_SPAMPR = '      '
UPDATE U_AZI_AN SET AZI_SPACQS = '      '
UPDATE U_AZI_AN SET AZI_CQUSLC = '      '
UPDATE U_AZI_AN SET AZI_CQUSLN = '      '
UPDATE U_AZI_AN SET AZI_RIBPRO = '      '
UPDATE U_AZI_AN SET AZI_RIBSLR = '      '
UPDATE U_AZI_AN SET AZI_RIBSLO = '      '
UPDATE U_AZI_AN SET AZI_TAGPRO = '      '
UPDATE U_AZI_AN SET AZI_TAGSLR = '      '
UPDATE U_AZI_AN SET AZI_TAGPFO = '      '
UPDATE U_AZI_AN SET AZI_ALTLUN = 0

