
ALTER TABLE [DBO].[U_CNT_TT] ADD 
	CNT_IDNSO varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_CNT_TT_ORD_IDNSO] DEFAULT (''),
	CNT_IDSDI varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_CNT_TT_ORD_IDSDI] DEFAULT ('')
GO
