/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	ART_TIPADE VARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	ART_ADESIV VARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	ART_ROTLNG VARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	ART_ROTTRA VARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	ART_ALNLNG VARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	ART_ALNTRA VARCHAR(20) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_TIPADE] DEFAULT ('') FOR [ART_TIPADE],
	CONSTRAINT [DF_U_ART_PR_ART_ADESIV] DEFAULT ('') FOR [ART_ADESIV],
	CONSTRAINT [DF_U_ART_PR_ART_ROTLNG] DEFAULT ('') FOR [ART_ROTLNG],
	CONSTRAINT [DF_U_ART_PR_ART_ROTTRA] DEFAULT ('') FOR [ART_ROTTRA],
	CONSTRAINT [DF_U_ART_PR_ART_ALNLNG] DEFAULT ('') FOR [ART_ALNLNG],
	CONSTRAINT [DF_U_ART_PR_ART_ALNTRA] DEFAULT ('') FOR [ART_ALNTRA]
go

UPDATE U_ART_PR SET ART_TIPADE = SPACE(50)
UPDATE U_ART_PR SET ART_ADESIV = SPACE(20)
UPDATE U_ART_PR SET ART_ROTLNG = SPACE(20)
UPDATE U_ART_PR SET ART_ROTTRA = SPACE(20)
UPDATE U_ART_PR SET ART_ALNLNG = SPACE(20)
UPDATE U_ART_PR SET ART_ALNTRA = SPACE(20)


