/*    
***********************************************************************
INSERIMENTO DATI LETTERA INTENTO IN ANAGRAFICA CLIENTI
***********************************************************************
*/

ALTER TABLE [dbo].[U_ANA_CL] ADD 
	 CLI_UFFIVA varchar(25) COLLATE Latin1_General_CI_AS NULL,
	 CLI_ARTINTE varchar(3) COLLATE Latin1_General_CI_AS NULL,
     CLI_NOTEINT [text] COLLATE Latin1_General_CI_AS NULL,
	 CLI_INTUNO varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_INTDUE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_INTTRE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_ANNOPE varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 CLI_IMPINT numeric (17,3),
	 CLI_ANNOPE2 varchar(4) COLLATE Latin1_General_CI_AS NULL,
	 CLI_GGINTD varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_MMINTD varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_GGINTA varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_MMINTA varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 CLI_DOGANA varchar(25) COLLATE Latin1_General_CI_AS NULL,
	 CLI_CLIAZI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 CLI_INDAZI varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 CLI_CAPAZI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 CLI_COMUNEAZI varchar(35) COLLATE Latin1_General_CI_AS NULL,
	 CLI_PROVAZI varchar(3) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ANA_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ANA_CL_CLI_UFFIVA] DEFAULT ('') FOR [CLI_UFFIVA],
	CONSTRAINT [DF_U_ANA_CL_CLI_ARTINTE] DEFAULT ('') FOR [CLI_ARTINTE],
	CONSTRAINT [DF_U_ANA_CL_CLI_NOTEINT] DEFAULT ('') FOR [CLI_NOTEINT],
	CONSTRAINT [DF_U_ANA_CL_CLI_INTUNO] DEFAULT ('') FOR [CLI_INTUNO],
	CONSTRAINT [DF_U_ANA_CL_CLI_INTDUE] DEFAULT ('') FOR [CLI_INTDUE],
	CONSTRAINT [DF_U_ANA_CL_CLI_INTTRE] DEFAULT ('') FOR [CLI_INTTRE],
	CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE] DEFAULT ('') FOR [CLI_ANNOPE],
	CONSTRAINT [DF_U_ANA_CL_CLI_IMPINT] DEFAULT (0) FOR [CLI_IMPINT],
	CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE2] DEFAULT ('') FOR [CLI_ANNOPE2],
	CONSTRAINT [DF_U_ANA_CL_CLI_GGINTD] DEFAULT ('') FOR [CLI_GGINTD],
	CONSTRAINT [DF_U_ANA_CL_CLI_MMINTD] DEFAULT ('') FOR [CLI_MMINTD],
	CONSTRAINT [DF_U_ANA_CL_CLI_GGINTA] DEFAULT ('') FOR [CLI_GGINTA],
	CONSTRAINT [DF_U_ANA_CL_CLI_MMINTA] DEFAULT ('') FOR [CLI_MMINTA],
	CONSTRAINT [DF_U_ANA_CL_CLI_DOGANA] DEFAULT ('') FOR [CLI_DOGANA],
	CONSTRAINT [DF_U_ANA_CL_CLI_CLIAZI] DEFAULT ('') FOR [CLI_CLIAZI],
	CONSTRAINT [DF_U_ANA_CL_CLI_INDAZI] DEFAULT ('') FOR [CLI_INDAZI],
	CONSTRAINT [DF_U_ANA_CL_CLI_CAPAZI] DEFAULT ('') FOR [CLI_CAPAZI],
	CONSTRAINT [DF_U_ANA_CL_CLI_COMUNEAZI] DEFAULT ('') FOR [CLI_COMUNEAZI],
	CONSTRAINT [DF_U_ANA_CL_CLI_PROVAZI] DEFAULT ('') FOR [CLI_PROVAZI]
go

UPDATE U_ANA_CL SET CLI_UFFIVA = ''
UPDATE U_ANA_CL SET CLI_ARTINTE = ''
UPDATE U_ANA_CL SET CLI_NOTEINT = ''
UPDATE U_ANA_CL SET CLI_INTUNO = ''
UPDATE U_ANA_CL SET CLI_INTDUE = ''
UPDATE U_ANA_CL SET CLI_INTTRE = ''
UPDATE U_ANA_CL SET CLI_ANNOPE = ''
UPDATE U_ANA_CL SET CLI_IMPINT = 0
UPDATE U_ANA_CL SET CLI_ANNOPE2 = ''
UPDATE U_ANA_CL SET CLI_GGINTD = ''
UPDATE U_ANA_CL SET CLI_MMINTD = ''
UPDATE U_ANA_CL SET CLI_GGINTA = ''
UPDATE U_ANA_CL SET CLI_MMINTA = ''
UPDATE U_ANA_CL SET CLI_DOGANA = ''
UPDATE U_ANA_CL SET CLI_CLIAZI = ''
UPDATE U_ANA_CL SET CLI_INDAZI = ''
UPDATE U_ANA_CL SET CLI_CAPAZI = ''
UPDATE U_ANA_CL SET CLI_COMUNEAZI = ''
UPDATE U_ANA_CL SET CLI_PROVAZI = ''