/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	ART_CARATTERE VARCHAR(16) COLLATE Latin1_General_CI_AS NULL,
	ART_NUMERICO1 NUMERIC (7,0)  NULL,
	ART_NUMERICO2 NUMERIC(6,3) NULL,
	ART_CAMPOMEMO TEXT COLLATE Latin1_General_CI_AS NULL,
        ART_CAMLOGICO [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_CARATTERE] DEFAULT ('') FOR [ART_CARATTERE],
	CONSTRAINT [DF_U_ART_PR_ART_NUMERICO1] DEFAULT (0) FOR [ART_NUMERICO1],	
	CONSTRAINT [DF_U_ART_PR_ART_NUMERICO2] DEFAULT (0) FOR [ART_NUMERICO2],	
	CONSTRAINT [DF_U_ART_PR_ART_CAMPOMEMO] DEFAULT ('') FOR [ART_CAMPOMEMO],
	CONSTRAINT [DF_U_ART_PR_ART_CAMLOGICO] DEFAULT (0) FOR [ART_CAMLOGICO]

go

UPDATE U_ART_PR SET ART_CARATTERE = SPACE(16)
UPDATE U_ART_PR SET ART_NUMERICO1 = 0
UPDATE U_ART_PR SET ART_NUMERICO2 = 0
UPDATE U_ART_PR SET ART_CAMPOMEMO = ''
UPDATE U_ART_PR SET ART_CAMLOGICO = 0
