
/*         
***************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
***************************************************************
*/
ALTER TABLE [dbo].[CONTI] ADD 
	 CON_PADRE BIT NOT NULL CONSTRAINT [DF_CONTI_CON_PADRE] DEFAULT (0)
go

if exists (select * from U_AZI_PC WHERE AZI_CONTOSIMILCEE = 1)
	UPDATE CONTI SET CON_PADRE = 1 WHERE CON_ANNO+CON_CONTO NOT IN (
		SELECT CON_ANNO+CON_CONTO FROM CONTI AS C1 WHERE (SELECT COUNT(*) FROM CONTI WHERE CON_ANNO = C1.CON_ANNO AND CON_CONTO <> C1.CON_CONTO AND CON_CONTO LIKE RTRIM(C1.CON_CONTO)+'%') = 0)

	UPDATE CONTI SET CON_PADRE = 0 WHERE CON_TIPOCO IN ('C','F')
GO 


