/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_SP] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_SP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_SP_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_SP_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_SP_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_SP_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_SP_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_SP_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_SP SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_SP SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_SP SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_SP SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_SP SET STA_TEMPOC = 0
UPDATE U_PRG_SP SET STA_TIPRDC = SPACE(03)


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_RA] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_RA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_RA_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_RA_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_RA_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_RA_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_RA_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_RA_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_RA SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_RA SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_RA SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_RA SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_RA SET STA_TEMPOC = 0
UPDATE U_PRG_RA SET STA_TIPRDC = SPACE(03)


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_RI] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_RI] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_RI_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_RI_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_RI_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_RI_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_RI_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_RI_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_RI SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_RI SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_RI SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_RI SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_RI SET STA_TEMPOC = 0
UPDATE U_PRG_RI SET STA_TIPRDC = SPACE(03)


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_RR] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_RR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_RR_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_RR_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_RR_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_RR_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_RR_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_RR_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_RR SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_RR SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_RR SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_RR SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_RR SET STA_TEMPOC = 0
UPDATE U_PRG_RR SET STA_TIPRDC = SPACE(03)


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_TG] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_TG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_TG_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_TG_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_TG_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_TG_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_TG_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_TG_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_TG SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_TG SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_TG SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_TG SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_TG SET STA_TEMPOC = 0
UPDATE U_PRG_TG SET STA_TIPRDC = SPACE(03)


/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_RT] ADD 
	STA_DTINIC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORINIC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_DTFINC VARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	STA_ORFINC VARCHAR(08) COLLATE Latin1_General_CI_AS NULL,
	STA_TEMPOC NUMERIC (6,2)  NULL,
	STA_TIPRDC VARCHAR(03) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_RT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_RT_STA_DTINIC] DEFAULT ('') FOR [STA_DTINIC],
	CONSTRAINT [DF_U_PRG_RT_STA_ORINIC] DEFAULT ('') FOR [STA_ORINIC],
	CONSTRAINT [DF_U_PRG_RT_STA_DTFINC] DEFAULT ('') FOR [STA_DTFINC],
	CONSTRAINT [DF_U_PRG_RT_STA_ORFINC] DEFAULT ('') FOR [STA_ORFINC],
	CONSTRAINT [DF_U_PRG_RT_STA_TEMPOC] DEFAULT (0) FOR [STA_TEMPOC],	
	CONSTRAINT [DF_U_PRG_RT_STA_TIPRDC] DEFAULT ('') FOR [STA_TIPRDC]
go

UPDATE U_PRG_RT SET STA_DTINIC = SPACE(10)
UPDATE U_PRG_RT SET STA_ORINIC = SPACE(08)
UPDATE U_PRG_RT SET STA_DTFINC = SPACE(10)
UPDATE U_PRG_RT SET STA_ORFINC = SPACE(08)
UPDATE U_PRG_RT SET STA_TEMPOC = 0
UPDATE U_PRG_RT SET STA_TIPRDC = SPACE(03)
