
UPDATE U_ART_PR SET ART_PERCOP = 0  WHERE ART_PERCOP IS NULL
UPDATE U_ART_PR SET ART_TIPDOC = '' WHERE ART_TIPDOC IS NULL
UPDATE U_ART_PR SET ART_DSTDOC = '' WHERE ART_DSTDOC IS NULL
UPDATE U_ART_PR SET ART_MICROL = '' WHERE ART_MICROL IS NULL
UPDATE U_ART_PR SET ART_SCOFIS = 0  WHERE ART_SCOFIS IS NULL
UPDATE U_ART_PR SET ART_PRVFIS = 0  WHERE ART_PRVFIS IS NULL
UPDATE U_ART_PR SET ART_QPKMIN = 0  WHERE ART_QPKMIN IS NULL
UPDATE U_ART_PR SET ART_QPKMAX = 0  WHERE ART_QPKMAX IS NULL
UPDATE U_ART_PR SET ART_SCFIS2 = 0  WHERE ART_SCFIS2 IS NULL
UPDATE U_ART_PR SET ART_SCFIS3 = 0  WHERE ART_SCFIS3 IS NULL

UPDATE U_ART_KO SET ART_SERBOL = '' WHERE ART_SERBOL IS NULL
UPDATE U_ART_KO SET ART_AAPROD = 0  WHERE ART_AAPROD IS NULL
UPDATE U_ART_KO SET ART_SERNUM = '' WHERE ART_SERNUM IS NULL
UPDATE U_ART_KO SET ART_NUMEDA = 0  WHERE ART_NUMEDA IS NULL
UPDATE U_ART_KO SET ART_NUMEAL = 0  WHERE ART_NUMEAL IS NULL
UPDATE U_ART_KO SET ART_CBFISC = '' WHERE ART_CBFISC IS NULL

UPDATE U_AST_AN SET AST_CORSIA = '' WHERE AST_CORSIA IS NULL

UPDATE U_BOL_TT SET ORD_SGNCLL = 0  WHERE ORD_SGNCLL IS NULL

UPDATE L_BOL_TT SET ORD_SGNCLL = 0  WHERE ORD_SGNCLL IS NULL

UPDATE U_CLI_AN SET CLI_RECCAT = 0  WHERE CLI_RECCAT IS NULL
UPDATE U_CLI_AN SET CLI_RECCOG = '' WHERE CLI_RECCOG IS NULL
UPDATE U_CLI_AN SET CLI_RECNOM = '' WHERE CLI_RECNOM IS NULL
UPDATE U_CLI_AN SET CLI_RECCDF = '' WHERE CLI_RECCDF IS NULL
UPDATE U_CLI_AN SET CLI_RECTIP = '' WHERE CLI_RECTIP IS NULL
UPDATE U_CLI_AN SET CLI_RECDES = '' WHERE CLI_RECDES IS NULL
UPDATE U_CLI_AN SET CLI_MEMO   = '' WHERE SUBSTRING(CLI_MEMO,1,1) IS NULL
UPDATE U_CLI_AN SET CLI_SC2FIS = 0  WHERE CLI_SC2FIS IS NULL
UPDATE U_CLI_AN SET CLI_FLAVV1 = 0  WHERE CLI_FLAVV1 IS NULL
UPDATE U_CLI_AN SET CLI_FLAVV2 = 0  WHERE CLI_FLAVV2 IS NULL
UPDATE U_CLI_AN SET CLI_FLAVV3 = 0  WHERE CLI_FLAVV3 IS NULL

UPDATE U_ORD_TT SET ORD_MEMO   = '' WHERE SUBSTRING(ORD_MEMO,1,1) IS NULL
