ALTER TABLE [dbo].[U_PRD_DR] ADD
	PRR_SEQUEN numeric(3, 0) NULL,
	PRR_SEQPOS numeric(3, 0) NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_PRR_SEQUEN] DEFAULT (0) FOR [PRR_SEQUEN],
	CONSTRAINT [DF_U_PRD_DR_PRR_SEQPOS] DEFAULT (0) FOR [PRR_SEQPOS]
go

UPDATE U_PRD_DR SET PRR_SEQUEN = 0
UPDATE U_PRD_DR SET PRR_SEQPOS = 0
