/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[RES_OPER] ADD 
	MAIL [numeric] (2,0) NULL,
	MITTENTE varchar(100) COLLATE Latin1_General_CI_AS NULL,
	SMTP varchar(100) COLLATE Latin1_General_CI_AS NULL,
	AUTH_USER varchar(100) COLLATE Latin1_General_CI_AS NULL,
	AUTH_PASS varchar(100) COLLATE Latin1_General_CI_AS NULL,
	PORT varchar(5) COLLATE Latin1_General_CI_AS NULL,
	CRYPTO varchar(10) COLLATE Latin1_General_CI_AS NULL,
	NOTIFICA varchar(100) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[RES_OPER] WITH NOCHECK ADD 
	CONSTRAINT [DF_RES_OPER_MAIL] DEFAULT (0) FOR [MAIL],
	CONSTRAINT [DF_RES_OPER_MITTENTE] DEFAULT '' FOR [MITTENTE],
	CONSTRAINT [DF_RES_OPER_SMTP] DEFAULT '' FOR [SMTP],
	CONSTRAINT [DF_RES_OPER_AUTH_USER] DEFAULT '' FOR [AUTH_USER],
	CONSTRAINT [DF_RES_OPER_AUTH_PASS] DEFAULT '' FOR [AUTH_PASS],
	CONSTRAINT [DF_RES_OPER_PORT] DEFAULT '' FOR [PORT],
	CONSTRAINT [DF_RES_OPER_CRYPTO] DEFAULT '' FOR [CRYPTO],
	CONSTRAINT [DF_RES_OPER_NOTIFICA] DEFAULT '' FOR [NOTIFICA]
go

UPDATE RES_OPER SET MAIL	= 1
UPDATE RES_OPER SET MITTENTE = ''
UPDATE RES_OPER SET SMTP = ''
UPDATE RES_OPER SET AUTH_USER = ''
UPDATE RES_OPER SET AUTH_PASS = ''
UPDATE RES_OPER SET PORT = '25'
UPDATE RES_OPER SET CRYPTO = ''
UPDATE RES_OPER SET NOTIFICA = ''
