
ALTER TABLE [dbo].[IMPIANTI_LI] ADD 
	LIS_IMPRVO NUMERIC(19,3) NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_IMPRVO] DEFAULT (0),
	LIS_ATTRVO varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTRVO] DEFAULT (''),
	LIS_IMPRFG NUMERIC(19,3) NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_IMPRFG] DEFAULT (0),
	LIS_ATTRFG varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTRFG] DEFAULT (''),
	LIS_IMPABT NUMERIC(19,3) NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_IMPABT] DEFAULT (0),
	LIS_ATTABT varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_IMPIANTI_LI_LIS_ATTABT] DEFAULT ('')
GO
