
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_PRG_RI] ADD 
	 STA_CDCLI6 varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 STA_DSCLI6 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 STA_CDCLI7 varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 STA_DSCLI7 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 STA_CDCLI8 varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 STA_DSCLI8 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 STA_CDCLI9 varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 STA_DSCLI9 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 STA_CDCLI0 varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 STA_DSCLI0 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 STA_UNIQU6 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB6 numeric(6) NULL,
	 STA_QTBOB6 numeric(6) NULL,
	 STA_UNIQU7 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB7 numeric(6) NULL,
	 STA_QTBOB7 numeric(6) NULL,
	 STA_UNIQU8 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB8 numeric(6) NULL,
	 STA_QTBOB8 numeric(6) NULL,
	 STA_UNIQU9 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB9 numeric(6) NULL,
	 STA_QTBOB9 numeric(6) NULL,
	 STA_UNIQU0 varchar(36) COLLATE Latin1_General_CI_AS NULL,
	 STA_NRBOB0 numeric(6) NULL,
	 STA_QTBOB0 numeric(6) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_PRG_RI] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRG_RI_STA_CDCLI6] DEFAULT ('') FOR [STA_CDCLI6],
	CONSTRAINT [DF_U_PRG_RI_STA_DSCLI6] DEFAULT ('') FOR [STA_DSCLI6],
	CONSTRAINT [DF_U_PRG_RI_STA_CDCLI7] DEFAULT ('') FOR [STA_CDCLI7],
	CONSTRAINT [DF_U_PRG_RI_STA_DSCLI7] DEFAULT ('') FOR [STA_DSCLI7],
	CONSTRAINT [DF_U_PRG_RI_STA_CDCLI8] DEFAULT ('') FOR [STA_CDCLI8],
	CONSTRAINT [DF_U_PRG_RI_STA_DSCLI8] DEFAULT ('') FOR [STA_DSCLI8],
	CONSTRAINT [DF_U_PRG_RI_STA_CDCLI9] DEFAULT ('') FOR [STA_CDCLI9],
	CONSTRAINT [DF_U_PRG_RI_STA_DSCLI9] DEFAULT ('') FOR [STA_DSCLI9],
	CONSTRAINT [DF_U_PRG_RI_STA_CDCLI0] DEFAULT ('') FOR [STA_CDCLI0],
	CONSTRAINT [DF_U_PRG_RI_STA_DSCLI0] DEFAULT ('') FOR [STA_DSCLI0],
	CONSTRAINT [DF_U_PRG_RI_STA_UNIQU6] DEFAULT ('') FOR [STA_UNIQU6],
	CONSTRAINT [DF_U_PRG_RI_STA_NRBOB6] DEFAULT (0) FOR [STA_NRBOB6],
	CONSTRAINT [DF_U_PRG_RI_STA_QTBOB6] DEFAULT (0) FOR [STA_QTBOB6],
	CONSTRAINT [DF_U_PRG_RI_STA_UNIQU7] DEFAULT ('') FOR [STA_UNIQU7],
	CONSTRAINT [DF_U_PRG_RI_STA_NRBOB7] DEFAULT (0) FOR [STA_NRBOB7],
	CONSTRAINT [DF_U_PRG_RI_STA_QTBOB7] DEFAULT (0) FOR [STA_QTBOB7],
	CONSTRAINT [DF_U_PRG_RI_STA_UNIQU8] DEFAULT ('') FOR [STA_UNIQU8],
	CONSTRAINT [DF_U_PRG_RI_STA_NRBOB8] DEFAULT (0) FOR [STA_NRBOB8],
	CONSTRAINT [DF_U_PRG_RI_STA_QTBOB8] DEFAULT (0) FOR [STA_QTBOB8],
	CONSTRAINT [DF_U_PRG_RI_STA_UNIQU9] DEFAULT ('') FOR [STA_UNIQU9],
	CONSTRAINT [DF_U_PRG_RI_STA_NRBOB9] DEFAULT (0) FOR [STA_NRBOB9],
	CONSTRAINT [DF_U_PRG_RI_STA_QTBOB9] DEFAULT (0) FOR [STA_QTBOB9],
	CONSTRAINT [DF_U_PRG_RI_STA_UNIQU0] DEFAULT ('') FOR [STA_UNIQU0],
	CONSTRAINT [DF_U_PRG_RI_STA_NRBOB0] DEFAULT (0) FOR [STA_NRBOB0],
	CONSTRAINT [DF_U_PRG_RI_STA_QTBOB0] DEFAULT (0) FOR [STA_QTBOB0]
go

UPDATE U_PRG_RI SET STA_CDCLI6 = SPACE(10)
UPDATE U_PRG_RI SET STA_DSCLI6 = SPACE(50)
UPDATE U_PRG_RI SET STA_CDCLI7 = SPACE(10)
UPDATE U_PRG_RI SET STA_DSCLI7 = SPACE(50)
UPDATE U_PRG_RI SET STA_CDCLI8 = SPACE(10)
UPDATE U_PRG_RI SET STA_DSCLI8 = SPACE(50)
UPDATE U_PRG_RI SET STA_CDCLI9 = SPACE(10)
UPDATE U_PRG_RI SET STA_DSCLI9 = SPACE(50)
UPDATE U_PRG_RI SET STA_CDCLI0 = SPACE(10)
UPDATE U_PRG_RI SET STA_DSCLI0 = SPACE(50)
UPDATE U_PRG_RI SET STA_UNIQU6 = 0
UPDATE U_PRG_RI SET STA_NRBOB6 = 0
UPDATE U_PRG_RI SET STA_QTBOB6 = 0
UPDATE U_PRG_RI SET STA_UNIQU7 = 0
UPDATE U_PRG_RI SET STA_NRBOB7 = 0
UPDATE U_PRG_RI SET STA_QTBOB7 = 0
UPDATE U_PRG_RI SET STA_UNIQU8 = 0
UPDATE U_PRG_RI SET STA_NRBOB8 = 0
UPDATE U_PRG_RI SET STA_QTBOB8 = 0
UPDATE U_PRG_RI SET STA_UNIQU9 = 0
UPDATE U_PRG_RI SET STA_NRBOB9 = 0
UPDATE U_PRG_RI SET STA_QTBOB9 = 0
UPDATE U_PRG_RI SET STA_UNIQU0 = 0
UPDATE U_PRG_RI SET STA_NRBOB0 = 0
UPDATE U_PRG_RI SET STA_QTBOB0 = 0

