
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_IVA_CO] ADD 
	 COR_IMIVA1 [numeric](15, 2) NULL ,
	 COR_IVIVA1 [numeric](15, 2) NULL ,
	 COR_IMIVA2 [numeric](15, 2) NULL ,
	 COR_IVIVA2 [numeric](15, 2) NULL ,
	 COR_IMIVA3 [numeric](15, 2) NULL ,
	 COR_IVIVA3 [numeric](15, 2) NULL ,
	 COR_IMIVA4 [numeric](15, 2) NULL ,
	 COR_IVIVA4 [numeric](15, 2) NULL ,
	 COR_IMIVA5 [numeric](15, 2) NULL ,
	 COR_IVIVA5 [numeric](15, 2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_IVA_CO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_IVA_CO_COR_IMIVA1] DEFAULT (0) FOR [COR_IMIVA1],
	CONSTRAINT [DF_U_IVA_CO_COR_IVIVA1] DEFAULT (0) FOR [COR_IVIVA1],
	CONSTRAINT [DF_U_IVA_CO_COR_IMIVA2] DEFAULT (0) FOR [COR_IMIVA2],
	CONSTRAINT [DF_U_IVA_CO_COR_IVIVA2] DEFAULT (0) FOR [COR_IVIVA2],
	CONSTRAINT [DF_U_IVA_CO_COR_IMIVA3] DEFAULT (0) FOR [COR_IMIVA3],
	CONSTRAINT [DF_U_IVA_CO_COR_IVIVA3] DEFAULT (0) FOR [COR_IVIVA3],
	CONSTRAINT [DF_U_IVA_CO_COR_IMIVA4] DEFAULT (0) FOR [COR_IMIVA4],
	CONSTRAINT [DF_U_IVA_CO_COR_IVIVA4] DEFAULT (0) FOR [COR_IVIVA4],
	CONSTRAINT [DF_U_IVA_CO_COR_IMIVA5] DEFAULT (0) FOR [COR_IMIVA5],
	CONSTRAINT [DF_U_IVA_CO_COR_IVIVA5] DEFAULT (0) FOR [COR_IVIVA5]
go
