ALTER TABLE [dbo].[U_IVF_CL] ADD 
	[IVF_DEDUCIBILE] [bit] NULL
go
ALTER TABLE [dbo].[U_IVF_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_IVF_CL_IVF_DEDUCIBILE] DEFAULT (0) FOR [IVF_DEDUCIBILE]
go

UPDATE U_IVF_CL SET IVF_DEDUCIBILE = 0
