

ALTER TABLE [DBO].[U_AZI_PA] ADD 
	AZI_IVAXCA BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_IVAXCA] DEFAULT (0) FOR [AZI_IVAXCA]
GO

UPDATE U_AZI_PA SET AZI_IVAXCA = 0
