
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	 ART_PRZETI [numeric](17, 6) NULL ,
	 ART_PRZCOP [numeric](17, 6) NULL ,
	 ART_SC1 [numeric](6, 2) NULL ,
	 ART_SC2 [numeric](6, 2) NULL ,
	 ART_SC3 [numeric](6, 2) NULL ,
	 ART_GRUEDI varchar(5) COLLATE Latin1_General_CI_AS NULL ,
	 ART_EDITOR varchar(5) COLLATE Latin1_General_CI_AS NULL ,
	 ART_COLLAN varchar(3) COLLATE Latin1_General_CI_AS NULL ,
	 ART_CATAGO varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	 ART_AUTORE varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	 ART_ARGOME varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	 ART_PROSPE [bit] NULL ,
	 ART_QTASPE [numeric](11, 3) NULL ,
	 ART_PRESPE [numeric](17, 6) NULL ,
	 ART_CDISBN varchar(50) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_PRZETI] DEFAULT (0) FOR [ART_PRZETI],
	CONSTRAINT [DF_U_ART_PR_ART_PRZCOP] DEFAULT (0) FOR [ART_PRZCOP],
	CONSTRAINT [DF_U_ART_PR_ART_SC1] DEFAULT (0) FOR [ART_SC1],
	CONSTRAINT [DF_U_ART_PR_ART_SC2] DEFAULT (0) FOR [ART_SC2],
	CONSTRAINT [DF_U_ART_PR_ART_SC3] DEFAULT (0) FOR [ART_SC3],
	CONSTRAINT [DF_U_ART_PR_ART_GRUEDI] DEFAULT ('') FOR [ART_GRUEDI],
	CONSTRAINT [DF_U_ART_PR_ART_EDITOR] DEFAULT ('') FOR [ART_EDITOR],
	CONSTRAINT [DF_U_ART_PR_ART_COLLAN] DEFAULT ('') FOR [ART_COLLAN],
	CONSTRAINT [DF_U_ART_PR_ART_CATAGO] DEFAULT ('') FOR [ART_CATAGO],
	CONSTRAINT [DF_U_ART_PR_ART_AUTORE] DEFAULT ('') FOR [ART_AUTORE],
	CONSTRAINT [DF_U_ART_PR_ART_ARGOME] DEFAULT ('') FOR [ART_ARGOME],
	CONSTRAINT [DF_U_ART_PR_ART_PROSPE] DEFAULT (0) FOR [ART_PROSPE],
	CONSTRAINT [DF_U_ART_PR_ART_QTASPE] DEFAULT (0) FOR [ART_QTASPE],
	CONSTRAINT [DF_U_ART_PR_ART_PRESPE] DEFAULT (0) FOR [ART_PRESPE],
	CONSTRAINT [DF_U_ART_PR_ART_CDISBN] DEFAULT ('') FOR [ART_CDISBN]
go
