
ALTER TABLE [dbo].[U_FOR_PR] ADD 
	[FPR_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_FOR_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FOR_PR_FPR_FLGTRA] DEFAULT (0) FOR [FPR_FLGTRA]
go
UPDATE U_FOR_PR SET FPR_FLGTRA = 0


ALTER TABLE [dbo].[U_ALT_DA] ADD 
	[ALT_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_ALT_DA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ALT_DA_ALT_FLGTRA] DEFAULT (0) FOR [ALT_FLGTRA]
go
UPDATE U_ALT_DA SET ALT_FLGTRA = 0


ALTER TABLE [dbo].[U_MAG_GG] ADD 
	[MAG_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_GG_MAG_FLGTRA] DEFAULT (0) FOR [MAG_FLGTRA]
go
UPDATE U_MAG_GG SET MAG_FLGTRA = 0


ALTER TABLE [dbo].[U_MAG_DA] ADD 
	[MAG_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_MAG_DA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_DA_MAG_FLGTRA] DEFAULT (0) FOR [MAG_FLGTRA]
go
UPDATE U_MAG_DA SET MAG_FLGTRA = 0


ALTER TABLE [dbo].[U_MAG_AN] ADD 
	[MAG_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_MAG_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_AN_MAG_FLGTRA] DEFAULT (0) FOR [MAG_FLGTRA]
go
UPDATE U_MAG_AN SET MAG_FLGTRA = 0


ALTER TABLE [dbo].[U_MAG_PR] ADD 
	[MAG_FLGTRA] [bit] NULL
go
ALTER TABLE [dbo].[U_MAG_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_PR_MAG_FLGTRA] DEFAULT (0) FOR [MAG_FLGTRA]
go
UPDATE U_MAG_PR SET MAG_FLGTRA = 0


