
-- AGGIUNTA CAMPI "Validità Dal/Al" IN TABELLA CONTRATTI VETTORI

ALTER TABLE [DBO].[U_CON_VE] ADD 
       CON_VALIDA varchar(10) COLLATE Latin1_General_CI_AS NOT NULL DEFAULT (''),
       CON_VALIAL varchar(10) COLLATE Latin1_General_CI_AS NOT NULL DEFAULT ('')
GO

-- AGGIORNAMENTO CAMPI "Validità Dal/Al" IN TABELLA CONTRATTI VETTORI PER CONTRATTI PREESISTENTI
UPDATE U_CON_VE SET CON_VALIDA = '2000/01/01'
UPDATE U_CON_VE SET CON_VALIAL = '2999/12/31'