/***************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
***************************************************************/

ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_LDTMST numeric(3,0) NULL,
	ART_LDTM1 numeric(3,0) NULL,
	ART_LDTM2 numeric(3,0) NULL,
	ART_LDTM3 numeric(3,0) NULL,
	ART_LDTM4 numeric(3,0) NULL,
	ART_LDTM5 numeric(3,0) NULL
go

ALTER TABLE [dbo].[U_ART_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_AN_ART_LDTMST] DEFAULT ('') FOR [ART_LDTMST],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM1] DEFAULT ('') FOR [ART_LDTM1],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM2] DEFAULT ('') FOR [ART_LDTM2],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM3] DEFAULT ('') FOR [ART_LDTM3],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM4] DEFAULT ('') FOR [ART_LDTM4],
	CONSTRAINT [DF_U_ART_AN_ART_LDTM5] DEFAULT ('') FOR [ART_LDTM5]
go


UPDATE U_ART_AN SET ART_LDTMST = 0
UPDATE U_ART_AN SET ART_LDTM1 = 0
UPDATE U_ART_AN SET ART_LDTM2 = 0
UPDATE U_ART_AN SET ART_LDTM3 = 0
UPDATE U_ART_AN SET ART_LDTM4 = 0
UPDATE U_ART_AN SET ART_LDTM5 = 0
