
/*         
***************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
***************************************************************
*/
ALTER TABLE [dbo].[U_PRV_AN] ADD 
	 PRV_NPART numeric(10,0)  NULL,
	 PRV_TIPFAT varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 PRV_TMOV varchar(1) COLLATE Latin1_General_CI_AS NULL,
	 PRV_CODPAG varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 PRV_DESPAG varchar(30) COLLATE Latin1_General_CI_AS NULL,
	 PRV_DTSCAD varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 PRV_LIQUID varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 PRV_ANOMAX varchar(3) COLLATE Latin1_General_CI_AS NULL,	 
	 PRV_DTLIQU varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 PRV_STORIC varchar(1) COLLATE Latin1_General_CI_AS NULL,
	 PRV_MESE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	 PRV_NONMAT numeric(17,3)  NULL,
	 PRV_MATURA numeric(17,3)  NULL,
	 PRV_TOTLIQ numeric(17,3)  NULL,
	 PRV_PNONMA numeric(17,3)  NULL,
	 PRV_PMATUR numeric(17,3)  NULL,
	 PRV_PTOTLI numeric(17,3)  NULL

go
ALTER TABLE [dbo].[U_PRV_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRV_AN_PRV_NPART] DEFAULT (0) FOR [PRV_NPART],
	CONSTRAINT [DF_U_PRV_AN_PRV_TIPFAT] DEFAULT ('') FOR [PRV_TIPFAT],
	CONSTRAINT [DF_U_PRV_AN_PRV_TMOV] DEFAULT ('') FOR [PRV_TMOV],
	CONSTRAINT [DF_U_PRV_AN_PRV_CODPAG] DEFAULT ('') FOR [PRV_CODPAG],
	CONSTRAINT [DF_U_PRV_AN_PRV_DESPAG] DEFAULT ('') FOR [PRV_DESPAG],
	CONSTRAINT [DF_U_PRV_AN_PRV_DTSCAD] DEFAULT ('') FOR [PRV_DTSCAD],
	CONSTRAINT [DF_U_PRV_AN_PRV_LIQUID] DEFAULT ('') FOR [PRV_LIQUID],
	CONSTRAINT [DF_U_PRV_AN_PRV_ANOMAX] DEFAULT ('') FOR [PRV_ANOMAX],
	CONSTRAINT [DF_U_PRV_AN_PRV_DTLIQU] DEFAULT ('') FOR [PRV_DTLIQU],
	CONSTRAINT [DF_U_PRV_AN_PRV_STORIC] DEFAULT ('') FOR [PRV_STORIC]	
	CONSTRAINT [DF_U_PRV_AN_PRV_MESE] DEFAULT ('') FOR [PRV_MESE],	
	CONSTRAINT [DF_U_PRV_AN_PRV_NONMAT] DEFAULT (0) FOR [PRV_NONMAT],
	CONSTRAINT [DF_U_PRV_AN_PRV_MATURA] DEFAULT (0) FOR [PRV_MATURA],
	CONSTRAINT [DF_U_PRV_AN_PRV_TOTLIQ] DEFAULT (0) FOR [PRV_TOTLIQ],
	CONSTRAINT [DF_U_PRV_AN_PRV_PNONMA] DEFAULT (0) FOR [PRV_PNONMA],
	CONSTRAINT [DF_U_PRV_AN_PRV_PMATUR] DEFAULT (0) FOR [PRV_PMATUR],
	CONSTRAINT [DF_U_PRV_AN_PRV_PTOTLI] DEFAULT (0) FOR [PRV_PTOTLI]
go


UPDATE U_PRV_AN SET PRV_NPART = 0
UPDATE U_PRV_AN SET PRV_TIPFAT = SPACE(3)
UPDATE U_PRV_AN SET PRV_TMOV = SPACE(1)
UPDATE U_PRV_AN SET PRV_CODPAG = SPACE(3)
UPDATE U_PRV_AN SET PRV_DESPAG = SPACE(30)
UPDATE U_PRV_AN SET PRV_DTSCAD = SPACE(10)
UPDATE U_PRV_AN SET PRV_LIQUID = SPACE(2)
UPDATE U_PRV_AN SET PRV_ANOMAX = SPACE(3)
UPDATE U_PRV_AN SET PRV_DTLIQU = SPACE(10)
UPDATE U_PRV_AN SET PRV_STORIC = SPACE(1)
UPDATE U_PRV_AN SET PRV_STORIC = SPACE(2)
UPDATE U_PRV_AN SET PRV_NONMAT = 0
UPDATE U_PRV_AN SET PRV_MATURA = 0
UPDATE U_PRV_AN SET PRV_TOTLIQ = 0
UPDATE U_PRV_AN SET PRV_PNONMA = 0
UPDATE U_PRV_AN SET PRV_PMATUR = 0
UPDATE U_PRV_AN SET PRV_PTOTLI = 0