
-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MAG_GG] ALTER COLUMN MAG_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MAG_GG] ALTER COLUMN MAG_ANAART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MAG_MO] ALTER COLUMN MOV_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MAG_MO] ALTER COLUMN MOV_ANAART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_MAG_MO_NEW] ALTER COLUMN MOV_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_PR] ALTER COLUMN ART_CODPRI     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[U_ART_AN] ALTER COLUMN ART_CODPRI     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL


-- ALLARGAMENTO CAMPO CODICE ARTICOLO A 30 CARATTERI
ALTER TABLE [dbo].[VENDITE_DD] ALTER COLUMN ORD_CODART     VARCHAR(30) COLLATE Latin1_General_CI_AS NULL





