
--- AGGIUNTA NUOVI CAMPI IN TABELLA CARICHI DI PRODUZIONE PER GESTIONE BANCALI
ALTER TABLE [dbo].[U_LIC_AN] ADD
	LICENZA varchar(200) COLLATE Latin1_General_CI_AS NULL
go

-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_LIC_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_LIC_AN_LICENZA] DEFAULT ('') FOR [LICENZA]
go

UPDATE U_LIC_AN SET LICENZA = ''
