
/*
***		- Blocco registrazioni contabili : BLOCCA SOLO LE FATTURA DI ACQUISTO/VENDITA
*/

ALTER TABLE [DBO].[BLOCCAPN] ADD 
	BPN_FATCLFO  BIT NOT NULL CONSTRAINT [DF_BLOCCAPN_BPN_FATCLFO] DEFAULT (0)
GO


UPDATE BLOCCAPN SET BPN_FATCLFO = 0