/*
*** NUOVO CAMPO PER GESTIONE CRITICITA' CLIENTE
*/


ALTER TABLE [DBO].[U_ANA_CL] ADD 
	CLI_EPEC varchar(200) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_ANA_CL_CLI_EPEC] DEFAULT ('')
GO
