/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_ORD_DD] ADD 
	 ORD_FLGPRG numeric(1,0) NULL ,
	 ORD_FLGAVA numeric(1,0) NULL ,
	 ORD_NUMPRG varchar(06) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DATPRG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_SEIPRG varchar(07) COLLATE Latin1_General_CI_AS NULL,
	 ORD_SEFPRG varchar(07) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DAIPRG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DAFPRG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_NRBOBP numeric(6) NULL,
	 ORD_QUANTP numeric(11,2) NULL,
	 ORD_NRBOBF numeric(6) NULL,
	 ORD_QUANTF numeric(11,2) NULL,
	 ORD_NRBOBD numeric(6) NULL,
	 ORD_QUANTD numeric(11,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ORD_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORD_DD_ORD_FLGPRG] DEFAULT (0) FOR [ORD_FLGPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_FLGAVA] DEFAULT (0) FOR [ORD_FLGAVA],
	CONSTRAINT [DF_U_ORD_DD_ORD_NUMPRG] DEFAULT ('') FOR [ORD_NUMPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_DATPRG] DEFAULT ('') FOR [ORD_DATPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_SEIPRG] DEFAULT ('') FOR [ORD_SEIPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_SEFPRG] DEFAULT ('') FOR [ORD_SEFPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_DAIPRG] DEFAULT ('') FOR [ORD_DAIPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_DAFPRG] DEFAULT ('') FOR [ORD_DAFPRG],
	CONSTRAINT [DF_U_ORD_DD_ORD_NRBOBP] DEFAULT (0) FOR [ORD_NRBOBP],
	CONSTRAINT [DF_U_ORD_DD_ORD_QUANTP] DEFAULT (0) FOR [ORD_QUANTP],
	CONSTRAINT [DF_U_ORD_DD_ORD_NRBOBF] DEFAULT (0) FOR [ORD_NRBOBF],
	CONSTRAINT [DF_U_ORD_DD_ORD_QUANTF] DEFAULT (0) FOR [ORD_QUANTF],
	CONSTRAINT [DF_U_ORD_DD_ORD_NRBOBD] DEFAULT (0) FOR [ORD_NRBOBD],
	CONSTRAINT [DF_U_ORD_DD_ORD_QUANTD] DEFAULT (0) FOR [ORD_QUANTD]
go

UPDATE U_ORD_DD SET ORD_FLGPRG = 1
UPDATE U_ORD_DD SET ORD_FLGAVA = 1
UPDATE U_ORD_DD SET ORD_NUMPRG = SPACE(06)
UPDATE U_ORD_DD SET ORD_DATPRG = SPACE(10)
UPDATE U_ORD_DD SET ORD_SEIPRG = SPACE(07)
UPDATE U_ORD_DD SET ORD_SEFPRG = SPACE(07)
UPDATE U_ORD_DD SET ORD_DAIPRG = SPACE(10)
UPDATE U_ORD_DD SET ORD_DAFPRG = SPACE(10)
UPDATE U_ORD_DD SET ORD_NRBOBP = 0
UPDATE U_ORD_DD SET ORD_QUANTP = 0
UPDATE U_ORD_DD SET ORD_NRBOBF = 0
UPDATE U_ORD_DD SET ORD_QUANTF = 0
UPDATE U_ORD_DD SET ORD_NRBOBD = 0
UPDATE U_ORD_DD SET ORD_QUANTD = 0
