

ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_OMACIO2 bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_OMACIO2] DEFAULT (0),
	AZI_LISBANCO bit NOT NULL CONSTRAINT [DF_U_AZI_PB_AZI_LISBANCO] DEFAULT (0)
GO

-- SE AZIENDA PRODUZIONE DISPOSITIVI MEDICALI, SETTO A 1 (TRUE)
UPDATE U_AZI_PB SET AZI_OMACIO2 = CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 1 ELSE 0 END
