
/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[U_ART_PR] ADD 
	 	 ART_CODITG1 varchar (16) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DESCTG1 varchar (50) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_CLITAG1 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DSCLIT1 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 
	 	 ART_CODITG2 varchar (16) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DESCTG2 varchar (50) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_CLITAG2 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DSCLIT2 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 
	 	 ART_CODITG3 varchar (16) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DESCTG3 varchar (50) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_CLITAG3 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DSCLIT3 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 
	 	 ART_CODITG4 varchar (16) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DESCTG4 varchar (50) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_CLITAG4 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DSCLIT4 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 
	 	 ART_CODITG5 varchar (16) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DESCTG5 varchar (50) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_CLITAG5 varchar (10) COLLATE Latin1_General_CI_AS NULL,
	 	 ART_DSCLIT5 varchar (10) COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_CODITG1] DEFAULT ('') FOR [ART_CODITG1],
	CONSTRAINT [DF_U_ART_PR_ART_DESCTG1] DEFAULT ('') FOR [ART_DESCTG1],
	CONSTRAINT [DF_U_ART_PR_ART_CLITAG1] DEFAULT ('') FOR [ART_CLITAG1],
	CONSTRAINT [DF_U_ART_PR_ART_DSCLIT1] DEFAULT ('') FOR [ART_DSCLIT1],
	
	CONSTRAINT [DF_U_ART_PR_ART_CODITG2] DEFAULT ('') FOR [ART_CODITG2],
	CONSTRAINT [DF_U_ART_PR_ART_DESCTG2] DEFAULT ('') FOR [ART_DESCTG2],
	CONSTRAINT [DF_U_ART_PR_ART_CLITAG2] DEFAULT ('') FOR [ART_CLITAG2],
	CONSTRAINT [DF_U_ART_PR_ART_DSCLIT2] DEFAULT ('') FOR [ART_DSCLIT2],
	
	CONSTRAINT [DF_U_ART_PR_ART_CODITG3] DEFAULT ('') FOR [ART_CODITG3],
	CONSTRAINT [DF_U_ART_PR_ART_DESCTG3] DEFAULT ('') FOR [ART_DESCTG3],
	CONSTRAINT [DF_U_ART_PR_ART_CLITAG3] DEFAULT ('') FOR [ART_CLITAG3],
	CONSTRAINT [DF_U_ART_PR_ART_DSCLIT3] DEFAULT ('') FOR [ART_DSCLIT3],
	
	CONSTRAINT [DF_U_ART_PR_ART_CODITG4] DEFAULT ('') FOR [ART_CODITG4],
	CONSTRAINT [DF_U_ART_PR_ART_DESCTG4] DEFAULT ('') FOR [ART_DESCTG4],
	CONSTRAINT [DF_U_ART_PR_ART_CLITAG4] DEFAULT ('') FOR [ART_CLITAG4],
	CONSTRAINT [DF_U_ART_PR_ART_DSCLIT4] DEFAULT ('') FOR [ART_DSCLIT4],
	
	CONSTRAINT [DF_U_ART_PR_ART_CODITG5] DEFAULT ('') FOR [ART_CODITG5],
	CONSTRAINT [DF_U_ART_PR_ART_DESCTG5] DEFAULT ('') FOR [ART_DESCTG5],
	CONSTRAINT [DF_U_ART_PR_ART_CLITAG5] DEFAULT ('') FOR [ART_CLITAG5],
	CONSTRAINT [DF_U_ART_PR_ART_DSCLIT5] DEFAULT ('') FOR [ART_DSCLIT5]
	
go

UPDATE U_ART_PR SET ART_CODITG1 	= ''
UPDATE U_ART_PR SET ART_DESCTG1 	= ''
UPDATE U_ART_PR SET ART_CLITAG1 	= ''
UPDATE U_ART_PR SET ART_DSCLIT1 	= ''

UPDATE U_ART_PR SET ART_CODITG2 	= ''
UPDATE U_ART_PR SET ART_DESCTG2 	= ''
UPDATE U_ART_PR SET ART_CLITAG2 	= ''
UPDATE U_ART_PR SET ART_DSCLIT2 	= ''

UPDATE U_ART_PR SET ART_CODITG3 	= ''
UPDATE U_ART_PR SET ART_DESCTG3 	= ''
UPDATE U_ART_PR SET ART_CLITAG3 	= ''
UPDATE U_ART_PR SET ART_DSCLIT3 	= ''

UPDATE U_ART_PR SET ART_CODITG4 	= ''
UPDATE U_ART_PR SET ART_DESCTG4 	= ''
UPDATE U_ART_PR SET ART_CLITAG4 	= ''
UPDATE U_ART_PR SET ART_DSCLIT4 	= ''

UPDATE U_ART_PR SET ART_CODITG5 	= ''
UPDATE U_ART_PR SET ART_DESCTG5 	= ''
UPDATE U_ART_PR SET ART_CLITAG5 	= ''
UPDATE U_ART_PR SET ART_DSCLIT5 	= ''