
 
ALTER TABLE [DBO].[U_AZI_PB] ADD 
	AZI_NOLOCCF  BIT NULL,
	AZI_NOLOCCM  BIT NULL
GO

ALTER TABLE [DBO].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_NOLOCCF] DEFAULT (0) FOR [AZI_NOLOCCF],
	CONSTRAINT [DF_U_AZI_PB_AZI_NOLOCCM] DEFAULT (0) FOR [AZI_NOLOCCM]
GO

UPDATE U_AZI_PB SET AZI_NOLOCCF  = 0
UPDATE U_AZI_PB SET AZI_NOLOCCM  = 0