
ALTER TABLE [dbo].[U_ART_AN] ADD 
	ART_SPEPOL numeric (5,0) NOT NULL DEFAULT (0)
go


--UPDATE U_ART_AN SET ART_SPEPOL = COALESCE(
--	(SELECT ART_SPESSO FROM U_ART_PR WHERE ART_CODPRI = (SELECT TOP 1 DIS_CODART FROM U_DIS_DD WHERE DIS_CODART LIKE '%LDPE%' AND DAGGANCIO IN (SELECT DAGGANCIO FROM U_DIS_DD WHERE DIS_GRUPPO = U_ART_AN.ART_CODPRI))),0)