/* 
********************************************************************
INSERIMENTO NUOVO CAMPO PER PROGRAMMA DI PRODUZIONE:
	- Tipo programma (per poter gestire più tipi di programmi)
********************************************************************
*/

if exists(select * from sys.columns where name = 'TIPO' and object_id = object_id(N'[dbo].[PRODUZIONE]'))
BEGIN
	ALTER TABLE [dbo].[PRODUZIONE] DROP CONSTRAINT DF_PRODUZIONE_TIPO
	ALTER TABLE [dbo].[PRODUZIONE] DROP COLUMN TIPO
END


ALTER TABLE [dbo].[PRODUZIONE] ADD 
	[TIPO] [varchar] (3) COLLATE Latin1_General_CI_AS NULL
go

ALTER TABLE [dbo].[PRODUZIONE] WITH NOCHECK ADD 
	CONSTRAINT [DF_PRODUZIONE_TIPO] DEFAULT ('') FOR [TIPO]
go


-- AGGIORNAMENTO IDENTIFICATORE TIPO DI PRODUZIONE PER PRODUZIONE STANDARD (ES. IMPRESIND)
UPDATE PARA SET DESIVA = 'STD' WHERE CODICE = 'FALPRODUZ'

-- AGGIORNAMENTO IDENTIFICATORE TIPO DI PRODUZIONE PER PRODUZIONE PANNELLI TRUCIOLARI E DADI PRESSATI (ES. XILOPAN)
UPDATE PARA SET DESIVA = 'PPT' WHERE CODICE = 'FALLEVIGA'
UPDATE PARA SET DESIVA = 'PPT' WHERE CODICE = 'FALNOBILI'
UPDATE PARA SET DESIVA = 'PPT' WHERE CODICE = 'FALPRESSA'
UPDATE PARA SET DESIVA = 'DAD' WHERE CODICE = 'FALPRSDAD'

-- AGGIORNAMENTO NUOVO CAMPO "TIPO PROGRAMMA" IN BASE ALL'IDENTIFICATORE DELLE FASI DI LAVORAZIONE
UPDATE PRODUZIONE SET TIPO = (SELECT DESIVA FROM PARA WHERE CODICE = 'FAL' + (SELECT TOP 1 FASELA FROM PROD_AVANZA WHERE IDPRG = PRODUZIONE.IDPRG))
