
ALTER TABLE [DBO].[PARAMETRI_SCHEDULER] ADD 
	SOSPENDIALL  BIT NULL,
	SOSPENDIORD  BIT NULL,
	SOSPENDIORF  BIT NULL,
	SOSPENDICHK1  BIT NULL,
	SOSPENDICHK2  BIT NULL
GO

ALTER TABLE [DBO].[PARAMETRI_SCHEDULER] WITH NOCHECK ADD 
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SOSPENDIALL] DEFAULT (0) FOR [SOSPENDIALL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SOSPENDIORD] DEFAULT (0) FOR [SOSPENDIORD],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SOSPENDIORF] DEFAULT (0) FOR [SOSPENDIORF],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SOSPENDICHK1] DEFAULT (0) FOR [SOSPENDICHK1],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SOSPENDICHK2] DEFAULT (0) FOR [SOSPENDICHK2]
GO

UPDATE PARAMETRI_SCHEDULER SET SOSPENDIALL  = 0
UPDATE PARAMETRI_SCHEDULER SET SOSPENDIORD  = 0
UPDATE PARAMETRI_SCHEDULER SET SOSPENDIORF  = 0
UPDATE PARAMETRI_SCHEDULER SET SOSPENDICHK1  = 0
UPDATE PARAMETRI_SCHEDULER SET SOSPENDICHK2  = 0