/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/
ALTER TABLE [dbo].[FATTURABILE_X] ADD 
	 ORD_NUMORC varchar(20) COLLATE Latin1_General_CI_AS NULL,
	 ORD_DATORC varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_IDSDI varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_CUP varchar(15) COLLATE Latin1_General_CI_AS NULL,
	 ORD_CIG varchar(10) COLLATE Latin1_General_CI_AS NULL,
	 ORD_RIFAMMFE varchar(150) COLLATE Latin1_General_CI_AS NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)

ALTER TABLE [dbo].[FATTURABILE_X] WITH NOCHECK ADD 

	CONSTRAINT [DF_FATTURABILE_X_ORD_NUMORC] DEFAULT ('') FOR [ORD_NUMORC],
	CONSTRAINT [DF_FATTURABILE_X_ORD_DATORC] DEFAULT ('') FOR [ORD_DATORC],
	CONSTRAINT [DF_FATTURABILE_X_ORD_IDSDI] DEFAULT ('') FOR [ORD_IDSDI],
	CONSTRAINT [DF_FATTURABILE_X_ORD_CUP] DEFAULT ('') FOR [ORD_CUP],
	CONSTRAINT [DF_FATTURABILE_X_ORD_CIG] DEFAULT ('') FOR [ORD_CIG],
	CONSTRAINT [DF_FATTURABILE_X_ORD_RIFAMMFE] DEFAULT ('') FOR [ORD_RIFAMMFE]

go

UPDATE FATTURABILE_X SET ORD_NUMORC = ''
UPDATE FATTURABILE_X SET ORD_DATORC = ''
UPDATE FATTURABILE_X SET ORD_IDSDI = ''
UPDATE FATTURABILE_X SET ORD_CUP = ''
UPDATE FATTURABILE_X SET ORD_CIG = ''
UPDATE FATTURABILE_X SET ORD_RIFAMMFE = ''