ALTER TABLE [dbo].[U_PRD_D4] ADD 
 	 PR4_FLGVIEW BIT NULL,
 	 PR4_FLGMULTI BIT NULL,
 	 PR4_NUMSEZRAGG NUMERIC(5,0) NULL
go
-- CONSTRAINT e forzature di default 
ALTER TABLE [dbo].[U_PRD_D4] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D4_PR4_FLGVIEW] DEFAULT (0) FOR [PR4_FLGVIEW],
	CONSTRAINT [DF_U_PRD_D4_PR4_FLGMULTI] DEFAULT (0) FOR [PR4_FLGMULTI],
	CONSTRAINT [DF_U_PRD_D4_PR4_NUMSEZRAGG] DEFAULT (0) FOR [PR4_NUMSEZRAGG]
go

UPDATE U_PRD_D4 SET PR4_FLGVIEW = 0
UPDATE U_PRD_D4 SET PR4_FLGMULTI = 0
UPDATE U_PRD_D4 SET PR4_NUMSEZRAGG = 0




