ALTER TABLE [dbo].[U_MAG_DA] ADD 
	 MAG_FLGCEL [bit] NULL,
	 MAG_SERBOL varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MAG_SERNUM varchar(3) COLLATE Latin1_General_CI_AS NULL,
	 MAG_NUMEDA numeric(9) NULL,
	 MAG_NUMEAL numeric(9) NULL,
	 MAG_AAPROD numeric(4) NULL,
	 MAG_CBFISC varchar(50) COLLATE Latin1_General_CI_AS NULL
go

-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_MAG_DA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_DA_MAG_FLGCEL] DEFAULT (0) FOR [MAG_FLGCEL],
	CONSTRAINT [DF_U_MAG_DA_MAG_SERBOL] DEFAULT ('') FOR [MAG_SERBOL],
	CONSTRAINT [DF_U_MAG_DA_MAG_SERNUM] DEFAULT ('') FOR [MAG_SERNUM],
	CONSTRAINT [DF_U_MAG_DA_MAG_NUMEDA] DEFAULT ('') FOR [MAG_NUMEDA],
	CONSTRAINT [DF_U_MAG_DA_MAG_NUMEAL] DEFAULT ('') FOR [MAG_NUMEAL],
	CONSTRAINT [DF_U_MAG_DA_MAG_AAPROD] DEFAULT (0) FOR [MAG_AAPROD],
	CONSTRAINT [DF_U_MAG_DA_MAG_CBFISC] DEFAULT ('') FOR [MAG_CBFISC]
go

UPDATE U_MAG_DA SET MAG_FLGCEL = 0
UPDATE U_MAG_DA SET MAG_SERBOL = SPACE(03)
UPDATE U_MAG_DA SET MAG_SERNUM = SPACE(03)
UPDATE U_MAG_DA SET MAG_NUMEDA = 0
UPDATE U_MAG_DA SET MAG_NUMEAL = 0
UPDATE U_MAG_DA SET MAG_AAPROD = 0
UPDATE U_MAG_DA SET MAG_CBFISC = SPACE(50)
