/* 
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/    

ALTER TABLE [dbo].[MOV_CONT] ADD 
  MOV_RAGSOC varchar(100) COLLATE Latin1_General_CI_AS NULL,
  MOV_NAZIONE_COD_UNICO varchar(03) COLLATE Latin1_General_CI_AS NULL,
  MOV_INDIRIZZO_ESTERO varchar(100) COLLATE Latin1_General_CI_AS NULL,
  MOV_LOCALITA_ESTERA varchar(100) COLLATE Latin1_General_CI_AS NULL,
  MOV_CODICE_FISCALE varchar(25) COLLATE Latin1_General_CI_AS NULL,
  MOV_PIVA_ESTERA varchar(25) COLLATE Latin1_General_CI_AS NULL,
  MOV_IMP_BLACKLIST numeric (17,3) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[MOV_CONT] WITH NOCHECK ADD 
	CONSTRAINT [DF_MOV_CONT_MOV_RAGSOC] DEFAULT ('') FOR [MOV_RAGSOC],
	CONSTRAINT [DF_MOV_CONT_MOV_NAZIONE_COD_UNICO] DEFAULT ('') FOR [MOV_NAZIONE_COD_UNICO],
	CONSTRAINT [DF_MOV_CONT_MOV_INDIRIZZO_ESTERO] DEFAULT ('') FOR [MOV_INDIRIZZO_ESTERO],
	CONSTRAINT [DF_MOV_CONT_MOV_LOCALITA_ESTERA] DEFAULT ('') FOR [MOV_LOCALITA_ESTERA],
	CONSTRAINT [DF_MOV_CONT_MOV_CODICE_FISCALE] DEFAULT ('') FOR [MOV_CODICE_FISCALE],
	CONSTRAINT [DF_MOV_CONT_MOV_PIVA_ESTERA] DEFAULT ('') FOR [MOV_PIVA_ESTERA],
    CONSTRAINT [DF_MOV_CONT_MOV_IMP_BLACKLIST] DEFAULT ('0')   FOR [MOV_IMP_BLACKLIST]
go

UPDATE MOV_CONT SET MOV_RAGSOC = ''
UPDATE MOV_CONT SET MOV_NAZIONE_COD_UNICO = ''
UPDATE MOV_CONT SET MOV_INDIRIZZO_ESTERO = ''
UPDATE MOV_CONT SET MOV_LOCALITA_ESTERA = ''
UPDATE MOV_CONT SET MOV_CODICE_FISCALE = ''
UPDATE MOV_CONT SET MOV_PIVA_ESTERA = ''
UPDATE MOV_CONT SET MOV_IMP_BLACKLIST 	= 0