
 
ALTER TABLE [DBO].[U_ORF_DD] ADD 
	ORD_PRSPOT  BIT NULL
GO

ALTER TABLE [DBO].[U_ORF_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORF_DD_ORD_PRSPOT] DEFAULT (0) FOR [ORD_PRSPOT]
GO

UPDATE U_ORF_DD SET ORD_PRSPOT  = 0