/*
*/

ALTER TABLE [dbo].[U_AZI_PB] ADD 
	 AZI_CALSCOF bit NULL,
	 AZI_CALSCBO bit NULL,
	 AZI_CALSCFP bit NULL,
	 AZI_CALSCFT bit NULL,
	 AZI_CALSCOR bit NULL

go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AZI_PB] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOF] DEFAULT (0) FOR [AZI_CALSCOF],
	CONSTRAINT [DF_U_AZI_PB_AZI_CALSCBO] DEFAULT (0) FOR [AZI_CALSCBO],
	CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFP] DEFAULT (0) FOR [AZI_CALSCFP],
	CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFT] DEFAULT (0) FOR [AZI_CALSCFT],
	CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOR] DEFAULT (0) FOR [AZI_CALSCOR]
go


UPDATE U_AZI_PB SET AZI_CALSCOF = 0
UPDATE U_AZI_PB SET AZI_CALSCBO = 0
UPDATE U_AZI_PB SET AZI_CALSCFP = 0
UPDATE U_AZI_PB SET AZI_CALSCFT = 0
UPDATE U_AZI_PB SET AZI_CALSCOR = 0