ALTER TABLE [dbo].[U_FOR_AN] ADD 
  FOR_RECCAT numeric(1,0) NULL,
  FOR_RECCOG varchar(24) COLLATE Latin1_General_CI_AS NULL,
  FOR_RECNOM varchar(20) COLLATE Latin1_General_CI_AS NULL,  
  FOR_ESTNAZ varchar(3) COLLATE Latin1_General_CI_AS NULL,
  FOR_ESTNAS varchar(10) COLLATE Latin1_General_CI_AS NULL,
  FOR_PRONAS varchar(2) COLLATE Latin1_General_CI_AS NULL,
  FOR_ESTCOM varchar(40) COLLATE Latin1_General_CI_AS NULL,
  FOR_ESTDOM varchar(3) COLLATE Latin1_General_CI_AS NULL
go


ALTER TABLE [dbo].[U_FOR_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FOR_AN_FOR_RECCAT] DEFAULT (1) FOR [FOR_RECCAT],
	CONSTRAINT [DF_U_FOR_AN_FOR_RECCOG] DEFAULT ('') FOR [FOR_RECCOG],
	CONSTRAINT [DF_U_FOR_AN_FOR_RECNOM] DEFAULT ('') FOR [FOR_RECNOM],	
	CONSTRAINT [DF_U_FOR_AN_FOR_ESTNAZ] DEFAULT ('') FOR [FOR_ESTNAZ],
	CONSTRAINT [DF_U_FOR_AN_FOR_ESTNAS] DEFAULT ('') FOR [FOR_ESTNAS],
	CONSTRAINT [DF_U_FOR_AN_FOR_PRONAS] DEFAULT ('') FOR [FOR_PRONAS],
	CONSTRAINT [DF_U_FOR_AN_FOR_ESTCOM] DEFAULT ('') FOR [FOR_ESTCOM],
	CONSTRAINT [DF_U_FOR_AN_FOR_ESTDOM] DEFAULT ('') FOR [FOR_ESTDOM]
go

UPDATE U_FOR_AN SET FOR_RECCAT = 1 
UPDATE U_FOR_AN SET FOR_RECCOG = ''
UPDATE U_FOR_AN SET FOR_RECNOM = ''
UPDATE U_FOR_AN SET FOR_ESTNAZ = ''
UPDATE U_FOR_AN SET FOR_ESTNAS = ''
UPDATE U_FOR_AN SET FOR_PRONAS = ''
UPDATE U_FOR_AN SET FOR_ESTCOM = ''
UPDATE U_FOR_AN SET FOR_ESTDOM = ''


select for_reccog from u_for_an

