/*    
**************************************************************
COME INSERIRE UN NUOVO CAMPO IN UNA TABELLA
**************************************************************
*/

ALTER TABLE [dbo].[U_FOR_AN] ADD 
	 FOR_PERS01 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_EMAIL1 varchar(100) COLLATE Latin1_General_CI_AS NULL,
	 FOR_PERS02 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_EMAIL2 varchar(100) COLLATE Latin1_General_CI_AS NULL,
	 FOR_PERS03 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_EMAIL3 varchar(100) COLLATE Latin1_General_CI_AS NULL,
	 FOR_PERS04 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_EMAIL4 varchar(100) COLLATE Latin1_General_CI_AS NULL,
	 FOR_PERS05 varchar(50) COLLATE Latin1_General_CI_AS NULL,
	 FOR_EMAIL5 varchar(100) COLLATE Latin1_General_CI_AS NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_FOR_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FOR_AN_FOR_PERS01] DEFAULT ('') FOR [FOR_PERS01],
	CONSTRAINT [DF_U_FOR_AN_FOR_EMAIL1] DEFAULT ('') FOR [FOR_EMAIL1],
	CONSTRAINT [DF_U_FOR_AN_FOR_PERS02] DEFAULT ('') FOR [FOR_PERS02],
	CONSTRAINT [DF_U_FOR_AN_FOR_EMAIL2] DEFAULT ('') FOR [FOR_EMAIL2],
	CONSTRAINT [DF_U_FOR_AN_FOR_PERS03] DEFAULT ('') FOR [FOR_PERS03],
	CONSTRAINT [DF_U_FOR_AN_FOR_EMAIL3] DEFAULT ('') FOR [FOR_EMAIL3],
	CONSTRAINT [DF_U_FOR_AN_FOR_PERS04] DEFAULT ('') FOR [FOR_PERS04],
	CONSTRAINT [DF_U_FOR_AN_FOR_EMAIL4] DEFAULT ('') FOR [FOR_EMAIL4],
	CONSTRAINT [DF_U_FOR_AN_FOR_PERS05] DEFAULT ('') FOR [FOR_PERS05],
	CONSTRAINT [DF_U_FOR_AN_FOR_EMAIL5] DEFAULT ('') FOR [FOR_EMAIL5]

go

UPDATE U_FOR_AN SET FOR_PERS01 = ''
UPDATE U_FOR_AN SET FOR_EMAIL1 = ''
UPDATE U_FOR_AN SET FOR_PERS02 = ''
UPDATE U_FOR_AN SET FOR_EMAIL2 = ''
UPDATE U_FOR_AN SET FOR_PERS03 = ''
UPDATE U_FOR_AN SET FOR_EMAIL3 = ''
UPDATE U_FOR_AN SET FOR_PERS04 = ''
UPDATE U_FOR_AN SET FOR_EMAIL4 = ''
UPDATE U_FOR_AN SET FOR_PERS05 = ''
UPDATE U_FOR_AN SET FOR_EMAIL5 = ''
