
-- PERMETTE DI SETTARE LE FASI DI LAVORAZIONE IN MODO DA DIFFERENZIARLE, 
-- RENDENDOLE DISPONIBILI SOLO PER UNA DETERMINATA TIPOLOGIA DI PROGRAMMAZIONE DELLA PRODUZIONE:
--		- PARA.DESIVA = 'STD' = FASE DI LAVORAZIONE PER PROGRAMMAZIONE STANDARD
--		- PARA.DESIVA = 'PPT' = FASE DI LAVORAZIONE PER PROGRAMMAZIONE PANNELI TRUCIOLARI
--		- PARA.DESIVA = 'DAD' = FASE DI LAVORAZIONE PER PROGRAMMAZIONE DADI (SETTORE LEGNO TRUCIOLARE)

UPDATE PARA SET DESIVA = 'STD' WHERE CODICE = 'FALPRODUZ'

UPDATE PARA SET DESIVA = 'PPT' WHERE CODICE = 'FALPRESSA' OR CODICE = 'FALLEVIGA' OR CODICE = 'FALNOBILI'

UPDATE PARA SET DESIVA = 'DAD' WHERE CODICE = 'FALPRSDAD'

SELECT * FROM PARA WHERE CODICE LIKE 'FAL%' ORDER BY SUBSTRING(LIBERA,1,1),CODICE

