
-- ALLARGAMENTO CAMPO CODICE CLIENTE DIREZIONALE USATO PER LA GESTIONE DEGLI IMPIANTI (CCODSCHE) A 20 CARATTERI
ALTER TABLE [dbo].[U_CLI_AN] ALTER COLUMN CLI_CODDIR VARCHAR(20) COLLATE Latin1_General_CI_AS NULL

