
-- ALLARGAMENTO CAMPO CODICE MOV_DESMOV A254 CARATTERI
ALTER TABLE [dbo].[MOV_CONT] ALTER COLUMN MOV_DESMOV VARCHAR(254) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE MOV_DESMOV A254 CARATTERI
ALTER TABLE [dbo].[MOV_CONT] ALTER COLUMN MOV_DESMO1 VARCHAR(254) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE MOV_DESMOV A254 CARATTERI
ALTER TABLE [dbo].[INDICE] ALTER COLUMN MOV_DESMOV VARCHAR(254) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO CODICE MOV_DESMOV A254 CARATTERI
ALTER TABLE [dbo].[INDICE] ALTER COLUMN MOV_DESMO1 VARCHAR(254) COLLATE Latin1_General_CI_AS NULL