
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'ID_UTENTE')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[ID_UTENTE] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_ID_UTENTE] DEFAULT ('')
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[NOME] [varchar] (60) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_NOME] DEFAULT ('')
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'COGNOME')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[COGNOME] [varchar] (60) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_COGNOME] DEFAULT ('')
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'DATA')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[DATA] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_DATA] DEFAULT ('')
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'ATTIVO')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[ATTIVO] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_ATTIVO] DEFAULT ('')
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = 'UTENTI' AND COLUMN_NAME = 'DATA_SC')
BEGIN
	ALTER TABLE [dbo].[UTENTI] ADD 
		[DATA_SC] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_UTENTI_DATA_SC] DEFAULT ('')
END