

/****** Object:  Table [dbo].[AQ_SCHEDECALD]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AQ_SCHEDECALD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[AQ_SCHEDECALD]
GO  


CREATE TABLE [dbo].[AQ_SCHEDECALD](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_AQ_SCHEDECALD_id_unique] DEFAULT (newid()),
	[ID_PMKEY]        [varchar](10) NULL CONSTRAINT [DF_AQ_SCHEDECALD_ID_PMKEY] DEFAULT (''),            
	[CCODSCHE]        [varchar](20) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CCODSCHE] DEFAULT (''),
	[ID_CAL]          [varchar](5) NULL CONSTRAINT [DF_AQ_SCHEDECALD_ID_CAL] DEFAULT (''), 
	[CMODCAL]         [varchar](25) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CMODCAL] DEFAULT (''), 
	[CMATCAL]         [varchar](50) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CMATCAL] DEFAULT (''), 
	[CDITTACAL]       [varchar](50) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CDITTACAL] DEFAULT (''), 
	[CCODCLI]         [varchar](10) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CCODCLI] DEFAULT (''), 
	[CFLAGGARZ]       [bit] NULL,
	[CDAINACCES]      [varchar](10) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CDAINACCES] DEFAULT (''), 
	[CDAINGARNZ]      [varchar](10) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CDAINGARNZ] DEFAULT (''), 
	[CDAFIGARNZ]      [varchar](10) NULL CONSTRAINT [DF_AQ_SCHEDECALD_CDAFIGARNZ] DEFAULT ('')
) 

ALTER TABLE [dbo].[AQ_SCHEDECALD] WITH NOCHECK ADD 
	CONSTRAINT [PK_AQ_SCHEDECALD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


