if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BFO_CLAV_COMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[BFO_CLAV_COMP]
GO

CREATE TABLE [dbo].[BFO_CLAV_COMP] (
	id_unique uniqueidentifier ROWGUIDCOL NOT NULL DEFAULT (newid()),
	NUMBFO varchar(30) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_NUMBFO] DEFAULT (''),
	DATBFO varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_DATBFO] DEFAULT (''),
	CODFOR varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_CODFOR] DEFAULT (''),
	LEGAME varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_LEGAME] DEFAULT (''),
	IDPRG varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_IDPRG] DEFAULT (''),
	CODPRD varchar(30) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_CODPRD] DEFAULT (''),
	SYSPRD varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_SYSPRD] DEFAULT (''),
	CODART varchar(30) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_CODART] DEFAULT (''),
	QTASCA numeric(19,6) NOT NULL CONSTRAINT [DF_BFO_CLAV_COMP_QTASCA] DEFAULT (0)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BFO_CLAV_COMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_BFO_CLAV_COMP] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
