if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BUDENTRFOR]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[BUDENTRFOR]
GO
 
CREATE TABLE [dbo].[BUDENTRFOR] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	IDBUDENTRFOR varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	AAAAMM varchar(07) COLLATE Latin1_General_CI_AS NULL ,
	UNIMIS varchar(03) COLLATE Latin1_General_CI_AS NULL ,
	CSTCAT varchar(02) COLLATE Latin1_General_CI_AS NULL ,
	DSTCAT varchar(100) COLLATE Latin1_General_CI_AS NULL ,
	QUANTITA numeric(17,4) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUDENTRFOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_BUDENTRFOR] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BUDENTRFOR] WITH NOCHECK ADD 
	CONSTRAINT [DF_BUDENTRFOR_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_BUDENTRFOR_IDBUDENTRFOR] DEFAULT ('') FOR [IDBUDENTRFOR],
	CONSTRAINT [DF_BUDENTRFOR_AAAAMM] DEFAULT ('') FOR [AAAAMM],
	CONSTRAINT [DF_BUDENTRFOR_UNIMIS] DEFAULT ('') FOR [UNIMIS],
	CONSTRAINT [DF_BUDENTRFOR_CSTCAT] DEFAULT ('') FOR [CSTCAT],
	CONSTRAINT [DF_BUDENTRFOR_DSTCAT] DEFAULT ('') FOR [DSTCAT],
	CONSTRAINT [DF_BUDENTRFOR_QUANTITA] DEFAULT (0) FOR [QUANTITA]
GO

