if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BUDGET_CCOSTO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[BUDGET_CCOSTO]
GO
 
CREATE TABLE [dbo].[BUDGET_CCOSTO] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	CCOSTO varchar(13) COLLATE Latin1_General_CI_AS NULL ,
	ANNO varchar(4) COLLATE Latin1_General_CI_AS NULL ,
	MESE varchar(2) COLLATE Latin1_General_CI_AS NULL ,
	ORDINATO numeric(17,3) NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUDGET_CCOSTO] WITH NOCHECK ADD 
	CONSTRAINT [PK_BUDGET_CCOSTO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BUDGET_CCOSTO] WITH NOCHECK ADD 
	CONSTRAINT [DF_BUDGET_CCOSTO_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_BUDGET_CCOSTO_CCOSTO] DEFAULT ('') FOR [CCOSTO],
	CONSTRAINT [DF_BUDGET_CCOSTO_ANNO] DEFAULT ('') FOR [ANNO],
	CONSTRAINT [DF_BUDGET_CCOSTO_MESE] DEFAULT ('') FOR [MESE],
	CONSTRAINT [DF_BUDGET_CCOSTO_ORDINATO] DEFAULT (0) FOR [ORDINATO]

GO
