
/****** Object:  Table [dbo].[LOG_CONT]    Script Date: 31/12/2015 09:41:18 ******/
DROP TABLE [dbo].[LOG_CONT]
GO

/****** Object:  Table [dbo].[LOG_CONT]    Script Date: 31/12/2015 09:41:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LOG_CONT](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_LOG_CONT_id_unique]  DEFAULT (newid()),
	[LOG_PROGRA] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_PROGRA]  DEFAULT (''),
	[LOG_ARCHIV] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_ARCHIV]  DEFAULT (''),
	[LOG_TIPOPE] [varchar](3) NULL CONSTRAINT [DF_LOG_CONT_LOG_TIPOPE]  DEFAULT (''),
	[LOG_CODOPE] [varchar](20) NULL CONSTRAINT [DF_LOG_CONT_LOG_CODOPE]  DEFAULT (''),
	[LOG_NOMOPE] [varchar](50) NULL CONSTRAINT [DF_LOG_CONT_LOG_NOMOPE]  DEFAULT (''),
	[LOG_POSOPE] [varchar](50) NULL CONSTRAINT [DF_LOG_CONT_LOG_POSOPE]  DEFAULT (''),
	[LOG_CODCON] [varchar](13) NULL CONSTRAINT [DF_LOG_CONT_LOG_CODCON]  DEFAULT (''),
	[LOG_DESCON] [varchar](50) NULL CONSTRAINT [DF_LOG_CONT_LOG_DESCON]  DEFAULT (''),
	[LOG_NUMREG] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_NUMREG]  DEFAULT (''),
	[LOG_DATREG] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_DATREG]  DEFAULT (''),
	[LOG_NUMDOC] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_NUMDOC]  DEFAULT (''),
	[LOG_DATDOC] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_DATDOC]  DEFAULT (''),
	[LOG_VALDOC] [numeric](17, 3) NULL CONSTRAINT [DF_LOG_CONT_LOG_VALDOC]  DEFAULT (0),
	[LOG_DATOPE] [varchar](10) NULL CONSTRAINT [DF_LOG_CONT_LOG_DATOPE]  DEFAULT (''),
	[LOG_ORAOPE] [varchar](20) NULL CONSTRAINT [DF_LOG_CONT_LOG_ORAOPE]  DEFAULT (''),
 CONSTRAINT [PK_LOG_CONT] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


