SELECT * FROM U_MAG_MO WHERE MOV_DTREGI > '2006/03/31' ORDER BY MOV_DTREGI,MOV_ORAMOV
SELECT * FROM U_MAG_SA WHERE MAG_AAAAMM > '2006/03' ORDER BY MAG_DATSAL
DELETE FROM U_MAG_SA WHERE MAG_AAAAMM > '2006/04'
