DELETE FROM INDICE
DELETE FROM MOV_CONT
DELETE FROM PART_CLI
DELETE FROM PART_FOR
DELETE FROM MO_CONCA


SELECT * FROM INDICE
SELECT * FROM MOV_CONT
SELECT * FROM PART_CLI
SELECT * FROM PART_FOR
SELECT * FROM MO_CONCA