
DELETE FROM PARA WHERE CODICE LIKE 'CDC%'
DELETE FROM PARA WHERE CODICE LIKE 'AML%'
DELETE FROM PARA WHERE CODICE LIKE 'CTC%'
DELETE FROM PARA WHERE CODICE LIKE 'CMP%'
DELETE FROM PARA WHERE CODICE LIKE 'FIP%'
DELETE FROM PARA WHERE CODICE LIKE 'RGN%'
DELETE FROM PARA WHERE CODICE LIKE 'TCT%'

DELETE FROM CLIENTIC
DELETE FROM COMMESSA_DP
DELETE FROM COMMESSA_DC
DELETE FROM COMMESSA_TT
DELETE FROM TIMESHT
DELETE FROM FATTURABILE_R
DELETE FROM FATTURABILE_A
DELETE FROM FATTURABILE_P
DELETE FROM FATTURABILE_S
DELETE FROM FATTURABILE_X
DELETE FROM PIANIFIC_COMM
DELETE FROM TIPOORA
DELETE FROM DETTORA
DELETE FROM BUDGET_PREV
DELETE FROM BUDGET_CONS



DELETE FROM RISUMANA

DELETE FROM BUDGETPC
DELETE FROM AULA

DELETE FROM FATTURABILE





