if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CANDIDATI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[CANDIDATI]
GO


CREATE TABLE [CANDIDATI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_CANDIDATI_id_unique] DEFAULT (newid()),
	[CODICE] 	[varchar] (16) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_CODICE] DEFAULT ('') ,
	[IDNAZIONE] [varchar] (32) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_IDNAZIONE] DEFAULT (''),
	[IDTITOLO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_IDTITOLO] DEFAULT (''),
	[IDSTATOCIV] [varchar] (32) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_IDSTATOCIV] DEFAULT (''),
	[IDPOSMILIT] [varchar] (32) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_IDPOSMILIT] DEFAULT (''),
	[D_REGISTRAZ] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_D_REGISTRAZ] DEFAULT (''),
	[COGNOME] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_COGNOME] DEFAULT (''),
	[NOME] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_NOME] DEFAULT (''),
	[SESSO] [varchar] (1) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_SESSO] DEFAULT (''),
	[CODFISCALE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_CODFISCALE] DEFAULT (''),
	[PARTITAIVA] [varchar] (11) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_PARTITAIVA] DEFAULT (''),
	[LOCNASCITA] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_LOCNASCITA] DEFAULT (''),
	[D_NASCITA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_D_NASCITA] DEFAULT (''),
	[ETA] [numeric](3, 0) NULL CONSTRAINT [DF_CANDIDATI_ETA] DEFAULT (0),
	[LOCRESIDENZ] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_LOCRESIDENZ] DEFAULT (''),
	[INDRESIDENZ] [varchar] (100) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_INDRESIDENZ] DEFAULT (''),
	[CAPRESIDENZ] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_CAPRESIDENZ] DEFAULT (''),
	[FAXRES] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_FAXRES] DEFAULT (''),
	[LOCDOMICIL] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_LOCDOMICIL] DEFAULT (''),
	[INDDOMICIL] [varchar] (100) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_INDDOMICIL] DEFAULT (''),
	[CAPDOMICIL] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_CAPDOMICIL] DEFAULT (''),
	[TELDOMICIL] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_TELDOMICIL] DEFAULT (''),
	[FAXDOM] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_FAXDOM] DEFAULT (''),
	[TELFISSO] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_TELFISSO] DEFAULT (''),
	[TELMOBILE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_TELMOBILE] DEFAULT (''),
	[EMAIL] [varchar] (100) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_EMAIL] DEFAULT (''),
	[PASSWORD]    	[varchar] (30) COLLATE Latin1_General_CI_AS  NULL CONSTRAINT [DF_CANDIDATI_PASSWORD] DEFAULT ('') ,
	[UTENTEINS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_UTENTEINS] DEFAULT (''),
	[D_DATAINS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_D_DATAINS] DEFAULT (''),
	[UTENTEMOD] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_UTENTEMOD] DEFAULT (''),
	[D_DATAMOD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_CANDIDATI_D_DATAMOD] DEFAULT (''),
	[NOTE] 			[text]    COLLATE Latin1_General_CI_AS NULL  CONSTRAINT [DF_CANDIDATI_NOTE] DEFAULT ('') ,
	CONSTRAINT [PK_CANDIDATI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


