if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CASHFLOWFIN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CASHFLOWFIN]
GO

CREATE TABLE [dbo].[CASHFLOWFIN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_CASHFLOWFIN_id_unique] DEFAULT newid(),
	[IDRIGA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_IDRIGA] DEFAULT (''),
	[B_ATTIVA] BIT NOT NULL CONSTRAINT [DF_CASHFLOWFIN_B_ATTIVA] DEFAULT (0),
	[COSTO_RICAVO] varchar(1) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_COSTO_RICAVO] DEFAULT (''),
	[SEGNOXDIFF] varchar(1) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_SEGNOXDIFF] DEFAULT (''),
	[DESRIGA] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_DESRIGA] DEFAULT (''),
	[ANNORIF] varchar(4) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_ANNORIF] DEFAULT (''),
	[SEQUEN] numeric(10,0) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_SEQUEN] DEFAULT (0),
	[TIPOELAB] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_TIPOELAB] DEFAULT (''),
	[CAUS] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_CAUS] DEFAULT (''),
	[TIPOFORN] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_TIPOFORN] DEFAULT (''),
	[TIPOELAB2] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_TIPOELAB2] DEFAULT (''),
	[CAUS2] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CASHFLOWFIN_CAUS2] DEFAULT (''),
	[M01] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M01] DEFAULT (0),
	[M02] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M02] DEFAULT (0),
	[M03] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M03] DEFAULT (0),
	[M04] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M04] DEFAULT (0),
	[M05] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M05] DEFAULT (0),
	[M06] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M06] DEFAULT (0),
	[M07] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M07] DEFAULT (0),
	[M08] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M08] DEFAULT (0),
	[M09] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M09] DEFAULT (0),
	[M10] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M10] DEFAULT (0),
	[M11] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M11] DEFAULT (0),
	[M12] numeric(20,2) NOT NULL CONSTRAINT [DF_CASHFLOWFIN_M12] DEFAULT (0)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CASHFLOWFIN] WITH NOCHECK ADD 
	CONSTRAINT [PK_CASHFLOWFIN] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
