if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CEDOLINI_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CEDOLINI_DD]
GO
 
CREATE TABLE [dbo].[CEDOLINI_DD] (
	id_unique uniqueidentifier ROWGUIDCOL NOT NULL ,
	DAGGANCIO varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DAGGANCIO_DL varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_DESCLI varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	AAAA varchar(4) COLLATE Latin1_General_CI_AS NULL ,
	MM varchar(2) COLLATE Latin1_General_CI_AS NULL ,
	TIPO_ELAB varchar(1) COLLATE Latin1_General_CI_AS NULL ,
	NUM_CEDOLINI numeric(17,2) NULL ,
	NUM_CEDOLIN2 numeric(17,2) NULL ,
	TIPO_FATT varchar(1) COLLATE Latin1_General_CI_AS NULL ,
	Annotazioni text NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CEDOLINI_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_CEDOLINI_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CEDOLINI_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_CEDOLINI_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CEDOLINI_DD_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_CEDOLINI_DD_DAGGANCIO_DL] DEFAULT ('') FOR [DAGGANCIO_DL],
	CONSTRAINT [DF_CEDOLINI_DD_CED_CODCLI] DEFAULT ('') FOR [CED_CODCLI],
	CONSTRAINT [DF_CEDOLINI_DD_CED_DESCLI] DEFAULT ('') FOR [CED_DESCLI],
	CONSTRAINT [DF_CEDOLINI_DD_AAAA] DEFAULT ('') FOR [AAAA],
	CONSTRAINT [DF_CEDOLINI_DD_MM] DEFAULT ('') FOR [MM],
	CONSTRAINT [DF_CEDOLINI_DD_TIPO_ELAB] DEFAULT ('') FOR [TIPO_ELAB],
	CONSTRAINT [DF_CEDOLINI_DD_NUM_CEDOLINI] DEFAULT (0) FOR [NUM_CEDOLINI],
	CONSTRAINT [DF_CEDOLINI_DD_NUM_CEDOLIN2] DEFAULT (0) FOR [NUM_CEDOLIN2],
	CONSTRAINT [DF_CEDOLINI_DD_TIPO_FATT] DEFAULT ('') FOR [TIPO_FATT],
	CONSTRAINT [DF_CEDOLINI_DD_Annotazioni] DEFAULT ('') FOR [Annotazioni]
GO

