if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CEDOLINI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CEDOLINI]
GO
 
CREATE TABLE [dbo].[CEDOLINI] (
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL ,
	TAGGANCIO varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_DESCLI varchar(254) COLLATE Latin1_General_CI_AS NULL ,
	NOTE text COLLATE Latin1_General_CI_AS NULL ,
	UTENTEINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAINS varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	UTENTEMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAMOD varchar(8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CEDOLINI] WITH NOCHECK ADD 
	CONSTRAINT [PK_CEDOLINI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CEDOLINI] WITH NOCHECK ADD 
	CONSTRAINT [DF_CEDOLINI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CEDOLINI_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_CEDOLINI_CED_CODCLI] DEFAULT ('') FOR [CED_CODCLI],
	CONSTRAINT [DF_CEDOLINI_CED_DESCLI] DEFAULT ('') FOR [CED_DESCLI],
	CONSTRAINT [DF_CEDOLINI_NOTE] DEFAULT ('') FOR [NOTE],
	CONSTRAINT [DF_CEDOLINI_UTENTEINS] DEFAULT ('') FOR [UTENTEINS],
	CONSTRAINT [DF_CEDOLINI_DATAINS] DEFAULT ('') FOR [DATAINS],
	CONSTRAINT [DF_CEDOLINI_ORAINS] DEFAULT ('') FOR [ORAINS],
	CONSTRAINT [DF_CEDOLINI_UTENTEMOD] DEFAULT ('') FOR [UTENTEMOD],
	CONSTRAINT [DF_CEDOLINI_DATAMOD] DEFAULT ('') FOR [DATAMOD],
	CONSTRAINT [DF_CEDOLINI_ORAMOD] DEFAULT ('') FOR [ORAMOD]
GO

