if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CEDOLINI_DL]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CEDOLINI_DL]
GO
 
CREATE TABLE [dbo].[CEDOLINI_DL] (
	id_unique uniqueidentifier ROWGUIDCOL NOT NULL ,
	DAGGANCIO_DD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CED_NOMDIP varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CED_CODCON varchar(3) COLLATE Latin1_General_CI_AS NULL ,
	CED_TIPOCO varchar(25) COLLATE Latin1_General_CI_AS NULL ,
	Annotazioni text NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CEDOLINI_DL] WITH NOCHECK ADD 
	CONSTRAINT [PK_CEDOLINI_DL] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CEDOLINI_DL] WITH NOCHECK ADD 
	CONSTRAINT [DF_CEDOLINI_DL_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CEDOLINI_DL_DAGGANCIO_DD] DEFAULT ('') FOR [DAGGANCIO_DD],
	CONSTRAINT [DF_CEDOLINI_DL_CED_CODCLI] DEFAULT ('') FOR [CED_CODCLI],
	CONSTRAINT [DF_CEDOLINI_DL_CED_NOMDIP] DEFAULT ('') FOR [CED_NOMDIP],
	CONSTRAINT [DF_CEDOLINI_DL_CED_CODCON] DEFAULT ('') FOR [CED_CODCON],
	CONSTRAINT [DF_CEDOLINI_DL_CED_TIPOCO] DEFAULT ('') FOR [CED_TIPOCO],
	CONSTRAINT [DF_CEDOLINI_DL_Annotazioni] DEFAULT ('') FOR [Annotazioni]
GO

