if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHIUSURA_MAGAZZINO_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CHIUSURA_MAGAZZINO_DD]
GO
 
CREATE TABLE [dbo].[CHIUSURA_MAGAZZINO_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_CHIUSURA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_ARTICOLO] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI_TIPO_ARTICOLO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI] [varchar] (200) COLLATE Latin1_General_CI_AS NULL ,
	[CODMAG] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[DESMAG] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[UM_ACQ]     [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[GIACENZA]  [numeric] (19,6) NULL ,
	[VAL_ACQ]  [numeric] (19,6) NULL ,
	[VAL_VEN]  [numeric] (19,6) NULL ,
	[COSTO_PROD] [numeric] (19,6) NULL ,
	[COSTO_CMP] [numeric] (19,6) NULL ,
	[VALORE_CMP] [numeric] (19,6) NULL ,
	[COSTO_LIFO] [numeric] (19,6) NULL ,
	[VALORE_LIFO] [numeric] (19,6) NULL ,
	[COSTO_SCELTO] [numeric] (19,6) NULL ,
	[VALORE_SCELTO] [numeric] (19,6) NULL ,
	[UM_VEN]     [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[PREZZO_MEDIO_VENDITA] [numeric] (19,6) NULL ,
	[VALORE_VENDITA] [numeric] (19,6) NULL ,
	[MOM_CMP] [numeric] (19,6) NULL ,
	[MOM_LIFO] [numeric] (19,6) NULL 

) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHIUSURA_MAGAZZINO_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_CHIUSURA_MAGAZZINO_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHIUSURA_MAGAZZINO_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_ID_CHIUSURA] DEFAULT ('') FOR [ID_CHIUSURA],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_TIPO_ARTICOLO] DEFAULT ('') FOR [TIPO_ARTICOLO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_DESCRI_TIPO_ARTICOLO] DEFAULT ('') FOR [DESCRI_TIPO_ARTICOLO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_CODART] DEFAULT ('') FOR [CODART],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_DESCRI] DEFAULT ('') FOR [DESCRI],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_CODMAG] DEFAULT ('') FOR [CODMAG],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_DESMAG] DEFAULT ('') FOR [DESMAG],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_UM_ACQ] DEFAULT ('') FOR [UM_ACQ],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_GIACENZA] DEFAULT (0) FOR [GIACENZA],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VAL_ACQ] DEFAULT (0) FOR [VAL_ACQ],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VAL_VEN] DEFAULT (0) FOR [VAL_VEN],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_COSTO_SCELTO] DEFAULT (0) FOR [COSTO_SCELTO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VALORE_SCELTO] DEFAULT (0) FOR [VALORE_SCELTO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_COSTO_CMP] DEFAULT (0) FOR [COSTO_CMP],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VALORE_CMP] DEFAULT (0) FOR [VALORE_CMP],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_COSTO_LIFO] DEFAULT (0) FOR [COSTO_LIFO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VALORE_LIFO] DEFAULT (0) FOR [VALORE_LIFO],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_UM_VEN] DEFAULT ('') FOR [UM_VEN],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_PREZZO_MEDIO_VENDITA] DEFAULT (0) FOR [PREZZO_MEDIO_VENDITA],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_VALORE_VENDITA] DEFAULT (0) FOR [VALORE_VENDITA],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_MOM_CMP] DEFAULT (0) FOR [MOM_CMP],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_DD_MOM_LIFO] DEFAULT (0) FOR [MOM_LIFO]
GO

