if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHIUSURA_MAGAZZINO_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CHIUSURA_MAGAZZINO_TT]
GO
 
CREATE TABLE [dbo].[CHIUSURA_MAGAZZINO_TT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_CHIUSURA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_CHIUSURA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DTMOV_DAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DTMOV_AL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_VALORIZZAZIONE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHIUSURA_MAGAZZINO_TT] WITH NOCHECK ADD 
	CONSTRAINT [PK_CHIUSURA_MAGAZZINO_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHIUSURA_MAGAZZINO_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_TT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_TT_DATA_CHIUSURA] DEFAULT ('') FOR [DATA_CHIUSURA],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_TT_DTMOV_DAL] DEFAULT ('') FOR [DTMOV_DAL],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_TT_DTMOV_AL] DEFAULT ('') FOR [DTMOV_AL],
	CONSTRAINT [DF_CHIUSURA_MAGAZZINO_TT_TIPO_VALORIZZAZIONE] DEFAULT ('') FOR [TIPO_VALORIZZAZIONE]
GO

