if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COLLOQUI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COLLOQUI]
GO

CREATE TABLE [dbo].[COLLOQUI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[ID_COLLOQUIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDTCONTATT] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDTIOPL] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDTIPOCNTR] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[COMUNE] [varchar] (150) COLLATE Latin1_General_CI_AS NULL ,
	[D_DTCONTATT] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL ,
	[SINTESIESIT] [text] COLLATE Latin1_General_CI_AS NULL ,
	[QUALIFICLAV] [text] COLLATE Latin1_General_CI_AS NULL ,
	[RETRIBUZION] [text] COLLATE Latin1_General_CI_AS NULL ,
	[PROFILOPROF] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SPECIALIZZ] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SITUAZIONE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[DISPONTRASF] [text] COLLATE Latin1_General_CI_AS NULL ,
	[ANNOTAZIONI] [text] COLLATE Latin1_General_CI_AS NULL ,
	[DISPONDAL] [text] COLLATE Latin1_General_CI_AS NULL ,
	[RISULTATO] [text] COLLATE Latin1_General_CI_AS NULL ,
	[IMPRESVALUT] [text] COLLATE Latin1_General_CI_AS NULL ,
	[ANNOTRISER] [text] COLLATE Latin1_General_CI_AS NULL ,
	[AZIONIDAINT] [text] COLLATE Latin1_General_CI_AS NULL ,
	[PROPDAFORM] [text] COLLATE Latin1_General_CI_AS NULL ,
	[ALTREINDIC] [text] COLLATE Latin1_General_CI_AS NULL ,
	[ORDINE] [numeric](3, 0) NULL ,
	[RISCOLLOQUIO] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[RICHIESTASPEC] [text] COLLATE Latin1_General_CI_AS NULL ,
	[IDRISUMANA] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[RISUMANA] [varchar] (175) COLLATE Latin1_General_CI_AS NULL ,
	[DELTA_DISP] [numeric](3, 0) NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COLLOQUI] WITH NOCHECK ADD 
	CONSTRAINT [PK_COLLOQUI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COLLOQUI] WITH NOCHECK ADD 
	CONSTRAINT [DF_COLLOQUI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_COLLOQUI_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_COLLOQUI_ID_COLLOQUIO] DEFAULT ('') FOR [ID_COLLOQUIO],
	CONSTRAINT [DF_COLLOQUI_IDTCONTATT] DEFAULT ('') FOR [IDTCONTATT],
	CONSTRAINT [DF_COLLOQUI_IDTIOPL] DEFAULT ('') FOR [IDTIOPL],
	CONSTRAINT [DF_COLLOQUI_IDTIPOCNTR] DEFAULT ('') FOR [IDTIPOCNTR],
	CONSTRAINT [DF_COLLOQUI_COMUNE] DEFAULT ('') FOR [COMUNE],
	CONSTRAINT [DF_COLLOQUI_D_DTCONTATT] DEFAULT ('') FOR [D_DTCONTATT],
	CONSTRAINT [DF_COLLOQUI_SINTESIESIT] DEFAULT ('') FOR [SINTESIESIT],
	CONSTRAINT [DF_COLLOQUI_QUALIFICLAV] DEFAULT ('') FOR [QUALIFICLAV],
	CONSTRAINT [DF_COLLOQUI_RETRIBUZION] DEFAULT ('') FOR [RETRIBUZION],
	CONSTRAINT [DF_COLLOQUI_PROFILOPROF] DEFAULT ('') FOR [PROFILOPROF],
	CONSTRAINT [DF_COLLOQUI_SPECIALIZZ] DEFAULT ('') FOR [SPECIALIZZ],
	CONSTRAINT [DF_COLLOQUI_SITUAZIONE] DEFAULT ('') FOR [SITUAZIONE],
	CONSTRAINT [DF_COLLOQUI_DISPONTRASF] DEFAULT ('') FOR [DISPONTRASF],
	CONSTRAINT [DF_COLLOQUI_ANNOTAZIONI] DEFAULT ('') FOR [ANNOTAZIONI],
	CONSTRAINT [DF_COLLOQUI_DISPONDAL] DEFAULT ('') FOR [DISPONDAL],
	CONSTRAINT [DF_COLLOQUI_RISULTATO] DEFAULT ('') FOR [RISULTATO],
	CONSTRAINT [DF_COLLOQUI_IMPRESVALUT] DEFAULT ('') FOR [IMPRESVALUT],
	CONSTRAINT [DF_COLLOQUI_ANNOTRISER] DEFAULT ('') FOR [ANNOTRISER],
	CONSTRAINT [DF_COLLOQUI_AZIONIDAINT] DEFAULT ('') FOR [AZIONIDAINT],
	CONSTRAINT [DF_COLLOQUI_PROPDAFORM] DEFAULT ('') FOR [PROPDAFORM],
	CONSTRAINT [DF_COLLOQUI_ALTREINDIC] DEFAULT ('') FOR [ALTREINDIC],
	CONSTRAINT [DF_COLLOQUI_ORDINE] DEFAULT (0) FOR [ORDINE],
	CONSTRAINT [DF_COLLOQUI_RISCOLLOQUIO] DEFAULT ('') FOR [RISCOLLOQUIO],
	CONSTRAINT [DF_COLLOQUI_RICHIESTASPEC] DEFAULT ('') FOR [RICHIESTASPEC],
	CONSTRAINT [DF_COLLOQUI_IDRISUMANA] DEFAULT ('') FOR [IDRISUMANA],
	CONSTRAINT [DF_COLLOQUI_RISUMANA] DEFAULT ('') FOR [RISUMANA],
	CONSTRAINT [DF_COLLOQUI_DELTA_DISP] DEFAULT (0) FOR [DELTA_DISP]
GO

