if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COMPETENZE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMPETENZE]
GO

CREATE TABLE [dbo].[COMPETENZE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDCOMPETENZA] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[CODICEC] [varchar] (9) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRIZIONE] [varchar] (254) COLLATE Latin1_General_CI_AS NULL ,
	[LIVELLO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[ANNI] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[PERIODO] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[CERTIFIC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[NOTE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[CHECKC] [varchar] (1) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPETENZE] WITH NOCHECK ADD 
	CONSTRAINT [PK_COMPETENZE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COMPETENZE] WITH NOCHECK ADD 
	CONSTRAINT [DF_COMPETENZE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_COMPETENZE_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_COMPETENZE_IDCOMPETENZA] DEFAULT ('') FOR [IDCOMPETENZA],
	CONSTRAINT [DF_COMPETENZE_CODICEC] DEFAULT ('') FOR [CODICEC],
	CONSTRAINT [DF_COMPETENZE_DESCRIZIONE] DEFAULT ('') FOR [DESCRIZIONE],
	CONSTRAINT [DF_COMPETENZE_LIVELLO] DEFAULT ('') FOR [LIVELLO],
	CONSTRAINT [DF_COMPETENZE_ANNI] DEFAULT ('') FOR [ANNI],
	CONSTRAINT [DF_COMPETENZE_PERIODO] DEFAULT ('') FOR [PERIODO],
	CONSTRAINT [DF_COMPETENZE_CERTIFIC] DEFAULT ('') FOR [CERTIFIC],
	CONSTRAINT [DF_COMPETENZE_NOTE] DEFAULT ('') FOR [NOTE],
	CONSTRAINT [DF_COMPETENZE_CHECKC] DEFAULT ('') FOR [CHECKC]
GO

