SELECT 	DIS_GRUPPO AS CODART,
		ARTG.ART_DESCR AS DESCRI,
		ARTG.ART_BASADE AS BASE_ADESIVO,
		'KG' AS UM_ACQ,
		ARTG.ART_UMMAGA AS UM_VEN,
		DIS_CODART AS COD_COMPONENTE, 
		DIS_QTA AS QTA,
	    COALESCE((SELECT TOP 1 ORD_VALORE/ORD_QTAORD 	 
					FROM U_BFO_DD 
					WHERE ORD_CODART=DIS.DIS_CODART AND ORS_DATORD < '2012/12/31' 
					ORDER BY ORS_DATORD DESC ),0) AS COSTO_DA_ULTIMA_BOLLA_DI_CARICO ,
		COALESCE((SELECT AVG(MOV_VALACQ/MOV_QTAMOV) AS COSTO_MEDIO
				FROM U_MAG_MO
				WHERE MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31'
					AND MOV_ANAART=DIS.DIS_CODART 
					AND MOV_SEGNO='+'
					AND MOV_QTAMOV<>0
					AND MOV_VALACQ<>0),0) AS COSTO_MEDIO_MAGAZZINO,
		COALESCE(ART.ART_PRZCO1,0) AS COSTO_COMPONENTE_DA_ANAGRAFICA_ARTICOLI,
		ARTG.ART_PRZCO1 AS COSTO_DISTINTA_DA_ANAGRAFICA_ARTICOLI
	FROM U_DIS_DD AS DIS
	LEFT OUTER JOIN U_ART_PR AS ART
	ON DIS.DIS_CODART = ART.ART_CODPRI 
	INNER JOIN U_ART_PR AS ARTG
	ON DIS.DIS_GRUPPO = ARTG.ART_CODPRI 
	WHERE DIS.DIS_UM <>'NR' AND DIS.DIS_UM <>'ML' AND DIS.DIS_GRUPPO ='A 0025'




SELECT * FROM U_MAG_MO
WHERE MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31'
					AND MOV_SEGNO='+'
					AND MOV_QTAMOV<>0
					AND MOV_VALACQ<>0

