if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COMUNICAZIONI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMUNICAZIONI]
GO

CREATE TABLE [dbo].[COMUNICAZIONI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[IDCommessa] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[Codice] [varchar] (25) COLLATE Latin1_General_CI_AS NULL ,
	[D_Data] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[IDCOMMESSA_DC] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[CodAttivita] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[DesAttivita] [varchar] (254) COLLATE Latin1_General_CI_AS NULL ,
	[TipoSogg] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[CodSogg] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[DesSogg] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[DsTipSog] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[DATINI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATFIN] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[Anno] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[Mese] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[AAAAMM] [varchar] (7) COLLATE Latin1_General_CI_AS NULL ,
	[QtaGG] [numeric](17, 2) NULL ,
	[OreGG] [numeric](10, 2) NULL ,
	[UMcosto] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[UMricavo] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[Costo] [numeric](17, 6) NULL ,
	[Ricavo] [numeric](17, 6) NULL ,
	[ValCosto] [numeric](17, 2) NULL ,
	[ValRicavo] [numeric](17, 2) NULL ,
	[ValUtile] [numeric](17, 2) NULL ,
	[IDTipoOra_c] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[TipoOra_c] [varchar] (254) COLLATE Latin1_General_CI_AS NULL ,
	[IDDettOra_c] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[DettOra_c] [varchar] (245) COLLATE Latin1_General_CI_AS NULL ,
	[IDTipoOra_r] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[TipoOra_r] [varchar] (254) COLLATE Latin1_General_CI_AS NULL ,
	[IDDettOra_r] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[DettOra_r] [varchar] (245) COLLATE Latin1_General_CI_AS NULL ,
	[Annotazioni] [text] COLLATE Latin1_General_CI_AS NULL ,
	[COD_UTENTE_INS] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[DES_UTENTE_INS] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_INS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[COD_UTENTE_MOD] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[DES_UTENTE_MOD] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_MOD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[FLG_CONFERMATO] [bit] NULL ,
	[FLAG_CS] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[IDCOMUNICAZIONE] [varchar] (32) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMUNICAZIONI] WITH NOCHECK ADD 
	CONSTRAINT [PK_COMUNICAZIONI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COMUNICAZIONI] WITH NOCHECK ADD 
	CONSTRAINT [DF_COMUNICAZIONI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_COMUNICAZIONI_IDCommessa] DEFAULT ('') FOR [IDCommessa],
	CONSTRAINT [DF_COMUNICAZIONI_Codice] DEFAULT ('') FOR [Codice],
	CONSTRAINT [DF_COMUNICAZIONI_D_Data] DEFAULT ('') FOR [D_Data],
	CONSTRAINT [DF_COMUNICAZIONI_IDCOMMESSA_DC] DEFAULT ('') FOR [IDCOMMESSA_DC],
	CONSTRAINT [DF_COMUNICAZIONI_CodAttivita] DEFAULT ('') FOR [CodAttivita],
	CONSTRAINT [DF_COMUNICAZIONI_DesAttivita] DEFAULT ('') FOR [DesAttivita],
	CONSTRAINT [DF_COMUNICAZIONI_TipoSogg] DEFAULT ('') FOR [TipoSogg],
	CONSTRAINT [DF_COMUNICAZIONI_CodSogg] DEFAULT ('') FOR [CodSogg],
	CONSTRAINT [DF_COMUNICAZIONI_DesSogg] DEFAULT ('') FOR [DesSogg],
	CONSTRAINT [DF_COMUNICAZIONI_DsTipSog] DEFAULT ('') FOR [DsTipSog],
	CONSTRAINT [DF_COMUNICAZIONI_DATINI] DEFAULT ('') FOR [DATINI],
	CONSTRAINT [DF_COMUNICAZIONI_DATFIN] DEFAULT ('') FOR [DATFIN],
	CONSTRAINT [DF_COMUNICAZIONI_Anno] DEFAULT ('') FOR [Anno],
	CONSTRAINT [DF_COMUNICAZIONI_Mese] DEFAULT ('') FOR [Mese],
	CONSTRAINT [DF_COMUNICAZIONI_AAAAMM] DEFAULT ('') FOR [AAAAMM],
	CONSTRAINT [DF_COMUNICAZIONI_QtaGG] DEFAULT (0) FOR [QtaGG],
	CONSTRAINT [DF_COMUNICAZIONI_OreGG] DEFAULT (0) FOR [OreGG],
	CONSTRAINT [DF_COMUNICAZIONI_UMcosto] DEFAULT ('') FOR [UMcosto],
	CONSTRAINT [DF_COMUNICAZIONI_UMricavo] DEFAULT ('') FOR [UMricavo],
	CONSTRAINT [DF_COMUNICAZIONI_Costo] DEFAULT (0) FOR [Costo],
	CONSTRAINT [DF_COMUNICAZIONI_Ricavo] DEFAULT (0) FOR [Ricavo],
	CONSTRAINT [DF_COMUNICAZIONI_ValCosto] DEFAULT (0) FOR [ValCosto],
	CONSTRAINT [DF_COMUNICAZIONI_ValRicavo] DEFAULT (0) FOR [ValRicavo],
	CONSTRAINT [DF_COMUNICAZIONI_ValUtile] DEFAULT (0) FOR [ValUtile],
	CONSTRAINT [DF_COMUNICAZIONI_IDTipoOra_c] DEFAULT ('') FOR [IDTipoOra_c],
	CONSTRAINT [DF_COMUNICAZIONI_TipoOra_c] DEFAULT ('') FOR [TipoOra_c],
	CONSTRAINT [DF_COMUNICAZIONI_IDDettOra_c] DEFAULT ('') FOR [IDDettOra_c],
	CONSTRAINT [DF_COMUNICAZIONI_DettOra_c] DEFAULT ('') FOR [DettOra_c],
	CONSTRAINT [DF_COMUNICAZIONI_IDTipoOra_r] DEFAULT ('') FOR [IDTipoOra_r],
	CONSTRAINT [DF_COMUNICAZIONI_TipoOra_r] DEFAULT ('') FOR [TipoOra_r],
	CONSTRAINT [DF_COMUNICAZIONI_IDDettOra_r] DEFAULT ('') FOR [IDDettOra_r],
	CONSTRAINT [DF_COMUNICAZIONI_DettOra_r] DEFAULT ('') FOR [DettOra_r],
	CONSTRAINT [DF_COMUNICAZIONI_Annotazioni] DEFAULT ('') FOR [Annotazioni],
	CONSTRAINT [DF_COMUNICAZIONI_COD_UTENTE_INS] DEFAULT ('') FOR [COD_UTENTE_INS],
	CONSTRAINT [DF_COMUNICAZIONI_DES_UTENTE_INS] DEFAULT ('') FOR [DES_UTENTE_INS],
	CONSTRAINT [DF_COMUNICAZIONI_DATA_INS] DEFAULT ('') FOR [DATA_INS],
	CONSTRAINT [DF_COMUNICAZIONI_COD_UTENTE_MOD] DEFAULT ('') FOR [COD_UTENTE_MOD],
	CONSTRAINT [DF_COMUNICAZIONI_DES_UTENTE_MOD] DEFAULT ('') FOR [DES_UTENTE_MOD],
	CONSTRAINT [DF_COMUNICAZIONI_DATA_MOD] DEFAULT ('') FOR [DATA_MOD],
	CONSTRAINT [DF_COMUNICAZIONI_FLG_CONFERMATO] DEFAULT (0) FOR [FLG_CONFERMATO],
	CONSTRAINT [DF_COMUNICAZIONI_FLAG_CS] DEFAULT ('') FOR [FLAG_CS],
	CONSTRAINT [DF_COMUNICAZIONI_IDCOMUNICAZIONE] DEFAULT ('') FOR [IDCOMUNICAZIONE]
GO

