if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONTRSTUDI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CONTRSTUDI]
GO
 
CREATE TABLE [dbo].[CONTRSTUDI] (
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL ,
	TAGGANCIO varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	NUMERO varchar(6) COLLATE Latin1_General_CI_AS NULL ,
	DATA varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	RAGSOC varchar(80) COLLATE Latin1_General_CI_AS NULL ,
	INDIRI varchar(80) COLLATE Latin1_General_CI_AS NULL ,
	LOCALI varchar(80) COLLATE Latin1_General_CI_AS NULL ,
	CAP varchar(5) COLLATE Latin1_General_CI_AS NULL ,
	PROVIN varchar(2) COLLATE Latin1_General_CI_AS NULL ,
	NOTE text COLLATE Latin1_General_CI_AS NULL ,
	UTENTEINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAINS varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	UTENTEMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAMOD varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	CHIUSO bit NULL ,
	REGFAT numeric(1,0) NULL ,
	RFAT_T bit NULL ,
	RFAT_Q bit NULL ,
	RFAT_C bit NULL ,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRSTUDI] WITH NOCHECK ADD 
	CONSTRAINT [PK_CONTRSTUDI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CONTRSTUDI] WITH NOCHECK ADD 
	CONSTRAINT [DF_CONTRSTUDI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_CONTRSTUDI_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_CONTRSTUDI_NUMERO] DEFAULT ('') FOR [NUMERO],
	CONSTRAINT [DF_CONTRSTUDI_DATA] DEFAULT ('') FOR [DATA],
	CONSTRAINT [DF_CONTRSTUDI_CODCLI] DEFAULT ('') FOR [CODCLI],
	CONSTRAINT [DF_CONTRSTUDI_RAGSOC] DEFAULT ('') FOR [RAGSOC],
	CONSTRAINT [DF_CONTRSTUDI_INDIRI] DEFAULT ('') FOR [INDIRI],
	CONSTRAINT [DF_CONTRSTUDI_LOCALI] DEFAULT ('') FOR [LOCALI],
	CONSTRAINT [DF_CONTRSTUDI_CAP] DEFAULT ('') FOR [CAP],
	CONSTRAINT [DF_CONTRSTUDI_PROVIN] DEFAULT ('') FOR [PROVIN],
	CONSTRAINT [DF_CONTRSTUDI_NOTE] DEFAULT ('') FOR [NOTE],
	CONSTRAINT [DF_CONTRSTUDI_UTENTEINS] DEFAULT ('') FOR [UTENTEINS],
	CONSTRAINT [DF_CONTRSTUDI_DATAINS] DEFAULT ('') FOR [DATAINS],
	CONSTRAINT [DF_CONTRSTUDI_ORAINS] DEFAULT ('') FOR [ORAINS],
	CONSTRAINT [DF_CONTRSTUDI_UTENTEMOD] DEFAULT ('') FOR [UTENTEMOD],
	CONSTRAINT [DF_CONTRSTUDI_DATAMOD] DEFAULT ('') FOR [DATAMOD],
	CONSTRAINT [DF_CONTRSTUDI_ORAMOD] DEFAULT ('') FOR [ORAMOD],
	CONSTRAINT [DF_CONTRSTUDI_REGFAT] DEFAULT (0) FOR [REGFAT],
	CONSTRAINT [DF_CONTRSTUDI_RFAT_T] DEFAULT (0) FOR [RFAT_T],
	CONSTRAINT [DF_CONTRSTUDI_RFAT_Q] DEFAULT (0) FOR [RFAT_Q],
	CONSTRAINT [DF_CONTRSTUDI_RFAT_C] DEFAULT (0) FOR [RFAT_C]
GO

