if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONVERSIONI_UM]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[CONVERSIONI_UM]
GO
 
CREATE TABLE [dbo].[CONVERSIONI_UM] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_id_unique] DEFAULT newid(),
	[CODICE] varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_CODICE] DEFAULT (''),
	[DESCRI] varchar(200) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_DESCRI] DEFAULT (''),
	[UMORIG] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_UMORIG] DEFAULT (''),
	[UMDEST] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_UMDEST] DEFAULT (''),
	[COEFF] numeric(19,6) NOT NULL CONSTRAINT [DF_CONVERSIONI_UM_COEFF] DEFAULT ('')
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONVERSIONI_UM] WITH NOCHECK ADD 
	CONSTRAINT [PK_CONVERSIONI_UM] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
