if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COSTI_PRODUZIONE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[COSTI_PRODUZIONE]
GO
 
CREATE TABLE [dbo].[COSTI_PRODUZIONE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_COSTO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_DAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_AL]  [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_PROD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[STATO_LAV] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_COSTO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI_COSTO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[UM] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[COSTO] [numeric] (17,6) NULL 

) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COSTI_PRODUZIONE] WITH NOCHECK ADD 
	CONSTRAINT [PK_COSTI_PRODUZIONE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COSTI_PRODUZIONE] WITH NOCHECK ADD 
	CONSTRAINT [DF_COSTI_PRODUZIONE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_COSTI_PRODUZIONE_ID_COSTO] DEFAULT ('') FOR [ID_COSTO],
	CONSTRAINT [DF_COSTI_PRODUZIONE_DATA_DAL] DEFAULT ('') FOR [DATA_DAL],
	CONSTRAINT [DF_COSTI_PRODUZIONE_DATA_AL] DEFAULT ('') FOR [DATA_AL],
	CONSTRAINT [DF_COSTI_PRODUZIONE_TIPO_PROD] DEFAULT ('') FOR [TIPO_PROD],
	CONSTRAINT [DF_COSTI_PRODUZIONE_STATO_LAV] DEFAULT ('') FOR [STATO_LAV],
	CONSTRAINT [DF_COSTI_PRODUZIONE_TIPO_COSTO] DEFAULT ('') FOR [TIPO_COSTO],
	CONSTRAINT [DF_COSTI_PRODUZIONE_DESCRI_COSTO] DEFAULT ('') FOR [DESCRI_COSTO],
	CONSTRAINT [DF_COSTI_PRODUZIONE_UM] DEFAULT ('') FOR [UM],
	CONSTRAINT [DF_COSTI_PRODUZIONE_COSTO] DEFAULT (0) FOR [COSTO]

GO

