if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COSTISTUDI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[COSTISTUDI]
GO
 
CREATE TABLE [dbo].[COSTISTUDI] (
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL ,
	TAGGANCIO varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CODRIS varchar(5) COLLATE Latin1_General_CI_AS NULL ,
	DESRIS varchar(254) COLLATE Latin1_General_CI_AS NULL ,
	NOTE text COLLATE Latin1_General_CI_AS NULL ,
	UTENTEINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAINS varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	UTENTEMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DATAMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	ORAMOD varchar(8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COSTISTUDI] WITH NOCHECK ADD 
	CONSTRAINT [PK_COSTISTUDI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COSTISTUDI] WITH NOCHECK ADD 
	CONSTRAINT [DF_COSTISTUDI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_COSTISTUDI_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_COSTISTUDI_CODRIS] DEFAULT ('') FOR [CODRIS],
	CONSTRAINT [DF_COSTISTUDI_DESRIS] DEFAULT ('') FOR [DESRIS],
	CONSTRAINT [DF_COSTISTUDI_NOTE] DEFAULT ('') FOR [NOTE],
	CONSTRAINT [DF_COSTISTUDI_UTENTEINS] DEFAULT ('') FOR [UTENTEINS],
	CONSTRAINT [DF_COSTISTUDI_DATAINS] DEFAULT ('') FOR [DATAINS],
	CONSTRAINT [DF_COSTISTUDI_ORAINS] DEFAULT ('') FOR [ORAINS],
	CONSTRAINT [DF_COSTISTUDI_UTENTEMOD] DEFAULT ('') FOR [UTENTEMOD],
	CONSTRAINT [DF_COSTISTUDI_DATAMOD] DEFAULT ('') FOR [DATAMOD],
	CONSTRAINT [DF_COSTISTUDI_ORAMOD] DEFAULT ('') FOR [ORAMOD]
GO

