
-- PARAMETRI PER RETTIFICHE INVENTARIALI UTILIZZATE IN UTILITY DI RIALLINEAMENTO GIACENZE DA MOVIMENTI

delete from PARA where CODICE = 'TOPFL+'
delete from PARA where CODICE = 'TOPFL-'

insert into PARA (CODICE,DESCRI,LIBERA)
values ('TOPFL+','CARICO INVENTARIALE DI RIALLINEAMENTO','CN      NNNN                    MOFL-   NM')
insert into PARA (CODICE,DESCRI,LIBERA)
values ('TOPFL-','SCARICO INVENTARIALE DI RIALLINEAMENTO','SN      NNNN                    MOFL+   NM')

select * from PARA where CODICE = 'TOPFL+'
select * from PARA where CODICE = 'TOPFL-'