-- PARAMETRO PER DIMENSIONE MASSIMA E MINIMA BOBINA MADRE

delete from para where codice like 'LMB%'

--insert into para (codice,descri,LIBERA,NOTE) values ('LMBP38T','DIMENSIONE MASSIMA E MINIMA BOBINA MADRE',   '15000     7000','DIGITARE NEI PRIMI 10 CARATTERI LA DIMENSIONE MASSIMA E NEI CARATTERI DA 11 IN POI LA DIMENSIONE MINIMA IN METRI LINEARI')
--insert into para (codice,descri,LIBERA,NOTE) values ('LMBP40T','DIMENSIONE MASSIMA E MINIMA BOBINA MADRE',   '16000     8000','DIGITARE NEI PRIMI 10 CARATTERI LA DIMENSIONE MASSIMA E NEI CARATTERI DA 11 IN POI LA DIMENSIONE MINIMA IN METRI LINEARI')
--insert into para (codice,descri,LIBERA,NOTE) values ('LMBP30T','DIMENSIONE MASSIMA E MINIMA BOBINA MADRE',   '15000     5000','DIGITARE NEI PRIMI 10 CARATTERI LA DIMENSIONE MASSIMA E NEI CARATTERI DA 11 IN POI LA DIMENSIONE MINIMA IN METRI LINEARI')
--insert into para (codice,descri,LIBERA,NOTE) values ('LMBP40TS','DIMENSIONE MASSIMA E MINIMA BOBINA MADRE',  '15000     7000','DIGITARE NEI PRIMI 10 CARATTERI LA DIMENSIONE MASSIMA E NEI CARATTERI DA 11 IN POI LA DIMENSIONE MINIMA IN METRI LINEARI')
insert into para (codice,descri,LIBERA,NOTE) values ('LMBDEFAULT','DIMENSIONE MASSIMA E MINIMA BOBINA MADRE','15000     10000','DIGITARE NEI PRIMI 10 CARATTERI LA DIMENSIONE MASSIMA E NEI CARATTERI DA 11 IN POI LA DIMENSIONE MINIMA IN METRI LINEARI')

select * from para where codice like 'LMB%'

