
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[DESLINGUE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[DESLINGUE]
GO

CREATE TABLE [dbo].[DESLINGUE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[IDDESLING] varchar (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPODES] varchar (10) COLLATE Latin1_General_CI_AS NULL ,
	[LINGUA] varchar (3) COLLATE Latin1_General_CI_AS NULL ,
	[CODICE] varchar (20) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI] varchar (200) COLLATE Latin1_General_CI_AS NULL ,
	[DESEST] varchar (200) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DESLINGUE] WITH NOCHECK ADD 
	CONSTRAINT [PK_DESLINGUE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DESLINGUE] WITH NOCHECK ADD 
	CONSTRAINT [DF_DESLINGUE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_DESLINGUE_IDDESLING] DEFAULT ('') FOR [IDDESLING],
	CONSTRAINT [DF_DESLINGUE_TIPODES] DEFAULT ('') FOR [TIPODES],
	CONSTRAINT [DF_DESLINGUE_LINGUA] DEFAULT ('') FOR [LINGUA],
	CONSTRAINT [DF_DESLINGUE_CODICE] DEFAULT ('') FOR [CODICE],
	CONSTRAINT [DF_DESLINGUE_DESCRI] DEFAULT ('') FOR [DESCRI],
	CONSTRAINT [DF_DESLINGUE_DESEST] DEFAULT ('') FOR [DESEST]
GO
