
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[DESTINATARI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[DESTINATARI]
GO
 
CREATE TABLE [dbo].[DESTINATARI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_DESTINATARIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,	
	[SYS_DESTINATARIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DESTINATARIO] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
	[CC]  BIT NULL ,
	[CCN]  BIT NULL, 
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL

) ON [PRIMARY]   
GO
  

ALTER TABLE [dbo].[DESTINATARI] WITH NOCHECK ADD 
	CONSTRAINT [DF_DESTINATARI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_DESTINATARI_ID_DESTINATARIO] DEFAULT ('') FOR [ID_DESTINATARIO],
	CONSTRAINT [DF_DESTINATARI_SYS_DESTINATARIO] DEFAULT ('') FOR [SYS_DESTINATARIO],
	CONSTRAINT [DF_DESTINATARI_DESTINATARIO] DEFAULT ('') FOR [DESTINATARIO],
	CONSTRAINT [DF_DESTINATARI_CC] DEFAULT (0) FOR [CC],
	CONSTRAINT [DF_DESTINATARI_CCN] DEFAULT (0) FOR [CCN],
	CONSTRAINT [DF_DESTINATARI_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

