
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[DOCUMENTI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[DOCUMENTI]
GO

CREATE TABLE [dbo].[DOCUMENTI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DOC_TIPOCF] varchar (1) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_CODICE] varchar (10) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_TIPODOC] varchar (3) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_AGGANCIO] varchar (10) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_RAGSOC ] varchar (200) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_NOTE] text NULL ,
	[DOC_FLATTIVO] bit NULL ,
	[DOC_FLREPORT1] bit NULL ,
	[DOC_REPORT1] varchar (15) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_FLREPORT2] bit NULL ,
	[DOC_REPORT2] varchar (15) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_FLREPORT3] bit NULL ,
	[DOC_REPORT3] varchar (15) COLLATE Latin1_General_CI_AS NULL ,
	[DOC_FLREPORT4] bit NULL ,
	[DOC_REPORT4] varchar (15) COLLATE Latin1_General_CI_AS NULL ,
	[DOCT_NOLOG1] bit NULL ,
	[DOCT_NOLOG2] bit NULL ,
	[DOCT_NOSTPLAYOUT] bit NULL ,
	[DOCD_SOLO_TXT] bit NULL ,
	[DOCD_TXT_UNICO] text NULL ,
	[DOCD_CAMBIA_ART] bit NULL ,
	[DOCD_NOSTP_ART] bit NULL ,
	[DOCD_NOSTP_VSRIF] bit NULL ,
	[DOCD_NOSTP_UM] bit NULL ,
	[DOCD_NOSTP_QTA] bit NULL ,
	[DOCD_NOSTP_PRZ] bit NULL ,
	[DOCD_NOSTP_SCO] bit NULL ,
	[DOCD_NOSTP_VAL] bit NULL ,
	[DOCD_NOSTP_IVA] bit NULL ,
	[DOCD_NOSTPLAYOUT] bit NULL ,
	[DOCC_SOLO_VAL] bit NULL ,
	[DOCC_NOSTP_SCA] bit NULL ,
	[DOCC_NOSTP_CPA] bit NULL ,
	[DOCC_NOSTP_IMPST] bit NULL ,
	[DOCC_NOSTP_TXT] bit NULL ,
	[DOCC_NOSTP_IVA] bit NULL ,
	[DOCC_NOSTP_LAYOUT] bit NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


ALTER TABLE [dbo].[DOCUMENTI] WITH NOCHECK ADD 
	CONSTRAINT [PK_DOCUMENTI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DOCUMENTI] WITH NOCHECK ADD 
	CONSTRAINT [DF_DOCUMENTI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_DOCUMENTI_DOC_TIPOCF] DEFAULT ('') FOR [DOC_TIPOCF],
	CONSTRAINT [DF_DOCUMENTI_DOC_CODICE] DEFAULT ('') FOR [DOC_CODICE],
	CONSTRAINT [DF_DOCUMENTI_DOC_TIPODOC] DEFAULT ('') FOR [DOC_TIPODOC],
	CONSTRAINT [DF_DOCUMENTI_DOC_AGGANCIO] DEFAULT ('') FOR [DOC_AGGANCIO],
	CONSTRAINT [DF_DOCUMENTI_DOC_RAGSOC ] DEFAULT ('') FOR [DOC_RAGSOC ],
	CONSTRAINT [DF_DOCUMENTI_DOC_NOTE] DEFAULT ('') FOR [DOC_NOTE],
	CONSTRAINT [DF_DOCUMENTI_DOC_FLATTIVO] DEFAULT (0) FOR [DOC_FLATTIVO],
	CONSTRAINT [DF_DOCUMENTI_DOC_FLREPORT1] DEFAULT (0) FOR [DOC_FLREPORT1],
	CONSTRAINT [DF_DOCUMENTI_DOC_REPORT1] DEFAULT ('') FOR [DOC_REPORT1],
	CONSTRAINT [DF_DOCUMENTI_DOC_FLREPORT2] DEFAULT (0) FOR [DOC_FLREPORT2],
	CONSTRAINT [DF_DOCUMENTI_DOC_REPORT2] DEFAULT ('') FOR [DOC_REPORT2],
	CONSTRAINT [DF_DOCUMENTI_DOC_FLREPORT3] DEFAULT (0) FOR [DOC_FLREPORT3],
	CONSTRAINT [DF_DOCUMENTI_DOC_REPORT3] DEFAULT ('') FOR [DOC_REPORT3],
	CONSTRAINT [DF_DOCUMENTI_DOC_FLREPORT4] DEFAULT (0) FOR [DOC_FLREPORT4],
	CONSTRAINT [DF_DOCUMENTI_DOC_REPORT4] DEFAULT ('') FOR [DOC_REPORT4],
	CONSTRAINT [DF_DOCUMENTI_DOCT_NOLOG1] DEFAULT (0) FOR [DOCT_NOLOG1],
	CONSTRAINT [DF_DOCUMENTI_DOCT_NOLOG2] DEFAULT (0) FOR [DOCT_NOLOG2],
	CONSTRAINT [DF_DOCUMENTI_DOCT_NOSTPLAYOUT] DEFAULT (0) FOR [DOCT_NOSTPLAYOUT],
	CONSTRAINT [DF_DOCUMENTI_DOCD_SOLO_TXT] DEFAULT (0) FOR [DOCD_SOLO_TXT],
	CONSTRAINT [DF_DOCUMENTI_DOCD_TXT_UNICO] DEFAULT ('') FOR [DOCD_TXT_UNICO],
	CONSTRAINT [DF_DOCUMENTI_DOCD_CAMBIA_ART] DEFAULT (0) FOR [DOCD_CAMBIA_ART],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_ART] DEFAULT (0) FOR [DOCD_NOSTP_ART],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_VSRIF] DEFAULT (0) FOR [DOCD_NOSTP_VSRIF],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_UM] DEFAULT (0) FOR [DOCD_NOSTP_UM],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_QTA] DEFAULT (0) FOR [DOCD_NOSTP_QTA],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_PRZ] DEFAULT (0) FOR [DOCD_NOSTP_PRZ],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_SCO] DEFAULT (0) FOR [DOCD_NOSTP_SCO],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_VAL] DEFAULT (0) FOR [DOCD_NOSTP_VAL],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTP_IVA] DEFAULT (0) FOR [DOCD_NOSTP_IVA],
	CONSTRAINT [DF_DOCUMENTI_DOCD_NOSTPLAYOUT] DEFAULT (0) FOR [DOCD_NOSTPLAYOUT],
	CONSTRAINT [DF_DOCUMENTI_DOCC_SOLO_VAL] DEFAULT (0) FOR [DOCC_SOLO_VAL],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_SCA] DEFAULT (0) FOR [DOCC_NOSTP_SCA],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_CPA] DEFAULT (0) FOR [DOCC_NOSTP_CPA],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_IMPS] DEFAULT (0) FOR [DOCC_NOSTP_IMPST],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_TXT] DEFAULT (0) FOR [DOCC_NOSTP_TXT],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_IVA] DEFAULT (0) FOR [DOCC_NOSTP_IVA],
	CONSTRAINT [DF_DOCUMENTI_DOCC_NOSTP_LAYOUT] DEFAULT (0) FOR [DOCC_NOSTP_LAYOUT]
GO
