	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[DOMISCRIZ]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[DOMISCRIZ]
GO

/****** Object:  Table [dbo].[DOMISCRIZ]    Script Date: 02/10/2007 15.41.01 ******/
CREATE TABLE [DOMISCRIZ] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] 	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDCONTATTO]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDDOMISCRIZ] 	[varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL ,
	[IDCENTRCOM]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDCONTATTOD]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDAREA]	    [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDAREACORS]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDANNOCORS]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDANACCORS]  	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[D_DOMISCR]   	[varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PROGRESSIVO] 	[varchar] (25) COLLATE Latin1_General_CI_AS NULL ,
	[B_ANNULLATO] 	[varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL ,
	[B_CONFERMATO] 	[varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DOMISCRIZ] WITH NOCHECK ADD 
	CONSTRAINT [PK_DOMISCRIZ] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DOMISCRIZ] WITH NOCHECK ADD 
	CONSTRAINT [DF_DOMISCRIZ_id_unique] 		DEFAULT (newid()) FOR 	[id_unique]			,
	CONSTRAINT [DF_CONTATTO_DAGGANCIO] 	  	DEFAULT ('') FOR 		[DAGGANCIO] ,	
	CONSTRAINT [DF_DOMISCRIZ_IDCONTATTO]       	DEFAULT ('') FOR 	[IDCONTATTO]   	,
	CONSTRAINT [DF_DOMISCRIZ_IDDOMISCRIZ] 	DEFAULT ('') FOR 			[IDDOMISCRIZ] 	,
	CONSTRAINT [DF_DOMISCRIZ_IDCENTRCOM]  	DEFAULT ('') FOR 			[IDCENTRCOM]  	,
	CONSTRAINT [DF_DOMISCRIZ_IDCONTATTOD]       	DEFAULT ('') FOR 	[IDCONTATTOD]   	,
	CONSTRAINT [DF_DOMISCRIZ_IDAREA]	     	DEFAULT ('') FOR 		[IDAREA]	     	,
	CONSTRAINT [DF_DOMISCRIZ_IDAREACORS]      	DEFAULT ('') FOR 		[IDAREACORS]   	,
	CONSTRAINT [DF_DOMISCRIZ_IDANNOCORS]     	DEFAULT ('') FOR 		[IDANNOCORS]  	,   
	CONSTRAINT [DF_DOMISCRIZ_IDANACCORS]     	DEFAULT ('') FOR 		[IDANACCORS]  	,   
	CONSTRAINT [DF_DOMISCRIZ_D_DOMISCR]      	DEFAULT ('') FOR 		[D_DOMISCR]   	,   
	CONSTRAINT [DF_DOMISCRIZ_PROGRESSIVO]    	DEFAULT ('') FOR 		[PROGRESSIVO] 	,  
	CONSTRAINT [DF_DOMISCRIZ_B_ANNULLATO]     DEFAULT ('') FOR 			[B_ANNULLATO] 	,    
	CONSTRAINT [DF_DOMISCRIZ_B_CONFERMATO]   	DEFAULT ('') FOR 		[B_CONFERMATO]
GO



