if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[ELAB_MENS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[ELAB_MENS]
GO
 
CREATE TABLE [dbo].[ELAB_MENS] (
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL ,
    TIPO_ELAB varchar(15) COLLATE Latin1_General_CI_AS NULL ,
    AAAAMM varchar(7) COLLATE Latin1_General_CI_AS NULL ,
    CODCLI_AQUARIUS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
    RAGSOC_AQUARIUS varchar(45) COLLATE Latin1_General_CI_AS NULL ,
    NUM_CEDOLINI numeric(17,0) NULL ,
	ELAB_FATTA  bit NULL 		
) ON [PRIMARY]  
GO

ALTER TABLE [dbo].[ELAB_MENS] WITH NOCHECK ADD 
	CONSTRAINT [PK_ELAB_MENS] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ELAB_MENS] WITH NOCHECK ADD 
	CONSTRAINT [DF_ELAB_MENS_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_ELAB_MENS_TIPO_ELAB] DEFAULT ('') FOR [TIPO_ELAB],
	CONSTRAINT [DF_ELAB_MENS_AAAAMM] DEFAULT ('') FOR [AAAAMM],
	CONSTRAINT [DF_ELAB_MENS_CODCLI_AQUARIUS] DEFAULT ('') FOR [CODCLI_AQUARIUS],
	CONSTRAINT [DF_ELAB_MENS_RAGSOC_AQUARIUS] DEFAULT ('') FOR [RAGSOC_AQUARIUS],
	CONSTRAINT [DF_ELAB_MENS_NUM_CEDOLINI] DEFAULT ('') FOR [NUM_CEDOLINI],
	CONSTRAINT [DF_ELAB_MENS_ELAB_FATTA] DEFAULT ('') FOR [ELAB_FATTA]
GO
