if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[EVENTI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[EVENTI]
GO

CREATE TABLE [dbo].[EVENTI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_EVENTO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRIZIONE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[D_DATA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[D_DATAPROSSIMO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_EVENTO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EVENTI] WITH NOCHECK ADD 
	CONSTRAINT [PK_EVENTI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[EVENTI] WITH NOCHECK ADD 
	CONSTRAINT [DF_EVENTI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_EVENTI_ID_EVENTO] DEFAULT ('') FOR [ID_EVENTO],
	CONSTRAINT [DF_EVENTI_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_EVENTI_DESCRIZIONE] DEFAULT ('') FOR [DESCRIZIONE],
	CONSTRAINT [DF_EVENTI_D_DATA] DEFAULT ('') FOR [D_DATA],
	CONSTRAINT [DF_EVENTI_D_DATAPROSSIMO] DEFAULT ('') FOR [D_DATAPROSSIMO],
	CONSTRAINT [DF_EVENTI_TIPO_EVENTO] DEFAULT ('') FOR [TIPO_EVENTO]
GO

