

/****** Object:  Table [dbo].[FATTURE_ELETTRONICHE]    Script Date: 19/02/2016 17:14:01 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FATTURE_ELETTRONICHE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[FATTURE_ELETTRONICHE]
GO  

/****** Object:  Table [dbo].[FATTURE_ELETTRONICHE]    Script Date: 19/02/2016 17:14:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FATTURE_ELETTRONICHE](
	[id_unique]  [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_id_unique]  DEFAULT (newid()),
	[FE_SYSFATELE] [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_SYSFATELE]  DEFAULT (''),
	[TAGGANCIO]    [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_TAGGANCIO]  DEFAULT (''),
    [FE_NUMORD] [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_FE_NUMORD]  DEFAULT (''),
	[FE_DATORD]   [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_DATORD]  DEFAULT (''),
    [FE_NPROT] [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_FE_NPROT]  DEFAULT (''),
	[FE_TIPODOC] [varchar](20) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_TIPODOC]  DEFAULT (''),
	[FE_CAUS] [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_CAUS]  DEFAULT (''),
	[FE_CODCLFO] [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_CODCLFO]  DEFAULT (''),
	[FE_RAGSOC] [varchar](150) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_RAGSOC]  DEFAULT (''),
	[FE_PARIVA] [varchar](25) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_PARIVA]  DEFAULT (''),
	[FE_IMPORTO]	[Numeric](19,2) NULL,  
    [FE_ESITO] [varchar](3) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_ESITO]  DEFAULT (''),
	[FE_DTRICEZ] [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_DTRICEZ]  DEFAULT (''),
	[FE_DTIMPOR] [varchar](10) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_DTIMPOR]  DEFAULT (''),
	[FE_REGISTRATO]	[bit],
	[FE_ANTEPRIDOC]	[bit],
	[FE_RICEVUTA]	[bit],
	[FE_ALLEGATI]	[bit],
	[FE_INFFAT]	[bit],
	[FE_FILEXML] [varchar](254) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_FILEXML]  DEFAULT (''),
	[FE_CFILEXML] [varchar](30) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_CFILEXML]  DEFAULT (''),
	[FE_NOMEFILEBLUE_XML] [varchar](100) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_NOMEFILEBLUE_XML]  DEFAULT (''),
	[FE_NOMEFILEBLUE_ZIP] [varchar](100) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_NOMEFILEBLUE_ZIP]  DEFAULT (''),
	[FE_ARCHIVE_ID] [varchar](50) NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_ARCHIVE_ID]  DEFAULT (''),
	[FE_NOTE]   [text] NULL CONSTRAINT [DF_FATTURE_ELETTRONICHE_FE_NOTE]  DEFAULT ('')
 CONSTRAINT [PK_FATTURE_ELETTRONICHE] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
