if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FATTURABST]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[FATTURABST]
GO
 
CREATE TABLE [dbo].[FATTURABST] (
	id_unique uniqueidentifier ROWGUIDCOL NOT NULL ,
	IDFATTURAB varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	AAAAMM varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	RAGSOC varchar(80) COLLATE Latin1_General_CI_AS NULL ,
	TIPO varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	DESTIPO varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	TIPO_ELAB varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	TIPO_FATT varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	IDATTIVITA varchar(20) COLLATE Latin1_General_CI_AS NULL ,
	CODATTIV varchar(5) COLLATE Latin1_General_CI_AS NULL ,
	DESATTIV varchar(254) COLLATE Latin1_General_CI_AS NULL ,
	QTAFAT numeric(17,2) NULL ,
	UMFAT varchar(2) COLLATE Latin1_General_CI_AS NULL ,
	PRZFAT numeric(17,6) NULL ,
	VALFAT numeric(17,2) NULL ,
	ANNOTAZIONI text NULL ,
	FATTURATO bit NULL ,
	NUMFAP varchar(6) COLLATE Latin1_General_CI_AS NULL ,
	DATFAP varchar(10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FATTURABST] WITH NOCHECK ADD 
	CONSTRAINT [PK_FATTURABST] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FATTURABST] WITH NOCHECK ADD 
	CONSTRAINT [DF_FATTURABST_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_FATTURABST_IDFATTURAB] DEFAULT ('') FOR [IDFATTURAB],
	CONSTRAINT [DF_FATTURABST_AAAAMM] DEFAULT ('') FOR [AAAAMM],
	CONSTRAINT [DF_FATTURABST_CODCLI] DEFAULT ('') FOR [CODCLI],
	CONSTRAINT [DF_FATTURABST_RAGSOC] DEFAULT ('') FOR [RAGSOC],
	CONSTRAINT [DF_FATTURABST_TIPO] DEFAULT ('') FOR [TIPO],
	CONSTRAINT [DF_FATTURABST_DESTIPO] DEFAULT ('') FOR [DESTIPO],
	CONSTRAINT [DF_FATTURABST_TIPO_ELAB] DEFAULT ('') FOR [TIPO_ELAB],
	CONSTRAINT [DF_FATTURABST_TIPO_FATT] DEFAULT ('') FOR [TIPO_FATT],
	CONSTRAINT [DF_FATTURABST_IDATTIVITA] DEFAULT ('') FOR [IDATTIVITA],
	CONSTRAINT [DF_FATTURABST_CODATTIV] DEFAULT ('') FOR [CODATTIV],
	CONSTRAINT [DF_FATTURABST_DESATTIV] DEFAULT ('') FOR [DESATTIV],
	CONSTRAINT [DF_FATTURABST_QTAFAT] DEFAULT (0) FOR [QTAFAT],
	CONSTRAINT [DF_FATTURABST_UMFAT] DEFAULT ('') FOR [UMFAT],
	CONSTRAINT [DF_FATTURABST_PRZFAT] DEFAULT (0) FOR [PRZFAT],
	CONSTRAINT [DF_FATTURABST_VALFAT] DEFAULT (0) FOR [VALFAT],
	CONSTRAINT [DF_FATTURABST_ANNOTAZIONI] DEFAULT ('') FOR [ANNOTAZIONI],
	CONSTRAINT [DF_FATTURABST_FATTURATO] DEFAULT (0) FOR [FATTURATO],
	CONSTRAINT [DF_FATTURABST_NUMFAP] DEFAULT ('') FOR [NUMFAP],
	CONSTRAINT [DF_FATTURABST_DATFAP] DEFAULT ('') FOR [DATFAP]
GO

