if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FLOW_PROCEDURE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[FLOW_PROCEDURE]
GO
 
CREATE TABLE [dbo].[FLOW_PROCEDURE] (
	[id_unique]          uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[SELEZIONE]          [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
	[ID_PROCEDURA]       [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ID_PROCEDURA_PADRE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[DESCRIZIONE]        [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
	[CODCLI]			 [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_INIZIO]        [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORA_INIZIO]         [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
	[DATA_FINE]          [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[ORA_FINE]           [varchar] (8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FLOW_PROCEDURE] WITH NOCHECK ADD 
	CONSTRAINT [PK_FLOW_PROCEDURE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FLOW_PROCEDURE] WITH NOCHECK ADD 
	CONSTRAINT [DF_FLOW_PROCEDURE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_FLOW_PROCEDURE_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE],
	CONSTRAINT [DF_FLOW_PROCEDURE_ID_PROCEDURA]  DEFAULT ('') FOR [ID_PROCEDURA],
	CONSTRAINT [DF_FLOW_PROCEDURE_PROCEDURA_PADRE] DEFAULT ('') FOR [ID_PROCEDURA_PADRE], 
	CONSTRAINT [DF_FLOW_PROCEDURE_DESCRIZIONE] DEFAULT ('') FOR [DESCRIZIONE], 
	CONSTRAINT [DF_FLOW_PROCEDURE_CODCLI] DEFAULT ('') FOR [CODCLI], 
	CONSTRAINT [DF_FLOW_PROCEDURE_DATA_INIZIO]  DEFAULT ('') FOR [DATA_INIZIO], 
	CONSTRAINT [DF_FLOW_PROCEDURE_ORA_INIZIO]  DEFAULT ('') FOR [ORA_INIZIO],    
	CONSTRAINT [DF_FLOW_PROCEDURE_DATA_FINE]  DEFAULT ('') FOR [DATA_FINE],
	CONSTRAINT [DF_FLOW_PROCEDURE_ORA_FINE]  DEFAULT ('') FOR [ORA_FINE]
GO                               



