if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FLOW_BLOCCHI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[FLOW_BLOCCHI]
GO
 
CREATE TABLE [dbo].[FLOW_BLOCCHI] (
	[id_unique]          uniqueidentifier ROWGUIDCOL  NOT NULL ,
    [ID_PROCEDURA]       [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
    [NR_BLOCCO]  [numeric] (5) NULL,
	[NOME]       [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
	[TIPO]       [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
	[TOPPOS]     [numeric] (5) NULL,
	[LEFTPOS]    [numeric] (5) NULL,
	[HEIGHT]     [numeric] (5) NULL,
	[WIDTH]      [numeric] (5) NULL,
	[COLORE]     [numeric] (10) NULL,
	[TESTO]      [text] COLLATE Latin1_General_CI_AS NULL,
	[PREC]       [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
	[SUCC]       [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
	[SELEZIONE]  [varchar] (1) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FLOW_BLOCCHI] WITH NOCHECK ADD 
	CONSTRAINT [PK_FLOW_BLOCCHI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FLOW_BLOCCHI] WITH NOCHECK ADD 
	CONSTRAINT [DF_FLOW_BLOCCHI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_FLOW_BLOCCHI_ID_PROCEDURA]  DEFAULT ('') FOR [ID_PROCEDURA],
	CONSTRAINT [DF_FLOW_BLOCCHI_NR_BLOCCO]  DEFAULT (0) FOR [NR_BLOCCO], 
	CONSTRAINT [DF_FLOW_BLOCCHI_NOME]  DEFAULT ('') FOR [NOME],
	CONSTRAINT [DF_FLOW_BLOCCHI_TIPO] DEFAULT ('') FOR [TIPO], 
	CONSTRAINT [DF_FLOW_BLOCCHI_TOPPOS]  DEFAULT (0) FOR [TOPPOS], 
	CONSTRAINT [DF_FLOW_BLOCCHI_LEFTPOS] DEFAULT (0) FOR [LEFTPOS], 
	CONSTRAINT [DF_FLOW_BLOCCHI_HEIGHT] DEFAULT (0) FOR [HEIGHT], 
	CONSTRAINT [DF_FLOW_BLOCCHI_WIDTH] DEFAULT (0) FOR [WIDTH], 
	CONSTRAINT [DF_FLOW_BLOCCHI_COLORE]  DEFAULT (0) FOR [COLORE],    
	CONSTRAINT [DF_FLOW_BLOCCHI_TESTO]  DEFAULT ('') FOR [TESTO],    
 	CONSTRAINT [DF_FLOW_BLOCCHI_PREC]  DEFAULT ('') FOR [PREC],    
	CONSTRAINT [DF_FLOW_BLOCCHI_SUCC]  DEFAULT ('') FOR [SUCC],
	CONSTRAINT [DF_FLOW_BLOCCHI_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO                               



