if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FLOW_UTENTI_PROCEDURE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[FLOW_UTENTI_PROCEDURE]
GO
 
CREATE TABLE [dbo].[FLOW_UTENTI_PROCEDURE] (
	[id_unique]          uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_PROCEDURA]       [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[USERID]             [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
	[TIPO_ACCESSO]       [varchar] (8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FLOW_UTENTI_PROCEDURE] WITH NOCHECK ADD 
	CONSTRAINT [PK_FLOW_UTENTI_PROCEDURE]  PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FLOW_UTENTI_PROCEDURE] WITH NOCHECK ADD 
	CONSTRAINT [DF_FLOW_UTENTI_PROCEDURE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_FLOW_UTENTI_PROCEDURE_ID_PROCEDURA]  DEFAULT ('') FOR [ID_PROCEDURA],
	CONSTRAINT [DF_FLOW_UTENTI_PROCEDURE_USERID] DEFAULT ('') FOR [USERID], 
	CONSTRAINT [DF_FLOW_UTENTI_PROCEDURE_TIPO_ACCESSO]  DEFAULT ('') FOR [TIPO_ACCESSO]
GO                               



