

/* DROP TABLE [dbo].[FORM_EXE_UTENTE]
GO */


/****** Object:  Table [dbo].[FORM_EXE_UTENTE]    Script Date: 27/04/2015 17.46.34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FORM_EXE_UTENTE](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[NOMEPROC] [varchar](50) NULL,
	[UTENTE] [varchar](20) NULL,
	[DESPROC] [text] NULL,
	[NOMEFORMEXE] [varchar](50) NULL,
 CONSTRAINT [PK_FORM_EXE_UTENTE] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FORM_EXE_UTENTE] ADD  CONSTRAINT [DF_FORM_EXE_UTENTE_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[FORM_EXE_UTENTE] ADD  CONSTRAINT [DF_FORM_EXE_UTENTE_NOMEPROC]  DEFAULT ('') FOR [NOMEPROC]
GO

ALTER TABLE [dbo].[FORM_EXE_UTENTE] ADD  CONSTRAINT [DF_FORM_EXE_UTENTE_UTENTE]  DEFAULT ('') FOR [UTENTE]
GO

ALTER TABLE [dbo].[FORM_EXE_UTENTE] ADD  CONSTRAINT [DF_FORM_EXE_UTENTE_DESPROC]  DEFAULT ('') FOR [DESPROC]
GO

ALTER TABLE [dbo].[FORM_EXE_UTENTE] ADD  CONSTRAINT [DF_FORM_EXE_UTENTE_NOMEFORMEXE]  DEFAULT ('') FOR [NOMEFORMEXE]
GO




DELETE FROM FORM_EXE_UTENTE 

INSERT INTO FORM_EXE_UTENTE (UTENTE,NOMEPROC,DESPROC,NOMEFORMEXE) VALUES ('SER','MENU_PRIMANOT','PRIMA NOTA STANDARD : MENU_PRIMANOT ; PRIMA NOTA NUOVA RELEASE CON AGGIORNAMENTO GRIGLIE : MENU_PRIMA_NOTA','')