


ALTER TABLE [dbo].[FORM_EXE] DROP CONSTRAINT [DF_FORM_EXE_NOMEFORMEXE]
GO

ALTER TABLE [dbo].[FORM_EXE] DROP CONSTRAINT [DF_FORM_EXE_DESPROC]
GO

ALTER TABLE [dbo].[FORM_EXE] DROP CONSTRAINT [DF_FORM_EXE_NOMEPROC]
GO

ALTER TABLE [dbo].[FORM_EXE] DROP CONSTRAINT [DF_FORM_EXE_id_unique]
GO

/****** Object:  Table [dbo].[FORM_EXE]    Script Date: 27/04/2015 17.46.34 ******/
DROP TABLE [dbo].[FORM_EXE]
GO

/****** Object:  Table [dbo].[FORM_EXE]    Script Date: 27/04/2015 17.46.34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FORM_EXE](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[NOMEPROC] [varchar](50) NULL,
	[DESPROC] [text] NULL,
	[NOMEFORMEXE] [varchar](50) NULL,
 CONSTRAINT [PK_FORM_EXE] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FORM_EXE] ADD  CONSTRAINT [DF_FORM_EXE_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[FORM_EXE] ADD  CONSTRAINT [DF_FORM_EXE_NOMEPROC]  DEFAULT ('') FOR [NOMEPROC]
GO

ALTER TABLE [dbo].[FORM_EXE] ADD  CONSTRAINT [DF_FORM_EXE_DESPROC]  DEFAULT ('') FOR [DESPROC]
GO

ALTER TABLE [dbo].[FORM_EXE] ADD  CONSTRAINT [DF_FORM_EXE_NOMEFORMEXE]  DEFAULT ('') FOR [NOMEFORMEXE]
GO




DELETE FROM FORM_EXE 

INSERT INTO FORM_EXE (NOMEPROC,DESPROC,NOMEFORMEXE) VALUES ('MENU_PRIMANOT','PRIMA NOTA STANDARD : MENU_PRIMANOT PRIMA NOTA AGGIORNAMENTO GRIGLIE : MENU_PRIMANOTA','')