
-------------------------------------------
--- ACCESSO PER ARTICOLO 
-------------------------------------------

--- (1) QUERY PER TROVARE GLI ARTICOLI CON GIACENZA NEGATIVA
--- ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * FROM (
SELECT 
	MOV_ANAART AS CODART,
	MOV_UM AS UM,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS QTA
FROM U_MAG_MO
WHERE MOV_TOP <> 'M++'
GROUP BY MOV_ANAART,MOV_UM ) AS GIAC
WHERE QTA <0

--- (2) QUERY PER TROVARE I MOVIMENTI DEGLI ARTICOLI OTTENUTI DALLA QUERY (1)
--- SEMPRE ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * 
FROM U_MAG_MO 
WHERE MOV_TOP <> 'M++' 
	AND  MOV_ANAART IN (
		SELECT CODART  FROM (
			SELECT 
				MOV_ANAART AS CODART,
				MOV_UM AS UM,
				SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS QTA
			FROM U_MAG_MO
			WHERE MOV_TOP <> 'M++'
			GROUP BY MOV_ANAART,MOV_UM ) AS GIAC
			WHERE QTA <0 ) 
ORDER BY MOV_DTDOCU,MOV_ORAMOV


-------------------------------------------
--- ACCESSO PER ARTICOLO + CODICE MAGAZZINO
-------------------------------------------

--- (1) QUERY PER TROVARE GLI ARTICOLI CON GIACENZA NEGATIVA
--- ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * FROM (
SELECT 
	MOV_ANAART AS CODART,
	MOV_CODMAG AS CODMAG,
	MOV_UM AS UM,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS QTA
FROM U_MAG_MO
WHERE MOV_TOP <> 'M++'
GROUP BY MOV_ANAART,MOV_CODMAG,MOV_UM ) AS GIAC
WHERE QTA <0

--- (2) QUERY PER TROVARE I MOVIMENTI DEGLI ARTICOLI OTTENUTI DALLA QUERY (1)
--- SEMPRE ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * 
FROM U_MAG_MO 
WHERE MOV_TOP <> 'M++' 
	AND  MOV_ANAART IN (
		SELECT CODART  FROM (
			SELECT 
				MOV_ANAART AS CODART,
				MOV_CODMAG AS CODMAG,
				MOV_UM AS UM,
				SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS QTA
			FROM U_MAG_MO
			WHERE MOV_TOP <> 'M++'
			GROUP BY MOV_ANAART,MOV_CODMAG,MOV_UM ) AS GIAC
			WHERE QTA <0) 
ORDER BY MOV_DTDOCU,MOV_ORAMOV






