
/****** Object:  Index [IDX_PRODUZIONE_01]    Script Date: 04/05/2018 16:10:01 ******/
CREATE NONCLUSTERED INDEX [IDX_PRODUZIONE_01] ON [dbo].[PRODUZIONE]
(
	[IDPRG] ASC,
	[PARENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


