
/****** Object:  Index [INDICE_08]    Script Date: 05/12/2018 10:51:35 ******/
CREATE NONCLUSTERED INDEX [INDICE_08] ON [dbo].[U_FAT_DD]
(
	[ORS_NUMORC] ASC,
	[ORS_DATORC] ASC,
	[ORD_DESART] ASC
)
INCLUDE ([DAGGANCIO],[ORS_NUMORD],[ORS_DATORD]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


