
/****** Object:  Index [IDX_MOV_DTREG_CONTO_TOP]    Script Date: 26/09/2018 14:44:12 ******/
CREATE NONCLUSTERED INDEX [IDX_MOV_DTREG_CONTO_TOP] ON [dbo].[MOV_CONT]
(
	[MOV_DTREG] ASC,
	[MOV_CONTO] ASC,
	[MOV_TOP] ASC
)
INCLUDE (
	[MOV_ANNO],
	[MOV_NREGIS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


