/****** Object:  Index [U_ART_DO]    Script Date: 08/08/2017 11:45:11 ******/
CREATE NONCLUSTERED INDEX [U_ART_DO] ON [dbo].[U_ART_PR]
(
	[ART_CODSOC] ASC,
	[ART_DESCR] ASC,
	[ART_OBSOL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


