
/****** Object:  Index [IDX_PROD_CARICHI_02]    Script Date: 04/05/2018 15:32:05 ******/
CREATE NONCLUSTERED INDEX [IDX_PROD_CARICHI_02] ON [dbo].[PROD_CARICHI]
(
	[IDBANC] ASC,
	[NUMBAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


