
/****** Object:  Index [IDX_LOG_EVENTI_01]    Script Date: 04/05/2018 15:32:55 ******/
CREATE NONCLUSTERED INDEX [IDX_LOG_EVENTI_01] ON [dbo].[LOG_EVENTI]
(
	[COD_USER] ASC,
	[RUOLO_DEST] ASC,
	[STATO_EVENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


