
/****** Object:  Index [INDICE_46]    Script Date: 25/03/2014 09:57:13 ******/

if exists (select * from sys.indexes where name = 'INDICE_46' and object_id = object_id(N'[dbo].[U_MAG_GG]'))
	DROP INDEX INDICE_46 ON U_MAG_GG
GO

CREATE NONCLUSTERED INDEX [INDICE_46] ON [dbo].[U_MAG_GG]
(
	[MAG_CODSOC] ASC,
	[MAG_DATAGG] ASC,
	[MAG_ANAART] ASC,
	[MAG_CODMAG] ASC,
	[MAG_PRENOT] ASC,
	[MAG_GIACEN] ASC,
	[MAG_QTAIMP] ASC,
	[MAG_CODART] ASC,
	[MAG_ALTEZZ] ASC,
	[MAG_LUNGHE] ASC,
	[MAG_FILA_X] ASC,
	[MAG_PIAN_X] ASC,
	[MAG_UBIC_X] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
