
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_CT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IMPIANTI_CT]
GO  


CREATE TABLE [dbo].[IMPIANTI_CT](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_CT_id_unique] DEFAULT (newid()),
	[TIPO_COMPONENTE]	varchar(5) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_TIPO_COMPONENTE] DEFAULT (''),
	[ID_RIGA_CONF]		varchar(10) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_ID_RIGA_CONF] DEFAULT (''),
	[ORDINAMENTO]		numeric(3,0) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_ORDINAMENTO] DEFAULT (0),
	[DESCRIZIONE]		varchar(100) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_DESCRIZIONE] DEFAULT (''),
	[TIPO]				varchar(1) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_TIPO] DEFAULT (''),
	[DIMENSIONE]		numeric(3,0) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_DIMENSIONE] DEFAULT (0),
	[DECIMALI]			numeric(1,0) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_DECIMALI] DEFAULT (0),
	[VALORI_PREIMP]		text NOT NULL CONSTRAINT [DF_IMPIANTI_CT_VALORI_PREIMP] DEFAULT (''),
	[NOME_X_REPORT]		varchar(20) NOT NULL CONSTRAINT [DF_IMPIANTI_CT_NOME_X_REPORT] DEFAULT ('')
) 

ALTER TABLE [dbo].[IMPIANTI_CT] WITH NOCHECK ADD 
	CONSTRAINT [PK_IMPIANTI_CT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
