
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_CC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IMPIANTI_CC]
GO  


CREATE TABLE [dbo].[IMPIANTI_CC](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_CC_id_unique] DEFAULT (newid()),
	[CCODSCHE]        	varchar(20) NULL CONSTRAINT [DF_IMPIANTI_CC_CCODSCHE] DEFAULT (''),
	[ID_PMKEY]        	varchar(10) NULL CONSTRAINT [DF_IMPIANTI_CC_ID_PMKEY] DEFAULT (''),
	[ID_RIGO]         	varchar(5) NULL CONSTRAINT [DF_IMPIANTI_CC_ID_RIGO] DEFAULT (''),
	[TIPO_COMPONENTE]	varchar(5) NOT NULL CONSTRAINT [DF_IMPIANTI_CC_TIPO_COMPONENTE] DEFAULT (''),
	[LINKCOMP]			varchar(10) NOT NULL CONSTRAINT [DF_IMPIANTI_CC_LINKCOMP] DEFAULT (''),
	[ID_RIGA_CONF]		varchar(10) NOT NULL CONSTRAINT [DF_IMPIANTI_CC_ID_RIGA_CONF] DEFAULT (''),
	[VALORE]			varchar(254) NOT NULL CONSTRAINT [DF_IMPIANTI_CC_VALORE] DEFAULT (''),
	[VALORE_MEMO]		text NOT NULL CONSTRAINT [DF_IMPIANTI_CC_VALORE_MEMO] DEFAULT ('')
) 

ALTER TABLE [dbo].[IMPIANTI_CC] WITH NOCHECK ADD
	CONSTRAINT [PK_IMPIANTI_CC] PRIMARY KEY  CLUSTERED
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
