
/****** Object:  Table [dbo].[IMPIANTI_LG]    Script Date: 19/02/2016 17:14:01 ******/
/****** LOG_KEY: LOG_CODOPE+LOG_CODLIS+LOG_CODMANU+LOG_ZONA+LOG_DATAINI+LOG_DATAFIN+LOG_DATINI_BV+LOG_DATFIN_BV ******/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_LG]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IMPIANTI_LG]
GO  

/****** Object:  Table [dbo].[IMPIANTI_LG]    Script Date: 19/02/2016 17:14:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[IMPIANTI_LG](
	[id_unique]      [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_LG_id_unique]  DEFAULT (newid()),
	[SELEZI] bit NOT NULL CONSTRAINT [DF_IMPIANTI_LG_SELEZI] DEFAULT (0),
	[LOG_KEY]        [varchar](150) NULL,
	[LOG_CODOPE]     [varchar](20) NULL,
    [LOG_DATREG]     [varchar](10) NULL,
    [LOG_ORAREG]     [varchar](8) NULL,
    [LOG_ESTRAZIONE] [varchar](200) NULL,
	[LOG_CODLIS]     [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_LGS_CODLIS]  DEFAULT (''),
	[LOG_CODMANU]    [varchar](10) NULL,
	[LOG_ZONA]       [varchar](6) NULL,
	[LOG_DATAINI]    [varchar](10) NULL,
	[LOG_DATAFIN]    [varchar](10) NULL,
	[LOG_DATINI_ORD] [varchar](10) NULL,
	[LOG_DATFIN_ORD] [varchar](10) NULL,
	[LOG_STACON]     [varchar](10) NULL,
	[LOG_DESSTACON]  [varchar](30) NULL,
	[LOG_SOLO_COMPONENTI_CON_INTERVENTI_GENERATI] bit NOT NULL CONSTRAINT [DF_IMPIANTI_LG_LOG_SOLO_COMPONENTI_CON_INTERVENTI_GENERATI] DEFAULT (0),
	[LOG_SOLO_COMPONENTI_SENZA_INTERVENTI_GENERATI] bit NOT NULL CONSTRAINT [DF_IMPIANTI_LG_LOG_SENZA_COMPONENTI_CON_INTERVENTI_GENERATI] DEFAULT (0),
	[LIS_NOTE]      [text] NULL CONSTRAINT [DF_IMPIANTI_LI_LOG_NOTE]  DEFAULT (''),
 CONSTRAINT [PK_IMPIANTI_LG] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

