

/****** Object:  Table [dbo].[IMPIANTI_DD]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IMPIANTI_DD]
GO  


CREATE TABLE [dbo].[IMPIANTI_DD](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_DD_id_unique] DEFAULT (newid()),
	[ID_PMKEY]        [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_ID_PMKEY] DEFAULT (''),            
	[CCODSCHE]        [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_DD_CCODSCHE] DEFAULT (''),
	[ID_RIGO]         [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_DD_ID_RIGO] DEFAULT (''), 
	[TIPO_COMPONENTE] [varchar](03) NULL CONSTRAINT [DF_IMPIANTI_DD_TIPO_COMPONENTE] DEFAULT (''),            
	[CSETTORE]        [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_DD_CSETTORE] DEFAULT (''), 
	[CTELCONTRO]      [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_DD_CTELCONTRO] DEFAULT (''), 
	[CDITTACAL]       [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_DD_CDITTACAL] DEFAULT (''), 
	[CMODCAL]         [varchar](25) NULL CONSTRAINT [DF_IMPIANTI_DD_CMODCAL] DEFAULT (''), 
	[CMATCAL]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_DD_CMATCAL] DEFAULT (''), 
	[CCALCAL]         [Numeric](10) NULL, 
	[CDITTABRU]       [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_DD_CDITTABRU] DEFAULT (''), 
	[CMODBRU]         [varchar](25) NULL CONSTRAINT [DF_IMPIANTI_DD_CMODBRU] DEFAULT (''), 
	[CMATBRU]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_DD_CMATBRU] DEFAULT (''), 
	[COD_PRODUT]      [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_DD_COD_PRODUT] DEFAULT (''), 
	[DT_INSTALL]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_INSTALL] DEFAULT (''), 
	[CNOTE]           [varchar](254) NULL CONSTRAINT [DF_IMPIANTI_DD_CNOTE] DEFAULT (''),
	[CNOTE1]          [varchar](100) NULL CONSTRAINT [DF_IMPIANTI_DD_CNOTE1] DEFAULT (''), 
	[CNOTE2]          [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_DD_CNOTE2] DEFAULT (''),  
	[CNOTE3]          [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_DD_CNOTE3] DEFAULT (''),  
	[DISMESSA]        [bit] NULL,
	[DT_DISMESS]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_DISMESS] DEFAULT (''), 
	[ANNO_CONTR]      [varchar](4) NULL CONSTRAINT [DF_IMPIANTI_DD_ANNO_CONTR] DEFAULT (''), 
	[CONTRATTO]       [varchar](30) NULL CONSTRAINT [DF_IMPIANTI_DD_CONTRATTO] DEFAULT (''), 
	[CINIZCONTR]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_CINIZCONTR] DEFAULT (''), 
	[CSCADCONTR]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_CSCADCONTR] DEFAULT (''), 
	[CFLAGGARNZ]      [varchar](1) NULL CONSTRAINT [DF_IMPIANTI_DD_CFLAGGARNZ] DEFAULT (''),
	[CDAINGARNZ]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_CDAINGARNZ] DEFAULT (''), 
	[CDAFIGARNZ]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_CDAFIGARNZ] DEFAULT (''), 
	[CFLAGGARZ]       [bit] NULL,            
	[DT_CONFERM]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_CONFERM] DEFAULT (''), 
	[DT_DISDETT]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_DISDETT] DEFAULT (''), 
	[DT_INIZIO]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_INIZIO] DEFAULT (''), 
	[DT_FINE]         [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_FINE] DEFAULT (''), 
	[CRINNOVARE]      [bit] NULL,
	[DT_INIZ_BV]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_INIZ_BV] DEFAULT (''), 
	[DT_SCAD_BV]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_SCAD_BV] DEFAULT (''), 
	[DT_ACCENSIONE]   [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_ACCENSIONE] DEFAULT (''), 
	[DT_ULT_RISTRUTT] [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_ULT_RISTRUTT] DEFAULT (''), 
	[DT_ULT_MAN]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_DT_ULT_MAN] DEFAULT (''), 
	[BRU_DT_INSTALL]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_BRU_DT_INSTALL] DEFAULT (''), 
	[BRU_CDAINGARNZ]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_BRU_CDAINGARNZ] DEFAULT (''), 
	[BRU_CDAFIGARNZ]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_DD_BRU_CDAFIGARNZ] DEFAULT (''), 
	[ID_CLASSIF]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_DD_ID_CLASSIF] DEFAULT ('')
) 

ALTER TABLE [dbo].[IMPIANTI_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_IMPIANTI_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


