

/****** Object:  Table [dbo].[IMPIANTI_NO]  GESTIONE RIFERIMENTI IMPIANTI ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_NO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[c]
GO  
              

CREATE TABLE [dbo].[IMPIANTI_NO](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_NO_id_unique] DEFAULT (newid()),
	[ID_PMKEY]        [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_ID_PMKEY] DEFAULT (''),            
	[CCODSCHE]        [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_NO_CCODSCHE] DEFAULT (''),
	[PK_CATASTO]      [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_NO_PK_CATASTO] DEFAULT (''), 
	[TIPO_IMPIA]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_TIPO_IMPIA] DEFAULT (''), 
	[CT]			  [bit] NULL,
	[CSETTORE]        [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_NO_CSETTORE] DEFAULT (''), 
	[CTELCONTRO]      [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_NO_CTELCONTRO] DEFAULT (''),
	[CCODCLI]         [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_CCODCLI] DEFAULT (''), 
	[OLD_CCODCLI]     [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_OLD_CCODCLI] DEFAULT (''), 
	[CINDINS]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CINDINS] DEFAULT (''),
	[CLOCINS]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CLOCINS] DEFAULT (''),
	[CPROINS]         [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_NO_CPROINS] DEFAULT (''),
	[CCAPINS]         [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_NO_CCAPINS] DEFAULT (''), 
	[CZONAINS]        [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_NO_CZONAINS] DEFAULT (''), 
	[CRAGSOC]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CRAGSOC] DEFAULT (''), 
	[CRAGSOC1]        [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CRAGSOC1] DEFAULT (''), 
	[CINDDES]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CINDDES] DEFAULT (''), 
	[CLOCDES]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_NO_CLOCDES] DEFAULT (''),
	[CPRODES]         [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_NO_CPRODES] DEFAULT (''),
	[CCAPDES]         [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_NO_CCAPDES] DEFAULT (''), 
	[CTELDES]         [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_CTELDES] DEFAULT (''), 
	[CFAXDES]         [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_CFAXDES] DEFAULT (''), 
 	[CTE]             [varchar](254) NULL CONSTRAINT [DF_IMPIANTI_NO_CTE] DEFAULT (''), 
	[CTE1]            [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_CTE1] DEFAULT (''), 
	[CTE2]            [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_CTE2] DEFAULT (''), 
	[DIR_FISSO]       [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_DIR_FISSO] DEFAULT (''), 
	[COD_RIF_01]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_01] DEFAULT (''), 
	[DEX_RIF_01]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_01] DEFAULT (''), 
	[COD_RIF_02]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_02] DEFAULT (''), 
	[DEX_RIF_02]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_02] DEFAULT (''), 
	[COD_RIF_03]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_03] DEFAULT (''), 
	[DEX_RIF_03]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_03] DEFAULT (''), 
	[COD_RIF_04]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_04] DEFAULT (''), 
	[DEX_RIF_04]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_04] DEFAULT (''), 
	[COD_RIF_05]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_05] DEFAULT (''), 
	[DEX_RIF_05]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_05] DEFAULT (''), 
	[COD_RIF_06]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_06] DEFAULT (''), 
	[DEX_RIF_06]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_06] DEFAULT (''), 
	[COD_RIF_07]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_07] DEFAULT (''), 
	[DEX_RIF_07]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_07] DEFAULT (''), 
	[COD_RIF_08]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_08] DEFAULT (''), 
	[DEX_RIF_08]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_08] DEFAULT (''), 
	[COD_RIF_09]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_RIF_09] DEFAULT (''), 
	[DEX_RIF_09]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_NO_DEX_RIF_09] DEFAULT (''), 
	[MEMO_1]          [text] COLLATE Latin1_General_CI_AS NULL ,
	[DT_REGIST]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_DT_REGIST] DEFAULT (''), 
	[ORA_REGIST]      [varchar](8) NULL CONSTRAINT [DF_IMPIANTI_NO_ORA_REGIST] DEFAULT (''), 
	[COD_AMMIN]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_COD_AMMIN] DEFAULT (''), 
	[CNUMFATT]        [Numeric](6) NULL,       
	[CDATAFATT]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_NO_CDATAFATT] DEFAULT (''), 
	[TIPO_CARBU]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_NO_TIPO_CARBU] DEFAULT (''), 
	[VOLUMETRIA]      [Numeric](19,5) NULL,       
	[ID_TIPOANG]      [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_NO_ID_TIPOANG] DEFAULT (''), 
	[ID_RESPONS]      [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_NO_ID_RESPONS] DEFAULT (''), 
	[ID_PROPRIE]      [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_NO_ID_PROPRIE] DEFAULT ('')
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[IMPIANTI_NO] WITH NOCHECK ADD 
	CONSTRAINT [PK_IMPIANTI_NO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO





  