

/****** Object:  Table [dbo].[IMPIANTI_TT]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IMPIANTI_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IMPIANTI_TT]
GO  


CREATE TABLE [dbo].[IMPIANTI_TT](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_IMPIANTI_TT_id_unique] DEFAULT (newid()),
	[ID_PMKEY]        [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_ID_PMKEY] DEFAULT (''),            
	[CCODSCHE]        [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_TT_CCODSCHE] DEFAULT (''),
	[TIPO_IMPIA]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_ID_RIGO] DEFAULT (''), 
	[PK_CATASTO]      [varchar](23) NULL CONSTRAINT [DF_IMPIANTI_TT_PK_CATASTO] DEFAULT (''),            
	[CSETTORE]        [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_TT_CSETTORE] DEFAULT (''), 
	[CTELCONTRO]      [varchar](20) NULL CONSTRAINT [DF_IMPIANTI_TT_CTELCONTRO] DEFAULT (''), 
	[CCODCLI]         [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_CCODCLI] DEFAULT (''), 
	[CINDINS]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CINDINS] DEFAULT (''),
	[CLOCINS]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CLOCINS] DEFAULT (''), 
	[CPROINS]         [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_TT_CPROINS] DEFAULT (''), 
	[CCAPINS]         [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_TT_CCAPINS] DEFAULT (''),
	[CZONAINS]        [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_TT_CZONAINS] DEFAULT (''),
	[CRAGSOC]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CRAGSOC] DEFAULT (''),
	[CRAGSOC1]        [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CRAGSOC1] DEFAULT (''), 
	[CINDDES]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CINDDES] DEFAULT (''), 
	[CLOCDES]         [varchar](40) NULL CONSTRAINT [DF_IMPIANTI_TT_CLOCDES] DEFAULT (''), 
	[CPRODES]         [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_TT_CPRODES] DEFAULT (''), 
	[CCAPDES]         [varchar](5) NULL CONSTRAINT [DF_IMPIANTI_TT_CCAPDES] DEFAULT (''), 
	[CTELDES]         [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_CTELDES] DEFAULT (''),
	[CFAXDES]         [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_CFAXDES] DEFAULT (''),
	[CNOTE]           [varchar](254) NULL CONSTRAINT [DF_IMPIANTI_TT_CNOTE] DEFAULT (''),
	[CNOTE1]          [varchar](100) NULL CONSTRAINT [DF_IMPIANTI_TT_CNOTE1] DEFAULT (''), 
	[CNOTE2]          [varchar](100) NULL CONSTRAINT [DF_IMPIANTI_TT_CNOTE2] DEFAULT (''),  
	[DIR_FISSO]       [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_DIR_FISSO] DEFAULT (''), 
	[COD_RIF_01]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_01] DEFAULT (''),
	[DEX_RIF_01]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_01] DEFAULT (''),
	[COD_RIF_02]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_02] DEFAULT (''),
	[DEX_RIF_02]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_02] DEFAULT (''), 
	[COD_RIF_03]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_03] DEFAULT (''),
	[DEX_RIF_03]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_03] DEFAULT (''), 
	[COD_RIF_04]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_04] DEFAULT (''),
	[DEX_RIF_04]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_04] DEFAULT (''), 
	[COD_RIF_05]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_05] DEFAULT (''),
	[DEX_RIF_05]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_05] DEFAULT (''), 
	[COD_RIF_06]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_06] DEFAULT (''),
	[DEX_RIF_06]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_06] DEFAULT (''), 
	[COD_RIF_07]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_07] DEFAULT (''),
	[DEX_RIF_07]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_07] DEFAULT (''), 
	[COD_RIF_08]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_08] DEFAULT (''),
	[DEX_RIF_08]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_08] DEFAULT (''), 
	[COD_RIF_09]      [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_RIF_09] DEFAULT (''),  
	[DEX_RIF_09]      [varchar](50) NULL CONSTRAINT [DF_IMPIANTI_TT_DEX_RIF_09] DEFAULT (''), 
	[DT_REGIST]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_DT_REGIST] DEFAULT (''), 
	[ORA_REGIST]      [varchar](8) NULL CONSTRAINT [DF_IMPIANTI_TT_ORA_REGIST] DEFAULT (''), 
	[COD_AMMIN]       [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_TT_COD_AMMIN] DEFAULT (''), 
	[MEMO_1]          [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_MEMO_1] DEFAULT (''), 
	[CNUMFATT]        [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_TT_CNUMFATT] DEFAULT (''), 
	[CDATAFATT]       [varchar](10) NULL CONSTRAINT [DF_IMPIANTI_TT_DT_CDATAFATT] DEFAULT (''), 
	[TIPO_CARBU]      [varchar](3) NULL CONSTRAINT [DF_IMPIANTI_TT_TIPO_CARBU] DEFAULT (''),
	[VOLUMETRIA]      [Numeric](19,5) NULL,       
	[ID_TIPOANG]      [varchar](2) NULL CONSTRAINT [DF_IMPIANTI_TT_ID_ID_TIPOANG] DEFAULT (''),
	[ID_RESPONS]      [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_TT_ID_RESPONS] DEFAULT (''),
	[ID_PROPRIE]      [varchar](6) NULL CONSTRAINT [DF_IMPIANTI_TT_ID_PROPRIE] DEFAULT ('')
) 

ALTER TABLE [dbo].[IMPIANTI_TT] WITH NOCHECK ADD 
	CONSTRAINT [PK_IMPIANTI_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


