
/****** Object:  Index [SELE_CLI01]    Script Date: 16/04/2014 17.01.21 ******/
CREATE NONCLUSTERED INDEX [SELE_CLI01] ON [dbo].[PART_CLI]
(
	[PAR_CODSOC] ASC,
	[PAR_CODCLI] ASC,
	[PAR_TIPODO] ASC,
	[PAR_NPROG] ASC,
	[PAR_TIPFAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
