IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'U_BFO_DD_CBF_NUMPRO')
    DROP INDEX U_BFO_DD_CBF_NUMPRO ON U_BFO_DD;
GO

CREATE INDEX U_BFO_DD_CBF_NUMPRO ON U_BFO_DD ( CBF_NUMPRO ) 


GO


IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'U_BFO_DD_NUMPRO')
    DROP INDEX U_BFO_DD_NUMPRO ON U_BFO_DD;
GO

CREATE INDEX U_BFO_DD_NUMPRO ON U_BFO_DD ( CBF_NUMPRO ) 


GO