IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'INDICE_NREGIS')
    DROP INDEX INDICE_NREGIS ON INDICE;
GO

CREATE INDEX INDICE_NREGIS ON INDICE ( MOV_SOC,MOV_ANNO,MOV_NREGIS,MOV_NUMPRO ) 


GO