
/****** Oggetto:  Index [U_ART_N12345] ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[U_ART_PR]') AND name = N'U_ART_N12345')
DROP INDEX [U_ART_N12345] ON [dbo].[U_ART_PR] WITH ( ONLINE = OFF )
GO

/****** Object:  Index [U_ART_N12345] ******/
CREATE NONCLUSTERED INDEX [U_ART_N12345] ON [dbo].[U_ART_PR]
(
	[ART_CODSOC] ASC,
	[ART_NOTA1] ASC,
	[ART_NOTA2] ASC,
	[ART_NOTA3] ASC,
	[ART_NOTA4] ASC,
	[ART_NOTA5] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


