
/****** Object:  Index [INDEX_02]    Script Date: 06/05/2026 15:43:19 ******/
CREATE NONCLUSTERED INDEX [INDEX_02] ON [dbo].[IMPIANTI_DD]
(
	[ID_PMKEY] ASC,
	[CCODSCHE] ASC,
	[ID_RIGO] ASC,
	[TIPO_COMPONENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


