IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'GIACENZE_DA_MOVIMENTI')
    DROP INDEX CARICHI ON U_MAG_MO;
GO

/****** Oggetto:  Index [GIACENZE_DA_MOVIMENTI]    Data script: 12/21/2012 14:25:25 ******/
CREATE NONCLUSTERED INDEX [GIACENZE_DA_MOVIMENTI] ON [dbo].[U_MAG_MO] 
(
	[MOV_DTREGI] ASC,
	[MOV_ANAART] ASC,
	[MOV_SEGNO] ASC,
	[MOV_UM] ASC,
	[MOV_QTAMOV] ASC,
	[MOV_VALACQ] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO