IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'ULT_CAR_SCAR')
    DROP INDEX ULT_CAR_SCAR ON U_MAG_MO;
GO


CREATE NONCLUSTERED INDEX [ULT_CAR_SCAR] ON [dbo].[U_MAG_MO] 
([MOV_SEGNO],[MOV_ANAART],[MOV_PRSPOT],[MOV_TOP],[MOV_NUMDOC],[MOV_DTREGI])
INCLUDE ([MOV_DTDOCU],[MOV_QTAMOV],[MOV_PREACQ],[MOV_VALUTA],[MOV_ORAMOV],[MOV_LEGAME])
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO