if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[INDICE_XML]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[INDICE_XML]
GO
 
CREATE TABLE [dbo].[INDICE_XML] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	MOV_SYSDOC varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	MOV_CONTO varchar(16) COLLATE Latin1_General_CI_AS NULL ,
	MOV_CODART varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	MOV_DESART varchar(250) COLLATE Latin1_General_CI_AS NULL ,
	MOV_IMPORTO numeric(17,3) NULL
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[INDICE_XML] WITH NOCHECK ADD 
	CONSTRAINT [PK_INDICE_XML] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[INDICE_XML] WITH NOCHECK ADD 
	CONSTRAINT [DF_INDICE_XML_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_INDICE_XML_MOV_SYSDOC] DEFAULT ('') FOR [MOV_SYSDOC],
	CONSTRAINT [DF_INDICE_XML_MOV_CONTO] DEFAULT ('') FOR [MOV_CONTO],
	CONSTRAINT [DF_INDICE_XML_MOV_CODART] DEFAULT ('') FOR [MOV_CODART],
	CONSTRAINT [DF_INDICE_XML_MOV_DESART] DEFAULT ('') FOR [MOV_DESART],
	CONSTRAINT [DF_INDICE_XML_MOV_IMPORTO] DEFAULT (0) FOR [MOV_IMPORTO]
GO

