
/****** Object:  Index [INDICE_06]    Script Date: 28/02/2018 15:14:14 ******/
CREATE NONCLUSTERED INDEX [INDICE_06] ON [dbo].[U_FAT_DD]
(
	[ORD_CODART] ASC,
	[ORS_NUMDDT] ASC,
	[ORS_DATDDT] ASC
)
INCLUDE ( 	[ORS_NUMORD],
	[ORS_DATORD]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


