
/****** Object:  Index [ACQ_VEN]    Script Date: 11/02/2016 19:06:37 ******/
DROP INDEX [ACQ_VEN] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [ACQ_VEN]    Script Date: 11/02/2016 19:06:37 ******/
CREATE NONCLUSTERED INDEX [ACQ_VEN] ON [dbo].[S_MAG_MO]
(
	[MOV_DTDOCU] ASC,
	[MOV_ANAART] ASC,
	[MOV_SEGNO] ASC,
	[MOV_UM] ASC,
	[MOV_QTAMOV] ASC,
	[MOV_VALACQ] ASC,
	[MOV_VALVEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [CARICHI]    Script Date: 11/02/2016 19:31:13 ******/
DROP INDEX [CARICHI] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [CARICHI]    Script Date: 11/02/2016 19:31:13 ******/
CREATE NONCLUSTERED INDEX [CARICHI] ON [dbo].[S_MAG_MO]
(
	[MOV_DTDOCU] ASC,
	[MOV_ANAART] ASC,
	[MOV_SEGNO] ASC,
	[MOV_UM] ASC,
	[MOV_QTAMOV] ASC,
	[MOV_VALACQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [CODART]    Script Date: 11/02/2016 19:31:53 ******/
DROP INDEX [CODART] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [CODART]    Script Date: 11/02/2016 19:31:53 ******/
CREATE NONCLUSTERED INDEX [CODART] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [CODPDV]    Script Date: 11/02/2016 19:32:20 ******/
DROP INDEX [CODPDV] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [CODPDV]    Script Date: 11/02/2016 19:32:20 ******/
CREATE NONCLUSTERED INDEX [CODPDV] ON [dbo].[S_MAG_MO]
(
	[MOV_CODPDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [DTREG]    Script Date: 11/02/2016 19:32:48 ******/
DROP INDEX [DTREG] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [DTREG]    Script Date: 11/02/2016 19:32:48 ******/
CREATE NONCLUSTERED INDEX [DTREG] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_DTREGI] ASC,
	[MOV_CODART] ASC,
	[MOV_TOP] ASC,
	[MOV_CODFOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [GIANEG]    Script Date: 11/02/2016 19:33:11 ******/
DROP INDEX [GIANEG] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [GIANEG]    Script Date: 11/02/2016 19:33:11 ******/
CREATE NONCLUSTERED INDEX [GIANEG] ON [dbo].[S_MAG_MO]
(
	[MOV_LEGAME] ASC,
	[MOV_GIANEG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [I_TROVDEL]    Script Date: 11/02/2016 19:33:30 ******/
DROP INDEX [I_TROVDEL] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [I_TROVDEL]    Script Date: 11/02/2016 19:33:30 ******/
CREATE NONCLUSTERED INDEX [I_TROVDEL] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_CODART] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_TOP] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDEX_01]    Script Date: 11/02/2016 19:33:48 ******/
DROP INDEX [INDEX_01] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDEX_01]    Script Date: 11/02/2016 19:33:48 ******/
CREATE NONCLUSTERED INDEX [INDEX_01] ON [dbo].[S_MAG_MO]
(
	[MOV_CODMAG] ASC,
	[MOV_FILA_N] ASC,
	[MOV_PIAN_N] ASC,
	[MOV_UBIC_N] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDEX_02]    Script Date: 11/02/2016 19:34:06 ******/
DROP INDEX [INDEX_02] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDEX_02]    Script Date: 11/02/2016 19:34:06 ******/
CREATE NONCLUSTERED INDEX [INDEX_02] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_ANAART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_ALTEZZ] ASC,
	[MOV_LUNGHE] ASC,
	[MOV_LEGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [INDEX_03]    Script Date: 11/02/2016 19:34:25 ******/
DROP INDEX [INDEX_03] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDEX_03]    Script Date: 11/02/2016 19:34:25 ******/
CREATE NONCLUSTERED INDEX [INDEX_03] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_DTREGI] ASC,
	[MOV_SPESSO] ASC,
	[MOV_ALTEZZ] ASC,
	[MOV_LUNGHE] ASC,
	[MOV_ANAART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_FORNIT] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_TOP] ASC,
	[MOV_CODMAT] ASC,
	[MOV_PREVEN] ASC,
	[MOV_CLIENT] ASC,
	[MOV_DOCMOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDEX_04]    Script Date: 11/02/2016 19:34:44 ******/
DROP INDEX [INDEX_04] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDEX_04]    Script Date: 11/02/2016 19:34:44 ******/
CREATE NONCLUSTERED INDEX [INDEX_04] ON [dbo].[S_MAG_MO]
(
	[MOV_CODART] ASC,
	[MOV_SEGNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [INDICE_01]    Script Date: 11/02/2016 19:35:02 ******/
DROP INDEX [INDICE_01] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_01]    Script Date: 11/02/2016 19:35:02 ******/
CREATE NONCLUSTERED INDEX [INDICE_01] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_FORNIT] ASC,
	[MOV_CODACQ] ASC,
	[MOV_PREACQ] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_CODBUN] ASC,
	[MOV_ANNO] ASC,
	[MOV_DATSCA] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_02]    Script Date: 11/02/2016 19:35:32 ******/
DROP INDEX [INDICE_02] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_02]    Script Date: 11/02/2016 19:35:32 ******/
CREATE NONCLUSTERED INDEX [INDICE_02] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_FORNIT] ASC,
	[MOV_CODACQ] ASC,
	[MOV_PRZCON] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_CODBUN] ASC,
	[MOV_ANNO] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_03]    Script Date: 11/02/2016 19:35:52 ******/
DROP INDEX [INDICE_03] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_03]    Script Date: 11/02/2016 19:35:52 ******/
CREATE NONCLUSTERED INDEX [INDICE_03] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAT] ASC,
	[MOV_CODCOL] ASC,
	[MOV_SPESSO] ASC,
	[MOV_ALTEZZ] ASC,
	[MOV_LUNGHE] ASC,
	[MOV_ANAART] ASC,
	[MOV_NRLINT] ASC,
	[MOV_CODMAG] ASC,
	[MOV_FORNIT] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_ANNO] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_TOP] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_04]    Script Date: 11/02/2016 19:36:37 ******/
DROP INDEX [INDICE_04] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_04]    Script Date: 11/02/2016 19:36:37 ******/
CREATE NONCLUSTERED INDEX [INDICE_04] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_TOP] ASC,
	[MOV_CODFOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_05]    Script Date: 11/02/2016 19:37:04 ******/
DROP INDEX [INDICE_05] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_05]    Script Date: 11/02/2016 19:37:04 ******/
CREATE NONCLUSTERED INDEX [INDICE_05] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_FORNIT] ASC,
	[MOV_CODACQ] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_CODBUN] ASC,
	[MOV_ANNO] ASC,
	[MOV_DATSCA] ASC,
	[MOV_PREACQ] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_06]    Script Date: 11/02/2016 19:37:25 ******/
DROP INDEX [INDICE_06] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_06]    Script Date: 11/02/2016 19:37:25 ******/
CREATE NONCLUSTERED INDEX [INDICE_06] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAT] ASC,
	[MOV_ANAART] ASC,
	[MOV_FORNIT] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_ANNO] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_TOP] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_07]    Script Date: 11/02/2016 19:37:50 ******/
DROP INDEX [INDICE_07] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_07]    Script Date: 11/02/2016 19:37:50 ******/
CREATE NONCLUSTERED INDEX [INDICE_07] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_DTREGI] ASC,
	[MOV_CODART] ASC,
	[MOV_TOP] ASC,
	[MOV_CODACQ] ASC,
	[MOV_CODFOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_08]    Script Date: 11/02/2016 19:38:12 ******/
DROP INDEX [INDICE_08] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_08]    Script Date: 11/02/2016 19:38:12 ******/
CREATE NONCLUSTERED INDEX [INDICE_08] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_NRLINT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_09]    Script Date: 11/02/2016 19:38:32 ******/
DROP INDEX [INDICE_09] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_09]    Script Date: 11/02/2016 19:38:32 ******/
CREATE NONCLUSTERED INDEX [INDICE_09] ON [dbo].[S_MAG_MO]
(
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [INDICE_10]    Script Date: 11/02/2016 19:38:49 ******/
DROP INDEX [INDICE_10] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [INDICE_10]    Script Date: 11/02/2016 19:38:49 ******/
CREATE NONCLUSTERED INDEX [INDICE_10] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_TOP] ASC,
	[MOV_CODFOR] ASC,
	[MOV_LEGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




/****** Object:  Index [MOV_UNIQUE]    Script Date: 11/02/2016 19:39:12 ******/
DROP INDEX [MOV_UNIQUE] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [MOV_UNIQUE]    Script Date: 11/02/2016 19:39:12 ******/
CREATE NONCLUSTERED INDEX [MOV_UNIQUE] ON [dbo].[S_MAG_MO]
(
	[MOV_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [NUMDOC]    Script Date: 11/02/2016 19:39:29 ******/
DROP INDEX [NUMDOC] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [NUMDOC]    Script Date: 11/02/2016 19:39:29 ******/
CREATE NONCLUSTERED INDEX [NUMDOC] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_01]    Script Date: 11/02/2016 19:40:46 ******/
DROP INDEX [U_MAG_01] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_01]    Script Date: 11/02/2016 19:40:46 ******/
CREATE NONCLUSTERED INDEX [U_MAG_01] ON [dbo].[S_MAG_MO]
(
	[MOV_CODPDV] ASC,
	[MOV_LEGAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




/****** Object:  Index [U_MAG_02]    Script Date: 11/02/2016 19:41:15 ******/
DROP INDEX [U_MAG_02] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_02]    Script Date: 11/02/2016 19:41:15 ******/
CREATE NONCLUSTERED INDEX [U_MAG_02] ON [dbo].[S_MAG_MO]
(
	[MOV_CODPDV] ASC,
	[MOV_LEGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_03]    Script Date: 11/02/2016 19:42:14 ******/
DROP INDEX [U_MAG_03] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_03]    Script Date: 11/02/2016 19:42:14 ******/
CREATE NONCLUSTERED INDEX [U_MAG_03] ON [dbo].[S_MAG_MO]
(
	[MOV_CODMAG] ASC,
	[MOV_LEGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_04]    Script Date: 11/02/2016 19:42:57 ******/
DROP INDEX [U_MAG_04] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_04]    Script Date: 11/02/2016 19:42:57 ******/
CREATE NONCLUSTERED INDEX [U_MAG_04] ON [dbo].[S_MAG_MO]
(
	[MOV_CODMAG] ASC,
	[MOV_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [U_MAG_05]    Script Date: 11/02/2016 19:43:19 ******/
DROP INDEX [U_MAG_05] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_05]    Script Date: 11/02/2016 19:43:19 ******/
CREATE NONCLUSTERED INDEX [U_MAG_05] ON [dbo].[S_MAG_MO]
(
	[MOV_FLGTRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [U_MAG_06]    Script Date: 11/02/2016 19:43:47 ******/
DROP INDEX [U_MAG_06] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_06]    Script Date: 11/02/2016 19:43:47 ******/
CREATE NONCLUSTERED INDEX [U_MAG_06] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_FORNIT] ASC,
	[MOV_CODACQ] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_CODBUN] ASC,
	[MOV_ANNO] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_07]    Script Date: 11/02/2016 19:44:10 ******/
DROP INDEX [U_MAG_07] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_07]    Script Date: 11/02/2016 19:44:10 ******/
CREATE NONCLUSTERED INDEX [U_MAG_07] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_FORNIT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_08]    Script Date: 11/02/2016 19:44:30 ******/
DROP INDEX [U_MAG_08] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_08]    Script Date: 11/02/2016 19:44:30 ******/
CREATE NONCLUSTERED INDEX [U_MAG_08] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_ANNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_09]    Script Date: 11/02/2016 19:44:49 ******/
DROP INDEX [U_MAG_09] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_09]    Script Date: 11/02/2016 19:44:49 ******/
CREATE NONCLUSTERED INDEX [U_MAG_09] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_DTDOCU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




/****** Object:  Index [U_MAG_10]    Script Date: 11/02/2016 19:45:04 ******/
DROP INDEX [U_MAG_10] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_10]    Script Date: 11/02/2016 19:45:04 ******/
CREATE NONCLUSTERED INDEX [U_MAG_10] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_TOP] ASC,
	[MOV_CODMAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [U_MAG_11]    Script Date: 11/02/2016 19:45:24 ******/
DROP INDEX [U_MAG_11] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_11]    Script Date: 11/02/2016 19:45:24 ******/
CREATE NONCLUSTERED INDEX [U_MAG_11] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [U_MAG_AR]    Script Date: 11/02/2016 19:46:05 ******/
DROP INDEX [U_MAG_AR] ON [dbo].[S_MAG_MO]
GO


/****** Object:  Index [U_MAG_AR]    Script Date: 11/02/2016 19:46:05 ******/
CREATE NONCLUSTERED INDEX [U_MAG_AR] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODART] ASC,
	[MOV_FORNIT] ASC,
	[MOV_CODACQ] ASC,
	[MOV_NUMIDE] ASC,
	[MOV_CODBUN] ASC,
	[MOV_ANNO] ASC,
	[MOV_DATSCA] ASC,
	[MOV_PREACQ] ASC,
	[MOV_CODMAG] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_DC]    Script Date: 11/02/2016 19:46:40 ******/
DROP INDEX [U_MAG_DC] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_DC]    Script Date: 11/02/2016 19:46:40 ******/
CREATE NONCLUSTERED INDEX [U_MAG_DC] ON [dbo].[S_MAG_MO]
(
	[MOV_CODART] ASC,
	[MOV_CODMAG] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_DR]    Script Date: 11/02/2016 19:47:04 ******/
DROP INDEX [U_MAG_DR] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_DR]    Script Date: 11/02/2016 19:47:04 ******/
CREATE NONCLUSTERED INDEX [U_MAG_DR] ON [dbo].[S_MAG_MO]
(
	[MOV_CODART] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_MA]    Script Date: 11/02/2016 19:47:22 ******/
DROP INDEX [U_MAG_MA] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_MA]    Script Date: 11/02/2016 19:47:22 ******/
CREATE NONCLUSTERED INDEX [U_MAG_MA] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_CODART] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_MC]    Script Date: 11/02/2016 19:47:40 ******/
DROP INDEX [U_MAG_MC] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_MC]    Script Date: 11/02/2016 19:47:40 ******/
CREATE NONCLUSTERED INDEX [U_MAG_MC] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_CODART] ASC,
	[MOV_TOP] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_DTREGI] ASC,
	[MOV_ORAMOV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




/****** Object:  Index [U_MAG_MD]    Script Date: 11/02/2016 19:47:57 ******/
DROP INDEX [U_MAG_MD] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_MD]    Script Date: 11/02/2016 19:47:57 ******/
CREATE NONCLUSTERED INDEX [U_MAG_MD] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_MF]    Script Date: 11/02/2016 19:48:14 ******/
DROP INDEX [U_MAG_MF] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_MF]    Script Date: 11/02/2016 19:48:14 ******/
CREATE NONCLUSTERED INDEX [U_MAG_MF] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_CODFOR] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_ML]    Script Date: 11/02/2016 19:48:40 ******/
DROP INDEX [U_MAG_ML] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_ML]    Script Date: 11/02/2016 19:48:40 ******/
CREATE NONCLUSTERED INDEX [U_MAG_ML] ON [dbo].[S_MAG_MO]
(
	[MOV_CODMAG] ASC,
	[MOV_LEGSYS] ASC,
	[MOV_NUMIDE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [U_MAG_RD]    Script Date: 11/02/2016 19:49:01 ******/
DROP INDEX [U_MAG_RD] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_RD]    Script Date: 11/02/2016 19:49:01 ******/
CREATE NONCLUSTERED INDEX [U_MAG_RD] ON [dbo].[S_MAG_MO]
(
	[MOV_CODSOC] ASC,
	[MOV_CODMAG] ASC,
	[MOV_CODART] ASC,
	[MOV_DTREGI] ASC,
	[MOV_FORNIT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




/****** Object:  Index [U_MAG_SE]    Script Date: 11/02/2016 19:49:37 ******/
DROP INDEX [U_MAG_SE] ON [dbo].[S_MAG_MO]
GO

/****** Object:  Index [U_MAG_SE]    Script Date: 11/02/2016 19:49:37 ******/
CREATE NONCLUSTERED INDEX [U_MAG_SE] ON [dbo].[S_MAG_MO]
(
	[MOV_CODMAG] ASC,
	[MOV_CODART] ASC,
	[MOV_TOP] ASC,
	[MOV_NUMDOC] ASC,
	[MOV_DTDOCU] ASC,
	[MOV_DTREGI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO







