IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'INDICE_DTREG')
    DROP INDEX INDICE_DTREG ON INDICE;
GO

CREATE INDEX INDICE_DTREG ON INDICE ( MOV_SOC,MOV_ANNO,MOV_DTREG,MOV_NUMPRO ) 


GO