
/****** Object:  Index [INDICE_04]    Script Date: 28/02/2018 15:11:37 ******/
CREATE NONCLUSTERED INDEX [INDICE_04] ON [dbo].[U_BOL_DD]
(
	[ORD_CODART] ASC,
	[ORS_NUMORC] ASC,
	[ORS_DATORC] ASC
)
INCLUDE ( 	[ORS_NUMORD],
	[ORS_DATORD]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


