IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'MOV_CONT_CONTO_NUMPRO')
    DROP INDEX MOV_CONT_CONTO_NUMPRO ON MOV_CONT;
GO

CREATE INDEX MOV_CONT_CONTO_NUMPRO ON MOV_CONT ( MOV_SOC,MOV_CONTO,MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN ) 


GO