DELETE FROM U_ANA_CL
SELECT ID_UNIQUE,CLI_CODSOC,CLI_CODCLI, '' AS CLI_CLDOG, '' AS CLI_TISPE,''  AS CLI_SERVINTRA FROM U_CLI_AN
INSERT INTO U_ANA_CL SELECT ID_UNIQUE,CLI_CODSOC,CLI_CODCLI, '' AS CLI_CLDOG, '' AS CLI_TISPE,''  AS CLI_SERVINTRA FROM U_CLI_AN  

