
-- INSERIMENTO PARAMETRO RIC: NUMERATORE RICHIESTE INTERVENTO

DELETE FROM PARA WHERE CODICE = 'NUMLII202201'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('NUMLII202201', 'NUMERI RICHIESTE INTERVENTO', '')
