
-- INSERIMENTO PARAMETRO PASSWORD PER SBLOCCO PREZZO ULTIMO CARICO IN ANAGRAFICA ARTICOLI

INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDUPC', 'PASSWORD PER SBLOCCO PREZZO ULTIMO CARICO IN ANAGRAFICA ARTICOLI', 'STANDARD')
