
-- INSERIMENTO PARAMETRO PASSWORD PER SBLOCCO PREZZO DI COSTO STANDARD IN ANAGRAFICA ARTICOLI

DELETE FROM PARA WHERE CODICE = 'PWDPCS'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDPCS', 'PASSWORD PER	SBLOCCO PREZZO DI COSTO STANDARD IN ANAGRAFICA ARTICOLI', 'PCS')
