
-- INSERIMENTO PARAMETRO NUMBCL01 PER GESTIONE C/ANTICIPO ESTERO AUTOMATICO

DECLARE @DATA_OGGI_ISO_cAAAAMMGG VARCHAR(8)
DECLARE @DATA_OGGI_TXT_cAAAAMMGG VARCHAR(10)

SET @DATA_OGGI_ISO_cAAAAMMGG = CONVERT(VARCHAR(8), Getdate(), 112)
SET @DATA_OGGI_TXT_cAAAAMMGG = Substring(@DATA_OGGI_ISO_cAAAAMMGG, 1, 4) + '/' +
							   Substring(@DATA_OGGI_ISO_cAAAAMMGG, 5, 2) + '/' +
							   Substring(@DATA_OGGI_ISO_cAAAAMMGG, 7, 2)

DELETE FROM PARA WHERE CODICE = 'NUMBCL01'

INSERT INTO PARA	(CODICE,
					 DESCRI,
					 LIBERA,
					 PAR_DATINS)
VALUES           	('NUMBCL01',
					 'N. DDT CONTO LAVORO',
					 '   0000',
					 @DATA_OGGI_TXT_cAAAAMMGG)
