
-- INSERIMENTO PARAMETRO PASSWORD PER RESET ELABORAZIONI PENDENTI DI SINCRONIZZAZIONE CON SALESFORCE

DELETE FROM PARA WHERE CODICE = 'PWDRSF'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDRSF', 'PASSWORD PER	RESET ELABORAZIONI DI SINCR. SALESFORCE', 'SFDC')
