
-- INSERIMENTO PARAMETRO PASSWORD PER GESTIONE PASSWORD PER INTERVENTI/RIPARAZIONI
DELETE FROM PARA WHERE CODICE = 'PWDINR'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDINR','PASSWORD PER GESTIONE INTERVENTI/RIPARAZIONI','INTE')
