  DELETE FROM PARA WHERE CODICE LIKE 'SCC%'

  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS1','Sconto 3%  ','3,00')
  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS2','Sconto 5%  ','5,00')
  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS3','sconto 4%  ','4,00')
  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS4','sconto 6%  ','6,00')
  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS5','Sconto 2%  ','2,00')
  INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SCCS6','Sconto 3,5%','3,50')
  
  UPDATE PARA SET DESCRI=RTRIM(DESCRI) WHERE CODICE LIKE 'SCC%'

  SELECT * FROM PARA WHERE CODICE LIKE 'SCC%'
  
  