DELETE FROM PARA WHERE CODICE LIKE 'GRC%'

INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCA','DECORATIVO A')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCB','DECORATIVO B')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCC','DECORATIVO C')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCD','DECORATIVO D')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCE','DECORATIVO E')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCF','DECORATIVO F')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCG','DECORATIVO G')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GRCX','GREZZO SENZA DECORATIVO')
  
UPDATE PARA SET DESCRI=RTRIM(DESCRI) WHERE CODICE LIKE 'GRC%'

SELECT * FROM PARA WHERE CODICE LIKE 'GRC%'
  
  