
-- INSERIMENTO PARAMETRO PASSWORD PER GESTIONE PASSWORD MOVIMENTI DI MAGAZZINO

INSERT INTO PARA	(CODICE,
			 DESCRI,
                         LIBERA)
VALUES           	('PWDMOV',
			'PASSWORD PER GESTIONE MOVIMENTI DI MAGAZZINO',
                        '1357')
