
-- INSERIMENTO PARAMETRO PASSWORD PER	SBLOCCO DESCRIZIONE IN DETTAGLIO ORDINE

DELETE FROM PARA WHERE CODICE = 'PWDMDD'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDMDD', 'PASSWORD PER	SBLOCCO DESCRIZIONE IN DETTAGLIO ORDINE', 'MDD')
