
-- INSERIMENTO PARAMETRO PASSWORD PER PROGRAMMAZIONE DELLA PRODUZIONE

DELETE FROM PARA WHERE CODICE = 'PWDPRD'
INSERT INTO PARA	(CODICE,
					 DESCRI,
					 LIBERA)
VALUES           	('PWDPRD',
					 'PASSWORD PER PROGRAMMAZIONE DELLA PRODUZIONE',
					 '1234')


SELECT * FROM PARA WHERE CODICE = 'PWDPRD'