
-- INSERIMENTO PARAMETRO PASSWORD PER	CANCELLAZIONE RIGHE PARTITARIO

DELETE FROM PARA WHERE CODICE = 'PWDPAR'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDPAR', 'PASSWORD PER	CANCELLAZIONE RIGHE PARTITARIO', 'CPAR')
