
-- INSERIMENTO PARAMETRO PASSWORD PER GESTIONE PASSWORD CERTIFICATI DI CONFORMITA'

INSERT INTO PARA	(CODICE,
			 DESCRI,
                         LIBERA)
VALUES           	('PWDIVA',
			'PASSWORD PER CAMBIO CODICI IVA',
                        'CAMBIOIVA')
