INSERT INTO MAIL_ADDRESS (CLI_FOR, CODICE_CLI_FOR, TIPO_DOC, INDIRIZZO_A, INDIRIZZO_CC, INDIRIZZO_CCN, OGGETTO, CORPO)
SELECT CLI_FOR, CODICE_CLI_FOR, 'GEN' AS TIPO_DOC,
		INDIRIZZO_A, INDIRIZZO_CC, INDIRIZZO_CCN,
		'' AS OGGETTO, '' AS CORPO
	from MAIL_ADDRESS
WHERE TIPO_DOC = 'FAT'