
-- INSERIMENTO NUOVI PARANEWMETRI 

DELETE FROM PARANEW WHERE CODICE = 'TOPCAMA'
INSERT INTO PARANEW (CODICE, DESCRI, CONCAU, CAUSUCC, CAUSDDT, CAUSORD,TOP_COL,NOTE)
	VALUES ('TOPCAMA', 'CARICO MAGAZZINO MP', 'SCP1', 'SCP1', 'SCP1', 'SCP1', 'SCP1', '')

DELETE FROM PARANEW WHERE CODICE = 'TOPSCP1'
INSERT INTO PARANEW (CODICE, DESCRI, CONCAU, CAUSUCC, CAUSDDT, CAUSORD,TOP_COL,NOTE)
	VALUES ('TOPSCP1', 'SCARICO MAGAZZINO', 'CAMA', 'CAMA', 'CAMA', 'CAMA', 'CAMA', '')