
-- INSERIMENTO PARAMETRO PASSWORD PER INIBIZIONE CONTROLLO BLOCCANTE P.IVA O COD.FISCALE DUPLICATI

DELETE FROM PARA WHERE CODICE = 'PWDBDP'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('PWDBDP', 'PASSWORD PER INIBIZIONE CONTROLLO BLOCCANTE P.IVA O COD.FISCALE DUPLICATI', '')
