
/*
###########################################################################
***************************************************************************
SCRIPT PER ADEGUAMENTO NUOVO DB AL VECCHIO DB SEMPER - 28/03/2011
***************************************************************************
###########################################################################
*/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[L_MAG_GG]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[L_MAG_GG]
GO
 
CREATE TABLE [dbo].[L_MAG_GG] (
	[LOG_TIPLOG] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[LOG_DATLOG] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[LOG_ORALOG] [varchar](8) COLLATE Latin1_General_CI_AS NULL ,
	[LOG_NOTLOG] [text] COLLATE Latin1_General_CI_AS NULL ,
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL ,
	[MAG_CODSOC] [varchar](2) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DATAGG] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODART] [varchar](16) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESART] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODMAG] [varchar](6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODPDV] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FORNIT] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESFOR] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_GIACEN] [numeric](17, 2) NULL ,
	[MAG_PRZCON] [numeric](19, 6) NULL ,
	[SELEZIONE] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_LEGSYS] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_LEGAME] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODACQ] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESACQ] [varchar](30) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_PRZUFF] [numeric](19, 6) NULL ,
	[MAG_DATINI] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DATFIN] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_SC1] [numeric](8, 2) NULL ,
	[MAG_SC2] [numeric](8, 2) NULL ,
	[MAG_SC3] [numeric](8, 2) NULL ,
	[MAG_SC4] [numeric](8, 2) NULL ,
	[MAG_SC5] [numeric](8, 2) NULL ,
	[MAG_PRZSCO] [numeric](19, 6) NULL ,
	[MAG_PAGAME] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NUMIDE] [varchar](6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODBUN] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ANNO] [varchar](4) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FLGTRA] [bit] NULL ,
	[MAG_UNIQUE] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NUMCAM] [varchar](6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DATCAM] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_PRZFIS] [numeric](19, 6) NULL ,
	[MAG_DTCGMA] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DTIGMA] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DTFGMA] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FLGVIA] [bit] NULL ,
	[MAG_CODMAT] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESMAT] [varchar](30) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODCOL] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESCOL] [varchar](30) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_SPESSO] [numeric](5, 0) NULL ,
	[MAG_ALTEZZ] [numeric](7, 0) NULL ,
	[MAG_LUNGHE] [numeric](8, 0) NULL ,
	[MAG_NRLINT] [numeric](12, 0) NULL ,
	[MAG_NRDBOB] [numeric](8, 0) NULL ,
	[MAG_QTAKG] [numeric](13, 2) NULL ,
	[MAG_QTAMQ] [numeric](13, 2) NULL ,
	[MAG_QTAML] [numeric](13, 2) NULL ,
	[MAG_CDAFOR] [varchar](20) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_OINFOR] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_PINFOR] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DTPFOR] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_TRAFOR] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NBAFOR] [numeric](13, 2) NULL ,
	[MAG_BDAFOR] [numeric](13, 2) NULL ,
	[MAG_BALFOR] [numeric](13, 2) NULL ,
	[MAG_PNKFOR] [numeric](13, 2) NULL ,
	[MAG_ANAART] [varchar](16) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DTINCQ] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ORINCQ] [varchar](8) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DTFICQ] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ORFICQ] [varchar](8) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CDRECQ] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DSRECQ] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ALTRES] [numeric](5, 0) NULL ,
	[MAG_QTAIMP] [numeric](12, 2) NULL ,
	[MAG_COMODO] [numeric](12, 2) NULL ,
	[MAG_GMLIMP] [numeric](12, 2) NULL ,
	[MAG_GKGIMP] [numeric](12, 2) NULL ,
	[MAG_FLGMOD] [bit] NULL ,
	[MAG_QTAKGA] [numeric](11, 2) NULL ,
	[MAG_QTAMQA] [numeric](11, 2) NULL ,
	[MAG_QTAMLA] [numeric](11, 2) NULL ,
	[MAG_TIPART] [varchar](1) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FLGRIB] [bit] NULL ,
	[MAG_BYPASS] [bit] NULL ,
	[MAG_CLIENT] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NUMORD] [varchar](6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DATORD] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_SYSORD] [varchar](10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NLPROV] [numeric](8, 0) NULL ,
	[MAG_NUMPED] [numeric](8, 0) NULL ,
	[MAG_CSTFNU] [numeric](11, 2) NULL ,
	[MAG_CSTADE] [numeric](11, 2) NULL ,
	[MAG_CSTAMQ] [numeric](16, 6) NULL ,
	[MAG_FLGCEL] [bit] NULL ,
	[MAG_SERBOL] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_AAPROD] [numeric](4, 0) NULL ,
	[MAG_SERNUM] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NUMEDA] [numeric](9, 0) NULL ,
	[MAG_NUMEAL] [numeric](9, 0) NULL ,
	[MAG_CBFISC] [varchar](50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_QTACON] [numeric](10, 2) NULL ,
	[MAG_SERIE] [varchar](3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FLGIMB] [bit] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[L_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [PK_L_MAG_GG] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[L_MAG_GG] WITH NOCHECK ADD 
	CONSTRAINT [DF_L_MAG_GG_LOG_TIPLOG] DEFAULT ('') FOR [LOG_TIPLOG],
	CONSTRAINT [DF_L_MAG_GG_LOG_DATLOG] DEFAULT ('') FOR [LOG_DATLOG],
	CONSTRAINT [DF_L_MAG_GG_LOG_ORALOG] DEFAULT ('') FOR [LOG_ORALOG],
	CONSTRAINT [DF_L_MAG_GG_LOG_NOTLOG] DEFAULT ('') FOR [LOG_NOTLOG],
	CONSTRAINT [DF_L_MAG_GG_id_unique]  DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODSOC]  DEFAULT ('') FOR [MAG_CODSOC],
	CONSTRAINT [DF_L_MAG_GG_MAG_DATAGG]  DEFAULT ('') FOR [MAG_DATAGG],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODART]  DEFAULT ('') FOR [MAG_CODART],
	CONSTRAINT [DF_L_MAG_GG_MAG_DESART]  DEFAULT ('') FOR [MAG_DESART],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODMAG]  DEFAULT ('') FOR [MAG_CODMAG],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODPDV]  DEFAULT ('') FOR [MAG_CODPDV],
	CONSTRAINT [DF_L_MAG_GG_MAG_FORNIT]  DEFAULT ('') FOR [MAG_FORNIT],
	CONSTRAINT [DF_L_MAG_GG_MAG_DESFOR]  DEFAULT ('') FOR [MAG_DESFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_GIACEN]  DEFAULT (0) FOR [MAG_GIACEN],
	CONSTRAINT [DF_L_MAG_GG_MAG_PRZCON]  DEFAULT (0) FOR [MAG_PRZCON],
	CONSTRAINT [DF_L_MAG_GG_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE],
	CONSTRAINT [DF_L_MAG_GG_MAG_LEGSYS]  DEFAULT ('') FOR [MAG_LEGSYS],
	CONSTRAINT [DF_L_MAG_GG_MAG_LEGAME]  DEFAULT ('') FOR [MAG_LEGAME],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODACQ]  DEFAULT ('') FOR [MAG_CODACQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_DESACQ]  DEFAULT ('') FOR [MAG_DESACQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_PRZUFF]  DEFAULT (0) FOR [MAG_PRZUFF],
	CONSTRAINT [DF_L_MAG_GG_MAG_DATINI]  DEFAULT ('') FOR [MAG_DATINI],
	CONSTRAINT [DF_L_MAG_GG_MAG_DATFIN]  DEFAULT ('') FOR [MAG_DATFIN],
	CONSTRAINT [DF_L_MAG_GG_MAG_SC1]  DEFAULT (0) FOR [MAG_SC1],
	CONSTRAINT [DF_L_MAG_GG_MAG_SC2]  DEFAULT (0) FOR [MAG_SC2],
	CONSTRAINT [DF_L_MAG_GG_MAG_SC3]  DEFAULT (0) FOR [MAG_SC3],
	CONSTRAINT [DF_L_MAG_GG_MAG_SC4]  DEFAULT (0) FOR [MAG_SC4],
	CONSTRAINT [DF_L_MAG_GG_MAG_SC5]  DEFAULT (0) FOR [MAG_SC5],
	CONSTRAINT [DF_L_MAG_GG_MAG_PRZSCO]  DEFAULT (0) FOR [MAG_PRZSCO],
	CONSTRAINT [DF_L_MAG_GG_MAG_PAGAME]  DEFAULT ('') FOR [MAG_PAGAME],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMIDE]  DEFAULT ('') FOR [MAG_NUMIDE],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODBUN]  DEFAULT ('') FOR [MAG_CODBUN],
	CONSTRAINT [DF_L_MAG_GG_MAG_ANNO]  DEFAULT ('') FOR [MAG_ANNO],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGTRA]  DEFAULT (0) FOR [MAG_FLGTRA],
	CONSTRAINT [DF_L_MAG_GG_MAG_UNIQUE]  DEFAULT ('') FOR [MAG_UNIQUE],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMCAM]  DEFAULT ('') FOR [MAG_NUMCAM],
	CONSTRAINT [DF_L_MAG_GG_MAG_DATCAM]  DEFAULT ('') FOR [MAG_DATCAM],
	CONSTRAINT [DF_L_MAG_GG_MAG_PRZFIS]  DEFAULT (0) FOR [MAG_PRZFIS],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTCGMA]  DEFAULT ('') FOR [MAG_DTCGMA],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTIGMA]  DEFAULT ('') FOR [MAG_DTIGMA],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTFGMA]  DEFAULT ('') FOR [MAG_DTFGMA],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGVIA]  DEFAULT (0) FOR [MAG_FLGVIA],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODMAT]  DEFAULT ('') FOR [MAG_CODMAT],
	CONSTRAINT [DF_L_MAG_GG_MAG_DESMAT]  DEFAULT ('') FOR [MAG_DESMAT],
	CONSTRAINT [DF_L_MAG_GG_MAG_CODCOL]  DEFAULT ('') FOR [MAG_CODCOL],
	CONSTRAINT [DF_L_MAG_GG_MAG_DESCOL]  DEFAULT ('') FOR [MAG_DESCOL],
	CONSTRAINT [DF_L_MAG_GG_MAG_SPESSO]  DEFAULT (0) FOR [MAG_SPESSO],
	CONSTRAINT [DF_L_MAG_GG_MAG_ALTEZZ]  DEFAULT (0) FOR [MAG_ALTEZZ],
	CONSTRAINT [DF_L_MAG_GG_MAG_LUNGHE]  DEFAULT (0) FOR [MAG_LUNGHE],
	CONSTRAINT [DF_L_MAG_GG_MAG_NRLINT]  DEFAULT (0) FOR [MAG_NRLINT],
	CONSTRAINT [DF_L_MAG_GG_MAG_NRDBOB]  DEFAULT (0) FOR [MAG_NRDBOB],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAKG]  DEFAULT (0) FOR [MAG_QTAKG],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAMQ]  DEFAULT (0) FOR [MAG_QTAMQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAML]  DEFAULT (0) FOR [MAG_QTAML],
	CONSTRAINT [DF_L_MAG_GG_MAG_CDAFOR]  DEFAULT ('') FOR [MAG_CDAFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_OINFOR]  DEFAULT ('') FOR [MAG_OINFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_PINFOR]  DEFAULT ('') FOR [MAG_PINFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTPFOR]  DEFAULT ('') FOR [MAG_DTPFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_TRAFOR]  DEFAULT ('') FOR [MAG_TRAFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_NBAFOR]  DEFAULT (0) FOR [MAG_NBAFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_BDAFOR]  DEFAULT (0) FOR [MAG_BDAFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_BALFOR]  DEFAULT (0) FOR [MAG_BALFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_PNKFOR]  DEFAULT (0) FOR [MAG_PNKFOR],
	CONSTRAINT [DF_L_MAG_GG_MAG_ANAART]  DEFAULT ('') FOR [MAG_ANAART],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTINCQ]  DEFAULT ('') FOR [MAG_DTINCQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_ORINCQ]  DEFAULT ('') FOR [MAG_ORINCQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_DTFICQ]  DEFAULT ('') FOR [MAG_DTFICQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_ORFICQ]  DEFAULT ('') FOR [MAG_ORFICQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_CDRECQ]  DEFAULT ('') FOR [MAG_CDRECQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_DSRECQ]  DEFAULT ('') FOR [MAG_DSRECQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_ALTRES]  DEFAULT (0) FOR [MAG_ALTRES],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAIMP]  DEFAULT (0) FOR [MAG_QTAIMP],
	CONSTRAINT [DF_L_MAG_GG_MAG_COMODO]  DEFAULT (0) FOR [MAG_COMODO],
	CONSTRAINT [DF_L_MAG_GG_MAG_GMLIMP]  DEFAULT (0) FOR [MAG_GMLIMP],
	CONSTRAINT [DF_L_MAG_GG_MAG_GKGIMP]  DEFAULT (0) FOR [MAG_GKGIMP],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGMOD]  DEFAULT (0) FOR [MAG_FLGMOD],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAKGA]  DEFAULT (0) FOR [MAG_QTAKGA],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAMQA]  DEFAULT (0) FOR [MAG_QTAMQA],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTAMLA]  DEFAULT (0) FOR [MAG_QTAMLA],
	CONSTRAINT [DF_L_MAG_GG_MAG_TIPART]  DEFAULT ('') FOR [MAG_TIPART],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGRIB]  DEFAULT (0) FOR [MAG_FLGRIB],
	CONSTRAINT [DF_L_MAG_GG_MAG_BYPASS]  DEFAULT (0) FOR [MAG_BYPASS],
	CONSTRAINT [DF_L_MAG_GG_MAG_CLIENT]  DEFAULT ('') FOR [MAG_CLIENT],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMORD]  DEFAULT ('') FOR [MAG_NUMORD],
	CONSTRAINT [DF_L_MAG_GG_MAG_DATORD]  DEFAULT ('') FOR [MAG_DATORD],
	CONSTRAINT [DF_L_MAG_GG_MAG_SYSORD]  DEFAULT ('') FOR [MAG_SYSORD],
	CONSTRAINT [DF_L_MAG_GG_MAG_NLPROV]  DEFAULT (0) FOR [MAG_NLPROV],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMPED]  DEFAULT (0) FOR [MAG_NUMPED],
	CONSTRAINT [DF_L_MAG_GG_MAG_CSTFNU]  DEFAULT (0) FOR [MAG_CSTFNU],
	CONSTRAINT [DF_L_MAG_GG_MAG_CSTADE]  DEFAULT (0) FOR [MAG_CSTADE],
	CONSTRAINT [DF_L_MAG_GG_MAG_CSTAMQ]  DEFAULT (0) FOR [MAG_CSTAMQ],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGCEL]  DEFAULT (0) FOR [MAG_FLGCEL],
	CONSTRAINT [DF_L_MAG_GG_MAG_SERBOL]  DEFAULT ('') FOR [MAG_SERBOL],
	CONSTRAINT [DF_L_MAG_GG_MAG_AAPROD]  DEFAULT (0) FOR [MAG_AAPROD],
	CONSTRAINT [DF_L_MAG_GG_MAG_SERNUM]  DEFAULT ('') FOR [MAG_SERNUM],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMEDA]  DEFAULT (0) FOR [MAG_NUMEDA],
	CONSTRAINT [DF_L_MAG_GG_MAG_NUMEAL]  DEFAULT (0) FOR [MAG_NUMEAL],
	CONSTRAINT [DF_L_MAG_GG_MAG_CBFISC]  DEFAULT ('') FOR [MAG_CBFISC],
	CONSTRAINT [DF_L_MAG_GG_MAG_QTACON]  DEFAULT (0) FOR [MAG_QTACON],
	CONSTRAINT [DF_L_MAG_GG_MAG_SERIE]  DEFAULT ('') FOR [MAG_SERIE],
	CONSTRAINT [DF_L_MAG_GG_MAG_FLGIMB]  DEFAULT (0) FOR [MAG_FLGIMB]
GO




ALTER TABLE [dbo].[U_AZI_PA] ADD 
	[AZI_LOG_GG] [bit] NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_AZI_PA] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AZI_PA_AZI_LOG_GG] DEFAULT (0) FOR [AZI_LOG_GG]
go

UPDATE U_AZI_PA SET AZI_LOG_GG = 0




ALTER TABLE [dbo].[U_ART_PR] ADD 
	ART_GGROTA numeric(10,2) NULL
go
-- forzature di default (vedi script standard per valorizzare campi diversi da varchar)
ALTER TABLE [dbo].[U_ART_PR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_PR_ART_GGROTA] DEFAULT (0) FOR [ART_GGROTA]
go

UPDATE U_ART_PR SET ART_GGROTA = 0





