

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[INTRASTAT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[INTRASTAT]
GO
 

 

/****** Object:  Table [dbo].[INTRASTAT]    Script Date: 06/08/2015 10.47.05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[INTRASTAT](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[MOV_SOC] [varchar](2) NULL,
	[MOV_ANNO] [varchar](4) NULL,
	[MOV_CONTO] [varchar](13) NULL,
	[MOV_CLDOG] [varchar](16) NULL,
	[MOV_SERV_INTRA] [varchar](10) NULL,
	[MOV_NDOC] [varchar](20) NULL,
	[MOV_DTDOC] [varchar](10) NULL,
	[CON_DESCR] [varchar](100) NULL,
	[CON_TIPOCO] [varchar](1) NULL,
	[MOV_NREGIS] [varchar](10) NULL,
	[MOV_DTREG] [varchar](10) NULL,
	[MOV_TOP] [varchar](3) NULL,
	[TOP_INTRA] [varchar](1) NULL,
	[TOP_CLI_FOR] [varchar](1) NULL,
    [MOV_ANT_CAMB_SEGNO] [bit] NOT NULL,
	[MOV_IMP] [numeric](17, 3) NULL,
	[MOV_TMOV] [varchar](1) NULL,
	[MOV_VALUTA] [varchar](3) NULL,
	[MOV_CAMBIO] [numeric](15, 10) NULL,
	[MOV_IVA] [varchar](3) NULL,
	[FLG_BENI_SERVIZI] [varchar](100) NULL,
	[MOV_MODPAG] [varchar](3) NULL,
	[CPA_MOD_PAG] [varchar](1) NULL,
	[MOV_PESO] [numeric](10, 2) NULL,
	[MOV_TISPE] [varchar](3) NULL,
	[MOV_PORTO] [varchar](3) NULL,
	[MOV_IMPEUR_INTRA] [numeric](13, 0) NULL,
	[MOV_IMPSTAT_INTRA] [numeric](13, 0) NULL,
	[MOV_NAZIONE_INTRA] [varchar](3) NULL,
	[MOV_STATO_INTRA_PROV] [varchar](2) NULL,
	[MOV_STATO_INTRA_ORIG] [varchar](2) NULL,
	[PAESE_ORIGINE] [varchar](2) NULL,
	[ITALIANO] [varchar](2) NULL,
	[MOV_PARTITA_IVA_INTRA] [varchar](20) NULL,
	[MOV_QTA_INTRA] [numeric](10, 0) NULL,
	[MOV_COND_CONS_INTRA] [varchar](1) NULL,
	[MOV_MEZZI_TRASP_INTRA] [varchar](1) NULL,
	[MOV_PROVIN_DESTI_INTRA] [varchar](2) NULL,
	[MOV_UNITA_SUPPL_INTRA] [numeric](10, 0) NULL,
	[MOV_NUMPRO] [varchar](13) NULL,
	[CPA_MOD_INC] [varchar](1) NOT NULL,
	[MOV_INTRA_ok_ko] [bit] NULL,
	[MOV_CONTABILITA_PREVISIONALE] [varchar](1) NULL,
	[MESSAGGIO_PARA4] [varchar](100) NOT NULL,
	[MOV_NPROT] [varchar](10) NULL,
	[MOV_IMPVAL] [numeric](18, 4) NULL,
	[MOV_NPART] [numeric](10, 0) NULL,
	[MOV_IMPVAL_INTRA] [numeric](13, 0) NULL,
	[MOV_STATO_CEE] [varchar](3) NULL,
	[MOV_INTRA_DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_INTRASTAT] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_SOC]  DEFAULT ('') FOR [MOV_SOC]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_ANNO]  DEFAULT ('') FOR [MOV_ANNO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_CONTO]  DEFAULT ('') FOR [MOV_CONTO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_CON_DESCR]  DEFAULT ('') FOR [CON_DESCR]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_CON_TIPOCO]  DEFAULT ('') FOR [CON_TIPOCO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NREGIS]  DEFAULT ('') FOR [MOV_NREGIS]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_DTREG]  DEFAULT ('') FOR [MOV_DTREG]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NDOC]  DEFAULT ('') FOR [MOV_NDOC]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_DTDOC]  DEFAULT ('') FOR [MOV_DTDOC]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_TOP]  DEFAULT ('') FOR [MOV_TOP]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_TOP_INTRA]  DEFAULT ('') FOR [TOP_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_TOP_CLI_FOR]  DEFAULT ('') FOR [TOP_CLI_FOR]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_ANT_CAMB_SEGNO]  DEFAULT ((0)) FOR [MOV_ANT_CAMB_SEGNO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IMP]  DEFAULT (0) FOR [MOV_IMP]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_TMOV]  DEFAULT ('') FOR [MOV_TMOV]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_VALUTA]  DEFAULT ('') FOR [MOV_VALUTA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_CAMBIO]  DEFAULT (0) FOR [MOV_CAMBIO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IVA]  DEFAULT ('') FOR [MOV_IVA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_FLG_BENI_SERVIZI]  DEFAULT ('') FOR [FLG_BENI_SERVIZI]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_MODPAG]  DEFAULT ('') FOR [MOV_MODPAG]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_CPA_MOD_PAG]  DEFAULT ('') FOR [CPA_MOD_PAG]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_PESO]  DEFAULT (0) FOR [MOV_PESO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_TISPE]  DEFAULT ('') FOR [MOV_TISPE]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_PORTO]  DEFAULT ('') FOR [MOV_PORTO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_CLDOG]  DEFAULT ('') FOR [MOV_CLDOG]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_SERV_INTRA]  DEFAULT ('   ') FOR [MOV_SERV_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IMPEUR_INTRA]  DEFAULT ('0') FOR [MOV_IMPEUR_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IMPSTAT_INTRA]  DEFAULT ('0') FOR [MOV_IMPSTAT_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NAZIONE_INTRA]  DEFAULT ('    ') FOR [MOV_NAZIONE_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_STATO_INTRA_PROV]  DEFAULT ('     ') FOR [MOV_STATO_INTRA_PROV]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_STATO_INTRA_ORIG]  DEFAULT ('     ') FOR [MOV_STATO_INTRA_ORIG]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_PAESE_ORIGINE]  DEFAULT ('') FOR [PAESE_ORIGINE]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_ITALIANO]  DEFAULT ('') FOR [ITALIANO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_PARTITA_IVA_INTRA]  DEFAULT ('     ') FOR [MOV_PARTITA_IVA_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_QTA_INTRA]  DEFAULT ('0') FOR [MOV_QTA_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_PMOV_COND_CONS_INTRA]  DEFAULT ('     ') FOR [MOV_COND_CONS_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_MEZZI_TRASP_INTRA]  DEFAULT ('    ') FOR [MOV_MEZZI_TRASP_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_PROVIN_DESTI_INTRA]  DEFAULT ('    ') FOR [MOV_PROVIN_DESTI_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_UNITA_SUPPL_INTRA]  DEFAULT ('0') FOR [MOV_UNITA_SUPPL_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NUMPRO]  DEFAULT ('') FOR [MOV_NUMPRO]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_CPA_MOD_INC]  DEFAULT ('') FOR [CPA_MOD_INC]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_INTRA_ok_ko]  DEFAULT ((0)) FOR [MOV_INTRA_ok_ko]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_CONTABILITA_PREVISIONALE]  DEFAULT ('0') FOR [MOV_CONTABILITA_PREVISIONALE]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MESSAGGIO_PARA4]  DEFAULT ('0') FOR [MESSAGGIO_PARA4]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NPROT]  DEFAULT ('') FOR [MOV_NPROT]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IMPVAL]  DEFAULT (0) FOR [MOV_IMPVAL]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_NPART]  DEFAULT (0) FOR [MOV_NPART]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_IMPVAL_INTRA]  DEFAULT ('0') FOR [MOV_IMPVAL_INTRA]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_STATO_CEE]  DEFAULT ('') FOR [MOV_STATO_CEE]
GO

ALTER TABLE [dbo].[INTRASTAT] ADD  CONSTRAINT [DF_INTRASTAT_MOV_INTRA_DELETED]  DEFAULT ((0)) FOR [MOV_INTRA_DELETED]
GO

