	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[INTRA_ACQ_SERV]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[INTRA_ACQ_SERV]
GO

/****** Object:  Table [dbo].[INTRA_ACQ_SERV]    Script Date: 26/02/2015 ******/
CREATE TABLE [INTRA_ACQ_SERV] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[NUMERO_PROGR_RIGA_6]		    [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ANNO_MESE_RETT_6]				[varchar] (7) COLLATE Latin1_General_CI_AS NULL ,
	[COD_SEZ_DOGANALE_6]			[varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[ANNO_REG_DICH_DA_RET_6]		[varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[PROT_DICH_DA_RETT_6]			[varchar] (6) COLLATE Latin1_General_CI_AS  NULL ,
	[PROG_SEZ_3_DA_RETT_6]			[varchar] (5) COLLATE Latin1_General_CI_AS  NULL ,
	[STATO_MEMBRO_ACQUIR_6]		 	[varchar] (2) COLLATE Latin1_General_CI_AS  NULL ,
	[CODICE_IVA_ACQUIR_6] 			[varchar] (12) COLLATE Latin1_General_CI_AS  NULL ,
	[AMMONTARE_OPERAZ_EUR_6] 		[varchar] (13) COLLATE Latin1_General_CI_AS  NULL ,
	[AMMONTARE_OPERAZ_VALUTA_6] 	[varchar] (13) COLLATE Latin1_General_CI_AS  NULL ,
	[NUMERO_FATTURA_6]		 		[varchar] (15) COLLATE Latin1_General_CI_AS  NULL ,
	[DATA_FATTURA_6] 				[varchar] (6) COLLATE Latin1_General_CI_AS  NULL,
	[CODICE_SERVIZIO_6] 			[varchar] (6)  COLLATE Latin1_General_CI_AS NULL ,
	[MODALITA_EROGAZ_6] 			[varchar] (1)  COLLATE Latin1_General_CI_AS NULL ,
	[MODALITA_INCASSO_6] 			[varchar] (1)  COLLATE Latin1_General_CI_AS NULL ,
	[CODICE_PAESE_PAGAM_6] 			[varchar] (2)  COLLATE Latin1_General_CI_AS NULL


	
	
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[INTRA_ACQ_SERV] WITH NOCHECK ADD 
	CONSTRAINT [PK_INTRA_ACQ_SERV] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[INTRA_ACQ_SERV] WITH NOCHECK ADD 
	CONSTRAINT [DF_INTRA_ACQ_SERV_id_unique] 					DEFAULT (newid()) FOR 	[id_unique]	,
	CONSTRAINT [DF_INTRA_ACQ_SERV_NUMERO_PROGR_RIGA_6] 			DEFAULT ('') FOR [NUMERO_PROGR_RIGA_6],
	CONSTRAINT [DF_INTRA_ACQ_BENI_ANNO_MESE_RETT_6] 			DEFAULT ('') FOR [ANNO_MESE_RETT_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_COD_SEZ_DOGANALE_6] 			DEFAULT ('') FOR [COD_SEZ_DOGANALE_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_ANNO_REG_DICH_DA_RET_6] 		DEFAULT ('') FOR [ANNO_REG_DICH_DA_RET_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_PROT_DICH_DA_RETT_6] 			DEFAULT ('') FOR [PROT_DICH_DA_RETT_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_PROG_SEZ_3_DA_RETT_6] 		DEFAULT ('') FOR [PROG_SEZ_3_DA_RETT_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_STATO_MEMBRO_ACQUIR_6] 		DEFAULT ('') FOR [STATO_MEMBRO_ACQUIR_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_CODICE_IVA_ACQUIR_6] 			DEFAULT ('') FOR [CODICE_IVA_ACQUIR_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_AMMONTARE_OPERAZ_EUR_6] 		DEFAULT ('') FOR [AMMONTARE_OPERAZ_EUR_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_AMMONTARE_OPERAZ_VALUTA_6] 	DEFAULT ('') FOR [AMMONTARE_OPERAZ_VALUTA_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_NUMERO_FATTURA_6] 			DEFAULT ('') FOR [NUMERO_FATTURA_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_DATA_FATTURA_6] 				DEFAULT ('') FOR [DATA_FATTURA_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_CODICE_SERVIZIO_6] 			DEFAULT ('') FOR [CODICE_SERVIZIO_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_MODALITA_EROGAZ_6] 			DEFAULT ('') FOR [MODALITA_EROGAZ_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_MODALITA_INCASSO_6] 			DEFAULT ('') FOR [MODALITA_INCASSO_6],
	CONSTRAINT [DF_INTRA_ACQ_SERV_CODICE_PAESE_PAGAM_6] 		DEFAULT ('') FOR [CODICE_PAESE_PAGAM_6]
GO
