
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[IVADEFAULT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[IVADEFAULT]
GO
 
CREATE TABLE [dbo].[IVADEFAULT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[CODIVA] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[DESIVA] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[ALIQUOTA] [numeric] (6,2) NULL ,
	[DATADA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATAAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[IVADEFAULT] WITH NOCHECK ADD 
	CONSTRAINT [PK_IVADEFAULT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[IVADEFAULT] WITH NOCHECK ADD 
	CONSTRAINT [DF_IVADEFAULT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_IVADEFAULT_CODIVA] DEFAULT ('') FOR [CODIVA],
	CONSTRAINT [DF_IVADEFAULT_DESIVA] DEFAULT ('') FOR [DESIVA],
	CONSTRAINT [DF_IVADEFAULT_ALIQUOTA] DEFAULT (0) FOR [ALIQUOTA],
	CONSTRAINT [DF_IVADEFAULT_DATADA] DEFAULT ('') FOR [DATADA],
	CONSTRAINT [DF_IVADEFAULT_DATAAL] DEFAULT ('') FOR [DATAAL]
GO

INSERT INTO IVADEFAULT (CODIVA,DESIVA,ALIQUOTA,DATADA,DATAAL) VALUES ('20','IVA 20%',20.00,'1990/01/01','2011/09/16')
INSERT INTO IVADEFAULT (CODIVA,DESIVA,ALIQUOTA,DATADA,DATAAL) VALUES ('21','IVA 21%',21.00,'2011/09/17','2999/12/31')

SELECT * FROM IVADEFAULT
