
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOC_RULES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOC_RULES]
GO
 
CREATE TABLE [dbo].[LOC_RULES] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[RUL_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_NOME] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_CODMAG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_DESMAG] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_FILA_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_FDESCR] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_PIAN_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_UBIC_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[RUL_FILA_N] [numeric] (6,0) NULL ,
	[RUL_PIAN_N] [numeric] (6,0) NULL ,
	[RUL_UBIC_N] [numeric] (6,0) NULL ,
	[RUL_DESCRI] [text] COLLATE Latin1_General_CI_AS NULL ,
	[RUL_EXPRESSION] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


ALTER TABLE [dbo].[LOC_RULES] WITH NOCHECK ADD 
	CONSTRAINT [DF_LOC_RULES_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_LOC_RULES_RUL_ID] DEFAULT ('') FOR [RUL_ID],
	CONSTRAINT [DF_LOC_RULES_RUL_NOME] DEFAULT ('') FOR [RUL_NOME],
	CONSTRAINT [DF_LOC_RULES_RUL_CODMAG] DEFAULT ('') FOR [RUL_CODMAG],
	CONSTRAINT [DF_LOC_RULES_RUL_DESMAG] DEFAULT ('') FOR [RUL_DESMAG],
	CONSTRAINT [DF_LOC_RULES_RUL_FILA_X] DEFAULT ('') FOR [RUL_FILA_X],
	CONSTRAINT [DF_LOC_RULES_RUL_FDESCR] DEFAULT ('') FOR [RUL_FDESCR],
	CONSTRAINT [DF_LOC_RULES_RUL_PIAN_X] DEFAULT ('') FOR [RUL_PIAN_X],
	CONSTRAINT [DF_LOC_RULES_RUL_UBIC_X] DEFAULT ('') FOR [RUL_UBIC_X],
	CONSTRAINT [DF_LOC_RULES_RUL_FILA_N] DEFAULT (0) FOR [RUL_FILA_N],
	CONSTRAINT [DF_LOC_RULES_RUL_PIAN_N] DEFAULT (0) FOR [RUL_PIAN_N],
	CONSTRAINT [DF_LOC_RULES_RUL_UBIC_N] DEFAULT (0) FOR [RUL_UBIC_N],
	CONSTRAINT [DF_LOC_RULES_RUL_DESCRI] DEFAULT ('') FOR [RUL_DESCRI],
	CONSTRAINT [DF_LOC_RULES_RUL_EXPRESSION] DEFAULT ('') FOR [RUL_EXPRESSION]
GO

