if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_SFSYNC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOG_SFSYNC]
GO
 
CREATE TABLE [dbo].[LOG_SFSYNC] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_LOG_SFSYNC_id_unique] DEFAULT newid(),
	[CODSYS] varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_CODSYS] DEFAULT (''),
	[OGGETTO] varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_OGGETTO] DEFAULT (''),
	[DATA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_DATA] DEFAULT (''),
	[ORA] varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_ORA] DEFAULT (''),
	[CODOPE] varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_CODOPE] DEFAULT (''),
	[NOMOPE] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_NOMOPE] DEFAULT (''),
	[ESITO] varchar(2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_SFSYNC_ESITO] DEFAULT (''),
	[MESSAGGIO] text NOT NULL CONSTRAINT [DF_LOG_SFSYNC_MESSAGGIO] DEFAULT (''),
	[NRECINS_FROM_AQ] numeric(10,0) NOT NULL CONSTRAINT [DF_LOG_SFSYNC_NRECINS_FROM_AQ] DEFAULT (''),
	[NRECAGG_FROM_AQ] numeric(10,0) NOT NULL CONSTRAINT [DF_LOG_SFSYNC_NRECAGG_FROM_AQ] DEFAULT (''),
	[NRECINS_FROM_SF] numeric(10,0) NOT NULL CONSTRAINT [DF_LOG_SFSYNC_NRECINS_FROM_SF] DEFAULT (''),
	[NRECAGG_FROM_SF] numeric(10,0) NOT NULL CONSTRAINT [DF_LOG_SFSYNC_NRECAGG_FROM_SF] DEFAULT (''),
	[TEMPO_IMPIEGATO] numeric(10,0) NOT NULL CONSTRAINT [DF_LOG_SFSYNC_TEMPO_IMPIEGATO] DEFAULT ('')
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOG_SFSYNC] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_SFSYNC] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
