if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_CARONTE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOG_CARONTE]
GO
 
CREATE TABLE [dbo].[LOG_CARONTE] (
	id_unique uniqueidentifier ROWGUIDCOL NOT NULL ,
	LOG_CODCLI varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_RAGSOC varchar(80) COLLATE Latin1_General_CI_AS NULL ,
	LOG_TIPPRG varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	LOG_AAAAMM varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_MATRIC varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_UTEINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_DATINS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_ORAINS varchar(8) COLLATE Latin1_General_CI_AS NULL ,
	LOG_UTEMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_DATMOD varchar(10) COLLATE Latin1_General_CI_AS NULL ,
	LOG_ORAMOD varchar(8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOG_CARONTE] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_CARONTE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_CARONTE] WITH NOCHECK ADD 
	CONSTRAINT [DF_LOG_CARONTE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_LOG_CARONTE_LOG_CODCLI] DEFAULT ('') FOR [LOG_CODCLI],
	CONSTRAINT [DF_LOG_CARONTE_LOG_RAGSOC] DEFAULT ('') FOR [LOG_RAGSOC],
	CONSTRAINT [DF_LOG_CARONTE_LOG_TIPPRG] DEFAULT ('') FOR [LOG_TIPPRG],
	CONSTRAINT [DF_LOG_CARONTE_LOG_AAAAMM] DEFAULT ('') FOR [LOG_AAAAMM],
	CONSTRAINT [DF_LOG_CARONTE_LOG_MATRIC] DEFAULT ('') FOR [LOG_MATRIC],
	CONSTRAINT [DF_LOG_CARONTE_LOG_UTEINS] DEFAULT ('') FOR [LOG_UTEINS],
	CONSTRAINT [DF_LOG_CARONTE_LOG_DATINS] DEFAULT ('') FOR [LOG_DATINS],
	CONSTRAINT [DF_LOG_CARONTE_LOG_ORAINS] DEFAULT ('') FOR [LOG_ORAINS],
	CONSTRAINT [DF_LOG_CARONTE_LOG_UTEMOD] DEFAULT ('') FOR [LOG_UTEMOD],
	CONSTRAINT [DF_LOG_CARONTE_LOG_DATMOD] DEFAULT ('') FOR [LOG_DATMOD],
	CONSTRAINT [DF_LOG_CARONTE_LOG_ORAMOD] DEFAULT ('') FOR [LOG_ORAMOD]
GO
