if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_EVENTI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LOG_EVENTI]
GO

CREATE TABLE [dbo].[LOG_EVENTI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_EVENTO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[GRUPPO_EVENTO] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRIZIONE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[DATA_EVENTO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_EVENTO] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_EVENTO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
	[COD_USER] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
	[RUOLO_DEST] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
	[CAMPO_MODIFICATO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
	[VALORE_PREC] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
	[VALORE_SUCC] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
	[STATO_EVENTO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
	[RISPOSTA] [bit]  NULL,
	[ID_EVENTO_SUCC] [varchar] (32) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOG_EVENTI] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_EVENTI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_EVENTI] WITH NOCHECK ADD 
	CONSTRAINT [DF_LOG_EVENTI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_LOG_EVENTI_ID_EVENTO] DEFAULT ('') FOR [ID_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_GRUPPO_EVENTO] DEFAULT ('') FOR [GRUPPO_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_DESCRIZIONE] DEFAULT ('') FOR [DESCRIZIONE],
	CONSTRAINT [DF_LOG_EVENTI_[DF_LOG_EVENTI_DATA_EVENTO] DEFAULT ('') FOR [DATA_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_ORA_EVENTO] DEFAULT ('') FOR [ORA_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_TIPO_EVENTO] DEFAULT ('') FOR [TIPO_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_COD_USER] DEFAULT ('') FOR [COD_USER],
	CONSTRAINT [DF_LOG_EVENTI_RUOLO_DEST] DEFAULT ('') FOR [RUOLO_DEST],
	CONSTRAINT [DF_LOG_EVENTI_CAMPO_MODIFICATO] DEFAULT ('') FOR [CAMPO_MODIFICATO],
	CONSTRAINT [DF_LOG_EVENTI_VALORE_PREC] DEFAULT ('') FOR [VALORE_PREC],
	CONSTRAINT [DF_LOG_EVENTI_VALORE_SUCC] DEFAULT ('') FOR [VALORE_SUCC],
	CONSTRAINT [DF_LOG_EVENTI_STATO_EVENTO] DEFAULT ('') FOR [STATO_EVENTO],
	CONSTRAINT [DF_LOG_EVENTI_RISPOSTA] DEFAULT (0) FOR [RISPOSTA],
	CONSTRAINT [DF_LOG_EVENTI_ID_EVENTO_SUCC] DEFAULT ('') FOR [ID_EVENTO_SUCC]
	
GO

