
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_DELETED]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOG_DELETED]
GO  

CREATE TABLE [dbo].[LOG_DELETED](
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_LOG_DELETED_id_unique] DEFAULT (newid()),
	TABLE_NAME varchar (20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_TABLE_NAME] DEFAULT (''),
	AGGANCIO varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_AGGANCIO] DEFAULT (''),
	CHIAVE varchar (30) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_CHIAVE] DEFAULT (''),
	LIBERA varchar (254) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_LIBERA] DEFAULT (''),
	CODOPE varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_CODOPE] DEFAULT (''),
	NOMOPE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_NOMOPE] DEFAULT (''),
	DATLOG varchar (10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_DATREG] DEFAULT (''),
	ORALOG varchar (08) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_DELETED_ORAREG] DEFAULT ('')
) 

ALTER TABLE [dbo].[LOG_DELETED] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_DELETED] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
