

/****** Object:  Table [dbo].[LOG_KOMAX]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_KOMAX]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOG_KOMAX]
GO  


CREATE TABLE [dbo].[LOG_KOMAX](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_LOG_KOMAX_id_unique] DEFAULT (newid()),
	[LOG_DATA]             [varchar](10) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_DATA] DEFAULT (''),
	[LOG_DATA_REG]         [varchar](10) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_DATA_REG] DEFAULT (''),
	[LOG_ORA_REG]          [varchar](8) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_ORA_REG] DEFAULT (''),
	[LOG_TIPO_LOG]         [varchar](10) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_TIPO_LOG] DEFAULT (''),
	[LOG_AZIONE]           [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_AZIONE] DEFAULT (''),
	[LOG_ARTICOLO]         [varchar](35) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_ARTICOLO] DEFAULT (''),
	[LOG_POSIZIONE]        [varchar](10) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_POSIZIONE] DEFAULT (''),
	[LOG_PEZZI_RICHIESTI]  [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_PEZZI_RICHIESTI] DEFAULT (''),
	[LOG_PEZZI_BUONI]      [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_PEZZI_BUONI] DEFAULT (''),
	[LOG_PEZZI_PRODOTTI]   [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_PEZZI_PRODOTTI] DEFAULT (''),
	[LOG_PEZZI_INCOMPLETI] [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_PEZZI_INCOMPLETI] DEFAULT (''),
	[LOG_CICLO_ATTIVO]     [varchar](50) NULL CONSTRAINT [DF_LOG_KOMAX_LOG_CICLO_ATTIVO] DEFAULT (''),
	[LOG_NOTE]             [text] NULL

) 

ALTER TABLE [dbo].[LOG_KOMAX] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_KOMAX] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


