if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOG_ECOMMERCE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOG_ECOMMERCE]
GO
 
CREATE TABLE [dbo].[LOG_ECOMMERCE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_id_unique] DEFAULT newid(),
	[CODSYS] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_CODSYS] DEFAULT (''),
	[PROCEDURA] varchar(50) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_PROCEDURA] DEFAULT (''),
	[DATA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_DATA] DEFAULT (''),
	[ORA] varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_ORA] DEFAULT (''),
	[CODOPE] varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_CODOPE] DEFAULT (''),
	[NOMOPE] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_NOMOPE] DEFAULT (''),
	[ESITO] varchar(2) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_ESITO] DEFAULT (''),
	[MESSAGGIO] text NOT NULL CONSTRAINT [DF_LOG_ECOMMERCE_MESSAGGIO] DEFAULT ('')
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOG_ECOMMERCE] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_ECOMMERCE] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
