if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[LOGPRD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[LOGPRD]
GO
 
CREATE TABLE [dbo].[LOGPRD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_LOGPRD_id_unique] DEFAULT newid(),
	[IDATTIVITA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_IDATTIVITA] DEFAULT (''),
	[CODOPE] varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_CODOPE] DEFAULT (''),
	[DESOPE] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_DESOPE] DEFAULT (''),
	[CODFAL] varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_CODFAL] DEFAULT (''),
	[DESFAL] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_DESFAL] DEFAULT (''),
	[NUMORD] varchar(6) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_NUMORD] DEFAULT (''),
	[ANNORD] varchar(4) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_ANNORD] DEFAULT (''),
	[CODCLI] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_CODCLI] DEFAULT (''),
	[RAGSOC] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_RAGSOC] DEFAULT (''),
	[CODART] varchar(16) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_CODART] DEFAULT (''),
	[DESART] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_DESART] DEFAULT (''),
	[QTA] numeric(10,0) NOT NULL CONSTRAINT [DF_LOGPRD_QTA] DEFAULT (0),
	[CODSYS] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_CODSYS] DEFAULT (''),
	[DATCON] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_DATCON] DEFAULT (''),
	[NOTE] varchar(200) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_NOTE] DEFAULT (''),
	[STATO] varchar(20) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_STATO] DEFAULT (''),
	[DATA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_DATA] DEFAULT (''),
	[ORA] varchar(8) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_LOGPRD_ORA] DEFAULT (''),
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOGPRD] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOGPRD] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
