if exists (select * from dbo.sysobjects where id = object_id(N'[MARGINE_CV]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [MARGINE_CV]
GO

CREATE TABLE [MARGINE_CV] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[MIN]     	[numeric] (17,2) NULL ,
	[MAX]		[numeric] (17,2) NULL ,
	[MAR_MAX_SCA]	[numeric] (17,2) NULL ,
	[PERC_RIC] 	[numeric] (17,2) NULL ,
	[MARGINE] 	[numeric] (17,2) NULL ,
	[ACQMAX] 	[numeric] (17,2) NULL 
) ON [PRIMARY]
GO


ALTER TABLE [MARGINE_CV] WITH NOCHECK ADD 
	CONSTRAINT [PK_MARGINE_CV] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [MARGINE_CV] WITH NOCHECK ADD 
	CONSTRAINT [DF_MARGINE_CV_id_unique] 	DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_MARGINE_CV_MIN] 		DEFAULT (0) FOR [MIN],     
	CONSTRAINT [DF_MARGINE_CV_MAX]		DEFAULT (0) FOR [MAX],
	CONSTRAINT [DF_MARGINE_CV_MAR_MAX_SCA]	DEFAULT (0) FOR [MAR_MAX_SCA],
	CONSTRAINT [DF_MARGINE_CV_PERC_RIC]	DEFAULT (0) FOR [PERC_RIC],	
	CONSTRAINT [DF_MARGINE_CV_MARGINE] 	DEFAULT (0) FOR [MARGINE], 	  
	CONSTRAINT [DF_MARGINE_CV_ACQMAX] 	DEFAULT (0) FOR [ACQMAX] 	  
GO



delete from MARGINE_CV

insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (  0.00, 80.00,20.00,25.00,20.00, 80.00)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values ( 80.01,119.00,10.99,28.20,10.78,119.22)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (119.01,157.00,11.99,31.57,11.76,157.46)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (157.01,194.01,12.99,35.13,12.74,194.72)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (194.02,230.01,13.99,38.88,13.72,231.00)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (230.02,265.01,14.99,42.84,14.70,286.30)
insert into MARGINE_CV (MIN,MAX,MAR_MAX_SCA,PERC_RIC,MARGINE,ACQMAX) values (265.02,299.02,15.99,47.04,15.68,331.40)
                                                                                              
select * from MARGINE_CV order by min
