/*************************************************************************************

    INSERIMENTO DEI TERRITORI E STATI CHE VENGONO INDICATI
    IN COMPILAZIONE DEL MODELLO "UNICO"
    QUESTA TABELLA E' UTILIZZATA DALL' ELENCO CLIENTI/FORNITORI ANNUALE
    
*************************************************************************************/
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('238','ABU DHABI                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('002','AFGHANISTAN                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('239','AJMAN                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('087','ALBANIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('794','ALDERNEY C.I.                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('003','ALGERIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('148','AMERICAN SAMOA ISOLE                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('004','ANDORRA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('133','ANGOLA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('209','ANGUILLA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('197','ANTIGUA E BARBUDA                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('251','ANTILLE OLANDESI                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('005','ARABIA SAUDITA                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('006','ARGENTINA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('266','ARMENIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('212','ARUBA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('227','ASCENSION                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('007','AUSTRALIA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('008','AUSTRIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('268','AZERBAIGIAN                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('234','AZZORRE ISOLE                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('160','BAHAMAS                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('169','BAHRAIN                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('130','BANGLADESH                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('118','BARBADOS                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('795','BARBUDA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('009','BELGIO                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('198','BELIZE                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('158','BENIN                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('207','BERMUDA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('097','BHUTAN                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('264','BIELORUSSIA                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('010','BOLIVIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('274','BOSNIA-ERZEGOVINA                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('098','BOTSWANA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('280','BOUVET ISLAND                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('011','BRASILE                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('125','BRUNEI DARUSSALAM                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('012','BULGARIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('142','BURKINA FASO                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('025','BURUNDI                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('135','CAMBOGIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('119','CAMERUN                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('139','CAMPIONE D´ITALIA                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('013','CANADA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('100','CANARIE ISOLE                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('188','CAPO VERDE                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('256','CAROLINE ISOLE                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('211','CAYMAN (ISOLE)                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('275','CECA (REPUBBLICA)                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('143','CENTROAFRICANA (REPUBBLICA)             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('246','CEUTA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('230','CHAFARINAS                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('255','CHAGOS ISOLE                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('282','CHRISTMAS ISLAND                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('144','CIAD                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('015','CILE                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('016','CINA                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('101','CIPRO                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('279','CISGIORDANIA/STRISCIA DI GAZA           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('223','CLIPPERTON                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('281','COCOS (KEELING) ISLAND                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('017','COLOMBIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('176','COMORE                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('145','CONGO                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('018','CONGO (REP. DEMOCRATICA DEL)            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('237','COOK ISOLE                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('084','COREA (REPUBBLICA DI)                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('074','COREA (REP. POPOLARE DEMOCRATICA)       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('146','COSTA D´AVORIO                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('019','COSTA RICA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('261','CROAZIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('020','CUBA                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('021','DANIMARCA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('192','DOMINICA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('063','DOMINICANA (REPUBBLICA)                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('240','DUBAI                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('287','EAST TIMOR                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('024','ECUADOR                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('023','EGITTO                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('064','EL SALVADOR                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('796','EMIRATI ARABI UNITI                     ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('277','ERITREA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('257','ESTONIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('026','ETIOPIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('204','FAEROER (ISOLE)                         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('190','FALKLAND (ISOLE)                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('161','FIJI                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('027','FILIPPINE                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('028','FINLANDIA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('029','FRANCIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('241','FUIJAYRAH                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('157','GABON                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('164','GAMBIA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('267','GEORGIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('094','GERMANIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('112','GHANA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('082','GIAMAICA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('088','GIAPPONE                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('102','GIBILTERRA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('113','GIBUTI                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('122','GIORDANIA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('228','GOUGH                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('032','GRECIA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('156','GRENADA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('200','GROENLANDIA                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('214','GUADALUPA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('154','GUAM ISOLA DI                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('033','GUATEMALA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('123','GUAYANA FRANCESE                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('201','GUERNSEY C.I.                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('137','GUINEA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('185','GUINEA BISSAU                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('167','GUINEA EQUATORIALE                      ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('159','GUYANA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('034','HAITI                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('284','HEARD AND MCDONALD ISLAND               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('797','HERM C.I.                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('035','HONDURAS                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('103','HONG KONG                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('114','INDIA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('129','INDONESIA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('039','IRAN                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('038','IRAQ                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('040','IRLANDA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('041','ISLANDA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('252','ISOLE AMERICANE DEL PACIFICO            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('191','ISOLE SALOMONE                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('182','ISRAELE                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('202','JERSEY C.I.                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('269','KAZAKISTAN                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('116','KENYA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('270','KIRGHIZISTAN                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('194','KIRIBATI                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('126','KUWAIT                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('136','LAOS (REP. DEMOCRATICA POPOLARE)        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('089','LESOTHO                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('258','LETTONIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('095','LIBANO                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('044','LIBERIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('045','LIBIA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('090','LIECHTENSTEIN                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('259','LITUANIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('092','LUSSEMBURGO                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('059','MACAO                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('278','MACEDONIA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('104','MADAGASCAR                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('235','MADEIRA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('056','MALAWI                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('106','MALAYSIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('127','MALDIVE                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('149','MALI                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('105','MALTA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('203','MAN ISOLA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('219','MARIANNE SETTENTRIONALI (ISOLE)         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('107','MAROCCO                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('217','MARSHALL (ISOLE)                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('213','MARTINICA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('141','MAURITANIA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('128','MAURITIUS                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('226','MAYOTTE                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('231','MELILLA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('046','MESSICO                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('215','MICRONESIA (STATI FEDERATI DI)          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('177','MIDWAY ISOLE                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('265','MOLDOVIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('110','MONGOLIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('208','MONTSERRAT                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('134','MOZAMBICO                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('083','MYANMAR                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('206','NAMIBIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('109','NAURU                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('115','NEPAL                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('047','NICARAGUA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('150','NIGER                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('117','NIGERIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('205','NIUE                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('285','NORFOLK ISLAND                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('048','NORVEGIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('253','NUOVA CALEDONIA                         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('049','NUOVA ZELANDA                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('163','OMAN                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('050','PAESI BASSI                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('799','PAESI NON CLASSIFICATI                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('036','PAKISTAN                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('216','PALAU                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('051','PANAMA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('250','PANAMA - ZONA DEL CANALE                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('186','PAPUA NUOVA GUINEA                      ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('052','PARAGUAY                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('232','PENON DE ALHUCEMAS                      ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('233','PENON DE VELEZ DE LA GOMERA             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('053','PERU´                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('175','PITCAIRN                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('225','POLINESIA FRANCESE                      ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('054','POLONIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('055','PORTOGALLO                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('220','PORTORICO                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('091','PRINCIPATO DI MONACO                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('168','QATAR                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('242','RAS EL KAIMAH                           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('031','REGNO UNITO                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('078','REPUBBLICA SUDAFRICANA                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('247','REUNION                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('061','ROMANIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('151','RUANDA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('262','RUSSIA (FEDERAZIONE DI)                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('166','SAHARA OCCIDENTALE                      ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('195','SAINT KITTS E NEVIS                     ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('222','SAINT MARTIN SETTENTRIONALE             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('199','SAINTE LUCIA                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('248','SAINT-PIERRE E MIQUELON                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('131','SAMOA OCCIDENTALI                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('037','SAN MARINO                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('093','SANTA SEDE (CITTA´ DEL VATICANO)        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('187','SAO TOME E PRINCIPE                     ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('798','SARK C.I.                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('152','SENEGAL                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('189','SEYCHELLES                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('288','SERBIA E MONTENEGRO                     ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('243','SHARJAH                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('153','SIERRA LEONE                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('147','SINGAPORE                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('065','SIRIA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('276','SLOVACCHIA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('260','SLOVENIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('066','SOMALIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('283','SOUTH GEORGIA AND SOUTH SANDWICH.       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('067','SPAGNA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('085','SRI LANKA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('254','ST. HELENA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('196','ST. VINCENTE E LE GRENADINE             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('069','STATI UNITI                             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('070','SUDAN                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('124','SURINAM                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('286','SVALBARD AND JAN MAYEN ISLANDS          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('068','SVEZIA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('071','SVIZZERA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('138','SWAZILAND                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('272','TAGIKISTAN                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('022','TAIWAN                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('057','TANZANIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('180','TERRITORIO ANTARTICO BRITANNICO         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('183','TERRITORIO ANTARTICO FRANCESE           ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('245','TERRITORIO BRIT. OCEANO INDIANO         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('072','THAILANDIA                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('155','TOGO                                    ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('236','TOKELAU                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('162','TONGA                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('120','TRINIDAD E TOBAGO                       ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('229','TRISTAN DA CUNHA                        ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('075','TUNISIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('076','TURCHIA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('273','TURKMENISTAN                            ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('210','TURKS E CAICOS (ISOLE)                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('193','TUVALU                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('263','UCRAINA                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('132','UGANDA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('244','UMM AL QAIWAIN                          ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('077','UNGHERIA                                ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('080','URUGUAY                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('271','UZBEKISTAN                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('121','VANUATU                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('081','VENEZUELA                               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('221','VERGINI AMERICANE (ISOLE)               ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('249','VERGINI BRITANNICHE (ISOLE)             ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('062','VIETNAM                                 ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('178','WAKE ISOLE                              ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('218','WALLIS E FUTUNA                         ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('042','YEMEN                                   ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('058','ZAMBIA                                  ');
INSERT INTO NAZIONI_UNICO (codice,descri) VALUES ('073','ZIMBABWE                                ');

select * from nazioni_unico order by descri