
/****** Object:  Table [dbo].[PART_FOR_STO]    Script Date: 22/06/2015 17:56:05 ******/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PART_FOR_STO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[PART_FOR_STO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PART_FOR_STO](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[PAR_CODSOC] [varchar](2) NULL,
	[PAR_ANNO] [varchar](4) NULL,
	[PAR_TIPODO] [varchar](3) NULL,
	[PAR_NUMPRO] [varchar](13) NULL,
	[PAR_NREG] [varchar](10) NULL,
	[PAR_NPART] [numeric](10, 0) NULL,
	[PAR_NPROG] [numeric](5, 0) NULL,
	[PAR_CODCLI] [varchar](13) NULL,
	[PAR_RAGSOC] [varchar](40) NULL,
	[PAR_TEL] [varchar](15) NULL,
	[PAR_IVA] [varchar](11) NULL,
	[PAR_DTREG] [varchar](10) NULL,
	[PAR_DTFAT] [varchar](10) NULL,
	[PAR_NUMFAT] [varchar](20) NULL,
	[PAR_TMOV] [varchar](1) NULL,
	[PAR_TIPFAT] [varchar](3) NULL,
	[PAR_TOTIM] [numeric](17, 3) NULL,
	[PAR_TIMPOS] [numeric](17, 3) NULL,
	[PAR_FATT] [numeric](17, 3) NULL,
	[PAR_IMPO1] [numeric](17, 3) NULL,
	[PAR_IMPOS1] [numeric](17, 3) NULL,
	[PAR_TOT1] [numeric](17, 3) NULL,
	[PAR_CIVA1] [varchar](3) NULL,
	[PAR_IMPO2] [numeric](17, 3) NULL,
	[PAR_IMPOS2] [numeric](17, 3) NULL,
	[PAR_TOT2] [numeric](17, 3) NULL,
	[PAR_CIVA2] [varchar](3) NULL,
	[PAR_IMPO3] [numeric](17, 3) NULL,
	[PAR_IMPOS3] [numeric](17, 3) NULL,
	[PAR_TOT3] [numeric](17, 3) NULL,
	[PAR_CIVA3] [varchar](3) NULL,
	[PAR_IMPO4] [numeric](17, 3) NULL,
	[PAR_IMPOS4] [numeric](17, 3) NULL,
	[PAR_TOT4] [numeric](17, 3) NULL,
	[PAR_CIVA4] [varchar](3) NULL,
	[PAR_IMPO5] [numeric](17, 3) NULL,
	[PAR_IMPOS5] [numeric](17, 3) NULL,
	[PAR_TOT5] [numeric](17, 3) NULL,
	[PAR_CIVA5] [varchar](3) NULL,
	[PAR_CODPAG] [varchar](3) NULL,
	[PAR_DTSCAD] [varchar](10) NULL,
	[PAR_UTPPAR] [numeric](5, 0) NULL,
	[PAR_DAPAG] [numeric](13, 0) NULL,
	[PAR_GIAPAG] [numeric](17, 3) NULL,
	[PAR_DATPAG] [varchar](10) NULL,
	[PAR_FATRI] [bit] NULL,
	[PAR_CLOSE] [bit] NULL,
	[PAR_DESMOV] [varchar](254) NULL,
	[PAR_DESMO1] [varchar](254) NULL,
	[PAR_CAMBIO] [numeric](15, 10) NULL,
	[PAR_IMPVAL] [numeric](18, 4) NULL,
	[PAR_VALUTA] [varchar](3) NULL,
	[PAR_DTVAL] [varchar](10) NULL,
	[PAR_SYS] [varchar](10) NULL,
	[PAR_BANCA] [varchar](5) NULL,
	[PAR_PAGATO] [numeric](17, 3) NULL,
	[PAR_NPARTO] [numeric](10, 0) NULL,
	[PAR_CONTABILITA_PREVISIONALE] [varchar](1) NULL,
	[PAR_CODACQ] [varchar](3) NULL,
	[PAR_TIPOCONTRATTO] [varchar](5) NULL,
	[PAR_FORMAPAGAMENTO] [varchar](5) NULL,
	[PAR_GRADOIMPORTANZA] [varchar](5) NULL,
	[PAR_COSATRATTA] [varchar](5) NULL,
	[PAR_PRIPAGA] [varchar](4) NULL,
	[PAR_FATTD] [numeric](17, 3) NULL,
	[PAR_FATTA] [numeric](17, 3) NULL,
	[PAR_ANOMAX] [varchar](3) NULL,
	[PAR_NPORI] [varchar](10) NULL,
	[PAR_NPROT] [varchar](6) NULL,
	[MOV_NUCOM] [varchar](30) NULL,
	[PAR_NUCOM] [varchar](30) NULL,
	[PAR_RIFASC] [bit] NULL,
	[SYS_PARTI] [varchar](10) NULL,
	[PAR_TIPOPA] [varchar](3) NULL,
	[PAR_DTUSOL] [varchar](10) NULL,
	[PAR_NUMSOL] [numeric](6, 0) NULL,
	[PAR_NOPART] [bit] NULL,
	[PAR_STORIA] [text] NULL,
	[PAR_DTNEWS] [varchar](10) NULL,
	[PAR_ALLE01] [varchar](240) NULL,
	[PAR_ALLE02] [varchar](240) NULL,
	[PAR_ALLE03] [varchar](240) NULL,
	[PAR_ALLE04] [varchar](240) NULL,
	[PAR_ALLE05] [varchar](240) NULL,
	[SELEZIONE] [varchar](10) NULL,
	[PAR_BLOCCO] [bit] NULL,
	[PAR_STATO_CEE] [varchar](3) NULL,
	[PAR_NUMATRI] [numeric](20, 0) NULL,
	[PAR_EFFETDA] [varchar](30) NULL,
	[PAR_INTEPER] [varchar](30) NULL,
	[PAR_NOTEFF] [text] NULL,
	[PAR_DTSCOR] [varchar](10) NOT NULL,
 CONSTRAINT [PK_PART_FOR_STO] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CODSOC]  DEFAULT ('') FOR [PAR_CODSOC]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ANNO]  DEFAULT ('') FOR [PAR_ANNO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TIPODO]  DEFAULT ('') FOR [PAR_TIPODO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NUMPRO]  DEFAULT ('') FOR [PAR_NUMPRO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NREG]  DEFAULT ('') FOR [PAR_NREG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NPART]  DEFAULT (0) FOR [PAR_NPART]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NPROG]  DEFAULT (0) FOR [PAR_NPROG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CODCLI]  DEFAULT ('') FOR [PAR_CODCLI]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_RAGSOC]  DEFAULT ('') FOR [PAR_RAGSOC]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TEL]  DEFAULT ('') FOR [PAR_TEL]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IVA]  DEFAULT ('') FOR [PAR_IVA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTREG]  DEFAULT ('') FOR [PAR_DTREG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTFAT]  DEFAULT ('') FOR [PAR_DTFAT]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NUMFAT]  DEFAULT ('') FOR [PAR_NUMFAT]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TMOV]  DEFAULT ('') FOR [PAR_TMOV]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TIPFAT]  DEFAULT ('') FOR [PAR_TIPFAT]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOTIM]  DEFAULT (0) FOR [PAR_TOTIM]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TIMPOS]  DEFAULT (0) FOR [PAR_TIMPOS]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_FATT]  DEFAULT (0) FOR [PAR_FATT]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPO1]  DEFAULT (0) FOR [PAR_IMPO1]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPOS1]  DEFAULT (0) FOR [PAR_IMPOS1]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOT1]  DEFAULT (0) FOR [PAR_TOT1]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CIVA1]  DEFAULT ('') FOR [PAR_CIVA1]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPO2]  DEFAULT (0) FOR [PAR_IMPO2]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPOS2]  DEFAULT (0) FOR [PAR_IMPOS2]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOT2]  DEFAULT (0) FOR [PAR_TOT2]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CIVA2]  DEFAULT ('') FOR [PAR_CIVA2]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPO3]  DEFAULT (0) FOR [PAR_IMPO3]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPOS3]  DEFAULT (0) FOR [PAR_IMPOS3]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOT3]  DEFAULT (0) FOR [PAR_TOT3]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CIVA3]  DEFAULT ('') FOR [PAR_CIVA3]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPO4]  DEFAULT (0) FOR [PAR_IMPO4]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPOS4]  DEFAULT (0) FOR [PAR_IMPOS4]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOT4]  DEFAULT (0) FOR [PAR_TOT4]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CIVA4]  DEFAULT ('') FOR [PAR_CIVA4]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPO5]  DEFAULT (0) FOR [PAR_IMPO5]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPOS5]  DEFAULT (0) FOR [PAR_IMPOS5]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TOT5]  DEFAULT (0) FOR [PAR_TOT5]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CIVA5]  DEFAULT ('') FOR [PAR_CIVA5]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CODPAG]  DEFAULT ('') FOR [PAR_CODPAG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTSCAD]  DEFAULT ('') FOR [PAR_DTSCAD]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_UTPPAR]  DEFAULT (0) FOR [PAR_UTPPAR]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DAPAG]  DEFAULT (0) FOR [PAR_DAPAG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_GIAPAG]  DEFAULT (0) FOR [PAR_GIAPAG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DATPAG]  DEFAULT ('') FOR [PAR_DATPAG]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_FATRI]  DEFAULT (0) FOR [PAR_FATRI]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CLOSE]  DEFAULT (0) FOR [PAR_CLOSE]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DESMOV]  DEFAULT ('') FOR [PAR_DESMOV]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DESMO1]  DEFAULT ('') FOR [PAR_DESMO1]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CAMBIO]  DEFAULT (0) FOR [PAR_CAMBIO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_IMPVAL]  DEFAULT (0) FOR [PAR_IMPVAL]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_VALUTA]  DEFAULT ('') FOR [PAR_VALUTA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTVAL]  DEFAULT ('') FOR [PAR_DTVAL]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_SYS]  DEFAULT ('') FOR [PAR_SYS]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_BANCA]  DEFAULT ('') FOR [PAR_BANCA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_PAGATO]  DEFAULT (0) FOR [PAR_PAGATO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NPARTO]  DEFAULT ('0') FOR [PAR_NPARTO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_CONTABILITA_PREVISIONALE]  DEFAULT ('0') FOR [PAR_CONTABILITA_PREVISIONALE]
GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PAR_CODACQ]  DEFAULT ('   ') FOR [PAR_CODACQ]
--GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PAR_TIPOCONTRATTO]  DEFAULT ('     ') FOR [PAR_TIPOCONTRATTO]
--GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PAR_FORMAPAGAMENTO]  DEFAULT ('     ') FOR [PAR_FORMAPAGAMENTO]
--GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PAR_GRADOIMPORTANZA]  DEFAULT ('     ') FOR [PAR_GRADOIMPORTANZA]
--GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PPAR_COSATRATTA]  DEFAULT ('     ') FOR [PAR_COSATRATTA]
--GO

--ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_PAR_PAR_PRIPAGA]  DEFAULT ('    ') FOR [PAR_PRIPAGA]
--GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_FATTD]  DEFAULT ('0') FOR [PAR_FATTD]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_FATTA]  DEFAULT ('0') FOR [PAR_FATTA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ANOMAX]  DEFAULT ('') FOR [PAR_ANOMAX]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NPORI]  DEFAULT ('') FOR [PAR_NPORI]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NPROT]  DEFAULT ('') FOR [PAR_NPROT]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NUCOM]  DEFAULT (' ') FOR [PAR_NUCOM]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_RIFASC]  DEFAULT ((0)) FOR [PAR_RIFASC]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_SYS_PARTI]  DEFAULT ('') FOR [SYS_PARTI]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_TIPOPA]  DEFAULT ('') FOR [PAR_TIPOPA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTUSOL]  DEFAULT ('') FOR [PAR_DTUSOL]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NUMSOL]  DEFAULT ('0') FOR [PAR_NUMSOL]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NOPART]  DEFAULT ((0)) FOR [PAR_NOPART]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_STORIA]  DEFAULT ('') FOR [PAR_STORIA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTNEWS]  DEFAULT ('') FOR [PAR_DTNEWS]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ALLE01]  DEFAULT ('') FOR [PAR_ALLE01]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ALLE02]  DEFAULT ('') FOR [PAR_ALLE02]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ALLE03]  DEFAULT ('') FOR [PAR_ALLE03]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ALLE04]  DEFAULT ('') FOR [PAR_ALLE04]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_ALLE05]  DEFAULT ('') FOR [PAR_ALLE05]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_BLOCCO]  DEFAULT ((0)) FOR [PAR_BLOCCO]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_STATO_CEE]  DEFAULT ('') FOR [PAR_STATO_CEE]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NUMATRI]  DEFAULT ((0)) FOR [PAR_NUMATRI]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_EFFETDA]  DEFAULT ('') FOR [PAR_EFFETDA]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_INTEPER]  DEFAULT ('') FOR [PAR_INTEPER]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_NOTEFF]  DEFAULT ('') FOR [PAR_NOTEFF]
GO

ALTER TABLE [dbo].[PART_FOR_STO] ADD  CONSTRAINT [DF_PART_FOR_STO_PAR_DTSCOR]  DEFAULT ('') FOR [PAR_DTSCOR]
GO


