
DELETE FROM PARA WHERE CODICE = 'PWDCGP'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDCGP','PASSWORD PER RIALLINEARE I PROTOCOLLI PER BOLLATI','PROT')

SELECT * FROM PARA WHERE CODICE LIKE 'PWDCGP%' ORDER BY CODICE


