
DELETE FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'NAT'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT0','NESSUNA TRANSAZIONE IN TRIANGOLAZIONE',' ')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT1','ACQUISTO O VENDITA (COMPRESO IL BARATTO)','A')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT2','RESTITUZIONE O SOSTITUZIONE MERCE','B')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT3','AIUTI GOVERNATIVI PRIVATI O FINANZIATI DALLA COMUNITA EUROPEA)','C')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT4','OPERAZIONE IN VISTA DI UNA LAVORAZIONE PER CONTO TERZI O AD UNA RIPARAZIONE','D')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT5','OPERAZIONE SUCCESSIVA AD UNA LAVORAZIONE PER CONTO TERZI O AD UNA RIPARAZIONE','E')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT6','MOVIMENTO DI MERCI SENZA TRASFERIMENTO DI PROPRIETA PER NOLEGGIO,LEASING....','F')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT7','OPERAZIONE A TITOLO DI UN PROGRAMMA COMUNE DI DIFESA DI UN ALTRO PROGRAMMA INTERGOVERNATIVO','G')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT8','FORNITUR MATERIALI E MACCHINARI NEL QUADRO DI UN CONTRATTO GENERALE','H')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('NAT9','ALTRE TRANSAZIONI','I')


SELECT * FROM PARA WHERE CODICE LIKE 'NAT%' ORDER BY CODICE


