
DELETE FROM PARA WHERE CODICE = 'PWDRDA'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDRDA','PASSWORD PER AUTORIZZAZIONI SPECIALI IN GESTIONE RDA','0000')

SELECT * FROM PARA WHERE CODICE LIKE 'PWD%' ORDER BY CODICE


