
DELETE FROM PARA WHERE CODICE = 'PXML"'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PXML"','DOUBLE QUOTATION MARK','&quot;')

SELECT * FROM PARA WHERE CODICE LIKE 'PXML%' order by codice
