   
/* 
**********************************************************************************************
INSERIMENTO PARAMETRO "TIPOLOGIA ORDINE" IN PARA
**********************************************************************************************
*/

DELETE PARA WHERE SUBSTRING(CODICE,1,3) = 'TPO'


--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO001','VENDITA BENI','')
--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO002','VENDITA SERVIZI','')
--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO003','RIPARAZIONE','')
--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO101','VENDITA BENI    (BENI INTRASTAT)','SI-BENI-INTRASTAT')
--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO102','VENDITA SERVIZI (SERVIZI INTRASTAT)','SI-SERVIZI-INTRASTAT')
--INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPO103','RIPARAZIONE     (SERVIZI INTRASTAT)','SI-SERVIZI-INTRASTAT')


INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOU30','CAMPAGNA UNDER 30','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOU.P','CAMPAGNA USATO PLUS','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOMAT','ORDINE MATERIALI','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPONOL','ORDINE NOLEGGIO','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOOPZ','ORDINE OPZIONI','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOSER','ORDINE SERVICE','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOH2E','CAMPAGNA H2E','')
INSERT INTO PARA (CODICE,DESCRI,DESIVA) values ('TPOPHA','CAMPAGNA PHARMA','')