
DELETE FROM PARA WHERE CODICE = 'PWDPCK'
DELETE FROM PARA WHERE CODICE = 'PWDPKA'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDPCK','PASSWORD PER CONFERMA SPEDIZIONE PACKING LIST DI PRODUZIONE','1234')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDPKA','PASSWORD PER AUTORIZZAZIONE CLIENTI A RISCHIO IN PACKING LIST DI PRODUZIONE','4321')

SELECT * FROM PARA WHERE CODICE LIKE 'PWD%' ORDER BY CODICE


