
DELETE FROM PARA WHERE CODICE = 'PWDMCF'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDMCF','PASSWORD PER MODIFICA COMMENTI FATTURE CONTABILIZZATE','LOG9')

SELECT * FROM PARA WHERE CODICE LIKE 'PWD%' ORDER BY CODICE


