  
DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'DP%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'DP%'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
	VALUES ('01','DP10014578','DADI PRESSATI 100X145X78','MC','05','21','SEDE','1','6010110','EUR','D','DADI','012','P','S','S','MC','DADI PRESSATI',78,100,145,'DP','DADI PRESSATI')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC)
	VALUES ('01','DP10014578',1000)

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
	VALUES ('01','DP10014595','DADI PRESSATI 100X145X95','MC','05','21','SEDE','1','6010110','EUR','D','DADI','012','P','S','S','MC','DADI PRESSATI',95,100,145,'DP','DADI PRESSATI')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC)
	VALUES ('01','DP10014595',1000)

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
	VALUES ('01','DP14514578','DADI PRESSATI 145X145X78','MC','05','21','SEDE','1','6010110','EUR','D','DADI','012','P','S','S','MC','DADI PRESSATI',78,145,145,'DP','DADI PRESSATI')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC)
	VALUES ('01','DP14514578',1000)

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
	VALUES ('01','DP145145100','DADI PRESSATI 145X145X100','MC','05','21','SEDE','1','6010110','EUR','D','DADI','012','P','S','S','MC','DADI PRESSATI',100,145,145,'DP','DADI PRESSATI')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC)
	VALUES ('01','DP145145100',1000)

SELECT * FROM U_ART_PR WHERE ART_CODPRI LIKE 'DP%' ORDER BY ART_CODPRI
SELECT * FROM U_ART_AN WHERE ART_CODPRI LIKE 'DP%' ORDER BY ART_CODPRI