
-- POPOLAMENTO PARAMETRO PER INTESTAZIONI PERSONALIZZATE BOLLATI IVA

DELETE FROM PARA WHERE CODICE LIKE 'IBI%'

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFOSTA',
		'TITOLO PERSONALIZZATO BOLLATO IVAFOSTA',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA ACQUISTI' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFOCEE',
		'TITOLO PERSONALIZZATO BOLLATO IVAFOCEE',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA ACQUISTI REVERSE CHARGE' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVACLCEE',
		'TITOLO PERSONALIZZATO BOLLATO IVACLCEE',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		'')

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVARECOM',
		'TITOLO PERSONALIZZATO BOLLATO IVARECOM',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA CESSIONI COMPENSATIVE' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVACOSTA',
		'TITOLO PERSONALIZZATO BOLLATO IVACOSTA',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		'')

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVACASTA',
		'TITOLO PERSONALIZZATO BOLLATO IVACASTA',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		'')

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVACLSTA',
		'TITOLO PERSONALIZZATO BOLLATO IVACLSTA',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA VENDITE' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFATNOELE',
		'TITOLO PERSONALIZZATO BOLLATO IVAFATNOELE',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA VENDITE IN SOSPENSIONE' ELSE '' END)
		
INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFATSIELE',
		'TITOLO PERSONALIZZATO BOLLATO IVAFATSIELE',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'BOLLATO IVA VENDITE SPLIT PAYMENT' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFATSOSINC',
		'TITOLO PERSONALIZZATO BOLLATO IVAFATSOSINC',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		CASE WHEN COALESCE((SELECT AZI_PRDISP FROM U_AZI_PA),0) = 1 THEN 'ELENCO FATTURE IN SOSPENSIONE INCASSATE' ELSE '' END)

INSERT INTO PARA (CODICE,DESCRI,ITALIANO,LIBERA) 
VALUES ('IBIIVAFONOC',
		'TITOLO PERSONALIZZATO BOLLATO IVAFONOC',
		'INSERIRE NEL CAMPO LIBERA IL TITOLO PERSONALIZZATO DA FAR COMPARIRE NEL BOLLATO PRODOTTO DALLA OMONIMA PROCEDURA DI STAMPA BOLLATO IVA',
		'')


SELECT * FROM PARA WHERE CODICE LIKE 'IBI%' ORDER BY CODICE

