
DELETE FROM PARA WHERE CODICE = 'E13E13'

INSERT INTO PARA (CODICE, DESCRI, LIBERA, ITALIANO) VALUES ('E13E13','CODICI A BARRE EAN13','8010000000000','ITPRODUARTICK	
IT= NAZIONE ITALIA = 80/81
PRODU = CODICE PRODUTTORE
ARTIC = CODICE ARTICOLO
K = CHECK DIGIT')

SELECT * FROM PARA WHERE CODICE LIKE 'E13%' ORDER BY CODICE


