   
/* 
********************************************************************************************************
INSERIMENTO PARAMETRO "SERVIZI ASSISTENZA": 'SAS'
********************************************************************************************************
*/


DELETE PARA WHERE SUBSTRING(CODICE,1,3) = 'SAS'


INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASAAB','ABBONAMENTO ANNUALE BRUCIATORE','400','6')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASAAM','ABBONAMENTO ANNUALE CALDAIA MURALE + A TERRA INF. 35 KW.','402','4')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASABM','ABBONAMENTO BIENNALE CALDAIA M. +  ANALISI COMB. +LIBRETTO','401','8')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASACB','ABBONAMENTO COMPLETO BRUCIATORE CON FORNITURA LIBRETTO','403','4')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASASB','ABBONAMENTO SEMPLICE BRUCIATORE','404','2')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASADC','ANALISI DI COMBUSTIONE BRUCIATORE E / O CALD. M.+TERRA INF. 35  KW.','600-601','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASLAV','LAVAGGIO SCAMBIATORE','350','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASLDC','LIBRETTO DI CENTRALE  BRUCIATORE','700','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASLDI','LIBRETTO DI IMPIANTO   CALDAIA MURALE + A TERRA INF. 35 KW.','701','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASPCO','PULIZIA CALDAIA','500','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASREA','REVISIONE + ANALISI DI COMBUSTIONE','333','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASRBM','REVISIONE BIENNALE CALDAIA M. + ANALISI COMB. + LIBRETTO','301','2')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASREV','REVISIONE BRUCIATORE  E / O  CALDAIA MURALE + A TERRA','300','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASRAC','REVISIONE AUTOCLAVE ','','0')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASRVMC','REVISIONE VMC','','0')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASRAD','REVISIONE ADDOLCITORE','','0')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASTRC','ATERZO RESPONSABILE Esercizio e Manutenzione ( ACB+ADC+PCO+CCT)','801','0')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASIGI','PRESTAZIONI SUSSIDIARIE IN GARANZIA (Imar interventi+ricambi) LISTINO 18','931','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASAVV','AVVIAMENTI (Viessmann NB: prime accensioni)','940','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASIGV','INTERVENTI IN GARANZIA','941','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASRSA','RIMBORSO SPESE ASSISTENZA  (Sant’Andrea)','950','1')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASAUTOC','AUTOCERTIFICAZIONE PROVINCIA DI MILANO/BERGAMO/CREMONA','2.AUTOC','0')
INSERT INTO PARA (CODICE,DESCRI,CONTO2,PAR_COSTCAD1) values ('SASPCF','ASSISTENZA ???????','PCF','0')


--SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'SAS'