/*************************************************************  
 INSERIMENTO PARAMETRI DI DEFAULT PER PRODUZIONE DADI PRESSATI
**************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'MCD%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MCD01','CAPACITÀ PRODUTTIVA MEDIA PRODUZIONE DADI (MC al giorno)','200',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'FALPRSDAD'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,PAR_DATINS) VALUES ('FALPRSDAD','PRESSATURA DADI','1','DAD',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

SELECT * FROM PARA WHERE CODICE LIKE 'MCD%'
SELECT * FROM PARA WHERE CODICE LIKE 'FALPRSDAD'
