
-- TOP PREVENTIVI CLIENTI: FASCIA COMPETENZA 'P'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'P' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_OFF_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_OFF_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA



-- TOP ORDINI CLIENTI: FASCIA COMPETENZA 'O'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'O' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_ORD_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_ORD_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA


-- TOP ORDINI FORNITORI : FASCIA COMPETENZA 'O'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'O' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_ORF_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_ORF_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA


-- TOP FATTURE CLIENTI : FASCIA COMPETENZA 'F'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'F' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_FAT_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_FAT_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA

-- TOP FATTURE PROFORMA : FASCIA COMPETENZA 'F'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'F' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_FAP_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_FAP_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA



-- TOP DDT CLIENTI: FASCIA COMPETENZA 'D'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'D' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_BOL_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_BOL_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA


-- TOP DDT CARICO DA FORNITORE: FASCIA COMPETENZA 'D'
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,41) + 'D' + SUBSTRING(LIBERA,43,212) WHERE CODICE IN (SELECT 'TOP'+ORD_CAUS AS CAUSALE FROM U_BFO_TT GROUP BY ORD_CAUS)

SELECT 'TOP'+ORD_CAUS AS CAUSALE, LIBERA FROM U_BFO_TT 
LEFT OUTER JOIN PARA ON CODICE = 'TOP'+ORD_CAUS
GROUP BY ORD_CAUS,LIBERA

