
DELETE FROM PARA WHERE CODICE = 'PWDDTO'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('PWDDTO','PASSWORD PER RETRODATAZIONE ORDINE CLIENTE','RDTO')

SELECT * FROM PARA WHERE CODICE LIKE 'PWD%' ORDER BY CODICE


