/********************************************************************
 PARAMETRO STATO CONTROLLO QUALITA'
********************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'SCQ%'


INSERT INTO PARA (CODICE,DESCRI) VALUES ('SCQQRC','RICHIESTO CONTROLLO QUALITA''')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('SCQQOK','C.Q. SUPERATO CON ESITO POSITIVO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('SCQQNC','MATERIALE UTILIZZABILE MA NON CONFORME ALLE RICHIESTE')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('SCQQKO','C.Q. NON SUPERATO')

SELECT * FROM PARA WHERE CODICE LIKE 'SCQ%'

