/********************************************************************
 PARAMETRO ATTIVITA' PER STUDI PROFESSIONALI
*********************************************************************
********************************************************************/

delete from para where codice like 'SOL01'
insert into para (codice,descri,libera,italiano,note,desiva) values ('SOL01','Situazione contabile alla data di riferimento primo sollecito','Situazione contabile alla data di riferimento primo sollecito','Nella eventualità che abbiate già provveduto al pagamento, Vi preghiamo di non voler considerare la presente e Vi chiediamo cortesemente di inviarci a mezzo fax o via e-mail gli estremi del pagamento.Nel caso in cui non abbiate ancora provveduto al saldo sopra riportato, nulla ricevendo entro la fine del corrente mese, ci vedremo costretti ad addebitarVi gli interessi e spese.Con questa occasione Vi porgiamo distinti saluti.','In allegato Vi inviamo la situazione delle fatture clienti ancora in essere. Vi chiediamo cortesemente di verificare la situazione contabile e di comunicarci via fax o via email le eventuali discordanze e/o gli eventuali pagamenti effettuati da noi non ancora registrati contabilmente. Con questa occasione Vi porgiamo distinti saluti.','Ufficio Contabilità')
delete from para where codice like 'SOL02'
insert into para (codice,descri,libera,italiano,note,desiva) values ('SOL02','Situazione contabile alla data di riferimento secondo sollecito','Situazione contabile alla data di riferimento secondo sollecito','Nella eventualità che abbiate già provveduto al pagamento, Vi preghiamo di non voler considerare la presente e Vi chiediamo cortesemente di inviarci a mezzo fax o via e-mail gli estremi del pagamento.Nel caso in cui non abbiate ancora provveduto al saldo sopra riportato, nulla ricevendo entro la fine del corrente mese, ci vedremo costretti ad addebitarVi gli interessi e spese.Con questa occasione Vi porgiamo distinti saluti.','In allegato Vi inviamo la situazione delle fatture clienti ancora in essere. Vi chiediamo cortesemente di verificare la situazione contabile e di comunicarci via fax o via email le eventuali discordanze e/o gli eventuali pagamenti effettuati da noi non ancora registrati contabilmente. Con questa occasione Vi porgiamo distinti saluti.','Ufficio Contabilità')
delete from para where codice like 'SOL03'
insert into para (codice,descri,libera,italiano,note,desiva) values ('SOL03','Situazione contabile alla data di riferimento terzo sollecito','Situazione contabile alla data di riferimento terzo sollecito','Nella eventualità che abbiate già provveduto al pagamento, Vi preghiamo di non voler considerare la presente e Vi chiediamo cortesemente di inviarci a mezzo fax o via e-mail gli estremi del pagamento.Nel caso in cui non abbiate ancora provveduto al saldo sopra riportato, nulla ricevendo entro la fine del corrente mese, ci vedremo costretti ad addebitarVi gli interessi e spese.Con questa occasione Vi porgiamo distinti saluti.','In allegato Vi inviamo la situazione delle fatture clienti ancora in essere. Vi chiediamo cortesemente di verificare la situazione contabile e di comunicarci via fax o via email le eventuali discordanze e/o gli eventuali pagamenti effettuati da noi non ancora registrati contabilmente. Con questa occasione Vi porgiamo distinti saluti.','Ufficio Contabilità')




select codice,descri,libera,italiano,note,desiva,* from para where codice like 'SOL%'
