/********************************************************************/
/* POPOLAMENTO PARAMETRI PER CAMPI PER GESTIONE QUALIFICA FORNITORE */
/********************************************************************/
-- Campo DIVISIONE
DELETE FROM PARA WHERE CODICE LIKE 'DIF%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('DIFPRO','PRODUZIONE','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('DIFGEN','SERVIZI GENERALI','02')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('DIFALT','ALTRO','03')
SELECT * FROM PARA WHERE CODICE LIKE 'DIF%' ORDER BY LIBERA

-- Campo TIPOLOGIA
DELETE FROM PARA WHERE CODICE LIKE 'QUF%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('QUFQUA','QUALIFICATO','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('QUFNOQ','NON QUALIFICATO','02')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('QUFVER','IN VERIFICA','03')
SELECT * FROM PARA WHERE CODICE LIKE 'QUF%' ORDER BY LIBERA


-- Campo TIPO QUALIFICA
DELETE FROM PARA WHERE CODICE LIKE 'TQF%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TQFMED','MEDICALE','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TQFISO','ISO','02')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TQFQUA','QUALITÀ','03')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TQFN/A','NON APPLICABILE','04')
SELECT * FROM PARA WHERE CODICE LIKE 'TQF%' ORDER BY LIBERA


-- Campo TIPO CONTRATTO
DELETE FROM PARA WHERE CODICE LIKE 'TCF%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TCFOBL','OBL','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TCFOEM','OEM','02')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TCFDIS','DISTRIBUZIONE','03')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TCFN/A','NON APPLICABILE','04')
SELECT * FROM PARA WHERE CODICE LIKE 'TCF%' ORDER BY LIBERA


-- Campo CLASSE DI RISCHIO
DELETE FROM PARA WHERE CODICE LIKE 'CRF%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CRFI','I','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CRFIFM','I con funzione di misura','02')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CRFIIA','IIA','03')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CRFIIB','IIB','04')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CRFN/A','NON APPLICABILE','05')
SELECT * FROM PARA WHERE CODICE LIKE 'CRF%' ORDER BY LIBERA
