
/****** Object:  Table [dbo].[PROD_PACKFOR]    Script Date: 17/11/2016 09:57:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PROD_PACKFOR](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[IDPRG] [varchar](10) NULL,
	[MAG_UNIQUE] [varchar](10) NULL,
	[ORDSYS] [varchar](10) NULL,
	[CODMAG] [varchar](6) NULL,
	[CODINT] [varchar](16) NULL,
	[CODART] [varchar](16) NULL,
	[DESART] [varchar](200) NULL,
	[QTA] [numeric](17, 4) NULL,
	[UM] [varchar](6) NULL,
	[QTAKG] [numeric](17, 4) NULL,
	[QTAMQ] [numeric](17, 4) NULL,
	[QTAML] [numeric](17, 4) NULL,
	[QTAMC] [numeric](17, 4) NULL,
	[QTANR] [numeric](12, 0) NULL,
	[SEQUEN] [numeric](10, 0) NULL,
	[PRDFIN] [bit] NULL,
	[NUMPCK] [varchar](10) NULL,
	[DATPCK] [varchar](10) NULL,
	[QTAPCK] [numeric](17, 4) NULL,
	[QTAKGPCK] [numeric](17, 4) NULL,
	[QTAMQPCK] [numeric](17, 4) NULL,
	[QTAMLPCK] [numeric](17, 4) NULL,
	[QTAMCPCK] [numeric](17, 4) NULL,
	[QTANRPCK] [numeric](12, 0) NULL,
	[QTANR2PCK] [numeric](12, 0) NULL,
	[NUMCAM] [numeric](3, 0) NULL,
	[VETTOR] [varchar](3) NULL,
	[DESVET] [varchar](200) NULL,
	[DATTRA] [varchar](10) NULL,
	[ORATRA] [varchar](5) NULL,
	[FLGOK] [bit] NULL,
	[FLGDDT] [bit] NULL,
	[NUMDDT] [varchar](6) NULL,
	[DATDDT] [varchar](10) NULL,
	[SYSDDT] [varchar](10) NULL,
	[FLGRISK] [bit] NULL,
	[INS_CODOPE] [varchar](20) NULL,
	[INS_NOMOPE] [varchar](50) NULL,
	[INS_DATREG] [varchar](10) NULL,
	[INS_ORAREG] [varchar](8) NULL,
	[MOD_CODOPE] [varchar](20) NULL,
	[MOD_NOMOPE] [varchar](50) NULL,
	[MOD_DATREG] [varchar](10) NULL,
	[MOD_ORAREG] [varchar](8) NULL,
	[NRPALLETS] [numeric](13, 0) NULL,
	[QTANRC] [numeric](17, 0) NULL,
	[LOTTO] [varchar](20) NULL,
	[CAUSXDDT] [varchar](3) NULL,

	[MAGDEP] [varchar](3) NULL,
	[CODFOR] [varchar](10) NULL,
	[RAGSOC] [varchar](10) NULL,
	[SPESSO] [numeric](5,0) NULL,
	[ALTEZZ] [numeric](6,0) NULL,
	[LUNGHE] [numeric](7,0) NULL,
	[DESTIN] [varchar](254) NULL

 CONSTRAINT [PK_PROD_PACKFOR] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_IDPRG]  DEFAULT ('') FOR [IDPRG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MAG_UNIQUE]  DEFAULT ('') FOR [MAG_UNIQUE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_ORDSYS]  DEFAULT ('') FOR [ORDSYS]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_CODMAG]  DEFAULT ('') FOR [CODMAG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_CODINT]  DEFAULT ('') FOR [CODINT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_CODART]  DEFAULT ('') FOR [CODART]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DESART]  DEFAULT ('') FOR [DESART]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTA]  DEFAULT ((0)) FOR [QTA]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_UM]  DEFAULT ('') FOR [UM]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAKG]  DEFAULT ((0)) FOR [QTAKG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAMQ]  DEFAULT ((0)) FOR [QTAMQ]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAML]  DEFAULT ((0)) FOR [QTAML]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAMC]  DEFAULT ((0)) FOR [QTAMC]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTANR]  DEFAULT ((0)) FOR [QTANR]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_SEQUEN]  DEFAULT ((0)) FOR [SEQUEN]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_PRDFIN]  DEFAULT ((0)) FOR [PRDFIN]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_NUMPCK]  DEFAULT ('') FOR [NUMPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DATPCK]  DEFAULT ('') FOR [DATPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAPCK]  DEFAULT ((0)) FOR [QTAPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAKGPCK]  DEFAULT ((0)) FOR [QTAKGPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAMQPCK]  DEFAULT ((0)) FOR [QTAMQPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAMLPCK]  DEFAULT ((0)) FOR [QTAMLPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTAMCPCK]  DEFAULT ((0)) FOR [QTAMCPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTANRPCK]  DEFAULT ((0)) FOR [QTANRPCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTANR2PCK]  DEFAULT ((0)) FOR [QTANR2PCK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_NUMCAM]  DEFAULT ((0)) FOR [NUMCAM]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_VETTOR]  DEFAULT ('') FOR [VETTOR]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DESVET]  DEFAULT ('') FOR [DESVET]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DATTRA]  DEFAULT ('') FOR [DATTRA]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_ORATRA]  DEFAULT ('') FOR [ORATRA]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_FLGOK]  DEFAULT ((0)) FOR [FLGOK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_FLGDDT]  DEFAULT ((0)) FOR [FLGDDT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_NUMDDT]  DEFAULT ('') FOR [NUMDDT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DATDDT]  DEFAULT ('') FOR [DATDDT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_SYSDDT]  DEFAULT ('') FOR [SYSDDT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_FLGRISK]  DEFAULT ((0)) FOR [FLGRISK]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_INS_CODOPE]  DEFAULT ('') FOR [INS_CODOPE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_INS_NOMOPE]  DEFAULT ('') FOR [INS_NOMOPE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_INS_DATREG]  DEFAULT ('') FOR [INS_DATREG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_INS_ORAREG]  DEFAULT ('') FOR [INS_ORAREG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MOD_CODOPE]  DEFAULT ('') FOR [MOD_CODOPE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MOD_NOMOPE]  DEFAULT ('') FOR [MOD_NOMOPE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MOD_DATREG]  DEFAULT ('') FOR [MOD_DATREG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MOD_ORAREG]  DEFAULT ('') FOR [MOD_ORAREG]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_NRPALLETS]  DEFAULT ((0)) FOR [NRPALLETS]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_QTANRC]  DEFAULT ((0)) FOR [QTANRC]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_LOTTO]  DEFAULT ('') FOR [LOTTO]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_CAUSXDDT]  DEFAULT ('') FOR [CAUSXDDT]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_MAGDEP]  DEFAULT ('') FOR [MAGDEP]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_CODFOR]  DEFAULT ('') FOR [CODFOR]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_RAGSOC]  DEFAULT ('') FOR [RAGSOC]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_SPESSO]  DEFAULT (0) FOR [SPESSO]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_ALTEZZ]  DEFAULT (0) FOR [ALTEZZ]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_LUNGHE]  DEFAULT (0) FOR [LUNGHE]
GO

ALTER TABLE [dbo].[PROD_PACKFOR] ADD  CONSTRAINT [DF_PROD_PACKFOR_DESTIN]  DEFAULT ('') FOR [DESTIN]
GO
