if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PROD_IMPEGNI]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[PROD_IMPEGNI]
GO

CREATE TABLE [dbo].[PROD_IMPEGNI] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[IDPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[FASELA] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[SEQUEN] [numeric] (10,0) NULL ,
	[CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[DESART] [varchar] (200) COLLATE Latin1_General_CI_AS NULL ,
	[CODINT] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[SPESSO] [numeric] (5,0) NULL ,
	[ALTEZZ] [numeric] (5,0) NULL ,
	[LUNGHE] [numeric] (6,0) NULL ,
	[QTANRIMP] [numeric] (12,0) NULL ,
	[QTAIMP] [numeric] (17,4) NULL ,
	[UM] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NEWUNQ] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CODMAG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[FILA_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[PIAN_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[UBIC_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[DATIMP] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORAIMP] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[CODOPE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[NOMOPE] [varchar] (100) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROD_IMPEGNI] WITH NOCHECK ADD 
	CONSTRAINT [PK_PROD_IMPEGNI] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PROD_IMPEGNI] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROD_IMPEGNI_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_PROD_IMPEGNI_IDPRG] DEFAULT ('') FOR [IDPRG],
	CONSTRAINT [DF_PROD_IMPEGNI_FASELA] DEFAULT ('') FOR [FASELA],
	CONSTRAINT [DF_PROD_IMPEGNI_SEQUEN] DEFAULT (0) FOR [SEQUEN],
	CONSTRAINT [DF_PROD_IMPEGNI_CODART] DEFAULT ('') FOR [CODART],
	CONSTRAINT [DF_PROD_IMPEGNI_DESART] DEFAULT ('') FOR [DESART],
	CONSTRAINT [DF_PROD_IMPEGNI_CODINT] DEFAULT ('') FOR [CODINT],
	CONSTRAINT [DF_PROD_IMPEGNI_SPESSO] DEFAULT (0) FOR [SPESSO],
	CONSTRAINT [DF_PROD_IMPEGNI_ALTEZZ] DEFAULT (0) FOR [ALTEZZ],
	CONSTRAINT [DF_PROD_IMPEGNI_LUNGHE] DEFAULT (0) FOR [LUNGHE],
	CONSTRAINT [DF_PROD_IMPEGNI_QTANRIMP] DEFAULT (0) FOR [QTANRIMP],
	CONSTRAINT [DF_PROD_IMPEGNI_QTAIMP] DEFAULT (0) FOR [QTAIMP],
	CONSTRAINT [DF_PROD_IMPEGNI_UM] DEFAULT ('') FOR [UM],
	CONSTRAINT [DF_PROD_IMPEGNI_MAG_NEWUNQ] DEFAULT ('') FOR [MAG_NEWUNQ],
	CONSTRAINT [DF_PROD_IMPEGNI_CODMAG] DEFAULT ('') FOR [CODMAG],
	CONSTRAINT [DF_PROD_IMPEGNI_FILA_X] DEFAULT ('') FOR [FILA_X],
	CONSTRAINT [DF_PROD_IMPEGNI_PIAN_X] DEFAULT ('') FOR [PIAN_X],
	CONSTRAINT [DF_PROD_IMPEGNI_UBIC_X] DEFAULT ('') FOR [UBIC_X],
	CONSTRAINT [DF_PROD_IMPEGNI_DATIMP] DEFAULT ('') FOR [DATIMP],
	CONSTRAINT [DF_PROD_IMPEGNI_ORAIMP] DEFAULT ('') FOR [ORAIMP],
	CONSTRAINT [DF_PROD_IMPEGNI_CODOPE] DEFAULT ('') FOR [CODOPE],
	CONSTRAINT [DF_PROD_IMPEGNI_NOMOPE] DEFAULT ('') FOR [NOMOPE]
GO

