           
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PROGRAMMI_BATCH]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[PROGRAMMI_BATCH]
GO
 
CREATE TABLE [dbo].[PROGRAMMI_BATCH] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_PROGRAMMA_BATCH] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SYS_PROGRAMMA_BATCH] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PROGRAMMA_BATCH] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL

) ON [PRIMARY]   
GO


ALTER TABLE [dbo].[PROGRAMMI_BATCH] WITH NOCHECK ADD 
	CONSTRAINT [DF_PROGRAMMI_BATCH_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_PROGRAMMI_BATCH_ID_PROGRAMMA_BATCH] DEFAULT ('') FOR [ID_PROGRAMMA_BATCH],
	CONSTRAINT [DF_PROGRAMMI_BATCH_SYS_PROGRAMMA_BATCH] DEFAULT ('') FOR [SYS_PROGRAMMA_BATCH],
	CONSTRAINT [DF_PROGRAMMI_BATCH_PROGRAMMA_BATCH] DEFAULT ('') FOR [PROGRAMMA_BATCH],
	CONSTRAINT [DF_PROGRAMMI_BATCH_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

