if exists (select * from dbo.sysobjects where id = object_id(N'[RAPPATT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [RAPPATT]
GO

CREATE TABLE [RAPPATT] (
	id_unique  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[IDUTENTE] 	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDPROSPRA] 	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[FLAG_CF] 	[varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[IDCOMMESSA]	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,  --campo idcommessa su commessa_tt
	[IDCOMPXCOM]	[varchar] (32) COLLATE Latin1_General_CI_AS NULL ,  --campo idcommessa_dc su commessa_dc
	[CODSOGG]	[varchar] (16) COLLATE Latin1_General_CI_AS NULL ,  	--campo codsogg su commessa_dc
	[CODICE] 	[varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[D_CONTATTO] 	[varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[D_PROSSSCAD] 	[varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TEMPOIMPIEG] 	[numeric] (5, 2) NULL,
	[PROSPRA] 	[varchar] (150) COLLATE Latin1_General_CI_AS NULL ,
	[ATTIVSVOLTA] 	[text] COLLATE Latin1_General_CI_AS NULL ,
	[STEPSUCCES] 	[text] COLLATE Latin1_General_CI_AS NULL ,
	[ANNOTAZIONI] 	[text] COLLATE Latin1_General_CI_AS NULL ,
	[B_BLOCCATO] 	[varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[UTENTEINS] 	[varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[D_DATAINS] 	[varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[UTENTEMOD] 	[varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[D_DATAMOD] 	[varchar] (10) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [RAPPATT] WITH NOCHECK ADD 
	CONSTRAINT [PK_RAPPATT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RAPPATT] WITH NOCHECK ADD 
	CONSTRAINT [DF_RAPPATT_id_unique] DEFAULT (newid()) FOR [id_unique],
	--CONSTRAINT [DF_RAPPATT_IDRAPPATT]   DEFAULT ('') FOR [IDRAPPATT],  	NON SERVE A NOI
	CONSTRAINT [DF_RAPPATT_IDUTENTE]    DEFAULT ('') FOR [IDUTENTE],	  
	CONSTRAINT [DF_RAPPATT_IDPROSPRA]   DEFAULT ('') FOR [IDPROSPRA],  
	CONSTRAINT [DF_RAPPATT_FLAG_CF]   DEFAULT ('') FOR [FLAG_CF],  
	CONSTRAINT [DF_RAPPATT_IDCOMMESSA]  DEFAULT ('') FOR [IDCOMMESSA],  --CAMPO NON ESISTENTE SU OMEGA MA UTILE
	CONSTRAINT [DF_RAPPATT_IDCOMPXCOM]  DEFAULT ('') FOR [IDCOMPXCOM],  
	CONSTRAINT [DF_RAPPATT_CODSOGG]	    DEFAULT ('') FOR [CODSOGG],  
	CONSTRAINT [DF_RAPPATT_CODICE] 	    DEFAULT ('') FOR [CODICE],  
	CONSTRAINT [DF_RAPPATT_D_CONTATTO]  DEFAULT ('') FOR [D_CONTATTO], 
	CONSTRAINT [DF_RAPPATT_D_PROSSSCAD] DEFAULT ('') FOR [D_PROSSSCAD],
	CONSTRAINT [DF_RAPPATT_TEMPOIMPIEG] DEFAULT (0) FOR [TEMPOIMPIEG],
	CONSTRAINT [DF_RAPPATT_PROSPRA]  	DEFAULT ('') FOR [PROSPRA],  
	CONSTRAINT [DF_RAPPATT_ATTIVSVOLTA] DEFAULT ('') FOR [ATTIVSVOLTA],
	CONSTRAINT [DF_RAPPATT_STEPSUCCES]  DEFAULT ('') FOR [STEPSUCCES], 
	CONSTRAINT [DF_RAPPATT_ANNOTAZIONI]  DEFAULT ('') FOR [ANNOTAZIONI],
	CONSTRAINT [DF_RAPPATT_B_BLOCCATO]  DEFAULT ('') FOR [B_BLOCCATO], 
	CONSTRAINT [DF_RAPPATT_UTENTEINS]   DEFAULT ('') FOR [UTENTEINS],  
	CONSTRAINT [DF_RAPPATT_D_DATAINS]   DEFAULT ('') FOR [D_DATAINS],  
	CONSTRAINT [DF_RAPPATT_UTENTEMOD]   DEFAULT ('') FOR [UTENTEMOD],  
	CONSTRAINT [DF_RAPPATT_D_DATAMOD]   DEFAULT ('') FOR [D_DATAMOD]
GO


