


/****** Object:  Table [dbo].[RETTI_BIL_RIC]    Script Date: 19/04/2016 16:15:38 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RETTI_BIL_RIC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[RETTI_BIL_RIC]
GO


/****** Object:  Table [dbo].[RETTI_BIL_RIC]    Script Date: 11/05/2016 12:41:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RETTI_BIL_RIC](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[RET_CODSOC] [varchar](2) NULL,
	[RET_ANNO] [varchar](4) NULL,
	[RET_RIGA] [varchar](10) NULL,
	[RET_DESRIG] [varchar](70) NULL,
	[RET_IMPORT] [numeric](17, 3) NULL,
	[SELEZIONE] [varchar](10) NULL,
	[RET_VALUTA] [varchar](3) NULL,
 CONSTRAINT [PK_RETTI_BIL_RIC] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_CODSOC]  DEFAULT ('') FOR [RET_CODSOC]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_ANNO]  DEFAULT ('') FOR [RET_ANNO]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_RIGA]  DEFAULT ('') FOR [RET_RIGA]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_DESRIG]  DEFAULT ('') FOR [RET_DESRIG]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_IMPORT]  DEFAULT (0) FOR [RET_IMPORT]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO

ALTER TABLE [dbo].[RETTI_BIL_RIC] ADD  CONSTRAINT [DF_RETTI_BIL_RIC_RET_VALUTA]  DEFAULT ('') FOR [RET_VALUTA]
GO


