if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RICEMAC_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[RICEMAC_TT]
GO

CREATE TABLE [dbo].[RICEMAC_TT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_RICEMAC] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PRODOTTO] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[MATERIALE] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[FASCIA] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[CODICE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LOTTO] [varchar] (8) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RICEMAC_TT] WITH NOCHECK ADD 
	CONSTRAINT [PK_RICEMAC_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RICEMAC_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_RICEMAC_TT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_RICEMAC_TT_PJ_RICEMAC] DEFAULT ('') FOR [PJ_RICEMAC],
	CONSTRAINT [DF_RICEMAC_TT_PRODOTTO] DEFAULT ('') FOR [PRODOTTO],
	CONSTRAINT [DF_RICEMAC_TT_MATERIALE] DEFAULT ('') FOR [MATERIALE],
	CONSTRAINT [DF_RICEMAC_TT_FASCIA] DEFAULT ('') FOR [FASCIA],
	CONSTRAINT [DF_RICEMAC_TT_CODICE] DEFAULT ('') FOR [CODICE],
	CONSTRAINT [DF_RICEMAC_TT_LOTTO] DEFAULT ('') FOR [LOTTO]
GO

