if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RICEMAC_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[RICEMAC_DD]
GO

CREATE TABLE [dbo].[RICEMAC_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_RICEMAC] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[SEQUENZA] [numeric](10, 0) NULL ,
	[PARAMETRO] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[UM] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[VALORE] [numeric](17, 6) NULL ,
	[PAGINA_PLC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[COLORE_PLC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL1] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL2] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL3] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL4] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL5] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_CTRL6] [varchar] (5) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RICEMAC_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_RICEMAC_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RICEMAC_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_RICEMAC_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_RICEMAC_DD_PJ_RICEMAC] DEFAULT ('') FOR [PJ_RICEMAC],
	CONSTRAINT [DF_RICEMAC_DD_SEQUENZA] DEFAULT (0) FOR [SEQUENZA],
	CONSTRAINT [DF_RICEMAC_DD_PARAMETRO] DEFAULT ('') FOR [PARAMETRO],
	CONSTRAINT [DF_RICEMAC_DD_UM] DEFAULT ('') FOR [UM],
	CONSTRAINT [DF_RICEMAC_DD_VALORE] DEFAULT (0) FOR [VALORE],
	CONSTRAINT [DF_RICEMAC_DD_PAGINA_PLC] DEFAULT ('') FOR [PAGINA_PLC],
	CONSTRAINT [DF_RICEMAC_DD_COLORE_PLC] DEFAULT ('') FOR [COLORE_PLC],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL1] DEFAULT ('') FOR [ORA_CTRL1],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL2] DEFAULT ('') FOR [ORA_CTRL2],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL3] DEFAULT ('') FOR [ORA_CTRL3],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL4] DEFAULT ('') FOR [ORA_CTRL4],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL5] DEFAULT ('') FOR [ORA_CTRL5],
	CONSTRAINT [DF_RICEMAC_DD_ORA_CTRL6] DEFAULT ('') FOR [ORA_CTRL6]
GO

