if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RICHIEST_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[RICHIEST_DD]
GO

CREATE TABLE [dbo].[RICHIEST_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[ID_DETTAGLIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_TIPSOG] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_FIGPROF] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_DESGEN] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SOG_ANNESP] [numeric](3, 0) NULL ,
	[SOG_POSTI] [numeric](3, 0) NULL ,
	[D_INIZIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[D_FINE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_GGPREV] [numeric](10, 0) NULL ,
	[SOG_COSTO] [numeric](17, 2) NULL ,
	[SOG_RICAVO] [numeric](17, 2) NULL ,
	[SOG_UTILE] [numeric](17, 2) NULL ,
	[SOG_STATO] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_SEDELA] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_QTASOG] [numeric](3, 0) NULL ,
	[SOG_ANNOTA] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SOG_ANNRIS] [text] COLLATE Latin1_General_CI_AS NULL ,
	[OREGG] [numeric](10, 2) NULL ,
	[UMCOSTO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[UMRICAVO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[VALCOSTO] [numeric](17, 2) NULL ,
	[VALRICAVO] [numeric](17, 2) NULL ,
	[UM_SOG_GGPREV] [varchar] (2) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RICHIEST_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_RICHIEST_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RICHIEST_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_RICHIEST_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_RICHIEST_DD_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_RICHIEST_DD_ID_DETTAGLIO] DEFAULT ('') FOR [ID_DETTAGLIO],
	CONSTRAINT [DF_RICHIEST_DD_SOG_TIPSOG] DEFAULT ('') FOR [SOG_TIPSOG],
	CONSTRAINT [DF_RICHIEST_DD_SOG_FIGPROF] DEFAULT ('') FOR [SOG_FIGPROF],
	CONSTRAINT [DF_RICHIEST_DD_SOG_DESGEN] DEFAULT ('') FOR [SOG_DESGEN],
	CONSTRAINT [DF_RICHIEST_DD_SOG_ANNESP] DEFAULT (0) FOR [SOG_ANNESP],
	CONSTRAINT [DF_RICHIEST_DD_SOG_POSTI] DEFAULT (0) FOR [SOG_POSTI],
	CONSTRAINT [DF_RICHIEST_DD_D_INIZIO] DEFAULT ('') FOR [D_INIZIO],
	CONSTRAINT [DF_RICHIEST_DD_D_FINE] DEFAULT ('') FOR [D_FINE],
	CONSTRAINT [DF_RICHIEST_DD_SOG_GGPREV] DEFAULT (0) FOR [SOG_GGPREV],
	CONSTRAINT [DF_RICHIEST_DD_SOG_COSTO] DEFAULT (0) FOR [SOG_COSTO],
	CONSTRAINT [DF_RICHIEST_DD_SOG_RICAVO] DEFAULT (0) FOR [SOG_RICAVO],
	CONSTRAINT [DF_RICHIEST_DD_SOG_UTILE] DEFAULT (0) FOR [SOG_UTILE],
	CONSTRAINT [DF_RICHIEST_DD_SOG_STATO] DEFAULT ('') FOR [SOG_STATO],
	CONSTRAINT [DF_RICHIEST_DD_SOG_SEDELA] DEFAULT ('') FOR [SOG_SEDELA],
	CONSTRAINT [DF_RICHIEST_DD_SOG_QTASOG] DEFAULT (0) FOR [SOG_QTASOG],
	CONSTRAINT [DF_RICHIEST_DD_SOG_ANNOTA] DEFAULT ('') FOR [SOG_ANNOTA],
	CONSTRAINT [DF_RICHIEST_DD_SOG_ANNRIS] DEFAULT ('') FOR [SOG_ANNRIS],
	CONSTRAINT [DF_RICHIEST_DD_OREGG] DEFAULT (0) FOR [OREGG],
	CONSTRAINT [DF_RICHIEST_DD_UMCOSTO] DEFAULT ('0') FOR [UMCOSTO],
	CONSTRAINT [DF_RICHIEST_DD_UMRICAVO] DEFAULT ('0') FOR [UMRICAVO],
	CONSTRAINT [DF_RICHIEST_DD_VALCOSTO] DEFAULT ('0') FOR [VALCOSTO],
	CONSTRAINT [DF_RICHIEST_DD_VALRICAVO] DEFAULT ('0') FOR [VALRICAVO],
	CONSTRAINT [DF_RICHIEST_DD_UM_SOG_GGPREV] DEFAULT ('') FOR [UM_SOG_GGPREV]
GO

