

/****** Object:  Table [dbo].[RIGHE_BIL_RIC]    Script Date: 19/04/2016 16:15:38 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RIGHE_BIL_RIC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[RIGHE_BIL_RIC]
GO

/****** Object:  Table [dbo].[RIGHE_BIL_RIC]    Script Date: 11/05/2016 12:33:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RIGHE_BIL_RIC](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_RIGHE_BIL_RIC_id_unique]  DEFAULT (newid()),
	[COR_CODSOC] [varchar](2) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_CODSOC]  DEFAULT (''),
	[COR_RIGA] [varchar](10) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_RIGA]  DEFAULT (''),
	[COR_DESRIG] [varchar](50) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_DESRIG]  DEFAULT (''),
	[COR_CONFLU] [varchar](10) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_CONFLU]  DEFAULT (''),
	[COR_DESCON] [varchar](50) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_DESCON]  DEFAULT (''),
	[COR_SEGNO] [varchar](1) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_COR_SEGNO]  DEFAULT (''),
	[SELEZIONE] [varchar](10) NULL CONSTRAINT [DF_RIGHE_BIL_RIC_SELEZIONE]  DEFAULT (''),
 CONSTRAINT [PK_RIGHE_BIL_RIC] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


