-- RIPORTA SU U_BAN_AN IL CONTO CONTABILE IMPOSTATO SU U_CC_TT (SE PRESENTE)

UPDATE U_BAN_AN 
	SET BAN_CONCON = COALESCE((SELECT TOP 1 ORD_CONTO FROM U_CCO_TT WHERE ORD_BANCA = BAN_CODBAN),'')
WHERE BAN_CODBAN  IN (select BAN_CODBAN from U_BAN_AN where ban_prese='S')
