
-- ALLARGAMENTO CAMPO CODICE ATTIVITA' A 10 CARATTERI
ALTER TABLE [dbo].[COMMESSA_DP] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[COMMESSA_DC] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[BUDGET_PREV] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[BUDGET_CONS] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[FATTURABILE_R] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[FATTURABILE_A] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[FATTURABILE_P] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[FATTURABILE_S] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[FATTURABILE_X] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[PIANIFIC_COMM] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

ALTER TABLE [dbo].[BUDGET_SINT_DD] ALTER COLUMN CodAttivita VARCHAR(10) COLLATE Latin1_General_CI_AS NULL

