if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[RISUMANA]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[RISUMANA]
GO

CREATE TABLE [dbo].[RISUMANA] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[IDRisUmana] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[Curricul] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[CentrCom] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[AnaAzi] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[Codice] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[Cognome] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Nome] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[Sigla] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[Sesso] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[CodFiscale] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PartitaIva] [varchar] (11) COLLATE Latin1_General_CI_AS NULL ,
	[LocNascita] [varchar] (120) COLLATE Latin1_General_CI_AS NULL ,
	[D_Nascita] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[Eta] [numeric](17, 6) NULL ,
	[LocResidenz] [varchar] (120) COLLATE Latin1_General_CI_AS NULL ,
	[IndResidenz] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[CapResidenz] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[LocDomicil] [varchar] (120) COLLATE Latin1_General_CI_AS NULL ,
	[IndDomicil] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[CapDomicil] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[TelDomicil] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[FaxDom] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[FaxRes] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[TelFisso] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[TelMobile] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[EMail] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[Annotazioni] [varchar] (255) COLLATE Latin1_General_CI_AS NULL ,
	[B_RisSociet] [bit] NULL ,
	[B_RisGruppo] [bit] NULL ,
	[B_RisEstern] [bit] NULL ,
	[UtenteIns] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[D_DataIns] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[UtenteMod] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[D_DataMod] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ModPag] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[TermPagCli] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[TermPagFor] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[TAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_RISORSA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[IDTITOLO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[TELRESIDENZ] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[IDSTATORIS] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[NAZIONE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[IDSTATOCIV] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDPOSMILIT] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PAGCLI] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[PAGFOR] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[PASSWORD] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[USERID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[RUOLO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[EMAIL1] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[EMAIL2] [varchar] (100) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RISUMANA] WITH NOCHECK ADD 
	CONSTRAINT [PK_RISUMANA] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RISUMANA] WITH NOCHECK ADD 
	CONSTRAINT [DF_RISUMANA_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_RISUMANA_IDRisUmana] DEFAULT ('') FOR [IDRisUmana],
	CONSTRAINT [DF_RISUMANA_Curricul] DEFAULT ('') FOR [Curricul],
	CONSTRAINT [DF_RISUMANA_CentrCom] DEFAULT ('') FOR [CentrCom],
	CONSTRAINT [DF_RISUMANA_AnaAzi] DEFAULT ('') FOR [AnaAzi],
	CONSTRAINT [DF_RISUMANA_Codice] DEFAULT ('') FOR [Codice],
	CONSTRAINT [DF_RISUMANA_Cognome] DEFAULT ('') FOR [Cognome],
	CONSTRAINT [DF_RISUMANA_Nome] DEFAULT ('') FOR [Nome],
	CONSTRAINT [DF_RISUMANA_Sigla] DEFAULT ('') FOR [Sigla],
	CONSTRAINT [DF_RISUMANA_Sesso] DEFAULT ('') FOR [Sesso],
	CONSTRAINT [DF_RISUMANA_CodFiscale] DEFAULT ('') FOR [CodFiscale],
	CONSTRAINT [DF_RISUMANA_PartitaIva] DEFAULT ('') FOR [PartitaIva],
	CONSTRAINT [DF_RISUMANA_LocNascita] DEFAULT ('') FOR [LocNascita],
	CONSTRAINT [DF_RISUMANA_D_Nascita] DEFAULT ('') FOR [D_Nascita],
	CONSTRAINT [DF_RISUMANA_Eta] DEFAULT (0) FOR [Eta],
	CONSTRAINT [DF_RISUMANA_LocResidenz] DEFAULT ('') FOR [LocResidenz],
	CONSTRAINT [DF_RISUMANA_IndResidenz] DEFAULT ('') FOR [IndResidenz],
	CONSTRAINT [DF_RISUMANA_CapResidenz] DEFAULT ('') FOR [CapResidenz],
	CONSTRAINT [DF_RISUMANA_LocDomicil] DEFAULT ('') FOR [LocDomicil],
	CONSTRAINT [DF_RISUMANA_IndDomicil] DEFAULT ('') FOR [IndDomicil],
	CONSTRAINT [DF_RISUMANA_CapDomicil] DEFAULT ('') FOR [CapDomicil],
	CONSTRAINT [DF_RISUMANA_TelDomicil] DEFAULT ('') FOR [TelDomicil],
	CONSTRAINT [DF_RISUMANA_FaxDom] DEFAULT ('') FOR [FaxDom],
	CONSTRAINT [DF_RISUMANA_FaxRes] DEFAULT ('') FOR [FaxRes],
	CONSTRAINT [DF_RISUMANA_TelFisso] DEFAULT ('') FOR [TelFisso],
	CONSTRAINT [DF_RISUMANA_TelMobile] DEFAULT ('') FOR [TelMobile],
	CONSTRAINT [DF_RISUMANA_EMail] DEFAULT ('') FOR [EMail],
	CONSTRAINT [DF_RISUMANA_Annotazioni] DEFAULT ('') FOR [Annotazioni],
	CONSTRAINT [DF_RISUMANA_B_RisSociet] DEFAULT (0) FOR [B_RisSociet],
	CONSTRAINT [DF_RISUMANA_B_RisGruppo] DEFAULT (0) FOR [B_RisGruppo],
	CONSTRAINT [DF_RISUMANA_B_RisEstern] DEFAULT (0) FOR [B_RisEstern],
	CONSTRAINT [DF_RISUMANA_UtenteIns] DEFAULT ('') FOR [UtenteIns],
	CONSTRAINT [DF_RISUMANA_D_DataIns] DEFAULT ('') FOR [D_DataIns],
	CONSTRAINT [DF_RISUMANA_UtenteMod] DEFAULT ('') FOR [UtenteMod],
	CONSTRAINT [DF_RISUMANA_D_DataMod] DEFAULT ('') FOR [D_DataMod],
	CONSTRAINT [DF_RISUMANA_ModPag] DEFAULT ('') FOR [ModPag],
	CONSTRAINT [DF_RISUMANA_TermPagCli] DEFAULT ('') FOR [TermPagCli],
	CONSTRAINT [DF_RISUMANA_TermPagFor] DEFAULT ('') FOR [TermPagFor],
	CONSTRAINT [DF_RISUMANA_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_RISUMANA_TIPO_RISORSA] DEFAULT ('') FOR [TIPO_RISORSA],
	CONSTRAINT [DF_RISUMANA_IDTITOLO] DEFAULT ('') FOR [IDTITOLO],
	CONSTRAINT [DF_RISUMANA_TELRESIDENZ] DEFAULT ('') FOR [TELRESIDENZ],
	CONSTRAINT [DF_RISUMANA_IDSTATORIS] DEFAULT ('') FOR [IDSTATORIS],
	CONSTRAINT [DF_RISUMANA_NAZIONE] DEFAULT ('') FOR [NAZIONE],
	CONSTRAINT [DF_RISUMANA_IDSTATOCIV] DEFAULT ('') FOR [IDSTATOCIV],
	CONSTRAINT [DF_RISUMANA_IDPOSMILIT] DEFAULT ('') FOR [IDPOSMILIT],
	CONSTRAINT [DF_RISUMANA_PAGCLI] DEFAULT ('') FOR [PAGCLI],
	CONSTRAINT [DF_RISUMANA_PAGFOR] DEFAULT ('') FOR [PAGFOR],
	CONSTRAINT [DF_RISUMANA_PASSWORD] DEFAULT ('') FOR [PASSWORD],
	CONSTRAINT [DF_RISUMANA_USERID] DEFAULT ('') FOR [USERID],
	CONSTRAINT [DF_RISUMANA_RUOLO] DEFAULT ('') FOR [RUOLO],
	CONSTRAINT [DF_RISUMANA_EMAIL1] DEFAULT ('') FOR [EMAIL1],
	CONSTRAINT [DF_RISUMANA_EMAIL2] DEFAULT ('') FOR [EMAIL2]
GO

