
/****** Object:  Table [dbo].[S_MAG_MO]    Script Date: 01/04/2015 18.09.05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[S_MAG_MO](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[MOV_CODSOC] [varchar](2) NULL,
	[MOV_CODMAG] [varchar](6) NULL,
	[MOV_ARTGRU] [varchar](1) NULL,
	[MOV_CODART] [varchar](16) NULL,
	[MOV_TOP] [varchar](3) NULL,
	[MOV_NUMDOC] [varchar](15) NULL,
	[MOV_DTDOCU] [varchar](10) NULL,
	[MOV_QTAMOV] [numeric](19, 4) NULL,
	[MOV_PREACQ] [numeric](19, 6) NULL,
	[MOV_SCONTO] [numeric](9, 2) NULL,
	[MOV_CODFOR] [varchar](10) NULL,
	[MOV_PREVEN] [numeric](19, 6) NULL,
	[MOV_IVAVEN] [varchar](3) NULL,
	[MOV_DTREGI] [varchar](10) NULL,
	[MOV_AGGPAR] [varchar](1) NULL,
	[MOV_VALVEN] [numeric](15, 2) NULL,
	[MOV_VALACQ] [numeric](15, 2) NULL,
	[MOV_QTARES] [numeric](13, 2) NULL,
	[MOV_CORR] [varchar](1) NULL,
	[MOV_IMPOST] [numeric](12, 0) NULL,
	[MOV_RECNO] [numeric](12, 0) NULL,
	[SELEZIONE] [varchar](10) NULL,
	[MOV_UM] [varchar](2) NULL,
	[MOV_QTCONF] [numeric](12, 2) NULL,
	[MOV_QTXCON] [numeric](10, 3) NULL,
	[MOV_COORD] [varchar](23) NULL,
	[MOV_RAGSOC] [varchar](40) NULL,
	[MOV_VALUTA] [varchar](3) NULL,
	[MOV_SERIE] [varchar](3) NULL,
	[MOV_DSERIE] [varchar](30) NULL,
	[MOV_AAPROD] [numeric](6, 0) NULL,
	[MOV_SERCAR] [varchar](3) NULL,
	[MOV_NUMDA] [numeric](11, 0) NULL,
	[MOV_NUMAL] [numeric](11, 0) NULL,
	[MOV_DESART] [varchar](100) NULL,
	[MOV_NOTVAR] [varchar](100) NULL,
	[MOV_CODTAG] [varchar](3) NULL,
	[MOV_DESTAG] [varchar](30) NULL,
	[MOV_CODCOL] [varchar](3) NULL,
	[MOV_DESCOL] [varchar](30) NULL,
	[MOV_TRASME] [bit] NULL,
	[MOV_NOTE] [text] NULL,
	[MOV_CODPDV] [varchar](10) NULL,
	[MOV_ORAMOV] [varchar](8) NULL,
	[MOV_SEGNO] [varchar](1) NULL,
	[MOV_TIPMOV] [varchar](3) NULL,
	[MOV_FORNIT] [varchar](10) NULL,
	[MOV_DESFOR] [varchar](50) NULL,
	[MOV_FLGTRA] [bit] NULL,
	[MOV_PRZCON] [numeric](19, 6) NULL,
	[MOV_LEGSYS] [varchar](10) NULL,
	[MOV_CODCAS] [varchar](6) NULL,
	[MOV_LEGAME] [varchar](10) NULL,
	[MOV_PAGAME] [varchar](3) NULL,
	[MOV_NUMORF] [varchar](6) NULL,
	[MOV_DATORF] [varchar](10) NULL,
	[MOV_SC1] [numeric](8, 2) NULL,
	[MOV_SC2] [numeric](8, 2) NULL,
	[MOV_SC3] [numeric](8, 2) NULL,
	[MOV_CODACQ] [varchar](3) NULL,
	[MOV_DATSCA] [varchar](10) NULL,
	[MOV_TIPORI] [numeric](3, 0) NULL,
	[MOV_NUMORI] [varchar](6) NULL,
	[MOV_DATORI] [varchar](10) NULL,
	[MOV_NUMIDE] [varchar](6) NULL,
	[MOV_CODBUN] [varchar](10) NULL,
	[MOV_ANNO] [varchar](4) NULL,
	[MOV_UNIQUE] [varchar](10) NULL,
	[MOV_TIPTRA] [varchar](3) NULL,
	[MOV_SYSGGG] [varchar](10) NULL,
	[MOV_SYSGGS] [varchar](10) NULL,
	[MOV_SYSDAG] [varchar](10) NULL,
	[MOV_SYSDAS] [varchar](10) NULL,
	[MOV_CODOPE] [varchar](20) NULL,
	[MOV_NOMOPE] [varchar](50) NULL,
	[MOV_PRZCAM] [numeric](19, 6) NULL,
	[MOV_NUMCAM] [varchar](6) NULL,
	[MOV_DATCAM] [varchar](10) NULL,
	[MOV_INICAM] [varchar](10) NULL,
	[MOV_FINCAM] [varchar](10) NULL,
	[MOV_SC1CAM] [numeric](8, 2) NULL,
	[MOV_SC2CAM] [numeric](8, 2) NULL,
	[MOV_SC3CAM] [numeric](8, 2) NULL,
	[MOV_SC4CAM] [numeric](8, 2) NULL,
	[MOV_SC5CAM] [numeric](8, 2) NULL,
	[MOV_FISCAM] [numeric](19, 6) NULL,
	[MOV_CODMAT] [varchar](3) NULL,
	[MOV_DESMAT] [varchar](30) NULL,
	[MOV_SPESSO] [numeric](5, 0) NULL,
	[MOV_ALTEZZ] [numeric](7, 0) NULL,
	[MOV_LUNGHE] [numeric](8, 0) NULL,
	[MOV_NRLINT] [numeric](12, 0) NULL,
	[MOV_NRDBOB] [numeric](8, 0) NULL,
	[MOV_QTAKG] [numeric](19, 4) NULL,
	[MOV_QTAMQ] [numeric](19, 4) NULL,
	[MOV_QTAML] [numeric](19, 4) NULL,
	[MOV_CDAFOR] [varchar](20) NULL,
	[MOV_OINFOR] [varchar](10) NULL,
	[MOV_PINFOR] [varchar](10) NULL,
	[MOV_DTPFOR] [varchar](10) NULL,
	[MOV_TRAFOR] [varchar](3) NULL,
	[MOV_NBAFOR] [numeric](13, 2) NULL,
	[MOV_BDAFOR] [numeric](13, 2) NULL,
	[MOV_BALFOR] [numeric](13, 2) NULL,
	[MOV_PNKFOR] [numeric](13, 2) NULL,
	[MOV_ANAART] [varchar](16) NULL,
	[MOV_DTINCQ] [varchar](10) NULL,
	[MOV_ORINCQ] [varchar](8) NULL,
	[MOV_DTFICQ] [varchar](10) NULL,
	[MOV_ORFICQ] [varchar](8) NULL,
	[MOV_CDRECQ] [varchar](3) NULL,
	[MOV_DSRECQ] [varchar](50) NULL,
	[MOV_QTAKGA] [numeric](11, 2) NULL,
	[MOV_QTAMQA] [numeric](11, 2) NULL,
	[MOV_QTAMLA] [numeric](11, 2) NULL,
	[MOV_TIPART] [varchar](1) NULL,
	[MOV_FLGCEL] [bit] NULL,
	[MOV_QTACON] [numeric](10, 2) NULL,
	[MOV_SERBOL] [varchar](3) NULL,
	[MOV_SERNUM] [varchar](3) NULL,
	[MOV_NUMEDA] [numeric](9, 0) NULL,
	[MOV_NUMEAL] [numeric](9, 0) NULL,
	[MOV_CBFISC] [varchar](50) NULL,
	[MOV_CODCLI] [varchar](10) NULL,
	[MOV_DESCLI] [varchar](50) NULL,
	[MST_DATAST] [varchar](10) NULL,
	[MST_ORASTO] [varchar](8) NULL,
	[MST_CODOPE] [varchar](20) NULL,
	[MST_DESOPE] [varchar](50) NULL,
	[MOV_FILA_X] [varchar](5) NULL,
	[MOV_PIAN_X] [varchar](5) NULL,
	[MOV_UBIC_X] [varchar](5) NULL,
	[MOV_FILA_N] [numeric](5, 0) NULL,
	[MOV_PIAN_N] [numeric](5, 0) NULL,
	[MOV_UBIC_N] [numeric](5, 0) NULL,
	[MOV_CSTMAN] [numeric](16, 6) NULL,
	[MOV_CSTSCA] [numeric](16, 6) NULL,
	[MOV_NUMMOV] [varchar](6) NULL,
	[MOV_DOCMOD] [bit] NULL,
	[MOV_QTAMC] [numeric](19, 4) NULL,
	[MOV_MAGUNQ] [varchar](10) NULL,
	[MOV_QUAPRO] [varchar](3) NULL,
	[MOV_CLIENT] [varchar](10) NULL,
	[MOV_QTANR] [numeric](19, 4) NULL,
	[MOV_GIANEG] [bit] NULL,
	[MOV_SERIAL] [varchar](20) NULL,
	[MOV_PRSPOT] [bit] NULL,
	[MOV_TRCKNG] [text] NOT NULL,
 CONSTRAINT [PK_S_MAG_MO] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODSOC]  DEFAULT ('') FOR [MOV_CODSOC]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODMAG]  DEFAULT ('') FOR [MOV_CODMAG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ARTGRU]  DEFAULT ('') FOR [MOV_ARTGRU]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODART]  DEFAULT ('') FOR [MOV_CODART]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TOP]  DEFAULT ('') FOR [MOV_TOP]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMDOC]  DEFAULT ('') FOR [MOV_NUMDOC]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DTDOCU]  DEFAULT ('') FOR [MOV_DTDOCU]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAMOV]  DEFAULT ((0)) FOR [MOV_QTAMOV]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PREACQ]  DEFAULT ((0)) FOR [MOV_PREACQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SCONTO]  DEFAULT ((0)) FOR [MOV_SCONTO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODFOR]  DEFAULT ('') FOR [MOV_CODFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PREVEN]  DEFAULT ((0)) FOR [MOV_PREVEN]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_IVAVEN]  DEFAULT ('') FOR [MOV_IVAVEN]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DTREGI]  DEFAULT ('') FOR [MOV_DTREGI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_AGGPAR]  DEFAULT ('') FOR [MOV_AGGPAR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_VALVEN]  DEFAULT ((0)) FOR [MOV_VALVEN]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_VALACQ]  DEFAULT ((0)) FOR [MOV_VALACQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTARES]  DEFAULT ((0)) FOR [MOV_QTARES]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CORR]  DEFAULT ('') FOR [MOV_CORR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_IMPOST]  DEFAULT ((0)) FOR [MOV_IMPOST]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_RECNO]  DEFAULT ((0)) FOR [MOV_RECNO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_UM]  DEFAULT ('') FOR [MOV_UM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTCONF]  DEFAULT ((0)) FOR [MOV_QTCONF]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTXCON]  DEFAULT ((0)) FOR [MOV_QTXCON]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_COORD]  DEFAULT ('') FOR [MOV_COORD]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_RAGSOC]  DEFAULT ('') FOR [MOV_RAGSOC]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_VALUTA]  DEFAULT ('') FOR [MOV_VALUTA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SERIE]  DEFAULT ('') FOR [MOV_SERIE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DSERIE]  DEFAULT ('') FOR [MOV_DSERIE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_AAPROD]  DEFAULT ((0)) FOR [MOV_AAPROD]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SERCAR]  DEFAULT ('') FOR [MOV_SERCAR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMDA]  DEFAULT ((0)) FOR [MOV_NUMDA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMAL]  DEFAULT ((0)) FOR [MOV_NUMAL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESART]  DEFAULT ('') FOR [MOV_DESART]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NOTVAR]  DEFAULT ('') FOR [MOV_NOTVAR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODTAG]  DEFAULT ('') FOR [MOV_CODTAG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESTAG]  DEFAULT ('') FOR [MOV_DESTAG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODCOL]  DEFAULT ('') FOR [MOV_CODCOL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESCOL]  DEFAULT ('') FOR [MOV_DESCOL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TRASME]  DEFAULT ((0)) FOR [MOV_TRASME]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NOTE]  DEFAULT ('') FOR [MOV_NOTE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODPDV]  DEFAULT ('') FOR [MOV_CODPDV]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ORAMOV]  DEFAULT ('') FOR [MOV_ORAMOV]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SEGNO]  DEFAULT ('') FOR [MOV_SEGNO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TIPMOV]  DEFAULT ('') FOR [MOV_TIPMOV]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FORNIT]  DEFAULT ('') FOR [MOV_FORNIT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESFOR]  DEFAULT ('') FOR [MOV_DESFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FLGTRA]  DEFAULT ((0)) FOR [MOV_FLGTRA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PRZCON]  DEFAULT ((0)) FOR [MOV_PRZCON]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_LEGSYS]  DEFAULT ('') FOR [MOV_LEGSYS]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODCAS]  DEFAULT ('') FOR [MOV_CODCAS]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_LEGAME]  DEFAULT ('') FOR [MOV_LEGAME]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PAGAME]  DEFAULT ('') FOR [MOV_PAGAME]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMORF]  DEFAULT ('') FOR [MOV_NUMORF]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DATORF]  DEFAULT ('') FOR [MOV_DATORF]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC1]  DEFAULT ((0)) FOR [MOV_SC1]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC2]  DEFAULT ((0)) FOR [MOV_SC2]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC3]  DEFAULT ((0)) FOR [MOV_SC3]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODACQ]  DEFAULT ('') FOR [MOV_CODACQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DATSCA]  DEFAULT ('') FOR [MOV_DATSCA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TIPORI]  DEFAULT ((0)) FOR [MOV_TIPORI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMORI]  DEFAULT ('') FOR [MOV_NUMORI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DATORI]  DEFAULT ('') FOR [MOV_DATORI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMIDE]  DEFAULT ('') FOR [MOV_NUMIDE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODBUN]  DEFAULT ('') FOR [MOV_CODBUN]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ANNO]  DEFAULT ('') FOR [MOV_ANNO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_UNIQUE]  DEFAULT ('') FOR [MOV_UNIQUE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TIPTRA]  DEFAULT ('') FOR [MOV_TIPTRA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SYSGGG]  DEFAULT ('') FOR [MOV_SYSGGG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SYSGGS]  DEFAULT ('') FOR [MOV_SYSGGS]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SYSDAG]  DEFAULT ('') FOR [MOV_SYSDAG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SYSDAS]  DEFAULT ('') FOR [MOV_SYSDAS]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODOPE]  DEFAULT ('') FOR [MOV_CODOPE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NOMOPE]  DEFAULT ('') FOR [MOV_NOMOPE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PRZCAM]  DEFAULT ((0)) FOR [MOV_PRZCAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMCAM]  DEFAULT ('') FOR [MOV_NUMCAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DATCAM]  DEFAULT ('') FOR [MOV_DATCAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_INICAM]  DEFAULT ('') FOR [MOV_INICAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FINCAM]  DEFAULT ('') FOR [MOV_FINCAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC1CAM]  DEFAULT ((0)) FOR [MOV_SC1CAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC2CAM]  DEFAULT ((0)) FOR [MOV_SC2CAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC3CAM]  DEFAULT ((0)) FOR [MOV_SC3CAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC4CAM]  DEFAULT ((0)) FOR [MOV_SC4CAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SC5CAM]  DEFAULT ((0)) FOR [MOV_SC5CAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FISCAM]  DEFAULT ((0)) FOR [MOV_FISCAM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODMAT]  DEFAULT ('') FOR [MOV_CODMAT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESMAT]  DEFAULT ('') FOR [MOV_DESMAT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SPESSO]  DEFAULT ((0)) FOR [MOV_SPESSO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ALTEZZ]  DEFAULT ((0)) FOR [MOV_ALTEZZ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_LUNGHE]  DEFAULT ((0)) FOR [MOV_LUNGHE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NRLINT]  DEFAULT ((0)) FOR [MOV_NRLINT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NRDBOB]  DEFAULT ((0)) FOR [MOV_NRDBOB]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAKG]  DEFAULT ((0)) FOR [MOV_QTAKG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAMQ]  DEFAULT ((0)) FOR [MOV_QTAMQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAML]  DEFAULT ((0)) FOR [MOV_QTAML]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CDAFOR]  DEFAULT ('') FOR [MOV_CDAFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_OINFOR]  DEFAULT ('') FOR [MOV_OINFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PINFOR]  DEFAULT ('') FOR [MOV_PINFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DTPFOR]  DEFAULT ('') FOR [MOV_DTPFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TRAFOR]  DEFAULT ('') FOR [MOV_TRAFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NBAFOR]  DEFAULT ((0)) FOR [MOV_NBAFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_BDAFOR]  DEFAULT ((0)) FOR [MOV_BDAFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_BALFOR]  DEFAULT ((0)) FOR [MOV_BALFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PNKFOR]  DEFAULT ((0)) FOR [MOV_PNKFOR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ANAART]  DEFAULT ('') FOR [MOV_ANAART]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DTINCQ]  DEFAULT ('') FOR [MOV_DTINCQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ORINCQ]  DEFAULT ('') FOR [MOV_ORINCQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DTFICQ]  DEFAULT ('') FOR [MOV_DTFICQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_ORFICQ]  DEFAULT ('') FOR [MOV_ORFICQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CDRECQ]  DEFAULT ('') FOR [MOV_CDRECQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DSRECQ]  DEFAULT ('') FOR [MOV_DSRECQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAKGA]  DEFAULT ((0)) FOR [MOV_QTAKGA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAMQA]  DEFAULT ((0)) FOR [MOV_QTAMQA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAMLA]  DEFAULT ((0)) FOR [MOV_QTAMLA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_TIPART]  DEFAULT ('') FOR [MOV_TIPART]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FLGCEL]  DEFAULT ((0)) FOR [MOV_FLGCEL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTACON]  DEFAULT ((0)) FOR [MOV_QTACON]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SERBOL]  DEFAULT ('') FOR [MOV_SERBOL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SERNUM]  DEFAULT ('') FOR [MOV_SERNUM]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMEDA]  DEFAULT ((0)) FOR [MOV_NUMEDA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMEAL]  DEFAULT ((0)) FOR [MOV_NUMEAL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CBFISC]  DEFAULT ('') FOR [MOV_CBFISC]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CODCLI]  DEFAULT ('') FOR [MOV_CODCLI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DESCLI]  DEFAULT ('') FOR [MOV_DESCLI]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MST_DATAST]  DEFAULT ('') FOR [MST_DATAST]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MST_ORASTO]  DEFAULT ('') FOR [MST_ORASTO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MST_CODOPE]  DEFAULT ('') FOR [MST_CODOPE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MST_DESOPE]  DEFAULT ('') FOR [MST_DESOPE]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FILA_X]  DEFAULT ('') FOR [MOV_FILA_X]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PIAN_X]  DEFAULT ('') FOR [MOV_PIAN_X]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_UBIC_X]  DEFAULT ('') FOR [MOV_UBIC_X]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_FILA_N]  DEFAULT ((0)) FOR [MOV_FILA_N]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PIAN_N]  DEFAULT ((0)) FOR [MOV_PIAN_N]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_UBIC_N]  DEFAULT ((0)) FOR [MOV_UBIC_N]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CSTMAN]  DEFAULT ((0)) FOR [MOV_CSTMAN]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CSTSCA]  DEFAULT ((0)) FOR [MOV_CSTSCA]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_NUMMOV]  DEFAULT ('') FOR [MOV_NUMMOV]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_DOCMOD]  DEFAULT ((0)) FOR [MOV_DOCMOD]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTAMC]  DEFAULT ((0)) FOR [MOV_QTAMC]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_MAGUNQ]  DEFAULT ('') FOR [MOV_MAGUNQ]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QUAPRO]  DEFAULT ('') FOR [MOV_QUAPRO]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_CLIENT]  DEFAULT ('') FOR [MOV_CLIENT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_QTANR]  DEFAULT ((0)) FOR [MOV_QTANR]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_GIANEG]  DEFAULT ((0)) FOR [MOV_GIANEG]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_SERIAL]  DEFAULT ('') FOR [MOV_SERIAL]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  CONSTRAINT [DF_S_MAG_MO_MOV_PRSPOT]  DEFAULT ((0)) FOR [MOV_PRSPOT]
GO

ALTER TABLE [dbo].[S_MAG_MO] ADD  DEFAULT ('') FOR [MOV_TRCKNG]
GO


