    
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PARAMETRI_SCHEDULER]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[PARAMETRI_SCHEDULER]
GO
 
CREATE TABLE [dbo].[PARAMETRI_SCHEDULER] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ID_PARAMETRI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
    [SYS_PARAMETRI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PERIDAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
    [PERIAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CODICE_CLI_DAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_CLI_AL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_FOR_DAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_FOR_AL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_CONTO_DAL] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_CONTO_AL] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_AGENTE_DAL] [varchar] (03) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_AGENTE_AL] [varchar] (03) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_ARTICOLO_DAL] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
	[CODICE_ARTICOLO_AL] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
	[TESTO_NOTE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] 
GO


ALTER TABLE [dbo].[PARAMETRI_SCHEDULER] WITH NOCHECK ADD 
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_ID_PARAMETRI] DEFAULT ('') FOR [ID_PARAMETRI],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SYS_PARAMETRI] DEFAULT ('') FOR [SYS_PARAMETRI],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_PERIDAL] DEFAULT ('') FOR [PERIDAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_PERIAL] DEFAULT ('') FOR [PERIAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_CLI_DAL] DEFAULT ('') FOR [CODICE_CLI_DAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_CLI_AL] DEFAULT ('') FOR [CODICE_CLI_AL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_FOR_DAL] DEFAULT ('') FOR [CODICE_FOR_DAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_FOR_AL] DEFAULT ('') FOR [CODICE_FOR_AL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_CONTO_DAL] DEFAULT ('') FOR [CODICE_CONTO_DAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_CONTO_AL] DEFAULT ('') FOR [CODICE_CONTO_AL],
    CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_AGENTE_DAL] DEFAULT ('') FOR [CODICE_AGENTE_DAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_AGENTE_AL] DEFAULT ('') FOR [CODICE_AGENTE_AL],
    CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_ARTICOLO_DAL] DEFAULT ('') FOR [CODICE_ARTICOLO_DAL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_CODICE_ARTICOLO_AL] DEFAULT ('') FOR [CODICE_ARTICOLO_AL],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_TESTO_NOTE] DEFAULT ('') FOR [TESTO_NOTE],
	CONSTRAINT [DF_PARAMETRI_SCHEDULER_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

