SELECT * FROM (
SELECT MOV_CODART, COUNT(*) AS DIVERSI_CODMAT FROM (
SELECT 
 MOV_CODMAT,
 MOV_CODART
FROM U_MAG_MO
GROUP BY MOV_CODART,MOV_CODMAT) AS T1
GROUP BY MOV_CODART) AS T2
WHERE DIVERSI_CODMAT>1
ORDER BY MOV_CODART

select mov_codart,mov_dtregi,mov_oramov,mov_codmag,mov_top,mov_codmat,mov_segno,mov_qtamov,* from u_mag_mo
 where mov_codart = 'C40/3A .55006757' order by mov_dtregi,mov_oramov

SELECT MAG_CODART,MAG_DATAGG,MAG_PRZCON,MAG_CODMAG, COUNT(*) AS DIVERSI_CODMAT FROM U_MAG_GG
WHERE MAG_DATAGG <> SPACE(10)
GROUP BY MAG_CODART,MAG_DATAGG,MAG_PRZCON,MAG_CODMAG
ORDER BY MAG_CODART

SELECT * FROM (
SELECT MAG_CODART,MAG_DATAGG,MAG_CODMAG,MAG_PRZCON, COUNT(*) AS DIVERSI_CODMAT FROM (
SELECT MAG_CODART,MAG_DATAGG,MAG_CODMAG,MAG_PRZCON
FROM U_MAG_GG
GROUP BY MAG_CODART,MAG_DATAGG,MAG_CODMAG,MAG_PRZCON) AS T1
GROUP BY MAG_CODART,MAG_DATAGG,MAG_CODMAG,MAG_PRZCON) AS T2
WHERE DIVERSI_CODMAT=1 AND MAG_CODMAG = '008'
ORDER BY MAG_CODART,MAG_CODMAG

SELECT * FROM (
SELECT MOV_CODART,MOV_DATSCA,MOV_CODMAG, COUNT(*) AS DIVERSI_CODMAT FROM (
SELECT MOV_CODART,MOV_DATSCA,MOV_CODMAG,MOV_PREACQ
FROM U_MAG_MO
GROUP BY MOV_CODART,MOV_DATSCA,MOV_CODMAG,MOV_PREACQ) AS T1
GROUP BY MOV_CODART,MOV_DATSCA,MOV_CODMAG) AS T2
WHERE DIVERSI_CODMAT>1 AND MOV_CODMAG = '008'
ORDER BY MOV_CODART,MOV_CODMAG

SELECT * FROM U_MAG_GG WHERE MAG_CODMAG = '007'
SELECT * FROM U_MAG_MO WHERE MOV_CODMAG = '007'

SELECT MAG_ANAART,MAG_NRLINT,MAG_CODART,MAG_GIACEN,MAG_DATAGG,MAG_PRZCON,* FROM U_MAG_GG WHERE MAG_CODART = 'C100/6C.55006412' AND MAG_DATAGG <> SPACE(10) AND MAG_CODMAG = '008'
SELECT MOV_ANAART,MOV_NRLINT,MOV_CODART,MOV_QTAMOV,MOV_TOP,MOV_DATSCA,MOV_PREACQ,MOV_DTREGI,MOV_ORAMOV,* FROM U_MAG_MO WHERE MOV_CODART = 'C100/6C.55006412' AND MOV_CODMAG = '008' ORDER BY MOV_DTREGI,MOV_ORAMOV

select mag_codart,mag_codmag,mag_datagg,mag_giacen,mag_przcon,* from u_mag_gg where mag_przcon = 0 AND MAG_GIACEN > 0 order by mag_codmag,mag_codart
