select PAR_ANNO,PAR_NREG,PAR_DTREG,PAR_DTFAT,PAR_DTSCAD,PAR_DATPAG,PAR_TMOV,PAR_TIPFAT,PAR_TOTIM,* from part_cli where par_ragsoc like 'KONTI STEEL HELLAS%' AND PAR_ANNO = '2004' AND PAR_NREG = 1115 ORDER BY PAR_NREG,PAR_NPROG
UPDATE PART_CLI SET PAR_DTSCAD = '2004/12/06' WHERE ID_UNIQUE = 'E52FCB6B-9BB1-4A34-8C4D-AF0907F6481A'
/*UPDATE PART_CLI SET PAR_DTSCAD = '2004/12/10' WHERE ID_UNIQUE = 'E52FCB6B-9BB1-4A34-8C4D-AF0907F6481A' */

select PAR_ANNO,PAR_NREG,PAR_DTREG,PAR_DTFAT,PAR_DTSCAD,PAR_DATPAG,PAR_TMOV,PAR_TIPFAT,PAR_TOTIM,* from part_cli where par_ragsoc = 'PANELTECH SP.ZO.O.' AND PAR_NREG = 975 ORDER BY PAR_NREG,PAR_NPROG
DELETE FROM PART_CLI WHERE par_ragsoc = 'PANELTECH SP.ZO.O.' AND PAR_NREG = 975

