
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[SQLFIND_DETT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[SQLFIND_DETT]
GO
 
CREATE TABLE [dbo].[SQLFIND_DETT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[CHIAVE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[SEQUEN] numeric (10,0) NULL ,
	[FRASE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[FRASESQL] [text] COLLATE Latin1_General_CI_AS NULL ,
	[TAG] [varchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


ALTER TABLE [dbo].[SQLFIND_DETT] WITH NOCHECK ADD 
	CONSTRAINT [DF_SQLFIND_DETT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_SQLFIND_DETT_CHIAVE] DEFAULT ('') FOR [CHIAVE],
	CONSTRAINT [DF_SQLFIND_DETT_TIPO] DEFAULT ('') FOR [TIPO],
	CONSTRAINT [DF_SQLFIND_DETT_SEQUEN] DEFAULT (0) FOR [SEQUEN],
	CONSTRAINT [DF_SQLFIND_DETT_FRASE] DEFAULT ('') FOR [FRASE],
	CONSTRAINT [DF_SQLFIND_DETT_FRASESQL] DEFAULT ('') FOR [FRASESQL],
	CONSTRAINT [DF_SQLFIND_DETT_TAG] DEFAULT ('') FOR [TAG]
GO

