
UPDATE PARA SET DESIVA = '' WHERE CODICE LIKE 'COL%'

UPDATE PARA SET DESIVA = 'LEGNO' WHERE CODICE LIKE 'COL%' AND (DESCRI NOT LIKE '%BARRIERA%' OR DESCRI = '')

UPDATE PARA SET DESIVA = 'BIANCO' WHERE CODICE LIKE 'COL%' AND DESCRI LIKE '%BIANCO%'

UPDATE PARA SET DESIVA = 'UNICO' WHERE CODICE LIKE 'COL%' AND 
	((DESCRI LIKE '%GRIGIO%' AND DESCRI NOT LIKE '%ROVERE GRIGIO%') OR 
	 DESCRI LIKE '%VERD%' OR 
	 DESCRI LIKE '%VANIGLIA%' OR 
	 DESCRI LIKE '%BLU%' OR 
	 DESCRI LIKE '%FANTASIA%' OR 
	 DESCRI LIKE '%MARRONE%' OR 
	 DESCRI LIKE '%GIALL%' OR 
	 DESCRI LIKE '%NUVOLATO%' OR 
	 DESCRI LIKE '%SABBIA%' OR 
	 DESCRI LIKE '%PANNA%' OR 
	 DESCRI LIKE '%AVORIO%' OR 
	 DESCRI LIKE '%ALLUMINIO%' OR 
	 DESCRI LIKE '%GR.%' OR 
	 DESCRI LIKE '%ARANCIO%' OR 
	 DESCRI LIKE '%ROSSO%' OR 
	 DESCRI LIKE '%AZZURR%' OR 
	 DESCRI LIKE '%BLEU%' OR 
	 DESCRI LIKE '%NERO%' OR 
	 DESCRI LIKE '%ALUMINIUM%' OR 
	 DESCRI LIKE '%CORDA%')

SELECT CODICE,DESCRI,DESIVA FROM PARA WHERE CODICE LIKE 'COL%' ORDER BY CODICE

