if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TRATTOFF_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TRATTOFF_DD]
GO

CREATE TABLE [dbo].[TRATTOFF_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[ID_OFFERTA] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_CODICE] [varchar] (33) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_DATA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_DOC] [varchar] (255) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_CORRISP] [numeric](17, 2) NULL ,
	[OFF_COMMEN] [text] COLLATE Latin1_General_CI_AS NULL ,
	[OFF_IDMITTENTE] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_IDENTEAZI] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_IDFUNAZIEN] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_IDRISUMANA] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_OGGETTO] [text] COLLATE Latin1_General_CI_AS NULL ,
	[OFF_D_VALIDITA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_D_ATTINIZIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_D_ATTFINE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_IDCONTROP] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[OFF_CORRISP_PARZ] [numeric](17, 2) NULL ,
	[UM_OFF_CORRISP_PARZ] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[UM_OFF_CORRISP] [varchar] (2) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TRATTOFF_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_TRATTOFF_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRATTOFF_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_TRATTOFF_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_TRATTOFF_DD_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_TRATTOFF_DD_ID_OFFERTA] DEFAULT ('') FOR [ID_OFFERTA],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_CODICE] DEFAULT ('') FOR [OFF_CODICE],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_DATA] DEFAULT ('') FOR [OFF_DATA],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_DOC] DEFAULT ('') FOR [OFF_DOC],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_CORRISP] DEFAULT (0) FOR [OFF_CORRISP],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_COMMEN] DEFAULT ('') FOR [OFF_COMMEN],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_IDMITTENTE] DEFAULT ('') FOR [OFF_IDMITTENTE],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_IDENTEAZI] DEFAULT ('') FOR [OFF_IDENTEAZI],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_IDFUNAZIEN] DEFAULT ('') FOR [OFF_IDFUNAZIEN],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_IDRISUMANA] DEFAULT ('') FOR [OFF_IDRISUMANA],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_OGGETTO] DEFAULT ('') FOR [OFF_OGGETTO],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_D_VALIDITA] DEFAULT ('') FOR [OFF_D_VALIDITA],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_D_ATTINIZIO] DEFAULT ('') FOR [OFF_D_ATTINIZIO],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_D_ATTFINE] DEFAULT ('') FOR [OFF_D_ATTFINE],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_IDCONTROP] DEFAULT ('') FOR [OFF_IDCONTROP],
	CONSTRAINT [DF_TRATTOFF_DD_OFF_CORRISP_PARZ] DEFAULT ('0') FOR [OFF_CORRISP_PARZ],
	CONSTRAINT [DF_TRATTOFF_DD_UM_OFF_CORRISP_PARZ] DEFAULT ('') FOR [UM_OFF_CORRISP_PARZ],
	CONSTRAINT [DF_TRATTOFF_DD_UM_OFF_CORRISP] DEFAULT ('') FOR [UM_OFF_CORRISP]
GO

