if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TRATTSOG_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TRATTSOG_DD]
GO

CREATE TABLE [dbo].[TRATTSOG_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[ID_DETTAGLIO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_TIPSOG] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_CODICE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_COGNOM] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_NOME] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_FIGPROF] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_DESGEN] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SOG_ANNESP] [numeric](3, 0) NULL ,
	[SOG_POSTI] [numeric](3, 0) NULL ,
	[D_INIZIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[D_FINE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_GGPREV] [numeric](10, 0) NULL ,
	[SOG_COSTO] [numeric](17, 2) NULL ,
	[SOG_RICAVO] [numeric](17, 2) NULL ,
	[SOG_UTILE] [numeric](17, 2) NULL ,
	[CODATTIVITA] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[DESATTIVITA] [varchar] (254) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_STATO] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_SEDELA] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[SOG_QTASOG] [numeric](3, 0) NULL ,
	[SOG_ANNOTA] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SOG_ANNRIS] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SOG_DESCRI] [varchar] (100) COLLATE Latin1_General_CI_AS NULL ,
	[STATO] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[IDTipoOra_c] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDDettOra_c] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDTipoOra_r] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[IDDettOra_r] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[UM_SOG_GGPREV] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[OREGG] [numeric](10, 2) NULL ,
	[UMCOSTO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[UMRICAVO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[VALCOSTO] [numeric](17, 2) NULL ,
	[VALRICAVO] [numeric](17, 2) NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TRATTSOG_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_TRATTSOG_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRATTSOG_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_TRATTSOG_DD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_TRATTSOG_DD_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_TRATTSOG_DD_ID_DETTAGLIO] DEFAULT ('') FOR [ID_DETTAGLIO],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_TIPSOG] DEFAULT ('') FOR [SOG_TIPSOG],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_CODICE] DEFAULT ('') FOR [SOG_CODICE],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_COGNOM] DEFAULT ('') FOR [SOG_COGNOM],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_NOME] DEFAULT ('') FOR [SOG_NOME],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_FIGPROF] DEFAULT ('') FOR [SOG_FIGPROF],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_DESGEN] DEFAULT ('') FOR [SOG_DESGEN],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_ANNESP] DEFAULT (0) FOR [SOG_ANNESP],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_POSTI] DEFAULT (0) FOR [SOG_POSTI],
	CONSTRAINT [DF_TRATTSOG_DD_D_INIZIO] DEFAULT ('') FOR [D_INIZIO],
	CONSTRAINT [DF_TRATTSOG_DD_D_FINE] DEFAULT ('') FOR [D_FINE],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_GGPREV] DEFAULT (0) FOR [SOG_GGPREV],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_COSTO] DEFAULT (0) FOR [SOG_COSTO],
	CONSTRAINT [DF_TRATTSOG_DD_RSOG_RICAVO] DEFAULT (0) FOR [SOG_RICAVO],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_UTILE] DEFAULT (0) FOR [SOG_UTILE],
	CONSTRAINT [DF_TRATTSOG_DD_CODATTIVITA] DEFAULT ('') FOR [CODATTIVITA],
	CONSTRAINT [DF_TRATTSOG_DD_DESATTIVITA] DEFAULT ('') FOR [DESATTIVITA],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_STATO] DEFAULT ('') FOR [SOG_STATO],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_SEDELA] DEFAULT ('') FOR [SOG_SEDELA],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_QTASOG] DEFAULT (0) FOR [SOG_QTASOG],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_ANNOTA] DEFAULT ('') FOR [SOG_ANNOTA],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_ANNRIS] DEFAULT ('') FOR [SOG_ANNRIS],
	CONSTRAINT [DF_TRATTSOG_DD_SOG_DESCRI] DEFAULT ('') FOR [SOG_DESCRI],
	CONSTRAINT [DF_TRATTSOG_DD_STATO] DEFAULT ('') FOR [STATO],
	CONSTRAINT [DF_TRATTSOG_DD_IDTipoOra_c] DEFAULT ('') FOR [IDTipoOra_c],
	CONSTRAINT [DF_TRATTSOG_DD_IDDettOra_c] DEFAULT ('') FOR [IDDettOra_c],
	CONSTRAINT [DF_TRATTSOG_DD_IDTipoOra_r] DEFAULT ('') FOR [IDTipoOra_r],
	CONSTRAINT [DF_TRATTSOG_DD_IDDettOra_r] DEFAULT ('') FOR [IDDettOra_r],
	CONSTRAINT [DF_TRATTSOG_DD_UM_SOG_GGPREV] DEFAULT (0) FOR [UM_SOG_GGPREV],
	CONSTRAINT [DF_TRATTSOG_DD_OREGG] DEFAULT (0) FOR [OREGG],
	CONSTRAINT [DF_TRATTSOG_DD_UMCOSTO] DEFAULT ('0') FOR [UMCOSTO],
	CONSTRAINT [DF_TRATTSOG_DD_UMRICAVO] DEFAULT ('0') FOR [UMRICAVO],
	CONSTRAINT [DF_TRATTSOG_DD_VALCOSTO] DEFAULT ('0') FOR [VALCOSTO],
	CONSTRAINT [DF_TRATTSOG_DD_VALRICAVO] DEFAULT ('0') FOR [VALRICAVO]
GO

