if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TURNI_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[TURNI_TT]
GO

CREATE TABLE [dbo].[TURNI_TT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_TURNI] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_CODICE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_DESCRI] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_DATINI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_ORAINI] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_DATFIN] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_ORAFIN] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[TUR_NOTE] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TURNI_TT] WITH NOCHECK ADD 
	CONSTRAINT [PK_TURNI_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TURNI_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_TURNI_TT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_TURNI_TT_PJ_TURNI] DEFAULT ('') FOR [PJ_TURNI],
	CONSTRAINT [DF_TURNI_TT_TUR_CODICE] DEFAULT ('') FOR [TUR_CODICE],
	CONSTRAINT [DF_TURNI_TT_TUR_DESCRI] DEFAULT ('') FOR [TUR_DESCRI],
	CONSTRAINT [DF_TURNI_TT_TUR_DATINI] DEFAULT ('') FOR [TUR_DATINI],
	CONSTRAINT [DF_TURNI_TT_TUR_ORAINI] DEFAULT ('') FOR [TUR_ORAINI],
	CONSTRAINT [DF_TURNI_TT_TUR_DATFIN] DEFAULT ('') FOR [TUR_DATFIN],
	CONSTRAINT [DF_TURNI_TT_TUR_ORAFIN] DEFAULT ('') FOR [TUR_ORAFIN],
	CONSTRAINT [DF_TURNI_TT_TUR_NOTE] DEFAULT ('') FOR [TUR_NOTE]
GO

