if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_AGN_AN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_AGN_AN]
GO
 
CREATE TABLE [dbo].[U_AGN_AN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_U_AGN_AN_id_unique] DEFAULT (newid()),
	[AGN_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_CODSOC] DEFAULT (''),
	[AGN_UTENTE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_UTENTE] DEFAULT (''),
        [AGN_CODAGN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_CODAGN] DEFAULT (''),
	[AGN_NOME] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_NOME] DEFAULT (''),
	[AGN_COGNOME] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_COGNOME] DEFAULT (''),
	[AGN_CODPDV] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_CODPDV] DEFAULT (''),
	[AGN_TELEF] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_TELEF] DEFAULT (''),
	[AGN_CELL] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_CELL] DEFAULT (''),
	[AGN_CELLAZ] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_CELLAZ] DEFAULT (''),
	[AGN_EMAIL] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_EMAIL] DEFAULT (''),
	[AGN_TIPOL] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_TIPOL] DEFAULT (''),
	[AGN_SOCIET] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_SOCIET] DEFAULT (''),
	[AGN_TELEF2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_TELEF2] DEFAULT (''),
	[AGN_TELEF3] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_TELEF3] DEFAULT (''),
	[AGN_FAX1] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_FAX1] DEFAULT (''),
	[AGN_FAX2] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_FAX2] DEFAULT (''),
	[AGN_INDIR] [varchar] (55) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_INDIR] DEFAULT (''),
	[AGN_NOTE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_NOTE] DEFAULT (''),
	[AGN_SITO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_AGN_AN_AGN_SITO] DEFAULT ('')
	CONSTRAINT [PK_U_AGN_AN] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO

