if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_AMM_PE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_AMM_PE]
GO
 
CREATE TABLE [dbo].[U_AMM_PE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ORD_DTREGI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_DATADA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_DATAAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_CATEG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_PEORI]  [numeric] (10,3) NULL ,
	[ORD_PEORD]  [numeric] (10,3) NULL ,
	[ORD_PEANT]  [numeric] (10,3) NULL ,
	[ORD_PEACC]  [numeric] (10,3) NULL ,
	[ORD_QUOTA]  [numeric] (17,3) NULL ,
	[ORD_SYSSIM] [varchar] (10) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_AMM_PE] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_AMM_PE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_AMM_PE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_AMM_PE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_AMM_PE_ORD_DTREGI] DEFAULT ('') FOR [ORD_DTREGI],
	CONSTRAINT [DF_U_AMM_PE_ORD_DATADA] DEFAULT ('') FOR [ORD_DATADA],
	CONSTRAINT [DF_U_AMM_PE_ORD_DATAAL] DEFAULT ('') FOR [ORD_DATAAL],
	CONSTRAINT [DF_U_AMM_PE_ORD_CATEG] DEFAULT ('') FOR [ORD_CATEG],
	CONSTRAINT [DF_U_AMM_PE_ORD_PEORI] DEFAULT (0) FOR [ORD_PEORI],
	CONSTRAINT [DF_U_AMM_PE_ORD_PEORD] DEFAULT (0) FOR [ORD_PEORD],
	CONSTRAINT [DF_U_AMM_PE_ORD_PEANT] DEFAULT (0) FOR [ORD_PEANT],
	CONSTRAINT [DF_U_AMM_PE_ORD_PEACC] DEFAULT (0) FOR [ORD_PEACC],
	CONSTRAINT [DF_U_AMM_PE_ORD_QUOTA] DEFAULT (0) FOR [ORD_QUOTA],
	CONSTRAINT [DF_U_AMM_PE_ORD_SYSSIM] DEFAULT ('') FOR [ORD_SYSSIM]
GO

