if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_ANF_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_ANF_DD]
GO

CREATE TABLE [U_ANF_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_U_ANF_DD_id_unique] DEFAULT (newid()),
	[DAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_DAGGANCIO] DEFAULT (''),
	[RIC_CONTO] [varchar] (13) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_RIC_CONTO] DEFAULT (''),
	[RIC_NUMPAR] [numeric](10, 0) NULL CONSTRAINT [DF_U_ANF_DD_RIC_NUMPAR] DEFAULT (0),
	[RIC_NUMFAT] [varchar] (6) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_RIC_NUMFAT] DEFAULT (''),
	[RIC_FATAGE] [varchar] (6) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_RIC_FATAGE] DEFAULT (''),
	[RIC_DATFAT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_RIC_DATFAT] DEFAULT (''),
	[RIC_DATSCA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_DD_RIC_DATSCA] DEFAULT (''),
	[RIC_TOTALE] [numeric](17, 3) NULL CONSTRAINT [DF_U_ANF_DD_RIC_TOTALE] DEFAULT (0),
	[ORD_SINTE] [bit] NULL CONSTRAINT [DF_U_ANF_DD_ORD_SINTE] DEFAULT (0),
	CONSTRAINT [PK_U_ANF_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO


