if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_ANF_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_ANF_TT]
GO

CREATE TABLE [U_ANF_TT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_U_ANF_TT_id_unique] DEFAULT (newid()),
	[RIC_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_CODSOC] DEFAULT (''),
	[RIC_CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_CODCLI] DEFAULT (''),
	[RIC_RAGSOC] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_RAGSOC] DEFAULT (''),
	[RIC_INDIRI] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_INDIRI] DEFAULT (''),
	[RIC_CAP] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_CAP] DEFAULT (''),
	[RIC_LOCALI] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_LOCALI] DEFAULT (''),
	[RIC_NFATT] [varchar] (6) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_NFATT] DEFAULT (''),
	[RIC_DTFATT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_DTFATT] DEFAULT (''),
	[RIC_DTSCAD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_DTSCAD] DEFAULT (''),
	[RIC_TOTFAT] [numeric](19, 3) NULL CONSTRAINT [DF_U_ANF_TT_RIC_TOTFAT] DEFAULT (0),
	[RIC_TRANC] [numeric](19, 3) NULL CONSTRAINT [DF_U_ANF_TT_RIC_TRANC] DEFAULT (0),
	[RIC_BACLI] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_BACLI] DEFAULT (''),
	[RIC_DEBACL] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_DEBACL] DEFAULT (''),
	[RIC_BAPRES] [varchar] (5) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_BAPRES] DEFAULT (''),
	[RIC_DEBAPR] [varchar] (40) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_DEBAPR] DEFAULT (''),
	[RIC_STAMP] [bit] NULL CONSTRAINT [DF_U_ANF_TT_RIC_STAMP] DEFAULT (0),
	[RIC_TRASF] [bit] NULL CONSTRAINT [DF_U_ANF_TT_RIC_TRASF] DEFAULT (0),
	[RIC_TOP] [varchar] (3) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_TOP] DEFAULT (''),
	[RIC_NOTE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_NOTE] DEFAULT (''),
	[RIC_PROGR] [varchar] (6) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_PROGR] DEFAULT (''),
	[TAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_TAGGANCIO] DEFAULT (''),
	[RIC_CGE] [bit] NULL CONSTRAINT [DF_U_ANF_TT_RIC_CGE] DEFAULT (0),
	[RIC_NUMDIS] [varchar] (6) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_NUMDIS] DEFAULT (''),
	[RIC_VALUTA] [varchar] (3) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_VALUTA] DEFAULT (''),
	[RIC_CAMBIO] [numeric](17, 10) NULL CONSTRAINT [DF_U_ANF_TT_RIC_CAMBIO] DEFAULT (0),
	[RIC_PARIVA] [varchar] (11) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_PARIVA] DEFAULT (''),
	[ORD_ANNO] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[RIC_CONPAG] [varchar] (3) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_CONPAG] DEFAULT (''),
	[RIC_DATDIS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_U_ANF_TT_RIC_DATDIS] DEFAULT (''),
	CONSTRAINT [PK_U_ANF_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO


