if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_ART_AN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_ART_AN]
GO
 
CREATE TABLE [dbo].[U_ART_AN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[ART_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[ART_CODPRI] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[ART_TIPOG] [VARCHAR] (1) COLLATE Latin1_General_CI_AS NULL,
    [ART_TIPON] [VARCHAR] (1) COLLATE Latin1_General_CI_AS NULL,
	[ART_CODCOLRET] [VARCHAR] (3) COLLATE Latin1_General_CI_AS NULL,
	[ART_FINI] [VARCHAR] (1) COLLATE Latin1_General_CI_AS NULL,
	[ART_SCELTA] [VARCHAR] (40) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[U_ART_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ART_AN_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_ART_AN_ART_CODSOC] DEFAULT ('') FOR [ART_CODSOC],
	CONSTRAINT [DF_U_ART_AN_ART_CODPRI] DEFAULT ('') FOR [ART_CODPRI],
	CONSTRAINT [DF_U_ART_AN_ART_TIPOG] DEFAULT ('') FOR [ART_TIPOG],
	CONSTRAINT [DF_U_ART_AN_ART_TIPON] DEFAULT ('') FOR [ART_TIPON],
	CONSTRAINT [DF_U_ART_AN_ART_CODCOLRET] DEFAULT ('') FOR [ART_CODCOLRET],
	CONSTRAINT [DF_U_ART_AN_ART_FINI] DEFAULT ('') FOR [ART_FINI],
	CONSTRAINT [DF_U_ART_AN_ART_SCELTA] DEFAULT ('') FOR [ART_SCELTA]	
GO

