
/****** Oggetto:  Index [INDEX_01]    Data script: 18/12/2012 ******/
CREATE NONCLUSTERED INDEX [INDEX_01] ON [dbo].[U_BOL_DD] 
(
	[ORD_LEGSYS] ASC,
	[ORD_DESART] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
