if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_CAM_AN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_CAM_AN]
GO
 
CREATE TABLE [dbo].[U_CAM_AN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[CAM_SOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_CATEG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_DESCR] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_DESC1] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_DESC2] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_TIPOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_TIPOP] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_PEORD] [numeric] (8,2) NULL ,
	[CAM_PEANT] [numeric] (8,2) NULL ,
	[CAM_PEACC] [numeric] (8,2) NULL ,
	[CAM_PEUTI] [numeric] (8,2) NULL ,
	[CAM_SPEMA] [numeric] (8,2) NULL ,
	[CAM_CONTR] [varchar] (13) COLLATE Latin1_General_CI_AS NULL ,
	[CAM_AAMIN] [numeric] (6,0) NULL ,
	[CAM_AAMAX] [numeric] (6,0) NULL ,
	[CAM_PREVI] [numeric] (6,0) NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_CAM_AN] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_CAM_AN] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_CAM_AN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CAM_AN_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_CAM_AN_CAM_SOC] DEFAULT ('') FOR [CAM_SOC],
	CONSTRAINT [DF_U_CAM_AN_CAM_CATEG] DEFAULT ('') FOR [CAM_CATEG],
	CONSTRAINT [DF_U_CAM_AN_CAM_DESCR] DEFAULT ('') FOR [CAM_DESCR],
	CONSTRAINT [DF_U_CAM_AN_CAM_DESC1] DEFAULT ('') FOR [CAM_DESC1],
	CONSTRAINT [DF_U_CAM_AN_CAM_DESC2] DEFAULT ('') FOR [CAM_DESC2],
	CONSTRAINT [DF_U_CAM_AN_CAM_TIPOC] DEFAULT ('') FOR [CAM_TIPOC],
	CONSTRAINT [DF_U_CAM_AN_CAM_TIPOP] DEFAULT ('') FOR [CAM_TIPOP],
	CONSTRAINT [DF_U_CAM_AN_CAM_PEORD] DEFAULT (0) FOR [CAM_PEORD],
	CONSTRAINT [DF_U_CAM_AN_CAM_PEANT] DEFAULT (0) FOR [CAM_PEANT],
	CONSTRAINT [DF_U_CAM_AN_CAM_PEACC] DEFAULT (0) FOR [CAM_PEACC],
	CONSTRAINT [DF_U_CAM_AN_CAM_PEUTI] DEFAULT (0) FOR [CAM_PEUTI],
	CONSTRAINT [DF_U_CAM_AN_CAM_SPEMA] DEFAULT (0) FOR [CAM_SPEMA],
	CONSTRAINT [DF_U_CAM_AN_CAM_CONTR] DEFAULT ('') FOR [CAM_CONTR],
	CONSTRAINT [DF_U_CAM_AN_CAM_AAMIN] DEFAULT (0) FOR [CAM_AAMIN],
	CONSTRAINT [DF_U_CAM_AN_CAM_AAMAX] DEFAULT (0) FOR [CAM_AAMAX],
	CONSTRAINT [DF_U_CAM_AN_CAM_PREVI] DEFAULT (0) FOR [CAM_PREVI]

GO
