if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_CAS_TT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_CAS_TT]
GO
 
CREATE TABLE [dbo].[U_CAS_TT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[TAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODSOC] [varchar] (02) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_NUMSCA] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DATSCA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_RAGSOC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_INDIRI] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_LOCALI] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CAP] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODCCO] [varchar] (04) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DESCCO] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODMAG] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DESMAG] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_FILA_X] [varchar] (05) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_PIAN_X] [varchar] (05) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_UBIC_X] [varchar] (05) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_FILA_N] [numeric] (5,0) NULL ,
	[CAS_PIAN_N] [numeric] (5,0) NULL ,
	[CAS_UBIC_N] [numeric] (5,0) NULL ,
	[CAS_FLAG] [varchar] (01) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODDOC] [varchar] (04) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DESDOC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODOPE] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_CODLOC] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DESLOC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_NUMSCH] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_DATFIN] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_NOTE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CAS_ANNO] [varchar] (04) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_CAS_TT] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_CAS_TT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_CAS_TT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CAS_TT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_CAS_TT_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODSOC] DEFAULT ('') FOR [CAS_CODSOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_NUMSCA] DEFAULT ('') FOR [CAS_NUMSCA],
	CONSTRAINT [DF_U_CAS_TT_CAS_DATSCA] DEFAULT ('') FOR [CAS_DATSCA],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODCLI] DEFAULT ('') FOR [CAS_CODCLI],
	CONSTRAINT [DF_U_CAS_TT_CAS_RAGSOC] DEFAULT ('') FOR [CAS_RAGSOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_INDIRI] DEFAULT ('') FOR [CAS_INDIRI],
	CONSTRAINT [DF_U_CAS_TT_CAS_LOCALI] DEFAULT ('') FOR [CAS_LOCALI],
	CONSTRAINT [DF_U_CAS_TT_CAS_CAP] DEFAULT ('') FOR [CAS_CAP],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODCCO] DEFAULT ('') FOR [CAS_CODCCO],
	CONSTRAINT [DF_U_CAS_TT_CAS_DESCCO] DEFAULT ('') FOR [CAS_DESCCO],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODMAG] DEFAULT ('') FOR [CAS_CODMAG],
	CONSTRAINT [DF_U_CAS_TT_CAS_DESMAG] DEFAULT ('') FOR [CAS_DESMAG],
	CONSTRAINT [DF_U_CAS_TT_CAS_FILA_X] DEFAULT ('') FOR [CAS_FILA_X],
	CONSTRAINT [DF_U_CAS_TT_CAS_PIAN_X] DEFAULT ('') FOR [CAS_PIAN_X],
	CONSTRAINT [DF_U_CAS_TT_CAS_UBIC_X] DEFAULT ('') FOR [CAS_UBIC_X],
	CONSTRAINT [DF_U_CAS_TT_CAS_FILA_N] DEFAULT (0) FOR [CAS_FILA_N],
	CONSTRAINT [DF_U_CAS_TT_CAS_PIAN_N] DEFAULT (0) FOR [CAS_PIAN_N],
	CONSTRAINT [DF_U_CAS_TT_CAS_UBIC_N] DEFAULT (0) FOR [CAS_UBIC_N],
	CONSTRAINT [DF_U_CAS_TT_CAS_FLAG] DEFAULT ('') FOR [CAS_FLAG],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODDOC] DEFAULT ('') FOR [CAS_CODDOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_DESDOC] DEFAULT ('') FOR [CAS_DESDOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODOPE] DEFAULT ('') FOR [CAS_CODOPE],
	CONSTRAINT [DF_U_CAS_TT_CAS_CODLOC] DEFAULT ('') FOR [CAS_CODLOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_DESLOC] DEFAULT ('') FOR [CAS_DESLOC],
	CONSTRAINT [DF_U_CAS_TT_CAS_NUMSCH] DEFAULT ('') FOR [CAS_NUMSCH],
	CONSTRAINT [DF_U_CAS_TT_CAS_DATFIN] DEFAULT ('') FOR [CAS_DATFIN],
	CONSTRAINT [DF_U_CAS_TT_CAS_NOTE] DEFAULT ('') FOR [CAS_NOTE],
	CONSTRAINT [DF_U_CAS_TT_SELEZIONE] DEFAULT ('') FOR [SELEZIONE],
	CONSTRAINT [DF_U_CAS_TT_CAS_ANNO] DEFAULT ('') FOR [CAS_ANNO]
GO

