if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_CCO_DD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_CCO_DD]
GO
 
CREATE TABLE [dbo].[U_CCO_DD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO]    [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_PRORIG]   [numeric] (5,0) NULL ,
	[ORD_DATREG]   [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_CAUS]     [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_DESCAUS]  [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_VALORE]   [numeric] (19,3) NULL ,
	[ORD_CODPDV]   [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_COCASSAC] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_SALDOCAS] [numeric] (19,3) NULL ,
	[ORD_IDENTPOS] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_NTELEPOS] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_COCA1POS] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_SALD1POS] [numeric] (19,3) NULL ,
	[ORD_VIEW]     [bit] NULL ,
	[ORD_NOTE]     [text]         COLLATE Latin1_General_CI_AS NULL ,
	[ORS_CODCLI]   [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORS_RAGSOC]   [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[ORS_NUMDOC]   [varchar] (6)  COLLATE Latin1_General_CI_AS NULL ,
	[ORS_DATDOC]   [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE]    [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_SEQUEN]   [numeric] (7,0) NULL ,
	[ORD_CODSYS]   [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_UNIQUE]   [varchar] (10) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_CCO_DD] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_CCO_DD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_CCO_DD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CCO_DD_id_unique]     DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_CCO_DD_DAGGANCIO]     DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_U_CCO_DD_ORD_DATREG]    DEFAULT ('') FOR [ORD_DATREG],
	CONSTRAINT [DF_U_CCO_DD_ORD_CAUS]      DEFAULT ('') FOR [ORD_CAUS],
	CONSTRAINT [DF_U_CCO_DD_ORD_DESCAUS]   DEFAULT ('') FOR [ORD_DESCAUS],
	CONSTRAINT [DF_U_CCO_DD_ORD_VALORE]    DEFAULT (0)  FOR [ORD_VALORE],
	CONSTRAINT [DF_U_CCO_DD_ORD_PRORIG]    DEFAULT (0)  FOR [ORD_PRORIG],
	CONSTRAINT [DF_U_CCO_TT_ORD_CODPDV]    DEFAULT ('') FOR [ORD_CODPDV],
	CONSTRAINT [DF_U_CCO_TT_ORD_COCASSAC]  DEFAULT ('') FOR [ORD_COCASSAC],
	CONSTRAINT [DF_U_CCO_TT_ORD_SALDOCAS]  DEFAULT (0)  FOR [ORD_SALDOCAS],
	CONSTRAINT [DF_U_CCO_TT_ORD_IDENTPOS]  DEFAULT ('') FOR [ORD_IDENTPOS],
	CONSTRAINT [DF_U_CCO_TT_ORD_NTELEPOS]  DEFAULT ('') FOR [ORD_NTELEPOS],
	CONSTRAINT [DF_U_CCO_TT_ORD_COCA1POS]  DEFAULT ('') FOR [ORD_COCA1POS],
	CONSTRAINT [DF_U_CCO_TT_ORD_SALD1POS]  DEFAULT (0)  FOR [ORD_SALD1POS],
	CONSTRAINT [DF_U_CCO_DD_ORD_VIEW]      DEFAULT (0)  FOR [ORD_VIEW],
	CONSTRAINT [DF_U_CCO_DD_ORD_NOTE]      DEFAULT ('') FOR [ORD_NOTE],
	CONSTRAINT [DF_U_CCO_DD_ORS_CODCLI]    DEFAULT ('') FOR [ORS_CODCLI],
	CONSTRAINT [DF_U_CCO_DD_ORS_RAGSOC]    DEFAULT ('') FOR [ORS_RAGSOC],
	CONSTRAINT [DF_U_CCO_DD_ORS_NUMDOC]    DEFAULT ('') FOR [ORS_NUMDOC],
	CONSTRAINT [DF_U_CCO_DD_ORS_DATDOC]    DEFAULT ('') FOR [ORS_DATDOC],
	CONSTRAINT [DF_U_CCO_DD_SELEZIONE]     DEFAULT ('') FOR [SELEZIONE],
	CONSTRAINT [DF_U_CCO_DD_ORD_SEQUEN]    DEFAULT (0)  FOR [ORD_SEQUEN],
	CONSTRAINT [DF_U_CCO_DD_ORD_CODSYS]    DEFAULT ('') FOR [ORD_CODSYS],
	CONSTRAINT [DF_U_CCO_DD_ORD_UNIQUE]    DEFAULT ('') FOR [ORD_UNIQUE]
GO

