if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_CER_CO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_CER_CO]
GO
 
CREATE TABLE [dbo].[U_CER_CO] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[CER_AGGANC] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_NUMDDT] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DATDDT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_RAGSOC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[CER_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_RIFERI] [varchar] (60) COLLATE Latin1_General_CI_AS NULL ,
	[CER_NRLINT] [numeric] (10,0) NULL ,
	[CER_TIPPRG] [varchar] (01) COLLATE Latin1_General_CI_AS NULL ,
	[CER_NUMPRG] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[CER_AMGPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_PROGRE] [numeric] (10,0) NULL ,
	[CER_CODMAT] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DESMAT] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_SPESSO] [numeric] (4,0) NULL ,
	[CER_CODCOL] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DESCOL] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_TIPADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ADESIV] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ROTLNG] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ROTTRA] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ALNLNG] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ALNTRA] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CER_CDOINS] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DSOINS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DATINS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ORAINS] [varchar] (08) COLLATE Latin1_General_CI_AS NULL ,
	[CER_CDOMOD] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DSOMOD] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DATMOD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ORAMOD] [varchar] (08) COLLATE Latin1_General_CI_AS NULL ,
	[CER_CDOFIR] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DSOFIR] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CER_DATFIR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CER_ORAFIR] [varchar] (08) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_CER_CO] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_CER_CO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_CER_CO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CER_CO_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_CER_CO_CER_AGGANC] DEFAULT ('') FOR [CER_AGGANC],
	CONSTRAINT [DF_U_CER_CO_CER_NUMDDT] DEFAULT ('') FOR [CER_NUMDDT],
	CONSTRAINT [DF_U_CER_CO_CER_DATDDT] DEFAULT ('') FOR [CER_DATDDT],
	CONSTRAINT [DF_U_CER_CO_CER_CODCLI] DEFAULT ('') FOR [CER_CODCLI],
	CONSTRAINT [DF_U_CER_CO_CER_RAGSOC] DEFAULT ('') FOR [CER_RAGSOC],
	CONSTRAINT [DF_U_CER_CO_CER_CODART] DEFAULT ('') FOR [CER_CODART],
	CONSTRAINT [DF_U_CER_CO_CER_DESART] DEFAULT ('') FOR [CER_DESART],
	CONSTRAINT [DF_U_CER_CO_CER_RIFERI] DEFAULT ('') FOR [CER_RIFERI],
	CONSTRAINT [DF_U_CER_CO_CER_NRLINT] DEFAULT (0) FOR [CER_NRLINT],
	CONSTRAINT [DF_U_CER_CO_CER_TIPPRG] DEFAULT ('') FOR [CER_TIPPRG],
	CONSTRAINT [DF_U_CER_CO_CER_NUMPRG] DEFAULT ('') FOR [CER_NUMPRG],
	CONSTRAINT [DF_U_CER_CO_CER_AMGPRG] DEFAULT ('') FOR [CER_AMGPRG],
	CONSTRAINT [DF_U_CER_CO_CER_PROGRE] DEFAULT (0) FOR [CER_PROGRE],
	CONSTRAINT [DF_U_CER_CO_CER_CODMAT] DEFAULT ('') FOR [CER_CODMAT],
	CONSTRAINT [DF_U_CER_CO_CER_DESMAT] DEFAULT ('') FOR [CER_DESMAT],
	CONSTRAINT [DF_U_CER_CO_CER_SPESSO] DEFAULT (0) FOR [CER_SPESSO],
	CONSTRAINT [DF_U_CER_CO_CER_CODCOL] DEFAULT ('') FOR [CER_CODCOL],
	CONSTRAINT [DF_U_CER_CO_CER_DESCOL] DEFAULT ('') FOR [CER_DESCOL],
	CONSTRAINT [DF_U_CER_CO_CER_TIPADE] DEFAULT ('') FOR [CER_TIPADE],
	CONSTRAINT [DF_U_CER_CO_CER_ADESIV] DEFAULT ('') FOR [CER_ADESIV],
	CONSTRAINT [DF_U_CER_CO_CER_ROTLNG] DEFAULT ('') FOR [CER_ROTLNG],
	CONSTRAINT [DF_U_CER_CO_CER_ROTTRA] DEFAULT ('') FOR [CER_ROTTRA],
	CONSTRAINT [DF_U_CER_CO_CER_ALNLNG] DEFAULT ('') FOR [CER_ALNLNG],
	CONSTRAINT [DF_U_CER_CO_CER_ALNTRA] DEFAULT ('') FOR [CER_ALNTRA],
	CONSTRAINT [DF_U_CER_CO_CER_CDOINS] DEFAULT ('') FOR [CER_CDOINS],
	CONSTRAINT [DF_U_CER_CO_CER_DSOINS] DEFAULT ('') FOR [CER_DSOINS],
	CONSTRAINT [DF_U_CER_CO_CER_DATINS] DEFAULT ('') FOR [CER_DATINS],
	CONSTRAINT [DF_U_CER_CO_CER_ORAINS] DEFAULT ('') FOR [CER_ORAINS],
	CONSTRAINT [DF_U_CER_CO_CER_CDOMOD] DEFAULT ('') FOR [CER_CDOMOD],
	CONSTRAINT [DF_U_CER_CO_CER_DSOMOD] DEFAULT ('') FOR [CER_DSOMOD],
	CONSTRAINT [DF_U_CER_CO_CER_DATMOD] DEFAULT ('') FOR [CER_DATMOD],
	CONSTRAINT [DF_U_CER_CO_CER_ORAMOD] DEFAULT ('') FOR [CER_ORAMOD],
	CONSTRAINT [DF_U_CER_CO_CER_CDOFIR] DEFAULT ('') FOR [CER_CDOFIR],
	CONSTRAINT [DF_U_CER_CO_CER_DSOFIR] DEFAULT ('') FOR [CER_DSOFIR],
	CONSTRAINT [DF_U_CER_CO_CER_DATFIR] DEFAULT ('') FOR [CER_DATFIR],
	CONSTRAINT [DF_U_CER_CO_CER_ORAFIR] DEFAULT ('') FOR [CER_ORAFIR]
GO

