if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_CLI_EX]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_CLI_EX]
GO
 
CREATE TABLE [dbo].[U_CLI_EX] (
	id_unique uniqueidentifier ROWGUIDCOL  NOT NULL ,
    CODCLI_AQUARIUS varchar(10) COLLATE Latin1_General_CI_AS NULL ,
    RAGSOC_AQUARIUS varchar(45) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_ZUCCHETTI varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_SYSPAC varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_COPERNICO varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_PAG01 varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_PAG02 varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	CODCLI_PAG03 varchar(50) COLLATE Latin1_General_CI_AS NULL ,
	[NOTEINT] [text] COLLATE Latin1_General_CI_AS NULL 
		
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_CLI_EX] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_CLI_EX] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_CLI_EX] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_CLI_EX_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_AQUARIUS] DEFAULT ('') FOR [CODCLI_AQUARIUS],
	CONSTRAINT [DF_U_CLI_EX_RAGSOC_AQUARIUS] DEFAULT ('') FOR [RAGSOC_AQUARIUS],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_ZUCCHETTI] DEFAULT ('') FOR [CODCLI_ZUCCHETTI],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_SYSPAC] DEFAULT ('') FOR [CODCLI_SYSPAC],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_COPERNICO] DEFAULT ('') FOR [CODCLI_COPERNICO],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_PAG01] DEFAULT ('') FOR [CODCLI_PAG01],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_PAG02] DEFAULT ('') FOR [CODCLI_PAG02],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_PAG03] DEFAULT ('') FOR [CODCLI_PAG03],
	CONSTRAINT [DF_U_CLI_EX_CODCLI_NOTEINT] DEFAULT ('') FOR [NOTEINT]
	
GO
