if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_FAB_CL]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_FAB_CL]
GO
 
CREATE TABLE [dbo].[U_FAB_CL] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_CODSYS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORS_NUMORD] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[ORS_DATORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORS_RAGSOC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_UM] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[ORD_QTAORD] [numeric] (17,2) NULL ,
	[ORD_QTAEV] [numeric] (17,2) NULL ,
	[ORD_VALORE] [numeric] (17,2) NULL ,
	[ORD_DATCON] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[FAB_SETTIM] [varchar] (7) COLLATE Latin1_General_CI_AS NULL ,
	[FAB_SETRIB] [varchar] (7) COLLATE Latin1_General_CI_AS NULL ,
	[FAB_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[FAB_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[FAB_QTEVAD] [numeric] (17,2) NULL ,
	[FAB_QTAORD] [numeric] (17,2) NULL ,
	[FAB_NUMBOB] [numeric] (7,0) NULL ,
	[FAB_QTAUNI] [numeric] (17,2) NULL ,
	[FAB_QTAUKG] [numeric] (17,2) NULL ,
	[FAB_QTAUMQ] [numeric] (17,2) NULL ,
	[FAB_QTAUML] [numeric] (17,2) NULL ,
	[FAB_SPESSO] [numeric] (3,0) NULL ,
	[FAB_ALTEZZ] [numeric] (5,0) NULL ,
	[FAB_LUNGHE] [numeric] (6,0) NULL ,
	[ORF_NUMORD] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[ORF_DATORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORF_CODFOR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_FAB_CL] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_FAB_CL] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_FAB_CL] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_FAB_CL_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_FAB_CL_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_U_FAB_CL_ORD_CODSYS] DEFAULT ('') FOR [ORD_CODSYS],
	CONSTRAINT [DF_U_FAB_CL_ORS_NUMORD] DEFAULT ('') FOR [ORS_NUMORD],
	CONSTRAINT [DF_U_FAB_CL_ORS_DATORD] DEFAULT ('') FOR [ORS_DATORD],
	CONSTRAINT [DF_U_FAB_CL_ORS_RAGSOC] DEFAULT ('') FOR [ORS_RAGSOC],
	CONSTRAINT [DF_U_FAB_CL_ORD_CODART] DEFAULT ('') FOR [ORD_CODART],
	CONSTRAINT [DF_U_FAB_CL_ORD_DESART] DEFAULT ('') FOR [ORD_DESART],
	CONSTRAINT [DF_U_FAB_CL_ORD_UM] DEFAULT ('') FOR [ORD_UM],
	CONSTRAINT [DF_U_FAB_CL_ORD_QTAORD] DEFAULT (0) FOR [ORD_QTAORD],
	CONSTRAINT [DF_U_FAB_CL_ORD_QTAEV] DEFAULT (0) FOR [ORD_QTAEV],
	CONSTRAINT [DF_U_FAB_CL_ORD_VALORE] DEFAULT (0) FOR [ORD_VALORE],
	CONSTRAINT [DF_U_FAB_CL_ORD_DATCON] DEFAULT ('') FOR [ORD_DATCON],
	CONSTRAINT [DF_U_FAB_CL_FAB_SETTIM] DEFAULT ('') FOR [FAB_SETTIM],
	CONSTRAINT [DF_U_FAB_CL_FAB_SETRIB] DEFAULT ('') FOR [FAB_SETRIB],
	CONSTRAINT [DF_U_FAB_CL_FAB_CODART] DEFAULT ('') FOR [FAB_CODART],
	CONSTRAINT [DF_U_FAB_CL_FAB_DESART] DEFAULT ('') FOR [FAB_DESART],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTEVAD] DEFAULT (0) FOR [FAB_QTEVAD],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTAORD] DEFAULT (0) FOR [FAB_QTAORD],
	CONSTRAINT [DF_U_FAB_CL_FAB_NUMBOB] DEFAULT (0) FOR [FAB_NUMBOB],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTAUNI] DEFAULT (0) FOR [FAB_QTAUNI],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTAUKG] DEFAULT (0) FOR [FAB_QTAUKG],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTAUMQ] DEFAULT (0) FOR [FAB_QTAUMQ],
	CONSTRAINT [DF_U_FAB_CL_FAB_QTAUML] DEFAULT (0) FOR [FAB_QTAUML],
	CONSTRAINT [DF_U_FAB_CL_FAB_SPESSO] DEFAULT (0) FOR [FAB_SPESSO],
	CONSTRAINT [DF_U_FAB_CL_FAB_ALTEZZ] DEFAULT (0) FOR [FAB_ALTEZZ],
	CONSTRAINT [DF_U_FAB_CL_FAB_LUNGHE] DEFAULT (0) FOR [FAB_LUNGHE],
	CONSTRAINT [DF_U_FAB_CL_ORF_NUMORD] DEFAULT ('') FOR [ORF_NUMORD],
	CONSTRAINT [DF_U_FAB_CL_ORF_DATORD] DEFAULT ('') FOR [ORF_DATORD],
	CONSTRAINT [DF_U_FAB_CL_ORF_CODFOR] DEFAULT ('') FOR [ORF_CODFOR]
GO

