
/****** Object:  Table [dbo].[U_IVA_TO_DTDOC]    Script Date: 30/04/2019 11:09:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_IVA_TO_DTDOC](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_id_unique]  DEFAULT (newid()),
	[ITO_CODSOC] [varchar](2) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_CODSOC]  DEFAULT (''),
	[ITO_ANNO] [varchar](4) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_ANNO]  DEFAULT (''),
	[ITO_MESE] [varchar](2) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_MESE]  DEFAULT (''),
	[ITO_CODIVA] [varchar](3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_CODIVA]  DEFAULT (''),
	[ITO_IND100] [varchar](1) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_IND100]  DEFAULT (''),
	[ITO_DESIVA] [varchar](30) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_DESIVA]  DEFAULT (''),
	[ITO_IMPONI] [numeric](16, 3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_IMPONI]  DEFAULT (0),
	[ITO_IMPOST] [numeric](16, 3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_IMPOST]  DEFAULT (0),
	[ITO_DTCREA] [varchar](10) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_DTCREA]  DEFAULT (''),
	[ITO_FATNOT] [varchar](1) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_FATNOT]  DEFAULT (''),
	[ITO_CLIFOR] [varchar](1) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_CLIFOR]  DEFAULT (''),
	[ITO_IMPONR] [numeric](16, 3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_IMPONR]  DEFAULT (0),
	[ITO_IMPOSR] [numeric](16, 3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_IMPOSR]  DEFAULT (0),
	[ITO_VALUTA] [varchar](3) NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_VALUTA]  DEFAULT (''),
	[ITO_DEDUCIBILE] [bit] NULL CONSTRAINT [DF_U_IVA_TO_DTDOC_ITO_DEDUCIBILE]  DEFAULT ((0)),
 CONSTRAINT [PK_U_IVA_TO_DTDOC] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

