
/****** Object:  Table [dbo].[U_IVF_CL_DTDOC]    Script Date: 30/04/2019 11:12:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_IVF_CL_DTDOC](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_id_unique]  DEFAULT (newid()),
	[IVF_CHIAVE] [numeric](6, 0) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CHIAVE]  DEFAULT (0),
	[IVF_CODSOC] [varchar](2) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CODSOC]  DEFAULT (''),
	[IVF_ANNO] [varchar](4) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_ANNO]  DEFAULT (''),
	[IVF_MESE] [varchar](2) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_MESE]  DEFAULT (''),
	[IVF_CODCLI] [varchar](10) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CODCLI]  DEFAULT (''),
	[IVF_RAGSOC] [varchar](40) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_RAGSOC]  DEFAULT (''),
	[IVF_INDIRI] [varchar](40) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_INDIRI]  DEFAULT (''),
	[IVF_LOCALI] [varchar](40) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_LOCALI]  DEFAULT (''),
	[IVF_CAP] [varchar](5) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CAP]  DEFAULT (''),
	[IVF_FATNOT] [varchar](1) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_FATNOT]  DEFAULT (''),
	[IVF_DTFATT] [varchar](10) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_DTFATT]  DEFAULT (''),
	[IVF_DTCREA] [varchar](10) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_DTCREA]  DEFAULT (''),
	[IVF_IMPONI] [numeric](18, 3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_IMPONI]  DEFAULT (0),
	[IVF_CODIVA] [varchar](3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CODIVA]  DEFAULT (''),
	[IVF_ALIQUO] [numeric](7, 3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_ALIQUO]  DEFAULT (0),
	[IVF_IND100] [varchar](1) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_IND100]  DEFAULT (''),
	[IVF_DESIVA] [varchar](21) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_DESIVA]  DEFAULT (''),
	[IVF_IMPOST] [numeric](18, 3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_IMPOST]  DEFAULT (0),
	[IVF_TOTALE] [numeric](17, 3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_TOTALE]  DEFAULT (0),
	[IVF_PARIVA] [varchar](16) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_PARIVA]  DEFAULT (''),
	[IVF_NUMFAT] [varchar](20) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_NUMFAT]  DEFAULT (''),
	[IVF_FCHIUS] [bit] NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_FCHIUS]  DEFAULT (0),
	[IVF_NUMPRO] [numeric](6, 0) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_NUMPRO]  DEFAULT (0),
	[IVF_FATRI] [bit] NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_FATRI]  DEFAULT (0),
	[IVF_BDOG] [bit] NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_BDOG]  DEFAULT (0),
	[IVF_TOP] [varchar](3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_TOP]  DEFAULT (''),
	[IVF_VALUTA] [varchar](3) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_VALUTA]  DEFAULT (''),
	[IVF_CAMBIO] [numeric](17, 10) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_CAMBIO]  DEFAULT (0),
	[IVF_NUMNEW] [numeric](10, 0) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_NUMNEW]  DEFAULT (0),
	[IVF_DL78] [bit] NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_DL78]  DEFAULT ((0)),
	[IVF_NUMORI] [varchar](10) NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_NUMORI]  DEFAULT (''),
	[IVF_DEDUCIBILE] [bit] NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_IVF_DEDUCIBILE]  DEFAULT ((0)),
	[MOV_NUMPRO] [varchar](10) NOT NULL CONSTRAINT [DF_U_IVF_CL_DTDOC_MOV_NUMPRO]  DEFAULT (''),
 CONSTRAINT [PK_U_IVF_CL_DTDOC] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
