

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_ttresi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_12resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_11resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_10resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_09resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_08resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_07resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_06resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_05resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_04resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_03resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_02resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_iva_01resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_PLAFOND]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_DICEMB]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_NOVEMB]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_OTTOBR]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_SETTEM]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_AGOSTO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_LUGLIO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_GIUGNO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_MAGGIO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_APRILE]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_MARZO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_FEBBRA]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_GENNAI]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_ANNO]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_IVA_CODSOC]
GO

ALTER TABLE [dbo].[U_IVA_ES] DROP CONSTRAINT [DF_U_IVA_ES_id_unique]
GO

/****** Object:  Table [dbo].[U_IVA_ES]    Script Date: 13/02/2014 17.52.46 ******/
DROP TABLE [dbo].[U_IVA_ES]
GO

/****** Object:  Table [dbo].[U_IVA_ES]    Script Date: 13/02/2014 17.52.46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_IVA_ES](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[IVA_CODSOC] [varchar](2) NULL,
	[IVA_ANNO] [numeric](4, 0) NULL,
	[IVA_PLAFOND] [numeric](17, 3) NULL,
	[IVA_GENNAI] [numeric](15, 2) NULL,
	[IVA_FEBBRA] [numeric](15, 2) NULL,
	[IVA_MARZO] [numeric](15, 2) NULL,
	[IVA_APRILE] [numeric](15, 2) NULL,
	[IVA_MAGGIO] [numeric](15, 2) NULL,
	[IVA_GIUGNO] [numeric](15, 2) NULL,
	[IVA_LUGLIO] [numeric](15, 2) NULL,
	[IVA_AGOSTO] [numeric](15, 2) NULL,
	[IVA_SETTEM] [numeric](15, 2) NULL,
	[IVA_OTTOBR] [numeric](15, 2) NULL,
	[IVA_NOVEMB] [numeric](15, 2) NULL,
	[IVA_DICEMB] [numeric](15, 2) NULL,
	[iva_01resi] [numeric](17, 3) NULL,
	[iva_02resi] [numeric](17, 3) NULL,
	[iva_03resi] [numeric](17, 3) NULL,
	[iva_04resi] [numeric](17, 3) NULL,
	[iva_05resi] [numeric](17, 3) NULL,
	[iva_06resi] [numeric](17, 3) NULL,
	[iva_07resi] [numeric](17, 3) NULL,
	[iva_08resi] [numeric](17, 3) NULL,
	[iva_09resi] [numeric](17, 3) NULL,
	[iva_10resi] [numeric](17, 3) NULL,
	[iva_11resi] [numeric](17, 3) NULL,
	[iva_12resi] [numeric](17, 3) NULL,
	[iva_ttresi] [numeric](17, 3) NULL

 CONSTRAINT [PK_U_IVA_ES] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_CODSOC]  DEFAULT ('') FOR [IVA_CODSOC]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_ANNO]  DEFAULT (0) FOR [IVA_ANNO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_PLAFOND]  DEFAULT ('0') FOR [IVA_PLAFOND]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_GENNAI]  DEFAULT (0) FOR [IVA_GENNAI]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_FEBBRA]  DEFAULT (0) FOR [IVA_FEBBRA]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_MARZO]  DEFAULT (0) FOR [IVA_MARZO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_APRILE]  DEFAULT (0) FOR [IVA_APRILE]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_MAGGIO]  DEFAULT (0) FOR [IVA_MAGGIO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_GIUGNO]  DEFAULT (0) FOR [IVA_GIUGNO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_LUGLIO]  DEFAULT (0) FOR [IVA_LUGLIO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_AGOSTO]  DEFAULT (0) FOR [IVA_AGOSTO]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_SETTEM]  DEFAULT (0) FOR [IVA_SETTEM]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_OTTOBR]  DEFAULT (0) FOR [IVA_OTTOBR]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_NOVEMB]  DEFAULT (0) FOR [IVA_NOVEMB]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_IVA_DICEMB]  DEFAULT (0) FOR [IVA_DICEMB]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_01resi]  DEFAULT ('0') FOR [iva_01resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_02resi]  DEFAULT ('0') FOR [iva_02resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_03resi]  DEFAULT ('0') FOR [iva_03resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_04resi]  DEFAULT ('0') FOR [iva_04resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_05resi]  DEFAULT ('0') FOR [iva_05resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_06resi]  DEFAULT ('0') FOR [iva_06resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_07resi]  DEFAULT ('0') FOR [iva_07resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_08resi]  DEFAULT ('0') FOR [iva_08resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_09resi]  DEFAULT ('0') FOR [iva_09resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_10resi]  DEFAULT ('0') FOR [iva_10resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_11resi]  DEFAULT ('0') FOR [iva_11resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_12resi]  DEFAULT ('0') FOR [iva_12resi]
GO

ALTER TABLE [dbo].[U_IVA_ES] ADD  CONSTRAINT [DF_U_IVA_ES_iva_ttresi]  DEFAULT ('0') FOR [iva_ttresi]
GO



