
/****** Object:  Table [dbo].[U_IVA_CS]    Script Date: 24/10/2013 14.40.44 ******/
DROP TABLE [dbo].[U_IVA_CS]
GO

/****** Object:  Table [dbo].[U_IVA_CS]    Script Date: 24/10/2013 14.40.44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_IVA_CS](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[IVA_CHIAVE] [numeric](6, 0) NULL,
	[IVA_CODSOC] [varchar](2) NULL,
	[IVA_ANNO] [varchar](4) NULL,
	[IVA_MESE] [varchar](2) NULL,
    [IVA_STATO] [varchar](10) NULL,
	[IVA_DTPAGAM] [varchar](10) NULL,
	[IVA_DTFATT] [varchar](10) NULL,
	[IVA_NUMDOC] [varchar](6) NULL,
	[IVA_NUMFAT] [varchar](6) NULL,
	[IVA_NUMCEE] [varchar](6) NULL,
	[IVA_CODCLI] [varchar](13) NULL,
	[IVA_RAGSOC] [varchar](40) NULL,
	[IVA_INDIRI] [varchar](40) NULL,
	[IVA_LOCALI] [varchar](40) NULL,
	[IVA_CAP] [varchar](5) NULL,
	[IVA_FATNOT] [varchar](1) NULL,
	[IVA_DTCREA] [varchar](10) NULL,
	[IVA_IMPONI] [numeric](18, 3) NULL,
	[IVA_IMPOST] [numeric](18, 3) NULL,
	[IVA_TOTALE] [numeric](17, 3) NULL,
	[SOS_IMPONI] [numeric](18, 3) NULL,
	[SOS_IMPOST] [numeric](18, 3) NULL,
	[SOS_TOTALE] [numeric](17, 3) NULL,
	[IVA_CODIVA] [varchar](3) NULL,
	[IVA_ALIQUO] [numeric](7, 3) NULL,
	[IVA_DESIVA] [varchar](21) NULL,
	[IVA_PARIVA] [varchar](16) NULL,
	[IVA_FCHIUS] [bit] NULL,
	[IVA_CEE] [varchar](2) NULL,
	[IVA_CODAGE] [varchar](3) NULL,
	[IVA_VALUTA] [varchar](3) NULL,
	[IVA_CAMBIO] [numeric](17, 10) NULL,
	[IVA_BOLLATOIVA] [varchar](1) NULL,
	[iva_top] [varchar](10) NULL,
	[IVA_NUMNEW] [numeric](10, 0) NULL,
 CONSTRAINT [PK_U_IVA_CS] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CHIAVE]  DEFAULT (0) FOR [IVA_CHIAVE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CODSOC]  DEFAULT ('') FOR [IVA_CODSOC]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_ANNO]  DEFAULT ('') FOR [IVA_ANNO]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_MESE]  DEFAULT ('') FOR [IVA_MESE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_STATO]  DEFAULT ('') FOR [IVA_STATO]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_DTPAGAM]  DEFAULT ('') FOR [IVA_DTPAGAM]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_DTFATT]  DEFAULT ('') FOR [IVA_DTFATT]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_NUMDOC]  DEFAULT ('') FOR [IVA_NUMDOC]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_NUMFAT]  DEFAULT ('') FOR [IVA_NUMFAT]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_NUMCEE]  DEFAULT ('') FOR [IVA_NUMCEE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CODCLI]  DEFAULT ('') FOR [IVA_CODCLI]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_RAGSOC]  DEFAULT ('') FOR [IVA_RAGSOC]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_INDIRI]  DEFAULT ('') FOR [IVA_INDIRI]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_LOCALI]  DEFAULT ('') FOR [IVA_LOCALI]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CAP]  DEFAULT ('') FOR [IVA_CAP]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_FATNOT]  DEFAULT ('') FOR [IVA_FATNOT]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_DTCREA]  DEFAULT ('') FOR [IVA_DTCREA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_IMPONI]  DEFAULT (0) FOR [IVA_IMPONI]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_IMPOST]  DEFAULT (0) FOR [IVA_IMPOST]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_TOTALE]  DEFAULT (0) FOR [IVA_TOTALE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_SOS_IMPONI]  DEFAULT (0) FOR [SOS_IMPONI]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_SOS_IMPOST]  DEFAULT (0) FOR [SOS_IMPOST]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_SOS_TOTALE]  DEFAULT (0) FOR [SOS_TOTALE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CODIVA]  DEFAULT ('') FOR [IVA_CODIVA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_ALIQUO]  DEFAULT (0) FOR [IVA_ALIQUO]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_DESIVA]  DEFAULT ('') FOR [IVA_DESIVA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_PARIVA]  DEFAULT ('') FOR [IVA_PARIVA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_FCHIUS]  DEFAULT (0) FOR [IVA_FCHIUS]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CEE]  DEFAULT ('') FOR [IVA_CEE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CODAGE]  DEFAULT ('') FOR [IVA_CODAGE]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_VALUTA]  DEFAULT ('') FOR [IVA_VALUTA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_CAMBIO]  DEFAULT (0) FOR [IVA_CAMBIO]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_BOLLATOIVA]  DEFAULT ('') FOR [IVA_BOLLATOIVA]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_iva_top]  DEFAULT ('   ') FOR [iva_top]
GO

ALTER TABLE [dbo].[U_IVA_CS] ADD  CONSTRAINT [DF_U_IVA_CS_IVA_NUMNEW]  DEFAULT (0) FOR [IVA_NUMNEW]
GO


