

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_LIS_LO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_LIS_LO]
GO
 
CREATE TABLE [dbo].[U_LIS_LO] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[LIS_CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_RAGSOC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_DDAOLD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_DALOLD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_DDANEW] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_DALNEW] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_PERVAR] [numeric] (6,2) NULL ,
	[LIS_DATGEN] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_ORAGEN] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_CODOPE] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[LIS_DESOPE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_LIS_LO] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_LIS_LO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_LIS_LO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_LIS_LO_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_LIS_LO_LIS_CODCLI] DEFAULT ('') FOR [LIS_CODCLI],
	CONSTRAINT [DF_U_LIS_LO_LIS_RAGSOC] DEFAULT ('') FOR [LIS_RAGSOC],
	CONSTRAINT [DF_U_LIS_LO_LIS_CODART] DEFAULT ('') FOR [LIS_CODART],
	CONSTRAINT [DF_U_LIS_LO_LIS_DDAOLD] DEFAULT ('') FOR [LIS_DDAOLD],
	CONSTRAINT [DF_U_LIS_LO_LIS_DALOLD] DEFAULT ('') FOR [LIS_DALOLD],
	CONSTRAINT [DF_U_LIS_LO_LIS_DDANEW] DEFAULT ('') FOR [LIS_DDANEW],
	CONSTRAINT [DF_U_LIS_LO_LIS_DALNEW] DEFAULT ('') FOR [LIS_DALNEW],
	CONSTRAINT [DF_U_LIS_LO_LIS_PERVAR] DEFAULT (0) FOR [LIS_PERVAR],
	CONSTRAINT [DF_U_LIS_LO_LIS_DATGEN] DEFAULT ('') FOR [LIS_DATGEN],
    CONSTRAINT [DF_U_LIS_LO_LIS_ORAGEN] DEFAULT ('') FOR [LIS_ORAGEN],
    CONSTRAINT [DF_U_LIS_LO_LIS_CODOPE] DEFAULT ('') FOR [LIS_CODOPE],
    CONSTRAINT [DF_U_LIS_LO_LIS_DESOPE] DEFAULT ('') FOR [LIS_DESOPE],
	CONSTRAINT [DF_U_LIS_LO_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

