
ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_UMMAGA]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_QTA]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_PRZSCO]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_FLGTRA]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_PUBBLI]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_CODVAL]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_SELEZIONE]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_SC3]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_SC2]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_SC1]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_PROVVI]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_KILIMP]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DTCONT]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_SCONTO]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_TRASME]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DEARC1]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_PREZZO]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DEARCL]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_ARTGRU]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_CLIART]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_ALLIST]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DATLIS]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DESART]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_CODART]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_DESLIS]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_TIPOAZI]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_LIS_CODSOC]
GO

ALTER TABLE [dbo].[U_LIS_AA] DROP CONSTRAINT [DF_U_LIS_AA_id_unique]
GO

/****** Object:  Table [dbo].[U_LIS_AA]    Script Date: 13/12/2013 22.54.30 ******/
DROP TABLE [dbo].[U_LIS_AA]
GO

/****** Object:  Table [dbo].[U_LIS_AA]    Script Date: 13/12/2013 22.54.30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_LIS_AA](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[LIS_CODSOC] [varchar](2) NULL,
	[LIS_TIPOAZI] [varchar](10) NULL,
	[LIS_DESLIS] [varchar](30) NULL,
	[LIS_CODART] [varchar](16) NULL,
	[LIS_DESART] [varchar](100) NULL,
	[LIS_DATLIS] [varchar](10) NULL,
	[LIS_ALLIST] [varchar](10) NULL,
	[LIS_CLIART] [varchar](16) NULL,
	[LIS_ARTGRU] [varchar](1) NULL,
	[LIS_DEARCL] [varchar](40) NULL,
	[LIS_PREZZO] [numeric](17, 6) NULL,
	[LIS_DEARC1] [varchar](40) NULL,
	[LIS_TRASME] [varchar](2) NULL,
	[LIS_SCONTO] [numeric](16, 3) NULL,
	[LIS_DTCONT] [varchar](10) NULL,
	[LIS_KILIMP] [numeric](6, 0) NULL,
	[LIS_PROVVI] [numeric](8, 3) NULL,
	[LIS_SC1] [numeric](5, 2) NULL,
	[LIS_SC2] [numeric](5, 2) NULL,
	[LIS_SC3] [numeric](5, 2) NULL,
	[SELEZIONE] [varchar](10) NULL,
	[LIS_CODVAL] [varchar](3) NULL,
	[LIS_PUBBLI] [varchar](1) NULL,
	[LIS_FLGTRA] [bit] NULL,
	[LIS_PRZSCO] [numeric](17, 6) NULL,
	[LIS_QTA] [numeric](10, 2) NULL,
	[LIS_UMMAGA] [varchar](4) NULL,
 CONSTRAINT [PK_U_LIS_AA] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_CODSOC]  DEFAULT ('') FOR [LIS_CODSOC]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_TIPOAZI]  DEFAULT ('') FOR [LIS_TIPOAZI]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DESLIS]  DEFAULT ('') FOR [LIS_DESLIS]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_CODART]  DEFAULT ('') FOR [LIS_CODART]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DESART]  DEFAULT ('') FOR [LIS_DESART]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DATLIS]  DEFAULT ('') FOR [LIS_DATLIS]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_ALLIST]  DEFAULT ('') FOR [LIS_ALLIST]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_CLIART]  DEFAULT ('') FOR [LIS_CLIART]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_ARTGRU]  DEFAULT ('') FOR [LIS_ARTGRU]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DEARCL]  DEFAULT ('') FOR [LIS_DEARCL]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_PREZZO]  DEFAULT (0) FOR [LIS_PREZZO]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DEARC1]  DEFAULT ('') FOR [LIS_DEARC1]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_TRASME]  DEFAULT ('') FOR [LIS_TRASME]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_SCONTO]  DEFAULT (0) FOR [LIS_SCONTO]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_DTCONT]  DEFAULT ('') FOR [LIS_DTCONT]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_KILIMP]  DEFAULT (0) FOR [LIS_KILIMP]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_PROVVI]  DEFAULT (0) FOR [LIS_PROVVI]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_SC1]  DEFAULT (0) FOR [LIS_SC1]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_SC2]  DEFAULT (0) FOR [LIS_SC2]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_SC3]  DEFAULT (0) FOR [LIS_SC3]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_CODVAL]  DEFAULT ('') FOR [LIS_CODVAL]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_PUBBLI]  DEFAULT ('') FOR [LIS_PUBBLI]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_FLGTRA]  DEFAULT (0) FOR [LIS_FLGTRA]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_PRZSCO]  DEFAULT (0) FOR [LIS_PRZSCO]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_QTA]  DEFAULT (0) FOR [LIS_QTA]
GO

ALTER TABLE [dbo].[U_LIS_AA] ADD  CONSTRAINT [DF_U_LIS_AA_LIS_UMMAGA]  DEFAULT ('') FOR [LIS_UMMAGA]
GO


