
/****** Object:  Table [dbo].[U_LIF_BA]    Script Date: 19/04/2016 16:15:38 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_LIF_BA]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_LIF_BA]
GO


/****** Object:  Table [dbo].[U_LIF_BA]    Script Date: 19/04/2016 16:15:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_LIF_BA](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[LIS_CODSOC] [varchar](2) NULL,
	[LIS_CODLIS] [varchar](6) NULL,
	[LIS_DESLIS] [varchar](30) NULL,
	[LIS_TIPOLI] [bit] NULL,
	[LIS_DATLIS] [varchar](10) NULL,
	[LIS_ALLIST] [varchar](10) NULL,
	[LIS_SC1] [numeric](7, 2) NULL,
	[LIS_SC2] [numeric](7, 2) NULL,
	[LIS_SC3] [numeric](7, 2) NULL,
	[LIS_PE_PRI] [numeric](7, 2) NULL,
	[LIS_PE_PRO] [numeric](7, 2) NULL,
	[LIS_PE_PA1] [numeric](7, 2) NULL,
	[LIS_PE_PA2] [numeric](7, 2) NULL,
	[LIS_PE_PA3] [numeric](7, 2) NULL,
 	[SELEZIONE] [varchar](10) NULL,
	[LIS_VALUTA] [varchar](3) NULL,
	[LIF_VALUTA] [varchar](3) NULL,
 CONSTRAINT [PK_U_LIF_BA] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_CODSOC]  DEFAULT ('') FOR [LIS_CODSOC]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_TIPOLI]  DEFAULT ((0)) FOR [LIS_TIPOLI]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_DATLIS]  DEFAULT ('') FOR [LIS_DATLIS]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_ALLIST]  DEFAULT ('') FOR [LIS_ALLIST]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_SC1]  DEFAULT ((0)) FOR [LIS_SC1]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_SC2]  DEFAULT ((0)) FOR [LIS_SC2]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_SC3]  DEFAULT ((0)) FOR [LIS_SC3]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_PE_PRI]  DEFAULT ((0)) FOR [LIS_PE_PRI]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_PE_PRO]  DEFAULT ((0)) FOR [LIS_PE_PRO]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_PE_PA1]  DEFAULT ((0)) FOR [LIS_PE_PA1]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_PE_PA2]  DEFAULT ((0)) FOR [LIS_PE_PA2]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_PE_PA3]  DEFAULT ((0)) FOR [LIS_PE_PA3]
GO
  
ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_SELEZIONE]  DEFAULT ('') FOR [SELEZIONE]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIS_VALUTA]  DEFAULT ('') FOR [LIS_VALUTA]
GO

ALTER TABLE [dbo].[U_LIF_BA] ADD  CONSTRAINT [DF_U_LIF_BA_LIF_VALUTA]  DEFAULT ('') FOR [LIF_VALUTA]
GO


