if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_LOC_GE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_LOC_GE]
GO
 
CREATE TABLE [dbo].[U_LOC_GE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[LOC_CODMAG] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[LOC_FILSEL] [bit] NULL ,
	[LOC_FILNUM] [numeric] (6,0) NULL ,
	[LOC_FILALF] [varchar] (05) COLLATE Latin1_General_CI_AS NULL ,
	[LOC_PIASEL] [bit] NULL ,
	[LOC_PIANUM] [numeric] (6,0) NULL ,
	[LOC_PIAALF] [varchar] (05) COLLATE Latin1_General_CI_AS NULL ,
	[LOC_UBISEL] [bit] NULL ,
	[LOC_UBINUM] [numeric] (6,0) NULL ,
	[LOC_UBIALF] [varchar] (05) COLLATE Latin1_General_CI_AS NULL

) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_LOC_GE] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_LOC_GE] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_LOC_GE] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_LOC_GE_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_LOC_GE_LOC_CODMAG] DEFAULT ('') FOR [LOC_CODMAG],
	CONSTRAINT [DF_U_LOC_GE_LOC_FILSEL] DEFAULT (0) FOR [LOC_FILSEL],
	CONSTRAINT [DF_U_LOC_GE_LOC_FILNUM] DEFAULT (0) FOR [LOC_FILNUM],
	CONSTRAINT [DF_U_LOC_GE_LOC_FILALF] DEFAULT ('') FOR [LOC_FILALF],
	CONSTRAINT [DF_U_LOC_GE_LOC_PIASEL] DEFAULT (0) FOR [LOC_PIASEL],
	CONSTRAINT [DF_U_LOC_GE_LOC_PIANUM] DEFAULT (0) FOR [LOC_PIANUM],
	CONSTRAINT [DF_U_LOC_GE_LOC_PIAALF] DEFAULT ('') FOR [LOC_PIAALF],
	CONSTRAINT [DF_U_LOC_GE_LOC_UBISEL] DEFAULT (0) FOR [LOC_UBISEL],
	CONSTRAINT [DF_U_LOC_GE_LOC_UBINUM] DEFAULT (0) FOR [LOC_UBINUM],
	CONSTRAINT [DF_U_LOC_GE_LOC_UBIALF] DEFAULT ('') FOR [LOC_UBIALF]
GO

