if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_MAG_AR]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_MAG_AR]
GO
 
CREATE TABLE [dbo].[U_MAG_AR] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[MAG_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODMAG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESMAG] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_FORNIT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESFOR] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_PERI]   [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODACQ] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_DESACQ] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_MATCHC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_QTMOVI] [numeric] (19,2) NULL ,
	[MAG_QTCARI] [numeric] (19,2) NULL ,
	[MAG_VACARI] [numeric] (20,3) NULL ,
	[MAG_QTSCAR] [numeric] (19,2) NULL ,
	[MAG_VASCAR] [numeric] (20,3) NULL ,
	[MAG_VALVEN] [numeric] (20,3) NULL ,
	[MAG_VALCOS] [numeric] (20,3) NULL ,
	[MAG_SCOSTA] [numeric] (20,3) NULL ,
	[MAG_PERSCO] [numeric] (12,3) NULL ,
	[MAG_QTRESC] [numeric] (20,3) NULL ,
	[MAG_VARESC] [numeric] (20,3) NULL ,
	[MAG_QTRESF] [numeric] (20,3) NULL ,
	[MAG_VARESF] [numeric] (20,3) NULL ,
	[MAG_DATAGG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_MAG_AR] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_MAG_AR] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_MAG_AR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAG_AR_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_MAG_AR_MAG_CODSOC] DEFAULT ('') FOR [MAG_CODSOC],
	CONSTRAINT [DF_U_MAG_AR_MAG_PERI] DEFAULT ('') FOR [MAG_PERI],
	CONSTRAINT [DF_U_MAG_AR_MAG_CODMAG] DEFAULT ('') FOR [MAG_CODMAG],
	CONSTRAINT [DF_U_MAG_AR_MAG_DESMAG] DEFAULT ('') FOR [MAG_DESMAG],
	CONSTRAINT [DF_U_MAG_AR_MAG_CODART] DEFAULT ('') FOR [MAG_CODART],
	CONSTRAINT [DF_U_MAG_AR_MAG_DESART] DEFAULT ('') FOR [MAG_DESART],
	CONSTRAINT [DF_U_MAG_AR_MAG_FORNIT] DEFAULT ('') FOR [MAG_FORNIT],
	CONSTRAINT [DF_U_MAG_AR_MAG_DESFOR] DEFAULT ('') FOR [MAG_DESFOR],
	CONSTRAINT [DF_U_MAG_AR_MAG_CODACQ] DEFAULT ('') FOR [MAG_CODACQ],
	CONSTRAINT [DF_U_MAG_AR_MAG_DESACQ] DEFAULT ('') FOR [MAG_DESACQ],
	CONSTRAINT [DF_U_MAG_AR_MAG_MATCHC] DEFAULT ('') FOR [MAG_MATCHC],
	CONSTRAINT [DF_U_MAG_AR_MAG_QTMOVI] DEFAULT (0) FOR [MAG_QTMOVI],
	CONSTRAINT [DF_U_MAG_AR_MAG_QTCARI] DEFAULT (0) FOR [MAG_QTCARI],
	CONSTRAINT [DF_U_MAG_AR_MAG_VACARI] DEFAULT (0) FOR [MAG_VACARI],
	CONSTRAINT [DF_U_MAG_AR_MAG_QTSCAR] DEFAULT (0) FOR [MAG_QTSCAR],
	CONSTRAINT [DF_U_MAG_AR_MAG_VASCAR] DEFAULT (0) FOR [MAG_VASCAR],
	CONSTRAINT [DF_U_MAG_AR_MAG_VALVEN] DEFAULT (0) FOR [MAG_VALVEN],
	CONSTRAINT [DF_U_MAG_AR_MAG_VALCOS] DEFAULT (0) FOR [MAG_VALCOS],
	CONSTRAINT [DF_U_MAG_AR_MAG_SCOSTA] DEFAULT (0) FOR [MAG_SCOSTA],
	CONSTRAINT [DF_U_MAG_AR_MAG_PERSCO] DEFAULT (0) FOR [MAG_PERSCO],
	CONSTRAINT [DF_U_MAG_AR_MAG_QTRESC] DEFAULT (0) FOR [MAG_QTRESC],
	CONSTRAINT [DF_U_MAG_AR_MAG_VARESC] DEFAULT (0) FOR [MAG_VARESC],
	CONSTRAINT [DF_U_MAG_AR_MAG_QTRESF] DEFAULT (0) FOR [MAG_QTRESF],
	CONSTRAINT [DF_U_MAG_AR_MAG_VARESF] DEFAULT (0) FOR [MAG_VARESF],
	CONSTRAINT [DF_U_MAG_AR_MAG_DATAGG] DEFAULT ('') FOR [MAG_DATAGG],
	CONSTRAINT [DF_U_MAG_AR_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

