if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_MAN_CO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_MAN_CO]
GO
 
CREATE TABLE [dbo].[U_MAN_CO] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[MAN_ALTEDA] [numeric] (5,0) NULL ,
	[MAN_ALTEAL] [numeric] (5,0) NULL ,
	[MAN_LUNGDA] [numeric] (6,0) NULL ,
	[MAN_LUNGAL] [numeric] (6,0) NULL ,
	[MAN_SPESDA] [numeric] (3,0) NULL ,
	[MAN_SPESAL] [numeric] (3,0) NULL ,
	[MAN_CODPER] [varchar] (02) COLLATE Latin1_General_CI_AS NULL ,
	[MAN_CODMAN] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[MAN_DESMAN] [varchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_MAN_CO] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_MAN_CO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_MAN_CO] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_MAN_CO_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_MAN_CO_MAN_ALTEDA] DEFAULT (0) FOR [MAN_ALTEDA],
	CONSTRAINT [DF_U_MAN_CO_MAN_ALTEAL] DEFAULT (0) FOR [MAN_ALTEAL],
	CONSTRAINT [DF_U_MAN_CO_MAN_LUNGDA] DEFAULT (0) FOR [MAN_LUNGDA],
	CONSTRAINT [DF_U_MAN_CO_MAN_LUNGAL] DEFAULT (0) FOR [MAN_LUNGAL],
	CONSTRAINT [DF_U_MAN_CO_MAN_SPESDA] DEFAULT (0) FOR [MAN_SPESDA],
	CONSTRAINT [DF_U_MAN_CO_MAN_SPESAL] DEFAULT (0) FOR [MAN_SPESAL],
	CONSTRAINT [DF_U_MAN_CO_MAN_CODPER] DEFAULT ('') FOR [MAN_CODPER],
	CONSTRAINT [DF_U_MAN_CO_MAN_CODMAN] DEFAULT ('') FOR [MAN_CODMAN],
	CONSTRAINT [DF_U_MAN_CO_MAN_DESMAN] DEFAULT ('') FOR [MAN_DESMAN]
GO

