if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_ORD_IM]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_ORD_IM]
GO
 
CREATE TABLE [dbo].[U_ORD_IM] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CODSYS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[LOTTO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_UNIQUE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_LEGAME] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[QUANTI] [numeric] (12,2) NULL ,
	[QTAEV] [numeric] (12,2) NULL ,
	[FLGEV] [bit] NULL ,
	[DATEV] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORAEV] [varchar] (8) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_ORD_IM] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_ORD_IM] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_ORD_IM] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_ORD_IM_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_ORD_IM_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_U_ORD_IM_CODSYS] DEFAULT ('') FOR [CODSYS],
	CONSTRAINT [DF_U_ORD_IM_CODART] DEFAULT ('') FOR [CODART],
	CONSTRAINT [DF_U_ORD_IM_LOTTO] DEFAULT ('') FOR [LOTTO],
	CONSTRAINT [DF_U_ORD_MAG_UNIQUE] DEFAULT ('') FOR [MAG_UNIQUE],
	CONSTRAINT [DF_U_ORD_MAG_LEGAME] DEFAULT ('') FOR [MAG_LEGAME],
	CONSTRAINT [DF_U_ORD_IM_QUANTI] DEFAULT (0) FOR [QUANTI],
	CONSTRAINT [DF_U_ORD_IM_QTAEV] DEFAULT (0) FOR [QTAEV],
	CONSTRAINT [DF_U_ORD_IM_FLGEV] DEFAULT ('') FOR [FLGEV],
	CONSTRAINT [DF_U_ORD_IM_DATEV] DEFAULT ('') FOR [DATEV],
CONSTRAINT [DF_U_ORD_IM_ORAEV] DEFAULT ('') FOR [ORAEV]
GO

