if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PAR_CT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_PAR_CT]
GO

CREATE TABLE [dbo].[U_PAR_CT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
        [PAR_CODNAZ] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PAR_DESNAZ] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
        [PAR_ZONA] [varchar] (02) COLLATE Latin1_General_CI_AS NULL ,
        [PAR_TIPTRA] [varchar] (01) COLLATE Latin1_General_CI_AS NULL ,
	[PAR_DESTRA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PAR_PRZITA] [numeric] (17,6) NULL ,
	[PAR_PRZE01] [numeric] (17,6) NULL ,
	[PAR_PRZE02] [numeric] (17,6) NULL ,
	[PAR_PRZE03] [numeric] (17,6) NULL ,
	[PAR_PRZE04] [numeric] (17,6) NULL ,
	[PAR_PRZE05] [numeric] (17,6) NULL ,
	[PAR_PRZE06] [numeric] (17,6) NULL ,
	[PAR_PRZE07] [numeric] (17,6) NULL ,
	[PAR_PRZE08] [numeric] (17,6) NULL ,
	[PAR_PRZE09] [numeric] (17,6) NULL ,
	[PAR_PRZE10] [numeric] (17,6) NULL ,
	[PAR_PRZE11] [numeric] (17,6) NULL ,
	[PAR_PRZE12] [numeric] (17,6) NULL ,
	[PAR_PRZE13] [numeric] (17,6) NULL ,
	[PAR_PRZE14] [numeric] (17,6) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PAR_CT] WITH NOCHECK ADD
	CONSTRAINT [PK_U_PAR_CT] PRIMARY KEY  CLUSTERED
	(
		[id_unique]
	)  ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PAR_CT] WITH NOCHECK ADD
	CONSTRAINT [DF_U_PAR_CT_id_unique] DEFAULT (newid()) FOR [id_unique],
        CONSTRAINT [DF_U_PAR_CT_PAR_CODNAZ] DEFAULT ('') FOR [PAR_CODNAZ],
        CONSTRAINT [DF_U_PAR_CT_PAR_DESNAZ] DEFAULT ('') FOR [PAR_DESNAZ],
        CONSTRAINT [DF_U_PAR_CT_PAR_ZONA] DEFAULT ('') FOR [PAR_ZONA],
        CONSTRAINT [DF_U_PAR_CT_PAR_TIPTRA] DEFAULT ('') FOR [PAR_TIPTRA],
        CONSTRAINT [DF_U_PAR_CT_PAR_DESTRA] DEFAULT ('') FOR [PAR_DESTRA],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZITA] DEFAULT (0) FOR [PAR_PRZITA],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE01] DEFAULT (0) FOR [PAR_PRZE01],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE02] DEFAULT (0) FOR [PAR_PRZE02],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE03] DEFAULT (0) FOR [PAR_PRZE03],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE04] DEFAULT (0) FOR [PAR_PRZE04],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE05] DEFAULT (0) FOR [PAR_PRZE05],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE06] DEFAULT (0) FOR [PAR_PRZE06],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE07] DEFAULT (0) FOR [PAR_PRZE07],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE08] DEFAULT (0) FOR [PAR_PRZE08],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE09] DEFAULT (0) FOR [PAR_PRZE09],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE10] DEFAULT (0) FOR [PAR_PRZE10],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE11] DEFAULT (0) FOR [PAR_PRZE11],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE12] DEFAULT (0) FOR [PAR_PRZE12],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE13] DEFAULT (0) FOR [PAR_PRZE13],
	CONSTRAINT [DF_U_PAR_CT_PAR_PRZE14] DEFAULT (0) FOR [PAR_PRZE14]
GO







