if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PDA_TP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_PDA_TP]
GO

CREATE TABLE [dbo].[U_PDA_TP] (
	[id_unique] [uniqueidentifier] NOT NULL ,
	[ACCESSCODE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODMAG] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_UNIQUE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ANAART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[INV_SPESSO] [numeric](9, 0) NULL ,
	[INV_ALTEZZ] [numeric](7, 0) NULL ,
	[INV_LUNGHE] [numeric](8, 0) NULL ,
	[INV_UNIMIS] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[INV_GIACEN] [numeric](17, 2) NULL ,
	[INV_CODMAT] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[INV_CODCOL] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[ERROR] [bit] NULL ,
	[INV_FORNIT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[INV_DESFOR] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[INV_PRZCON] [numeric](20, 6) NULL ,
	[INV_DATAGG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_NUMIDE] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[MAG_ANNO] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[INV_FILA_N] [numeric](9, 0) NULL ,
	[INV_PIAN_N] [numeric](9, 0) NULL ,
	[INV_UBIC_N] [numeric](9, 0) NULL ,
	[INV_FILA_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[INV_PIAN_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[INV_UBIC_X] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ERRORTYPE] [varchar] (100) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[U_PDA_TP] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PDA_TP] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PDA_TP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PDA_TP_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PDA_TP_MAG_CODSOC] DEFAULT ('') FOR [MAG_CODSOC],
	CONSTRAINT [DF_U_PDA_TP_MAG_CODMAG] DEFAULT ('') FOR [MAG_CODMAG],
	CONSTRAINT [DF_U_PDA_TP_MAG_UNIQUE] DEFAULT ('') FOR [MAG_UNIQUE],
	CONSTRAINT [DF_U_PDA_TP_MAG_CODART] DEFAULT ('') FOR [MAG_CODART],
	CONSTRAINT [DF_U_PDA_TP_MAG_ANAART] DEFAULT ('') FOR [MAG_ANAART],
	CONSTRAINT [DF_U_PDA_TP_INV_SPESSO] DEFAULT (0) FOR [INV_SPESSO],
	CONSTRAINT [DF_U_PDA_TP_MAG_ALTEZZ] DEFAULT (0) FOR [INV_ALTEZZ],
	CONSTRAINT [DF_U_PDA_TP_MAG_LUNGHE] DEFAULT (8) FOR [INV_LUNGHE],
	CONSTRAINT [DF_U_PDA_TP_INV_UNIMIS] DEFAULT ('') FOR [INV_UNIMIS],
	CONSTRAINT [DF_U_PDA_TP_MAG_GIACEN] DEFAULT (0) FOR [INV_GIACEN],
	CONSTRAINT [DF_U_PDA_TP_INV_CODMAT] DEFAULT ('') FOR [INV_CODMAT],
	CONSTRAINT [DF_U_PDA_TP_INV_CODCOL] DEFAULT ('') FOR [INV_CODCOL],
	CONSTRAINT [DF_U_PDA_TP_ERROR] DEFAULT (0) FOR [ERROR],
	CONSTRAINT [DF_U_PDA_TP_INV_FORNIT] DEFAULT ('') FOR [INV_FORNIT],
	CONSTRAINT [DF_U_PDA_TP_INV_DESFOR] DEFAULT ('') FOR [INV_DESFOR],
	CONSTRAINT [DF_U_PDA_TP_INV_PRZCON] DEFAULT (0) FOR [INV_PRZCON],
	CONSTRAINT [DF_U_PDA_TP_INV_DATAAGG] DEFAULT ('') FOR [INV_DATAGG],
	CONSTRAINT [DF_U_PDA_TP_INV_NUMIDE] DEFAULT ('') FOR [MAG_NUMIDE],
	CONSTRAINT [DF_U_PDA_TP_MAG_ANNO] DEFAULT ('') FOR [MAG_ANNO],
	CONSTRAINT [DF_U_PDA_TP_INV_FILA_N] DEFAULT (0) FOR [INV_FILA_N],
	CONSTRAINT [DF_U_PDA_TP_INV_FILA_N1] DEFAULT (0) FOR [INV_PIAN_N],
	CONSTRAINT [DF_U_PDA_TP_INV_FILA_N2] DEFAULT (0) FOR [INV_UBIC_N],
	CONSTRAINT [DF_U_PDA_TP_INV_FILA_X] DEFAULT ('') FOR [INV_FILA_X],
	CONSTRAINT [DF_U_PDA_TP_INV_PIAN_X] DEFAULT ('') FOR [INV_PIAN_X],
	CONSTRAINT [DF_U_PDA_TP_INV_UBIC_X] DEFAULT ('') FOR [INV_UBIC_X],
	CONSTRAINT [DF_U_PDA_TP_ERRORTYPE] DEFAULT ('') FOR [ERRORTYPE]
GO

