if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PES_VE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_PES_VE]
GO

CREATE TABLE [dbo].[U_PES_VE] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
        [PES_CODVET] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PES_DESVET] [varchar] (60) COLLATE Latin1_General_CI_AS NULL ,
	[PES_RNGDA1] [numeric] (7,2) NULL ,
	[PES_RNGAL1] [numeric] (7,2) NULL ,
	[PES_RNGDA2] [numeric] (7,2) NULL ,
	[PES_RNGAL2] [numeric] (7,2) NULL ,
	[PES_RNGDA3] [numeric] (7,2) NULL ,
	[PES_RNGAL3] [numeric] (7,2) NULL ,
	[PES_RNGDA4] [numeric] (7,2) NULL ,
	[PES_RNGAL4] [numeric] (7,2) NULL ,
	[PES_RNGDA5] [numeric] (7,2) NULL ,
	[PES_RNGAL5] [numeric] (7,2) NULL ,
	[PES_RNGDA6] [numeric] (7,2) NULL ,
	[PES_RNGAL6] [numeric] (7,2) NULL ,
	[PES_RNGDA7] [numeric] (7,2) NULL ,
	[PES_RNGAL7] [numeric] (7,2) NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PES_VE] WITH NOCHECK ADD
	CONSTRAINT [PK_U_PES_VE] PRIMARY KEY  CLUSTERED
	(
		[id_unique]
	)  ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PES_VE] WITH NOCHECK ADD
	CONSTRAINT [DF_U_PES_VE_id_unique] DEFAULT (newid()) FOR [id_unique],
        CONSTRAINT [DF_U_PES_VE_PES_CODVET] DEFAULT ('') FOR [PES_CODVET],
        CONSTRAINT [DF_U_PES_VE_PES_DESVET] DEFAULT ('') FOR [PES_DESVET],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA1] DEFAULT (0) FOR [PES_RNGDA1],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL1] DEFAULT (0) FOR [PES_RNGAL1],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA2] DEFAULT (0) FOR [PES_RNGDA2],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL2] DEFAULT (0) FOR [PES_RNGAL2],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA3] DEFAULT (0) FOR [PES_RNGDA3],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL3] DEFAULT (0) FOR [PES_RNGAL3],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA4] DEFAULT (0) FOR [PES_RNGDA4],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL4] DEFAULT (0) FOR [PES_RNGAL4],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA5] DEFAULT (0) FOR [PES_RNGDA5],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL5] DEFAULT (0) FOR [PES_RNGAL5],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA6] DEFAULT (0) FOR [PES_RNGDA6],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL6] DEFAULT (0) FOR [PES_RNGAL6],
	CONSTRAINT [DF_U_PES_VE_PES_RNGDA7] DEFAULT (0) FOR [PES_RNGDA7],
	CONSTRAINT [DF_U_PES_VE_PES_RNGAL7] DEFAULT (0) FOR [PES_RNGAL7]
GO







