if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_CT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_CT]
GO

CREATE TABLE [dbo].[U_PRD_CT] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[TAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL,
	[PTT_NUMPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[PTT_DATPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[PTT_CODADE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
	[PTT_DESADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
	[PTT_TOTMTL] [numeric] (10,2) NULL,
	[PTT_TOTMTQ] [numeric] (10,2) NULL,
	[PTT_TOTMIN] [numeric] (10,2) NULL,
	[PTT_TOTORE] [numeric] (10,2) NULL,
	[PTT_TOTFOR] [numeric] (10,2) NULL,
	[PTT_TOTDIL] [numeric] (10,2) NULL,
	[PTT_TOTRET] [numeric] (10,2) NULL,
	[PTT_NOTE] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_CT] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_CT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_CT] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_CT_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_CT_TAGGANCIO] DEFAULT ('') FOR [TAGGANCIO],
	CONSTRAINT [DF_U_PRD_CT_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_CT_PTT_NUMPRG] DEFAULT ('') FOR [PTT_NUMPRG],
	CONSTRAINT [DF_U_PRD_CT_PTT_DATPRG] DEFAULT ('') FOR [PTT_DATPRG],
	CONSTRAINT [DF_U_PRD_CT_PTT_CODADE] DEFAULT ('') FOR [PTT_CODADE],
	CONSTRAINT [DF_U_PRD_CT_PTT_DESADE] DEFAULT ('') FOR [PTT_DESADE],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTMTL] DEFAULT (0) FOR [PTT_TOTMTL],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTMTQ] DEFAULT (0) FOR [PTT_TOTMTQ],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTMIN] DEFAULT (0) FOR [PTT_TOTMIN],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTORE] DEFAULT (0) FOR [PTT_TOTORE],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTFOR] DEFAULT (0) FOR [PTT_TOTFOR],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTDIL] DEFAULT (0) FOR [PTT_TOTDIL],
	CONSTRAINT [DF_U_PRD_CT_PTT_TOTRET] DEFAULT (0) FOR [PTT_TOTRET]
GO
