if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_D3]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_D3]
GO

CREATE TABLE [dbo].[U_PRD_D3] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD2] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD3] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_UNIMIS] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_CODBOB] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_DESBOB] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_ALTEZZ] [numeric](5,0) NULL ,
	[PR3_LUNGHE] [numeric](6,0) NULL ,
	[PR3_SPESSO] [numeric](3,0) NULL ,
	[PR3_CODINT] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_ALTCAR] [numeric](5,0) NULL ,
	[PR3_LUNCAR] [numeric](6,0) NULL ,
	[PR3_SPECAR] [numeric](3,0) NULL ,
	[PR3_CODADE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_DESADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_CDADIN] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR3_QUANTI] [numeric](17,6) NULL ,
	[PR3_QTACAR] [numeric](17,6) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_D3] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_D3] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_D3] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D3_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_D3_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_D3_PJ_PRGPRD2] DEFAULT ('') FOR [PJ_PRGPRD2],
	CONSTRAINT [DF_U_PRD_D3_PJ_PRGPRD3] DEFAULT ('') FOR [PJ_PRGPRD3],
	CONSTRAINT [DF_U_PRD_D3_PR3_CODART] DEFAULT ('') FOR [PR3_CODART],
	CONSTRAINT [DF_U_PRD_D3_PR3_DESART] DEFAULT ('') FOR [PR3_DESART],
	CONSTRAINT [DF_U_PRD_D3_PR3_UNIMIS] DEFAULT ('') FOR [PR3_UNIMIS],
	CONSTRAINT [DF_U_PRD_D3_PR3_CODBOB] DEFAULT ('') FOR [PR3_CODBOB],
	CONSTRAINT [DF_U_PRD_D3_PR3_DESBOB] DEFAULT ('') FOR [PR3_DESBOB],
	CONSTRAINT [DF_U_PRD_D3_PR3_ALTEZZ] DEFAULT ('') FOR [PR3_ALTEZZ],
	CONSTRAINT [DF_U_PRD_D3_PR3_LUNGHE] DEFAULT ('') FOR [PR3_LUNGHE],
	CONSTRAINT [DF_U_PRD_D3_PR3_SPESSO] DEFAULT ('') FOR [PR3_SPESSO],
	CONSTRAINT [DF_U_PRD_D3_PR3_CODINT] DEFAULT ('') FOR [PR3_CODINT],
	CONSTRAINT [DF_U_PRD_D3_PR3_ALTCAR] DEFAULT ('') FOR [PR3_ALTCAR],
	CONSTRAINT [DF_U_PRD_D3_PR3_LUNCAR] DEFAULT ('') FOR [PR3_LUNCAR],
	CONSTRAINT [DF_U_PRD_D3_PR3_SPECAR] DEFAULT ('') FOR [PR3_SPECAR],
	CONSTRAINT [DF_U_PRD_D3_PR3_CODADE] DEFAULT ('') FOR [PR3_CODADE],
	CONSTRAINT [DF_U_PRD_D3_PR3_DESADE] DEFAULT ('') FOR [PR3_DESADE],
	CONSTRAINT [DF_U_PRD_D3_PR3_CDADIN] DEFAULT ('') FOR [PR3_CDADIN],
	CONSTRAINT [DF_U_PRD_D3_PR3_QUANTI] DEFAULT ('') FOR [PR3_QUANTI],
	CONSTRAINT [DF_U_PRD_D3_PR3_QTACAR] DEFAULT ('') FOR [PR3_QTACAR]
GO

