if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_DR]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_DR]
GO

CREATE TABLE [dbo].[U_PRD_DR] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD2] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD3] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD4] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRDR] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_UNIMIS] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_PROGRE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_ALTEZZ] [numeric](5,0) NULL ,
	[PRR_LUNGHE] [numeric](6,0) NULL ,
	[PRR_SPESSO] [numeric](3,0) NULL ,
	[PRR_CODINT] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_ALTCAR] [numeric](5,0) NULL ,
	[PRR_LUNCAR] [numeric](6,0) NULL ,
	[PRR_SPECAR] [numeric](3,0) NULL ,
	[PRR_DATAVA] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_ORAAVA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_CODEVE] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_QUALIT] [numeric](1,0) NULL ,
	[PRR_GRAMMA] [numeric](17,6) NULL ,
	[PRR_NRTTAG] [numeric](10,0) NULL ,
	[PRR_FORTAG] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PRR_RIBOBI] [bit] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_DR] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_DR] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_DR_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_DR_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_DR_PJ_PRGPRD2] DEFAULT ('') FOR [PJ_PRGPRD2],
	CONSTRAINT [DF_U_PRD_DR_PJ_PRGPRD3] DEFAULT ('') FOR [PJ_PRGPRD3],
	CONSTRAINT [DF_U_PRD_DR_PJ_PRGPRD4] DEFAULT ('') FOR [PJ_PRGPRD4],
	CONSTRAINT [DF_U_PRD_DR_PJ_PRGPRDR] DEFAULT ('') FOR [PJ_PRGPRDR],
	CONSTRAINT [DF_U_PRD_DR_PRR_CODART] DEFAULT ('') FOR [PRR_CODART],
	CONSTRAINT [DF_U_PRD_DR_PRR_DESART] DEFAULT ('') FOR [PRR_DESART],
	CONSTRAINT [DF_U_PRD_DR_PRR_UNIMIS] DEFAULT ('') FOR [PRR_UNIMIS],
	CONSTRAINT [DF_U_PRD_DR_PRR_PROGRE] DEFAULT ('') FOR [PRR_PROGRE],
	CONSTRAINT [DF_U_PRD_DR_PRR_ALTEZZ] DEFAULT (0) FOR [PRR_ALTEZZ],
	CONSTRAINT [DF_U_PRD_DR_PRR_LUNGHE] DEFAULT (0) FOR [PRR_LUNGHE],
	CONSTRAINT [DF_U_PRD_DR_PRR_SPESSO] DEFAULT (0) FOR [PRR_SPESSO],
	CONSTRAINT [DF_U_PRD_DR_PRR_CODINT] DEFAULT ('') FOR [PRR_CODINT],
	CONSTRAINT [DF_U_PRD_DR_PRR_ALTCAR] DEFAULT (0) FOR [PRR_ALTCAR],
	CONSTRAINT [DF_U_PRD_DR_PRR_LUNCAR] DEFAULT (0) FOR [PRR_LUNCAR],
	CONSTRAINT [DF_U_PRD_DR_PRR_SPECAR] DEFAULT (0) FOR [PRR_SPECAR],
	CONSTRAINT [DF_U_PRD_DR_PRR_DATAVA] DEFAULT ('') FOR [PRR_DATAVA],
	CONSTRAINT [DF_U_PRD_DR_PRR_ORAAVA] DEFAULT ('') FOR [PRR_ORAAVA],
	CONSTRAINT [DF_U_PRD_DR_PRR_CODEVE] DEFAULT ('') FOR [PRR_CODEVE],
	CONSTRAINT [DF_U_PRD_DR_PRR_QUALIT] DEFAULT (0) FOR [PRR_QUALIT],
	CONSTRAINT [DF_U_PRD_DR_PRR_GRAMMA] DEFAULT (0) FOR [PRR_GRAMMA],
	CONSTRAINT [DF_U_PRD_DR_PRR_NRTTAG] DEFAULT (0) FOR [PRR_NRTTAG],
	CONSTRAINT [DF_U_PRD_DR_PRR_FORTAG] DEFAULT ('') FOR [PRR_FORTAG],
	CONSTRAINT [DF_U_PRD_DR_PRR_RIBOBI] DEFAULT (0) FOR [PRR_RIBOBI]
GO
