if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_D1]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_D1]
GO

CREATE TABLE [dbo].[U_PRD_D1] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_NUMPIA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DATPIA] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_NUMPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DATPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DTINPR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DTFIPR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DTINEF] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DTFIEF] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_NOTE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[PR1_OPEINS] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DATINS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_OPEMOD] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_DATMOD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[SELEZIONE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[PR1_FLGCON] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_D1] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_D1] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_D1] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D1_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_D1_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_D1_PR1_NUMPIA] DEFAULT ('') FOR [PR1_NUMPIA],
	CONSTRAINT [DF_U_PRD_D1_PR1_DATPIA] DEFAULT ('') FOR [PR1_DATPIA],
	CONSTRAINT [DF_U_PRD_D1_PR1_NUMPRG] DEFAULT ('') FOR [PR1_NUMPRG],
	CONSTRAINT [DF_U_PRD_D1_PR1_DATPRG] DEFAULT ('') FOR [PR1_DATPRG],
	CONSTRAINT [DF_U_PRD_D1_PR1_DTINPR] DEFAULT ('') FOR [PR1_DTINPR],
	CONSTRAINT [DF_U_PRD_D1_PR1_DTFIPR] DEFAULT ('') FOR [PR1_DTFIPR],
	CONSTRAINT [DF_U_PRD_D1_PR1_DTINEF] DEFAULT ('') FOR [PR1_DTINEF],
	CONSTRAINT [DF_U_PRD_D1_PR1_DTFIEF] DEFAULT ('') FOR [PR1_DTFIEF],
	CONSTRAINT [DF_U_PRD_D1_PR1_NOTE] DEFAULT ('') FOR [PR1_NOTE],
	CONSTRAINT [DF_U_PRD_D1_PR1_OPEINS] DEFAULT ('') FOR [PR1_OPEINS],
	CONSTRAINT [DF_U_PRD_D1_PR1_DATINS] DEFAULT ('') FOR [PR1_DATINS],
	CONSTRAINT [DF_U_PRD_D1_PR1_OPEMOD] DEFAULT ('') FOR [PR1_OPEMOD],
	CONSTRAINT [DF_U_PRD_D1_PR1_DATMOD] DEFAULT ('') FOR [PR1_DATMOD],
	CONSTRAINT [DF_U_PRD_D1_SELEZIONE] DEFAULT ('') FOR [SELEZIONE],
	CONSTRAINT [DF_U_PRD_D1_PR1_FLGCON] DEFAULT (0) FOR [PR1_FLGCON]
GO

