if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_CD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_CD]
GO

CREATE TABLE [dbo].[U_PRD_CD] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[DAGGANCIO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
	[PDD_CONSAD] [numeric] (10,2) NULL,
	[PDD_SECCO] [numeric] (10,2) NULL,
	[PDD_ADEFOR] [numeric] (10,2) NULL,
	[PDD_H2OADE] [numeric] (10,2) NULL,
	[PDD_ADEDIL] [numeric] (10,2) NULL,
	[PDD_FASCIA] [numeric] (5,0) NULL,
	[PDD_SPESSO] [numeric] (3,0) NULL,
	[PDD_GRUPRD] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
	[PDD_NUMBOB] [numeric] (5,0) NULL,
	[PDD_LUNBOB] [numeric] (6,0) NULL,
	[PDD_VELMAC] [numeric] (5,0) NULL,
	[PDD_TOTMTL] [numeric] (10,2) NULL,
	[PDD_TOTMTQ] [numeric] (10,2) NULL,
	[PDD_TEMLAV] [numeric] (10,2) NULL,
	[PDD_PRODUZ] [numeric] (10,2) NULL,
	[PDD_ADEFKG] [numeric] (10,2) NULL,
	[PDD_ADEDKG] [numeric] (10,2) NULL,
	[PDD_H2OFKG] [numeric] (10,2) NULL,
	[PDD_RETICO] [numeric] (10,2) NULL,
	[PDD_TOTFOR] [numeric] (10,2) NULL,
	[PDD_TOTDIL] [numeric] (10,2) NULL,
	[PDD_TOTRET] [numeric] (10,2) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_CD] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_CD] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_CD] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_CD_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_CD_DAGGANCIO] DEFAULT ('') FOR [DAGGANCIO],
	CONSTRAINT [DF_U_PRD_CD_PDD_CONSAD] DEFAULT (0) FOR [PDD_CONSAD],
	CONSTRAINT [DF_U_PRD_CD_PDD_SECCO] DEFAULT (0) FOR [PDD_SECCO],
	CONSTRAINT [DF_U_PRD_CD_PDD_ADEFOR] DEFAULT (0) FOR [PDD_ADEFOR],
	CONSTRAINT [DF_U_PRD_CD_PDD_H2OADE] DEFAULT (0) FOR [PDD_H2OADE],
	CONSTRAINT [DF_U_PRD_CD_PDD_ADEDIL] DEFAULT (0) FOR [PDD_ADEDIL],
	CONSTRAINT [DF_U_PRD_CD_PDD_FASCIA] DEFAULT (0) FOR [PDD_FASCIA],
	CONSTRAINT [DF_U_PRD_CD_PDD_SPESSO] DEFAULT (0) FOR [PDD_SPESSO],
	CONSTRAINT [DF_U_PRD_CD_PDD_GRUPRD] DEFAULT ('') FOR [PDD_GRUPRD],
	CONSTRAINT [DF_U_PRD_CD_PDD_NUMBOB] DEFAULT (0) FOR [PDD_NUMBOB],
	CONSTRAINT [DF_U_PRD_CD_PDD_LUNBOB] DEFAULT (0) FOR [PDD_LUNBOB],
	CONSTRAINT [DF_U_PRD_CD_PDD_VELMAC] DEFAULT (0) FOR [PDD_VELMAC],
	CONSTRAINT [DF_U_PRD_CD_PDD_TOTMTL] DEFAULT (0) FOR [PDD_TOTMTL],
	CONSTRAINT [DF_U_PRD_CD_PDD_TOTMTQ] DEFAULT (0) FOR [PDD_TOTMTQ],
	CONSTRAINT [DF_U_PRD_CD_PDD_TEMLAV] DEFAULT (0) FOR [PDD_TEMLAV],
	CONSTRAINT [DF_U_PRD_CD_PDD_PRODUZ] DEFAULT (0) FOR [PDD_PRODUZ],
	CONSTRAINT [DF_U_PRD_CD_PDD_ADEFKG] DEFAULT (0) FOR [PDD_ADEFKG],
	CONSTRAINT [DF_U_PRD_CD_PDD_ADEDKG] DEFAULT (0) FOR [PDD_ADEDKG],
	CONSTRAINT [DF_U_PRD_CD_PDD_H2OFKG] DEFAULT (0) FOR [PDD_H2OFKG],
	CONSTRAINT [DF_U_PRD_CD_PDD_RETICO] DEFAULT (0) FOR [PDD_RETICO],
	CONSTRAINT [DF_U_PRD_CD_PDD_TOTFOR] DEFAULT (0) FOR [PDD_TOTFOR],
	CONSTRAINT [DF_U_PRD_CD_PDD_TOTDIL] DEFAULT (0) FOR [PDD_TOTDIL],
	CONSTRAINT [DF_U_PRD_CD_PDD_TOTRET] DEFAULT (0) FOR [PDD_TOTRET]
GO
