if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_D5]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_D5]
GO

CREATE TABLE [dbo].[U_PRD_D5] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD2] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD3] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD4] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD5] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_UNIMIS] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_PROGRE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_CODINT] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_RAGSOC] [varchar] (80) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_NUMORD] [varchar] (06) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_DATORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_ALTEZZ] [numeric](5,0) NULL ,
	[PR5_LUNGHE] [numeric](6,0) NULL ,
	[PR5_SPESSO] [numeric](3,0) NULL ,
	[PR5_ALTTAG] [numeric](5,0) NULL ,
	[PR5_LUNTAG] [numeric](6,0) NULL ,
	[PR5_SPETAG] [numeric](3,0) NULL ,
	[PR5_DATAVA] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_ORAAVA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_CODEVE] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_DATCON] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[PR5_DTCON2] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_D5] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_D5] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D5_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_D5_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_D5_PJ_PRGPRD2] DEFAULT ('') FOR [PJ_PRGPRD2],
	CONSTRAINT [DF_U_PRD_D5_PJ_PRGPRD3] DEFAULT ('') FOR [PJ_PRGPRD3],
	CONSTRAINT [DF_U_PRD_D5_PJ_PRGPRD4] DEFAULT ('') FOR [PJ_PRGPRD4],
	CONSTRAINT [DF_U_PRD_D5_PJ_PRGPRD5] DEFAULT ('') FOR [PJ_PRGPRD5],
	CONSTRAINT [DF_U_PRD_D5_PR5_CODART] DEFAULT ('') FOR [PR5_CODART],
	CONSTRAINT [DF_U_PRD_D5_PR5_DESART] DEFAULT ('') FOR [PR5_DESART],
	CONSTRAINT [DF_U_PRD_D5_PR5_UNIMIS] DEFAULT ('') FOR [PR5_UNIMIS],
	CONSTRAINT [DF_U_PRD_D5_PR5_PROGRE] DEFAULT ('') FOR [PR5_PROGRE],
	CONSTRAINT [DF_U_PRD_D5_PR5_CODINT] DEFAULT ('') FOR [PR5_CODINT],
	CONSTRAINT [DF_U_PRD_D5_PR5_CODCLI] DEFAULT ('') FOR [PR5_CODCLI],
	CONSTRAINT [DF_U_PRD_D5_PR5_RAGSOC] DEFAULT ('') FOR [PR5_RAGSOC],
	CONSTRAINT [DF_U_PRD_D5_PR5_NUMORD] DEFAULT ('') FOR [PR5_NUMORD],
	CONSTRAINT [DF_U_PRD_D5_PR5_DATORD] DEFAULT ('') FOR [PR5_DATORD],
	CONSTRAINT [DF_U_PRD_D5_PR5_ALTEZZ] DEFAULT (0) FOR [PR5_ALTEZZ],
	CONSTRAINT [DF_U_PRD_D5_PR5_LUNGHE] DEFAULT (0) FOR [PR5_LUNGHE],
	CONSTRAINT [DF_U_PRD_D5_PR5_SPESSO] DEFAULT (0) FOR [PR5_SPESSO],
	CONSTRAINT [DF_U_PRD_D5_PR5_ALTTAG] DEFAULT (0) FOR [PR5_ALTTAG],
	CONSTRAINT [DF_U_PRD_D5_PR5_LUNTAG] DEFAULT (0) FOR [PR5_LUNTAG],
	CONSTRAINT [DF_U_PRD_D5_PR5_SPETAG] DEFAULT (0) FOR [PR5_SPETAG],
	CONSTRAINT [DF_U_PRD_D5_PR5_DATAVA] DEFAULT ('') FOR [PR5_DATAVA],
	CONSTRAINT [DF_U_PRD_D5_PR5_ORAAVA] DEFAULT ('') FOR [PR5_ORAAVA],
	CONSTRAINT [DF_U_PRD_D5_PR5_CODEVE] DEFAULT ('') FOR [PR5_CODEVE],
	CONSTRAINT [DF_U_PRD_D5_PR5_DATCON] DEFAULT ('') FOR [PR5_DATCON],
	CONSTRAINT [DF_U_PRD_D5_PR5_DTCON2] DEFAULT ('') FOR [PR5_DTCON2]
GO
