if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_HY]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_HY]
GO

CREATE TABLE [dbo].[U_PRD_HY] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[HY_TIPO] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[NUMORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DTCONS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAGSOC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[CODCLI] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DATORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[QTA] [NUMERIC] (5,0)  NULL ,
	[ALTEZ] [numeric] (5,0)  NULL ,
	[LUNGH] [numeric] (5,0)  NULL ,
	[SPESS] [numeric] (5,0)  NULL ,
	[ID_ROTOLO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[ID] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[SEZIONE] [numeric] (5,0)  NULL ,
	[BOBINA] [numeric] (5,0)  NULL ,
	[NUMSEZRAGG] [numeric] (5,0)  NULL ,
	[SEZINI] [numeric] (5,0)  NULL ,
	[SEZFIN] [numeric] (5,0)  NULL ,
	[NUMBARRE] [numeric] (5,0)  NULL ,
	[XCOORD0] [numeric] (5,0)  NULL ,
	[XCOORD1] [numeric] (5,0)  NULL ,
	[YCOORD0] [numeric] (5,0)  NULL ,
	[CESTINO] [bit] NULL,
	[FLGMULTI] [bit] NULL,
	[FLGVIEW] [bit] NULL,
	[PATTERN] [varchar] (254) COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_HY] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_HY] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_HY] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_HY_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_HY_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_HY_HY_TIPO] DEFAULT ('') FOR [HY_TIPO],
	CONSTRAINT [DF_U_PRD_HY_NUMORD] DEFAULT ('') FOR [NUMORD],
	CONSTRAINT [DF_U_PRD_HY_DTCONS] DEFAULT ('') FOR [DTCONS],
	CONSTRAINT [DF_U_PRD_HY_RAGSOC] DEFAULT ('') FOR [RAGSOC],
	CONSTRAINT [DF_U_PRD_HY_CODCLI] DEFAULT ('') FOR [CODCLI],
	CONSTRAINT [DF_U_PRD_HY_DATORD] DEFAULT ('') FOR [DATORD],
	CONSTRAINT [DF_U_PRD_HY_QTA] DEFAULT (0) FOR [QTA],
	CONSTRAINT [DF_U_PRD_HY_ALTEZ] DEFAULT (0) FOR [ALTEZ],
	CONSTRAINT [DF_U_PRD_HY_LUNGH] DEFAULT (0) FOR [LUNGH],
	CONSTRAINT [DF_U_PRD_HY_SPESS] DEFAULT (0) FOR [SPESS],
	CONSTRAINT [DF_U_PRD_HY_ID_ROTOLO] DEFAULT ('') FOR [ID_ROTOLO],
	CONSTRAINT [DF_U_PRD_HY_ID] DEFAULT ('') FOR [ID],
	CONSTRAINT [DF_U_PRD_HY_SEZIONE] DEFAULT (0) FOR [SEZIONE],
	CONSTRAINT [DF_U_PRD_HY_BOBINA] DEFAULT (0) FOR [BOBINA],
	CONSTRAINT [DF_U_PRD_HY_NUMSEZRAGG] DEFAULT (0) FOR [NUMSEZRAGG],
	CONSTRAINT [DF_U_PRD_HY_SEZINI] DEFAULT (0) FOR [SEZINI],
	CONSTRAINT [DF_U_PRD_HY_SEZFIN] DEFAULT (0) FOR [SEZFIN],
	CONSTRAINT [DF_U_PRD_HY_NUMBARRE] DEFAULT (0) FOR [NUMBARRE],
	CONSTRAINT [DF_U_PRD_HY_XCOORD0] DEFAULT (0) FOR [XCOORD0],
	CONSTRAINT [DF_U_PRD_HY_XCOORD1] DEFAULT (0) FOR [XCOORD1],
	CONSTRAINT [DF_U_PRD_HY_YCOORD0] DEFAULT (0) FOR [YCOORD0],
	CONSTRAINT [DF_U_PRD_HY_CESTINO] DEFAULT (0) FOR [CESTINO],
	CONSTRAINT [DF_U_PRD_HY_FLGMULTI] DEFAULT (0) FOR [FLGMULTI],
	CONSTRAINT [DF_U_PRD_HY_FLGVIEW] DEFAULT (0) FOR [FLGVIEW],
	CONSTRAINT [DF_U_PRD_HY_PATTERN] DEFAULT ('') FOR [PATTERN]
GO

