if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_PRD_D2]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_PRD_D2]
GO

CREATE TABLE [dbo].[U_PRD_D2] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PJ_PRGPRD1] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PJ_PRGPRD2] [varchar] (32) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_UNIMIS] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_SEQUEN] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_NUMBOB] [numeric](10,0) NULL ,
	[PR2_FASCIA] [numeric](5,0) NULL ,
	[PR2_SPEBOB] [numeric](3,0) NULL ,
	[PR2_CLIENT] [text] COLLATE Latin1_General_CI_AS NULL ,
	[PR2_CODADE] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_DESADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_FORMUL] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[PR2_GRAMMA] [numeric](17,6) NULL ,
	[PR2_DBARRE] [text] COLLATE Latin1_General_CI_AS NULL ,
	[PR2_DATSEQ] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_PRD_D2] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_PRD_D2] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_PRD_D2_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_PRD_D2_PJ_PRGPRD1] DEFAULT ('') FOR [PJ_PRGPRD1],
	CONSTRAINT [DF_U_PRD_D2_PJ_PRGPRD2] DEFAULT ('') FOR [PJ_PRGPRD2],
	CONSTRAINT [DF_U_PRD_D2_PR2_CODART] DEFAULT ('') FOR [PR2_CODART],
	CONSTRAINT [DF_U_PRD_D2_PR2_DESART] DEFAULT ('') FOR [PR2_DESART],
	CONSTRAINT [DF_U_PRD_D2_PR2_UNIMIS] DEFAULT ('') FOR [PR2_UNIMIS],
	CONSTRAINT [DF_U_PRD_D2_PR2_SEQUEN] DEFAULT ('') FOR [PR2_SEQUEN],
	CONSTRAINT [DF_U_PRD_D2_PR2_NUMBOB] DEFAULT (0) FOR [PR2_NUMBOB],
	CONSTRAINT [DF_U_PRD_D2_PR2_FASCIA] DEFAULT (0) FOR [PR2_FASCIA],
	CONSTRAINT [DF_U_PRD_D2_PR2_SPEBOB] DEFAULT (0) FOR [PR2_SPEBOB],
	CONSTRAINT [DF_U_PRD_D2_PR2_CLIENT] DEFAULT ('') FOR [PR2_CLIENT],
	CONSTRAINT [DF_U_PRD_D2_PR2_CODADE] DEFAULT ('') FOR [PR2_CODADE],
	CONSTRAINT [DF_U_PRD_D2_PR2_DESADE] DEFAULT ('') FOR [PR2_DESADE],
	CONSTRAINT [DF_U_PRD_D2_PR2_FORMUL] DEFAULT ('') FOR [PR2_FORMUL],
	CONSTRAINT [DF_U_PRD_D2_PR2_GRAMMA] DEFAULT (0) FOR [PR2_GRAMMA],
	CONSTRAINT [DF_U_PRD_D2_PR2_DBARRE] DEFAULT ('') FOR [PR2_DBARRE],
	CONSTRAINT [DF_U_PRD_D2_PR2_DATSEQ] DEFAULT ('') FOR [PR2_DATSEQ]
GO

