if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_QUO_AM]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_QUO_AM]
GO
 
CREATE TABLE [dbo].[U_QUO_AM] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[QUO_CODCES] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[QUO_DESCES] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[QUO_CODCAT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[QUO_DESCAT] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[QUO_ANNRIF] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[QUO_VALSTO] [numeric] (15,2) NULL ,
	[QUO_PERORD] [numeric] (6,2) NULL ,
	[QUO_VALORD] [numeric] (15,2) NULL ,
	[QUO_FONORD] [numeric] (15,2) NULL ,
	[QUO_PERANT] [numeric] (6,2) NULL ,
	[QUO_VALANT] [numeric] (15,2) NULL ,
	[QUO_FONANT] [numeric] (15,2) NULL ,
	[QUO_PERACC] [numeric] (6,2) NULL ,
	[QUO_VALACC] [numeric] (15,2) NULL ,
	[QUO_FONACC] [numeric] (15,2) NULL ,
	[QUO_TOTAMM] [numeric] (15,2) NULL ,
	[QUO_VALRES] [numeric] (15,2) NULL ,
	[QUO_VARFIS] [numeric] (15,2) NULL ,
	[QUO_IMPDIF] [numeric] (15,2) NULL ,
	[QUO_FLGCGE] [bit] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_QUO_AM] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_QUO_AM] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_QUO_AM] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_QUO_AM_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_QUO_AM_QUO_CODCES] DEFAULT ('') FOR [QUO_CODCES],
	CONSTRAINT [DF_U_QUO_AM_QUO_DESCES] DEFAULT ('') FOR [QUO_DESCES],
	CONSTRAINT [DF_U_QUO_AM_QUO_CODCAT] DEFAULT ('') FOR [QUO_CODCAT],
	CONSTRAINT [DF_U_QUO_AM_QUO_DESCAT] DEFAULT ('') FOR [QUO_DESCAT],
	CONSTRAINT [DF_U_QUO_AM_QUO_ANNRIF] DEFAULT ('') FOR [QUO_ANNRIF],
	CONSTRAINT [DF_U_QUO_AM_QUO_VALSTO] DEFAULT (0) FOR [QUO_VALSTO],
	CONSTRAINT [DF_U_QUO_AM_QUO_PERORD] DEFAULT (0) FOR [QUO_PERORD],
	CONSTRAINT [DF_U_QUO_AM_QUO_VALORD] DEFAULT (0) FOR [QUO_VALORD],
	CONSTRAINT [DF_U_QUO_AM_QUO_FONORD] DEFAULT (0) FOR [QUO_FONORD],
	CONSTRAINT [DF_U_QUO_AM_QUO_PERANT] DEFAULT (0) FOR [QUO_PERANT],
	CONSTRAINT [DF_U_QUO_AM_QUO_VALANT] DEFAULT (0) FOR [QUO_VALANT],
	CONSTRAINT [DF_U_QUO_AM_QUO_FONANT] DEFAULT (0) FOR [QUO_FONANT],
	CONSTRAINT [DF_U_QUO_AM_QUO_PERACC] DEFAULT (0) FOR [QUO_PERACC],
	CONSTRAINT [DF_U_QUO_AM_QUO_VALACC] DEFAULT (0) FOR [QUO_VALACC],
	CONSTRAINT [DF_U_QUO_AM_QUO_FONACC] DEFAULT (0) FOR [QUO_FONACC],
	CONSTRAINT [DF_U_QUO_AM_QUO_TOTAMM] DEFAULT (0) FOR [QUO_TOTAMM],
	CONSTRAINT [DF_U_QUO_AM_QUO_VALRES] DEFAULT (0) FOR [QUO_VALRES],
	CONSTRAINT [DF_U_QUO_AM_QUO_VARFIS] DEFAULT (0) FOR [QUO_VARFIS],
	CONSTRAINT [DF_U_QUO_AM_QUO_IMPDIF] DEFAULT (0) FOR [QUO_IMPDIF],
	CONSTRAINT [DF_U_QUO_AM_QUO_FLGCGE] DEFAULT (0) FOR [QUO_FLGCGE]
GO

