if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_RAP_SP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_RAP_SP]
GO
 
CREATE TABLE [dbo].[U_RAP_SP] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
        [RAP_CODSOC] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_NUMPRG] [varchar] (6) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DATPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_AMGPRG] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_PROGRE] [numeric] (10,0) NULL ,
	[RAP_TEMPB1] [numeric] (3,0) NULL ,
	[RAP_TEMPB2] [numeric] (3,0) NULL ,
	[RAP_TEMPB3] [numeric] (3,0) NULL ,
	[RAP_POSMF1] [numeric] (1,0) NULL ,
	[RAP_POSMF2] [numeric] (1,0) NULL ,
	[RAP_POSMF3] [numeric] (1,0) NULL ,
	[RAP_POSMF4] [numeric] (1,0) NULL ,
	[RAP_POSMF5] [numeric] (1,0) NULL ,
	[RAP_GRADF1] [numeric] (3,0) NULL ,
	[RAP_GRADF2] [numeric] (3,0) NULL ,
	[RAP_GRADF3] [numeric] (3,0) NULL ,
	[RAP_GRADF4] [numeric] (3,0) NULL ,
	[RAP_GRADF5] [numeric] (3,0) NULL ,
	[RAP_GRADF6] [numeric] (3,0) NULL ,
	[RAP_GRADF7] [numeric] (3,0) NULL ,
	[RAP_GRADF8] [numeric] (3,0) NULL ,
	[RAP_VELSPA] [numeric] (3,0) NULL ,
	[RAP_VELLIN] [numeric] (3,0) NULL ,
	[RAP_TIRO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DINPRO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_OINPRO] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DFIPRO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_OFIPRO] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DINTPR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_OINTPR] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_OFIINT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_MTLSUP] [numeric] (6,0) NULL ,
	[RAP_MTLSPA] [numeric] (6,0) NULL ,
	[RAP_MQTOT] [numeric] (6,0) NULL ,
	[RAP_ADESIV] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_PHADE] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_RESSEC] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_VISFRD] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_GRAMMA] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_SPESSO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_NOTE] [text] COLLATE Latin1_General_CI_AS NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_RAP_SP] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_RAP_SP] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_RAP_SP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_RAP_SP_id_unique] DEFAULT (newid()) FOR [id_unique],
        CONSTRAINT [DF_U_RAP_SP_RAP_CODSOC] DEFAULT ('') FOR [RAP_CODSOC],
        CONSTRAINT [DF_U_RAP_SP_RAP_NUMPRG] DEFAULT ('') FOR [RAP_NUMPRG],
        CONSTRAINT [DF_U_RAP_SP_RAP_DATPRG] DEFAULT ('') FOR [RAP_DATPRG],
        CONSTRAINT [DF_U_RAP_SP_RAP_AMGPRG] DEFAULT ('') FOR [RAP_AMGPRG],
        CONSTRAINT [DF_U_RAP_SP_RAP_PROGRE] DEFAULT (0) FOR [RAP_PROGRE],
        CONSTRAINT [DF_U_RAP_SP_RAP_TEMPB1] DEFAULT (0) FOR [RAP_TEMPB1],
        CONSTRAINT [DF_U_RAP_SP_RAP_TEMPB2] DEFAULT (0) FOR [RAP_TEMPB2],
        CONSTRAINT [DF_U_RAP_SP_RAP_TEMPB3] DEFAULT (0) FOR [RAP_TEMPB3],
        CONSTRAINT [DF_U_RAP_SP_RAP_POSMF1] DEFAULT (0) FOR [RAP_POSMF1],
        CONSTRAINT [DF_U_RAP_SP_RAP_POSMF2] DEFAULT (0) FOR [RAP_POSMF2],
        CONSTRAINT [DF_U_RAP_SP_RAP_POSMF3] DEFAULT (0) FOR [RAP_POSMF3],
        CONSTRAINT [DF_U_RAP_SP_RAP_POSMF4] DEFAULT (0) FOR [RAP_POSMF4],
        CONSTRAINT [DF_U_RAP_SP_RAP_POSMF5] DEFAULT (0) FOR [RAP_POSMF5],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF1] DEFAULT (0) FOR [RAP_GRADF1],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF2] DEFAULT (0) FOR [RAP_GRADF2],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF3] DEFAULT (0) FOR [RAP_GRADF3],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF4] DEFAULT (0) FOR [RAP_GRADF4],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF5] DEFAULT (0) FOR [RAP_GRADF5],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF6] DEFAULT (0) FOR [RAP_GRADF6],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF7] DEFAULT (0) FOR [RAP_GRADF7],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRADF8] DEFAULT (0) FOR [RAP_GRADF8],
        CONSTRAINT [DF_U_RAP_SP_RAP_VELSPA] DEFAULT (0) FOR [RAP_VELSPA],
        CONSTRAINT [DF_U_RAP_SP_RAP_VELLIN] DEFAULT (0) FOR [RAP_VELLIN],
        CONSTRAINT [DF_U_RAP_SP_RAP_TIRO] DEFAULT ('') FOR [RAP_TIRO],
        CONSTRAINT [DF_U_RAP_SP_RAP_DINPRO] DEFAULT ('') FOR [RAP_DINPRO],
        CONSTRAINT [DF_U_RAP_SP_RAP_OINPRO] DEFAULT ('') FOR [RAP_OINPRO],
        CONSTRAINT [DF_U_RAP_SP_RAP_DFIPRO] DEFAULT ('') FOR [RAP_DFIPRO],
        CONSTRAINT [DF_U_RAP_SP_RAP_OFIPRO] DEFAULT ('') FOR [RAP_OFIPRO],
        CONSTRAINT [DF_U_RAP_SP_RAP_DINTPR] DEFAULT ('') FOR [RAP_DINTPR],
        CONSTRAINT [DF_U_RAP_SP_RAP_OINTPR] DEFAULT ('') FOR [RAP_OINTPR],
        CONSTRAINT [DF_U_RAP_SP_RAP_OFIINT] DEFAULT ('') FOR [RAP_OFIINT],
        CONSTRAINT [DF_U_RAP_SP_RAP_MTLSUP] DEFAULT (0) FOR [RAP_MTLSUP],
        CONSTRAINT [DF_U_RAP_SP_RAP_MTLSPA] DEFAULT (0) FOR [RAP_MTLSPA],
        CONSTRAINT [DF_U_RAP_SP_RAP_MQTOT] DEFAULT (0) FOR [RAP_MQTOT],
        CONSTRAINT [DF_U_RAP_SP_RAP_ADESIV] DEFAULT ('') FOR [RAP_ADESIV],
        CONSTRAINT [DF_U_RAP_SP_RAP_PHADE] DEFAULT ('') FOR [RAP_PHADE],
        CONSTRAINT [DF_U_RAP_SP_RAP_RESSEC] DEFAULT ('') FOR [RAP_RESSEC],
        CONSTRAINT [DF_U_RAP_SP_RAP_VISFRD] DEFAULT ('') FOR [RAP_VISFRD],
        CONSTRAINT [DF_U_RAP_SP_RAP_GRAMMA] DEFAULT ('') FOR [RAP_GRAMMA],
        CONSTRAINT [DF_U_RAP_SP_RAP_SPESSO] DEFAULT ('') FOR [RAP_SPESSO],
        CONSTRAINT [DF_U_RAP_SP_RAP_NOTE] DEFAULT ('') FOR [RAP_NOTE]
GO

 
 
 
 
 
