if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_RAP_IN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_RAP_IN]
GO
 
CREATE TABLE [dbo].[U_RAP_IN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[RAP_DATINT] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_CODRIS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_COGNOM] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_NOME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_NUMCTR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DATCTR] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_TIPCTR] [varchar] (01) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_CODSOC] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DESSOC] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DESART] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_UMART] [varchar] (03) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_DESUM] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_PRZACT] [numeric] (10,2)  NULL,
	[RAP_ORAINI] [varchar] (08) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_ORAFIN] [varchar] (08) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_TOTORE] [numeric] (10,2)  NULL ,
	[RAP_SPECIF] [text] COLLATE Latin1_General_CI_AS NULL ,
	[RAP_FLGFAT] [bit] NULL ,
	[RAP_CODSYS] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[RAP_ORDFAT] [numeric] (2,0)  NULL ,
	[SELEZIONE] [varchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_RAP_IN] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_RAP_IN] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_RAP_IN] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_RAP_IN_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_RAP_IN_RAP_DATINT] DEFAULT ('') FOR [RAP_DATINT],
	CONSTRAINT [DF_U_RAP_IN_RAP_CODRIS] DEFAULT ('') FOR [RAP_CODRIS],
	CONSTRAINT [DF_U_RAP_IN_RAP_COGNOM] DEFAULT ('') FOR [RAP_COGNOM],
	CONSTRAINT [DF_U_RAP_IN_RAP_NOME] DEFAULT ('') FOR [RAP_NOME],
	CONSTRAINT [DF_U_RAP_IN_RAP_NUMCTR] DEFAULT ('') FOR [RAP_NUMCTR],
	CONSTRAINT [DF_U_RAP_IN_RAP_DATCTR] DEFAULT ('') FOR [RAP_DATCTR],
	CONSTRAINT [DF_U_RAP_IN_RAP_TIPCTR] DEFAULT ('') FOR [RAP_TIPCTR],
	CONSTRAINT [DF_U_RAP_IN_RAP_CODSOC] DEFAULT ('') FOR [RAP_CODSOC],
	CONSTRAINT [DF_U_RAP_IN_RAP_DESSOC] DEFAULT ('') FOR [RAP_DESSOC],
	CONSTRAINT [DF_U_RAP_IN_RAP_CODART] DEFAULT ('') FOR [RAP_CODART],
	CONSTRAINT [DF_U_RAP_IN_RAP_DESART] DEFAULT ('') FOR [RAP_DESART],
	CONSTRAINT [DF_U_RAP_IN_RAP_UMART] DEFAULT ('') FOR [RAP_UMART],
	CONSTRAINT [DF_U_RAP_IN_RAP_DESUM] DEFAULT ('') FOR [RAP_DESUM],
	CONSTRAINT [DF_U_RAP_IN_RAP_PRZACT] DEFAULT (0) FOR [RAP_PRZACT],
	CONSTRAINT [DF_U_RAP_IN_RAP_ORAINI] DEFAULT ('') FOR [RAP_ORAINI],
	CONSTRAINT [DF_U_RAP_IN_RAP_ORAFIN] DEFAULT ('') FOR [RAP_ORAFIN],
	CONSTRAINT [DF_U_RAP_IN_RAP_TOTORE] DEFAULT (0) FOR [RAP_TOTORE],
	CONSTRAINT [DF_U_RAP_IN_RAP_SPECIF] DEFAULT ('') FOR [RAP_SPECIF],
	CONSTRAINT [DF_U_RAP_IN_RAP_FLGFAT] DEFAULT (0) FOR [RAP_FLGFAT],
	CONSTRAINT [DF_U_RAP_IN_RAP_CODSYS] DEFAULT ('') FOR [RAP_CODSYS],
	CONSTRAINT [DF_U_RAP_IN_RAP_ORDFAT] DEFAULT (0) FOR [RAP_ORDFAT],
	CONSTRAINT [DF_U_RAP_IN_SELEZIONE] DEFAULT ('') FOR [SELEZIONE]
GO

