if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_SCO_CV]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_SCO_CV]
GO
 
CREATE TABLE [dbo].[U_SCO_CV] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_U_SCO_CV_id_unique] DEFAULT newid(),
	[IDRIGA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_IDRIGA] DEFAULT (''),
	[CODCVE] varchar(9) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_CODCVE] DEFAULT (''),
	[DESCVE] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DESCVE] DEFAULT (''),
	[CODCLI] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_CODCLI] DEFAULT (''),
	[DESCLI] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DESCLI] DEFAULT (''),
	[CODGMI] varchar(9) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_CODGMI] DEFAULT (''),
	[DESGMI] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DESGMI] DEFAULT (''),
	[CODCPA] varchar(3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_CODCPA] DEFAULT (''),
	[DESCPA] varchar(100) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DESCPA] DEFAULT (''),
	[SCONTO] numeric(14,10) NOT NULL CONSTRAINT [DF_U_SCO_CV_SCONTO] DEFAULT (0),
	[DTVADA] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DTVADA] DEFAULT (''),
	[DTVAAL] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_U_SCO_CV_DTVAAL] DEFAULT ('')
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_SCO_CV] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_SCO_CV] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
