if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_XLS_RP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[U_XLS_RP]
GO

CREATE TABLE [dbo].[U_XLS_RP] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[SOCIETA] [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[CODICE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL ,
	[ANNO] [varchar] (4) COLLATE Latin1_General_CI_AS NULL ,
	[PDV] [varchar] (3) COLLATE Latin1_General_CI_AS NULL ,
	[DESPDV] [varchar] (40) COLLATE Latin1_General_CI_AS NULL ,
	[SALDOAA] [numeric](17, 3) NULL ,
	[SALDO01] [numeric](17, 3) NULL ,
	[SALDO02] [numeric](17, 3) NULL ,
	[SALDO03] [numeric](17, 3) NULL ,
	[SALDO04] [numeric](17, 3) NULL ,
	[SALDO05] [numeric](17, 3) NULL ,
	[SALDO06] [numeric](17, 3) NULL ,
	[SALDO07] [numeric](17, 3) NULL ,
	[SALDO08] [numeric](17, 3) NULL ,
	[SALDO09] [numeric](17, 3) NULL ,
	[SALDO10] [numeric](17, 3) NULL ,
	[SALDO11] [numeric](17, 3) NULL ,
	[SALDO12] [numeric](17, 3) NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[U_XLS_RP] WITH NOCHECK ADD 
	CONSTRAINT [PK_U_XLS_RP] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[U_XLS_RP] WITH NOCHECK ADD 
	CONSTRAINT [DF_U_XLS_RP_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_U_XLS_RP_SOCIETA] DEFAULT ('') FOR [SOCIETA],
	CONSTRAINT [DF_U_XLS_RP_CODICE] DEFAULT ('') FOR [CODICE],
	CONSTRAINT [DF_U_XLS_RP_ANNO] DEFAULT ('') FOR [ANNO],
	CONSTRAINT [DF_U_XLS_RP_PDV] DEFAULT ('') FOR [PDV],
	CONSTRAINT [DF_U_XLS_RP_DESPDV] DEFAULT ('') FOR [DESPDV],
	CONSTRAINT [DF_U_XLS_RP_SALDOAA] DEFAULT (0) FOR [SALDOAA],
	CONSTRAINT [DF_U_XLS_RP_SALDO01] DEFAULT (0) FOR [SALDO01],
	CONSTRAINT [DF_U_XLS_RP_SALDO02] DEFAULT (0) FOR [SALDO02],
	CONSTRAINT [DF_U_XLS_RP_SALDO03] DEFAULT (0) FOR [SALDO03],
	CONSTRAINT [DF_U_XLS_RP_SALDO04] DEFAULT (0) FOR [SALDO04],
	CONSTRAINT [DF_U_XLS_RP_SALDO05] DEFAULT (0) FOR [SALDO05],
	CONSTRAINT [DF_U_XLS_RP_SALDO06] DEFAULT (0) FOR [SALDO06],
	CONSTRAINT [DF_U_XLS_RP_SALDO07] DEFAULT (0) FOR [SALDO07],
	CONSTRAINT [DF_U_XLS_RP_SALDO08] DEFAULT (0) FOR [SALDO08],
	CONSTRAINT [DF_U_XLS_RP_SALDO09] DEFAULT (0) FOR [SALDO09],
	CONSTRAINT [DF_U_XLS_RP_SALDO10] DEFAULT (0) FOR [SALDO10],
	CONSTRAINT [DF_U_XLS_RP_SALDO11] DEFAULT (0) FOR [SALDO11],
	CONSTRAINT [DF_U_XLS_RP_SALDO12] DEFAULT (0) FOR [SALDO12]
GO

 CREATE  INDEX [IX_U_XLS_RP] ON [dbo].[U_XLS_RP]([SOCIETA], [ANNO], [CODICE], [PDV]) ON [PRIMARY]
GO

