if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[ULTIMA_PN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[ULTIMA_PN]
GO
 
CREATE TABLE [dbo].[ULTIMA_PN] (
	[id_unique]  uniqueidentifier ROWGUIDCOL NOT NULL CONSTRAINT [DF_ULTIMA_PN_id_unique] DEFAULT newid(),
	[ULPN_FORNITORE] varchar(10) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_ULTIMA_PN_ULPN_FORNITORE] DEFAULT (''),
	[ULPN_KEY] varchar(250) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_ULTIMA_ULPN_KEY] DEFAULT (''),
	[ULPN_DESFORNIT] varchar(250) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_ULTIMA_PN_ULPN_DESFORNIT] DEFAULT (''),
	[ULPN_CONTROPARTITA] varchar(13) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_ULTIMA_PN_ULPN_CONTROPARTITA] DEFAULT (''),
	[ULPN_DESCONTROPAR] varchar(250) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_ULTIMA_PN_ULPN_DESCONTROPAR] DEFAULT ('')
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ULTIMA_PN] WITH NOCHECK ADD 
	CONSTRAINT [PK_ULTIMA_PN] PRIMARY KEY CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO
