
UPDATE PARA SET CODPGO = 
	CASE
		WHEN SUBSTRING(LIBERA,10,1) = 'X' THEN 'MP12'  -- RI.BA.
		WHEN SUBSTRING(LIBERA,4,3) = 'BON' THEN 'MP05'  -- BONIFICO
		WHEN SUBSTRING(LIBERA,10,1) = 'R' THEN 'MP09'  -- RID
		ELSE 'MP01'  -- CONTANTI
	END
WHERE CODICE LIKE 'CPA%' AND CODPGO = ''
