
/* CANCELLAZIONE RECORD DETTAGLI DI TERZO LIVELLO GENERATI IN MODO  */
/* ANOMALO A CAUSA DI BUG SU MENU_ORF000 RISOLTO IN DATA 11/09/2009 */

DELETE FROM U_ORF_DL WHERE ORD_DESART = '*** COMMENTO ***'

DELETE FROM U_BFO_DL WHERE ORD_DESART = '*** COMMENTO ***'
