
/* Aggiorna per tutte le righe della tabella U_ORD_DD i campi: 

	- U_ORD_DD.ORS_NUMORD 
	- U_ORD_DD.ORS_DATORD 
	- U_ORD_DD.ORS_CODCLI 
	- U_ORD_DD.ORS_RAGSOC 
	- U_ORD_DD.ORS_CODEMI 
	- U_ORD_DD.ORS_RAGEMI
 
in base ai valori della tabella di testata U_ORD_TT, e quindi rispettivamente ai campi:

	- U_ORD_TT.ORD_NUMORD 
	- U_ORD_TT.ORD_DATORD 
	- U_ORD_TT.ORD_CODCLI 
	- U_ORD_TT.ORD_RAGSOC 
	- U_ORD_TT.ORD_CODEMI 
	- U_ORD_TT.ORD_RAGEMI

*/

UPDATE U_ORD_DD SET 
	U_ORD_DD.ORS_NUMORD = U_ORD_TT.ORD_NUMORD,
	U_ORD_DD.ORS_DATORD = U_ORD_TT.ORD_DATORD,
	U_ORD_DD.ORS_CODCLI = U_ORD_TT.ORD_CODCLI,
	U_ORD_DD.ORS_RAGSOC = U_ORD_TT.ORD_RAGSOC,
	U_ORD_DD.ORS_CODEMI = U_ORD_TT.ORD_CODEMI,
	U_ORD_DD.ORS_RAGEMI = U_ORD_TT.ORD_RAGEMI
FROM U_ORD_DD JOIN U_ORD_TT
ON U_ORD_DD.DAGGANCIO = U_ORD_TT.TAGGANCIO
