

-- AGGIORNO LE RIGHE DDT CON QTA IN METRI QUARDI DIVERSA DALLA QTA VENDUTA
UPDATE U_BOL_DD SET ORD_QTAMQ = ORD_QTAORD
WHERE ORD_UM = 'MQ' AND ORS_DATORD >= '2008/01/01' AND ORS_DATORD <= '2008/12/31' AND ORD_DESART <> '*** COMMENTO ***' 
AND ORD_QTAORD <> ORD_QTAMQ


-- VERIFICO CHE NON CI SIANO ALTRE RIGHE DDT CON QTA IN METRI QUARDI DIVERSA DALLA QTA VENDUTA
SELECT ORS_NUMORD,ORS_DATORD,ORS_RAGSOC,ORD_QTAMQ,ORD_QTAORD,ORD_UM,ORD_ALTEZZ,ORD_LUNGHE,ORD_NUMBOB,* FROM U_BOL_DD 
WHERE ORD_UM = 'MQ' AND ORS_DATORD >= '2008/01/01' AND ORS_DATORD <= '2008/12/31' AND ORD_DESART <> '*** COMMENTO ***' 
AND ORD_QTAORD <> ORD_QTAMQ
ORDER BY DAGGANCIO,ORD_SEQUEN