
/* Aggiorna per tutte le righe della tabella U_FAT_DD i campi: 

	- U_FAT_DD.ORS_NUMORD 
	- U_FAT_DD.ORS_DATORD 
	- U_FAT_DD.ORS_CODCLI 
	- U_FAT_DD.ORS_RAGSOC 
	- U_FAT_DD.ORS_CODEMI 
	- U_FAT_DD.ORS_RAGEMI
 
in base ai valori della tabella di testata U_FAT_TT, e quindi rispettivamente ai campi:

	- U_FAT_TT.ORD_NUMORD 
	- U_FAT_TT.ORD_DATORD 
	- U_FAT_TT.ORD_CODCLI 
	- U_FAT_TT.ORD_RAGSOC 
	- U_FAT_TT.ORD_CODEMI 
	- U_FAT_TT.ORD_RAGEMI

*/

UPDATE U_FAT_DD SET 
	U_FAT_DD.ORS_NUMORD = U_FAT_TT.ORD_NUMORD,
	U_FAT_DD.ORS_DATORD = U_FAT_TT.ORD_DATORD,
	U_FAT_DD.ORS_CODCLI = U_FAT_TT.ORD_CODCLI,
	U_FAT_DD.ORS_RAGSOC = U_FAT_TT.ORD_RAGSOC,
	U_FAT_DD.ORS_CODEMI = U_FAT_TT.ORD_CODEMI,
	U_FAT_DD.ORS_RAGEMI = U_FAT_TT.ORD_RAGEMI
FROM U_FAT_DD JOIN U_FAT_TT
ON U_FAT_DD.DAGGANCIO = U_FAT_TT.TAGGANCIO
