if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[UTILPRZMOV]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[UTILPRZMOV]
GO
 
CREATE TABLE [dbo].[UTILPRZMOV] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[TABLENAME] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[FIELDNAME] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[TIDUNIQUE] [varchar] (36) COLLATE Latin1_General_CI_AS NULL ,
	[OLD_PREACQ] [numeric] (17,6) NULL ,
	[NEW_PREACQ] [numeric] (17,6) NULL ,
	[DATA_UPD_RECORD] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_UPD_RECORD] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[DATA_ELAB] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ORA_ELAB] [varchar] (8) COLLATE Latin1_General_CI_AS NULL ,
	[SYS_ELAB] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[DESCR_ELAB] [varchar] (254) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UTILPRZMOV] WITH NOCHECK ADD 
	CONSTRAINT [PK_UTILPRZMOV] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[UTILPRZMOV] WITH NOCHECK ADD 
	CONSTRAINT [DF_UTILPRZMOV_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_UTILPRZMOV_TABLENAME] DEFAULT ('') FOR [TABLENAME],
	CONSTRAINT [DF_UTILPRZMOV_FIELDNAME] DEFAULT ('') FOR [FIELDNAME],
	CONSTRAINT [DF_UTILPRZMOV_TIDUNIQUE] DEFAULT ('') FOR [TIDUNIQUE],
	CONSTRAINT [DF_UTILPRZMOV_OLD_PREACQ] DEFAULT (0) FOR [OLD_PREACQ],
	CONSTRAINT [DF_UTILPRZMOV_NEW_PREACQ] DEFAULT (0) FOR [NEW_PREACQ],
	CONSTRAINT [DF_UTILPRZMOV_DATA_UPD_RECORD] DEFAULT ('') FOR [DATA_UPD_RECORD],
	CONSTRAINT [DF_UTILPRZMOV_ORA_UPD_RECORD] DEFAULT ('') FOR [ORA_UPD_RECORD],
	CONSTRAINT [DF_UTILPRZMOV_DATA_ELAB] DEFAULT ('') FOR [DATA_ELAB],
	CONSTRAINT [DF_UTILPRZMOV_ORA_ELAB] DEFAULT ('') FOR [ORA_ELAB],
	CONSTRAINT [DF_UTILPRZMOV_SYS_ELAB] DEFAULT ('') FOR [SYS_ELAB],
	CONSTRAINT [DF_UTILPRZMOV_DESCR_ELAB] DEFAULT ('') FOR [DESCR_ELAB]
GO

