if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VALORE_MAGAZZINO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[VALORE_MAGAZZINO]
GO
 
CREATE TABLE [dbo].[VALORE_MAGAZZINO] (
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL ,
	[PERIODO] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI_PERIODO] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[ELAB_DATA_DAL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[ELAB_DATA_AL] [varchar] (10) COLLATE Latin1_General_CI_AS NULL ,
	[TIPO_ARTICOLO] [varchar] (1) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI_TIPO_ARTICOLO] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[CODART] [varchar] (16) COLLATE Latin1_General_CI_AS NULL ,
	[DESCRI] [varchar] (200) COLLATE Latin1_General_CI_AS NULL ,
	[CODMAG] [varchar] (20) COLLATE Latin1_General_CI_AS NULL ,
	[DESMAG] [varchar] (30) COLLATE Latin1_General_CI_AS NULL ,
	[UM_ACQ]     [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[GIACENZA]  [numeric] (19,6) NULL ,
	[VAL_ACQ]  [numeric] (19,6) NULL ,
	[VAL_VEN]  [numeric] (19,6) NULL ,
	[COSTO_PROD] [numeric] (19,6) NULL ,
	[COSTO_CMP] [numeric] (19,6) NULL ,
	[VALORE_CMP] [numeric] (19,6) NULL ,
	[COSTO_LIFO] [numeric] (19,6) NULL ,
	[VALORE_LIFO] [numeric] (19,6) NULL ,
	[UM_VEN]     [varchar] (2) COLLATE Latin1_General_CI_AS NULL ,
	[PREZZO_MEDIO_VENDITA] [numeric] (19,6) NULL ,
	[VALORE_VENDITA] [numeric] (19,6) NULL ,
	[MOM_CMP] [numeric] (19,6) NULL ,
	[MOM_LIFO] [numeric] (19,6) NULL 

) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[VALORE_MAGAZZINO] WITH NOCHECK ADD 
	CONSTRAINT [PK_VALORE_MAGAZZINO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[VALORE_MAGAZZINO] WITH NOCHECK ADD 
	CONSTRAINT [DF_VALORE_MAGAZZINO_id_unique] DEFAULT (newid()) FOR [id_unique],
	CONSTRAINT [DF_VALORE_MAGAZZINO_PERIODO] DEFAULT ('') FOR [PERIODO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_DESCRI_PERIODO] DEFAULT ('') FOR [DESCRI_PERIODO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_ELAB_DATA_DAL] DEFAULT ('') FOR [ELAB_DATA_DAL],
	CONSTRAINT [DF_VALORE_MAGAZZINO_ELAB_DATA_AL] DEFAULT ('') FOR [ELAB_DATA_AL],
	CONSTRAINT [DF_VALORE_MAGAZZINO_TIPO_ARTICOLO] DEFAULT ('') FOR [TIPO_ARTICOLO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_DESCRI_TIPO_ARTICOLO] DEFAULT ('') FOR [DESCRI_TIPO_ARTICOLO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_CODART] DEFAULT ('') FOR [CODART],
	CONSTRAINT [DF_VALORE_MAGAZZINO_DESCRI] DEFAULT ('') FOR [DESCRI],
	CONSTRAINT [DF_VALORE_MAGAZZINO_CODMAG] DEFAULT ('') FOR [CODMAG],
	CONSTRAINT [DF_VALORE_MAGAZZINO_DESMAG] DEFAULT ('') FOR [DESMAG],
	CONSTRAINT [DF_VALORE_MAGAZZINO_UM_ACQ] DEFAULT ('') FOR [UM_ACQ],
	CONSTRAINT [DF_VALORE_MAGAZZINO_GIACENZA] DEFAULT (0) FOR [GIACENZA],
	CONSTRAINT [DF_VALORE_MAGAZZINO_VAL_ACQ] DEFAULT (0) FOR [VAL_ACQ],
	CONSTRAINT [DF_VALORE_MAGAZZINO_VAL_VEN] DEFAULT (0) FOR [VAL_VEN],
	CONSTRAINT [DF_VALORE_MAGAZZINO_COSTO_CMP] DEFAULT (0) FOR [COSTO_CMP],
	CONSTRAINT [DF_VALORE_MAGAZZINO_VALORE_CMP] DEFAULT (0) FOR [VALORE_CMP],
	CONSTRAINT [DF_VALORE_MAGAZZINO_COSTO_LIFO] DEFAULT (0) FOR [COSTO_LIFO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_VALORE_LIFO] DEFAULT (0) FOR [VALORE_LIFO],
	CONSTRAINT [DF_VALORE_MAGAZZINO_UM_VEN] DEFAULT ('') FOR [UM_VEN],
	CONSTRAINT [DF_VALORE_MAGAZZINO_PREZZO_MEDIO_VENDITA] DEFAULT (0) FOR [PREZZO_MEDIO_VENDITA],
	CONSTRAINT [DF_VALORE_MAGAZZINO_VALORE_VENDITA] DEFAULT (0) FOR [VALORE_VENDITA],
	CONSTRAINT [DF_VALORE_MAGAZZINO_MOM_CMP] DEFAULT (0) FOR [MOM_CMP],
	CONSTRAINT [DF_VALORE_MAGAZZINO_MOM_LIFO] DEFAULT (0) FOR [MOM_LIFO]
GO

