

/****** Object:  Table [dbo].[VENDITE_ST]    Script Date: 19/04/2016 16:15:38 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VENDITE_ST]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[VENDITE_ST]
GO

/****** Object:  Table [dbo].[VENDITE_ST]    Script Date: 19/02/2016 17:11:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[VENDITE_ST](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_VENDITE_ST_id_unique]  DEFAULT (newid()),
	[ORD_CODSOC] [varchar](2) NULL CONSTRAINT [DF_VENDITE_ST_ORD_CODSOC]  DEFAULT (''),
	[ORD_CODCLI] [varchar](10) NULL CONSTRAINT [DF_VENDITE_ST_ORD_CODCLI]  DEFAULT (''),
	[ORD_RAGSOC] [varchar](150) NULL CONSTRAINT [DF_VENDITE_ST_ORD_RAGSOC]  DEFAULT (''),
	[ORD_RAGDUE] [varchar](40) NULL CONSTRAINT [DF_VENDITE_ST_ORD_RAGDUE]  DEFAULT (''),
	[ORD_INDIRI] [varchar](150) NULL CONSTRAINT [DF_VENDITE_ST_ORD_INDIRI]  DEFAULT (''),
	[ORD_CAP] [varchar](15) NULL CONSTRAINT [DF_VENDITE_ST_ORD_CAP]  DEFAULT (''),
	[ORD_LOCALI] [varchar](150) NULL CONSTRAINT [DF_VENDITE_ST_ORD_LOCALI]  DEFAULT (''),
	[ORD_PARIVA] [varchar](20) NULL CONSTRAINT [DF_VENDITE_ST_ORD_PARIVA]  DEFAULT (''),
	[ORD_TIPOCL] [varchar](15) NOT NULL CONSTRAINT [DF_VENDITE_ST_ORD_TIPOCL]  DEFAULT (''),
	[ORD_TIPOVE] [varchar](20) NOT NULL CONSTRAINT [DF_VENDITE_ST_ORD_TIPOVE]  DEFAULT (''),
	[ORD_VALUTA] [varchar](3) NULL CONSTRAINT [DF_VENDITE_ST_ORD_VALUTA]  DEFAULT (''),
	[ORD_CAMBIO] [numeric](17, 10) NULL CONSTRAINT [DF_VENDITE_ST_ORD_CAMBIO]  DEFAULT (0),
	[ORD_IMPONIB] [numeric](17, 3) NULL CONSTRAINT [DF_VENDITE_ST_ORD_IMPONIB]  DEFAULT ((0)),
	[ORD_IMPOSTA] [numeric](17, 3) NULL CONSTRAINT [DF_VENDITE_ST_ORD_IMPOSTA]  DEFAULT ((0)),
	[ORD_VALORE] [numeric](17, 3) NULL CONSTRAINT [DF_VENDITE_ST_ORD_VALORE]  DEFAULT (0),
 	[ORD_DATINS] [varchar](10) NOT NULL CONSTRAINT [DF_VENDITE_ST_ORD_DATINS]  DEFAULT (''),
	[ORD_NOTA] [text] NULL CONSTRAINT [DF_VENDITE_ORD_NOTA]  DEFAULT (''),
 CONSTRAINT [PK_VENDITE_ST] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


