

/****** Object:  Table [dbo].[VENDITE_CO]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VENDITE_CO]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[VENDITE_CO]
GO  


CREATE TABLE [dbo].[VENDITE_CO](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_VENDITE_CO_id_unique] DEFAULT (newid()),
	[DAGGANCIO]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_TAGGANCIO]  DEFAULT (''),
	[LINK_DT_CO]	[varchar](10) NULL CONSTRAINT [DF_VENDITE_DC_LINK_DT_CO] DEFAULT (''),            
	[LINK_CONTR]	[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_LINK_CONTR] DEFAULT (''),            
	[PMKEY]			[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_PMKEY] DEFAULT (''),            
	[CCODSCHE]		[varchar](20) NULL CONSTRAINT [DF_VENDITE_CO_CCODSCHE] DEFAULT (''),
	[NUMORD]		[varchar](6) NULL CONSTRAINT [DF_VENDITE_CO_NUMORD] DEFAULT (''), 
	[DATORD]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_DATORD] DEFAULT (''), 
	[ID_PMCONTR]	[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_ID_PMCONTR] DEFAULT (''), 
	[ANNO_CONTR]	[varchar](4) NULL CONSTRAINT [DF_VENDITE_CO_ANNO_CONTR] DEFAULT (''), 
	[DT_REGIST]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_DT_REGIST] DEFAULT (''),
	[CONTR_A]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_A] DEFAULT (''), 
	[CONTR_B]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_B] DEFAULT (''), 
	[CONTR_C]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_C] DEFAULT (''), 
	[CONTR_D1]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_D1] DEFAULT (''), 
	[CONTR_D2]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_D2] DEFAULT (''), 
	[CONTR_E1]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_E1] DEFAULT (''), 
	[CONTR_E2]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_E2] DEFAULT (''), 
	[CONTR_F1]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_F1]DEFAULT (''),
	[CONTR_F2]		[varchar](10) NULL CONSTRAINT [DF_VENDITE_CO_CONTR_F2]DEFAULT ('')
 	) 
ALTER TABLE [dbo].[VENDITE_CO] WITH NOCHECK ADD 
	CONSTRAINT [PK_VENDITE_CO] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


