

/****** Object:  Table [dbo].[VENDITE_DT]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VENDITE_DT]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[VENDITE_DT]
GO  
                    

CREATE TABLE [dbo].[VENDITE_DT](
	[id_unique]  uniqueidentifier ROWGUIDCOL  NOT NULL CONSTRAINT [DF_VENDITE_DT_id_unique] DEFAULT (newid()),
	[DAGGANCIO]       [varchar](10)   NULL CONSTRAINT [DF_VENDITE_DT_DAGGANCIO] DEFAULT (''),            
	[ORD_CODSYS]      [varchar](10)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_CODSYS] DEFAULT (''),            
	[ORD_SEQUE]       [Numeric](10)   NULL, 
	[ORD_TECNICO]     [varchar](06)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_TECNICO] DEFAULT (''),
	[ORD_NOME_TECN]   [varchar](40)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_NOME_TECN] DEFAULT (''),
	[ORD_ATTIVITA]    [varchar](06)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_ATTIVITA] DEFAULT (''),
	[ORD_DTPROGR]     [varchar](10)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_DTPROGR] DEFAULT (''),
	[ORD_ORAINIPRO]   [varchar](08)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_ORAINIPRO] DEFAULT (''),
	[ORD_ORAFINPRO]   [varchar](08)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_ORAFINPRO] DEFAULT (''),
	[ORD_MINPAUPRO]   [Numeric](10)   NULL, 
	[ORD_PAGAALTEC]   [Bit]           NULL CONSTRAINT [DF_VENDITE_DT_ORD_PAGAALTEC] DEFAULT (0),
	[ORD_VALPRE]      [Numeric](17,3) NULL, 
	[ORD_VALINC]      [Numeric](17,3) NULL, 
	[ORD_DTINIINT]    [varchar](10)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_DTINIINT] DEFAULT (''),
	[ORD_ORAINIINT]   [varchar](08)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_ORAINIINT] DEFAULT (''),
	[ORD_ORAFININT]   [varchar](08)   NULL CONSTRAINT [DF_VENDITE_DT_ORD_ORAFININT] DEFAULT (''),
	[ORD_MINPAUINT]   [Numeric](10)   NULL, 
	[ORD_RAPPORT]     [text]          NULL CONSTRAINT [DF_VENDITE_DT_ORD_RAPPORT]  DEFAULT (''),
	[ORD_INTCLOSE]    [Bit]           NULL CONSTRAINT [DF_VENDITE_DT_ORD_INTCLOSE] DEFAULT (0)) 

ALTER TABLE [dbo].[VENDITE_DT] WITH NOCHECK ADD 
	CONSTRAINT [PK_VENDITE_DT] PRIMARY KEY  CLUSTERED 
	(
		[id_unique]
	)  ON [PRIMARY] 
GO


