-- BILANCIO_CCOSTO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BILANCIO_CCOSTO]'))
	DROP VIEW [dbo].BILANCIO_CCOSTO
GO

CREATE VIEW [dbo].[BILANCIO_CCOSTO]  
AS
	SELECT * FROM (SELECT 
		  CON_ANNO
		  ,CON_CONTO
		  ,COALESCE(MOV.MOV_CCO,'') AS CENTROCOSTO
		  ,COALESCE(SUM(CASE WHEN MOV.MOV_TMOV='D' THEN MOV.MOV_IMP ELSE -1*MOV.MOV_IMP END),0) AS SALDO_CENTROCOSTO
	FROM dbo.CONTI AS CO
	LEFT OUTER JOIN MOV_CONT AS MOV
	ON CO.CON_CONTO = MOV.MOV_CONTO AND CO.CON_ANNO = MOV.MOV_ANNO 
	WHERE COALESCE(MOV.MOV_CCO,'') <>''
	GROUP BY CON_ANNO,CON_CONTO,MOV_CCO
	) AS T1
	WHERE CENTROCOSTO<>'' AND SALDO_CENTROCOSTO<>0

GO




