
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[U_FAF_TT]'))
	DROP VIEW [dbo].[U_FAF_TT]
GO

CREATE VIEW [dbo].[U_FAF_TT]  
AS
	SELECT
		MAIN.*,
		COALESCE(FORN.FOR_INDIR,'') AS ORD_INDIRI,
		COALESCE(FORN.FOR_CAP,'') AS ORD_CAP,
		COALESCE(FORN.FOR_LOCALI,'') AS ORD_LOCALI,
		COALESCE(FORN.FOR_PROVIN,'') AS ORD_PROVIN,
		CASE
			WHEN COALESCE(FORN.FOR_PARIVA,'') NOT IN ('','.') THEN COALESCE(FORN.FOR_PARIVA,'')
			WHEN COALESCE(FORN.FOR_CODFIS,'') NOT IN ('','.') THEN COALESCE(FORN.FOR_PARIVA,'')
			WHEN COALESCE(FORN.FOR_IVACEE,'') NOT IN ('','.') THEN COALESCE(FORN.FOR_IVACEE,'')
			ELSE ''
		END AS ORD_PARIVA,
		FORN.FOR_NAZION AS ORD_CODNAZ
	FROM (
		SELECT
			(SELECT AZI_CODSOC FROM U_AZI_AN) AS ORD_CODSOC,
			SUBSTRING(IND.MOV_DTREG,1,4) AS ORD_ANNO,
			IND.MOV_NUMPRO AS TAGGANCIO,
			IND.MOV_DTREG AS ORD_DATORD,
			IND.MOV_DTDOC AS ORD_DATOR2,
			IND.MOV_NDOC AS ORD_NUMORD,
			IND.MOV_NPROT AS ORD_NPROT,
			IND.MOV_DTREG AS ORD_DTREGIS,
			IND.MOV_NREGIS AS ORD_NREGIS,
			IND.MOV_TOP AS ORD_CAUS,
			CASE
				WHEN COALESCE((SELECT AZI_CONTOSIMILCEE FROM U_AZI_PC),0) = 1 THEN
					RIGHT('0000000000' + RTRIM(REVERSE(LEFT(REVERSE(CONTO_FOR.CON_CONTO), CHARINDEX('.', REVERSE(CONTO_FOR.CON_CONTO)) -1))), COALESCE((SELECT AZI_CONTO FROM U_AZI_AN),9))
				ELSE SUBSTRING(CONTO_FOR.CON_CONTO,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10)
			END AS ORD_CODCLI,
			COALESCE(CONTO_FOR.CON_DESCR,'') AS ORD_RAGSOC,
			COALESCE(SUBSTRING(MOVRF.MOV_CONTO,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10),'') AS ORD_RIFCDF,
			COALESCE((SELECT CON_DESCR FROM CONTI WHERE CON_ANNO = MOVRF.MOV_ANNO AND CON_CONTO = MOVRF.MOV_CONTO),'') AS ORD_RIFDSF,
			COALESCE(INDRF.MOV_TOP,'') AS ORD_RIFTFF,
			COALESCE(INDRF.MOV_NDOC,'') AS ORD_RIFNFF,
			COALESCE(INDRF.MOV_DTDOC,'') AS ORD_RIFDFF,
			IND.MOV_MODPAG AS ORD_CPA,
			'' AS ORD_AGE,
			'' AS ORD_DESAGE,
			IND.MOV_DESMOV AS ORD_RIFERI,
			IND.MOV_VALUTA AS ORD_VALUTA,
			IND.MOV_CAMBIO AS ORD_CAMBIO,
			'' AS ORD_TIPOLOGIA,
			'' AS ORD_DESTIPOLOGIA,
			COALESCE((SELECT ABS(SUM(CASE MOV_TMOV WHEN 'D' THEN MOV_IMP ELSE -1*MOV_IMP END)) FROM MOV_CONT WHERE MOV_NUMPRO = IND.MOV_NUMPRO AND MOV_IVA <> 'NO' AND MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = IND.MOV_ANNO AND CON_TIPOCO = 'I')),0) AS ORD_IMPOSTA,
			IND.MOV_IMP - COALESCE((SELECT ABS(SUM(CASE MOV_TMOV WHEN 'D' THEN MOV_IMP ELSE -1*MOV_IMP END)) FROM MOV_CONT WHERE MOV_NUMPRO = IND.MOV_NUMPRO AND MOV_IVA <> 'NO' AND MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = IND.MOV_ANNO AND CON_TIPOCO = 'I')),0) AS ORD_IMPONIB,
			IND.MOV_IMP AS ORD_VALORE,
			CAST(0 AS BIT) AS ORD_CHIUSO,
			0 AS ORD_BOVIRT,
			(SELECT TOP 1 AZI_IDSDI FROM U_AZI_PC) AS ORD_IDSDI,
			CAST('' AS VARCHAR(200)) AS ORD_EPEC,
			CASE
				WHEN (SELECT RTRIM(COALESCE(CODPGO,'')) FROM PARA WHERE CODICE = 'IVA'+(COALESCE((SELECT TOP 1 MOV_IVA FROM MOV_CONT WHERE MOV_NUMPRO = IND.MOV_NUMPRO AND MOV_IVA <> 'NO' ORDER BY MOV_SEQUEN),''))) <> ''
					THEN (SELECT RTRIM(COALESCE(CODPGO,'')) FROM PARA WHERE CODICE = 'IVA'+(COALESCE((SELECT TOP 1 MOV_IVA FROM MOV_CONT WHERE MOV_NUMPRO = IND.MOV_NUMPRO AND MOV_IVA <> 'NO' ORDER BY MOV_SEQUEN),'')))  -- DA PARAMETRO IVA PRIMA RIGA DETTAGLI
				WHEN (SELECT RTRIM(COALESCE(TIPODOCAUTXML,'')) FROM PARANEW WHERE CODICE = 'TOP'+IND.MOV_TOP) <> '' THEN (SELECT RTRIM(TIPODOCAUTXML) FROM PARANEW WHERE CODICE = 'TOP'+IND.MOV_TOP)  -- ERASMO - 16/03/2026 - DA PARAMETRO TOP - CAMPO SPECIFICO "Tipo docum. per creaz. autofatture XML" IN PARANEW
				WHEN (SELECT RTRIM(COALESCE(SUBSTRING(LIBERA,84,4),'')) FROM PARA WHERE CODICE = 'TOP'+IND.MOV_TOP) <> '' THEN (SELECT RTRIM(SUBSTRING(LIBERA,84,4)) FROM PARA WHERE CODICE = 'TOP'+IND.MOV_TOP)  -- DA PARAMETRO TOP
				ELSE '' 
			END AS ORD_TDXML,
			IND.MOV_FILEXML AS ORD_FILEXML
		FROM INDICE AS IND
		RIGHT OUTER JOIN (SELECT DISTINCT MOV_ANNO,MOV_CONTO,MOV_NUMPRO,MOV_NUCOM FROM MOV_CONT AS MC WHERE MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = MC.MOV_ANNO AND CON_TIPOCO = 'F')) AS MOV ON MOV.MOV_NUMPRO = IND.MOV_NUMPRO
		LEFT OUTER JOIN CONTI as CONTO_FOR ON CONTO_FOR.CON_ANNO = MOV.MOV_ANNO AND CONTO_FOR.CON_CONTO = MOV.MOV_CONTO
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+IND.MOV_TOP
		LEFT OUTER JOIN INDICE AS INDRF ON INDRF.MOV_SYSDOC = (CASE SUBSTRING(MOV.MOV_NUCOM,1,1) WHEN '_' THEN MOV.MOV_NUCOM ELSE NULL END)
		LEFT OUTER JOIN MOV_CONT AS MOVRF ON INDRF.MOV_NUMPRO = MOVRF.MOV_NUMPRO AND MOVRF.MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = MOVRF.MOV_ANNO AND CON_TIPOCO = 'F')

		WHERE
			SUBSTRING(PARA_TOP.LIBERA,2,1) = 'S' AND SUBSTRING(PARA_TOP.LIBERA,12,1) = 'F'
		) AS MAIN
	LEFT OUTER JOIN U_FOR_AN AS FORN ON FORN.FOR_CODSOC = '01' AND FORN.FOR_CODCLI = MAIN.ORD_CODCLI

GO



IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[U_FAF_DD]'))
	DROP VIEW [dbo].[U_FAF_DD]
GO

CREATE VIEW [dbo].[U_FAF_DD]  
AS
	SELECT
		IND.MOV_NUMPRO AS DAGGANCIO,
		IND.MOV_DTREG AS ORS_DATORD,
		IND.MOV_DTDOC AS ORS_DATOR2,
		IND.MOV_NDOC AS ORS_NUMORD,
		IND.MOV_NPROT AS ORS_NPROT,
		IND.MOV_DTREG AS ORS_DTREGIS,
		IND.MOV_NREGIS AS ORS_NREGIS,
		--SUBSTRING(IND.MOV_CONTO,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10) AS ORS_CODCLI,
		--COALESCE(CONTO_FOR.CON_DESCR,'') AS ORS_RAGSOC,
		CASE
			WHEN COALESCE((SELECT AZI_CONTOSIMILCEE FROM U_AZI_PC),0) = 1 THEN
				RIGHT('0000000000' + RTRIM(REVERSE(LEFT(REVERSE(CONTO_FOR.CON_CONTO), CHARINDEX('.', REVERSE(CONTO_FOR.CON_CONTO)) -1))), COALESCE((SELECT AZI_CONTO FROM U_AZI_AN),9))
			ELSE SUBSTRING(CONTO_FOR.CON_CONTO,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10)
		END AS ORS_CODCLI,
		CASE
			WHEN COALESCE((SELECT AZI_CONTOSIMILCEE FROM U_AZI_PC),0) = 1 THEN
				RIGHT('0000000000' + RTRIM(REVERSE(LEFT(REVERSE(CONTO_FOR.CON_CONTO), CHARINDEX('.', REVERSE(CONTO_FOR.CON_CONTO)) -1))), COALESCE((SELECT AZI_CONTO FROM U_AZI_AN),9))
			ELSE SUBSTRING(CONTO_FOR.CON_CONTO,(SELECT AZI_SOTTOG FROM U_AZI_AN)+1,10)
		END AS ORD_CODCLI,
		COALESCE(CONTO_FOR.CON_DESCR,'') AS ORD_RAGSOC,
		COALESCE(MOV.MOV_CONTO,'') AS ORD_CODART,
		COALESCE(CONTI.CON_DESCR,'') AS ORD_DESART,
		1.000000 AS ORD_QTAORD,
		IND.MOV_VALUTA AS ORS_VALUTA,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE -1*COALESCE(MOV.MOV_IMP,0) END,2) AS NUMERIC(19,2)) AS ORD_PREZZO,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE -1*COALESCE(MOV.MOV_IMP,0) END,2) AS NUMERIC(19,2)) AS ORD_PRZNET,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE -1*COALESCE(MOV.MOV_IMP,0) END,2) AS NUMERIC(19,2)) AS ORD_VALORE,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMPOST,0) ELSE -1*COALESCE(MOV.MOV_IMPOST,0) END,2) AS NUMERIC(19,2)) AS ORD_IMPOST,
		COALESCE(MOV.MOV_IVA,'') AS ORD_IVA,
		COALESCE(PA_IVA.DESCRI,'') AS ORD_DESIVA,
		COALESCE(MOV.MOV_CCO,'') AS ORD_CCODET,
		IND.MOV_CAMBIO AS ORS_CAMBIO,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE -1*COALESCE(MOV.MOV_IMP,0) END * IND.MOV_CAMBIO,2) AS NUMERIC(19,2)) AS ORD_VALORE_EUR,
		CAST(ROUND(CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMPOST,0) ELSE -1*COALESCE(MOV.MOV_IMPOST,0) END * IND.MOV_CAMBIO,2) AS NUMERIC(19,2)) AS ORD_IMPOST_EUR,
		MOV.MOV_SEQUEN AS ORD_SEQUEN,
		COALESCE(CONTORF.CON_CONTO,'') AS ORD_CDAPRD,
		COALESCE(CONTORF.CON_DESCR,'') AS ORD_DSAPRD
	FROM INDICE AS IND
	LEFT OUTER JOIN MOV_CONT AS MOV ON MOV.MOV_ANNO = IND.MOV_ANNO AND MOV.MOV_NUMPRO = IND.MOV_NUMPRO AND MOV.MOV_CONTO <> IND.MOV_CONTO
	LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_CONTO = MOV.MOV_CONTO
	LEFT OUTER JOIN CONTI as CONTO_FOR ON CONTO_FOR.CON_ANNO = IND.MOV_ANNO AND CONTO_FOR.CON_CONTO = IND.MOV_CONTO
	LEFT OUTER JOIN PARA AS PA_IVA ON PA_IVA.CODICE = 'IVA'+MOV.MOV_IVA
	--LEFT OUTER JOIN MOV_CONT AS MOVF ON MOVF.MOV_ANNO = IND.MOV_ANNO AND MOVF.MOV_NUMPRO = IND.MOV_NUMPRO AND MOVF.MOV_CONTO = IND.MOV_CONTO
	LEFT OUTER JOIN (SELECT DISTINCT MOV_NUCOM,MOV_ANNO,MOV_NUMPRO,MOV_CONTO FROM MOV_CONT WHERE MOV_NUCOM <> '') AS MOVF ON MOVF.MOV_ANNO = IND.MOV_ANNO AND MOVF.MOV_NUMPRO = IND.MOV_NUMPRO AND MOVF.MOV_CONTO = IND.MOV_CONTO
	LEFT OUTER JOIN INDICE AS INDRF ON INDRF.MOV_SYSDOC = (CASE SUBSTRING(MOVF.MOV_NUCOM,1,1) WHEN '_' THEN MOVF.MOV_NUCOM ELSE NULL END)
	OUTER APPLY (SELECT TOP 1 * FROM MOV_CONT WHERE MOV_NUMPRO = INDRF.MOV_NUMPRO AND MOV_CONTO <> INDRF.MOV_CONTO ORDER BY MOV_SEQUEN) AS MOVRF
	LEFT OUTER JOIN CONTI as CONTORF ON CONTORF.CON_ANNO = INDRF.MOV_ANNO AND CONTORF.CON_CONTO = MOVRF.MOV_CONTO
	WHERE 
		IND.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'F') AND 
		CONTI.CON_TIPOCO <> 'I'
GO

--SELECT * FROM U_FAF_TT WHERE ORD_ANNO >= '2021'

--SELECT * FROM U_FAF_DD WHERE ORS_DATORD >= '2021/01/01'

/*
SELECT * FROM U_FAF_TT WHERE ORD_ANNO >= '2021' AND ORD_NREGIS = 5151
SELECT * FROM U_FAF_DD WHERE DAGGANCIO = '_6170LROMQ'
*/
