
-- VISTA SPARE_PARTS

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SPARE_PARTS]'))
	DROP VIEW [dbo].[SPARE_PARTS]
GO

CREATE VIEW [dbo].[SPARE_PARTS]  
AS

SELECT 
	*,
	ROW_NUMBER() OVER (ORDER BY ARTICLE,SPARE_CODE,CODICE_ORIGINALE) AS INDICE
FROM (
	SELECT
		RTRIM(DIT.DIT_GRUPPO) AS ARTICLE,
		RTRIM(DIT.DIT_DESCRI) AS ART_DESCRIPTION,
		RTRIM(DIS.DIS_CODART) AS SPARE_CODE,
		RTRIM(DIS.DIS_DESCRI) AS COMPONENT_DESCRIPTION,
		COALESCE(RTRIM(DIS2.DIS_CODART),'') AS CODICE_ORIGINALE,
		COALESCE(ART2.ART_ULPCAR,ART.ART_ULPCAR) AS PRICE_LAST_PURCHASE,
		COALESCE((SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = '' AND LIS_CODART = DIS.DIS_CODART ORDER BY LIS_ALLIST,LIS_DATLIS),0) AS SALE_PRICE,
		COALESCE(MAG2.TOT_GIACEN,COALESCE(MAG.TOT_GIACEN,0)) AS GIACENZA,
		COALESCE(ART2.ART_ULPCAR,ART.ART_ULPCAR) * COALESCE(MAG2.TOT_GIACEN,COALESCE(MAG.TOT_GIACEN,0)) AS TOTALE
	FROM U_DIS_TT AS DIT
	LEFT OUTER JOIN U_DIS_DD AS DIS ON DIS.DIS_GRUPPO = DIT.DIT_GRUPPO
	LEFT OUTER JOIN U_ART_PR AS ART ON ART.ART_CODPRI = DIS.DIS_CODART
	LEFT OUTER JOIN U_DIS_DD AS DIS2 ON DIS2.DIS_GRUPPO = DIS.DIS_CODART
	LEFT OUTER JOIN U_ART_PR AS ART2 ON ART2.ART_CODPRI = DIS2.DIS_CODART
	LEFT OUTER JOIN (SELECT MAG_ANAART, SUM(MAG_GIACEN) AS TOT_GIACEN FROM U_MAG_GG GROUP BY MAG_ANAART) AS MAG ON MAG.MAG_ANAART = DIS.DIS_CODART
	LEFT OUTER JOIN (SELECT MAG_ANAART, SUM(MAG_GIACEN) AS TOT_GIACEN FROM U_MAG_GG GROUP BY MAG_ANAART) AS MAG2 ON MAG2.MAG_ANAART = DIS2.DIS_CODART
	WHERE RIGHT(RTRIM(DIT.DIT_GRUPPO),1) = 'R' AND COALESCE(DIS2.DIS_CODART,'') NOT IN ('001','002','003') AND ART.ART_NONMOV = 0 AND (ART2.ART_NONMOV = 0 OR COALESCE(DIS2.DIS_CODART,'') = '')

	UNION

	SELECT DISTINCT
		'NONE' AS ARTICLE,
		'-' AS ART_DESCRIPTION,
		RTRIM(DIT.DIT_GRUPPO) AS SPARE_CODE,
		RTRIM(DIT.DIT_DESCRI) AS COMPONENT_DESCRIPTION,
		COALESCE(RTRIM(DIS2.DIS_CODART),'') AS CODICE_ORIGINALE,
		COALESCE(ART2.ART_ULPCAR,0) AS PRICE_LAST_PURCHASE,
		COALESCE((SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = '' AND LIS_CODART = DIT.DIT_GRUPPO ORDER BY LIS_ALLIST,LIS_DATLIS),0) AS SALE_PRICE,
		COALESCE(MAG2.TOT_GIACEN,0) AS GIACENZA,
		COALESCE(ART2.ART_ULPCAR,0) * COALESCE(MAG2.TOT_GIACEN,0) AS TOTALE
	FROM U_DIS_TT AS DIT
	LEFT OUTER JOIN U_ART_PR AS ART ON ART.ART_CODPRI = DIT.DIT_GRUPPO
	LEFT OUTER JOIN U_DIS_DD AS DIS2 ON DIS2.DIS_GRUPPO = DIT.DIT_GRUPPO
	LEFT OUTER JOIN U_ART_PR AS ART2 ON ART2.ART_CODPRI = DIS2.DIS_CODART
	LEFT OUTER JOIN (SELECT MAG_ANAART, SUM(MAG_GIACEN) AS TOT_GIACEN FROM U_MAG_GG GROUP BY MAG_ANAART) AS MAG2 ON MAG2.MAG_ANAART = DIS2.DIS_CODART
	WHERE SUBSTRING(DIT.DIT_GRUPPO,1,3) = '697' AND COALESCE(DIS2.DIS_CODART,'') NOT IN ('001','002','003') AND ART.ART_NONMOV = 0 AND (ART2.ART_NONMOV = 0 OR COALESCE(DIS2.DIS_CODART,'') = '')
	AND
		DIT.DIT_GRUPPO NOT IN (SELECT DIS_CODART FROM U_DIS_DD)
	) AS MAIN
GO

SELECT * FROM SPARE_PARTS ORDER BY INDICE
