
-- VISTA SOSTITUTIVA DELL'ARCHIVIO STATISTICO U_STC_AN

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[U_STC_AN]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [dbo].[U_STC_AN]
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[U_STC_AN]'))
	DROP VIEW [dbo].[U_STC_AN]
GO


CREATE VIEW [dbo].[U_STC_AN]  
AS

	SELECT 
		TT.ORD_CODSOC AS STC_CODSOC, 
		SUBSTRING(TT.ORD_DATORD,1,4) AS STC_ANNO, 
		SUBSTRING(TT.ORD_DATORD,1,4)+SUBSTRING(TT.ORD_DATORD,6,2) AS STC_DATA, 
		TT.ORD_DATORD AS STC_DTDOC, 
		TT.ORD_NUMORD AS STC_NUMORD, 
		TT.ORD_AGE AS STC_CODAGE, 
		COALESCE(AG.AGE_RAGSOC,'') AS STC_DESAGE, 
		TT.ORD_CODNAZ AS STC_CODNAZ,
		TT.ORD_CODCLI AS STC_CODCLI, 
		TT.ORD_RAGSOC AS STC_DESCLI, 
		ORD_CODART AS STC_CODART, 
		ORD_DESART AS STC_DESART, 
		CASE WHEN ORD_UM = '' THEN COALESCE(AR.ART_UMMAGA,'') ELSE ORD_UM END AS STC_UNIMIS, 		
		COALESCE(AR.ART_LINEA,'') AS STC_LINEA, 
		COALESCE(LIN.DESCRI,'') AS STC_DESLIN, 
		DD.ORD_QTAORD * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS STC_QTAVEN, 
		CASE AR.ART_PUBBLI 
			WHEN 'S' THEN 0 
			ELSE ROUND(DD.ORD_VALORE * TT.ORD_CAMBIO * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END),2) 
		END AS STC_VALORE, 		
		TT.ORD_CAUS AS STC_TOP, 		
		TT.ORD_CAP AS STC_CAP, 				
		TT.ORD_VALUTA AS STC_VALUTA, 
		TT.ORD_CAMBIO AS STC_CAMBIO, 
		COALESCE(AR.ART_PRZCOS,0) AS STC_PRZCOS, 
		CASE AR.ART_PUBBLI 
			WHEN 'S' THEN 0 
			ELSE ROUND(DD.ORD_VALORE * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END),2) 
		END AS STC_VALVAL, 
		CASE ORD_UM 
			WHEN 'MQ' THEN DD.ORD_QTAORD * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) 
			ELSE DD.ORD_QTAMQ * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) 
		END AS ORD_QTAMQ, 
		DD.ORD_QTAMQ1 * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAMQ1, 
		DD.ORD_QTAML * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAML, 
		DD.ORD_QTAML1 * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAML1, 
		DD.ORD_QTAKG * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAKG, 
		DD.ORD_QTAKG1 * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAKG1, 		
		ORD_CODMAT AS ORD_CODMAT, 
		ORD_DESMAT AS ORD_DESMAT, 
		ORD_SPESSO AS ORD_SPESSO, 
		ORD_ALTEZZ AS ORD_ALTEZZ, 
		ORD_LUNGHE AS ORD_LUNGHE, 
		ORD_NUMBOB AS ORD_NUMBOB, 
		ORD_DATPED AS ORD_DATPED, 
		ORD_NOTEBO AS ORD_NOTEBO, 
		ORD_DESIMB AS ORD_DESIMB, 
		ORD_LOTMIN AS ORD_LOTMIN, 
		DD.ORD_QTAKGI * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAKGI, 
		DD.ORD_QTAKGE * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAKGE, 
		ORD_CDAPRD AS ORD_CDAPRD, 
		ORD_DSAPRD AS ORD_DSAPRD, 			
		COALESCE(CL.CLI_ZONA,'') AS STC_ZONA, 
		COALESCE(AR.ART_SERIE,'') AS STC_SERIE, 
		COALESCE(ZON.DESCRI,'') AS STC_DESZON, 
		COALESCE(SER.DESCRI,'') AS STC_DESSER, 
		DD.ORD_QTAMCE * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAMCE, 
		DD.ORD_QTAMC1 * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAMC1, 
		DD.ORD_QTAMC * (CASE SUBSTRING(CAUS.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) AS ORD_QTAMC, 
		TT.ORD_PARIVA,
		COALESCE(CL.CLI_CANVEN,'') AS STC_CANVEN, 
		COALESCE(CVE.DESCRI,'') AS STC_DESCVE,
		COALESCE(TPO.CODICE,'') AS TIPOLOGIA_DOC,
		COALESCE(TPO.DESCRI,'') AS DESCR_TIPOLOGIA,
		DD.ORD_CCODET AS CCODET,
		COALESCE(CCO.CON_DESCR,'') AS DESCR_CCODET,
		DD.ORD_PRZCON AS STC_PRZCON
	FROM U_FAT_DD AS DD
	INNER JOIN U_FAT_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO 
	LEFT OUTER JOIN U_CLI_AN AS CL ON CL.CLI_CODSOC = TT.ORD_CODSOC AND CL.CLI_CODCLI = TT.ORD_CODCLI 
	LEFT OUTER JOIN U_AGE_AN AS AG ON AG.AGE_CODSOC = TT.ORD_CODSOC AND AG.AGE_CODICE = TT.ORD_AGE 
	LEFT OUTER JOIN PARA AS CAUS ON CAUS.CODICE = 'TOP'+TT.ORD_CAUS 
	LEFT OUTER JOIN U_ART_PR AS AR ON AR.ART_CODSOC = TT.ORD_CODSOC AND AR.ART_CODPRI = DD.ORD_CODART 
	LEFT OUTER JOIN PARA AS SER ON SER.CODICE = 'SER'+AR.ART_SERIE 
	LEFT OUTER JOIN PARA AS ZON ON ZON.CODICE = 'ZON'+CL.CLI_ZONA 
	LEFT OUTER JOIN PARA AS CVE ON CVE.CODICE = 'CVE'+CL.CLI_CANVEN 
	LEFT OUTER JOIN PARA AS LIN ON LIN.CODICE = 'REP'+AR.ART_LINEA 
	LEFT OUTER JOIN PARA AS TPO ON TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN CCOSTO AS CCO ON CCO.CON_ANNO = SUBSTRING(TT.ORD_DATORD,1,4) AND CCO.CON_CONTO = DD.ORD_CCODET
	WHERE 
		TT.ORD_CODSOC = (SELECT AZI_CODSOC FROM U_AZI_AN) AND 
		--TT.ORD_DATORD BETWEEN '<<PERDAL>>' AND '<<PERAL>>' AND 
		DD.ORD_DESART <> '*** COMMENTO ***' AND 
		DD.ORD_CODART <> 'POLIECO'

GO

--SELECT * FROM U_STC_AN