
-- VISTA FATTURATO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO]'))
	DROP VIEW [dbo].[FATTURATO]
GO

CREATE VIEW [dbo].[FATTURATO]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_DATORD AS DATA_DOC_RIBALTATA,
		SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_DOC,
		TT.ORD_NUMORD AS NUM_FATTURA,
		DD.ORD_DATCON AS DTE_PREV_EVASIONE_RIBALTATA,
		SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_PREV_EVASIONE,
		TT.ord_TIPOLOGIA AS TIPO_ORDINE,
		COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
		CLI.CLI_CANVEN AS CANALE_VENDITA,
		COALESCE(CVEN.DESCRI,'')  AS DESCRI_CANALE_VENDITA,
		TT.ORD_CODCLI AS CODICE_CLIENTE,
		CLI.CLI_RAGSOC AS RAGIONE_SOCIALE,	
		'' AS REGIONE,
		CLI.CLI_NAZION AS NAZIONE,
		CLI.CLI_ZONA AS ZONA,
		CZONA.DESCRI AS DESZONA,
		CLI.CLI_PROVIN AS SUBZONA,
		--COALESCE(CC.CON_DESCR,'') AS BU,
		DD.ORD_CODART AS ARTICOLO,
		DD.ORD_DESART AS DESARTICOLO,
		SUBSTRING(ARTAN.ART_CODGMI,1,3) AS GRUPPO,
		CCODGRU.DESCRI AS DESGRUPPO,
		SUBSTRING(ARTAN.ART_CODGMI,1,6) AS FAMIGLIA,
		CCODFAM.DESCRI AS DESFAMIGLIA,
		ARTAN.ART_CODGMI AS SOTTOFAMIGLIA,
		CCODMERC.DESCRI AS DESSOTTOFAMIGLIA,
		DD.ORD_CCODET AS CENTRCOSTO,
		COALESCE(CC.CON_DESCR,'') AS CENTRCOSTO_DESCRIZIONE,
		--DD.ORD_PRZNET*DD.ORD_QTAORD AS EURO_PRNETTO_QUANTITA,
		(CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) * DD.ORD_PRZNET*DD.ORD_QTAORD AS EURO_PRNETTO_QUANTITA,
		--(DD.ORD_PREZZO - DD.ORD_PRZNET)*DD.ORD_QTAORD AS SCONTO_QUANTITA,
		(CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) * (DD.ORD_PREZZO - DD.ORD_PRZNET)*DD.ORD_QTAORD AS SCONTO_QUANTITA,
		DD.ORD_QTAORD AS FATTURATO,
		PR.ART_ULPCAR AS ULT_PREZZO_ACQUISTO,
		COALESCE((SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODART = DD.ORD_CODART ORDER BY LIS_DATLIS DESC),0) AS PREZZO_ULT_LISTINO
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR
	ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_AN AS ARTAN
	ON DD.ORD_CODART = ARTAN.ART_CODPRI
	LEFT OUTER JOIN CCOSTO AS CC
	ON DD.ORD_CCODET = CC.CON_CONTO AND CC.CON_ANNO = TT.ORD_ANNO
	LEFT OUTER JOIN U_CLI_AN AS CLI
	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS CVEN
	ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN  
	LEFT OUTER JOIN PARA AS CZONA
	ON CZONA.CODICE = 'ZON'+CLI.CLI_ZONA 
	LEFT OUTER JOIN PARA AS CCODMERC
	ON CCODMERC.CODICE = 'GMI'+ARTAN.ART_CODGMI 
	LEFT OUTER JOIN PARA AS CCODGRU
	ON CCODGRU.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS CCODFAM
	ON CCODFAM.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS TIPORD
	ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN PARA AS CAUSAL
	ON CAUSAL.CODICE = 'TOP'+TT.ORD_CAUS
	WHERE DD.ORD_VALORE<>0
GO
