
-- VISTA GRUPPI_MAIL_CLIENTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GRUPPI_MAIL_CLIENTI]'))
	DROP VIEW [dbo].[GRUPPI_MAIL_CLIENTI]
GO

CREATE VIEW [dbo].[GRUPPI_MAIL_CLIENTI]  
AS
	SELECT
		CLI.CLI_CODCLI AS CODICE,
		CLI.CLI_RAGSOC AS RAG_SOCIALE,
		CLI.CLI_NAZION AS NAZIONE,
		CLI.CLI_EMAIL AS IND_EMAIL_ANAGR,
		COALESCE(EML_GEN.INDIRIZZO_A,'') AS IND_EMAIL_A_GEN,
		COALESCE(EML_OFF.INDIRIZZO_A,'') AS IND_EMAIL_A_OFF,
		COALESCE(EML_ORD.INDIRIZZO_A,'') AS IND_EMAIL_A_ORD,
		COALESCE(EML_BOL.INDIRIZZO_A,'') AS IND_EMAIL_A_BOL,
		COALESCE(EML_FAP.INDIRIZZO_A,'') AS IND_EMAIL_A_FAP,
		COALESCE(EML_FAT.INDIRIZZO_A,'') AS IND_EMAIL_A_FAT,
		COALESCE(EML_ORT.INDIRIZZO_A,'') AS IND_EMAIL_A_ORT,
		COALESCE(EML_REC.INDIRIZZO_A,'') AS IND_EMAIL_A_REC,
		COALESCE(EML_SOL.INDIRIZZO_A,'') AS IND_EMAIL_A_SOL
	FROM U_CLI_AN AS CLI
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_GEN ON EML_GEN.CLI_FOR = 'C' AND EML_GEN.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_GEN.TIPO_DOC = 'GEN'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_OFF ON EML_OFF.CLI_FOR = 'C' AND EML_OFF.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_OFF.TIPO_DOC = 'OFF'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_ORD ON EML_ORD.CLI_FOR = 'C' AND EML_ORD.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_ORD.TIPO_DOC = 'ORD'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_BOL ON EML_BOL.CLI_FOR = 'C' AND EML_BOL.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_BOL.TIPO_DOC = 'BOL'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_FAP ON EML_FAP.CLI_FOR = 'C' AND EML_FAP.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_FAP.TIPO_DOC = 'FAP'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_FAT ON EML_FAT.CLI_FOR = 'C' AND EML_FAT.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_FAT.TIPO_DOC = 'FAT'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_ORT ON EML_ORT.CLI_FOR = 'C' AND EML_ORT.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_ORT.TIPO_DOC = 'ORT'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_REC ON EML_REC.CLI_FOR = 'C' AND EML_REC.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_REC.TIPO_DOC = 'REC'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_SOL ON EML_SOL.CLI_FOR = 'C' AND EML_SOL.CODICE_CLI_FOR = CLI.CLI_CODCLI AND EML_SOL.TIPO_DOC = 'SOL'
