
-- VISTA V_CLI_AN PER STAMPE ANAGRAFICA CLIENTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[V_CLI_AN]'))
	DROP VIEW [dbo].[V_CLI_AN]
GO

CREATE VIEW [dbo].[V_CLI_AN]  
AS
	SELECT
		U_CLI_AN.CLI_CODSOC     ,
		U_CLI_AN.CLI_CODCLI     ,
		CLI_PARIVA     ,
		CLI_CODFIS     ,
		CLI_IVACEE     ,
		CLI_RAGSOC     ,
		CLI_RAGDUE     ,
		CLI_INDIR      ,
		CLI_CAP        ,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		CLI_LOCALI     ,
		CLI_NAZION     ,
		CLI_ZONA       ,
		CLI_AGE        ,
		CLI_TELEFO     ,
		CLI_FAX        ,
		CLI_TELEX      ,
		CLI_CONPAG     ,
		CLI_BAE        ,
		CLI_CODIVA     ,
		CLI_ALRID      ,
		CLI_LOCDOC     ,
		CLI_INDDOC     ,
		CLI_PORTO      ,
		CLI_MEZZO      ,
		CLI_VETTO1     ,
		CLI_VETTO2     ,
		CLI_VETTO3     ,
		CLI_BOLLI      ,
		CLI_VALUTA     ,
		CLI_SPINCA     ,
		CLI_NOTE       ,
		CLI_LISTIN     ,
		CLI_CONTO1     ,
		CLI_CONTO2     ,
		CLI_CONTO3     ,
		CLI_CONTO4     ,
		CLI_CONTO5     ,
		CLI_TRASME     ,
		CLI_PROVVI     ,
		CLI_DTCLOK     ,
		CLI_SC1        ,
		CLI_SC2        ,
		CLI_SC3        ,
		CLI_EMAIL      ,
		CLI_TIPFAT     ,
		CLI_CODIMB     ,
		CLI_PROVIN     ,
		CLI_DATINS     ,
		CLI_DATNEW     ,
		CLI_CDIBAN     ,
		CLI_LINGUA     ,
		CLI_SOTZONA    ,
		CLI_CLASSE     ,
		CLI_BAEFOR     ,
		CLI_IBAFOR     ,
		CLI_CCOST1     ,
		CLI_CCOST2     ,
		CLI_CCOST3     ,
		CLI_CCOST4     ,
		CLI_CCOST5     ,
		CLI_OBSOL      ,
		CLI_APPPRO     ,
		COALESCE(P_APPPRO.DESCRI,'') AS CLI_APPPRO_DESCR     ,
		cli_scinco     ,
		CLI_HOMPAG     ,
		COALESCE(CVEN_1_3.DESCRI,'') AS CANALE_VENDITA,
		COALESCE(CVEN_1_6.DESCRI,'') AS MACROCLASSE_CLIENTE,
		COALESCE(CVEN.DESCRI,'') AS CLASSE_CLIENTE,
		CLI_CANVEN AS COD_COMPL_CANALE_VENDITA
	FROM U_CLI_AN
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = U_CLI_AN.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+U_CLI_AN.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	LEFT OUTER JOIN PARA AS P_APPPRO ON P_APPPRO.CODICE = 'APP'+U_CLI_AN.CLI_APPPRO

GO
