-- VISTA BILANCIO_P-E_MULTILIVELLO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VISTA_BILANCIO_P_E_MLIV]'))
	DROP VIEW [dbo].[VISTA_BILANCIO_P_E_MLIV]
GO

CREATE VIEW [dbo].[VISTA_BILANCIO_P_E_MLIV]
AS

SELECT
	ANNO,
	LIVELLO,
	CONTO,
	DESCR,
	HAS_CHILDREN,
	DARE,
	AVERE,
	PADRE,
	DESCR_PADRE,
	DARE_PADRE,
	AVERE_PADRE,
	TIPOCO,
	CASE
		WHEN TIPOCO IN ('C','F') THEN 'S'
		WHEN HAS_CHILDREN = 'S' AND TIPOCO_SON IN ('C','F') THEN 'S'
		ELSE 'N'
	END AS CLI_FOR,
	CASE
		WHEN TIPOCO IN ('O') THEN 'S'
		WHEN HAS_CHILDREN = 'S' AND CONTA_FIGLI_C_ORD > 0 THEN 'S'
		ELSE 'N'
	END AS C_ORD,
	POSBIL,
	TIPO_CONTO,
	RIGHT('000' + REPLACE(SUBSTRING(CONTO,1,FIRST_DOT_INDEX),'.',''),3) AS ORDINE1,
	CASE
		WHEN SECOND_DOT_INDEX-FIRST_DOT_INDEX > 0 THEN RIGHT('000' + REPLACE(SUBSTRING(CONTO,FIRST_DOT_INDEX+1,SECOND_DOT_INDEX-FIRST_DOT_INDEX),'.',''),3)
		ELSE '000'
	END AS ORDINE2,
	CASE
		WHEN THIRD_DOT_INDEX-SECOND_DOT_INDEX > 0 THEN RIGHT('000' + REPLACE(SUBSTRING(CONTO,SECOND_DOT_INDEX+1,THIRD_DOT_INDEX-SECOND_DOT_INDEX),'.',''),3)
		ELSE '000'
	END AS ORDINE3,
	CASE
		WHEN TIPOCO IN ('C','F') AND RIGHT(CONTO,1) <> '.' THEN substring(DESCR,1,10)
		WHEN FOURTH_DOT_INDEX-THIRD_DOT_INDEX > 0 THEN RIGHT('0000000000' + REPLACE(SUBSTRING(CONTO,THIRD_DOT_INDEX+1,FOURTH_DOT_INDEX-THIRD_DOT_INDEX),'.',''),10)
		ELSE '0000000000'
	END AS ORDINE4,
	CASE
		WHEN TIPOCO IN ('C','F') AND RIGHT(CONTO,1) <> '.' THEN substring(DESCR,1,10)
		WHEN FIFTH_DOT_INDEX-FOURTH_DOT_INDEX > 0 THEN RIGHT('0000000000' + REPLACE(SUBSTRING(CONTO,FOURTH_DOT_INDEX+1,FIFTH_DOT_INDEX-FOURTH_DOT_INDEX),'.',''),10)
		ELSE '0000000000'
	END AS ORDINE5,
	CASE
		WHEN TIPOCO IN ('C','F') AND RIGHT(CONTO,1) <> '.' THEN substring(DESCR,1,10)
		WHEN SIXTH_DOT_INDEX-FIFTH_DOT_INDEX > 0 THEN RIGHT('0000000000' + REPLACE(SUBSTRING(CONTO,FIFTH_DOT_INDEX+1,SIXTH_DOT_INDEX-FIFTH_DOT_INDEX),'.',''),10)
		ELSE '0000000000'
	END AS ORDINE6
FROM (
	SELECT
		MAIN.CON_ANNO AS ANNO,
		LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END AS LIVELLO,
		RTRIM(MAIN.CON_CONTO) AS CONTO,
		RTRIM(MAIN.CON_DESCR) AS DESCR,
		CASE
			WHEN (COALESCE(SON.CON_CONTO,'') = '' OR RIGHT(RTRIM(MAIN.CON_CONTO),1) <> '.') THEN 'N'
			ELSE 'S'
		END AS HAS_CHILDREN,
		CASE
			WHEN ROUND(MAIN.CON_IMP_D - MAIN.CON_IMP_A,2) > 0 THEN ROUND(MAIN.CON_IMP_D - MAIN.CON_IMP_A,2)
			ELSE 0
		END AS DARE,
		CASE
			WHEN ROUND(MAIN.CON_IMP_A - MAIN.CON_IMP_D,2) > 0 THEN ROUND(MAIN.CON_IMP_A - MAIN.CON_IMP_D,2)
			ELSE 0
		END AS AVERE,
		COALESCE(FATHER.CON_CONTO,'') AS PADRE,
		COALESCE(FATHER.CON_DESCR,'') AS DESCR_PADRE,
		CASE
			WHEN ROUND(COALESCE(FATHER.CON_IMP_D,0) - COALESCE(FATHER.CON_IMP_A,0),2) > 0 THEN ROUND(COALESCE(FATHER.CON_IMP_D,0) - COALESCE(FATHER.CON_IMP_A,0),2)
			ELSE 0
		END AS DARE_PADRE,
		CASE
			WHEN ROUND(COALESCE(FATHER.CON_IMP_A,0) - COALESCE(FATHER.CON_IMP_D,0),2) > 0 THEN ROUND(COALESCE(FATHER.CON_IMP_A,0) - COALESCE(FATHER.CON_IMP_D,0),2)
			ELSE 0
		END AS AVERE_PADRE,

		--COALESCE(SOTTOGRUPPO.CON_CONTO,'') AS SOTTOGRUPPO,
		--COALESCE(SOTTOGRUPPO.CON_DESCR,'') AS DESCR_SOTTOGRUPPO,
		--CASE
		--	WHEN ROUND(COALESCE(SOTTOGRUPPO.CON_IMP_D,0) - COALESCE(SOTTOGRUPPO.CON_IMP_A,0),2) > 0 THEN ROUND(COALESCE(SOTTOGRUPPO.CON_IMP_D,0) - COALESCE(SOTTOGRUPPO.CON_IMP_A,0),2)
		--	ELSE 0
		--END AS DARE_SOTTOGRUPPO,
		--CASE
		--	WHEN ROUND(COALESCE(SOTTOGRUPPO.CON_IMP_A,0) - COALESCE(SOTTOGRUPPO.CON_IMP_D,0),2) > 0 THEN ROUND(COALESCE(SOTTOGRUPPO.CON_IMP_A,0) - COALESCE(SOTTOGRUPPO.CON_IMP_D,0),2)
		--	ELSE 0
		--END AS AVERE_SOTTOGRUPPO,

		--COALESCE(GRUPPO.CON_CONTO,'') AS GRUPPO,
		--COALESCE(GRUPPO.CON_DESCR,'') AS DESCR_GRUPPO,
		--CASE
		--	WHEN ROUND(COALESCE(GRUPPO.CON_IMP_D,0) - COALESCE(GRUPPO.CON_IMP_A,0),2) > 0 THEN ROUND(COALESCE(GRUPPO.CON_IMP_D,0) - COALESCE(GRUPPO.CON_IMP_A,0),2)
		--	ELSE 0
		--END AS DARE_GRUPPO,
		--CASE
		--	WHEN ROUND(COALESCE(GRUPPO.CON_IMP_A,0) - COALESCE(GRUPPO.CON_IMP_D,0),2) > 0 THEN ROUND(COALESCE(GRUPPO.CON_IMP_A,0) - COALESCE(GRUPPO.CON_IMP_D,0),2)
		--	ELSE 0
		--END AS AVERE_GRUPPO,
		MAIN.CON_TIPOCO AS TIPOCO,
		COALESCE(SON.CON_TIPOCO,'') AS TIPOCO_SON,
		SONS_C_ORD.CONTA_FIGLI_C_ORD AS CONTA_FIGLI_C_ORD,
		MAIN.CON_POSBIL AS POSBIL,
		MAIN.CON_TIPO_CONTO AS TIPO_CONTO,
		CHARINDEX('.', RTRIM(MAIN.CON_CONTO)) AS FIRST_DOT_INDEX,
		CASE
			WHEN (LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END) >=2
			THEN CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END) + 1) 
			ELSE 0
		END AS SECOND_DOT_INDEX,
		CASE
			WHEN (LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END) >=3
			THEN CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END) + 1) + 1)
			ELSE 0
		END AS THIRD_DOT_INDEX,
		CASE
			WHEN (LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END) >=4
			THEN CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END) + 1) + 1) + 1)
			ELSE 0
		END AS FOURTH_DOT_INDEX,
		CASE
			WHEN (LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END) >=5
			THEN CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END) + 1) + 1) + 1) + 1) 
			ELSE 0
		END AS FIFTH_DOT_INDEX,
		CASE
			WHEN (LEN(RTRIM(MAIN.CON_CONTO)) - LEN(REPLACE(RTRIM(MAIN.CON_CONTO),'.','')) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN 0 ELSE 1 END) >=6
			THEN CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END, CHARINDEX('.', RTRIM(MAIN.CON_CONTO) + CASE RIGHT(RTRIM(MAIN.CON_CONTO),1) WHEN '.' THEN '' ELSE '.' END) + 1) + 1) + 1) + 1) + 1)
			ELSE 0
		END  AS SIXTH_DOT_INDEX
	FROM CONTI AS MAIN
	--OUTER APPLY (SELECT TOP 1 CON_ANNO,CON_CONTO,CON_DESCR,CON_IMP_A,CON_IMP_D FROM CONTI WHERE CON_ANNO = MAIN.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(MAIN.CON_CONTO) AND RTRIM(MAIN.CON_CONTO) LIKE RTRIM(CON_CONTO)+'%' 
	--	AND RIGHT(RTRIM(CON_CONTO),1) = '.' ORDER BY CON_CONTO DESC) AS FATHER
	LEFT OUTER JOIN CONTI AS FATHER ON FATHER.CON_ANNO = MAIN.CON_ANNO AND FATHER.CON_CONTO = MAIN.CON_CODPADRE  -- ERASMO - 09/05/2025 - OTTIMIZZAZIONE CON INTRODUZIONE CAMPO CONTI.CON_CODPADRE
	--OUTER APPLY (SELECT TOP 1 CON_ANNO,CON_CONTO,CON_DESCR,CON_IMP_A,CON_IMP_D FROM CONTI WHERE CON_ANNO = FATHER.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(FATHER.CON_CONTO) AND RTRIM(FATHER.CON_CONTO) LIKE RTRIM(CON_CONTO)+'%' 
	--	AND RIGHT(RTRIM(CON_CONTO),1) = '.' ORDER BY CON_CONTO DESC) AS SOTTOGRUPPO
	--OUTER APPLY (SELECT TOP 1 CON_ANNO,CON_CONTO,CON_DESCR,CON_IMP_A,CON_IMP_D FROM CONTI WHERE CON_ANNO = SOTTOGRUPPO.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(SOTTOGRUPPO.CON_CONTO) AND RTRIM(SOTTOGRUPPO.CON_CONTO) LIKE RTRIM(CON_CONTO)+'%' 
	--	AND RIGHT(RTRIM(CON_CONTO),1) = '.' ORDER BY CON_CONTO DESC) AS GRUPPO
	OUTER APPLY (SELECT TOP 1 CON_ANNO,CON_CONTO,CON_DESCR,CON_TIPOCO FROM CONTI WHERE CON_ANNO = MAIN.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(MAIN.CON_CONTO) AND RTRIM(CON_CONTO) LIKE RTRIM(MAIN.CON_CONTO)+'%' ORDER BY CON_CONTO DESC) AS SON
	OUTER APPLY (SELECT COUNT(*) AS CONTA_FIGLI_C_ORD FROM CONTI WHERE CON_ANNO = MAIN.CON_ANNO AND RTRIM(CON_CONTO) <> RTRIM(MAIN.CON_CONTO) AND RTRIM(CON_CONTO) LIKE RTRIM(MAIN.CON_CONTO)+'%' AND CON_TIPOCO IN ('O')) AS SONS_C_ORD
	--WHERE COALESCE(SON.CON_CONTO,'') = '' AND COALESCE(FATHER.CON_CONTO,'') <> ''
	) AS MAIN

GO


/*
-- QUERY X BILANCIO P/E (SOLO CONTI SEMPLICI CON SALDO <> 0)
SELECT * FROM [VISTA_BILANCIO_P_E_MLIV] WHERE ANNO = '2021' AND HAS_CHILDREN = 'N' AND DARE+AVERE > 0 AND TIPOCO <> 'O' AND POSBIL IN ('P','E') ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4

-- QUERY X RIEPILOGO
-- ATTIVO
SELECT 'ATTIVO' AS TIPOREC,* FROM VISTA_BILANCIO_P_E_MLIV WHERE ANNO = '2021' AND DARE+AVERE > 0 AND TIPOCO <> 'O' AND TIPO_CONTO = 1  AND PADRE <> '' AND PADRE = GRUPPO ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4
-- PASSIVO
SELECT 'PASSIVO' AS TIPOREC,* FROM VISTA_BILANCIO_P_E_MLIV WHERE ANNO = '2021' AND DARE+AVERE > 0 AND TIPOCO <> 'O' AND TIPO_CONTO IN (2,0)  AND PADRE <> '' AND PADRE = GRUPPO ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4

-- RICAVI
SELECT 'RICAVI' AS TIPOREC,* FROM VISTA_BILANCIO_P_E_MLIV WHERE ANNO = '2021' AND DARE+AVERE > 0 AND TIPOCO <> 'O' AND TIPO_CONTO = 3  AND PADRE <> '' AND PADRE = GRUPPO ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4
-- COSTI
SELECT 'COSTI' AS TIPOREC,* FROM VISTA_BILANCIO_P_E_MLIV WHERE ANNO = '2021' AND DARE+AVERE > 0 AND TIPOCO <> 'O' AND TIPO_CONTO = 4  AND PADRE <> '' AND PADRE = GRUPPO ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4

-- CONTI D'ORDINE
SELECT 'CONTI D''ORDINE' AS TIPOREC,* FROM VISTA_BILANCIO_P_E_MLIV WHERE ANNO = '2021' AND TIPOCO = 'O' AND PADRE <> '' AND PADRE = GRUPPO ORDER BY ORDINE1,ORDINE2,ORDINE3,ORDINE4

*/