
WAIT WINDOWS "Sto cancellando i .FXP e ricompilando i .PRG"  NOWAIT
ERASE PRG\*.FXP
ERASE PRG\*.BAK
COMPILE PRG\*.PRG

ERASE RICERCHE\*.FXP
ERASE RICERCHE\*.BAK
COMPILE RICERCHE\*.PRG

WAIT WINDOWS "Sto compilando Aq_movimaga_scarico" NOWAIT
BUILD EXE AQ_MOVIMAGA_SCARICO FROM AQ_MOVIMAGA_SCARICO
        
WAIT WINDOWS "Fine compilazione progetti" NOWAIT
