WAIT WINDOWS "Stò cancellando i .FXP e ricompilando i .PRG"  NOWAIT
ERASE PRG\*.FXP
ERASE PRG\*.BAK
COMPILE PRG\*.PRG

ERASE RICERCHE\*.FXP
ERASE RICERCHE\*.BAK
COMPILE RICERCHE\*.PRG

WAIT WINDOWS "Stò compilando il MUT" NOWAIT
BUILD EXE MUT FROM MUT
        
WAIT WINDOWS "Fine compilazione MUT" NOWAIT
