
WAIT WINDOWS "Sto cancellando i .FXP e ricompilando i .PRG"  NOWAIT
ERASE PRG\*.FXP
ERASE PRG\*.BAK
COMPILE PRG\*.PRG

ERASE RICERCHE\*.FXP
ERASE RICERCHE\*.BAK
COMPILE RICERCHE\*.PRG

WAIT WINDOWS "Sto compilando Aq_dadi" NOWAIT
BUILD EXE AQ_DADI FROM AQ_DADI
        
WAIT WINDOWS "Fine compilazione progetti" NOWAIT
