--SELECT * FROM U_ART_PR WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CBOVUO = '')

SELECT 
	'UPDATE U_ART_AN SET ART_CODPRI = '''+NEW_CODPRI+''' WHERE ART_CODPRI = '''+ART_CODPRI+'''' AS SCRIPT_AN_ART_CODPRI,
	'UPDATE U_ART_PR SET ART_CODPRI = '''+NEW_CODPRI+''' WHERE ART_CODPRI = '''+ART_CODPRI+'''' AS SCRIPT_PR_ART_CODPRI,
	'UPDATE U_ART_PR SET ART_DESCR = '''+NEW_DESCR+''' WHERE ART_CODPRI = '''+NEW_CODPRI+'''' AS SCRIPT_PR_ART_DESCR
FROM (
	SELECT 
		RTRIM(AN.ART_CODPRI) AS ART_CODPRI,
		RTRIM(SUBSTRING(AN.ART_CBOVUO,1,12))
			+ CASE PR.ART_CODTAG WHEN '' THEN '' ELSE '.'+RTRIM(PR.ART_CODTAG) END
			+ CASE PR.ART_CODCOL WHEN '' THEN '' ELSE '.'+RTRIM(PR.ART_CODCOL) END
			+ CASE AN.ART_TIPOG WHEN '' THEN '' ELSE '.'+RTRIM(AN.ART_TIPOG) END
			+ CASE AN.ART_CODCOLRET WHEN '' THEN '' ELSE '.'+RTRIM(AN.ART_CODCOLRET) END
			+ CASE AN.ART_TIPON WHEN '' THEN '' ELSE '.'+RTRIM(AN.ART_TIPON) END
			AS NEW_CODPRI,
		PR.ART_DESCR,
		RTRIM(PR_BASE.ART_DESCR)
			+ CASE PR.ART_CODTAG WHEN '' THEN '' ELSE ' '+COALESCE(RTRIM(PTAG.DESCRI),'') END
			+ CASE PR.ART_CODCOL WHEN '' THEN '' ELSE ' '+COALESCE(RTRIM(PCOLA.DESCRI),'') END
			+ CASE AN.ART_TIPOG WHEN '' THEN '' ELSE ' '+COALESCE(RTRIM(PTIG.DESCRI),'') END
			+ CASE WHEN AN.ART_CODCOLRET <> '' OR AN.ART_TIPON <> '' THEN ' /' ELSE '' END
			+ CASE AN.ART_CODCOLRET WHEN '' THEN '' ELSE ' '+COALESCE(RTRIM(PCOLB.DESCRI),'') END
			+ CASE AN.ART_TIPON WHEN '' THEN '' ELSE ' '+COALESCE(RTRIM(PTNO.DESCRI),'') END
			AS NEW_DESCR
	FROM U_ART_AN AS AN
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = AN.ART_CODPRI
	LEFT OUTER JOIN U_ART_PR AS PR_BASE ON PR_BASE.ART_CODPRI = AN.ART_CBOVUO
	LEFT OUTER JOIN PARA AS PTAG ON PTAG.CODICE = 'TAG'+PR.ART_CODTAG 
	LEFT OUTER JOIN PARA AS PCOLA ON PCOLA.CODICE = 'COL'+PR.ART_CODCOL 
	LEFT OUTER JOIN PARA AS PCOLB ON PCOLB.CODICE = 'COL'+AN.ART_CODCOLRET 
	LEFT OUTER JOIN PARA AS PTIG ON PTIG.CODICE = 'TIG'+AN.ART_TIPOG 
	LEFT OUTER JOIN PARA AS PTNO ON PTNO.CODICE = 'TNO'+AN.ART_TIPON 
	WHERE ART_CBOVUO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CBOVUO = '')) --ORDER BY ART_CODPRI
) AS MAIN