
-- SETTAGGIO CONTI DI CHIUSURA/APERTURA BILANCIO

/*
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%UTILE%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%PERDIT%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%PROFIT%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%APERT%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%CHIUSU%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%ARROT%'
*/

UPDATE CHIUSURA SET
	FIN_UTIESE = '3.20.',
	FIN_PERESE = '1.10.',
	FIN_PROPER = '6.1.',
	FIN_BILAPE = '7.1.',
	FIN_BILCHI = '7.2.',
	FIN_RISARR = '4.6.3.3.'
WHERE 1=1

SELECT * FROM chiusura