
-- SETTAGGIO CONTI DI CHIUSURA/APERTURA BILANCIO

/*
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%UTILE%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%PERDITE ESER%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%PROF%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%APE%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%CHIUSU%'
SELECT * FROM CONTI WHERE CON_DESCR LIKE '%PASSIVI%'
*/

UPDATE CHIUSURA SET
	FIN_UTIESE = '3.20.',
	FIN_PERESE = '1.19.1.',
	FIN_PROPER = '6.1.',
	FIN_BILAPE = '7.1.',
	FIN_BILCHI = '7.2.',
	FIN_RISARR = '4.20.23.'
WHERE 1=1

SELECT * FROM chiusura