
-- VISTA TIMESHEET RAGGRUPPATI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TIMESHEET_RAGGRUPPATI]'))
	DROP VIEW [dbo].[TIMESHEET_RAGGRUPPATI]
GO

CREATE VIEW [dbo].[TIMESHEET_RAGGRUPPATI]  
AS
	SELECT
		ANNO,
		MESE,
		CODRIS,
		DESRIS,
		CAST(ROUND(SUM(ORE_ORDINA + MIN_ORDINA / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_ORDINARIE,
		CAST(ROUND(SUM(ORE_STRAOR + MIN_STRAOR / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_STRAORDINARIE,
		CAST(ROUND(SUM(ORE_ROL + MIN_ROL / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_ROL,
		CAST(ROUND(SUM(ORE_FERIE + MIN_FERIE / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_FERIE,
		CAST(ROUND(SUM(ORE_MALATT + MIN_MALATT / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_MALATT,
		CAST(ROUND(SUM(ORE_ALTRO + MIN_ALTRO / 60),2) AS NUMERIC(10,2)) AS TOTALE_ORE_ALTRO
	FROM TIMESHT
	GROUP BY
		ANNO,
		MESE,
		CODRIS,
		DESRIS

GO