/*SELECT 
DISTINCT MOV_CONTO AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)





SELECT 
DISTINCT SUBSTRING(MOV_CONTO,1,4) AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE SUBSTRING(MOV_CONTO,1,4) NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)


SELECT 
DISTINCT SUBSTRING(MOV_CONTO,1,2) AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE SUBSTRING(MOV_CONTO,1,2) NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)
*/



INSERT INTO CONTI (CON_CONTO,CON_ANNO,CON_DESCR,CON_POSBIL,CON_TIPOCO,CON_SOC)
SELECT 
DISTINCT MOV_CONTO AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=MOV_CONTO ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)


INSERT INTO CONTI (CON_CONTO,CON_ANNO,CON_DESCR,CON_POSBIL,CON_TIPOCO,CON_SOC)
SELECT 
DISTINCT SUBSTRING(MOV_CONTO,1,4) AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,4) ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE SUBSTRING(MOV_CONTO,1,4) NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)


INSERT INTO CONTI (CON_CONTO,CON_ANNO,CON_DESCR,CON_POSBIL,CON_TIPOCO,CON_SOC)
SELECT 
DISTINCT SUBSTRING(MOV_CONTO,1,2) AS CON_CONTO, 
MOV_ANNO AS CON_ANNO,
(select top 1 CON_DESCR from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_DESCR,
(select top 1 CON_POSBIL from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_POSBIL, 
(select top 1 CON_TIPOCO from CONTI WHERE CON_CONTO=SUBSTRING(MOV_CONTO,1,2) ORDER BY CON_ANNO DESC) as CON_TIPOCO,
'01' AS CON_SOC
FROM MOV_CONT 
WHERE SUBSTRING(MOV_CONTO,1,2) NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO =MOV_ANNO)