
-- VISTA FATTURE_CON_BOLLO_VIRT
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_CON_BOLLO_VIRT]'))
	DROP VIEW [dbo].[FATTURE_CON_BOLLO_VIRT]
GO
CREATE VIEW [dbo].[FATTURE_CON_BOLLO_VIRT]
AS
	SELECT 
		SUBSTRING(ORD_DATORD,1,4) AS ANNO,
		CASE
			WHEN SUBSTRING(ORD_DATORD,6,2) BETWEEN '01' AND '03' THEN '1'
			WHEN SUBSTRING(ORD_DATORD,6,2) BETWEEN '04' AND '06' THEN '2'
			WHEN SUBSTRING(ORD_DATORD,6,2) BETWEEN '07' AND '09' THEN '3'
			WHEN SUBSTRING(ORD_DATORD,6,2) BETWEEN '10' AND '12' THEN '4'
			ELSE '0'
		END +'/'+SUBSTRING(ORD_DATORD,1,4) AS TRIMESTRE,
		ORD_NUMORD AS NR_FATTURA,
		ORD_DATORD AS DATA_FATTURA,
		ORD_CODCLI AS COD_CLIENTE,
		ORD_RAGSOC AS RAG_SOCIALE,
		ORD_VALORE AS IMPORTO_FATTURA,
		ORD_BOVIRT AS IMPORTO_BOLLO
	FROM U_FAT_TT
	WHERE ORD_BOVIRT > 0
GO

SELECT * FROM FATTURE_CON_BOLLO_VIRT ORDER BY ANNO,TRIMESTRE,NR_FATTURA