SELECT COUNT(*) FROM LOGSQL
SELECT * FROM LOGSQL ORDER BY TIME DESC
SELECT * FROM LOGSQL ORDER BY TIMESTAMP DESC
SELECT * FROM LOGSQL ORDER BY CurrentProgramFilename, TIMESTAMP
SELECT * FROM LOGSQL ORDER BY TIME,WORKSTAT DESC
SELECT TIME/60 AS TIME_MINUTI,CSQL,CurrentProgramFilename,* FROM LOGSQL where TIMESTAMP >= '2022-07-01 00:00:00.000' ORDER BY TIME DESC
SELECT TIME/60 AS TIME_MINUTI,CSQL,CurrentProgramFilename,* FROM LOGSQL where TIMESTAMP >= '2022-07-01 00:00:00.000' and CurrentProgramFilename = 'alertlib.fxp' ORDER BY TIME DESC


select
	CurrentProgramFilename,
	SUBSTRING(CSQL,1,8000) AS CSQL_STR,
	COUNT(*) AS NR_ESECUZIONI,
	MAX(TIME)/60 AS TIME_MINUTI_MAX
FROM LOGSQL
where TIMESTAMP >= '2022-07-01 00:00:00.000'
GROUP BY CurrentProgramFilename,SUBSTRING(CSQL,1,8000)
ORDER BY NR_ESECUZIONI DESC



