
delete from para where codice like 'CVE%'
or codice like 'TPO%'
or codice like 'RUO%'
or codice like 'TEV%'
or codice like 'LNG%'
or codice like 'FSD%'
or codice like 'CPL%'
or codice like 'TPA%'
or codice like 'SOL%'
or codice like 'AML%'
or codice like 'CDC%'
or codice like 'CPL%'
or codice like 'CST%'
or codice like 'CTC%'
or codice like 'CTE%'
or codice like 'CTF%'
or codice like 'CTZ%'
or codice like 'DBI%'
or codice like 'DCA%'
or codice like 'DIS%'
or codice like 'F24%'
or codice like 'FLU%'
or codice like 'FRZ%'
or codice like 'FUN%'
or codice like 'GLF%'
or codice like 'PIP%'
or codice like 'PLA%'
or codice like 'POL%'
or codice like 'RAC%'
or codice like 'RES%'
or codice like 'RIA%'
or codice like 'SEC%'
or codice like 'TMR%'


INSERT INTO PARA
select * from para_old where
codice like 'CVE%'
or codice like 'TPO%'
or codice like 'RUO%'
or codice like 'TEV%'
or codice like 'LNG%'
or codice like 'FSD%'
or codice like 'CPL%'
or codice like 'TPA%'
or codice like 'SOL%'
or codice like 'AML%'
or codice like 'CDC%'
or codice like 'CPL%'
or codice like 'CST%'
or codice like 'CTC%'
or codice like 'CTE%'
or codice like 'CTF%'
or codice like 'CTZ%'
or codice like 'DBI%'
or codice like 'DCA%'
or codice like 'DIS%'
or codice like 'F24%'
or codice like 'FLU%'
or codice like 'FRZ%'
or codice like 'FUN%'
or codice like 'GLF%'
or codice like 'PIP%'
or codice like 'PLA%'
or codice like 'POL%'
or codice like 'RAC%'
or codice like 'RES%'
or codice like 'RIA%'
or codice like 'SEC%'
or codice like 'TMR%'