
SELECT ART_CODPRI, ART_CODGMI, ART_CGEACQ, LIBERA FROM U_ART_AN 
LEFT OUTER JOIN PARA ON PARA.CODICE = 'GMI'+U_ART_AN.ART_CODGMI
WHERE LIBERA NOT LIKE '%CONTO_COSTO: '+RTRIM(U_ART_AN.art_cgeacq)+'%' AND LIBERA <> '' AND ART_CGEACQ <> ''
ORDER BY ART_CODPRI