
DECLARE @_ANNO AS VARCHAR(4)
SET @_ANNO = '2025'

--SELECT * FROM PARA WHERE CODICE LIKE 'ANN01%'

--SELECT * FROM PARA WHERE CODICE = 'ANN01'+@_ANNO
--DELETE FROM PARA WHERE CODICE = 'ANN01'+@_ANNO

--SELECT * FROM CONTI WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO
--DELETE FROM CONTI WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO

--SELECT * FROM CCOSTO WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO
--DELETE FROM CCOSTO WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO

--SELECT * FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'01'
--SELECT * FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'011'
--SELECT * FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'012'

--DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'01'
--DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'011'
--DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'012'

--SELECT * FROM PARA WHERE CODICE = 'NUMREG'+@_ANNO+'01'
--DELETE FROM PARA WHERE CODICE = 'NUMREG'+@_ANNO+'01'

--SELECT * FROM PARA WHERE CODICE = 'NUMREP'+@_ANNO+'01'
--DELETE FROM PARA WHERE CODICE = 'NUMREP'+@_ANNO+'01'


--SELECT * FROM U_IVA_CR WHERE IVA_CODSOC = '01' AND iva_anno = @_ANNO
--DELETE FROM U_IVA_CR WHERE IVA_CODSOC = '01' AND iva_anno = @_ANNO

--SELECT * FROM U_VVA_CH WHERE VVA_CODSOC = '01' AND SUBSTRING(VVA_DATA,1,4) = @_ANNO
--DELETE FROM U_VVA_CH WHERE VVA_CODSOC = '01' AND SUBSTRING(VVA_DATA,1,4) = @_ANNO

/*
SELECT * FROM PARA WHERE CODICE = 'NUMFAT'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMFVS'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMFEL'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMFAD'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMNCR'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMFAP'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMOFF'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMORD'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMORF'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMBOL'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMBOE'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMINR'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMRIC'+@_ANNO+'01'
SELECT * FROM PARA WHERE CODICE = 'NUMRLII'+@_ANNO+'01'
*/

/*
DELETE FROM PARA WHERE CODICE = 'ANN01'+@_ANNO

DELETE FROM CONTI WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO

DELETE FROM CCOSTO WHERE CON_SOC = '01' AND CON_ANNO = @_ANNO

DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'011'
DELETE FROM PARA WHERE CODICE = 'NUMPRO'+@_ANNO+'012'

DELETE FROM PARA WHERE CODICE = 'NUMREG'+@_ANNO+'01'

DELETE FROM PARA WHERE CODICE = 'NUMREP'+@_ANNO+'01'

DELETE FROM U_IVA_CR WHERE IVA_CODSOC = '01' AND iva_anno = @_ANNO

DELETE FROM U_VVA_CH WHERE VVA_CODSOC = '01' AND SUBSTRING(VVA_DATA,1,4) = @_ANNO

DELETE FROM PARA WHERE CODICE = 'NUMFAT'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMFVS'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMFEL'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMFAD'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMNCR'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMFAP'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMOFF'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMORD'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMORF'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMBOL'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMBOE'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMINR'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMRIC'+@_ANNO+'01'
DELETE FROM PARA WHERE CODICE = 'NUMRLII'+@_ANNO+'01'
*/
