/**** cancellazione di tutti gli utenti ****/

DELETE FROM UTENTI

/**** inserimento utenti da RISUMANA ****/

INSERT INTO UTENTI
	(USERID,
	PASSWORD,
	RUOLO,
	COGNOME,
	NOME,
	EMAIL,
	DATA,
	SC_FLAG,
	SCADENZA)
SELECT LOWER(SUBSTRING(NOME,1,PATINDEX('% %',NOME)-1)+SUBSTRING(COGNOME,1,1)) AS USERID,
    LOWER(SUBSTRING(NOME,1,PATINDEX('% %',NOME)-1)+SUBSTRING(COGNOME,1,1)) AS PASSWORD,
	'U' AS RUOLO,
	COGNOME,
	NOME,
	EMAIL,
	'2010/12/01' AS DATA,
	'0' AS SC_FLAG ,
	60  AS SCADENZA 
FROM RISUMANA


/**** inserimento utente admin ****/

INSERT INTO UTENTI
	(USERID,
	PASSWORD,
	RUOLO,
	EMAIL,
	DATA,
	SC_FLAG,
	SCADENZA)
SELECT 'admin' AS USERID,
    'password' AS PASSWORD,
	'U' AS RUOLO,
	''  AS EMAIL,
	'2010/12/01' AS DATA,
	'0' AS SC_FLAG ,
	60  AS SCADENZA 




/**** aggiorna userid su risumana ****/
UPDATE RISUMANA SET USERID = LOWER(SUBSTRING(NOME,1,PATINDEX('% %',NOME)-1)+SUBSTRING(COGNOME,1,1))
