
SELECT ORD_SYSRINT,ORD_NOTERIC,* FROM IMPIANTI_RI ORDER BY ORD_DATA DESC

SELECT ORD_SYSRINT,ORD_NOTERIC,* FROM IMPIANTI_RI WHERE ORD_CODRIC = '00006' ORDER BY ORD_DATA 
SELECT ORD_NUMORD,TAGGANCIO,ORD_SYSRINT AS _SYSRINT,ORD_CCODSCHE,* FROM VENDITE_TT WHERE ORD_NUMORD = '000139'  ORDER BY ORD_DATORD 

UPDATE VENDITE_TT SET ORD_SYSRINT = '_6O11EM42L'WHERE TAGGANCIO = '1000000316'

SELECT ORD_NUMORD,TAGGANCIO,ORD_SYSRINT AS _SYSRINT,ORD_CCODSCHE,* FROM VENDITE_TT  ORDER BY ORD_DATORD DESC



SELECT TAGGANCIO,ORD_SYSRINT AS _SYSRINT,ORD_CCODSCHE,* FROM VENDITE_TT WHERE ORD_SYSRINT <> ''  ORDER BY ORD_NUMORD DESC

SELECT * FROM VENDITE_DT ORDER BY ORD_NUMORD DESC

SELECT * FROM VENDITE_DT WHERE DAGGANCIO = '1000000173'

SELECT ORD_SYSRINT,ORD_NOTERIC,* FROM IMPIANTI_RI WHERE ORD_SYSRINT = '_6HZ0WWDZR'

SELECT * FROM IMPIANTI_TT 