
SELECT CINIZCONTR,CSCADCONTR,DT_INIZIO,DT_FINE,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.GAVERRI' ORDER BY TIPO_COMPONENTE
SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.GAVERRI' ORDER BY TIPO_COMPONENTE



SELECT ORD_INTCLOSE,ORD_DATORD,* FROM VENDITE_TT WHERE ORD_DATORD > '2023/06/01' ORDER BY ORD_NUMORD
UPDATE VENDITE_TT SET ORD_INTCLOSE = 1 WHERE ID_UNIQUE = 'D579E313-454B-4CB5-B78E-42AA8BCF9401'
UPDATE VENDITE_TT SET ORD_INTCLOSE = 1 WHERE ID_UNIQUE = 'EA8FEED8-9745-4D12-8BF8-F5543F48BB10'


