
SELECT * FROM IMPIANTI_CO ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE
SELECT GRUPPO,* FROM IMPIANTI_DD ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE


SELECT GRUPPO,CDITTACAL,CMATCAL,CMODCAL,CNOTECONTR,* FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE
SELECT GRUPPO,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE

SELECT CCODSCHE,ID_RIGO,TIPO_COMPONENTE,CONTR_A,CA,CQTA_A,CCOSTOA,CSCAD_A,* FROM IMPIANTI_CO WHERE CCODSCHE = 'TREV.C.INSURREZIONE'


SELECT TIPO_COMPONENTE AS TIPO_COMPON,CDITTACAL,CMATCAL,CMODCAL,DT_INSTALL,* FROM IMPIANTI_DD WHERE CCODSCHE = 'TREV.C.INSURREZIONE' ORDER BY TIPO_COMPONENTE

SELECT	* from IMPIANTI_CO AS CONTR 
		INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where CONTR.ID_PMKEY =  SCHE.ID_PMKEY  order by SCHE.ID_PMKEY


SELECT * FROM IMPIANTI_CO

SELECT	* from IMPIANTI_CO AS CONTR 
		INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where  CONTR.CCODSCHE = 'TREV.C.INSURREZIONE'  order by CONTR.ID_PMKEY



SELECT TIPO_COMPONENTE AS TIPO_COMPON,CDITTACAL,CMATCAL,CMODCAL,DT_INSTALL,* FROM IMPIANTI_DD WHERE id_pmkey = '1' and tipo_componente = '001' and ID_RIGO = '00010'