
SELECT * FROM IMPIANTI_CO ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE
SELECT GRUPPO,* FROM IMPIANTI_DD ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE


SELECT GRUPPO,CDITTACAL,CMATCAL,CMODCAL,CNOTECONTR,* FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE
SELECT GRUPPO,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE,ID_RIGO,TIPO_COMPONENTE

SELECT CCODSCHE,ID_RIGO,TIPO_COMPONENTE,CONTR_A,CA,CQTA_A,CCOSTOA,CSCAD_A,* FROM IMPIANTI_CO WHERE CCODSCHE = 'TREV.C.INSURREZIONE'


SELECT TIPO_COMPONENTE AS TIPO_COMPON,CDITTACAL,CMATCAL,CMODCAL,DT_INSTALL,* FROM IMPIANTI_DD WHERE CCODSCHE = 'TREV.C.INSURREZIONE' ORDER BY TIPO_COMPONENTE

SELECT	* from IMPIANTI_CO AS CONTR 
		INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where CONTR.ID_PMKEY =  SCHE.ID_PMKEY  order by SCHE.ID_PMKEY


SELECT * FROM IMPIANTI_CO

SELECT	* from IMPIANTI_CO AS CONTR 
		INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where  CONTR.CCODSCHE = 'TREV.C.INSURREZIONE'  order by CONTR.ID_PMKEY



SELECT TIPO_COMPONENTE AS TIPO_COMPON,CDITTACAL,CMATCAL,CMODCAL,DT_INSTALL,* FROM IMPIANTI_DD WHERE id_pmkey = '1' and tipo_componente = '001' and ID_RIGO = '00010'

SELECT ID_PMKEY,* FROM IMPIANTI_TT ORDER BY CCODSCHE
SELECT CMATBRU,ID_PMKEY,* FROM IMPIANTI_DD ORDER BY CCODSCHE
SELECT ORD_ATTIVITA,* FROM VENDITE_DT

      SELECT
             TT.TAGGANCIO					AS TAGGANCIO,
			 TT.ORD_NUMORD					AS ORD_NUMORD,
			 TT.ORD_DATORD					AS ORD_DATORD,
  			 TT.ORD_CCODSCHE				AS ORD_CCODSCHE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
             TT.ORD_CODCLI					AS ORD_CODCLI,
             TT.ORD_RAGSOC					AS ORD_RAGSOC,
             TT.ORD_NOTE_INTERVENTI			AS ORD_NOTE_INTERVENTI,
			 TT.ORD_VALORE					AS ORD_VALORE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
			 TT.ORD_INTCLOSE				AS ORD_INTCLOSE,
 			 DT.ORD_TECNICO					AS ORD_TECNICO,
			 DT.ORD_NOME_TECN				AS ORD_NOME_TECN,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
			 DT.ORD_DTINIINT				AS ORD_DTINIINT,
			 DT.ORD_VALPRE					AS ORD_VALPRE,
			 DT.ORD_VALINC					AS ORD_VALINC,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
             DT.DAGGANCIO					AS DAGGANCIO,
			 IM_TT.CZONAINS					AS CZONAINS,
			 IM_TT.CSETTORE					AS CSETTORE,
			 IM_DD.CMODCAL					AS CMODCAL,
			 IM_DD.CMODBRU					AS CMODBRU,
			 IM_DD.CMATBRU					AS CMATBRU,
			 IM_DD.TIPO_COMPONENTE			AS TIPO_COMPONENTE,
			 SUBSTRING(PARA.DESCRI,1,100)	AS PRESTAZIONE1,
			 COALESCE(SPACE(100),'')		AS SERVIZI_CONTRATTO
       FROM VENDITE_DT			AS DT
       INNER JOIN VENDITE_TT	AS TT ON TT.TAGGANCIO = DT.DAGGANCIO AND TT.ORD_NUMORD = '000117' 
       INNER JOIN IMPIANTI_TT	AS IM_TT ON TT.ORD_CCODSCHE = IM_TT.CCODSCHE
       INNER JOIN IMPIANTI_DD	AS IM_DD ON TT.ORD_CCODSCHE = IM_DD.CCODSCHE AND IM_DD.TIPO_COMPONENTE = '001'
	   LEFT OUTER JOIN PARA AS PARA
	   ON 'ATT'+DT.ORD_ATTIVITA = PARA.CODICE
	   WHERE TT.ORD_DATORD BETWEEN '2023/01/06' AND '2023/06/30'
	   ORDER BY TT.ORD_DATORD



      SELECT
             TT.TAGGANCIO					AS TAGGANCIO,
			 TT.ORD_NUMORD					AS ORD_NUMORD,
			 TT.ORD_DATORD					AS ORD_DATORD,
  			 TT.ORD_CCODSCHE				AS ORD_CCODSCHE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
             TT.ORD_CODCLI					AS ORD_CODCLI,
             TT.ORD_RAGSOC					AS ORD_RAGSOC,
             TT.ORD_NOTE_INTERVENTI			AS ORD_NOTE_INTERVENTI,
			 TT.ORD_VALORE					AS ORD_VALORE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
			 TT.ORD_INTCLOSE				AS ORD_INTCLOSE,
 			 DT.ORD_TECNICO					AS ORD_TECNICO,
			 DT.ORD_NOME_TECN				AS ORD_NOME_TECN,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
			 DT.ORD_DTINIINT				AS ORD_DTINIINT,
			 DT.ORD_VALPRE					AS ORD_VALPRE,
			 DT.ORD_VALINC					AS ORD_VALINC,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
             DT.DAGGANCIO					AS DAGGANCIO,
			 IM_TT.CZONAINS					AS CZONAINS,
			 IM_TT.CSETTORE					AS CSETTORE,
			 IM_DD.CMODCAL					AS CMODCAL,
			 IM_DD.CMODBRU					AS CMODBRU,
			 IM_DD.CMATBRU					AS CMATBRU,
			 IM_DD.TIPO_COMPONENTE			AS TIPO_COMPONENTE,
			 SUBSTRING(PARA.DESCRI,1,100)	AS PRESTAZIONE1,
			 SPACE(100)						AS PRESTAZIONE2,
			 SPACE(100)						AS PRESTAZIONE3,
			 SPACE(100)						AS PRESTAZIONE4,
			 SPACE(100)						AS PRESTAZIONE5,
			 COALESCE(SPACE(100),'')		AS SERVIZI_CONTRATTO
       FROM VENDITE_TT			AS TT
       INNER JOIN VENDITE_DT	AS DT ON TT.TAGGANCIO = DT.DAGGANCIO AND TT.ORD_NUMORD = '000117' 
       INNER JOIN IMPIANTI_TT	AS IM_TT ON TT.ORD_CCODSCHE = IM_TT.CCODSCHE
       INNER JOIN IMPIANTI_DD	AS IM_DD ON TT.ORD_CCODSCHE = IM_DD.CCODSCHE AND IM_DD.TIPO_COMPONENTE = '001'
	   LEFT OUTER JOIN PARA AS PARA
	   ON 'ATT'+DT.ORD_ATTIVITA = PARA.CODICE
	   WHERE TT.ORD_DATORD BETWEEN '2023/01/06' AND '2023/06/30'
	   ORDER BY TT.ORD_DATORD


      SELECT
             TT.TAGGANCIO					AS TAGGANCIO,
			 TT.ORD_NUMORD					AS ORD_NUMORD,
			 TT.ORD_DATORD					AS ORD_DATORD,
  			 TT.ORD_CCODSCHE				AS ORD_CCODSCHE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
             TT.ORD_CODCLI					AS ORD_CODCLI,
             TT.ORD_RAGSOC					AS ORD_RAGSOC,
             TT.ORD_NOTE_INTERVENTI			AS ORD_NOTE_INTERVENTI,
			 TT.ORD_VALORE					AS ORD_VALORE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
			 TT.ORD_INTCLOSE				AS ORD_INTCLOSE,
 			 DT.ORD_TECNICO					AS ORD_TECNICO,
			 DT.ORD_NOME_TECN				AS ORD_NOME_TECN,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
			 DT.ORD_DTINIINT				AS ORD_DTINIINT,
			 DT.ORD_VALPRE					AS ORD_VALPRE,
			 DT.ORD_VALINC					AS ORD_VALINC,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
             DT.DAGGANCIO					AS DAGGANCIO,
			 IM_TT.CZONAINS					AS CZONAINS,
			 IM_TT.CSETTORE					AS CSETTORE,
			 IM_DD.CMODCAL					AS CMODCAL,
			 IM_DD.CMODBRU					AS CMODBRU,
			 IM_DD.CMATBRU					AS CMATBRU,
			 IM_DD.TIPO_COMPONENTE			AS TIPO_COMPONENTE,
			 SUBSTRING(PARA.DESCRI,1,100)	AS PRESTAZIONE1,
			 SPACE(100)						AS PRESTAZIONE2,
			 SPACE(100)						AS PRESTAZIONE3,
			 SPACE(100)						AS PRESTAZIONE4,
			 SPACE(100)						AS PRESTAZIONE5,
			 COALESCE(SPACE(100),'')		AS SERVIZI_CONTRATTO
       FROM VENDITE_TT			AS TT
       INNER JOIN VENDITE_DT	AS DT ON TT.TAGGANCIO = DT.DAGGANCIO 
       INNER JOIN IMPIANTI_TT	AS IM_TT ON TT.ORD_CCODSCHE = IM_TT.CCODSCHE
       INNER JOIN IMPIANTI_DD	AS IM_DD ON TT.ORD_CCODSCHE = IM_DD.CCODSCHE AND IM_DD.TIPO_COMPONENTE = '001'
	   LEFT OUTER JOIN PARA AS PARA
	   ON 'ATT'+DT.ORD_ATTIVITA = PARA.CODICE
	   WHERE TT.ORD_DATORD BETWEEN '2023/06/11' AND '2023/06/11'
	   ORDER BY TT.ORD_DATORD






	   SELECT	* from IMPIANTI_CO AS CONTR 
	   INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where  CONTR.CCODSCHE = 'TREV.C.INSURREZIONE'  order by CONTR.ID_PMKEY,CONTR.CINIZCONTR DESC

	   select CONTR.*,SCHE.CINIZCONTR,SCHE.CSCADCONTR,SCHE.DT_DISDETT from IMPIANTI_CO AS CONTR 
   INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where CONTR.ID_PMKEY = '7940' order by ID_PMKEY



         	SELECT
             TT.TAGGANCIO					AS TAGGANCIO,
			 TT.ORD_NUMORD					AS ORD_NUMORD,
			 TT.ORD_DATORD					AS ORD_DATORD,
  			 TT.ORD_CCODSCHE				AS ORD_CCODSCHE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
             TT.ORD_CODCLI					AS ORD_CODCLI,
             TT.ORD_RAGSOC					AS ORD_RAGSOC,
             TT.ORD_NOTE_INTERVENTI			AS ORD_NOTE_INTERVENTI,
			 TT.ORD_VALORE					AS ORD_VALORE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
			 TT.ORD_INTCLOSE				AS ORD_INTCLOSE,
 			 DT.ORD_TECNICO					AS ORD_TECNICO,
			 DT.ORD_NOME_TECN				AS ORD_NOME_TECN,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
			 DT.ORD_DTINIINT				AS ORD_DTINIINT,
			 DT.ORD_VALPRE					AS ORD_VALPRE,
			 DT.ORD_VALINC					AS ORD_VALINC,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
             DT.DAGGANCIO					AS DAGGANCIO,
			 IM_TT.CZONAINS					AS CZONAINS,
			 IM_TT.CSETTORE					AS CSETTORE,
			 IM_DD.CMODCAL					AS CMODCAL,
			 IM_DD.CMODBRU					AS CMODBRU,
			 IM_DD.CMATBRU					AS CMATBRU,
			 IM_DD.TIPO_COMPONENTE			AS TIPO_COMPONENTE,
			 SUBSTRING(PARA.DESCRI,1,100)	AS PRESTAZIONE1,
			 SPACE(100)						AS PRESTAZIONE2,
			 SPACE(100)						AS PRESTAZIONE3,
			 SPACE(100)						AS PRESTAZIONE4,
			 SPACE(100)						AS PRESTAZIONE5,
			 COALESCE(SPACE(100),'')		AS SERVIZI_CONTRATTO
       	FROM VENDITE_TT			AS TT
       	INNER JOIN VENDITE_DT	AS DT ON TT.TAGGANCIO = DT.DAGGANCIO  
       	INNER JOIN IMPIANTI_TT	AS IM_TT ON TT.ORD_CCODSCHE = IM_TT.CCODSCHE  AND TT.ORD_NUMORD = '000117' 
       	INNER JOIN IMPIANTI_DD	AS IM_DD ON TT.ORD_CCODSCHE = IM_DD.CCODSCHE AND IM_DD.TIPO_COMPONENTE = '001'
	   	LEFT OUTER JOIN PARA AS PARA
	   	ON 'ATT'+DT.ORD_ATTIVITA = PARA.CODICE
		WHERE TT.ord_codsoc = '01' and TT.ord_datord between '2023/06/11' and '2023/06/11' and DT.ord_tecnico = '121'
	   	ORDER BY TT.ORD_DATORD



      	SELECT
             TT.TAGGANCIO					AS TAGGANCIO,
			 TT.ORD_NUMORD					AS ORD_NUMORD,
			 TT.ORD_DATORD					AS ORD_DATORD,
  			 TT.ORD_CCODSCHE				AS ORD_CCODSCHE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
             TT.ORD_CODCLI					AS ORD_CODCLI,
             TT.ORD_RAGSOC					AS ORD_RAGSOC,
             TT.ORD_INDIRI					AS ORD_INDIRI,
             TT.ORD_CAP						AS ORD_CAP,
             TT.ORD_LOCALI					AS ORD_LOCALI,
             TT.ORD_PROVIN        			AS ORD_PROVIN,
             TT.ORD_TELEFO					AS ORD_TELEFO,
             TT.ORD_NOTE_INTERVENTI			AS ORD_NOTE_INTERVENTI,
			 TT.ORD_VALORE					AS ORD_VALORE,
			 TT.ORD_DTPROGR					AS ORD_DTPROGR,
			 TT.ORD_INTCLOSE				AS ORD_INTCLOSE,
 			 DT.ORD_TECNICO					AS ORD_TECNICO,
			 DT.ORD_NOME_TECN				AS ORD_NOME_TECN,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
			 DT.ORD_DTINIINT				AS ORD_DTINIINT,
			 DT.ORD_VALPRE					AS ORD_VALPRE,
			 DT.ORD_VALINC					AS ORD_VALINC,
			 DT.ORD_ATTIVITA				AS ORD_ATTIVITA,
             DT.DAGGANCIO					AS DAGGANCIO,
			 IM_TT.CZONAINS					AS CZONAINS,
			 IM_TT.CSETTORE					AS CSETTORE,
			 IM_DD.CMODCAL					AS CMODCAL,
			 IM_DD.CMODBRU					AS CMODBRU,
			 IM_DD.CMATBRU					AS CMATBRU,
			 IM_DD.TIPO_COMPONENTE			AS TIPO_COMPONENTE,
			 SUBSTRING(PARA.DESCRI,1,100)	AS PRESTAZIONE1,
			 SPACE(100)						AS PRESTAZIONE2,
			 SPACE(100)						AS PRESTAZIONE3,
			 SPACE(100)						AS PRESTAZIONE4,
			 SPACE(100)						AS PRESTAZIONE5,
			 COALESCE(SPACE(100),'')		AS SERVIZI_CONTRATTO
       	FROM VENDITE_TT			AS TT
       	INNER JOIN VENDITE_DT	AS DT ON TT.TAGGANCIO = DT.DAGGANCIO  
       	INNER JOIN IMPIANTI_TT	AS IM_TT ON TT.ORD_CCODSCHE = IM_TT.CCODSCHE
       	INNER JOIN IMPIANTI_DD	AS IM_DD ON TT.ORD_CCODSCHE = IM_DD.CCODSCHE AND IM_DD.TIPO_COMPONENTE = '001'
	   	LEFT OUTER JOIN PARA AS PARA
	   	ON 'ATT'+DT.ORD_ATTIVITA = PARA.CODICE
		WHERE TT.ord_codsoc = '01' and TT.ord_datord between '2023/06/11' and '2023/06/11' and DT.ord_tecnico = '121'
	   	ORDER BY TT.ORD_DATORD
	   


SELECT ORD_CCODSCHE AS CCODSCHE,* FROM VENDITE_TT WHERE ORD_CCODSCHE = 'ZANI.JOVINO M. '

select * from VENDITE_tt
select * from VENDITE_DT WHERE DAGGANCIO = '_6F813RV63'
select ORD_NUMORD,ORD_SYSCOMPONENTI,* from VENDITE_DT ORDER BY DAGGANCIO DESC

UPDATE VENDITE_DT SET ORD_SYSCOMPONENTI = '' WHERE DAGGANCIO = '1000000294'



SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'ZANI.JOVINO M.'
SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'ZANI.JOVINO M.'

SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY TIPO_COMPONENTE,ID_RIGO
SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY CCODSCHE
SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY CCODSCHE,ID_RIGO

SELECT ORD_CCODSCHE AS CCODSCHE,* FROM VENDITE_TT WHERE ORD_CCODSCHE = 'ZANI.JOVINO M. '

select * from VENDITE_TT
select ORD_RAPPORT,* from VENDITE_DT WHERE DAGGANCIO = '_6F813RV63'


select * from VENDITE_TT WHERE ORD_NUMORD = '000117' 
select * from VENDITE_TT WHERE TAGGANCIO = '1000000294'
select ORD_SYSCOMPONENTI AS _SYSCOMPONENTI,* from VENDITE_DT WHERE DAGGANCIO = '1000000294' ORDER BY ORD_SYSCOMPONENTI
select LINK_DT_DC AS _LINK_DT_DC,* from VENDITE_DC WHERE DAGGANCIO = '1000000294' ORDER BY LINK_DT_DC
select * from VENDITE_DD WHERE DAGGANCIO = '1000000294'

SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'ZANI.JOVINO M.'
SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'ZANI.JOVINO M.'

SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY TIPO_COMPONENTE,ID_RIGO
SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY CCODSCHE
SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'INZA.C.S.GIUSEPPE/B' ORDER BY CCODSCHE,ID_RIGO



select * from para where codice = 'ATT001'


SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'CREMO.MIRABELLI'
SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'CREMO.MIRABELLI'


SELECT ORD_CCODSCHE,* FROM VENDITE_TT ORDER BY TAGGANCIO DESC

SELECT * FROM VENDITE_DT WHERE DAGGANCIO = '1000000306'
SELECT ORD_CCODSCHE,* FROM VENDITE_CO WHERE DAGGANCIO = '1000000306'
SELECT ORD_CCODSCHE,* FROM VENDITE_DC WHERE DAGGANCIO = '1000000306'

--DELETE VENDITE_CO WHERE DAGGANCIO = '1000000298'
--DELETE VENDITE_DC WHERE DAGGANCIO = '1000000298'
