SELECT ORD_SCAR,* FROM U_BOL_TT ORDER BY TAGGANCIO DESC
SELECT ORD_CDAPRD,* FROM U_BOL_DD ORDER BY DAGGANCIO DESC



SELECT ORD_SCAR,* FROM U_FAT_TT ORDER BY TAGGANCIO DESC
SELECT ORD_SYSMAG,ORD_SEQUEN AS SEQUEN,* FROM U_FAT_DD WHERE DAGGANCIO = '6000036186' ORDER BY ORD_SEQUEN
SELECT MOV_LEGAME,MOV_LEGSYS,* FROM U_MAG_MO WHERE MOV_DTREGI = '2023/07/09'

SELECT * FROM U_MAG_GG WHERE MAG_DATAGG = '2023/07/09'
SELECT * FROM U_MAG_GG WHERE MAG_CODART = '2.9140' 
SELECT * FROM U_MAG_MO WHERE MOV_CODART = '2.9140' 

SELECT * FROM U_MAG_GG WHERE MAG_CODART = '2.9191' 
SELECT * FROM U_MAG_MO WHERE MOV_CODART = '2.9191' 
  




--DELETE FROM U_MAG_GG WHERE MAG_CODART = '2.9140' 
--DELETE FROM U_MAG_MO WHERE MOV_CODART = '2.9140' 
                       

SELECT ORD_SYSMAG,ORD_CDAPRD,ORD_DESART,ORD_DSAPRD,ORD_CODMAT,ORS_DESTIN,ORD_QTXCON,ORD_DATCON,ORD_CODSYS,ORS_CODCLI,ORS_RAGSOC,ORS_NUMORD,ORS_DATORD,ORS_CODEMI,ORS_RAGEMI,* FROM U_FAT_DD ORDER BY DAGGANCIO DESC


_6LR10WQPF
UPDATE U_FAT_DD SET ORD_SYSMAG = '_6NQ0S14BW' WHERE DAGGANCIO = '6000036186' and ORD_SEQUEN = '10'

