
--SELECT CLI_TELEFO,dbo.RimuoviChrNonNumerici(CLI_TELEFO) as telefono_numerico,cli_fax,dbo.RimuoviChrNonNumerici(cli_fax) as cellulare_numerico,* FROM U_CLI_AN WHERE CLI_CODCLI IN (SELECT CCODCLI FROM IMPIANTI_TT WHERE ID_PMKEY IN (SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS <> '700')) ORDER BY CLI_CODCLI
--SELECT CLI_EMAIL,* FROM U_CLI_AN WHERE CLI_CODCLI IN (SELECT CCODCLI FROM IMPIANTI_TT WHERE ID_PMKEY IN (SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS <> '700')) ORDER BY CLI_CODCLI

UPDATE TT SET
	TT.NOTIFY_WA = '',
	TT.NOTIFY_SMS = '',
	TT.NOTIFY_EMAIL = '',
	TT.NOTIFY_TYPE = 2,
	TT.NOTIFY_EMAIL_MTZ = '',
	TT.NOTIFY_TYPE_MTZ = 4
FROM IMPIANTI_TT AS TT
GO

UPDATE TT SET
	TT.NOTIFY_WA = SUBSTRING(COALESCE(CASE
								WHEN (SELECT dbo.RimuoviChrNonNumerici(CLI_FAX) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI) <> ''
								THEN (SELECT dbo.RimuoviChrNonNumerici(CLI_FAX) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI)
								ELSE (SELECT dbo.RimuoviChrNonNumerici(CLI_TELEFO) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI)
							END,''),1,10),
	TT.NOTIFY_SMS = SUBSTRING(COALESCE(CASE
								WHEN (SELECT dbo.RimuoviChrNonNumerici(CLI_FAX) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI) <> ''
								THEN (SELECT dbo.RimuoviChrNonNumerici(CLI_FAX) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI)
								ELSE (SELECT dbo.RimuoviChrNonNumerici(CLI_TELEFO) as cellulare_numerico FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI)
							END,''),1,10),
	TT.NOTIFY_EMAIL = COALESCE((SELECT RTRIM(CLI_EMAIL) as email FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI),''),
	TT.NOTIFY_EMAIL_MTZ = COALESCE((SELECT RTRIM(CLI_EMAIL) as email FROM U_CLI_AN WHERE CLI_CODCLI = TT.CCODCLI),'')
FROM IMPIANTI_TT AS TT
WHERE TT.ID_PMKEY IN (SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS <> '700')
GO

UPDATE TT SET
	TT.NOTIFY_TYPE =	CASE
							WHEN TT.NOTIFY_WA <> '' AND SUBSTRING(TT.NOTIFY_WA,1,1) <> '0' THEN 2
							WHEN TT.NOTIFY_EMAIL <> '' THEN 4
							ELSE 1
						END,
	TT.NOTIFY_TYPE_MTZ =	CASE
								WHEN TT.NOTIFY_EMAIL_MTZ <> '' THEN 4
								ELSE 1
							END
FROM IMPIANTI_TT AS TT
WHERE TT.ID_PMKEY IN (SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS <> '700')
GO

UPDATE IMPIANTI_TT SET NOTIFY_TYPE = 1 WHERE CCODCLI IN (SELECT CLI_CODCLI FROM U_ANA_CL WHERE CLI_CATCLI = 'CON')

SELECT CCODSCHE,CCODCLI,CRAGSOC,NOTIFY_TYPE,NOTIFY_WA,NOTIFY_SMS,NOTIFY_TYPE_MTZ,NOTIFY_EMAIL_MTZ FROM IMPIANTI_TT WHERE ID_PMKEY IN (SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS <> '700') ORDER BY CCODSCHE


SELECT CLI_CODCLI FROM U_ANA_CL WHERE CLI_CATCLI = 'CON' AND CLI_CODCLI = '000005434'