
SELECT * FROM MAIL_ADDRESS WHERE TIPO_DOC = 'OFF'

SELECT * FROM MAIL_ADDRESS WHERE CLI_FOR = 'C' AND CODICE_CLI_FOR NOT IN (SELECT CLI_CODCLI FROM U_CLI_AN)
--DELETE FROM MAIL_ADDRESS WHERE CLI_FOR = 'C' AND CODICE_CLI_FOR NOT IN (SELECT CLI_CODCLI FROM U_CLI_AN)

/*
UPDATE MAIL_ADDRESS SET INDIRIZZO_CC = 'info@trevicalor.it' WHERE CLI_FOR = 'C' AND TIPO_DOC = 'OFF' AND SUBSTRING(INDIRIZZO_CC,1,10) = ''

INSERT INTO MAIL_ADDRESS (
	CLI_FOR,
	CODICE_CLI_FOR,
	TIPO_DOC,
	INDIRIZZO_CC
	)
SELECT
	'C' AS CLI_FOR,
	CLI_CODCLI AS CODICE_CLI_FOR,
	'OFF' AS TIPO_DOC,
	'info@trevicalor.it' AS INDIRIZZO_CC
FROM U_CLI_AN
WHERE CLI_CODCLI NOT IN (SELECT CODICE_CLI_FOR FROM MAIL_ADDRESS WHERE CLI_FOR = 'C' AND TIPO_DOC = 'OFF')
*/
