
DELETE FROM PARA WHERE CODICE LIKE 'NUMLII%'

INSERT INTO PARA (CODICE, DESCRI, LIBERA, PAR_DATINS) VALUES ('NUMLII01','NUMERO LISTINO PER IMPIANTI',(SELECT RIGHT('       '+REPLACE(MAX(LIS_CODLIS),'0',''),7) FROM IMPIANTI_LI),(SELECT CONVERT(char(10), GETDATE(), 111) AS DataFormattata))

SELECT * FROM PARA WHERE CODICE LIKE 'NUMLII%'

