
--DELETE FROM PARA WHERE CODICE LIKE 'SDA%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,CODPGO)
	SELECT 'SDA'+SUBSTRING(CODICE,4,6),DESCRI,LIBERA,CODPGO FROM PARA WHERE CODICE LIKE 'SEA%'

DELETE FROM PARA WHERE CODICE LIKE 'SEA%' AND CODICE <> 'SEA001'

UPDATE PARA SET CODPGO = '16777088' WHERE CODICE = 'SDACM'
UPDATE PARA SET CODPGO = '8454143' WHERE CODICE = 'SDACT'
UPDATE PARA SET CODPGO = '65280' WHERE CODICE = 'SDAEX'
UPDATE PARA SET CODPGO = '11711154' WHERE CODICE = 'SDARF'