
UPDATE CO SET
	CO.CCOSTOA = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_A) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOA
			END
		),
	CO.CCOSTOB = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_B) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOB
			END
		),
	CO.CCOSTOC = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_C) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOC
			END
		),
	CO.CCOSTOD1 = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D1) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOD1
			END
		),
	CO.CCOSTOD2 = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_D2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOD2
			END
		),
	CO.CCOSTOF2 = (
		SELECT
			CASE
				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVISI FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)
			
				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRVO) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRVO FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTRFG) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPRFG FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONSEMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONSEMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABBONCOMP) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ABBONCOMP FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTABT) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_IMPABT FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTPULIZIA) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_PULIZIA FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTANALCOMBU) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_ANALCOMBU FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				WHEN RTRIM(CO.CONTR_F2) = (SELECT RTRIM(CONTO2) AS COD_CONTR FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
					(SELECT TOP 1 RTRIM(LIS_ATTREVADC) FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE
						where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC))
					THEN (SELECT TOP 1 LIS_REVADC FROM IMPIANTI_LI WHERE LIS_CODRAG = (SELECT TOP 1 CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = CO.ID_PMKEY AND TE.ID_RIGO = CO.ID_RIGO AND TE.TIPO_COMPONENTE = CO.TIPO_COMPONENTE ORDER BY id_unique DESC) ORDER BY LIS_DATLIS DESC)

				ELSE CO.CCOSTOF2
			END
		)
FROM IMPIANTI_CO AS CO
WHERE CO.ID_PMKEY IN (
	SELECT ID_PMKEY FROM IMPIANTI_TE WHERE CCODLIS IN (
'1',
'-1',
'2',
'-2',
'3',
'-3',
'4',
'-4',
'5',
'-5',
'6',
'-6',
'7',
'-7',
'11',
'-11',
'12',
'-12',
'13',
'-13',
'14',
'-14',
'21',
'-21',
'22',
'-22',
'23',
'-23',
'25',
'-25',
'26',
'-26',
'27',
'-27',
'28',
'-28',
'29',
'31',
'-31',
'32',
'-32',
'34',
'-34',
'35',
'36',
'30',
'40',
'-40',
'41',
'-41')
)

/*
SELECT ID_PMKEY,ID_RIGO,TIPO_COMPONENTE,* FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.AMETRANO'

SELECT RTRIM(CONTO2) AS COD_CONTR,* FROM PARA WHERE SUBSTRING(CODICE,1,3) = 'ATT' AND SUBSTRING(CODICE,4,3) = 
	(SELECT RTRIM(LIS_ATTREV) FROM IMPIANTI_LI WHERE LIS_CODRAG = (
		SELECT CCODLIS from IMPIANTI_TE AS TE where TE.ID_PMKEY = '8811      ' AND TE.ID_RIGO = '00010' AND TE.TIPO_COMPONENTE = '001  ')
	)


SELECT CCODLIS,* from IMPIANTI_TE AS TE where TE.ID_PMKEY = '8811      ' AND TE.ID_RIGO = '00010' AND TE.TIPO_COMPONENTE = '001  '
*/