
UPDATE PARA SET CONTO4 = '5.1.2.1.' WHERE SUBSTRING(CODICE,1,3) =  'TPI' AND SUBSTRING(CODICE,1,6)  =  'TPI000'
UPDATE PARA SET CONTO1 = 'GENERICO' WHERE SUBSTRING(CODICE,1,3) =  'TPI' AND SUBSTRING(CODICE,1,6)  =  'TPI000'


UPDATE PARA SET CONTO4 = '5.1.4.1.' WHERE SUBSTRING(CODICE,1,3) =  'TPI' AND SUBSTRING(CODICE,1,6)  <>  'TPI000'
UPDATE PARA SET CONTO1 = 'MAN.PROGRAMM.' WHERE SUBSTRING(CODICE,1,3) =  'TPI' AND SUBSTRING(CODICE,1,6)  <> 'TPI000'

SELECT * FROM PARA WHERE SUBSTRING(CODICE,1,3) =  'TPI'