
SELECT cli_reccat FROM U_CLI_AN

SELECT 
rtrim(SUBSTRING(CLI_RAGSOC,1, CHARINDEX(' ',CLI_RAGSOC,1))) AS COGNOME,
LTRIM(RTRIM(SUBSTRING(CLI_RAGSOC,CHARINDEX(' ',CLI_RAGSOC,1),100))) AS NOME,
* FROM U_CLI_AN WHERE CLI_CODFIS <> '' AND LEN(RTRIM(CLI_CODFIS)) = 16 ORDER BY CLI_CODCLI

/*
UPDATE U_CLI_AN SET 
	cli_reccat = 2,
	cli_reccog  = SUBSTRING(rtrim(SUBSTRING(CLI_RAGSOC,1, CHARINDEX(' ',CLI_RAGSOC,1))),1,24),
	cli_recnom  = SUBSTRING(LTRIM(RTRIM(SUBSTRING(CLI_RAGSOC,CHARINDEX(' ',CLI_RAGSOC,1),100))),1,20),
	cli_PRONAS  = cli_PROVIN,
	cli_reccdf  = cli_CODFIS,
	cli_RAGLEG  = '',
	cli_RGLEG2  = '',
	cli_INDLEG  = '',
	cli_LOCLEG  = '',
	cli_PROLEG  = '',
	cli_NAZLEG  = '',
	cli_CAPLEG  = '',
	cli_CFISLG  = '',
	cli_PIVALG  = '',
	cli_IVCELG  = ''
WHERE CLI_CODFIS <> '' AND LEN(RTRIM(CLI_CODFIS)) = 16
*/