
UPDATE PARA SET LIBERA = RTRIM(LIBERA) + 'AGG_SCAD_CONTR_INTERV:SI;' WHERE CODICE LIKE 'RAL%' AND RTRIM(LIBERA) NOT LIKE '%AGG_SCAD_CONTR_INTERV%' AND CODICE NOT IN ('RAL600','RAL900','RAL-60','RAL-90')
UPDATE PARA SET LIBERA = RTRIM(LIBERA) + 'AGG_SCAD_CONTR_INTERV:NO;' WHERE CODICE = 'RAL600' AND RTRIM(LIBERA) NOT LIKE '%AGG_SCAD_CONTR_INTERV%'
UPDATE PARA SET LIBERA = RTRIM(LIBERA) + 'AGG_SCAD_CONTR_INTERV:NO;' WHERE CODICE = 'RAL900' AND RTRIM(LIBERA) NOT LIKE '%AGG_SCAD_CONTR_INTERV%'
UPDATE PARA SET LIBERA = RTRIM(LIBERA) + 'AGG_SCAD_CONTR_INTERV:NO;' WHERE CODICE = 'RAL-60' AND RTRIM(LIBERA) NOT LIKE '%AGG_SCAD_CONTR_INTERV%'
UPDATE PARA SET LIBERA = RTRIM(LIBERA) + 'AGG_SCAD_CONTR_INTERV:NO;' WHERE CODICE = 'RAL-90' AND RTRIM(LIBERA) NOT LIKE '%AGG_SCAD_CONTR_INTERV%'

--UPDATE PARA SET LIBERA = REPLACE(LIBERA,'AGG_SCAD_CONTR_INTERV:SI;','') WHERE CODICE LIKE 'RAL%'
--UPDATE PARA SET LIBERA = REPLACE(LIBERA,'AGG_SCAD_CONTR_INTERV:NO;','') WHERE CODICE LIKE 'RAL%'