
/********************************************************
 AGGIORNAMENTO PARAMETRI PER RICHIAMO REPORT PERSONALIZZAZI
 ********************************************************/
DELETE FROM PJTIPREP WHERE NOMEPROC = 'ORDPJEUR'
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('ORDPJEUR','REPORT PERSONALIZZATO ORDINI CLIENTI STANDARD PRISMA','ORDPJPRISMA.FRX')
SELECT * FROM PJTIPREP WHERE NOMEPROC = 'ORDPJEUR'

DELETE FROM PJTIPREP WHERE NOMEPROC = 'FAPPJEUR'
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('FAPPJEUR','REPORT PERSONALIZZATO FATTURE PROFORMA STANDARD PRISMA','FAPPJPRISMA.FRX')
SELECT * FROM PJTIPREP WHERE NOMEPROC = 'FAPPJEUR'

DELETE FROM PJTIPREP WHERE NOMEPROC = 'FATPJEUR'
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('FATPJEUR','REPORT PERSONALIZZATO FATTURE CLIENTI STANDARD PRISMA','FATPJPRISMA.FRX')
SELECT * FROM PJTIPREP WHERE NOMEPROC = 'FATPJEUR'

DELETE FROM PJTIPREP WHERE NOMEPROC = 'BOLPJITA'
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('BOLPJITA','REPORT PERSONALIZZATO DDT STANDARD PRISMA','BOLPJPRISMA.FRX')
SELECT * FROM PJTIPREP WHERE NOMEPROC = 'BOLPJITA'

DELETE FROM PJTIPREP WHERE NOMEPROC = 'BCLPJITA'
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('BCLPJITA','REPORT PERSONALIZZATO DDT CONTO LAVORO STANDARD PRISMA','BCLPJPRISMA.FRX')
SELECT * FROM PJTIPREP WHERE NOMEPROC = 'BCLPJITA'


/********************************************************
 AGGIORNAMENTO PARAMETRI AZIENDALI 
 ********************************************************/
DECLARE @_INTESTAZIONE AS VARCHAR(8000), @_PIE_DI_PAGINA AS VARCHAR(8000)
SET @_INTESTAZIONE = 'PRISMA S.P.A.
Sede legale: VIA MARZIALE 13 - 04023 FORMIA (LT)
Uffici comm. e sede operativa: VIA PIETRA ERTA snc
Tel. 0771.723028 - Fax. 0771.725049
Cod. Fisc. e P.IVA 02058310596
prismaspa@prismaspa.com - www.prismaspa.com
Capitale sociale € 291.400,00 i.v.  -  R.E.A. Latina nr.142302'
SET @_PIE_DI_PAGINA = ''
--SET @_PIE_DI_PAGINA = 'In piè di pagina verranno inserite le note per la certificazione FSC una volta inserito il LOGO'

UPDATE U_AZI_AN SET 
AZI_CODCLI = '00000100', 
AZI_RAGSOC = 'PRISMA SPA', 
AZI_INDIRI = 'VIA PIETRA ERTA SNC', 
AZI_LOCALI = 'FORMIA', 
AZI_CAP = '04023', 
AZI_PIVA = '02058310596', 
AZI_TELEFO = '0771/723028', 
AZI_FAX = '0771/725049', 
AZI_INTOFF = @_INTESTAZIONE,
AZI_INTORD = @_INTESTAZIONE,
AZI_INTORF = @_INTESTAZIONE,
AZI_INTBOL = @_INTESTAZIONE,
AZI_INTFAT = @_INTESTAZIONE,
AZI_PIEOFF = @_PIE_DI_PAGINA,
AZI_PIEORD = @_PIE_DI_PAGINA,
AZI_PIEORF = @_PIE_DI_PAGINA,
AZI_PIEBOL = @_PIE_DI_PAGINA,
AZI_PIEFAT = @_PIE_DI_PAGINA,
AZI_CFDEF = '00000100',
AZI_CODM = 'SEDE',
AZI_DECQTA = 2, 
AZI_DECPRZ = 6, 
AZI_DECVAL = 2,
AZI_IVA = '21',
AZI_UM = 'NR',
AZI_LINEA = '05',
AZI_AGE = '001',
AZI_CPA = '100',
AZI_VALU = 'EUR',
AZI_NAZI = 'ITA',
--AZI_BOLLA = '',
AZI_FAPRO = 'FAP',
AZI_ORDIN = 'ORD',
AZI_FATTU = 'VEN',
AZI_EFFE = '693',
AZI_ORFO = 'ORF',
AZI_OFFE = 'OFF',
AZI_COMM = 'CMS',
AZI_CTLO = 'CTL',
AZI_NCR = '399',
AZI_FAMTU = 'ACQ',
--AZI_COMCEE = '',
--AZI_FATTR = '',
--AZI_CAUDIR = '',
AZI_CTRGIA = 0,
AZI_LIS03 = 1,
AZI_LIS06 = 1,
AZI_SAU = 1,
AZI_BOLFOR = 1,
AZI_MAGLOG = 0,
AZI_CARORF = 'SEDE',
AZI_CQUMPC = '',
AZI_CQUMPN = '',
AZI_CQUSLC = '',
AZI_CQUSLN = '',
AZI_SPAPRO = '',
AZI_SPAMPR = '',
AZI_SPACQS = '',
AZI_RIBPRO = '',
AZI_RIBSLR = '',
AZI_RIBSLO = '',
AZI_TAGPRO = '',
AZI_TAGSLR = '',
AZI_TAGPFO = ''

SELECT * FROM U_AZI_AN

UPDATE U_AZI_PA SET 
AZI_CLIMAG = '00000100',
AZI_GGCONS = 15,
AZI_CDAPRD = 0,
AZI_OPZRSK = 2,
AZI_MSGORDNODB = 0,
AZI_LCKORDNODB = 0,
AZI_SSPORD = 2,
AZI_DDTQTADOPPIE = 0,
AZI_SSPFAP = 2,
AZI_SSPFAT = 2,
AZI_LIS12 = 0,
AZI_LIS13 = 0,
AZI_LIS14 = 0,
AZI_CGMAGA = 1,
AZI_SPASCA = '',
AZI_PRESSA = '',
AZI_LEVIGA1 = '',
AZI_LEVIGA2 = '',
AZI_LEVIGA3 = '',
AZI_NOBILI = '',
AZI_SCAPPT = '',
AZI_CAIPPT = '',
AZI_MACINA = '',
AZI_TAGLIO = '',
AZI_PROFIN = '',
AZI_GIANEG = '',
AZI_MAGNO0 = 'CANCELLA_GIACENZE_A_ZERO',
AZI_PRSSTD = 0,
AZI_PRDFILM = 0,
AZI_PRMMOL = 0,
AZI_PRTTES = 0,
AZI_PRGPLET = 0,
AZI_PRGDADI = 0,
AZI_PRGPRD = 0,
AZI_NCLBOL = 1,
AZI_NODSTFAT = 1,
AZI_NORIFORD = 1
SELECT * FROM U_AZI_PA

/********************************************************
 AGGIORNAMENTO ANAGRAFICA CLIENTI
 ********************************************************/
UPDATE U_CLI_AN SET CLI_RAGSOC = 'PRISMA SPA', CLI_INDIR = 'VIA PIETRA ERTA SNC', CLI_LOCALI = 'FORMIA', CLI_CAP = '04023', CLI_PARIVA = '02058310596',
	CLI_TELEFO = '0771/723028', CLI_FAX = '0771/725049' WHERE CLI_CODCLI = '00000100'
SELECT * FROM U_CLI_AN WHERE CLI_CODCLI = '00000100'

/********************************************************
 AGGIORNAMENTO PARAMETRO IMPORTO MAX EURO GESTIBILE
 ********************************************************/
UPDATE PARA SET LIBERA = '1000000000,00' WHERE CODICE = 'TEUEUR'
SELECT * FROM PARA WHERE CODICE = 'TEUEUR'