-- VISTA UTILIZZO_IVA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[UTILIZZO_IVA]'))
	DROP VIEW [dbo].[UTILIZZO_IVA]
GO

CREATE VIEW [dbo].[UTILIZZO_IVA]
AS

	SELECT
		CODICE,
		DESCRI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_CLI_AN WHERE CLI_CODIVA = SUBSTRING(PARA.CODICE,4,3) OR CLI_ALRID = SUBSTRING(PARA.CODICE,4,3) OR (SELECT CLI_IVASPTRAS FROM U_ANA_CL WHERE U_ANA_CL.CLI_CODCLI = U_CLI_AN.CLI_CODCLI) = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_ANAGR_CLIENTI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_FOR_AN WHERE FOR_CODIVA = SUBSTRING(PARA.CODICE,4,3) OR FOR_ALRID = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_ANAGR_FORNITORI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_FAT_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_DETTAGLI_FATTURE_CLIENTI,
		COALESCE((SELECT TOP 1 ORS_DATORD FROM U_FAT_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3) ORDER BY ORS_DATORD DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_DETTAGLI_FATTURE_CLIENTI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_ORF_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_DETTAGLI_ORDINI_FORN,
		COALESCE((SELECT TOP 1 ORS_DATORD FROM U_ORF_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3) ORDER BY ORS_DATORD DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_DETTAGLI_ORDINI_FORN,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_ORD_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_DETTAGLI_ORDINI_CLIENTI,
		COALESCE((SELECT TOP 1 ORS_DATORD FROM U_ORD_DD WHERE ORD_IVA = SUBSTRING(PARA.CODICE,4,3) ORDER BY ORS_DATORD DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_DETTAGLI_ORDINI_CLIENTI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM MOV_CONT WHERE MOV_IVA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_MOVIMENTI_CONTABILI,
		COALESCE((SELECT TOP 1 MOV_DTREG FROM MOV_CONT WHERE MOV_IVA = SUBSTRING(PARA.CODICE,4,3) ORDER BY MOV_DTREG DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_MOVIMENTI_CONTABILI
	FROM PARA 

	WHERE
		CODICE LIKE 'IVA%'

GO

