-- VISTA ORDINATO CON DESTINAZIONE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_CON_DESTINAZIONE]'))
	DROP VIEW [dbo].[ORDINATO_CON_DESTINAZIONE]
GO

CREATE VIEW [dbo].[ORDINATO_CON_DESTINAZIONE]  
AS
	SELECT 
		TT.ORD_CODCLI AS COD_CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_CAUS AS CAUSALE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_DATORD AS DATA_ORDINE,
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_RIFERI AS RIFERIMENTO,
		TT.ORD_CPA AS CONDIZ_PAGAMENTO,
		COALESCE(P4.DESCRI,'') AS DESC_CONDIZ_PAGAMENTO,
		CLI.CLI_ZONA AS ZONA,
		P1.DESCRI AS DESC_ZONA,
		CLI.CLI_NAZION AS NAZIONE,
		P2.DESCRI AS DESC_NAZIONE,
		DD.ORD_CODART AS CODICE_ARTICOLO,
		DD.ORD_DESART  AS DESCR_ARTICOLO,
		DD.ORD_UM AS UM,
		DD.ORD_QTAORD AS QTA,
		DD.ORD_PRZNET AS PREZZO,
		DD.ORD_VALORE AS VALORE,
		DD.ORD_DATCON AS DATA_CONSEGNA,
		DD.ORD_QTAEV AS QTA_EVASA,
		COALESCE((SELECT TOP 1 ORS_DATORD FROM U_BOL_DD AS BDD WHERE BDD.ORD_LEGSYS=DD.ORD_LEGSYS ORDER BY ORS_DATORD DESC ) ,'') AS ULTIMA_DATA_CONS_EFFETT,
		DD.ORD_CHIUSO AS CHIUSO,
		DD.ORD_VALORE AS VALORE_NETTO,
		DD.ORD_CCODET AS CENTRO_COSTO,
		COALESCE(CC.CON_DESCR,'') AS DESC_CENTRO_COSTO, 
		COALESCE(PR.ART_LINEA,'') AS CODLIN, 
		COALESCE(PARA_LIN.DESCRI,'') AS DESLIN,
		RTRIM(TT.ORD_RAGC) AS DESTINAZIONE_RAG_SOCIALE,
		RTRIM(TT.ORD_INDC) AS DESTINAZIONE_INDIRIZZO,
		RTRIM(TT.ORD_CAPC) AS DESTINAZIONE_CAP,
		RTRIM(TT.ORD_LOCC) AS DESTINAZIONE_LOCALITA,
		RTRIM(TT.ORD_PROC) AS DESTINAZIONE_PROVINCIA,
		CASE TT.ORD_DSNAZC WHEN '' THEN P2.DESCRI ELSE TT.ORD_DSNAZC END AS DESTINAZIONE_NAZIONE,
		CAST(coalesce(stuff((SELECT distinct ',' + ORS_NUMORD
                    from    U_FAT_DD
					where   ORD_CODART <> '' AND ((ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD) OR (ORS_NUMDDT+ORS_DATDDT IN (SELECT ORS_NUMORD+ORS_DATORD FROM U_BOL_DD WHERE ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)))  -- ERASMO - 19/01/2021
					for xml path('')
                ),1,1,''),'') AS nvarchar(254))	AS NUM_FAT,
		CAST(coalesce(stuff((SELECT distinct ',' + ORS_DATORD
                    from    U_FAT_DD
					where   ORD_CODART <> '' AND ((ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD) OR (ORS_NUMDDT+ORS_DATDDT IN (SELECT ORS_NUMORD+ORS_DATORD FROM U_BOL_DD WHERE ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)))  -- ERASMO - 19/01/2021
					for xml path('')
                ),1,1,''),'') AS nvarchar(254))	AS DATA_FAT
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_CLI_AN AS CLI	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN U_ART_PR AS PR ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN CCOSTO AS CC ON DD.ORD_CCODET = CC.CON_CONTO AND TT.ORD_ANNO = CC.CON_ANNO
	LEFT OUTER JOIN PARA AS P1 ON 'ZON'+CLI.CLI_ZONA = P1.CODICE
	LEFT OUTER JOIN PARA AS P2 ON 'STA'+CLI.CLI_NAZION = P2.CODICE
	LEFT OUTER JOIN PARA AS P3 ON 'PRO'+CLI.CLI_PROVIN = P3.CODICE
	LEFT OUTER JOIN PARA AS P4 ON 'CPA'+TT.ORD_CPA = P4.CODICE
	LEFT OUTER JOIN PARA AS PARA_LIN ON PARA_LIN.CODICE = 'REP'+PR.ART_LINEA
	WHERE ORD_QTAORD<>0 AND ORD_DESART <> '*** COMMENTO ***'
GO
