-- VISTA ORDINI_FORNITORI_MENSILE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_FORNITORI_MENSILE]'))
	DROP VIEW [dbo].[ORDINI_FORNITORI_MENSILE]
GO

CREATE VIEW [dbo].[ORDINI_FORNITORI_MENSILE]  
AS

	SELECT
		ORD_ANNO AS ANNO,
		ART_LINEA AS LINEA,
		DES_LINEA,
		ORD_CONDET AS CONTO,
		DES_CONTO,
		ORD_CODART AS ARTICOLO,
		ORD_DESART AS DESCRIZIONE,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '01' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_GEN,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '01' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_GEN,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '02' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_FEB,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '02' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_FEB,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '03' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_MAR,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '03' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_MAR,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '04' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_APR,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '04' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_APR,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '05' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_MAG,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '05' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_MAG,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '06' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_GIU,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '06' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_GIU,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '07' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_LUG,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '07' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_LUG,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '08' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_AGO,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '08' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_AGO,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '09' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_SET,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '09' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_SET,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '10' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_OTT,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '10' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_OTT,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '11' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_NOV,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '11' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_NOV,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '12' THEN ORD_QTAORD ELSE 0 END) AS NUMERIC(19,2)) AS QTA_DIC,
		CAST(SUM(CASE SUBSTRING(ORD_DATORD,6,2) WHEN '12' THEN VALORE_EUR ELSE 0 END) AS NUMERIC(19,2)) AS VALORE_EUR_DIC
	FROM (
		SELECT
			TT.ORD_ANNO,
			TT.ORD_DATORD,
			PR.ART_LINEA,
			COALESCE(PARA_REP.DESCRI,'') AS DES_LINEA,
			DD.ORD_CONDET,
			COALESCE(CONTI.CON_DESCR,'') AS DES_CONTO,
			DD.ORD_CODART,
			DD.ORD_DESART,
			DD.ORD_QTAORD,
			DD.ORD_VALORE * TT.ORD_CAMBIO AS VALORE_EUR
		FROM U_ORF_DD AS DD
		INNER JOIN U_ORF_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
		LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
		LEFT OUTER JOIN PARA AS PARA_REP ON PARA_REP.CODICE = 'REP'+PR.ART_LINEA
		LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = TT.ORD_ANNO AND CONTI.CON_CONTO = DD.ORD_CONDET
		WHERE ORD_CODART <> '' AND ORD_DESART <> '*** COMMENTO ***'
		--AND TT.ORD_ANNO >= '2025'
	) AS MAIN
	GROUP BY
		ORD_ANNO,
		ART_LINEA,
		DES_LINEA,
		ORD_CONDET,
		DES_CONTO,
		ORD_CODART,
		ORD_DESART

GO

SELECT * FROM ORDINI_FORNITORI_MENSILE WHERE ANNO = '2025' ORDER BY ANNO, LINEA, CONTO, ARTICOLO