-- VISTA UTILIZZO_CPA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[UTILIZZO_CPA]'))
	DROP VIEW [dbo].[UTILIZZO_CPA]
GO

CREATE VIEW [dbo].[UTILIZZO_CPA]
AS

	SELECT
		CODICE,
		DESCRI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_CLI_AN WHERE CLI_CONPAG = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_ANAGR_CLIENTI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_FOR_AN WHERE FOR_CONPAG = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_ANAGR_FORNITORI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_FAT_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_FATTURE_CLIENTI,
		COALESCE((SELECT TOP 1 ORD_DATORD FROM U_FAT_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3) ORDER BY ORD_DATORD DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_FATTURE_CLIENTI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM U_ORF_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_ORDINI_FORNITORI,
		COALESCE((SELECT TOP 1 ORD_DATORD FROM U_ORF_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3) ORDER BY ORD_DATORD DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_ORDINI_FORNITORI,
		COALESCE((SELECT COUNT(*) AS CONTA FROM INDICE WHERE MOV_MODPAG = SUBSTRING(PARA.CODICE,4,3)),'') AS RICORRENZE_IN_CONTABILITA_GENERALE,
		COALESCE((SELECT TOP 1 MOV_DTREG FROM INDICE WHERE MOV_MODPAG = SUBSTRING(PARA.CODICE,4,3) ORDER BY MOV_DTREG DESC),'') AS DATA_ULTIMA_RICORRENZA_IN_CONTABILITA_GENERALE
	FROM PARA 

	WHERE
		CODICE LIKE 'CPA%'

GO

