
-- VISTA CONFR_SALDI_CONT_PART_CLI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CONFR_SALDI_CONT_PART_CLI]'))
	DROP VIEW [dbo].[CONFR_SALDI_CONT_PART_CLI]
GO

CREATE VIEW [dbo].[CONFR_SALDI_CONT_PART_CLI]  
AS

SELECT
	CON_CONTO AS CONTO_CLIENTE,
	CON_DESCR AS DESCRIZIONE,
	SALDO_CONTABILE,
	COALESCE(SALDO_PARTITE,0) AS SALDO_PARTITE,
	CAST((CASE WHEN COALESCE(T3.PAR_CODCLI_NO_LEG,'') = '' THEN 0 ELSE 1 END) AS BIT) AS PART_NO_LEG,
	CASE
		WHEN (COALESCE(SALDO_CONTABILE,0) = COALESCE(SALDO_PARTITE,0)) AND COALESCE(T3.PAR_CODCLI_NO_LEG,'') = '' THEN 'OK'
		ELSE 'KO'
	END AS CONFR_OK_KO
FROM (
	SELECT 
		CON_CONTO,
		SUBSTRING(CON_DESCR,1,30) AS CON_DESCR,
		COALESCE(SUM(CASE 
			WHEN MOV_TMOV='A' THEN MOV_IMP 
			ELSE  -1*MOV_IMP 
		END  ),0) AS SALDO_CONTABILE
	FROM CONTI 
	LEFT OUTER JOIN MOV_CONT AS MOV ON CON_CONTO=MOV.MOV_CONTO AND SUBSTRING(MOV_DTREG,1,4) = CAST(YEAR(GETDATE()) AS NVARCHAR(4))
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE='TOP'+MOV.MOV_TOP
	WHERE
		CON_TIPOCO='C' AND 
		CON_ANNO=CAST(YEAR(GETDATE()) AS NVARCHAR(4))
	GROUP BY CON_CONTO,SUBSTRING(CON_DESCR,1,30)
	) AS T1
	LEFT OUTER JOIN (
		SELECT 
			PAR_CODCLI,
			SUM(CASE 
				WHEN PAR_TMOV='A' THEN PAR_FATT 
				ELSE  -1*PAR_FATT 
			END  ) AS SALDO_PARTITE
		FROM  PART_CLI 
		WHERE PAR_NPROG<>100
		GROUP BY PAR_CODCLI
		) AS T2 ON T1.CON_CONTO = T2.PAR_CODCLI
	OUTER APPLY (
		SELECT TOP 1
			PAR_CODCLI AS PAR_CODCLI_NO_LEG
		FROM  PART_CLI 
		WHERE PAR_NPROG<>100 AND PAR_CODCLI = T1.CON_CONTO 
			AND PAR_NPART NOT IN (SELECT PAR_NPART FROM PART_CLI WHERE PAR_NPROG<>100 AND PAR_CODCLI = T1.CON_CONTO AND 'TOP'+PAR_TIPFAT IN (
					SELECT CODICE FROM PARA WHERE COALESCE(SUBSTRING(LIBERA,2,1),'') IN ('S','F','A') AND COALESCE(SUBSTRING(LIBERA,11,1),'') <> 'S'))
			AND PAR_NPART NOT IN (SELECT DISTINCT PAR_NPART FROM
											(SELECT PAR_NPART, COUNT(*) AS CONTA_RIGHE_PARTITA FROM PART_CLI AS PART 
												WHERE PAR_CODCLI=T1.CON_CONTO AND PAR_NPROG<>100 GROUP BY PAR_NPART) AS TMP_PART WHERE CONTA_RIGHE_PARTITA >= 2)
		GROUP BY PAR_CODCLI
		) AS T3

GO

--SELECT * FROM CONFR_SALDI_CONT_PART_CLI 
--WHERE SALDO_PARTITE <> SALDO_CONTABILE
--ORDER BY CONTO_CLIENTE
