
-- VISTA ORDINATO_FORNITORI_PER_ANNO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_FORNITORI_PER_ANNO]'))
	DROP VIEW [dbo].[ORDINATO_FORNITORI_PER_ANNO]
GO

CREATE VIEW [dbo].[ORDINATO_FORNITORI_PER_ANNO]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		TT.ORD_CODCLI AS COD_FORNITORE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_CPA AS COD_CPA,
		COALESCE(CPA.DESCRI,'') AS DES_CPA,
		SUM(ORD_VALORE*ORD_CAMBIO) AS TOTALE_EUR
	FROM U_ORF_TT AS TT
	LEFT OUTER JOIN PARA AS CPA ON CPA.CODICE LIKE 'CPA%' AND SUBSTRING(CPA.CODICE,4,3) = TT.ORD_CPA
	GROUP BY
		SUBSTRING(TT.ORD_DATORD,1,4),TT.ORD_CODCLI,TT.ORD_RAGSOC,TT.ORD_CPA,CPA.DESCRI
GO

SELECT * FROM ORDINATO_FORNITORI_PER_ANNO ORDER BY ANNO,RAG_SOCIALE