
-- VISTA BUDGET_SALDI_PER_DATA_DOCUMENTO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BUDGET_SALDI_PER_DATA_DOCUMENTO]'))
	DROP VIEW [dbo].[BUDGET_SALDI_PER_DATA_DOCUMENTO]
GO

CREATE VIEW [dbo].[BUDGET_SALDI_PER_DATA_DOCUMENTO]  
AS

	SELECT
		BUD_ANNO AS ANNO,
		BUD_CONTO AS CONTO,
		BUD_DESCR AS DESCRIZIONE,
		BUD_IMP_TT AS TOT_BUDGET,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,4) = RTRIM(BUDGET.BUD_ANNO)) AS TOT_SALDO,
		BUD_IMP_01 AS GENNAIO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'01') AS SALDO_GENNAIO,
		BUD_IMP_02 AS FEBBRAIO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'02') AS SALDO_FEBBRAIO,
		BUD_IMP_03 AS MARZO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'03') AS SALDO_MARZO,
		BUD_IMP_04 AS APRILE,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'04') AS SALDO_APRILE,
		BUD_IMP_05 AS MAGGIO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'05') AS SALDO_MAGGIO,
		BUD_IMP_06 AS GIUGNO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'06') AS SALDO_GIUGNO,
		BUD_IMP_07 AS LUGLIO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'07') AS SALDO_LUGLIO,
		BUD_IMP_08 AS AGOSTO,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'08') AS SALDO_AGOSTO,
		BUD_IMP_09 AS SETTEMBRE,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'09') AS SALDO_SETTEMBRE,
		BUD_IMP_10 AS OTTOBRE,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'10') AS SALDO_OTTOBRE,
		BUD_IMP_11 AS NOVEMBRE,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'11') AS SALDO_NOVEMBRE,
		BUD_IMP_12 AS DICEMBRE,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'D' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_TOP NOT IN ('APE','CHI') AND MOV_CONTO = BUDGET.BUD_CONTO AND SUBSTRING(MOV_DTDOC,1,7) = RTRIM(BUDGET.BUD_ANNO)+'/'+'12') AS SALDO_DICEMBRE
	FROM BUDGET
	WHERE LEN(BUD_CONTO) > 5

GO

