-- VISTA ORDINATO CON FATTURATO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_CON_FATTURATO]'))
	DROP VIEW [dbo].[ORDINATO_CON_FATTURATO]
GO


--•	Creiamo un altro archivio che risponda alle esigenze della mail sotto, cioè il monitoraggio dei valori fatturati per ogni ordine. Quindi dovrà comprendere le colonne seguenti, ricavate per buona parte dall'archivio del punto precedente, ma con le aggiunte e le accortezze che trovi sottolineate:
--COD_CLIENTE, RAG_SOCIALE, CAUSALE NUM_ORDINE, DATA_ORDINE, ANNO, MESE, RIFERIMENTO, CONDIZ_PAGAMENTO, DESC_CONDIZ_PAGAMENTO, ZONA DESC_ZONA NAZIONE, DESC_NAZIONE, CHIUSO, VALORE TOTALE ORDINE, NUM_FAT (Univoco per ogni riga), DATA_FAT, VALORE FATTURA.



CREATE VIEW [dbo].[ORDINATO_CON_FATTURATO]  
AS
	SELECT 
		TT.ORD_CODCLI AS COD_CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_CAUS AS CAUSALE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_DATORD AS DATA_ORDINE,
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_RIFERI AS RIFERIMENTO,
		TT.ORD_CPA AS CONDIZ_PAGAMENTO,
		COALESCE(P4.DESCRI,'') AS DESC_CONDIZ_PAGAMENTO,
		CLI.CLI_ZONA AS ZONA,
		COALESCE(P1.DESCRI,'') AS DESC_ZONA,
		CLI.CLI_NAZION AS NAZIONE,
		COALESCE(P2.DESCRI,'') AS DESC_NAZIONE,
		TT.ORD_CHIUSO AS CHIUSO,
		TT.ORD_VALORE AS VALORE_TOTALE_ORDINE,
		COALESCE(FAT.ORS_NUMORD,'') AS NUM_FATTURA,
		COALESCE(FAT.ORS_DATORD,'') AS DATA_FATTURA,
		COALESCE(FAT.ORD_VALORE,0) AS VALORE_FATTURA,
		TT.ORD_IMPONIB AS IMPONIBILE_ORDINE,
		COALESCE(FAT.IMPONIB_DD,0) AS IMPONIBILE_FATT_DA_ORDINE
	FROM U_ORD_TT AS TT
	OUTER APPLY (SELECT DISTINCT U_FAT_DD.ORS_NUMORD,U_FAT_DD.ORS_DATORD,U_FAT_TT.ORD_VALORE,SUM(U_FAT_DD.ORD_VALORE) AS IMPONIB_DD FROM U_FAT_DD RIGHT JOIN U_FAT_TT ON U_FAT_TT.TAGGANCIO = U_FAT_DD.DAGGANCIO 
		where ORD_CODART <> '' AND ((ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD) OR (ORS_NUMDDT+ORS_DATDDT IN (SELECT ORS_NUMORD+ORS_DATORD FROM U_BOL_DD WHERE ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)))
		GROUP BY U_FAT_DD.ORS_NUMORD,U_FAT_DD.ORS_DATORD,U_FAT_TT.ORD_VALORE) AS FAT
	LEFT OUTER JOIN U_CLI_AN AS CLI	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS P1 ON 'ZON'+CLI.CLI_ZONA = P1.CODICE
	LEFT OUTER JOIN PARA AS P2 ON 'STA'+CLI.CLI_NAZION = P2.CODICE
	LEFT OUTER JOIN PARA AS P3 ON 'PRO'+CLI.CLI_PROVIN = P3.CODICE
	LEFT OUTER JOIN PARA AS P4 ON 'CPA'+TT.ORD_CPA = P4.CODICE
GO

--SELECT * FROM [ORDINATO_CON_FATTURATO] WHERE ANNO = '2022' AND MESE = '09' ORDER BY NUM_ORDINE