
-- VISTA CRUSCOTTO_COMMERCIALE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CRUSCOTTO_COMMERCIALE]'))
	DROP VIEW [dbo].[CRUSCOTTO_COMMERCIALE]
GO

--SELECT * FROM U_STC_AN

CREATE VIEW [dbo].[CRUSCOTTO_COMMERCIALE]  
AS
	SELECT
		STC_ANNO AS ANNO,
		SUBSTRING(STC_DTDOC,6,2) AS MESE,
		STC_CODAGE AS COD_AGENTE,
		STC_DESAGE AS DES_AGENTE,
		STC_CODCLI AS COD_CLIENTE,
		STC_DESCLI AS RAG_SOCIALE,
		STC_CODART AS COD_ARTICOLO,
		STC_DESART AS DES_ARTICOLO,
		COALESCE(LNG_IT.DESCRI,'') AS DES_ARTICOLO_IT_COMM,
		COALESCE(LNG_EN.DESCRI,'') AS DES_ARTICOLO_EN_COMM,
		STC_LINEA AS COD_LINEA,
		STC_DESLIN AS DES_LINEA,
		STC_UNIMIS AS UM,
		STC_QTAVEN AS QTA,
		STC_NUMORD AS NUM_FATTURA,
		STC_DTDOC AS DATA_FATTURA,
		STC_VALORE * STC_CAMBIO AS VALORE_EUR,
		ART_PRZCOS AS PRZ_COSTO_STD,
		CLI_PROVIN AS PROVINCIA,
		COALESCE(STA.DESCRI,'') AS NAZIONE,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		COALESCE(CVEN_1_3.DESCRI,'') AS CANALE_VENDITA,
		COALESCE(CVEN_1_6.DESCRI,'') AS SETTORE,
		COALESCE(CVEN.DESCRI,'') AS TIPOLOGIA,
		DESCR_CCODET AS GENERE_DOCUMENTO
	FROM U_STC_AN AS STC
	LEFT OUTER JOIN U_CLI_AN AS CLI ON CLI.CLI_CODCLI = STC.STC_CODCLI
	LEFT OUTER JOIN U_ART_PR AS ART ON ART.ART_CODPRI = STC.STC_CODART
	LEFT OUTER JOIN PARA AS STA ON STA.CODICE LIKE 'STA%' AND SUBSTRING(STA.CODICE,4,3) = CLI.CLI_NAZION
	LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = CLI.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN DESLINGUE AS LNG_IT ON LNG_IT.TIPODES = 'ARTICOLO' AND LNG_IT.LINGUA = '010' AND LNG_IT.CODICE = STC.STC_CODART
	LEFT OUTER JOIN DESLINGUE AS LNG_EN ON LNG_EN.TIPODES = 'ARTICOLO' AND LNG_EN.LINGUA = '008' AND LNG_EN.CODICE = STC.STC_CODART
GO

SELECT * FROM CRUSCOTTO_COMMERCIALE WHERE ANNO = '2024' ORDER BY DATA_FATTURA,NUM_FATTURA,COD_ARTICOLO