
-- VISTA ARTICOLI_CONTI_LINEA_NAZIONE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI_CONTI_LINEA_NAZIONE]'))
	DROP VIEW [dbo].[ARTICOLI_CONTI_LINEA_NAZIONE]
GO

CREATE VIEW [dbo].[ARTICOLI_CONTI_LINEA_NAZIONE]  
AS

	WITH T_CRA AS (
		SELECT 
			SUBSTRING(P1.CODICE,4,6) AS CODICE_CRA,
			P1.DESCRI AS DESCRIZIONE_CRA,
			P1.LIBERA AS CONTO_CONTABILE_CRA,
			COALESCE((SELECT TOP 1 CON_DESCR FROM CONTI WHERE CON_CONTO = P1.LIBERA),'') AS DESCR_CONTO,
			SUBSTRING(SUBSTRING(RTRIM(P1.CODICE),4,6),1,LEN(SUBSTRING(RTRIM(P1.CODICE),4,6))-3) AS COD_LINEA,
			COALESCE(P2.DESCRI,'###PARAMETRO LINEA '+SUBSTRING(SUBSTRING(RTRIM(P1.CODICE),4,6),1,LEN(SUBSTRING(RTRIM(P1.CODICE),4,6))-3)+' MANCANTE###') AS DESCR_LINEA,
			RIGHT(RTRIM(P1.CODICE),3) AS NAZIONE, 
			P3.DESCRI AS DESCR_NAZIONE
		FROM PARA AS P1
		LEFT OUTER JOIN PARA AS P2 ON P2.CODICE = 'REP'+SUBSTRING(SUBSTRING(RTRIM(P1.CODICE),4,6),1,LEN(SUBSTRING(RTRIM(P1.CODICE),4,6))-3)
		LEFT OUTER JOIN PARA AS P3 ON P3.CODICE = 'STA'+RIGHT(RTRIM(P1.CODICE),3)
		WHERE P1.CODICE LIKE 'CRA%'
	)

	SELECT
		ART_CODPRI AS COD_ARTICOLO,
		ART_DESCR AS DESCR_ARTICOLO,
		ART_LINEA AS COD_LINEA_ARTICOLO,
		T_CRA.*
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN T_CRA ON T_CRA.COD_LINEA = PR.ART_LINEA

GO
