-- VISTA PLAFOND_FORNITORI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PLAFOND_FORNITORI]'))
	DROP VIEW [dbo].[PLAFOND_FORNITORI]
GO

CREATE VIEW [dbo].[PLAFOND_FORNITORI]
AS

	SELECT 
		IVA_ANNO AS ANNO,
		IVA_CODFOR AS CODFOR,
		IVA_DESFOR AS DESFOR,
		IVA_PLAFOND AS PLAFOND_TOTALE,
		IVA_GENNAI AS IMPONIB_GENNAI,
		IVA_FEBBRA AS IMPONIB_FEBBRA,
		IVA_MARZO AS IMPONIB_MARZO,
		IVA_APRILE AS IMPONIB_APRILE,
		IVA_MAGGIO AS IMPONIB_MAGGIO,
		IVA_GIUGNO AS IMPONIB_GIUGNO,
		IVA_LUGLIO AS IMPONIB_LUGLIO,
		IVA_AGOSTO AS IMPONIB_AGOSTO,
		IVA_SETTEM AS IMPONIB_SETTEM,
		IVA_OTTOBR AS IMPONIB_OTTOBR,
		IVA_NOVEMB AS IMPONIB_NOVEMB,
		IVA_DICEMB AS IMPONIB_DICEMB,
		IVA_GENNAI+IVA_FEBBRA+IVA_MARZO+IVA_APRILE+IVA_MAGGIO+IVA_GIUGNO+IVA_LUGLIO+IVA_AGOSTO+IVA_SETTEM+IVA_OTTOBR+IVA_NOVEMB+IVA_DICEMB AS IMPONIB_TOTALE,
		IVA_01RESI AS IMPONIB_RESIDUO_GENNAI,
		IVA_02RESI AS IMPONIB_RESIDUO_FEBBRA,
		IVA_03RESI AS IMPONIB_RESIDUO_MARZO,
		IVA_04RESI AS IMPONIB_RESIDUO_APRILE,
		IVA_05RESI AS IMPONIB_RESIDUO_MAGGIO,
		IVA_06RESI AS IMPONIB_RESIDUO_GIUGNO,
		IVA_07RESI AS IMPONIB_RESIDUO_LUGLIO,
		IVA_08RESI AS IMPONIB_RESIDUO_AGOSTO,
		IVA_09RESI AS IMPONIB_RESIDUO_SETTEM,
		IVA_10RESI AS IMPONIB_RESIDUO_OTTOBR,
		IVA_11RESI AS IMPONIB_RESIDUO_NOVEMB,
		IVA_12RESI AS IMPONIB_RESIDUO_DICEMB,
		IVA_PLAFOND-IVA_GENNAI-IVA_FEBBRA-IVA_MARZO-IVA_APRILE-IVA_MAGGIO-IVA_GIUGNO-IVA_LUGLIO-IVA_AGOSTO-IVA_SETTEM-IVA_OTTOBR-IVA_NOVEMB-IVA_DICEMB AS IMPONIB_RESIDUO_TOTALE
	FROM U_IVA_FE WHERE IVA_CODFOR <> ''

GO
