-- VISTA ARTICOLI_LINGUE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI_LINGUE]'))
	DROP VIEW [dbo].[ARTICOLI_LINGUE]
GO

CREATE VIEW [dbo].[ARTICOLI_LINGUE]  
AS
	SELECT
		ART_CODPRI, 
		ART_DESCR, 
		COALESCE(IT.DESCRI,'') AS DESCR_IT,
		COALESCE(EN.DESCRI,'') AS DESCR_EN,
		ART_DESEST, 
		ART_MAGA, 
		ART_UNIMIS, 
		ART_UMMAGA, 
		ART_LINEA, 
		ART_PRZVEN, 
		ART_PRZVE2, 
		ART_PRZVE3, 
		ART_PRZVE4, 
		ART_PRZVE5, 
		ART_PRZCOS, 
		ART_ULPCAR, 
		ART_PRZCO1, 
		ART_TIPART, 
		ART_CLDOG, 
		ART_PESOUM, 
		ART_PESOSP, 
		ART_CATMER, 
		ART_SCORMI, 
		ART_DATINS,
		ART_OBSOL
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN DESLINGUE AS IT ON IT.TIPODES = 'ARTICOLO' AND IT.CODICE = PR.ART_CODPRI AND IT.LINGUA = '010'
	LEFT OUTER JOIN DESLINGUE AS EN ON EN.TIPODES = 'ARTICOLO' AND EN.CODICE = PR.ART_CODPRI AND EN.LINGUA = '008'

GO

SELECT * FROM [ARTICOLI_LINGUE] ORDER BY ART_CODPRI