
-- VISTA ARTICOLI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI]'))
	DROP VIEW [dbo].[ARTICOLI]
GO

CREATE VIEW [dbo].[ARTICOLI]  
AS

	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCR_ARTICOLO,
		AN.ART_CGEACQ AS COD_CONTO_ACQUISTI,
		COALESCE(CC.CON_DESCR,'') AS DESCR_CONTO_ACQUISTI,
		ART_DATVAR AS DATA_INSERIMENTO,
		ART_DATINS AS DATA_MODIFICA,
		COALESCE(MAG_GIACEN,0) AS GIACENZA
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN CONTI AS CC ON CC.CON_CONTO = AN.ART_CGEACQ AND CON_ANNO = CAST(YEAR(GETDATE()) AS char(4))
	LEFT OUTER JOIN (SELECT MAG_ANAART,SUM(MAG_GIACEN) AS MAG_GIACEN FROM U_MAG_GG GROUP BY MAG_ANAART) AS GG ON GG.MAG_ANAART = PR.ART_CODPRI

GO
