-- VISTA FATTURE_CLIENTI_DA_SALDARE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_CLIENTI_DA_SALDARE]'))
	DROP VIEW [dbo].[FATTURE_CLIENTI_DA_SALDARE]
GO

CREATE VIEW [dbo].[FATTURE_CLIENTI_DA_SALDARE]
AS

	SELECT
		SUBSTRING(RIGHE_PART.PAR_CODCLI,5,10) AS COD_CLIENTE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NPROT AS NUM_FATTURA,
		RIGHE_PART.PAR_DTFAT AS DATA_FATTURA,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) AS IMPORTO_SCAD_PAG,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		ROUND(FAT_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		ROUND(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO + FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,2) AS IMPONIBILE_IMPOSTA_TOT_FATTURA,
		ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		ROUND(COALESCE(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO,0),2) AS IMPONIBILE_TOT_FATTURA,
		ROUND(COALESCE(FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,0),2) AS IMPOSTA_TOT_FATTURA,
		COALESCE(U_CLI_AN.CLI_CANVEN,'') AS CANALE_VENDITA_CLIENTE,
		COALESCE(PARA_CVE.DESCRI,'') AS DESCR_CANALE_VENDITA_CLIENTE,
		COALESCE(U_CLI_AN.CLI_NAZION,'') AS NAZIONE_CLIENTE,
		COALESCE(PARA_STA.DESCRI,'') AS DESCR_NAZIONE_CLIENTE,
		COALESCE(U_CLI_AN.CLI_ZONA,'') AS AREA_GEOGRAFICA_CLIENTE,
		COALESCE(PARA_ZON.DESCRI,'') AS DESCR_AREA_GEOGRAFICA_CLIENTE,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO

	FROM PART_CLI AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'D' GROUP BY PAR_CODCLI, PAR_NPART) AS FAT_TOT ON FAT_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAT_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_SCAD_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS ULT_IMPORTO_SCAD_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS PAG_ULT
		OUTER APPLY (SELECT TOP 1 PAR_ANNO,PAR_DTSCAD,PAR_NPROT,PAR_DTFAT FROM PART_CLI WHERE PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_NPROG <> 100 AND PAR_TMOV = 'D' AND PAR_TIPODO = 'FAT' ORDER BY PAR_DTSCAD) AS TEST_PART
		RIGHT OUTER JOIN U_FAT_TT AS FAT_TT ON FAT_TT.ORD_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_TT.ORD_DATORD = RIGHE_PART.PAR_DTFAT
		LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODCLI = FAT_TT.ORD_CODCLI
		LEFT OUTER JOIN PARA AS PARA_CVE ON PARA_CVE.CODICE = 'CVE'+U_CLI_AN.CLI_CANVEN
		LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION
		LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+U_CLI_AN.CLI_ZONA
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'D' AND RIGHE_PART.PAR_TIPODO = 'FAT')
		AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAT_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))
		AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)

GO

