
-- VISTA FATTURATO_PER_ANNO_LINEA_CLIENTE_AGENTE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_PER_ANNO_LINEA_CLIENTE_AGENTE]'))
	DROP VIEW [dbo].[FATTURATO_PER_ANNO_LINEA_CLIENTE_AGENTE]
GO

CREATE VIEW [dbo].[FATTURATO_PER_ANNO_LINEA_CLIENTE_AGENTE]  
AS

SELECT
	ANNO,
	COD_LINEA,
	COD_NAZIONE,
	DES_NAZIONE,
	COD_CLIENTE,
	DES_CLIENTE,
	COD_AGENTE,
	DES_AGENTE,
	COD_CANVEN,
	DES_CANVEN,
	PROVINCIA,
	COD_ARTICOLO,
	DES_ARTICOLO,
	SUM(GEN_QTA) AS GEN_QTA,
	SUM(GEN_VALORE_EUR) AS GEN_VALORE_EUR,
	SUM(FEB_QTA) AS FEB_QTA,
	SUM(FEB_VALORE_EUR) AS FEB_VALORE_EUR,
	SUM(MAR_QTA) AS MAR_QTA,
	SUM(MAR_VALORE_EUR) AS MAR_VALORE_EUR,
	SUM(APR_QTA) AS APR_QTA,
	SUM(APR_VALORE_EUR) AS APR_VALORE_EUR,
	SUM(MAG_QTA) AS MAG_QTA,
	SUM(MAG_VALORE_EUR) AS MAG_VALORE_EUR,
	SUM(GIU_QTA) AS GIU_QTA,
	SUM(GIU_VALORE_EUR) AS GIU_VALORE_EUR,
	SUM(LUG_QTA) AS LUG_QTA,
	SUM(LUG_VALORE_EUR) AS LUG_VALORE_EUR,
	SUM(AGO_QTA) AS AGO_QTA,
	SUM(AGO_VALORE_EUR) AS AGO_VALORE_EUR,
	SUM(SET_QTA) AS SET_QTA,
	SUM(SET_VALORE_EUR) AS SET_VALORE_EUR,
	SUM(OTT_QTA) AS OTT_QTA,
	SUM(OTT_VALORE_EUR) AS OTT_VALORE_EUR,
	SUM(NOV_QTA) AS NOV_QTA,
	SUM(NOV_VALORE_EUR) AS NOV_VALORE_EUR,
	SUM(DIC_QTA) AS DIC_QTA,
	SUM(DIC_VALORE_EUR) AS DIC_VALORE_EUR
FROM (
	SELECT
		SUBSTRING(STC.STC_DATA,1,4) AS ANNO,
		STC.STC_LINEA AS COD_LINEA,
		COALESCE(CLI.CLI_NAZION,'') AS COD_NAZIONE,
		COALESCE(STA.DESCRI,'') AS DES_NAZIONE,
		STC.STC_CODCLI AS COD_CLIENTE,
		STC.STC_DESCLI AS DES_CLIENTE,
		STC.STC_CODAGE AS COD_AGENTE,
		STC.STC_DESAGE AS DES_AGENTE,
		STC.STC_CANVEN AS COD_CANVEN,
		STC.STC_DESCVE AS DES_CANVEN,
		COALESCE(CLI.CLI_PROVIN,'') AS PROVINCIA,
		STC.STC_CODART AS COD_ARTICOLO,
		STC.STC_DESART AS DES_ARTICOLO,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '01' THEN STC_QTAVEN ELSE 0 END AS GEN_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '01' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS GEN_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '02' THEN STC_QTAVEN ELSE 0 END AS FEB_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '02' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS FEB_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '03' THEN STC_QTAVEN ELSE 0 END AS MAR_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '03' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS MAR_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '04' THEN STC_QTAVEN ELSE 0 END AS APR_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '04' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS APR_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '05' THEN STC_QTAVEN ELSE 0 END AS MAG_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '05' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS MAG_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '06' THEN STC_QTAVEN ELSE 0 END AS GIU_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '06' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS GIU_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '07' THEN STC_QTAVEN ELSE 0 END AS LUG_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '07' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS LUG_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '08' THEN STC_QTAVEN ELSE 0 END AS AGO_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '08' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS AGO_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '09' THEN STC_QTAVEN ELSE 0 END AS SET_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '09' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS SET_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '10' THEN STC_QTAVEN ELSE 0 END AS OTT_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '10' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS OTT_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '11' THEN STC_QTAVEN ELSE 0 END AS NOV_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '11' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS NOV_VALORE_EUR,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '12' THEN STC_QTAVEN ELSE 0 END AS DIC_QTA,
		CASE SUBSTRING(STC_DATA,5,2) WHEN '12' THEN (STC_VALORE * STC_CAMBIO) ELSE 0 END AS DIC_VALORE_EUR
	FROM U_STC_AN AS STC
	LEFT OUTER JOIN U_CLI_AN AS CLI ON CLI.CLI_CODCLI = STC.STC_CODCLI
	LEFT OUTER JOIN PARA AS STA ON STA.CODICE LIKE 'STA%' AND SUBSTRING(STA.CODICE,4,3) = CLI.CLI_NAZION
	) AS MAIN
GROUP BY
	ANNO,
	COD_LINEA,
	COD_NAZIONE,
	DES_NAZIONE,
	COD_CLIENTE,
	DES_CLIENTE,
	COD_AGENTE,
	DES_AGENTE,
	COD_CANVEN,
	DES_CANVEN,
	PROVINCIA,
	COD_ARTICOLO,
	DES_ARTICOLO

GO

SELECT * FROM FATTURATO_PER_ANNO_LINEA_CLIENTE_AGENTE ORDER BY ANNO