
-- VISTA FATTURATO_CLIENTI_PERSONA_FISICA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_CLIENTI_PERSONA_FISICA]'))
	DROP VIEW [dbo].[FATTURATO_CLIENTI_PERSONA_FISICA]
GO

CREATE VIEW [dbo].[FATTURATO_CLIENTI_PERSONA_FISICA]  
AS
	SELECT 
		ORD_ANNO AS ANNO,
		ORD_NUMORD AS NUM_FATTURA,
		ORD_DATORD AS DATA_FATTURA,
		ORD_CODCLI AS COD_CLIENTE,
		ORD_RAGSOC AS RAG_SOCIALE,
		ORD_VALORE AS IMPORTO,
		ORD_IMPONIB AS IMPONIBILE,
		ORD_IMPOSTA AS IMPOSTA
	FROM U_FAT_TT
	LEFT OUTER JOIN U_CLI_AN ON U_FAT_TT.ORD_CODCLI = U_CLI_AN.CLI_CODCLI
	WHERE U_CLI_AN.CLI_RECCAT = 2
GO
