-- VISTA ARTICOLI_LEAD_TIME

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI_LEAD_TIME]'))
	DROP VIEW [dbo].[ARTICOLI_LEAD_TIME]
GO

CREATE VIEW [dbo].[ARTICOLI_LEAD_TIME]  
AS

SELECT
	PR.ART_CODPRI AS Codice,
	PR.ART_DESCR AS Descrizione,
	AN.ART_LDTMST AS Lead_Time_standard,
	PR.ART_LOTMIN AS Lotto_minimo,
	PR.ART_SCORMI AS Scorta_minima,
	PR.ART_COSMAT AS Prezzo_materiale,
	PR.ART_UNIMIS AS UM_acquisti,
	RTRIM(PR.ART_CODF1) + CASE PR.ART_CODF1 WHEN '' THEN '' ELSE ' - '+COALESCE(F1.FOR_RAGSOC,'') END AS Fornitore_1,
	AN.ART_LDTM1 AS Lead_Time_Fornitore_1,
	0 AS Lotto_minimo_Fornitore_1,
	PR.ART_PRZCO1 AS Prezzo_Fornitore_1,
	RTRIM(PR.ART_CODF2) + CASE PR.ART_CODF2 WHEN '' THEN '' ELSE ' - '+COALESCE(F2.FOR_RAGSOC,'') END AS Fornitore_2,
	AN.ART_LDTM2 AS Lead_Time_Fornitore_2,
	0 AS Lotto_minimo_Fornitore_2,
	PR.ART_PRZCO2 AS Prezzo_Fornitore_2,
	RTRIM(PR.ART_CODF3) + CASE PR.ART_CODF3 WHEN '' THEN '' ELSE ' - '+COALESCE(F3.FOR_RAGSOC,'') END AS Fornitore_3,
	AN.ART_LDTM3 AS Lead_Time_Fornitore_3,
	0 AS Lotto_minimo_Fornitore_3,
	PR.ART_PRZCO3 AS Prezzo_Fornitore_3,
	RTRIM(PR.ART_CODF4) + CASE PR.ART_CODF4 WHEN '' THEN '' ELSE ' - '+COALESCE(F4.FOR_RAGSOC,'') END AS Fornitore_4,
	AN.ART_LDTM4 AS Lead_Time_Fornitore_4,
	0 AS Lotto_minimo_Fornitore_4,
	PR.ART_PRZCO4 AS Prezzo_Fornitore_4,
	RTRIM(PR.ART_CODF5) + CASE PR.ART_CODF5 WHEN '' THEN '' ELSE ' - '+COALESCE(F5.FOR_RAGSOC,'') END AS Fornitore_5,
	AN.ART_LDTM5 AS Lead_Time_Fornitore_5,
	0 AS Lotto_minimo_Fornitore_5,
	PR.ART_PRZCO5 AS Prezzo_Fornitore_5,
	AN.ART_CGEACQ AS Codice_conto_contabile,
	COALESCE(CONTI.CON_DESCR,'') AS Descrizione_conto_contabile
FROM U_ART_PR AS PR
LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = CAST(YEAR(GETDATE()) AS varchar(4)) AND CONTI.CON_CONTO = AN.ART_CGEACQ
LEFT OUTER JOIN U_FOR_AN AS F1 ON F1.FOR_CODCLI = PR.ART_CODF1
LEFT OUTER JOIN U_FOR_AN AS F2 ON F2.FOR_CODCLI = PR.ART_CODF2
LEFT OUTER JOIN U_FOR_AN AS F3 ON F3.FOR_CODCLI = PR.ART_CODF3
LEFT OUTER JOIN U_FOR_AN AS F4 ON F4.FOR_CODCLI = PR.ART_CODF4
LEFT OUTER JOIN U_FOR_AN AS F5 ON F5.FOR_CODCLI = PR.ART_CODF5

GO

SELECT * FROM ARTICOLI_LEAD_TIME ORDER BY Codice
