/*
•	codice fornitore
•	ragione sociale
•	codice cond pagamento
•	descrizione condizione di pagamento
•	netto fatturato
•	obsoleto
•	email 1, 2,3
•	sito web
•	codice conto contabile
•	descrizione conto contabile
•	valuta
•	codice iva 
•	descrizione codice iva

*/

-- VISTA ANAGR_FORNIT
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_FORNIT]'))
	DROP VIEW [dbo].[ANAGR_FORNIT]
GO
CREATE VIEW [dbo].[ANAGR_FORNIT]
AS
	SELECT
		FOR_CODCLI AS CODFOR,
		FOR_RAGSOC AS RAGSOC,
		FOR_CONPAG AS CONPAG,
		COALESCE(CPA.DESCRI,'') AS DESCR_CONPAG,
		(SELECT COALESCE(SUM((CASE MOV_TMOV WHEN 'A' THEN 1 ELSE -1 END) * MOV_IMP),0) FROM MOV_CONT WHERE MOV_CONTO = '3031'+U_FOR_AN.FOR_CODCLI AND MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')) AS TOT_FATTURATO,
		FOR_OBSOL AS OBSOL,
		FOR_EMAIL AS EMAIL_ANAGR,
		COALESCE(EML_GEN.INDIRIZZO_A,'') AS EMAIL_A_GEN,
		COALESCE(EML_RDA.INDIRIZZO_A,'') AS EMAIL_A_RDA,
		COALESCE(EML_ORF.INDIRIZZO_A,'') AS EMAIL_A_ORF,
		COALESCE(EML_BFO.INDIRIZZO_A,'') AS EMAIL_A_BFO,
		COALESCE(EML_REF.INDIRIZZO_A,'') AS EMAIL_A_REF,
		FOR_TELEX AS WEB,
		FOR_CONTO1 AS CONTO,
		COALESCE(CONTI.CON_DESCR,'') AS DESCR_CONTO,
		FOR_VALUTA AS VALUTA,
		FOR_CODIVA AS COD_IVA,
		COALESCE(IVA.DESCRI,'') AS DESCR_IVA
	FROM U_FOR_AN
	LEFT OUTER JOIN PARA AS CPA ON CPA.CODICE LIKE 'CPA%' AND SUBSTRING(CPA.CODICE,4,3) = U_FOR_AN.FOR_CONPAG
	LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = (SELECT TOP 1 SUBSTRING(CODICE,6,4) FROM PARA WHERE CODICE LIKE 'ANN%' ORDER BY CODICE DESC) AND CON_CONTO = U_FOR_AN.FOR_CONTO1
	LEFT OUTER JOIN PARA AS IVA ON IVA.CODICE LIKE 'IVA%' AND SUBSTRING(IVA.CODICE,4,3) = U_FOR_AN.FOR_CODIVA
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_GEN ON EML_GEN.CLI_FOR = 'F' AND EML_GEN.CODICE_CLI_FOR = U_FOR_AN.FOR_CODCLI AND EML_GEN.TIPO_DOC = 'GEN'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_RDA ON EML_RDA.CLI_FOR = 'F' AND EML_RDA.CODICE_CLI_FOR = U_FOR_AN.FOR_CODCLI AND EML_RDA.TIPO_DOC = 'RDA'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_ORF ON EML_ORF.CLI_FOR = 'F' AND EML_ORF.CODICE_CLI_FOR = U_FOR_AN.FOR_CODCLI AND EML_ORF.TIPO_DOC = 'ORF'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_BFO ON EML_BFO.CLI_FOR = 'F' AND EML_BFO.CODICE_CLI_FOR = U_FOR_AN.FOR_CODCLI AND EML_BFO.TIPO_DOC = 'BFO'
	LEFT OUTER JOIN MAIL_ADDRESS AS EML_REF ON EML_REF.CLI_FOR = 'F' AND EML_REF.CODICE_CLI_FOR = U_FOR_AN.FOR_CODCLI AND EML_REF.TIPO_DOC = 'REF'
GO

SELECT * FROM ANAGR_FORNIT ORDER BY CODFOR


