
-- VISTA ACQUISTI_RAGGR_PER_ANNO_FORN_CPAG

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ACQUISTI_RAGGR_PER_ANNO_FORN_CPAG]'))
	DROP VIEW [dbo].[ACQUISTI_RAGGR_PER_ANNO_FORN_CPAG]
GO

CREATE VIEW [dbo].[ACQUISTI_RAGGR_PER_ANNO_FORN_CPAG]  
AS

SELECT
	MOV_CONT.MOV_ANNO AS ANNO_REGISTRAZIONE,
	MOV_CONT.MOV_CONTO AS COD_FORNITORE,
	CONTI.CON_DESCR AS RAG_SOCIALE,
	MOV_CONT.MOV_MODPAG AS COD_CONDIZ_PAG,
	COALESCE(PARA.DESCRI,'') AS DESCR_CONDIZ_PAG,
	CAST(ROUND(SUM(MOV_CONT.MOV_IMP * MOV_CONT.MOV_CAMBIO),2) AS numeric(19,2)) AS IMPORTO_TOTALE
FROM MOV_CONT
LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = MOV_CONT.MOV_ANNO AND CONTI.CON_CONTO = MOV_CONT.MOV_CONTO
LEFT OUTER JOIN PARA ON SUBSTRING(PARA.CODICE,1,3) = 'CPA' AND SUBSTRING(PARA.CODICE,4,3) = MOV_CONT.MOV_MODPAG
WHERE 
	CONTI.CON_TIPOCO = 'F'
	AND MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
GROUP BY MOV_CONT.MOV_ANNO,MOV_CONTO,CONTI.CON_DESCR,MOV_CONT.MOV_MODPAG,COALESCE(PARA.DESCRI,'')

--SELECT * FROM ACQUISTI_RAGGR_PER_ANNO_FORN_CPAG ORDER BY ANNO_REGISTRAZIONE,RAG_SOCIALE
