SELECT * FROM CONTI ORDER BY CON_ANNO,CON_CONTO
SELECT * FROM PART_CLI WHERE PAR_ANNO = '2019'
SELECT * FROM CONTI WHERE CON_ANNO <> '2019' ORDER BY CON_ANNO,CON_CONTO
SELECT * FROM CONTI WHERE CON_ANNO = '2019' AND  SUBSTRING(CON_CONTO,1,4) = '1212'   ORDER BY CON_ANNO,CON_CONTO


SELECT * FROM INDICE WHERE MOV_ANNO = '2013'
SELECT * FROM INDICE WHERE MOV_ANNO = '2017'
SELECT * FROM MOV_CONT WHERE MOV_ANNO = '2019' ORDER BY MOV_NUMPRO,MOV_SEQUEN
SELECT * FROM PART_CLI WHERE PAR_ANNO = '2019'
SELECT * FROM PART_FOR WHERE PAR_ANNO = '2019'

SELECT * FROM MOV_CONT WHERE MOV_ANNO = '2019' AND SUBSTRING(MOV_CONTO,1,4) <> '0301'

SELECT * FROM INDICE WHERE SUBSTRING(MOV_CONTO,1,4) = '1011'
--UPDATE INDICE SET MOV_CONTO = '0301'+ SUBSTRING(MOV_CONTO,5,10)

--UPDATE TABLE
DELETE FROM INDICE WHERE MOV_ANNO < '2018'
DELETE FROM MOV_CONT WHERE MOV_ANNO < '2018'
--DELETE FROM PART_CLI WHERE PAR_ANNO < '2018'
DELETE FROM PART_CLI WHERE PAR_npart NOT in (SELECT PAR_NPART FROM PART_CLI WHERE PAR_DTFAT >= '2018/08/01' AND PAR_TIPODO = 'FAT')

UPDATE INDICE   SET MOV_CONTO  = '0301'+ SUBSTRING(MOV_CONTO,5,10) WHERE SUBSTRING(MOV_CONTO,1,4)    = '1011' 
UPDATE MOV_CONT SET MOV_CONTO  = '0301'+ SUBSTRING(MOV_CONTO,5,10) WHERE SUBSTRING(MOV_CONTO,1,4)    = '1011'
UPDATE PART_CLI SET PAR_CODCLI = '0301'+ SUBSTRING(PAR_CODCLI,5,10) WHERE  SUBSTRING(PAR_CODCLI,1,4) <> '1012'

UPDATE INDICE   SET MOV_CONTO  = '0302'+ SUBSTRING(MOV_CONTO,5,10) WHERE SUBSTRING(MOV_CONTO,1,4)    = '1012' 
UPDATE MOV_CONT SET MOV_CONTO  = '0302'+ SUBSTRING(MOV_CONTO,5,10) WHERE SUBSTRING(MOV_CONTO,1,4)    = '1012'
UPDATE PART_CLI SET PAR_CODCLI = '0302'+ SUBSTRING(PAR_CODCLI,5,10) WHERE  SUBSTRING(PAR_CODCLI,1,4) = '1012'

UPDATE MOV_CONT SET MOV_CONTO = '2020002' WHERE MOV_CONTO = '1414002'
UPDATE MOV_CONT SET MOV_CONTO = '8080001' WHERE MOV_CONTO = '8010001'






