-- VISTA ANAGRAFICA_ARTICOLI_PER_CAMBIO_CODICE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_PER_CAMBIO_CODICE]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_PER_CAMBIO_CODICE]
GO

CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_PER_CAMBIO_CODICE]
AS

	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		PR.ART_MAGA AS MAGAZZINO,
		PR.ART_CODMAT AS TIPO_PRODOTTO,
		PR.ART_CODF1 AS COD_FORNITORE_1,
		COALESCE(FORN.FOR_RAGSOC,'') AS DESCR_FORNITORE_1,
		ART_NOTA1 AS COD_ARTICOLO_FORNITORE_1
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_FOR_AN AS FORN ON FORN.FOR_CODCLI = PR.ART_CODF1

GO

SELECT * FROM ANAGRAFICA_ARTICOLI_PER_CAMBIO_CODICE WHERE MAGAZZINO = 'OLEO' ORDER BY COD_ARTICOLO