
-- POPOLAMENTO PARAMETRO PER REPORT ETICHETTE DA UTILIZZARE NEL CARICO DELLE MATERIE PRIME E SEMILAVORATI
-- ### ATTENZIONE !!! : IL SETTAGGIO DEI NOMI DEI REPORT E' POSIZIONALE; RISPETTARE CARATTERI E SPAZI

DELETE FROM PARA WHERE CODICE = 'EXR01'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('EXR01','ETICHETTE PER CARICO SEMILAVORATI','ETICSPALMAR_SOP.LBX')
