
DELETE FROM PARA WHERE CODICE = 'EPP001'
DELETE FROM PARA WHERE CODICE = 'EPP002'

INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('EPP001','UTILE ESERCIZIO PRECEDENTE PROVVISORIO','203099')
INSERT INTO PARA (CODICE, DESCRI, LIBERA) VALUES ('EPP002','PERDITA ESERCIZIO PRECEDENTE PROVVISORIO','116099')

SELECT * FROM PARA WHERE CODICE LIKE 'EPP%' ORDER BY CODICE


