
SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_AN
SELECT * FROM SOPRAD.DBO.U_AZI_AN

SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_PA
SELECT * FROM SOPRAD.DBO.U_AZI_PA

SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_PB
SELECT * FROM SOPRAD.DBO.U_AZI_PB


/*
N.B.: U_AZI_AN E' IDENTICO
--DELETE FROM SOPRAD.DBO.U_AZI_AN
--INSERT INTO SOPRAD.DBO.U_AZI_AN SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_AN

DELETE FROM SOPRAD.DBO.U_AZI_PA
INSERT INTO SOPRAD.DBO.U_AZI_PA SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_PA

DELETE FROM SOPRAD.DBO.U_AZI_PB
INSERT INTO SOPRAD.DBO.U_AZI_PB SELECT * FROM SOPRAD_COLLAUDO.DBO.U_AZI_PB
*/