
UPDATE PARA SET LIBERA = 'E' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'EXW' OR SUBSTRING(DESCRI,1,4) = 'EXW ' OR SUBSTRING(DESCRI,1,6) = 'E X W ')

UPDATE PARA SET LIBERA = 'F' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'FCA' OR SUBSTRING(DESCRI,1,4) = 'FCA ' OR SUBSTRING(DESCRI,1,6) = 'F C A ')
UPDATE PARA SET LIBERA = 'F' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'FAS' OR SUBSTRING(DESCRI,1,4) = 'FAS ' OR SUBSTRING(DESCRI,1,6) = 'F A S ')
UPDATE PARA SET LIBERA = 'F' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'FOB' OR SUBSTRING(DESCRI,1,4) = 'FOB ' OR SUBSTRING(DESCRI,1,6) = 'F O B ')

UPDATE PARA SET LIBERA = 'C' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'CFR' OR SUBSTRING(DESCRI,1,4) = 'CFR ' OR SUBSTRING(DESCRI,1,6) = 'C F R ')
UPDATE PARA SET LIBERA = 'C' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'CIF' OR SUBSTRING(DESCRI,1,4) = 'CIF ' OR SUBSTRING(DESCRI,1,6) = 'C I F ')
UPDATE PARA SET LIBERA = 'C' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'CPT' OR SUBSTRING(DESCRI,1,4) = 'CPT ' OR SUBSTRING(DESCRI,1,6) = 'C P T ')
UPDATE PARA SET LIBERA = 'C' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'CIP' OR SUBSTRING(DESCRI,1,4) = 'CIP ' OR SUBSTRING(DESCRI,1,6) = 'C I P ')

UPDATE PARA SET LIBERA = 'D' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'DAF' OR SUBSTRING(DESCRI,1,4) = 'DAF ' OR SUBSTRING(DESCRI,1,6) = 'D A F ')
UPDATE PARA SET LIBERA = 'D' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'DES' OR SUBSTRING(DESCRI,1,4) = 'DES ' OR SUBSTRING(DESCRI,1,6) = 'D E S ')
UPDATE PARA SET LIBERA = 'D' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'DEQ' OR SUBSTRING(DESCRI,1,4) = 'DEQ ' OR SUBSTRING(DESCRI,1,6) = 'D E Q ')
UPDATE PARA SET LIBERA = 'D' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'DDU' OR SUBSTRING(DESCRI,1,4) = 'DDU ' OR SUBSTRING(DESCRI,1,6) = 'D D U ')
UPDATE PARA SET LIBERA = 'D' WHERE CODICE LIKE 'POR%' AND (SUBSTRING(CODICE,4,3) = 'DDP' OR SUBSTRING(DESCRI,1,4) = 'DDP ' OR SUBSTRING(DESCRI,1,6) = 'D D P ')



UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR&F' --C&F
UPDATE PARA SET LIBERA = 'E' WHERE CODICE = 'POR01' --FRANCO NS. STABILIMENTO
UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'POR02' --FRANCO VETTORE-SOTTO BORDO-FRANCO A BORDO
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR03' --COSTO E NOLO- COSTO ASSICURAZIONE E NOLO-TRASPORTO PAGATO FI
UPDATE PARA SET LIBERA = 'D' WHERE CODICE = 'POR04' --RESO ALLA FRONTIERA- RESO A BORDO- RESO SULLA BANCHINA - RES
UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'POR05' --PORTO FRANCO
UPDATE PARA SET LIBERA = 'E' WHERE CODICE = 'POR06' --PORTO ASSEGNATO
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR07' --C F R ISTANBUL
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR08' --C I F ALEXANDRIA PORT
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR09' --CARRIAGE PAID TO
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR10' --CPT FOLTEC
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR20' --CFR.L.T.
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'POR70' --CIF AIRPORT
UPDATE PARA SET LIBERA = 'E' WHERE CODICE = 'PORAB' --ABWERK
UPDATE PARA SET LIBERA = '' WHERE CODICE = 'PORAIR' -- AIR FREIGHT


SELECT * FROM PARA WHERE CODICE LIKE 'POR%' ORDER BY CODICE