
WITH CorrezioneDIBA
AS (
	SELECT * FROM (
		select DIS_GRUPPO,DIS_CODART,DIS_FASELA,dis_costo,CASE WHEN (COALESCE(PIANIF.QCONF,0) > 0 AND COALESCE(lavt.ECOSTU,0) > 0) THEN (lavt.ECOSTU / PIANIF.QCONF) ELSE 0 END AS COSTO_UNITARIO_PIANIFICAZ_FABRICA,lavt.ECOSTU,PIANIF.QCONF from u_dis_dd 
		outer apply (select top 1 * from CARD_lavt where CODART = u_dis_dd.dis_gruppo AND TIPORD = 'PF' AND CODFASE = '0'+u_dis_dd.dis_fasela ORDER BY DATAIL DESC) AS lavt
		LEFT OUTER JOIN CARD_PIANIF AS PIANIF ON PIANIF.TIPREC = LAVT.TIPREC AND PIANIF.ANNO = LAVT.ANNO AND PIANIF.TIPNUM = LAVT.TIPNUM AND PIANIF.NUM = LAVT.NUM
		where u_dis_dd.dis_costo > 0 and u_dis_dd.dis_fasela <> ''
		) AS MAIN
	WHERE DIS_COSTO <> ROUND(COSTO_UNITARIO_PIANIFICAZ_FABRICA,6) AND COSTO_UNITARIO_PIANIFICAZ_FABRICA > 0
)

-- ESEGUIRE PRIMA UNA UPDATE E POI L'ALTRA IN MODO ALTERNATO (ASTERISCARE LA SECONDA UPDATE ED ESEGUIRE, SUCCESSIVAMENTE ASTERISCARE LA PRIMA UPDATE E POI ESEGUIRE)

-- 1° UPDATE: AGGIORNAMENTO COSTI FASI DI LAVORAZIONE INTERNE
UPDATE U_DIS_DD SET 
	DIS_COSTO = (SELECT COSTO_UNITARIO_PIANIFICAZ_FABRICA FROM CorrezioneDIBA WHERE DIS_GRUPPO+DIS_CODART = U_DIS_DD.DIS_GRUPPO+U_DIS_DD.DIS_CODART),
	DIS_COSLAI = (SELECT COSTO_UNITARIO_PIANIFICAZ_FABRICA FROM CorrezioneDIBA WHERE DIS_GRUPPO+DIS_CODART = U_DIS_DD.DIS_GRUPPO+U_DIS_DD.DIS_CODART)
WHERE DIS_TIPOPR = 'I' AND dis_fasela <> '' AND DIS_GRUPPO+DIS_CODART IN (SELECT DIS_GRUPPO+DIS_CODART FROM CorrezioneDIBA)

-- 2° UPDATE: AGGIORNAMENTO COSTI FASI DI LAVORAZIONE ESTERNE
UPDATE U_DIS_DD SET 
	DIS_COSTO = (SELECT COSTO_UNITARIO_PIANIFICAZ_FABRICA FROM CorrezioneDIBA WHERE DIS_GRUPPO+DIS_CODART = U_DIS_DD.DIS_GRUPPO+U_DIS_DD.DIS_CODART),
	DIS_COSLAE = (SELECT COSTO_UNITARIO_PIANIFICAZ_FABRICA FROM CorrezioneDIBA WHERE DIS_GRUPPO+DIS_CODART = U_DIS_DD.DIS_GRUPPO+U_DIS_DD.DIS_CODART)
WHERE DIS_TIPOPR = 'E' AND dis_fasela <> '' AND DIS_GRUPPO+DIS_CODART IN (SELECT DIS_GRUPPO+DIS_CODART FROM CorrezioneDIBA)