
-- POPOLAMENTO PARAMETRO PER REPORT ETICHETTE DA UTILIZZARE NEL CARICO DELLE MATERIE PRIME E SEMILAVORATI
-- ### ATTENZIONE !!! : IL SETTAGGIO DEI NOMI DEI REPORT E' POSIZIONALE; RISPETTARE CARATTERI E SPAZI

DELETE FROM PARA WHERE CODICE = 'EMP01'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('EMP01','ETICHETTE PER CARICO MATERIE PRIME','BFOPJETI_L3A.FRX   BFOPJETC_L3A.FRX    BFOPJETM_L3A.FRX')

DELETE FROM PARA WHERE CODICE = 'EXR01'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('EXR01','ETICHETTE PER CARICO SEMILAVORATI','BFOPJETI_L3A.FRX')


SELECT * FROM PARA WHERE CODICE = 'EMP01'
SELECT * FROM PARA WHERE CODICE = 'EXR01'