
--*** CREAZIONE ARTICOLI E PARAMETRI PER LA GESTIONE DEL POLIECO

DELETE FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO ASS'
DELETE FROM U_ART_AN WHERE ART_CODPRI = 'POLIECO ASS'
DELETE FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO MPP'
DELETE FROM U_ART_AN WHERE ART_CODPRI = 'POLIECO MPP'
DELETE FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO P'
DELETE FROM U_ART_AN WHERE ART_CODPRI = 'POLIECO P'

INSERT INTO U_ART_PR (ART_CODSOC,ART_TIPO,ART_LUNG,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZVEN,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_BARCOD,ART_GRUPRD) VALUES ('01','POLI','ECO','POLIECO ASS','RIVALSA CONTRIBUTO POLIECO ASS','KG','05',0.000000,0.015000,'22','SEDE','401007','001','A','S','S','KG','GENERICO',1,'O','POLIECO')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI) VALUES ('01','POLIECO ASS')

INSERT INTO U_ART_PR (ART_CODSOC,ART_TIPO,ART_LUNG,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZVEN,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_BARCOD,ART_GRUPRD) VALUES ('01','POLI','ECO','POLIECO MPP','CONTRIBUTO MPP POLIECO','KG','05',0.015000,0.000000,'22','SEDE','401007','001','A','S','S','KG','GENERICO',1,'O','POLIECO')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI) VALUES ('01','POLIECO MPP')

INSERT INTO U_ART_PR (ART_CODSOC,ART_TIPO,ART_LUNG,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZVEN,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_BARCOD,ART_GRUPRD) VALUES ('01','POLI','ECO','POLIECO P','CONTRIBUTO POLIECO PLASTICA','KG','05',0.015000,0.000000,'22','SEDE','401007','001','A','S','S','KG','GENERICO',1,'O','POLIECO')
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI) VALUES ('01','POLIECO P')


SELECT * FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO ASS'
SELECT * FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO MPP'
SELECT * FROM U_ART_PR WHERE ART_CODPRI = 'POLIECO P'


DELETE FROM PARA WHERE CODICE LIKE 'POL%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('POL01','CONTRIBUTO POLIECO P',  'POLIECO P        CONTRIBUTO POLIECO P                               ITA')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('POL02','CONTRIBUTO MPP POLIECO','POLIECO MPP      CONTRIBUTO MPP POLIECO                             EXP')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('POL03','RIVALSA CON. P  ASS',   'POLIECO ASS      RIVALSA CONTRIBUTO POLIECO ASS                     ITA')

SELECT * FROM PARA WHERE CODICE LIKE 'POL%'


