
DELETE FROM PARA WHERE CODICE LIKE 'PWD%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDALL','PASSWORD PER GESTIONE GENERICA','5667')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDBLO','PASSWORD PER BLOCCO FORNITURA IN ANAGRAFICA CLIENTI','STOP')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDCER','PASSWORD PER GESTIONE CERTIFICATI DI CONFORMITA','ALOAP')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDDTR','PASSWORD PER GESTIONE DATA DI REGISTRAZIONE SUI MOVIMENTI','9876')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDIVA','PASSWORD PER CAMBIO CODICI IVA','CAMBIOIVA')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDIVA','PASSWORD PER CAMBIO CODICI IVA','CAMBIOIVA')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDMAG','PASSWORD PER GESTIONE MAGAZZINO','7889')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDMOV','PASSWORD PER GESTIONE MOVIMENTI DI MAGAZZINO','1357')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPCK','PASSWORD PER CONFERMA SPEDIZIONE PACKING LIST DI PRODUZIONE','1234')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPCK','SOTTODIRETTORY PER INVIO REPORT DI CHECK-UP AZIENDALI','CHECK-UP')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPKA','PASSWORD PER AUTORIZZAZIONE CLIENTI A RISCHIO IN PACKING LIST DI PRODUZIONE','4321')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPRC','PASSWORD PER CHIUSURA PROGRAMMA DI PRODUZIONE STANDARD','5678')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPRD','PASSWORD PER PROGRAMMAZIONE DELLA PRODUZIONE','1234')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDPWD','PASSWORD PER ENTRARE NELLA GESTIONE CAMBIO PASSWORD','PJ')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDUTY','PASSWORD PER FUNZIONI UTILITY GENERALI','UTY')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('PWDUTY','PASSWORD PER FUNZIONI UTILITY GENERALI','UTY')

SELECT * FROM PARA WHERE CODICE LIKE 'PWD%' ORDER BY CODICE