/*******************************************************************************
 INSERIMENTO CAUSALI PER PRODUZIONE FILM CON PIANIFICAZIONE
*******************************************************************************/

DELETE FROM PARA WHERE CODICE IN ('TOPCPS','TOPSPS','TOPCVS','TOPSVS')
DELETE FROM PARA WHERE CODICE IN ('TOPCPR','TOPSPR','TOPCVR','TOPSVR')
DELETE FROM PARA WHERE CODICE IN ('TOPCPT','TOPSPT','TOPCVT','TOPSVT')
DELETE FROM PARA WHERE CODICE IN ('TOPCSP','TOPSSP')

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCPS','CARICO PRELIEVO SPALMATURA',		'CN      NNNN                      SPS    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSPS','SCARICO PRELIEVO SPALMATURA',		'SN      NNNN                      CPS    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCVS','CARICO VERSAMENTO SPALMATURA',	'CN      NNNN                      SVS    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSVS','SCARICO VERSAMENTO SPALMATURA',	'SN      NNNN                      CVS    M')

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCPR','CARICO PRELIEVO RIBOBINATURA',	'CN      NNNN                      SPR    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSPR','SCARICO PRELIEVO RIBOBINATURA',	'SN      NNNN                      CPR    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCVR','CARICO VERSAMENTO RIBOBINATURA',	'CN      NNNN                      SVR    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSVR','SCARICO VERSAMENTO RIBOBINATURA',	'SN      NNNN                      CVR    M')

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCPT','CARICO PRELIEVO TAGLIO',			'CN      NNNN                      SPT    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSPT','SCARICO PRELIEVO TAGLIO',			'SN      NNNN                      CPT    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCVT','CARICO VERSAMENTO TAGLIO',		'CN      NNNN                      SVT    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSVT','SCARICO VERSAMENTO TAGLIO',		'SN      NNNN                      CVT    M')

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCSP','CARICO PER SPOSTAMENTO',			'CN      NNNN                      SSP    M')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPSSP','SCARICO PER SPOSTAMENTO',			'SN      NNNN                      CSP    M')

SELECT *  FROM PARA WHERE CODICE IN ('TOPCPS','TOPSPS','TOPCVS','TOPSVS') ORDER BY CODICE
SELECT * FROM PARA WHERE CODICE IN ('TOPCPR','TOPSPR','TOPCVR','TOPSVR') ORDER BY CODICE
SELECT * FROM PARA WHERE CODICE IN ('TOPCPT','TOPSPT','TOPCVT','TOPSVT') ORDER BY CODICE
SELECT * FROM PARA WHERE CODICE IN ('TOPCSP','TOPSSP') ORDER BY CODICE
