

/*******************************************************************************
 INSERIMENTO TIPI IMBALLI PER PRODUZIONE FILM PROTETTIVI CON PIANIFICAZIONE
*******************************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'IMB%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB000','BANCALI DIVISI PER H.','PFP','V','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB001','CUBO','PFP','V','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB003','PIRAMIDE','PFP','H','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB004','VERTICALE','PFP','V','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB005','ORIZZONTALE','PFP','H','01')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB006','LATTA','','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB007','FUSTO','','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB008','CISTERNA','','','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB009','SCATOLE SINGOLE','PFP','V','03')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,CODPGO) VALUES ('IMB010','SCATOLE SU BANCALE','PFP','H','06')

SELECT * FROM PARA WHERE CODICE LIKE 'IMB%' ORDER BY LIBERA,CODICE
