/*******************************************************************************
 INSERIMENTO FASI DI LAVORAZIONE PER PRODUZ. FILM PROTETTIVI CON PIANIFICAZIONE
*******************************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'FAL%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,ITALIANO) VALUES ('FALSPA','SPALMATURA','1','PFP','VARIAZIONE_DIMENSIONE:L;SCARICO_DIBA:SI;PRENOTA_GIACENZE_VERSATE:NO;REPORT_STAMPA_ETICHETTE:AVANZA_PFP.FRX;MAG_DESTINAZIONE_PRELIEVO:006;MAG_DESTINAZIONE_VERSAMENTO:006;FORMATO_DIMENSIONE_STD:500;TOP_CARICO_PREL:CPS;TOP_SCARICO_PREL:SPS;TOP_CARICO_VERS:CVS;TOP_SCARICO_VERS:SVS;H_SFRIDO_CIMOSA:70;ACCETTA_PRELIEVO_LUNGHEZZA_MAGGIORE:SI;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,ITALIANO) VALUES ('FALRIB','RIBOBINATURA','2','PFP','VARIAZIONE_DIMENSIONE:L;SCARICO_DIBA:NO;PRENOTA_GIACENZE_VERSATE:NO;REPORT_STAMPA_ETICHETTE:AVANZA_PFP.FRX;MAG_DESTINAZIONE_PRELIEVO:006;MAG_DESTINAZIONE_VERSAMENTO:006;TOP_CARICO_PREL:CPR;TOP_SCARICO_PREL:SPR;TOP_CARICO_VERS:CVR;TOP_SCARICO_VERS:SVR;')
--INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,ITALIANO) VALUES ('FALTAG','TAGLIO','3','PFP','VARIAZIONE_DIMENSIONE:H;SCARICO_DIBA:NO;MAG_DESTINAZIONE_PRELIEVO:006;TOP_CARICO_PREL:CPT;TOP_SCARICO_PREL:SPT;TOP_CARICO_VERS:CVT;TOP_SCARICO_VERS:SVT;H_SFRIDO_CIMOSA:70;H_SFRIDO_SINGOLO_TAGLIO:5;H_TOLLERANZA_MAX:200;H_NR_TAGLI_SFRIDO_FORFAIT:4;H_SFRIDO_FORFAIT:20;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,ITALIANO) VALUES ('FALTAG','TAGLIO','3','PFP','VARIAZIONE_DIMENSIONE:H;SCARICO_DIBA:NO;PRENOTA_GIACENZE_VERSATE:SI;REPORT_STAMPA_ETICHETTE:AVANZA_TAGLIO_PFP.LBX;REPORT_STAMPA_ETICHETTE_SECONDARIO:AVANZA_TAGLIO_PFP_2.LBX;REPORT_STAMPA_ETICHETTE_STOCK:AVANZA_PFP.FRX;MAG_DESTINAZIONE_PRELIEVO:006;MAG_DESTINAZIONE_VERSAMENTO:010;MAG_DESTINAZIONE_VERSAMENTO_STOCK:006;TOP_CARICO_PREL:CPT;TOP_SCARICO_PREL:SPT;TOP_CARICO_VERS:CVT;TOP_SCARICO_VERS:SVT;H_SFRIDO_SINGOLO_TAGLIO:5;H_TOLLERANZA_MAX:200;')
--INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA,ITALIANO) VALUES ('FALRIT','RIBOBINATURA CON TAGLIO SIMULTANEO','4','PFP','VARIAZIONE_DIMENSIONE:L;VARIAZIONE_DIMENSIONE:H;SCARICO_DIBA:NO;MAG_DESTINAZIONE_PRELIEVO:006;')

SELECT * FROM PARA WHERE CODICE LIKE 'FAL%' ORDER BY LIBERA
