
--/********************************************************
-- AGGIORNAMENTO PARAMETRI AZIENDALI 
-- ********************************************************/

UPDATE U_AZI_AN SET 
AZI_CAUSSP = 'SSP',
AZI_CAUCSP = 'CSP'
SELECT * FROM U_AZI_AN

UPDATE U_AZI_PA SET 
AZI_GGCONS = 7
SELECT * FROM U_AZI_PA

UPDATE U_AZI_PB SET 
AZI_PFPLINPV = '05',
AZI_NOSKPROD = 0,
AZI_NOSTPCOMPESORD = 0,
AZI_NOSTPCOMPESBOL = 0,
AZI_NOSTPCOMPESFAT = 0,
AZI_NOSTPCOMPESFAP = 0
SELECT * FROM U_AZI_PB


--/********************************************************
-- AGGIORNAMENTO PARAMETRI PER RICHIAMO REPORT PERSONALIZZAZI
-- ********************************************************/
--DELETE FROM PJTIPREP WHERE NOMEPROC = 'ORDPJEUR'
--INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('ORDPJEUR','REPORT PERSONALIZZATO ORDINI CLIENTI STANDARD PRISMA','ORDPJPRISMA.FRX')
--SELECT * FROM PJTIPREP WHERE NOMEPROC = 'ORDPJEUR'

--DELETE FROM PJTIPREP WHERE NOMEPROC = 'FAPPJEUR'
--INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('FAPPJEUR','REPORT PERSONALIZZATO FATTURE PROFORMA STANDARD PRISMA','FAPPJPRISMA.FRX')
--SELECT * FROM PJTIPREP WHERE NOMEPROC = 'FAPPJEUR'

--DELETE FROM PJTIPREP WHERE NOMEPROC = 'FATPJEUR'
--INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('FATPJEUR','REPORT PERSONALIZZATO FATTURE CLIENTI STANDARD PRISMA','FATPJPRISMA.FRX')
--SELECT * FROM PJTIPREP WHERE NOMEPROC = 'FATPJEUR'

--DELETE FROM PJTIPREP WHERE NOMEPROC = 'BOLPJITA'
--INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('BOLPJITA','REPORT PERSONALIZZATO DDT STANDARD PRISMA','BOLPJPRISMA.FRX')
--SELECT * FROM PJTIPREP WHERE NOMEPROC = 'BOLPJITA'

--DELETE FROM PJTIPREP WHERE NOMEPROC = 'BCLPJITA'
--INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP) VALUES ('BCLPJITA','REPORT PERSONALIZZATO DDT CONTO LAVORO STANDARD PRISMA','BCLPJPRISMA.FRX')
--SELECT * FROM PJTIPREP WHERE NOMEPROC = 'BCLPJITA'


--/********************************************************
-- AGGIORNAMENTO PARAMETRI AZIENDALI 
-- ********************************************************/
--DECLARE @_INTESTAZIONE AS VARCHAR(8000), @_PIE_DI_PAGINA AS VARCHAR(8000)
--SET @_INTESTAZIONE = 'PRISMA S.P.A.
--Sede legale: VIA MARZIALE 13 - 04023 FORMIA (LT)
--Uffici comm. e sede operativa: VIA PIETRA ERTA snc
--Tel. 0771.723028 - Fax. 0771.725049
--Cod. Fisc. e P.IVA 02058310596
--prismaspa@prismaspa.com - www.prismaspa.com
--Capitale sociale € 291.400,00 i.v.  -  R.E.A. Latina nr.142302'
--SET @_PIE_DI_PAGINA = ''

--/********************************************************
-- AGGIORNAMENTO ANAGRAFICA CLIENTI
-- ********************************************************/
--UPDATE U_CLI_AN SET CLI_RAGSOC = 'PRISMA SPA', CLI_INDIR = 'VIA PIETRA ERTA SNC', CLI_LOCALI = 'FORMIA', CLI_CAP = '04023', CLI_PARIVA = '02058310596',
--	CLI_TELEFO = '0771/723028', CLI_FAX = '0771/725049' WHERE CLI_CODCLI = '00000100'
--SELECT * FROM U_CLI_AN WHERE CLI_CODCLI = '00000100'

--/********************************************************
-- AGGIORNAMENTO PARAMETRO IMPORTO MAX EURO GESTIBILE
-- ********************************************************/
--UPDATE PARA SET LIBERA = '1000000000,00' WHERE CODICE = 'TEUEUR'
--SELECT * FROM PARA WHERE CODICE = 'TEUEUR'
