/*****************************************************************************************
 PARAMETRO CODICE MATERIALE PER IDENTIFACAZIONE ARTICOLI DI TIPO CARTA GREZZA E IMPREGNATA
*****************************************************************************************/

DELETE FROM PARA WHERE CODICE = 'MAT010'
DELETE FROM PARA WHERE CODICE = 'MAT011'


INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MAT010','CARTA GREZZA','7 UM_ACQUISTO:KG;UM_MAGAZZINO:KG;TIPO_ARTICOLO:A;')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MAT011','CARTA IMPREGNATA','8 UM_ACQUISTO:MQ;UM_MAGAZZINO:NR;TIPO_ARTICOLO:A;')

SELECT * FROM PARA WHERE CODICE LIKE 'MAT%' ORDER BY CODICE

