SELECT * FROM INDICE WHERE MOV_DTREG = '    /  /  ' AND MOV_TOP = 'VEN'
SELECT * FROM MOV_CONT WHERE MOV_DTREG = '    /  /  ' AND MOV_TOP = 'VEN'

UPDATE INDICE SET MOV_DTREG  = '2012/01/31' WHERE MOV_DTREG = '    /  /  ' AND MOV_TOP = 'VEN'
UPDATE MOV_CONT SET MOV_DTREG  = '2012/01/31' WHERE MOV_DTREG = '    /  /  ' AND MOV_TOP = 'VEN'

SELECT * FROM INDICE WHERE MOV_TOP = 'VEN'
SELECT * FROM MOV_CONT WHERE MOV_TOP = 'VEN'