
DELETE FROM PARA WHERE CODICE = 'TOPCC+'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCC+','CARICO MAGAZZINO PER CAMBIO CODICE' ,'CN      NNNN                    MOCC-   NM')

DELETE FROM PARA WHERE CODICE = 'TOPCC-'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPCC-','SCARICO MAGAZZINO PER CAMBIO CODICE','SN      NNNN                    MOCC+   NM')

SELECT * FROM PARA WHERE CODICE = 'TOPCC+'
SELECT * FROM PARA WHERE CODICE = 'TOPCC-'
