
UPDATE U_ORD_DD SET ORD_CDAPRD = ORD_CODART
UPDATE U_ORD_DD SET ORD_DSAPRD = ORD_DESART

UPDATE U_BOL_DD SET ORD_CDAPRD = ORD_CODART
UPDATE U_BOL_DD SET ORD_DSAPRD = ORD_DESART

UPDATE U_FAP_DD SET ORD_CDAPRD = ORD_CODART
UPDATE U_FAP_DD SET ORD_DSAPRD = ORD_DESART

UPDATE U_FAT_DD SET ORD_CDAPRD = ORD_CODART
UPDATE U_FAT_DD SET ORD_DSAPRD = ORD_DESART
