/**********************************************************
 INSERIMENTO FASI DI LAVORAZIONE PER PANNELLI TRUCIOLARI
**********************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'FAL%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FALPRESSA','PRESSATURA','1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FALLEVIGA','LEVIGATURA','2')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FALNOBILI','NOBILITA','3')

SELECT * FROM PARA WHERE CODICE LIKE 'FAL%' ORDER BY LIBERA
