/********************************************************************
 PARAMETRO STATO SOTTOCATEGORIA
********************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'CAT%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CAT01','CARTIERA / SFOGLIATO','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CAT02','CIMALI / CEPPE / CIPPATO / MISTO','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CAT03','RICICLATO','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CAT04','REFILI','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CAT05','COLLA','')

UPDATE U_ART_PR SET ART_CSTCAT = '', ART_DSTCAT = '', ART_CODCAT = '', ART_DESCAT = ''

UPDATE U_ART_PR SET ART_CSTCAT = '01', ART_DSTCAT = 'CARTIERA / SFOGLIATO' WHERE ART_CODPRI = '01.001.0001'
UPDATE U_ART_PR SET ART_CSTCAT = '01', ART_DSTCAT = 'CARTIERA / SFOGLIATO' WHERE ART_CODPRI = '01.001.0002'
UPDATE U_ART_PR SET ART_CSTCAT = '01', ART_DSTCAT = 'CARTIERA / SFOGLIATO' WHERE ART_CODPRI = '01.001.0017'

UPDATE U_ART_PR SET ART_CSTCAT = '02', ART_DSTCAT = 'CIMALI / CEPPE / CIPPATO / MISTO' WHERE ART_CODPRI = '01.001.0005'
UPDATE U_ART_PR SET ART_CSTCAT = '02', ART_DSTCAT = 'CIMALI / CEPPE / CIPPATO / MISTO' WHERE ART_CODPRI = '01.001.0006'
UPDATE U_ART_PR SET ART_CSTCAT = '02', ART_DSTCAT = 'CIMALI / CEPPE / CIPPATO / MISTO' WHERE ART_CODPRI = '01.001.0003'
UPDATE U_ART_PR SET ART_CSTCAT = '02', ART_DSTCAT = 'CIMALI / CEPPE / CIPPATO / MISTO' WHERE ART_CODPRI = '01.001.0012'

UPDATE U_ART_PR SET ART_CSTCAT = '03', ART_DSTCAT = 'RICICLATO' WHERE ART_CODPRI = '01.001.0021'

UPDATE U_ART_PR SET ART_CSTCAT = '04', ART_DSTCAT = 'REFILI' WHERE ART_CODPRI = '01.001.0008'

UPDATE U_ART_PR SET ART_CSTCAT = '05', ART_DSTCAT = 'COLLA' WHERE ART_CODPRI = '01.001.0029'
UPDATE U_ART_PR SET ART_CSTCAT = '05', ART_DSTCAT = 'COLLA' WHERE ART_CODPRI = 'E 286'
UPDATE U_ART_PR SET ART_CSTCAT = '05', ART_DSTCAT = 'COLLA' WHERE ART_CODPRI = 'L 1612'


SELECT * FROM PARA WHERE CODICE LIKE 'CAT%' ORDER BY CODICE
SELECT ART_CODPRI,ART_DESCR,ART_CSTCAT,ART_DSTCAT FROM U_ART_PR WHERE ART_CSTCAT <> '' ORDER BY ART_CODPRI

