/*******************************************************************
 INSERIMENTO MAGAZZINI DI DEFAULT PER PRODUZIONE PANNELLI TRUCIOLARI
********************************************************************/

DELETE FROM PARA WHERE CODICE = 'MAG1'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG1','MATERIALE DA LEVIGARE','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG2'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG2','MATERIALE NOBILITATO','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG3'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG3','MAGAZZINO CARTE','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG5'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG5','PRODOTTO FINITO (SPESSORI DA 8 A 19 mm)','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG4'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG4','PRODOTTO FINITO (SPESSORI DA 20 A 40 mm)','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG6'
--INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG6','PRODOTTO FINITO (SPESSORI DA 41 A 60 mm)','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG6','PRODOTTO FINITO (SPESSORI DA 8 A 19 mm)','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

DELETE FROM PARA WHERE CODICE = 'MAG10'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,PAR_DATINS) VALUES ('MAG10','PRODOTTO FINITO (SPESSORI DA 41 A 60 mm)','',REPLACE(CONVERT(VARCHAR,getdate(),23),'-','/'))

UPDATE u_azi_pa SET AZI_PRESSA = '1'
UPDATE u_azi_pa SET AZI_LEVIGA1 = '5'
UPDATE u_azi_pa SET AZI_LEVIGA2 = '4'
UPDATE u_azi_pa SET AZI_LEVIGA3 = '10'
UPDATE u_azi_pa SET AZI_NOBILI = '2'
UPDATE u_azi_pa SET AZI_CAIPPT = '3'
UPDATE u_azi_pa SET AZI_SCAPPT = 'SCA'

SELECT * FROM PARA 
WHERE CODICE = 'MAG1'
  or  CODICE = 'MAG2'
  or  CODICE = 'MAG3'
  or  CODICE = 'MAG4'
  or  CODICE = 'MAG5'
  or  CODICE = 'MAG6'
  or  CODICE = 'MAG10'
order by codice

SELECT AZI_PRESSA, AZI_LEVIGA1, AZI_LEVIGA2, AZI_LEVIGA3, AZI_NOBILI, AZI_CAIPPT, AZI_SCAPPT FROM u_azi_pa