/**********************************************************
 INSERIMENTO FASI DI LAVORAZIONE PER PANNELLI TRUCIOLARI
**********************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'SPE%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE8','SPESSORE 8 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE9','SPESSORE 9 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE10','SPESSORE 10 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE11','SPESSORE 11 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE12','SPESSORE 12 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE13','SPESSORE 13 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE14','SPESSORE 14 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE15','SPESSORE 15 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE16','SPESSORE 16 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE17','SPESSORE 17 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE18','SPESSORE 18 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE19','SPESSORE 19 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE20','SPESSORE 20 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE21','SPESSORE 21 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE22','SPESSORE 22 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE23','SPESSORE 23 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE24','SPESSORE 24 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE25','SPESSORE 25 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE26','SPESSORE 26 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE27','SPESSORE 27 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE28','SPESSORE 28 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE29','SPESSORE 29 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE30','SPESSORE 30 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE32','SPESSORE 32 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE33','SPESSORE 33 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE35','SPESSORE 35 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE36','SPESSORE 36 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE37','SPESSORE 37 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE38','SPESSORE 38 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE39','SPESSORE 39 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE40','SPESSORE 40 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE42','SPESSORE 42 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE43','SPESSORE 43 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE44','SPESSORE 44 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE45','SPESSORE 45 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE47','SPESSORE 47 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE48','SPESSORE 48 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE50','SPESSORE 50 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE53','SPESSORE 53 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE54','SPESSORE 54 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE56','SPESSORE 56 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE58','SPESSORE 58 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE59','SPESSORE 59 mm','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('SPE60','SPESSORE 60 mm','')







SELECT * FROM PARA WHERE CODICE LIKE 'SPE%' ORDER BY CODICE
