/**********************************************************
 INSERIMENTO MAGAZZINI ESTERNI FORNITORE PER CONTO LAVORO
**********************************************************/

DELETE FROM PARA WHERE CODICE = 'MAG001373'
DELETE FROM PARA WHERE CODICE = 'MAG000053'
DELETE FROM PARA WHERE CODICE = 'MAG000061'

INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MAG001373','SCHATTDECOR SRL (MAGAZZINO ESTERNO)','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MAG000053','CARTIERA GIACOSA S.P.A. (MAGAZZINO ESTERNO)','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('MAG000061','CONFALONIERI S.P.A. (MAGAZZINO ESTERNO)','')

SELECT * FROM PARA WHERE CODICE = 'MAG001373' OR CODICE = 'MAG000053' OR CODICE = 'MAG000061' ORDER BY CODICE
