
DELETE FROM PARA WHERE CODICE = 'COTMERCE'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('COTMERCE','FORNITORE DI MERCE','')

UPDATE U_FOR_AN SET FOR_COSATRATTA = 'MERCE' WHERE FOR_CODCLI IN (SELECT ORD_CODCLI FROM U_BFO_TT)

SELECT * FROM PARA WHERE CODICE LIKE 'COT%'
SELECT FOR_COSATRATTA, * FROM U_FOR_AN WHERE FOR_CODCLI IN (SELECT ORD_CODCLI FROM U_BFO_TT)

