/********************************************************************
 PARAMETRO GRUPPO LISTINI
********************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'GLI%'

INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI01','1ø LISTINO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI02','TRUCIOLARE GREZZO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI03','TRUCIOLARE NOBILITATO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI04','MDF/MULTISTRATI/LISTELLARE GREZZO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLIP4','TRUC. IDRO P4 GREZZO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLIP5','TRUC. IDRO P5 GREZZO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI4N','TRUC. IDRO P4 NOB.')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI5N','TRUC. IDRO P5 NOB.')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI46','LISTELLARE NOBILITATO')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI48','MULTISTRATO NOBILITATO')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI50','IGNIFUGO')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI51','TRUC.IGNIFUGO NOB.')  
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI52','MDF NOBILITATO')
INSERT INTO PARA (CODICE,DESCRI) VALUES ('GLI99','BORDI')

/* VISUALIZZO I RECORD INSERITI */
SELECT * FROM PARA WHERE CODICE LIKE 'GLI%'

/* ABBINAMENTO CON I TIPI PRODOTTO GREZZO 'TIG' E NOBILITATO 'TNO' */
SELECT	SUBSTRING(P1.CODICE,4,1) AS TIPO_PRODOTTO,
		P1.DESCRI AS DES_TIPO_PRODOTTO,
		CASE WHEN SUBSTRING(P1.CODICE,1,3)='TIG' THEN 'GREZZO' ELSE 'NOBILITATO' END AS G_N ,
		SUBSTRING(P2.CODICE,4,2) AS GRUPPO_LISTINO,
		P2.DESCRI AS DES_GRUPPO_LISTINO 
FROM PARA AS P1 
LEFT OUTER JOIN PARA AS P2
ON 'GLI'+P1.LIBERA = P2.CODICE
WHERE (P1.CODICE LIKE 'TIG%' OR P1.CODICE LIKE 'TNO%') AND P2.CODICE LIKE 'GLI%' 
ORDER BY P1.CODICE


