/********************************************************************
 PARAMETRO SOTTODIRECTORY PER TIPI DOCUMENTO IN RISTAMPA DOCUMENTI
********************************************************************/

DELETE FROM PARA WHERE CODICE = 'FSDORF'
DELETE FROM PARA WHERE CODICE = 'FSDBFO'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDORF','SOTTODIRECTORY PER CREAZIONE ORDINI A FORNITORE DA RISTAMPA DOCUMENTI','DOC-FORNITORI')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDBFO','SOTTODIRECTORY PER CREAZIONE DOCUMENTI DA FORNITORE DA RISTAMPA DOCUMENTI','DOC-FORNITORI')
SELECT * FROM PARA WHERE CODICE = 'FSDORF' OR CODICE = 'FSDBFO' ORDER BY CODICE

DELETE FROM PARA WHERE CODICE = 'FSDOFF'
DELETE FROM PARA WHERE CODICE = 'FSDORD'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDOFF','SOTTODIRECTORY PER CREAZIONE OFFERTE CLIENTI DA RISTAMPA DOCUMENTI','OFFERTE-ORDINI')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDORD','SOTTODIRECTORY PER CREAZIONE ORDINI CLIENTI DA RISTAMPA DOCUMENTI','OFFERTE-ORDINI')
SELECT * FROM PARA WHERE CODICE = 'FSDOFF' OR CODICE = 'FSDORD' ORDER BY CODICE

DELETE FROM PARA WHERE CODICE = 'FSDBOL'
DELETE FROM PARA WHERE CODICE = 'FSDFAP'
DELETE FROM PARA WHERE CODICE = 'FSDFAT'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDBOL','SOTTODIRECTORY PER CREAZIONE BOLLE CLIENTI DA RISTAMPA DOCUMENTI','BOLLE-FATTURE')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDFAP','SOTTODIRECTORY PER CREAZIONE FATTURE PROFORMA CLIENTI DA RISTAMPA DOCUMENTI','BOLLE-FATTURE')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('FSDFAT','SOTTODIRECTORY PER CREAZIONE FATTURE CLIENTI DA RISTAMPA DOCUMENTI','BOLLE-FATTURE')
SELECT * FROM PARA WHERE CODICE = 'FSDBOL' OR CODICE = 'FSDFAP' OR CODICE = 'FSDFAT' ORDER BY CODICE
