
-- ############################################################################################################
-- ###### RIPOPOLAMENTO CAMPO 'DESIVA' IN PARAMETRI TIPO GREZZO / NOBILITATO PER PRODUZIONE PANNELLI TRUCIOLARI
-- ############################################################################################################

UPDATE PARA SET DESIVA = 'BEST'				WHERE CODICE = 'TIG1' OR CODICE = 'TNO1'
UPDATE PARA SET DESIVA = 'LIGHT'			WHERE CODICE = 'TIG2' OR CODICE = 'TNO2'
UPDATE PARA SET DESIVA = 'V100_P5'			WHERE CODICE = 'TIG3' OR CODICE = 'TNO3'
UPDATE PARA SET DESIVA = 'IDRO_P4'			WHERE CODICE = 'TIG4' OR CODICE = 'TNO4'
UPDATE PARA SET DESIVA = 'IGNIFUGO'			WHERE CODICE = 'TIG5' OR CODICE = 'TNO5'
UPDATE PARA SET DESIVA = 'LIGHT_FSC'		WHERE CODICE = 'TIG6' OR CODICE = 'TNO6'
UPDATE PARA SET DESIVA = 'BEST_FSC'			WHERE CODICE = 'TIG8' OR CODICE = 'TNO8'
UPDATE PARA SET DESIVA = 'CLEAF'			WHERE CODICE = 'TIGA' OR CODICE = 'TNOA'
UPDATE PARA SET DESIVA = 'LIGHT_EPFS'		WHERE CODICE = 'TIGB' OR CODICE = 'TNOB'
UPDATE PARA SET DESIVA = 'V100_P5_EPFS'		WHERE CODICE = 'TIGC' OR CODICE = 'TNOC'
UPDATE PARA SET DESIVA = 'IDRO_P4_EPFS'		WHERE CODICE = 'TIGD' OR CODICE = 'TNOD'
UPDATE PARA SET DESIVA = 'IGNIFUGO_EPFS'	WHERE CODICE = 'TIGE' OR CODICE = 'TNOE'
UPDATE PARA SET DESIVA = 'XIL400'			WHERE CODICE = 'TIGI' OR CODICE = 'TNOI'
UPDATE PARA SET DESIVA = 'XIL400_I'			WHERE CODICE = 'TIGU' OR CODICE = 'TNOU'


