

DELETE FROM AQ_ROLMEK.DBO.PARA WHERE CODICE LIKE 'TPO%'

INSERT INTO AQ_ROLMEK.DBO.PARA (CODICE,DESCRI)
	SELECT 'TPO'+SUBSTRING(CodiceCauTrasp,1,3) AS CODICE,DESCRIZIONE AS DESCRI FROM AS_ROLMEK.DBO.CAUSALI_TRASPORTO


SELECT * FROM AQ_ROLMEK.DBO.PARA WHERE CODICE LIKE 'TPO%' ORDER BY CODICE


