
UPDATE U_FAT_TT SET ORD_IDSDI = (SELECT CLI_IDSDI FROM U_ANA_CL WHERE CLI_CODCLI = U_FAT_TT.ORD_CODCLI)
UPDATE U_FAT_TT SET ORD_EPEC = (SELECT CLI_EPEC FROM U_ANA_CL WHERE CLI_CODCLI = U_FAT_TT.ORD_CODCLI)
UPDATE U_FAT_TT SET ORD_BOVIRT = ORD_SPBOLL