
UPDATE PARA SET DESCRI = REPLACE(DESCRI,'MM',' MM') WHERE CODICE LIKE 'PRD%' AND DESCRI NOT LIKE '% MM%'

UPDATE U_ART_PR SET ART_DESCR = (SELECT COALESCE(DESCRI,'') FROM PARA WHERE CODICE = 'PRD'+U_ART_PR.ART_CODPRI) WHERE ART_CODPRI = ART_GRUPRD

SELECT * FROM PARA WHERE CODICE LIKE 'PRD%' ORDER BY CODICE
SELECT ART_CODPRI,ART_DESCR FROM U_ART_PR WHERE ART_CODPRI = ART_GRUPRD ORDER BY ART_CODPRI
