
-- AGGIORNAMENTO CAMPO U_ART_PR.ART_GRUPRD PER GLI ARTICOLI GRUPPI PRODUTTIVI

UPDATE U_ART_PR SET ART_GRUPRD = ART_CODPRI WHERE ART_CODPRI IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRD%')
