
-- CORREZIONE DISTINTE CARB: 01.002.0007 (COLLA CON MELAMINA AL 3% ) AL POSTO DI 01.002.0001 (COLLA UREICA)
UPDATE U_DIS_DD SET 
	DIS_CODART = '01.002.0007',
	DIS_DESCRI = (SELECT ART_DESCR FROM U_ART_PR WHERE ART_CODPRI = '01.002.0007')
WHERE DIS_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_%' AND DESCRI LIKE '%CARB%') AND DIS_CODART = '01.002.0001'


-- CORREZIONE DISTINTE CARB: INSERIMENTO COMPONENTI 01.002.0002 (UREA 40%) E 01.004.0009 (UREA MICRO PRILL) OVE MANCANTI
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		4.1 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-2 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_%' AND DESCRI LIKE '%CARB%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.002.0002')) AS DIT
	WHERE ART_CODPRI = '01.002.0002' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		5.7 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-1 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_%' AND DESCRI LIKE '%CARB%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.004.0009')) AS DIT
	WHERE ART_CODPRI = '01.004.0009' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO


--DELETE FROM U_DIS_DD WHERE DIS_GRUPPO IS NULL
--DELETE FROM U_DIS_DD WHERE DIS_CODART IN ('01.002.0002','01.004.0009') AND DIS_GRUPPO LIKE 'P_ARI_CARB_E1-%'