
-- INSERIMENTO DI.BA. GREZZO DA LEVIGARE PER TUTTI GLI SPESSORI DEL GRUPPO PRODUTTIVO, PARTENDO DA UNA DI.BA. SORGENTE INSERITA MANUALMENTE

--INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_MAT_EPFSFSC%' AND CODICE NOT IN (SELECT 'PRD'+DIT_GRUPPO FROM U_DIS_TT) ORDER BY DESIVA

--INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST 
FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_MAT_EPFSFSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_MAT_EPFSFSC-%'  AND CODICE NOT IN (SELECT 'PRD'+DIS_GRUPPO FROM U_DIS_DD GROUP BY DIS_GRUPPO) ORDER BY PARA.DESIVA


SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_MAT_EPFSFSC%' ORDER BY DIT_GRUPPO
SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_MAT_EPFSFSC%' ORDER BY DIS_GRUPPO,DIS_SEQUEN