
--* INSERIMENTO TIPO GREZZO
DELETE FROM PARA WHERE CODICE = 'TIGFJ'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TIGFJ','FUOCO - XILOPAN IGNIFUGO - E1E05','P_F_E1E05','44101190',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TIGFK'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TIGFK','FUOCO - XILOPAN IGNIFUGO - E1E05 FSC MIX 100%','P_F_E1E05_FSC','44101190',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TIGIJ'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TIGIJ','ARIA - XIL400 E1E05','P_A_E1E05','44101110',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TIGIK'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TIGIK','ARIA - XIL400 E1E05 FSC 100%','P_A_E1E05_FSC','44101110',CONVERT(VARCHAR, GETDATE(), 111))
--SELECT * FROM PARA WHERE CODICE IN ('TIGFJ','TIGFK','TIGIJ','TIGIK')

--* INSERIMENTO TIPO NOBILITATO
DELETE FROM PARA WHERE CODICE = 'TNOFJ'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TNOFJ','FUOCO - XILOPAN IGNIFUGO - E1E05','P_F_E1E05','44101130',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TNOFK'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TNOFK','FUOCO - XILOPAN IGNIFUGO - E1E05 FSC MIX 100%','P_F_E1E05_FSC','44101130',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TNOIJ'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TNOIJ','ARIA - XIL400 E1E05','P_A_E1E05','44101130',CONVERT(VARCHAR, GETDATE(), 111))
DELETE FROM PARA WHERE CODICE = 'TNOIK'
INSERT INTO PARA (CODICE,DESCRI,DESIVA,CODPGO,REG_DATREG) VALUES ('TNOIK','ARIA - XIL400 E1E05 FSC 100%','P_A_E1E05_FSC','44101130',CONVERT(VARCHAR, GETDATE(), 111))
--SELECT * FROM PARA WHERE CODICE IN ('TNOFJ','TNOFK','TNOIJ','TNOIK')




-- NUOVI GRUPPI PRODUTTIVI

DECLARE @_PREF_CODICE AS VARCHAR(100)
DECLARE @_PREF_DESCRI AS VARCHAR(100)
DECLARE @_LIBERA AS VARCHAR(2)

SET @_PREF_CODICE = 'P_F_E1E05-'
SET @_PREF_DESCRI = 'FUOCO - XILOPAN IGNIFUGO - E1E05 '
SET @_LIBERA = 'FJ'
DELETE FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
	SELECT
		'PRD'+@_PREF_CODICE+DESIVA AS CODICE,
		@_PREF_DESCRI + DESIVA + ' MM DA LEVIGARE' AS DESCRI,
		@_LIBERA AS LIBERA,
		DESIVA AS DESIVA
	FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA

--SELECT CODICE,DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'


SET @_PREF_CODICE = 'P_F_E1E05_FSC-'
SET @_PREF_DESCRI = 'FUOCO - XILOPAN IGNIFUGO - E1E05 FSC MIX 100% '
SET @_LIBERA = 'FK'
DELETE FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
	SELECT
		'PRD'+@_PREF_CODICE+DESIVA AS CODICE,
		@_PREF_DESCRI + DESIVA + ' MM DA LEVIGARE' AS DESCRI,
		@_LIBERA AS LIBERA,
		DESIVA AS DESIVA
	FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA

--SELECT CODICE,DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'


SET @_PREF_CODICE = 'P_A_E1E05-'
SET @_PREF_DESCRI = 'ARIA - XIL400 E1E05 '
SET @_LIBERA = 'IJ'
DELETE FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
	SELECT
		'PRD'+@_PREF_CODICE+DESIVA AS CODICE,
		@_PREF_DESCRI + DESIVA + ' MM DA LEVIGARE' AS DESCRI,
		@_LIBERA AS LIBERA,
		DESIVA AS DESIVA
	FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA

--SELECT CODICE,DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'


SET @_PREF_CODICE = 'P_A_E1E05_FSC-'
SET @_PREF_DESCRI = 'ARIA - XIL400 E1E05 FSC 100% '
SET @_LIBERA = 'IK'
DELETE FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
	SELECT
		'PRD'+@_PREF_CODICE+DESIVA AS CODICE,
		@_PREF_DESCRI + DESIVA + ' MM DA LEVIGARE' AS DESCRI,
		@_LIBERA AS LIBERA,
		DESIVA AS DESIVA
	FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA

--SELECT CODICE,DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'



-- CREAZIONE NUOVI CODICI ARTICOLO PANNELLO GREZZO DA LEVIGARE
DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'P_F_E1E05-%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'P_F_E1E05-%'
INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_DATVAR,ART_UMMAGA,ART_CODMAT,ART_TIPART,ART_SPESSO,ART_GRUPRD) 
	SELECT '01','P_F_E1E05-10','FUOCO - XILOPAN IGNIFUGO - E1E05 10 MM DA LEVIGARE','MC','05','022','SEDE',CONVERT(VARCHAR, GETDATE(), 111),'MC','008','P',10,'P_F_E1E05-10'
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,REG_DATREG) 
	SELECT '01','P_F_E1E05-10','FJ',CONVERT(VARCHAR, GETDATE(), 111)

DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'P_F_E1E05_FSC-%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'P_F_E1E05_FSC-%'
INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_DATVAR,ART_UMMAGA,ART_CODMAT,ART_TIPART,ART_SPESSO,ART_GRUPRD) 
	SELECT '01','P_F_E1E05_FSC-10','FUOCO - XILOPAN IGNIFUGO - E1E05 FSC MIX 100% 10 MM DA LEVIGARE','MC','05','022','SEDE',CONVERT(VARCHAR, GETDATE(), 111),'MC','008','P',10,'P_F_E1E05_FSC-10'
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,REG_DATREG) 
	SELECT '01','P_F_E1E05_FSC-10','FK',CONVERT(VARCHAR, GETDATE(), 111)

DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'P_A_E1E05-%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'P_A_E1E05-%'
INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_DATVAR,ART_UMMAGA,ART_CODMAT,ART_TIPART,ART_SPESSO,ART_GRUPRD) 
	SELECT '01','P_A_E1E05-10','ARIA - XIL400 E1E05 10 MM DA LEVIGARE','MC','05','022','SEDE',CONVERT(VARCHAR, GETDATE(), 111),'MC','008','P',10,'P_A_E1E05-10'
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,REG_DATREG) 
	SELECT '01','P_A_E1E05-10','AJ',CONVERT(VARCHAR, GETDATE(), 111)

DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'P_A_E1E05_FSC-%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'P_A_E1E05_FSC-%'
INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_DATVAR,ART_UMMAGA,ART_CODMAT,ART_TIPART,ART_SPESSO,ART_GRUPRD) 
	SELECT '01','P_A_E1E05_FSC-10','ARIA - XIL400 E1E05 FSC 100% 10 MM DA LEVIGARE','MC','05','022','SEDE',CONVERT(VARCHAR, GETDATE(), 111),'MC','008','P',10,'P_A_E1E05_FSC-10'
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,REG_DATREG) 
	SELECT '01','P_A_E1E05_FSC-10','AK',CONVERT(VARCHAR, GETDATE(), 111)



-- INSERIMENTO DI.BA. GREZZO DA LEVIGARE PER TUTTI GLI SPESSORI DEL GRUPPO PRODUTTIVO, PARTENDO DA UNA DI.BA. SORGENTE
DELETE FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_F_E1E05-%'
DELETE FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_F_E1E05-%'
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_F_E1E05-%' AND CODICE NOT IN (SELECT 'PRD'+DIT_GRUPPO FROM U_DIS_TT) ORDER BY DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST 
FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_FUO_E1-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_F_E1E05-%'  AND CODICE NOT IN (SELECT 'PRD'+DIS_GRUPPO FROM U_DIS_DD GROUP BY DIS_GRUPPO) ORDER BY PARA.DESIVA
--SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_F_E1E05-%' ORDER BY DIT_GRUPPO
--SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_F_E1E05-%' ORDER BY DIS_GRUPPO,DIS_SEQUEN

DELETE FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_F_E1E05_FSC-%'
DELETE FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_F_E1E05_FSC-%'
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_F_E1E05_FSC-%' AND CODICE NOT IN (SELECT 'PRD'+DIT_GRUPPO FROM U_DIS_TT) ORDER BY DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST 
FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_FUO_E1_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_F_E1E05_FSC-%'  AND CODICE NOT IN (SELECT 'PRD'+DIS_GRUPPO FROM U_DIS_DD GROUP BY DIS_GRUPPO) ORDER BY PARA.DESIVA
--SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_F_E1E05_FSC-%' ORDER BY DIT_GRUPPO
--SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_F_E1E05_FSC-%' ORDER BY DIS_GRUPPO,DIS_SEQUEN

DELETE FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_A_E1E05-%'
DELETE FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_A_E1E05-%'
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_A_E1E05-%' AND CODICE NOT IN (SELECT 'PRD'+DIT_GRUPPO FROM U_DIS_TT) ORDER BY DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST 
FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_ARI_E1-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_A_E1E05-%'  AND CODICE NOT IN (SELECT 'PRD'+DIS_GRUPPO FROM U_DIS_DD GROUP BY DIS_GRUPPO) ORDER BY PARA.DESIVA
--SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_A_E1E05-%' ORDER BY DIT_GRUPPO
--SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_A_E1E05-%' ORDER BY DIS_GRUPPO,DIS_SEQUEN

DELETE FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_A_E1E05_FSC-%'
DELETE FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_A_E1E05_FSC-%'
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_A_E1E05_FSC-%' AND CODICE NOT IN (SELECT 'PRD'+DIT_GRUPPO FROM U_DIS_TT) ORDER BY DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST 
FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_ARI_E1_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_A_E1E05_FSC-%'  AND CODICE NOT IN (SELECT 'PRD'+DIS_GRUPPO FROM U_DIS_DD GROUP BY DIS_GRUPPO) ORDER BY PARA.DESIVA
--SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'P_A_E1E05_FSC-%' ORDER BY DIT_GRUPPO
--SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO LIKE 'P_A_E1E05_FSC-%' ORDER BY DIS_GRUPPO,DIS_SEQUEN


-- SOSTITUZIONE COMPONENTE 01.002.0001 (COLLA UREICA) CON 01.002.0007 (COLLA CON MELAMINA AL 3%)
UPDATE U_DIS_DD SET 
	DIS_CODART = '01.002.0007',
	DIS_DESCRI = (SELECT ART_DESCR FROM U_ART_PR WHERE ART_CODPRI = '01.002.0007')
WHERE DIS_CODART = '01.002.0001'
	AND (
		DIS_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05-%') OR
		DIS_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05_FSC-%') OR
		DIS_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05-%') OR
		DIS_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05_FSC-%')
		)



-- INSERIMENTO COMPONENTI 01.002.0002 (UREA 40%) E 01.004.0009 (UREA MICRO PRILL) OVE MANCANTI
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		4.1 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-2 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.002.0002')) AS DIT
	WHERE ART_CODPRI = '01.002.0002' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		5.7 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-1 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.004.0009')) AS DIT
	WHERE ART_CODPRI = '01.004.0009' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		4.1 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-2 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05_FSC-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.002.0002')) AS DIT
	WHERE ART_CODPRI = '01.002.0002' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		5.7 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-1 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_F_E1E05_FSC-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.004.0009')) AS DIT
	WHERE ART_CODPRI = '01.004.0009' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		4.1 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-2 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.002.0002')) AS DIT
	WHERE ART_CODPRI = '01.002.0002' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		5.7 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-1 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.004.0009')) AS DIT
	WHERE ART_CODPRI = '01.004.0009' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		4.1 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-2 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05_FSC-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.002.0002')) AS DIT
	WHERE ART_CODPRI = '01.002.0002' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_CODART,DIS_QTA,DIS_UM,DIS_MAGA,DIS_DESCRI,DIS_SEQUEN)
	SELECT
		DIT.TAGGANCIO AS DAGGANCIO,
		DIT.DIT_GRUPPO AS DIS_GRUPPO,
		ART_CODPRI AS DIS_CODART,
		5.7 AS DIS_QTA,
		ART_UMMAGA AS DIS_UM,
		ART_MAGA AS DIS_MAGA,
		ART_DESCR AS DIS_DESCRI,
		(SELECT TOP 1 DIS_SEQUEN-1 FROM U_DIS_DD WHERE DAGGANCIO = DIT.TAGGANCIO ORDER BY DIS_SEQUEN DESC) AS DIS_SEQUEN
	FROM U_ART_PR
	OUTER APPLY (SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT SUBSTRING(CODICE,4,16) FROM PARA WHERE CODICE LIKE 'PRDP_A_E1E05_FSC-%')
		AND DIT_GRUPPO NOT IN (SELECT DIS_GRUPPO FROM U_DIS_DD WHERE DIS_CODART = '01.004.0009')) AS DIT
	WHERE ART_CODPRI = '01.004.0009' AND DIT.TAGGANCIO IS NOT NULL
	ORDER BY DIT_GRUPPO

/*
DELETE FROM U_DIS_DD WHERE DIS_CODART IN ('01.002.0002','01.004.0009') AND DIS_GRUPPO LIKE 'P_F_E1E05-%'
DELETE FROM U_DIS_DD WHERE DIS_CODART IN ('01.002.0002','01.004.0009') AND DIS_GRUPPO LIKE 'P_F_E1E05_FSC-%'
DELETE FROM U_DIS_DD WHERE DIS_CODART IN ('01.002.0002','01.004.0009') AND DIS_GRUPPO LIKE 'P_A_E1E05-%'
DELETE FROM U_DIS_DD WHERE DIS_CODART IN ('01.002.0002','01.004.0009') AND DIS_GRUPPO LIKE 'P_A_E1E05_FSC-%'
*/