--***************************************************************
-- CREAZIONE NUOVI CODICI COLORE
--***************************************************************
DELETE FROM PARA WHERE CODICE IN ('COLUI2','COLUD2','COLUI3','COLUD3')
--SELECT * FROM PARA WHERE CODICE = 'COLU12'
--SELECT * FROM PARA WHERE CODICE = 'COLU13'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) SELECT 'COLUI2' AS CODICE,'UI2 BIANCO MEDIO I.' AS DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE = 'COLU12'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) SELECT 'COLUD2' AS CODICE,'UD2 BIANCO MEDIO D.' AS DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE = 'COLU12'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) SELECT 'COLUI3' AS CODICE,'UI3 BIANCO SUPER I.' AS DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE = 'COLU13'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) SELECT 'COLUD3' AS CODICE,'UD3 BIANCO SUPER D.' AS DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE = 'COLU13'

--UPDATE PARA SET DISATTIVO = 1 WHERE CODICE = 'COLU12'
--UPDATE PARA SET DISATTIVO = 1 WHERE CODICE = 'COLU13'

--SELECT * FROM PARA WHERE CODICE IN ('COLUI2','COLUD2','COLUI3','COLUD3')




--***************************************************************
-- CREAZIONE CODICI ARTICOLO CARTE IMPREGNATE
--***************************************************************
/*
SELECT * FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U12%'
SELECT * FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U12%')
SELECT * FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U13%'
SELECT * FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U12%')
*/

--SELECT * FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U12%' AND ART_CODPRI <> '01.003.0844'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODF1,ART_PRZCO1,ART_NOTA1,ART_NOTE,ART_DATVAR,ART_DATINS,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
SELECT
	ART_CODSOC,
	'01.003.'+CAST((ROW_NUMBER() OVER(ORDER BY ART_CODPRI)) + CAST((select TOP 1 SUBSTRING(ART_CODPRI,8,4) AS CODES from u_art_pr where SUBSTRING(ART_CODPRI,1,2) = '01' AND SUBSTRING(ART_CODPRI,4,3) = '003' AND SUBSTRING(ART_CODPRI,8,1) <> 'G'  order by art_codpri DESC) AS NUMERIC(4,0)) AS NVARCHAR(4)) AS ART_CODPRI,
	REPLACE(ART_DESCR,'U12','UI2') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	'6010101' AS ART_CGE,
	'00002814' AS ART_CODF1,
	CASE
		WHEN ART_CODF1 = '00002814' THEN ART_PRZCO1
		WHEN ART_CODF2 = '00002814' THEN ART_PRZCO2
		WHEN ART_CODF3 = '00002814' THEN ART_PRZCO3
		WHEN ART_CODF4 = '00002814' THEN ART_PRZCO4
		WHEN ART_CODF5 = '00002814' THEN ART_PRZCO5
		ELSE 0
	END AS ART_PRZCO1,
	CASE
		WHEN ART_CODF1 = '00002814' THEN ART_NOTA1
		WHEN ART_CODF2 = '00002814' THEN ART_NOTA2
		WHEN ART_CODF3 = '00002814' THEN ART_NOTA3
		WHEN ART_CODF4 = '00002814' THEN ART_NOTA4
		WHEN ART_CODF5 = '00002814' THEN ART_NOTA5
		ELSE ''
	END AS ART_NOTA1,
	ART_NOTE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	'UI2' AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COLUI2'),REPLACE(ART_DESCOL,'U12','UI2')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	ART_CODCAT,
	ART_DESCAT
FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U12%' AND ART_CODPRI <> '01.003.0844'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODF1,ART_PRZCO1,ART_NOTA1,ART_NOTE,ART_DATVAR,ART_DATINS,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
SELECT
	ART_CODSOC,
	'01.003.'+CAST((ROW_NUMBER() OVER(ORDER BY ART_CODPRI)) + CAST((select TOP 1 SUBSTRING(ART_CODPRI,8,4) AS CODES from u_art_pr where SUBSTRING(ART_CODPRI,1,2) = '01' AND SUBSTRING(ART_CODPRI,4,3) = '003' AND SUBSTRING(ART_CODPRI,8,1) <> 'G'  order by art_codpri DESC) AS NUMERIC(4,0)) AS NVARCHAR(4)) AS ART_CODPRI,
	REPLACE(ART_DESCR,'U12','UD2') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	'6010101' AS ART_CGE,
	'00003924' AS ART_CODF1,
	CASE
		WHEN ART_CODF1 = '00003924' THEN ART_PRZCO1
		WHEN ART_CODF2 = '00003924' THEN ART_PRZCO2
		WHEN ART_CODF3 = '00003924' THEN ART_PRZCO3
		WHEN ART_CODF4 = '00003924' THEN ART_PRZCO4
		WHEN ART_CODF5 = '00003924' THEN ART_PRZCO5
		ELSE 0
	END AS ART_PRZCO1,
	CASE
		WHEN ART_CODF1 = '00003924' THEN ART_NOTA1
		WHEN ART_CODF2 = '00003924' THEN ART_NOTA2
		WHEN ART_CODF3 = '00003924' THEN ART_NOTA3
		WHEN ART_CODF4 = '00003924' THEN ART_NOTA4
		WHEN ART_CODF5 = '00003924' THEN ART_NOTA5
		ELSE ''
	END AS ART_NOTA1,
	ART_NOTE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	'UD2' AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COLUD2'),REPLACE(ART_DESCOL,'U12','UD2')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	ART_CODCAT,
	ART_DESCAT
FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U12%' AND ART_CODPRI <> '01.003.0844'


--SELECT * FROM U_ART_PR WHERE ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U13%'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODF1,ART_PRZCO1,ART_NOTA1,ART_NOTE,ART_DATVAR,ART_DATINS,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
SELECT
	ART_CODSOC,
	'01.003.'+CAST((ROW_NUMBER() OVER(ORDER BY ART_CODPRI)) + CAST((select TOP 1 SUBSTRING(ART_CODPRI,8,4) AS CODES from u_art_pr where SUBSTRING(ART_CODPRI,1,2) = '01' AND SUBSTRING(ART_CODPRI,4,3) = '003' AND SUBSTRING(ART_CODPRI,8,1) <> 'G'  order by art_codpri DESC) AS NUMERIC(4,0)) AS NVARCHAR(4)) AS ART_CODPRI,
	REPLACE(ART_DESCR,'U13','UI3') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	'6010101' AS ART_CGE,
	'00002814' AS ART_CODF1,
	CASE
		WHEN ART_CODF1 = '00002814' THEN ART_PRZCO1
		WHEN ART_CODF2 = '00002814' THEN ART_PRZCO2
		WHEN ART_CODF3 = '00002814' THEN ART_PRZCO3
		WHEN ART_CODF4 = '00002814' THEN ART_PRZCO4
		WHEN ART_CODF5 = '00002814' THEN ART_PRZCO5
		ELSE 0
	END AS ART_PRZCO1,
	CASE
		WHEN ART_CODF1 = '00002814' THEN ART_NOTA1
		WHEN ART_CODF2 = '00002814' THEN ART_NOTA2
		WHEN ART_CODF3 = '00002814' THEN ART_NOTA3
		WHEN ART_CODF4 = '00002814' THEN ART_NOTA4
		WHEN ART_CODF5 = '00002814' THEN ART_NOTA5
		ELSE ''
	END AS ART_NOTA1,
	ART_NOTE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	'UI3' AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COLUI3'),REPLACE(ART_DESCOL,'U13','UI3')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	ART_CODCAT,
	ART_DESCAT
FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U13%'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CGE,ART_CODF1,ART_PRZCO1,ART_NOTA1,ART_NOTE,ART_DATVAR,ART_DATINS,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT)
SELECT
	ART_CODSOC,
	'01.003.'+CAST((ROW_NUMBER() OVER(ORDER BY ART_CODPRI)) + CAST((select TOP 1 SUBSTRING(ART_CODPRI,8,4) AS CODES from u_art_pr where SUBSTRING(ART_CODPRI,1,2) = '01' AND SUBSTRING(ART_CODPRI,4,3) = '003' AND SUBSTRING(ART_CODPRI,8,1) <> 'G'  order by art_codpri DESC) AS NUMERIC(4,0)) AS NVARCHAR(4)) AS ART_CODPRI,
	REPLACE(ART_DESCR,'U13','UD3') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	'6010101' AS ART_CGE,
	'00003924' AS ART_CODF1,
	CASE
		WHEN ART_CODF1 = '00003924' THEN ART_PRZCO1
		WHEN ART_CODF2 = '00003924' THEN ART_PRZCO2
		WHEN ART_CODF3 = '00003924' THEN ART_PRZCO3
		WHEN ART_CODF4 = '00003924' THEN ART_PRZCO4
		WHEN ART_CODF5 = '00003924' THEN ART_PRZCO5
		ELSE 0
	END AS ART_PRZCO1,
	CASE
		WHEN ART_CODF1 = '00003924' THEN ART_NOTA1
		WHEN ART_CODF2 = '00003924' THEN ART_NOTA2
		WHEN ART_CODF3 = '00003924' THEN ART_NOTA3
		WHEN ART_CODF4 = '00003924' THEN ART_NOTA4
		WHEN ART_CODF5 = '00003924' THEN ART_NOTA5
		ELSE ''
	END AS ART_NOTA1,
	ART_NOTE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	'UD3' AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COLUD3'),REPLACE(ART_DESCOL,'U13','UD3')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	ART_CODCAT,
	ART_DESCAT
FROM U_ART_PR WHERE ART_OBSOL = '' AND ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U13%'

INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI)
	SELECT ART_CODSOC,ART_CODPRI FROM U_ART_PR WHERE ART_CODPRI NOT IN (SELECT ART_CODPRI FROM U_ART_AN)


--SELECT * FROM U_ART_PR WHERE ART_CODCOL IN ('UI2','UD2','UI3','UD3') AND ART_CODMAT = '011' ORDER BY ART_CODPRI

/*
UPDATE U_ART_PR SET ART_OBSOL = 'S' WHERE ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U12%'
UPDATE U_ART_PR SET ART_OBSOL = 'S' WHERE ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND ART_DESCR LIKE '%U13%'
*/

--UPDATE U_ART_PR SET ART_OBSOL = '' WHERE ART_CODCOL = 'U12' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U12%' AND ART_CODPRI <> '01.003.0844'
--UPDATE U_ART_PR SET ART_OBSOL = '' WHERE ART_CODCOL = 'U13' AND ART_CODMAT = '011' AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('37702080','42101870','42102080','56202080') AND ART_DESCR LIKE '%U13%'

/*
DELETE FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODCOL IN ('UI2','UD2','UI3','UD3') AND ART_CODMAT = '011')
DELETE FROM U_ART_PR WHERE ART_CODCOL IN ('UI2','UD2','UI3','UD3') AND ART_CODMAT = '011'
*/



--***************************************************************
-- CREAZIONE CODICI ARTICOLO PANNELLI NOBILITATI
--***************************************************************
--SELECT * FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1')
--SELECT * FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1'))

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CLDOG,ART_CGE,ART_DATVAR,ART_DATINS,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CDDIBA,ART_GRUPRD)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U12','UI2') AS ART_CODPRI,
	REPLACE(ART_DESCR,'U12','UI2') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	ART_CLDOG,
	ART_CGE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODVAL,
	ART_CATMER,
	ART_DESMER,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	REPLACE(ART_CODCOL,'U12','UI2') AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COL'+REPLACE(ART_CODCOL,'U12','UI2')),REPLACE(ART_DESCOL,'U12','UI2')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	REPLACE(ART_CDDIBA,'U12','UI2') AS ART_CDDIBA,
	ART_GRUPRD
FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070')

INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,ART_TIPON,ART_CODCOLRET,ART_FINI,ART_SCELTA)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U12','UI2') AS ART_CODPRI,
	ART_TIPOG,
	ART_TIPON,
	REPLACE(ART_CODCOLRET,'U12','UI2') AS ART_CODCOLRET,
	ART_FINI,
	ART_SCELTA
FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))



INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CLDOG,ART_CGE,ART_DATVAR,ART_DATINS,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CDDIBA,ART_GRUPRD)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U12','UD2') AS ART_CODPRI,
	REPLACE(ART_DESCR,'U12','UD2') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	ART_CLDOG,
	ART_CGE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODVAL,
	ART_CATMER,
	ART_DESMER,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	REPLACE(ART_CODCOL,'U12','UD2') AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COL'+REPLACE(ART_CODCOL,'U12','UD2')),REPLACE(ART_DESCOL,'U12','UD2')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	REPLACE(ART_CDDIBA,'U12','UD2') AS ART_CDDIBA,
	ART_GRUPRD
FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070')

INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,ART_TIPON,ART_CODCOLRET,ART_FINI,ART_SCELTA)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U12','UD2') AS ART_CODPRI,
	ART_TIPOG,
	ART_TIPON,
	REPLACE(ART_CODCOLRET,'U12','UD2') AS ART_CODCOLRET,
	ART_FINI,
	ART_SCELTA
FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U12' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))



INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CLDOG,ART_CGE,ART_DATVAR,ART_DATINS,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CDDIBA,ART_GRUPRD)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U13','UI3') AS ART_CODPRI,
	REPLACE(ART_DESCR,'U13','UI3') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	ART_CLDOG,
	ART_CGE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODVAL,
	ART_CATMER,
	ART_DESMER,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	REPLACE(ART_CODCOL,'U13','UI3') AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COL'+REPLACE(ART_CODCOL,'U13','UI3')),REPLACE(ART_DESCOL,'U13','UI3')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	REPLACE(ART_CDDIBA,'U13','UI3') AS ART_CDDIBA,
	ART_GRUPRD
FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U13' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070')

INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,ART_TIPON,ART_CODCOLRET,ART_FINI,ART_SCELTA)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U13','UI3') AS ART_CODPRI,
	ART_TIPOG,
	ART_TIPON,
	REPLACE(ART_CODCOLRET,'U13','UI3') AS ART_CODCOLRET,
	ART_FINI,
	ART_SCELTA
FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U13' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))



INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_PRZCOS,ART_CODIVA,ART_MAGA,ART_CLDOG,ART_CGE,ART_DATVAR,ART_DATINS,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_CODCOL,ART_DESCOL,ART_DESRID,ART_DESLIN,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CDDIBA,ART_GRUPRD)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U13','UD3') AS ART_CODPRI,
	REPLACE(ART_DESCR,'U13','UD3') AS ART_DESCR,
	ART_UNIMIS,
	ART_LINEA,
	ART_PRZCOS,
	ART_CODIVA,
	ART_MAGA,
	ART_CLDOG,
	ART_CGE,
	convert(varchar, GETDATE(), 111) AS ART_DATVAR,
	'' AS ART_DATINS,
	ART_CODVAL,
	ART_CATMER,
	ART_DESMER,
	ART_CODMAT,
	ART_TIPART,
	ART_DISBAS,
	ART_RIPCOM,
	REPLACE(ART_CODCOL,'U13','UD3') AS ART_CODCOL,
	COALESCE((SELECT TOP 1 DESCRI FROM PARA WHERE CODICE = 'COL'+REPLACE(ART_CODCOL,'U13','UD3')),REPLACE(ART_DESCOL,'U13','UD3')) AS ART_DESCOL,
	ART_DESRID,
	ART_DESLIN,
	ART_UMMAGA,
	ART_DESMAT,
	ART_SPESSO,
	ART_ALTEZZ,
	ART_LUNGHE,
	REPLACE(ART_CDDIBA,'U13','UD3') AS ART_CDDIBA,
	ART_GRUPRD
FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U13' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070')

INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_TIPOG,ART_TIPON,ART_CODCOLRET,ART_FINI,ART_SCELTA)
SELECT
	ART_CODSOC,
	REPLACE(ART_CODPRI,'U13','UD3') AS ART_CODPRI,
	ART_TIPOG,
	ART_TIPON,
	REPLACE(ART_CODCOLRET,'U13','UD3') AS ART_CODCOLRET,
	ART_FINI,
	ART_SCELTA
FROM U_ART_AN WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND (ART_CODCOL = 'U13' OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET= 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))


--UPDATE U_ART_PR SET ART_OBSOL = 'S' WHERE ART_OBSOL = '' AND (ART_CODCOL IN ('U12','U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('U12','U13'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '')

--UPDATE U_ART_PR SET ART_OBSOL = '' WHERE ART_OBSOL = 'S' AND (ART_CODCOL IN ('U12','U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('U12','U13'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070')

--DELETE FROM U_ART_PR WHERE (ART_CODCOL IN ('UI2','UD2','UI3','UD3') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('UI2','UD2','UI3','UD3'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '')
--DELETE FROM U_ART_AN WHERE ART_CODPRI NOT IN (SELECT ART_CODPRI FROM U_ART_PR)




--***************************************************************
-- CREAZIONE DISTINTE BASE NUOVI PANNELLI GENERATI
--***************************************************************
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA)
SELECT
	'01' AS DIT_CODSOC,
	'_'+SUBSTRING(CONVERT(varchar(40), NEWID()),0,9) AS TAGGANCIO,
	REPLACE(DIT_GRUPPO,'U12','UI2') AS DIT_GRUPPO,
	REPLACE(DIT_DESCRI,'U12','UI2') AS DIT_DESCRI,
	DIT_UM,
	DIT_MAGA,
	DIT_LINEA,
	'022' AS DIT_CODIVA
FROM U_DIS_TT 
WHERE DIT_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL = 'U12') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	'01' AS DIT_CODSOC,
	'_'+SUBSTRING(CONVERT(varchar(40), NEWID()),0,9) AS TAGGANCIO,
	REPLACE(DIT_GRUPPO,'U12','UD2') AS DIT_GRUPPO,
	REPLACE(DIT_DESCRI,'U12','UD2') AS DIT_DESCRI,
	DIT_UM,
	DIT_MAGA,
	DIT_LINEA,
	'022' AS DIT_CODIVA
FROM U_DIS_TT 
WHERE DIT_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL = 'U12') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	'01' AS DIT_CODSOC,
	'_'+SUBSTRING(CONVERT(varchar(40), NEWID()),0,9) AS TAGGANCIO,
	REPLACE(DIT_GRUPPO,'U13','UI3') AS DIT_GRUPPO,
	REPLACE(DIT_DESCRI,'U13','UI3') AS DIT_DESCRI,
	DIT_UM,
	DIT_MAGA,
	DIT_LINEA,
	'022' AS DIT_CODIVA
FROM U_DIS_TT 
WHERE DIT_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL = 'U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	'01' AS DIT_CODSOC,
	'_'+SUBSTRING(CONVERT(varchar(40), NEWID()),0,9) AS TAGGANCIO,
	REPLACE(DIT_GRUPPO,'U13','UD3') AS DIT_GRUPPO,
	REPLACE(DIT_DESCRI,'U13','UD3') AS DIT_DESCRI,
	DIT_UM,
	DIT_MAGA,
	DIT_LINEA,
	'022' AS DIT_CODIVA
FROM U_DIS_TT 
WHERE DIT_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ((ART_CODCOL = 'U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))

--DELETE FROM U_DIS_TT WHERE DIT_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL IN ('UI2','UD2','UI3','UD3')) OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('UI2','UD2','UI3','UD3'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1'))

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) 
SELECT
	(SELECT TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO = REPLACE(DIS_GRUPPO,'U12','UI2')) AS DAGGANCIO,
	REPLACE(DIS_GRUPPO,'U12','UI2') AS DIS_GRUPPO,
	DIS_TIPO,
	DIS_ESPLOD,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UI2' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'.')
		ELSE DIS_CODART
	END AS DIS_CODART,
	DIS_QTA,
	DIS_MAGA,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UI2' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'')
		ELSE DIS_DESCRI
	END AS DIS_DESCRI,
	DIS_UM,
	DIS_SEQUEN,
	DIS_FASELA,
	DIS_OPZCST
FROM U_DIS_DD
WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ((ART_CODCOL = 'U12') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	(SELECT TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO = REPLACE(DIS_GRUPPO,'U12','UD2')) AS DAGGANCIO,
	REPLACE(DIS_GRUPPO,'U12','UD2') AS DIS_GRUPPO,
	DIS_TIPO,
	DIS_ESPLOD,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UD2' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'.')
		ELSE DIS_CODART
	END AS DIS_CODART,
	DIS_QTA,
	DIS_MAGA,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UD2' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'')
		ELSE DIS_DESCRI
	END AS DIS_DESCRI,
	DIS_UM,
	DIS_SEQUEN,
	DIS_FASELA,
	DIS_OPZCST
FROM U_DIS_DD
WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ((ART_CODCOL = 'U12') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U12')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	(SELECT TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO = REPLACE(DIS_GRUPPO,'U13','UI3')) AS DAGGANCIO,
	REPLACE(DIS_GRUPPO,'U13','UI3') AS DIS_GRUPPO,
	DIS_TIPO,
	DIS_ESPLOD,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UI3' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'.')
		ELSE DIS_CODART
	END AS DIS_CODART,
	DIS_QTA,
	DIS_MAGA,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UI3' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'')
		ELSE DIS_DESCRI
	END AS DIS_DESCRI,
	DIS_UM,
	DIS_SEQUEN,
	DIS_FASELA,
	DIS_OPZCST
FROM U_DIS_DD
WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ((ART_CODCOL = 'U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))
UNION
SELECT
	(SELECT TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO = REPLACE(DIS_GRUPPO,'U13','UD3')) AS DAGGANCIO,
	REPLACE(DIS_GRUPPO,'U13','UD3') AS DIS_GRUPPO,
	DIS_TIPO,
	DIS_ESPLOD,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UD3' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'.')
		ELSE DIS_CODART
	END AS DIS_CODART,
	DIS_QTA,
	DIS_MAGA,
	CASE
		WHEN SUBSTRING(DIS_CODART,1,7) = '01.003.' THEN COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = 'UD3' AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = DIS_CODART)),'')
		ELSE DIS_DESCRI
	END AS DIS_DESCRI,
	DIS_UM,
	DIS_SEQUEN,
	DIS_FASELA,
	DIS_OPZCST
FROM U_DIS_DD
WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL = '' AND ((ART_CODCOL = 'U13') OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET = 'U13')) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1') AND RTRIM(CAST(ART_ALTEZZ AS NVARCHAR(10)))+RTRIM(CAST(ART_LUNGHE AS NVARCHAR(10))) IN ('28002070','37602070','42001860','42002070','56002070','56102070'))

--DELETE FROM U_DIS_DD WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL IN ('UI2','UD2','UI3','UD3')) OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('UI2','UD2','UI3','UD3'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1'))
--SELECT * FROM U_DIS_DD WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ((ART_CODCOL IN ('UI2','UD2','UI3','UD3')) OR ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_CODCOLRET IN ('UI2','UD2','UI3','UD3'))) AND ART_CODMAT = '008' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPON <> '' AND ART_SCELTA = '1'))



--***************************************************************
-- AGGIORNAMENTO ORDINI FORNITORI
--***************************************************************
/*
SELECT ORS_CODCLI AS CODCLI,ORS_RAGSOC AS RAGSOC,ORD_CODCOL,
	COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = (CASE WHEN ORS_CODCLI='00002814' THEN 'UI2' ELSE 'UD2' END) AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART)),ORD_CODART),
* 
FROM U_ORF_DD WHERE DAGGANCIO IN (SELECT TAGGANCIO FROM U_ORF_TT WHERE ORD_CHIUSO = 0) AND  ORD_CHIUSO = 0 AND ORD_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODCOL IN ('U12','U13') AND ART_CODMAT = '011') AND ORD_QTAEV < ORD_QTAORD
ORDER BY ORS_CODCLI,ORD_CODART
*/

UPDATE U_ORF_DD SET
	ORD_CODART = COALESCE((SELECT ART_CODPRI FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = (CASE WHEN ORS_CODCLI='00002814' THEN 'UI2' ELSE 'UD2' END) AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART)),ORD_CODART),
	ORD_DESART = COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = (CASE WHEN ORS_CODCLI='00002814' THEN 'UI2' ELSE 'UD2' END) AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART)),ORD_CODART),
	ORD_CODCOL = COALESCE((SELECT ART_CODCOL FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = (CASE WHEN ORS_CODCLI='00002814' THEN 'UI2' ELSE 'UD2' END) AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART)),ORD_CODART),
	ORD_DESCOL = COALESCE((SELECT ART_DESCOL FROM U_ART_PR WHERE SUBSTRING(ART_CODPRI,1,7) = '01.003.' AND ART_CODCOL = (CASE WHEN ORS_CODCLI='00002814' THEN 'UI2' ELSE 'UD2' END) AND ART_ALTEZZ = (SELECT ART_ALTEZZ FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART) AND ART_LUNGHE = (SELECT ART_LUNGHE FROM U_ART_PR WHERE ART_CODPRI = ORD_CODART)),ORD_CODART)
FROM U_ORF_DD WHERE DAGGANCIO IN (SELECT TAGGANCIO FROM U_ORF_TT WHERE ORD_CHIUSO = 0) AND  ORD_CHIUSO = 0 AND ORD_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODCOL IN ('U12','U13') AND ART_CODMAT = '011') AND ORD_QTAEV < ORD_QTAORD

/*
SELECT ORS_CODCLI AS CODCLI,ORS_RAGSOC AS RAGSOC,ORD_CODART AS CODART,ORD_DESART,ORD_CODCOL,ORD_DESCOL,*
FROM U_ORF_DD WHERE DAGGANCIO IN (SELECT TAGGANCIO FROM U_ORF_TT WHERE ORD_CHIUSO = 0) AND  ORD_CHIUSO = 0 AND ORD_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODCOL IN ('UI2','UD2') AND ART_CODMAT = '011') AND ORD_QTAEV < ORD_QTAORD
ORDER BY ORS_CODCLI,ORD_CODART
*/
