
-- INSERIRE LE VARIABILI DA DICHIARARE PER POPOLARE TUTTI GLI SPESSORI PER I NUOVI GRUPPI PRODUTTIVI

DECLARE @_PREF_CODICE AS VARCHAR(100)
DECLARE @_PREF_DESCRI AS VARCHAR(100)
DECLARE @_LIBERA AS VARCHAR(2)
SET @_PREF_CODICE = 'POP_ACQ_FUOCO-'
SET @_PREF_DESCRI = 'TRUCIOLARE GREZZO IGNI-IDRO '
SET @_LIBERA = 'HA'


DELETE FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
	SELECT
		'PRD'+@_PREF_CODICE+DESIVA AS CODICE,
		@_PREF_DESCRI + DESIVA + ' MM DA LEVIGARE' AS DESCRI,
		@_LIBERA AS LIBERA,
		DESIVA AS DESIVA
	FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA


SELECT CODICE,DESCRI,LIBERA,DESIVA FROM PARA WHERE CODICE LIKE 'PRD'+@_PREF_CODICE+'%'