
DELETE FROM pjtiprep WHERE NOMEPROC = 'RDA_DD'
DELETE FROM pjtiprep WHERE NOMEPROC = 'RDA_ELEN'

INSERT INTO pjtiprep (COMPA,DESCOM,NOMEPROC,DESPROC,NOMEREP,NOMEREP2,NOMEREP3,NOMEREP4) VALUES ('','','RDA_DD','STAMPA RDA','RDA_DD_XIL.FRX','','','')
INSERT INTO pjtiprep (COMPA,DESCOM,NOMEPROC,DESPROC,NOMEREP,NOMEREP2,NOMEREP3,NOMEREP4) VALUES ('','','RDA_ELEN','STAMPA ELENCO RDA','RDA_ELEN_XIL.FRX','','','')

select * from pjtiprep WHERE NOMEPROC = 'RDA_DD' OR NOMEPROC = 'RDA_ELEN' ORDER BY NOMEPROC

