
-- TRASFORMAZIONE ATTUALE PARAMETRO 'TIPO GREZZO'
SELECT * FROM PARA WHERE CODICE LIKE 'TIG%' ORDER BY CODICE
--UPDATE PARA SET CODICE = 'TIG0'+SUBSTRING(CODICE,4,1) WHERE CODICE LIKE 'TIG%'
--UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'TIG%' AND SUBSTRING(CODICE,4,1) = '0' AND SUBSTRING(CODICE,4,2) NOT IN ('0*','0#','0F','0G','0J','0K','0L','0M','0N','0O','0P','0Q','0R','0S')


-- TRASFORMAZIONE ATTUALE PARAMETRO 'TIPO NOBILITATO'
SELECT * FROM PARA WHERE CODICE LIKE 'TNO%' ORDER BY CODICE
--UPDATE PARA SET CODICE = 'TNO0'+SUBSTRING(CODICE,4,1) WHERE CODICE LIKE 'TNO%'
--UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'TNO%' AND SUBSTRING(CODICE,4,1) = '0' AND SUBSTRING(CODICE,4,2) NOT IN ('0*','0#','0F','0G','0J','0K','0L','0M','0N','0O','0P','0Q','0R','0S')


-- AGGIORNAMENTO PARAMETRO 'GRUPPI PRODUTTIVI'
SELECT * FROM PARA WHERE CODICE LIKE 'PRD%' ORDER BY codice
--UPDATE PARA SET LIBERA = '0'+RTRIM(LIBERA) WHERE CODICE LIKE 'PRD%'
--UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'PRD%' AND LIBERA LIKE '0%'


-- AGGIORNAMENTO PARAMETRO AZIENDALE Non visualizza i parametri disattivati in ELENCO
--UPDATE U_AZI_PB SET AZI_ELNODISA = 1


-- INSERIMENTO NUOVI TIPI GREZZI
/*
DELETE FROM PARA WHERE CODICE IN ('TIGAA','TIGBA','TIGCA','TIGDA','TIGFA','TIGBB','TIGIB','TIGAB','TIGDB','TIGAC','TIGBC','TIGCC','TIGDC','TIGFC','TIGHA','TIGIA','TIGAG','TIGGA','TIGDE','TIGCE','TIGFE','TIGFB','TIGAE')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGBG','POP MATERIA - CARB 2','','P_MAT_CARB')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGAA','POP LEGNO - E1','','P_LGN_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGBA','POP MATERIA - E1','','P_MAT_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGCA','POP ACQUA PLUS - E1','','P_ACQ_PL_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGDA','POP ACQUA - E1','','P_ACQ_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGFA','POP FUOCO - XILOPAN IGNIFUGO - E1','','P_FUO_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGBB','POP MATERIA - E1 FSC MIX CREDIT','','P_MAT_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGIB','POP ARIA - E1 FSC 100%','','P_ARI_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGAB','POP LEGNO - E1 FSC 100%','','P_LGN_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGDB','POP ACQUA - E1 FSC MIX CREDIT','','P_ACQ_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGAC','POP LEGNO - EPF-S','','P_LGN_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGBC','POP MATERIA - EPF-S','','P_MAT_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGCC','POP ACQUA PLUS - EPF-S','','P_ACQ_PL_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGDC','POP ACQUA - EPF-S','','P_ACQ_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGFC','POP FUOCO - XILOPAN IGNIFUGO - EPF-S','','P_FUO_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGHA','POP ACQUA-FUOCO - XILOPAN IGNIFUGO - E1','','P_ACQ_FUO_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGIA','POP ARIA - E1','','P_ARI_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGAG','POP LEGNO - CARB 2','','P_LGN_CARB')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGGA','POP ACQUA PURA - E1','','P_ACQ_PU_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGDE','POP ACQUA - E0','','P_ACQ_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGCE','POP ACQUA PLUS - E0','','P_ACQ_PL_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGFE','POP FUOCO - XILOPAN IGNIFUGO - E0','','P_FUO_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGFB','POP FUOCO - XILOPAN IGNIFUGO - E1 FSC MIX CREDIT','','P_FUO_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TIGAE','POP LEGNO - E0','','P_LGN_E0')


-- INSERIMENTO NUOVI TIPI NOBILITATO
DELETE FROM PARA WHERE CODICE IN ('TNOBG','TNOAA','TNOBA','TNOCA','TNODA','TNOFA','TNOBB','TNOIB','TNOAB','TNODB','TNOAC','TNOBC','TNOCC','TNODC','TNOFC','TNOHA','TNOIA','TNOAG','TNOGA','TNODE','TNOCE','TNOFE','TNOFB','TNOAE')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOBG','POP MATERIA - CARB 2','','P_MAT_CARB')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOAA','POP LEGNO - E1','','P_LGN_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOBA','POP MATERIA - E1','','P_MAT_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOCA','POP ACQUA PLUS - E1','','P_ACQ_PL_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNODA','POP ACQUA - E1','','P_ACQ_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOFA','POP FUOCO - XILOPAN IGNIFUGO - E1','','P_FUO_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOBB','POP MATERIA - E1 FSC MIX CREDIT','','P_MAT_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOIB','POP ARIA - E1 FSC 100%','','P_ARI_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOAB','POP LEGNO - E1 FSC 100%','','P_LGN_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNODB','POP ACQUA - E1 FSC MIX CREDIT','','P_ACQ_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOAC','POP LEGNO - EPF-S','','P_LGN_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOBC','POP MATERIA - EPF-S','','P_MAT_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOCC','POP ACQUA PLUS - EPF-S','','P_ACQ_PL_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNODC','POP ACQUA - EPF-S','','P_ACQ_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOFC','POP FUOCO - XILOPAN IGNIFUGO - EPF-S','','P_FUO_EPFS')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOHA','POP ACQUA-FUOCO - XILOPAN IGNIFUGO - E1','','P_ACQ_FUO_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOIA','POP ARIA - E1','','P_ARI_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOAG','POP LEGNO - CARB 2','','P_LGN_CARB')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOGA','POP ACQUA PURA - E1','','P_ACQ_PU_E1')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNODE','POP ACQUA - E0','','P_ACQ_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOCE','POP ACQUA PLUS - E0','','P_ACQ_PL_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOFE','POP FUOCO - XILOPAN IGNIFUGO - E0','','P_FUO_E0')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOFB','POP FUOCO - XILOPAN IGNIFUGO - E1 FSC MIX CREDIT','','P_FUO_E1_FSC')
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA) VALUES ('TNOAE','POP LEGNO - E0','','P_LGN_E0')
*/

-- INSERIMENTO NUOVI GRUPPI PRODUTTIVI
/*
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_MAT_CARB-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_MAT_CARB-'+RTRIM(DESIVA) AS CODICE, 'POP MATERIA - CARB 2 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'BG' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_LGN_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_LGN_E1-'+RTRIM(DESIVA) AS CODICE, 'POP LEGNO - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'AA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_MAT_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_MAT_E1-'+RTRIM(DESIVA) AS CODICE, 'POP MATERIA - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'BA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_PL_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_PL_E1-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA PLUS - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'CA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_E1-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'DA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_FUO_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_FUO_E1-'+RTRIM(DESIVA) AS CODICE, 'POP FUOCO - XILOPAN IGNIFUGO - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'FA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_MAT_E1_FSC-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_MAT_E1_FSC-'+RTRIM(DESIVA) AS CODICE, 'POP MATERIA - E1 FSC MIX CREDIT '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'BB' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ARI_E1_FSC-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ARI_E1_FSC-'+RTRIM(DESIVA) AS CODICE, 'POP ARIA - E1 FSC 100% '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'IB' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_LGN_E1_FSC-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_LGN_E1_FSC-'+RTRIM(DESIVA) AS CODICE, 'POP LEGNO - E1 FSC 100% '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'AB' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_E1_FSC-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_E1_FSC-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA - E1 FSC MIX CREDIT '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'DB' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_LGN_EPFS-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_LGN_EPFS-'+RTRIM(DESIVA) AS CODICE, 'POP LEGNO - EPF-S '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'AC' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_MAT_EPFS-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_MAT_EPFS-'+RTRIM(DESIVA) AS CODICE, 'POP MATERIA - EPF-S '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'BC' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_PL_EPFS-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_PL_EPFS-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA PLUS - EPF-S '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'CC' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_EPFS-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_EPFS-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA - EPF-S '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'DC' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_FUO_EPFS-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_FUO_EPFS-'+RTRIM(DESIVA) AS CODICE, 'POP FUOCO - XILOPAN IGNIFUGO - EPF-S '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'FC' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_FUO_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_FUO_E1-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA-FUOCO - XILOPAN IGNIFUGO - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'HA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ARI_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ARI_E1-'+RTRIM(DESIVA) AS CODICE, 'POP ARIA - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'IA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_LGN_CARB-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_LGN_CARB-'+RTRIM(DESIVA) AS CODICE, 'POP LEGNO - CARB 2 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'AG' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_PU_E1-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_PU_E1-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA PURA - E1 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'GA' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_E0-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_E0-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA - E0 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'DE' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_ACQ_PL_E0-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_ACQ_PL_E0-'+RTRIM(DESIVA) AS CODICE, 'POP ACQUA PLUS - E0 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'CE' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_FUO_E0-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_FUO_E0-'+RTRIM(DESIVA) AS CODICE, 'POP FUOCO - XILOPAN IGNIFUGO - E0 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'FE' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_FUO_E1_FSC-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_FUO_E1_FSC-'+RTRIM(DESIVA) AS CODICE, 'POP FUOCO - XILOPAN IGNIFUGO - E1 FSC MIX CREDIT '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'FB' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
DELETE FROM PARA WHERE CODICE LIKE 'PRDP_LGN_E0-%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA,DESIVA)
SELECT 'PRDP_LGN_E0-'+RTRIM(DESIVA) AS CODICE, 'POP LEGNO - E0 '+RTRIM(DESIVA)+ ' MM DA LEVIGARE' AS DESCRI,'AE' AS LIBERA, DESIVA AS DESIVA FROM PARA WHERE CODICE LIKE 'PRD%' GROUP BY DESIVA
*/

SELECT * FROM PARA WHERE CODICE LIKE 'PRD%' ORDER BY CODICE
--CORREZIONE X SPESSORI (NON ESEGUIRE)
--UPDATE PARA SET DESIVA = RTRIM(SUBSTRING(CODICE,CHARINDEX('-',CODICE)+1,2)) WHERE CODICE LIKE 'PRD%'


-- MODIFICA TIPO GREZZO/NOBILITATO IN ANAGRAFICA ARTICOLI PREESISTENTE (PER RETROCOMPATIBILITA' STATISTICHE DI MAGAZZINO)
/*
UPDATE U_ART_AN
SET 
	ART_TIPOG = CASE ART_TIPOG WHEN '' THEN ''
				ELSE '0'+ ART_TIPOG
				END,
	ART_TIPON = CASE ART_TIPON WHEN '' THEN ''
				ELSE '0'+ ART_TIPON
				END
WHERE ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 15 AND (LEN(RTRIM(ART_TIPOG)) = 1 OR LEN(RTRIM(ART_TIPON)) = 1))
*/
SELECT ART_TIPOG,ART_TIPON,* FROM U_ART_AN 
WHERE 
ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 15) 
ORDER BY ART_CODPRI


-- SETTAGGIO COME ARTICOLI OBSOLETI PER GLI ARTICOLI CON VECCHIA CODIFICA
/*
UPDATE U_ART_PR
SET 
	ART_OBSOL = 'S'
WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 15
*/


-- CHIUSURA PACKING LIST APERTE ESISTENTI
--UPDATE PROD_PACKING SET FLGDDT = 1 WHERE FLGDDT = 0
SELECT * FROM PROD_PACKING WHERE FLGDDT = 0


-- CHIUSURA PROGRAMMI DI PRODUZIONE APERTI (SOLO NOBILITATURA)
--UPDATE PRODUZIONE SET FLGCLOSED = 1 WHERE PARENT = '' AND FLGCLOSED = 0 AND IDPRG IN (SELECT IDPRG FROM PROD_AVANZA WHERE FASELA = 'NOBILI')
SELECT * FROM PRODUZIONE WHERE IDPRG IN (SELECT IDPRG FROM PRODUZIONE WHERE PARENT = '' AND FLGCLOSED = 0) AND IDPRG IN (SELECT IDPRG FROM PROD_AVANZA WHERE FASELA = 'NOBILI') ORDER BY IDPRG DESC


-- CREAZIONE DISTINTE BASE SPESSORE 10 PER OGNI NUOVO GRUPPO PRODUTTIVO
/*
DELETE FROM U_DIS_TT WHERE TAGGANCIO LIKE 'X%'
DELETE FROM U_DIS_DD WHERE DAGGANCIO LIKE 'X%'

INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_MAT_CARB-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_LGN_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_MAT_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_PL_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_FUO_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_MAT_E1_FSC-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ARI_E1_FSC-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_LGN_E1_FSC-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_E1_FSC-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_LGN_EPFS-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_MAT_EPFS-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_PL_EPFS-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_EPFS-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_FUO_EPFS-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_FUO_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ARI_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_LGN_CARB-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_ACQ_PU_E1-%' ORDER BY DESIVA
INSERT INTO U_DIS_TT (DIT_CODSOC,TAGGANCIO,DIT_GRUPPO,DIT_DESCRI,DIT_UM,DIT_MAGA,DIT_LINEA,DIT_CODIVA) SELECT '01' AS DIT_CODSOC, 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS TAGGANCIO, SUBSTRING(CODICE,4,16) AS DIT_GRUPPO, DESCRI AS DIT_DESCRI,'MC' AS DIT_UM,'SEDE' AS DIT_MAGA,'05' AS DIT_LINEA,'022' AS DIT_CODIVA
FROM PARA WHERE CODICE LIKE 'PRD'+'P_FUO_E1_FSC-%' ORDER BY DESIVA

INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'CARB_2B-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_MAT_CARB-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'BEST-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_LGN_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'LIGHT-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_MAT_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'V100_P5-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_PL_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IDRO_P4-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IGNIFUGO-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_FUO_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'LIGHT_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_MAT_E1_FSC-%' ORDER BY PARA.DESIVA
--INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'XIL 400_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ARI_E1_FSC-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'BEST_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_LGN_E1_FSC-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IDRO_P4_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_E1_FSC-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'CLEAF-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_LGN_EPFS-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'LIGHT_EPFS-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_MAT_EPFS-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'V100_P5_EPFS-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_PL_EPFS-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IDRO_P4_EPFS-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_EPFS-%' ORDER BY PARA.DESIVA
--INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IGNIFUGO_EPFS-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_FUO_EPFS-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'POP_ACQ_FUOCO-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_FUO_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'XIL400-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ARI_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'CARB_2A-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_LGN_CARB-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'XIL400_I-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_ACQ_PU_E1-%' ORDER BY PARA.DESIVA
INSERT INTO U_DIS_DD (DAGGANCIO,DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST) SELECT 'X'+RTRIM(LIBERA)+'00000'+REPLACE(STR(DESIVA,2),SPACE(1),'0') AS DAGGANCIO, SUBSTRING(CODICE,4,16) AS DIS_GRUPPO,DIS_TIPO,DIS_ESPLOD,DIS_CODART,DIS_QTA,DIS_MAGA,DIS_DESCRI,DIS_UM,DIS_SEQUEN,DIS_FASELA,DIS_OPZCST FROM PARA LEFT OUTER JOIN U_DIS_DD ON DAGGANCIO = (SELECT TOP 1 TAGGANCIO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'IGNIFUGO_FSC-%' ORDER BY TAGGANCIO) WHERE PARA.CODICE LIKE 'PRD'+'P_FUO_E1_FSC-%' ORDER BY PARA.DESIVA
*/

SELECT * FROM U_DIS_TT WHERE TAGGANCIO LIKE 'X%' ORDER BY DIT_GRUPPO
SELECT * FROM U_DIS_DD WHERE DAGGANCIO LIKE 'X%' ORDER BY DIS_GRUPPO,DIS_SEQUEN


-- TABELLA PER FUNZIONE DI ATTRIBUZIONE DEL NUMERO DI PANNELLI PER PACCO
/*
UPDATE PARA SET CODICE = REPLACE(CODICE,'SHTE','SHTFC') WHERE CODICE LIKE 'SHTE%'
UPDATE PARA SET CODICE = REPLACE(CODICE,'SHTI','SHTIA') WHERE CODICE LIKE 'SHTI%'
*/
SELECT * FROM PARA WHERE CODICE LIKE 'SHT%' ORDER BY CODICE



-- DISATTIVAZIONE GRUPPI PRODUTTIVI SENZA DI.BA.
UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'PRDP_ACQ_E0-%'
UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'PRDP_ACQ_PL_E0-%'
UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'PRDP_FUO_E0-%'
UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'PRDP_LGN_E0-%'
