
UPDATE PARA SET FRANCESE = 'ABILITA_STAMPA_DOP:SI;
DICITURA_DOP:01-DOP;
DICITURA_ENI:ENI13986:2004+A1:2015;
DICITURA_TIPO_GREZZO:STANDARD;
DICITURA_TIPO_PANNELLO:Pannello di particelle P2 in legno riciclato e vergine;
DICITURA_CLASSE:Classe E1 (EN 13986);'
WHERE CODICE LIKE 'TIG%' AND (DESCRI LIKE '%STANDARD%' OR DESCRI LIKE '%STD%')

UPDATE PARA SET FRANCESE = 'ABILITA_STAMPA_DOP:SI;
DICITURA_DOP:01-DOP;
DICITURA_ENI:ENI13986:2004+A1:2015;
DICITURA_TIPO_GREZZO:PIOPPO;
DICITURA_TIPO_PANNELLO:Pannello di particelle P2 in legno vergine;
DICITURA_CLASSE:Classe E1 (EN 13986);'
WHERE CODICE LIKE 'TIG%' AND (DESCRI LIKE '%PIOPPO%' OR DESCRI LIKE '%PIOPPO%')

SELECT * FROM PARA WHERE CODICE LIKE 'TIG%' AND (DESCRI LIKE '%PIOPPO%' OR DESCRI LIKE '%PIOPPO%')
SELECT * FROM PARA WHERE CODICE LIKE 'TIG%' AND (DESCRI LIKE '%STANDARD%' OR DESCRI LIKE '%STD%')


