
-- UPDATE INDICE / MOV_CONT / MOV_CCO
UPDATE INDICE SET MOV_CODCCO = '' WHERE MOV_CODCCO <> '6010110' AND MOV_CODCCO <> ''
UPDATE MOV_CONT SET MOV_CCO = '' WHERE MOV_CONTO <> '6010110'
DELETE FROM MOV_CCO WHERE MOV_COPRIM <> '6010110'

-- VERIFICHE
SELECT MOV_NUMPRO,MOV_CONTO,MOV_CODCCO,MOV_TOP,* FROM INDICE WHERE MOV_CODCCO <> '6010110' AND MOV_CODCCO <> '' ORDER BY MOV_ANNO
SELECT MOV_NUMPRO,MOV_CCO,MOV_CONTO,MOV_SYSCCO,MOV_TOP,* FROM MOV_CONT WHERE MOV_CCO <> ''  AND MOV_CONTO = '6010110' ORDER BY MOV_SEQUEN
SELECT MOV_NUMPRO,MOV_CCO,MOV_COPRIM,MOV_SYSCCO,MOV_TOP,* FROM MOV_CCO WHERE MOV_CCO <> ''  AND MOV_COPRIM = '6010110'
SELECT SUM(MOV_IMP) AS TOTALE FROM MOV_CCO WHERE MOV_CCO <> ''  AND MOV_COPRIM = '6010110'