
UPDATE PARA SET LIBERA = 'V20 CARB P2', ITALIANO = 'CERT. CARB NR. 123 compliant with IOS MAT 0003 V8 and CCR-17-93120.2(a) P2' WHERE CODICE LIKE 'TIG%' AND DESCRI LIKE '%CARB%' AND  SUBSTRING(CODICE,4,1) <> '0'

SELECT * FROM PARA WHERE CODICE LIKE 'TIG%' AND DESCRI LIKE '%CARB%' AND SUBSTRING(CODICE,4,1) <> '0' ORDER BY CODICE