
UPDATE U_ART_PR SET ART_DESEST = 'PURO PIOPPO' WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE art_tipoG IN ('IA'))
UPDATE PARA SET NOTE = 'PURO PIOPPO' WHERE CODICE IN ('TIGIA')
UPDATE PARA SET NOTE = 'PURO PIOPPO' WHERE CODICE IN ('TNOIA')


UPDATE U_ART_PR SET ART_DESEST = 'TPC-036 CARB P2/EPA TSCA Title VI COMPLIANT' WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_DESCR LIKE '%CARB%'
UPDATE PARA SET NOTE = 'TPC-036 CARB P2/EPA TSCA Title VI COMPLIANT' WHERE CODICE LIKE 'TIG%' AND DESCRI LIKE '%CARB%'
UPDATE PARA SET NOTE = 'TPC-036 CARB P2/EPA TSCA Title VI COMPLIANT' WHERE CODICE LIKE 'TNO%' AND DESCRI LIKE '%CARB%'


SELECT ART_DESEST,* from u_art_pr WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE art_tipoG IN ('IA')) ORDER BY ART_CODPRI
SELECT NOTE,* FROM PARA WHERE CODICE IN ('TIGIA')
SELECT NOTE,* FROM PARA WHERE CODICE IN ('TNOIA')

SELECT ART_DESEST,* from u_art_pr WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_DESCR LIKE '%CARB%'
SELECT NOTE,* FROM PARA WHERE CODICE LIKE 'TIG%' AND DESCRI LIKE '%CARB%'
SELECT NOTE,* FROM PARA WHERE CODICE LIKE 'TNO%' AND DESCRI LIKE '%CARB%'