
UPDATE PARA SET CODPGO = '44101110' WHERE CODICE IN ('TIGAA','TIGAB','TIGAC','TIGAE','TIGAG','TIGBA','TIGBB','TIGBC','TIGBG','TIGIA','TIGIB')
UPDATE PARA SET CODPGO = '44101130' WHERE CODICE IN ('TNOAA','TNOAB','TNOAC','TNOAE','TNOAG','TNOBA','TNOBB','TNOBC','TNOBG','TNOIA','TNOIB')

UPDATE PARA SET CODPGO = '44101190' WHERE CODICE IN ('TIGCA','TIGCC','TIGCE','TIGDA','TIGDB','TIGDC','TIGDE','TIGFA','TIGFB','TIGFC','TIGFE','TIGGA','TIGHA')
UPDATE PARA SET CODPGO = '44101190' WHERE CODICE IN ('TNOCA','TNOCC','TNOCE','TNODA','TNODB','TNODC','TNODE','TNOFA','TNOFB','TNOFC','TNOFE','TNOGA','TNOHA')


SELECT * FROM PARA WHERE CODICE LIKE 'TIG%' ORDER BY CODICE
SELECT * FROM PARA WHERE CODICE LIKE 'TNO%' ORDER BY CODICE