
SELECT ART_DESEST,* from u_art_pr WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE art_tipoG IN ('IA')) ORDER BY ART_CODPRI

--UPDATE U_ART_PR SET ART_DESEST = 'PURO PIOPPO' WHERE ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE art_tipoG IN ('IA'))