
SELECT ART_CODCOL,ART_CODCOLRET,ART_FINI,ART_ALTEZZ,ART_LUNGHE FROM U_ART_PR, U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND U_ART_PR.ART_CODPRI = 'BG28A2B300000001'

SELECT U_ART_PR.ART_CODPRI,ART_CODCOL,ART_CODCOLRET,ART_FINI FROM U_ART_PR, U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND U_ART_PR.ART_CODPRI LIKE 'BG%' ORDER BY U_ART_PR.ART_CODPRI

SELECT ART_CODCOL,* FROM U_ART_PR
WHERE ART_CODCOL = '' AND ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI 
	AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPOG <> '' AND ART_TIPON = '')

SELECT ART_CODCOLRET, ART_FINI,* FROM U_ART_AN
WHERE ART_CODCOLRET = '' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND ART_GRUPRD <> ART_CODPRI) AND LEN(RTRIM(ART_CODPRI)) = 16  
	AND ART_TIPOG <> '' AND ART_TIPON = ''

SELECT ART_CODCOLRET, ART_FINI,* FROM U_ART_AN
WHERE ART_FINI = '' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND ART_GRUPRD <> ART_CODPRI) AND LEN(RTRIM(ART_CODPRI)) = 16  
	AND ART_TIPOG <> '' AND ART_TIPON = ''


/*

UPDATE U_ART_PR SET ART_CODCOL = '000' 
WHERE ART_CODCOL = '' AND ART_CODMAT = '008' AND LEN(RTRIM(ART_CODPRI)) = 16 AND ART_GRUPRD <> ART_CODPRI 
	AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_AN WHERE ART_TIPOG <> '' AND ART_TIPON = '')

UPDATE U_ART_AN SET ART_CODCOLRET = '000'
WHERE ART_CODCOLRET = '' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND ART_GRUPRD <> ART_CODPRI) AND LEN(RTRIM(ART_CODPRI)) = 16  
	AND ART_TIPOG <> '' AND ART_TIPON = ''

UPDATE U_ART_AN SET ART_FINI = '0'
WHERE ART_FINI = '' AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_CODMAT = '008' AND ART_GRUPRD <> ART_CODPRI) AND LEN(RTRIM(ART_CODPRI)) = 16  
	AND ART_TIPOG <> '' AND ART_TIPON = ''
*/
