
UPDATE U_CLI_AN SET CLI_CCOST1 = COALESCE((SELECT CCOSTO FROM CARD_CFVEN WHERE TIPO = 'C' AND CODCF = U_CLI_AN.CLI_CODCLI),'')

UPDATE U_FOR_AN SET FOR_CCOST1 = COALESCE((SELECT CCOSTO FROM CARD_CFVEN WHERE TIPO = 'F' AND CODCF = U_FOR_AN.FOR_CODCLI),'')