
UPDATE U_CLI_AN SET CLI_LINGUA = (
	SELECT LINGUA_AQUARIUS FROM (
		SELECT CLIENTI.CODICE, CLIENTI.RAGIONESOC, COALESCE(CLIENTI.LINGUA,'I') AS LINGUA, COALESCE(LINGUE.DESCRIZION,'') AS DESLINGUA,
			COALESCE(SUBSTRING(PARA_LNG.CODICE,4,3),'') AS LINGUA_AQUARIUS, COALESCE(PARA_LNG.DESCRI,'') AS DESLINGUA_AQUARIUS 
		FROM CARD_CLIFO AS CLIENTI
		LEFT OUTER JOIN CARD_LINGUE AS LINGUE ON LINGUE.CODICE = COALESCE(CLIENTI.LINGUA,'I')
		LEFT OUTER JOIN PARA AS PARA_LNG ON PARA_LNG.CODICE LIKE 'LNG%' AND UPPER(RTRIM(PARA_LNG.DESCRI)) = UPPER(RTRIM(LINGUE.DESCRIZION))
		WHERE CLIENTI.TIPO = 'C') AS T1
	WHERE T1.CODICE = U_CLI_AN.CLI_CODCLI)

UPDATE U_FOR_AN SET FOR_LINGUA = (
	SELECT LINGUA_AQUARIUS FROM (
		SELECT CLIENTI.CODICE, CLIENTI.RAGIONESOC, COALESCE(CLIENTI.LINGUA,'I') AS LINGUA, COALESCE(LINGUE.DESCRIZION,'') AS DESLINGUA,
			COALESCE(SUBSTRING(PARA_LNG.CODICE,4,3),'') AS LINGUA_AQUARIUS, COALESCE(PARA_LNG.DESCRI,'') AS DESLINGUA_AQUARIUS 
		FROM CARD_CLIFO AS CLIENTI
		LEFT OUTER JOIN CARD_LINGUE AS LINGUE ON LINGUE.CODICE = COALESCE(CLIENTI.LINGUA,'I')
		LEFT OUTER JOIN PARA AS PARA_LNG ON PARA_LNG.CODICE LIKE 'LNG%' AND UPPER(RTRIM(PARA_LNG.DESCRI)) = UPPER(RTRIM(LINGUE.DESCRIZION))
		WHERE CLIENTI.TIPO = 'F') AS T1
	WHERE T1.CODICE = U_FOR_AN.FOR_CODCLI)
