
--*** SETTAGGIO ARTICOLI DA NON MOVIMENTARE

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE '.%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE '.%' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI = 'W01STAND' OR ART_CODPRI = 'W12STAND'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI = 'W01STAND' OR ART_CODPRI = 'W12STAND' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE 'WXY%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE 'WXY%' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE '667%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE '667%' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_DESCR LIKE 'MANUALE%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_DESCR LIKE 'MANUALE%' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE '270%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE '270%' ORDER BY ART_CODPRI

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI = '16002210'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI = '16002210'

UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE 'INTR%'
SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE 'INTR%' ORDER BY ART_CODPRI

--UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_DESCR LIKE 'ETIC%'
--SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_DESCR LIKE 'ETIC%' ORDER BY ART_CODPRI

--UPDATE U_ART_PR SET ART_NONMOV = 1 WHERE ART_CODPRI LIKE '9%'
--SELECT ART_NONMOV,* FROM U_ART_PR WHERE ART_CODPRI LIKE '9%' ORDER BY ART_CODPRI


