
/*
SETTAGGIO TIPOLOGIA DOCUMENTO DI DEFAULT CHE VIENE PREVALORIZZATA IN BASE ALLA CAUSALE IN INSERIMENTO ORDINI CLIENTI
*/

UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'U30   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOE'	-- Campagna Under 30
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'U.P   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPO3'	-- Campagna Usato Plu
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'MAT   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOM'	-- Ordine Materiali
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'NOL   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPON'	-- Noleggio
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'OPZ   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOP'	-- Ordine Opzioni
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'SER   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOS'	-- Ordine Service
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'H2E   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPO1'	-- Campagna H2E
UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'PHA   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOH'	-- Campagna Pharma

UPDATE PARA SET LIBERA = SUBSTRING(LIBERA,1,68)+'MAT   '+SUBSTRING(LIBERA,75,200) WHERE CODICE = 'TOPOC'	-- Ordine Cliente