
UPDATE FORMCONF SET propvalue = 'Cod.Valore(Fat.Elettr) / RDM' where NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH = 'PAGEFRAME1.PAGE12.LABEL4' AND PROPNAME = 'CAPTION'


DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.LBLALTRO'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','LBLALTRO','PAGEFRAME1.PAGE4.LBLALTRO','Altro','Label','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.LBLART_CDISBN'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','LBLART_CDISBN','PAGEFRAME1.PAGE4.LBLART_CDISBN','UDI di base','Label','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.LBLART_GRUPRD'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','LBLART_GRUPRD','PAGEFRAME1.PAGE4.LBLART_GRUPRD','CND','Label','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.SHPALTRO'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','SHPALTRO','PAGEFRAME1.PAGE4.SHPALTRO','','Shape','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.TXTART_CDISBN'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','TXTART_CDISBN','PAGEFRAME1.PAGE4.TXTART_CDISBN','','Textbox','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.TXTART_GRUPRD'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','TXTART_GRUPRD','PAGEFRAME1.PAGE4.TXTART_GRUPRD','','Textbox','VISIBLE','.T.','L')

DELETE FROM FORMCONF WHERE NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4.TXTSAY_GRUPRD'
INSERT INTO FORMCONF (IDFORMCONF,NOMECONF,SRCFILENAME,FORMNAME,OBJNAME,OBJPATH,OBJCAPT,OBJTYPE,PROPNAME,PROPVALUE,PROPTYPE) VALUES (
	'_43R0NTPTB','Configurazione del 30/06/2014 ore 11:06:57','\FORM\MENU_ART000.SCT','Form1','TXTSAY_GRUPRD','PAGEFRAME1.PAGE4.TXTSAY_GRUPRD','','Textbox','VISIBLE','.T.','L')


select * from FORMCONF where NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH = 'PAGEFRAME1.PAGE12.LABEL4' AND PROPNAME = 'CAPTION'
select * from FORMCONF where NOMECONF = 'Configurazione del 30/06/2014 ore 11:06:57' AND SRCFILENAME = '\FORM\MENU_ART000.SCT' and OBJPATH LIKE 'PAGEFRAME1.PAGE4%' ORDER BY OBJNAME