
-- AGGIORNAMENTO PROVINCIA IN LOCALITA' DI CONSEGNA

-- DIFFERENZE (PRIMA)
SELECT * FROM U_LOC_AN WHERE LOC_LOCALI <> '' AND LOC_LOCALI IN (SELECT COMUNE FROM COMUNI) AND LOC_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = LOC_LOCALI)
ORDER BY LOC_LOCALI

UPDATE U_LOC_AN SET LOC_PROVIN = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = LOC_LOCALI) WHERE LOC_LOCALI <> '' AND LOC_LOCALI IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_LOC_AN WHERE LOC_LOCALI <> '' AND LOC_LOCALI IN (SELECT COMUNE FROM COMUNI) AND LOC_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = LOC_LOCALI)
ORDER BY LOC_LOCALI



-- AGGIORNAMENTO PROVINCIA IN ANAGRAFICA CLIENTI

-- DIFFERENZE (PRIMA)
SELECT * FROM U_CLI_AN WHERE CLI_LOCALI <> '' AND CLI_LOCALI IN (SELECT COMUNE FROM COMUNI) AND CLI_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALI)
ORDER BY CLI_LOCALI

UPDATE U_CLI_AN SET CLI_PROVIN = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALI) WHERE CLI_LOCALI <> '' AND CLI_LOCALI IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_CLI_AN WHERE CLI_LOCALI <> '' AND CLI_LOCALI IN (SELECT COMUNE FROM COMUNI) AND CLI_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALI)
ORDER BY CLI_LOCALI


-- DIFFERENZE (PRIMA)
SELECT * FROM U_CLI_AN WHERE CLI_LOCLEG <> '' AND CLI_LOCLEG IN (SELECT COMUNE FROM COMUNI) AND CLI_PROLEG <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCLEG)
ORDER BY CLI_LOCLEG

UPDATE U_CLI_AN SET CLI_PROLEG = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCLEG) WHERE CLI_LOCLEG <> '' AND CLI_LOCLEG IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_CLI_AN WHERE CLI_LOCLEG <> '' AND CLI_LOCLEG IN (SELECT COMUNE FROM COMUNI) AND CLI_PROLEG <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCLEG)
ORDER BY CLI_LOCLEG


-- DIFFERENZE (PRIMA)
SELECT * FROM U_CLI_AN WHERE CLI_LOCALIA <> '' AND CLI_LOCALIA IN (SELECT COMUNE FROM COMUNI) AND CLI_PROVINA <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALIA)
ORDER BY CLI_LOCALIA

UPDATE U_CLI_AN SET CLI_PROVINA = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALIA) WHERE CLI_LOCALIA <> '' AND CLI_LOCALIA IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_CLI_AN WHERE CLI_LOCALIA <> '' AND CLI_LOCALIA IN (SELECT COMUNE FROM COMUNI) AND CLI_PROVINA <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = CLI_LOCALIA)
ORDER BY CLI_LOCALIA




-- AGGIORNAMENTO PROVINCIA IN ANAGRAFICA FORNITORI

-- DIFFERENZE (PRIMA)
SELECT * FROM U_FOR_AN WHERE FOR_LOCALI <> '' AND FOR_LOCALI IN (SELECT COMUNE FROM COMUNI) AND FOR_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCALI)
ORDER BY FOR_LOCALI

UPDATE U_FOR_AN SET FOR_PROVIN = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCALI) WHERE FOR_LOCALI <> '' AND FOR_LOCALI IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_FOR_AN WHERE FOR_LOCALI <> '' AND FOR_LOCALI IN (SELECT COMUNE FROM COMUNI) AND FOR_PROVIN <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCALI)
ORDER BY FOR_LOCALI


-- DIFFERENZE (PRIMA)
SELECT * FROM U_FOR_AN WHERE FOR_LOCLEG <> '' AND FOR_LOCLEG IN (SELECT COMUNE FROM COMUNI) AND FOR_PROLEG <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCLEG)
ORDER BY FOR_LOCLEG

UPDATE U_FOR_AN SET FOR_PROLEG = (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCLEG) WHERE FOR_LOCLEG <> '' AND FOR_LOCLEG IN (SELECT COMUNE FROM COMUNI)

-- DIFFERENZE (DOPO)
SELECT * FROM U_FOR_AN WHERE FOR_LOCLEG <> '' AND FOR_LOCLEG IN (SELECT COMUNE FROM COMUNI) AND FOR_PROLEG <> (SELECT PROVINCIA FROM COMUNI WHERE COMUNE = FOR_LOCLEG)
ORDER BY FOR_LOCLEG