
DECLARE @stringa_chiave varchar(20)
SET @stringa_chiave = 'CONTO_COSTO: '

DECLARE @delimitarore varchar(1)
SET @delimitarore = ';'

UPDATE U_ART_AN SET ART_CGEACQ = (
	SELECT 
		CASE 
			WHEN CHR_INI > 0 
				THEN SUBSTRING(LIBERA,CHR_INI,
					CASE 
						WHEN (CHARINDEX(@delimitarore,SUBSTRING(LIBERA,CHR_INI,LEN(LIBERA)))-1) > 0
							THEN CHARINDEX(@delimitarore,SUBSTRING(LIBERA,CHR_INI,LEN(LIBERA)))-1
						ELSE LEN(LIBERA)
					END)
			ELSE ''
		END AS SOTTOSTRINGA_LIBERA
	FROM (
		SELECT AN.ART_CODPRI,AN.ART_CODGMI,COALESCE(PARA.DESCRI,'') AS DESCRI,COALESCE(PARA.LIBERA,'') AS LIBERA,
		CASE 
			WHEN CHARINDEX(@stringa_chiave,COALESCE(PARA.LIBERA,'')) > 0 
				THEN CHARINDEX(@stringa_chiave,COALESCE(PARA.LIBERA,'')) + LEN(@stringa_chiave) + 1
			ELSE 0
		END AS CHR_INI
		FROM U_ART_AN AS AN
		LEFT OUTER JOIN PARA ON PARA.CODICE LIKE 'GMI%' AND PARA.CODICE = 'GMI'+AN.ART_CODGMI
		) AS T1
	WHERE ART_CODPRI = U_ART_AN.ART_CODPRI)


SELECT ART_CODPRI, ART_CODGMI, ART_CGEACQ FROM U_ART_AN ORDER BY ART_CODPRI