--SELECT * FROM PARA WHERE CODICE LIKE 'STA%' and LIBERA<>''


SELECT 
	CLI_CODCLI AS CODCIE,
	CLI_RAGSOC AS RAGSOC,
	CLI_NAZION AS NAZIONE,
	SUBSTRING(PARA.LIBERA,1,2) AS NAZIONE_ISO,
	CLI_PARIVA AS PIVA_ATTUALE,
	CLI_CODFIS AS CODFIS_ATTUALE,
	CLI_IVACEE AS PIVACEE_ATTUALE,
	CASE WHEN CLI_NAZION='ITA' THEN CLI_PARIVA
		ELSE '' END AS PIVA_CORRETTA,
	CASE WHEN CLI_NAZION='ITA' THEN CLI_CODFIS
		ELSE '' END AS CODFIS_CORRETTO,
	CASE WHEN CLI_NAZION='ITA' THEN ''
		WHEN CLI_NAZION<>'ITA' AND PARA.LIBERA='' THEN ''
		WHEN CLI_NAZION<>'ITA' AND PARA.LIBERA<>'' AND CLI_IVACEE='' THEN ''
		ELSE 
			CASE WHEN SUBSTRING(CLI_IVACEE,1,2)=SUBSTRING(CLI_NAZION,1,2) THEN SUBSTRING(PARA.LIBERA,1,2)+SUBSTRING(CLI_IVACEE,4,16)
			ELSE SUBSTRING(PARA.LIBERA,1,2)+CLI_IVACEE END
		END AS PIVACEE_CORRETTO
FROM U_CLI_AN AS FORN
LEFT OUTER JOIN PARA 
ON 'STA'+CLI_NAZION=PARA.CODICE
ORDER BY CLI_NAZION, CLI_RAGSOC

