
-- INSERIMENTO PARAMETRO MAGAZZINO DEDICATO PER E-COMMERCE

DELETE FROM PARA WHERE CODICE = 'MAGECOM'
INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	VALUES ('MAGECOM', 'MAGAZZINO E-COMMERCE', 'S')

--SELECT * FROM PARA WHERE CODICE LIKE 'MAG%'

UPDATE U_AZI_PC SET AZI_ECMAGA = 'ECOM'