/******************************************************************************
 INSERIMENTO PARAMETRI
	- MODELLI DICHIARAZIONE DI CONFORMITÀ PER ACCETTAZIONE
	- MODELLI DICHIARAZIONE DI CONFORMITÀ PER PRODUZIONE
*******************************************************************************/

DELETE FROM PARA WHERE CODICE LIKE 'MDCA%'
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCA01','DICH_I con funz. di misura','DICH_CONF_ACQ_01.FRX','','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCA02','DICH_I senza CE','DICH_CONF_ACQ_02.FRX','','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCA03','DICH_IIA','DICH_CONF_ACQ_03.FRX','','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCA04','DICH_IIB','DICH_CONF_ACQ_04.FRX','','')

DELETE FROM PARA WHERE CODICE LIKE 'MDCP%'
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCP01','DICH_I senza CE','DICH_CONF_PRD_01.FRX','','')
INSERT INTO PARA (CODICE, DESCRI, LIBERA, CODPGO, DESIVA) VALUES ('MDCP02','DICH_IIA','DICH_CONF_PRD_02.FRX','','')

SELECT * FROM PARA WHERE CODICE LIKE 'MDCA%'
SELECT * FROM PARA WHERE CODICE LIKE 'MDCP%'