
-- CESSIONI (FATTURE CLIENTI)

SELECT 
	MOV.MOV_NUMPRO,
	MOV.MOV_QTA_INTRA,
	MOV.MOV_UNITA_SUPPL_INTRA,
	MOV.MOV_NUMPRO,
	CASE MOV.MOV_SERV_INTRA WHEN '' THEN CEILING(COALESCE(PF.PESO_NETTO_ARTICOLI,0)) ELSE 0 END AS NEW_PESO_INTRA, PF.PESO_NETTO_ARTICOLI,
	MOV.MOV_PESO,
	PF.ORD_QTATOT,
	PF.ORD_CONDET,
	MOV.MOV_CONTO,
	PF.ORD_CCODET,
	MOV.MOV_CCO,
	PF.ORD_CLDOG,
	MOV.MOV_CLDOG,
	PF.ORD_SERV_INTRA,
	MOV.MOV_SERV_INTRA,
	FT.ORD_RAGSOC, 
	FT.ORD_NUMORD, 
	FT.ORD_DATORD, 
	MOV.MOV_DESMOV, MOV.*
FROM MOV_CONT AS MOV
LEFT OUTER JOIN PARA AS PARA1 ON 'TOP'+MOV.MOV_TOP = PARA1.CODICE
LEFT OUTER JOIN PARA AS PARA2 ON 'IVA'+MOV.MOV_IVA = PARA2.CODICE
LEFT OUTER JOIN PARA AS PARA3 ON 'CPA'+MOV.MOV_MODPAG = PARA3.CODICE
LEFT OUTER JOIN CONTI AS CONTI ON MOV.MOV_CONTO = CONTI.CON_CONTO AND CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_TIPOCO='X'
LEFT OUTER JOIN PART_CLI AS PC ON PC.PAR_NUMPRO = MOV.MOV_NUMPRO AND PAR_NPROG = '100'
LEFT OUTER JOIN U_FAT_TT AS FT ON FT.ORD_NUMORD = PC.PAR_NPROT AND FT.ORD_DATORD = PC.PAR_DTFAT AND FT.ORD_NPROT = PC.PAR_NPART
LEFT OUTER JOIN (SELECT DAGGANCIO, ORD_CONDET, ORD_CCODET, ORD_CLDOG, ORD_SERV_INTRA, SUM(ART_PESOUM * ORD_QTAORD) AS PESO_NETTO_ARTICOLI, SUM(ORD_QTAORD) AS ORD_QTATOT FROM (
					SELECT PR.ART_PESOUM, FD.* FROM U_FAT_DD AS FD
					LEFT OUTER JOIN U_ART_PR AS PR ON FD.ORD_CODART = PR.ART_CODPRI
					WHERE
						FD.ORD_DESART <> '*** COMMENTO ***'
					) AS MAIN
				GROUP BY DAGGANCIO, ORD_CONDET, ORD_CCODET, ORD_CLDOG, ORD_SERV_INTRA 
	) AS PF ON PF.DAGGANCIO = FT.TAGGANCIO AND PF.ORD_CONDET = MOV.MOV_CONTO AND PF.ORD_CCODET = MOV.MOV_CCO AND PF.ORD_CLDOG = MOV.MOV_CLDOG AND PF.ORD_SERV_INTRA = MOV.MOV_SERV_INTRA
WHERE 
	--MOV_NUMPRO = '_4A9110Y5K' AND 
	MOV_DTREG BETWEEN '2015/01/01' AND '2015/05/31'
	AND MOV_TOP <> 'CHI'
	AND MOV_CONTABILITA_PREVISIONALE<>'P'
	AND SUBSTRING(PARA1.LIBERA,24,1)='S'
	AND SUBSTRING(PARA1.LIBERA,12,1)='C'  -- CLIENTE/FORNITORE
	AND SUBSTRING(PARA1.LIBERA,2,1)='S'
	AND SUBSTRING(PARA1.LIBERA,23,1)='E'
	AND SUBSTRING(PARA1.LIBERA,11,1)<>'S'
	AND CONTI.CON_TIPOCO='X'
	AND (SUBSTRING(PARA2.ITALIANO,1,100) = 'BENI-INTRASTAT' OR SUBSTRING(PARA2.ITALIANO,1,100) = 'SERVIZI-INTRASTAT')
ORDER BY MOV_NREGIS



with MOV_CONT_PESI_ARTICOLI AS (
	SELECT 
		CASE MOV.MOV_SERV_INTRA WHEN '' THEN CEILING(COALESCE(PF.PESO_NETTO_ARTICOLI,0)) ELSE 0 END AS NEW_PESO_INTRA,
		MOV.*
	FROM MOV_CONT AS MOV
	LEFT OUTER JOIN PARA AS PARA1 ON 'TOP'+MOV.MOV_TOP = PARA1.CODICE
	LEFT OUTER JOIN PARA AS PARA2 ON 'IVA'+MOV.MOV_IVA = PARA2.CODICE
	LEFT OUTER JOIN PARA AS PARA3 ON 'CPA'+MOV.MOV_MODPAG = PARA3.CODICE
	LEFT OUTER JOIN CONTI AS CONTI ON MOV.MOV_CONTO = CONTI.CON_CONTO AND CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_TIPOCO='X'
	LEFT OUTER JOIN PART_CLI AS PC ON PC.PAR_NUMPRO = MOV.MOV_NUMPRO AND PAR_NPROG = '100'
	LEFT OUTER JOIN U_FAT_TT AS FT ON FT.ORD_NUMORD = PC.PAR_NPROT AND FT.ORD_DATORD = PC.PAR_DTFAT AND FT.ORD_NPROT = PC.PAR_NPART
	LEFT OUTER JOIN (SELECT DAGGANCIO, ORD_CONDET, ORD_CCODET, ORD_CLDOG, ORD_SERV_INTRA, SUM(ART_PESOUM * ORD_QTAORD) AS PESO_NETTO_ARTICOLI, SUM(ORD_QTAORD) AS ORD_QTATOT FROM (
						SELECT PR.ART_PESOUM, FD.* FROM U_FAT_DD AS FD
						LEFT OUTER JOIN U_ART_PR AS PR ON FD.ORD_CODART = PR.ART_CODPRI
						WHERE
							FD.ORD_DESART <> '*** COMMENTO ***'
						) AS MAIN
					GROUP BY DAGGANCIO, ORD_CONDET, ORD_CCODET, ORD_CLDOG, ORD_SERV_INTRA 
		) AS PF ON PF.DAGGANCIO = FT.TAGGANCIO AND PF.ORD_CONDET = MOV.MOV_CONTO AND PF.ORD_CCODET = MOV.MOV_CCO AND PF.ORD_CLDOG = MOV.MOV_CLDOG AND PF.ORD_SERV_INTRA = MOV.MOV_SERV_INTRA
	WHERE MOV_TOP <> 'CHI'
		AND MOV_CONTABILITA_PREVISIONALE<>'P'
		AND SUBSTRING(PARA1.LIBERA,24,1)='S'
		AND SUBSTRING(PARA1.LIBERA,12,1)='C'  -- CLIENTE/FORNITORE
		AND SUBSTRING(PARA1.LIBERA,2,1)='S'
		AND SUBSTRING(PARA1.LIBERA,23,1)='E'
		AND SUBSTRING(PARA1.LIBERA,11,1)<>'S'
		AND CONTI.CON_TIPOCO='X'
		AND (SUBSTRING(PARA2.ITALIANO,1,100) = 'BENI-INTRASTAT' OR SUBSTRING(PARA2.ITALIANO,1,100) = 'SERVIZI-INTRASTAT')
)

UPDATE MOV_CONT SET MOV_PESO = (SELECT NEW_PESO_INTRA FROM MOV_CONT_PESI_ARTICOLI WHERE ID_UNIQUE = MOV_CONT.ID_UNIQUE)
WHERE MOV_NUMPRO = '_4A9110Y5K' AND MOV_DTREG BETWEEN '2015/01/01' AND '2015/03/31'
AND ID_UNIQUE IN (SELECT ID_UNIQUE FROM MOV_CONT_PESI_ARTICOLI WHERE MOV_NUMPRO = MOV_CONT.MOV_NUMPRO)





-- ACQUISTI (FATTURE FORNITORI)

SELECT
	MOV.MOV_NUMPRO,
	CASE MOV.MOV_SERV_INTRA WHEN '' THEN CEILING(COALESCE(PF.PESO_NETTO_ARTICOLI,0)) ELSE 0 END AS NEW_PESO_INTRA, PF.PESO_NETTO_ARTICOLI,
	MOV.MOV_PESO,

	PF.ORD_QTATOT,

	BE.LEG_AGGANC,
	BE.LEG_NUMPRN,
	BE.LEG_DESCRI, 
	BE.LEG_NUMDOC, 
	BE.LEG_DATDOC, 

	PF.ORD_CONDET,
	MOV.MOV_CONTO,
	PF.ORD_CCODET,
	MOV.MOV_CCO,
	PF.ART_CLDOG,
	MOV.MOV_CLDOG,
	PF.ART_SERVINTRA,
	MOV.MOV_SERV_INTRA,
	MOV.MOV_DESMOV, MOV.*
FROM MOV_CONT AS MOV
LEFT OUTER JOIN PARA AS PARA1 ON 'TOP'+MOV.MOV_TOP = PARA1.CODICE
LEFT OUTER JOIN PARA AS PARA2 ON 'IVA'+MOV.MOV_IVA = PARA2.CODICE
LEFT OUTER JOIN PARA AS PARA3 ON 'CPA'+MOV.MOV_MODPAG = PARA3.CODICE
LEFT OUTER JOIN CONTI AS CONTI ON MOV.MOV_CONTO = CONTI.CON_CONTO AND CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_TIPOCO='X'
LEFT OUTER JOIN (SELECT * FROM U_BFO_LE) AS BE ON BE.LEG_NUMPRO = MOV.MOV_NUMPRO AND BE.LEG_AGGANC <> '' AND BE.LEG_NUMPRN <> ''
LEFT OUTER JOIN (SELECT ord_valore, DAGGANCIO, cbf_ndoc, ORD_CONDET, ORD_CCODET, art_cldog, art_servintra, SUM(ART_PESOUM * ORD_QTAORD) AS PESO_NETTO_ARTICOLI, SUM(ORD_QTAORD) AS ORD_QTATOT FROM (

					SELECT PR.ART_PESOUM, PR.art_cldog, AN.art_servintra, BD.* FROM U_BFO_DD AS BD
					LEFT OUTER JOIN U_ART_PR AS PR ON BD.ORD_CODART = PR.ART_CODPRI
					LEFT OUTER JOIN U_ART_AN AS AN ON BD.ORD_CODART = AN.ART_CODPRI
					WHERE
						BD.ORD_DESART <> '*** COMMENTO ***'
					) AS MAIN
				GROUP BY ord_valore, DAGGANCIO, cbf_ndoc, ORD_CONDET, ORD_CCODET, art_cldog, art_servintra 
	) AS PF ON PF.DAGGANCIO = BE.LEG_AGGANC AND PF.cbf_ndoc = BE.LEG_NUMPRN AND PF.ORD_VALORE = MOV.MOV_IMP and PF.ORD_CONDET = MOV.MOV_CONTO AND PF.ORD_CCODET = MOV.MOV_CCO AND PF.art_cldog = MOV.MOV_CLDOG AND PF.art_servintra = MOV.MOV_SERV_INTRA
WHERE 
	--MOV_NUMPRO = '_4A9110Y5K' AND 
	MOV_DTREG BETWEEN '2015/05/01' AND '2015/05/31'
	AND MOV_TOP <> 'CHI'
	AND MOV_CONTABILITA_PREVISIONALE<>'P'
	AND SUBSTRING(PARA1.LIBERA,24,1)='S'
	AND SUBSTRING(PARA1.LIBERA,12,1)='F'  -- CLIENTE/FORNITORE
	AND SUBSTRING(PARA1.LIBERA,2,1)='S'
	AND SUBSTRING(PARA1.LIBERA,23,1)='E'
	AND SUBSTRING(PARA1.LIBERA,11,1)<>'S'
	AND CONTI.CON_TIPOCO='X'
	AND (SUBSTRING(PARA2.ITALIANO,1,100) = 'BENI-INTRASTAT' OR SUBSTRING(PARA2.ITALIANO,1,100) = 'SERVIZI-INTRASTAT')
ORDER BY MOV_NREGIS


with MOV_CONT_PESI_ARTICOLI_CESSIONI AS (
	SELECT 
		CASE MOV.MOV_SERV_INTRA WHEN '' THEN CEILING(COALESCE(PF.PESO_NETTO_ARTICOLI,0)) ELSE 0 END AS NEW_PESO_INTRA, PF.PESO_NETTO_ARTICOLI,
		MOV.*
	FROM MOV_CONT AS MOV
	LEFT OUTER JOIN PARA AS PARA1 ON 'TOP'+MOV.MOV_TOP = PARA1.CODICE
	LEFT OUTER JOIN PARA AS PARA2 ON 'IVA'+MOV.MOV_IVA = PARA2.CODICE
	LEFT OUTER JOIN PARA AS PARA3 ON 'CPA'+MOV.MOV_MODPAG = PARA3.CODICE
	LEFT OUTER JOIN CONTI AS CONTI ON MOV.MOV_CONTO = CONTI.CON_CONTO AND CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_TIPOCO='X'
	LEFT OUTER JOIN (SELECT * FROM U_BFO_LE) AS BE ON BE.LEG_NUMPRO = MOV.MOV_NUMPRO AND BE.LEG_AGGANC <> '' AND BE.LEG_NUMPRN <> ''
	LEFT OUTER JOIN (SELECT ord_valore, DAGGANCIO, cbf_ndoc, ORD_CONDET, ORD_CCODET, art_cldog, art_servintra, SUM(ART_PESOUM * ORD_QTAORD) AS PESO_NETTO_ARTICOLI, SUM(ORD_QTAORD) AS ORD_QTATOT FROM (

						SELECT PR.ART_PESOUM, PR.art_cldog, AN.art_servintra, BD.* FROM U_BFO_DD AS BD
						LEFT OUTER JOIN U_ART_PR AS PR ON BD.ORD_CODART = PR.ART_CODPRI
						LEFT OUTER JOIN U_ART_AN AS AN ON BD.ORD_CODART = AN.ART_CODPRI
						WHERE
							BD.ORD_DESART <> '*** COMMENTO ***'
						) AS MAIN
					GROUP BY ord_valore, DAGGANCIO, cbf_ndoc, ORD_CONDET, ORD_CCODET, art_cldog, art_servintra 
		) AS PF ON PF.DAGGANCIO = BE.LEG_AGGANC AND PF.cbf_ndoc = BE.LEG_NUMPRN AND PF.ORD_VALORE = MOV.MOV_IMP and PF.ORD_CONDET = MOV.MOV_CONTO AND PF.ORD_CCODET = MOV.MOV_CCO AND PF.art_cldog = MOV.MOV_CLDOG AND PF.art_servintra = MOV.MOV_SERV_INTRA
	WHERE 
		MOV_DTREG BETWEEN '2015/01/01' AND '2015/05/31'
		AND MOV_TOP <> 'CHI'
		AND MOV_CONTABILITA_PREVISIONALE<>'P'
		AND SUBSTRING(PARA1.LIBERA,24,1)='S'
		AND SUBSTRING(PARA1.LIBERA,12,1)='F'  -- CLIENTE/FORNITORE
		AND SUBSTRING(PARA1.LIBERA,2,1)='S'
		AND SUBSTRING(PARA1.LIBERA,23,1)='E'
		AND SUBSTRING(PARA1.LIBERA,11,1)<>'S'
		AND CONTI.CON_TIPOCO='X'
		AND (SUBSTRING(PARA2.ITALIANO,1,100) = 'BENI-INTRASTAT' OR SUBSTRING(PARA2.ITALIANO,1,100) = 'SERVIZI-INTRASTAT')
)

UPDATE MOV_CONT SET MOV_PESO = (SELECT NEW_PESO_INTRA FROM MOV_CONT_PESI_ARTICOLI_CESSIONI WHERE ID_UNIQUE = MOV_CONT.ID_UNIQUE)
WHERE MOV_NUMPRO = '_4CG12M8YD' AND MOV_DTREG BETWEEN '2015/05/01' AND '2015/05/31'
AND ID_UNIQUE IN (SELECT ID_UNIQUE FROM MOV_CONT_PESI_ARTICOLI_CESSIONI WHERE MOV_NUMPRO = MOV_CONT.MOV_NUMPRO)