
-- INSERIMENTO CAUSALI DEDICATE PER RIENTRO DA CONTO VISIONE
DELETE FROM PARA WHERE CODICE = 'TOPRV-'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPRV-','SCARICO PER RIENTRO VISIONE','SN      N                         RV+    M')
DELETE FROM PARA WHERE CODICE = 'TOPRV+'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('TOPRV+','CARICO PER RIENTRO VISIONE','SN      N                         RV-    M')

-- INSERIMENTO CAUSALI GUIDATE PER SPOSTAMENTI CON RIENTRO DA CONTO VISIONE
DELETE FROM U_TOP_MO WHERE TOP_MAGSCA = 'VIS'
INSERT INTO U_TOP_MO (TOP_MAGSCA,TOP_MAGCAR,TOP_CAUSCA,TOP_CAUCAR,TOP_ATTIVO) VALUES ('VIS','MPF','RV-','RV+',1)
INSERT INTO U_TOP_MO (TOP_MAGSCA,TOP_MAGCAR,TOP_CAUSCA,TOP_CAUCAR,TOP_ATTIVO) VALUES ('VIS','SEDE','RV-','RV+',1)