
UPDATE U_ORF_DD SET ORD_DATCON = DBO.ribalta2(ORD_DATCON) WHERE ORD_CODART <> '' AND SUBSTRING(ORD_DATCON,3,1) = '/'
UPDATE U_ORF_DD SET ORS_DATORD = DBO.ribalta2(ORS_DATORD) WHERE SUBSTRING(ORS_DATORD,3,1) = '/'

UPDATE U_ORF_DD SET ORD_CONFER = 
	CASE
		WHEN DATEADD(day, (DATEDIFF(DAY, CAST(ORS_DATORD AS DATE), CAST(ORD_DATCON AS DATE)) / 2), CAST(ORS_DATORD AS DATE)) > CAST(GETDATE() AS DATE) THEN CONVERT(VARCHAR, CAST(GETDATE() AS DATE), 111)
		ELSE CONVERT(VARCHAR, DATEADD(day, (DATEDIFF(DAY, CAST(ORS_DATORD AS DATE), CAST(ORD_DATCON AS DATE)) / 2), CAST(ORS_DATORD AS DATE)), 111)
	END	
WHERE ORD_CONFER = '' AND ORD_CODART <> '' AND ORD_CHIUSO = 0


SELECT
	DD.ORD_CONFER AS DATA_ULTIMO_CONTATTO,
	CONVERT(VARCHAR, DATEADD(day, (DATEDIFF(DAY, CAST(ORS_DATORD AS DATE), CAST(ORD_DATCON AS DATE)) / 2), CAST(ORS_DATORD AS DATE)), 111) AS DATA_META_SCADENZA,
	TT.ORD_CODCLI AS CODICE_FORNITORE,
	TT.ORD_RAGSOC AS FORNITORE,
	TT.ORD_NUMORD AS NUM_ORDINE,
	TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
	DD.ORD_CCODET AS CENTRO_COSTO,
	DD.ORD_CODART AS CODICE_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
	DD.ORD_DATCON AS DATA_CONSEGNA_RIBALTATA,
	SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
	DD.ORD_CONFER AS DATA_ULTIMO_CONTATTO_FORN,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA_ORDINATA,
	DD.ORD_QTAEV AS QTA_EVASA,
	TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
	CASE TT.ORD_FLGCON WHEN 1 THEN 'SI' ELSE 'NO' END AS CONFERMATO
FROM U_ORF_TT AS TT
LEFT OUTER JOIN U_ORF_DD AS DD
ON TT.TAGGANCIO=DD.DAGGANCIO
WHERE 
	DD.ORD_QTAORD>0
	AND DD.ORD_CHIUSO=0 
	AND TT.ORD_CHIUSO=0
ORDER BY DD.ORD_DATCON,TT.ORD_NUMORD