
--SELECT * FROM U_RIF_CF where CAST(rif_CODCLI AS NUMERIC(10,0)) <> 0 ORDER BY RIF_CODICE
--SELECT * FROM U_RIF_CF where CAST(rif_CODCLI AS NUMERIC(10,0)) = 0 ORDER BY RIF_CODICE

DELETE FROM U_RIF_CF WHERE CAST(rif_CODCLI AS NUMERIC(10,0)) = 0
DELETE FROM U_RIF_CF WHERE SUBSTRING(RIF_CODICE,1,1) = 'S'

INSERT INTO U_RIF_CF (
	RIF_CODCLI,
	RIF_CLIFOR,
	RIF_CODICE,
	RIF_COGNOM,
	RIF_NOME,
	RIF_FUNAZI,
	RIF_LOCUFF,
	RIF_INDUFF,
	RIF_CAPUFF,
	RIF_TELUFF,
	RIF_TELMOB,
	RIF_FAX,
	RIF_EMAIL,
	RIF_NOTE)
SELECT
	CODCF AS RIF_CODCLI,
	TIPOCF AS RIF_CLIFOR,
	'S' + REPLICATE('0',8-LEN(CAST(ROW_NUMBER() OVER (ORDER BY TIPOCF,CODCF,CAST(CODICE AS NUMERIC(10,0))) AS VARCHAR(10)))) + (CAST(ROW_NUMBER() OVER (ORDER BY TIPOCF,CODCF,CAST(CODICE AS NUMERIC(10,0))) AS VARCHAR(10))) AS RIF_CODICE,
	COALESCE(NOMINATIVO,'') AS RIF_COGNOM,
	'' AS RIF_NOME,
	COALESCE((SELECT TOP 1 RTRIM(DESCRI) FROM PARA WHERE CODICE = 'FUN'+MANSIONE),'') AS RIF_FUNAZI,
	COALESCE((SELECT TOP 1 LOCALITA FROM CARD_INDSPED WHERE TIPO = CARD_TABRIAZ.TIPOCF AND CODCF = CARD_TABRIAZ.CODCF AND CODIND = CARD_TABRIAZ.CODIND),'') AS RIF_LOCUFF,
	COALESCE((SELECT TOP 1 INDIR FROM CARD_INDSPED WHERE TIPO = CARD_TABRIAZ.TIPOCF AND CODCF = CARD_TABRIAZ.CODCF AND CODIND = CARD_TABRIAZ.CODIND),'') AS RIF_INDUFF,
	COALESCE((SELECT TOP 1 CAP FROM CARD_INDSPED WHERE TIPO = CARD_TABRIAZ.TIPOCF AND CODCF = CARD_TABRIAZ.CODCF AND CODIND = CARD_TABRIAZ.CODIND),'') AS RIF_CAPUFF,
	LTRIM(RTRIM(COALESCE(PTEL,'')+' '+COALESCE(TEL,''))) AS RIF_TELUFF,
	COALESCE(TELEX,'') AS RIF_TELMOB,
	LTRIM(RTRIM(COALESCE(PFAX,'')+' '+COALESCE(FAX,''))) AS RIF_FAX,
	COALESCE(E_MAILL,'') AS RIF_EMAIL,
	COALESCE(INTERNETL,'') AS RIF_NOTE
FROM CARD_TABRIAZ

SELECT * FROM U_RIF_CF WHERE SUBSTRING(RIF_CODICE,1,1) = 'S'
