
--SELECT CLI_CODCLI,CLI_TELEX FROM U_CLI_AN WHERE CLI_TELEX <> ''
--SELECT FOR_CODCLI,FOR_TELEX FROM U_FOR_AN WHERE FOR_TELEX <> ''

UPDATE U_CLI_AN SET CLI_TELEX = COALESCE((SELECT TELEX FROM CARD_CFVEN WHERE TIPO = 'C' AND CODCF = U_CLI_AN.CLI_CODCLI),'') WHERE CLI_TELEX = ''

UPDATE U_FOR_AN SET FOR_TELEX = COALESCE((SELECT TELEX FROM CARD_CFVEN WHERE TIPO = 'F' AND CODCF = U_FOR_AN.FOR_CODCLI),'') WHERE FOR_TELEX = ''

SELECT AC.CLI_TELEX,AF.FOR_TELEX,TELEX,CF.* FROM CARD_CFVEN AS CF
LEFT OUTER JOIN U_CLI_AN AS AC ON CF.CODCF = AC.CLI_CODCLI
LEFT OUTER JOIN U_FOR_AN AS AF ON CF.CODCF = AF.FOR_CODCLI
WHERE COALESCE(TELEX,'') <> ''
ORDER BY CF.TIPO,CF.CODCF
