
DELETE FROM PJTIPREP WHERE NOMEPROC = 'OFFPJEUR_PERS'
DELETE FROM PJTIPREP WHERE NOMEPROC = 'ORDPJEUR_PERS'
DELETE FROM PJTIPREP WHERE NOMEPROC = 'ORFPJEUR_PERS'
DELETE FROM PJTIPREP WHERE NOMEPROC = 'BOLPJITA_PERS'
DELETE FROM PJTIPREP WHERE NOMEPROC = 'FAPPJEUR_PERS'
DELETE FROM PJTIPREP WHERE NOMEPROC = 'FATPJEUR_PERS'

INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('OFFPJEUR_PERS','REPORT PERSONALIZZABILE PER OFFERTE CLIENTI','OFFPJCARD_PERS.FRX','')
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('ORDPJEUR_PERS','REPORT PERSONALIZZABILE PER ORDINI CLIENTI','ORDPJCARD_PERS.FRX','')
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('ORFPJEUR_PERS','REPORT PERSONALIZZABILE PER ORDINI FORNITORI','ORFPJCARD_PERS.FRX','')
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('BOLPJITA_PERS','REPORT PERSONALIZZABILE PER BOLLE','BOLPJCARD_PERS.FRX','BOLPJITP.FRX')
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('FAPPJEUR_PERS','REPORT PERSONALIZZABILE PER FATTURE PROFORMA','FAPPJCARD_PERS.FRX','')
INSERT INTO PJTIPREP (NOMEPROC,DESPROC,NOMEREP,NOMEREP2) VALUES ('FATPJEUR_PERS','REPORT PERSONALIZZABILE PER FATTURE CLIENTI','FATPJCARD_PERS.FRX','FATPJCARDE.FRX')

UPDATE DOCUMENTI SET DOC_REPORT1 = 'OFFPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'OFF'
UPDATE DOCUMENTI SET DOC_REPORT1 = 'ORDPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'ORD'
UPDATE DOCUMENTI SET DOC_REPORT1 = 'ORFPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'ORF'
UPDATE DOCUMENTI SET DOC_REPORT1 = 'BOLPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'BOL'
UPDATE DOCUMENTI SET DOC_REPORT1 = 'FAPPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'FAP'
UPDATE DOCUMENTI SET DOC_REPORT1 = 'FATPJCARD_PERS.FRX' WHERE DOC_TIPODOC = 'FAT'
