

UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'PORFAS'
UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'PORFCA'
UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'PORFOB'
UPDATE PARA SET LIBERA = 'F' WHERE CODICE = 'PORPAS'

UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'PORC&F'
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'PORCFR'
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'PORCIF'
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'PORCIP'
UPDATE PARA SET LIBERA = 'C' WHERE CODICE = 'PORCPT'

UPDATE PARA SET LIBERA = 'D' WHERE CODICE = 'PORDAF'
UPDATE PARA SET LIBERA = 'D' WHERE CODICE = 'PORDDP'
UPDATE PARA SET LIBERA = 'D' WHERE CODICE = 'PORDDU'

UPDATE PARA SET LIBERA = 'E' WHERE CODICE = 'POREX'
UPDATE PARA SET LIBERA = 'E' WHERE CODICE = 'POREXW'

SELECT * FROM PARA WHERE CODICE LIKE 'POR%'