
SELECT * FROM CONTI WHERE CON_ANNO = '2024' AND CON_NUMPAR <> ''

SELECT * FROM CONTI WHERE CON_ANNO = '2024' AND CON_NUMPAR = 'YES_ANT_FORN'
SELECT * FROM CONTI WHERE CON_ANNO = '2024' AND CON_TIPOCO = 'F' ORDER BY CON_CONTO

/*
UPDATE CONTI SET CON_NUMPAR = '' WHERE CON_ANNO = '2024' AND CON_NUMPAR = 'YES_ANT_FORN'
UPDATE CONTI SET CON_NUMPAR = 'YES_ANT_FORN' WHERE CON_ANNO = '2024' AND CON_TIPOCO = 'F'
*/