
SELECT PAR_NUMFAT,PAR_NPROT,* FROM PART_CLI WHERE PAR_ANNO <= '2014' ORDER BY PAR_ANNO,PAR_NPART
SELECT PAR_NUMFAT,PAR_NPROT,* FROM PART_CLI WHERE PAR_ANNO <= '2014' AND PAR_NUMFAT LIKE '%'+RTRIM(PAR_NPROT)+'%' ORDER BY PAR_ANNO,PAR_NPART

--UPDATE PART_CLI SET PAR_NPROT = PAR_NUMFAT WHERE PAR_ANNO <= '2014' AND PAR_NUMFAT LIKE '%'+RTRIM(PAR_NPROT)+'%'