
-- CANCELLAZIONE VECCHIE VISTE SENZA SUFFISSO '_AQ'

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDPROD]'))
	DROP VIEW [dbo].[ORDPROD]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAMAGA]'))
	DROP VIEW [dbo].[ANAMAGA]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TESDOCUM]'))
	DROP VIEW [dbo].[TESDOCUM]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MOVIMAG]'))
	DROP VIEW [dbo].[MOVIMAG]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANARTIC]'))
	DROP VIEW [dbo].[ANARTIC]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANARTIC2]'))
	DROP VIEW [dbo].[ANARTIC2]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[COMUNI]'))
	DROP VIEW [dbo].[COMUNI]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BARCODE]'))
	DROP VIEW [dbo].[BARCODE]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CPG]'))
	DROP VIEW [dbo].[CPG]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LINGUE]'))
	DROP VIEW [dbo].[LINGUE]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[STATIEST]'))
	DROP VIEW [dbo].[STATIEST]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABDIST]'))
	DROP VIEW [dbo].[TABDIST]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABIVA]'))
	DROP VIEW [dbo].[TABIVA]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABPORTI]'))
	DROP VIEW [dbo].[TABPORTI]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABVALUT]'))
	DROP VIEW [dbo].[TABVALUT]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TAZOCO]'))
	DROP VIEW [dbo].[TAZOCO]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DESARTLI]'))
	DROP VIEW [dbo].[DESARTLI]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[AGENTI]'))
	DROP VIEW [dbo].[AGENTI]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CLIFO]'))
	DROP VIEW [dbo].[CLIFO]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GRUPMERC]'))
	DROP VIEW [dbo].[GRUPMERC]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CAUSMAGA]'))
	DROP VIEW [dbo].[CAUSMAGA]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CFVEN]'))
	DROP VIEW [dbo].[CFVEN]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABTELIS]'))
	DROP VIEW [dbo].[TABTELIS]
GO

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABRILIS]'))
	DROP VIEW [dbo].[TABRILIS]
GO



-- ORDINI DI PRODUZIONE
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDPROD_AQ]'))
	DROP VIEW [dbo].[ORDPROD_AQ]
GO

CREATE VIEW [dbo].[ORDPROD_AQ]  
AS
	SELECT
		CASE ART_TIPOPR
			WHEN 'I' THEN 'OP'
			ELSE 'OE'
		END AS TIPO,
		CAST(SUBSTRING(DATPRG,1,4) AS DECIMAL(6,0)) AS ANNO, 
		CAST(NUMPRG AS DECIMAL(10,0)) AS NUM,
		STATO,
		--CAST(0 AS DECIMAL(6,0)) AS ANNOF,
		--CAST(0 AS DECIMAL(10,0)) AS NUMF,
		SUBSTRING(COMP1,1,16) AS CODPADRE,
		CAST(COALESCE(QTA4,QTA3,QTA2) AS FLOAT) AS Q1,
		COALESCE(SUBSTRING(COMP4,1,16),SUBSTRING(COMP3,1,16),SUBSTRING(COMP2,1,16)) AS CODART,
		IDPRG,
		Q2
	FROM (
		SELECT * FROM (
			SELECT P1.IDPRG, PR.ART_TIPOPR, P1.COMP AS COMP1, P1.NUMPRG, P1.DATPRG, P2.COMP AS COMP2, P2.QTA AS QTA2, D2.DIS_FITTIZ AS F2, P3.COMP AS COMP3, P3.QTA AS QTA3, D3.DIS_FITTIZ AS F3, P4.COMP AS COMP4, P4.QTA AS QTA4, D4.DIS_FITTIZ AS F4, CASE WHEN PA.QTAPROD >= PA.QTA THEN 'S' ELSE '' END AS STATO, NULL AS Q2
			FROM PRODUZIONE AS P1
			LEFT OUTER JOIN PRODUZIONE AS P2 ON P2.IDPRG = P1.IDPRG AND P2.PARENT = P1.CHIAVE AND P2.FASELA = ''
			LEFT OUTER JOIN U_DIS_DD AS D2 ON D2.DIS_GRUPPO = P1.COMP AND D2.DIS_CODART = P2.COMP
			LEFT OUTER JOIN PRODUZIONE AS P3 ON P3.IDPRG = P1.IDPRG AND P3.PARENT = P2.CHIAVE AND P3.FASELA = '' AND D2.DIS_FITTIZ = 1
			LEFT OUTER JOIN U_DIS_DD AS D3 ON D3.DIS_GRUPPO = P2.COMP AND D3.DIS_CODART = P3.COMP
			LEFT OUTER JOIN PRODUZIONE AS P4 ON P4.IDPRG = P1.IDPRG AND P4.PARENT = P3.CHIAVE AND P4.FASELA = '' AND D3.DIS_FITTIZ = 1
			LEFT OUTER JOIN U_DIS_DD AS D4 ON D4.DIS_GRUPPO = P3.COMP AND D4.DIS_CODART = P4.COMP
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = P1.COMP
			LEFT OUTER JOIN (SELECT IDPRG, COMP, SUM(QTA) AS QTA, SUM(QTAPROD) AS QTAPROD FROM PROD_AVANZA GROUP BY IDPRG, COMP) AS PA ON PA.IDPRG = P1.IDPRG AND PA.COMP = P1.COMP
			WHERE P1.PARENT = '000000001_' AND NOT (D2.DIS_FITTIZ = 1 AND D3.DIS_FITTIZ = 1)

			UNION

			SELECT P1.IDPRG, PR.ART_TIPOPR, P1.COMP AS COMP1, P1.NUMPRG, P1.DATPRG, PP.COMP AS COMP2, PP.QTA AS QTA2, CAST(1 AS BIT) AS F2, NULL AS COMP3, NULL AS QTA3, NULL AS F3, NULL AS COMP4, NULL AS QTA4, NULL AS F4, CASE WHEN PC.NROWS > 0 THEN 'M' ELSE '' END AS STATO, PC.QTAPREL AS Q2
			FROM PRODUZIONE AS P1
			LEFT OUTER JOIN PRODUZIONE AS PP ON PP.IDPRG = P1.IDPRG AND PP.CHIAVE = P1.CHIAVE
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = P1.COMP
			LEFT OUTER JOIN (SELECT IDPRG, CODART, COUNT(*) AS NROWS, SUM(1) AS QTAPREL, SUM(CASE QTAPROD WHEN 0 THEN 1 ELSE 0 END) AS QTAPREL_NON_VERS FROM PROD_CARICHI GROUP BY IDPRG, CODART) AS PC ON PC.IDPRG = P1.IDPRG AND PC.CODART = P1.COMP
			WHERE P1.PARENT = '000000001_'

		) AS T_MAIN
	) AS MAIN
GO

--WHERE NUMPRG = '000075'
--ORDER BY ANNO,CODPADRE,CODART

--SELECT * FROM ORDPROD_AQ


-- SERIAL NUMBERS/LOTTI ORDINI DI PRODUZIONE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDPROD_SERIALS_AQ]'))
	DROP VIEW [dbo].[ORDPROD_SERIALS_AQ]
GO

CREATE VIEW [dbo].[ORDPROD_SERIALS_AQ]  
AS
	SELECT
		IDPRG,
		SERIAL,
		PROGRE,
		QTAPROD,
		UM,
		DATAVA,
		ORAAVA,
		NOMOPE
	FROM PROD_CARICHI
GO

--SELECT * FROM ORDPROD_SERIALS_AQ WHERE IDPRG = 'P3ZE0R923S' ORDER BY PROGRE


-- ANAGRAFICA ARTICOLI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAMAGA_AQ]'))
	DROP VIEW [dbo].[ANAMAGA_AQ]
GO

CREATE VIEW [dbo].[ANAMAGA_AQ]  
AS
	SELECT
		SUBSTRING(PR.ART_CODPRI,1,16) AS CODICE,
		PR.ART_DESCR AS DESCRIZION,
		PR.ART_DESRID AS CODICERICE,
		PR.ART_CODITG1 AS CODICEVUOT,
		--NULL AS CODICEALTE,
		CASE
			WHEN COALESCE(DIT.DIT_GRUPPO,'') <> '' AND COALESCE(DIS.DIS_CODART,'') = '' THEN 'K'
			WHEN COALESCE(DIT.DIT_GRUPPO,'') <> '' AND COALESCE(DIS.DIS_CODART,'') <> '' THEN 'S'
			ELSE 'M'
		END AS TIPO,
		PR.ART_UNIMIS AS UNITAMIVEN,
		AN.ART_CODGMI AS GRUPPOMERC,
		--CASE
		--	WHEN PR.ART_CGE = '' THEN NULL
		--	ELSE PR.ART_CGE
		--END AS CONTROVEN,
		CASE PR.ART_OBSOL
			WHEN 'S' THEN 'N'
			ELSE 'S'
		END AS STATO
		--NULL AS MARCHIO
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODSOC = PR.ART_CODSOC AND AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN (SELECT DIT_GRUPPO FROM U_DIS_TT GROUP BY DIT_GRUPPO) AS DIT ON PR.ART_CODPRI = DIT.DIT_GRUPPO
	LEFT OUTER JOIN (SELECT DIS_CODART FROM U_DIS_DD GROUP BY DIS_CODART) AS DIS ON PR.ART_CODPRI = DIS.DIS_CODART
	WHERE LEN(RTRIM(PR.ART_CODPRI)) <= 16
GO

--SELECT CODICE, DESCRIZION, CODICERICE, CODICEVUOT, CODICEALTE, TIPO, UNITAMIVEN, GRUPPOMERC, CONTROVEN, STATO, MARCHIO FROM ANAMAGA_AQ

-- TESTATE DOCUMENTI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TESDOCUM_AQ]'))
	DROP VIEW [dbo].[TESDOCUM_AQ]
GO

CREATE VIEW [dbo].[TESDOCUM_AQ]  
AS
	SELECT
		ORD_CODCLI AS CLI_FOR,
		SUBSTRING(ORD_CAUS,1,3) AS TIPOPROTOC,
		SUBSTRING(ORD_DATORD,1,4) AS ESERPROTOC,
		'0'+ORD_NUMORD AS NUMEPROTOC,
		'ORD'+TAGGANCIO AS NUMERO,
		--SPACE(3) AS CAUSTRASPO,
		--NULL AS ESERDEFINI,
		--NULL AS NUMEDEFINI,
		--NULL AS DATADEFINI,
		SUBSTRING(ORD_DATORD,1,4)+SUBSTRING(ORD_DATORD,6,2)+SUBSTRING(ORD_DATORD,9,2) AS DATAPROTOC,
		--NULL AS TIPODEFINI,
		CASE ORD_INDC 
			WHEN '' THEN ORD_INDIRI
			ELSE ORD_INDC
		END AS INDIR_DEST,
		CASE ORD_RAGC
			WHEN '' THEN ORD_RAGSOC
			ELSE ORD_RAGC
		END AS RGSOC_DEST,
		CASE ORD_LOCC 
			WHEN '' THEN ORD_LOCALI
			ELSE ORD_LOCC
		END AS LOCAL_DEST,
		CASE ORD_CAPC 
			WHEN '' THEN ORD_CAP
			ELSE ORD_CAPC
		END AS CAP_DEST,
		ORD_CODCLI AS DESTINATAR
	FROM U_ORD_TT AS ORD_T

	UNION

	SELECT
		ORD_CODCLI AS CLI_FOR,
		SUBSTRING(ORD_CAUS,1,3) AS TIPOPROTOC,
		SUBSTRING(ORD_DATORD,1,4) AS ESERPROTOC,
		'0'+ORD_NUMORD AS NUMEPROTOC,
		'ORF'+TAGGANCIO AS NUMERO,
		--SPACE(3) AS CAUSTRASPO,
		--NULL AS ESERDEFINI,
		--NULL AS NUMEDEFINI,
		--NULL AS DATADEFINI,
		SUBSTRING(ORD_DATORD,1,4)+SUBSTRING(ORD_DATORD,6,2)+SUBSTRING(ORD_DATORD,9,2) AS DATAPROTOC,
		--NULL AS TIPODEFINI,
		CASE ORD_INDC 
			WHEN '' THEN ORD_INDIRI
			ELSE ORD_INDC
		END AS INDIR_DEST,
		CASE ORD_RAGC
			WHEN '' THEN ORD_RAGSOC
			ELSE ORD_RAGC
		END AS RGSOC_DEST,
		CASE ORD_LOCC 
			WHEN '' THEN ORD_LOCALI
			ELSE ORD_LOCC
		END AS LOCAL_DEST,
		CASE ORD_CAPC 
			WHEN '' THEN ORD_CAP
			ELSE ORD_CAPC
		END AS CAP_DEST,
		ORD_CODCLI AS DESTINATAR
	FROM U_ORF_TT AS ORF_T

GO

--SELECT * FROM TESDOCUM_AQ

-- DETTAGLI DOCUMENTI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MOVIMAG_AQ]'))
	DROP VIEW [dbo].[MOVIMAG_AQ]
GO

CREATE VIEW [dbo].[MOVIMAG_AQ]  
AS
	SELECT
		SUBSTRING(ORD_CODART,1,16) AS ARTICOLO,
		PR.ART_DESCR AS DESARTICOL,
		PR.ART_BARCLI AS BARCODE,
		CAST(ORD_QTAORD AS INT) AS QUANTITA,
		'ORD'+ORD_D.DAGGANCIO AS NUMERO,
		'ORD'+ORD_D.ORD_CODSYS AS RIGA,
		CASE
			WHEN COALESCE(BOL_LEG.DAGGANCIO,'') <> '' THEN 'BOL'+BOL_LEG.DAGGANCIO
			ELSE NULL
		END AS NUMERORIF,
		ORD_PESOUM AS PESOKG,
		ORD_UM AS UNIMISURA,
		CAST(ORD_QTAORD AS INT) AS QTACQUISTO
	FROM U_ORD_DD AS ORD_D
	LEFT OUTER JOIN (SELECT DAGGANCIO, ORD_LEGSYS FROM U_BOL_DD) AS BOL_LEG ON BOL_LEG.ORD_LEGSYS = ORD_D.ORD_LEGSYS
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = ORD_D.ORD_CODART
	WHERE ORD_CODART <> '' AND ORD_DESART <> '*** COMMENTO ***'

	UNION

	SELECT
		SUBSTRING(ORD_CODART,1,16) AS ARTICOLO,
		PR.ART_DESCR AS DESARTICOL,
		PR.ART_BARCLI AS BARCODE,
		CAST(ORD_QTAORD AS INT) AS QUANTITA,
		'ORF'+ORF_D.DAGGANCIO AS NUMERO,
		'ORF'+ORF_D.ORD_CODSYS AS RIGA,
		CASE
			WHEN COALESCE(BFO_LEG.DAGGANCIO,'') <> '' THEN 'BFO'+BFO_LEG.DAGGANCIO
			ELSE NULL
		END AS NUMERORIF,
		0 AS PESOKG,
		ORD_UM AS UNIMISURA,
		CAST(ORD_QTAORD AS INT) AS QTACQUISTO
	FROM U_ORF_DD AS ORF_D
	LEFT OUTER JOIN (SELECT DAGGANCIO, ORD_LEGAME, ORD_LEGASY FROM U_BFO_DD) AS BFO_LEG ON BFO_LEG.ORD_LEGASY = ORF_D.ORD_CODSYS AND BFO_LEG.ORD_LEGAME = ORF_D.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = ORF_D.ORD_CODART
	WHERE ORD_CODART <> '' AND ORD_DESART <> '*** COMMENTO ***'
GO

--SELECT * FROM MOVIMAG_AQ


-- ANAGRAFICA ARTICOLI FABRICA
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANARTIC_AQ]'))
	DROP VIEW [dbo].[ANARTIC_AQ]
GO

CREATE VIEW [dbo].[ANARTIC_AQ]  
AS
	SELECT
		SUBSTRING(PR.ART_CODPRI,1,16) AS CODART,
		PR.ART_DESCR AS DESCR,
		PR.ART_CODCTL AS CODIS,
		PR.ART_LINEA AS TIPDIST,
		CAST(SUBSTRING(PR.ART_DATINS,1,4)+SUBSTRING(PR.ART_DATINS,6,2)+SUBSTRING(PR.ART_DATINS,9,2) AS DATETIME) AS DATAULTAGG,
		PR.ART_DATINS AS DATINS,
		CASE DIS.DIS_FITTIZ
			WHEN 1 THEN 'S'
			ELSE 'N'
		END AS FITTIZIO,
		CASE PR.ART_OBSOL
			WHEN 'S' THEN 'N'
			ELSE 'S'
		END AS STATO
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODSOC = PR.ART_CODSOC AND AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN (SELECT DIS_CODART,DIS_FITTIZ FROM U_DIS_DD GROUP BY DIS_CODART,DIS_FITTIZ) AS DIS ON PR.ART_CODPRI = DIS.DIS_CODART
GO

--SELECT * FROM ANARTIC

-- DATI AGGIUNTIVI ANAGRAFICA ARTICOLI FABRICA
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANARTIC2_AQ]'))
	DROP VIEW [dbo].[ANARTIC2_AQ]
GO

CREATE VIEW [dbo].[ANARTIC2_AQ]  
AS
	SELECT
		SUBSTRING(PR.ART_CODPRI,1,16) AS CODART,
		--PR.ART_CODPRI AS CHIEST,
		PR.ART_PESOUM AS PESOKG,
		--'' AS MARCHIO,
		PR.ART_PRZCOS / 1936.27 AS PRSTANDAR,
		PR.ART_PRZCOS AS EPRSTANDAR
		--'' AS CODICERICE
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODSOC = PR.ART_CODSOC AND AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN (SELECT DIS_CODART,DIS_FITTIZ FROM U_DIS_DD GROUP BY DIS_CODART,DIS_FITTIZ) AS DIS ON PR.ART_CODPRI = DIS.DIS_CODART
GO

--SELECT * FROM ANARTIC2_AQ


-- COMUNI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[COMUNI_AQ]'))
	DROP VIEW [dbo].[COMUNI_AQ]
GO

CREATE VIEW [dbo].[COMUNI_AQ]  
AS
	SELECT
		'ITA' AS STATO, 
		COD_FIS AS COM, 
		COMUNE AS DENCOM, 
		PROVINCIA AS PROVCOM, 
		CAP AS CAPCOM, 
		'' AS CODISTAT, 
		NULL AS UFFIIDD1, 
		NULL AS UFFIIDD2, 
		NULL AS UFFIIDD3, 
		NULL AS UFFIVA1, 
		NULL AS UFFIVA2, 
		NULL AS UFFIVA3, 
		NULL AS UFFREG, 
		NULL AS UFFCONC, 
		NULL AS UFFCSERV, 
		NULL AS UFFESPROV, 
		NULL AS UFFESCOM, 
		NULL AS ALIQICI, 
		NULL AS COMAGG, 
		NULL AS TERRMON, 
		'S' AS ATTIVO, 
		NULL AS ULT_AGG
	FROM COMUNI
GO

--SELECT * FROM COMUNI_AQ


-- BARCODE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BARCODE_AQ]'))
	DROP VIEW [dbo].[BARCODE_AQ]
GO

CREATE VIEW [dbo].[BARCODE_AQ]  
AS
	SELECT
		ART_BARCLI AS BARCODE,
		SUBSTRING(ART_CODPRI,1,16) AS CODICE
	FROM U_ART_PR WHERE ART_BARCLI <> ''
GO

--SELECT * FROM BARCODE_AQ


-- CONDIZIONI DI PAGAMENTO
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CPG_AQ]'))
	DROP VIEW [dbo].[CPG_AQ]
GO

CREATE VIEW [dbo].[CPG_AQ]  
AS
	SELECT
		SUBSTRING(CODICE,4,3) AS CODICE, 
		DESCRI AS DESCRIZION, 
		CASE SUBSTRING(LIBERA,1,3)
			WHEN 'FM ' THEN 'M'
			WHEN 'DF ' THEN 'F'
			ELSE 'I'
		END AS INIZIOCAL, 
		NULL AS TPRATA, 
		NULL AS MESECOMM, 
		NULL AS SCONTOVALU, 
		NULL AS CODLINGUA, 
		'S' AS STATO,
		NULL AS UTENTE, 
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG,
		CASE
			WHEN PERIMPO > 0 OR PERCENTUALI <> '' THEN 'N'
			ELSE 'S'
		END AS RATECOSTAN, 
		NULL AS EXPORTED, 
		NULL AS AMOD_INCAS, 
		NULL AS APAESE_PAG, 
		NULL AS VMOD_INCAS, 
		NULL AS VPAESE_PAG, 
		NULL AS GGCALENDAR, 
		NULL AS AFINEMESE
	FROM PARA WHERE CODICE LIKE 'CPA%'
GO

--SELECT * FROM CPG_AQ


-- LINGUE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LINGUE_AQ]'))
	DROP VIEW [dbo].[LINGUE_AQ]
GO

CREATE VIEW [dbo].[LINGUE_AQ]  
AS
	SELECT
		SUBSTRING(CODICE,4,3) AS CODICE, 
		DESCRI AS DESCRIZION, 
		'S' AS STATO,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG
	FROM PARA WHERE CODICE LIKE 'LNG%'
GO

-- SELECT * FROM LINGUE_AQ


-- STATI ESTERI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[STATIEST_AQ]'))
	DROP VIEW [dbo].[STATIEST_AQ]
GO

CREATE VIEW [dbo].[STATIEST_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS CODICE,
		DESCRI AS DENOMINAZI,
		CASE
			WHEN DESIVA LIKE '%STATOCEE: S%' THEN (SELECT TOP 1 AZI_VALU FROM U_AZI_AN)
			ELSE NULL
		END AS VALUTA,
		NULL AS NAZIONALIT,
		CASE LIBERA
			WHEN '' THEN NULL
			ELSE LIBERA
		END AS STATOINTRA,
		'S' AS STATO,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG,
		CASE
			WHEN DESIVA LIKE '%STATOCEE: S%' THEN 'S'
			WHEN DESIVA LIKE '%STATOCEE: N%' THEN 'N'
			ELSE NULL
		END AS STATOCEE
	FROM PARA WHERE CODICE LIKE 'STA%' AND SUBSTRING(CODICE,4,3) <> (SELECT TOP 1 AZI_NAZI FROM U_AZI_AN)
GO

-- SELECT * FROM STATIEST_AQ


-- TIPO PARTE DISTINTA BASE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABDIST_AQ]'))
	DROP VIEW [dbo].[TABDIST_AQ]
GO

CREATE VIEW [dbo].[TABDIST_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS COD,
		DESCRI AS DESCR,
		DESIVA AS TPDOC,
		'N' AS PRELAUT,
		LIBERA AS CODMAG
	FROM PARA WHERE CODICE LIKE 'REP%'
GO

-- SELECT * FROM TABDIST_AQ


-- CODICI IVA
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABIVA_AQ]'))
	DROP VIEW [dbo].[TABIVA_AQ]
GO

CREATE VIEW [dbo].[TABIVA_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS CODICE,
		DESCRI AS DESCRIZION
	FROM PARA WHERE CODICE LIKE 'IVA%'
GO

-- SELECT * FROM TABIVA_AQ


-- PORTI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABPORTI_AQ]'))
	DROP VIEW [dbo].[TABPORTI_AQ]
GO

CREATE VIEW [dbo].[TABPORTI_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS CODICE,
		DESCRI AS DESCRIZION,
		'S' AS STATO,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG,
		NULL AS CONSEGNA,
		NULL AS CONSINTRA
	FROM PARA WHERE CODICE LIKE 'POR%'
GO

-- SELECT * FROM TABPORTI_AQ


-- VALUTE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABVALUT_AQ]'))
	DROP VIEW [dbo].[TABVALUT_AQ]
GO

CREATE VIEW [dbo].[TABVALUT_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS CODICE,
		DESCRI AS DESCRIZION,
		'S' AS STATO,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG,
		NULL AS CODICEISO,
		0 AS CODNUM
	FROM PARA WHERE CODICE LIKE 'VVA%'
GO

-- SELECT * FROM TABVALUT_AQ


-- ZONE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TAZOCO_AQ]'))
	DROP VIEW [dbo].[TAZOCO_AQ]
GO

CREATE VIEW [dbo].[TAZOCO_AQ]  
AS
	SELECT 
		SUBSTRING(CODICE,4,3) AS CODICE,
		DESCRI AS DESCRIZION,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG,
		'S' AS STATO
	FROM PARA WHERE CODICE LIKE 'ZON%'
GO

-- SELECT * FROM TAZOCO_AQ


-- DESCRIZIONI IN LINGUA ARTICOLI DI MAGAZZINO
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DESARTLI_AQ]'))
	DROP VIEW [dbo].[DESARTLI_AQ]
GO

CREATE VIEW [dbo].[DESARTLI_AQ]  
AS
	SELECT
		CODICE AS ARTICOLO,
		LINGUA AS LINGUA,
		DESCRI AS DESCRIZION,
		NULL AS UTENTE,
		NULL AS ULTAGG
	FROM DESLINGUE
	WHERE TIPODES = 'ARTICOLO'
GO

-- SELECT * FROM DESARTLI_AQ


-- AGENTI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[AGENTI_AQ]'))
	DROP VIEW [dbo].[AGENTI_AQ]
GO

CREATE VIEW [dbo].[AGENTI_AQ]  
AS
	SELECT
		SUBSTRING(PARA.CODICE,4,3) AS CODICE,
		CASE
			WHEN PARA.LIBERA LIKE 'Fornitore legato: %' THEN RTRIM(SUBSTRING(PARA.LIBERA,19,10))
			ELSE NULL
		END AS CODFORNITO,
		NULL AS CODCAPOZON,
		U_AGE_AN.AGE_PROVVI AS PERCPROVVI,
		'N' AS CAP_ZON_SN,
		'S' AS STATO,
		NULL AS UTENTE,
		SUBSTRING(PAR_DATINS,1,4)+SUBSTRING(PAR_DATINS,6,2)+SUBSTRING(PAR_DATINS,9,2) AS ULT_AGG
	FROM PARA 
	LEFT OUTER JOIN U_AGE_AN ON SUBSTRING(PARA.CODICE,4,3) = U_AGE_AN.AGE_CODICE
	WHERE CODICE LIKE 'AGE%' AND SUBSTRING(CODICE,4,3) <> (SELECT TOP 1 AZI_AGE FROM U_AZI_AN)
GO

-- SELECT * FROM AGENTI_AQ


-- ANAGRAFICA CLIENTI/FORNITORI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CLIFO_AQ]'))
	DROP VIEW [dbo].[CLIFO_AQ]
GO

CREATE VIEW [dbo].[CLIFO_AQ]  
AS
SELECT * FROM (
	SELECT
		CLI_RAGSOC AS RAGIONESOC, 
		CLI_CODCLI AS CODICE,
		'C' AS TIPO, 
		CLI_INDIR AS INDIR1, 
		NULL AS INDIR2, 
		CLI_CAP AS CAP, 
		CLI_LOCALI AS LOCALITA, 
		COD_FIS AS COD_COMUNE, 
		CLI_LOCALI AS COMUNE,
		CLI_PROVIN AS PROVINCIA, 
		CLI_NAZION AS COD_NAZION,
		PARA_STA.DESCRI AS NAZIONE,
		CLI_PARIVA AS PAIV,
		CLI_CODFIS AS COFI,
		NULL AS PTEL,
		CLI_TELEFO AS TEL, 
		'N' AS RAGGR_SN,
		SUBSTRING(CLI_DATINS,1,4)+SUBSTRING(CLI_DATINS,6,2)+SUBSTRING(CLI_DATINS,9,2) AS ULT_AGG,
		CASE
			WHEN CLI_PARIVA = '' AND CLI_IVACEE = '' THEN 'N'
			ELSE 'S'
		END AS SOGGIVA_SN, 
		CASE
			WHEN CLI_DTCLOK <> '' THEN 'S'
			ELSE 'N'
		END AS BLOCCO_SN,
		0 AS PERC_INT,
		NULL AS PERCENT_DA, 
		NULL AS SOLLSCA_SN, 
		NULL ADDINT_SN,
		CASE CLI_VALUTA
			WHEN (SELECT TOP 1 AZI_VALU FROM U_AZI_AN) THEN NULL
			ELSE CLI_VALUTA
		END AS CODVAL,
		CASE CLI_OBSOL
			WHEN 'S' THEN 'N'
			ELSE 'S'
		END AS STATO,
		CLI_RAGRID AS NOMEBREVE,
		NULL AS FATTURAREA, 
		CASE LIBERA
			WHEN '' THEN 'N'
			ELSE 'S'
		END AS STATOINTRA,
		NULL AS ALLEGAT_SN,
		'N' AS FTFAX_SN,
		NULL AS FTFAXNUM,
		'N' AS FTMAIL_SN,
		NULL AS FTE_MAIL,
		SUBSTRING(CLI_CONPAG,1,3) AS CODPAG,
		NULL AS PER_FATTUR,
		CLI_EMAIL AS EMAIL
	FROM U_CLI_AN 
	LEFT OUTER JOIN COMUNI ON COMUNI.CAP = U_CLI_AN.CLI_CAP AND COMUNI.COMUNE = U_CLI_AN.CLI_LOCALI
	LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION

	UNION

	SELECT
		FOR_RAGSOC AS RAGIONESOC, 
		FOR_CODCLI AS CODICE,
		'F' AS TIPO, 
		FOR_INDIR AS INDIR1, 
		NULL AS INDIR2, 
		FOR_CAP AS CAP, 
		FOR_LOCALI AS LOCALITA, 
		COD_FIS AS COD_COMUNE, 
		FOR_LOCALI AS COMUNE,
		FOR_PROVIN AS PROVINCIA, 
		FOR_NAZION AS COD_NAZION,
		PARA_STA.DESCRI AS NAZIONE,
		FOR_PARIVA AS PAIV,
		FOR_CODFIS AS COFI,
		NULL AS PTEL,
		FOR_TELEFO AS TEL, 
		'N' AS RAGGR_SN,
		SUBSTRING(FOR_DATINS,1,4)+SUBSTRING(FOR_DATINS,6,2)+SUBSTRING(FOR_DATINS,9,2) AS ULT_AGG,
		CASE
			WHEN FOR_PARIVA = '' AND FOR_IVACEE = '' THEN 'N'
			ELSE 'S'
		END AS SOGGIVA_SN,
		'N' BLOCCO_SN,
		0 AS PERC_INT,
		NULL AS PERCENT_DA, 
		NULL AS SOLLSCA_SN, 
		NULL ADDINT_SN,
		CASE FOR_VALUTA
			WHEN (SELECT TOP 1 AZI_VALU FROM U_AZI_AN) THEN NULL
			ELSE FOR_VALUTA
		END AS CODVAL,
		CASE FOR_OBSOL
			WHEN 'S' THEN 'N'
			ELSE 'S'
		END AS STATO,
		'' AS NOMEBREVE,
		NULL AS FATTURAREA, 
		CASE LIBERA
			WHEN '' THEN 'N'
			ELSE 'S'
		END AS STATOINTRA,
		NULL AS ALLEGAT_SN,
		'N' AS FTFAX_SN,
		NULL AS FTFAXNUM,
		'N' AS FTMAIL_SN,
		NULL AS FTE_MAIL,
		SUBSTRING(FOR_CONPAG,1,3) AS CODPAG,
		NULL AS PER_FATTUR,
		FOR_EMAIL AS EMAIL
	FROM U_FOR_AN 
	LEFT OUTER JOIN COMUNI ON COMUNI.CAP = U_FOR_AN.FOR_CAP AND COMUNI.COMUNE = U_FOR_AN.FOR_LOCALI
	LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_FOR_AN.FOR_NAZION
	) AS CLIENTI_FORNITORI
GO

-- SELECT * FROM CLIFO_AQ


-- GRUPPI MERCEOLOGICI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GRUPMERC_AQ]'))
	DROP VIEW [dbo].[GRUPMERC_AQ]
GO

CREATE VIEW [dbo].[GRUPMERC_AQ]  
AS
	SELECT
		SUBSTRING(CODICE,4,9) AS COMPLETO, 
		SUBSTRING(CODICE,4,3) AS CODGRU,
		CASE SUBSTRING(CODICE,7,3)
			WHEN '' THEN NULL
			ELSE SUBSTRING(CODICE,7,3)
		END AS CODFAM, 
		CASE SUBSTRING(CODICE,10,3)
			WHEN '' THEN NULL
			ELSE SUBSTRING(CODICE,10,3)
		END AS CODSFAM, 
		DESCRI AS DESCRIZION, 
		'S' AS STATO
	FROM PARA WHERE CODICE LIKE 'GMI%'
GO

-- SELECT * FROM GRUPMERC_AQ


-- CAUSALI DI MAGAZZINO
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CAUSMAGA_AQ]'))
	DROP VIEW [dbo].[CAUSMAGA_AQ]
GO

CREATE VIEW [dbo].[CAUSMAGA_AQ]  
AS
	SELECT
		SUBSTRING(CODICE,4,3) AS CODCAUMAG,
		DESCRI AS DESCAUMAG,
		CASE
			WHEN DESCRI LIKE '%INVENTARIO%' THEN
				CASE
					WHEN SUBSTRING(LIBERA,1,1) = 'C' THEN '+'
					WHEN SUBSTRING(LIBERA,1,1) = 'S' THEN '-'
					ELSE 'N'
				END
			ELSE 'N'
		END AS MOVINVENT,
		CASE
			WHEN DESIVA LIKE '%Stato: N%' THEN 'N'
			ELSE 'S'
		END AS STATO,
		'N' AS MOVCADAAQ,
		CASE
			WHEN DESCRI LIKE '%INVENTARIO%' THEN 'N'
			WHEN SUBSTRING(LIBERA,1,1) = 'C' THEN '+'
			ELSE 'N'
		END AS MOVALTRIC,
		'N' AS SCAPERVEN,
		CASE
			WHEN DESCRI LIKE '%INVENTARIO%' THEN 'N'
			WHEN SUBSTRING(LIBERA,1,1) = 'S' THEN '+'
			ELSE 'N'
		END AS ALTRISCAR
	FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,42,1) = 'M'
GO

-- SELECT * FROM CAUSMAGA_AQ



-- DATI GESTIONALI ANAGRAFICA CLIENTI/FORNITORI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CFVEN_AQ]'))
	DROP VIEW [dbo].[CFVEN_AQ]
GO

CREATE VIEW [dbo].[CFVEN_AQ]
AS
SELECT * FROM (
	SELECT
		CLI_CODCLI AS CODCF,
		CLI_LOCDOC AS CODINDSP,
		NULL AS PFAX,
		CLI_FAX AS FAX,
		CLI_EMAIL AS E_MAILL,
		CLI_HOMPAG AS INTERNETL,
		CLI_IMPFID AS EFIDO,
		NULL AS ADDSPVA_SN,
		NULL AS ADDSPBO_SN,
		NULL AS ADDSPPA_SN, 
		NULL AS EIMPMORD,
		NULL AS EIMPMSPED,
		NULL AS CLASSIFIC1,
		NULL AS CLASSIFIC2,
		NULL AS CLASSIFIC3,
		NULL AS CLASSIFIC4,
		CLI_ZONA AS ZONA,
		CLI_OBSOL AS STATO,
		CLI_AGE AS CODAG,
		CLI_PORTO AS CODPORTO,
		CLI_CODIVA AS ASSFIS,
		NULL AS CODSCINC,
		NULL AS MSGDOCUM
	FROM U_CLI_AN 

	UNION

	SELECT
		FOR_CODCLI AS CODCF,
		FOR_LOCDOC AS CODINDSP,
		NULL AS PFAX,
		FOR_FAX AS FAX,
		FOR_EMAIL AS E_MAILL,
		FOR_HOMPAG AS INTERNETL,
		0 AS EFIDO,
		NULL AS ADDSPVA_SN,
		NULL AS ADDSPBO_SN,
		NULL AS ADDSPPA_SN, 
		NULL AS EIMPMORD,
		NULL AS EIMPMSPED,
		NULL AS CLASSIFIC1,
		NULL AS CLASSIFIC2,
		NULL AS CLASSIFIC3,
		NULL AS CLASSIFIC4,
		FOR_ZONA AS ZONA,
		FOR_OBSOL AS STATO,
		FOR_AGE AS CODAG,
		FOR_PORTO AS CODPORTO,
		FOR_CODIVA AS ASSFIS,
		NULL AS CODSCINC,
		NULL AS MSGDOCUM
	FROM U_FOR_AN
	) AS DATI_GESTIONALI_CLI_FOR
GO

-- SELECT * FROM CFVEN_AQ


-- TESTATE LISTINI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABTELIS_AQ]'))
	DROP VIEW [dbo].[TABTELIS_AQ]
GO

CREATE VIEW [dbo].[TABTELIS_AQ]
AS
	SELECT
		'V' AS TIPO,
		'Listino vendita ' + SUBSTRING(LIS_ALLIST,1,4) + ' - ' + SUBSTRING(LIS_ALLIST,1,4) AS DESCRIZION,
		(SELECT TOP 1 AZI_VALU FROM U_AZI_AN) AS VALUTA,
		SUBSTRING(LIS_DATLIS,1,4)+SUBSTRING(LIS_DATLIS,6,2)+SUBSTRING(LIS_DATLIS,9,2) AS DATAINVALI,
		SUBSTRING(LIS_ALLIST,1,4)+SUBSTRING(LIS_ALLIST,6,2)+SUBSTRING(LIS_ALLIST,9,2) AS DATAFIVALI,
		'N' AS LORDOIVA,
		NULL AS LISTINSUCC,
		'S' AS STATO,
		NULL AS UTENTE,
		NULL AS ULT_AGG,
		'N' AS LIFASCE_SN,
		'N' AS SCONTI_SN,
		'L_' + SUBSTRING(LIS_ALLIST,1,4) + '-' + SUBSTRING(LIS_ALLIST,1,4) AS CODICE
	FROM U_LIS_TT
	GROUP BY LIS_DATLIS, LIS_ALLIST
GO

-- SELECT * FROM TABTELIS_AQ


-- RIGHE LISTINI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[TABRILIS_AQ]'))
	DROP VIEW [dbo].[TABRILIS_AQ]
GO

CREATE VIEW [dbo].[TABRILIS_AQ]
AS
	SELECT
		LIS_PREZZO AS PREZZO,
		SUBSTRING(LIS_DATLIS,1,4)+SUBSTRING(LIS_DATLIS,6,2)+SUBSTRING(LIS_DATLIS,9,2) AS DATAINVALI,
		NULL AS UTENTE,
		NULL AS ULT_AGG,
		'L_' + SUBSTRING(LIS_ALLIST,1,4) + '-' + SUBSTRING(LIS_ALLIST,1,4) AS CODICE,
		SUBSTRING(LIS_CODART,1,16) AS ARTICOLO
	FROM U_LIS_TT
	WHERE LIS_CODCLI = ''
GO

-- SELECT * FROM TABRILIS_AQ


-- RIGHE DISTINTE BASE (SIGLA)
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[RIGDIS_AQ]'))
	DROP VIEW [dbo].[RIGDIS_AQ]
GO

CREATE VIEW [dbo].[RIGDIS_AQ]
AS
	SELECT
		DIS_GRUPPO AS CODICE,
		ART_LINEA AS TIPO,
		NULL AS IDEVARIAN,
		SUBSTRING(DIS_CODART,1,16) AS CODART,
		0 AS PERCRICARI,
		DIS_QTA AS QUANTITA,
		NULL AS FILE1,
		'S' AS STATO,
		'' AS UTENTE,
		'' AS ULT_AGG
	FROM U_DIS_DD
	LEFT OUTER JOIN U_ART_PR ON U_ART_PR.ART_CODPRI = U_DIS_DD.DIS_GRUPPO
	WHERE DIS_FASELA = ''
	--WHERE DIS_GRUPPO IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_LINEA IN (SELECT AZI_PDMLINPV FROM U_AZI_PB))  --SOLO GRUPPI CHE SIANO CODICI DI VENDITA
GO

-- SELECT * FROM RIGDIS_AQ ORDER BY CODICE, CODART


 -- NOTE DETTAGLI ORDINI CLIENTI
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[NOTE_AQ]'))
	DROP VIEW [dbo].[NOTE_AQ]
GO

/* COMMENTATA PER INUTILIZZO
CREATE VIEW [dbo].[NOTE_AQ]  
AS
	SELECT
		'DC' AS TIPORECORD,
		SUBSTRING(ORS_DATORD,1,4) AS ESERCIZIO,
		DAGGANCIO AS NUMEMOVIME,
		ORD_SEQUEN AS RIGAMOVIME,
		1 AS PROGRESSIV,
		ORD_CODICE AS CODICE,
		ORD_NOTE AS NOTA
	FROM U_ORD_DD
	WHERE ORD_DESART = '*** COMMENTO ***'
GO

--SELECT * FROM NOTE_AQ
*/



 -- INDIRIZZI DI SPEDIZIONE
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[INDSPED_AQ]'))
	DROP VIEW [dbo].[INDSPED_AQ]
GO


CREATE VIEW [dbo].[INDSPED_AQ]  
AS
	SELECT
		LOC_CODCLI AS CODCF,
		LOC_CODLOC+LOC_CODCLI AS CODIND,
		LOC_RAGSOC AS RAGSOC,
		LOC_INDIRI AS INDIR,
		LOC_LOCALI AS LOCALITA,
		SUBSTRING(LOC_CAP,1,5) AS CAP,
		LOC_LOCALI AS DES_COM,
		LOC_PROVIN AS PROVINCIA,
		CLI_NAZION AS STATOES,
		PARA_STA.DESCRI AS DES_STATO
	FROM U_LOC_AN
	LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODCLI = U_LOC_AN.LOC_CODCLI
	LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION
	WHERE LOC_CF = 'C'
GO

--SELECT * FROM INDSPED_AQ

 -- ARTICOLO DI ACQUISTO TRACCIATI A SERIAL NUMBER
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SERIALS_AQ]'))
	DROP VIEW [dbo].[SERIALS_AQ]
GO

CREATE VIEW [dbo].[SERIALS_AQ]  
AS
	SELECT
		SUBSTRING(U_BFO_TT.ORD_CAUS,1,3) AS TIP_ORDINE,
		SUBSTRING(U_BFO_TT.ORD_ANNO,1,4) AS ANN_ORDINE,
		SUBSTRING(U_BFO_TT.ORD_NUMORD,1,15) AS NUM_ORDINE,
		SUBSTRING(U_BFO_SN.CODART,1,16) AS ARTICOLO,
		SUBSTRING(U_BFO_SN.SERIAL,1,20) AS SN
	FROM U_BFO_SN
	LEFT OUTER JOIN U_BFO_TT ON U_BFO_TT.TAGGANCIO = U_BFO_SN.DAGGANCIO
GO

--SELECT * FROM INDSPED_AQ
