SELECT cli_nses,* FROM U_CLI_AN  WHERE CLI_NSES <> ''

SELECT ORD_NRPLEI AS NRPLEI,* FROM U_FAT_TT WHERE ORD_NRPLEI <> ''

select cli_nses,* from u_cli_an where cli_codsoc = '01' and cli_codcli = '000002740' order by cli_codsoc,cli_codcli

select ORS_CODCLI,DAGGANCIO from u_off_dd where ORD_LEGSYS = '_6NW0QZ0RF' and ORD_DESART <> '*** COMMENTO ***' order by daggancio,ord_sequen

SELECT * FROM U_FAT_TT ORDER BY TAGGANCIO DESC
SELECT * FROM U_OFF_TT ORDER BY TAGGANCIO DESC

SELECT ORD_NUMLEI,ORD_DATLEI,ORD_NRPLEI,ORD_DTPLEI,* FROM U_FAT_TT WHERE TAGGANCIO = '6000036188'

UPDATE U_FAT_TT SET ORD_NUMLEI = '',ORD_DATLEI = '',ORD_NRPLEI = '',ORD_DTPLEI = ''  WHERE TAGGANCIO = '6000036188'