SELECT MOV_CONTO,MOV_NUMPRO AS NUMPRO,MOV_IMP,MOV_IMPOST,MOV_IVA,MOV_TOP,* FROM INDICE WHERE SUBSTRING(MOV_NOTE,1,20) = '### PN IMPORTATA ###' ORDER BY MOV_NUMPRO

SELECT MOV_CONTO,MOV_NUMPRO AS NUMPRO,MOV_SEQUEN AS SEQUEN,MOV_IMP,MOV_IMPOST,MOV_IVA,MOV_TOP,* FROM MOV_CONT WHERE SUBSTRING(MOV_NOTE,1,20) = '### PN IMPORTATA ###' ORDER BY MOV_NUMPRO,MOV_SEQUEN

--DELETE FROM INDICE WHERE SUBSTRING(MOV_NOTE,1,20) ='### PN IMPORTATA ###'
--DELETE FROM MOV_CONT WHERE SUBSTRING(MOV_NOTE,1,20) ='### PN IMPORTATA ###'

SELECT * FROM U_IVF_CL WHERE IVF_ANNO = '2023' AND IVF_MESE = '06' AND IVF_CODIVA = '22' ORDER BY IVF_CHIAVE

SELECT * FROM U_IVF_CL WHERE IVF_ANNO = '2023' AND IVF_MESE = '06' ORDER BY IVF_CHIAVE
SELECT * FROM U_IVA_TO WHERE ITO_ANNO = '2023' AND ITO_MESE = '06' 


SELECT 
      SUM(IVF_IMPONI) AS IMPONI,SUM(IVF_IMPOST) AS IMPOST
FROM U_IVF_CL
WHERE IVF_ANNO = '2023' AND IVF_MESE = '06' AND IVF_CODIVA = '22' 

