
SELECT
	(SELECT CODICEALIQUOTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS CODICEALIQUOTA
	,(SELECT IMPOSTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS IMPOSTA
	,MC.MOV_IVA
	,MC.MOV_IMPOST
	,MC.*
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C','F'))
	AND MC.MOV_CONTO = '3.9.4.       '
ORDER BY MC.MOV_DTREG,MC.MOV_NREGIS

SELECT * FROM (
SELECT
	(SELECT CODICEALIQUOTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS CODICEALIQUOTA
	,(SELECT IMPOSTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS IMPOSTA
	,MC.*
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C','F'))
--ORDER BY MC.MOV_DTREG,MC.MOV_NREGIS
) AS MAIN ORDER BY CODICEALIQUOTA

-- AGGIORNAMENTO CODICE IVA E IMPOSTA SULLE CONTROPARTITE DEI MOVIMENTI CONTABILI DELLE FATTURE DI ACQUISTO E VENDITA
/*
UPDATE MC SET
	MOV_IVA = COALESCE(SUBSTRING((SELECT CODICEALIQUOTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN),2,3),MOV_IVA),
	MOV_IMPOST = COALESCE((SELECT ABS(IMPOSTA) FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN),MOV_IMPOST)
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C','F'))
*/



SELECT
	(SELECT CODICEALIQUOTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS CODICEALIQUOTA
	,(SELECT IMPOSTA FROM EC_ELINS.DBO.MovimentiIVA WHERE IDregistrazione = MC.MOV_NREGIS AND RIGAREGISTRAZIONE = MC.MOV_SEQUEN) AS IMPOSTA
	,MC.MOV_IVA
	,MC.MOV_IMPOST
	,MC.*
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C','F'))
	AND MC.MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('I'))
ORDER BY MC.MOV_DTREG,MC.MOV_NREGIS

-- FORZATURA CODICE IVA A 'XXX' SULLE RIGHE IVA DEI MOVIMENTI CONTABILI DELLE FATTURE DI ACQUISTO E VENDITA
/*
UPDATE MC SET
	MOV_IVA = 'XXX'
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C','F'))
	AND MC.MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('I'))
*/



SELECT
	MC.MOV_IVA
	,MC.MOV_IMPOST
	,MC.*
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C')
	AND MC.MOV_CONTO IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C'))
ORDER BY MC.MOV_DTREG,MC.MOV_NREGIS

SELECT
	MC.MOV_IVA
	,MC.MOV_IMPOST
	,MC.*
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C'))
ORDER BY MC.MOV_DTREG,MC.MOV_NREGIS


-- AGGIORNAMENTO NR.PROTOCOLLO SUI MOVIMENTI CONTABILI DELLE FATTURE DI ACQUISTO E VENDITA IMPORTATI DI APRILE E MAGGIO 
/*
UPDATE MC SET
	MOV_NPROT = MOV_NDOC
FROM MOV_CONT AS MC
WHERE
	MC.MOV_DTREG >= '2023/04/01' AND MC.MOV_DTREG <= '2023/05/31' AND RTRIM(SUBSTRING(MC.MOV_NOTE,1,100)) = '### PN IMPORTATA ###'
	AND MC.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C')
	AND MC.MOV_CONTO NOT IN (SELECT CON_CONTO FROM CONTI WHERE CON_ANNO = '2023' AND CON_TIPOCO IN ('C'))
*/
