SELECT MOV_NREGIS, MOV_NUMPRO AS NUMPRO,MOV_ANNO AS ANNO ,* FROM MOV_CONT ORDER BY MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN


SELECT MOV_NREGIS, MOV_NUMPRO AS NUMPRO,MOV_ANNO AS ANNO ,* FROM MOV_CONT WHERE MOV_TOP = '0001' ORDER BY MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN

SELECT MOV_CONTO,MOV_TMOV,MOV_IMP,MOV_IMPOST,MOV_IVA,MOV_NREGIS,MOV_SEQUEN AS SEQUEN, MOV_NUMPRO AS NUMPRO,MOV_ANNO AS ANNO ,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6MJ113UB2' ORDER BY MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN

SELECT MOV_CONTO,MOV_TMOV,MOV_IMP,MOV_IMPOST,MOV_IVA,MOV_NREGIS,MOV_SEQUEN AS SEQUEN, MOV_NUMPRO AS NUMPRO,MOV_ANNO AS ANNO ,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6MJ11430F' ORDER BY MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN

SELECT MOV_CONTO,MOV_SEQUEN AS SEQUEN,MOV_TMOV,MOV_IMP,MOV_IMPOST,MOV_IVA,MOV_NREGIS, MOV_NUMPRO AS NUMPRO,MOV_ANNO AS ANNO ,* FROM MOV_CONT WHERE MOV_NREGIS = '2375' AND MOV_ANNO = '2023' ORDER BY MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN

SELECT * FROM MOV_CONT WHERE MOV_ANNO = '2023' AND MOV_NREGIS = '2503      ' ORDER BY MOV_SEQUEN
--UPDATE MOV_CONT SET MOV_IVA = '058' WHERE id_unique = 'B7E9A22A-D716-4391-9E70-AB1348659574'





SELECT MOV_ANT_CAMB_SEGNO,* FROM MOV_CONT WHERE MOV_ANNO = '2023' AND MOV_NREGIS = '2533' ORDER BY MOV_SEQUEN
--UPDATE MOV_CONT SET MOV_ANT_CAMB_SEGNO = 1 WHERE ID_UNIQUE = 'D76BE6FD-27A0-4CC4-96FA-5A8D0057F386'

SELECT MOV_ANT_CAMB_SEGNO,* FROM MOV_CONT WHERE MOV_ANNO = '2023' AND MOV_NREGIS = '2583' ORDER BY MOV_SEQUEN
--UPDATE MOV_CONT SET MOV_ANT_CAMB_SEGNO = 1 WHERE ID_UNIQUE = 'C9B4609E-5FC5-41D8-B981-C186267BCC4E'

SELECT MOV_ANT_CAMB_SEGNO,* FROM MOV_CONT WHERE MOV_ANNO = '2023' AND MOV_NREGIS = '2657' ORDER BY MOV_SEQUEN
--UPDATE MOV_CONT SET MOV_ANT_CAMB_SEGNO = 1 WHERE ID_UNIQUE = 'F4971A6B-F767-4F09-9D26-71E648776C12'

SELECT MOV_ANT_CAMB_SEGNO,* FROM MOV_CONT WHERE MOV_ANNO = '2023' AND MOV_NREGIS = '2658' ORDER BY MOV_SEQUEN
--UPDATE MOV_CONT SET MOV_ANT_CAMB_SEGNO = 1 WHERE ID_UNIQUE = '22A18B18-14B0-4BBC-B5D3-AE9FB2C7C650'

      
