
-- ###### INSERIMENTO MENU DEI PREFERITI PER L'UTENTE 'SER' PER TESTARE CARICO CON PESATA

INSERT INTO PREFERITI (CHIAVE,PARENT,TEXT,EXPANDED,TAG,CODOPE,NOMOPE) VALUES ('40_','1_','Carico da Fornitore con pesata',0,'do form form\MENU_BFOPES with ''SEDE'',0 linked   ','SER','ASS. - Assistenza Project')

SELECT * FROM PREFERITI WHERE CODOPE = 'SER'
