SELECT * FROM U_RIC_TT ORDER BY RIC_PROGR DESC

SELECT * 
FROM U_RIC_TT 
WHERE RIC_CODCLI+RIC_NFATT+RIC_DTFATT IN (SELECT RIC_CODCLI+RIC_NFATT+RIC_DTFATT FROM (
SELECT RIC_CODCLI,RIC_NFATT,RIC_DTFATT,RIC_TOTFAT,SUM(RIC_TRANC) AS GIA_PRES
FROM U_RIC_TT 
WHERE RIC_RICMAN<>'S' AND RIC_TOTFAT<>0
GROUP BY RIC_CODCLI,RIC_NFATT,RIC_DTFATT,RIC_TOTFAT ) AS RIC_PRES
WHERE GIA_PRES<>RIC_TOTFAT )
ORDER BY RIC_NFATT,RIC_DTFATT,RIC_DTSCAD


SELECT RIC_CODCLI,RIC_NFATT,RIC_DTFATT FROM (
SELECT RIC_CODCLI,RIC_NFATT,RIC_DTFATT,RIC_TOTFAT,SUM(RIC_TRANC) AS GIA_PRES
FROM U_RIC_TT 
WHERE RIC_RICMAN<>'S' AND RIC_TOTFAT<>0
GROUP BY RIC_CODCLI,RIC_NFATT,RIC_DTFATT,RIC_TOTFAT ) AS RIC_PRES
WHERE GIA_PRES<>RIC_TOTFAT