	SELECT 
		OPE.CODICE AS USERID,
		OPE.DESCRI AS NOME_UTENTE,
		COALESCE(ORG.RUOLO,'') AS RUOLO,
		COALESCE(RUO.DESCRI,'') AS DESCR_RUOLO,
		COALESCE(ORG.RUOLO_SUP,'') AS RUOLO_SUP,
		COALESCE(RUOSUP.DESCRI,'') AS DESCR_RUOLO_SUP,
		AUT.VEDE_TUTTI AS VEDE_TUTTI,
		AUT.INSERIMENTO AS INSERIMENTO,
		AUT.MODIFICA AS MODIFICA,
		AUT.ANNULLO AS ANNULLO,
		AUT.STAMPA AS STAMPA,
		AUT.AUT_LIVELLO1 AS AUT_LIVELLO1,
		AUT.AUT_LIVELLO2 AS AUT_LIVELLO2,
		AUT.AUT_LIVELLO3 AS AUT_LIVELLO3,
		AUT.AUT_LIVELLO4 AS AUT_LIVELLO4,
		AUT.AUT_LIVELLO5 AS AUT_LIVELLO5,
		AUT.MOSTRA_PREZZI AS MOSTRA_PREZZI,
		AUT.MOSTRA_FORNITORI AS MOSTRA_FORNITORI,
		AUT.TES_CLIENTI AS TES_CLIENTI,
		AUT.TES_FORNITORI AS TES_FORNITORI,
		AUT.TES_RIBA AS TES_RIBA,    
		AUT.TES_F24 AS TES_F24,    
		AUT.TES_CBI AS TES_CBI,    
		AUT.TES_STIPENDI AS TES_STIPENDI
	FROM RES_OPER AS OPE
	LEFT OUTER JOIN UTENTIXRUOLI AS UXR
	ON UXR.USERID=OPE.CODICE AND OPE.SOCIETA='01'
	LEFT OUTER JOIN  ORGANIGRAMMA AS ORG
	ON ORG.RUOLO = UXR.RUOLO
	LEFT OUTER JOIN PARA AS RUO
	ON RUO.CODICE='RUO'+ORG.RUOLO
	LEFT OUTER JOIN PARA AS RUOSUP
	ON RUOSUP.CODICE='RUO'+ORG.RUOLO_SUP
	LEFT OUTER JOIN AUTORIZZAZIONI AS AUT
	ON UXR.USERID=AUT.USERID AND UXR.RUOLO=AUT.RUOLO
