---SELECT * FROM U_FAT_TT 

   		SELECT 	COALESCE(CL.CLI_RAGSOC,PA.PAR_RAGSOC) AS CLI_RAGSOC,
   				COALESCE(CL.CLI_CAP,'') AS CLI_CAP,
   				COALESCE(CL.CLI_INDIR,'') AS CLI_INDIR,
   				COALESCE(CL.CLI_LOCALI,'') AS CLI_LOCALI,
   				COALESCE(CL.CLI_AGE,'') AS CLI_AGE,
   				COALESCE(CL.CLI_AGE,'') AS AGENTE,
				SUBSTRING(PAR.LIBERA,10,1) AS RIBA,
   				PA.* 
   		FROM PART_CLI AS PA 
   		LEFT OUTER JOIN U_CLI_AN AS CL 	
   		ON SUBSTRING(PA.PAR_CODCLI,6,LEN(PA.PAR_CODCLI))=CL.CLI_CODCLI 
   		LEFT OUTER JOIN PARA AS PAR
   		ON PAR.CODICE='CPA'+PA.PAR_CODPAG 
   		WHERE PAR_CODSOC = '01'
	        AND PAR_NPROG <> 100 
        ORDER BY PAR_CODSOC,PAR_CODCLI,PAR_NPART
