	
SELECT 
	DIBA1.CODART,
	COALESCE(RUO.ART_DESCR,'') AS DESCR_CODART,
	DIBA1.CODART_SUP,
	COALESCE(RUOSUP.ART_DESCR,'') AS DESCR_CODART_SUP,
	DIBA1.QTA,
	DIBA1.UM,
	DIBA1.COSTO,
	DIBA1.PREZZO,
	DIBA1.COSTO_TOT,
	DIBA1.PREZZO_TOT 
FROM (SELECT DISTINCT
	DIT_GRUPPO AS CODART, 
	'' AS CODART_SUP,
	1 AS QTA, 
	'NR' AS UM, 
	0 AS COSTO, 
	0 AS PREZZO, 
	0 AS COSTO_TOT, 
	0 AS PREZZO_TOT 
	FROM U_DIS_TT WHERE DIT_GRUPPO NOT IN (SELECT DIS_CODART AS CODART FROM U_DIS_DD) AND DIT_GRUPPO = 'ELITURBO01'
UNION 
SELECT 
	DIBA.CODART,
	COALESCE(DIBA.CODART_SUP,'') AS CODART_SUP,
	DIBA.QTA, 
	DIBA.UM, 
	DIBA.COSTO AS COSTO, 
	DIBA.PREZZO AS PREZZO, 
	DIBA.COSTO AS COSTO_TOT, 
	DIBA.PREZZO AS PREZZO_TOT 
	FROM (SELECT 
			DD.DIS_CODART AS CODART,
			DT.DIT_GRUPPO AS CODART_SUP,
			SUM(DD.DIS_QTA) AS QTA,
			DD.DIS_UM AS UM,
			MAX(DD.DIS_COSTO) AS COSTO,
			MAX(DD.DIS_PREZZO) AS PREZZO,
			MAX(DD.DIS_COSTO)*SUM(DD.DIS_QTA) AS COSTO_TOT,
			MAX(DD.DIS_PREZZO)*SUM(DD.DIS_QTA) AS PREZZO_TOT
			FROM U_DIS_DD AS DD 
			LEFT OUTER JOIN U_DIS_TT AS DT 
			ON DD.DAGGANCIO=DT.TAGGANCIO 
			GROUP BY DD.DIS_CODART,DT.DIT_GRUPPO,DD.DIS_UM) AS DIBA
) AS DIBA1
LEFT OUTER JOIN U_ART_PR AS RUO
ON RUO.ART_CODPRI=DIBA1.CODART
LEFT OUTER JOIN U_ART_PR AS RUOSUP
ON RUOSUP.ART_CODPRI=DIBA1.CODART_SUP
ORDER BY DIBA1.CODART,DIBA1.CODART_SUP






	SELECT 
		DIBA.CODART,
		COALESCE(RUO.ART_DESCR,'') AS DESCR_CODART,
		DIBA.CODART_SUP,
		COALESCE(RUOSUP.ART_DESCR,'') AS DESCR_CODART_SUP	,	
		DIBA.QTA, 
		DIBA.UM, 
		DIBA.COSTO,
		DIBA.PREZZO,
		DIBA.COSLAI,
		DIBA.COSLAE,
		DIBA.COSMAT,
		DIBA.COSATR,
		DIBA.RICLAI,
		DIBA.RICLAE,
		DIBA.RICMAT,
		DIBA.RICATR,
		DIBA.COSTO_TOT,
		DIBA.PREZZO_TOT
	FROM (SELECT 
			DD.DIS_CODART AS CODART,
			DT.DIT_GRUPPO AS CODART_SUP,
			SUM(DD.DIS_QTA) AS QTA,
			DD.DIS_UM AS UM,
			MAX(DD.DIS_COSTO) AS COSTO,
			MAX(DD.DIS_PREZZO) AS PREZZO,
			MAX(DD.DIS_COSLAI) AS COSLAI,
			MAX(DD.DIS_COSLAE) AS COSLAE,
			MAX(DD.DIS_COSMAT) AS COSMAT,
			MAX(DD.DIS_COSATR) AS COSATR,
			MAX(DD.DIS_RICLAI) AS RICLAI,
			MAX(DD.DIS_RICLAE) AS RICLAE,
			MAX(DD.DIS_RICMAT) AS RICMAT,
			MAX(DD.DIS_RICATR) AS RICATR,
			MAX(DD.DIS_COSTO)*SUM(DD.DIS_QTA) AS COSTO_TOT,
			MAX(DD.DIS_PREZZO)*SUM(DD.DIS_QTA) AS PREZZO_TOT
			FROM U_DIS_DD AS DD 
			LEFT OUTER JOIN U_DIS_TT AS DT 
			ON DD.DAGGANCIO=DT.TAGGANCIO 
			GROUP BY DD.DIS_CODART,DT.DIT_GRUPPO,DD.DIS_UM) AS DIBA
	LEFT OUTER JOIN U_ART_PR AS RUO
	ON RUO.ART_CODPRI=DIBA.CODART
	LEFT OUTER JOIN U_ART_PR AS RUOSUP
	ON RUOSUP.ART_CODPRI=DIBA.CODART_SUP WHERE DIBA.CODART_SUP='ELITURBO01'
	ORDER BY DIBA.CODART,DIBA.CODART_SUP


--SELECT * FROM U_DIS_DD