SELECT 
	ANA.COGNOME,
	ANA.NOME,
	RAP.CONTOCONT,
	RAP.MATRICOLA,
	COALESCE(BAN.IBAN,'') AS  IBAN,
	SUBSTRING(COALESCE(BAN.IBAN,''),1,2) AS COD_NAZIONE,
	SUBSTRING(COALESCE(BAN.IBAN,''),3,2) AS CHK_DIGIT,
	SUBSTRING(COALESCE(BAN.IBAN,''),5,1) AS CIN,
	SUBSTRING(COALESCE(BAN.IBAN,''),6,5) AS ABI,
	SUBSTRING(COALESCE(BAN.IBAN,''),11,5) AS CAB,
	SUBSTRING(COALESCE(BAN.IBAN,''),16,12) AS CC 
FROM RISUMANA AS ANA
LEFT OUTER JOIN RISURAPP AS RAP
ON ANA.TAGGANCIO=RAP.DAGGANCIO AND B_INCORSO='S'
LEFT OUTER JOIN RISUBANC AS BAN
ON ANA.TAGGANCIO=BAN.DAGGANCIO AND B_RIFER='S' 
WHERE RAP.MATRICOLA='89'




SELECT 
	ANA.TAGGANCIO,
	ANA.COGNOME,
	ANA.NOME,
	RAP.MATRICOLA
FROM RISUMANA AS ANA
LEFT OUTER JOIN RISURAPP AS RAP
ON ANA.TAGGANCIO=RAP.DAGGANCIO AND B_INCORSO='S'
WHERE RAP.MATRICOLA='89'

SELECT 
	ANA.TAGGANCIO,
	ANA.COGNOME,
	ANA.NOME,
	ANA.SESSO,
	RAP.MATRICOLA
FROM RISUMANA AS ANA
LEFT OUTER JOIN RISURAPP AS RAP
ON ANA.TAGGANCIO=RAP.DAGGANCIO AND B_INCORSO='S'
ORDER BY ANA.COGNOME,ANA.NOME

SELECT * FROM RISUMANA

UPDATE RISUMANA	SET 
	SESSO='M',
	CodFiscale='',
    PartitaIva='',
	LocNascita='',
	D_Nascita='',
	LocResidenz='',
	IndResidenz='',
    CapResidenz='',
	LocDomicil='',
    IndDomicil='',
    CapDomicil='',
    TelDomicil='',
    FaxDom='',
	FaxRes='',
	TelFisso='',
	TelMobile='',
	EMail='',
    Annotazioni='',
    B_RisSociet=1,
    B_RisGruppo=0,
	B_RisEstern=0,
	UtenteIns='SER',
	D_DataIns='',
	UtenteMod='',
	D_DataMod='',
	ModPag='',
	TermPagCli='',
	TermPagFor='',
	TIPO_RISORSA='',
	IDTITOLO='',
	TELRESIDENZ='',
	IDSTATORIS='',
	NAZIONE='',
	IDSTATOCIV='',
	IDPOSMILIT='',
	PAGCLI='',
	PAGFOR='',
	PASSWORD='',
	USERID='',
	RUOLO='',
	EMAIL1='',
	EMAIL2=''
WHERE TAGGANCIO='_3DD12GHE1_3DD12GHE2_3DD12GHE3_3'



/*
SELECT * FROM U_GPP_MO 
DELETE FROM RISUBANC WHERE DAGGANCIO IN (SELECT TAGGANCIO FROM RISUMANA WHERE RTRIM(COGNOME)+' '+RTRIM(NOME)='DE STEFANI MARCO CLEMENTE')

INSERT INTO RISUBANC (DAGGANCIO,B_RIFER,ORDINE,IBAN) VALUES('_3DD12GHD1_3DD12GHD2_3DD12GHD3_3','S',1,'IT59K0504856210000000004373')
*/


-- SELECT * FROM U_GPP_MO

---UPDATE U_GPP_MO SET GPP_PAGATO=''


-- SELECT CONTO1 FROM PARA WHERE CODICE = 'TOP'+(SELECT AZI_STIPE FROM U_AZI_PA)

-- SELECT AZI_STIPE FROM U_AZI_PA


SELECT * FROM CBI_LOG 

DELETE FROM CBI_LOG