	SELECT 
		T1.ID_UNIQUE AS ID_PARTITA ,
		'STIPENDIO' AS TIPOLOGIA,
		'STIP.'+ T1.GPP_MESE + '/' + T1.GPP_ANNO + ' - '+RTRIM(T2.COGNOME)+' '+RTRIM(T2.NOME) AS ragsoc,
		SUBSTRING(T2.ANNOTAZIONI,1,13) AS codfor,
		T1.GPP_ANNO+T1.GPP_MESE AS npart,
		T1.GPP_DTSCAD AS dtscad,
		T1.GPP_DAPAGA*-1 AS nsaldo, 
		0 AS ndare ,
		T1.GPP_DAPAGA AS navere 
	FROM U_GPP_MO AS T1
	INNER JOIN (
		SELECT 
			ANA.COGNOME,
			ANA.NOME,
			ANA.ANNOTAZIONI,
			RAP.MATRICOLA,
			BAN.IBAN ,
			SUBSTRING(BAN.IBAN,1,2) AS COD_NAZIONE,
			SUBSTRING(BAN.IBAN,3,2) AS CHK_DIGIT,
			SUBSTRING(BAN.IBAN,5,1) AS CIN,
			SUBSTRING(BAN.IBAN,6,5) AS ABI,
			SUBSTRING(BAN.IBAN,11,5) AS CAB,
			SUBSTRING(BAN.IBAN,16,12) AS CC 
		FROM RISUMANA AS ANA
		LEFT OUTER JOIN RISURAPP AS RAP
		ON ANA.TAGGANCIO=RAP.DAGGANCIO AND B_INCORSO='S'
		LEFT OUTER JOIN RISUBANC AS BAN
		ON ANA.TAGGANCIO=BAN.DAGGANCIO AND B_RIFER='S' ) AS T2
		ON T1.GPP_MATRI=T2.MATRICOLA 
		WHERE T1.GPP_PAGATO <>'S'

SELECT * FROM U_GPP_MO


DELETE FROM U_GPP_MO

UPDATE U_GPP_MO SET GPP_PAGATO=''

SELECT * FROM PIANOP_DD 

SELECT * FROM PIANOP_DD WHERE DAGGANCIO IN (SELECT TAGGANCIO FROM PIANOP_TT WHERE TNUMERO='')


DELETE FROM PIANOP_DD

DELETE FROM PIANOP_TT







		SELECT 
			ANA.COGNOME,
			ANA.NOME,
			ANA.ANNOTAZIONI,
			RAP.MATRICOLA,
			BAN.IBAN ,
			SUBSTRING(BAN.IBAN,1,2) AS COD_NAZIONE,
			SUBSTRING(BAN.IBAN,3,2) AS CHK_DIGIT,
			SUBSTRING(BAN.IBAN,5,1) AS CIN,
			SUBSTRING(BAN.IBAN,6,5) AS ABI,
			SUBSTRING(BAN.IBAN,11,5) AS CAB,
			SUBSTRING(BAN.IBAN,16,12) AS CC 
		FROM RISUMANA AS ANA
		LEFT OUTER JOIN RISURAPP AS RAP
		ON ANA.TAGGANCIO=RAP.DAGGANCIO AND B_INCORSO='S'
		LEFT OUTER JOIN RISUBANC AS BAN
		ON ANA.TAGGANCIO=BAN.DAGGANCIO AND B_RIFER='S' 
		WHERE RAP.MATRICOLA='89'


SELECT * FROM PART_FOR WHERE PAR_RAGSOC LIKE 'CARTIERA%'
SELECT * FROM PART_CLI

SELECT * FROM U_FOR_AN WHERE FOR_CODCLI LIKE '%000053'

2110100000053
00000053  


select PR.ART_CODPRI + SPACE(1) + CAST('(' + RTRIM(PR.ART_DESCR) + '12345678901234567890123456789012345678901234567890123456789012345678901234567890)' AS VARCHAR(81)) AS CODICE from U_ART_PR as PR  left outer join U_ART_AN as AN on PR.ART_CODPRI = AN.ART_CODPRI 


SELECT * FROM U_AZI_PA


INSERT INTO PARA 
SELECT * FROM [AQM].[dbo].[PARA] WHERE CODICE = 'TOPACQ'

