	SELECT 
			TT.ORD_NUMORD AS ORDINE,
			TT.ORD_DATORD AS DATORD,
			TT.ORD_CODCLI AS CODCLI,
			TT.ORD_RAGSOC AS RAGCLI,
			TT.ORD_DTCONS AS DATACONS,	
			DD.ORD_CODART AS PRODOTTO,
			DD.ORD_DESART AS DESART,
			CASE DD.ORD_DARIV 
      			  WHEN 1 THEN DD.ORD_DAPROD
			         ELSE DD.ORD_NUMBOB
        		  END AS QTA,
			DD.ORD_ALTEZZ AS ALTEZZA,
			DD.ORD_LUNGHE AS LUNGHEZZA,
			DD.ORD_CODSYS AS ORD_CODSYS,
			ART.ART_GRUPRD AS GRP_PROD,
			CLI.CLI_GGEVAS AS GGEVAS,
			SUBSTRING(ART.ART_GRUPRD,2,2) AS SPESSORE,
			CASE ART.ART_MICROF 
      			  WHEN 1 THEN 'S'
				ELSE ''
        		  END AS MICROFORATO,
			DD.ORD_CODART AS CHK_ART,
			DD.ORD_ALTEZZ AS CHK_ALT,
			DD.ORD_LUNGHE AS CHK_LUN,
			CASE DD.ORD_DARIV 
      			  WHEN 1 THEN DD.ORD_DAPROD
			         ELSE DD.ORD_NUMBOB
        		  END AS CHK_BOB,
			DD.ORD_DATCON AS CHK_DTC,
			DD.ORD_DARIV AS RIVALUTA,
			DD.ORD_DAPROD AS DA_PROD
		FROM 
			U_ORD_TT AS TT,
			U_ORD_DD AS DD,
			U_ART_PR AS ART,
			U_CLI_AN AS CLI
        WHERE TT.ORD_CHIUSO = 0 
            AND DD.ORD_CHIUSO = 0 
            AND DD.ORD_CODART != '' 
            AND TT.TAGGANCIO = DD.DAGGANCIO 
            AND DD.ORD_CODART = ART.ART_CODPRI
            AND CLI.CLI_CODCLI = TT.ORD_CODCLI 					
			AND TT.ORD_DTCONS BETWEEN '2011/11/01' AND '2011/12/31'   AND TT.ORD_DATORD BETWEEN '2011/11/01' AND '2011/12/31'  
		ORDER BY 
			GRP_PROD,DATACONS ASC,ORDINE