DELETE  FROM PARA WHERE CODICE  = 'RUOU'
DELETE  FROM PARA WHERE CODICE  = 'RUOG'
DELETE  FROM PARA WHERE CODICE  = 'RUOA'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOU','Utente','',0)
INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOG','Guest','',0)
INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOA','Administrator','',0)
