  
ALTER TABLE [dbo].[LOG_UTENTI] ADD 
	[HTTP_PARAMS] [text] COLLATE Latin1_General_CI_AS NULL
GO

ALTER TABLE [dbo].[LOG_UTENTI] WITH NOCHECK ADD 
	CONSTRAINT [DF_LOG_UTENTI_HTTP_PARAMS]	DEFAULT ('') 		FOR 	[HTTP_PARAMS]
GO

UPDATE LOG_UTENTI SET HTTP_PARAMS=''

GO


