
/*
SCRIPT COMPLEMENTARE DI AGGIORNAMENTO TIPO SERIAL CODICI GRUPPI SEMILAVORATI ESTERNI IN ANAGRAFICA ARTICOLI
*/

UPDATE U_ART_AN SET ART_CODTSN = 'LOT' WHERE ART_CODPRI IN (SELECT DIT_GRUPPO FROM U_DIS_TT) AND ART_CODPRI IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_TIPOPR = 'E')

