
-- VISTA GIACENZE_FIN_CON_DATI_BANCALI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GIACENZE_FIN_CON_DATI_BANCALI]'))
	DROP VIEW [dbo].[GIACENZE_FIN_CON_DATI_BANCALI]
GO

CREATE VIEW [dbo].[GIACENZE_FIN_CON_DATI_BANCALI]  
AS

	SELECT
		MAG_CODMAG AS COD_MAGAZZINO,
		MAG_ANAART AS COD_ARTICOLO,
		MAG_DESART AS DESCRIZIONE,
		MAG_CODART AS COD_INTERNO,
		COALESCE(D5.PR5_UNIMIS,PK.PR5_UNIMIS,'') AS UM,
		MAG_GIACEN AS GIACENZA,
		MAG_ALTEZZ AS ALTEZZA,
		MAG_LUNGHE AS LUNGHEZZA,
		COALESCE(D5.PR5_NUMORD,PK.PR5_NUMORD,'') AS NUMORD,
		COALESCE(D5.PR5_DATORD,PK.PR5_DATORD,'') AS DATORD,
		COALESCE(D5.PR5_CODCLI,PK.PR5_CODCLI,'') AS CODCLI,
		COALESCE(D5.PR5_RAGSOC,PK.PR5_RAGSOC,'') AS RAGSOC,
		COALESCE(D5.PR5_PROGRE,PK.PR5_PROGRE,'') AS PROGRE,
		COALESCE((RTRIM(ISNULL(D1.PR1_NUMPRG,'')) + RTRIM(ISNULL(D2.PR2_SEQUEN,''))),PK.PR5_LOTPRD,'') AS LOTPRD,
		COALESCE(D5.PR5_NUMBAN,PK.PR5_NUMBAN,0) AS NUMBAN,
		COALESCE(D5.PR5_ALTBAN,PK.PR5_ALTBAN,0) AS ALTBAN,
		COALESCE(D5.PR5_LARBAN,PK.PR5_LARBAN,0) AS LARBAN
	FROM U_MAG_GG 
	LEFT OUTER JOIN U_PRD_D5 AS D5 ON MAG_CODART = D5.PR5_CODINT
	LEFT OUTER JOIN U_PRD_PK AS PK ON MAG_CODART = PK.PR5_CODINT
	LEFT OUTER JOIN U_PRD_D2 AS D2 ON D5.PJ_PRGPRD1 = D2.PJ_PRGPRD1 AND D5.PJ_PRGPRD2 = D2.PJ_PRGPRD2
	LEFT OUTER JOIN U_PRD_D1 AS D1 ON D5.PJ_PRGPRD1 = D1.PJ_PRGPRD1
	WHERE 
		MAG_GIACEN > 0 AND 
		MAG_CODMAG = 'FIN'

GO

