
-- VISTA ORDINATO_CLIENTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_CLIENTI]'))
	DROP VIEW [dbo].[ORDINATO_CLIENTI]
GO

CREATE VIEW [dbo].[ORDINATO_CLIENTI]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
		SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		DD.ORD_SEQUEN AS NR_RIGA,
		--DD.ORD_DATCON AS DTE_PREV_EVASIONE_RIBALTATA,
		SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_PREV_EVASIONE,
		TT.ORD_CAUS AS CAUSALE,
		COALESCE(CAUS.DESCRI,'') AS DES_CAUSALE,
		--TT.ord_TIPOLOGIA AS TIPO_ORDINE,
		--COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
		--COALESCE(CVEN_1_3.DESCRI,'') AS CANALE_VENDITA,
		--COALESCE(CVEN_1_6.DESCRI,'') AS MACROCLASSE_CLIENTE,
		--COALESCE(CVEN.DESCRI,'') AS CLASSE_CLIENTE,
		--CLI.CLI_CANVEN AS COD_COMPL_CANALE_VENDITA,
		TT.ORD_CODCLI AS CODICE_CLIENTE,
		CLI.CLI_RAGSOC AS RAGIONE_SOCIALE,	
		--COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		CLI.CLI_NAZION AS NAZIONE,
		COALESCE(CNAZION.DESCRI,'') AS DESNAZIONE,
		--CLI.CLI_ZONA AS ZONA,
		--COALESCE(CZONA.DESCRI,'') AS DESZONA,
		--CLI.CLI_PROVIN AS SUBZONA,
		--COALESCE(CC.CON_DESCR,'') AS BU,
		--COALESCE(CC_AN.CON_DESCR,'') AS BU,
		TT.ORD_SPTRAS AS SPESE_TRASPORTO,
		DD.ORD_CODART AS ARTICOLO,
		DD.ORD_DESART AS DESARTICOLO,
		DD.ORD_NOTE AS COMMENTO,
		DD.ORD_UM AS UNITA_MISURA,
		DD.ORD_ALTEZZ AS H,
		DD.ORD_LUNGHE AS L,
		DD.ORD_NUMBOB AS NR_ROTOLI,
		DD.ORD_QTAORD AS QTA_ORDINATA,
		DD.ORD_QTAEV AS QTA_EVASA,
		DD.ORD_QTAORD-DD.ORD_QTAEV AS QTA_DA_EVADERE,
		DD.ORD_CHIUSO AS CHIUSO,
		--SUBSTRING(ARTAN.ART_CODGMI,1,3) AS GRUPPO,
		--CCODGRU.DESCRI AS DESGRUPPO,
		--SUBSTRING(ARTAN.ART_CODGMI,1,6) AS FAMIGLIA,
		--CCODFAM.DESCRI AS DESFAMIGLIA,
		--ARTAN.ART_CODGMI AS SOTTOFAMIGLIA,
		--CCODMERC.DESCRI AS DESSOTTOFAMIGLIA,
		--DD.ORD_CCODET AS CENTRCOSTO,
		--COALESCE(CC.CON_DESCR,'') AS CENTRCOSTO_DESCRIZIONE,
		--CASE WHEN DD.ORD_PUBBLI = '' THEN DD.ORD_PRZNET*DD.ORD_QTAEV ELSE 0 END AS PRNETTO_EVASO,
		CASE WHEN DD.ORD_PUBBLI = '' THEN DD.ORD_PRZNET*DD.ORD_QTAORD ELSE 0 END AS PREZZO_NETTO,
		DD.ORD_SC1 AS SCONTO_1,
		DD.ORD_SC1 AS SCONTO_2,
		DD.ORD_SC1 AS SCONTO_3,
		DD.ORD_SC1 AS SCONTO_4,
		DD.ORD_SC1 AS SCONTO_5,
		DD.ORD_IVA AS COD_IVA,
		COALESCE(IVA.DESCRI,'') AS DESCR_IVA,
		CAST(COALESCE(SUBSTRING(IVA.LIBERA,1,3),'0') AS NUMERIC(3,0)) AS ALIQUOTA_IVA,
		CASE WHEN DD.ORD_PUBBLI = '' THEN DD.ORD_PRZNET*DD.ORD_QTAORD ELSE 0 END AS VALORE,
		--CASE WHEN DD.ORD_PUBBLI = '' THEN DD.ORD_PRZNET*(DD.ORD_QTAORD-DD.ORD_QTAEV) ELSE 0 END AS PRNETTO_DA_EVADERE,
		TT.ORD_VALUTA AS VALUTA,
		TT.ORD_CAMBIO AS CAMBIO,
		--CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET*DD.ORD_QTAEV ELSE 0 END AS EURO_PRNETTO_EVASO,
		CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET*DD.ORD_QTAORD ELSE 0 END AS VALORE_EURO,
		--CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET*(DD.ORD_QTAORD-DD.ORD_QTAEV) ELSE 0 END AS EURO_PRNETTO_DA_EVADERE,
		--(DD.ORD_PREZZO - DD.ORD_PRZNET)*DD.ORD_QTAORD AS SCONTO_QUANTITA,
		/*
		CAST(coalesce(stuff((select  ',' + bol.ORS_NUMORD 
                    from    u_bol_dd as bol
                    where   DD.ORD_LEGSYS = BOL.ORD_LEGSYS
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS NUM_DDT,
		CAST(coalesce(stuff((select distinct  ',' + SUBSTRING(bol.ORS_DATORD,9,2)+'/'+SUBSTRING(bol.ORS_DATORD,6,2)+'/'+SUBSTRING(bol.ORS_DATORD,1,4)
                    from    u_bol_dd as bol
                    where   DD.ORD_LEGSYS = BOL.ORD_LEGSYS
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS DATA_DDT,
		CAST(coalesce(stuff((SELECT distinct ',' + ORS_NUMORD FROM (
					select  ORS_NUMORD 
                    from    U_FAT_DD
                    where   (ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)
					UNION
					select  ORS_NUMORD 
                    from    U_FAT_DD
                    where   ORS_NUMDDT+ORS_DATDDT IN (SELECT ORS_NUMORD+ORS_DATORD FROM U_BOL_DD WHERE DD.ORD_LEGSYS = ORD_LEGSYS)
					) AS TBL
					for xml path('')
                ),1,1,''),'') AS nvarchar(127))	AS NUM_FAT,
		CAST(coalesce(stuff((SELECT distinct ',' + SUBSTRING(ORS_DATORD,9,2)+'/'+SUBSTRING(ORS_DATORD,6,2)+'/'+SUBSTRING(ORS_DATORD,1,4) FROM (
					select  ORS_DATORD 
                    from    U_FAT_DD
                    where   (ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD)
					UNION
					select  ORS_DATORD 
                    from    U_FAT_DD
                    where   ORS_NUMDDT+ORS_DATDDT IN (SELECT ORS_NUMORD+ORS_DATORD FROM U_BOL_DD WHERE DD.ORD_LEGSYS = ORD_LEGSYS)
					) AS TBL
					for xml path('')
                ),1,1,''),'') AS nvarchar(127))	AS DATA_FAT,
		*/
		CAST(coalesce(stuff((select  DISTINCT ',' + ORS_NUMORD
                    from	U_BOL_DD
					WHERE	ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD AND ORS_NUMORD <> ''
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS NUM_DDT,
		CAST(coalesce(stuff((select  DISTINCT ',' + ORS_DATORD
                    from	U_BOL_DD
					WHERE	ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD AND ORS_NUMORD <> ''
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS DATA_DDT,
		CAST(coalesce(stuff((SELECT distinct ',' + ORS_NUMORD
                    from    U_FAT_DD
                    where   ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD
					for xml path('')
                ),1,1,''),'') AS nvarchar(254))	AS NUM_FAT,
		CAST(coalesce(stuff((SELECT distinct ',' + ORS_DATORD
                    from    U_FAT_DD
                    where   ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD
					for xml path('')
                ),1,1,''),'') AS nvarchar(254))	AS DATA_FAT,
		--PR.ART_ULPCAR AS ULT_PREZZO_ACQUISTO,
		--DD.ORD_CODSYS AS CODSYS,
		TT.REG_CODOPE AS REG_CODOPE,
		TT.REG_NOMOPE AS REG_NOMOPE,
		TT.REG_DATREG AS REG_DATREG,
		TT.REG_ORAREG AS REG_ORAREG,
		TT.MOD_CODOPE AS MOD_CODOPE,
		TT.MOD_NOMOPE AS MOD_NOMOPE,
		TT.MOD_DATREG AS MOD_DATREG,
		TT.MOD_ORAREG AS MOD_ORAREG
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT
	ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR
	ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_AN AS ARTAN
	ON DD.ORD_CODART = ARTAN.ART_CODPRI
	LEFT OUTER JOIN CCOSTO AS CC
	ON DD.ORD_CCODET = CC.CON_CONTO AND TT.ORD_ANNO = CC.CON_ANNO
	LEFT OUTER JOIN U_CLI_AN AS CLI
	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	--LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	--LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	--LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	--LEFT OUTER JOIN PARA AS CZONA ON CZONA.CODICE = 'ZON'+CLI.CLI_ZONA
	LEFT OUTER JOIN PARA AS CNAZION ON CNAZION.CODICE = 'STA'+CLI.CLI_NAZION  
	--LEFT OUTER JOIN PARA AS CCODMERC ON CCODMERC.CODICE = 'GMI'+ARTAN.ART_CODGMI 
	--LEFT OUTER JOIN PARA AS CCODGRU ON CCODGRU.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,3)
	--LEFT OUTER JOIN PARA AS CCODFAM ON CCODFAM.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS CAUS ON CAUS.CODICE = 'TOP'+TT.ORD_CAUS
	--LEFT OUTER JOIN PARA AS TIPORD ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	--LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = TT.ORD_PROVIN
	--LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	--LEFT OUTER JOIN CCOSTO AS CC_AN ON CLI.CLI_CCOST1 = CC_AN.CON_CONTO AND TT.ORD_ANNO = CC_AN.CON_ANNO
	LEFT OUTER JOIN PARA AS IVA ON IVA.CODICE = 'IVA'+DD.ORD_IVA
	--WHERE DD.ORD_QTAORD<>0
	
	--UNION

	--SELECT
	--	SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
	--	SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
	--	TT.ORD_DATORD AS DATA_DOC_RIBALTATA,
	--	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_DOC,
	--	COALESCE(DD.ORD_DATCON,TT.ORD_DATORD) AS DTE_PREV_EVASIONE_RIBALTATA,
	--	SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_PREV_EVASIONE,
	--	TT.ORD_CAUS AS CAUSALE,
	--	COALESCE(CAUS.DESCRI,'') AS DES_CAUSALE,
	--	TT.ord_TIPOLOGIA AS TIPO_ORDINE,
	--	COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
	--	TT.ORD_NUMORD AS NUM_ORDINE,
	--	COALESCE(CVEN_1_3.DESCRI,'') AS CANALE_VENDITA,
	--	COALESCE(CVEN_1_6.DESCRI,'') AS MACROCLASSE_CLIENTE,
	--	COALESCE(CVEN.DESCRI,'') AS CLASSE_CLIENTE,
	--	CLI.CLI_CANVEN AS COD_COMPL_CANALE_VENDITA,
	--	TT.ORD_CODCLI AS CODICE_CLIENTE,
	--	CLI.CLI_RAGSOC AS RAGIONE_SOCIALE,	
	--	COALESCE(REGIONI.REGIONE,'') AS REGIONE,
	--	CLI.CLI_NAZION AS NAZIONE,
	--	COALESCE(CNAZION.DESCRI,'') AS DESNAZIONE,
	--	CLI.CLI_ZONA AS ZONA,
	--	COALESCE(CZONA.DESCRI,'') AS DESZONA,
	--	CLI.CLI_PROVIN AS SUBZONA,
	--	--COALESCE(CC.CON_DESCR,'') AS BU,
	--	COALESCE(CC_AN.CON_DESCR,'') AS BU,
	--	COALESCE((SELECT AZI_ARTTRA FROM U_AZI_PB),'..') AS ARTICOLO,
	--	CAST(('*'+COALESCE((SELECT ART_DESCR FROM U_ART_PR WHERE ART_CODPRI = (SELECT AZI_ARTTRA FROM U_AZI_PB)),'')) AS VARCHAR(100)) AS DESARTICOLO,
	--	SUBSTRING(ARTAN.ART_CODGMI,1,3) AS GRUPPO,
	--	CCODGRU.DESCRI AS DESGRUPPO,
	--	SUBSTRING(ARTAN.ART_CODGMI,1,6) AS FAMIGLIA,
	--	CCODFAM.DESCRI AS DESFAMIGLIA,
	--	ARTAN.ART_CODGMI AS SOTTOFAMIGLIA,
	--	CCODMERC.DESCRI AS DESSOTTOFAMIGLIA,
	--	DD.ORD_CCODET AS CENTRCOSTO,
	--	COALESCE(CC.CON_DESCR,'') AS CENTRCOSTO_DESCRIZIONE,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_SPTRAS*(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END) ELSE 0 END AS PRNETTO_EVASO,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_SPTRAS*1 ELSE 0 END AS PRNETTO_QUANTITA,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_SPTRAS*(1-(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END)) ELSE 0 END AS PRNETTO_DA_EVADERE,
	--	TT.ORD_VALUTA AS VALUTA,
	--	TT.ORD_CAMBIO AS CAMBIO,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*TT.ORD_SPTRAS*(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END) ELSE 0 END AS EURO_PRNETTO_EVASO,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*TT.ORD_SPTRAS*1 ELSE 0 END AS EURO_PRNETTO_QUANTITA,
	--	CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*TT.ORD_SPTRAS*(1-(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END)) ELSE 0 END AS EURO_PRNETTO_DA_EVADERE,
	--	0 AS SCONTO_QUANTITA,
	--	1 AS ORDINATO,
	--	(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END) AS EVASO_TOT,
	--	1-(CASE TT.ORD_CHIUSO WHEN 0 THEN 0 ELSE 1 END) AS DA_EVADERE,
	--	CAST(coalesce(stuff((select  DISTINCT ',' + ORS_NUMORD
 --                   from	U_BOL_DD
	--				WHERE	ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD AND ORS_NUMORD <> ''
 --                   for xml path('')
 --               ),1,1,''),'') AS nvarchar(254)) AS NUM_DDT,
	--	CAST(coalesce(stuff((select  DISTINCT ',' + ORS_DATORD
 --                   from	U_BOL_DD
	--				WHERE	ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD AND ORS_NUMORD <> ''
 --                   for xml path('')
 --               ),1,1,''),'') AS nvarchar(254)) AS DATA_DDT,
	--	CAST(coalesce(stuff((SELECT distinct ',' + ORS_NUMORD
 --                   from    U_FAT_DD
 --                   where   ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD
	--				for xml path('')
 --               ),1,1,''),'') AS nvarchar(254))	AS NUM_FAT,
	--	CAST(coalesce(stuff((SELECT distinct ',' + ORS_DATORD
 --                   from    U_FAT_DD
 --                   where   ORD_CODART <> '' AND ORS_NUMORC = TT.ORD_NUMORD AND ORS_DATORC = TT.ORD_DATORD
	--				for xml path('')
 --               ),1,1,''),'') AS nvarchar(254))	AS DATA_FAT,
	--	PR.ART_ULPCAR AS ULT_PREZZO_ACQUISTO,
	--	RIGHT(NEWID(),10) AS CODSYS,
	--	TT.REG_CODOPE AS REG_CODOPE,
	--	TT.REG_NOMOPE AS REG_NOMOPE,
	--	TT.REG_DATREG AS REG_DATREG,
	--	TT.REG_ORAREG AS REG_ORAREG,
	--	TT.MOD_CODOPE AS MOD_CODOPE,
	--	TT.MOD_NOMOPE AS MOD_NOMOPE,
	--	TT.MOD_DATREG AS MOD_DATREG,
	--	TT.MOD_ORAREG AS MOD_ORAREG,
	--	DD.ORD_IVA AS COD_IVA,
	--	COALESCE(IVA.DESCRI,'') AS DESCR_IVA
	--FROM U_ORD_TT AS TT
	--LEFT OUTER JOIN U_ORD_DD AS DD
	--ON TT.TAGGANCIO = DD.DAGGANCIO AND DD.ORD_SEQUEN = (SELECT TOP 1 ORD_SEQUEN FROM U_ORD_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_QTAORD <> 0 ORDER BY ORD_SEQUEN)
	--LEFT OUTER JOIN U_ART_PR AS PR
	--ON PR.ART_CODPRI = COALESCE((SELECT AZI_ARTTRA FROM U_AZI_PB),'..')
	--LEFT OUTER JOIN U_ART_AN AS ARTAN
	--ON PR.ART_CODPRI = ARTAN.ART_CODPRI
	--LEFT OUTER JOIN CCOSTO AS CC
	--ON DD.ORD_CCODET = CC.CON_CONTO AND TT.ORD_ANNO = CC.CON_ANNO
	--LEFT OUTER JOIN U_CLI_AN AS CLI
	--ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	--LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	--LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	--LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	--LEFT OUTER JOIN PARA AS CZONA ON CZONA.CODICE = 'ZON'+CLI.CLI_ZONA
	--LEFT OUTER JOIN PARA AS CNAZION ON CNAZION.CODICE = 'STA'+CLI.CLI_NAZION  
	--LEFT OUTER JOIN PARA AS CCODMERC ON CCODMERC.CODICE = 'GMI'+ARTAN.ART_CODGMI 
	--LEFT OUTER JOIN PARA AS CCODGRU ON CCODGRU.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,3)
	--LEFT OUTER JOIN PARA AS CCODFAM ON CCODFAM.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,6)
	--LEFT OUTER JOIN PARA AS CAUS ON CAUS.CODICE = 'TOP'+TT.ORD_CAUS
	--LEFT OUTER JOIN PARA AS TIPORD ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	--LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = TT.ORD_PROVIN
	--LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	--LEFT OUTER JOIN CCOSTO AS CC_AN ON CLI.CLI_CCOST1 = CC_AN.CON_CONTO AND TT.ORD_ANNO = CC_AN.CON_ANNO
	--LEFT OUTER JOIN PARA AS IVA ON IVA.CODICE = 'IVA'+DD.ORD_IVA
	--WHERE TT.ORD_SPTRAS<>0

GO

--SELECT * FROM ORDINATO WHERE ANNO = 2018 ORDER BY DATA_DOC_RIBALTATA,NUM_ORDINE