DELETE  FROM PARA WHERE CODICE LIKE 'RUO%'

INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOU','Utente','',0)
INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOC','Coordinatore','',0)
INSERT INTO PARA (CODICE,DESCRI,LIBERA,CLASSE) VALUES ('RUOA','Web administrator','',0)
