
--- AGGIORNA CONTI BOLLATO IVA ACQUISTI REVERSE CHARGE
UPDATE MOV_CONT SET MOV_CONTO ='12040006' 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FRC' ,'NFE','FAC','NFC')
	AND MOV_IVA IN ('22R','N73') 
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'

--- AGGIORNA CONTI BOLLATO IVA SPLIT PAYMENT
UPDATE MOV_CONT SET MOV_CONTO ='44010004' 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FVS' ,'NCS')
	AND MOV_IVA IN ('SP') 
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'

--- BOLLATO IVA ACQUISTI
SELECT DISTINCT MOV_IVA ,MOV_CONTO
FROM MOV_CONT 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FAE' ,'FAI','FEN','FPE','NCF','NEN')
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'


--- BOLLATO IVA ACQUISTI REVERSE CHARGE
SELECT DISTINCT MOV_IVA ,MOV_CONTO
FROM MOV_CONT 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FRC' ,'NFE','FAC','NFC')
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'



--- BOLLATO IVA VENDITE
SELECT DISTINCT MOV_IVA ,MOV_CONTO
FROM MOV_CONT 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FVC' ,'FVE','FVI','NCC','NCE','NCI')
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'


--- BOLLATO IVA VENDITE
SELECT DISTINCT MOV_IVA ,MOV_CONTO
FROM MOV_CONT 
WHERE MOV_ANNO='2015' 
	AND MOV_TOP IN ('FVS' ,'NCS')
	AND (SELECT CON_TIPOCO FROM CONTI WHERE CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO )='I'



















