SELECT 
	MOV_IMP, 
	PAR_FATT,
	MOV_NUMPRO ,
	MOV_NREGIS
FROM MOV_CONT AS MOV
LEFT OUTER JOIN PART_FOR AS PAR
ON MOV.MOV_NUMPRO = PAR.PAR_NUMPRO
WHERE 
	MOV_TOP = 'SPE' 
	AND MOV_ANNO='2015' 
	AND MOV_CONTO LIKE '08%' 
	AND MOV_TMOV='A'
	AND MOV_IMP<>PAR_FATT

