
-- LAVORARE SELEZIONANDO IL DB DI TEST


-- VERIFICA DOPPIONI CODICI IVA
SELECT CODICE, COUNT(*) AS CONTA FROM PARA WHERE CODICE LIKE 'IVA%' GROUP BY CODICE ORDER BY CONTA DESC

-- VERIFICA RECORD DOPPI PER MODIFICARE LA ROUTINE 'CARDIOLINE_DECODIFICA_CODICE_IVA' IN 'CONVERTILIB.PRG'
SELECT * FROM PARA WHERE CODICE = 'IVA280'
SELECT * FROM PARA WHERE CODICE = 'IVA2AR'

-- ESEGUIRE LA CONVERSIONE IN AMBIENTE DI TEST 

-- CONTROLLO INCROCIATO TABELLA IVA TRA AMBIENTE DI TEST ED AMBIENTE DI PRODUZIONE (VERSIONE PRECEDENTE)
SELECT * FROM PARA WHERE CODICE LIKE 'IVA%' AND CODICE NOT IN (SELECT CODICE FROM CARDIOLINE.DBO.PARA WHERE CODICE LIKE 'IVA%')

-- INSERIMENTO CODICI IVA MANCANTI IN CARDIOLINE PRODUZIONE (SELEZIONARE IL DB DI PRODUZIONE)
INSERT INTO PARA 
	SELECT * FROM Cardioline_test.DBO.PARA WHERE CODICE LIKE 'IVA%' AND CODICE NOT IN (SELECT CODICE FROM PARA WHERE CODICE LIKE 'IVA%')

-- RIVERIFICA CONTROLLO INCROCIATO TABELLA IVA TRA AMBIENTE DI TEST ED AMBIENTE DI PRODUZIONE (VERSIONE PRECEDENTE)  (RISELEZIONARE IL DB DI TEST)
SELECT * FROM PARA WHERE CODICE LIKE 'IVA%' AND CODICE NOT IN (SELECT CODICE FROM CARDIOLINE.DBO.PARA WHERE CODICE LIKE 'IVA%')
