
-- LAVORARE SELEZIONANDO IL DB DI PRODUZIONE

-- VERIFICA TOP CONTABILI MANCANTI IN AQUARIUS RISPETTO A SIGLA
select 'TOP'+CAUSCONT.CODICE,* from [10.0.18.9].CARDIOLINE.[dbo].CAUSCONT AS CAUSCONT WHERE 'TOP'+CAUSCONT.CODICE NOT IN (SELECT CODICE FROM PARA WHERE CODICE LIKE 'TOP%')

-- INSERIMENTO TOP CONTABILI MANCANTI IN AQUARIUS RISPETTO A SIGLA
insert into PARA (CODICE,DESCRI,LIBERA)
	select 
		'TOP'+CAUSCONT.CODICE AS CODICE,
		DESCRIZION AS DESCRI,
		'DS      SNSC                            SF' AS LIBERA
	from [10.0.18.9].CARDIOLINE.[dbo].CAUSCONT AS CAUSCONT WHERE 'TOP'+CAUSCONT.CODICE NOT IN (SELECT CODICE FROM PARA WHERE CODICE LIKE 'TOP%')

-- RETTIFICHE MANUALI DEI NUOVI TOP INSERITI