
-- VISTA BILANCIO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BILANCIO]'))
	DROP VIEW [dbo].[BILANCIO]
GO

CREATE VIEW [dbo].[BILANCIO]  
AS
	SELECT
		CON_POSBIL AS TIPO,
		CON_ANNO AS ANNO,
		CON_CONTO AS CONTO,
		CON_DESCR AS DESCRIZIONE,
		COALESCE((SELECT TOP 1 CON_IMP_D-CON_IMP_A FROM CONTI WHERE (CON_IMP_D > 0 OR CON_IMP_A > 0) AND CON_ANNO <> '' AND CON_CONTO = CC.CON_CONTO AND CON_ANNO = CAST((CAST(CC.CON_ANNO AS NUMERIC(4,0)) -1) AS VARCHAR(4))),0) AS SALDO_AP,
		CON_IMP_D AS DARE,
		CON_IMP_A AS AVERE,
		CON_IMP_D-CON_IMP_A AS SALDO
	FROM CONTI AS CC
	WHERE LEN(CON_CONTO) > (SELECT TOP 1 AZI_SOTTOG FROM U_AZI_AN)
GO