
-- VISTA ANAGR_CLIENTI_COMPLETA_2
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLIENTI_COMPLETA_2]'))
	DROP VIEW [dbo].[ANAGR_CLIENTI_COMPLETA_2]
GO
CREATE VIEW [dbo].[ANAGR_CLIENTI_COMPLETA_2]  
AS
	SELECT
		U_ANA_CL.CLI_CODSOC     ,
		U_ANA_CL.CLI_CODCLI     ,
		U_CLI_AN.CLI_RAGSOC     ,
		CLI_CLDOG      ,
		CLI_TISPE      ,
		CLI_SERVINTRA  ,
		CLI_ARTINTE    ,
		CLI_NOTEINT    ,
		CLI_INTUNO     ,
		CLI_INTDUE     ,
		CLI_INTTRE     ,
		CLI_ANNOPE     ,
		CLI_IMPINT     ,
		CLI_ANNOPE2    ,
		CLI_GGINTD     ,
		CLI_MMINTD     ,
		CLI_GGINTA     ,
		CLI_MMINTA     ,
		CLI_DOGANA     ,
		CLI_CLIAZI     ,
		CLI_INDAZI     ,
		CLI_CAPAZI     ,
		CLI_COMUNEAZI  ,
		CLI_PROVAZI    ,
		cli_ivasptras  ,
		CLI_NOCLDOG    ,
		CLI_FATELETT   ,
		CLI_PA         ,
		CLI_IDSDI      ,
		CLI_EPEC       ,
		CLI_FLGDPR     ,
		CLI_DTGDPR
	FROM U_ANA_CL
	LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODSOC = U_ANA_CL.CLI_CODSOC AND U_CLI_AN.CLI_CODCLI = U_ANA_CL.CLI_CODCLI
	WHERE U_ANA_CL.CLI_CODCLI NOT IN (SELECT FOR_CLICEE FROM U_FOR_AN WHERE FOR_CLICEE<>'')  -- ESCLUDE I CLIENTI PER COMPENSAZIONI, PRESENTI IN U_FOR_AN.FOR_CLICEE

GO

SELECT * FROM ANAGR_CLIENTI_COMPLETA_2 ORDER BY CLI_CODCLI