
-- VISTA BOLLATO_CLIENTI_CONTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BOLLATO_CLIENTI_CONTI]'))
	DROP VIEW [dbo].[BOLLATO_CLIENTI_CONTI]
GO

CREATE VIEW [dbo].[BOLLATO_CLIENTI_CONTI]  
AS
	SELECT 
		IVA_ANNO,
		IVA_MESE,
		IVA_DTFATT,
		IVA_NUMDOC,
		IVA_CODCLI,
		IVA_RAGSOC,
		IVA_IMPONI,
		IVA_TOTALE,
		MOV_CONTO,
		CON_DESCR,
		MOV_IMP,
		MOV_VALUTA,
		MOV_CAMBIO,
		MOV_IVA,
		MOV_IMPOST
	FROM U_IVA_CL 
	LEFT OUTER JOIN MOV_CONT ON MOV_NUMPRO IN 
		(SELECT MOV_NUMPRO FROM MOV_CONT WHERE MOV_ANNO = IVA_ANNO AND MOV_NPROT = IVA_NUMDOC AND MOV_DTDOC = IVA_DTFATT AND SUBSTRING(MOV_CONTO ,5,9) = IVA_CODCLI) 
	LEFT OUTER JOIN CONTI ON CON_ANNO = IVA_ANNO AND CON_CONTO = MOV_CONTO 
	WHERE SUBSTRING(MOV_CONTO ,5,9) <> IVA_CODCLI
GO