
-- VISTA SCADENZE_FATTURE_CLIENTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SCADENZE_FATTURE_CLIENTI]'))
	DROP VIEW [dbo].[SCADENZE_FATTURE_CLIENTI]
GO

CREATE VIEW [dbo].[SCADENZE_FATTURE_CLIENTI]  
AS

	SELECT
		SUBSTRING(PAR_DTFAT,1,4) AS ANNO,
		PAR_CODCLI AS CODCLI,
		PAR_RAGSOC AS RAGSOC,
		PAR_NPROT AS NUMFAT,
		PAR_DTFAT AS DATFAT,
		CASE FLAG_NOTAC_TOP WHEN 'S' THEN -1*PAR_FATT ELSE PAR_FATT END AS IMPORTO,
		PAR_DTSCAD AS SCADENZA,
		FLAG_NOTAC_TOP,
		PAR_CODPAG AS COND_PAG,
		DESCPA AS DESCRIZIONE_PAG,
		PAG_RIBA
	FROM (
		SELECT 
			PART.* ,
			COALESCE(CPA.DESCRI,'')  AS DESCPA ,
			COALESCE(CASE SUBSTRING(CPA.LIBERA,10,1) WHEN 'X' THEN 'SI' ELSE '' END, '') AS PAG_RIBA,
			CASE WHEN COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'') IN ('S','F','A') THEN 'FAT' ELSE 'PAG' END AS FLAG_NATURA,
			COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'') AS FLAG_NOTAC_TOP ,
			CASE WHEN PAR_NPART IN (SELECT DISTINCT PAR_NPART
										FROM PART_CLI AS PART 
										LEFT OUTER JOIN PARA AS PARTOP
										ON 'TOP'+PART.PAR_TIPFAT = PARTOP.CODICE
										WHERE PAR_NPROG<>100 
											AND COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'') IN ('S','F','A') AND COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'') <> 'S') THEN 'OK'
			
				WHEN PAR_NPART IN (SELECT DISTINCT PAR_NPART FROM
									(SELECT PAR_NPART, COUNT(*) AS CONTA_RIGHE_PARTITA FROM PART_CLI AS PART 
										WHERE PAR_NPROG<>100 GROUP BY PAR_NPART) AS TMP_PART WHERE CONTA_RIGHE_PARTITA >= 2) THEN 'OK'
			
				ELSE 'KO'
			END AS LEGATA,
			COALESCE((SELECT TOP 1 MOV_DESMOV FROM MOV_CONT WHERE MOV_NUMPRO = PART.PAR_NUMPRO AND MOV_CONTO = PART.PAR_CODCLI),'') AS MOV_DESMOV,
			COALESCE((SELECT TOP 1 MOV_NPROT FROM MOV_CONT WHERE MOV_NUMPRO = PART.PAR_NUMPRO AND MOV_CONTO = PART.PAR_CODCLI),'') AS MOV_NPROT
		FROM PART_CLI AS PART 
		LEFT OUTER JOIN PARA AS CPA
			ON 'CPA'+PART.PAR_CODPAG = CPA.CODICE 
		LEFT OUTER JOIN PARA AS PARTOP
			ON 'TOP'+PART.PAR_TIPFAT = PARTOP.CODICE
		WHERE 
		PAR_NPROG <> 100 AND 
		PAR_NPART IN (SELECT PAR_NPART FROM PART_CLI WHERE PAR_NPROT <> '') AND 
		PAR_NPART IN (SELECT PAR_NPART FROM PART_CLI WHERE PAR_DTFAT <> '')
		--ORDER BY LEGATA DESC, PAR_NPART DESC,FLAG_NATURA,PAR_DTFAT DESC, PAR_DTREG DESC
		) AS MAIN
	WHERE FLAG_NATURA = 'FAT' AND SUBSTRING(PAR_DTSCAD,5,1) = '/' AND SUBSTRING(PAR_DTSCAD,8,1) = '/'

GO
