-- VISTA GIACENZE_DA_VERIFICARE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GIACENZE_DA_VERIFICARE]'))
	DROP VIEW [dbo].[GIACENZE_DA_VERIFICARE]
GO

CREATE VIEW [dbo].[GIACENZE_DA_VERIFICARE]  
AS

	SELECT
		MAG_CODMAG AS COD_MAGAZZINO,
		MAG_ANAART AS COD_ARTICOLO,
		MAG_DESART AS DESCRIZIONE,
		MAG_CODART AS COD_INTERNO,
		MAG_ALTEZZ AS ALTEZZA,
		MAG_LUNGHE AS LUNGHEZZA
	FROM U_MAG_GG 
	WHERE 
		MAG_GIACEN > 0 AND 
		MAG_CODART LIKE '%.6%' AND MAG_NRLINT BETWEEN 60000000 AND 69999999 AND 
		MAG_CODART IN (SELECT MOV_CODART FROM U_MAG_MO WHERE MOV_TOP = 'CAP') AND
		MAG_CODART NOT IN (SELECT PR5_CODINT FROM U_PRD_D5 UNION SELECT PR5_CODINT FROM U_PRD_PK)

	UNION

	SELECT
		MAG_CODMAG AS COD_MAGAZZINO,
		MAG_ANAART AS COD_ARTICOLO,
		MAG_DESART AS DESCRIZIONE,
		MAG_CODART AS COD_INTERNO,
		MAG_ALTEZZ AS ALTEZZA,
		MAG_LUNGHE AS LUNGHEZZA
	FROM U_MAG_GG 
	WHERE 
		MAG_GIACEN > 0 AND 
		MAG_CODART LIKE '%.4%' AND MAG_NRLINT BETWEEN 40000000 AND 49999999 AND 
		MAG_CODART IN (SELECT MOV_CODART FROM U_MAG_MO WHERE MOV_TOP = 'CAP') AND
		MAG_CODART NOT IN (SELECT PR4_CODINT FROM U_PRD_D4)

GO
