-- VISTA FATTURE_E_DDT_DA_FATTURARE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_E_DDT_DA_FATTURARE]'))
	DROP VIEW [dbo].[FATTURE_E_DDT_DA_FATTURARE]
GO

CREATE VIEW [dbo].[FATTURE_E_DDT_DA_FATTURARE]  
AS

	SELECT 
		'INVOICE' AS TYPE,
		TT.ORD_NUMORD AS DOC_NO,
		TT.ORD_DATORD AS DOC_DATE,
		TT.ORD_CODCLI AS CUSTOMER_CODE,
		TT.ORD_RAGSOC AS CUSTOMER_NAME,
		COALESCE(P_STA.DESCRI,'') AS COUNTRY,
		CAST(ROUND(TT.ORD_IMPONIB * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAXABLE_EUR,
		CAST(ROUND(TT.ORD_IMPOSTA * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAX_EUR,
		CAST(ROUND(TT.ORD_VALORE * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TOTAL_EUR
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN PARA AS P_STA ON P_STA.CODICE = 'STA'+TT.ORD_CODNAZ
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	WHERE SUBSTRING(P_TOP.LIBERA,20,1) <> 'S'

	UNION

	SELECT 
		'CREDIT NOTE' AS TYPE,
		TT.ORD_NUMORD AS DOC_NO,
		TT.ORD_DATORD AS DOC_DATE,
		TT.ORD_CODCLI AS CUSTOMER_CODE,
		TT.ORD_RAGSOC AS CUSTOMER_NAME,
		COALESCE(P_STA.DESCRI,'') AS COUNTRY,
		-1 * CAST(ROUND(TT.ORD_IMPONIB * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAXABLE_EUR,
		-1 * CAST(ROUND(TT.ORD_IMPOSTA * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAX_EUR,
		-1 * CAST(ROUND(TT.ORD_VALORE * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TOTAL_EUR
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN PARA AS P_STA ON P_STA.CODICE = 'STA'+TT.ORD_CODNAZ
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	WHERE SUBSTRING(P_TOP.LIBERA,20,1) = 'S'

	UNION

	SELECT 
		'DELIVERY NOTE' AS TYPE,
		TT.ORD_NUMORD AS DOC_NO,
		TT.ORD_DATORD AS DOC_DATE,
		TT.ORD_CODCLI AS CUSTOMER_CODE,
		TT.ORD_RAGSOC AS CUSTOMER_NAME,
		COALESCE(P_STA.DESCRI,'') AS COUNTRY,
		CAST(ROUND(TT.ORD_IMPONIB * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAXABLE_EUR,
		CAST(ROUND(TT.ORD_IMPOSTA * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TAX_EUR,
		CAST(ROUND(TT.ORD_VALORE * TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TOTAL_EUR
	FROM U_BOL_TT AS TT
	LEFT OUTER JOIN PARA AS P_STA ON P_STA.CODICE = 'STA'+TT.ORD_CODNAZ
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	WHERE SUBSTRING(P_TOP.LIBERA,2,1) = 'V' AND TT.ORD_FLBOL <> 'S'

GO
