
DELETE FROM U_AZI_AN
DELETE FROM U_AZI_PA
DELETE FROM U_AZI_PB


INSERT INTO L3A.[dbo].U_AZI_AN
	select * from CARDIOLINE.[dbo].U_AZI_AN
SELECT * FROM CARDIOLINE.[dbo].U_AZI_AN

INSERT INTO L3A.[dbo].U_AZI_PA
	select * from CARDIOLINE.[dbo].U_AZI_PA
SELECT * FROM CARDIOLINE.[dbo].U_AZI_PA

INSERT INTO L3A.[dbo].U_AZI_PB
	select * from CARDIOLINE.[dbo].U_AZI_PB
SELECT * FROM CARDIOLINE.[dbo].U_AZI_PB
