
SELECT MOV_DATORI,* FROM U_MAG_MO WHERE MOV_DTDOCU >= '2014/09/01' AND MOV_DOCMOD = 0 AND MOV_ANAART LIKE '%LDPE%' AND MOV_DTREGI < MOV_DTDOCU
ORDER BY MOV_DTREGI

--/*
UPDATE U_MAG_MO SET MOV_DATORI = MOV_DTREGI WHERE ID_UNIQUE IN 
(SELECT ID_UNIQUE FROM U_MAG_MO WHERE MOV_DTDOCU >= '2014/09/01' AND MOV_DOCMOD = 0 AND MOV_ANAART LIKE '%LDPE%' AND MOV_DTREGI < MOV_DTDOCU)

UPDATE U_MAG_MO SET MOV_DTREGI = MOV_DTDOCU WHERE ID_UNIQUE IN 
(SELECT ID_UNIQUE FROM U_MAG_MO WHERE MOV_DTDOCU >= '2014/09/01' AND MOV_DOCMOD = 0 AND MOV_ANAART LIKE '%LDPE%' AND MOV_DTREGI < MOV_DTDOCU)

UPDATE U_MAG_GG SET MAG_DATAGG = (SELECT TOP 1 MOV_DTREGI FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = U_MAG_GG.MAG_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) WHERE MAG_LEGAME IN 
	(SELECT MOV_LEGAME FROM U_MAG_MO WHERE MOV_DTDOCU >= '2014/09/01' AND MOV_DATORI <> '' and mov_legame in (select mag_legame from u_mag_gg))

--*/

SELECT MOV_DATORI,* FROM U_MAG_MO WHERE MOV_DTDOCU >= '2014/09/01' AND MOV_DATORI <> ''
and mov_legame in (select mag_legame from u_mag_gg)
ORDER BY MOV_DTREGI
