
ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_cli_ivasptras]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_PROVAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_COMUNEAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_CAPAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_INDAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_CLIAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_DOGANA]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_MMINTA]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_GGINTA]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_MMINTD]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_GGINTD]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE2]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_IMPINT]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_INTTRE]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_INTDUE]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_INTUNO]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_NOTEINT]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_ARTINTE]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_UFFIVA]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_SERVINTRA]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_TISPE]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_CLDOG]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_CODCLI]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_CLI_CODSOC]
GO

ALTER TABLE [dbo].[U_ANA_CL] DROP CONSTRAINT [DF_U_ANA_CL_id_unique]
GO

/****** Object:  Table [dbo].[U_ANA_CL]    Script Date: 13/03/2014 17.17.21 ******/
DROP TABLE [dbo].[U_ANA_CL]
GO

/****** Object:  Table [dbo].[U_ANA_CL]    Script Date: 13/03/2014 17.17.21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_ANA_CL](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[CLI_CODSOC] [varchar](2) NULL,
	[CLI_CODCLI] [varchar](10) NULL,
	[CLI_CLDOG] [varchar](16) NULL,
	[CLI_TISPE] [varchar](3) NULL,
	[CLI_SERVINTRA] [varchar](10) NULL,
	[CLI_UFFIVA] [varchar](25) NULL,
	[CLI_ARTINTE] [varchar](3) NULL,
	[CLI_NOTEINT] [text] NULL,
	[CLI_INTUNO] [varchar](2) NULL,
	[CLI_INTDUE] [varchar](2) NULL,
	[CLI_INTTRE] [varchar](2) NULL,
	[CLI_ANNOPE] [varchar](4) NULL,
	[CLI_IMPINT] [numeric](17, 3) NULL,
	[CLI_ANNOPE2] [varchar](4) NULL,
	[CLI_GGINTD] [varchar](2) NULL,
	[CLI_MMINTD] [varchar](2) NULL,
	[CLI_GGINTA] [varchar](2) NULL,
	[CLI_MMINTA] [varchar](2) NULL,
	[CLI_DOGANA] [varchar](25) NULL,
	[CLI_CLIAZI] [varchar](50) NULL,
	[CLI_INDAZI] [varchar](50) NULL,
	[CLI_CAPAZI] [varchar](10) NULL,
	[CLI_COMUNEAZI] [varchar](35) NULL,
	[CLI_PROVAZI] [varchar](3) NULL,
	[cli_ivasptras] [varchar](3) NULL,
 CONSTRAINT [PK_U_ANA_CL] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_CODSOC]  DEFAULT ('') FOR [CLI_CODSOC]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_CODCLI]  DEFAULT ('') FOR [CLI_CODCLI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_CLDOG]  DEFAULT ('') FOR [CLI_CLDOG]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_TISPE]  DEFAULT ('') FOR [CLI_TISPE]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_SERVINTRA]  DEFAULT ('') FOR [CLI_SERVINTRA]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_UFFIVA]  DEFAULT ('') FOR [CLI_UFFIVA]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_ARTINTE]  DEFAULT ('') FOR [CLI_ARTINTE]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_NOTEINT]  DEFAULT ('') FOR [CLI_NOTEINT]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_INTUNO]  DEFAULT ('') FOR [CLI_INTUNO]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_INTDUE]  DEFAULT ('') FOR [CLI_INTDUE]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_INTTRE]  DEFAULT ('') FOR [CLI_INTTRE]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE]  DEFAULT ('') FOR [CLI_ANNOPE]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_IMPINT]  DEFAULT ((0)) FOR [CLI_IMPINT]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_ANNOPE2]  DEFAULT ('') FOR [CLI_ANNOPE2]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_GGINTD]  DEFAULT ('') FOR [CLI_GGINTD]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_MMINTD]  DEFAULT ('') FOR [CLI_MMINTD]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_GGINTA]  DEFAULT ('') FOR [CLI_GGINTA]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_MMINTA]  DEFAULT ('') FOR [CLI_MMINTA]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_DOGANA]  DEFAULT ('') FOR [CLI_DOGANA]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_CLIAZI]  DEFAULT ('') FOR [CLI_CLIAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_INDAZI]  DEFAULT ('') FOR [CLI_INDAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_CAPAZI]  DEFAULT ('') FOR [CLI_CAPAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_COMUNEAZI]  DEFAULT ('') FOR [CLI_COMUNEAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_CLI_PROVAZI]  DEFAULT ('') FOR [CLI_PROVAZI]
GO

ALTER TABLE [dbo].[U_ANA_CL] ADD  CONSTRAINT [DF_U_ANA_CL_cli_ivasptras]  DEFAULT ('') FOR [cli_ivasptras]
GO


