
ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOUPPER]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_RICFLD]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_STBIL_DA_MOV_CONT]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_GNELAU]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_QUOAMM]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_DOCFAT ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_DOCFAP ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_DOCOFF ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_REGISTRA_TOOLBAR ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_MAGPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_MAGPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_PMILINSE]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_PMILINSL]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_PMILINPF]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_SCPPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CAPPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_SCPPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CAPPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_IVADEDU ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_TIMEEV ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_PLAFACQ ]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOR]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFT]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFP]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALSCBO]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOF]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPIART]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CALCSCO]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPIORD]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_azi_nodatispe]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_azi_noskaltrid]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_azi_ivaintra]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_DOCORD]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_DOCDDT]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_ANAART]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPICLI]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOCONTI]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_NOSKPROD]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_AZI_CODSOC]
GO

ALTER TABLE [dbo].[U_AZI_PB] DROP CONSTRAINT [DF_U_AZI_PB_id_unique]
GO

/****** Object:  Table [dbo].[U_AZI_PB]    Script Date: 13/03/2014 17.18.29 ******/
DROP TABLE [dbo].[U_AZI_PB]
GO

/****** Object:  Table [dbo].[U_AZI_PB]    Script Date: 13/03/2014 17.18.29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[U_AZI_PB](
	[id_unique] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[AZI_CODSOC] [varchar](2) NULL,
	[AZI_NOSKPROD] [bit] NULL,
	[AZI_NOCONTI] [bit] NULL,
	[AZI_NOCAMPICLI] [bit] NULL,
	[AZI_ANAART] [bit] NULL,
	[AZI_DOCDDT] [bit] NULL,
	[AZI_DOCORD] [bit] NULL,
	[azi_ivaintra] [bit] NULL,
	[azi_noskaltrid] [bit] NULL,
	[azi_nodatispe] [bit] NULL,
	[AZI_NOCAMPIORD] [bit] NULL,
	[AZI_CALCSCO] [bit] NULL,
	[AZI_NOCAMPIART] [bit] NULL,
	[AZI_CALSCOF] [bit] NULL,
	[AZI_CALSCBO] [bit] NULL,
	[AZI_CALSCFP] [bit] NULL,
	[AZI_CALSCFT] [bit] NULL,
	[AZI_CALSCOR] [bit] NULL,
	[AZI_PLAFACQ] [bit] NULL,
	[AZI_TIMEEV] [numeric](4, 0) NULL,
	[AZI_IVADEDU] [bit] NULL,
	[AZI_CAPPMIPREL] [varchar](3) NULL,
	[AZI_SCPPMIPREL] [varchar](3) NULL,
	[AZI_CAPPMIVERS] [varchar](3) NULL,
	[AZI_SCPPMIVERS] [varchar](3) NULL,
	[AZI_PMILINPF] [varchar](3) NULL,
	[AZI_PMILINSL] [varchar](3) NULL,
	[AZI_PMILINSE] [varchar](3) NULL,
	[AZI_MAGPMIPREL] [varchar](6) NULL,
	[AZI_MAGPMIVERS] [varchar](6) NULL,
	[AZI_REGISTRA_TOOLBAR] [bit] NULL,
	[AZI_DOCOFF] [bit] NULL,
	[AZI_DOCFAP] [bit] NULL,
	[AZI_DOCFAT] [bit] NULL,
	[AZI_QUOAMM] [varchar](3) NULL,
	[AZI_GNELAU] [bit] NULL,
	[AZI_STBIL_DA_MOV_CONT] [bit] NULL,
	[AZI_RICFLD] [bit] NULL,
	[AZI_NOUPPER] [bit] NULL,
 CONSTRAINT [PK_U_AZI_PB] PRIMARY KEY CLUSTERED 
(
	[id_unique] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_id_unique]  DEFAULT (newid()) FOR [id_unique]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CODSOC]  DEFAULT ('') FOR [AZI_CODSOC]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOSKPROD]  DEFAULT ((0)) FOR [AZI_NOSKPROD]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOCONTI]  DEFAULT ((0)) FOR [AZI_NOCONTI]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPICLI]  DEFAULT ((0)) FOR [AZI_NOCAMPICLI]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_ANAART]  DEFAULT ((0)) FOR [AZI_ANAART]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_DOCDDT]  DEFAULT ((0)) FOR [AZI_DOCDDT]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_DOCORD]  DEFAULT ((0)) FOR [AZI_DOCORD]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_azi_ivaintra]  DEFAULT ((0)) FOR [azi_ivaintra]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_azi_noskaltrid]  DEFAULT ((0)) FOR [azi_noskaltrid]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_azi_nodatispe]  DEFAULT ((0)) FOR [azi_nodatispe]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPIORD]  DEFAULT ((0)) FOR [AZI_NOCAMPIORD]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALCSCO]  DEFAULT ((0)) FOR [AZI_CALCSCO]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOCAMPIART]  DEFAULT ((0)) FOR [AZI_NOCAMPIART]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOF]  DEFAULT ((0)) FOR [AZI_CALSCOF]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALSCBO]  DEFAULT ((0)) FOR [AZI_CALSCBO]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFP]  DEFAULT ((0)) FOR [AZI_CALSCFP]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALSCFT]  DEFAULT ((0)) FOR [AZI_CALSCFT]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CALSCOR]  DEFAULT ((0)) FOR [AZI_CALSCOR]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_PLAFACQ ]  DEFAULT ((0)) FOR [AZI_PLAFACQ]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_TIMEEV ]  DEFAULT ((0)) FOR [AZI_TIMEEV]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_IVADEDU ]  DEFAULT ((0)) FOR [AZI_IVADEDU]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CAPPMIPREL]  DEFAULT ('') FOR [AZI_CAPPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_SCPPMIPREL]  DEFAULT ('') FOR [AZI_SCPPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_CAPPMIVERS]  DEFAULT ('') FOR [AZI_CAPPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_SCPPMIVERS]  DEFAULT ('') FOR [AZI_SCPPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_PMILINPF]  DEFAULT ('') FOR [AZI_PMILINPF]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_PMILINSL]  DEFAULT ('') FOR [AZI_PMILINSL]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_PMILINSE]  DEFAULT ('') FOR [AZI_PMILINSE]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_MAGPMIPREL]  DEFAULT ('') FOR [AZI_MAGPMIPREL]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_MAGPMIVERS]  DEFAULT ('') FOR [AZI_MAGPMIVERS]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_REGISTRA_TOOLBAR ]  DEFAULT ((0)) FOR [AZI_REGISTRA_TOOLBAR]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_DOCOFF ]  DEFAULT ((0)) FOR [AZI_DOCOFF]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_DOCFAP ]  DEFAULT ((0)) FOR [AZI_DOCFAP]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_DOCFAT ]  DEFAULT ((0)) FOR [AZI_DOCFAT]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_QUOAMM]  DEFAULT ('') FOR [AZI_QUOAMM]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_GNELAU]  DEFAULT ((0)) FOR [AZI_GNELAU]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_STBIL_DA_MOV_CONT]  DEFAULT ((0)) FOR [AZI_STBIL_DA_MOV_CONT]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_RICFLD]  DEFAULT ((0)) FOR [AZI_RICFLD]
GO

ALTER TABLE [dbo].[U_AZI_PB] ADD  CONSTRAINT [DF_U_AZI_PB_AZI_NOUPPER]  DEFAULT ((0)) FOR [AZI_NOUPPER]
GO


