
UPDATE U_CLI_AN SET CLI_NOTSPE = 
'ETIC_STAMPA_NR_LOTTO:SI;
ETIC_STAMPA_NR_PRODUZIONE:SI;
ETIC_STAMPA_CLIENTE:SI;
ETIC_STAMPA_ARTICOLO:SI;
ETIC_STAMPA_ALTEZZA:SI;
ETIC_STAMPA_LUNGHEZZA:SI;
ETIC_STAMPA_DATA:SI;'
WHERE SUBSTRING(CLI_NOTSPE,1,1000) = ''

SELECT CLI_NOTSPE,CLI_CODCLI,CLI_RAGSOC FROM U_CLI_AN ORDER BY CLI_RAGSOC