
-- VISTA ANAGR_FORNITORI_SINTETICA
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_FORNITORI_SINTETICA]'))
	DROP VIEW [dbo].[ANAGR_FORNITORI_SINTETICA]
GO
CREATE VIEW [dbo].[ANAGR_FORNITORI_SINTETICA]  
AS

	SELECT
		FOR_CODCLI AS COD_CLIENTE,
		FOR_RAGSOC AS RAG_SOCIALE,
		FOR_INDIR AS INDIRIZZO,
		FOR_CAP AS CAP,
		FOR_LOCALI AS COMUNE,
		FOR_PROVIN AS PROVIN,
		FOR_NAZION AS NAZIONE,
		FOR_CODFIS AS COD_FISCALE,
		FOR_PARIVA AS PARTITA_IVA,
		FOR_EMAIL AS E_MAIL,
		FOR_TELEFO AS TELEFONO,
		FOR_CONPAG AS COD_COND_PAGAMENTO,
		COALESCE(PARA_CPA.DESCRI,'') AS DESCR_COND_PAGAMENTO,
		FOR_ZONA AS COD_ZONA,
		COALESCE(PARA_ZON.DESCRI,'') AS DESCR_ZONA,
		FOR_AGE AS COD_AGENTE,
		COALESCE(PARA_AGE.DESCRI,'') AS DESCR_AGENTE,
		FOR_BAE AS COD_BANCA_RIBA,
		COALESCE(BAE.BAN_DESBAN,'') AS DESCR_BANCA_RIBA,
		FOR_BA2 AS COD_BANCA_BONIFICI,
		COALESCE(BAEFOR.BAN_DESBAN,'') AS DESCR_BANCA_BONIFICI
	FROM U_FOR_AN
	LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+FOR_CONPAG
	LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+FOR_ZONA
	LEFT OUTER JOIN PARA AS PARA_AGE ON PARA_AGE.CODICE = 'AGE'+FOR_AGE
	LEFT OUTER JOIN U_BAN_AN AS BAE ON BAE.BAN_CODBAN = FOR_BAE
	LEFT OUTER JOIN U_BAN_AN AS BAEFOR ON BAEFOR.BAN_CODBAN = FOR_BA2
GO

SELECT * FROM ANAGR_FORNITORI_SINTETICA ORDER BY RAG_SOCIALE
