
-- VISTA ANAGRAFICA_ARTICOLI_RIDOTTA
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA]
GO

/*
-	Codice articolo
-	Descrizione articolo
-	Colore
-	Spessore film
-	Spessore prodotto
-	Data inserimento
-	operatore
-	Data modifica
-	Operatore
*/

CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA] 
AS
	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		PR.ART_CODCOL AS COD_COLORE,
		COALESCE(P_COL.DESCRI,'') AS DESCR_COLORE,
		AN.ART_SPEPOL AS SPESSORE_FILM,
		PR.ART_SPESSO AS SPESSORE_PRODOTTO,
		AN.REG_DATREG AS DATA_INS,
		AN.REG_CODOPE AS OPER_INS,
		AN.MOD_DATREG AS DATA_MOD,
		AN.REG_CODOPE AS OPER_MOD
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS P_COL ON P_COL.CODICE = 'COL'+PR.ART_CODCOL
	WHERE 
		ART_OBSOL <> 'S'
GO

SELECT * FROM ANAGRAFICA_ARTICOLI_RIDOTTA ORDER BY COD_ARTICOLO
