
-- VISTA ANAGR_CLIENTI_SINTETICA
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLIENTI_SINTETICA]'))
	DROP VIEW [dbo].[ANAGR_CLIENTI_SINTETICA]
GO
CREATE VIEW [dbo].[ANAGR_CLIENTI_SINTETICA]  
AS

	SELECT
		CLI_CODCLI AS COD_CLIENTE,
		CLI_RAGSOC AS RAG_SOCIALE,
		CLI_INDIR AS INDIRIZZO,
		CLI_CAP AS CAP,
		CLI_LOCALI AS COMUNE,
		CLI_PROVIN AS PROVIN,
		CLI_NAZION AS NAZIONE,
		CLI_CODFIS AS COD_FISCALE,
		CLI_PARIVA AS PARTITA_IVA,
		CLI_EMAIL AS E_MAIL,
		CLI_TELEFO AS TELEFONO,
		CLI_CONPAG AS COD_COND_PAGAMENTO,
		COALESCE(PARA_CPA.DESCRI,'') AS DESCR_COND_PAGAMENTO,
		CLI_ZONA AS COD_ZONA,
		COALESCE(PARA_ZON.DESCRI,'') AS DESCR_ZONA,
		CLI_AGE AS COD_AGENTE,
		COALESCE(PARA_AGE.DESCRI,'') AS DESCR_AGENTE,
		CLI_BAE AS COD_BANCA_CLIENTE,
		COALESCE(BAE.BAN_DESBAN,'') AS DESCR_BANCA_CLIENTE,
		CLI_BAEFOR AS COD_BANCA_FORNITORE,
		COALESCE(BAEFOR.BAN_DESBAN,'') AS DESCR_BANCA_FORNITORE,
		CLI_DTCLOK AS DT_BLOCCO_FORN
	FROM U_CLI_AN
	LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+CLI_CONPAG
	LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+CLI_ZONA
	LEFT OUTER JOIN PARA AS PARA_AGE ON PARA_AGE.CODICE = 'AGE'+CLI_AGE
	LEFT OUTER JOIN U_BAN_AN AS BAE ON BAE.BAN_CODBAN = CLI_BAE
	LEFT OUTER JOIN U_BAN_AN AS BAEFOR ON BAEFOR.BAN_CODBAN = CLI_BAEFOR
GO

SELECT * FROM ANAGR_CLIENTI_SINTETICA ORDER BY RAG_SOCIALE
