-- VISTA CONFRONTO VALORE RIEPILOGO ORDINATO CON LISTINO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[RIEPILOGO_ORDINATO_LISTINO]'))
	DROP VIEW [dbo].[RIEPILOGO_ORDINATO_LISTINO]
GO

CREATE VIEW [dbo].[RIEPILOGO_ORDINATO_LISTINO]  
AS

SELECT
	ANNO,
	MESE,
	CASE MESE
		WHEN '01' THEN 'GEN'
		WHEN '02' THEN 'FEB'
		WHEN '03' THEN 'MAR'
		WHEN '04' THEN 'APR'
		WHEN '05' THEN 'MAG'
		WHEN '06' THEN 'GIU'
		WHEN '07' THEN 'LUG'
		WHEN '08' THEN 'AGO'
		WHEN '09' THEN 'SET'
		WHEN '10' THEN 'OTT'
		WHEN '11' THEN 'NOV'
		WHEN '12' THEN 'DIC'
		ELSE '???'
	END + ' ' + ANNO AS DESCR_MESE_ANNO,
	SUM(IMPORTO_EFFETTIVO) AS IMPORTO_EFFETTIVO,
	SUM(IMPORTO_DA_LISTINO) AS IMPORTO_DA_LISTINO,
	SUM((IMPORTO_EFFETTIVO - IMPORTO_DA_LISTINO)) AS DIFFERENZA
FROM (
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		DD.ORD_PRZNET * DD.ORD_QTAORD AS IMPORTO_EFFETTIVO,
		--(SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = TT.ORD_CODCLI AND LIS_CODART = DD.ORD_CODART AND TT.ORD_DATORD BETWEEN LIS_DATLIS AND LIS_ALLIST) AS PREZZO_LISTINO_CODART,
		--(SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = TT.ORD_CODCLI AND LIS_CODART = DD.ORD_CDAPRD AND TT.ORD_DATORD BETWEEN LIS_DATLIS AND LIS_ALLIST) AS PREZZO_LISTINO_CDAPRD,
		COALESCE(COALESCE((SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = TT.ORD_CODCLI AND LIS_CODART = DD.ORD_CDAPRD AND TT.ORD_DATORD BETWEEN LIS_DATLIS AND LIS_ALLIST),
			(SELECT TOP 1 LIS_PREZZO FROM U_LIS_TT WHERE LIS_CODCLI = TT.ORD_CODCLI AND LIS_CODART = DD.ORD_CODART AND TT.ORD_DATORD BETWEEN LIS_DATLIS AND LIS_ALLIST)),
				DD.ORD_PRZNET) * DD.ORD_QTAORD AS IMPORTO_DA_LISTINO,
		DAGGANCIO,ORD_CODART,ORD_CDAPRD,ORD_NUMORD,ORD_CODCLI
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	WHERE ORD_DESART <> '*** COMMENTO ***' AND ORD_CODART <> '' --AND DD.ORD_CDAPRD <> DD.ORD_CODART
	) AS MAIN
GROUP BY ANNO,MESE


GO

