-- VISTA RIEPILOGO ORDINATO GUADAGNO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[RIEPILOGO_GUADAGNO_ORDINATO]'))
	DROP VIEW [dbo].[RIEPILOGO_GUADAGNO_ORDINATO]
GO

CREATE VIEW [dbo].[RIEPILOGO_GUADAGNO_ORDINATO]  
AS

SELECT
	ANNO,
	MESE,
	CASE MESE
		WHEN '01' THEN 'GEN'
		WHEN '02' THEN 'FEB'
		WHEN '03' THEN 'MAR'
		WHEN '04' THEN 'APR'
		WHEN '05' THEN 'MAG'
		WHEN '06' THEN 'GIU'
		WHEN '07' THEN 'LUG'
		WHEN '08' THEN 'AGO'
		WHEN '09' THEN 'SET'
		WHEN '10' THEN 'OTT'
		WHEN '11' THEN 'NOV'
		WHEN '12' THEN 'DIC'
		ELSE '???'
	END + ' ' + ANNO AS DESCR_MESE_ANNO,
	SUM(IMPORTO_RICAVO) AS IMPORTO_RICAVO,
	SUM(IMPORTO_COSTO) AS IMPORTO_COSTO,
	SUM((IMPORTO_RICAVO - IMPORTO_COSTO)) AS IMPORTO_GUADAGNO
FROM (
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		DD.ORD_PRZNET AS PREZZO_RICAVO,
		PR.ART_PRZCOS AS PREZZO_COSTO,
		DD.ORD_PRZNET * DD.ORD_QTAORD AS IMPORTO_RICAVO,
		PR.ART_PRZCOS * DD.ORD_QTAORD AS IMPORTO_COSTO
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = DD.ORD_CODART
	WHERE ORD_DESART <> '*** COMMENTO ***' AND ORD_CODART <> ''
	) AS MAIN
GROUP BY ANNO,MESE


GO

