
-- AGGIORNAMENTO FLAG DI ART_GRUPPO IN ANAGRAFICA, IN BASE ALL'ESISTENZA DELLA DI.BA.

UPDATE U_ART_PR SET ART_GRUPPO = 0 

UPDATE U_ART_PR SET ART_GRUPPO = 1 WHERE ART_CODPRI IN(SELECT DIT_GRUPPO FROM U_DIS_TT)
--SELECT * FROM  U_ART_PR WHERE ART_CODPRI IN(SELECT DIT_GRUPPO FROM U_DIS_TT)


