--- INSERT INTO PARAOLD SELECT * FROM IMPRESIND_TEST.[DBO].PARAOLD



/*********************************************
NAZIONI
*********************************************/
--- CONTROLLO NAZIONI NON PRESENTI IN VECCHIO PARA ---
SELECT * FROM PARA
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'STA%'

--- CONTRO-VERIFICA NAZIONI PRESENTI IN VECCHIO PARA ---
SELECT * FROM PARA
WHERE CODICE IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'STA%'


--- CONTROLLO NAZIONI NON PRESENTI IN VECCHIO PARA ---
--- PRESENTI IN DOCUMENTI


SELECT CODICE FROM PARA
--DELETE FROM PARA 
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'STA%'
AND CODICE NOT IN (SELECT 'STA'+ORD_CODNAZ FROM U_ORD_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>'') 
AND CODICE NOT IN (SELECT 'STA'+ORD_CODNAZ FROM U_BOL_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>'')
AND CODICE NOT IN (SELECT 'STA'+ORD_CODNAZ FROM U_FAT_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>'')
AND CODICE NOT IN (SELECT 'STA'+ORD_CODNAZ FROM U_FAP_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>'')
AND CODICE NOT IN (SELECT 'STA'+ORD_CODNAZ FROM U_ORF_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>'')
AND CODICE NOT IN (SELECT 'STA'+CLI_NAZION FROM U_CLI_AN
WHERE 'STA'+CLI_NAZION NOT IN (SELECT CODICE FROM PARAOLD)
AND CLI_NAZION<>'')
AND CODICE NOT IN (SELECT 'STA'+FOR_NAZION FROM U_FOR_AN
WHERE 'STA'+FOR_NAZION NOT IN (SELECT CODICE FROM PARAOLD)
AND FOR_NAZION<>'')




SELECT CLI_NAZION,* FROM U_CLI_AN
WHERE 'STA'+CLI_NAZION NOT IN (SELECT CODICE FROM PARAOLD)
AND CLI_NAZION<>''

SELECT FOR_NAZION,* FROM U_FOR_AN
WHERE 'STA'+FOR_NAZION NOT IN (SELECT CODICE FROM PARAOLD)
AND FOR_NAZION<>''




SELECT ORD_CODNAZ,ORD_NUMORD,ORD_DATORD,* FROM U_ORD_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_CODNAZ,ORD_NUMORD,ORD_DATORD,* FROM U_BOL_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_CODNAZ,ORD_NUMORD,ORD_DATORD,* FROM U_FAT_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_CODNAZ,ORD_NUMORD,ORD_DATORD,* FROM U_ORF_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>''
ORDER BY TAGGANCIO DESC


/*SELECT ORD_CODNAZ,ORD_NUMORD,ORD_DATORD,* FROM U_BFO_TT
WHERE 'STA'+ORD_CODNAZ NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_CODNAZ<>''
ORDER BY TAGGANCIO DESC*/




/*********************************************
VETTORI
*********************************************/
--- CONTROLLO VETTORI NON PRESENTI IN VECCHIO PARA ---
SELECT * FROM PARA
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'VET%'
ORDER BY DESCRI


--- CONTROLLO VETTORI NON PRESENTI IN VECCHIO PARA ---
--- PRESENTI IN DOCUMENTI

SELECT ORD_VETTO1,ORD_NUMORD,ORD_DATORD,* FROM U_ORD_TT
WHERE 'VET'+ORD_VETTO1 NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_VETTO1<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_VETTO1,ORD_NUMORD,ORD_DATORD,* FROM U_BOL_TT
WHERE 'VET'+ORD_VETTO1 NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_VETTO1<>''
ORDER BY TAGGANCIO DESC



SELECT * FROM PARA
--DELETE FROM PARA
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'VET%'
AND CODICE NOT IN (SELECT  'VET'+ORD_VETTO1 FROM U_ORD_TT
WHERE 'VET'+ORD_VETTO1 NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_VETTO1<>'')
AND CODICE NOT IN (SELECT  'VET'+ORD_VETTO1 FROM U_BOL_TT
WHERE 'VET'+ORD_VETTO1 NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_VETTO1<>'')








/*********************************************
AGENTI
*********************************************/
--- CONTROLLO AGENTI NON PRESENTI IN VECCHIO PARA ---
SELECT * FROM PARA
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'AGE%'

SELECT ORD_AGE,ORD_NUMORD,ORD_DATORD,* FROM U_ORD_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_AGE,ORD_NUMORD,ORD_DATORD,* FROM U_BOL_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>''
ORDER BY TAGGANCIO DESC

SELECT ORD_AGE,ORD_NUMORD,ORD_DATORD,* FROM U_FAT_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>''
ORDER BY TAGGANCIO DESC


SELECT * FROM PARA
--DELETE FROM PARA 
WHERE CODICE NOT IN (SELECT CODICE FROM PARAOLD)
AND CODICE LIKE 'AGE%'
AND CODICE NOT IN (SELECT  'AGE'+ORD_AGE FROM U_ORD_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>'')
AND CODICE NOT IN (SELECT  'AGE'+ORD_AGE FROM U_BOL_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>'')
AND CODICE NOT IN (SELECT  'AGE'+ORD_AGE FROM U_FAT_TT
WHERE 'AGE'+ORD_AGE NOT IN (SELECT CODICE FROM PARAOLD)
AND ORD_AGE<>'')