
DELETE FROM PARA WHERE CODICE LIKE 'DOG%'

INSERT INTO PARA (CODICE, DESCRI)
	SELECT 'DOG'+RTRIM(art_cldog) AS CODICE, '' AS DESCRI
	FROM U_ART_PR 
	WHERE art_cldog <> ''
	GROUP BY RTRIM(art_cldog)


SELECT * FROM PARA WHERE CODICE LIKE 'DOG%' ORDER BY CODICE


