UPDATE U_BAN_AN SET 
BAN_NAZION = SUBSTRING(BAN_LOCA,1,2),
ban_checkd = SUBSTRING(BAN_LOCA,2,2),
ban_CIN = SUBSTRING(BAN_LOCA,5,1),
ban_CODABI = SUBSTRING(BAN_LOCA,6,5),
ban_CODCAB = SUBSTRING(BAN_LOCA,11,5),
BAN_CODNCC = SUBSTRING(BAN_LOCA,16,12)
WHERE SUBSTRING(BAN_LOCA,1,2) = 'IT' AND LEN(RTRIM(BAN_LOCA)) = 27