
UPDATE U_OFF_TT SET ORD_PROVIN= CLI_PROVIN FROM U_CLI_AN LEFT JOIN U_OFF_TT ON ORD_CODCLI = CLI_CODCLI
UPDATE U_ORD_TT SET ORD_PROVIN= CLI_PROVIN FROM U_CLI_AN LEFT JOIN U_ORD_TT ON ORD_CODCLI = CLI_CODCLI
UPDATE U_FAT_TT SET ORD_PROVIN= CLI_PROVIN FROM U_CLI_AN LEFT JOIN U_FAT_TT ON ORD_CODCLI = CLI_CODCLI
UPDATE U_FAP_TT SET ORD_PROVIN= CLI_PROVIN FROM U_CLI_AN LEFT JOIN U_FAP_TT ON ORD_CODCLI = CLI_CODCLI
UPDATE U_BOL_TT SET ORD_PROVIN= CLI_PROVIN FROM U_CLI_AN LEFT JOIN U_BOL_TT ON ORD_CODCLI = CLI_CODCLI

