
UPDATE U_ART_PR SET ART_COSMAT = ART_PRZCOS
WHERE ART_PRZCOS > 0 AND ART_COSMAT = 0 AND ART_COSLAI = 0 AND ART_COSLAE = 0 AND ART_COSATR = 0

UPDATE U_ART_PR SET ART_RICMAT = ART_PRZVEN
WHERE ART_PRZVEN > 0 AND ART_RICMAT = 0 AND ART_RICLAI = 0 AND ART_RICLAE = 0 AND ART_RICATR = 0
