
-- VISTE PER ESPLOSIONE DI.BA. MACCHINE CON QTATOT PER COMPONENTI


-- VISTA ESPL_DIBA_MACCHINE_BASE_QTATOT_COMP
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ESPL_DIBA_MACCHINE_BASE_QTATOT_COMP]'))
	DROP VIEW [dbo].[ESPL_DIBA_MACCHINE_BASE_QTATOT_COMP]
GO
CREATE VIEW [dbo].[ESPL_DIBA_MACCHINE_BASE_QTATOT_COMP]  
AS

WITH AlberoDIBA
AS (
    SELECT 
		1 AS LIVELLO,
		DIS_GRUPPO AS MACCHINA,
		DIS_GRUPPO AS PADRE,
		CAST(RTRIM(DIS_GRUPPO) + ' -> ' + CAST(COALESCE(RTRIM(DIS_CODART),'') AS VARCHAR(1000)) AS VARCHAR(1000)) AS GERARCHIA,
		CAST(DIS_QTA AS NUMERIC(19,7)) AS DIS_QTATOT,
		U_DIS_DD.*
    FROM U_DIS_DD
    WHERE DIS_GRUPPO IN (SELECT DIT_GRUPPO FROM U_DIS_TT WHERE DIT_GRUPPO LIKE 'SEVEN%' and DIT_GRUPPO not LIKE '%#%')
    UNION ALL
    SELECT 
		LIVELLO + 1,
		AlberoDIBA.MACCHINA AS MACCHINA,
		DD.DIS_GRUPPO AS PADRE,
		CAST(AlberoDIBA.GERARCHIA+' -> '+RTRIM(DD.DIS_CODART) AS VARCHAR(1000)) AS GERARCHIA,
		CAST((DD.DIS_QTA * AlberoDIBA.DIS_QTATOT) AS NUMERIC(19,7)) AS DIS_QTATOT,
		DD.*
    FROM U_DIS_DD AS DD
    INNER JOIN AlberoDIBA
    ON DD.DIS_GRUPPO = AlberoDIBA.DIS_CODART
)

SELECT DISTINCT
	A1.DIS_CODART AS COMPONENTE,
	A1.DIS_DESCRI AS DESCRIZIONE,
	CASE WHEN COALESCE(DT.DIT_GRUPPO,'') = '' THEN 'A' ELSE 'G' END AS TIPO,
	A2.QTATOT AS QTATOT_TUTTE_LE_MACCHINE,
	PR.ART_CODF1 AS CODFORN_1_ANAGR_ART,
	COALESCE(F1.FOR_RAGSOC,'') AS DESFORN_1_ANAGR_ART
FROM AlberoDIBA AS A1
LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = A1.DIS_CODART
LEFT OUTER JOIN U_FOR_AN AS F1 ON F1.FOR_CODCLI = PR.ART_CODF1
LEFT OUTER JOIN U_DIS_TT AS DT ON DT.DIT_GRUPPO = A1.DIS_CODART
LEFT OUTER JOIN (SELECT DIS_CODART, SUM(DIS_QTATOT) AS QTATOT FROM AlberoDIBA GROUP BY DIS_CODART) AS A2 ON A2.DIS_CODART = A1.DIS_CODART
--ORDER BY GERARCHIA

GO


