**************************************
* AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND
**************************************
LPARAMETERS _NR_MESI

IF PCOUNT()<1
	RETURN .F.
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

RELEASE V_TITOLO,V_NR_GIORNI
PUBLIC V_TITOLO,V_NR_GIORNI

V_TITOLO = "Elenco articoli aggiornati con prezzo medio ponderato degli ultimi " + ALLTRIM(STR(_NR_MESI,10,0)) + " mesi"
**=> ERASMO - INIZIO 18/03/2021
IF V_NR_MESI<=0
	V_TITOLO = "Elenco articoli aggiornati con ultimo prezzo di carico"
ENDIF
**=> ERASMO - FINE 18/03/2021
V_NR_MESI = _NR_MESI

WAIT WINDOWS "ESEGUE PROGRAMMA AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND" TIMEOUT 3

*** INIZIO AGGIORNAMENTO PREZZO STANDARD COMPONENTI DI.BA.
cSql=""     
cNomeCursorSql="CU_NEW_PREZZI"
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT DISTINCT
		U_DIS_DD.DIS_CODART,
		PR.ART_DESCR,
		COALESCE(COALESCE((SELECT SUM(MOV_PREACQ*MOV_CAMBIO*MOV_QTAMOV) / SUM(MOV_QTAMOV) FROM U_MAG_MO WHERE MOV_TOP = (SELECT AZI_BFO FROM U_AZI_AN) AND MOV_ANAART = U_DIS_DD.DIS_CODART AND MOV_DTREGI >= 
			convert(varchar, DATEADD(month, - <<ALLTRIM(STR(V_NR_MESI,10,0))>>, GETDATE()), 111)), PR.ART_ULPCAR), PR.ART_PRZCOS) AS PRZ_ACQ_MED_POND,
		COALESCE(COALESCE((SELECT TOP 1 MOV_PREACQ*MOV_CAMBIO FROM U_MAG_MO WHERE MOV_TOP = (SELECT AZI_BFO FROM U_AZI_AN) AND MOV_ANAART = U_DIS_DD.DIS_CODART ORDER BY MOV_DTREGI DESC),PR.ART_ULPCAR, PR.ART_PRZCOS) AS PRZ_ACQ_ULT_CAR
		PR.ART_PRZCOS,
		PR.ART_ULPCAR,
		PR.ART_COSLAI,
		PR.ART_COSLAE,
		PR.ART_COSATR,
		(SELECT COUNT(*) FROM U_MAG_MO WHERE MOV_TOP = (SELECT AZI_BFO FROM U_AZI_AN) AND MOV_ANAART = U_DIS_DD.DIS_CODART AND MOV_DTREGI >= convert(varchar, DATEADD(month, - 12, GETDATE()), 111)) AS TOT_CARICHI
	FROM U_DIS_DD 
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = U_DIS_DD.DIS_CODART
	WHERE 
		U_DIS_DD.DIS_CODART NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT)
		AND PR.ART_NONMOV = 0
	GROUP BY
		U_DIS_DD.DIS_CODART,
		PR.ART_DESCR,
		PR.ART_PRZCOS,
		PR.ART_ULPCAR,
		PR.ART_COSLAI,
		PR.ART_COSLAE,
		PR.ART_COSATR
	ORDER BY U_DIS_DD.DIS_CODART

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF

*!*	SELECT CU_NEW_PREZZI
*!*	GO TOP
*!*	SCAN
*!*		IF ART_PRZCOS = PRZ_ACQ_MED_POND
*!*			DELETE
*!*			LOOP
*!*		ENDIF
*!*		
*!*	*!*		IF DIS_CODART = 'C101.230'
*!*	*!*		ELSE
*!*	*!*			LOOP
*!*	*!*		ENDIF
*!*		
*!*		_cCODART = DIS_CODART
*!*		_cPRZ_ACQ_MED_POND = STRTRAN(ALLTRIM(STR(PRZ_ACQ_MED_POND,17,6)),",",".")
*!*	   
*!*		*Usql = "UPDATE U_ART_PR SET ART_PRZCOS = " + _cPRZ_ACQ_MED_POND + " WHERE ART_CODPRI = '" + ALLTRIM(_cCODART) + "'"
*!*		Usql = "UPDATE U_ART_PR SET ART_PRZCOS = " + _cPRZ_ACQ_MED_POND + ", ART_COSMAT = (" + _cPRZ_ACQ_MED_POND + " - ART_COSLAI - ART_COSLAE - ART_COSATR) WHERE ART_CODPRI = '" + ALLTRIM(_cCODART) + "'"  && ERASMO - 10/03/2021
*!*		IF !ExecCommand(Usql,"UPD_ART_PR")
*!*		   return(.f.)
*!*		ENDIF
*!*			
*!*	ENDSCAN

**=> ERASMO - INIZIO 18/03/2021
SELECT CU_NEW_PREZZI
GO TOP
SCAN
	_NEW_COSMAT = IIF(V_NR_MESI<=0,PRZ_ACQ_ULT_CAR,PRZ_ACQ_MED_POND)
	_NEW_PRZCOS = _NEW_COSMAT + ART_COSLAI + ART_COSLAE + ART_COSATR
	IF ART_PRZCOS = _NEW_PRZCOS
		DELETE
		LOOP
	ENDIF
	
	_cCODART = DIS_CODART
	_c_NEW_PRZCOS = STRTRAN(ALLTRIM(STR(_NEW_PRZCOS,17,6)),",",".")
	_c_NEW_COSMAT = STRTRAN(ALLTRIM(STR(_NEW_COSMAT,17,6)),",",".")
	
	Usql = "UPDATE U_ART_PR SET ART_PRZCOS = " + _c_NEW_PRZCOS + ", ART_COSMAT = " + _c_NEW_COSMAT + " WHERE ART_CODPRI = '" + ALLTRIM(_cCODART) + "'"
	IF !ExecCommand(Usql,"UPD_ART_PR")
	   return(.f.)
	ENDIF
ENDSCAN
**=> ERASMO - FINE 18/03/2021
*** FINE AGGIORNAMENTO PREZZO STANDARD COMPONENTI DI.BA.

*!*	*** INIZIO RIVALUTAZIONE COSTI / RICAVI / TEMPI DI PRODUZIONE GRUPPI DI.BA.
*!*	cSql = "SELECT DIT_GRUPPO FROM U_DIS_TT ORDER BY DIT_GRUPPO"
*!*	IF !ExecCommand(cSql,"TMP_DIS_TT")
*!*		RETURN(.F.)
*!*	ENDIF
*!*	SELECT TMP_DIS_TT
*!*	GO TOP
*!*	SCAN	
*!*		_XY_GRUPPO = DIT_GRUPPO
*!*		
*!*		cSql = "SELECT * FROM U_DIS_TT WHERE DIT_GRUPPO = '" + _XY_GRUPPO + "'"
*!*		IF !ExecRW(cSql,"U_DIS_TT","R")
*!*			RETURN(.F.)
*!*		ENDIF
*!*		
*!*		SCATTER MEMVAR MEMO
*!*		DO RIVALUTA_CAMPI_U_DIS_TT WITH "U_DIS_TT"
*!*		
*!*		SELECT U_DIS_TT
*!*		GO TOP
*!*		IF !EOF()			
*!*			SCATTER MEMVAR MEMO
*!*			
*!*			x_soci = "art_codsoc = '" + PUB_CODSOC + "'"
*!*			x_codi = "art_codpri = '" + ALLTRIM(M.DIT_GRUPPO) + "'"
*!*			x_cond = x_soci + " and " + x_codi
*!*			Csql   = "select * from u_art_pr where " + x_cond + " order by art_codsoc,art_codpri"
*!*			IF !ExecRW(cSql,"u_art_pr","R")
*!*			   return(.f.)
*!*			ENDIF
*!*			SELECT u_art_pr
*!*			GO TOP
*!*			IF !EOF()
*!*			   	REPLACE ART_GRUPPO WITH .T.
*!*				REPLACE ART_PRZCOS WITH M.DIT_COSTO
*!*				*IF PUB_PRZDIB
*!*				REPLACE ART_COSLAI WITH M.DIT_COSLAI
*!*				REPLACE ART_COSLAE WITH M.DIT_COSLAE
*!*				REPLACE ART_COSMAT WITH M.DIT_COSMAT
*!*				REPLACE ART_COSATR WITH M.DIT_COSATR
*!*				REPLACE ART_ORELAV WITH M.DIT_ORELAV
*!*				REPLACE ART_OREATT WITH M.DIT_OREATT
*!*				REPLACE ART_OREIMP WITH M.DIT_OREIMP
*!*				REPLACE ART_SECIMP WITH M.DIT_SECIMP
*!*				REPLACE ART_SECLAV WITH M.DIT_SECLAV
*!*				REPLACE ART_SECATT WITH M.DIT_SECATT
*!*				*ENDIF
*!*			ENDIF
*!*			IF !ExecRW(cSql,"U_ART_PR","W")
*!*			   return(.f.)
*!*			ENDIF

*!*		ENDIF
*!*		
*!*		IF !ExecRW(cSql,"U_DIS_TT","W")
*!*			RETURN(.F.)
*!*		ENDIF
*!*	ENDSCAN
*!*	*** FINE RIVALUTAZIONE COSTI / RICAVI / TEMPI DI PRODUZIONE GRUPPI DI.BA.

**=> ERASMO - INIZIO 22/10/2020
SET PROCEDURE TO PRG\DISTINTA_BASE_LIB ADDITIVE
SET PROCEDURE TO PRG\APPLILIB ADDITIVE


RELEASE PUB_LIS01,PUB_LIS02,PUB_LIS03,PUB_LIS04,PUB_LIS05,PUB_LIS06,PUB_LIS07,PUB_LIS08,PUB_LIS09,PUB_LIS10,PUB_LIS11,PUB_LIS12,PUB_LISCASCA,PUB_LISVESCA,PUB_LIS0A,PUB_LIS13,PUB_LISCV,PUB_LISAV,PUB_FLGSCF,;
	PUB_LISZONAIE,PUB_LISMDB,PUB_LIS14,PUB_PRZDIB,PUB_CSTSEC,PUB_NONVAL
PUBLIC PUB_LIS01,PUB_LIS02,PUB_LIS03,PUB_LIS04,PUB_LIS05,PUB_LIS06,PUB_LIS07,PUB_LIS08,PUB_LIS09,PUB_LIS10,PUB_LIS11,PUB_LIS12,PUB_LISCASCA,PUB_LISVESCA,PUB_LIS0A,PUB_LIS13,PUB_LISCV,PUB_LISAV,PUB_FLGSCF,;
	PUB_LISZONAIE,PUB_LISMDB,PUB_LIS14,PUB_PRZDIB,PUB_CSTSEC,PUB_NONVAL
PUB_LIS01 = .F.
PUB_LIS02 = .F.
PUB_LIS03 = .F.
PUB_LIS04 = .F.
PUB_LIS05 = .F.
PUB_LIS06 = .F.
PUB_LIS07 = .F.
PUB_LIS08 = .F.
PUB_LIS09 = .F.
PUB_LIS10 = .F.
PUB_LIS11 = .F.
PUB_LIS12 = .F.
PUB_LISCASCA = .F.
PUB_LISVESCA = .F.
PUB_LIS0A = .F.
PUB_LIS13 = .F.
PUB_LISCV = .F.
PUB_LISAV = .F.
PUB_FLGSCF = .F.
PUB_LISZONAIE = .F.
PUB_LISMDB = .F.
PUB_LIS14 = .F.
PUB_PRZDIB = .F.
PUB_CSTSEC = 0
PUB_NONVAL = .F.
=AQUADOCU()

__gestione_prospect_attivata = .F.
_p_aggiorna_przcos = .T.
_p_descr_wait = "Rivalutazione"
_p_opzdbcost = 1  && Rivaluta i costi rispetto al prezzo standard in anagr. articoli
_p_non_aggiorna_u_dis_tt = .F.

DO PRG\RIVALUTA_U_DIS_TT_DIBA WITH _p_aggiorna_przcos,_p_descr_wait,_p_opzdbcost,_p_non_aggiorna_u_dis_tt
*DO PRG\MENUSTA WITH "CU_NEW_PREZZI",.T.,.T.,"XXX","AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND","AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND.FRX"
**=> ERASMO - FINE 22/10/2020

_PDF_REPORT_ 		= ALLTRIM(CERCAREPO("XXX","AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND","AGGIORNA_PREZZI_STD_CON_PRZ_MED_POND.FRX"))
_PDF_DESCRIZIONE_	= V_TITOLO+_PROGRESSIVO_PROGRAMMA 
_PDF_SELECT_ 		= "CU_NEW_PREZZI"

IF !EMPTY(_PDF_SUBDIR_)
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_)
ELSE
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
ENDIF

_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 


_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
