**** LIBRERIA DI SUPPORTO DI SERGIO 
**** IN QUESTA LIBRERIA SONO CARICATI LE FUNZIONI, LE ROUTIN CHE TEMPORANEAMENTE SONO STATE MODIFICATE 
**** OGNI FUNZIONE MODIFICATA DEVE ESSERE ESTRABOLATA DALLA LIBRERIA DI PARTENZA E SARA' INTERATA SUCCESSIVAMENTE
**** AL MOMENTO DEL RILASCIO EFFETTIVO 



