**********************************************************************************
*** ATTENZIONE QUESTO PRG E' ANCORA DA SISTEMARE PER LA GESTIONE SQL
*** ATTENZIONE QUESTO PRG E' ANCORA DA SISTEMARE PER LA GESTIONE SQL
*** ATTENZIONE QUESTO PRG E' ANCORA DA SISTEMARE PER LA GESTIONE SQL
*** ATTENZIONE QUESTO PRG E' ANCORA DA SISTEMARE PER LA GESTIONE SQL
**********************************************************************************

X_FILE = 'U_AST_AN.DBF'
IF FILE('&X_FILE')
ELSE
   RETURN
ENDIF

SWS=SELECT()

=OPENDB("U_AST_AN")
SELECT U_AST_AN

SELECT *                                                          ;
FROM U_AST_AN                                                     ;
WHERE AST_CODMAG = _V_CODMAG AND AST_CORSIA = _V_CORSIADA     AND ;
      AST_FILA = _V_FILADA AND AST_PIANO = _V_PIANODA         AND ;
      VAL(ALLTRIM(AST_NUMSCA)) = VAL(SUBSTR(_V_CODART,5,6))   AND ;
      VAL(ALLTRIM(AST_NUMSCH)) = VAL(SUBSTR(_V_CODART,11,6))  AND ;
      VAL(ALLTRIM(AST_CODCLI)) = VAL(SUBSTR(_V_DESART,33,8))      ;
INTO CURSOR PIPPO

SELECT PIPPO
IF EOF()
   SELECT(SWS)
   RETURN
ENDIF

DO WHILE .T.
   IF EOF()
      EXIT
   ENDIF
   IF DELETED()
      SKIP +1
      LOOP
   ENDIF
   X_CODSOC = AST_CODSOC
   X_NUMSCA = AST_NUMSCA
   X_DATSCA = AST_DATSCA
   X_NUMSCH = AST_NUMSCH
   X_CODCLI = AST_CODCLI
   SELECT U_AST_AN
   SET ORDER TO U_AST_A1
   SEEK PUB_CODSOC + SUBSTR(X_DATSCA,7,4) + X_NUMSCA + X_NUMSCH + X_CODCLI 
   IF FOUND()
      IF _V_CORSIAAL = '999' .AND. _V_FILAAL = 99 .AND. _V_PIANOAL = 99
         REPLACE AST_CODMAG WITH SPACE(06)
         REPLACE AST_CORSIA WITH SPACE(03)
         REPLACE AST_FILA   WITH 0
         REPLACE AST_PIANO  WITH 0
      ELSE
         REPLACE AST_CODMAG WITH _V_CODMAG
         REPLACE AST_CORSIA WITH _V_CORSIAAL
         REPLACE AST_FILA   WITH _V_FILAAL
         REPLACE AST_PIANO  WITH _V_PIANOAL
      ENDIF
   ENDIF
   SELECT PIPPO
   SKIP +1
ENDDO

SELECT(SWS)

RETURN   

