* CANCELLA_TABELLA_SQL("PIANOP_TT")
* CANCELLA_TABELLA_SQL("PIANOP_DD")
* CANCELLA_TABELLA_SQL("PIANOP_MO")
* CANCELLA_TABELLA_SQL("PIANOP_P1")
* CANCELLA_TABELLA_SQL("PIANOP_P2")
* CANCELLA_TABELLA_SQL("PIANOP_SA")

CARICA_TABELLA_DA_BACKUP("PIANOP_TT")
CARICA_TABELLA_DA_BACKUP("PIANOP_DD")
CARICA_TABELLA_DA_BACKUP("PIANOP_MO")
CARICA_TABELLA_DA_BACKUP("PIANOP_P1")
CARICA_TABELLA_DA_BACKUP("PIANOP_P2")
CARICA_TABELLA_DA_BACKUP("PIANOP_SA")

MESSAGEBOX("Operazione terminata.",64,"Restore piani di pagamento")

***********************************
PROCEDURE CARICA_TABELLA_DA_BACKUP
***********************************
PARAMETERS PNOME_TABELLA

LOCAL NOME_TABELLA,;
      CURS_TABELLA
      
NOME_TABELLA = ALLTRIM(PNOME_TABELLA)
CURS_TABELLA = "CURS_"+NOME_TABELLA
BAK_TABELLA = "BACKUP_"+NOME_TABELLA

****** DEFINIZIONE DEL CURSORE STP
IF !ExecCommand("select * from "+NOME_TABELLA+" where 1=0",CURS_TABELLA)
   return
ENDIF


*** CANCELLAZIONE DEI RECORD DELLA TABELLA U_CLI_AN SQL
cSql = "delete from "+NOME_TABELLA
IF !ExecCommand(cSql,NOME_TABELLA)
   return(.f.)
ENDIF

IF !FILE(BAK_TABELLA+".DBF")
  MESSAGEBOX("File di salvataggio "+BAK_TABELLA+" inesistente.",48,"ATTENZIONE")
  RETURN
ENDIF

****** CARICA IL FILE DBF
USE &BAK_TABELLA IN 0 AGAIN EXCL
SELECT &BAK_TABELLA
GO TOP
DO WHILE !EOF()
  SCATTER MEMVAR
  SELECT &CURS_TABELLA
  APPEND BLANK
  GATHER MEMVAR
  
  SELECT &BAK_TABELLA
  SKIP
ENDDO

****** AGGIORNA TABELLA SQL
IF !ExecRW('',NOME_TABELLA,'I','',CURS_TABELLA)
   return(.f.)
ENDIF

SELECT &BAK_TABELLA
USE  
* FINE PROCEDURE CARICA_TABELLA_DA_BACKUP
***********************************



***********************************
PROCEDURE CANCELLA_TABELLA_SQL
***********************************
PARAMETERS PNOME_TABELLA

LOCAL NOME_TABELLA
      
NOME_TABELLA = ALLTRIM(PNOME_TABELLA)

*** CANCELLAZIONE DEI RECORD DELLA TABELLA U_CLI_AN SQL
cSql = "delete from "+NOME_TABELLA
IF !ExecCommand(cSql,NOME_TABELLA)
   return(.f.)
ENDIF

* FINE PROCEDURE CANCELLA_TABELLA_SQL
***********************************
