WAIT WINDOWS "Stò compilando Aquarius" NOWAIT
BUILD EXE AQUARIUS FROM AQUARIUS
        
WAIT WINDOWS "Stò compilando i .PRG"  NOWAIT
ERASE PRG\RIATFC.FXP
ERASE PRG\RIATFP.FXP
ERASE PRG\RIARCT.FXP
ERASE PRG\PRNIVACN.FXP
ERASE PRG\PRNIVACE.FXP
ERASE PRG\TFCRIBA.FXP
ERASE PRG\BOLLATI.FXP
ERASE PRG\IVACLSTA.FXP
ERASE PRG\IVAFOSTA.FXP
ERASE PRG\IVAFOCEE.FXP
ERASE PRG\IVACLCEE.FXP
ERASE PRG\IVACOSTA.FXP
ERASE PRG\IVACASTA.FXP
ERASE PRG\LIQUIDA.FXP
ERASE PRG\LIQUIDOS.FXP
ERASE PRG\LIQUIMM.FXP
ERASE PRG\PROV000.FXP
ERASE PRG\PROVSTA.FXP


COMPILE PRG\RIATFC
COMPILE PRG\RIATFP
COMPILE PRG\RIARCT
COMPILE PRG\PRNIVACN
COMPILE PRG\PRNIVACE
COMPILE PRG\TFCRIBA
COMPILE PRG\BOLLATI
COMPILE PRG\IVACLSTA
COMPILE PRG\IVAFOSTA
COMPILE PRG\IVAFOCEE
COMPILE PRG\IVACLCEE
COMPILE PRG\IVACOSTA
COMPILE PRG\IVACASTA
COMPILE PRG\LIQUIDA
COMPILE PRG\LIQUIDOS
COMPILE PRG\LIQUIMM
COMPILE PRG\PROV000
COMPILE PRG\PROVSTA

WAIT WINDOWS "Fine compilazione progetti" NOWAIT
