
SET DEFAULT TO &PUB_DIR

__connectString = PUB_NOMEDB
__connectString_DATABASE = SUBSTR(__connectString,AT("DATABASE=",__connectString),AT(';',SUBSTR(__connectString,AT("DATABASE=",__connectString)))-1)
_V_DBAL = STRTRAN(__connectString_DATABASE,"DATABASE=","")
__config_name = "conversioni_" + _V_DBAL + ".cfg"
*PERCORSO_TREVICALOR= "D:\Trevicalor\asterdat"
PERCORSO_TREVICALOR=legge_config(__config_name,"PERCORSO_ASTERDAT")						&& RICERCA VARIABILE
WAIT WINDOWS "PERCORSO ARCHIVI TREVICALOR: " + PERCORSO_TREVICALOR
SET DEFAULT TO &PERCORSO_TREVICALOR


RIT = MESSAGEBOX("PROCEDO CON IL CARICAMENTO DELLE TABELLE CONTRATTI IMPIANTI (SCHEDECONTR/CONTRATTI_SERVIZI) TREVICALOR? " + REPLICATE(CHR(13),2) + ;
		"Continuare?",4+32+256,"ATTENZIONE")

IF RIT = 7
   MESSAGEBOX("Operazione abbandonata",48,"Informazione")
   RETURN
ENDIF
	

*** CANCELLAZIONE TABELLE CONTRATTI IMPIANTI
WAIT WINDOWS "Cancellazione CONTRATTI IMPIANTI...  -  Prego Attendere" NOWAIT


cSql = "truncate table IMPIANTI_CO" 
IF !ExecCommand(cSql,"IMPIANTI_CO")
   return(.f.)
ENDIF


_V_PERCORSO = PERCORSO_TREVICALOR

SET EXCLUSIVE ON

V_PATH = ALLTRIM(_V_PERCORSO)
SET DEFAULT TO &V_PATH
=OPENDB("SCHEDECONTR")
SELECT SCHEDECONTR
GO TOP

V_PATH = ALLTRIM(_V_PERCORSO)
SET DEFAULT TO &V_PATH
=OPENDB("CONTRATTI_SERVIZI")
SELECT CONTRATTI_SERVIZI
INDEX ON ALLTRIM(ID_PMCONTR)+ALLTRIM(ID_RIGO) DESCENDING ADDITIVE TAG I_PMCRIG
SET ORDER TO I_PMCRIG
GO TOP


WAIT WINDOWS "Caricamento dati, attendere prego..." NOWAIT

SELECT SCHEDECONTR
GO TOP 
SCAN
	
	M.ID_PMKEY = ALLTRIM(ID_PMKEY)
	M.ID_PMCONTR = ALLTRIM(ID_PMCONTR)
	M.ID_RIGO = "00010"
		
	WAIT WINDOWS "Caricamento Contratto " + M.ID_PMKEY NOWAIT
	
	_SEEK = M.ID_PMCONTR+M.ID_RIGO
	SELECT CONTRATTI_SERVIZI
	GO TOP
	SEEK _SEEK
	IF FOUND()
		SCATTER MEMVAR MEMO
	ELSE
		SCATTER MEMVAR MEMO BLANK
	ENDIF
	
	M.TIPO_COMPONENTE = "001"
	M.CDITTACAL = ""
	M.CMODCAL = ""
	M.CMATCAL = ""
	M.GRUPPO = ""
	
	x_pmkey  = "id_pmkey = '" + ALLTRIM(M.ID_PMKEY) + "'"
	x_tipoco = "tipo_componente = '" + ALLTRIM(M.TIPO_COMPONENTE) + "'"
	x_rigo   = "ID_RIGO = '" + ALLTRIM(M.ID_RIGO) + "'"
	x_cond   = x_pmkey + " and " + x_tipoco + " and " + x_rigo
    cSql     = "SELECT * FROM IMPIANTI_DD WHERE " + x_cond
    IF !ExecCommand(cSql,"CUR_IMPIANTI_DD")
       return(.f.)
    ENDIF
    SELECT CUR_IMPIANTI_DD
    GO TOP    
	IF !EOF()
		M.CDITTACAL = CDITTACAL
		M.CMODCAL = CMODCAL
		M.CMATCAL = CMATCAL
		M.GRUPPO = GRUPPO
	ENDIF
	
	SELECT SCHEDECONTR
	SCATTER MEMVAR MEMO
	
	**==> CREAZIONE TABELLA IMPIANTO
		
	IF !ExecRW("select * from IMPIANTI_CO where 0=1","IMPIANTI_CO","R")
	   return(.f.)
	ENDIF
	SELECT IMPIANTI_CO
	APPEND BLANK
	GATHER MEMVAR MEMO
	
	REPLACE ID_PMKEY 	WITH ALLTRIM(M.ID_PMKEY)
	REPLACE ID_PMCONTR 	WITH ALLTRIM(M.ID_PMCONTR)
	REPLACE ID_RIGO 	WITH ALLTRIM(M.ID_RIGO)

	REPLACE CINIZCONTR	WITH RIBALTA2(DTOC(M.CINIZCONTR))
	REPLACE CSCADCONTR	WITH RIBALTA2(DTOC(M.CSCADCONTR))
	REPLACE DT_REGIST	WITH RIBALTA2(DTOC(M.DT_REGIST))
	REPLACE DT_CONFERM	WITH RIBALTA2(DTOC(M.DT_CONFERM))
	REPLACE DT_DISDETT	WITH RIBALTA2(DTOC(M.DT_DISDETT))
	REPLACE DT_INIZIO	WITH RIBALTA2(DTOC(M.DT_INIZIO))
	REPLACE DT_FINE		WITH RIBALTA2(DTOC(M.DT_FINE))
	
	REPLACE CSCAD_A     WITH RIBALTA2(CSCAD_A)
	REPLACE CSCAD_B     WITH RIBALTA2(CSCAD_B)
	REPLACE CSCAD_C     WITH RIBALTA2(CSCAD_C)
	REPLACE CSCAD_D1    WITH RIBALTA2(CSCAD_D1)
	REPLACE CSCAD_D2    WITH RIBALTA2(CSCAD_D2)
	REPLACE CSCAD_E1    WITH RIBALTA2(CSCAD_E1)
	REPLACE CSCAD_E2    WITH RIBALTA2(CSCAD_E1)
	REPLACE CSCAD_F1    WITH RIBALTA2(CSCAD_F1)
	REPLACE CSCAD_F2    WITH RIBALTA2(CSCAD_F2)
		
	IF !ExecRW("select * from IMPIANTI_CO where 0=1","IMPIANTI_CO","W")
	   return(.f.)
	ENDIF

	SELECT SCHEDECONTR
	
ENDSCAN


=MESSAGEBOX("OPERAZIONE TERMINATA CORRETTAMENTE ",62,"ATTENZIONE")

SET DEFAULT TO &PUB_DIR

RETURN
