*************************************************************************************************
*							CONVERSIONE DISTINTE BASE   										*
*							 																	*
*	by Project S.r.l.																			*
*	gennaio 2014 : Rumi					 														*
*************************************************************************************************

** ASSEGNAZIONE DELLA VARIABILE PATH **************************
V_PATH = ""
=OPENDB("PERCORSO")
SELECT PERCORSO
SET ORDER TO I_TIPO
GO TOP
SEEK "RUM"
IF FOUND()
	V_PATH = ALLTRIM(PER_PATH)
ELSE
	MESSAGEBOX("Percorso 'RUM' non configurato" + CHR(13) + CHR(13) + ;
		"Controllare il file PERCORSO.DBF",16,"Attenzione")
	USE
	RETURN .F.
ENDIF

IF DIRECTORY(V_PATH)
ELSE
	MESSAGEBOX("Percorso '" + ALLTRIM(V_PATH) + "' non trovato!" + CHR(13) + CHR(13) + ;
		"Controllare il file PERCORSO.DBF",16,"Attenzione")
	RETURN .F.
ENDIF

SET DEFAULT TO &V_PATH

**** CARICAMENTO DEL FILE IN FORMATO EXCEL 5.0 !!!!!!!!!!!!!! IL FORMATO OFFICE 2003 IN POI NON FUNZIONA
gcFile = GETFILE('XLS', '', 'Browse', 1, 'Seleziona')
SET DEFAULT TO &PUB_DIR

IF EMPTY(gcFile)
	MESSAGEBOX("Nessun file selezionato",64,"Informazione")
	RETURN
ENDIF

RIT = MESSAGEBOX("Conversione Distinte Base da foglio Excel: " + REPLICATE(CHR(13),2) + ;
		ALLTRIM(V_PATH) + REPLICATE(CHR(13),2) + "Continuare?",4+32+256,"ATTENZIONE")
		
IF RIT = 7
   MESSAGEBOX("Operazione abbandonata",48,"Informazione")
   RETURN
ENDIF

*!*	RIT = MESSAGEBOX("Desideri cancellare le Distinte Base esistenti?" + REPLICATE(CHR(13),2) + ;
*!*			 "Continuare?",4+32+256,"ATTENZIONE")
*!*			
*!*	IF RIT <> 7
	WAIT WINDOWS "Cancellazione vecchie Distinte Base in corso..." NOWAIT

	cSql = "DELETE FROM U_DIS_TT"
	IF !ExecCommand(cSql,"DEL_DIS_TT")
	   return
	ENDIF

	cSql = "DELETE FROM U_DIS_DD"
	IF !ExecCommand(cSql,"DEL_DIS_DD")
	   return
	ENDIF
*!*	ENDIF 


WAIT WINDOWS "Conversione Distinte Base in corso..." NOWAIT		

CREATE CURSOR IMPORTAXLS ( ;
	LIVELLO N(2,0), ;
	CACODICE C(200), ;
	CADESART C(200), ;
	CACODART C(200), ;
	CACODVAR C(200), ;
	CAUNIMIS C(200), ;
	CAOPERAT C(200), ;
	CAMOLTIP C(200), ;
	CACONFIG C(200), ;
	CACONATO C(200), ;
	CAPREZUM C(200), ;
	CACONCAR C(200), ;
	ARUNMIS1 C(200), ;
	ARUNMIS2 C(200), ;
	AROPERAT C(200), ;
	ARMOLTIP C(200), ;
	ARTIPART C(200), ;
	ARPROPRE C(200), ;
	ARTIPGES C(200), ;
	CORIFDIS C(200), ;
	CPROWNUM N(10,0), ;
	CPROWORD N(10,0), ;
	COCODCOM C(200), ;
	COCODART C(200), ;
	COCODVAR C(200), ;
	COUNIMIS C(200), ;
	COCOEIMP N(10,0), ;
	COCOEUM1 N(10,0), ;
	COSCAPRO N(10,0), ;
	CORECSCA N(10,0), ;
	COSFRIDO N(10,0), ;
	CORECSFR N(10,0), ;
	COIDEGRU C(200), ;
	COOPELOG C(200), ;
	COFLPREF C(200), ;
	COPROGRU C(200), ;
	CORIFFAS N(10,0), ;
	COCORLEA N(10,0), ;
	COPERRIC N(10,0), ;
	CODESSUP C(200), ;
	COCLAPRE C(200), ;
	COCLARIF C(200), ;
	COATTGES C(200), ;
	CODISGES C(200), ;
	COULTGES C(200), ;
	COOPUMGE N(10,0), ;
	COXCHKGE N(10,0), ;
	TIPPRO C(200), ;
	CPBMPNAME C(200), ;
	LVLKEY C(200), ;
	QTACOMP N(10,0), ;
	QTACOMPN N(10,0), ;
	QTACOMPL N(10,0), ;
	TIPPAD C(200), ;
	STADIS C(200), ;
	COSTO C(200), ;
	MSGERRORE C(200), ;
	CODICEDIBA C(200), ;
	DESCRITV C(200), ;
	OPTDUPL C(200), ;
	DBTIPGEN C(200), ;
	CODICE C(200), ;
	PADRE C(10))

*** NON FUNZIONA CON NOMI FILE/CARTELLE CON SPAZI
*APPEND FROM (gcFile) TYPE xls

_COMMAND = "APPEND FROM '" + ALLTRIM(gcFile) + "' TYPE xls"
&_COMMAND

_LIVELLO = -1
_TOT_COUNT = 0

_GRUPPO = ""
_AGGANCIO = ""
*_ULT_GRUPPO_DETT = ""

CREATE CURSOR CU_GRUPPI (LIVELLO N(10,0), GRUPPO C(30), AGGANCIO C(10))
INDEX ON ALLTRIM(STR(LIVELLO,3,0)) TAG I_LIVELLO

CREATE CURSOR CU_GRUPPI_CREATI (GRUPPO C(30), FLG_COMPLETED L)
INDEX ON ALLTRIM(GRUPPO) TAG I_GRUPPO

SELECT IMPORTAXLS
GO TOP
DO WHILE .T.
	IF EOF()
		EXIT
	ENDIF
	
    IF RECNO() = 1  && SCARTO PRIMO RECORD (INTESTAZIONI DI COLONNA)
    	SKIP +1
		LOOP
    ENDIF
    
    SCATTER MEMVAR MEMO
    
    *IF M.CACODICE = '20988020'
    *	SET STEP ON
    *ENDIF
       
    IF M.LIVELLO >= -1 AND !EMPTY(M.CACODICE) AND !EMPTY(M.ARTIPART)  && SCARTO RECORD NON SIGNIFICATIVI
    ELSE
    	SELECT IMPORTAXLS
    	SKIP +1
    	LOOP
    ENDIF
    
    *** SE LIVELLO MINORE DI QUELLO PRECEDENTE, CHIUDO TUTTI I GRUPPI DEI LIVELLI PRECEDENTI
    IF M.LIVELLO < _LIVELLO
    	FOR _i = (_LIVELLO - 1) TO (M.LIVELLO) STEP -1
    		_cNomevar = "_ULT_GRUPPO_DETT_LIV_" + ALLTRIM(STR(_i,3,0))
    		IF TYPE(_cNomevar) == 'C'
				SELECT CU_GRUPPI_CREATI
				SET ORDER TO I_GRUPPO
				GO TOP
				SEEK ALLTRIM(&_cNomevar)
				IF FOUND()
					REPLACE FLG_COMPLETED WITH .T.
				ENDIF
			ENDIF
		NEXT
	ENDIF
    
    IF M.LIVELLO <> _LIVELLO
    	
    	_LIVELLO = M.LIVELLO
    	
    	IF ALLTRIM(M.ARTIPART) <> 'MP'
			
			_SEEK = ALLTRIM(STR(_LIVELLO,3,0))
			_AGGANCIO = SYS(2015)
			
			SELECT CU_GRUPPI
			SET ORDER TO I_LIVELLO
			GO TOP
			SEEK _SEEK
			IF !FOUND()
				APPEND BLANK
				REPLACE LIVELLO WITH _LIVELLO
			ENDIF
			
			REPLACE GRUPPO WITH ALLTRIM(M.CACODICE)
			REPLACE AGGANCIO WITH SYS(2015)
			
			_GRUPPO = ALLTRIM(GRUPPO)
			_AGGANCIO = ALLTRIM(AGGANCIO)
			
			SELECT CU_GRUPPI_CREATI
			SET ORDER TO I_GRUPPO
			GO TOP
			SEEK _GRUPPO
			IF !FOUND()
				
				SELECT IMPORTAXLS
				
				WAIT WINDOWS "Conversione Distinta Base Gruppo " + ALLTRIM(M.CACODICE) + " (" + ALLTRIM(STR(RECNO() * 100 / RECCOUNT(),10,0)) + "%)" NOWAIT
				
				__DIT_CODSOC = PUB_CODSOC
				__TAGGANCIO = _AGGANCIO
				__DIT_GRUPPO = _GRUPPO
				__DIT_NOTE = ""
				__DIT_DESCRI = ""
				__DIT_UM = ""
				__DIT_MAGA = ""
				__DIT_CODIVA = ""
				__DIT_LINEA = ""
					
				x_soci = "ART_CODSOC = '" + PUB_CODSOC + "'"
				x_codi = "ART_CODPRI = '" + __DIT_GRUPPO + "'"
				x_cond = x_soci + " and " + x_codi
				cSql = "SELECT ART_CODPRI,ART_DESCR,ART_UMMAGA,ART_MAGA,ART_CODIVA,ART_LINEA FROM U_ART_PR WHERE " + x_cond
				IF !ExecCommand(cSql,"CX_ART_PR")
					RETURN .F.
				ENDIF
				SELECT CX_ART_PR
				GO TOP
				IF !EOF()
					__DIT_DESCRI = ART_DESCR
					__DIT_UM = ART_UMMAGA
					__DIT_MAGA = ART_MAGA
					__DIT_CODIVA = ART_CODIVA
					__DIT_LINEA = ART_LINEA
				ELSE
					
					DO CONV_DIBA_RUMI_CREA_ARTICOLO
					
					x_soci = "ART_CODSOC = '" + PUB_CODSOC + "'"
					x_codi = "ART_CODPRI = '" + __DIT_GRUPPO + "'"
					x_cond = x_soci + " and " + x_codi
					cSql = "SELECT ART_CODPRI,ART_DESCR,ART_UMMAGA,ART_MAGA,ART_CODIVA,ART_LINEA FROM U_ART_PR WHERE " + x_cond
					IF !ExecCommand(cSql,"CX_ART_PR")
						RETURN .F.
					ENDIF
					SELECT CX_ART_PR
					GO TOP
					IF !EOF()
						__DIT_DESCRI = ART_DESCR
						__DIT_UM = ART_UMMAGA
						__DIT_MAGA = ART_MAGA
						__DIT_CODIVA = ART_CODIVA
						__DIT_LINEA = ART_LINEA
					ELSE
						MESSAGEBOX("Impossibile creare l'articolo " + __DIT_GRUPPO,48,"Attenzione")
					ENDIF
					
				ENDIF
				
				cSql = "SELECT * FROM U_DIS_TT WHERE 1=0"
				IF !ExecRW(cSql,"U_DIS_TT","R")
				   return
				ENDIF
				SELECT U_DIS_TT
				GO TOP
				APPEND BLANK
				REPLACE DIT_CODSOC WITH __DIT_CODSOC 
				REPLACE TAGGANCIO WITH __TAGGANCIO 
				REPLACE DIT_GRUPPO WITH __DIT_GRUPPO 
				REPLACE DIT_NOTE WITH __DIT_NOTE 
				REPLACE DIT_DESCRI WITH __DIT_DESCRI 
				REPLACE DIT_UM WITH __DIT_UM 
				REPLACE DIT_MAGA WITH __DIT_MAGA 
				REPLACE DIT_CODIVA WITH __DIT_CODIVA 
				REPLACE DIT_LINEA WITH __DIT_LINEA
				IF !ExecRW(cSql,"U_DIS_TT","W")
				   return
				ENDIF
				
				SELECT CU_GRUPPI_CREATI
				APPEND BLANK
				REPLACE GRUPPO WITH __DIT_GRUPPO
				REPLACE FLG_COMPLETED WITH .F.
				
				_TOT_COUNT = _TOT_COUNT + 1
				
			ENDIF
			
			IF _LIVELLO > 0
			ELSE
				SELECT IMPORTAXLS
				SKIP +1
				LOOP
			ENDIF
			
			
		ENDIF
 		
	ENDIF
	
	_GRUPPO = ""
	_AGGANCIO = ""
	_SEEK = ALLTRIM(STR(_LIVELLO - 1,3,0))
	
	SELECT CU_GRUPPI
	SET ORDER TO I_LIVELLO
	GO TOP
	SEEK _SEEK
	IF !FOUND()
		SELECT IMPORTAXLS
		SKIP +1
		LOOP
	ENDIF
	_GRUPPO = ALLTRIM(GRUPPO)
	_AGGANCIO = ALLTRIM(AGGANCIO)
	
*!*		SELECT CU_GRUPPI
*!*		SET ORDER TO I_LIVELLO
*!*		GO TOP
*!*		SEEK _SEEK
*!*		IF FOUND()
*!*			_GRUPPO = ALLTRIM(GRUPPO)
*!*			_AGGANCIO = ALLTRIM(AGGANCIO)
*!*		ELSE
*!*			SELECT IMPORTAXLS
*!*			SKIP +1
*!*			LOOP
*!*		ENDIF
	
	SELECT CU_GRUPPI_CREATI
	SET ORDER TO I_GRUPPO
	GO TOP
	SEEK _GRUPPO
	IF FOUND()
		IF !FLG_COMPLETED  && CONTINUA A SCRIVERE I DETTAGLI DEL GRUPPO SOLO SE NON GIA' COMPLETATI PRECEDENTEMENTE
		ELSE
			SELECT IMPORTAXLS
			SKIP +1
			LOOP		
		ENDIF
	ELSE
		SELECT IMPORTAXLS
		SKIP +1
		LOOP
	ENDIF
	
	*_ULT_GRUPPO_DETT = _GRUPPO
	_cNomevar = "_ULT_GRUPPO_DETT_LIV_" + ALLTRIM(STR(_LIVELLO - 1,3,0))
	&_cNomevar = _GRUPPO
	
	__DIS_SEQUEN = M.CPROWORD
	__DAGGANCIO = _AGGANCIO 
	__DIS_GRUPPO = _GRUPPO 
	__DIS_CODART = ALLTRIM(M.CACODICE)
	__DIS_QTA = M.COCOEIMP
	__DIS_NOTE = ""
	__DIS_DESCRI = ""
	__DIS_UM = ""
	__DIS_MAGA = ""
	__DIS_TIPO = IIF(ALLTRIM(M.ARTIPART) = 'PH','A','G')
	__DIS_FITTIZ = IIF(ALLTRIM(M.ARTIPART) = 'PH',.T.,.F.)
		
	x_soci = "ART_CODSOC = '" + PUB_CODSOC + "'"
	x_codi = "ART_CODPRI = '" + __DIS_CODART + "'"
	x_cond = x_soci + " and " + x_codi
	cSql = "SELECT ART_CODPRI,ART_DESCR,ART_UMMAGA,ART_MAGA FROM U_ART_PR WHERE " + x_cond
	IF !ExecCommand(cSql,"CX_ART_PR")
		RETURN .F.
	ENDIF
	SELECT CX_ART_PR
	GO TOP
	IF !EOF()
		__DIS_DESCRI = ART_DESCR
		__DIS_UM = ART_UMMAGA
		__DIS_MAGA = ART_MAGA
	ELSE
		
		DO CONV_DIBA_RUMI_CREA_ARTICOLO
		
		x_soci = "ART_CODSOC = '" + PUB_CODSOC + "'"
		x_codi = "ART_CODPRI = '" + __DIS_CODART + "'"
		x_cond = x_soci + " and " + x_codi
		cSql = "SELECT ART_CODPRI,ART_DESCR,ART_UMMAGA,ART_MAGA FROM U_ART_PR WHERE " + x_cond
		IF !ExecCommand(cSql,"CX_ART_PR")
			RETURN .F.
		ENDIF
		SELECT CX_ART_PR
		GO TOP
		IF !EOF()
			__DIS_DESCRI = ART_DESCR
			__DIS_UM = ART_UMMAGA
			__DIS_MAGA = ART_MAGA
		ELSE
			MESSAGEBOX("Impossibile creare l'articolo " + __DIS_CODART,48,"Attenzione")
		ENDIF
	ENDIF
	
	cSql = "SELECT * FROM U_DIS_DD WHERE 1=0"
	IF !ExecRW(cSql,"U_DIS_DD","R")
	   return
	ENDIF
	SELECT U_DIS_DD
	APPEND BLANK

	REPLACE DIS_SEQUEN WITH __DIS_SEQUEN 
	REPLACE DAGGANCIO WITH __DAGGANCIO 
	REPLACE DIS_GRUPPO WITH __DIS_GRUPPO 
	REPLACE DIS_CODART WITH __DIS_CODART 
	REPLACE DIS_QTA WITH __DIS_QTA 
	REPLACE DIS_NOTE WITH __DIS_NOTE 
	REPLACE DIS_DESCRI WITH __DIS_DESCRI 
	REPLACE DIS_UM WITH __DIS_UM 
	REPLACE DIS_MAGA WITH __DIS_MAGA 
	REPLACE DIS_TIPO WITH __DIS_TIPO 
	REPLACE DIS_FITTIZ WITH __DIS_FITTIZ
	
	IF !ExecRW(cSql,"U_DIS_DD","W")
	   return
	ENDIF
	
	SELECT IMPORTAXLS
	SKIP +1
	
ENDDO


WAIT WINDOWS "Rinumerazione sequenza dettagli Distinte Base in corso..." NOWAIT

cSql = "SELECT * FROM U_DIS_TT"
IF !ExecCommand(cSql,"CX_DIS_TT")
   return
ENDIF
SELECT CX_DIS_TT
GO TOP
SCAN

	WAIT WINDOWS "Rinumerazione sequenza dettagli Distinte Base Gruppo " + ALLTRIM(DIT_GRUPPO) + " (" + ALLTRIM(STR(RECNO() * 100 / RECCOUNT(),10,0)) + "%)" NOWAIT
	
	__DIS_SEQUEN = 0
	
	__TAGGANCIO = TAGGANCIO 
	__DIT_GRUPPO = DIT_GRUPPO
	x_agga = "DAGGANCIO = '" + __TAGGANCIO + "'"
	x_grup = "DIS_GRUPPO = '" + __DIT_GRUPPO + "'"
	x_cond = x_agga + " and " + x_grup 
	cSql = "SELECT * FROM U_DIS_DD WHERE " + x_cond + " ORDER BY DIS_CODART"
	IF !ExecRW(cSql,"U_DIS_DD","R")
	   return
	ENDIF
	SELECT U_DIS_DD
	GO TOP
	SCAN
		__DIS_SEQUEN = __DIS_SEQUEN + 10
		REPLACE DIS_SEQUEN WITH __DIS_SEQUEN
	ENDSCAN
	IF !ExecRW(cSql,"U_DIS_DD","W")
	   return
	ENDIF

ENDSCAN


WAIT CLEAR

MESSAGEBOX("Operazione terminata correttamente" + REPLICATE(CHR(13),2) + ;
	"Totale gruppi convertiti: " + ALLTRIM(STR(_TOT_COUNT,10,0)),64,"Informazione")

RETURN



*************************************************************************************
PROCEDURE CONV_DIBA_RUMI_CREA_ARTICOLO
*************************************************************************************

M.ART_CODSOC = PUB_CODSOC
M.ART_CODPRI = ALLTRIM(M.CACODICE)
M.ART_DESCR = APITOSPA(ALLTRIM(M.CADESART))
M.ART_CATMER = ""
M.ART_UNIMIS = IIF(EMPTY(M.ARUNMIS1),"NR",ALLTRIM(M.ARUNMIS1))
M.ART_UMMAGA = IIF(EMPTY(M.ARUNMIS1),"NR",ALLTRIM(M.ARUNMIS1))
M.ART_CODIVA = PUB_IVA
M.ART_LINEA  = SUBSTR(ALLTRIM(M.ARTIPART),1,2)
*IF ALLTRIM(M.CACMPCAR) = 'S'
*	M.ART_CHDIBA = .T.
*ELSE
*	M.ART_CHDIBA = .F.
*ENDIF
M.ART_CHDIBA = .F.
	
DO CASE
	CASE M.ART_LINEA = "MP"
		M.ART_TIPART = 'A'
	CASE M.ART_LINEA = "SE"
		M.ART_TIPART = 'P'
	CASE M.ART_LINEA = "PF"
		M.ART_TIPART = 'P'
	OTHERWISE
		M.ART_TIPART = 'A'
ENDCASE

M.ART_MAGA = "SEDE"
M.ART_CODMAT = "001"

M.ART_DATVAR = RIBALTA2(DTOC(DATE()))
M.ART_DATINS = RIBALTA2(DTOC(DATE()))

x_soci = "art_codsoc = '" + PUB_CODSOC + "'"
x_codi = "art_codpri = '" + M.ART_CODPRI + "'"
x_cond = x_soci + " and " + x_codi
cSql = "select * from U_ART_PR where " + x_cond + " order by art_codsoc,art_codpri"
IF !ExecCommand(cSql,"VERIFICA_ART_PR")
   RETURN .F.
ENDIF
SELECT VERIFICA_ART_PR
GO TOP 
IF EOF()
	cSql = "SELECT * FROM U_ART_PR WHERE 1=0"
	IF !ExecRW(cSql,"U_ART_PR","R")
	   RETURN .F.
	ENDIF
	SELECT U_ART_PR
	APPEND BLANK
	REPLACE ART_CODSOC WITH M.ART_CODSOC 
	REPLACE ART_CODPRI WITH M.ART_CODPRI 
	REPLACE ART_DESCR WITH M.ART_DESCR 
	REPLACE ART_CATMER WITH M.ART_CATMER 
	REPLACE ART_UNIMIS WITH M.ART_UNIMIS 
	REPLACE ART_UMMAGA WITH M.ART_UMMAGA 
	REPLACE ART_CODIVA WITH M.ART_CODIVA 
	REPLACE ART_LINEA WITH M.ART_LINEA 
	REPLACE ART_TIPART WITH M.ART_TIPART 
	REPLACE ART_MAGA WITH M.ART_MAGA
	REPLACE ART_CODMAT WITH M.ART_CODMAT 
	REPLACE ART_DATVAR WITH M.ART_DATVAR 
	REPLACE ART_DATINS WITH M.ART_DATINS 

	
	IF !ExecRW(cSql,"U_ART_PR","W")
	   RETURN .F.
	ENDIF
	
	cSql = "SELECT * FROM U_ART_AN WHERE 1=0"
	IF !ExecRW(cSql,"U_ART_AN","R")
	   RETURN .F.
	ENDIF
	SELECT U_ART_AN
	APPEND BLANK
	REPLACE ART_CODSOC WITH M.ART_CODSOC 
	REPLACE ART_CODPRI WITH M.ART_CODPRI
	REPLACE ART_CHDIBA WITH M.ART_CHDIBA	
	
	IF !ExecRW(cSql,"U_ART_AN","W")
	   RETURN .F.
	ENDIF
ENDIF
	
ENDPROC