*************************************************************************************************
*									CONVERSIONE GIACENZE										*
*							 																	*
*	by Erasmo Masiello per Project S.r.l.														*
*	Novembre 2013: Cardioline			 														*
*************************************************************************************************

RIT = MESSAGEBOX("Procedo con la conversione delle giacenze di magazzino dalla tabella CARD_MOVIMAG / CARD_ANAMAGA?",292,"ATTENZIONE")
IF RIT = 7
   =MESSAGEBOX("Operazione abbandonata",62,"ATTENZIONE")
   RETURN
ENDIF

CONTR_CAUMOV = ""
** SERGIO 19/11/2021 INIZIO 
*!*	x_cond = "CODICE = 'TOP" + ALLTRIM(PUB_CAUMOV) + "'"
*!*	cSql   = "SELECT LIBERA from PARA where " + x_cond
*!*	IF !ExecCommand(cSql,"TMP_PARA")
*!*		return(.f.)
*!*	ENDIF
*!*	SELECT TMP_PARA
*!*	GO TOP
*!*	IF !EOF()
*!*		CONTR_CAUMOV = SUBSTR(LIBERA,35,3)
*!*	ENDIF
CONTR_CAUMOV = CERCA_CAUSALI_TOP(PUB_CAUMOV,'CONCAU')	&& CAUSALE CONTRARIA A QUELLA DIGITATA
** SERGIO 19/11/2021 FINE  


IF EMPTY(CONTR_CAUMOV)
	MESSAGEBOX("Causale per rettifiche di magazzino di default " + ALLTRIM(PUB_CAUMOV) + " senza controcausale configurata" + REPLICATE(CHR(13),2) + ;
		"Impossibile proseguire",48,"Attenzione")
	RETURN .F.
ENDIF

_V_ANNORIF = PJ_INPUTBOX("Digitare l'anno di riferimento da considerare per i movimenti","Esercizio di riferimento","2014")
IF EMPTY(_V_ANNORIF)
	MESSAGEBOX("Operazione annullata",48,"Attenzione")
	RETURN .F.
ENDIF

_V_CODMAG = PJ_INPUTBOX("Digitare il magazzino per cui importare le giacenze","Magazzino","ZXD")
IF EMPTY(_V_CODMAG)
	MESSAGEBOX("Operazione annullata",48,"Attenzione")
	RETURN .F.
ENDIF

WAIT WINDOWS "Cancellazione vecchie giacenze e movimenti del magazzino selezionato in corso..." NOWAIT

cSql = "DELETE FROM U_MAG_GG WHERE MAG_CODMAG = '" + ALLTRIM(_V_CODMAG) + "'"
IF !ExecCommand(cSql,"DEL_MAG_GG")
   return
ENDIF

cSql = "DELETE FROM U_MAG_MO WHERE MOV_CODMAG = '" + ALLTRIM(_V_CODMAG) + "'"
IF !ExecCommand(cSql,"DEL_MAG_MO")
   return
ENDIF

_TOT_COUNT = 0
_ULT_NUMORD = 0

WAIT WINDOWS "Conversione Giacenze in corso..." NOWAIT


IF USED("CU_BFO_DD")
	SELECT CU_BFO_DD
	USE
ENDIF
IF !ExecCommand("select * from u_bfo_dd where 0=1","CU_BFO_DD")
   return(.f.)
ENDIF
SELECT CU_BFO_DD
INDEX ON ORD_SEQUEN TAG SEQUEN ADDITIVE


cSql = ""
TEXT TO cSql NOSHOW
	SELECT 
		MOVIMENTI.*,
		CARD_ANAMAGA.EPRSTANDAR AS PREZZO_COSTO_STANDARD,
		CARD_ANAMAGA.EPRULTACQU AS PREZZO_COSTO_ULTIMO_ACQUISTO
	FROM (
		SELECT
			ARTICOLO,
			COALESCE(MAGAZZINO,'') AS MAGAZZINO,
			COUNT(*) AS N_MOVIMENTI,
			SUM(CASE
					WHEN (INVENTARIO = '+' OR ACARICO = '+' OR CARICO = '+' OR ASCARICO = '-' OR SCARICO = '-') THEN QUANTITA
					WHEN (INVENTARIO = '-' OR ASCARICO = '+' OR SCARICO = '+' OR ACARICO = '-' OR CARICO = '-') THEN -1*QUANTITA
					ELSE 0
				END) AS GIACENZA,
			CASE COALESCE(SUM(CASE WHEN EPRNETTO > 0 THEN QUANTITA ELSE 0 END),0)
				WHEN 0 THEN 0
				ELSE COALESCE(SUM(CASE WHEN EPRNETTO > 0 THEN QUANTITA * EPRNETTO ELSE 0 END),0) / COALESCE(SUM(CASE WHEN EPRNETTO > 0 THEN QUANTITA ELSE 0 END),0)
			END AS PREZZO_MEDIO_PONDERATO,
			CASE COALESCE(SUM(CASE WHEN EPRNETTO > 0 AND (INVENTARIO = '+' OR ACARICO = '+' OR CARICO = '+' OR ASCARICO = '-' OR SCARICO = '-') THEN QUANTITA ELSE 0 END),0)
				WHEN 0 THEN 0
				ELSE COALESCE(SUM(CASE WHEN EPRNETTO > 0 AND (INVENTARIO = '+' OR ACARICO = '+' OR CARICO = '+' OR ASCARICO = '-' OR SCARICO = '-') THEN QUANTITA * EPRNETTO ELSE 0 END),0) 
					/ COALESCE(SUM(CASE WHEN EPRNETTO > 0 AND (INVENTARIO = '+' OR ACARICO = '+' OR CARICO = '+' OR ASCARICO = '-' OR SCARICO = '-') THEN QUANTITA ELSE 0 END),0)
			END AS PREZZO_MEDIO_PONDERATO_SOLO_CARICHI
		FROM CARD_MOVIMAG 
		WHERE SUBSTRING(ARTICOLO,1,1) <> '.' AND ESERCIZIO = '<<_V_ANNORIF>>' AND TIPO <> '..' AND COALESCE(MAGAZZINO,'') = '<<_V_CODMAG>>'
		GROUP BY ARTICOLO,MAGAZZINO
		) AS MOVIMENTI
	LEFT OUTER JOIN CARD_ANAMAGA ON CODICE = ARTICOLO
	ORDER BY ARTICOLO
ENDTEXT

IF !ExecPreparedCommand(cSql,"CX_CARD_MOVIMAG_RAGGR")
   return
ENDIF

SELECT CX_CARD_MOVIMAG_RAGGR
GO TOP
SCAN
	
	WAIT WINDOWS "Conversione Giacenza " + ALLTRIM(STR(RECNO(),10,0)) + " di " + ALLTRIM(STR(RECCOUNT(),10,0)) + ;
		" (" + ALLTRIM(STR(RECNO() * 100 / RECCOUNT(),10,0)) + "%)" NOWAIT 
	
	SCATTER MEMVAR
	
	IF M.GIACENZA = 0
		LOOP
	ENDIF
	
	IF SUBSTR(M.ARTICOLO,1,4) = '1999'
		LOOP
	ENDIF
	
	*IF ALLTRIM(M.ARTICOLO) = '16001689'
	*ELSE
	*	LOOP
	*ENDIF
	
	PUB_DATREG = DTOC(DATE())

	SELECT CU_BFO_DD
	SET ORDER TO
	ZAP

	_X_CODMAT = ""
	_X_UMMAGA = ""
	_X_DESART = ""
	_X_ALTEZZ = 0
	_X_LUNGHE = 0
	_X_SPESSO = 0
	_X_MAGDEF = ""
	_X_CODIVA = ""
	x_soci = "ART_CODSOC = '" + PUB_CODSOC + "'"
	x_codi = "ART_CODPRI = '" + ALLTRIM(M.ARTICOLO) + "'"
	x_cond = x_soci + " and " + x_codi
	Csql   = "SELECT ART_DESCR, ART_UMMAGA, ART_CODMAT, ART_ALTEZZ, ART_LUNGHE, ART_SPESSO, ART_MAGA, ART_CODIVA FROM U_ART_PR WHERE " + x_cond
	IF !ExecCommand(cSql,"TMP_ART_PR")
	   return(.f.)
	ENDIF
	SELECT TMP_ART_PR
	GO TOP
	IF EOF()
		MESSAGEBOX("Articolo '" + ALLTRIM(M.ARTICOLO) + "' non trovato in anagrafica",48,"Attenzione")
		SELECT CX_CARD_MOVIMAG_RAGGR
		LOOP
	ELSE
		_X_CODMAT = ART_CODMAT
		_X_UMMAGA = ALLTRIM(ART_UMMAGA)
		_X_DESART = ALLTRIM(ART_DESCR)
		_X_ALTEZZ = ART_ALTEZZ
		_X_LUNGHE = ART_LUNGHE
		_X_SPESSO = ART_SPESSO
		_X_MAGDEF = ART_MAGA
		_X_CODIVA = ART_CODIVA
	ENDIF
	
	_X_PRZACQ = IIF(!ISNULL(M.PREZZO_COSTO_ULTIMO_ACQUISTO),M.PREZZO_COSTO_ULTIMO_ACQUISTO,0)
	
	
	_D_CODMAG = IIF(UPPER(ALLTRIM(M.MAGAZZINO)) == "VEN","SEDE",UPPER(ALLTRIM(M.MAGAZZINO)))
	IF EMPTY(_D_CODMAG)
		_D_CODMAG = ALLTRIM(_X_MAGDEF)
	ENDIF
	_D_DESMAG = ''
	x_cond = "codice = 'MAG" + ALLTRIM(_D_CODMAG) + "'"
	cSql   = "select CODICE, DESCRI from para where " + x_cond
	IF !ExecCommand(cSql,'CX_PARA')
	   return(.f.)
	ENDIF
	SELECT CX_PARA
	GO TOP
	IF EOF()
	   _D_DESMAG = ""
	ELSE
	   _D_DESMAG = DESCRI
	ENDIF
	
	SELECT CU_BFO_DD
	APPEND BLANK
	REPLACE DAGGANCIO  WITH '1111111111'
	REPLACE ORD_CODART WITH ALLTRIM(M.ARTICOLO)
	REPLACE ORD_NUMBOB WITH 0
	REPLACE ORD_UM     WITH _X_UMMAGA
	REPLACE ORD_IVA    WITH _X_CODIVA 
	REPLACE ORD_DESART WITH _X_DESART
	REPLACE ORD_MAGA   WITH _D_CODMAG			
	REPLACE ORD_QTAORD WITH ABS(M.GIACENZA)
	REPLACE ORD_PREZZO WITH _X_PRZACQ
	REPLACE ORD_SC1    WITH 0
	REPLACE ORD_SC2    WITH 0
	REPLACE ORD_SC3    WITH 0
	REPLACE ORD_PRZNET WITH _X_PRZACQ
	REPLACE ORD_VALORE WITH ROUND((ORD_PRZNET*ORD_QTAORD),2)
	REPLACE ORD_DATCON WITH RIBALTA2(DTOC(DATE()))
	REPLACE ORD_CODSYS WITH SYS(2015)
	REPLACE ORS_CODCLI WITH PUB_CFDEF
	REPLACE ORS_RAGSOC WITH ""  
	REPLACE ORS_NUMORD WITH "INV" + ALLTRIM(_V_ANNORIF)
	REPLACE ORS_DATORD WITH PUB_DATREG
	REPLACE ORS_VALUTA WITH PUB_VALU
	REPLACE ORD_SEQUEN WITH 0
	REPLACE ORD_LEGAME WITH '1111111111'
	REPLACE ORD_LEGSYS WITH SYS(2015)
	REPLACE ORD_FLGMOD WITH 'I'
	REPLACE ORS_NUMIDE WITH ""
	REPLACE ORS_ANNO   WITH SUBSTR(PUB_DATREG,1,4)
	REPLACE ORD_LEGASY WITH SYS(2015)
	REPLACE ORD_SALCON WITH 'S'
	REPLACE ORD_DTASCA WITH RIBALTA2(DTOC(DATE()))
	REPLACE ORD_QTAML  WITH 0
	REPLACE ORD_QTAMQ  WITH 0
	REPLACE ORD_QTAKG  WITH 0
	*REPLACE ORD_QTAMC  WITH M.QTAMCPROD 
	REPLACE ORD_QTAML1 WITH 0
	REPLACE ORD_QTAMQ1 WITH 0
	REPLACE ORD_QTAKG1 WITH 0
	REPLACE ORD_ALTEZZ WITH _X_ALTEZZ
	REPLACE ORD_LUNGHE WITH _X_LUNGHE
	REPLACE ORD_SPESSO WITH _X_SPESSO
	REPLACE ORD_CODMAT WITH _X_CODMAT 
	REPLACE ORD_CODCOL WITH "" 
	REPLACE ORD_DESMAT WITH ""
	REPLACE ORD_FILA_X WITH "" 
	REPLACE ORD_PIAN_X WITH ""
	REPLACE ORD_UBIC_X WITH ""
	REPLACE ORD_FILA_N WITH 0
	REPLACE ORD_PIAN_N WITH 0
	REPLACE ORD_UBIC_N WITH 0
	REPLACE ORD_SYSMAG WITH SYS(2015)
	*REPLACE ORD_TIPBOB WITH PUB_TIPOBOB
	*REPLACE ORD_QUAPRO WITH IIF(M.FLGNONCONF,"99","01")
	REPLACE ORD_CLIENT WITH ""

	SCATTER MEMVAR MEMO
	
	M.ORD_CAUS   = PUB_CAUMOV
	M.ORD_NUMORD = M.ORS_NUMORD
	M.ORD_DATORD = M.ORS_DATORD
	M.ORD_CODCLI = M.ORS_CODCLI
	M.ORD_RAGSOC = M.ORS_RAGSOC
	M.ORD_CODACQ = M.ORS_CODACQ
	M.ORD_VALUTA = M.ORS_VALUTA
	M.ORD_NUMIDE = AQM_NEW_NUMIDE()
	M.ORD_CODBUN = ""

	SELECT CU_BFO_DD
	GO TOP
	
	IF M.GIACENZA > 0

		XXY_CODINT = ""
		XXY_NRLINT = 0
		XXY_UNIQUE = ""
		=AQM_GESTIONE_CARICHI_BFO()
		_W_CODINT = XXY_CODINT
		_W_MAG_UNIQUE = XXY_UNIQUE 
	
	ELSE
		
		XXX_CAUS = CONTR_CAUMOV
		AQM_NUMMOV_LOCALE = AQM_RILEVA_NUMERO_INTERNO()
		XXX_NUMORD = M.ORD_NUMORD
		XXX_DATORD = IIF(SUBSTR(M.ORD_DATORD,3,1) = '/',RIBALTA2(M.ORD_DATORD),M.ORD_DATORD)
		XXX_VALUTA = M.ORD_VALUTA
		XXX_CODBUN = M.ORD_CODBUN
		XXX_NUMIDE = M.ORD_NUMIDE
		XXX_ANAART = M.ORD_CODART
		XXX_CODFOR = M.ORD_CODCLI
		XXX_FLGMOD = M.ORD_FLGMOD
		
		=AQM_DEFINISCE_AQM_VARIABILI_MAGAZZINO()
		=AQM_VALORIZZA_VARIABILI_MAGAZZINO("CU_BFO_DD")		
		DO AQM_SCARICA_MAGAZZINO_GIACENZE_NEGATIVE
	
	ENDIF		
		
	_TOT_COUNT = _TOT_COUNT + 1
	
ENDSCAN


WAIT WINDOWS "Aggiornamento dati ultimo carico articoli residui..." NOWAIT

Csql = ""
TEXT TO cSql NOSHOW
	UPDATE U_ART_PR SET 
		ART_ULPCAR = (SELECT COALESCE(EPRULTACQU,0) FROM CARD_ANAMAGA WHERE CODICE = U_ART_PR.ART_CODPRI),
		ART_ULDCAR = CASE COALESCE((SELECT DTULTACQUI FROM CARD_ANAMAGA WHERE CODICE = U_ART_PR.ART_CODPRI),'') WHEN '' THEN '' ELSE (SELECT SUBSTRING(DTULTACQUI,1,4)+'/'+SUBSTRING(DTULTACQUI,5,2)+'/'+SUBSTRING(DTULTACQUI,7,2) FROM CARD_ANAMAGA WHERE CODICE = U_ART_PR.ART_CODPRI) END
	WHERE U_ART_PR.ART_ULPCAR = 0
ENDTEXT
IF !ExecCommand(cSql,"UDP_ART_PR")
   return
ENDIF


WAIT CLEAR

MESSAGEBOX("Operazione terminata correttamente" + REPLICATE(CHR(13),2) + ;
	"Totale giacenze convertite: " + ALLTRIM(STR(_TOT_COUNT,10,0)),64,"Informazione")

RETURN


 