*************************************************************************************************
*							CONVERSIONE ANAGRAFICA BANCHE										*
*							 																	*
*	by Giuseppe,Fabio,Sergio																	*
*	23/01/2004				 																	*
*************************************************************************************************

*** conferma utente

		RIT = MESSAGEBOX("Procedo con la conversione "+CHR(13)+"dell'anagrafica banche ?",292,"ATTENZIONE")
		IF RIT = 7
		   =MESSAGEBOX("Operazione abbandonata",62,"ATTENZIONE")
		   RETURN
		ENDIF




** ASSEGNAZIONE DELLA VARIABILE PATH **************************
		
		*!*	=OPENDB("PERCORSO")
		*!*	SELECT PERCORSO
		*!*	SET ORDER TO I_TIPO
		*!*	SEEK 'BAN'
		*!*	IF FOUND()
		*!*	ELSE
		*!*	   RETURN
		*!*	ENDIF

		*!*	SELECT PERCORSO
		*!*	V_PATH = ALLTRIM(PER_PATH)

		V_PATH = ""


****** DEFINIZIONE DEL CURSORE STP

		IF !ExecCommand("select * from U_BAN_AN where 1=0","curs_u_ban_an")
		   return
		ENDIF


		WAIT WINDOWS "ATTENDERE PREGO, CANCELLAZIONE VECCHIA ANAGRAFICA BANCHE" NOWAIT


*** CANCELLAZIONE DEI RECORD DELLA TABELLA U_BAN_AN SQL

		cSql = "delete from U_BAN_AN where 1=1"
		IF !ExecCommand(cSql,"U_BAN_AN")
		   return(.f.)
		ENDIF

******** DEFINISCE LE VARIABILI E CREA IL CURSORE DI SUPPORTO

		RELEASE Y_CAMPO,V_CAMPO,_CTR,_PROGRE
		PUBLIC Y_CAMPO,V_CAMPO,_CTR,_PROGRE
		Y_CAMPO = ""
		V_CAMPO = ""
		_CTR    = 0
		_PROGRE = 0
		CREATE CURSOR TRANSITO (TRA_RECORD C(200))

		*SELECT TRANSITO
		*APPEND FROM &V_PATH SDF



**** CARICAMENTO DEL FILE IN FORMATO TESTO

		SELECT TRANSITO  
		gcTable = GETFILE('', 'Seleziona file banche da convertire', 'Converti',0)
		IF empty(gcTable) .or. gcTable = ""
		   =MESSAGEBOX("Nessun file selezionato, operazione abbandonata",62,"ATTENZIONE")
		   RETURN
		ENDIF
		APPEND FROM &gcTable SDF
		GO TOP

***** TOGLIE I RECORD SUPERFLUI

		SELECT TRANSITO

		DELETE FOR SUBSTR(TRA_RECORD,2,5) = "-----"  ALL
		GO TOP
		DELETE FOR SUBSTR(TRA_RECORD,5,7) = "Azienda"  ALL
		GO TOP
		DELETE FOR SUBSTR(TRA_RECORD,1,2) = "=="  ALL
		GO TOP
		DELETE FOR SUBSTR(TRA_RECORD,2,2) = "=="  ALL
		GO TOP
		DELETE FOR SUBSTR(TRA_RECORD,2,13) = "Banca/Agenzia"  ALL
		GO TOP
		DELETE FOR empty(TRA_RECORD)   ALL
		GO TOP

***** ELABORA IL CURSORE transito PER CREARE IL CURSORE STP


		SELECT TRANSITO
		GO TOP


		DO WHILE .T.

		   IF EOF()
		      EXIT
		   ENDIF

		*!*	   IF SUBSTR(TRA_RECORD,1,8) = SPACE(08)
		*!*	      SKIP +1
		*!*	      LOOP
		*!*	   ENDIF

		******** ASSEGNAZIONE VARIABILI DEL FILE DI TESTO CHE E' CONTENUTO NEL CURSORE TRANSITO

		   SELECT TRANSITO
		    	            
           IF  SUBSTR(TRA_RECORD,11,2) = " 0"							&& SONO SUL RECORD BANCA : MEMORIZZO LA DESCRIZIONE
			   M.BAN_DESBAN = ALLTRIM(SUBSTR(TRA_RECORD,21,34))
   		       M.BAN_DESBAN = UPPER(M.BAN_DESBAN)
               M.BAN_DESBAN = APITOSPA(M.BAN_DESBAN)
			   SELECT TRANSITO      
			   SKIP +1
        	   LOOP	   
           ENDIF 
           M.BAN_CODSOC = '01' 
 		   _PROGRE= _PROGRE + 1
		   M.BAN_CODBAN = ALLTRIM(STR(_PROGRE,5,0))						&& RICORDARSI DI AGGIUNGERE ZERI NON SIGNIFIcativi 
           PUB_LNO = 5
           M.BAN_CODBAN = TRC(PUB_LNO,ALLTRIM(M.BAN_CODBAN))

		   M.BAN_DESBAN = M.BAN_DESBAN + ' - ' + ALLTRIM(SUBSTR(TRA_RECORD,21,34))
	       M.BAN_DESBAN = UPPER(M.BAN_DESBAN)
           M.BAN_DESBAN = APITOSPA(M.BAN_DESBAN)

		   M.BAN_INDIR  = ALLTRIM(SUBSTR(TRA_RECORD,21,34))      
   		   M.BAN_INDIR  = UPPER(M.BAN_INDIR )
           M.BAN_INDIR  = APITOSPA(M.BAN_INDIR )
		   M.BAN_CODABI = ALLTRIM(SUBSTR(TRA_RECORD,55,5))
           M.BAN_CODABI = TRC(PUB_LNO,ALLTRIM(M.BAN_CODABI))
		   M.BAN_CODCAB = ALLTRIM(SUBSTR(TRA_RECORD,72,5))
           M.BAN_CODCAB = TRC(PUB_LNO,ALLTRIM(M.BAN_CODCAB))
   	


		*!*	   V_CAMPO      = ALLTRIM(SUBSTR(TRA_RECORD,127,5))
		*!*	   DO TOGLI_PUNTI

		   SELECT curs_u_ban_an				&& CREAZIONE DEL CURSORE STP PER IL SUCCESSIVO AGGIORNAMENTO IN AMBIENTE SQL
		   APPEND BLANK
		   GATHER MEMVAR MEMO 				&& EFFETTUA LA REPLACE NEL CURSORE STP FOX SOSTITUENDO LE REPLACE DI OGNI SINGOLO CAMPO 
											&&  ESEMPIO : REPLACE BAN_CODBAN WITH M.BAN_CODBAN		   
		   
		   _CTR = _CTR +1
		   WAIT WINDOWS "RECORDS SCRITTI : "+STR(_CTR,10,0) NOWAIT

		   SELECT TRANSITO      
		   SKIP +1

		ENDDO



SELECT curs_u_ban_an
GO TOP
***BROWSE NORMAL


****** AGGIORNA TABELLA U_BAN_AN SQL

		IF !ExecRW('','U_BAN_AN','I','','curs_u_ban_an')
		   return(.f.)
		ENDIF
	 
=MESSAGEBOX("OPERAZIONE TERMINATA CORRETTAMENTE ",62,"ATTENZIONE")

RETURN

   
*********************
PROCEDURE TOGLI_PUNTI
*********************

YY      = LEN(V_CAMPO)
XX      = 1
Y_CAMPO =  ' '
DO WHILE .T.
   IF XX > YY
      EXIT
   ENDIF
   IF SUBSTR(V_CAMPO,XX,1) = '.' 
   ELSE
      Y_CAMPO = Y_CAMPO + SUBSTR(V_CAMPO,XX,1) 
   ENDIF
   XX = XX + 1
ENDDO

RETURN


**************************
PROCEDURE VERIFICA_CLIENTE
**************************

x_soci = "cli_codsoc = '" + M.CLI_CODSOC + "'"
x_codi = "cli_codcli = '" + M.CLI_CODCLI + "'"
x_cond = x_soci + " and " + x_codi
cSql   = "select * from u_cli_an where " + x_cond + " order by cli_codsoc,cli_codcli"
IF !ExecRW(cSql,"u_cli_an","R")
   return
ENDIF
SELECT u_cli_an
IF EOF()
   m.id_unique = ""
   APPEND BLANK
ENDIF
M.CLI_RAGSOC = UPPER(M.CLI_RAGSOC)
M.CLI_RAGSOC = APITOSPA(M.CLI_RAGSOC)
M.CLI_INDIR  = UPPER(M.CLI_INDIR)
M.CLI_INDIR  = APITOSPA(M.CLI_INDIR)
M.CLI_LOCALI = UPPER(M.CLI_LOCALI)
M.CLI_LOCALI = APITOSPA(M.CLI_LOCALI)
M.CLI_PROVIN = UPPER(M.CLI_PROVIN)
M.CLI_PROVIN = APITOSPA(M.CLI_PROVIN)
M.CLI_CODFIS = UPPER(M.CLI_CODFIS)
M.CLI_CODFIS = APITOSPA(M.CLI_CODFIS)

REPLACE CLI_CODSOC WITH M.CLI_CODSOC
REPLACE CLI_CODCLI WITH M.CLI_CODCLI
REPLACE CLI_RAGSOC WITH M.CLI_RAGSOC
REPLACE CLI_INDIR  WITH M.CLI_INDIR
REPLACE CLI_CAP    WITH M.CLI_CAP
REPLACE CLI_LOCALI WITH M.CLI_LOCALI
REPLACE CLI_PROVIN WITH M.CLI_PROVIN
REPLACE CLI_PARIVA WITH M.CLI_PARIVA
REPLACE CLI_CODFIS WITH M.CLI_CODFIS
REPLACE CLI_AGE    WITH M.CLI_AGE
REPLACE CLI_SC1    WITH M.CLI_SC1
REPLACE CLI_SC2    WITH M.CLI_SC2
REPLACE CLI_TELEFO WITH M.CLI_TELEFO
REPLACE CLI_TELEX  WITH M.CLI_TELEX
REPLACE CLI_FAX    WITH M.CLI_FAX
REPLACE CLI_VALUTA WITH PUB_VALU
REPLACE CLI_NAZION WITH PUB_NAZI
REPLACE CLI_DATNEW WITH RIBALTA2(DTOC(DATE()))
REPLACE CLI_DATINS WITH RIBALTA2(DTOC(DATE()))
REPLACE CLI_CONPAG WITH PUB_CPA
REPLACE CLI_CODIVA WITH PUB_IVA
REPLACE CLI_BDAL   WITH "0108"
REPLACE CLI_BAL    WITH "3108"
REPLACE CLI_GG1    WITH "1009"
REPLACE CLI_B2DAL  WITH "2012"
REPLACE CLI_B2AL   WITH "3112"
REPLACE CLI_GG2    WITH "1001"
REPLACE CLI_TIPFAT WITH "FDV"
REPLACE CLI_FLGTRA WITH .T.

IF !ExecRW(cSql,"u_cli_an","W")
   return
ENDIF



_CTR = _CTR +1
WAIT WINDOWS "RECORDS SCRITTI : "+STR(_CTR,10,0) NOWAIT

RETURN