*********************************************************************************************
*																							*
*									 		*   											*
*	 								    ECASH SQL											*
*									 														*
*									      V 2002											*
*								            by 												*
*								       PROJECT S.R.L										*
*																							*
*							   STARTUP GESTIONE CASSE TECNOLOGICHE							*
*							     PER VENDITA AL BANCO  ANNO 2003 							*
*											*												*
*																							*
*																							*
* 			                                                               € Compliant      *
*																							*
*********************************************************************************************
PARAMETERS _codcassa

*CLEAR ALL
CLOSE ALL

SET MULTILOCKS ON
PUBLIC pub_sqlhd,pub_datawh
pub_sqlhd  = 0
pub_datawh = ""

SET PROCEDURE TO SQLLIB 	ADDITIVE

** Creazione ZToolbar dalla libreria ZClassLib
SET CLASSLIB TO ZCLASLIB ADDITIVE
PUBLIC ZTB,ZTF,ZTR
ZTB=CREATEOBJECT("ZTOOLBAR")
ZTR=CREATEOBJECT("ZTOOLRIC")
ZTF=CREATEOBJECT("OTOOLBAR")
ZTB.DOCK(0)
ZTF.DOCK(0)
ZTF.SHOW

** Impostazione SET Iniziali
SET STATUS BAR OFF
SET AUTOSAVE ON
SET CENTURY ON
SET CLOCK STATUS

****** SET DATE TO GERMAN

SET DATE TO DMY

SET DELETED ON
SET ESCAPE OFF
SET EXACT ON
SET EXCLUSIVE OFF
SET HOURS TO 24
SET NEAR ON
SET REPROCESS TO AUTOMATIC
SET SAFETY OFF
SET TALK OFF
SET MARK TO "/"
SET DECIMAL TO 6  && GESTIONE EURO

** Aggancio librerie di procedure esterne
SET PROCEDURE TO ECASHLIB 		ADDITIVE
SET PROCEDURE TO WINLIB 		ADDITIVE
SET PROCEDURE TO UTILITA 		ADDITIVE
SET PROCEDURE TO FTPLIB 		ADDITIVE
SET PROCEDURE TO RS232COMLIB	ADDITIVE
SET PROCEDURE TO REPLIB 		ADDITIVE
*SET PROCEDURE TO RICLIB 		ADDITIVE
*SET PROCEDURE TO PRNLIB 		ADDITIVE
*SET PROCEDURE TO ETILIB 		ADDITIVE
SET PROCEDURE TO PROJLIB 		ADDITIVE
SET PROCEDURE TO APPLILIB 		ADDITIVE
SET PROCEDURE TO CONTABILELIB	ADDITIVE
SET PROCEDURE TO MAGAZZINOLIB	ADDITIVE
*SET PROCEDURE TO FORMLIB 		ADDITIVE
*SET PROCEDURE TO DAVLIB 		ADDITIVE

*******************************************************
* -->> controlla se è già in esecuzione un ecash
*******************************************************
IF ProcessiExe("S","ecash.exe")
  RETURN
ENDIF
*******************************************************

PUBLIC PUB_CODSOC,PUB_DESSOC,PUB_CODOPE,PUB_NOMOPE,PUB_PASSWORD,PUB_UFILE,PUB_NOMSOC, ;
       PUB_VALRIF,COMPENSO,PUB_ARRIVO,PUB_ECASH,PUB_GESTIONE,P_CASSA
PUB_CODSOC   = "01"
PUB_DESSOC   = ""
PUB_CODOPE   = ""
PUB_NOMOPE   = ""
PUB_PASSWORD = ""
PUB_UFILE    = ""
PUB_NOMSOC   = ""
PUB_VALRIF   = 'EUR'
COMPENSO     = 0
PUB_ARRIVO   = 'ECASH'
PUB_ECASH    = SPACE(05)
PUB_GESTIONE = SPACE(01)
P_CASSA      = _CODCASSA
RELEASE PUB_PRIVACY
PUBLIC PUB_PRIVACY
PUB_PRIVACY ="Ai sensi della legge 300 del 1970 la pubblicazione delle telecamere costituisce "+CHR(13)+;
			 "esplicito consenso della pubblicazione delle immagini in remoto delle telecamere addette al circuito chiuso del punto di vendita."+CHR(13)+;
			 "In qualsiasi momento è possibile modificare le pubblicazioni delle stesse. "+CHR(13)+;
			 "Il semaforo rosso individua il divieto di pubblicazione , mentre il semaforo "+CHR(13)+;
			 "verde ed il giallo individuano stati di pubblicazione totali o parziali."+CHR(13)+;
			 "Si rammenta che le pubblicazioni hanno tassativamente scopo organizzativo "+CHR(13)+;
			 "o di supporto alle strategie di vendita o degli eventi all interno del punto"+CHR(13)+;
			 "di vendita , inoltre le immagini pubblicate quando vengono visualizzate "+CHR(13)+;
			 "in remoto , vengono viste e perse."+CHR(13)+;
			 "Per qualsiasi chiarimento vi preghiamo di contattare direttamente la sede."

PUBLIC PUB_LCL,PUB_ARCH      && DEFINISCE LA LUNGHEZZA DEL CODICE CLIENTE 
PUB_LCL  = 9
PUB_ARCH = ''

PUBLIC PUB_CC,PUB_FF,PUB_ER,PUB_ANNO
PUB_CC     = SPACE(04)
PUB_FF     = SPACE(04)
PUB_ER     = SPACE(04)
PUB_ANNO   = SUBSTR(DTOC(DATE()),7,4)

RELEASE PUB_MESERR,PUB_FAMTU,PUB_BOLLA,PUB_FAPRO,PUB_ORDIN,PUB_FATTU,PUB_FATTR,PUB_EFFE,    ;
        PUB_ORFO,PUB_OFFE,PUB_COMM,PUB_CTLO,PUB_CODM,PUB_SAU,PUB_NOSC,PUB_SKART,PUB_RISOLU, ;
        PUB_IVA,PUB_NCR,PUB_ESIVA,PUB_NORD,PUB_TFTOP,PUB_COMCEE,PUB_PREZZI,PUB_NBOBA,       ;
        PUB_CTRGIA,PUB_CTRORF,PUB_CLIDIR,PUB_CAUDIR,PUB_CERTIF,PUB_CAUANT,PUB_CAUAVA,       ;
        PUB_CAUSAL,PUB_COMSEM,PUB_CPAINC,PUB_ARTINC,PUB_CAUCFO,PUB_CAUCSP,PUB_CAUSSP,       ;
        PUB_CAUSFA,PUB_OREGIO,PUB_CAUCMA,PUB_DDTRIC,PUB_UM,PUB_VERYD,PUB_SPINC,PUB_SCAFA,PUB_CFDEF,    ;
        PUB_CADEF,PUB_WEBRCF,PUB_WEBRCD,PUB_WEBTRF,PUB_WEBTRD,PUB_MLPLTU,PUB_MLPLDT,        ;
        PUB_MLEBDT,PUB_QTAORF,PUB_MAGLOG,PUB_PROGAA,PUB_NOSPOO,PUB_CAULES,PUB_SC1,PUB_SC2,  ;
        PUB_SC3,PUB_PROVVI,PUB_PAGANT,PUB_BFO,PUB_BOLFOR,PUB_CTRLBF,PUB_CODBUN,PUB_VISRIC,PUB_CADEF,   ;
        PUB_NBOIE,PUB_NFANC,PUB_LIS01,PUB_LIS02,PUB_LIS03,PUB_LIS04,PUB_LIS05,PUB_LIS06,    ;
        PUB_LIS07,PUB_LIS08,PUB_LIS09,PUB_LIS0A,PUB_LINEA,PUB_STFAD,PUB_STFAT,PUB_STFAP,    ;
        PUB_CPA,PUB_AGE,PUB_VALU,PUB_NAZI,PUB_CLISOC,PUB_RAGSOC,PUB_FORMAR,PUB_MLDOCA,      ;
        PUB_MASTRO,PUB_SOTTOG,PUB_NUMLOT,PUB_CONTO,PUB_EAISBN,PUB_CDISBN,PUB_VISRID,		;
        PUB_CTRTAG,PUB_CTRCOL,PUB_CATACO,PUB_ARTRES,PUB_CAURES,PUB_CAUREC,PUB_CAUCAS,       ;
        PUB_CODCAS,PUB_NOSOL,PUB_AACDAL,PUB_AACAL,PUB_ROTT,PUB_CAURIF,PUB_CAUREF,PUB_GESEDI,;
        PUB_CFM,PUB_TIPCAS,PUB_ARTABB,PUB_FORPRE

PUBLIC  PUB_MESERR,PUB_FAMTU,PUB_BOLLA,PUB_FAPRO,PUB_ORDIN,PUB_FATTU,PUB_FATTR,PUB_EFFE,    ;
        PUB_ORFO,PUB_OFFE,PUB_COMM,PUB_CTLO,PUB_CODM,PUB_SAU,PUB_NOSC,PUB_SKART,PUB_RISOLU, ;
        PUB_IVA,PUB_NCR,PUB_ESIVA,PUB_NORD,PUB_TFTOP,PUB_COMCEE,PUB_PREZZI,PUB_NBOBA,       ;
        PUB_CTRGIA,PUB_CTRORF,PUB_CLIDIR,PUB_CAUDIR,PUB_CERTIF,PUB_CAUANT,PUB_CAUAVA,       ;
        PUB_CAUSAL,PUB_COMSEM,PUB_CPAINC,PUB_ARTINC,PUB_CAUCFO,PUB_CAUCSP,PUB_CAUSSP,       ;
        PUB_CAUSFA,PUB_OREGIO,PUB_CAUCMA,PUB_DDTRIC,PUB_UM,PUB_VERYD,PUB_SPINC,PUB_SCAFA,PUB_CFDEF,    ;
        PUB_CADEF,PUB_WEBRCF,PUB_WEBRCD,PUB_WEBTRF,PUB_WEBTRD,PUB_MLPLTU,PUB_MLPLDT,        ;
        PUB_MLEBDT,PUB_QTAORF,PUB_MAGLOG,PUB_PROGAA,PUB_NOSPOO,PUB_CAULES,PUB_SC1,PUB_SC2,  ;
        PUB_SC3,PUB_PROVVI,PUB_PAGANT,PUB_BFO,PUB_BOLFOR,PUB_CTRLBF,PUB_CODBUN,PUB_VISRIC,PUB_CADEF,   ;
        PUB_NBOIE,PUB_NFANC,PUB_LIS01,PUB_LIS02,PUB_LIS03,PUB_LIS04,PUB_LIS05,PUB_LIS06,    ;
        PUB_LIS07,PUB_LIS08,PUB_LIS09,PUB_LIS0A,PUB_LINEA,PUB_STFAD,PUB_STFAT,PUB_STFAP,    ;
        PUB_CPA,PUB_AGE,PUB_VALU,PUB_NAZI,PUB_CLISOC,PUB_RAGSOC,PUB_FORMAR,PUB_MLDOCA,      ;
        PUB_MASTRO,PUB_SOTTOG,PUB_NUMLOT,PUB_CONTO,PUB_EAISBN,PUB_CDISBN,PUB_VISRID,		;
        PUB_CTRTAG,PUB_CTRCOL,PUB_CATACO,PUB_ARTRES,PUB_CAURES,PUB_CAUREC,PUB_CAUCAS,       ;
        PUB_CODCAS,PUB_NOSOL,PUB_AACDAL,PUB_AACAL,PUB_ROTT,PUB_CAURIF,PUB_CAUREF,PUB_GESEDI,;
        PUB_CFM,PUB_TIPCAS,PUB_ARTABB,PUB_FORPRE

RELEASE PUB_TIPCON,PUB_PRZBAS,PUB_DATOLD,PUB_CAMCOS
PUBLIC  PUB_TIPCON,PUB_PRZBAS,PUB_DATOLD,PUB_CAMCOS

RELEASE PUB_PAGINA
PUBLIC  PUB_PAGINA
PUB_PAGINA = 20

PUB_CDISBN = SPACE(50)

_SCREEN.visible = .F.

=AQUADOCU()

DO CASE

   CASE PUB_TIPCAS = '1'
        SET PROCEDURE TO prg\MWCRLIB ADDITIVE
        V_ERR = ApriConnessione(1)
        *IF !V_ERR
            *   V_TESTO = "Impossibile comunicare col misuratore fiscale"
            *   V_FORM  = "DO FORM FORM\MESSAGE_ECASH WITH '" + V_TESTO + "'"
        *   SEGNALA ERRORE CON DESIDERI CONTINUARE UGUALMENTE
        *ENDIF

   CASE PUB_TIPCAS = '2'
        SET PROCEDURE TO prg\EPSONLIB ADDITIVE

   CASE PUB_TIPCAS = '3'
        SET PROCEDURE TO prg\OLIVETTILIB ADDITIVE
        V_ERR = ApriConnessione(1)

ENDCASE   

PUB_CODCAS  = P_CASSA

RELEASE QQR_CODPDV,QQR_DESPDV,QQR_CODCAS,QQR_DESCAS,QQR_TIPCAS,QQR_DESTIP,QQR_AMGINI,QQR_DATINI, ;
        QQR_ORAINI,QQR_PROINI,QQR_AMGFIN,QQR_DATFIN,QQR_ORAFIN,QQR_PROFIN,QQR_PROTOT
PUBLIC  QQR_CODPDV,QQR_DESPDV,QQR_CODCAS,QQR_DESCAS,QQR_TIPCAS,QQR_DESTIP,QQR_AMGINI,QQR_DATINI, ;
        QQR_ORAINI,QQR_PROINI,QQR_AMGFIN,QQR_DATFIN,QQR_ORAFIN,QQR_PROFIN,QQR_PROTOT
QQR_CODPDV = SPACE(10)
QQR_DESPDV = SPACE(50)
QQR_CODCAS = SPACE(03)
QQR_DESCAS = SPACE(10)
QQR_TIPCAS = SPACE(01)
QQR_DESTIP = SPACE(20)
QQR_AMGINI = SPACE(10)
QQR_DATINI = SPACE(10)
QQR_ORAINI = SPACE(08)
QQR_PROINI = 0
QQR_AMGFIN = SPACE(10)
QQR_DATFIN = SPACE(10)
QQR_ORAFIN = SPACE(08)
QQR_PROFIN = 0
QQQ_PROTOT = 0

QQR_CODPDV = PUB_CODBUN
x_cond     = "pdv_codice = '" + ALLTRIM(QQR_CODPDV) + "'"
Csql       = "select * from u_pdv_an where " + x_cond
IF !ExecCommand(Csql,"CU_PDV_AN")
   return(.f.)
ENDIF
SELECT CU_PDV_AN
GO TOP
IF EOF()
   QQR_DESPDV = SPACE(10)
ELSE
   QQR_DESPDV = PDV_DESCRI
ENDIF

QQR_CODCAS = PUB_CODCAS
v_seek     = 'NUMNRC' + QQR_CODCAS
v_chiave   = "codice"
cSql       = "select * from para where " + v_chiave + " = '" + v_seek + "'"
IF !ExecCommand(cSql,"PARA")
   return(.f.)
ENDIF
SELECT PARA
IF RECCOUNT() <> 0
   QQR_DESCAS = DESCRI
   QQR_PROINI = VAL(ALLTRIM(SUBSTR(LIBERA,1,7)))
ELSE
   QQR_DESCAS = SPACE(50)
   QQR_PROINI = 0
ENDIF

QQR_TIPCAS = PUB_TIPCAS
IF QQR_TIPCAS = '0'
   QQR_DESTIP = 'Nessuna cassa'
ENDIF
IF QQR_TIPCAS = '1'
   QQR_DESTIP = 'Cassa Mwcr'
ENDIF
IF QQR_TIPCAS = '2'
   QQR_DESTIP = 'Cassa Epson'
ENDIF
IF QQR_TIPCAS = '3'
   QQR_DESTIP = 'Cassa Olivetti'
ENDIF

QQR_DATINI = DTOC(DATE())
QQR_ORAINI = TIME()

v_cond = "codice like 'NUMNRC%'"
cSql   = "select * from para where " + v_cond
IF !ExecCommand(cSql,"PARA")
   return(.f.)
ENDIF
SELECT PARA
GO TOP
DO WHILE .T.
   IF EOF()
      EXIT
   ENDIF
   IF ALLTRIM(DESIVA) = 'CASSA'
   ELSE
      SKIP +1
      LOOP
   ENDIF
   XW_CODCAS = SUBSTR(CODICE,7,3)
   XW_DESCAS = DESCRI
   x_soci = "mon_codsoc = '" + PUB_CODSOC + "'"
   x_cpdv = "mon_codpdv = '" + ALLTRIM(QQR_CODPDV) + "'"
   x_cass = "mon_codcas = '" + ALLTRIM(XW_CODCAS) + "'"
   x_data = "mon_amgini = '" + RIBALTA2(DTOC(DATE())) + "'"
   x_cond = x_soci + " and " + x_cpdv + " and " + x_cass + " and " + x_data
   Csql   = "select * from u_mon_ca where " + x_cond
   IF !ExecRW(Csql,"U_MON_CA","R")
      return(.f.)
   ENDIF
   SELECT U_MON_CA
   IF EOF()
      APPEND BLANK
      REPLACE MON_CODSOC WITH PUB_CODSOC
      REPLACE MON_CODPDV WITH QQR_CODPDV
      REPLACE MON_DESPDV WITH QQR_DESPDV
      REPLACE MON_CODCAS WITH XW_CODCAS
      REPLACE MON_DESCAS WITH XW_DESCAS
      REPLACE MON_TIPCAS WITH QQR_TIPCAS
      REPLACE MON_DESTIP WITH QQR_DESTIP
      REPLACE MON_AMGINI WITH RIBALTA2(QQR_DATINI)
      REPLACE MON_DATINI WITH QQR_DATINI
      REPLACE MON_ORAINI WITH SPACE(08)
      REPLACE MON_PROINI WITH 0
      REPLACE MON_AMGFIN WITH SPACE(10)
      REPLACE MON_DATFIN WITH SPACE(10)
      REPLACE MON_ORAFIN WITH SPACE(08)
      REPLACE MON_PROFIN WITH 0
      REPLACE MON_PROTOT WITH 0
      REPLACE MON_FLGTRA WITH .F.
   ENDIF
   IF !ExecRW(Csql,"U_MON_CA","W")
      return(.f.)
   ENDIF
   SELECT PARA
   SKIP +1
ENDDO

x_soci = "mon_codsoc = '" + PUB_CODSOC + "'"
x_cpdv = "mon_codpdv = '" + ALLTRIM(QQR_CODPDV) + "'"
x_cass = "mon_codcas = '" + ALLTRIM(PUB_CODCAS) + "'"
x_data = "mon_amgini = '" + RIBALTA2(DTOC(DATE())) + "'"
x_ora1 = "mon_oraini = '" + SPACE(08) + "'"
x_cond = x_soci + " and " + x_cpdv + " and " + x_cass + " and " + x_data + " and " + x_ora1
Csql   = "select * from u_mon_ca where " + x_cond
IF !ExecRW(Csql,"U_MON_CA","R")
   return(.f.)
ENDIF
SELECT U_MON_CA
GO TOP
IF EOF()
   APPEND BLANK
ENDIF
REPLACE MON_CODSOC WITH PUB_CODSOC
REPLACE MON_CODPDV WITH QQR_CODPDV
REPLACE MON_DESPDV WITH QQR_DESPDV
REPLACE MON_CODCAS WITH QQR_CODCAS
REPLACE MON_DESCAS WITH QQR_DESCAS
REPLACE MON_TIPCAS WITH QQR_TIPCAS
REPLACE MON_DESTIP WITH QQR_DESTIP
REPLACE MON_AMGINI WITH RIBALTA2(QQR_DATINI)
REPLACE MON_DATINI WITH QQR_DATINI
REPLACE MON_ORAINI WITH QQR_ORAINI
REPLACE MON_PROINI WITH QQR_PROINI
REPLACE MON_AMGFIN WITH SPACE(10)
REPLACE MON_DATFIN WITH SPACE(10)
REPLACE MON_ORAFIN WITH SPACE(08)
REPLACE MON_PROFIN WITH 0
REPLACE MON_PROTOT WITH 0
REPLACE MON_FLGTRA WITH .F.
IF !ExecRW(Csql,"U_MON_CA","W")
   return(.f.)
ENDIF

DO FORM form\ecash linked
