
********************************************************************************************************
PROCEDURE CREA_FATTURA_ELETTRONICA
*
* SINTASSI:
*
* CREA_FATTURA_ELETTRONICA('000001','2014',SYS(5)+SYS(2003)+'\FATTURE_ELETTRONICHE'
*
********************************************************************************************************
PARAMETERS _NUMERO_FATTURA,_ANNO_FATTURA,_DIRECTORY_DI_CREAZIONE
    
LOCAL POSIZIONE_INIZIO_DETTAGLI,POSIZIONE_FINE_DETTAGLI,POSIZIONE_INIZIO_DDT,POSIZIONE_FINE_DDT
LOCAL POSIZIONE_INIZIO_ORDINE,POSIZIONE_FINE_ORDINE,POSIZIONE_INIZIO_RIEPILOGO_IVA,POSIZIONE_FINE_RIEPILOGO_IVA  && ERASMO - 07/11/2018

IF PCOUNT()<3
	MESSAGEBOX("Errore nei parametri della fattura elettonica: manca numero o mese-anno fattura",48,"Errore fattura elettronica")
ENDIF

**=> ERASMO - INIZIO 08/01/2019
_cNumeroFattura = TOGLI_CARATTERI_SPECIALI(ALLTRIM(_NUMERO_FATTURA))
_cNumeroFattura = PADL(_cNumeroFattura,6,'0')
*_NUMERO_FATTURA = _cNumeroFattura
**=> ERASMO - FINE 08/01/2019

IF FILE("fattura_elettronica.xml")	  && Esiste il file? 
ELSE
	MESSAGEBOX("File fattura_elettronica.xml non presente nella directory di AQUARIUS. Il file è necessario per creare le fatture elettroniche.";
		+CHR(13)+"Contattare assistenza",48,"Errore creazione XML fatturazione elettronica")

	DO CHIUDI_CURSORI
	
	RETURN .F.
ENDIF

WAIT WINDOWS "CREAZIONE FILE DI FATTURA ELETTRONICA IN CORSO..." NOWAIT

*SET STEP ON
*DO CREA_CURSOR_DATI_AZIENDA

_YES_CONTINUA = .T.  && ERASMO - 07/11/2018

DO CREA_CURSOR_HEADER_FATTURA_ELETTRONICA

DO CREA_CURSOR_DATI_AZIENDA  && ERASMO - 07/11/2018

DO CREA_CURSOR_BODY_FATTURA_ELETTRONICA

DO CREA_CURSOR_RIFERIMENTI_DDT

DO CREA_CURSOR_RIFERIMENTI_ORDINE  && ERASMO - 07/11/2018

DO CREA_CURSOR_RIEPILOGO_IVA  && ERASMO - 07/11/2018

DO CREA_CURSOR_DETTAGLI_PAGAMENTO  && ERASMO - 14/01/2019

DO CONTROLLI_FORMALI

**=> ERASMO - INIZIO 07/11/2018
IF !_YES_CONTINUA
	DO CHIUDI_CURSORI
	WAIT CLEAR
	RETURN .F.
ENDIF
**=> ERASMO - FINE 07/11/2018

*** crea il file xml: per ora è vuoto e nei passi successivi vengono aggiunti i vari elementi
SELECT CU_AZIENDA
_PIVA=ALLTRIM(AZI_PIVA)
*_FILE_FATTURA_XML = _DIRECTORY_DI_CREAZIONE+"\IT"+_PIVA+"_"+RIGHT(ALLTRIM(_NUMERO_FATTURA),5)+".xml"
DO CASE
	CASE PUB_FEPROGR = 1  && Progressivo alfanumerico per nomenclatura file - Usa Numero fattura ridotto a 5 caratteri
		*_FILE_FATTURA_XML = _DIRECTORY_DI_CREAZIONE+"\IT"+_PIVA+"_"+SUBSTR(ALLTRIM(_NUMERO_FATTURA),1,1)+SUBSTR(ALLTRIM(_NUMERO_FATTURA),3,4)+".xml"
		_FILE_FATTURA_XML = _DIRECTORY_DI_CREAZIONE+"\IT"+_PIVA+"_"+SUBSTR(ALLTRIM(_cNumeroFattura),1,1)+SUBSTR(ALLTRIM(_cNumeroFattura),3,4)+".xml"  && ERASMO - 16/01/2019
		
	CASE PUB_FEPROGR = 2  && Progressivo alfanumerico per nomenclatura file - Usa codice random alfanumerico di 5 caratteri
		_FILE_FATTURA_XML = _DIRECTORY_DI_CREAZIONE+"\IT"+_PIVA+"_"+RIGHT(SYS(2015),5)+".xml"
	
	OTHERWISE
		_FILE_FATTURA_XML = _DIRECTORY_DI_CREAZIONE+"\IT"+_PIVA+"_"+RIGHT(SYS(2015),5)+".xml"
ENDCASE


STRTOFILE("",_FILE_FATTURA_XML ,0)

_FATTURA_ELETTRONICA_COMPLETA=FILETOSTR("fattura_elettronica.xml")

_FATTURA_ELETTRONICA_COMPLETA=SOSTITUISCE_CAMPI_CURSOR_SU_TESTO("CU_AZIENDA",_FATTURA_ELETTRONICA_COMPLETA)

**==> SERGIO 02/11/2018 - INIZIO
_FATTURA_ELETTRONICA_COMPLETA=SOSTITUISCE_CAMPI_CURSOR_SU_TESTO("CU_AZIENDA_PB",_FATTURA_ELETTRONICA_COMPLETA)
**==> SERGIO 02/11/2018 - FINE

**=> ERASMO - INIZIO 07/11/2018
**** ORDINE CLIENTE
POSIZIONE_INIZIO_ORDINE	=ATC("<DatiOrdineAcquisto>",_FATTURA_ELETTRONICA_COMPLETA)
POSIZIONE_FINE_ORDINE	=ATC("</DatiOrdineAcquisto>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DatiOrdineAcquisto>")  

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,1,POSIZIONE_INIZIO_ORDINE-1)
APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)    

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_ORDINE,POSIZIONE_FINE_ORDINE-POSIZIONE_INIZIO_ORDINE)
APPEND_XML_FILE("RIFERIMENTI_ORDINE",_STRING_XML,_FILE_FATTURA_XML )
**=> ERASMO - FINE 07/11/2018

**** DDT
POSIZIONE_INIZIO_DDT	=ATC("<DatiDDT>",_FATTURA_ELETTRONICA_COMPLETA)
POSIZIONE_FINE_DDT		=ATC("</DatiDDT>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DatiDDT>")  

*!*	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,1,POSIZIONE_INIZIO_DDT-1)
*!*	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML )    

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_DDT,POSIZIONE_FINE_DDT-POSIZIONE_INIZIO_DDT)
APPEND_XML_FILE("RIFERIMENTI_DDT",_STRING_XML,_FILE_FATTURA_XML)
**** DDT

POSIZIONE_INIZIO_DETTAGLI	=ATC("<DettaglioLinee>",_FATTURA_ELETTRONICA_COMPLETA)
POSIZIONE_FINE_DETTAGLI		=ATC("</DettaglioLinee>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DettaglioLinee>")

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_DDT+1,POSIZIONE_INIZIO_DETTAGLI-POSIZIONE_FINE_DDT-1)
APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_DETTAGLI,POSIZIONE_FINE_DETTAGLI-POSIZIONE_INIZIO_DETTAGLI)
APPEND_XML_FILE("FatturaElettronica",_STRING_XML,_FILE_FATTURA_XML)

**=> ERASMO - INIZIO 07/11/2018
**** RIEPILOGO IVA
POSIZIONE_INIZIO_RIEPILOGO_IVA	=ATC("<DatiRiepilogo>",_FATTURA_ELETTRONICA_COMPLETA)
POSIZIONE_FINE_RIEPILOGO_IVA	=ATC("</DatiRiepilogo>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DatiRiepilogo>")  

_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_RIEPILOGO_IVA,POSIZIONE_FINE_RIEPILOGO_IVA-POSIZIONE_INIZIO_RIEPILOGO_IVA)
APPEND_XML_FILE("RIEPILOGO_IVA",_STRING_XML,_FILE_FATTURA_XML)
**=> ERASMO - FINE 07/11/2018

*!*	**=> ERASMO - INIZIO 14/01/2019
*!*	POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO	=ATC("<DettaglioPagamento>",_FATTURA_ELETTRONICA_COMPLETA)
*!*	POSIZIONE_FINE_DETTAGLIOPAGAMENTO	=ATC("</DettaglioPagamento>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DettaglioPagamento>")  

*!*	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_RIEPILOGO_IVA,POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO-POSIZIONE_FINE_RIEPILOGO_IVA)
*!*	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)

*!*	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO,POSIZIONE_FINE_DETTAGLIOPAGAMENTO-POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO)
*!*	APPEND_XML_FILE("DETTAGLI_PAGAMENTO",_STRING_XML,_FILE_FATTURA_XML)
*!*	**=> ERASMO - FINE 14/01/2019

*_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_DETTAGLI)
*_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_RIEPILOGO_IVA)  && ERASMO - 07/11/2018
*!*	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_DETTAGLIOPAGAMENTO)  && ERASMO - 14/01/2019
*!*	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)

**=> ERASMO - INIZIO 17/01/2019
SELECT DETTAGLI_PAGAMENTO
GO TOP
IF !EOF()
	POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO	=ATC("<DettaglioPagamento>",_FATTURA_ELETTRONICA_COMPLETA)
	POSIZIONE_FINE_DETTAGLIOPAGAMENTO	=ATC("</DettaglioPagamento>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DettaglioPagamento>")  

	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_RIEPILOGO_IVA,POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO-POSIZIONE_FINE_RIEPILOGO_IVA)
	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)

	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO,POSIZIONE_FINE_DETTAGLIOPAGAMENTO-POSIZIONE_INIZIO_DETTAGLIOPAGAMENTO)
	APPEND_XML_FILE("DETTAGLI_PAGAMENTO",_STRING_XML,_FILE_FATTURA_XML)
	
	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_DETTAGLIOPAGAMENTO)
	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)
ELSE
	POSIZIONE_FINE_DATIBENISERVIZI =ATC("</DatiBeniServizi>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DatiBeniServizi>")
	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_RIEPILOGO_IVA,POSIZIONE_FINE_DATIBENISERVIZI-POSIZIONE_FINE_RIEPILOGO_IVA)
	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)
	
	POSIZIONE_FINE_DATIPAGAMENTO =ATC("</DatiPagamento>",_FATTURA_ELETTRONICA_COMPLETA)+LEN("</DatiPagamento>") 
	_STRING_XML=SUBSTR(_FATTURA_ELETTRONICA_COMPLETA,POSIZIONE_FINE_DATIPAGAMENTO)
	APPEND_XML_FILE("HEADER_FATTURA_ELETTRONICA",_STRING_XML,_FILE_FATTURA_XML)
ENDIF
**=> ERASMO - FINE 17/01/2019

**=> ERASMO - INIZIO 07/11/2018
x_ndoc = "ORD_NUMORD = '" + _NUMERO_FATTURA + "'"
x_ddoc = "ORD_ANNO = '" + _ANNO_FATTURA + "'"
x_cond = x_ndoc + " and " + x_ddoc
cSql   = "UPDATE U_FAT_TT SET ORD_FILEXML = '" + ALLTRIM(_FILE_FATTURA_XML) + "' where " + x_cond
IF !ExecCommand(cSql,'UPD_FAT_TT')
   return(.f.)
ENDIF
**=> ERASMO - FINE 07/11/2018

WAIT WINDOW "CREAZIONE FATTURA ELETTRONICA "+_FILE_FATTURA_XML+" TERMINATA CORRETTAMENTE" TIMEOUT 1

DO CHIUDI_CURSORI  && ERASMO - 07/11/2018

RETURN .T.

* FINE PROCEDURE CREA_FATTURA_ELETTRONICA
***************************************


******************************************************************************
PROCEDURE CHIUDI_CURSORI
******************************************************************************
SELECT CU_AZIENDA 
USE

SELECT FATTURAELETTRONICA
USE

SELECT HEADER_FATTURA_ELETTRONICA
USE

SELECT RIFERIMENTI_DDT
USE

**=> ERASMO - INIZIO 07/11/2018
SELECT CU_AZIENDA_PB 
USE

SELECT RIFERIMENTI_ORDINE
USE

SELECT RIEPILOGO_IVA
USE
**=> ERASMO - FINE 07/11/2018

**=> ERASMO - FINE 14/01/2019
SELECT DETTAGLI_PAGAMENTO
USE
**=> ERASMO - FINE 14/01/2019

RETURN
* FINE PROCEDURE CHIUDI_CURSORI
******************************************************************************


******************************************************************************
PROCEDURE CREA_CURSOR_DATI_AZIENDA
******************************************************************************
*!*	TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

*!*		SELECT * FROM U_AZI_AN

*!*	ENDTEXT					&& FINE SCRITTURA QUERY

**=> ERASMO - INIZIO 08/01/2019
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT AZI_CODFIS,AZI_PIVA,AZI_RAGSOC,AZI_INDIRI,AZI_CAP,AZI_LOCALI,AZI_TELEFO,AZI_FAX,
		CASE WHEN AZI_TELEFO = '' THEN '' ELSE '<Telefono>'+RTRIM(AZI_TELEFO)+'</Telefono>' END AS CEDENTEPRESTATORECONTATTITELEFONO,
		CASE WHEN AZI_FAX = '' THEN '' ELSE '<Fax>'+RTRIM(AZI_FAX)+'</Fax>' END AS CEDENTEPRESTATORECONTATTIFAX
	FROM U_AZI_AN

ENDTEXT					&& FINE SCRITTURA QUERY
**=> ERASMO - FINE 08/01/2019

IF !ExecPreparedCommand(cSql,"CU_AZIENDA")
	return(.F.)
ENDIF

**=> ERASMO - INIZIO 07/11/2018
SELECT CU_AZIENDA
GO TOP
REPLACE AZI_RAGSOC WITH PARSE_STRING_XML(AZI_RAGSOC)
REPLACE AZI_INDIRI WITH PARSE_STRING_XML(AZI_INDIRI)
REPLACE AZI_LOCALI WITH PARSE_STRING_XML(AZI_LOCALI)
**=> ERASMO - FINE 07/11/2018

**==> SERGIO 02/11/2018 - INIZIO
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT AZI_IDPAESE,AZI_PIVAIN,AZI_FORTRA,AZI_CODEORI,AZI_ALBO,AZI_PRVALBO,AZI_NUMISALBO,AZI_DTALBO,AZI_REGIMEFI,
		AZI_NRCIVICO,AZI_PROVINCIA,AZI_NAZION,AZI_UFFICIO,AZI_NRREA,AZI_CAPITSO,AZI_SOCIOU,AZI_STATOL,AZI_EMAIL,AZI_IDPAESEIN,
		AZI_PIVAIN,AZI_RAGSOCIN,AZI_SOGGEMIN,AZI_CONPAG,AZI_MODPAG,AZI_IBAN,AZI_IBANFAT,
		CASE WHEN AZI_CODEORI = '' THEN '' ELSE '<CodEORI>'+RTRIM(AZI_CODEORI)+'</CodEORI>' END AS CEDENTEPRESTATOREDATIANAGRAFICIANAGRAFICACODEORI,
		CASE WHEN AZI_CAPITSO = 0 THEN '' ELSE '<CapitaleSociale>'+CAST(CAST(AZI_CAPITSO AS NUMERIC(16,2)) AS VARCHAR(20))+'</CapitaleSociale>' END AS CEDENTEPRESTATOREISCRIZIONEREACAPITALESOCIALE,
		CASE WHEN AZI_ALBO = '' THEN '' ELSE '<AlboProfessionale>'+RTRIM(AZI_ALBO)+'</AlboProfessionale>' END AS CEDENTEPRESTATOREDATIANAGRAFICIALBOPROFESSIONALE,
		CASE WHEN AZI_PRVALBO = '' THEN '' ELSE '<ProvinciaAlbo>'+RTRIM(AZI_PRVALBO)+'</ProvinciaAlbo>' END AS CEDENTEPRESTATOREDATIANAGRAFICIPROVINCIAALBO,
		CASE WHEN AZI_NUMISALBO = '' THEN '' ELSE '<NumeroIscrizioneAlbo>'+RTRIM(AZI_NUMISALBO)+'</NumeroIscrizioneAlbo>' END AS CEDENTEPRESTATOREDATIANAGRAFICINUMEROISCRIZIONEALBO,
		CASE WHEN AZI_DTALBO = '' THEN '' ELSE '<DataIscrizioneAlbo>'+RTRIM(AZI_DTALBO)+'</DataIscrizioneAlbo>' END AS CEDENTEPRESTATOREDATIANAGRAFICIDATAISCRIZIONEALBO
	FROM U_AZI_PB

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,"CU_AZIENDA_PB")
	return(.F.)
ENDIF
**==> SERGIO 02/11/2018 - FINE

**=> ERASMO - INIZIO 07/11/2018
SELECT CU_AZIENDA_PB
GO TOP
REPLACE AZI_UFFICIO WITH PARSE_STRING_XML(AZI_UFFICIO)
REPLACE AZI_SOGGEMIN WITH PARSE_STRING_XML(AZI_SOGGEMIN)
REPLACE AZI_RAGSOCIN WITH PARSE_STRING_XML(AZI_RAGSOCIN)

_ORD_IDSDI = ""
_ORD_CAUS = ""
_ORD_CODCLI = ""
SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF !EOF()
	_ORD_IDSDI = ALLTRIM(ORD_IDSDI)
	_ORD_CAUS = ALLTRIM(ORD_CAUS)
	_ORD_CODCLI = ALLTRIM(ORD_CODCLI)
ENDIF

*!*	IF LEN(_ORD_IDSDI) <= 6
*!*		SELECT CU_AZIENDA_PB
*!*		GO TOP
*!*		REPLACE AZI_FORTRA WITH "FPA12"
*!*	ENDIF
*!*	IF LEN(_ORD_IDSDI) = 7
*!*		SELECT CU_AZIENDA_PB
*!*		GO TOP
*!*		REPLACE AZI_FORTRA WITH "FPR12"
*!*	ENDIF

_FORMATO_TRASMISSIONE = "FPR12"
IF _ORD_CAUS = "FVS"  && FORZATURA PER CARDIOLINE
	_FORMATO_TRASMISSIONE = "FPA12"
ELSE
	v_seek	= PUB_CODSOC + _ORD_CODCLI
	v_chiave = "cli_codsoc+cli_codcli"
	IF seek_std('u_ana_cl',v_seek,v_chiave,'CL_CLIENTE')
	   SELECT CL_CLIENTE
	   IF CLI_PA
	      _FORMATO_TRASMISSIONE = "FPA12"
	   ENDIF
	ENDIF
ENDIF

IF (EMPTY(_ORD_IDSDI) OR ALLTRIM(_ORD_IDSDI) $ '0000000#XXXXXXX') AND _FORMATO_TRASMISSIONE = "FPA12"
	MESSAGEBOX("Codice Destinatario obbligatorio per la fattura PA n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
	_YES_CONTINUA = .F.
	RETURN .F.
ENDIF

SELECT CU_AZIENDA_PB
GO TOP
REPLACE AZI_FORTRA WITH _FORMATO_TRASMISSIONE

SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF !EOF()
	v_seek 	 = 'CPA'+ALLTRIM(ORD_CPA)
	v_chiave = "codice"
	IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
	   SELECT CUR_PARA
	   _PAGANT = SUBSTR(LIBERA,252,1)
	   _SCADEN = ALLTRIM(SUBSTR(LIBERA,11,239))
	   _RATE = OCCURS(SPACE(1),_SCADEN)
	   SELECT CU_AZIENDA_PB
	   GO TOP
	   IF _RATE > 1
	      REPLACE AZI_CONPAG WITH "TP01"  && pagamento a rate
	   ELSE
	      IF _PAGANT = "S"
	         REPLACE AZI_CONPAG WITH "TP03"  && anticipo
	      ELSE
	         REPLACE AZI_CONPAG WITH "TP02"  && pagamento completo
	      ENDIF
	   ENDIF
	ENDIF
ENDIF
**=> ERASMO - FINE 07/11/2018

DO CERCA_IBAN_FATTURA_CLIENTE  && ERASMO - 07/11/2018

*!*	**=> ERASMO - INIZIO 14/01/2019
*!*	SELECT CU_AZIENDA_PB
*!*	IF EMPTY(AZI_IBAN) OR LEN(ALLTRIM(AZI_IBAN)) <> 27
*!*		MESSAGEBOX("Codice IBAN vuoto o non corretto per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
*!*		_YES_CONTINUA = .F.
*!*		RETURN .F.
*!*	ENDIF
*!*	**=> ERASMO - FINE 14/01/2019

DO CERCA_MODALITA_PAGAMENTO_FATTURA_CLIENTE  && ERASMO - 07/11/2018

RETURN
* FINE PROCEDURE CREA_CURSOR_DATI_AZIENDA
******************************************************************************



******************************************************************************
PROCEDURE CREA_CURSOR_HEADER_FATTURA_ELETTRONICA
******************************************************************************
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT 
		CAST((ROW_NUMBER() OVER (ORDER BY TT.ORD_NUMORD)) AS NUMERIC(4,0)) AS NR_RIGA,  -- ERASMO - 14/01/2019
		TT.TAGGANCIO,  -- ERASMO - 14/12/2018
		TT.ORD_VALORE,
		TT.ORD_VALORE+ROUND(TT.I_OMAGGIO,2)+ROUND(TT.T_OMAGGIO,2) AS IMPORTOTOTALEDOCUMENTO,  -- ERASMO - 18/01/2019
		CASE --ORD_CAUS
			--WHEN 'FVS' THEN
			--	CASE
			--		WHEN (SELECT COUNT(*) FROM U_FAT_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' AND ORD_IVA = 'SP') > 0 THEN 'S'
			--		ELSE 'D'
			--	END
			--ELSE 'I'
			WHEN (SELECT COUNT(*) FROM U_FAT_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' AND ORD_IVA IN 
				(SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'IVA%' AND NOIVACARCLI = 'S')) > 0 THEN 'S'  -- ERASMO - 07/11/2018
			ELSE 'I'  -- ERASMO - 07/11/2018
		END AS ESIGIBILITA_IVA,
		CASE
			--WHEN (SELECT COUNT(*) FROM U_FAT_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' AND ORD_IVA = 'SP') > 0 THEN ORD_IMPONIB
			WHEN (SELECT COUNT(*) FROM U_FAT_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' AND ORD_IVA IN 
				(SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'IVA%' AND NOIVACARCLI = 'S')) > 0 THEN ORD_IMPONIB  -- ERASMO - 07/11/2018
			ELSE ORD_VALORE
		END AS IMPORTO_PAGAMENTO,
		--TT.ORD_VALORE/1.22 AS ORD_IMPONIB,
		ORD_IMPONIB,
		--ROUND(TT.ORD_VALORE*(1-1/1.22),2) AS ORD_IMPOSTA,
		ORD_IMPOSTA,
		--TT.ORD_INDIRI,
		SUBSTRING(TT.ORD_INDIRI,1,60) AS ORD_INDIRI,  -- ERASMO - 21/01/2019
		--TT.ORD_CAP,
		--SUBSTRING(TT.ORD_CAP,1,5) AS ORD_CAP,  -- ERASMO - 10/01/2019
		CASE 
			WHEN SUBSTRING(TT.ORD_CODNAZ,1,2) <> 'IT' AND (TT.ORD_CAP = '' OR ISNUMERIC(TT.ORD_CAP) = 0) THEN '99999'
			ELSE SUBSTRING(TT.ORD_CAP,1,5)
		END AS ORD_CAP,  -- ERASMO - 24/01/2019
		--TT.ORD_LOCALI,
		SUBSTRING(TT.ORD_LOCALI,1,60) AS ORD_LOCALI,  -- ERASMO - 21/01/2019
		TT.ORD_PROVIN,
		--TT.ORD_VARIE,
		--TT.ORD_CIG AS CodiceCIG,
		--CASE WHEN TT.ORD_CIG<>'' THEN '<CodiceCIG>'+RTRIM(TT.ORD_CIG)+'</CodiceCIG>' ELSE '' END AS CodiceCIG,  -- ERASMO/FABIANO - 05/07/2016
		--TT.ORD_CUP AS CodiceCUP,
		--CASE WHEN TT.ORD_CUP<>'' THEN '<CodiceCUP>'+RTRIM(TT.ORD_CUP)+'</CodiceCUP>' ELSE '' END AS CodiceCUP,  -- ERASMO/FABIANO - 11/08/2015
		CASE WHEN (SELECT COALESCE(SUBSTRING(LIBERA,11,1),'') FROM PARA WHERE CODICE = 'TOP'+TT.ORD_CAUS) = 'S' THEN 'TD04' ELSE 'TD01' END AS TIPODOCUMENTO,  -- ERASMO - 22/09/2015
		SUBSTRING(TT.ORD_DATORD,1,4)+'-'+SUBSTRING(TT.ORD_DATORD,6,2)+'-'+SUBSTRING(TT.ORD_DATORD,9,2) AS DatiGeneraliDocumentoData,
		TT.ORD_NUMORD AS DatiGeneraliDocumentoNumero,
		--SUBSTRING(TT.ORD_DATORC,1,4)+'-'+SUBSTRING(TT.ORD_DATORC,6,2)+'-'+SUBSTRING(TT.ORD_DATORC,9,2) AS DatiOrdineAcquistoData,
		--TT.ord_numorc AS DatiOrdineAcquistoIdDocumento,
		TT.ORD_VALUTA ,
		TT.ORD_PARIVA ,
		--TT.ORD_RAGSOC ,
		SUBSTRING(TT.ORD_RAGSOC,1,80) AS ORD_RAGSOC,  -- ERASMO - 21/01/2019
		--CASE RTRIM(TT.ORD_IDSDI) WHEN '' THEN (CASE RTRIM(TT.ORD_VARIE) WHEN '' THEN (CASE SUBSTRING(TT.ORD_CODNAZ,1,2) WHEN 'IT' THEN '0000000' ELSE 'XXXXXXX' END) 
		--	ELSE RTRIM(TT.ORD_VARIE) END) ELSE RTRIM(TT.ORD_IDSDI) END AS ORD_IDSDI ,  -- ERASMO - 07/11/2018
		CASE RTRIM(TT.ORD_IDSDI)
			WHEN '' THEN (
				CASE SUBSTRING(TT.ORD_CODNAZ,1,2)
					WHEN 'IT' THEN '0000000' 
					ELSE 'XXXXXXX' 
				END) 
			ELSE RTRIM(TT.ORD_IDSDI)
		END AS ORD_IDSDI ,  -- ERASMO - 21/01/2019
		CASE RTRIM(TT.ORD_EPEC) WHEN '' THEN '' ELSE ('<PECDestinatario>'+RTRIM(TT.ORD_EPEC)+'</PECDestinatario>') END AS ORD_EPEC ,  -- ERASMO - 07/11/2018	      
		TT.ORD_BANCA ,  -- ERASMO - 07/11/2018
		TT.ORD_CODCLI , -- ERASMO - 07/11/2018
		TT.ORD_CPA ,    -- ERASMO - 07/11/2018
		TT.ORD_CAUS ,   -- ERASMO - 07/11/2018
		TT.ORD_NUMORD ,   -- ERASMO - 15/01/2019
		TT.ORD_DATORD ,   -- ERASMO - 15/01/2019
		TT.ORD_NUMORD ,   -- ERASMO - 15/01/2019
		CASE SUBSTRING(TT.ORD_CODNAZ,1,2) WHEN 'IT' THEN 'IT' ELSE (SELECT RTRIM(LIBERA) FROM PARA WHERE CODICE = 'STA'+TT.ORD_CODNAZ) END AS ORD_IDPAESE,  -- ERASMO - 07/11/2018
		TT.ORD_VALUTA,   -- ERASMO - 07/11/2018
		CAST('' AS TEXT) AS ALLEGATI,  -- ERASMO - 28/11/2018
		CASE RTRIM(TT.ORD_PROVIN) WHEN '' THEN '' ELSE ('<Provincia>'+RTRIM(TT.ORD_PROVIN)+'</Provincia>') END AS CESSIONARIOCOMMITTENTESEDEPROVINCIA,  -- ERASMO - 08/01/2019
		CASE SUBSTRING(TT.ORD_CODNAZ,1,2)
			WHEN 'IT' THEN 
				CASE
					WHEN RTRIM(TT.ORD_PARIVA) = RTRIM((SELECT CLI_PARIVA FROM U_CLI_AN WHERE CLI_CODCLI = TT.ORD_CODCLI)) THEN '<IdFiscaleIVA><IdPaese>IT</IdPaese><IdCodice>'+RTRIM(TT.ORD_PARIVA)+'</IdCodice></IdFiscaleIVA>'	-- ERASMO - 16/01/2019
					WHEN RTRIM(TT.ORD_PARIVA) = RTRIM((SELECT CLI_CODFIS FROM U_CLI_AN WHERE CLI_CODCLI = TT.ORD_CODCLI)) THEN '<CodiceFiscale>'+RTRIM(TT.ORD_PARIVA)+'</CodiceFiscale>'											-- ERASMO - 16/01/2019
					ELSE '<IdFiscaleIVA><IdPaese>IT</IdPaese><IdCodice>'+RTRIM(TT.ORD_PARIVA)+'</IdCodice></IdFiscaleIVA>'																											-- ERASMO - 16/01/2019
				END																																																					-- ERASMO - 16/01/2019
				ELSE '<IdFiscaleIVA><IdPaese>'+(SELECT RTRIM(LIBERA) FROM PARA WHERE CODICE = 'STA'+TT.ORD_CODNAZ)+'</IdPaese><IdCodice>'+RTRIM(TT.ORD_PARIVA)+'</IdCodice></IdFiscaleIVA>'											-- ERASMO - 16/01/2019
		END AS CESSIONARIOCOMMITTENTEDATIANAGRAFICIIDFISCALEIVA	
	FROM U_FAT_TT AS TT
	WHERE TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'
	
ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,"HEADER_FATTURA_ELETTRONICA")
	return(.F.)
ENDIF

**=> ERASMO - INIZIO 07/11/2018
SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
*SCAN
	
	IF (!EMPTY(ORD_IDSDI) AND !EMPTY(ORD_EPEC) AND ALLTRIM(ORD_IDSDI) <> '0000000' AND ALLTRIM(ORD_IDSDI) <> 'XXXXXXX')
		REPLACE ORD_EPEC WITH ''
	ENDIF
	
	REPLACE ORD_INDIRI WITH PARSE_STRING_XML(ORD_INDIRI)
	REPLACE ORD_LOCALI WITH PARSE_STRING_XML(ORD_LOCALI)
	REPLACE ORD_RAGSOC WITH PARSE_STRING_XML(ORD_RAGSOC)
	IF (EMPTY(ORD_IDSDI) AND EMPTY(ORD_EPEC))
		MESSAGEBOX("Inserire il Codice Destinatario o l'e-mail PEC per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	IF EMPTY(ORD_IDPAESE)
		MESSAGEBOX("Inserire il Codice Nazione per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	IF EMPTY(ORD_RAGSOC)
		MESSAGEBOX("Inserire la Ragione Sociale per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	IF EMPTY(ORD_INDIRI)
		MESSAGEBOX("Inserire l'Indirizzo per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	IF EMPTY(ORD_CAP)
		MESSAGEBOX("Inserire il CAP per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	IF EMPTY(ORD_LOCALI)
		MESSAGEBOX("Inserire la Località per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
*!*		IF EMPTY(ORD_PROVIN)
*!*			MESSAGEBOX("Inserire la Provincia per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,16,"Attenzione")
*!*			_YES_CONTINUA = .F.
*!*			RETURN .F.
*!*		ENDIF
*ENDSCAN
GO TOP
**=> ERASMO - FINE 07/11/2018

**=> ERASMO - INIZIO 28/11/2018
SELECT CX_FILES_PDF_GENERATI
SET FILTER TO NUMORD = _NUMERO_FATTURA AND SUBSTR(DATORD,1,4) = _ANNO_FATTURA
GO TOP
IF !EOF()
*!*		IF FILE(ALLTRIM(ALLEGATO))  && ERASMO - 14/12/2018
*!*			_NOME_ALLEGATO = JUSTFNAME(ALLTRIM(ALLEGATO))
*!*			_FILE_ALLEGATO_STR_BASE64BINARY = STRCONV(FILETOSTR(ALLTRIM(ALLEGATO)),13)
*!*			SELECT HEADER_FATTURA_ELETTRONICA
*!*			GO TOP
*!*			REPLACE ALLEGATI WITH "<Allegati>"+CHR(10)+SPACE(12)+"<NomeAttachment>"+_NOME_ALLEGATO+"</NomeAttachment>"+CHR(10)+SPACE(12)+"<Attachment>"+_FILE_ALLEGATO_STR_BASE64BINARY+"</Attachment>"+CHR(10)+SPACE(8)+"</Allegati>"
*!*		ELSE
*!*			MESSAGEBOX("L'allegato PDF non verrà integrato per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,48,"Attenzione")
*!*		ENDIF
	
	**=> ERASMO - INIZIO 08/01/2019
	IF !EMPTY(ALLTRIM(ALLEGATO))
		_attach = ALLTRIM(ALLEGATO)
		_nr_allegati = OCCURS(";",_attach) + 1
		FOR I = 1 TO _nr_allegati
			_allegato_iesimo = ALLTRIM(STR_EXTRACT(_attach,";",I))
			IF FILE(_allegato_iesimo)
				_NOME_ALLEGATO = JUSTFNAME(ALLTRIM(_allegato_iesimo))
				_FILE_ALLEGATO_STR_BASE64BINARY = STRCONV(FILETOSTR(ALLTRIM(_allegato_iesimo)),13)
				SELECT HEADER_FATTURA_ELETTRONICA
				GO TOP
				REPLACE ALLEGATI WITH ALLTRIM(ALLEGATI) + IIF(!EMPTY(ALLEGATI), CHR(10)+SPACE(8), "") + ;
					"<Allegati>"+CHR(10)+SPACE(12)+"<NomeAttachment>"+_NOME_ALLEGATO+"</NomeAttachment>"+CHR(10)+SPACE(12)+"<Attachment>"+_FILE_ALLEGATO_STR_BASE64BINARY+"</Attachment>"+CHR(10)+SPACE(8)+"</Allegati>"
			ELSE
				MESSAGEBOX("L'allegato PDF " + JUSTFNAME(ALLTRIM(_allegato_iesimo)) + " non verrà integrato per la fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA,48,"Attenzione")
			ENDIF
		ENDFOR
	ENDIF
	**=> ERASMO - FINE 08/01/2019
	
ENDIF
SELECT CX_FILES_PDF_GENERATI
SET FILTER TO
GO TOP
**=> ERASMO - FINE 28/11/2018

**=> ERASMO - INIZIO 14/12/2018
SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
_ATCH_iddocumento = TAGGANCIO
_ATCH_tipo = 'FAT'
_V_PARA_PATH = ""
_V_PATH_DESTIN = ""
x_codi = "codice = 'ALL" + _ATCH_tipo + "'"
x_cond = x_codi
cSql   = "select * from para where " + x_cond
IF !ExecCommand(cSql,"TMP_PARA")
	return(.f.)
ENDIF
SELECT TMP_PARA
IF !EOF()
	_V_PARA_PATH = ALLTRIM(LIBERA)
	DO CASE
		CASE SUBSTR(_V_PARA_PATH,1,2) = "\\"	&& PERCORSO SU SERVER DIVERSO
			_V_PATH_DESTIN = _V_PARA_PATH

		CASE !EMPTY(JUSTDRIVE(_V_PARA_PATH))	&& PERCORSO FISSO
			_V_PATH_DESTIN = _V_PARA_PATH
		
		OTHERWISE								&& PERCORSO RELATIVO RISPETTO ALLA DIRECTORY DI LAVORO DI AQUARIUS (CARTELLA SUPERIORE)
			_cWorkDir = SYS(5) + SYS(2003)
			_V_PATH_DESTIN = SUBSTR(_cWorkDir,1,RAT('\',_cWorkDir,1)-1) + _V_PARA_PATH
	ENDCASE
		
	x_tipo = "TIPO = '" + _ATCH_tipo + "'"
	x_codi = "IDDOCUMENTO = '" + _ATCH_iddocumento + "'"
	x_cond = x_tipo + " and " + x_codi
	cSql = "select * from ATTACHMENTS where " + x_cond + " order by SEQUEN"
	IF !ExecCommand(cSql,"CX_ATTACHMENTS")
	  return(.f.)
	ENDIF
	SELECT CX_ATTACHMENTS
	GO TOP
	SCAN
		_FULLPATH = _V_PATH_DESTIN + "\" + ALLTRIM(FILENAME)
		
		IF FILE(ALLTRIM(_FULLPATH))
			_NOME_ALLEGATO = JUSTFNAME(ALLTRIM(_FULLPATH))
			_FILE_ALLEGATO_STR_BASE64BINARY = STRCONV(FILETOSTR(ALLTRIM(_FULLPATH)),13)
			SELECT HEADER_FATTURA_ELETTRONICA
			GO TOP
			REPLACE ALLEGATI WITH IIF(!EMPTY(ALLEGATI),RTRIM(ALLEGATI)+CHR(10)+SPACE(8),"")+"<Allegati>"+CHR(10)+SPACE(12)+"<NomeAttachment>"+_NOME_ALLEGATO+"</NomeAttachment>"+CHR(10)+SPACE(12)+;
				"<Attachment>"+_FILE_ALLEGATO_STR_BASE64BINARY+"</Attachment>"+CHR(10)+SPACE(8)+"</Allegati>"
		ENDIF
		
	ENDSCAN
ENDIF
**=> ERASMO - FINE 14/12/2018

RETURN
* FINE PROCEDURE CREA_CURSOR_HEADER_FATTURA_ELETTRONICA
******************************************************************************


******************************************************************************
PROCEDURE CREA_CURSOR_BODY_FATTURA_ELETTRONICA
******************************************************************************
_COND_COMMENTI = IIF(PUB_FECOMM,""," AND DD.ORD_QTAORD>0")  && ERASMO - 22/01/2019
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT 
		CAST((ROW_NUMBER() OVER (ORDER BY DD.ORD_SEQUEN)) AS NUMERIC(4,0)) AS NR_RIGA,  -- ERASMO - 14/01/2019
		DD.ORD_QTAORD,
		--CASE WHEN COALESCE(PR.ART_SERIE,'') <> '' THEN ART_SERIE ELSE 'ART' END AS CODICE_TIPO,
		--CASE WHEN COALESCE(PR.ART_CATBEN,'') <> '' THEN ART_CATBEN ELSE DD.ORD_CODART END AS CODICE_VALORE,
		CASE WHEN ((SELECT AZI_PRDISP FROM U_AZI_PA) = 1) AND COALESCE(PR.ART_SERIE,'') <> '' THEN ART_SERIE ELSE 'ART' END AS CODICE_TIPO,
		--CASE WHEN ((SELECT AZI_PRDISP FROM U_AZI_PA) = 1) AND COALESCE(PR.ART_CATBEN,'') <> '' THEN ART_CATBEN ELSE DD.ORD_CODART END AS CODICE_VALORE,
		CASE WHEN (DD.ORD_CODART='' AND DD.ORD_DESART='*** COMMENTO ***') THEN '*** COMMENTO ***' 
			WHEN ((SELECT AZI_PRDISP FROM U_AZI_PA) = 1) AND COALESCE(PR.ART_CATBEN,'') <> '' THEN ART_CATBEN ELSE DD.ORD_CODART END AS CODICE_VALORE,  -- ERASMO - 22/01/2019
		DD.ORD_CODART,
		--DD.ORD_DESART,
		--CASE DD.ORD_DESART WHEN '' THEN '-' ELSE DD.ORD_DESART END AS ORD_DESART,  -- ERASMO - 09/01/2019
		CASE DD.ORD_DESART WHEN '' THEN '-' WHEN '*** COMMENTO ***' THEN SUBSTRING(ORD_NOTE,1,1000) ELSE DD.ORD_DESART END AS ORD_DESART,  -- ERASMO - 22/01/2019
		DD.ORD_PREZZO,
		--DD.ORD_SC1,
		DD.ORD_PREZZO - DD.ORD_PRZNET AS IMPORTO_SCONTO,
		--(DD.ORD_PREZZO - DD.ORD_PRZNET) * DD.ORD_QTAORD AS IMPORTO_SCONTO,
		DD.ORD_SC1,  -- ERASMO - 15/01/2019
		DD.ORD_SC2,  -- ERASMO - 15/01/2019
		DD.ORD_SC3,  -- ERASMO - 15/01/2019
		DD.ORD_SC4,  -- ERASMO - 15/01/2019
		DD.ORD_SC5,  -- ERASMO - 15/01/2019
		CAST('' AS TEXT) AS DETTAGLIOLINEESCONTOMAGGIORAZIONE,
		DD.ORD_PRZNET,
		DD.ORD_VALORE,
		--CAST(SUBSTRING(IVA.LIBERA,1,3) AS NUMERIC(6,2)) AS DettaglioLineeAliquotaIVA,
		CASE WHEN DD.ORD_DESART = '*** COMMENTO ***' THEN (SELECT COALESCE(CAST(SUBSTRING(LIBERA,1,3) AS NUMERIC(6,2)),0.00) FROM PARA 
															WHERE CODICE = 'IVA'+(SELECT TOP 1 ORD_IVA FROM U_FAT_DD WHERE DAGGANCIO = DD.DAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' ORDER BY DAGGANCIO,ORD_SEQUEN))
			ELSE COALESCE(CAST(SUBSTRING(IVA.LIBERA,1,3) AS NUMERIC(6,2)),0.00) 
		END AS DettaglioLineeAliquotaIVA,  -- ERASMO - 22/01/2019
		--CASE WHEN CAST(SUBSTRING(IVA.LIBERA,1,3) AS NUMERIC (3,0)) = 0 THEN '<Natura>'+RTRIM(SUBSTRING(IVA.LIBERA,145,2))+'</Natura>' ELSE '' END AS DETTAGLIOLINEENATURAIVA,
		CASE WHEN DD.ORD_DESART = '*** COMMENTO ***' THEN 
				CASE WHEN (SELECT RTRIM(SUBSTRING(LIBERA,145,2)) FROM PARA WHERE CODICE = 'IVA'+(SELECT TOP 1 ORD_IVA FROM U_FAT_DD WHERE DAGGANCIO = DD.DAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' ORDER BY DAGGANCIO,ORD_SEQUEN)) = '' THEN '' 
					ELSE '<Natura>'+(SELECT RTRIM(SUBSTRING(LIBERA,145,2)) FROM PARA WHERE CODICE = 'IVA'+(SELECT TOP 1 ORD_IVA FROM U_FAT_DD WHERE DAGGANCIO = DD.DAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' ORDER BY DAGGANCIO,ORD_SEQUEN)) +'</Natura>'
				END
			WHEN CAST(SUBSTRING(IVA.LIBERA,1,3) AS NUMERIC (3,0)) = 0 THEN '<Natura>'+RTRIM(SUBSTRING(IVA.LIBERA,145,2))+'</Natura>' ELSE '' 
		END AS DETTAGLIOLINEENATURAIVA,  -- ERASMO - 22/01/2019
		CASE
			WHEN DD.ORD_SYSFAT <> '' AND COALESCE((SELECT TOP 1 ORD_RIFAMMFE FROM BUDGET_CONS WHERE ORD_SYSFAT = DD.ORD_SYSFAT),'') <> ''
				THEN '<RiferimentoAmministrazione>'+RTRIM(COALESCE((SELECT TOP 1 ORD_RIFAMMFE FROM BUDGET_CONS WHERE ORD_SYSFAT = DD.ORD_SYSFAT),''))+'</RiferimentoAmministrazione>'
			WHEN TT.ORD_RIFAMMFE <> '' THEN '<RiferimentoAmministrazione>'+RTRIM(ORD_RIFAMMFE)+'</RiferimentoAmministrazione>'
			ELSE ''
		END AS DETTAGLIOLINEERIFERIMENTOAMMINISTRAZIONE,
		SPACE(254) AS DETTAGLIOLINEETIPOCESSIONEPRESTAZIONE
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON DD.DAGGANCIO=TT.TAGGANCIO
	LEFT OUTER JOIN PARA AS IVA
	ON 'IVA'+DD.ORD_IVA = IVA.CODICE
	LEFT OUTER JOIN U_ART_PR AS PR
	ON DD.ORD_CODART = PR.ART_CODPRI
	--WHERE DD.ORD_QTAORD>0 AND TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'
	WHERE TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'  <<_COND_COMMENTI>>  -- ERASMO - 22/01/2019
	ORDER BY DD.ORD_SEQUEN

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,"FatturaElettronica")
	return(.F.)
ENDIF

**=> ERASMO/FABIANO - INIZIO 05/07/2016
SELECT FatturaElettronica
GO TOP
SCAN
	_ORD_DESART = ALLTRIM(ORD_DESART)
	_ORD_DESART = PARSE_STRING_XML(_ORD_DESART)
	REPLACE ORD_DESART WITH _ORD_DESART
ENDSCAN
GO TOP
**=> ERASMO/FABIANO - FINE 05/07/2016

**=> ERASMO - INIZIO 15/01/2019
SELECT FatturaElettronica
GO TOP
SCAN
	_STRINGA_SCONTO = ""
	IF IMPORTO_SCONTO > 0
		IF (IMPORTO_SCONTO*100)-FLOOR(IMPORTO_SCONTO*100) <> 0  && SE LO SCONTO HA PIU' DI 2 DECIMALI ALLORA INSERISCO LE PERCENTUALI DI SCONTO
			IF ORD_SC1 > 0
				_STRINGA_SCONTO = ALLTRIM(_STRINGA_SCONTO) + "<ScontoMaggiorazione><Tipo>SC</Tipo><Percentuale>" + STRTRAN(ALLTRIM(STR(ORD_SC1,6,2)),',','.') + "</Percentuale></ScontoMaggiorazione>"
			ENDIF
			IF ORD_SC2 > 0
				_STRINGA_SCONTO = ALLTRIM(_STRINGA_SCONTO) + "<ScontoMaggiorazione><Tipo>SC</Tipo><Percentuale>" + STRTRAN(ALLTRIM(STR(ORD_SC2,6,2)),',','.') + "</Percentuale></ScontoMaggiorazione>"
			ENDIF
			IF ORD_SC3 > 0
				_STRINGA_SCONTO = ALLTRIM(_STRINGA_SCONTO) + "<ScontoMaggiorazione><Tipo>SC</Tipo><Percentuale>" + STRTRAN(ALLTRIM(STR(ORD_SC3,6,2)),',','.') + "</Percentuale></ScontoMaggiorazione>"
			ENDIF
			IF ORD_SC4 > 0
				_STRINGA_SCONTO = ALLTRIM(_STRINGA_SCONTO) + "<ScontoMaggiorazione><Tipo>SC</Tipo><Percentuale>" + STRTRAN(ALLTRIM(STR(ORD_SC4,6,2)),',','.') + "</Percentuale></ScontoMaggiorazione>"
			ENDIF
			IF ORD_SC5 > 0
				_STRINGA_SCONTO = ALLTRIM(_STRINGA_SCONTO) + "<ScontoMaggiorazione><Tipo>SC</Tipo><Percentuale>" + STRTRAN(ALLTRIM(STR(ORD_SC5,6,2)),',','.') + "</Percentuale></ScontoMaggiorazione>"
			ENDIF
		ELSE
			_STRINGA_SCONTO = "<ScontoMaggiorazione><Tipo>SC</Tipo><Importo>" + STRTRAN(ALLTRIM(STR(IMPORTO_SCONTO,15,2)),',','.') + "</Importo></ScontoMaggiorazione>"
		ENDIF
	ENDIF
	REPLACE DETTAGLIOLINEESCONTOMAGGIORAZIONE WITH _STRINGA_SCONTO
ENDSCAN
GO TOP
**=> ERASMO - FINE 15/01/2019

RETURN
* FINE PROCEDURE CREA_CURSOR_BODY_FATTURA_ELETTRONICA
******************************************************************************


******************************************************************************
PROCEDURE CREA_CURSOR_RIFERIMENTI_DDT
******************************************************************************
_COND_COMMENTI = IIF(PUB_FECOMM,""," AND DD.ORD_QTAORD>0")  && ERASMO - 22/01/2019
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT 
		CAST((ROW_NUMBER() OVER (ORDER BY DD.ORD_SEQUEN)) AS NUMERIC(4,0)) AS NR_RIGA,  -- ERASMO - 14/01/2019
		DD.ORS_NUMDDT AS DATIDDTNUMERODDT,
		SUBSTRING(DD.ORS_DATDDT,1,4)+'-'+SUBSTRING(DD.ORS_DATDDT,6,2)+'-'+SUBSTRING(DD.ORS_DATDDT,9,2) AS DATIDDTDATA,
		DD.ORD_DESART  -- ERASMO - 22/01/2019
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON DD.DAGGANCIO=TT.TAGGANCIO
	--WHERE DD.ORD_QTAORD>0 AND DD.ORS_NUMDDT<>'' AND TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'
	--WHERE DD.ORD_QTAORD>0 AND TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'  -- ERASMO - 14/01/2019
	WHERE TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'  <<_COND_COMMENTI>>  -- ERASMO - 22/01/2019
	ORDER BY DD.ORD_SEQUEN

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,"RIFERIMENTI_DDT")
	return(.F.)
ENDIF

**=> ERASMO - INIZIO 14/01/2019
SELECT RIFERIMENTI_DDT
DELETE FOR EMPTY(DATIDDTNUMERODDT)
DELETE FOR ORD_DESART = '*** COMMENTO ***'  && ERASMO - 22/01/2019
GO TOP
**=> ERASMO - FINE 14/01/2019

RETURN
* FINE PROCEDURE CREA_CURSOR_RIFERIMENTI_DDT
******************************************************************************


**=> ERASMO - INIZIO 07/11/2018
******************************************************************************
PROCEDURE CREA_CURSOR_RIFERIMENTI_ORDINE
******************************************************************************
_COND_COMMENTI = IIF(PUB_FECOMM,""," AND DD.ORD_QTAORD>0")  && ERASMO - 22/01/2019
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT 
		CAST((ROW_NUMBER() OVER (ORDER BY DD.ORD_SEQUEN)) AS NUMERIC(4,0)) AS NR_RIGA,  -- ERASMO - 14/01/2019
		TT.ORD_NUMORC AS DATIORDINEACQUISTOIDDOCUMENTO,
		REPLACE(TT.ORD_DATORC,'/','-') AS DATIORDINEACQUISTODATA,
		DD.ORS_NUMORC AS DATIORDINEACQUISTOIDDOCUMENTO_DD,
		REPLACE(DD.ORS_DATORC,'/','-') AS DATIORDINEACQUISTODATA_DD,
		CASE WHEN TT.ORD_CIG<>'' THEN '<CodiceCIG>'+RTRIM(TT.ORD_CIG)+'</CodiceCIG>' ELSE '' END AS CodiceCIG,
		CASE WHEN TT.ORD_CUP<>'' THEN '<CodiceCUP>'+RTRIM(TT.ORD_CUP)+'</CodiceCUP>' ELSE '' END AS CodiceCUP,
		DD.ORD_SYSFAT AS ORD_SYSFAT,
		DD.ORD_DESART  -- ERASMO - 22/01/2019
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON DD.DAGGANCIO=TT.TAGGANCIO
	--WHERE DD.ORD_QTAORD>0 AND TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'
	WHERE TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'  <<_COND_COMMENTI>>  -- ERASMO - 22/01/2019
	ORDER BY DD.ORD_SEQUEN

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,"RIFERIMENTI_ORDINE")
	return(.F.)
ENDIF

SELECT RIFERIMENTI_ORDINE
DELETE FOR ORD_DESART = '*** COMMENTO ***'  && ERASMO - 22/01/2019
GO TOP
SCAN
	_NUMORD = DATIORDINEACQUISTOIDDOCUMENTO_DD
	_DATORD = STRTRAN(DATIORDINEACQUISTODATA_DD,"-","/")
	_SYSFAT = ORD_SYSFAT
	TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY
		SELECT 
			ORD_NUMORC,
			REPLACE(ORD_DATORC,'/','-') AS ORD_DATORC,
			CASE WHEN ORD_CIG<>'' THEN '<CodiceCIG>'+RTRIM(ORD_CIG)+'</CodiceCIG>' ELSE '' END AS ORD_CIG,
			CASE WHEN ORD_CUP<>'' THEN '<CodiceCUP>'+RTRIM(ORD_CUP)+'</CodiceCUP>' ELSE '' END AS ORD_CUP
		FROM U_ORD_TT
		WHERE ORD_NUMORD='<<_NUMORD>>' AND ORD_DATORD='<<_DATORD>>'
	ENDTEXT					&& FINE SCRITTURA QUERY
	IF !ExecPreparedCommand(cSql,"TMP_ORD_TT")
		return(.F.)
	ENDIF
	SELECT TMP_ORD_TT
	GO TOP
	IF !EOF()
		SELECT TMP_ORD_TT
		IF !EMPTY(ORD_NUMORC) AND !EMPTY(ORD_DATORC)
			_NUMORC = ORD_NUMORC
			_DATORC = ORD_DATORC
			SELECT RIFERIMENTI_ORDINE
			REPLACE DATIORDINEACQUISTOIDDOCUMENTO WITH _NUMORC 
			REPLACE DATIORDINEACQUISTODATA WITH _DATORC 
		ENDIF
		SELECT TMP_ORD_TT
		IF !EMPTY(ORD_CIG)
			_CIG = ORD_CIG
			SELECT RIFERIMENTI_ORDINE
			REPLACE CodiceCIG WITH _CIG
		ENDIF
		SELECT TMP_ORD_TT
		IF !EMPTY(ORD_CUP)
			_CUP = ORD_CUP
			SELECT RIFERIMENTI_ORDINE
			REPLACE CodiceCUP WITH _CUP
		ENDIF
	ELSE
		IF !EMPTY(_SYSFAT)
			TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY
				SELECT 
					ORD_NUMORC,
					CASE
						WHEN SUBSTRING(ORD_DATORC,3,1) = '/' AND SUBSTRING(ORD_DATORC,6,1) = '/' THEN REPLACE(DBO.RIBALTA2(ORD_DATORC),'/','-')
						ELSE REPLACE(ORD_DATORC,'/','-')
					END AS ORD_DATORC,
					CASE WHEN ORD_CIG<>'' THEN '<CodiceCIG>'+RTRIM(ORD_CIG)+'</CodiceCIG>' ELSE '' END AS ORD_CIG,
					CASE WHEN ORD_CUP<>'' THEN '<CodiceCUP>'+RTRIM(ORD_CUP)+'</CodiceCUP>' ELSE '' END AS ORD_CUP
				FROM BUDGET_CONS
				WHERE ORD_SYSFAT='<<_SYSFAT>>'
			ENDTEXT					&& FINE SCRITTURA QUERY
			IF !ExecPreparedCommand(cSql,"TMP_BUDGET_CONS")
				return(.F.)
			ENDIF
			SELECT TMP_BUDGET_CONS
			GO TOP
			IF !EOF()
				SELECT TMP_BUDGET_CONS
				IF !EMPTY(ORD_NUMORC) AND !EMPTY(ORD_DATORC)
					_NUMORC = ORD_NUMORC
					_DATORC = ORD_DATORC
					SELECT RIFERIMENTI_ORDINE
					REPLACE DATIORDINEACQUISTOIDDOCUMENTO WITH _NUMORC 
					REPLACE DATIORDINEACQUISTODATA WITH _DATORC 
				ENDIF
				SELECT TMP_BUDGET_CONS
				IF !EMPTY(ORD_CIG)
					_CIG = ORD_CIG
					SELECT RIFERIMENTI_ORDINE
					REPLACE CodiceCIG WITH _CIG
				ENDIF
				SELECT TMP_BUDGET_CONS
				IF !EMPTY(ORD_CUP)
					_CUP = ORD_CUP
					SELECT RIFERIMENTI_ORDINE
					REPLACE CodiceCUP WITH _CUP
				ENDIF
			ENDIF
		ENDIF
	ENDIF
ENDSCAN

**=> ERASMO - INIZIO 14/01/2019
*** INCLUDO INIZIO E FINE TAG NELLA DATA ORDINE, IN QUANTO LA DATA POTREBBE NON ESSERE PRESENTE, E NON E' OBBLIGATORIA
SELECT RIFERIMENTI_ORDINE
GO TOP
SCAN
*!*		IF !EMPTY(DATIORDINEACQUISTODATA)
*!*			REPLACE DATIORDINEACQUISTODATA WITH "<Data>"+DATIORDINEACQUISTODATA+"</Data>"
*!*		ENDIF
	**=> ERASMO - INIZIO 28/01/2019
	IF !EMPTY(ALLTRIM(DATIORDINEACQUISTODATA))
		REPLACE DATIORDINEACQUISTODATA WITH "<Data>"+DATIORDINEACQUISTODATA+"</Data>"
	ELSE
		REPLACE DATIORDINEACQUISTODATA WITH ""
	ENDIF
	**=> ERASMO - INIZIO 28/01/2019
ENDSCAN
GO TOP
**=> ERASMO - FINE 14/01/2019

SELECT RIFERIMENTI_ORDINE
*DELETE FOR EMPTY(DATIORDINEACQUISTOIDDOCUMENTO+DATIORDINEACQUISTODATA+CodiceCIG+CodiceCUP)
DELETE FOR EMPTY(DATIORDINEACQUISTOIDDOCUMENTO)  && ERASMO - 14/01/2019
GO TOP

RETURN
* FINE PROCEDURE CREA_CURSOR_RIFERIMENTI_ORDINE
******************************************************************************
**=> ERASMO - FINE 07/11/2018


******************************************************************************
PROCEDURE APPEND_XML_FILE
******************************************************************************

LPARAMETERS P_CURSOR,P_XML_STRING,P_XML_FILE

LOCAL _XML_STRING

SELECT &P_CURSOR
GO TOP

_NUMERO_RIGA=0

SCAN 

	_XML_STRING = P_XML_STRING

	*_NUMERO_RIGA= _NUMERO_RIGA+1
	_NUMERO_RIGA = NR_RIGA  && ERASMO - 14/01/2019
	
	*_XML_STRING = STRTRAN(_XML_STRING ,"#NUMERO_RIGA#"  ,ALLTRIM(STR(_NUMERO_RIGA,2,0)))
	_XML_STRING = STRTRAN(_XML_STRING ,"#NUMERO_RIGA#"  ,ALLTRIM(STR(_NUMERO_RIGA,4,0)))  && ERASMO - 07/11/2018

	_XML_STRING =SOSTITUISCE_CAMPI_CURSOR_SU_TESTO(P_CURSOR,_XML_STRING )

	STRTOFILE(_XML_STRING ,P_XML_FILE,1)
	
ENDSCAN

RETURN
* FINE PROCEDURE APPEND_XML_FILE
******************************************************************************


******************************************************************************
PROCEDURE SOSTITUISCE_CAMPI_CURSOR_SU_TESTO
******************************************************************************

LPARAMETERS P_CURSOR,P_XML_STRING

LOCAL _XML_STRING

_XML_STRING = P_XML_STRING

SELECT &P_CURSOR

SCATTER MEMVAR MEMO

_NUMERO_CAMPI=AFIELDS(_ARRAY_CAMPI_CURSOR)

FOR nCount  = 1 TO _NUMERO_CAMPI
	_NOME_CAMPO="M."+ALLTRIM(_ARRAY_CAMPI_CURSOR(nCount ,1))
	_NOME_TAG  ="#"+ALLTRIM(_ARRAY_CAMPI_CURSOR(nCount ,1))+"#"
	
	DO CASE
		 *CASE _ARRAY_CAMPI_CURSOR(nCount ,2) = "C"
		 CASE _ARRAY_CAMPI_CURSOR(nCount ,2) $ "C;M"  && ERASMO - 07/11/2018
			_VALORE_CAMPO=EVALUATE("ALLTRIM("+_NOME_CAMPO+")")
		 CASE _ARRAY_CAMPI_CURSOR(nCount ,2) = "N"
		 	_DIMENSIONE= _ARRAY_CAMPI_CURSOR(nCount ,3)
		 	_DECIMALI= _ARRAY_CAMPI_CURSOR(nCount ,4)
		 	IF _DECIMALI>0
				_VALORE_CAMPO=EVALUATE("STRTRAN(ALLTRIM(STR("+_NOME_CAMPO+","+STR(_DIMENSIONE,3,0)+",2)),',','.')")
				*IF _NOME_CAMPO = "M.ORD_PREZZO"
				IF _NOME_CAMPO = "M.ORD_PREZZO"
					_VALORE_CAMPO=EVALUATE("STRTRAN(ALLTRIM(STR("+_NOME_CAMPO+","+STR(_DIMENSIONE,3,0)+",6)),',','.')")
				ENDIF
				**=> ERASMO - INIZIO 14/01/2019
*!*					IF _NOME_CAMPO = "M.IMPORTO_SCONTO" AND M.IMPORTO_SCONTO > 0
*!*						_VALORE_CAMPO=EVALUATE("STRTRAN(ALLTRIM(STR("+_NOME_CAMPO+","+STR(_DIMENSIONE,3,0)+",6)),',','.')")
*!*					ENDIF
				IF _NOME_CAMPO = "M.ORD_QTAORD"
					_VALORE_CAMPO=EVALUATE("STRTRAN(ALLTRIM(STR("+_NOME_CAMPO+","+STR(_DIMENSIONE,3,0)+",4)),',','.')")
				ENDIF
				**=> ERASMO - FINE 14/01/2019
			ELSE
				_VALORE_CAMPO=EVALUATE("ALLTRIM(STR("+_NOME_CAMPO+","+STR(_DIMENSIONE,3,0)+",0))")
			ENDIF					
			
	ENDCASE
	
	_XML_STRING= STRTRAN(_XML_STRING,_NOME_TAG  ,_VALORE_CAMPO)
	
ENDFOR

RETURN _XML_STRING

* FINE PROCEDURE SOSTITUISCE_CAMPI_CURSOR_SU_TESTO
******************************************************************************


******************************************************************************
PROCEDURE CONTROLLI_FORMALI
******************************************************************************

SELECT CU_AZIENDA
GO TOP
_PIVA=ALLTRIM(AZI_PIVA)
IF EMPTY(_PIVA)
	MESSAGEBOX("Errore nei parametri della fattura elettronica: manca P.IVA AZIENDA su U_AZI_AN",48,"Errore fattura elettronica")
	_YES_CONTINUA = .F.  && ERASMO - 07/11/2018
ENDIF


* FINE PROCEDURE CONTROLLI_FORMALI
******************************************************************************


******************************************************************************
PROCEDURE CERCA_IBAN_FATTURA_CLIENTE
******************************************************************************
SELECT CU_AZIENDA_PB
GO TOP
IF !EOF()
	IF !AZI_IBANFAT
		RETURN
	ENDIF
ENDIF

V_BANAP = ""
V_BANCA = ""
V_BANFORN = ""

SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF EOF()
	RETURN
ENDIF
V_CODCLI = ORD_CODCLI
V_PAG = ORD_CPA

V_BANCA = ORD_BANCA

v_seek	= PUB_CODSOC + ORD_CODCLI
v_chiave = "cli_codsoc+cli_codcli"
IF seek_std('u_cli_an',v_seek,v_chiave,'CUR_CLIENTE')
   SELECT CUR_CLIENTE
   V_BANFORN  		= CLI_BAEFOR
   V_IBANFOR  		= CLI_IBAFOR
   V_CODICE_SWIFT 	= CLI_BSWFOR	
   V_IBANCLI  		= CLI_CDIBAN
   V_BICSWIFT 		= CLI_BSWFOR
   V_CFISC    		= CLI_CODFIS
   V_PIVA     		= CLI_PARIVA
   V_CODNAZ   		= CLI_NAZION  
   V_PIVA_CEE 		= CLI_IVACEE  
   V_ALRID    		= CLI_ALRID
   IF EMPTY(V_PIVA)
      V_PIVA  = CLI_IVACEE
   ENDIF
   IF EMPTY(V_PIVA)
      V_PIVA  = ALLTRIM(CLI_CODFIS)
   ENDIF
ELSE
   V_CFISC 			= " "
   V_PIVA  			= SPACE(11)
   V_ALRID 			= SPACE(03)
   V_BANFORN  		= ""
   V_IBANFOR  		= ""
   V_IBANCLI  		= ""
   V_BICSWIFT 		= ""
   V_CODNAZ   		= ""
   V_PIVA_CEE 		= ""
   V_PIVA     		= ""
   V_CODICE_SWIFT 	= ""
ENDIF

v_seek 	 = 'CPA'+ALLTRIM(V_PAG)
v_chiave = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   V_CPAG = DESCRI
   IF SUBSTR(LIBERA,10,1) = 'X'			&& RI.BA.
      X_RIDE = 'N'
   ELSE
      X_RIDE = 'S'
   ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'COND.PAGAM' ---------- *
   DL_TIPODES 		= 'COND.PAGAM'
   DL_CODICE  		= V_PAG
   _DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
   IF !EMPTY(_DESCR_LINGUA)
      V_CPAG        = _DESCR_LINGUA    
   ENDIF
	* -------------------------------------------------------------------------- descrizioni in lingua ---------- 'COND.PAGAM' ---------- *
ELSE
   V_CPAG = SPACE(40)
   X_RIDE = SPACE(01)
ENDIF

** 1) ################################### GESTIONE IBAN : TENTA DI PRELEVARE IL CODICE IBAN DELLA BANCA NOSTRA DALLA BANCA DI APPOGGIO DEL CLIENTE 
**    ################################### SOLO PER RIMESSE DIRETTE
IF X_RIDE = 'S'
   IF EMPTY(V_BANCA)
      V_BANCA = V_BANFORN
   ENDIF   
   x_soci = "ban_codsoc = '" + PUB_CODSOC + "'"
   x_codi = "ban_codban = '" + ALLTRIM(V_BANCA) + "'"
   x_cond = x_soci + " and " + x_codi   
   cSql = "select * from u_ban_an where " + x_cond + " order by ban_codsoc,ban_codban"
   IF !ExecCommand(cSql,"CUR_BANCA")
      RETURN .F.
   ENDIF
   SELECT CUR_BANCA
   GO TOP   
   IF EOF()
      V_BANAP = ""
   ELSE
   	  __codice_swift = BAN_SWIFT	
	  IF !EMPTY(BAN_IBAN) 
	      V_BANAP = ALLTRIM(BAN_IBAN)
	  ENDIF
      *IF EMPTY(ALLTRIM(__codice_swift)) 
      *ELSE
      *   V_BANAP = V_BANAP + '  -  BIC/SWIFT : ' + ALLTRIM(__codice_swift)
      *ENDIF
   ENDIF
ELSE
   x_soci = "ban_codsoc = '" + PUB_CODSOC + "'"
   x_codi = "ban_codban = '" + ALLTRIM(V_BANCA) + "'"
   x_cond = x_soci + " and " + x_codi   
   cSql = "select * from u_ban_an where " + x_cond + " order by ban_codsoc,ban_codban"
   IF !ExecCommand(cSql,"CUR_BANCA")
      RETURN .F.
   ENDIF
   SELECT CUR_BANCA
   GO TOP   
   IF EOF()
      V_BANAP = ""
   ELSE
	  IF !EMPTY(BAN_IBAN) 
	      V_BANAP = ALLTRIM(BAN_IBAN)	&& >>>>>>>>>>>>>>>> IBAN DA ANAGRAFICA BANCHE U_BAN_AN
	  ELSE
	      ** 2014/08/27 SERGIO NEL CASO NON ESISTA SULLA BANCA PRENDE IBAN PER LE RIBA DALL'ANAGRAFICA CLIENTE 
	      IF !EMPTY(V_IBANCLI)	
		      V_BANAP = ALLTRIM(V_IBANCLI)	&& >>>>>>>>>>>>>>>> IBAN DA ANAGRAFICA CLIENTI
	      ENDIF 
	      ** 2014/08/27 SERGIO NEL CASO NON ESISTA SULLA BANCA PRENDE IBAN PER LE RIBA DALL'ANAGRAFICA CLIENTE 
	  ENDIF
   ENDIF
ENDIF

** 2) ################################### GESTIONE IBAN : TENTA DI PRELEVARE IL CODICE IBAN DELLA BANCA NOSTRA DIRETTAMENTE DALL'ANAGRAFICA CLIENTE
**    ################################### SOLO PER RIMESSE DIRETTE

IF X_RIDE = 'S' AND EMPTY(V_BANAP)
	IF !EMPTY(ALLTRIM(V_BANFORN))  
	   x_soci = "ban_codsoc = '" + PUB_CODSOC + "'"
	   x_codi = "ban_codban = '" + ALLTRIM(V_BANFORN) + "'"
	   x_cond = x_soci + " and " + x_codi   
	   cSql = "select * from u_ban_an where " + x_cond + " order by ban_codsoc,ban_codban"
	   IF !ExecCommand(cSql,"CUR_BANCA")
	      RETURN .F.
	   ENDIF
	   SELECT CUR_BANCA
	   GO TOP   
	   IF EOF()
	      V_BANAP = ""
	   ELSE
	      V_BANAP = ALLTRIM(V_IBANFOR)	&& >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> IBAN BANCA NOSTRA DA ANAGRAFICA CLIENTE U_CLI_AN
	      *IF EMPTY(ALLTRIM(V_CODICE_SWIFT)) 
	      *ELSE
	      *   V_BANAP = V_BANAP + '  -  BIC/SWIFT : ' + ALLTRIM(V_CODICE_SWIFT)
	      *ENDIF
	   ENDIF
	ENDIF
ENDIF

IF !EMPTY(V_BANAP)
	SELECT CU_AZIENDA_PB
	REPLACE AZI_IBAN WITH V_BANAP
ENDIF
* FINE PROCEDURE CERCA_IBAN_FATTURA_CLIENTE
******************************************************************************


******************************************************************************
PROCEDURE CERCA_MODALITA_PAGAMENTO_FATTURA_CLIENTE  
******************************************************************************
V_MODPAG = ""

SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF EOF()
	RETURN
ENDIF
V_PAG = ORD_CPA

v_seek 	 = 'CPA'+ALLTRIM(V_PAG)
v_chiave = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   V_MODPAG = ALLTRIM(CODPGO)
ENDIF

IF !EMPTY(V_MODPAG)
	SELECT CU_AZIENDA_PB
	REPLACE AZI_MODPAG WITH V_MODPAG
ENDIF
* FINE PROCEDURE CERCA_MODALITA_PAGAMENTO_FATTURA_CLIENTE  
******************************************************************************



******************************************************************************
PROCEDURE CREA_CURSOR_RIEPILOGO_IVA
******************************************************************************
RELEASE IVA1,IVA2,IVA3,IVA4,IVA5,IMPO1,IMPO2,IMPO3,IMPO4,IMPO5,IMPOS1,IMPOS2,IMPOS3,IMPOS4,IMPOS5
RELEASE V_SPINCA,V_SPTRAS
RELEASE DIVA1,DIVA2,DIVA3,DIVA4,DIVA5
RELEASE PIVA1,PIVA2,PIVA3,PIVA4,PIVA5
RELEASE M.T_OMAGGIO,M.I_OMAGGIO
RELEASE _CNT_PUBBLI,_CNT_ARTICOLI,PUB_TOTPOLIECO 
RELEASE _CNT_OMAGGI,_IMPONIBILE_POLIECO,_IMPOSTA_POLIECO
RELEASE MATPUB
RELEASE V_SPESE,V_IMPSP,V_ALRID
RELEASE NETTO
RELEASE V_IVASPTRAS

IVA1      = ""
IVA2      = ""
IVA3      = ""
IVA4      = ""
IVA5      = ""

IMPO1     = 0
IMPO2     = 0
IMPO3     = 0
IMPO4     = 0
IMPO5     = 0

IMPOS1    = 0
IMPOS2    = 0
IMPOS3    = 0
IMPOS4    = 0
IMPOS5    = 0

V_SPINCA  = 0
V_SPTRAS  = 0

DIVA1     = ""
DIVA2     = ""
DIVA3     = ""
DIVA4     = ""
DIVA5     = ""

PIVA1     = ""
PIVA2     = ""
PIVA3     = ""
PIVA4     = ""
PIVA5     = ""

M.T_OMAGGIO = 0
M.I_OMAGGIO = 0

_CNT_PUBBLI 	= 0		&& CONTATORE DI ARTICOLI PUBBLICITARI
_CNT_ARTICOLI 	= 0		&& CONTATORE DI ARTICOLI DI VENDITA
PUB_TOTPOLIECO  = 0		&& CALCOLO POLIECO

_CNT_OMAGGI 		= 0		&& CONTATORE DI ARTICOLI OMAGGIO CON IVA A CARICO AZIENDA
_IMPONIBILE_POLIECO = 0
_IMPOSTA_POLIECO    = 0 

MATPUB = 0   && MATERIALE PUBBLICITARIO

V_SPESE = 0
V_IMPSP = 0
V_ALRID = ""

NETTO = 0

V_IVASPTRAS = ""


CREATE CURSOR RIEPILOGO_IVA (NR_RIGA N(4,0), DATIRIEPILOGOALIQUOTAIVA N(10,2), DATIRIEPILOGONATURA C(20), DATIRIEPILOGOIMPONIBILEIMPORTO N(19,2), DATIRIEPILOGOIMPOSTA N(19,2), DATIRIEPILOGOESIGIBILITAIVA C(1), DATIRIEPILOGOSPESEACCESSORIE C(254))

TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY
	SELECT TT.ORD_CODCLI AS TT_CODCLI, TT.ORD_SPBOLL AS TT_ORD_SPBOLL, TT.ORD_SPTRAS AS TT_ORD_SPTRAS, DD.* FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON DD.DAGGANCIO=TT.TAGGANCIO
	--LEFT OUTER JOIN PARA AS IVA
	--ON 'IVA'+DD.ORD_IVA = IVA.CODICE
	--LEFT OUTER JOIN U_ART_PR AS PR
	--ON DD.ORD_CODART = PR.ART_CODPRI
	WHERE DD.ORD_QTAORD>0 AND TT.ORD_NUMORD='<<_NUMERO_FATTURA>>' AND TT.ORD_ANNO='<<_ANNO_FATTURA>>'
	ORDER BY DD.ORD_SEQUEN
ENDTEXT					&& FINE SCRITTURA QUERY
IF !ExecPreparedCommand(cSql,"TMP_FAT_DD")
	return(.F.)
ENDIF
SELECT TMP_FAT_DD
GO TOP
IF EOF()
	MESSAGEBOX("Dettagli fattura '" + _NUMERO_FATTURA + "' non trovati",16,"Attenzione")
	RETURN .F.
ENDIF

V_CODCLI = TT_CODCLI
V_SPINCA = TT_ORD_SPBOLL   && SPESE INCASSO
V_SPTRAS = TT_ORD_SPTRAS   && SPESE TRASPORTO

v_seek	= PUB_CODSOC + V_CODCLI
v_chiave = "cli_codsoc+cli_codcli"
IF seek_std('u_cli_an',v_seek,v_chiave,'CUR_CLIENTE')
   SELECT CUR_CLIENTE
   V_ALRID = CLI_ALRID
ENDIF

v_seek	= PUB_CODSOC + V_CODCLI
v_chiave = "cli_codsoc+cli_codcli"
IF seek_std('u_ana_cl',v_seek,v_chiave,'CUR_ANA_CL')
   SELECT CUR_ANA_CL
   V_IVASPTRAS = CLI_IVASPTRAS
ENDIF

SELECT TMP_FAT_DD
GO TOP
COD_IVA = ""
DO WHILE .T.

   IF EOF()
      EXIT
   ENDIF

   IF ALLTRIM(ORD_DESART) = "*** COMMENTO ***"
      SELECT TMP_FAT_DD
      SKIP +1
      LOOP
   ENDIF

   COD_IVA = ORD_IVA
   IMPONIB = ORD_VALORE
   DES_ART = SUBSTR(ORD_DESART,1,16)

   IF ALLTRIM(ORD_DESART) <> "*** COMMENTO ***"   && CONTO SOLO LE RIGHE CHE NON SONO COMMENTI
	   IF SUBSTR(ORD_CODART,1,7) <> 'POLIECO'
	   		_CNT_ARTICOLI = _CNT_ARTICOLI + 1
	   ENDIF
   ENDIF   
   IF SUBSTR(ORD_CODART,1,7) = 'POLIECO'
   		PUB_TOTPOLIECO = PUB_TOTPOLIECO + ORD_VALORE
   ENDIF   


   * VERIFICA SE DEVE STAMPARE LA RIGA IN MODO SINTETICO
   =VERYSIN("TMP_FAT_DD")

   IF ORD_PUBBLI = "S"			 && MATERIALE PUBBLICITARIO SI PAGA SOLO IVA
      MATPUB   = MATPUB + IMPONIB
      _CNT_PUBBLI = _CNT_PUBBLI + 1		
   ENDIF

   v_seek 	 = 'IVA'+COD_IVA
   v_chiave  = "codice"
   IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
      SELECT CUR_PARA
      ALIQ = SUBSTR(LIBERA,1,3)
      NUM_ALIQ = VAL(ALIQ)
   ELSE
      NUM_ALIQ = 0
   ENDIF
   SELECT TMP_FAT_DD

   IMPOSTA = (IMPONIB * NUM_ALIQ) / 100
   
   IF ORD_PUBBLI = "O"						&& CONTA ARTICOLO OMAGGIO
	   _CNT_OMAGGI = _CNT_OMAGGI + 1		
   ENDIF

   IF SUBSTR(ORD_CODART,1,7) = 'POLIECO' 	&& CALCOLO IMPONIBILE E IMPOSTA POLIECO
 		_IMPONIBILE_POLIECO = _IMPONIBILE_POLIECO + IMPONIB
		_IMPOSTA_POLIECO    = _IMPOSTA_POLIECO    + IMPOSTA  	   
   ENDIF
   
   IF ORD_PUBBLI = "O"			&& MATERIALEIN OMAGGIO CON IVA A CARICO AZIENDA
      M.T_OMAGGIO = M.T_OMAGGIO + IMPONIB
      M.I_OMAGGIO = M.I_OMAGGIO + IMPOSTA
      *** ERASMO - 18/01/2019 - IN CASO DI FATTURAZIONE ELETTRONICA GLI ARTICOLI OMAGGIO E PUBBLICITARI ENTRANO COMUNQUE NEL CALCOLO DEL RIEPILOGO IVA
      *SKIP +1
      *LOOP
   ENDIF

   IF ((IVA1 = SPACE(3)) .OR. (IVA1 = COD_IVA)) .AND. (DES_ART <> ('*** COMMENTO ***'))
      IVA1   = COD_IVA
      IMPO1  = IMPO1+IMPONIB
      IMPOS1 = IMPOS1 + IMPOSTA
   ELSE
      IF ((IVA2 = SPACE(3)) .OR. (IVA2 = COD_IVA))  .AND. (DES_ART <> ('*** COMMENTO ***'))
         IVA2   = COD_IVA
         IMPO2  = IMPO2+IMPONIB
         IMPOS2 = IMPOS2 + IMPOSTA
      ELSE
         IF ((IVA3 = SPACE(3)) .OR. (IVA3 = COD_IVA)) .AND. (DES_ART <> ('*** COMMENTO ***'))
            IVA3   = COD_IVA
            IMPO3  = IMPO3+IMPONIB
            IMPOS3 = IMPOS3 + IMPOSTA
         ELSE
            IF ((IVA4 = SPACE(3)) .OR. (IVA4 = COD_IVA)) .AND. (DES_ART <> ('*** COMMENTO ***'))
               IVA4   = COD_IVA
               IMPO4  = IMPO4+IMPONIB
               IMPOS4 = IMPOS4 + IMPOSTA
            ELSE
               IF ((IVA5 = SPACE(3)) .OR. (IVA5 = COD_IVA)) .AND. (DES_ART <> ('*** COMMENTO ***'))
                  IVA5   = COD_IVA
                  IMPO5  = IMPO5+IMPONIB
                  IMPOS5 = IMPOS5 + IMPOSTA
               ENDIF
            ENDIF
         ENDIF
      ENDIF
   ENDIF

   SELECT TMP_FAT_DD
   SKIP +1

ENDDO


*** SOMMA SPESE DI TRASPORTO + INCASSO
_lImponibileSPINCA = 0
_lImpostaSPINCA = 0
_lCodIvaSPINCA = ""
IF PUB_NOIVASPINC
	V_SPESE = V_SPTRAS	&& NON DEVE SOMMARE LE SPESE DI INCASSO PERCHE' SU QUELLE NON SI CALCOLANO IMPOSTE
	IF V_SPINCA > 0
		_lImponibileSPINCA = V_SPINCA
		_lImpostaSPINCA = 0
		_lCodIvaSPINCA = PUB_IVASPINC
		AGGIUNGI_RIGA_SPESE_ACCESSORIE_CURSOR_BODY_FATTURA_ELETTRONICA(_lImponibileSPINCA,_lImpostaSPINCA,_lCodIvaSPINCA,"SPESE INCASSO")
	ENDIF
ELSE
	V_SPESE = V_SPINCA + V_SPTRAS
ENDIF


PUB_IVADEF = CERCA_IVA_DEFAULT("TMP_FAT_DD","CODICE")  
PUB_ALIQ = CERCA_IVA_DEFAULT("TMP_FAT_DD","ALIQUOTA")  


** --- 4) SE CLIENTE EXTRA CEE GESTISCE IL CODICE IVA SPESE TRASPORTO SE E' STATO CODIFICATI IN ANAGRAFICA CLIENTI ----------------------- *
PIVA1TRA = ""
DIVA_SPESE_TRASPORTO = ""
SAY_IVA_SPESE_TRASPORTO = ""
ALIQTRA = ""
_lCodIvaSP = ""
IF !EMPTY(V_IVASPTRAS)
	_lCodIvaSP  = V_IVASPTRAS
	v_seek 	  = 'IVA'+V_IVASPTRAS
	v_chiave  = "codice"
	IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
	   SELECT CUR_PARA
	   PIVA1TRA	= SUBSTR(LIBERA,1,03)
	   DIVA_SPESE_TRASPORTO	= ALLTRIM(SUBSTR(DESCRI,1,80))
	   SAY_IVA_SPESE_TRASPORTO = DIVA_SPESE_TRASPORTO
       ALIQTRA 	= SUBSTR(LIBERA,1,3)
       NUM_ALIQ = VAL(ALIQTRA)
	   * -------------------------------------------------------------------------- descrizioni in lingua ----------- 'IVA' ---------- *
		DL_TIPODES 		= 'IVA'
		DL_CODICE  		= V_IVASPTRAS
		_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
	    IF !EMPTY(_DESCR_LINGUA)
			DIVA_SPESE_TRASPORTO  = _DESCR_LINGUA
		    SAY_IVA_SPESE_TRASPORTO = _DESCR_LINGUA
	    ENDIF
	   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
    ELSE
       ALIQTRA  = ""
       NUM_ALIQ = 0
       SAY_IVA_SPESE_TRASPORTO = ""
	ENDIF

    V_IMPSP = V_SPESE * (NUM_ALIQ/100)

ELSE
    
	** VERIFICA CHE PERCENTUALE IVA ATTRIBUIRE AL COSTO DEL TRASPORTO :
	** ----------------------------------------------------------------
	** --- 1) SE CLIENTE IN ESENZIONE %PERCENTUALE IVA SUL TRASPORTO E' = 0
	** --- 2) SE CLIENTE CON IVA NON IMPONIBILE (OSSIA PERCENTUALE ULTIMA ALIQUOTA IVA = 0) ANCHE LA %PERCENTUALE IVA SUL TRASPORTO E' = 0
	** --- 3) SE CLIENTE CON IVA IMPONIBILE LA %PERCENTUALE IVA SUL TRASPORTO E' = ALLA %PERCENTUALE IVA DI DEFAULT STANDARD (SE CI SONO DIVERSE ALIQUOTE NE CONSIDERA UNA E NON LA MEDIA)
	** --- 4) SE CLIENTE ETRA CEE GESTISCE IL CODICE IVA SPESE TRASPORTO SE E' STATO CODIFICATI IN ANAGRAFICA CLIENTI

	IF !EMPTY(V_ALRID)
		_lCodIvaSP = V_ALRID
	   	V_IMPSP = 0		 							&& --- 1) SE CLIENTE IN ESENZIONE %PERCENTUALE IVA SUL TRASPORTO E' = 0
	ELSE
		IF NUM_ALIQ = PUB_ALIQ						&& PERCENTUALE DELL'ULTIMA ALIQUOTA IVA PRESENTE NEGLI ARTICOLI
	   		V_IMPSP = V_SPESE * (PUB_ALIQ/100)  	&& --- 3) SE CLIENTE CON IVA IMPONIBILE LA %PERCENTUALE IVA SUL TRASPORTO E' = ALLA %PERCENTUALE IVA DI DEFAULT STANDARD 
	   		_lCodIvaSP = PUB_IVADEF
		ELSE
	   		V_IMPSP = V_SPESE * (NUM_ALIQ/100)  	&& --- 2) SE CLIENTE CON IVA NON IMPONIBILE (OSSIA PERCENTUALE ULTIMA ALIQUOTA IVA = 0) ANCHE LA %PERCENTUALE IVA SUL TRASPORTO E' = 0 
	   		_lCodIvaSP = COD_IVA
		ENDIF
	ENDIF

ENDIF
** --- 4) SE CLIENTE EXTRA CEE GESTISCE IL CODICE IVA SPESE TRASPORTO SE E' STATO CODIFICATI IN ANAGRAFICA CLIENTI ----------------------- *

_lImponibileSP = 0
_lImpostaSP = 0
IF V_SPESE > 0
	_lImponibileSP = V_SPESE
	_lImpostaSP = V_IMPSP
	AGGIUNGI_RIGA_SPESE_ACCESSORIE_CURSOR_BODY_FATTURA_ELETTRONICA(_lImponibileSP,_lImpostaSP,_lCodIvaSP,"SPESE ACCESSORIE")
ENDIF
_SPTRAS_NrIvaAccodata = 0

*** SE TUTTI GLI ARTICOLI SONO OMAGGIO DEVO TOGLIERE IL POLIECO DAL TOTALE IMPONIBILE E IMPOSTA E LI SOMMA NEL TOTALE IMPONIBILE , IMPOSTA OMAGGIO
*** QUESTA REGOLA E' APPLICATA ALLE SOLE FATTURE IN QUANTO POI IL COSTO E L'IVA SONO A CARICO DELL'AZIENDA
 IF _CNT_OMAGGI = _CNT_ARTICOLI && ARTICOLO OMAGGIO
   IMPO1  = IMPO1  - _IMPONIBILE_POLIECO 
   IMPOS1 = IMPOS1 - _IMPOSTA_POLIECO  
   M.T_OMAGGIO = M.T_OMAGGIO + _IMPONIBILE_POLIECO 
   M.I_OMAGGIO = M.I_OMAGGIO + _IMPOSTA_POLIECO  
ENDIF

NETTO = (IMPO1 + IMPO2 + IMPO3 + IMPO4 + IMPO5) - MATPUB

ACCO_IVA = .F.

NUM_ALIQ_ENPACL = 0

v_seek 	  = 'IVA'+IVA1
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   PIVA1 			= SUBSTR(LIBERA,1,03)
   DIVA1 			= ALLTRIM(SUBSTR(DESCRI,1,80))
   NUM_ALIQ_ENPACL 	= VAL(PIVA1)
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
	DL_TIPODES 		= 'IVA'
	DL_CODICE  		= IVA1
	_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
    IF !EMPTY(_DESCR_LINGUA)
		DIVA1  = _DESCR_LINGUA
    ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   IF IVA1 = PUB_IVADEF AND EMPTY(V_IVASPTRAS)
	  ACCO_IVA = .T.
   	  IMPO1    = IMPO1	+ V_SPESE
      IMPOS1   = IMPOS1 + V_IMPSP
      _SPTRAS_NrIvaAccodata = 1
   ENDIF
ENDIF

v_seek 	  = 'IVA'+IVA2
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   PIVA2 = SUBSTR(LIBERA,1,03)
   DIVA2 = ALLTRIM(SUBSTR(DESCRI,1,80))
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
	DL_TIPODES 		= 'IVA'
	DL_CODICE  		= IVA2
	_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
    IF !EMPTY(_DESCR_LINGUA)
		DIVA2  = _DESCR_LINGUA
    ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   IF IVA2 = PUB_IVADEF AND EMPTY(V_IVASPTRAS)
	  ACCO_IVA = .T.
      IMPO2    = IMPO2	+ V_SPESE
      IMPOS2   = IMPOS2 + V_IMPSP
      _SPTRAS_NrIvaAccodata = 2
   ENDIF
ENDIF

v_seek 	  = 'IVA'+IVA3
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   PIVA3 = SUBSTR(LIBERA,1,03)
   DIVA3 = ALLTRIM(SUBSTR(DESCRI,1,80))
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
	DL_TIPODES 		= 'IVA'
	DL_CODICE  		= IVA3
	_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
    IF !EMPTY(_DESCR_LINGUA)
		DIVA3  = _DESCR_LINGUA
    ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   IF IVA3 = PUB_IVADEF AND EMPTY(V_IVASPTRAS)
	  ACCO_IVA = .T.
      IMPO3    = IMPO3	+ V_SPESE
      IMPOS3   = IMPOS3 + V_IMPSP
      _SPTRAS_NrIvaAccodata = 3
   ENDIF
ENDIF

v_seek 	  = 'IVA'+IVA4
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   PIVA4 = SUBSTR(LIBERA,1,03)
   DIVA4 = ALLTRIM(SUBSTR(DESCRI,1,80))
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
	DL_TIPODES 		= 'IVA'
	DL_CODICE  		= IVA4
	_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
    IF !EMPTY(_DESCR_LINGUA)
		DIVA4  = _DESCR_LINGUA
    ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   IF IVA4 = PUB_IVADEF AND EMPTY(V_IVASPTRAS)
	  ACCO_IVA = .T.
      IMPO4    = IMPO4	+ V_SPESE
      IMPOS4   = IMPOS4 + V_IMPSP
      _SPTRAS_NrIvaAccodata = 4
   ENDIF
ENDIF

v_seek 	  = 'IVA'+IVA5
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   PIVA5 = SUBSTR(LIBERA,1,03)
   DIVA5 = ALLTRIM(SUBSTR(DESCRI,1,80))
   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
	DL_TIPODES 		= 'IVA'
	DL_CODICE  		= IVA5
	_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
    IF !EMPTY(_DESCR_LINGUA)
		DIVA5  = _DESCR_LINGUA
    ENDIF
   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   IF IVA5 = PUB_IVADEF AND EMPTY(V_IVASPTRAS)
	  ACCO_IVA = .T.
      IMPO5    = IMPO5	+ V_SPESE
      IMPOS5   = IMPOS5 + V_IMPSP
      _SPTRAS_NrIvaAccodata = 5
   ENDIF
ENDIF

** --- 4) SE CLIENTE EXTRA CEE GESTISCE IL CODICE IVA SPESE TRASPORTO SE E' STATO CODIFICATI IN ANAGRAFICA CLIENTI ----------------------- *
IF !EMPTY(V_IVASPTRAS)

	IF V_SPESE <> 0									&& GESTIONE SOLO SE ESISTONO SPESE+SPESE DI TRASPORTO

	    DO CASE 
	    	CASE EMPTY(IVA1)						&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		IVA1		= ALLTRIM(V_IVASPTRAS)
			    PIVA1 		= ALLTRIM(ALIQTRA)		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		DIVA1  		= DIVA_SPESE_TRASPORTO	&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	        	IMPO1  		= IMPO1	 + V_SPESE		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	      		IMPOS1 		= IMPOS1 + V_IMPSP		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
				ACCO_IVA 	= .T.
				_SPTRAS_NrIvaAccodata = 1
	    	CASE EMPTY(IVA2)						&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
		    	IVA2		= ALLTRIM(V_IVASPTRAS)
			    PIVA2 		= ALLTRIM(ALIQTRA)		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		DIVA2  		= DIVA_SPESE_TRASPORTO	&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	        	IMPO2  		= IMPO2	 + V_SPESE		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	      		IMPOS2 		= IMPOS2 + V_IMPSP		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
				ACCO_IVA 	= .T.
				_SPTRAS_NrIvaAccodata = 2
	    	CASE EMPTY(IVA3)						&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
		    	IVA3		= ALLTRIM(V_IVASPTRAS)
			    PIVA3 		= ALLTRIM(ALIQTRA)	    && ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		DIVA3  		= DIVA_SPESE_TRASPORTO	&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	        	IMPO3  		= IMPO3	 + V_SPESE		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	      		IMPOS3 		= IMPOS3 + V_IMPSP		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
				ACCO_IVA 	= .T.
				_SPTRAS_NrIvaAccodata = 3
	    	CASE EMPTY(IVA4)						&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
		    	IVA4		= ALLTRIM(V_IVASPTRAS)
			    PIVA4 		= ALLTRIM(ALIQTRA)	    && ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		DIVA4  		= DIVA_SPESE_TRASPORTO	&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	        	IMPO4  		= IMPO4	 + V_SPESE		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	      		IMPOS4 		= IMPOS4 + V_IMPSP		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
				ACCO_IVA 	= .T.
				_SPTRAS_NrIvaAccodata = 4
	    	CASE EMPTY(IVA5)						&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
		    	IVA5		= ALLTRIM(V_IVASPTRAS)
			    PIVA5 		= ALLTRIM(ALIQTRA)	    && ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	    		DIVA5  		= DIVA_SPESE_TRASPORTO	&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	        	IMPO5  		= IMPO5	 + V_SPESE		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
	      		IMPOS5 		= IMPOS5 + V_IMPSP		&& ACCODO VALORI SPESE + SPESE TRASPORTO ALLA PRIMA VARIABILE LIBERA
				ACCO_IVA 	= .T.
				_SPTRAS_NrIvaAccodata = 5
	    ENDCASE
	    
	ENDIF
	
ENDIF
** --- 4) SE CLIENTE EXTRA CEE GESTISCE IL CODICE IVA SPESE TRASPORTO SE E' STATO CODIFICATI IN ANAGRAFICA CLIENTI ----------------------- *



IF !ACCO_IVA    && SE NON ESIST UN IVA  NELLE RIGHE SOMMA IMPOSTA SPESE TRASP. ALLA PRIMA IVA
   v_seek 	  = 'IVA'+IVA1
   v_chiave  = "codice"
   IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
       SELECT CUR_PARA
	   PIVA1  = SUBSTR(LIBERA,1,03)
	   DIVA1  = ALLTRIM(SUBSTR(DESCRI,1,80))
       IMPO1  = IMPO1+V_SPESE
 	   IMPOS1 = IMPOS1 + V_IMPSP
 	   _SPTRAS_NrIvaAccodata = 1
	   * -------------------------------------------------------------------------- descrizioni in lingua ---------- 'IVA' ---------- *
		DL_TIPODES 		= 'IVA'
		DL_CODICE  		= IVA1
		_DESCR_LINGUA 	= CERCA_DESCRIZIONI_IN_LINGUA(DL_TIPODES,DL_LINGUA,DL_CODICE)
	    IF !EMPTY(_DESCR_LINGUA)
			DIVA1  = _DESCR_LINGUA
	    ENDIF
	   * -------------------------------------------------------------------------- descrizioni in lingua ----------  'IVA' ---------- *
   ENDIF
ENDIF

_NR_RIGA = 0
FOR _I = 1 TO 5
	_VAR_IVA = "IVA"+ALLTRIM(STR(_I,1,0))
	_VAR_IMPO = "IMPO"+ALLTRIM(STR(_I,1,0))
	_VAR_IMPOS = "IMPOS"+ALLTRIM(STR(_I,1,0))
	
	IF !EMPTY(&_VAR_IVA)
	ELSE
		EXIT
	ENDIF
	
	_X_NUM_ALIQ = 0
	_X_NATURA = ""
    v_seek 	 = 'IVA'+&_VAR_IVA
    v_chiave  = "codice"
    IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
       SELECT CUR_PARA
       _X_ALIQ = SUBSTR(LIBERA,1,3)
       _X_NUM_ALIQ = VAL(_X_ALIQ)
       _X_NATURA = SUBSTR(LIBERA,145,2)
    ENDIF
    
    _DATIRIEPILOGONATURA = ""
    *IF &_VAR_IMPOS = 0
    IF &_VAR_IMPOS = 0 AND &_VAR_IMPO <> 0  && ERASMO - 08/01/2019
    	IF EMPTY(_X_NATURA)
    		MESSAGEBOX("Codificare la Natura esenzione per il codice iva " + ALLTRIM(&_VAR_IVA) + CHR(13) + "(Fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA+")",16,"Attenzione")
    		_YES_CONTINUA = .F.
    		RETURN .F.
    	ENDIF
    	_DATIRIEPILOGONATURA = "<Natura>"+ALLTRIM(_X_NATURA)+"</Natura>"
    ENDIF
    
    _DATIRIEPILOGOESIGIBILITAIVA = ""
	SELECT HEADER_FATTURA_ELETTRONICA
	GO TOP
	IF !EOF()
		_DATIRIEPILOGOESIGIBILITAIVA = ALLTRIM(ESIGIBILITA_IVA)
	ENDIF
	
	_DATIRIEPILOGOSPESEACCESSORIE = ""
	IF V_SPESE <> 0	AND _SPTRAS_NrIvaAccodata = _I
		_DATIRIEPILOGOSPESEACCESSORIE = "<SpeseAccessorie>"+STRTRAN(ALLTRIM(STR(ROUND(_lImponibileSP,2),10,2)),",",".")+"</SpeseAccessorie>"
	ENDIF

	SELECT RIEPILOGO_IVA
	APPEND BLANK
	_NR_RIGA = _NR_RIGA + 1
	REPLACE NR_RIGA WITH _NR_RIGA
	REPLACE DATIRIEPILOGOALIQUOTAIVA WITH _X_NUM_ALIQ
	REPLACE DATIRIEPILOGONATURA WITH _DATIRIEPILOGONATURA 
	REPLACE DATIRIEPILOGOIMPONIBILEIMPORTO WITH &_VAR_IMPO
	REPLACE DATIRIEPILOGOIMPOSTA WITH &_VAR_IMPOS
	REPLACE DATIRIEPILOGOESIGIBILITAIVA WITH _DATIRIEPILOGOESIGIBILITAIVA
	REPLACE DATIRIEPILOGOSPESEACCESSORIE WITH _DATIRIEPILOGOSPESEACCESSORIE
ENDFOR

IF PUB_NOIVASPINC AND V_SPINCA <> 0
	_X_NUM_ALIQ = 0
	_X_NATURA = ""
    v_seek 	 = 'IVA'+_lCodIvaSPINCA
    v_chiave  = "codice"
    IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
       SELECT CUR_PARA
       _X_ALIQ = SUBSTR(LIBERA,1,3)
       _X_NUM_ALIQ = VAL(_X_ALIQ)
       _X_NATURA = SUBSTR(LIBERA,145,2)
    ENDIF
    
    _DATIRIEPILOGONATURA = ""
    IF _lImpostaSPINCA = 0
    	IF EMPTY(_X_NATURA)
    		MESSAGEBOX("Codificare la Natura esenzione per il codice iva " + ALLTRIM(_lCodIvaSPINCA) + CHR(13) + "(Fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA+")",16,"Attenzione")
    		_YES_CONTINUA = .F.
    		RETURN .F.
    	ENDIF
    	_DATIRIEPILOGONATURA = "<Natura>"+ALLTRIM(_X_NATURA)+"</Natura>"
    ENDIF
    
    _DATIRIEPILOGOESIGIBILITAIVA = ""
	SELECT HEADER_FATTURA_ELETTRONICA
	GO TOP
	IF !EOF()
		_DATIRIEPILOGOESIGIBILITAIVA = ALLTRIM(ESIGIBILITA_IVA)
	ENDIF
	
	_DATIRIEPILOGOSPESEACCESSORIE = "<SpeseAccessorie>"+STRTRAN(ALLTRIM(STR(ROUND(_lImponibileSPINCA,2),10,2)),",",".")+"</SpeseAccessorie>"

	SELECT RIEPILOGO_IVA
	APPEND BLANK
	REPLACE DATIRIEPILOGOALIQUOTAIVA WITH _X_NUM_ALIQ
	REPLACE DATIRIEPILOGONATURA WITH _DATIRIEPILOGONATURA 
	REPLACE DATIRIEPILOGOIMPONIBILEIMPORTO WITH _lImponibileSPINCA
	REPLACE DATIRIEPILOGOIMPOSTA WITH _lImpostaSPINCA
	REPLACE DATIRIEPILOGOESIGIBILITAIVA WITH _DATIRIEPILOGOESIGIBILITAIVA
	REPLACE DATIRIEPILOGOSPESEACCESSORIE WITH _DATIRIEPILOGOSPESEACCESSORIE
ENDIF

**=> ERASMO - INIZIO 19/01/2019
SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF !EOF()
	REPLACE IMPORTOTOTALEDOCUMENTO WITH ROUND(ORD_VALORE,2) + ROUND(M.T_OMAGGIO,2) + ROUND(M.I_OMAGGIO,2)
ENDIF
**=> ERASMO - FINE 19/01/2019

RETURN
* FINE PROCEDURE CREA_CURSOR_RIEPILOGO_IVA
******************************************************************************


******************************************************************************
PROCEDURE CREA_CURSOR_DETTAGLI_PAGAMENTO
******************************************************************************
CREATE CURSOR DETTAGLI_PAGAMENTO (NR_RIGA N(4,0), DETTAGLIOPAGAMENTOMODALITAPAGAMENTO C(4), DETTAGLIOPAGAMENTODATASCADENZAPAGAMENTO C(10), DETTAGLIOPAGAMENTOIMPORTOPAGAMENTO N(10,2), DETTAGLIOPAGAMENTOIBAN C(40))

SELECT CU_AZIENDA_PB
GO TOP
_DETTAGLIOPAGAMENTOMODALITAPAGAMENTO_DEFAULT = ALLTRIM(AZI_MODPAG)
*_DETTAGLIOPAGAMENTOIBAN_DEFAULT = ALLTRIM(AZI_IBAN)
_DETTAGLIOPAGAMENTOIBAN_DEFAULT = IIF(LEN(ALLTRIM(AZI_IBAN))=27,"<IBAN>"+ALLTRIM(AZI_IBAN)+"</IBAN>","")  && ERASMO - 23/01/2019

SELECT HEADER_FATTURA_ELETTRONICA
GO TOP
IF EOF()
	RETURN
ENDIF
_XX_DATORD = ORD_DATORD
_XX_NUMORD = ORD_NUMORD
_XX_CODCLI = ORD_CODCLI

x_soci = "ord_codsoc = '" + PUB_CODSOC + "'"
x_dord = "ord_datord = '" + _XX_DATORD + "'"
x_nord = "ord_numord = '" + _XX_NUMORD + "'"
x_cond = x_soci + " and " + x_dord + " and " + x_nord
cSql   = "select * from U_FAT_TT where " + x_cond
IF !ExecCommand(cSql,"CU_FAT_TT")
	return(.f.)
ENDIF
SELECT CU_FAT_TT
DELETE FOR ORD_CODCLI <> _XX_CODCLI
GO TOP
SCATTER MEMVAR MEMO

IF USED("XU_FAT_DD")
	SELECT XU_FAT_DD
	USE
ENDIF

IF !ExecCommand("select * from U_FAT_DD where 0=1","XU_FAT_DD")
   return(.f.)
ENDIF

IF USED("U_DOC_DD")
	SELECT U_DOC_DD
	USE
ENDIF

SELECT XU_FAT_DD
SET FILTER TO
SET ORDER TO
ZAP

** RIEMPIE IL CURSORE DI TUTTI I DETTAGLI DOCUMENTO  --------------------------------------------------------------*
x_agga = "daggancio = '" + M.TAGGANCIO + "'"
x_cond = x_agga
Csql = "select * from U_FAT_DD where " + x_cond + " order by ord_sequen"  
IF !ExecCommand(cSql,"U_DOC_DD")
	return(.f.)
ENDIF
SELECT U_DOC_DD
GO TOP

DO WHILE .T.

	IF EOF()
		EXIT
	ENDIF

	IF DELETED()
		SKIP +1
		LOOP
	ENDIF
	
	SCATTER MEMVAR MEMO
	
	SELECT XU_FAT_DD
	APPEND BLANK
	
	M.ORS_NUMORD = M.ORD_NUMORD 
	M.ORS_DATORD = M.ORD_DATORD 
	M.ORS_CODCLI = M.ORD_CODCLI		 
	
	DO U_FAT_DD
		
	SELECT U_DOC_DD
	SKIP +1

ENDDO

SELECT CU_FAT_TT
GO TOP
SCATTER MEMVAR MEMO

*########## INIZIO - DA RISTAMPELIB.PRG
CREATE CURSOR PERIODI;
   (DSCAD C(10),IMP_SCAD N(15,3),NUM_TRAN N(5))
   
***==>  CREA TRANCHE 

PUBLIC VET_DAL[2],VET_AL[2],VET_DAY[2]

x_soci = "cli_codsoc = '" + PUB_CODSOC + "'"
x_codi = "cli_codcli = '" + ALLTRIM(M.ORD_CODCLI) + "'"
x_cond = x_soci + " and " + x_codi   
cSql = "select * from u_cli_an where " + x_cond + " order by cli_codsoc,cli_codcli"
IF !ExecCommand(cSql,"CUR_CLIENTI")
   RETURN .F.
ENDIF
SELECT CUR_CLIENTI
GO TOP   
IF EOF()
   DL_LINGUA = ""
   VET_DAL[1]= "0000"
   VET_DAL[2]= "0000"
   VET_AL[1] = "0000"
   VET_AL[2] = "0000"
   VET_DAY[1]= "0000"
   VET_DAY[2]= "0000"
   ___FLAG_POSALL = .F.		&& 2010-08-04 sergio posticipi per tutto l'anno
   ___CLIENTE     = ""		&& 2010-08-04 sergio posticipi per tutto l'anno 
ELSE
   DL_LINGUA = CLI_LINGUA
   VET_DAL[1]= CLI_BDAL
   VET_DAL[2]= CLI_B2DAL
   VET_AL[1] = CLI_BAL
   VET_AL[2] = CLI_B2AL
   VET_DAY[1]= CLI_GG1
   VET_DAY[2]= CLI_GG2
   ___FLAG_POSALL = CLI_POSALL		&& 2010-08-04 sergio posticipi per tutto l'anno
   ___CLIENTE     = M.ORD_CODCLI		&& 2010-08-04 sergio posticipi per tutto l'anno   
ENDIF

SELECT XU_FAT_DD
GO TOP

RELEASE __T_IMPON,__T_IMPOS   
PUBLIC  __T_IMPON,__T_IMPOS   
__T_IMPON	= M.ORD_IMPONIB
__T_IMPOS   = M.ORD_IMPOSTA  

V_DATASCAD = M.ORD_DATORD
V_PAG = M.ORD_CPA
TOT_FATT = M.ORD_VALORE
V_VALUTA = M.ORD_VALUTA

V_TUTTO = TRANCHE("PARA",V_PAG,V_DATASCAD,TOT_FATT,VET_DAL,VET_AL,VET_DAY,V_VALUTA,___FLAG_POSALL,___CLIENTE,__T_IMPON,__T_IMPOS)

=CREA_SCADENZE()



*** SE CONDIZIONE DI PAGAMENTO SPECIALE, A SECONDA DEL VALORE DI PUB_SSPORD:
*** 1 - RIGENERA IL COMMENTO CON I RIFERIMENTI ALLE SCADENZE SPECIALI
*** 2 - RIPORTA RIFERIMENTI ALLE SCADENZE SPECIALI NEI VETTORI RELATIVI ALLA GESTIONE DELLE SCADENZE
IF checkConSpe(V_PAG)
	=SCADENZE_SPECIALI(M.TIPRENDO,.F.,.F.,.T.,"XU_FAT_DD",.F.)
	SELECT XU_FAT_DD
    DELETE FOR DAGGANCIO = 'EOF'
	APPEND BLANK
	REPLACE DAGGANCIO  WITH 'EOF'
	REPLACE ORD_SEQUEN WITH 99999
	   
	REPLACE ORS_NUMORD WITH M.ORD_NUMORD
	REPLACE ORS_DATORD WITH M.ORD_DATORD
	REPLACE ORS_CODCLI WITH M.ORD_CODCLI   
ENDIF
*########## FINE - DA RISTAMPELIB.PRG

*!*	FOR _I = 1 TO 7
*!*		IF !EMPTY(DATA(_I)) AND IMPORTO(_I) > 0
*!*			SELECT DETTAGLI_PAGAMENTO
*!*			APPEND BLANK
*!*			REPLACE NR_RIGA WITH _I
*!*			REPLACE DETTAGLIOPAGAMENTOMODALITAPAGAMENTO WITH _DETTAGLIOPAGAMENTOMODALITAPAGAMENTO_DEFAULT
*!*			REPLACE DETTAGLIOPAGAMENTODATASCADENZAPAGAMENTO WITH SUBSTR(DATA(_I),7,4) + '-' + SUBSTR(DATA(_I),4,2) + '-' + SUBSTR(DATA(_I),1,2)
*!*			REPLACE DETTAGLIOPAGAMENTOIMPORTOPAGAMENTO WITH IMPORTO(_I)
*!*			REPLACE DETTAGLIOPAGAMENTOIBAN WITH _DETTAGLIOPAGAMENTOIBAN_DEFAULT
*!*		ENDIF
*!*	ENDFOR

**=> ERASMO - INIZIO 17/01/2019
IF checkConSpe(V_PAG)
	SELECT CUR_SCADENZE
	GO TOP
	_NR_RIGA = 0
	SCAN
		_NR_RIGA = _NR_RIGA + 1
		_ORD_RIBA = ORD_RIBA
		_ORD_DTSCAD = ORD_DTSCAD
		_ORD_TRANCH = ORD_TRANCH
		SELECT DETTAGLI_PAGAMENTO
		APPEND BLANK
		REPLACE NR_RIGA WITH _NR_RIGA
		REPLACE DETTAGLIOPAGAMENTOMODALITAPAGAMENTO WITH IIF(_ORD_RIBA,'MP12',_DETTAGLIOPAGAMENTOMODALITAPAGAMENTO_DEFAULT)
		REPLACE DETTAGLIOPAGAMENTODATASCADENZAPAGAMENTO WITH SUBSTR(_ORD_DTSCAD,7,4) + '-' + SUBSTR(_ORD_DTSCAD,4,2) + '-' + SUBSTR(_ORD_DTSCAD,1,2)
		REPLACE DETTAGLIOPAGAMENTOIMPORTOPAGAMENTO WITH _ORD_TRANCH
		REPLACE DETTAGLIOPAGAMENTOIBAN WITH _DETTAGLIOPAGAMENTOIBAN_DEFAULT
	ENDSCAN
ELSE
	FOR _I = 1 TO 7
		IF !EMPTY(DATA(_I)) AND IMPORTO(_I) > 0
			SELECT DETTAGLI_PAGAMENTO
			APPEND BLANK
			REPLACE NR_RIGA WITH _I
			REPLACE DETTAGLIOPAGAMENTOMODALITAPAGAMENTO WITH _DETTAGLIOPAGAMENTOMODALITAPAGAMENTO_DEFAULT
			REPLACE DETTAGLIOPAGAMENTODATASCADENZAPAGAMENTO WITH SUBSTR(DATA(_I),7,4) + '-' + SUBSTR(DATA(_I),4,2) + '-' + SUBSTR(DATA(_I),1,2)
			REPLACE DETTAGLIOPAGAMENTOIMPORTOPAGAMENTO WITH IMPORTO(_I)
			REPLACE DETTAGLIOPAGAMENTOIBAN WITH _DETTAGLIOPAGAMENTOIBAN_DEFAULT
		ENDIF
	ENDFOR
ENDIF
**=> ERASMO - FINE 17/01/2019
		

* FINE PROCEDURE CREA_CURSOR_DETTAGLI_PAGAMENTO
******************************************************************************


******************************************************************************
PROCEDURE AGGIUNGI_RIGA_SPESE_ACCESSORIE_CURSOR_BODY_FATTURA_ELETTRONICA
******************************************************************************
LPARAMETERS _par_ImponibileSP,__par_ImpostaSP,_par_CodIvaSP,_par_DescrRiga

_X_NUM_ALIQ = 0
_X_NATURA = ""
v_seek 	 = 'IVA'+_par_CodIvaSP
v_chiave  = "codice"
IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
   SELECT CUR_PARA
   _X_ALIQ = SUBSTR(LIBERA,1,3)
   _X_NUM_ALIQ = VAL(_X_ALIQ)
   _X_NATURA = SUBSTR(LIBERA,145,2)
ENDIF
    
_DETTAGLIOLINEENATURAIVA = ""
IF __par_ImpostaSP = 0
	IF EMPTY(_X_NATURA)
		MESSAGEBOX("Codificare la Natura esenzione per il codice iva " + ALLTRIM(_par_CodIvaSP) + CHR(13) + "(Fattura n°"+_NUMERO_FATTURA+"/"+_ANNO_FATTURA+")",16,"Attenzione")
		_YES_CONTINUA = .F.
		RETURN .F.
	ENDIF
	_DETTAGLIOLINEENATURAIVA = "<Natura>"+ALLTRIM(_X_NATURA)+"</Natura>"
ENDIF

SELECT FatturaElettronica
GO BOTTOM
_NR_RIGA = NR_RIGA + 1			&& ERASMO - 14/01/2019
APPEND BLANK					&& ERASMO - 14/01/2019
REPLACE NR_RIGA WITH _NR_RIGA	&& ERASMO - 14/01/2019
REPLACE ORD_QTAORD WITH 1
REPLACE CODICE_TIPO WITH 'ART'
REPLACE CODICE_VALORE WITH "."
REPLACE ORD_CODART WITH "."
REPLACE ORD_DESART WITH _par_DescrRiga
REPLACE ORD_PREZZO WITH _par_ImponibileSP
*REPLACE ORD_SC1 WITH 0
REPLACE IMPORTO_SCONTO WITH 0
REPLACE ORD_PRZNET WITH _par_ImponibileSP
REPLACE ORD_VALORE WITH _par_ImponibileSP
REPLACE DETTAGLIOLINEEALIQUOTAIVA WITH ROUND(_X_NUM_ALIQ,2)
REPLACE DETTAGLIOLINEENATURAIVA WITH _DETTAGLIOLINEENATURAIVA 
REPLACE DETTAGLIOLINEERIFERIMENTOAMMINISTRAZIONE WITH ""
REPLACE DETTAGLIOLINEETIPOCESSIONEPRESTAZIONE WITH "<TipoCessionePrestazione>AC</TipoCessionePrestazione>"  && SPESE ACCESSORIE

RETURN
* FINE PROCEDURE AGGIUNGI_RIGA_SPESE_ACCESSORIE_CURSOR_BODY_FATTURA_ELETTRONICA
******************************************************************************