************************************************************
********* FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO *********
************************************************************
*!*	LPARAMETERS _CENTRI_COSTO

*!*	IF PCOUNT()<1
*!*		RETURN .F.
*!*	ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

RELEASE V_TITOLO
PUBLIC V_TITOLO
V_TITOLO = "FATTURE DA SALDARE O SALDATE NELL'ULTIMO ANNO ALLA DATA " + STRTRAN(DTOC(DATE()),"/","-")

WAIT WINDOWS "ESEGUE PROGRAMMA FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO" TIMEOUT 3

cSql=""     
cNomeCursorSql="CU_SCADENZE"
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT
		COALESCE(FAT_DD.ORD_CCODET,'') AS COD_CENTRO_COSTO,
		COALESCE(CCOSTO.CON_DESCR,'') AS DESCR_CENTRO_COSTO,
		SUBSTRING(RIGHE_PART.PAR_CODCLI,5,10) AS COD_CLIENTE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NPROT AS NUM_FATTURA,
		RIGHE_PART.PAR_DTFAT AS DATA_FATTURA,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) AS IMPORTO_SCAD_PAG,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		ROUND(FAT_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		ROUND(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO + FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,2) AS IMPONIBILE_IMPOSTA_TOT_FATTURA,
		ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		ROUND(COALESCE(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO,0),2) AS IMPONIBILE_TOT_FATTURA,
		ROUND(COALESCE(FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,0),2) AS IMPOSTA_TOT_FATTURA,
		COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,1,3),'') AS CANALE_VENDITA_CLIENTE,
		COALESCE(PARA_CVE_1.DESCRI,'') AS DESCR_CANALE_VENDITA_CLIENTE,
		COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,4,3),'') AS MACROCLASSE_CLIENTE,
		COALESCE(PARA_CVE_2.DESCRI,'') AS DESCR_MACROCLASSE_CLIENTE,
		COALESCE(SUBSTRING(U_CLI_AN.CLI_CANVEN,7,3),'')	AS CLASSE_CLIENTE,
		COALESCE(PARA_CVE_3.DESCRI,'') AS DESCR_CLASSE_CLIENTE,
		COALESCE(U_CLI_AN.CLI_NAZION,'') AS NAZIONE_CLIENTE,
		COALESCE(PARA_STA.DESCRI,'') AS DESCR_NAZIONE_CLIENTE,
		COALESCE(U_CLI_AN.CLI_ZONA,'') AS AREA_GEOGRAFICA_CLIENTE,
		COALESCE(PARA_ZON.DESCRI,'') AS DESCR_AREA_GEOGRAFICA_CLIENTE,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA2,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2)
				THEN COALESCE(PAG_SCA.PAR_DTREG,'')
			ELSE ''
		END AS DATA_PAGAMENTO,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) AND COALESCE(PAG_SCA.PAR_DTREG,'') <> '' 
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAG_SCA.PAR_DTREG) AS datetime))
			ELSE 0
		END AS NR_GIORNI_RITARDO
	FROM PART_CLI AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'D' GROUP BY PAR_CODCLI, PAR_NPART) AS FAT_TOT ON FAT_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAT_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_SCAD_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_ANNO,PAR_DTSCAD,PAR_NPROT,PAR_DTFAT FROM PART_CLI WHERE PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_NPROG <> 100 AND PAR_TMOV = 'D' AND PAR_TIPODO = 'FAT' ORDER BY PAR_DTSCAD) AS TEST_PART
		LEFT OUTER JOIN (SELECT DISTINCT ORD_CCODET, ORS_NUMORD, ORS_DATORD FROM U_FAT_DD WHERE ORD_DESART <> '*** COMMENTO ***') AS FAT_DD ON FAT_DD.ORS_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_DD.ORS_DATORD = RIGHE_PART.PAR_DTFAT
		RIGHT OUTER JOIN U_FAT_TT AS FAT_TT ON FAT_TT.ORD_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_TT.ORD_DATORD = RIGHE_PART.PAR_DTFAT
		LEFT OUTER JOIN CCOSTO ON CCOSTO.CON_ANNO = SUBSTRING(FAT_DD.ORS_DATORD,1,4) AND CCOSTO.CON_CONTO = FAT_DD.ORD_CCODET
		LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODCLI = FAT_TT.ORD_CODCLI
		LEFT OUTER JOIN PARA AS PARA_CVE_1 ON PARA_CVE_1.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,3)
		LEFT OUTER JOIN PARA AS PARA_CVE_2 ON PARA_CVE_2.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,6)
		LEFT OUTER JOIN PARA AS PARA_CVE_3 ON PARA_CVE_3.CODICE = 'CVE'+SUBSTRING(U_CLI_AN.CLI_CANVEN,1,9)
		LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION
		LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+U_CLI_AN.CLI_ZONA
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'D' AND RIGHE_PART.PAR_TIPODO = 'FAT')
		AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAT_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))
		AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)
	ORDER BY RIGHE_PART.PAR_DTFAT,RIGHE_PART.PAR_NPROT,TEST_PART.PAR_DTSCAD DESC
	
ENDTEXT					&& FINE SCRITTURA QUERY           

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF


SELECT CU_SCADENZE
GO TOP

_PDF_REPORT_ 		=ALLTRIM(CERCAREPO("XXX","FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO","FATTURE_DA_SALDARE_O_SALDATE_ULTIMO_ANNO.FRX"))
_PDF_DESCRIZIONE_	= V_TITOLO+_PROGRESSIVO_PROGRAMMA 
_PDF_SELECT_ 		= "CU_SCADENZE"

IF !EMPTY(_PDF_SUBDIR_ )
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_ )
ELSE
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
ENDIF

_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 

_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
	
