**********************************************************************************************
**********************************************************************************************
***         PROJECT SRL - LIBRERIA DEI METODI DELLE VARIE FORM                          ****** 
***                                                                                     
**********************************************************************************************
**********************************************************************************************

**********************************************************************************************
*
* procedura primanot con i metodi presenti nella form primanot                          ******
*
**********************************************************************************************
PROCEDURE PRIMANOT
**********************************************************************************************
PARAMETERS _metodo

DO CASE  

	CASE UPPER(_metodo) = "LOAD"

		* #############################################################################
		IF !LICENZA_SOFTWARE()	&& VERIFICA DINAMICA DEL CONTRATTO DI LICENZA SOFTWARE
			RETURN .F.
		ENDIF
		* #############################################################################


		RELEASE PUB_DESBLOCCOPN
		PUBLIC PUB_DESBLOCCOPN
		PUB_DESBLOCCOPN = ""



		IF !PUB_RICPN
		
			***************************************************************************
			__CODICE_DA_RICERCARE	= "100"		&& INIZIO AGGIORNAMENTO PRIMA NOTA
			__VALORE_DA_AGGIORNARE	= "SI"
			=AGGIORNA_ELABORAZIONI_CONTABILI(__CODICE_DA_RICERCARE,__VALORE_DA_AGGIORNARE)
			***************************************************************************

		ENDIF
		

		************************** RILASCIO VARIABILI PUBBLICHE *********************
        
        RELEASE FATVENSOSIVA__	&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA
      
        
        RELEASE SAVE_NPROT
        RELEASE _INTRA_
		RELEASE  SAVE_DATASCAD   		&& SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA

        RELEASE MODIFICA_CONDIZIONI_PAGAMENTO
        RELEASE CODICE_FORNITORE_CONTROLLO_DDT_FATTURE,CODICE_CPA_FORNITORE_CONTROLLO_DDT_FATTURE  
        
        RELEASE _INTRASTAT_ACQUISTO_CESSIONE_DA_CONTROLLARE
		RELEASE OK_EFFETTI
		RELEASE M.EFF_DATASCAD
		RELEASE M.EFF_NUMATRI 
		RELEASE M.EFF_EFFETDA 
		RELEASE M.EFF_INTEPER 
		RELEASE M.EFF_NOTEFF
		
	    RELEASE OK_CERCAPAIN
	    RELEASE M.STATO_CEE
	    RELEASE _REGISTRAZIONE_CESPITE 
	    RELEASE M.CODCES,M.DESCCODCES
	    RELEASE IVA_ACQ_ESE
		RELEASE REGISTRAZIONE_INTRA
	    RELEASE ___RIPARTIZIONEGIAVERIFICATA
		RELEASE _FLAG_TIPO_ICONA 
		RELEASE _SFONDO_PNO
		RELEASE _MESE_IVA_CHIUSO
		RELEASE NUMERO_COMMESSA_NON_ATTRIBUITO_A_RIGA_PRIMA_NOTA
		RELEASE MOSTRA_MESSAGGIO_COMMESSA_RISORSA
		RELEASE NOCOMME
		RELEASE PUB_CONTROLLO_QUADRATURA_CENTRI_DI_COSTO 
		RELEASE NUCOM
		RELEASE NPROT_INSOLUTO 
		RELEASE __STO_INSERENDO_UN_INSOLUTO_A_FRONTE_DI_PIU_FATTURE_CLIENTI
		RELEASE __ESISTE_ALMENO_UN_BLOCCO_SU_SINGOLA_SCADENZA 
		RELEASE	IMPORTO_CENTRO_COSTO,WSYSCCO,HO_MODIFICATO_UNA_RIGA_DI_PN
		RELEASE	CENTRO_DI_COSTO_DIGITATO
		RELEASE	VERIFICA_CENTRI_DI_COSTO_INSERITI 
		RELEASE CONTRCCO  
		RELEASE TASTO_F7_ATTIVO
		RELEASE M.DESCCOS
		RELEASE ____STO_GESTENDO_UN_DOC_EXTRACONTABILE            
		RELEASE CREAPART            
        RELEASE COMPENSAZIONE_CLIENTE_FORNITORE         
        RELEASE NOTACREDITO         
        RELEASE pincamulti
        RELEASE M.SALDO_CONTO
        RELEASE ____CONTIENEMATERIALEPUBBLICITARIO	
		RELEASE CANT,NDOC,noquadra,M.IVAOMA,CALCIMPOS  
        RELEASE ____NOMENCLATURA_CONTO_ESATTA 
		RELEASE M.T_DARE_AVERE
		RELEASE ____DARE,____AVERE
		RELEASE ____ESISTE_ALMENO_UN_CONTO_AMMORTIZZABILE
		RELEASE ____CODCLI
		RELEASE ____RAGSOC
		RELEASE ____INDIRI
		RELEASE ____CAP
		RELEASE ____LOCALI
		RELEASE ____PARIVA
		RELEASE ____TOP
		RELEASE ____CPA
		RELEASE ____BANCA
		RELEASE ____CODNAZ
		RELEASE ____DATADOC
		RELEASE ____DATASCAD
		RELEASE _NUCESP

		RELEASE  M.___xanomax
		RELEASE  x_TIPOCONTO 
        RELEASE  _NPARF
        RELEASE  _NREG_
        RELEASE  _NPROT_


		RELEASE  M.___COSATRATTA 
		RELEASE  M.___GRADOIMPORTANZA 
		RELEASE  M.___FORMAPAGAMENTO 
		RELEASE  M.___TIPOCONTRATTO 
		RELEASE  M.___CODACQ 
		RELEASE  M.___PRIPAGA 

		RELEASE  ___COSATRATTA 
		RELEASE  ___GRADOIMPORTANZA 
		RELEASE  ___FORMAPAGAMENTO 
		RELEASE  ___TIPOCONTRATTO 
		RELEASE  ___CODACQ 
		RELEASE  ___PRIPAGA 

		RELEASE ___DESCOSATRATTA 		
		RELEASE ___DESGRADOIMPORTANZA 	
		RELEASE ___DESFORMAPAGAMENTO 	
		RELEASE ___DESTIPOCONTRATTO 		
		RELEASE ___DESACQ				
		RELEASE ___DESPRI				
		
		RELEASE BOLLATOIVA,__BOLLATOIVA,XXX_BOLLATOIVA	  
		RELEASE V_CAMBIA_IMPORTI_IN_LISTA,OK_CAMBIA_IMPORTI_IN_LISTA,_determina_se_cliente_fornitore
		RELEASE OK_CERCA_PAGAMENTI,V_CERCA_PAGAMENTI,__IDUNIQUE,PUB_NPART_ORIGINALE,OK_QUADRA_SCADENZE
		RELEASE CONTO
		RELEASE NOTE
		RELEASE BANCA,__CEE
		PUBLIC  BANCA,__CEE
		RELEASE XVALUTA,XDATAVAL,XCAMBIO,XX_XVALUTA,XX_XDATAVAL,XX_XCAMBIO,XANOMAX
		RELEASE GUARDA
		RELEASE IV
		RELEASE M.DARE
		RELEASE M.AVERE
		RELEASE DARE
		RELEASE AVERE
		RELEASE DOVE_SONO,PUNTATORE
		RELEASE X_CONTOP
		RELEASE PUB_OK,RECX,M.NOTE,M.SOLOIVA,M.CONTO
		RELEASE REC_COR    && USATO PER I CENTRI DI COSTO (IN MODIFICA LISTA)
		RELEASE CCOD01,CCOD02,CCOD03,CCOD04,CCOD05,VDE
		RELEASE TCOD01,TCOD02,TCOD03,TCOD04
		RELEASE WCOD01,WCOD02,WCOD03,WCOD04,WCOD05,WCOD06,WCOD07,WCOD08,WCOD09,WCOD10,NUM_INT
		RELEASE XCCLI,XCFOR
		RELEASE NOTE
		RELEASE M.COD01,M.DESCR01,M.SALDO01
		RELEASE M.COD02,M.DESCR02,M.SALDO02
		RELEASE M.COD03,M.DESCR03,M.SALDO03
		RELEASE M.COD04,M.DESCR04,M.SALDO04
		RELEASE M.COD05,M.DESCR05,M.SALDO05
		RELEASE M.COD06,M.DESCR06,M.SALDO06
		RELEASE M.COD07,M.DESCR07,M.SALDO07
		RELEASE M.COD08,M.DESCR08,M.SALDO08
		RELEASE M.COD09,M.DESCR09,M.SALDO09
		RELEASE M.COD10,M.DESCR10,M.SALDO10
		RELEASE M.PERC1,M.PERC2,M.PERC3,M.PERC4,M.PERC5,M.PERC6,M.PERC7,M.PERC8,M.PERC9,M.PERC10	
		RELEASE PAR_CF,CCO,DESCCO,CECOS
		RELEASE XXX_TIPODO,XXX_NPROG,XXX_DATPAG,XXX_NREG,XXX_DATSCA,F_CPA
		RELEASE V_FR,TP,M.CECO,V_BF
		RELEASE M.DESCRIC,M.IMPOSTA,DARE,AVERE,M.T_DARE,M.T_AVERE,CONTROLLO
		RELEASE M.N_CONTO,M.NDESCRI,MODIFY,TP,ACCODA,NPART,NPROT,DESPAG
		RELEASE M.DOCU,NATURA,VERO,TOPX,NREG,PN_C,NATURA,OK_QUADRA,CON,CONIVAX
		RELEASE DA,AV,V_CONPAG,DATADOC,FATTURA,VER_CONTO,X_NREG,X_NPROT,AGGANCIAPARTITARI
		RELEASE DTREG
		RELEASE NUM_REC,M.CODICE3
		RELEASE XXTIPOCO
		
		RELEASE M.PESO,M.TISPE,M.PORTO,M.CLDOG
		RELEASE M.SERV_INTRA			 	
		RELEASE M.IMPEUR_INTRA			
		RELEASE M.IMPVAL_INTRA			
		RELEASE M.IMPSTAT_INTRA			
		RELEASE M.STATO_INTRA_PROV		
		RELEASE M.PARTITA_IVA_INTRA		
		RELEASE M.QTA_INTRA	
		RELEASE M.UNITA_SUPPL_INTRA			
		RELEASE M.COND_CONS_INTRA			
		RELEASE M.MEZZI_TRASP_INTRA		
		RELEASE M.NAZIONE_INTRA			
		RELEASE M.PROVIN_DESTI_INTRA	
			
		RELEASE M.DESCRIZ,M.DESCRI1
		RELEASE TPROC

		************************** DEFINIZIONE VARIABILI PUBBLICHE ******************


		PUBLIC FATVENSOSIVA__	&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA
		        
        PUBLIC SAVE_NPROT  
        PUBLIC _INTRA_
 		PUBLIC  SAVE_DATASCAD   		&& SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA
 
        PUBLIC MODIFICA_CONDIZIONI_PAGAMENTO        
        PUBLIC CODICE_FORNITORE_CONTROLLO_DDT_FATTURE,CODICE_CPA_FORNITORE_CONTROLLO_DDT_FATTURE  
                 
        PUBLIC _INTRASTAT_ACQUISTO_CESSIONE_DA_CONTROLLARE
		PUBLIC OK_EFFETTI
		PUBLIC M.EFF_DATASCAD
		PUBLIC M.EFF_NUMATRI
		PUBLIC M.EFF_EFFETDA 
		PUBLIC M.EFF_INTEPER 
		PUBLIC M.EFF_NOTEFF	
		
		PUBLIC OK_CERCAPAIN
	    PUBLIC M.STATO_CEE		
		PUBLIC _REGISTRAZIONE_CESPITE 
		PUBLIC M.CODCES,M.DESCCODCES
		PUBLIC IVA_ACQ_ESE
		PUBLIC REGISTRAZIONE_INTRA
		PUBLIC ___RIPARTIZIONEGIAVERIFICATA
		PUBLIC _FLAG_TIPO_ICONA
		PUBLIC _SFONDO_PNO
		PUBLIC _MESE_IVA_CHIUSO 
		PUBLIC NUMERO_COMMESSA_NON_ATTRIBUITO_A_RIGA_PRIMA_NOTA
		PUBLIC MOSTRA_MESSAGGIO_COMMESSA_RISORSA
		PUBLIC NOCOMME
		PUBLIC PUB_CONTROLLO_QUADRATURA_CENTRI_DI_COSTO 
		PUBLIC NUCOM
		PUBLIC NPROT_INSOLUTO 
		PUBLIC __STO_INSERENDO_UN_INSOLUTO_A_FRONTE_DI_PIU_FATTURE_CLIENTI
	
		PUBLIC __ESISTE_ALMENO_UN_BLOCCO_SU_SINGOLA_SCADENZA
		PUBLIC IMPORTO_CENTRO_COSTO,WSYSCCO,HO_MODIFICATO_UNA_RIGA_DI_PN
		PUBLIC CENTRO_DI_COSTO_DIGITATO
	    PUBLIC VERIFICA_CENTRI_DI_COSTO_INSERITI 
		PUBLIC CONTRCCO  
		PUBLIC TASTO_F7_ATTIVO
		PUBLIC M.DESCCOS 
		PUBLIC ____STO_GESTENDO_UN_DOC_EXTRACONTABILE
		PUBLIC CREAPART            
        PUBLIC COMPENSAZIONE_CLIENTE_FORNITORE        
        PUBLIC NOTACREDITO         
        PUBLIC pincamulti
        PUBLIC M.SALDO_CONTO
        PUBLIC ____CONTIENEMATERIALEPUBBLICITARIO		
		PUBLIC CANT,NDOC,noquadra,M.IVAOMA,CALCIMPOS      
        PUBLIC ____NOMENCLATURA_CONTO_ESATTA 
		PUBLIC M.T_DARE_AVERE
		PUBLIC ____DARE,____AVERE
		PUBLIC ____ESISTE_ALMENO_UN_CONTO_AMMORTIZZABILE
		PUBLIC ____CODCLI
		PUBLIC ____RAGSOC
		PUBLIC ____INDIRI
		PUBLIC ____CAP
		PUBLIC ____LOCALI
		PUBLIC ____PARIVA
		PUBLIC ____TOP
		PUBLIC ____CPA
		PUBLIC ____BANCA
		PUBLIC ____CODNAZ
		PUBLIC ____DATADOC
		PUBLIC ____DATASCAD
		PUBLIC _NUCESP

		PUBLIC  M.___xanomax
		PUBLIC  x_TIPOCONTO 
        PUBLIC   _NPARF
        PUBLIC  _NREG_
        PUBLIC  _NPROT_

		PUBLIC  M.___COSATRATTA 
		PUBLIC  M.___GRADOIMPORTANZA 
		PUBLIC  M.___FORMAPAGAMENTO 
		PUBLIC  M.___TIPOCONTRATTO 
		PUBLIC  M.___CODACQ 
		PUBLIC  M.___PRIPAGA 


		PUBLIC   ___COSATRATTA 
		PUBLIC   ___GRADOIMPORTANZA 
		PUBLIC   ___FORMAPAGAMENTO 
		PUBLIC   ___TIPOCONTRATTO 
		PUBLIC   ___CODACQ 
		PUBLIC   ___PRIPAGA

		PUBLIC ___DESCOSATRATTA 		
		PUBLIC ___DESGRADOIMPORTANZA 	
		PUBLIC ___DESFORMAPAGAMENTO 	
		PUBLIC ___DESTIPOCONTRATTO 		
		PUBLIC ___DESACQ				
		PUBLIC ___DESPRI				

		
		
		
		PUBLIC BOLLATOIVA,__BOLLATOIVA,XXX_BOLLATOIVA	  
		PUBLIC V_CAMBIA_IMPORTI_IN_LISTA,OK_CAMBIA_IMPORTI_IN_LISTA,_determina_se_cliente_fornitore
		PUBLIC OK_CERCA_PAGAMENTI,V_CERCA_PAGAMENTI,__IDUNIQUE,PUB_NPART_ORIGINALE,OK_QUADRA_SCADENZE
		PUBLIC XVALUTA,XDATAVAL,XCAMBIO,XX_XVALUTA,XX_XDATAVAL,XX_XCAMBIO,XANOMAX
		PUBLIC GUARDA
		PUBLIC IV
		PUBLIC M.CONTO
		PUBLIC M.DARE
		PUBLIC M.AVERE
		PUBLIC DARE
		PUBLIC AVERE
		PUBLIC DOVE_SONO,PUNTATORE
		PUBLIC X_CONTOP
		PUBLIC PUB_OK,RECX,M.NOTE,M.SOLOIVA
		PUBLIC REC_COR    && USATO PER I CENTRI DI COSTO (IN MODIFICA LISTA)
		PUBLIC CCOD01,CCOD02,CCOD03,CCOD04,CCOD05,VDE
		PUBLIC TCOD01,TCOD02,TCOD03,TCOD04
		PUBLIC WCOD01,WCOD02,WCOD03,WCOD04,WCOD05,WCOD06,WCOD07,WCOD08,WCOD09,WCOD10,NUM_INT
		PUBLIC XCCLI,XCFOR
		PUBLIC NOTE
		PUBLIC M.COD01,M.DESCR01,M.SALDO01
		PUBLIC M.COD02,M.DESCR02,M.SALDO02
		PUBLIC M.COD03,M.DESCR03,M.SALDO03
		PUBLIC M.COD04,M.DESCR04,M.SALDO04
		PUBLIC M.COD05,M.DESCR05,M.SALDO05
		PUBLIC M.COD06,M.DESCR06,M.SALDO06
		PUBLIC M.COD07,M.DESCR07,M.SALDO07
		PUBLIC M.COD08,M.DESCR08,M.SALDO08
		PUBLIC M.COD09,M.DESCR09,M.SALDO09
		PUBLIC M.COD10,M.DESCR10,M.SALDO10
		PUBLIC M.PERC1,M.PERC2,M.PERC3,M.PERC4,M.PERC5,M.PERC6,M.PERC7,M.PERC8,M.PERC9,M.PERC10		
		PUBLIC PAR_CF,CCO,DESCCO,CECOS,DES
		PUBLIC XXX_TIPODO,XXX_NPROG,XXX_DATPAG,XXX_NREG,XXX_DATSCA,F_CPA
		PUBLIC V_FR,TP,M.CECO,V_BF
		PUBLIC M.DESCRIC,M.IMPOSTA,DARE,AVERE,M.T_DARE,M.T_AVERE,CONTROLLO
		PUBLIC M.N_CONTO,M.NDESCRI,MODIFY,TP,ACCODA,NPART,NPROT,DESPAG
		PUBLIC M.DOCU,NATURA,VERO,TOPX,NREG,PN_C,NATURA,OK_QUADRA,CON,CONIVAX
		PUBLIC DA,AV,V_CONPAG,DATADOC,FATTURA,VER_CONTO,X_NREG,X_NPROT,AGGANCIAPARTITARI

		PUBLIC SAVE_VET_DAL[2],SAVE_VET_AL[2],SAVE_VET_DAY[2],DTREG
		
		PUBLIC VET_DAL[2],VET_AL[2],VET_DAY[2],DTREG
		PUBLIC NUM_REC,M.CODICE3
		PUBLIC XXTIPOCO
		
		PUBLIC M.PESO,M.TISPE,M.PORTO,M.CLDOG
		PUBLIC M.SERV_INTRA			 	
		PUBLIC M.IMPEUR_INTRA			
		PUBLIC M.IMPVAL_INTRA			
		PUBLIC M.IMPSTAT_INTRA			
		PUBLIC M.STATO_INTRA_PROV		
		PUBLIC M.PARTITA_IVA_INTRA		
		PUBLIC M.QTA_INTRA
		PUBLIC M.UNITA_SUPPL_INTRA				
		PUBLIC M.COND_CONS_INTRA			
		PUBLIC M.MEZZI_TRASP_INTRA		
		PUBLIC M.NAZIONE_INTRA			
		PUBLIC M.PROVIN_DESTI_INTRA		
		
		PUBLIC M.DESCRIZ,M.DESCRI1
		PUBLIC TPROC


		FATVENSOSIVA__	= "" 	&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA


        SAVE_NPROT = ""  
        _INTRA_ = ""
		SAVE_DATASCAD = ""		&& SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA

        MODIFICA_CONDIZIONI_PAGAMENTO = .F.
		CODICE_FORNITORE_CONTROLLO_DDT_FATTURE = ""
		CODICE_CPA_FORNITORE_CONTROLLO_DDT_FATTURE = ""
		
        _INTRASTAT_ACQUISTO_CESSIONE_DA_CONTROLLARE = .F.
		OK_EFFETTI     = ""
		M.EFF_DATASCAD = ""
		M.EFF_NUMATRI  = 0
		M.EFF_EFFETDA  = ""
		M.EFF_INTEPER  = ""
		M.EFF_NOTEFF   = ""	

        OK_CERCAPAIN = ""
	    M.STATO_CEE = ""
        _REGISTRAZIONE_CESPITE = .F.
        M.CODCES = ""
        M.DESCCODCES = ""
        IVA_ACQ_ESE = ""
		REGISTRAZIONE_INTRA = .F.
		___RIPARTIZIONEGIAVERIFICATA = .F.	&& FLAG PER VERIFICARE SE L'UTENTE HA VERIFICATO LA RIPARTIZIONE DEI CENTRI CONTABILI CON APPOSITO FORM : SERGIO
		_FLAG_TIPO_ICONA = "STANDARD"				&& STANDARD / WIN-8
        _SFONDO_PNO = "C:\AQUARIUS\NUVOLE.BMP"		&& SFONDO PRIMA NOTA PREDEFINITO
		_MESE_IVA_CHIUSO = .F.
		NUMERO_COMMESSA_NON_ATTRIBUITO_A_RIGA_PRIMA_NOTA = .T.
		MOSTRA_MESSAGGIO_COMMESSA_RISORSA = .F.
		NOCOMME= ''
		PUB_CONTROLLO_QUADRATURA_CENTRI_DI_COSTO = .F.
		NUCOM = ""
		NPROT_INSOLUTO = ''
		__STO_INSERENDO_UN_INSOLUTO_A_FRONTE_DI_PIU_FATTURE_CLIENTI = .F.

		__ESISTE_ALMENO_UN_BLOCCO_SU_SINGOLA_SCADENZA = .F.
        HO_MODIFICATO_UNA_RIGA_DI_PN = .T.
        WSYSCCO = ""
		IMPORTO_CENTRO_COSTO = 0
		CENTRO_DI_COSTO_DIGITATO	= ""
		VERIFICA_CENTRI_DI_COSTO_INSERITI = .T.
		CONTRCCO  = " "
		  
		TASTO_F7_ATTIVO = .F.
		M.DESCCOS = ""
		____STO_GESTENDO_UN_DOC_EXTRACONTABILE = .F.
		CREAPART      = " "
        COMPENSAZIONE_CLIENTE_FORNITORE = .F.
        NOTACREDITO   = ""
        pincamulti    = ""
        M.SALDO_CONTO = 0

        ____CONTIENEMATERIALEPUBBLICITARIO			= .F.
           
        CALCIMPOS   = SPACE(01)
		CANT    	= SPACE(01)
		NDOC    	= SPACE(06)
		noquadra    = SPACE(01)
		M.IVAOMA    = 0
		
		____NOMENCLATURA_CONTO_ESATTA = .F.
		M.T_DARE_AVERE	= 0
		____DARE	= 0
		____AVERE	= 0
		____ESISTE_ALMENO_UN_CONTO_AMMORTIZZABILE = .F.
		____CODCLI  = SPACE(10)
		____RAGSOC  = SPACE(30)
		____INDIRI  = SPACE(30)
		____CAP		= SPACE(05)
		____LOCALI  = SPACE(30)
		____PARIVA  = SPACE(11)
		____TOP     = SPACE(03)
		____CPA     = SPACE(03)
		____BANCA   = SPACE(05)
		____CODNAZ  = SPACE(03)
		____datadoc = SPACE(10)
		____DATASCAD= SPACE(10)		
		_NUCESP		= 0
		
		
		M.___xanomax			= SPACE(3)
		_NPARF					= SPACE(10)
		_NREG_					= SPACE(10)
        _NPROT_					= SPACE(10)
		___COSATRATTA 			= SPACE(05)
		___GRADOIMPORTANZA 		= SPACE(05)
		___FORMAPAGAMENTO 		= SPACE(05)	
		___TIPOCONTRATTO 		= SPACE(05)
		___CODACQ				= SPACE(03) 
		___PRIPAGA				= SPACE(04) 

		___DESCOSATRATTA 		= SPACE(05)
		___DESGRADOIMPORTANZA 	= SPACE(05)
		___DESFORMAPAGAMENTO 	= SPACE(05)	
		___DESTIPOCONTRATTO 	= SPACE(05)
		___DESACQ				= SPACE(03) 
		___DESPRI				= SPACE(04) 


		V_CAMBIA_IMPORTI_IN_LISTA=.F.
		OK_CAMBIA_IMPORTI_IN_LISTA=.F.
		
		OK_QUADRA_SCADENZE=.F.
		OK_CERCA_PAGAMENTI = .F.
		V_CERCA_PAGAMENTI = .F.

		__IDUNIQUE = 0
		PUB_NPART_ORIGINALE = 0
		
		M.CONTO   = SPACE(13)
		M.CECO    = SPACE(13)
		M.DESCRIZ = " "
		M.DESCRI1 = " "
		BANCA     = SPACE(05)
		__CEE     = SPACE(01)
		RELEASE CODSYS,CODGRU,CODCCO
		PUBLIC  CODSYS,CODGRU,CODCCO
		CODSYS = SPACE(10)
		CODGRU = SPACE(10)
		CODCCO = SPACE(13)
		RELEASE NO_AUT,PR_NO,PR_SI,PR_TOP,PR_ANA,PR_LAN,PR_LIS,TOP_COL,IL_CCO,IN_CCO
		PUBLIC  NO_AUT,PR_NO,PR_SI,PR_TOP,PR_ANA,PR_LAN,PR_LIS,TOP_COL,IL_CCO,IN_CCO
		NO_AUT  = SPACE(01)
		PR_NO   = SPACE(01) 
		PR_SI   = SPACE(01) 
		PR_TOP  = SPACE(01) 
		PR_ANA  = SPACE(01) 
		PR_LAN  = SPACE(01) 
		PR_LIS  = SPACE(01) 
		TOP_COL = SPACE(03) 
		IL_CCO  = SPACE(01) 
		IN_CCO  = SPACE(01) 

		************************** ULTERIORE CONTROLLO CONTABILE ********************
        v_seek	 = 'ANN'+PUB_CODSOC+PUB_ANNO
        v_chiave = "codice"
        IF seek_std('para',v_seek,v_chiave,'CUR_PARA')
           SELECT CUR_PARA
 	       IF SUBSTR(LIBERA,1,6)=='APERTO'
	       ELSE
		      PUB_ERRORE=MESSAGEBOX('Esercizio contabile :'+PUB_ANNO+CHR(13)+'non aperto',16,'*** ATTENZIONE ***') 
		      RETURN .F.
	       ENDIF 
	    ELSE
	    	PUB_ERRORE=MESSAGEBOX('Anno contabile :'+PUB_ANNO+CHR(13)+'inesistente',16,'*** ATTENZIONE ***') 
	     	RETURN .F.
	  	ENDIF

		************************** VALORIZZA VALUTA DI RIFERIMENTO  ********************
		XDATAVAL = ""
		XCAMBIO  = 1
		XVALUTA  = PUB_VALRIF

		XANOMAX     = SPACE(03)
		GUARDA       = .F.
		X_CONTOP     = SPACE(13)
		DOVE_SONO    = 0
		PUNTATORE    = 0
		M.DARE       = 0
		M.AVERE      = 0
		DARE         = 0
		AVERE        = 0
		PUB_MODIFICA = .F.
		PUB_CANCELLA = .F.
		PUB_BLOCCA   = .T.
		RECX         = 0
		M.NOTE       = SPACE(1)
		M.SOLOIVA    = 0
		REC_COR      = 0
		VDE          = SPACE(20)
		XCCLI        = SPACE(10)
		XCFOR        = SPACE(10)
		PUB_OK       = .F.   && VERIFICA SE EFFETTIVAMENTE AGGIORNA GLI ARCHIVI
		M.COD01      = SPACE(13)
		M.COD02      = SPACE(13)
		M.COD03      = SPACE(13)
		M.COD04      = SPACE(13)
		M.COD05      = SPACE(13)
		M.COD06      = SPACE(13)
		M.COD07      = SPACE(13)
		M.COD08      = SPACE(13)
		M.COD09      = SPACE(13)
		M.COD10      = SPACE(13)
		M.DESCR01    = SPACE(13)
		M.DESCR02    = SPACE(13)
		M.DESCR03    = SPACE(13)
		M.DESCR04    = SPACE(13)
		M.DESCR05    = SPACE(13)
		M.DESCR06    = SPACE(13)
		M.DESCR07    = SPACE(13)
		M.DESCR08    = SPACE(13)
		M.DESCR09    = SPACE(13)
		M.DESCR10    = SPACE(13)
		M.PERC1		 = 0
		M.PERC2		 = 0
		M.PERC3		 = 0
		M.PERC4		 = 0
		M.PERC5		 = 0
		M.PERC6		 = 0
		M.PERC7		 = 0
		M.PERC8		 = 0
		M.PERC9		 = 0
		M.PERC10	 = 0
		NUM_INT      = SPACE(13)
		WCOD01       = SPACE(13)
		WCOD02       = SPACE(13)
		WCOD03       = SPACE(13)
		WCOD04       = SPACE(13)
		WCOD05       = SPACE(13)
		WCOD06       = SPACE(13)
		WCOD07       = SPACE(13)
		WCOD08       = SPACE(13)
		WCOD09       = SPACE(13)
		WCOD10       = SPACE(13)
		CCOD01       = SPACE(13)
		CCOD02       = SPACE(13)
		CCOD03       = SPACE(13)
		CCOD04       = SPACE(13)
		CCOD05       = SPACE(13)
		TCOD01       = SPACE(13)
		TCOD02       = SPACE(13)
		TCOD03       = SPACE(13)
		TCOD04       = SPACE(13)
		M.SALDO01    = 0
		M.SALDO02    = 0
		M.SALDO03    = 0
		M.SALDO04    = 0
		M.SALDO05    = 0
		M.SALDO06    = 0
		M.SALDO07    = 0
		M.SALDO08    = 0
		M.SALDO09    = 0
		M.SALDO10    = 0
		
		M.PESO	     			= 0
		M.TISPE      			= SPACE(03)
		M.PORTO      			= SPACE(03)
		M.CLDOG      			= SPACE(16)
		M.SERV_INTRA			= SPACE(10)			 	
		M.IMPEUR_INTRA			= 0			
		M.IMPVAL_INTRA			= 0			
		M.IMPSTAT_INTRA			= 0			
		M.STATO_INTRA_PROV		= SPACE(02)		
		M.PARTITA_IVA_INTRA		= SPACE(12)		
		M.QTA_INTRA				= 0		
		M.UNITA_SUPPL_INTRA		= 0	
		M.COND_CONS_INTRA		= SPACE(01)			
		M.MEZZI_TRASP_INTRA		= SPACE(01)		
		M.NAZIONE_INTRA			= SPACE(03)		
		M.PROVIN_DESTI_INTRA	= SPACE(02)				
		
		
		
		CECOS        = SPACE(13)
		CCO          = SPACE(13)
		DESCCO       = SPACE(20)
		PAR_CF       = 0
		DES          = ""

		******************************** GESTIONE DATA DI REGISTRAZIONE ***********************
		
		RELEASE DATAREG
		PUBLIC DATAREG
		DATAREG      = SPACE(10)

		IF EMPTY(DATAREG)
	    	DATAREG=DTOC(DATE())
		ENDIF  

		NUM_REC      = 0
		M.CODICE3    = SPACE(13)
		M.IMPOSTA    = 0   
		DESPAG       = SPACE(30)
		VET_DAL[1]   = "0000"      
		VET_DAL[2]   = "0000"
		VET_AL[1]    = "0000"
		VET_AL[2]    = "0000" 
		VET_DAY[1]   = "0000" 
		VET_DAY[2]   = "0000"
		
		SAVE_VET_DAL[1]   = "0000"      
		SAVE_VET_DAL[2]   = "0000"
		SAVE_VET_AL[1]    = "0000"
		SAVE_VET_AL[2]    = "0000" 
		SAVE_VET_DAY[1]   = "0000" 
		SAVE_VET_DAY[2]   = "0000"
		
		
		F_CPA        = .F.
		V_FR         = .F.  
		V_BF         = .F.
		TP           = " " 
		XXX_TIPODO   = SPACE(03)
		XXX_DATPAG   = SPACE(10) 
		XXX_NPROG    = 0
		XXX_NREG     = SPACE(10)
		XXX_DATSCA   = SPACE(10)
		XX_XVALUTA   = SPACE(3)
		XX_XDATAVAL  = SPACE(10)
		XX_XCAMBIO   = 0
		DTREG        = SPACE(10)  
		X_NREG       = SPACE(6)
		X_NPROT      = SPACE(10)
		VER_CONTO    = SPACE(1)
		DATADOC      = SPACE(10)  
		FATTURA      = SPACE(1) 
		AGGANCIAPARTITARI = SPACE(01)
		DA           = 0
		AV           = 0
		CONIVAX      = SPACE(10)
		V_CONPAG     = SPACE(03)
		CON          = SPACE(13)
		OK_QUADRA    = .F.
		NATURA       = SPACE(01)
		NPROT        = SPACE(6)
		PN_C         = SPACE(6)
		TOPX         = SPACE(03)
		VERO         = .F.
		NATURA       = SPACE(1)
		TOTDOCU      = 0
		NPART        = 0
		ACCODA       = .T.
		TP           = SPACE(1)
		TPROC        = SPACE(3)
		MODIFY       = .F.
		M.N_CONTO    = SPACE(20)
		M.N_DESCRI   = SPACE(40)
		CPA          = SPACE(03)
		DESPAG       = SPACE(30)
		DATASCAD     = SPACE(10)
		BANCA        = SPACE(05)

		IF PUB_VOLTE = 0     && VARIABILE INIZIALIZZATA IN BEG... PRIMO PGM
		   PUB_VOLTE = 1     && VARIABILE INIZIALIZZATA IN BEG... PRIMO PGM
		   M.IMPOSTA = 0
		ENDIF
			
		DES          = SPACE(40) 
		M.DARE       = 0
		M.AVERE      = 0
		M.T_DARE     = 0
		M.T_AVERE    = 0
		M.T_IMPOSTA  = 0
		M.DESCRIC    = SPACE(25)
		NREG         = SPACE(10)
		M.TOP        = ""
		TPROC        = SPACE(3)


		IF (PUB_VARPN=.T.) .OR. (PUB_ANNPN=.T.) .OR. (PUB_RICPN=.T.)
		ELSE
			CREATE CURSOR CORPO_SCA ;
			       (SCA_DATSCA C(10), SCA_VALSCA N(17,3), SCA_ANOMAX C(3))
			INDEX ON RIBALTA2(SCA_DATSCA) 				  TAG I_SCADE1 ADDITIVE

			CREATE CURSOR SAVE_CORPO_SCA ;
			       (SCA_DATSCA C(10), SCA_VALSCA N(17,3), SCA_ANOMAX C(3))
			INDEX ON RIBALTA2(SCA_DATSCA) 				  TAG I_SCADE1 ADDITIVE
		ENDIF


		* CASO IN CUI PASSO DA PRIMA NOTA A ALTRE VIDEATE (PERDO CORPO_MOV)
		IF !USED('CORPO_MOV')       && SE E' GIA' STATO CREATO NON LO RICREA
		   =DEF_CGE()
		ENDIF


		IF ALLTRIM(PUB_TIPOGE)  = "PREVISIONALE"
              
				DO CASE
				   CASE PUB_VARPN
				        PUB_DESBAR="VARIAZIONE PRIMA NOTA PREVISIONALE " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_RICPN
				        PUB_DESBAR="RICERCA PRIMA NOTA PREVISIONALE " && ANNO CONTABILE : "+PUB_ANNO   
				   CASE PUB_ANNPN  
				        PUB_DESBAR="ANNULLO PRIMA NOTA PREVISIONALE " && ANNO CONTABILE : "+PUB_ANNO   
				   OTHERWISE
				        PUB_DESBAR="INSERIMENTO PRIMA NOTA PREVISIONALE " && ANNO CONTABILE : "+PUB_ANNO
				ENDCASE
				IF PUB_RICPN
				   PUB_DESBAR="RICERCA PRIMA NOTA PREVISIONALE " && ANNO CONTABILE : "+PUB_ANNO   
				ENDIF

		ELSE

				DO CASE
				   CASE PUB_VARPN
				        PUB_DESBAR="VARIAZIONE PRIMA NOTA " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_RICPN
				        PUB_DESBAR="RICERCA PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO   
				   CASE PUB_ANNPN  
				        PUB_DESBAR="ANNULLO PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO   
				   OTHERWISE
				        PUB_DESBAR="INSERIMENTO PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO
				ENDCASE
				IF PUB_RICPN
				   PUB_DESBAR="RICERCA PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO   
				ENDIF

		ENDIF


		IF PUB_BLOCCA_SBLOCCA_PREVISIONALE="SIEFFETTIVA"

				DO CASE
				   CASE PUB_VARPN
				        PUB_DESBAR="VARIAZIONE PRIMA NOTA DA PREVISIONALE A EFFETTIVA " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_RICPN
				        PUB_DESBAR="RICERCA PRIMA NOTA DA PREVISIONALE A EFFETTIVA " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_ANNPN  
				        PUB_DESBAR="ANNULLO PRIMA NOTA DA PREVISIONALE A EFFETTIVA " && ANNO CONTABILE :"+PUB_ANNO  
				   OTHERWISE
				        PUB_DESBAR="INSERIMENTO PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO
				ENDCASE
				IF PUB_RICPN
				   PUB_DESBAR="RICERCA PRIMA NOTA DA PREVISIONALE " && ANNO CONTABILE : "+PUB_ANNO   
				ENDIF


        ENDIF
		IF PUB_BLOCCA_SBLOCCA_PREVISIONALE="SIPREVISIONALE"


				DO CASE
				   CASE PUB_VARPN
				        PUB_DESBAR="VARIAZIONE PRIMA NOTA DA EFFETTIVA A PREVISIONALE " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_RICPN
				        PUB_DESBAR="RICERCA PRIMA NOTA DA EFFETTIVA A PREVISIONALE " && ANNO CONTABILE :"+PUB_ANNO  
				   CASE PUB_ANNPN  
				        PUB_DESBAR="ANNULLO PRIMA NOTA DA EFFETTIVA A PREVISIONALE " && ANNO CONTABILE :"+PUB_ANNO  
				   OTHERWISE
				        PUB_DESBAR="INSERIMENTO PRIMA NOTA " && ANNO CONTABILE : "+PUB_ANNO
				ENDCASE
				IF PUB_RICPN
				   PUB_DESBAR="RICERCA PRIMA NOTA DA EFFETTIVA " && ANNO CONTABILE : "+PUB_ANNO   
				ENDIF


		ENDIF



		**===>>>  CASO DI VARIAZIONE PN  <<<===                     
 	    x_TIPOCONTO = "ALTRO"		&& SERVE PER IDENTIFICARE SE CARICARE O MENO I LEGAMI DELLE DDT/FATTURE
		   
		IF (PUB_VARPN=.T.) .OR. (PUB_ANNPN=.T.)
		   
		   M.TOTDOCU     = PUB_TOTPRN
		   M.___xanomax  = PUB_ANOMAX		&& PUB_ANOMAX GESTITA SU INDICE

		   * ACCESSO ALLA REGISTRAZIONE PER PRELEVARE IL TOP E SUCCESSIVAMENTE LA PARTITA CLIENTE/FORNITORE
		   x_soci = "mov_soc = '" + PUB_CODSOC + "'"
		   x_anno = "mov_anno = '" + PUB_ANNO + "'"
		   x_npro = "mov_numpro = '" + ALLTRIM(PUB_REGIN) + "'"
		   x_cond = x_soci + " and " + x_anno + " and " + x_npro
           Csql   = "select * from mov_cont where " + x_cond + " order by mov_soc,mov_anno,mov_numpro,mov_sequen"
           IF !ExecCommand(cSql,"MOV_CONT")
              return(.f.)
           ENDIF
           SELECT MOV_CONT
           GO TOP
		   V_SE= 'TOP'+MOV_TOP
	   	   =seek_std("para",V_SE,"codice","top_para")
           SELECT TOP_PARA
           GO TOP

		   IF SUBSTR(LIBERA,33,2)="CO"				&& compensazioni clienti/fornitori
             COMPENSAZIONE_CLIENTE_FORNITORE = .T.
		   ENDIF
		   	
SET STEP ON 


		   M.FATCESPI          = SUBSTR(LIBERA,75,1)
		   IF M.FATCESPI = "S"
			  _registrazione_cespite = .T.
		   ELSE
			 _registrazione_cespite = .F.
		   ENDIF

	       x_soci = "par_codsoc = '" + PUB_CODSOC + "'"
		   x_anno = "par_anno = '" + PUB_ANNO + "'"
		   x_npro = "par_numpro = '" + ALLTRIM(PUB_REGIN) + "'"
		   x_cond = x_soci + " and " + x_anno + " and " + x_npro
		  
		   _determina_se_cliente_fornitore= SUBSTR(libera,12,1)
		   
		   if SUBSTR(libera,12,1)="C"
              Csql   = "select * from part_cli where " + x_cond + " order by par_codsoc,par_anno,par_numpro"
              IF !ExecCommand(cSql,"_partite_clifor")
                 return(.f.)
              ENDIF

              SELECT _partite_clifor
              GO TOP
		   else
              Csql   = "select * from part_for where " + x_cond + " order by par_codsoc,par_anno,par_numpro"
              IF !ExecCommand(cSql,"_partite_clifor")
                 return(.f.)
              ENDIF
              SELECT _partite_clifor
              GO TOP
		   endif


	 
		   SELECT MOV_CONT
		   BROWSE NORMAL
		   GO TOP 

		   
		   DO WHILE .T.
		   
		      IF EOF()
		         EXIT
		      ENDIF
		   
		      IF MOV_IVAOMA    &&  OMAGGI A CARICO AZIENDA
					
					M.IVAOMA = M.IVAOMA + MOV_IMPOST

		      ENDIF 
		   
		   
		   
		      *===>> SCARTA I RECORD IVA DETERMINATI AUTOMATICAMENTE 
		      IF (MOV_IVA<>'NO ') .AND. (MOV_IMPOST=0)
		         **--> VERIFICA SE IVA E' INDEDUCIBILE O MOVIMENTO ESENTE IVA
		         XXCONTO=MOV_CONTO
		         SS=STR(SELECT())
  	             x_soci = "con_soc = '" + PUB_CODSOC + "'"
		         x_anno = "con_anno = '" + PUB_ANNO + "'"
		         x_cont = "con_conto = '" + ALLTRIM(XXCONTO) + "'"
		         x_cond = x_soci + " and " + x_anno + " and " + x_cont
                 Csql   = "select * from conti where " + x_cond + " order by con_soc,con_anno,con_conto"
                 IF !ExecCommand(cSql,"cur_conti")
                    return(.f.)
                 ENDIF
                 SELECT cur_conti
                 GO TOP
                 IF EOF()
 		            =MESSAGEBOX('Non esiste il conto '+XXCONTO+' sul piano dei conti',16,'*** ATTENZIONE ***')
		            XXTIPOCO = 'I'
                 ELSE
		            XXTIPOCO = CON_TIPOCO
                 ENDIF
		         SELECT &SS
		         SELECT MOV_CONT
		         IF XXTIPOCO='I'
		            SKIP +1
		            LOOP
		         ENDIF  
		      ENDIF
		      WCONTO      = MOV_CONTO
			  WDESCRIZ    = MOV_DESMOV
			  WDESCRI1    = MOV_DESMO1			  
			  WDARE       = 0
			  WAVERE      = 0 
		      WCCAGE      = MOV_CEE 
		      WANT_CAMB_SEGNO = MOV_ANT_CAMB_SEGNO

			  IMPORTO_CENTRO_COSTO  = 0
			  
			  IF MOV_TMOV = 'D'
		         WDARE    = MOV_IMP
		         IMPORTO_CENTRO_COSTO  = MOV_IMP
		      ELSE  
		         WAVERE   = MOV_IMP
		         IMPORTO_CENTRO_COSTO  = MOV_IMP
		      ENDIF

		      _imp_doc    = mov_imp
		  	  WCOD01      = SPACE(13)
			  WCOD02      = SPACE(13)
			  WCOD03      = SPACE(13)
			  WCOD04      = SPACE(13)
			  WCOD05      = SPACE(13)
			  WCOD06      = SPACE(13)
			  WCOD07      = SPACE(13)
			  WCOD08      = SPACE(13)
			  WCOD09      = SPACE(13)
			  WCOD10      = SPACE(13)
		      WIVA        = MOV_IVA
			  WIMPOSTA    = MOV_IMPOST
			  WIMPOSTA_D  = 0
			  WIMPOSTA_A  = 0
			  WNATURA     = MOV_TMOV 
		      M.CECO      = MOV_CCO


			  IF PUB_RIPACC && NON RIPARTISCE L'IMPORTO CONTABILE SU PIU' CENTRI DI COSTO : UN MOVIMENTO CONTABILE CORRISPONE AL 100% DI UN MOVIMENTO PER CENTRO DI COSTO
			     IF !EMPTY(ALLTRIM(M.CECO))
				   STORE ALLTRIM(M.CECO)	TO M.COD01	&& GESTIONE CENTRI DI COSTO : UN RECORD MOV_CONT = 1 RECORD MOV_CCO AL 100%
			   	   STORE 100			    TO M.PERC1
			     ENDIF
			  ENDIF
		      
		      
		      
		      M.CCLI      = MOV_CCLI	
		      M.CFOR      = MOV_CFOR	
		      M.NOTE 	  = MOV_NOTE
		      NUM_INT     = MOV_NUMPRO	
		      WCOD01      = MOV_CCO
			  X_CONTOP    = ALLTRIM(MOV_CONTOP)
		      TOPX	      = MOV_TOP
		  	  XVALUTA     = MOV_VALUTA
			  XDATAVAL    = RIBALTA2(MOV_DTVAL)
			  XCAMBIO     = MOV_CAMBIO
		  	  M.SALDO01   = 0
			  M.SALDO02   = 0
			  M.SALDO03   = 0
			  M.SALDO04   = 0
			  M.SALDO05   = 0
			  M.SALDO06   = 0
			  M.SALDO07   = 0
			  M.SALDO08   = 0
			  M.SALDO09   = 0
			  M.SALDO10   = 0
			  M.MPUBBLI   = MOV_PUBBLI
		      M.PERC1	  = 0
		      M.PERC2	  = 0
		      M.PERC3	  = 0
		      M.PERC4	  = 0
		      M.PERC5	  = 0
		      M.PERC6	  = 0
		      M.PERC7	  = 0
		      M.PERC8	  = 0
		      M.PERC9	  = 0
		      M.PERC10	  = 0
		      M.CODCES    = MOV_CODCES
		      M.STATO_CEE = MOV_STATO_CEE
		      
	          XXCONTO=MOV_CONTO
	          SS=STR(SELECT())
  	          x_soci = "con_soc = '" + PUB_CODSOC + "'"
	          x_anno = "con_anno = '" + PUB_ANNO + "'"
	          x_cont = "con_conto = '" + ALLTRIM(XXCONTO) + "'"
	          x_cond = x_soci + " and " + x_anno + " and " + x_cont
              Csql   = "select * from conti where " + x_cond + " order by con_soc,con_anno,con_conto"
              IF !ExecCommand(cSql,"cur_conti")
                return(.f.)
              ENDIF
              SELECT cur_conti
              GO TOP
              IF EOF()
 		        =MESSAGEBOX('Non esiste il conto '+XXCONTO+' sul piano dei conti',16,'*** ATTENZIONE ***')
	            XXTIPOCO = 'I'
              ELSE
	            XXTIPOCO = CON_TIPOCO
              ENDIF

			  IF XXTIPOCO = "F"
				  x_TIPOCONTO = "FORNITORE"							&& MEMORIZZA SE ESISTE UN RECORD FORNITORE
			  ENDIF

	          SELECT &SS
	          SELECT MOV_CONT

              ** --------------------------------- DATI PER LA GESTIONE INTRASTAT --------------------------------- 
		  	  M.PESO	  				= MOV_PESO
			  M.TISPE     				= MOV_TISPE
			  M.PORTO     				= MOV_PORTO
			  M.CLDOG     				= MOV_CLDOG
			  M.SERV_INTRA				= MOV_SERV_INTRA			 	
			  M.IMPEUR_INTRA			= MOV_IMPEUR_INTRA		
			  M.IMPVAL_INTRA			= MOV_IMPVAL_INTRA		
			  M.IMPSTAT_INTRA			= MOV_IMPSTAT_INTRA		
			  M.STATO_INTRA_PROV		= MOV_STATO_INTRA_PROV		
			  M.PARTITA_IVA_INTRA		= MOV_PARTITA_IVA_INTRA	
			  M.QTA_INTRA				= MOV_QTA_INTRA	
			  M.UNITA_SUPPL_INTRA		= MOV_UNITA_SUPPL_INTRA	
			  M.COND_CONS_INTRA			= MOV_COND_CONS_INTRA			
			  M.MEZZI_TRASP_INTRA		= MOV_MEZZI_TRASP_INTRA	
			  M.NAZIONE_INTRA			= MOV_NAZIONE_INTRA	
			  M.PROVIN_DESTI_INTRA		= MOV_PROVIN_DESTI_INTRA				
              ** --------------------------------- DATI PER LA GESTIONE INTRASTAT --------------------------------- 

			  
              M.SEQUEN    = MOV_SEQUEN
              _NUCOM_     = MOV_NUCOM 
              
              
		      SELECT MOV_CONT
		      *===>>> VA SU ARCHIVIO CONTI PER IDENTIFICARE IL CONTO (CLI/FOR)
		      XXCONTO=MOV_CONTO
		      SS=STR(SELECT())

              x_soci = "con_soc = '" + PUB_CODSOC + "'"
		      x_anno = "con_anno = '" + PUB_ANNO + "'"
		      x_cont = "con_conto = '" + ALLTRIM(XXCONTO) + "'"
		      x_cond = x_soci + " and " + x_anno + " and " + x_cont
              Csql   = "select * from conti where " + x_cond + " order by con_soc,con_anno,con_conto"
              IF !ExecCommand(cSql,"cur_conti")
                 return(.f.)
              ENDIF
              SELECT cur_conti
              GO TOP
              IF EOF()
		         =MESSAGEBOX('Non esiste il conto '+XXCONTO+' sul piano dei conti',16,'*** ATTENZIONE ***')
		         XXTIPOCO = ' '
              ELSE
		         XXTIPOCO = CON_TIPOCO
		      ENDIF

		      SELECT &SS
		      SELECT MOV_CONT
		      *===>>> CARICA VARIABILI DI TESTATA
		      DATAREG    = RIBALTA2(MOV_DTREG)
		      DATADOC	 = RIBALTA2(MOV_DTDOC)
		      DATASCAD   = RIBALTA2(MOV_DATSCAD) 
		      CPA        = MOV_MODPAG
		      BOLLATOIVA = MOV_BOLLATOIVA
		      __BOLLATOIVA = MOV_BOLLATOIVA
              XXX_BOLLATOIVA = MOV_BOLLATOIVA  
		      
		      NDOC       = MOV_NDOC
		      BANCA      = MOV_BANCA
		      NPROT      = MOV_NPROT
              SAVE_NPROT = MOV_NPROT 
		      NREG       = MOV_NREGIS
		      _NREG_     = MOV_NREGIS
		      _NPROT_    = MOV_NPROT
		      M.TOP      = MOV_TOP
		      V_FR	     = MOV_FATRI
		      WSOLOIVA   = MOV_IMPORT

	     	  WCNUMFAT   = MOV_NDORI	     	&& NUMERO DI DOCUMENTO ORIGINALE
	          WCDATFAT   = MOV_DTORI  			&& DATA   DI DOCUMENTO ORIGINALE
              WCNPORI    = MOV_NPORI  			&& NUMERO DI PROTOCOLLO ORIGINALE


	   		  WCOSATRATTA 		 = MOV_COSATRATTA
			  WGRADOIMPORTANZA 	 = MOV_GRADOIMPORTANZA
			  WFORMAPAGAMENTO 	 = MOV_FORMAPAGAMENTO
			  WTIPOCONTRATTO 	 = MOV_TIPOCONTRATTO
			  WCODACQ			 = MOV_CODACQ
			  WPRIPAGA			 = MOV_PRIPAGA
			  WNOIVA             = MOV_NOIVA

			  WSYSCCO            = MOV_SYSCCO 		&& SYS PER LEGAME TRA RIGA CORPO_MOV E CENTRI DI COSTO MAX 10 (NON ILLIMITATI)


			  M.EFF_NUMATRI		 = MOV_NUMATRI		&& GESTIONE EFFETTI
			  M.EFF_DATASCAD     = DATASCAD 
			  M.EFF_EFFETDA 	 = MOV_EFFETDA
			  M.EFF_INTEPER  	 = MOV_INTEPER 
			  M.EFF_NOTEFF 	     = MOV_NOTEFF
               


	          DES 		 = top_para.DESCRI     		&& descrizione parametro
	          WDESCRI    = cur_conti.CON_DESCR 		&& descrizione conto
		      
		      RELEASE XX_CODSYS,XX_CODGRU,XX_CODCCO
		      PUBLIC  XX_CODSYS,XX_CODGRU,XX_CODCCO
		      XX_CODSYS = NUM_INT
		      XX_CODGRU = SPACE(10)
		      XX_CODCCO = SPACE(13)
 		      
 		      
		      IF M.CECO = 'SI - C.COSTO '
		         DO CERCA_CCI        && CERCA I CENTRI DI COSTO ILLIMITATI PER QUESTA RIGA DI PRIMANOTA
		      ELSE
		         DO CERCA_CCO        && CERCA I CENTRI DI COSTO ( MAX 10 ) PER QUESTA RIGA DI PRIMANOTA
		      ENDIF

			  IF PUB_PLAFACQ 
				  ** salvataggio del cursore originale della prima nota per la gestione degli acquisti esenti e calcolo plafond residuo
			      SELEC CORPO_MOV_SAVE 
			      APPEND BLANK
			      REPLACE DTREGIS   WITH DATAREG
			      REPLACE CONTO     WITH WCONTO
			      REPLACE DESCRIC   WITH WDESCRI
			      REPLACE CECO      WITH M.CECO		      
			      REPLACE DARE      WITH WDARE
			      REPLACE AVERE     WITH WAVERE 
			      REPLACE IVA       WITH WIVA
			      REPLACE IMPOSTA   WITH WIMPOSTA
			      REPLACE IMPOSTA_D WITH WIMPOSTA_D
			      REPLACE IMPOSTA_A WITH WIMPOSTA_A
			      REPLACE NATURA    WITH WNATURA
	              REPLACE SEQUEN    WITH M.SEQUEN
			  ENDIF 

			  ** cursore prima nota
		      SELEC CORPO_MOV
		      APPEND BLANK
		      REPLACE CONTO     WITH WCONTO
		      REPLACE DESCRIC   WITH WDESCRI
		      REPLACE DESCRIZ   WITH WDESCRIZ
		      REPLACE DESCRI1   WITH WDESCRI1		      
		      REPLACE DARE      WITH WDARE
		      REPLACE AVERE     WITH WAVERE 
		      REPLACE IVA       WITH WIVA
		      REPLACE IMPOSTA   WITH WIMPOSTA
		      REPLACE IMPOSTA_D WITH WIMPOSTA_D
		      REPLACE IMPOSTA_A WITH WIMPOSTA_A
		      REPLACE NATURA    WITH WNATURA
		      REPLACE SOLOIVA   WITH WSOLOIVA
		      REPLACE CECO      WITH M.CECO
		      REPLACE COD01     WITH WCOD01
		      REPLACE COD02     WITH WCOD02
		      REPLACE COD03     WITH WCOD03
		      REPLACE COD04     WITH WCOD04
		      REPLACE COD05     WITH WCOD05
		      REPLACE COD06     WITH WCOD06
		      REPLACE COD07     WITH WCOD07
		      REPLACE COD08     WITH WCOD08
		      REPLACE COD09     WITH WCOD09
		      REPLACE COD10     WITH WCOD10
		      
		      REPLACE ANT_CAMB_SEGNO WITH WANT_CAMB_SEGNO && 2015/05/26 FABIANO/SERGIO GESTIONE ANTICIPI CON CAMBIO SEGNO
		      
		      REPLACE NOTE      WITH M.NOTE 
		      REPLACE SALDO01   WITH M.SALDO01
		      REPLACE SALDO02   WITH M.SALDO02
		      REPLACE SALDO03   WITH M.SALDO03
		      REPLACE SALDO04   WITH M.SALDO04
		      REPLACE SALDO05   WITH M.SALDO05
		      REPLACE SALDO06   WITH M.SALDO06
		      REPLACE SALDO07   WITH M.SALDO07
		      REPLACE SALDO08   WITH M.SALDO08
		      REPLACE SALDO09   WITH M.SALDO09
		      REPLACE SALDO10   WITH M.SALDO10
		      
		      REPLACE PERC1	    WITH M.PERC1
		      REPLACE PERC2	    WITH M.PERC2
		      REPLACE PERC3	    WITH M.PERC3
		      REPLACE PERC4	    WITH M.PERC4
		      REPLACE PERC5	    WITH M.PERC5
		      REPLACE PERC6	    WITH M.PERC6
		      REPLACE PERC7	    WITH M.PERC7
		      REPLACE PERC8	    WITH M.PERC8
		      REPLACE PERC9	    WITH M.PERC9
		      REPLACE PERC10    WITH M.PERC10
		      REPLACE CODCES    WITH M.CODCES 
		      
		      REPLACE CCLI      WITH M.CCLI	
		      REPLACE CFOR      WITH M.CFOR	
		      REPLACE CCAGE     WITH WCCAGE
		      REPLACE CONTOP    WITH X_CONTOP
		      REPLACE OK_PMULT  WITH "N"
		      
              ** ---------------------------------------- DATI PER LA GESTIONE INTRASTAT -------------------------------------- 
		      REPLACE PESO	    			WITH M.PESO
		      REPLACE TISPE 				WITH M.TISPE
		      REPLACE PORTO     			WITH M.PORTO
		      REPLACE CLDOG     			WITH M.CLDOG 
		      REPLACE SERV_INTRA			WITH M.SERV_INTRA			 	
		      REPLACE IMPEUR_INTRA			WITH M.IMPEUR_INTRA		
		      REPLACE IMPVAL_INTRA			WITH M.IMPVAL_INTRA		
		      REPLACE IMPSTAT_INTRA			WITH M.IMPSTAT_INTRA		
		      REPLACE STATO_INTRA_PROV		WITH M.STATO_INTRA_PROV		
		      REPLACE PARTITA_IVA_INTRA		WITH M.PARTITA_IVA_INTRA	
		      REPLACE QTA_INTRA				WITH M.QTA_INTRA	
		      REPLACE UNITA_SUPPL_INTRA		WITH M.UNITA_SUPPL_INTRA
		      REPLACE COND_CONS_INTRA		WITH M.COND_CONS_INTRA			
		      REPLACE MEZZI_TRASP_INTRA		WITH M.MEZZI_TRASP_INTRA			      
		      REPLACE NAZIONE_INTRA			WITH M.NAZIONE_INTRA	
		      REPLACE PROVIN_DESTI_INTRA	WITH M.PROVIN_DESTI_INTRA		
		      REPLACE DATI_INTRA_VERIFICATI WITH "" && SERVE PER IL CONTROLLO DDEFINITIVO PRIMA DELLA REGISTRAZIONE EFFETTIVA		
              ** ----------------------------------------- DATI PER LA GESTIONE INTRASTAT -------------------------------------- 
		      
		      
		      REPLACE CODSYS    WITH XX_CODSYS
		      REPLACE CODGRU    WITH XX_CODGRU
		      REPLACE CODCCO    WITH M.CECO
              REPLACE SEQUEN    WITH M.SEQUEN

			  REPLACE ___COSATRATTA 		WITH WCOSATRATTA
			  REPLACE ___GRADOIMPORTANZA 	WITH WGRADOIMPORTANZA
			  REPLACE ___FORMAPAGAMENTO 	WITH WFORMAPAGAMENTO
			  REPLACE ___TIPOCONTRATTO 		WITH WTIPOCONTRATTO
			  REPLACE ___CODACQ				WITH WCODACQ
			  REPLACE ___PRIPAGA			WITH WPRIPAGA

			  REPLACE MPUBBLI               WITH M.MPUBBLI  
			  
              REPLACE ___SCARTABOLLATO      WITH WNOIVA             
              REPLACE __BOLLATOIVA      	WITH XXX_BOLLATOIVA      
              REPLACE BOLLATOIVA    	  	WITH XXX_BOLLATOIVA        

			  REPLACE __SYSCCO				WITH WSYSCCO


	     	  REPLACE CNUMFAT				WITH WCNUMFAT   	     	&& NUMERO DI DOCUMENTO ORIGINALE
	          REPLACE CDATFAT               WITH WCDATFAT     			&& DATA   DI DOCUMENTO ORIGINALE
              REPLACE CNPORI                WITH WCNPORI     			&& NUMERO DI PROTOCOLLO ORIGINALE


			  REPLACE __NUCOM 				WITH _NUCOM_     			&& GESTIONE COMMESSA RISORSE LEGATE ALLE SINGOLE RIGHE DELLA PRIMA NOTA

			  REPLACE STATO_CEE 			WITH M.STATO_CEE			&& IDENTIFICA SE LA FATTURA FA PARTE DI UN PAESE MEMBRO CEE
 
 			  REPLACE EFF_NUMATRI		 	WITH M.EFF_NUMATRI			&& GESTIONE EFFETTI
			  REPLACE EFF_DATASCAD	  	    WITH M.EFF_DATASCAD
			  REPLACE EFF_EFFETDA 	 		WITH M.EFF_EFFETDA
			  REPLACE EFF_INTEPER  	 		WITH M.EFF_INTEPER 
			  REPLACE EFF_NOTEFF 	     	WITH M.EFF_NOTEFF

 
            		      
		      DOVE_SONO = RECNO()
			   * -->> ricerca numero partita a parità di conto e importo
			   * ---------------------------------------------------------
			   if used("_partite_clifor")
			     select _partite_clifor
			     go top
			     do while !eof()
			       if deleted()
			         skip+1
			         loop
			       ENDIF
			       
			       if par_nprog = 100
			         skip+1
			         loop
			       endif
			       
*!*				       IF PAR_CODCLI=WCONTO AND PAR_FATT=_IMP_DOC
			       IF PAR_CODCLI=WCONTO  && SERGIO SU FATTURE CON PIU' SCADENZE NON PUO' FUNZIONARE :  AND PAR_FATT=_IMP_DOC
				        
				         _W_NPART			= PAR_NPART
					 	 _NPARF	  			= PAR_NPART					&& NUMERO PARTITA ETERNA FORNITORE/CLIENTE
				 	  	 PUB_NPARF			= PAR_NPART					&& NUMERO PARTITA ETERNA FORNITORE/CLIENTE
				         _W_NUMFCF  		= PAR_NUMFAT
			    	     _W_DTSCACF 		= PAR_DTSCAD
			    	     FATVENSOSIVA__     = PAR_DESMOV				&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA
			    	     
			    	     SAVE_DATASCAD   	= RIBALTA2(PAR_DTSCAD)		&& SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA
			        	 _W_CIVA1CF 		= PAR_CIVA1
				         SELEC CORPO_MOV
				         REPLACE NPARTCF WITH _W_NPART
				         REPLACE NUMFCF  WITH _W_NUMFCF
				         REPLACE DTSCACF WITH _W_DTSCACF
				         REPLACE CIVA1CF WITH _W_CIVA1CF
				         
				         IF ALLTRIM(FATVENSOSIVA__) = "Fatt.Sospens.IVA incassata"		&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA 
	         			 	REPLACE FL_FVS 	WITH "S"									&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA
						 ENDIF															&& 2015/06/17 SERGIO FATTURE IN SOSPENSIONE IVA

			    	     EXIT
			       
			       ENDIF

			       skip+1

			     enddo
			   endif


			*!*	GESTIONE INSOLUTI : RIPORTA NUMERO PARTITA DI PIU' RIGHE PARTITARIO			 
			  ____FATTURA   			= SUBSTR(TOP_PARA.LIBERA,2,1)
			  IF ____FATTURA   = "I" OR  ____FATTURA   = "P"
			   
			   IF USED("_PARTITE_CLIFOR")
				     
				     
				    * -->> RICERCA NUMERO PARTITA A PARITÀ DI CONTO E IMPORTO A PARITA' DI PIU' SCADENZE SUL PARTITARIO
				    * ---------------------------------------------------------
				     ___TROVATA_SCADENZA = .F.
				     SELECT _PARTITE_CLIFOR
				     GO TOP
				     DO WHILE !EOF()
				       IF DELETED()
				         SKIP+1
				         LOOP
				       ENDIF
				       
				       IF PAR_NPROG = 100
				         SKIP+1
				         LOOP
				       ENDIF
				       
				       IF PAR_CODCLI=WCONTO AND PAR_FATT=_IMP_DOC
				         SELEC CORPO_MOV
				         REPLACE CPROTO  WITH _PARTITE_CLIFOR.PAR_NPART
				         REPLACE CFATAGE WITH _PARTITE_CLIFOR.PAR_NPROT
				         NPROT_INSOLUTO = ALLTRIM(_PARTITE_CLIFOR.PAR_NPROT)
				         ___TROVATA_SCADENZA = .T.
			    	     EXIT
				       ENDIF

				       SKIP+1

				     ENDDO
			     
			     
			     	 IF !___TROVATA_SCADENZA
			     	 
					    * -->> RICERCA NUMERO PARTITA A PARITÀ DI CONTO  A PARITA' DI UNA SOLA SCADENZA SUL PARTITARIO
					    * ---------------------------------------------------------
					     ___TROVATA_SCADENZA = .F.
					     SELECT _PARTITE_CLIFOR
					     GO TOP
					     DO WHILE !EOF()
					       IF DELETED()
					         SKIP+1
					         LOOP
					       ENDIF
					       
					       IF PAR_NPROG = 100
					         SKIP+1
					         LOOP
					       ENDIF
					       
					       IF PAR_CODCLI=WCONTO 
					         SELEC CORPO_MOV
					         REPLACE CPROTO  WITH _PARTITE_CLIFOR.PAR_NPART
				         	 REPLACE CFATAGE WITH _PARTITE_CLIFOR.PAR_NPROT
				             NPROT_INSOLUTO = ALLTRIM(_PARTITE_CLIFOR.PAR_NPROT)
				    	     EXIT
					       ENDIF

					       SKIP+1

					     ENDDO
			     	 
		     	 
			     	 ENDIF !___TROVATA_SCADENZA	
		     
			     
			     ENDIF

			  ENDIF




		      SELECT MOV_CONT
		      SKIP +1
		   ENDDO 

	 
		   SS=SELECT()

		   IF EMPTY(NPROT)
	       		NPROT = STR(_partite_clifor.PAR_NPART)    
		   ENDIF  
		    
		   SELECT(SS)


		   =CARICA_U_BFO_LE_VELOCE(x_TIPOCONTO) 			 && CARICA IL CURSORE DEI LEGAMI DDT FATTURE 
		   =CARICA_U_AMM_TT_DD() 			 				 && CARICA I CURSORI RELATIVI AGLI AMMORTAMENTI


		   ** SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA
		   IF !EMPTY(SAVE_DATASCAD)							 && RIPORTO LA DATA SCADENZA DLLA PARTITA DEL CLIENTE O DEL FORNITORE
		   	  DATASCAD = SAVE_DATASCAD						 && RIPORTO LA DATA SCADENZA DLLA PARTITA DEL CLIENTE O DEL FORNITORE
		   ENDIF											 && RIPORTO LA DATA SCADENZA DLLA PARTITA DEL CLIENTE O DEL FORNITORE
		   ** SERGIO 2015/02/18 : BUCO CHE DURA DA 30 ANNI SE ENTRO IN VARIAZIONE PRIMA NOTA MI SPUTTANA LA DATA DI SCADENZA

		   M.CECO    = SPACE(13)
		   M.CONTO   = SPACE(13)
		   M.DESCRIC = SPACE(40)
		   M.CONTO   = SPACE(13)
		   M.DARE	 = 0
		   M.AVERE	 = 0
		   M.IVA	 = SPACE(3)
		   M.IMPOSTA = 0
		   M.DESCRIZ = SPACE(40)
		   M.DESCRI1 = SPACE(40)		   
		   MODIFY    = .T.
		  
		   SELECT CORPO_MOV
		   SET ORDER TO I_CORPOMOV

		   GO TOP
 		   
		   DO QUAD_VAR


		   ** GESTIONE AUTOMATISMI DOCUMENTO
		   NO_AUT	= SPACE(1)
		   PR_NO	= SPACE(1)
		   PR_SI	= SPACE(1)
		   PR_TOP	= SPACE(1)
		   PR_ANA	= SPACE(1)
		   PR_LIS  = SPACE(1)
		   PR_LAN  = SPACE(1)
		   __CEE   = SPACE(1)
		   IL_CCO  = SPACE(1)
		   IN_CCO  = SPACE(1)
		   
  	       M.TOP     			= UPPER(M.TOP)
		   TOPX      			= M.TOP
		   CONIVAX   			= top_para.CONIVA  
		   TCOD01    			= top_para.CONTO1
		   TCOD02    			= top_para.CONTO2
		   TCOD03    			= top_para.CONTO3
		   TCOD04    			= top_para.CONTO4
		   DES       			= top_para.DESCRI     
		   TP        			= SUBSTR(top_para.LIBERA,1,1)
		   FATTURA   			= SUBSTR(top_para.LIBERA,2,1)
		   VER_CONTO 			= SUBSTR(top_para.LIBERA,12,1)
		   NATURA    			= TP
		   NO_AUT				= SUBSTR(top_para.LIBERA,16,1)
		   PR_NO	 			= SUBSTR(top_para.LIBERA,17,1)
		   PR_SI	 			= SUBSTR(top_para.LIBERA,18,1)
		   PR_TOP	 			= SUBSTR(top_para.LIBERA,19,1)
		   PR_ANA	 			= SUBSTR(top_para.LIBERA,20,1)
		   PR_LIS    			= SUBSTR(top_para.LIBERA,21,1)
		   PR_LAN    			= SUBSTR(top_para.LIBERA,22,1)
		   __CEE     			= SUBSTR(top_para.LIBERA,23,1)
		   IL_CCO    			= SUBSTR(top_para.LIBERA,31,1)
		   IN_CCO    			= SUBSTR(top_para.LIBERA,32,1)
		   PR_ANA1   			= .F.
		   PR_TOP1   			= .F.
		   TPROC     			= SUBSTR(top_para.LIBERA,38,3)
		   AGGANCIAPARTITARI 	= SUBSTR(top_para.LIBERA,44,1)
		   CANT    				= SUBSTR(top_para.LIBERA,45,1)     		&& PAGAMENTO IN CONTO ANTICIPO A=AGENTE;F=FORNITORE;C=CLIENTE
		   noquadra             = SUBSTR(top_para.LIBERA,46,1)
		   pincamulti 			= SUBSTR(top_para.LIBERA,48,1)
		   NOTACREDITO          = SUBSTR(top_para.LIBERA,11,1)
		   CREAPART             = SUBSTR(top_para.LIBERA,41,1)
		   _INTRA_   			= SUBSTR(top_para.LIBERA,24,1)

		   IF _INTRA_   = "S"
		  	  REGISTRAZIONE_INTRA = .T.									&& CONTROLLO REGISTRAZIONE INTRASTAT
		   ELSE
			  REGISTRAZIONE_INTRA = .F.
		   ENDIF

		   **  AGGANCIO PROCEDURE EXTRACONTABILI PER ATTRIBUZIONE RIFERIMENTI
		   IF TPROC = "GEN" .OR. EMPTY(TPROC) 	
		      ____STO_GESTENDO_UN_DOC_EXTRACONTABILE = .T.		&& CASO DI TIPO OPERAZIONE NORMALE NON LEGATO ALLE PROCEDURE EXTRA CONTABILI
		   ENDIF

 		   IF ____FATTURA   = "I" OR  ____FATTURA   = "P"
 		   		IF !EMPTY(NPROT_INSOLUTO)
 		   			NPROT   = NPROT_INSOLUTO 
 		   			_NPROT_ = NPROT_INSOLUTO 
 		   		ENDIF
 		   ENDIF ____FATTURA   = "I" 

		   SELECT CORPO_SCA
		   ZAP

		   SELECT _partite_clifor
		   GO TOP
		   	   
		   DO WHILE .T.
		      
		      IF EOF()
		         EXIT
		      ENDIF
		      IF PAR_NPROG = 100 
		         SKIP +1
		         LOOP
		      ENDIF
		      
		      M.SCA_DATSCA = RIBALTA2(PAR_DTSCAD)
		      M.SCA_VALSCA = PAR_FATT
		      M.SCA_ANOMAX = PAR_ANOMAX		      
		      SELECT CORPO_SCA
		      APPEND BLANK
		      GATHER MEMVAR
		      
			  
			  SELECT _partite_clifor
		      SKIP +1
		      
		   ENDDO
		   

		   SELECT CORPO_MOV
		   SET ORDER TO I_CORPOMOV

		   GO TOP


		   
		   XYZ_COD = CONTO
		   XYZ_DES = DESCRIC
		   XYZ_CPA = CPA
		   XYZ_BAN = BANCA
		   XYZ_DTS = DATASCAD
		   XYZ_DCB = DESPAG
		   XYZ_TOT = M.TOTDOCU


		ENDIF


	CASE UPPER(_metodo) = "PERIODI"
 
		SELECT CORPO_SCA
        SET ORDER TO I_SCADE1

		GO TOP
		IF EOF()
		ELSE
		   RETURN
		ENDIF

		RELEASE _OK
		PUBLIC  _OK
		_OK = .F.

		IF XYZ_TIP = 'C'
           x_soci = "cli_codsoc = '" + PUB_CODSOC + "'"
 	       x_codi = "cli_codcli = '" + SUBSTR(XYZ_COD,PUB_SOTTOG,9) + "'"
		   x_cond = x_soci + " and " + x_codi
           Csql   = "select * from u_cli_an where " + x_cond + " order by cli_codsoc,cli_codcli"
           IF !ExecCommand(cSql,"cur_cliente")
              return(.f.)
           ENDIF
           SELECT cur_cliente
           GO TOP
           IF EOF()
           ELSE
	          IF XYZ_BAN = SPACE(05) .OR. EMPTY(XYZ_BAN)
		       	 XYZ_BAN = CLI_BAE
		      ENDIF	
		      PUBLIC VET_DAL[2],VET_AL[2],VET_DAY[2]
		      VET_DAL[1]= CLI_BDAL
		      VET_DAL[2]= CLI_B2DAL
		      VET_AL[1] = CLI_BAL
		      VET_AL[2] = CLI_B2AL
		      VET_DAY[1]= CLI_GG1
		      VET_DAY[2]= CLI_GG2
		      _OK = .T.
		   ENDIF
		ELSE
           x_soci = "for_codsoc = '" + PUB_CODSOC + "'"
 	       x_codi = "for_codcli = '" + SUBSTR(XYZ_COD,PUB_SOTTOG,9) + "'"
		   x_cond = x_soci + " and " + x_codi
           Csql   = "select * from u_for_an where " + x_cond + " order by for_codsoc,for_codcli"
           IF !ExecCommand(cSql,"cur_fornitori")
              return(.f.)
           ENDIF
           SELECT cur_fornitori
           GO TOP
           IF EOF()
           ELSE
              IVA_ACQ_ESE = FOR_ALRID
              IF XYZ_BAN = SPACE(05) .OR. EMPTY(XYZ_BAN)
                 XYZ_BAN = FOR_BAE
              ENDIF
		      _OK = .T.
		   ENDIF			
		ENDIF	

		IF _OK
		   DATA_SCAD = SPACE(10)
		   XYZ_DTS   = SPACE(10)
		   V_TUTTO   = TRANCHE("PARA",XYZ_CPA,RIBALTA2(DATADOC),XYZ_TOT)    
		   CONTA_TRA = 0
		   IS        = 0
		   XPAROLA   = ''
		   DO PAROLA
		   IMP_TRANK=VAL(XPAROLA)
		   DO WHILE .T.
		      CONTA_TRA = CONTA_TRA + 1
		      * CNT IDENTIFICA IL NUMERO DI TRANCHE DETERMINATO DA TRANCHE
		      IF CONTA_TRA > CNT
		         EXIT
		      ENDIF
		      IF CONTA_TRA = CNT
		         IMP_TRANK = IMP_TRANK + COMPENSO
		      ENDIF
		      ** RICERCA DATA SCADENZA
		      XPAROLA = ''
		      DO PAROLA
		      DATA_SCAD=XPAROLA
		      SELECT CORPO_SCA
		      APPEND BLANK
		      REPLACE SCA_DATSCA WITH DATA_SCAD
		      REPLACE SCA_VALSCA WITH IMP_TRANK
		      IF DATA_SCAD<>SPACE(10)
		          XYZ_DTS = DATA_SCAD
		      ENDIF
		   ENDDO
           x_soci = "ban_codsoc = '" + PUB_CODSOC + "'"
 	       x_codi = "ban_codban = '" + ALLTRIM(XYZ_BAN) + "'"
		   x_cond = x_soci + " and " + x_codi
           Csql   = "select * from u_ban_an where " + x_cond + " order by ban_codsoc,ban_codban"
           IF !ExecCommand(cSql,"cur_banca")
              return(.f.)
           ENDIF
           SELECT cur_banca
           GO TOP
           IF EOF()
           ELSE
  		      XYZ_DCB = ALLTRIM(XYZ_DCB) +  " B." + XYZ_BAN + "-" + ALLTRIM(BAN_DESBAN)
           ENDIF
 		ENDIF

ENDCASE