*******************************
* GIACENZE_FINE_MESE
*******************************
LPARAMETERS _NR_MESI,_MAGAZZINO

IF PCOUNT()<1
	RETURN .F.
ENDIF

**=> ERASMO - INIZIO 14/02/2023
IF PCOUNT() >= 2
ELSE
	_MAGAZZINO = ""
ENDIF
**=> ERASMO - FINE 14/02/2023

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

*!*	RELEASE V_TITOLO,V_GIORNI_PRECEDENTI
*!*	PUBLIC V_TITOLO,V_GIORNI_PRECEDENTI

*!*	V_GIORNI_PRECEDENTI = _GIORNI_PRECEDENTI

*!*	V_TITOLO = "Giacenze alla data"

WAIT WINDOWS "ESEGUE PROGRAMMA GIACENZE_FINE_MESE" TIMEOUT 3

*###### DA FORM\PDM_SITGIAC.cerca_giacen ################################################################################################################################################

RELEASE _V_FILTRI,_V_DATAAL,_V_OPZDAT
PUBLIC _V_FILTRI,_V_DATAAL,_V_OPZDAT
_V_DATAAL = ""
_V_OPZDAT = .T.

_ActDate = DTOC(DATE())
_MMAAAA = SUBSTR(_ActDate,4,7)
_nMese = VAL(SUBSTR(_MMAAAA,1,2))
_nAnno = VAL(SUBSTR(_MMAAAA,4,4))
_nMese = _nMese - _NR_MESI
IF _nMese <= 0
	_nAnno = _nAnno - 1
	_nMese = 12
ENDIF
_nUltimoGiorno = 28
DO WHILE .T.
	_cData = TRC(2,STR(_nUltimoGiorno,2,0)) + "/" + TRC(2,STR(_nMese,2,0)) + "/" + TRC(4,STR(_nAnno,4,0))
	_dData = CTOD(_cData)
	_dData = _dData + 1
	IF VAL(SUBSTR(DTOC(_dData),1,2)) > _nUltimoGiorno
		_nUltimoGiorno = _nUltimoGiorno + 1
	ELSE
		EXIT
	ENDIF
ENDDO
_cDataUltimoGiorno = TRC(2,STR(_nUltimoGiorno,2,0)) + "/" + TRC(2,STR(_nMese,2,0)) + "/" + TRC(4,STR(_nAnno,4,0))
_V_DATAAL = _cDataUltimoGiorno 

_V_FILTRI = "FILTRI DI ELABORAZIONE: " + CHR(13) + "   GIACENZE ALLA DATA " + _V_DATAAL

**=> ERASMO - INIZIO 16/02/2023
RELEASE PUB_DECPRZ,PUB_DECVAL
PUBLIC PUB_DECPRZ,PUB_DECVAL
PUB_DECPRZ = 0
PUB_DECVAL = 0

Csql = "SELECT * FROM U_AZI_AN"
IF !ExecCommand(cSql,'CU_AZI_AN')
	return(.f.)
ENDIF
SELECT CU_AZI_AN
GO TOP
IF !EOF()
	PUB_DECPRZ = AZI_DECPRZ
	PUB_DECVAL = AZI_DECVAL
ENDIF
**=> ERASMO - FINE 16/02/2023

*!*	*** CREAZIONE CURSORE PRINCIPALE PER GRIGLIA RAGGRUPPATA PER MAGAZZINO / ARTICOLO
*!*	CREATE CURSOR C_GIACEN_RAGGR (CODMAG C(6), DESMAG C(200), CODART C(30), DESART C(200), UM C(3), GIACEN N(19,PUB_DECQTA), CONSISTENZA N(19,PUB_DECQTA), QTAIMP N(19,PUB_DECQTA), PRZSTD N(19,PUB_DECPRZ), VALSTD N(19,PUB_DECVAL), ;
*!*		PRZULT N(19,PUB_DECPRZ), VALULT N(19,PUB_DECVAL), PRZMEP N(19,PUB_DECPRZ), VALMEP N(19,PUB_DECVAL), LINEA C(2), DESLIN C(200), C_LINEA C(200), CODGMI C(9), DESGMI C(200), C_GMI C(200), ;
*!*		DESGMI_1_3 C(100), DESGMI_1_6 C(100))
*!*	INDEX ON ALLTRIM(CODMAG)+ALLTRIM(CODART) TAG I_MAGART ADDITIVE

*!*	*** CREAZIONE CURSORE PRINCIPALE PER GRIGLIA RAGGRUPPATA PER MAGAZZINO / ARTICOLO / DATA CARICO / SERIAL NUMBER - LOTTO
*!*	CREATE CURSOR C_GIACEN_RAGSN (CODMAG C(6), DESMAG C(200), CODART C(30), DESART C(200), UM C(3), GIACEN N(19,PUB_DECQTA), QTAIMP N(19,PUB_DECQTA), PRZSTD N(19,PUB_DECPRZ), VALSTD N(19,PUB_DECVAL), ;
*!*		PRZULT N(19,PUB_DECPRZ), VALULT N(19,PUB_DECVAL), PRZMEP N(19,PUB_DECPRZ), VALMEP N(19,PUB_DECVAL), DATCAR C(10), SERIAL C(20), LINEA C(2), DESLIN C(200), C_LINEA C(200), CODGMI C(9), DESGMI C(200), C_GMI C(200), ;
*!*		DESGMI_1_3 C(100), DESGMI_1_6 C(100))
*!*	INDEX ON ALLTRIM(CODMAG)+ALLTRIM(CODART)+ALLTRIM(DATCAR)+ALLTRIM(SERIAL) TAG I_MAGART ADDITIVE	

*** CREAZIONE CURSORE PRINCIPALE PER GRIGLIA DETTAGLIATA
CREATE CURSOR C_GIACEN_DETT (CODMAG C(6), DESMAG C(200), CODART C(30), DESART C(200), UM C(3), GIACEN N(19,PUB_DECQTA), QTAIMP N(19,PUB_DECQTA), PRZSTD N(19,PUB_DECPRZ), VALSTD N(19,PUB_DECVAL), MAG_LEGAME C(10), ;
	PRZULT N(19,PUB_DECPRZ), VALULT N(19,PUB_DECVAL), PRZMEP N(19,PUB_DECPRZ), VALMEP N(19,PUB_DECVAL), DATCAR C(10), ORACAR C(8), SERIAL C(20), LINEA C(2), DESLIN C(200), C_LINEA C(200), CODGMI C(9), DESGMI C(200), C_GMI C(200), ;
	DESGMI_1_3 C(100), DESGMI_1_6 C(100), PRZEFF N(19,PUB_DECPRZ), VALEFF N(19,PUB_DECVAL), DTSCAD C(10), SEL_DTSCAD L)
INDEX ON ALLTRIM(CODMAG)+ALLTRIM(CODART)+ALLTRIM(DATCAR)+ALLTRIM(ORACAR) TAG I_MAGART ADDITIVE	

*########################################################################################################################################################################################

*** REPORT RIEPILOGO
cSql=""     
cNomeCursorSql="CX_GIACEN"

*###### DA FORM\PDM_SITGIAC.cerca_giacen ################################################################################################################################################

*WAIT WINDOW "Ricerca giacenze in corso..." NOWAIT

*!*	SELECT C_GIACEN_RAGGR
*!*	SET FILTER TO 
*!*	SET ORDER TO
*!*	ZAP

*!*	SELECT C_GIACEN_RAGSN
*!*	SET FILTER TO 
*!*	SET ORDER TO
*!*	ZAP

SELECT C_GIACEN_DETT
SET FILTER TO 
SET ORDER TO
ZAP

x_giac = "MO.MOV_QTAMOV <> 0"
x_cond = x_giac
**=> ERASMO - INIZIO 14/02/2023
IF !EMPTY(_MAGAZZINO)
	x_cond = x_cond + " AND MO.MOV_CODMAG = '" + _MAGAZZINO + "'"
ENDIF
**=> ERASMO - FINE 14/02/2023

*!*	LOCAL cSql
*!*	cSql = ""
*!*	TEXT TO cSql NOSHOW 
*!*		Declare @DATAAL as varchar(10)
*!*		Set @DATAAL = '<<RIBALTA2(_V_DATAAL)>>'

*!*		SELECT
*!*			MOV_LEGAME AS MAG_LEGAME,
*!*			SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),1,10) AS MAG_DATAGG,
*!*			SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),11,8) AS MAG_ORACAR,
*!*			MOV_CODMAG AS MAG_CODMAG,
*!*			DESCRI,
*!*			MOV_ANAART AS MAG_ANAART,
*!*			ART_DESCR,
*!*			ART_UMMAGA,
*!*			ART_PRZCOS,
*!*			ART_LINEA,
*!*			DESLIN,
*!*			SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1*MOV_QTAMOV END) AS MAG_GIACEN,
*!*			0 AS MAG_QTAIMP,
*!*			MOV_SERIAL AS MAG_SERIAL,
*!*			MOV_PREACQ AS MAG_PRZCON,
*!*			MOV_CODFOR AS MAG_FORNIT,
*!*			ULT_DTSCAD AS MAG_DTSCAD,
*!*			ART_CODGMI,
*!*			DESGMI,
*!*			DESGMI_1_3,
*!*			DESGMI_1_6,
*!*			ULT_PREACQ,
*!*			ULT_FORNIT,
*!*			MEP_PREACQ,
*!*			MAG_VALUTA,
*!*			MAG_CHANGE FROM (

*!*			SELECT
*!*				MO.MOV_SEGNO,
*!*				MO.MOV_LEGAME,
*!*				MO.MOV_DTREGI,
*!*				MO.MOV_ORAMOV,
*!*				MO.MOV_CODMAG,
*!*				MG.DESCRI,
*!*				MO.MOV_ANAART,
*!*				PR.ART_DESCR,
*!*				PR.ART_UMMAGA,
*!*				PR.ART_PRZCOS,
*!*				PR.ART_LINEA,
*!*				COALESCE(LN.DESCRI,'') AS DESLIN,
*!*				MO.MOV_QTAMOV,
*!*				MO.MOV_SERIAL,
*!*				--MO.MOV_PREACQ,
*!*				--COALESCE(MV.MOV_PREACQ,MV.MOV_PREACQ,PR.ART_ULPCAR,0) AS MOV_PREACQ,
*!*				COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS MOV_PREACQ,  -- ERASMO - 28/05/2019
*!*				MO.MOV_CODFOR,
*!*				AN.ART_CODGMI,
*!*				COALESCE(GM.DESCRI,'') AS DESGMI,
*!*				COALESCE(GM_1_3.DESCRI,'') AS DESGMI_1_3,
*!*				COALESCE(GM_1_6.DESCRI,'') AS DESGMI_1_6,
*!*				COALESCE((SELECT TOP 1 MOV_DTSCAD FROM U_MAG_MO WHERE MOV_LEGAME = MO.MOV_LEGAME AND MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_DTSCAD,
*!*				--COALESCE((SELECT TOP 1 MOV_PREACQ FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),0) AS ULT_PREACQ,
*!*				--COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT,
*!*				COALESCE(PR.ART_ULPCAR,0) AS ULT_PREACQ,
*!*				COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT,
*!*				COALESCE(
*!*					(SELECT
*!*						CASE WHEN SOMMA_QTA > 0 THEN SOMMA_QTA_PER_PREZZO / SOMMA_QTA ELSE 0 END AS PREZZO_MEDIO_PONDERATO_GIACENZE
*!*					 FROM (
*!*						SELECT 
*!*							COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV * MOV_PREACQ ELSE 0 END),0) AS SOMMA_QTA_PER_PREZZO, 
*!*							COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV ELSE 0 END),0) AS SOMMA_QTA FROM (
*!*								SELECT MOV_QTAMOV,MOV_PREACQ FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_PREACQ > 0 AND MOV_SEGNO = '+' AND MOV_DTREGI <= @DATAAL
*!*							) AS MAIN
*!*						) AS T1),0) AS MEP_PREACQ,
*!*				--COALESCE(MV.MOV_VALUTA,'') AS MAG_VALUTA, 
*!*				COALESCE(MV.MOV_VALUTA,MVU.MOV_VALUTA,'') AS MAG_VALUTA, 
*!*				--COALESCE(VV.VVA_CHANGE,1) AS MAG_CHANGE
*!*				COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) AS MAG_CHANGE
*!*			FROM U_MAG_MO AS MO
*!*			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MO.MOV_ANAART
*!*			LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
*!*			LEFT OUTER JOIN PARA AS GM ON GM.CODICE = 'GMI'+AN.ART_CODGMI
*!*			LEFT OUTER JOIN PARA AS GM_1_3 ON GM_1_3.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
*!*			LEFT OUTER JOIN PARA AS GM_1_6 ON GM_1_6.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
*!*			LEFT OUTER JOIN PARA AS MG ON MG.CODICE = 'MAG'+MO.MOV_CODMAG
*!*			LEFT OUTER JOIN PARA AS LN ON LN.CODICE = 'REP'+PR.ART_LINEA
*!*			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = MO.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
*!*			--OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_DTREGI <= MO.MOV_DTREGI ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU   -- ERASMO - 19/04/2019			
*!*			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
*!*				(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= MO.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU   -- ERASMO - 28/05/2019 
*!*			--OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= MV.MOV_DTDOCU ORDER BY VVA_DATA DESC) AS VV 
*!*			--OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= MVU.MOV_DTDOCU ORDER BY VVA_DATA DESC) AS VVU 
*!*			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV   -- ERASMO - 19/04/2019
*!*			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU   -- ERASMO - 19/04/2019
*!*			WHERE <<x_cond>>  AND MO.MOV_SEGNO <> '' AND MO.MOV_DTREGI <= @DATAAL  --AND MO.MOV_CODMAG = 'RCH'
*!*			) AS MAIN
*!*			GROUP BY MOV_LEGAME,MOV_CODMAG,DESCRI,MOV_ANAART,ART_DESCR,ART_UMMAGA,ART_PRZCOS,ART_LINEA,DESLIN,MOV_SERIAL,MOV_PREACQ,MOV_CODFOR,ULT_DTSCAD,ART_CODGMI,DESGMI,DESGMI_1_3,DESGMI_1_6,ULT_PREACQ,ULT_FORNIT,MEP_PREACQ,MAG_VALUTA,MAG_CHANGE
*!*	ENDTEXT

**=> ERASMO - INIZIO 10/03/2023
LOCAL cSql
cSql = ""
TEXT TO cSql NOSHOW
	Declare @DATAAL as varchar(10)
	Set @DATAAL = '<<RIBALTA2(_V_DATAAL)>>'

	SELECT
		MAG_LEGAME,
		MAG_UNIQUE,  -- ERASMO - 18/05/2023
		MAG_DATAGG,
		MAG_ORACAR,
		MAG_CODMAG,
		MG.DESCRI,
		MAG_ANAART,
		PR.ART_DESCR,
		PR.ART_DESCR,
		PR.ART_UMMAGA,
		PR.ART_PRZCOS,
		PR.ART_LINEA,
		PR.ART_CODCTL,
		COALESCE(LN.DESCRI,'') AS DESLIN,
		MAG_GIACEN,
		MAG_QTAIMP,
		MAG_SERIAL,
		COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS MAG_PRZCON,
		MAG_FORNIT,
		COALESCE((SELECT TOP 1 MOV_DTSCAD FROM U_MAG_MO WHERE MOV_LEGAME = T1.MAG_LEGAME AND MOV_ANAART = T1.MAG_ANAART AND MOV_DOCMOD = 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS MAG_DTSCAD,
		AN.ART_CODGMI,
		COALESCE(GM.DESCRI,'') AS DESGMI,
		COALESCE(GM_1_3.DESCRI,'') AS DESGMI_1_3,
		COALESCE(GM_1_6.DESCRI,'') AS DESGMI_1_6,
		COALESCE(PR.ART_ULPCAR,0) AS ULT_PREACQ,
		COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = T1.MAG_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT,
		COALESCE(
			(SELECT
				CASE WHEN SOMMA_QTA > 0 THEN SOMMA_QTA_PER_PREZZO / SOMMA_QTA ELSE 0 END AS PREZZO_MEDIO_PONDERATO_GIACENZE
				FROM (
				SELECT 
					COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV * MOV_PREACQ ELSE 0 END),0) AS SOMMA_QTA_PER_PREZZO, 
					COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV ELSE 0 END),0) AS SOMMA_QTA FROM (
						SELECT MOV_QTAMOV,MOV_PREACQ FROM U_MAG_MO WHERE MOV_ANAART = T1.MAG_ANAART AND MOV_PREACQ > 0 AND MOV_SEGNO = '+' AND MOV_DTREGI <= @DATAAL
					) AS MAIN
				) AS T1),0) AS MEP_PREACQ,
		COALESCE(MV.MOV_VALUTA,MVU.MOV_VALUTA,'') AS MAG_VALUTA,
		COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) AS MAG_CHANGE
	FROM (
		SELECT * FROM (
			SELECT
				MOV_LEGAME AS MAG_LEGAME,
				MOV_MAGUNQ AS MAG_UNIQUE,  -- ERASMO - 18/05/2023
				SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),1,10) AS MAG_DATAGG,
				SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),11,8) AS MAG_ORACAR,
				MOV_CODMAG AS MAG_CODMAG,
				MOV_ANAART AS MAG_ANAART,
				SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1*MOV_QTAMOV END) AS MAG_GIACEN,
				0 AS MAG_QTAIMP,
				MOV_SERIAL AS MAG_SERIAL,
				MOV_CODFOR AS MAG_FORNIT
				FROM (
					SELECT
						MO.MOV_SEGNO,
						MO.MOV_LEGAME,
						MO.MOV_MAGUNQ,  -- ERASMO - 18/05/2023
						MO.MOV_DTREGI,
						MO.MOV_ORAMOV,
						MO.MOV_CODMAG,
						MO.MOV_ANAART,
						MO.MOV_QTAMOV,
						MO.MOV_SERIAL,
						MO.MOV_CODFOR
					FROM U_MAG_MO AS MO
					WHERE <<x_cond>> AND MO.MOV_SEGNO <> '' AND MO.MOV_DTREGI <= @DATAAL
				) AS MAIN
				GROUP BY 
				MOV_LEGAME,
				MOV_MAGUNQ,  -- ERASMO - 18/05/2023
				MOV_CODMAG,
				MOV_ANAART,
				MOV_SERIAL,
				MOV_CODFOR
		) AS T2
		WHERE MAG_GIACEN <> 0
	) AS T1
	LEFT OUTER JOIN PARA AS MG ON MG.CODICE = 'MAG'+T1.MAG_CODMAG
	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = T1.MAG_ANAART
	LEFT OUTER JOIN PARA AS LN ON LN.CODICE = 'REP'+PR.ART_LINEA
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS GM ON GM.CODICE = 'GMI'+AN.ART_CODGMI
	LEFT OUTER JOIN PARA AS GM_1_3 ON GM_1_3.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS GM_1_6 ON GM_1_6.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
	OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = T1.MAG_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
	OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
		(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = T1.MAG_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= T1.MAG_DATAGG ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU
	OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
	OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU

ENDTEXT
**=> ERASMO - FINE 10/03/2023

WAIT WINDOWS "ESTRAZIONE GIACENZE ALLA DATA DA MOVIMENTI IN CORSO..." NOWAIT

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
   return(.f.)
ENDIF

*!*	x_giac = "MO.MOV_QTAMOV <> 0"
*!*	x_cond = x_giac
*!*	SET STEP ON
*!*	LOCAL cSql
*!*	cSql = ""
*!*	cSql = "Declare @DATAAL as varchar(10)" + CHR(13) + ;
*!*		"Set @DATAAL = '" + RIBALTA2(_V_DATAAL) + "'" + CHR(13) + ;
*!*		"SELECT" + CHR(13) + ;
*!*		"	MOV_LEGAME AS MAG_LEGAME," + CHR(13) + ;
*!*		"	SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),1,10) AS MAG_DATAGG," + CHR(13) + ;
*!*		"	SUBSTRING(MIN(MOV_DTREGI+MOV_ORAMOV),11,8) AS MAG_ORACAR," + CHR(13) + ;
*!*		"	MOV_CODMAG AS MAG_CODMAG," + CHR(13) + ;
*!*		"	DESCRI," + CHR(13) + ;
*!*		"	MOV_ANAART AS MAG_ANAART," + CHR(13) + ;
*!*		"	ART_DESCR," + CHR(13) + ;
*!*		"	ART_UMMAGA," + CHR(13) + ;
*!*		"	ART_PRZCOS," + CHR(13) + ;
*!*		"	ART_LINEA," + CHR(13) + ;
*!*		"	DESLIN," + CHR(13) + ;
*!*		"	SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1*MOV_QTAMOV END) AS MAG_GIACEN," + CHR(13) + ;
*!*		"	0 AS MAG_QTAIMP," + CHR(13) + ;
*!*		"	MOV_SERIAL AS MAG_SERIAL," + CHR(13) + ;
*!*		"	MOV_PREACQ AS MAG_PRZCON," + CHR(13) + ;
*!*		"	MOV_CODFOR AS MAG_FORNIT," + CHR(13) + ;
*!*		"	ULT_DTSCAD AS MAG_DTSCAD," + CHR(13) + ;
*!*		"	ART_CODGMI," + CHR(13) + ;
*!*		"	DESGMI," + CHR(13) + ;
*!*		"	DESGMI_1_3," + CHR(13) + ;
*!*		"	DESGMI_1_6," + CHR(13) + ;
*!*		"	ULT_PREACQ," + CHR(13) + ;
*!*		"	ULT_FORNIT," + CHR(13) + ;
*!*		"	MEP_PREACQ," + CHR(13) + ;
*!*		"	MAG_VALUTA," + CHR(13) + ;
*!*		"	MAG_CHANGE FROM (" + CHR(13) + ;
*!*		"	SELECT" + CHR(13) + ;
*!*		"		MO.MOV_SEGNO," + CHR(13) + ;
*!*		"		MO.MOV_LEGAME," + CHR(13) + ;
*!*		"		MO.MOV_DTREGI," + CHR(13) + ;
*!*		"		MO.MOV_ORAMOV," + CHR(13) + ;
*!*		"		MO.MOV_CODMAG," + CHR(13) + ;
*!*		"		MG.DESCRI," + CHR(13) + ;
*!*		"		MO.MOV_ANAART," + CHR(13) + ;
*!*		"		PR.ART_DESCR," + CHR(13) + ;
*!*		"		PR.ART_UMMAGA," + CHR(13) + ;
*!*		"		PR.ART_PRZCOS," + CHR(13) + ;
*!*		"		PR.ART_LINEA," + CHR(13) + ;
*!*		"		COALESCE(LN.DESCRI,'') AS DESLIN," + CHR(13) + ;
*!*		"		MO.MOV_QTAMOV," + CHR(13) + ;
*!*		"		MO.MOV_SERIAL," + CHR(13) + ;
*!*		"		--MO.MOV_PREACQ," + CHR(13) + ;
*!*		"		--COALESCE(MV.MOV_PREACQ,MV.MOV_PREACQ,PR.ART_ULPCAR,0) AS MOV_PREACQ," + CHR(13) + ;
*!*		"		COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS MOV_PREACQ,  -- ERASMO - 28/05/2019" + CHR(13) + ;
*!*		"		MO.MOV_CODFOR," + CHR(13) + ;
*!*		"		AN.ART_CODGMI," + CHR(13) + ;
*!*		"		COALESCE(GM.DESCRI,'') AS DESGMI," + CHR(13) + ;
*!*		"		COALESCE(GM_1_3.DESCRI,'') AS DESGMI_1_3," + CHR(13) + ;
*!*		"		COALESCE(GM_1_6.DESCRI,'') AS DESGMI_1_6," + CHR(13) + ;
*!*		"		COALESCE((SELECT TOP 1 MOV_DTSCAD FROM U_MAG_MO WHERE MOV_LEGAME = MO.MOV_LEGAME AND MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_DTSCAD," + CHR(13) + ;
*!*		"		--COALESCE((SELECT TOP 1 MOV_PREACQ FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),0) AS ULT_PREACQ," + CHR(13) + ;
*!*		"		--COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 AND MOV_DTREGI <= @DATAAL ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT," + CHR(13) + ;
*!*		"		COALESCE(PR.ART_ULPCAR,0) AS ULT_PREACQ," + CHR(13) + ;
*!*		"		COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT," + CHR(13) + ;
*!*		"		COALESCE(" + CHR(13) + ;
*!*		"			(SELECT" + CHR(13) + ;
*!*		"				CASE WHEN SOMMA_QTA > 0 THEN SOMMA_QTA_PER_PREZZO / SOMMA_QTA ELSE 0 END AS PREZZO_MEDIO_PONDERATO_GIACENZE" + CHR(13) + ;
*!*		"			 FROM (" + CHR(13) + ;
*!*		"				SELECT " + CHR(13) + ;
*!*		"					COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV * MOV_PREACQ ELSE 0 END),0) AS SOMMA_QTA_PER_PREZZO, " + CHR(13) + ;
*!*		"					COALESCE(SUM(CASE WHEN (MOV_QTAMOV > 0 AND MOV_PREACQ > 0) THEN MOV_QTAMOV ELSE 0 END),0) AS SOMMA_QTA FROM (" + CHR(13) + ;
*!*		"						SELECT MOV_QTAMOV,MOV_PREACQ FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_PREACQ > 0 AND MOV_SEGNO = '+' AND MOV_DTREGI <= @DATAAL" + CHR(13) + ;
*!*		"					) AS MAIN" + CHR(13) + ;
*!*		"				) AS T1),0) AS MEP_PREACQ," + CHR(13) + ;
*!*		"		--COALESCE(MV.MOV_VALUTA,'') AS MAG_VALUTA, " + CHR(13) + ;
*!*		"		COALESCE(MV.MOV_VALUTA,MVU.MOV_VALUTA,'') AS MAG_VALUTA, " + CHR(13) + ;
*!*		"		--COALESCE(VV.VVA_CHANGE,1) AS MAG_CHANGE" + CHR(13) + ;
*!*		"		COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) AS MAG_CHANGE" + CHR(13) + ;
*!*		"	FROM U_MAG_MO AS MO" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MO.MOV_ANAART" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN PARA AS GM ON GM.CODICE = 'GMI'+AN.ART_CODGMI" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN PARA AS GM_1_3 ON GM_1_3.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN PARA AS GM_1_6 ON GM_1_6.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN PARA AS MG ON MG.CODICE = 'MAG'+MO.MOV_CODMAG" + CHR(13) + ;
*!*		"	LEFT OUTER JOIN PARA AS LN ON LN.CODICE = 'REP'+PR.ART_LINEA" + CHR(13) + ;
*!*		"	OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = MO.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV " + CHR(13) + ;
*!*		"	--OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_DTREGI <= MO.MOV_DTREGI ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU   -- ERASMO - 19/04/2019			" + CHR(13) + ;
*!*		"	OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = " + CHR(13) + ;
*!*		"		(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = MO.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= MO.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU   -- ERASMO - 28/05/2019 " + CHR(13) + ;
*!*		"	--OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= MV.MOV_DTDOCU ORDER BY VVA_DATA DESC) AS VV " + CHR(13) + ;
*!*		"	--OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= MVU.MOV_DTDOCU ORDER BY VVA_DATA DESC) AS VVU " + CHR(13) + ;
*!*		"	OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV   -- ERASMO - 19/04/2019" + CHR(13) + ;
*!*		"	OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU   -- ERASMO - 19/04/2019" + CHR(13) + ;
*!*		"	WHERE " + x_cond + " AND MO.MOV_CODMAG = 'ZFF'  AND MO.MOV_SEGNO <> '' AND MO.MOV_DTREGI <= @DATAAL" + CHR(13) + ;
*!*		"	) AS MAIN" + CHR(13) + ;
*!*		"	GROUP BY MOV_LEGAME,MOV_CODMAG,DESCRI,MOV_ANAART,ART_DESCR,ART_UMMAGA,ART_PRZCOS,ART_LINEA,DESLIN,MOV_SERIAL,MOV_PREACQ,MOV_CODFOR,ULT_DTSCAD,ART_CODGMI,DESGMI,DESGMI_1_3,DESGMI_1_6,ULT_PREACQ,ULT_FORNIT,MEP_PREACQ,MAG_VALUTA,MAG_CHANGE"
*!*	IF !ExecCommand(cSql,cNomeCursorSql)
*!*	   return(.f.)
*!*	ENDIF

*!*	SELECT C_GIACEN_RAGGR
*!*	SET ORDER TO I_MAGART
*!*	GO TOP

*!*	SELECT C_GIACEN_RAGSN
*!*	SET ORDER TO I_MAGART
*!*	GO TOP

WAIT WINDOWS "ELABORAZIONE CURSORE IN CORSO..." NOWAIT

SELECT &cNomeCursorSql
GO TOP
SCAN
	
*!*		*WAIT WINDOWS "Elaborazione giacenze... (" + ALLTRIM(STR(RECNO() * 100 / RECCOUNT(),10,0)) + "%)" NOWAIT 
*!*		
*!*		IF !AQ_WAITBAR(THISFORM,"CX_GIACEN",.T.,"Elaborazione giacenze... (" + ALLTRIM(STR(RECNO() * 100 / RECCOUNT(),10,0)) + "%)")  && ERASMO - 28/10/2014
*!*			SELECT C_GIACEN_RAGGR
*!*			SET FILTER TO 
*!*			SET ORDER TO
*!*			ZAP

*!*			SELECT C_GIACEN_RAGSN
*!*			SET FILTER TO 
*!*			SET ORDER TO
*!*			ZAP

*!*			SELECT C_GIACEN_DETT
*!*			SET FILTER TO 
*!*			SET ORDER TO
*!*			ZAP

*!*			_V_TOT_GIACEN = 0
*!*			_V_TOT_QTAIMP = 0
*!*			_V_TOT_VALMEP = 0
*!*			_V_TOT_VALSTD = 0
*!*			_V_TOT_VALULC = 0
*!*			_V_TOT_VALEFF = 0  && ERASMO - 07/11/2016

*!*			THISFORM.txt_V_TOT_GIACEN.Visible = .F.
*!*			THISFORM.lbl_V_TOT_GIACEN.Visible = .F.
*!*			THISFORM.lbl_V_TOT_QTAIMP.Visible = .F.
*!*			THISFORM.txt_V_TOT_QTAIMP.Visible = .F.
*!*			
*!*			THISFORM.Refresh
*!*			EXIT
*!*		ENDIF
	
	**=> ERASMO - INIZIO 17/03/2017
	IF MAG_GIACEN <> 0
	ELSE
		LOOP
	ENDIF
	
	*** SE VALUTA DIVERSA DA QUELLA DI RIFERIMENTO, CONVERTO IL PREZZO DI ACQUISTO NELL'ULTIMO CAMBIO DISPONIBILE 
	*** CON DATA VALUTA INFERIORE O UGUALE ALLA DATA DOCUMENTO DEL PRIMO MOVIMENTO DI CARICO LEGATO
	IF EMPTY(MAG_VALUTA)
		REPLACE MAG_VALUTA WITH PUB_VALRIF
	ENDIF
	IF ALLTRIM(MAG_VALUTA) <> ALLTRIM(PUB_VALRIF)
		__PREZZO_VALRIF = CAMBIO(MAG_VALUTA,MAG_PRZCON,MAG_CHANGE,"",.F.,PUB_DECPRZ)
		SELECT &cNomeCursorSql
		REPLACE MAG_PRZCON WITH __PREZZO_VALRIF
	ENDIF
	**=> ERASMO - FINE 17/03/2017
    
    LOCAL _X_CODMAG,_X_CODART,_X_DESART,_X_UM,_X_GIACEN,_X_QTAIMP,_X_PRZSTD,_X_PRZULT,_X_PRZMEP,_X_PRZEFF,_X_DATCAR,_X_ORACAR,_X_SERIAL,_X_LINEA,_X_DESLIN,_X_C_LINEA, ;
    	_X_CODGMI,_X_DESGMI,_X_DESGMI_1_3,_X_DESGMI_1_6,_X_C_GMI,_X_CONSISTENZA,_X_DTSCAD
    
    _X_LEGAME 	= ALLTRIM(MAG_LEGAME)
	_X_CODMAG 	= ALLTRIM(MAG_CODMAG)
	_X_CODART 	= ALLTRIM(MAG_ANAART)
	_X_DESART 	= ALLTRIM(ART_DESCR)
	_X_UM     	= ALLTRIM(ART_UMMAGA)
	_X_GIACEN 	= MAG_GIACEN
	_X_QTAIMP 	= MAG_QTAIMP
	_X_PRZSTD 	= ART_PRZCOS
	_X_PRZULT 	= ULT_PREACQ
	_X_PRZMEP 	= MEP_PREACQ
	_X_PRZEFF	= MAG_PRZCON  && ERASMO - 07/11/2016
	
	_X_DATCAR 	= ALLTRIM(MAG_DATAGG)
	_X_ORACAR 	= MAG_ORACAR
	_X_SERIAL 	= ALLTRIM(MAG_SERIAL)
	
	_X_LINEA 	= ALLTRIM(ART_LINEA)
	_X_DESLIN 	= ALLTRIM(DESLIN)
	_X_C_LINEA 	= ALLTRIM(DESLIN) + " (" + ALLTRIM(ART_LINEA) + ")"
	_X_CODGMI 	= ALLTRIM(ART_CODGMI)
	_X_DESGMI 	= ALLTRIM(DESGMI)
	_X_DESGMI_1_3 = ALLTRIM(DESGMI_1_3)
	_X_DESGMI_1_6 = ALLTRIM(DESGMI_1_6)
	_X_C_GMI 	= ALLTRIM(DESGMI) + " (" + ALLTRIM(ART_CODGMI) + ")"
	
	_X_DTSCAD   = MAG_DTSCAD  && ERASMO - 24/11/2016
		
	_X_CONSISTENZA = 0
*!*		IF !_V_OPZDAT OR _V_DATAAL = DTOC(DATE())	&& GIACENZE AD OGGI
*!*			IF _V_OPZCONSISTENZA
*!*				_ww_codsoc = PUB_CODSOC
*!*				_ww_anaart = _X_CODART
*!*				_ww_codmag = _X_CODMAG
*!*				_ww_prenot = .T.  && SOLO GIACENZE NON PRENOTATE
*!*				_ww_codint = ""
*!*				_ww_altezz = 0
*!*				_ww_lunghe = 0
*!*				_ww_fila_x = ""
*!*				_ww_pian_x = ""
*!*				_ww_ubic_x = ""
*!*				_X_CONSISTENZA = AQM_RILEVA_CONSISTENZA(_ww_codsoc,_ww_anaart,_ww_codmag,_ww_prenot,_ww_codint,_ww_altezz,_ww_lunghe,_ww_fila_x,_ww_pian_x,_ww_ubic_x)
*!*			ENDIF
*!*		ENDIF
*!*		
*!*		*** POPOLAMENTO CURSORE PER GRIGLIA RAGGRUPPATA PER MAGAZZINO / ARTICOLO
*!*		_SEEK = _X_CODMAG + _X_CODART
*!*		SELECT C_GIACEN_RAGGR
*!*		GO TOP
*!*		SEEK _SEEK
*!*		IF !FOUND()
*!*			APPEND BLANK
*!*			REPLACE CODMAG 			WITH _X_CODMAG
*!*			REPLACE CODART 			WITH _X_CODART
*!*			REPLACE DESART 			WITH _X_DESART
*!*			REPLACE UM     			WITH _X_UM 
*!*			REPLACE GIACEN 			WITH 0
*!*			REPLACE QTAIMP 			WITH 0
*!*			REPLACE CONSISTENZA 	WITH _X_CONSISTENZA 
*!*			REPLACE PRZSTD 			WITH _X_PRZSTD
*!*			REPLACE PRZULT 			WITH _X_PRZULT
*!*			REPLACE PRZMEP 			WITH _X_PRZMEP
*!*			REPLACE LINEA  			WITH _X_LINEA 
*!*			REPLACE DESLIN 			WITH _X_DESLIN 
*!*			REPLACE C_LINEA 		WITH _X_C_LINEA
*!*			REPLACE CODGMI 			WITH _X_CODGMI 
*!*			REPLACE DESGMI 			WITH _X_DESGMI 
*!*			REPLACE DESGMI_1_3		WITH _X_DESGMI_1_3
*!*			REPLACE DESGMI_1_6		WITH _X_DESGMI_1_6
*!*			REPLACE C_GMI  			WITH _X_C_GMI
*!*		ENDIF
*!*		REPLACE GIACEN 			WITH GIACEN 		+ _X_GIACEN
*!*		REPLACE QTAIMP 			WITH QTAIMP 		+ _X_QTAIMP
*!*		*REPLACE CONSISTENZA 	WITH CONSISTENZA	+ _X_CONSISTENZA
*!*		REPLACE VALSTD 			WITH GIACEN 		* _X_PRZSTD
*!*		REPLACE VALULT 			WITH GIACEN 		* _X_PRZULT
*!*		REPLACE VALMEP 			WITH GIACEN 		* _X_PRZMEP
*!*		
*!*		*** POPOLAMENTO CURSORE PER GRIGLIA RAGGRUPPATA PER MAGAZZINO / ARTICOLO / DATA CARICO / SERIAL NUMBER - LOTTO
*!*		_SEEK = _X_CODMAG + _X_CODART + _X_DATCAR + _X_SERIAL
*!*		SELECT C_GIACEN_RAGSN
*!*		GO TOP
*!*		SEEK _SEEK
*!*		IF !FOUND()
*!*			APPEND BLANK
*!*			REPLACE CODMAG WITH _X_CODMAG
*!*			REPLACE CODART WITH _X_CODART
*!*			REPLACE DESART WITH _X_DESART
*!*			REPLACE UM     WITH _X_UM 
*!*			REPLACE GIACEN WITH 0
*!*			REPLACE QTAIMP WITH 0
*!*			REPLACE PRZSTD WITH _X_PRZSTD
*!*			REPLACE PRZULT WITH _X_PRZULT
*!*			REPLACE PRZMEP WITH _X_PRZMEP
*!*			REPLACE DATCAR WITH _X_DATCAR
*!*			REPLACE SERIAL WITH _X_SERIAL
*!*			REPLACE LINEA  	WITH _X_LINEA 
*!*			REPLACE DESLIN 	WITH _X_DESLIN 
*!*			REPLACE C_LINEA WITH _X_C_LINEA
*!*			REPLACE CODGMI 	WITH _X_CODGMI 
*!*			REPLACE DESGMI 	WITH _X_DESGMI 
*!*			REPLACE DESGMI_1_3	WITH _X_DESGMI_1_3
*!*			REPLACE DESGMI_1_6	WITH _X_DESGMI_1_6
*!*			REPLACE C_GMI  	WITH _X_C_GMI
*!*		ENDIF
*!*		REPLACE GIACEN WITH GIACEN + _X_GIACEN
*!*		REPLACE QTAIMP WITH QTAIMP + _X_QTAIMP
*!*		REPLACE VALSTD WITH GIACEN * _X_PRZSTD
*!*		REPLACE VALULT WITH GIACEN * _X_PRZULT
*!*		REPLACE VALMEP WITH GIACEN * _X_PRZMEP
	
	*** POPOLAMENTO CURSORE PER GRIGLIA DETTAGLIATA
	SELECT C_GIACEN_DETT
	APPEND BLANK
	REPLACE CODMAG WITH _X_CODMAG
	REPLACE CODART WITH _X_CODART
	REPLACE DESART WITH _X_DESART
	REPLACE UM     WITH _X_UM 
	REPLACE GIACEN WITH _X_GIACEN
	REPLACE QTAIMP WITH _X_QTAIMP
	REPLACE PRZSTD WITH _X_PRZSTD
	REPLACE PRZULT WITH _X_PRZULT
	REPLACE PRZMEP WITH _X_PRZMEP
	REPLACE PRZEFF WITH _X_PRZEFF  && ERASMO - 07/11/2016
	REPLACE VALSTD WITH GIACEN * _X_PRZSTD
	REPLACE VALULT WITH GIACEN * _X_PRZULT
	REPLACE VALMEP WITH GIACEN * _X_PRZMEP
	REPLACE VALEFF WITH GIACEN * _X_PRZEFF && ERASMO - 07/11/2016	
	
	REPLACE DATCAR WITH _X_DATCAR
	REPLACE ORACAR WITH _X_ORACAR
	REPLACE SERIAL WITH _X_SERIAL
	REPLACE MAG_LEGAME WITH _X_LEGAME  && ERASMO - 12/08/2015
	
	REPLACE LINEA  	WITH _X_LINEA 
	REPLACE DESLIN 	WITH _X_DESLIN 
	REPLACE C_LINEA WITH _X_C_LINEA
	REPLACE CODGMI 	WITH _X_CODGMI 
	REPLACE DESGMI 	WITH _X_DESGMI 
	REPLACE DESGMI_1_3	WITH _X_DESGMI_1_3
	REPLACE DESGMI_1_6	WITH _X_DESGMI_1_6
	REPLACE C_GMI  	WITH _X_C_GMI
	
	REPLACE DTSCAD WITH _X_DTSCAD  && ERASMO - 24/11/2016
	
	REPLACE SEL_DTSCAD WITH .F.  && ERASMO - 01/02/2017
	
*!*		_V_TOT_GIACEN = _V_TOT_GIACEN + _X_GIACEN
*!*		_V_TOT_QTAIMP = _V_TOT_QTAIMP + _X_QTAIMP
*!*		
*!*		_V_TOT_VALMEP = _V_TOT_VALMEP + (GIACEN * _X_PRZMEP)
*!*		_V_TOT_VALSTD = _V_TOT_VALSTD + (GIACEN * _X_PRZSTD)
*!*		_V_TOT_VALULC = _V_TOT_VALULC + (GIACEN * _X_PRZULT)
*!*		_V_TOT_VALEFF = _V_TOT_VALEFF + (GIACEN * _X_PRZEFF) && ERASMO - 07/11/2016
	
    
ENDSCAN
*########################################################################################################################################################################################

LOCAL _DIRECTORY_PDF,_NOME_REPORT

_DIRECTORY_PDF=LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")  && RICERCA PERCORSO
IF !DIRECTORY(_DIRECTORY_PDF)
	*MESSAGEBOX("Directory '" + JUSTDRIVE(_DIRECTORY_PDF) + "' inesistente" + CHR(13) + CHR(13) + ;
		"Non sarà possibile creare correttamente i files PDF",48,"Attenzione")
	RETURN .F.
ENDIF	

_NOME_REPORT = _DIRECTORY_PDF + "\" + "GIACENZE_ALLA_DATA_" + STRTRAN(_V_DATAAL,"/","-") + SYS(2015) + ".XLS"

WAIT WINDOW "ATTENDERE PREGO: creazione excel in corso..." NOWAIT

*SELECT C_GIACEN_DETT
SELECT datcar, oracar,	codmag,	codart,	desart,	um,	serial,	giacen,	qtaimp,	codgmi,	desgmi,	przult,	valult,	przeff,	valeff FROM C_GIACEN_DETT INTO CURSOR XLS_GIACEN_DETT
SELECT XLS_GIACEN_DETT
GO TOP
COPY TO &_NOME_REPORT TYPE XL5

_FILE_DA_ALLEGARE = JUSTFNAME(_NOME_REPORT)

_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 

_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
