************************************
* ORDINI_INSERITI_ECOMMERCE
************************************
LPARAMETERS _TIPOLOGIE,_GIORNI_PRECEDENTI,_STAMPA_RIEPILOGO,_STAMPA_DETTAGLIO

&& _TIPOLOGIE = "TIPOLOGIA IN ('ECC','ECN')"

IF PCOUNT()<4
	RETURN .F.
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

RELEASE V_TITOLO,V_GIORNI_PRECEDENTI
PUBLIC V_TITOLO,V_GIORNI_PRECEDENTI

V_GIORNI_PRECEDENTI = _GIORNI_PRECEDENTI
V_TITOLO = "Ordini inseriti il " + DTOC(DATE() - _GIORNI_PRECEDENTI) + " da e-commerce"

WAIT WINDOWS "ESEGUE PROGRAMMA ORDINI INSERITI DA ECOMMERCE" TIMEOUT 3

*!*	*#### SET DB TEST ####
*!*	PUB_NOMEDB_TEST = "CARDIOLINE_TEST"
*!*	IF !SwicthDBConnection(PUB_NOMEDB_TEST)
*!*	   MESSAGEBOX("DataBase " + PUB_NOMEDB_TEST + " inesistente",16,"Attenzione",5)
*!*	   IF !SetHomeDB()
*!*	      RETURN(.f.)
*!*	   ENDIF
*!*	   RETURN .F.
*!*	ENDIF
*!*	*#### SET DB TEST ####

_ALLEGATI = ""

IF _STAMPA_RIEPILOGO

	cSql=""     
	cNomeCursorSql="CU_ORDINATO"
	TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

		SELECT * FROM (
			SELECT 
				ORT.ORD_RIFERI AS RIFERIMENTO,
				ORT.ORD_TIPOLOGIA AS TIPOLOGIA,
				COALESCE(P_TIPOL.DESCRI,'') AS DESCR_TIPOLOGIA,
				ORT.ORD_CPA AS CPAG,
				COALESCE(P_CPAG.DESCRI,'') AS DESCR_CPAG,
				CLI.CLI_ZONA AS ZONA,
				P1.DESCRI AS DESC_ZONA,
				CLI.CLI_NAZION AS NAZIONE,
				P2.DESCRI AS DESC_NAZIONE,
				CLI.CLI_PROVIN AS PROVINCIA,
				CLI.CLI_CANVEN SALES_CHANNEL,
				P4.DESCRI AS DESC_SALES_CHANNEL,
				ORT.ORD_CODCLI AS CODCLI,
				CLI.CLI_RAGSOC AS RAGSOC,
				ORT.ORD_NUMORD AS NUM_ORDINE,
				ORT.ORD_DATORD AS DATA_ORDINE,
				SUBSTRING(ORT.ORD_DATORD,1,4) AS ANNO,
				SUBSTRING(ORT.ORD_DATORD,6,2) AS MESE,
				ORT.ORD_MOTSCA AS MOTIVAZIONE,
				ORT.ORD_CAMBIO * ORT.ORD_VALORE AS VALORE
			FROM U_ORD_TT AS ORT
			LEFT OUTER JOIN U_CLI_AN AS CLI		ON ORD_CODCLI = CLI_CODCLI
			LEFT OUTER JOIN PARA AS P1		ON 'ZON'+CLI.CLI_ZONA = P1.CODICE
			LEFT OUTER JOIN PARA AS P2		ON 'STA'+CLI.CLI_NAZION = P2.CODICE
			LEFT OUTER JOIN PARA AS P4		ON 'CVE'+CLI.CLI_CANVEN = P4.CODICE
			LEFT OUTER JOIN PARA AS P_TIPOL ON 'TPO'+ORT.ORD_TIPOLOGIA = P_TIPOL.CODICE
			LEFT OUTER JOIN PARA AS P_CPAG 	ON 'CPA'+ORT.ORD_CPA = P_CPAG.CODICE
			) AS MAIN
		
		WHERE <<_TIPOLOGIE>>
			AND DATA_ORDINE = convert(varchar, DATEADD(day, -<<_GIORNI_PRECEDENTI>>, GETDATE()), 111) 
		ORDER BY DESCR_TIPOLOGIA,DATA_ORDINE,NUM_ORDINE
		
	ENDTEXT					&& FINE SCRITTURA QUERY   

	IF !ExecPreparedCommand(cSql,cNomeCursorSql)
		return(.F.)
	ENDIF

	SELECT CU_ORDINATO
	GO TOP

	_PDF_REPORT_		= ALLTRIM(CERCAREPO("XXX","ORDINI_INSERITI_ECOMMERCE","ORDINI_INSERITI_ECOMMERCE.FRX"))
	_PDF_DESCRIZIONE_	= STRTRAN(V_TITOLO,'/','-')+_PROGRESSIVO_PROGRAMMA 
	_PDF_SELECT_ 		= "CU_ORDINATO"

	IF !EMPTY(_PDF_SUBDIR_)
		=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_ )
	ELSE
		=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
	ENDIF

	_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

	_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 
	
ENDIF

IF _STAMPA_DETTAGLIO

	cSql=""     
	cNomeCursorSql="CU_ORDINATO"
	TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

		SELECT * FROM (
			SELECT 
				ORT.ORD_RIFERI AS RIFERIMENTO,
				ORT.ORD_TIPOLOGIA AS TIPOLOGIA,
				COALESCE(P_TIPOL.DESCRI,'') AS DESCR_TIPOLOGIA,
				ORT.ORD_CPA AS CPAG,
				COALESCE(P_CPAG.DESCRI,'') AS DESCR_CPAG,
				ORD.ORD_CCODET AS CENTRO_COSTO,
				CDC.CCODESCR AS DESCR_CENTRO_COSTO,
				CLI.CLI_ZONA AS ZONA,
				P1.DESCRI AS DESC_ZONA,
				CLI.CLI_NAZION AS NAZIONE,
				P2.DESCRI AS DESC_NAZIONE,
				CLI.CLI_PROVIN AS PROVINCIA,
				CLI.CLI_CANVEN SALES_CHANNEL,
				P4.DESCRI AS DESC_SALES_CHANNEL,
				ORT.ORD_CODCLI AS CODCLI,
				CLI.CLI_RAGSOC AS RAGSOC,
				ORT.ORD_NUMORD AS NUM_ORDINE,
				ORT.ORD_DATORD AS DATA_ORDINE,
				ORD.ORD_DATCON AS DATA_CONSEGNA,
				SUBSTRING(ORT.ORD_DATORD,1,4) AS ANNO,
				SUBSTRING(ORT.ORD_DATORD,6,2) AS MESE,
				ORD.ORD_CODART AS CODICE_ART,
				ART.ART_DESCR  AS DESCR_ART,
				ORD.ORD_UM     AS UM,
				ORD.ORD_QTAORD AS QTA_ORDINATA,
				CASE ORD.ORD_PUBBLI
					WHEN 'O' THEN 0
					ELSE ORD.ORD_VALORE
				END * ORT.ORD_CAMBIO AS VALORE,
				ORT.ORD_MOTSCA AS MOTIVAZIONE			
			FROM U_ORD_TT AS ORT
			LEFT OUTER JOIN U_ORD_DD AS ORD		ON ORT.TAGGANCIO=ORD.DAGGANCIO
			LEFT OUTER JOIN U_ART_PR AS ART		ON ORD_CODART = ART_CODPRI
			LEFT OUTER JOIN U_CLI_AN AS CLI		ON ORS_CODCLI = CLI_CODCLI
			LEFT OUTER JOIN (SELECT DISTINCT CON_CONTO AS CCOSTO, CON_DESCR AS CCODESCR, TIPO_CCOSTO  FROM CCOSTO ) AS CDC		ON ORD_CCODET= CCOSTO
			LEFT OUTER JOIN PARA AS P1		ON 'ZON'+CLI.CLI_ZONA = P1.CODICE
			LEFT OUTER JOIN PARA AS P2		ON 'STA'+CLI.CLI_NAZION = P2.CODICE
			LEFT OUTER JOIN PARA AS P4		ON 'CVE'+CLI.CLI_CANVEN = P4.CODICE
			LEFT OUTER JOIN PARA AS P_TIPOL ON 'TPO'+ORT.ORD_TIPOLOGIA = P_TIPOL.CODICE
			LEFT OUTER JOIN PARA AS P_CPAG 	ON 'CPA'+ORT.ORD_CPA = P_CPAG.CODICE
			WHERE ORD_QTAORD<>0
			) AS MAIN
		
		WHERE <<_TIPOLOGIE>>
			AND DATA_ORDINE = convert(varchar, DATEADD(day, -<<_GIORNI_PRECEDENTI>>, GETDATE()), 111) 
		ORDER BY DESCR_TIPOLOGIA,DATA_ORDINE,NUM_ORDINE
		
	ENDTEXT					&& FINE SCRITTURA QUERY           


	IF !ExecPreparedCommand(cSql,cNomeCursorSql)
		return(.F.)
	ENDIF

	SELECT CU_ORDINATO
	GO TOP

	_PDF_REPORT_		= ALLTRIM(CERCAREPO("XXX","ORDINI_INSERITI_ECOMMERCE_DETT","ORDINI_INSERITI_ECOMMERCE_DETT.FRX"))
	_PDF_DESCRIZIONE_	= "Dettaglio - "+STRTRAN(V_TITOLO,'/','-')+_PROGRESSIVO_PROGRAMMA 
	_PDF_SELECT_ 		= "CU_ORDINATO"

	IF !EMPTY(_PDF_SUBDIR_)
		=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_ )
	ELSE
		=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
	ENDIF

	_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

	_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 
	
ENDIF

*!*	*#### RESET DB PRODUZIONE ####
*!*	IF !SetHomeDB()
*!*	  RETURN(.f.)
*!*	ENDIF
*!*	*#### RESET DB PRODUZIONE ####

_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
	
