****************************************************
* ORDINI_FORNITORI_IN_CONSEGNA_NEI_PROSSIMI_N_GIORNI
****************************************************

LPARAMETERS _GIORNI_PRECEDENTI

IF PCOUNT()<1
	RETURN .F.
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

RELEASE V_TITOLO,V_GIORNI_PRECEDENTI
PUBLIC V_TITOLO,V_GIORNI_PRECEDENTI

V_GIORNI_PRECEDENTI = _GIORNI_PRECEDENTI

V_TITOLO	= "Ordini fornitori in consegna nei prossimi " + _GIORNI_PRECEDENTI + " giorni"

WAIT WINDOWS "ESEGUE PROGRAMMA ORDINI_FORNITORI_IN_CONSEGNA_NEI_PROSSIMI_N_GIORNI" TIMEOUT 3

*** REPORT RIEPILOGO
cSql=""     
cNomeCursorSql="CU_ORDINATO_FORNITORE"
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY
		
	SELECT
		TT.ORD_CODCLI AS CODICE_FORNITORE,
		TT.ORD_RAGSOC AS FORNITORE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
		SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
		DD.ORD_CCODET AS CENTRO_COSTO,
		DD.ORD_CODART AS CODICE_ARTICOLO,
		DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
		DD.ORD_DATCON AS DATA_CONSEGNA_RIBALTATA,
		SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
		DD.ORD_UM AS UM,
		DD.ORD_QTAORD AS QTA_ORDINATA,
		DD.ORD_QTAEV AS QTA_EVASA,
		TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
		CASE TT.ORD_FLGCON WHEN 1 THEN 'SI' ELSE 'NO' END AS CONFERMATO
	FROM U_ORF_TT AS TT
	LEFT OUTER JOIN U_ORF_DD AS DD
	ON TT.TAGGANCIO=DD.DAGGANCIO
	WHERE 
		DD.ORD_QTAORD>0
		AND DD.ORD_CHIUSO=0 
		AND TT.ORD_CHIUSO=0
		AND DD.ORD_DATCON <= convert(varchar, DATEADD(day, +<<_GIORNI_PRECEDENTI>>, GETDATE()), 111)
	ORDER BY DD.ORD_DATCON,TT.ORD_NUMORD

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF


SELECT CU_ORDINATO_FORNITORE

_PDF_REPORT_ 		=ALLTRIM(CERCAREPO("XXX","ORDINI_FORNITORI_IN_CONSEGNA_NEI_PROSSIMI_N_GIORNI","ORDINI_FORNITORI_IN_CONSEGNA_NEI_PROSSIMI_N_GIORNI.FRX"))
_PDF_DESCRIZIONE_	= V_TITOLO+_PROGRESSIVO_PROGRAMMA 
_PDF_SELECT_ 		= "CU_ORDINATO_FORNITORE"

IF !EMPTY(_PDF_SUBDIR_ )
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_ )
ELSE
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
ENDIF

_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 


_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
	
