SCARICA_TABELLA_SU_BACKUP("PIANOP_TT")
SCARICA_TABELLA_SU_BACKUP("PIANOP_DD")
SCARICA_TABELLA_SU_BACKUP("PIANOP_MO")
SCARICA_TABELLA_SU_BACKUP("PIANOP_P1")
SCARICA_TABELLA_SU_BACKUP("PIANOP_P2")
SCARICA_TABELLA_SU_BACKUP("PIANOP_SA")

MESSAGEBOX("Operazione terminata.",64,"Backup piani di pagamento")

***********************************
PROCEDURE SCARICA_TABELLA_SU_BACKUP
***********************************
PARAMETERS PNOME_TABELLA

LOCAL NOME_TABELLA,;
      BAK_TABELLA

NOME_TABELLA = ALLTRIM(PNOME_TABELLA)
BAK_TABELLA = "BACKUP_"+NOME_TABELLA

IF !EXECCOMMAND("SELECT * FROM "+NOME_TABELLA,NOME_TABELLA)
	MESSAGEBOX("ERRORE NEL BACKUP DELLA TABELLA "+NOME_TABELLA,48,"ATTENZIONE")
  RETURN
ENDIF	

SELECT &NOME_TABELLA
COPY TO &BAK_TABELLA
USE
