******************************************************
* STAMPA_ALLEGATO_RAPPORTO_CONTROLLO_TREVICALOR
******************************************************

LPARAMETERS _AGGANCIO_E_O_NOMEFILE

IF PCOUNT()<1
	_AGGANCIO_E_O_NOMEFILE = ""
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI_MAIL

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI_MAIL=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_DIRECTORY_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

LOCAL _AGGANCIO,_NOMEFILE
IF "|" $ _AGGANCIO_E_O_NOMEFILE
	_AGGANCIO = ALLTRIM(SUBSTR(_AGGANCIO_E_O_NOMEFILE,1,AT("|",_AGGANCIO_E_O_NOMEFILE,1)-1))
	_NOMEFILE_ZIP_OUT = ALLTRIM(_PDF_DIRECTORY_)+'\'+JUSTSTEM(ALLTRIM(SUBSTR(_AGGANCIO_E_O_NOMEFILE,AT("|",_AGGANCIO_E_O_NOMEFILE,1)+1)))+".ZIP"
ELSE
	_AGGANCIO = ALLTRIM(_AGGANCIO_E_O_NOMEFILE)
	_NOMEFILE_ZIP_OUT = ""
ENDIF

WAIT WINDOWS "ESEGUE PROGRAMMA STAMPA_ALLEGATO_RAPPORTO_CONTROLLO_TREVICALOR" NOWAIT

SET PROCEDURE TO PRG\WINLIB ADDITIVE
SET PROCEDURE TO PRG\AQMLIB ADDITIVE
SET PROCEDURE TO PRG\APPLILIB ADDITIVE

RELEASE PUB_RAGSOC,PUB_PIVA,PUB_INDIRI,PUB_LOCALI,PUB_PROVIN
PUBLIC PUB_RAGSOC,PUB_PIVA,PUB_INDIRI,PUB_LOCALI,PUB_PROVIN
PUB_RAGSOC = ""
PUB_PIVA = ""
PUB_INDIRI = ""
PUB_LOCALI = ""
PUB_PROVIN = ""
Csql = "SELECT * FROM U_AZI_AN"
IF !ExecCommand(cSql,'CU_AZI_AN')
	return(.f.)
ENDIF
SELECT CU_AZI_AN
GO TOP
IF !EOF()
	PUB_RAGSOC = AZI_RAGSOC
	PUB_PIVA = AZI_PIVA
	PUB_INDIRI = AZI_INDIRI
	PUB_LOCALI = AZI_LOCALI
ENDIF
Csql = "SELECT * FROM U_AZI_PB"
IF !ExecCommand(cSql,'CU_AZI_PB')
	return(.f.)
ENDIF
SELECT CU_AZI_PB
GO TOP
IF !EOF()
	PUB_PROVIN = AZI_PROVINCIA
ENDIF


x_soci = "TT.ORD_CODSOC = '" + PUB_CODSOC + "'"
x_agga = "TT.TAGGANCIO = '" + _AGGANCIO + "'"
x_tipo = "TT.ORD_TIPOLOGIA <> '000'"
x_cond = x_soci + " and " + x_agga + " and " + x_tipo

cSql=""
cNomeCursorSql="SEL_RAPPORTO_CONTROLLO"
TEXT TO cSql NOSHOW
	SELECT
		'==>' AS SELEZIONE,
		TAGGANCIO
		,ORD_NUMORD
		,ORD_DATORD
		,ORD_CODCLI
		,ORD_RAGSOC
		,ORD_DTPROGR
		,ORD_CCODSCHE
		,COALESCE(MIN(ORD_ORAINIPRO),'') AS ORD_ORAINIPRO
	FROM (
		SELECT
			 TT.*
			,DT.ORD_ORAINIPRO
		FROM VENDITE_TT AS TT
		LEFT OUTER JOIN VENDITE_DT AS DT ON DT.DAGGANCIO = TT.TAGGANCIO
		WHERE <<X_COND>>
	) AS MAIN
	GROUP BY
		TAGGANCIO
		,ORD_NUMORD
		,ORD_DATORD
		,ORD_CODCLI
		,ORD_RAGSOC
		,ORD_DTPROGR
		,ORD_CCODSCHE
	ORDER BY ORD_DTPROGR,ORD_ORAINIPRO
ENDTEXT
*STRTOFILE(CHR(13)+CHR(10)+"FASE1","STAMPA_ALLEGATO_RAPPORTO_CONTROLLO_TREVICALOR.TXT",.T.)
IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF

WAIT CLEAR

SELECT SEL_RAPPORTO_CONTROLLO
GO TOP
IF EOF()
	MESSAGEBOX("Nessun intervento",16,"Attenzione",1)
	RETURN .F.
ENDIF

IF EMPTY(_NOMEFILE_ZIP_OUT)  && SE NON PASSATO NEI PARAMETRI, DO UN NOME AL FILE ZIP DI DESTINAZIONE
	_NOMEFILE_ZIP_OUT = ALLTRIM(_PDF_DIRECTORY_)+"\ALLEGATI_RAPP_CTRL_INTERV_" + ALLTRIM(ORD_NUMORD) + "_" + ALLTRIM(STRTRAN(ORD_DATORD,"/","-")) + ".ZIP"
ENDIF
*** CANCELLO FILE ZIP DI DESTINAZIONE SE GIA' ESISTENTE
IF FILE(_NOMEFILE_ZIP_OUT,1)
	_COMM='ERASE "'+_NOMEFILE_ZIP_OUT+'"'
	&_COMM
ENDIF

x_csch = ""

SELECT SEL_RAPPORTO_CONTROLLO
GO TOP
DO WHILE .T.
	 
	IF EOF()
		EXIT
	ENDIF
	 
	IF DELETED()
		SKIP +1
		LOOP
	ENDIF
	 
	IF SELEZIONE = "==>"
	ELSE
		SKIP +1
		LOOP
	ENDIF
	
	IF !EMPTY(x_csch)
		x_csch = ALLTRIM(x_csch) + ","
	ENDIF
	x_csch = x_csch + "'" + ALLTRIM(ORD_CCODSCHE) + "'"
		
	SELECT SEL_RAPPORTO_CONTROLLO
	SKIP +1

ENDDO

x_tipo = "DD.TIPO_COMPONENTE <> '002'"
x_csch = "TT.CCODSCHE IN (" + x_csch + ")"
x_cond = x_tipo + " and " + x_csch 
cSql=""
cNomeCursorSql="CU_IMPIANTI_TT_DD_TE"
TEXT TO cSql NOSHOW
	SELECT
		DD.TIPO_COMPONENTE
		,COALESCE(RTRIM(PA_TCI.DESIVA),'') AS _NOME_REPORT_SMALL
		,COALESCE('REPORT\'+RTRIM(PA_TCI.DESIVA)+'.FRX','') AS _NOME_REPORT_SMALL_FRX
		,LTRIM(RTRIM(PK_CATASTO)) AS PK_CATASTO
		,TT.CCODSCHE
		,POT_NOM
		,CINDINS
		,CLOCINS
		,CPROINS
		,CCAPINS
		--,COALESCE(CLI_CODFIS,'') AS CCODFIS
		--,COALESCE(CLI_PARIVA,'') AS CPARIVA
		--,COALESCE(RTRIM(CLI_RAGSOC),'') AS _RAGSOC_RESPONS 
		--,COALESCE(RTRIM(CLI_INDIR),'') + '  ' + COALESCE(RTRIM(CLI_CAP),'') + '  ' + COALESCE(RTRIM(CLI_LOCALI),'') + (CASE COALESCE(RTRIM(CLI_PROVIN),'') WHEN '' THEN '' ELSE '(' + COALESCE(RTRIM(CLI_PROVIN),'') + ')' END) AS _INDIRI_RESPONS
		-- ERASMO - INIZIO 27/05/2024
		,COALESCE(CL.CLI_CODFIS,'') AS CCODFIS
		,COALESCE(CL.CLI_PARIVA,'') AS CPARIVA
		,COALESCE(RTRIM(CR.CLI_RAGSOC),'') AS _RAGSOC_RESPONS 
		,COALESCE(RTRIM(CR.CLI_INDIR),'') + '  ' + COALESCE(RTRIM(CR.CLI_CAP),'') + '  ' + COALESCE(RTRIM(CR.CLI_LOCALI),'') + (CASE COALESCE(RTRIM(CR.CLI_PROVIN),'') WHEN '' THEN '' ELSE '(' + COALESCE(RTRIM(CR.CLI_PROVIN),'') + ')' END) AS _INDIRI_RESPONS
		-- ERASMO - FINE 27/05/2024
		,ID_TIPOANG
		,GRUPPO
		,DBO.RIBALTA2(DD.DT_INSTALL) AS __DT_INSTALL 
		,CDITTACAL
		,ID_MARCATU
		,ID_CLASSIF
		,CMODCAL
		,CMATCAL
		,USO_RISCALDAMENTO
		,USO_H2O_SANITARIA
		,TE.TIPO_CARBU
		,TIPO_TIRAG
		,POT_FOC_KW
		,POT_NOM
		,TT.ID_PMKEY		-- ERASMO - 18/06/2024
		,DD.ID_RIGO			-- ERASMO - 18/06/2024
		,DD.ORD_LINKCOMP	-- ERASMO - 18/06/2024
		,COALESCE((SELECT SUM(POT_FOC_KW) AS POT_NOM_GRUPPO FROM IMPIANTI_TE WHERE ID_PMKEY = TT.ID_PMKEY AND TIPO_COMPONENTE = DD.TIPO_COMPONENTE),'') AS POT_NOM_GRUPPO  -- ERASMO - 12/05/2026
		,CNOTE3  -- ERASMO - 12/05/2026
	FROM IMPIANTI_DD AS DD
	LEFT OUTER JOIN IMPIANTI_TT AS TT ON DD.ID_PMKEY = TT.ID_PMKEY
	LEFT OUTER JOIN IMPIANTI_TE AS TE ON TE.ID_PMKEY = TT.ID_PMKEY AND TE.TIPO_COMPONENTE = DD.TIPO_COMPONENTE AND TE.ID_RIGO = DD.ID_RIGO
	LEFT OUTER JOIN U_CLI_AN AS CL ON CL.CLI_CODCLI = TT.CCODCLI
	LEFT OUTER JOIN U_CLI_AN AS CR ON CR.CLI_CODCLI = TT.ID_RESPONS
	LEFT OUTER JOIN PARA AS PA_TCI ON 'TCI'+DD.TIPO_COMPONENTE = PA_TCI.CODICE
	WHERE <<x_cond>>
	ORDER BY CCODSCHE
ENDTEXT

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF

_ERRORE = .F.
SELECT CU_IMPIANTI_TT_DD_TE
GO TOP
SCAN	
	IF EMPTY(_NOME_REPORT_SMALL)
		LOOP
	ENDIF
	
	SCATTER MEMVAR MEMO
	
	*** VARIABILI CAMPI PERSONALIZZATI (SE CONFIGURATI PER QUEL TIPO COMPONENTE)
	x_tipo = "CT.TIPO_COMPONENTE = '" + ALLTRIM(M.TIPO_COMPONENTE) + "'"
	x_pmky = "CC.ID_PMKEY = '" + ALLTRIM(M.ID_PMKEY) + "'"
	x_idrg = "CC.ID_RIGO = '" + ALLTRIM(M.ID_RIGO) + "'"
	x_link = "CC.LINKCOMP = '" + ALLTRIM(M.ORD_LINKCOMP) + "'"
	x_cond = x_tipo + " and " + x_pmky + " and " + x_idrg + " and " + x_link 
	cSql=""
	cNomeCursorSql="TMP_IMPIANTI_CT_CC"
	TEXT TO cSql NOSHOW
		SELECT
			CT.*,
			CC.VALORE,
			CC.VALORE_MEMO
		FROM IMPIANTI_CT AS CT
		LEFT OUTER JOIN IMPIANTI_CC AS CC ON CC.TIPO_COMPONENTE = CT.TIPO_COMPONENTE AND CC.ID_RIGA_CONF = CT.ID_RIGA_CONF
		WHERE <<x_cond>>
		ORDER BY CT.ORDINAMENTO
	ENDTEXT
	
	IF !ExecPreparedCommand(cSql,cNomeCursorSql)
		return(.F.)
	ENDIF
	SELECT TMP_IMPIANTI_CT_CC
	GO TOP
	SCAN
		_name = "M."+UPPER(ALLTRIM(NOME_X_REPORT))
		_value = ALLTRIM(VALORE)
		IF TIPO = 'M'
			_value = ALLTRIM(VALORE_MEMO)
		ENDIF
		&_name = _value
	ENDSCAN
	
	x_codi = "CODICE = 'TCI" + ALLTRIM(M.TIPO_COMPONENTE) + "'"
	x_cond = x_codi
	cSql = "select * from PARA where " + x_cond
	IF !ExecCommand(cSql,"TMP_PARA")
		RETURN .F.
	ENDIF
	SELECT TMP_PARA
	GO TOP
	
	RELEASE FILE_PDF_APPENA_GENERATO
	PUBLIC FILE_PDF_APPENA_GENERATO
	FILE_PDF_APPENA_GENERATO = ""
	
	_PDF_DESCRIZIONE_	= ALLTRIM(M._NOME_REPORT_SMALL)+"_"+ALLTRIM(M.TIPO_COMPONENTE)+"_"+ALLTRIM(M.ID_PMKEY)+"_"+ALLTRIM(M.ID_RIGO)
	_PDF_SELECT_ 		= "TMP_PARA"
	_PDF_REPORT_ 		= ALLTRIM(M._NOME_REPORT_SMALL_FRX)
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
	IF !EMPTY(ALLTRIM(FILE_PDF_APPENA_GENERATO)) AND FILE(FILE_PDF_APPENA_GENERATO,1)
		STRTOFILE(CHR(13)+CHR(10)+"FASE6.6: "+FILE_PDF_APPENA_GENERATO,"STAMPA_ALLEGATO_RAPPORTO_CONTROLLO_TREVICALOR.TXT",.T.)
		IF !CREATE_ZIP_FILE(FILE_PDF_APPENA_GENERATO,_NOMEFILE_ZIP_OUT,.F.)
			_COMM='ERASE "'+FILE_PDF_APPENA_GENERATO+'"'
			&_COMM
			MESSAGEBOX("ERRORE DURANTE LA CREAZIONE DEL FILE ZIP",16,"Attenzione",1)
			RETURN(.F.)
		ENDIF
		_COMM='ERASE "'+FILE_PDF_APPENA_GENERATO+'"'
		&_COMM
		
	ELSE
		_ERRORE = .T.
	ENDIF
	
	*** RILASCIO VARIABILI CAMPI PERSONALIZZATI
	SELECT TMP_IMPIANTI_CT_CC
	GO TOP
	SCAN
		_name = "M."+UPPER(ALLTRIM(NOME_X_REPORT))
		RELEASE &_name
	ENDSCAN
	
ENDSCAN

SELECT SEL_RAPPORTO_CONTROLLO
USE

SELECT CU_IMPIANTI_TT_DD_TE
USE

IF FILE(_NOMEFILE_ZIP_OUT,1)
	_ALLEGATI_MAIL = JUSTFNAME(_NOMEFILE_ZIP_OUT)
ENDIF

*_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI_MAIL,_ID_EMAIL_DA_INVIARE

SELECT(_SAVE_SEL )
