******************************************************
* STAMPA_RAPPORTO_LAVORO_TREVICALOR
******************************************************

*LPARAMETERS _AGGANCIO
LPARAMETERS _AGGANCIO_E_O_NOMEFILE  && ERASMO - 10/01/2025

IF PCOUNT()<1
	*_AGGANCIO = ""
	_AGGANCIO_E_O_NOMEFILE = ""  && ERASMO - 10/01/2025
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI_MAIL

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI_MAIL=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_DIRECTORY_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

*!*	RELEASE V_TITOLO,V_GIORNI_PRECEDENTI
*!*	PUBLIC V_TITOLO,V_GIORNI_PRECEDENTI

*!*	V_GIORNI_PRECEDENTI = _GIORNI_PRECEDENTI
*!*	V_META_SCADENZA = _META_SCADENZA

*!*	V_TITOLO = "Ordini fornitori da contattare per conferma consegna entro " + _GIORNI_PRECEDENTI + " giorni"
*!*	IF V_META_SCADENZA
*!*		V_TITOLO = "Ordini fornitori da contattare per conferma consegna a metà scadenza"
*!*	ENDIF

**=> ERASMO - INIZIO 10/01/2025
LOCAL _AGGANCIO,_NOMEFILE
IF "|" $ _AGGANCIO_E_O_NOMEFILE
	_AGGANCIO = ALLTRIM(SUBSTR(_AGGANCIO_E_O_NOMEFILE,1,AT("|",_AGGANCIO_E_O_NOMEFILE,1)-1))
	_NOMEFILE = ALLTRIM(SUBSTR(_AGGANCIO_E_O_NOMEFILE,AT("|",_AGGANCIO_E_O_NOMEFILE,1)+1))
ELSE
	_AGGANCIO = ALLTRIM(_AGGANCIO_E_O_NOMEFILE)
	_NOMEFILE = ""
ENDIF  
**=> ERASMO - FINE 10/01/2025

*WAIT WINDOWS "ESEGUE PROGRAMMA STAMPA_RAPPORTO_LAVORO_TREVICALOR" TIMEOUT 3
WAIT WINDOWS "ESEGUE PROGRAMMA STAMPA_RAPPORTO_LAVORO_TREVICALOR" NOWAIT  && ERASMO - 23/04/2025

x_soci = "TT.ORD_CODSOC = '" + PUB_CODSOC + "'"
IF !EMPTY(ALLTRIM(_AGGANCIO))
	x_agga = "TT.TAGGANCIO = '" + _AGGANCIO + "'"
ELSE
	x_agga = "TT.ORD_DTPROGR = '" + RIBALTA2(DTOC(DATE())) + "'"
ENDIF
x_cond = x_soci + " and " + x_agga

cSql=""
cNomeCursorSql="SEL_RAPPORTO_LAVORO"
TEXT TO cSql NOSHOW
	SELECT
		SPACE(10) AS SELEZIONE,
		TAGGANCIO
		,ORD_NUMORD
		,ORD_DATORD
		,ORD_CODCLI
		,ORD_RAGSOC
		,ORD_DTPROGR
		,ORD_CCODSCHE
		,COALESCE(MIN(ORD_ORAINIPRO),'') AS ORD_ORAINIPRO
	FROM (
		SELECT
			 TT.*
			,DT.ORD_ORAINIPRO
		FROM VENDITE_TT AS TT
		LEFT OUTER JOIN VENDITE_DT AS DT ON DT.DAGGANCIO = TT.TAGGANCIO
		WHERE <<X_COND>>
	) AS MAIN
	GROUP BY
		TAGGANCIO
		,ORD_NUMORD
		,ORD_DATORD
		,ORD_CODCLI
		,ORD_RAGSOC
		,ORD_DTPROGR
		,ORD_CCODSCHE
	ORDER BY ORD_DTPROGR,ORD_ORAINIPRO
ENDTEXT

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF

WAIT CLEAR

SELECT SEL_RAPPORTO_LAVORO
GO TOP
IF EOF()
	MESSAGEBOX("Nessun intervento da stampare",16,"Attenzione",3)
	RETURN .F.
ENDIF

*!*	DO prg\browseview WITH "SEL_RAPPORTO_LAVORO","Selezione Interventi per stampa Rapporti di lavoro","ORD_CCODSCHE:Impianto,W:10;ORD_DTPROGR:Dt.esecuz.,W:10;" + ;
*!*		"ORD_ORAINIPRO:Ora in. progr.,W:10;ORD_NUMORD:Nr.interv.,W:10;ORD_DATORD:Dt.reg.,W:20;ORD_CODCLI:Cod.Cliente,W:10;ORD_RAGSOC:Rag.Sociale,W:40;",600,800,.T.,.F.
*!*	IF NumeroRecordLetti = 0
*!*		MESSAGEBOX("Selezionare almeno un intervento",16,"Attenzione")
*!*		RETURN .F.
*!*	ENDIF

*!*	DO CASE
*!*		CASE _V_OPZSTA = 1
*!*			_RISP = MESSAGEBOX("Stampare i documenti selezionati?",36,"Attenzione")
*!*		CASE _V_OPZSTA = 2
*!*			_RISP = MESSAGEBOX("Visualizzare in anteprima i documenti selezionati?",36,"Attenzione")
*!*		OTHERWISE
*!*			RETURN .F.
*!*	ENDCASE

*!*	_cSavePrinterName = ""
*!*	IF TYPE('alltrim(set("PRINTER",3))') == 'C'
*!*		_cSavePrinterName = alltrim(set("PRINTER",3))
*!*	ENDIF

*!*	IF _RISP = 6
*!*		IF _V_OPZSTA = 1
*!*			
*!*			*** FACCIO SELEZIONARE DALL'UTENTE LA STAMPANTE SU CUI INVIARE LA STAMPA
*!*			_cSelPrinterName = GETPRINTER()
*!*			IF !EMPTY(_cSelPrinterName)
*!*				_set_printer_cmd = "SET PRINTER TO NAME '" + _cSelPrinterName + "'"
*!*				&_set_printer_cmd
*!*			ELSE
*!*				MESSAGEBOX("Operazione annullata",48,"Informazione")
*!*				RETURN .F.
*!*			ENDIF
*!*			
*!*		ENDIF
*!*	ELSE
*!*		RETURN
*!*	ENDIF

RELEASE PUB_NOMOPE,PUB_CAUCAS,PUB_NOIVASPINC,PUB_NOLOGO
PUBLIC PUB_NOMOPE,PUB_CAUCAS,PUB_NOIVASPINC,PUB_NOLOGO
PUB_NOMOPE = ""
PUB_CAUCAS = ""
PUB_NOIVASPINC = .F.
PUB_NOLOGO = .F.

Csql = "SELECT * FROM RES_OPER WHERE CODICE = '" + PUB_CODOPE + "'"
IF !ExecCommand(cSql,'CU_RES_OPER')
	return(.f.)
ENDIF
SELECT CU_RES_OPER
GO TOP
IF !EOF()
	PUB_NOMOPE = DESCRI
ENDIF

Csql = "SELECT AZI_CAUCAS FROM U_AZI_AN"
IF !ExecCommand(cSql,'CU_AZI_AN')
	return(.f.)
ENDIF
SELECT CU_AZI_AN
GO TOP
IF !EOF()
	PUB_CAUCAS = AZI_CAUCAS
ENDIF

Csql = "SELECT AZI_NOIVASPINC,AZI_NOLOGO FROM U_AZI_PB"
IF !ExecCommand(cSql,'CU_AZI_PB')
	return(.f.)
ENDIF
SELECT CU_AZI_PB
GO TOP
IF !EOF()
	PUB_NOIVASPINC = AZI_NOIVASPINC
	PUB_NOLOGO = AZI_NOLOGO
ENDIF

SET PROCEDURE TO PRG\APPLILIB ADDITIVE
SET PROCEDURE TO PRG\RISTAMPELIB ADDITIVE
SET PROCEDURE TO PRG\REPLIB ADDITIVE
SET PROCEDURE TO PRG\CONTABILELIB ADDITIVE  && ERASMO 13/05/2026

_V_ARCH_DD = "VENDITE_DD"
_V_ARCH_STA = 'X' + _V_ARCH_DD
IF !ExecCommand("select * from &_V_ARCH_DD where 0=1",_V_ARCH_STA)
   return(.f.)
ENDIF

_ALLEGATI_MAIL = ""
PUB_CREA_FILE_PDF = .T.
_ERRORE = .F.

SELECT SEL_RAPPORTO_LAVORO
GO TOP
DO WHILE .T.
	 
	IF EOF()
		EXIT
	ENDIF
	 
	IF DELETED()
		SKIP +1
		LOOP
	ENDIF
	 
*!*		IF SELEZIONE = "==>"
*!*		ELSE
*!*			SKIP +1
*!*			LOOP
*!*		ENDIF

	_XX_DATORD = ORD_DATORD
	_XX_NUMORD = ORD_NUMORD
	_XX_CODCLI = ORD_CODCLI
	_XX_AGGANC = TAGGANCIO  && ERASMO - 07/11/2024
	
	x_soci = "ord_codsoc = '" + PUB_CODSOC + "'"
	x_dord = "ord_datord = '" + _XX_DATORD + "'"
	x_nord = "ord_numord = '" + _XX_NUMORD + "'"
	x_agga = "taggancio = '" + _XX_AGGANC + "'"  && ERASMO - 07/11/2024
	*x_cond = x_soci + " and " + x_dord + " and " + x_nord
	x_cond = x_soci + " and " + x_dord + " and " + x_nord + " and " + x_agga  && ERASMO - 07/11/2024
	cSql	= "select * from VENDITE_TT where " + x_cond
	IF !ExecCommand(cSql,"CVENDITE_TT")
		return(.f.)
	ENDIF
	SELECT CVENDITE_TT
	DELETE FOR ORD_CODCLI <> _XX_CODCLI
	GO TOP
	SCATTER MEMVAR MEMO
	
	*THISFORM.cerca_dettagli()
	
	IF USED("U_DOC_DD")
		SELECT U_DOC_DD
		USE
	ENDIF

	SELECT &_V_ARCH_STA
	SET FILTER TO
	SET ORDER TO
	ZAP

	** RIEMPIE IL CURSORE DI TUTTI I DETTAGLI DOCUMENTO  --------------------------------------------------------------*
	x_agga = "daggancio = '" + M.TAGGANCIO + "'"
	x_cond = x_agga
	Csql = "select * from VENDITE_DD where " + x_cond + " order by ord_sequen"  
	IF !ExecCommand(cSql,"U_DOC_DD")
		return(.f.)
	ENDIF
	SELECT U_DOC_DD
	GO TOP

	DO WHILE .T.

		IF EOF()
			EXIT
		ENDIF

		IF DELETED()
			SKIP +1
			LOOP
		ENDIF
		
		SCATTER MEMVAR MEMO
		
		SELECT &_V_ARCH_STA
		APPEND BLANK
		
		M.ORS_NUMORD = M.ORD_NUMORD 
		M.ORS_DATORD = M.ORD_DATORD 
		M.ORS_CODCLI = M.ORD_CODCLI		 
		
		DO &_V_ARCH_DD
			
		SELECT U_DOC_DD
		SKIP +1

	ENDDO
	
	SELECT CVENDITE_TT
	GO TOP
	SCATTER MEMVAR MEMO
	
	_cPROGRAMMA__ = "INRPJITA_SMALL"
	_cREPORTNEW__ = "INRPJITA.FRX"
	_cREPORT__    = ALLTRIM(CERCAREPO("XXX",_cPROGRAMMA__,_cREPORTNEW__))
	_V_OPZSTA     = 999
	
	SELECT CVENDITE_TT
	DO RISTA_INR WITH _cREPORT__
	
	IF !EMPTY(ALLTRIM(FILE_PDF_APPENA_GENERATO)) AND FILE(FILE_PDF_APPENA_GENERATO,1)
		_FILE_PDF_APPENA_GENERATO_NEW = ALLTRIM(_PDF_DIRECTORY_) + '\' + JUSTFNAME(FILE_PDF_APPENA_GENERATO)
		_run = 'MOVE "' + ALLTRIM(FILE_PDF_APPENA_GENERATO) + '" "' + ALLTRIM(_PDF_DIRECTORY_) + '"'
		RUN &_run
		IF FILE(_FILE_PDF_APPENA_GENERATO_NEW,1)
		
			**=> ERASMO - INIZIO 10/01/2025
			*** SE PASSATO NEI PARAMETRI, RINOMINO IL FILE GENERATO
			IF !EMPTY(_NOMEFILE)
				_FILE_PDF_APPENA_GENERATO_NEW_RENAMED = JUSTPATH(_FILE_PDF_APPENA_GENERATO_NEW) + "\" + _NOMEFILE
				_cmd = 'RENAME "' + _FILE_PDF_APPENA_GENERATO_NEW + '" TO "' + _FILE_PDF_APPENA_GENERATO_NEW_RENAMED + '"'
				&_cmd
				IF FILE(_FILE_PDF_APPENA_GENERATO_NEW_RENAMED,1)
					_FILE_PDF_APPENA_GENERATO_NEW = _FILE_PDF_APPENA_GENERATO_NEW_RENAMED
				ENDIF				
			ENDIF  
			**=> ERASMO - FINE 10/01/2025
		
			_ALLEGATI_MAIL = ALLTRIM(_ALLEGATI_MAIL) + IIF(EMPTY(ALLTRIM(_ALLEGATI_MAIL)),"",";") + JUSTFNAME(ALLTRIM(_FILE_PDF_APPENA_GENERATO_NEW))
		ELSE
			_ERRORE = .T.
		ENDIF
	ELSE
		_ERRORE = .T.
	ENDIF
		
	SELECT SEL_RAPPORTO_LAVORO
	SKIP +1

ENDDO

SELECT U_DOC_DD
USE

SELECT &_V_ARCH_STA
USE

SELECT CVENDITE_TT
USE
	
SELECT SEL_RAPPORTO_LAVORO
USE

*_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI_MAIL,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
	
