
*DO SETLIB
SET STEP ON
_V_NOME_FILE_XML = "IT02406660064BNXBB_0000E"
_V_ARCHIVEID = "754e7dea-9e14-4c52-a9c4-bea03dd87a85"
_V_DIRECTORY = "D:\doc_aquarius\FATTURE_ELETTRONICHE_FORNITORI"
_V_OK_DOWNLOADED = BLUENEXT_GETFILE(_V_NOME_FILE_XML,_V_ARCHIVEID,_V_DIRECTORY)
IF !_V_OK_DOWNLOADED
	MESSAGEBOX("Errore")
ELSE
	MESSAGEBOX("File scaricato correttamente nella directory " + ALLTRIM(_V_DIRECTORY))
ENDIF
