CLEAR ALL
CLOSE ALL

SET MULTILOCKS ON
PUBLIC pub_sqlhd,pub_datawh
pub_sqlhd  = 0
pub_datawh = ""

SET PROCEDURE TO SQLLIB 	ADDITIVE

** Impostazione SET Iniziali
SET STATUS BAR OFF
SET AUTOSAVE ON
SET CENTURY ON
SET CLOCK STATUS

****** SET DATE TO GERMAN

SET DATE TO DMY

SET DELETED ON
SET ESCAPE OFF
SET EXACT ON
SET EXCLUSIVE OFF
SET HOURS TO 24
SET NEAR ON
SET REPROCESS TO AUTOMATIC
SET SAFETY OFF
SET TALK OFF
SET MARK TO "/"
SET DECIMAL TO 6  && GESTIONE EURO

_screen.Caption="Tra-Pdv-Sede"
_screen.WindowState= 1
*_screen.Visible=.f.

** Aggancio librerie di procedure esterne
SET PROCEDURE TO TRALIB	ADDITIVE

RELEASE PUB_CODSOC,PUB_CODBUN,PUB_CFDEF
PUBLIC  PUB_CODSOC,PUB_CODBUN,PUB_CFDEF
PUB_CODSOC = '01'
PUB_CODBUN = ""
PUB_CFDEF  = ""

DO WHILE .T.

   IF FILE("TRA_PDV.SEM")
   	  ERASE TRA_PDV.SEM
      EXIT
   ENDIF

   *IF !BETWEEN(TIME(),"06:00:00","23:59:59")
   *   WAIT WINDOW "" TIMEOUT 5
   *   LOOP 
   *ENDIF

   DO GESTIONE_TRAPDVSEDE

   WAIT WINDOW "" TIMEOUT 5

ENDDO

CLOSE DATABASES ALL
CLOSE DATABASES
CLOSE DATA ALL
 
RETURN

