************************
* ULTIMI_ORDINI_INSERITI
************************
LPARAMETERS _NR_GIORNI,_COD_NAZ

IF PCOUNT()<1
	RETURN .F.
ENDIF

IF PCOUNT()<2
	_COD_NAZ = ""
ENDIF

LOCAL _SAVE_SEL,_PDF_SUBDIR_,_FILE_DA_ALLEGARE,_PDF_DESCRIZIONE_,_PDF_SELECT_ ,_PDF_REPORT_ ,_PROGRESSIVO_PROGRAMMA,_ALLEGATI

_SAVE_SEL = SELECT()
_PROGRESSIVO_PROGRAMMA = SYS(2015)

_ALLEGATI=""
_FILE_DA_ALLEGARE=""
_PDF_DESCRIZIONE_=""
_PDF_SELECT_ =""
_PDF_REPORT_ =""
_PDF_SUBDIR_ = LEGGE_CONFIG("AQ_SCHEDULER_CONFIG.CFG","PATH_EMAIL")	&& RICERCA DIRECTORY E SOTTODIRECTORY CONTENENTE IL FILE PDF DA CREARE

RELEASE V_TITOLO,V_NR_GIORNI,V_COD_NAZ
PUBLIC V_TITOLO,V_NR_GIORNI,V_COD_NAZ

V_NR_GIORNI = _NR_GIORNI
V_COD_NAZ = _COD_NAZ
V_TITOLO = "Ordini clienti " + IIF(EMPTY(V_COD_NAZ),"",V_COD_NAZ+" ") + "inseriti negli ultimi " + ALLTRIM(STR(_NR_GIORNI,10,0)) + " giorni"

WAIT WINDOWS "ESEGUE PROGRAMMA ULTIMI_ORDINI_INSERITI" TIMEOUT 3

*** REPORT RIEPILOGO
cSql=""     
cNomeCursorSql="CU_ORDINATO"
TEXT TO cSql NOSHOW  	&& INIZIO SCRITTURA QUERY

	SELECT 	
		ORD_CODCLI AS CODICE_CLIENTE,
		ORD_RAGSOC AS CLIENTE,
		ORD_NUMORD AS NUM_ORDINE,
		DBO.RIBALTA2(ORD_DATORD) AS DATA_ORDINE_RIBALTATA, 
		ORD_DATORD AS DATA_ORDINE,
		CLI_CANVEN AS CANALE_VENDITA,
		COALESCE(PARA_CVE.DESCRI,'') AS DESCRIZIONE_CANALE_VENDITA,
		ORD_CAMBIO * ORD_VALORE AS VALORE_TOTALE
	FROM U_ORD_TT
	LEFT OUTER JOIN U_CLI_AN ON U_CLI_AN .CLI_CODCLI = U_ORD_TT.ORD_CODCLI
	LEFT OUTER JOIN PARA AS PARA_CVE ON PARA_CVE.CODICE = 'CVE'+U_CLI_AN.CLI_CANVEN
	WHERE ORD_DATORD >= convert(varchar, DATEADD(day, - <<ALLTRIM(STR(V_NR_GIORNI,10,0))>>, GETDATE()), 111) AND CLI_NAZION = <<IIF(EMPTY(V_COD_NAZ),"CLI_NAZION","'"+V_COD_NAZ+"'")>>
	ORDER BY DESCRIZIONE_CANALE_VENDITA,CLIENTE,NUM_ORDINE

ENDTEXT					&& FINE SCRITTURA QUERY

IF !ExecPreparedCommand(cSql,cNomeCursorSql)
	return(.F.)
ENDIF


SELECT CU_ORDINATO

_PDF_REPORT_ 		=ALLTRIM(CERCAREPO("XXX","ULTIMI_ORDINI_INSERITI","ULTIMI_ORDINI_INSERITI.FRX"))
_PDF_DESCRIZIONE_	= V_TITOLO+_PROGRESSIVO_PROGRAMMA 
_PDF_SELECT_ 		= "CU_ORDINATO"

IF !EMPTY(_PDF_SUBDIR_ )
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_,_PDF_SUBDIR_ )
ELSE
	=CREA_FILE_PDF(_PDF_SELECT_,_PDF_REPORT_,_PDF_DESCRIZIONE_)
ENDIF

_FILE_DA_ALLEGARE = ALLTRIM(_PDF_DESCRIZIONE_)+".PDF"

_ALLEGATI = _ALLEGATI + IIF(EMPTY(_ALLEGATI),"",";")+_FILE_DA_ALLEGARE 


_ERRORE =.F.
DO PRG\INVIA_MAIL_SCHEDULATE WITH _ERRORE,_ALLEGATI ,_ID_EMAIL_DA_INVIARE


SELECT(_SAVE_SEL )
	
