
RELEASE _V_DATADA,_V_DATAAL,_V_CODMAG,_V_DESMAG
PUBLIC _V_DATADA,_V_DATAAL,_V_CODMAG,_V_DESMAG

_V_DATADA = "01/01/2000"
_V_DATAAL = "31/12/"+PUB_ANNO
_V_CODMAG = ""
_V_DESMAG = ""

_CONTINUA = .F.
DO FORM FORM\VALORE_MAGAZZINO_L3A_SEL_FILTRI LINKED
IF !_CONTINUA
	MESSAGEBOX("Operazione abbandonata",48,"Informazione")
	RETURN .F.
ENDIF

WAIT WINDOWS "Estrazione saldo movimenti per valorizzazione magazzino alla data..." NOWAIT

cSql=""
cNomeCursorSql="SALDO_MOVIMENTI"
TEXT TO cSql NOSHOW

	SELECT * FROM (
		SELECT 
			MOV_CODMAG AS COD_MAGAZZINO,
			COALESCE(PARA_MAG.DESCRI,'') AS DESCR_MAGAZZINO,
			ART_CODMAT AS COD_TIPO_PRODOTTO,
			COALESCE(PARA_MAT.DESCRI,'') AS DESCR_TIPO_PRODOTTO,
			MOV_ANAART AS COD_ARTICOLO,
			ART_UMMAGA AS UM_MAG,
			SUM((CASE MOV_SEGNO WHEN '-' THEN -1 ELSE 1 END) * MOV_QTAMOV) AS SALDO_QTAMOV,
			ART_UNIMIS AS UM_ACQ,
			CASE ART_UNIMIS
				WHEN 'KG' THEN SUM((CASE MOV_SEGNO WHEN '-' THEN -1 ELSE 1 END) * MOV_QTAKG) 
				ELSE SUM((CASE MOV_SEGNO WHEN '-' THEN -1 ELSE 1 END) * MOV_QTAMOV)
			END AS SALDO_QTA_X_VAL,
			CASE ART_UNIMIS
				WHEN 'KG' THEN SUM((CASE MOV_SEGNO WHEN '-' THEN -1 ELSE 1 END) * MOV_QTAKG * MOV_PREACQ)
				ELSE SUM((CASE MOV_SEGNO WHEN '-' THEN -1 ELSE 1 END) * MOV_QTAMOV * MOV_PREACQ)
			END AS SALDO_VALORE	
		FROM ( 
		
			SELECT 
				MOV_DTREGI,
				MOV_CODMAG,
				MOV_ANAART,
				MOV_CODART,
				MOV_SEGNO,
				CASE
					WHEN (SELECT ART_UNIMIS FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'KG' AND ((SELECT ART_CODCAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'BO' OR (SELECT SUBSTRING(LIBERA,1,1) FROM PARA WHERE CODICE = 'MAT'+(SELECT ART_CODMAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART)) = '1')
						THEN COALESCE((SELECT TOP 1 MOV_QTAMOV FROM U_MAG_MO AS TMP_MO WHERE TMP_MO.MOV_SEGNO = '+' AND U_MAG_MO.mov_codart = TMP_MO.MOV_CODART AND TMP_MO.MOV_CODART <> TMP_MO.MOV_ANAART ORDER BY mov_dtregi,mov_oramov),MOV_QTAMOV)
					ELSE MOV_QTAMOV
				END AS MOV_QTAMOV,
				CASE
					WHEN (SELECT TOP 1 ART_UNIMIS FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'KG' AND (SELECT TOP 1 ART_UNIMIS FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = (SELECT TOP 1 ART_UMMAGA FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART)
						THEN MOV_QTAMOV
					WHEN (SELECT TOP 1 ART_UNIMIS FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'KG' AND ((SELECT TOP 1 ART_CODCAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'BO' OR (SELECT TOP 1 SUBSTRING(LIBERA,1,1) FROM PARA WHERE CODICE = 'MAT'+(SELECT TOP 1 ART_CODMAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART)) = '1')
						THEN COALESCE((SELECT TOP 1 MOV_QTAKG FROM U_MAG_MO AS TMP_MO WHERE TMP_MO.MOV_SEGNO = '+' AND U_MAG_MO.mov_codart = TMP_MO.MOV_CODART AND TMP_MO.MOV_CODART <> TMP_MO.MOV_ANAART ORDER BY mov_dtregi,mov_oramov),MOV_QTAMOV)
					ELSE MOV_QTAKG
				END AS MOV_QTAKG,
				CASE
					WHEN (SELECT TOP 1 ART_UNIMIS FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'KG' AND ((SELECT TOP 1 ART_CODCAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART) = 'BO' OR (SELECT TOP 1 SUBSTRING(LIBERA,1,1) FROM PARA WHERE CODICE = 'MAT'+(SELECT TOP 1 ART_CODMAT FROM U_ART_PR WHERE ART_CODPRI = MOV_ANAART)) = '1')
					THEN COALESCE((SELECT TOP 1 MOV_PREACQ FROM U_MAG_MO AS TMP_MO WHERE TMP_MO.MOV_SEGNO = '+' AND U_MAG_MO.mov_codart = TMP_MO.MOV_CODART AND TMP_MO.MOV_CODART <> TMP_MO.MOV_ANAART ORDER BY mov_dtregi,mov_oramov),MOV_QTAMOV)
					ELSE MOV_PREACQ
				END AS MOV_PREACQ
			FROM U_MAG_MO
			WHERE 
				MOV_QTAMOV > 0 AND 
				MOV_CODMAG = '<<_V_CODMAG>>' AND 
				MOV_DTREGI >= '<<RIBALTA2(_V_DATADA)>>' AND 
				MOV_DTREGI <= '<<RIBALTA2(_V_DATAAL)>>'
			) AS U_MAG_MO
		LEFT OUTER JOIN U_ART_PR ON MOV_ANAART = ART_CODPRI
		LEFT OUTER JOIN PARA AS PARA_MAT ON 'MAT'+U_ART_PR.ART_CODMAT = PARA_MAT.CODICE
		LEFT OUTER JOIN PARA AS PARA_MAG ON 'MAG'+U_MAG_MO.MOV_CODMAG = PARA_MAG.CODICE
		GROUP BY 
			MOV_CODMAG,
			COALESCE(PARA_MAG.DESCRI,''),
			ART_CODMAT,
			COALESCE(PARA_MAT.DESCRI,''),
			MOV_ANAART,
			ART_UNIMIS,
			ART_UMMAGA
		) AS MAIN
	WHERE SALDO_QTAMOV <> 0
	ORDER BY 
		COD_MAGAZZINO,
		COD_TIPO_PRODOTTO,
		COD_ARTICOLO
		
ENDTEXT
IF !ExecPreparedCommand(cSql,cNomeCursorSql,.T.)
	return(.F.)
ENDIF
*** SE L'UTENTE HA ANNULLATO LA QUERY IL CURSORE POTREBBE NON ESISTERE, 
*** QUINDI NON PERMETTO DI ANDARE AVANTI
IF !USED("SALDO_MOVIMENTI")
	RETURN .F.
ENDIF

SELECT SALDO_MOVIMENTI
GO TOP
IF EOF()
	MESSAGEBOX("Nessun dato da estrarre per i filtri selezionati",64,"Informazione")
ELSE
	_TITOLO_EXCEL1 = "Estrazione saldo movimenti per valorizzazione magazzino alla data"
	_TITOLO_EXCEL2 = "Periodo di riferimento dal " + _V_DATADA + " al " + _V_DATAAL
	_TITOLO_EXCEL3 = ""
	_TOTALI_GENERALI = .T.
	DO ESTRXLS WITH "SALDO_MOVIMENTI",_TITOLO_EXCEL1,_TITOLO_EXCEL2,_TITOLO_EXCEL3,_TOTALI_GENERALI
	
	MESSAGEBOX("Fine elaborazione",64,"Informazione")
ENDIF

