-- VISTA BONIFICI_CLIENTI_PER_ANNO_SETT

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BONIFICI_CLIENTI_PER_ANNO_SETT]'))
	DROP VIEW [dbo].[BONIFICI_CLIENTI_PER_ANNO_SETT]
GO

CREATE VIEW [dbo].[BONIFICI_CLIENTI_PER_ANNO_SETT]
AS
	SELECT
		MAIN.MOV_ANNO AS ANNO,
		CAST(DATEPART(WEEK,CAST(MAIN.MOV_DTREG AS date)) AS NUMERIC(2,0)) AS SETTIMANA,
		MAIN.MOV_NREGIS AS NR_REG,
		MAIN.MOV_CONTO AS COD_CLIENTE,
		MAIN.CON_DESCR AS RAG_SOCIALE,
		MAIN.MOV_IMPORTO AS IMPORTO_TOT_PAG,
		PC.PAR_NPROT AS NUM_FAT,
		DBO.RIBALTA2(PC.PAR_DTFAT) AS DATA_FAT,
		DBO.RIBALTA2(PC.PAR_DTSCAD) AS DATA_SCAD,
		CASE PC.PAR_TMOV WHEN 'A' THEN 1 ELSE -1 END * PC.PAR_FATT AS IMPORTO_SCAD
	FROM (
		SELECT
			MOV_NUMPRO,
			MOV_ANNO,
			MOV_NREGIS,
			MOV_DTREG,
			MOV_CONTO,
			CONTI.CON_DESCR,
			SUM(CASE MOV_TMOV WHEN 'A' THEN 1 ELSE -1 END * MOV_IMP) AS MOV_IMPORTO
		FROM MOV_CONT AS MC
		LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = MC.MOV_ANNO AND CONTI.CON_CONTO = MC.MOV_CONTO
		WHERE MOV_TOP IN (SELECT SUBSTRING(CODICE,4,10) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,1,1) = 'A' AND SUBSTRING(LIBERA,2,1) = 'P' AND SUBSTRING(LIBERA,10,1) = 'N' AND SUBSTRING(LIBERA,12,1) = 'C' AND SUBSTRING(LIBERA,42,1) = 'C') AND CONTI.CON_TIPOCO = 'C'
		GROUP BY MOV_NUMPRO,MOV_ANNO,MOV_NREGIS,MOV_DTREG,MOV_CONTO,CON_DESCR
		) AS MAIN
	LEFT OUTER JOIN PART_CLI AS PC ON PC.PAR_NUMPRO = MAIN.MOV_NUMPRO AND PC.PAR_CODCLI = MAIN.MOV_CONTO AND PC.PAR_NPROG <> '100'

GO

SELECT * FROM BONIFICI_CLIENTI_PER_ANNO_SETT WHERE ANNO = '2024' AND SETTIMANA = 41 ORDER BY NR_REG
