
/****** Object:  View [dbo].[DETTAGLI_FATTURE_PER_CONTO_RICAVO]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DETTAGLI_FATTURE_PER_CONTO_RICAVO]'))
	DROP VIEW [dbo].[DETTAGLI_FATTURE_PER_CONTO_RICAVO]
GO
CREATE VIEW [dbo].[DETTAGLI_FATTURE_PER_CONTO_RICAVO]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_DATORD AS DATA_FATTURA,
		TT.ORD_NUMORD AS NUM_FATTURA,
		TT.ord_TIPOLOGIA AS TIPO_ORDINE,
		COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
		DD.ORD_CONDET AS CONTO_RICAVO,
		COALESCE(CON.CON_DESCR,'') AS DES_CONTO_RICAVO,
		DD.ORD_CODART AS ARTICOLO,
		DD.ORD_DESART AS DESARTICOLO,
		DD.ORD_CCODET AS CENTRCOSTO,
		COALESCE(CC.CON_DESCR,'') AS CENTRCOSTO_DESCRIZIONE,
		CASE DD.ORD_PUBBLI
			WHEN 'O' THEN 0
			ELSE (CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) * DD.ORD_PRZNET*DD.ORD_QTAORD*TT.ORD_CAMBIO
		END AS EURO_PRNETTO_QUANTITA,
		CASE DD.ORD_PUBBLI
			WHEN 'O' THEN (CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) * DD.ORD_PRZNET*DD.ORD_QTAORD*TT.ORD_CAMBIO
			ELSE (CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END) * (DD.ORD_PREZZO - DD.ORD_PRZNET)*DD.ORD_QTAORD*TT.ORD_CAMBIO
		END AS SCONTO_QUANTITA,
		CASE SUBSTRING(CAUSAL.LIBERA,11,1) WHEN 'S' THEN -1 ELSE 1 END * DD.ORD_QTAORD AS QUANTITA,
		TT.ORD_IDSDI AS COD_DESTINATARIO_SDI,
		DD.ORD_IVA AS COD_IVA,
		COALESCE(IVA.DESCRI,'') AS DESCR_IVA
	FROM U_FAT_DD AS DD
	LEFT OUTER JOIN U_FAT_TT AS TT
	ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR
	ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_AN AS ARTAN
	ON DD.ORD_CODART = ARTAN.ART_CODPRI
	LEFT OUTER JOIN CCOSTO AS CC
	ON DD.ORD_CCODET = CC.CON_CONTO AND CC.CON_ANNO = TT.ORD_ANNO
	LEFT OUTER JOIN U_CLI_AN AS CLI
	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS TIPORD ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN PARA AS CAUSAL ON CAUSAL.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS IVA ON IVA.CODICE = 'IVA'+DD.ORD_IVA
	LEFT OUTER JOIN CONTI AS CON ON CON.CON_ANNO = TT.ORD_ANNO AND CON.CON_CONTO = DD.ORD_CONDET
	WHERE DD.ORD_CODART <> '' AND TT.ORD_DATORD <> '2999/12/31'

GO

SELECT * FROM DETTAGLI_FATTURE_PER_CONTO_RICAVO WHERE ANNO >= 2026