-- VISTA FATTURE_DA_SALDARE_O_SALDATE_PER_CLIENTE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_DA_SALDARE_O_SALDATE_PER_CLIENTE]'))
	DROP VIEW [dbo].[FATTURE_DA_SALDARE_O_SALDATE_PER_CLIENTE]
GO

CREATE VIEW [dbo].[FATTURE_DA_SALDARE_O_SALDATE_PER_CLIENTE]
AS

	SELECT 
		SUBSTRING(RIGHE_PART.PAR_DTFAT,1,4) AS ANNO_FATTURA,
		COALESCE(FAT_DD.ORD_CCODET,'') AS COD_CENTRO_COSTO,
		COALESCE(CCOSTO.CON_DESCR,'') AS DESCR_CENTRO_COSTO,
		SUBSTRING(RIGHE_PART.PAR_CODCLI,5,10) AS COD_CLIENTE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NPROT AS NUM_FATTURA,
		RIGHE_PART.PAR_DTFAT AS DATA_FATTURA,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS IMPORTO_SCAD_PAG,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) - ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS RESIDUO_SCAD_PAG,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		ROUND(FAT_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		ROUND(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO + FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,2) AS IMPONIBILE_IMPOSTA_TOT_FATTURA,
		ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		ROUND(COALESCE(FAT_TT.ORD_IMPONIB*FAT_TT.ORD_CAMBIO,0),2) AS IMPONIBILE_TOT_FATTURA,
		ROUND(COALESCE(FAT_TT.ORD_IMPOSTA*FAT_TT.ORD_CAMBIO,0),2) AS IMPOSTA_TOT_FATTURA,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA2,
		CASE
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0
				THEN COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN COALESCE(PAG_ULT.PAR_DTREG,'')
			ELSE ''
		END AS DATA_PAGAMENTO,
		CASE
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))) AS datetime))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_ULT.PAR_DTREG,'')) AS datetime))
			ELSE 0
		END AS NR_GIORNI_RITARDO,
		CAST(coalesce(stuff((select  ',' + ORD.ORD_NUMORC
                    from    U_ORD_TT as ORD
                    where   ORD.ORD_NUMORD+ORD.ORD_DATORD = FAT_DD.ORS_NUMORC+FAT_DD.ORS_DATORC
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS NUM_ORDINE_DEL_CLIENTE,
		CAST(COALESCE(
			STUFF(
				(SELECT 
					CHAR(13) + CHAR(10) + CAST(FAD.ORD_NOTE AS VARCHAR(8000))
				 FROM U_FAT_DD AS FAD
				 WHERE FAD.DAGGANCIO = FAT_TT.TAGGANCIO 
				   AND ORD_DESART = '*** COMMENTO ***'
				 ORDER BY FAD.ORD_SEQUEN
				 FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)')
			, 1, 2, '') -- Nota: qui usiamo 2 per rimuovere sia CHAR(13) che CHAR(10) iniziali
		, '') AS NVARCHAR(254)) AS COMMENTI_FATTURA
	FROM PART_CLI AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) <> 'S')  GROUP BY PAR_CODCLI, PAR_NPART) AS FAT_TOT ON FAT_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAT_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, COALESCE(MAX(PAR_DTREG),'') AS PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) AS IMPORTO_SCAD_PAG, CASE WHEN SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) <> 0 THEN (SUM(PAR_FATT * PAR_CAMBIO * CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END)) ELSE 0 END AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS ULT_IMPORTO_SCAD_PAG FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS PAG_ULT
		LEFT OUTER JOIN (SELECT DISTINCT ORD_CCODET, ORS_NUMORD, ORS_DATORD, ORS_NUMORC, ORS_DATORC FROM U_FAT_DD WHERE ORD_DESART <> '*** COMMENTO ***') AS FAT_DD ON FAT_DD.ORS_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_DD.ORS_DATORD = RIGHE_PART.PAR_DTFAT
		RIGHT OUTER JOIN U_FAT_TT AS FAT_TT ON FAT_TT.ORD_NUMORD = RIGHE_PART.PAR_NPROT AND FAT_TT.ORD_DATORD = RIGHE_PART.PAR_DTFAT
		LEFT OUTER JOIN CCOSTO ON CCOSTO.CON_ANNO = SUBSTRING(FAT_DD.ORS_DATORD,1,4) AND CCOSTO.CON_CONTO = FAT_DD.ORD_CCODET
		OUTER APPLY (SELECT (SUM(PAR_FATT * PAR_CAMBIO * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO)) AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_CLI WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD) AS MEDIA_PAG
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'D' AND COALESCE(SUBSTRING(PARA_TOP.LIBERA,2,1),'') IN ('S','F','A') AND SUBSTRING(PARA_TOP.LIBERA,11,1) <> 'S')
		--AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAT_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))
		--AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)

GO

SELECT * FROM FATTURE_DA_SALDARE_O_SALDATE_PER_CLIENTE WHERE COD_CLIENTE = '500007829' ORDER BY DATA_FATTURA,NUM_FATTURA