-- VISTA FATTURE_FORNITORI_DA_SALDARE_O_SALDATE_ULTIMO_ANNO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_FORNITORI_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]'))
	DROP VIEW [dbo].[FATTURE_FORNITORI_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
GO

CREATE VIEW [dbo].[FATTURE_FORNITORI_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
AS

	SELECT
		SUBSTRING(RIGHE_PART.PAR_CODCLI,5,10) AS COD_FORNITORE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NUMFAT AS NUM_FATTURA,
		RIGHE_PART.PAR_DTFAT AS DATA_FATTURA,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) AS IMPORTO_SCAD_PAG,
		ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) - ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS RESIDUO_SCAD_PAG,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		ROUND(FAT_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		CASE
			--WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAT_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			WHEN ABS(ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) - ROUND(COALESCE(FAT_TOT.IMPORTO_TOTALE,0),2)) <= 0.01 THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO,
		RIGHE_PART.PAR_DTSCAD AS DATA_SCADENZA2,
		CASE
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0
				THEN COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN COALESCE(PAG_ULT.PAR_DTREG,'')
			ELSE ''
		END AS DATA_PAGAMENTO,
		CASE
			--WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) >= ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))) AS datetime))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_ULT.PAR_DTREG,'')) AS datetime))
			ELSE 0
		END AS NR_GIORNI_RITARDO
	FROM PART_FOR AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' GROUP BY PAR_CODCLI, PAR_NPART) AS FAT_TOT ON FAT_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAT_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_TOTALE_PAG FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'D' GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO) AS IMPORTO_SCAD_PAG FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'D' GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS ULT_IMPORTO_SCAD_PAG FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'D' AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS PAG_ULT
		OUTER APPLY (SELECT TOP 1 PAR_ANNO,PAR_DTSCAD,PAR_NPROT,PAR_DTFAT FROM PART_FOR WHERE PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_NPROG <> 100 AND PAR_TMOV = 'A' AND PAR_TIPODO = 'FAT' ORDER BY PAR_DTSCAD) AS TEST_PART
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'A' AND RIGHE_PART.PAR_TIPODO = 'FAT')
		--AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAT_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))		
		AND ((ABS(ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) - ROUND(COALESCE(FAT_TOT.IMPORTO_TOTALE,0),2)) > 0.01) OR (RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111)))
		AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)
GO

SELECT * FROM FATTURE_FORNITORI_DA_SALDARE_O_SALDATE_ULTIMO_ANNO ORDER BY DATA_FATTURA,NUM_FATTURA