
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VALORE_MOVIMENTI_MPF_SEDE_PER_MESE]'))
	DROP VIEW [dbo].[VALORE_MOVIMENTI_MPF_SEDE_PER_MESE]
GO

CREATE VIEW [dbo].[VALORE_MOVIMENTI_MPF_SEDE_PER_MESE]  
AS

	SELECT * FROM (
		SELECT
			ANNO,
			MESE,
			'MPF SCARICO (PAT/PRG/PRL/PSD/RE-/ROT/TM/VEN/VG/VK)' AS TIPO_REC,
			CAST(ROUND(SUM(EUR_VALACQ),2) AS NUMERIC(19,2)) as VALORE
		FROM (
			SELECT
				SUBSTRING(T1.MOV_DTREGI,1,4) AS ANNO,
				SUBSTRING(T1.MOV_DTREGI,6,2) AS MESE,
				T1.MOV_QTAMOV * COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) * COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS EUR_VALACQ
			FROM U_MAG_MO AS T1
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU, MOV_CODCTL FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = T1.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
				(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = T1.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= T1.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU
			WHERE T1.MOV_CODMAG = 'MPF' AND T1.MOV_TOP IN ('PAT','PRG','PRL','PSD','RE-','ROT','TM','VEN','VG','VK') AND T1.MOV_DOCMOD = 0
			) AS MAIN
		GROUP BY ANNO,MESE
		UNION
		SELECT
			ANNO,
			MESE,
			'MPF CARICO (BC/CAP/CMR/CGE/RE+/CF)' AS TIPO_REC,
			CAST(ROUND(SUM(EUR_VALACQ),2) AS NUMERIC(19,2)) as VALORE
		FROM (
			SELECT
				SUBSTRING(T1.MOV_DTREGI,1,4) AS ANNO,
				SUBSTRING(T1.MOV_DTREGI,6,2) AS MESE,
				T1.MOV_QTAMOV * COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) * COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS EUR_VALACQ
			FROM U_MAG_MO AS T1
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU, MOV_CODCTL FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = T1.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
				(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = T1.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= T1.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU
			WHERE T1.MOV_CODMAG = 'MPF' AND T1.MOV_TOP IN ('BC','CAP','CMR','CGE','RE+','CF') AND T1.MOV_DOCMOD = 0
			) AS MAIN
		GROUP BY ANNO,MESE
		UNION
		SELECT
			ANNO,
			MESE,
			'SEDE SCARICO (PAT/PRG/PRL/PSD/RE-/ROT/USD/RES/PRE)' AS TIPO_REC,
			CAST(ROUND(SUM(EUR_VALACQ),2) AS NUMERIC(19,2)) as VALORE
		FROM (
			SELECT
				SUBSTRING(T1.MOV_DTREGI,1,4) AS ANNO,
				SUBSTRING(T1.MOV_DTREGI,6,2) AS MESE,
				T1.MOV_QTAMOV * COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) * COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS EUR_VALACQ
			FROM U_MAG_MO AS T1
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU, MOV_CODCTL FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = T1.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
				(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = T1.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= T1.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU
			WHERE T1.MOV_CODMAG = 'SEDE' AND T1.MOV_TOP IN ('PAT','PRG','PRL','PSD','RE-','ROT','USD','RES','PRE') AND T1.MOV_DOCMOD = 0
			) AS MAIN
		GROUP BY ANNO,MESE
		UNION
		SELECT
			ANNO,
			MESE,
			'SEDE CARICO (BC/CAP/CMR/CGE/RE+)' AS TIPO_REC,
			CAST(ROUND(SUM(EUR_VALACQ),2) AS NUMERIC(19,2)) as VALORE
		FROM (
			SELECT
				SUBSTRING(T1.MOV_DTREGI,1,4) AS ANNO,
				SUBSTRING(T1.MOV_DTREGI,6,2) AS MESE,
				T1.MOV_QTAMOV * COALESCE(VV.VVA_CHANGE,VVU.VVA_CHANGE,1) * COALESCE(MV.MOV_PREACQ,MVU.MOV_PREACQ,0) AS EUR_VALACQ
			FROM U_MAG_MO AS T1
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU, MOV_CODCTL FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = T1.MOV_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV 
			OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_PREACQ, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_LEGAME = 
				(SELECT TOP 1 MOV_LEGAME FROM U_MAG_MO WHERE MOV_ANAART = T1.MOV_ANAART AND MOV_SEGNO = '+' AND MOV_DTREGI <= T1.MOV_DTREGI ORDER BY MOV_DTREGI DESC,MOV_ORAMOV DESC) ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MVU
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
			OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MVU.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MVU.MOV_DTDOCU = '' THEN MVU.MOV_DTREGI ELSE MVU.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VVU
			WHERE T1.MOV_CODMAG = 'SEDE' AND T1.MOV_TOP IN ('BC','CAP','CMR','CGE','RE+') AND T1.MOV_DOCMOD = 0
			) AS MAIN
		GROUP BY ANNO,MESE
		) AS G1

GO


SELECT * FROM VALORE_MOVIMENTI_MPF_SEDE_PER_MESE WHERE ANNO = '2025' AND MESE = '09' ORDER BY TIPO_REC