
-- VISTA ORDINATO_BUNDLE_ECOMMERCE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_BUNDLE_ECOMMERCE]'))
	DROP VIEW [dbo].[ORDINATO_BUNDLE_ECOMMERCE]
GO

CREATE VIEW [dbo].[ORDINATO_BUNDLE_ECOMMERCE]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		TT.ORD_DATORD AS DATA_ORDINE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		COALESCE(P_APP.DESCRI,'') AS GRUPPO,
		TT.ORD_CODCLI AS COD_CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_PROVIN AS PROVINCIA,
		TT.ORD_PARIVA AS P_IVA,
		DD.ORD_CODART AS COD_ARTICOLO,
		DD.ORD_DESART AS DESCR_ARTICOLO,
		DD.ORD_QTAORD AS QUANTITA_ORDINATA,
		DD.ORD_VALORE AS VALORE_ORDINATO,
		DD.ORD_IVA AS COD_IVA,
		--CAST(SUBSTRING(COALESCE(P_IVA.LIBERA,'000'),1,3) AS NUMERIC(3,0)) AS ALIQUOTA_IVA,
		DD.ORD_VALORE * (1 + (CAST(SUBSTRING(COALESCE(P_IVA.LIBERA,'000'),1,3) AS NUMERIC(3,0)) / 100)) AS VALORE_ORDINATO_IVATO,
		'' AS FEE_CORMAN,
		--SUBSTRING(DB.ORD_NOTEBO,1,30) AS COD_BUNDLE,
		--SUBSTRING(DB.ORD_NOTE,1,CHARINDEX(' - ',SUBSTRING(DB.ORD_NOTE,1,30))-1) AS COD_BUNDLE,
		CASE WHEN (CHARINDEX(' - ',SUBSTRING(DB.ORD_NOTE,1,30))-1) > 0 THEN SUBSTRING(DB.ORD_NOTE,1,CHARINDEX(' - ',SUBSTRING(DB.ORD_NOTE,1,30))-1) ELSE '' END AS COD_BUNDLE,  -- ERASMO - 30/08/2024
		DD.ORD_SEQUEN AS N_RIGA
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_DD AS DB ON DB.DAGGANCIO = DD.DAGGANCIO AND DB.ORD_CODSYS = DD.KEY_AGG
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_CLI_AN AS CLI ON CLI.CLI_CODCLI = TT.ORD_CODCLI
	LEFT OUTER JOIN PARA AS P_APP ON P_APP.CODICE = 'APP'+CLI.CLI_APPPRO
	LEFT OUTER JOIN PARA AS P_IVA ON P_IVA.CODICE = 'IVA'+DD.ORD_IVA
	WHERE DD.DAGGANCIO IN (SELECT TAGGANCIO FROM U_ORD_TT WHERE ORD_TIPOLOGIA = 'ECC') AND DD.KEY_AGG <> '' AND DD.ORD_CODART <> '' AND DD.ORD_DESART <> '*** COMMENTO ***'

GO

--SELECT * FROM ORDINATO_BUNDLE_ECOMMERCE WHERE DATA_ORDINE >= '' ORDER BY DATA_ORDINE,NUM_ORDINE,N_RIGA