
-- VISTE PER ESTRAZIONE DATI DA ANAGRAFICA ARTICOLI PER IL CONTROLLE DEL LEAD TIME


-- VISTA ANAGRAFICA_ARTICOLI_LEAD_TIME
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_LEAD_TIME]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_LEAD_TIME]
GO
CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_LEAD_TIME]  
AS
	SELECT
		PR.ART_TIPART AS TIPO_ARTICOLO,
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCR_ARTICOLO,
		AN.ART_LDTMST AS LEAD_TIME_STANDARD,
		PR.ART_CODF1 AS COD_FORN_1, COALESCE(F1.FOR_RAGSOC,'') AS RAG_SOC_FORN_1, AN.ART_LDTM1 AS LEAD_TIME_FORN_1, PR.ART_PRZCO1 AS PREZZO_FORN_1, COALESCE(F1.FOR_VALUTA,'') AS VALUTA_FORN_1, 
		PR.ART_CODF2 AS COD_FORN_2, COALESCE(F2.FOR_RAGSOC,'') AS RAG_SOC_FORN_2, AN.ART_LDTM2 AS LEAD_TIME_FORN_2, PR.ART_PRZCO2 AS PREZZO_FORN_2, COALESCE(F2.FOR_VALUTA,'') AS VALUTA_FORN_2, 
		PR.ART_CODF3 AS COD_FORN_3, COALESCE(F3.FOR_RAGSOC,'') AS RAG_SOC_FORN_3, AN.ART_LDTM3 AS LEAD_TIME_FORN_3, PR.ART_PRZCO3 AS PREZZO_FORN_3, COALESCE(F3.FOR_VALUTA,'') AS VALUTA_FORN_3, 
		PR.ART_CODF4 AS COD_FORN_4, COALESCE(F4.FOR_RAGSOC,'') AS RAG_SOC_FORN_4, AN.ART_LDTM4 AS LEAD_TIME_FORN_4, PR.ART_PRZCO4 AS PREZZO_FORN_4, COALESCE(F4.FOR_VALUTA,'') AS VALUTA_FORN_4, 
		PR.ART_CODF5 AS COD_FORN_5, COALESCE(F5.FOR_RAGSOC,'') AS RAG_SOC_FORN_5, AN.ART_LDTM5 AS LEAD_TIME_FORN_5, PR.ART_PRZCO5 AS PREZZO_FORN_5, COALESCE(F5.FOR_VALUTA,'') AS VALUTA_FORN_5
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON PR.ART_CODSOC = AN.ART_CODSOC AND PR.ART_CODPRI = AN.ART_CODPRI
	LEFT OUTER JOIN U_FOR_AN AS F1 ON PR.ART_CODF1 = F1.FOR_CODCLI
	LEFT OUTER JOIN U_FOR_AN AS F2 ON PR.ART_CODF2 = F2.FOR_CODCLI
	LEFT OUTER JOIN U_FOR_AN AS F3 ON PR.ART_CODF3 = F3.FOR_CODCLI
	LEFT OUTER JOIN U_FOR_AN AS F4 ON PR.ART_CODF4 = F4.FOR_CODCLI
	LEFT OUTER JOIN U_FOR_AN AS F5 ON PR.ART_CODF5 = F5.FOR_CODCLI

GO


SELECT * FROM [ANAGRAFICA_ARTICOLI_LEAD_TIME]

