-- VISTA ORDINI_NON_EVASI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_NON_EVASI]'))
	DROP VIEW [dbo].[ORDINI_NON_EVASI]
GO

CREATE VIEW [dbo].[ORDINI_NON_EVASI]  
AS

SELECT T1.*,CCO.CON_DESCR AS DESCRIZIONE_CENTRO_COSTO FROM (
SELECT
	TT.ORD_CODCLI AS CODICE_CLIENTE,
	TT.ORD_RAGSOC AS CLIENTE,
	TT.ORD_NUMORD AS NUM_ORDINE,
	TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
	DD.ORD_CCODET AS CENTRO_COSTO,
	DD.ORD_CODART AS CODICE_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
	DD.ORD_DATCON AS DATA_CONSEGNA_RIBALTATA,
	SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA_ORDINATA,
	TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
	TT.ORD_MOTSCA AS MOTIVAZIONE
FROM U_ORD_TT AS TT
LEFT OUTER JOIN U_ORD_DD AS DD
ON TT.TAGGANCIO=DD.DAGGANCIO
WHERE 
	DD.ORD_QTAORD>0
	AND DD.ORD_CHIUSO=0 
	AND TT.ORD_CHIUSO=0
) AS T1
LEFT OUTER JOIN (SELECT DISTINCT CON_CONTO, CON_DESCR FROM  CCOSTO) AS CCO
ON T1.CENTRO_COSTO = CON_CONTO
WHERE 
	--T1.CODICE_CLIENTE <> (SELECT TOP 1 AZI_CODCLI FROM U_AZI_AN)
	T1.CODICE_ARTICOLO NOT LIKE '.%'

GO

