
-- VISTA ORDINATO FORNITORI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_FORNITORI]'))
	DROP VIEW [dbo].[ORDINATO_FORNITORI]
GO

CREATE VIEW [dbo].[ORDINATO_FORNITORI]  
AS
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_DATORD AS DATA_DOC_RIBALTATA,
		SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_DOC,
		DD.ORD_DATCON AS DTE_PREV_EVASIONE_RIBALTATA,
		SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_PREV_EVASIONE,
		TT.ORD_CAUS AS CAUSALE,
		COALESCE(CAUS.DESCRI,'') AS DES_CAUSALE,
		--TT.ord_TIPOLOGIA AS TIPO_ORDINE,
		--COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		--CLI.CLI_CANVEN AS CANALE_VENDITA,
		--COALESCE(CVEN.DESCRI,'')  AS DESCRI_CANALE_VENDITA,
		TT.ORD_CODCLI AS CODICE_FORNITORE,
		FORN.FOR_RAGSOC AS RAGIONE_SOCIALE,	
		'' AS REGIONE,
		FORN.FOR_NAZION AS NAZIONE,
		COALESCE(CNAZION.DESCRI,'') AS DESNAZIONE,
		FORN.FOR_ZONA AS ZONA,
		COALESCE(CZONA.DESCRI,'') AS DESZONA,
		FORN.FOR_PROVIN AS SUBZONA,
		COALESCE(CC.CON_DESCR,'') AS BU,
		DD.ORD_CODART AS ARTICOLO,
		DD.ORD_DESART AS DESARTICOLO,
		SUBSTRING(ARTAN.ART_CODGMI,1,3) AS GRUPPO,
		CCODGRU.DESCRI AS DESGRUPPO,
		SUBSTRING(ARTAN.ART_CODGMI,1,6) AS FAMIGLIA,
		CCODFAM.DESCRI AS DESFAMIGLIA,
		ARTAN.ART_CODGMI AS SOTTOFAMIGLIA,
		CCODMERC.DESCRI AS DESSOTTOFAMIGLIA,
		DD.ORD_CCODET AS CENTRCOSTO,
		COALESCE(CC.CON_DESCR,'') AS CENTRCOSTO_DESCRIZIONE,
		DD.ORD_PRZNET*DD.ORD_QTAEV AS PRNETTO_EVASO,
		DD.ORD_PRZNET*DD.ORD_QTAORD AS PRNETTO_QUANTITA,
		DD.ORD_PRZNET*(DD.ORD_QTAORD-DD.ORD_QTAEV) AS PRNETTO_DA_EVADERE,
		TT.ORD_VALUTA AS VALUTA,
		TT.ORD_CAMBIO AS CAMBIO,
		TT.ORD_CAMBIO*DD.ORD_PRZNET*DD.ORD_QTAEV AS EURO_PRNETTO_EVASO,
		TT.ORD_CAMBIO*DD.ORD_PRZNET*DD.ORD_QTAORD AS EURO_PRNETTO_QUANTITA,
		TT.ORD_CAMBIO*DD.ORD_PRZNET*(DD.ORD_QTAORD-DD.ORD_QTAEV) AS EURO_PRNETTO_DA_EVADERE,
		(DD.ORD_PREZZO - DD.ORD_PRZNET)*DD.ORD_QTAORD AS SCONTO_QUANTITA,
		DD.ORD_QTAORD AS ORDINATO,
		DD.ORD_QTAEV AS EVASO_TOT,
		DD.ORD_QTAORD-DD.ORD_QTAEV AS DA_EVADERE,
		CAST(coalesce(stuff((select  ',' + RTRIM(BFO.ORS_NUMORD)
                    from    U_BFO_DD as BFO
                    where   DD.DAGGANCIO = BFO.ORD_LEGAME AND DD.ORD_CODSYS = BFO.ORD_LEGASY
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS NUM_BFO,
		CAST(coalesce(stuff((select distinct  ',' + SUBSTRING(BFO.ORS_DATORD,9,2)+'/'+SUBSTRING(BFO.ORS_DATORD,6,2)+'/'+SUBSTRING(BFO.ORS_DATORD,1,4)
                    from    U_BFO_DD as BFO
                    where   DD.DAGGANCIO = BFO.ORD_LEGAME AND DD.ORD_CODSYS = BFO.ORD_LEGASY
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS DATA_BFO,
		CAST(coalesce(stuff((select  ',' + RTRIM(BFO_TT.ORD_NUMIDE)
                    from    U_BFO_DD as BFO LEFT OUTER JOIN U_BFO_TT AS BFO_TT ON BFO_TT.TAGGANCIO = BFO.DAGGANCIO
                    where   DD.DAGGANCIO = BFO.ORD_LEGAME AND DD.ORD_CODSYS = BFO.ORD_LEGASY
                    for xml path('')
                ),1,1,''),'') AS nvarchar(254)) AS ID_BFO,
		CAST(coalesce(stuff((select  distinct ',' + RTRIM(BFO.CBF_NDOC)
                    from    U_BFO_DD as BFO
                    where   DD.DAGGANCIO = BFO.ORD_LEGAME AND DD.ORD_CODSYS = BFO.ORD_LEGASY
                    for xml path('')
                ),1,1,''),'') AS nvarchar(127))	AS NUM_FAT,
		CAST(coalesce(stuff((select  distinct ',' + SUBSTRING(BFO.CBF_DTDOC,9,2)+'/'+SUBSTRING(BFO.CBF_DTDOC,6,2)+'/'+SUBSTRING(BFO.CBF_DTDOC,1,4)
                    from    U_BFO_DD as BFO
                    where   DD.DAGGANCIO = BFO.ORD_LEGAME AND DD.ORD_CODSYS = BFO.ORD_LEGASY
                    for xml path('')
                ),1,1,''),'') AS nvarchar(127)) AS DATA_FAT,
		PR.ART_ULPCAR AS ULT_PREZZO_ACQUISTO
	FROM U_ORF_DD AS DD
	LEFT OUTER JOIN U_ORF_TT AS TT
	ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_ART_PR AS PR
	ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_AN AS ARTAN
	ON DD.ORD_CODART = ARTAN.ART_CODPRI
	LEFT OUTER JOIN CCOSTO AS CC
	ON DD.ORD_CCODET = CC.CON_CONTO AND TT.ORD_ANNO = CC.CON_ANNO
	LEFT OUTER JOIN U_FOR_AN AS FORN
	ON TT.ORD_CODCLI = FORN.FOR_CODCLI 
	--LEFT OUTER JOIN PARA AS CVEN
	--ON CVEN.CODICE = 'CVE'+FORN.FOR_CANVEN  
	LEFT OUTER JOIN PARA AS CZONA
	ON CZONA.CODICE = 'ZON'+FORN.FOR_ZONA  
	LEFT OUTER JOIN PARA AS CNAZION
	ON CNAZION.CODICE = 'STA'+FORN.FOR_NAZION  
	LEFT OUTER JOIN PARA AS CCODMERC
	ON CCODMERC.CODICE = 'GMI'+ARTAN.ART_CODGMI 
	LEFT OUTER JOIN PARA AS CCODGRU
	ON CCODGRU.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS CCODFAM
	ON CCODFAM.CODICE = 'GMI'+SUBSTRING(ARTAN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS CAUS
	ON CAUS.CODICE = 'TOP'+TT.ORD_CAUS
	--LEFT OUTER JOIN PARA AS TIPORD
	--ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	WHERE DD.ORD_QTAORD<>0
GO
