-- VISTA BILANCIO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BILANCIO]'))
	DROP VIEW [dbo].[BILANCIO]
GO

CREATE VIEW [dbo].[BILANCIO]  
AS

SELECT 
	MOV_ANNO AS ANNO,
	MOV_CONTO AS CONTO,
	CON_DESCR AS DESCR_CONTO,
	SUM(CASE WHEN MOV_CONTABILITA_PREVISIONALE<>'P' THEN CASE WHEN MOV_TMOV='D' THEN MOV_IMP ELSE -1 * MOV_IMP END ELSE 0 END) AS IMPORTO,
	SUM(CASE WHEN MOV_CONTABILITA_PREVISIONALE='P' THEN CASE WHEN MOV_TMOV='D' THEN MOV_IMP ELSE -1 * MOV_IMP END ELSE 0 END) AS IMPORTO_PREV
FROM MOV_CONT AS ECO
LEFT OUTER JOIN CONTI 
ON MOV_CONTO=CON_CONTO AND MOV_ANNO=CON_ANNO
GROUP BY MOV_ANNO,MOV_CONTO,CON_DESCR 


GO