-- VISTA FATTURATO_DA_PRIMANOTA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_DA_PRIMANOTA]'))
	DROP VIEW [dbo].[FATTURATO_DA_PRIMANOTA]
GO

CREATE VIEW [dbo].[FATTURATO_DA_PRIMANOTA]  
AS

	SELECT 
		PAT.MOV_ANNO AS ANNO,
		SUBSTRING(PAT.MOV_DTDOC,6,2) AS MESE,
		PAT.MOV_DTDOC AS DATA_DOC,
		PAT.MOV_NDOC AS NUM_DOC,
		SUBSTRING(PAT.MOV_CONTO,5,9) AS CLIENTE,
		CONPAT.CON_DESCR AS RAGSOC,
		PAT.MOV_TOP AS CAUSALE,
		ECO.MOV_CONTO AS CONTO,
		CONECO.CON_DESCR AS DESCR_CONTO,
		ECO.MOV_CCO AS CENTRO_COSTO,
		CASE WHEN ECO.MOV_TMOV='D' THEN -1 *ECO.MOV_IMP ELSE  ECO.MOV_IMP END AS IMPORTO
	FROM MOV_CONT AS PAT
	LEFT OUTER JOIN CONTI AS CONPAT
	ON PAT.MOV_CONTO=CONPAT.CON_CONTO AND PAT.MOV_ANNO=CONPAT.CON_ANNO
	LEFT OUTER JOIN MOV_CONT AS ECO
	ON PAT.MOV_NUMPRO=ECO.MOV_NUMPRO AND PAT.MOV_CONTO<>ECO.MOV_CONTO AND ECO.MOV_CONTO NOT LIKE '44%' AND ECO.MOV_IMP<>0
	LEFT OUTER JOIN CONTI AS CONECO
	ON ECO.MOV_CONTO=CONECO.CON_CONTO AND ECO.MOV_ANNO=CONECO.CON_ANNO
	LEFT OUTER JOIN PARA AS FAT
	ON FAT.CODICE='TOP'+PAT.MOV_TOP 
	LEFT OUTER JOIN U_CLI_AN AS CLI
	ON SUBSTRING(PAT.MOV_CONTO,5,9) = CLI_CODCLI
	WHERE COALESCE(SUBSTRING(FAT.LIBERA,2,1),'')='S' AND CONPAT.CON_TIPOCO='C'


GO
