
/****** Object:  View [dbo].[LETTERE_INTENTO_CLIENTI]    Script Date: 13/03/2017 15:00:56 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LETTERE_INTENTO_CLIENTI]'))
	DROP VIEW [dbo].[LETTERE_INTENTO_CLIENTI]
GO
CREATE VIEW [dbo].[LETTERE_INTENTO_CLIENTI]  
AS

SELECT 
	CLI_RAGSOC,
	CLI_PARIVA,
	CLI_INDIR,
	CLI_CAP,
	CLI_LOCALI,
	CLI_CLIES AS PROT,
	CLI_dtcles
FROM U_CLI_AN
WHERE CLI_CLIES<>''


GO


