/*
-codice acquarius
-ragione sociale
-indirizzo
-località
-cap
-regione
-provincia
-codice fiscale
-p.iva
-n. di telefono
-pec
-sdi (codice destinatario)
-condizioni i pagamento
-email
-gruppo
-classe cliente (per il scritto)
*/

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLI_PER_ECOMMERCE]'))
	DROP VIEW [dbo].[ANAGR_CLI_PER_ECOMMERCE]
GO

CREATE VIEW [dbo].[ANAGR_CLI_PER_ECOMMERCE]  
AS
	SELECT
		AN.CLI_CODCLI AS CODICE,
		AN.CLI_RAGSOC AS RAG_SOCIALE,
		AN.CLI_INDIR AS INDIRIZZO,
		AN.CLI_LOCALI AS LOCALITA,
		AN.CLI_CAP AS CAP,
		AN.CLI_PROVIN AS PROVINCIA,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		AN.CLI_CODFIS AS COD_FISCALE,
		AN.CLI_PARIVA AS P_IVA,
		AN.CLI_TELEFO AS TELEFONO,
		CL.CLI_EPEC AS PEC,
		CL.CLI_IDSDI AS COD_SDI,
		AN.CLI_CONPAG AS COND_PAG,
		COALESCE(CPAG.DESCRI,'') AS DESCR_COND_PAG,
		AN.CLI_EMAIL AS EMAIL,
		COALESCE(AN.CLI_APPPRO,'') AS COD_GRUPPO,
		COALESCE(GRUPPO.DESCRI,'') AS DESCR_GRUPPO,
		SUBSTRING(AN.CLI_CANVEN,7,3) AS COD_CLASSE_CLIENTE,
		COALESCE(CVEN.DESCRI,'') AS DESCR_CLASSE_CLIENTE,
		CL.EC_CUSTOMER_ID AS ID_E_COMMERCE
	FROM U_CLI_AN AS AN
	RIGHT OUTER JOIN U_ANA_CL AS CL ON CL.CLI_CODCLI = AN.CLI_CODCLI
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = AN.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN PARA AS CPAG ON CPAG.CODICE = 'CPA'+AN.CLI_CONPAG
	LEFT OUTER JOIN PARA AS GRUPPO ON GRUPPO.CODICE = 'APP'+AN.CLI_APPPRO
	LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+AN.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9