
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_ART_PREZZI]'))
	DROP VIEW [dbo].[ANAGR_ART_PREZZI]
GO

CREATE VIEW [dbo].[ANAGR_ART_PREZZI]  
AS

	SELECT
		ART_CODPRI AS COD_ART,
		ART_DESCR AS DES_ART,
		ART_PRZVEN AS Listino_ITA,
		ART_PRZVE2 AS Listino_INTL,
		ART_PRZCOS AS PRZ_COSTO_STD,
		ART_ULPSCA AS COSTO_ULTIMO_SCARICO,
		ART_ULPCAR AS COSTO_ULTIMO_CARICO
	FROM U_ART_PR
	WHERE ART_PRZCOS <> ART_COSMAT

GO


SELECT * FROM ANAGR_ART_PREZZI ORDER BY COD_ART