-- VISTA ECONOMICI_PER_CENTRO_COSTO_MESE_NO_PREV

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ECONOMICI_PER_CENTRO_COSTO_MESE_NO_PREV]'))
	DROP VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO_MESE_NO_PREV]
GO

CREATE VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO_MESE_NO_PREV]  
AS

SELECT 
	ECO.MOV_ANNO AS ANNO,
	substring(ECO.MOV_DTREG,6,2) AS MESE,
	ECO.MOV_CONTO AS CONTO,
	CONECO.CON_DESCR AS DESCR_CONTO,
	ECO.MOV_CCO AS CENTRO_COSTO,
	--CAST(SUM(CASE WHEN MOV_TMOV='D' THEN ECO.MOV_IMP ELSE -1 * ECO.MOV_IMP * ECO.MOV_CAMBIO END) AS NUMERIC(19,2)) AS IMPORTO
	CAST(SUM(CASE WHEN MOV_TMOV='D' THEN 1 ELSE -1 END * ECO.MOV_IMP * ECO.MOV_CAMBIO) AS NUMERIC(19,2)) AS IMPORTO -- ERASMO - 05/10/2020
FROM MOV_CONT AS ECO
LEFT OUTER JOIN CONTI AS CONECO
ON ECO.MOV_CONTO=CONECO.CON_CONTO AND ECO.MOV_ANNO=CONECO.CON_ANNO
WHERE ECO.MOV_CONTABILITA_PREVISIONALE = ''
GROUP BY ECO.MOV_ANNO,substring(ECO.MOV_DTREG,6,2),ECO.MOV_CONTO,CONECO.CON_DESCR,ECO.MOV_CCO 


GO