-- VISTA ORDINATO_PER_VELOCITA_EVASIONE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_PER_VELOCITA_EVASIONE]'))
	DROP VIEW [dbo].[ORDINATO_PER_VELOCITA_EVASIONE]
GO

CREATE VIEW [dbo].[ORDINATO_PER_VELOCITA_EVASIONE]  
AS

SELECT
	ANNO,
	MESE,
	NUM_ORDINE,
	DATA_ORDINE,
	CODICE_CLIENTE,
	RAGIONE_SOCIALE,
	CAUSALE,
	DES_CAUSALE,
	TIPO_ORDINE,
	DES_TIPO_ORDINE,
	NAZIONE,
	DES_NAZIONE,
	CENTRCOSTO,
	DES_CENTRCOSTO,
	SUM(EURO_PRNETTO) AS EURO_PRNETTO,
	NUM_DDT,
	DATA_DDT,
	CASE WHEN DATA_DDT = '' THEN NULL ELSE DATEDIFF(DAY, CAST(DATA_ORDINE AS DATE), CAST(DATA_DDT AS DATE)) END AS NR_GIORNI_DA_DATA_ORDINE,
	DTE_PREV_EVASIONE,
	CASE WHEN DTE_PREV_EVASIONE = '' OR DATA_DDT = '' THEN NULL ELSE DATEDIFF(DAY, CAST(DTE_PREV_EVASIONE AS DATE), CAST(DATA_DDT AS DATE)) END AS NR_GIORNI_DA_DATA_EVASIONE
FROM (
	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_DATORD AS DATA_ORDINE,
		TT.ORD_CODCLI AS CODICE_CLIENTE,
		RTRIM(TT.ORD_RAGSOC) AS RAGIONE_SOCIALE,
		TT.ORD_CAUS AS CAUSALE,
		COALESCE(CAUS.DESCRI,'') AS DES_CAUSALE,
		TT.ord_TIPOLOGIA AS TIPO_ORDINE,
		COALESCE(TIPORD.DESCRI,'') AS DES_TIPO_ORDINE,
		CLI.CLI_NAZION AS NAZIONE,
		COALESCE(CNAZION.DESCRI,'') AS DES_NAZIONE,
		DD.ORD_CCODET AS CENTRCOSTO,
		COALESCE(CC.CON_DESCR,'') AS DES_CENTRCOSTO,
		CAST((CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET ELSE 0 END) AS NUMERIC(19,2)) AS EURO_PRNETTO,
		COALESCE(BD.ORS_NUMORD,'') AS NUM_DDT,
		COALESCE(BD.ORS_DATORD,'') AS DATA_DDT,
		DD.ORD_DATCON AS DTE_PREV_EVASIONE
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN CCOSTO AS CC ON DD.ORD_CCODET = CC.CON_CONTO AND TT.ORD_ANNO = CC.CON_ANNO
	LEFT OUTER JOIN U_CLI_AN AS CLI ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS CNAZION ON CNAZION.CODICE = 'STA'+CLI.CLI_NAZION  
	LEFT OUTER JOIN PARA AS CAUS ON CAUS.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS TIPORD ON TIPORD.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN CCOSTO AS CC_AN ON CLI.CLI_CCOST1 = CC_AN.CON_CONTO AND TT.ORD_ANNO = CC_AN.CON_ANNO
	LEFT OUTER JOIN U_BOL_DD AS BD ON BD.ORD_CODART <> '' AND BD.ORD_LEGSYS = DD.ORD_LEGSYS
	WHERE DD.ORD_QTAORD<>0
	) AS MAIN
GROUP BY
	ANNO,
	MESE,
	NUM_ORDINE,
	DATA_ORDINE,
	CODICE_CLIENTE,
	RAGIONE_SOCIALE,
	CAUSALE,
	DES_CAUSALE,
	TIPO_ORDINE,
	DES_TIPO_ORDINE,
	NAZIONE,
	DES_NAZIONE,
	CENTRCOSTO,
	DES_CENTRCOSTO,
	NUM_DDT,
	DATA_DDT,
	DTE_PREV_EVASIONE

GO

--SELECT * FROM ORDINATO_PER_VELOCITA_EVASIONE WHERE ANNO = '2025' AND MESE = '09' ORDER BY NUM_ORDINE,NR_GIORNI_DA_DATA_ORDINE
