 -- VISTA LOCALITA DI CONSEGNA
IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LOCALITA_CONSEGNA]'))
	DROP VIEW [dbo].[LOCALITA_CONSEGNA]
GO


CREATE VIEW [dbo].[LOCALITA_CONSEGNA]  
AS
	SELECT
		LOC_CODCLI AS COD_CLIENTE,
		LOC_CODLOC AS COD_LOCALITA,
		LOC_RAGSOC AS RAG_SOC,
		LOC_INDIRI AS INDIRIZZO,
		LOC_LOCALI AS LOCALITA,
		LOC_CAP AS CAP,
		LOC_PROVIN AS PROVINCIA,
		CLI_NAZION AS COD_NAZIONE,
		PARA_STA.DESCRI AS DES_NAZIONE,
		LOC_ATTENZIONE AS ALL_ATTENZIONE,
		LOC_VARIE AS NOTE_VARIE
	FROM U_LOC_AN
	RIGHT OUTER JOIN U_CLI_AN ON U_CLI_AN.CLI_CODCLI = U_LOC_AN.LOC_CODCLI
	LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_CLI_AN.CLI_NAZION
	WHERE LOC_CF = 'C'
GO
