-- VISTA SALDI_PARTITE_CLIENTE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SALDI_PARTITE_CLIENTE]'))
	DROP VIEW [dbo].[SALDI_PARTITE_CLIENTE]
GO

CREATE VIEW [dbo].[SALDI_PARTITE_CLIENTE]  
AS

SELECT 
	PAR_CODCLI,
	--PAR_RAGSOC,
	CLI.CLI_RAGSOC AS PAR_RAGSOC,
	SUM(CASE 
		WHEN PAR_TMOV='D' THEN PAR_FATT * PAR_CAMBIO
		ELSE  -1*PAR_FATT * PAR_CAMBIO
	END  ) AS SALDO_PARTITE
FROM  PART_CLI 
LEFT OUTER JOIN U_CLI_AN AS CLI ON CLI.CLI_CODCLI = SUBSTRING(PAR_CODCLI,5,10)
WHERE PAR_NPROG<>100
GROUP BY PAR_CODCLI,CLI.CLI_RAGSOC


GO


-- VISTA SALDI_CONTABILI_CLIENTE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SALDI_CONTABILI_CLIENTE]'))
	DROP VIEW [dbo].[SALDI_CONTABILI_CLIENTE]
GO

CREATE VIEW [dbo].[SALDI_CONTABILI_CLIENTE]  
AS

SELECT 
	CON_CONTO,
	SUBSTRING(CON_DESCR,1,30) AS CON_DESCR,
	COALESCE(SUM(CASE 
		WHEN MOV_TMOV='D' THEN MOV_IMP * MOV_CAMBIO
		ELSE  -1*MOV_IMP * MOV_CAMBIO
	END  ),0) AS SALDI_CONTABILI_CLIENTE
FROM CONTI 
LEFT OUTER JOIN MOV_CONT  AS MOV
ON CON_CONTO=MOV_CONTO AND CON_ANNO=MOV_ANNO
WHERE CON_TIPOCO='C' 
GROUP BY CON_CONTO,SUBSTRING(CON_DESCR,1,30)

GO



IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SALDI_PARTITE_FORNITORE]'))
	DROP VIEW [dbo].[SALDI_PARTITE_FORNITORE]
GO

CREATE VIEW [dbo].[SALDI_PARTITE_FORNITORE]  
AS

SELECT 
	PAR_CODCLI,
	--PAR_RAGSOC,
	FORN.FOR_RAGSOC AS PAR_RAGSOC,
	SUM(CASE 
		WHEN PAR_TMOV='D' THEN PAR_FATT * PAR_CAMBIO
		ELSE  -1*PAR_FATT * PAR_CAMBIO
	END  ) AS SALDO_PARTITE
FROM  PART_FOR 
LEFT OUTER JOIN U_FOR_AN AS FORN ON FORN.FOR_CODCLI = SUBSTRING(PAR_CODCLI,5,10)
WHERE PAR_NPROG<>100
GROUP BY PAR_CODCLI,FORN.FOR_RAGSOC


GO


-- VISTA SALDI_CONTABILI_FORNITORE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SALDI_CONTABILI_FORNITORE]'))
	DROP VIEW [dbo].[SALDI_CONTABILI_FORNITORE]
GO

CREATE VIEW [dbo].[SALDI_CONTABILI_FORNITORE]  
AS

SELECT 
	CON_CONTO,
	SUBSTRING(CON_DESCR,1,30) AS CON_DESCR,
	COALESCE(SUM(CASE 
		WHEN MOV_TMOV='D' THEN MOV_IMP * MOV_CAMBIO
		ELSE  -1*MOV_IMP * MOV_CAMBIO
	END  ),0) AS SALDI_CONTABILI_FORNITORE
FROM CONTI 
LEFT OUTER JOIN MOV_CONT  AS MOV
ON CON_CONTO=MOV.MOV_CONTO AND CON_ANNO=MOV_ANNO
WHERE CON_TIPOCO='C'
GROUP BY CON_CONTO,SUBSTRING(CON_DESCR,1,30)

GO
