-- VISTA ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI]'))
	DROP VIEW [dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI]
GO

CREATE VIEW [dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI]  
AS

SELECT T1.*,CCO.CON_DESCR AS DESCRIZIONE_CENTRO_COSTO FROM (
SELECT
	2 AS CODICE_STATO,
	'IN CONSEGNA' AS STATO,
	TT.ORD_CODCLI AS CODICE_CLIENTE,
	TT.ORD_RAGSOC AS CLIENTE,
	TT.ORD_NUMORD AS NUM_ORDINE,
	TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
	TT.ORD_TIPOLOGIA AS TIPOLOGIA,
	CASE TT.ORD_LOCC WHEN '' THEN RTRIM(TT.ORD_LOCC)+(CASE TT.ORD_PROC WHEN '' THEN '' ELSE ' ('+TT.ORD_PROC+')' END) ELSE RTRIM(TT.ORD_LOCALI)+(CASE TT.ORD_PROVIN WHEN '' THEN '' ELSE ' ('+TT.ORD_PROVIN+')' END) END AS LOCALITA_DESTINAZIONE,
	DD.ORD_CCODET AS CENTRO_COSTO,
	DD.ORD_CODART AS CODICE_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
	DD.ORD_DATCON AS DATA_CONSEGNA_RIBALTATA,
	SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA_ORDINATA,
	TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
	TT.ORD_MOTSCA AS MOTIVAZIONE
FROM U_ORD_TT AS TT
LEFT OUTER JOIN U_ORD_DD AS DD
ON TT.TAGGANCIO=DD.DAGGANCIO
WHERE 
	DD.ORD_QTAORD>0
	AND DD.ORD_CHIUSO=0
	AND ORD_DATCON BETWEEN convert(varchar, GETDATE(), 111) AND convert(varchar, DATEADD(day, 5, GETDATE()), 111) 
UNION
SELECT
	1 AS CODICE_STATO,
	'SPEDITO' AS STATO,
	TT.ORD_CODCLI AS CODICE_CLIENTE,
	TT.ORD_RAGSOC AS CLIENTE,
	ORDD.ORS_NUMORD AS NUM_ORDINE,
	ORDD.ORS_DATORD AS DATA_ORDINE_RIBALTATA,
	SUBSTRING(ORDD.ORS_DATORD,9,2)+'/'+SUBSTRING(ORDD.ORS_DATORD,6,2)+'/'+SUBSTRING(ORDD.ORS_DATORD,1,4) AS DATA_ORDINE,
	TT.ORD_TIPOLOGIA AS TIPOLOGIA,
	CASE TT.ORD_LOCC WHEN '' THEN RTRIM(TT.ORD_LOCC)+(CASE TT.ORD_PROC WHEN '' THEN '' ELSE ' ('+TT.ORD_PROC+')' END) ELSE RTRIM(TT.ORD_LOCALI)+(CASE TT.ORD_PROVIN WHEN '' THEN '' ELSE ' ('+TT.ORD_PROVIN+')' END) END AS LOCALITA_DESTINAZIONE,
	ORDD.ORD_CCODET AS CENTRO_COSTO,
	DD.ORD_CODART AS CODICE_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
	TT.ORD_DATORD AS DATA_CONSEGNA_RIBALTATA,
	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_CONSEGNA,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA_ORDINATA,
	TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
	'' AS MOTIVAZIONE
FROM U_BOL_TT AS TT
LEFT OUTER JOIN U_BOL_DD AS DD
ON TT.TAGGANCIO=DD.DAGGANCIO
LEFT OUTER JOIN U_ORD_DD AS ORDD
ON DD.ORD_LEGSYS = ORDD.ORD_LEGSYS
WHERE 
	DD.ORD_QTAORD>0
	AND DD.ORD_LEGSYS<>''
	AND ORDD.ORS_NUMORD IS NOT NULL
	--AND TT.ORD_DATORD=convert(varchar, DATEADD(day, -1, GETDATE()), 111) 
UNION
SELECT
	3 AS CODICE_STATO,
	'SCADUTO' AS STATO,
	TT.ORD_CODCLI AS CODICE_CLIENTE,
	TT.ORD_RAGSOC AS CLIENTE,
	TT.ORD_NUMORD AS NUM_ORDINE,
	TT.ORD_DATORD AS DATA_ORDINE_RIBALTATA,
	SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
	TT.ORD_TIPOLOGIA AS TIPOLOGIA,
	CASE TT.ORD_LOCC WHEN '' THEN RTRIM(TT.ORD_LOCC)+(CASE TT.ORD_PROC WHEN '' THEN '' ELSE ' ('+TT.ORD_PROC+')' END) ELSE RTRIM(TT.ORD_LOCALI)+(CASE TT.ORD_PROVIN WHEN '' THEN '' ELSE ' ('+TT.ORD_PROVIN+')' END) END AS LOCALITA_DESTINAZIONE,
	DD.ORD_CCODET AS CENTRO_COSTO,
	DD.ORD_CODART AS CODICE_ARTICOLO,
	DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
	DD.ORD_DATCON AS DATA_CONSEGNA_RIBALTATA,
	SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
	DD.ORD_UM AS UM,
	DD.ORD_QTAORD AS QTA_ORDINATA,
	TT.ORD_CAMBIO * DD.ORD_VALORE AS VALORE,
	TT.ORD_MOTSCA AS MOTIVAZIONE
FROM U_ORD_TT AS TT
LEFT OUTER JOIN U_ORD_DD AS DD
ON TT.TAGGANCIO=DD.DAGGANCIO
WHERE 
	DD.ORD_QTAORD>0
	AND DD.ORD_CHIUSO=0 
	AND TT.ORD_CHIUSO=0
	AND DD.ORD_DATCON<=convert(varchar, DATEADD(day, -1, GETDATE()), 111) 
) AS T1
LEFT OUTER JOIN (SELECT DISTINCT CON_CONTO, CON_DESCR FROM  CCOSTO) AS CCO
ON T1.CENTRO_COSTO = CON_CONTO
WHERE 
	--T1.CODICE_CLIENTE <> (SELECT TOP 1 AZI_CODCLI FROM U_AZI_AN)
	T1.CODICE_ARTICOLO NOT LIKE '.%'

GO

-- DROP VISTA ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ITALIA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ITALIA]'))
	DROP VIEW [dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ITALIA]
GO

-- DROP VISTA ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ESTERO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ESTERO]'))
	DROP VIEW [dbo].[ORDINI_IN_PROSSIMA_CONSEGNA_E_NON_CONSEGNATI_ESTERO]
GO





