
-- VISTE PER ESTRAZIONE DATI LISTINI GENERICI CLIENTE/ARTICOLO (PER INTERFACCIA CON WINLISTINO)


-- VISTA MBD_TB_ANAG_LISTINI (ANAGRAFICA LISTINI)
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MBD_TB_ANAG_LISTINI]'))
	DROP VIEW [dbo].[MBD_TB_ANAG_LISTINI]
GO
CREATE VIEW [dbo].[MBD_TB_ANAG_LISTINI]  
AS
	SELECT
		LIS_CODGLI+'-'+LIS_CODVAL+'-'+LIS_DATLIS+'-'+LIS_ALLIST AS COD_LISTINO,
		'LISTINO ' + LIS_CODGLI + ' IN VALUTA ' + LIS_CODVAL + ' DAL ' + LIS_DATLIS + ' AL ' + LIS_ALLIST AS DES_LISTINO,
		LIS_DATLIS AS DTE_INIZIO,
		LIS_ALLIST AS DTE_FINE,
		LIS_CODGLI AS TIP_LISTINO,
		LIS_CODVAL AS COD_VALUTA,
		CAST(0 AS BIT) AS DELETED,
		CASE LIS_VALIDO WHEN 'SI' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END ACTIVE
	FROM U_LIS_LG AS LG

GO


-- VISTA MBD_TB_ANAG_LISTINI (ANAGRAFICA LISTINI)
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MBD_TB_LISTINI]'))
	DROP VIEW [dbo].[MBD_TB_LISTINI]
GO
CREATE VIEW [dbo].[MBD_TB_LISTINI]  
AS
	SELECT
		TT.LIS_CODGLI+'-'+TT.LIS_CODVAL+'-'+TT.LIS_DATLIS+'-'+TT.LIS_ALLIST AS COD_LISTINO,
		TT.LIS_CODART AS COD_ARTICOLO,
		TT.LIS_PREZZO AS EUR_ARTICOLO,
		CAST(0 AS BIT) AS DELETED,
		CASE LG.LIS_VALIDO WHEN 'SI' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END ACTIVE
	FROM U_LIS_TT AS TT
	LEFT OUTER JOIN U_LIS_LG AS LG 
		ON LG.LIS_TIPO = 'CLIENTE' AND LG.LIS_CODCLI = '' AND LG.LIS_DATLIS = TT.LIS_DATLIS AND LG.LIS_ALLIST = TT.LIS_ALLIST AND LG.LIS_CODVAL = TT.LIS_CODVAL AND LG.LIS_CODGLI = TT.LIS_CODGLI

GO


-- VISTA MBD_TB_ARTICOLI_DESCRIZIONI (DESCRIZIONI, DESCRIZIONI IN LINGUA E NOTE ARTICOLI LISTINI)
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MBD_TB_ARTICOLI_DESCRIZIONI]'))
	DROP VIEW [dbo].[MBD_TB_ARTICOLI_DESCRIZIONI]
GO
CREATE VIEW [dbo].[MBD_TB_ARTICOLI_DESCRIZIONI]  
AS
	SELECT
		DL.CODICE AS COD_ARTICOLO,
		DL.LINGUA AS COD_LINGUA,
		COALESCE(PARA_LNG.DESCRI,'') AS DES_LINGUA,
		DL.DESCRI AS DES_ARTICOLO,
		DL.DESEST AS TXT_ARTICOLO,
		DL.NOTE AS NOTE_ARTICOLO,
		CAST(0 AS BIT) AS DELETED,
		CASE PARA_LNG.DISATTIVO WHEN 1 THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END ACTIVE
	FROM DESLINGUE AS DL
	LEFT OUTER JOIN PARA AS PARA_LNG ON PARA_LNG.CODICE = 'LNG'+DL.LINGUA
	WHERE TIPODES = 'ARTICOLO'

GO


SELECT * FROM MBD_TB_ANAG_LISTINI
SELECT * FROM MBD_TB_LISTINI
SELECT * FROM MBD_TB_ARTICOLI_DESCRIZIONI
