
-- VISTA FATTURATO_PER_POLIZZA_SIGLA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_PER_POLIZZA_SIGLA]'))
	DROP VIEW [dbo].[FATTURATO_PER_POLIZZA_SIGLA]
GO

CREATE VIEW [dbo].[FATTURATO_PER_POLIZZA_SIGLA]  
AS
	SELECT 
		ESERPROTOC AS ANNO,
		MODALSPEDI AS MEZZO_SPED,
		COALESCE(P_MEZ.DESCRIZION,'') AS DESCRIZIONE_MEZZO_SPED,
		PORTO AS PORTO,
		COALESCE(P_POR.DESCRIZION,'') AS DESCRIZIONE_PORTO,
		TIPOPROTOC,
		NUMEPROTOC AS NUM_FATTURA,
		SUBSTRING(DATAPROTOC,1,4) + '/' + SUBSTRING(DATAPROTOC,5,2) + '/' + SUBSTRING(DATAPROTOC,7,2) AS DATA_FATTURA,
		ETOTIMPORT AS IMPORTO_EUR,
		COALESCE(RGSOC_DEST,'') AS RAGSOC__DESTINAZIONE,
		COALESCE(INDIR_DEST,'') AS INDIRIZZO_DESTINAZIONE,
		COALESCE(LOCAL_DEST,'') AS LOCALITA_DESTINAZIONE,
		COALESCE(CAP_DEST,'') AS CAP_DESTINAZIONE,
		COALESCE(PROV_DEST,'') AS PROVINCIA_DESTINAZIONE,
		COALESCE(P_STA.DENOMINAZI,'') AS STATO_ESTERO_DESTINAZIONE
	FROM CARD_TESDOCUM AS TT
	LEFT OUTER JOIN CARD_TABPORTI AS P_POR ON P_POR.CODICE = TT.PORTO
	LEFT OUTER JOIN CARD_MODSPEDI AS P_MEZ ON P_MEZ.CODICE = TT.MODALSPEDI
	LEFT OUTER JOIN CARD_STATIEST AS P_STA ON P_STA.CODICE = TT.STAES_DEST
	WHERE C_F = 'C' AND TIPODOCUM IN ('F','R')
GO
