-- VISTA [IVA_SIGLA]

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[IVA_SIGLA]'))
	DROP VIEW [dbo].[IVA_SIGLA]
GO

CREATE VIEW [dbo].[IVA_SIGLA]
AS

SELECT 
	 '01' AS IVA_CODSOC,
	'2014' AS IVA_ANNO,
	'12' AS IVA_MESE,
	CAST(SUBSTRING(MOVCO.NUMPROTOC,2,6) as numeric(6,0)) AS IVA_CHIAVE,
	MOVCO.NUMDOCUM AS IVA_NUMDOC,
	SUBSTRING(MOVIVA.CODIVA,1,3) AS IVA_CODIVA,
	MOVCO.EIMPORTO  AS IVA_IMPONI,
	MOVIVA.EIMPOSTA as IVA_IMPOST,
	MOVCO.EIMPORTO +MOVIVA.EIMPOSTA AS IVA_TOTALE,
	MOVCO.CAUSALE AS IVA_TOP,
	SUBSTRING(MOVCO.DATADOCUM,1,4)+'/'+SUBSTRING(MOVCO.DATADOCUM,5,2)+'/'+SUBSTRING(MOVCO.DATADOCUM,7,2) AS IVA_DTFATT,
	'2014/12/31' AS IVA_DTCREA,
	CON_TIPOCO AS IVA_CLIFOR,
	MOVCO.SOTTOCONTO AS IVA_CODCLI,
	SUBSTRING(PIACON.DESCRIZION ,1,30) AS IVA_RAGSOC,
	'EUR' AS IVA_VALUTA,
	1 AS IVA_CAMBIO,
	CASE WHEN (MOVCO.SEGNO='D' AND CON_TIPOCO='C') OR  (MOVCO.SEGNO='A' AND CON_TIPOCO='F') THEN 'F'
	ELSE 'N' END AS IVA_FATNOT,
	MOVCO.*
FROM CARD_MOVCO AS  MOVCO 
LEFT OUTER JOIN CARD_PIACON AS PIACON
ON MOVCO.SOTTOCONTO = PIACON.SOTTOCONTO
LEFT OUTER JOIN CONTI 
ON MOVCO.SOTTOCONTO = SUBSTRING(CON_CONTO,5,9) AND CON_ANNO='2014'
LEFT OUTER JOIN card_moviva AS MOVIVA
ON MOVIVA.numero=MOVCO.NUMERO 
WHERE MOVCO.DATAREG BETWEEN '20141201' AND  '20141231'
	AND CON_TIPOCO IN ('C','F')
and MOVCO.SOSPESO_SN <> 'S'
and MOVCO.SIMULAZ_SN <> 'S'
and MOVCO.TEMPORA_SN <> 'S'
AND CAUSALE<>'APC'
AND MOVCO.NUMPROTOC IS NOT NULL

GO





SELECT * FROM U_IVF_CL WHERE IVF_ANNO='2015'