
-- VISTA FATTURATO_PER_POLIZZA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_PER_POLIZZA]'))
	DROP VIEW [dbo].[FATTURATO_PER_POLIZZA]
GO

CREATE VIEW [dbo].[FATTURATO_PER_POLIZZA]  
AS
	SELECT
		ORD_ANNO AS ANNO,
		ORD_TIPOLOGIA AS TIPOLOGIA,
		COALESCE(P_TPO.DESCRI,'') AS DESCRIZIONE_TIPOLOGIA,
		ORD_ACURA AS MEZZO_SPED,
		COALESCE(P_MEZ.DESCRI,'') AS DESCRIZIONE_MEZZO_SPED,
		ORD_PORTO AS PORTO,
		COALESCE(P_POR.DESCRI,'') AS DESCRIZIONE_PORTO,
		ORD_NUMORD AS NUM_FATTURA,
		ORD_DATORD AS DATA_FATTURA,
		(ORD_CAMBIO * ORD_VALORE) AS IMPORTO_EUR_CON_IVA,
		(ORD_CAMBIO * ORD_IMPONIB) AS IMPORTO_EUR_SENZA_IVA,
		ORD_RAGSOC AS RAGSOC_FATTURATO_A,
		ORD_INDIRI AS INDIRIZZO_FATTURATO_A,
		ORD_CAP AS CAP_FATTURATO_A,
		ORD_LOCALI AS LOCALITA_FATTURATO_A,
		ORD_PROVIN AS PROVINCIA_FATTURATO_A,
		P_STA.DESCRI AS NAZIONE_FATTURATO_A,
		ORD_RAGC AS RAGSOC_CONSEGNATO_A,
		ORD_INDC AS INDIRIZZO_CONSEGNATO_A,
		ORD_CAPC AS CAP_CONSEGNATO_A,
		ORD_LOCC AS LOCALITA_CONSEGNATO_A,
		ORD_PROC AS PROVINCIA_CONSEGNATO_A,
		(CASE ORD_DSNAZC WHEN '' THEN COALESCE(P_STA.DESCRI,'') ELSE ORD_DSNAZC END) AS NAZIONE_CONSEGNATO_A
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN PARA AS P_MEZ ON P_MEZ.CODICE = 'MEZ'+TT.ORD_ACURA
	LEFT OUTER JOIN PARA AS P_POR ON P_POR.CODICE = 'POR'+TT.ORD_PORTO
	LEFT OUTER JOIN PARA AS P_TPO ON P_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN PARA AS P_STA ON P_STA.CODICE = 'STA'+TT.ORD_CODNAZ
GO
