
-- VISTA LISTA_FATTURE_PER_ORDINE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LISTA_FATTURE_PER_ORDINE]'))
	DROP VIEW [dbo].[LISTA_FATTURE_PER_ORDINE]
GO

CREATE VIEW [dbo].[LISTA_FATTURE_PER_ORDINE]  
AS
	WITH TEMP AS
	(
	SELECT
		ORS_NUMORC AS NUMORC,
		ORS_DATORC AS DATORC,
		ORS_NUMORD AS NUMFAT,
		ORS_DATORD AS DATFAT
	FROM (
		SELECT ORS_NUMORD, ORS_DATORD, ORS_NUMORC, ORS_DATORC
		FROM U_FAT_DD
		WHERE ORD_CODART <> '' AND ORS_NUMORC <> '' AND ORS_DATORC <> ''	--AND U_FAT_DD.ORS_DATORD >= '2022/01/07'
		GROUP BY ORS_NUMORD, ORS_DATORD, ORS_NUMORC, ORS_DATORC
		UNION
		SELECT U_FAT_DD.ORS_NUMORD, U_FAT_DD.ORS_DATORD, U_BOL_DD.ORS_NUMORC, U_BOL_DD.ORS_DATORC
		FROM U_FAT_DD
		INNER JOIN U_BOL_DD ON U_FAT_DD.ORS_NUMDDT = U_BOL_DD.ORS_NUMORD AND U_FAT_DD.ORS_DATDDT = U_BOL_DD.ORS_DATORD AND U_BOL_DD.ORD_CODART <> '' AND U_BOL_DD.ORS_NUMORC <> '' AND U_BOL_DD.ORS_DATORC <> ''
		WHERE U_FAT_DD.ORD_CODART <> '' AND U_FAT_DD.ORS_NUMDDT <> '' AND U_FAT_DD.ORS_DATDDT <> ''	--AND U_FAT_DD.ORS_DATORD >= '2022/01/07'
		GROUP BY U_FAT_DD.ORS_NUMORD, U_FAT_DD.ORS_DATORD, U_BOL_DD.ORS_NUMORC, U_BOL_DD.ORS_DATORC
		) AS MAIN WHERE ORS_NUMORC <> '' AND ORS_DATORC <> ''
	)

	select NUMORC, DATORC,
		SUBSTRING((Select ','+NUMFAT from TEMP AS T1 where T1.NUMORC=T2.NUMORC AND T1.DATORC=T2.DATORC FOR XML PATH('')),2,254) AS NUMFAT,
		SUBSTRING((Select ','+DATFAT from TEMP AS T1 where T1.NUMORC=T2.NUMORC AND T1.DATORC=T2.DATORC FOR XML PATH('')),2,254) AS DATFAT
	from TEMP AS T2
	group by NUMORC, DATORC

GO
