
-- VISTA ANAGR_CLIENTI_SINTETICA
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLIENTI_SINTETICA]'))
	DROP VIEW [dbo].[ANAGR_CLIENTI_SINTETICA]
GO
CREATE VIEW [dbo].[ANAGR_CLIENTI_SINTETICA]  
AS

	SELECT
		CLI_CODCLI AS COD_CLIENTE,
		CLI_RAGSOC AS RAG_SOCIALE,
		CLI_INDIR AS INDIRIZZO,
		CLI_CAP AS CAP,
		CLI_LOCALI AS COMUNE,
		CLI_PROVIN AS PROVIN,
		CLI_NAZION AS NAZIONE,
		CLI_CODFIS AS COD_FISCALE,
		CLI_PARIVA AS PARTITA_IVA,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO
	FROM U_CLI_AN
	LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+CLI_CONPAG

GO

SELECT * FROM ANAGR_CLIENTI_SINTETICA ORDER BY RAG_SOCIALE
