
-- VISTA ANAGR_CLIENTI_DATI_FE
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLIENTI_DATI_FE]'))
	DROP VIEW [dbo].[ANAGR_CLIENTI_DATI_FE]
GO
CREATE VIEW [dbo].[ANAGR_CLIENTI_DATI_FE]  
AS

	SELECT
		AN.CLI_CODCLI AS COD_CLIENTE,
		AN.CLI_RAGSOC AS RAG_SOCIALE,
		CL.CLI_FATELETT AS FLAG_FATT_ELETTR,
		CL.CLI_PA AS FLAG_PA,
		CL.CLI_IDSDI AS COD_DESTINATARIO,
		CL.CLI_IDNSO AS COD_NSO,
		CL.CLI_EPEC AS EMAIL_PEC,
		CL.CLI_BOVIRT AS BOLLO_VIRTUALE,
		CL.CLI_FEPICF AS FLAG_INS_PIVA_CFIS
	FROM U_CLI_AN AS AN
	LEFT OUTER JOIN U_ANA_CL AS CL ON CL.CLI_CODCLI = AN.CLI_CODCLI
	WHERE AN.CLI_RAGSOC <> ''  AND AN.CLI_CODCLI NOT IN (SELECT FOR_CLICEE FROM U_FOR_AN WHERE FOR_CLICEE<>'')
GO

SELECT * FROM ANAGR_CLIENTI_DATI_FE ORDER BY RAG_SOCIALE
