-- VISTA ORDINATO_PER_VALUTAZIONE_PROCESSI_INTERNI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_PER_VALUTAZIONE_PROCESSI_INTERNI]'))
	DROP VIEW [dbo].[ORDINATO_PER_VALUTAZIONE_PROCESSI_INTERNI]
GO

CREATE VIEW [dbo].[ORDINATO_PER_VALUTAZIONE_PROCESSI_INTERNI]  
AS

SELECT
	ANNO,
	NUM_ORDINE,
	DATA_DOC AS DATA_ORDINE,
	SUM(EURO_PRNETTO_QUANTITA) AS TOT_EURO_PRNETTO,
	REG_DATREG AS DATA_INSERIMENTO,
	REG_NOMOPE AS UTENTE_INSERIMENTO,
	MOD_DATREG AS DATA_MODIFICA,
	MOD_NOMOPE AS UTENTE_MODIFICA,
	NUM_DDT,
	DATA_DDT
FROM ORDINATO
GROUP BY
	ANNO,
	NUM_ORDINE,
	DATA_DOC,
	REG_DATREG,
	REG_NOMOPE,
	MOD_DATREG,
	MOD_NOMOPE,
	NUM_DDT,
	DATA_DDT

GO
