-- VISTA CLIFOR_CONTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CLIFOR_CONTI]'))
	DROP VIEW [dbo].[CLIFOR_CONTI]
GO

CREATE VIEW [dbo].[CLIFOR_CONTI]  
AS

SELECT 
	'C' AS CF,
	CLI_CODCLI AS CODICE,
	CLI_NAZION AS NAZIONE,
	SUBSTRING(PARA.CODICE,4,2) AS ITA_CEE_EXT,
	SUBSTRING(PARA.LIBERA,1,4)+CLI_CODCLI AS CONTO ,
	'' AS CLICEE
FROM U_CLI_AN AS AN
LEFT OUTER JOIN PARA 
ON PARA.CODICE IN ('GENIT','GENCE','GENEX') AND PARA.NOTE LIKE '%.'+CLI_NAZION+'.%'
UNION 
SELECT 
	'F' AS CF,
	FOR_CODCLI  AS CODICE,
	FOR_NAZION AS NAZIONE,
	SUBSTRING(PARA.CODICE,4,2) AS ITA_CEE_EXT,
	SUBSTRING(PARA.LIBERA,18,4)+FOR_CODCLI AS CONTO ,
	FOR_CLICEE AS CLICEE
FROM U_FOR_AN AS AN
LEFT OUTER JOIN PARA 
ON PARA.CODICE IN ('GENIT','GENCE','GENEX') AND PARA.NOTE LIKE '%.'+FOR_NAZION+'.%'

GO

