 
-- VISTA ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8]'))
	DROP VIEW [dbo].[ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8]
GO

CREATE VIEW [dbo].[ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8]  
AS

WITH AlberoDIBA
AS (
    SELECT 
		1 AS LIVELLO,
		DIS_GRUPPO AS PADRE,
		CAST(COALESCE(RTRIM(DIS_CODART),'') AS VARCHAR(1000)) AS GERARCHIA,
		U_DIS_DD.*
    FROM U_DIS_DD
    --WHERE DIS_CODART = '12001295' --AND DAGGANCIO = '7000003034'
	WHERE DIS_fasela = ''
    UNION ALL
    SELECT 
		LIVELLO + 1,
		DD.DIS_GRUPPO AS PADRE,
		CAST(AlberoDIBA.GERARCHIA+' -> '+RTRIM(DD.DIS_CODART) AS VARCHAR(1000)) AS GERARCHIA,
		DD.*
    FROM U_DIS_DD AS DD
    INNER JOIN AlberoDIBA
    ON DD.DIS_CODART = AlberoDIBA.DIS_GRUPPO
)

SELECT
	SUBSTRING(GERARCHIA,1,CASE WHEN CHARINDEX(' -> ',GERARCHIA,1) > 0 THEN CHARINDEX(' -> ',GERARCHIA,1) ELSE 30 END) AS CODART_BASE,
	PADRE AS PADRE_PREF_8
FROM AlberoDIBA
WHERE PADRE LIKE '8%'
--ORDER BY PADRE

GO

/*
SELECT
	CODART_BASE
	,SUBSTRING((Select ','+RTRIM(PADRE_PREF_8) from ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8 AS T1 where T1.CODART_BASE=T2.CODART_BASE FOR XML PATH('')),2,2000) AS PADRI_PREF_8
FROM ELENCO_IMPLOSIONE_DIBA_CON_PADRE_PREF_8 AS T2
WHERE T2.CODART_BASE IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_OBSOL <> 'S' AND ART_TIPART = 'A' AND ART_NONMOV = 0)
	AND T2.CODART_BASE IN (SELECT MAG_ANAART FROM U_MAG_GG WHERE MAG_GIACEN > 0)
GROUP BY CODART_BASE
ORDER BY CODART_BASE
*/