
-- VISTA DDT_BLOCCATI_NON_FATTURATI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DDT_BLOCCATI_NON_FATTURATI]'))
	DROP VIEW [dbo].[DDT_BLOCCATI_NON_FATTURATI]
GO
CREATE VIEW [dbo].[DDT_BLOCCATI_NON_FATTURATI]  
AS
	SELECT
		TT.ORD_CODCLI AS CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_NUMORD AS NUM_DDT,
		TT.ORD_DATORD AS DATA_DDT,
		TT.ORD_CAUS AS COD_CAUSALE,
		COALESCE(P_TOP.DESCRI,'') AS DESCR_CAUSALE,
		TT.ORD_TIPOLOGIA AS COD_TIPOLOGIA,
		COALESCE(P_TPO.DESCRI,'') AS DESCR_TIPOLOGIA,
		TT.ORD_VALORE AS IMPORTO,
		COALESCE(DD.ORS_NUMORC,'') AS NUM_ORD,
		COALESCE(DD.ORS_DATORC,'') AS DATA_ORD,
		COALESCE(OC.ORD_DDTLCKADV,0) AS BLOCCO_DDT_ADV,
		COALESCE(OC.ORD_DDTLCKSER,0) AS BLOCCO_DDT_SERVICE
	FROM U_BOL_TT AS TT
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS P_TPO ON P_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	OUTER APPLY (SELECT TOP 1 ORS_NUMORC,ORS_DATORC FROM U_BOL_DD WHERE ORD_CODART <> '' AND DAGGANCIO = TT.TAGGANCIO ORDER BY ORS_DATORD,ORS_NUMORD) AS DD
	LEFT OUTER JOIN U_ORD_TT AS OC ON OC.ORD_NUMORD = DD.ORS_NUMORC AND OC.ORD_DATORD = DD.ORS_DATORC
	WHERE
		TT.ORD_FORNI = 0 AND 
		TT.ORD_FLBOL = 'S' AND 
		SUBSTRING(P_TOP.LIBERA,2,1) = 'V' AND
		TT.ORD_NUMORD+TT.ORD_DATORD NOT IN (SELECT ORS_NUMDDT+ORS_DATDDT FROM U_FAT_DD)

GO

SELECT * FROM DDT_BLOCCATI_NON_FATTURATI ORDER BY DATA_DDT DESC