
-- VISTA BOLLE PER TIPOLOGIA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[BOLLE_PER_TIPOLOGIA]'))
	DROP VIEW [dbo].[BOLLE_PER_TIPOLOGIA]
GO

CREATE VIEW [dbo].[BOLLE_PER_TIPOLOGIA]  
AS

	SELECT
		ANNO,
		ID_BOLLA,
		CAUSALE,
		DES_CAUSALE,
		TIPOLOGIA,
		DES_TIPOLOGIA,
		MAG_AG_DEP,
		NR_DDT,
		DATA_DDT,
		RAG_SOCIALE,
		COD_CLIENTE,
		LOCALITA,
		PROVINCIA,
		NAZIONE,
		LOCALITA_CONSEGNA,
		PROVINCIA_CONSEGNA,
		NAZIONE_CONSEGNA,
		CAST(coalesce(stuff((select  ', ' + RTRIM(ORD_CODART)
				FROM    U_BOL_DD
				WHERE   DAGGANCIO = MAIN.ID_BOLLA AND ORD_CODART <> '*** COMMENTO ***' AND ORD_CODART <> '' AND SUBSTRING(ORD_CODART,1,1) <> '.' 
					AND ORD_CODART NOT IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_DESCR LIKE '%IMBALLO%' OR ART_DESCR LIKE '%MANUALE%' OR ART_DESCR LIKE '%OPZION%' OR ART_DESCR LIKE '%GARANZIA%' OR ART_DESCR LIKE '%COMMISSION%' OR ART_DESCR LIKE '%ANTICIPO%' OR ART_DESCR LIKE '%ETIC.%' OR ART_DESCR LIKE '%ETICH.%' OR ART_DESCR LIKE '%ETICHETTA%' OR ART_DESCR LIKE '%LICENZA%')
				FOR XML PATH('')
			),1,2,''),'') AS NVARCHAR(254)) AS ARTICOLI,
		CAST(SUM((CASE NR_RIGHE_FIGLI WHEN 0 THEN 1 ELSE NR_RIGHE_FIGLI END) * QUANTITA) AS NUMERIC(10,0)) AS NR_RIGHE,
		PORTO,
		MEZZO_SPEDIZIONE,
		NR_COLLI,
		PESO_NETTO,
		PESO_LORDO

		FROM (

			SELECT
				TT.ORD_ANNO AS ANNO,
				TT.TAGGANCIO AS ID_BOLLA,
				TT.ORD_CAUS AS CAUSALE,
				COALESCE(P_TOP.DESCRI,'') AS DES_CAUSALE,
				TT.ORD_TIPOLOGIA AS TIPOLOGIA,
				COALESCE(P_TPO.DESCRI,'') AS DES_TIPOLOGIA,
				TT.ORD_MAGD AS MAG_AG_DEP,
				TT.ORD_NUMORD AS NR_DDT,
				TT.ORD_DATORD AS DATA_DDT,
				TT.ORD_RAGSOC AS RAG_SOCIALE,
				TT.ORD_CODCLI AS COD_CLIENTE,
				TT.ORD_LOCALI AS LOCALITA,
				TT.ORD_PROVIN AS PROVINCIA,
				TT.ORD_CODNAZ AS NAZIONE,
				TT.ORD_LOCC AS LOCALITA_CONSEGNA,
				TT.ORD_PROC AS PROVINCIA_CONSEGNA,
				TT.ORD_DSNAZC AS NAZIONE_CONSEGNA,
				DD.ORD_CODART AS COD_ARTICOLO,
				DD.ORD_QTAORD AS QUANTITA,
				COALESCE(
					(SELECT COUNT(*) AS NR_FIGLI FROM U_DIS_DD WHERE DIS_GRUPPO = DD.ORD_CODART AND SUBSTRING(ORD_CODART,1,1) <> '.' 
							AND ORD_CODART NOT IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_DESCR LIKE '%IMBALLO%' OR ART_DESCR LIKE '%MANUALE%' OR ART_DESCR LIKE '%OPZION%' OR ART_DESCR LIKE '%GARANZIA%' OR ART_DESCR LIKE '%COMMISSION%' OR ART_DESCR LIKE '%ANTICIPO%' OR ART_DESCR LIKE '%ETIC.%' OR ART_DESCR LIKE '%ETICH.%' OR ART_DESCR LIKE '%ETICHETTA%' OR ART_DESCR LIKE '%LICENZA%')
						AND DIS_CODART NOT IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_DESCR LIKE '%IMBALLO%' OR ART_DESCR LIKE '%MANUALE%' OR ART_DESCR LIKE '%OPZION%' OR ART_DESCR LIKE '%GARANZIA%' OR ART_DESCR LIKE '%COMMISSION%' OR ART_DESCR LIKE '%ANTICIPO%' OR ART_DESCR LIKE '%ETIC.%' OR ART_DESCR LIKE '%ETICH.%' OR ART_DESCR LIKE '%ETICHETTA%' OR ART_DESCR LIKE '%LICENZA%')
					),0)
				AS NR_RIGHE_FIGLI,

				ORD_PORTO AS PORTO,
				COALESCE(P_MEZ.DESCRI,'') AS MEZZO_SPEDIZIONE,
				LTRIM(RTRIM(ORD_COLLI)) AS NR_COLLI,
				ORD_PESNET AS PESO_NETTO,
				ORD_PESO AS PESO_LORDO
			FROM U_BOL_TT AS TT
			LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
			LEFT OUTER JOIN PARA AS P_TPO ON P_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
			LEFT OUTER JOIN PARA AS P_MEZ ON P_MEZ.CODICE = 'MEZ'+TT.ORD_ACURA
			LEFT OUTER JOIN U_BOL_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO
			) AS MAIN
	GROUP BY
		ANNO,
		ID_BOLLA,
		CAUSALE,
		DES_CAUSALE,
		TIPOLOGIA,
		DES_TIPOLOGIA,
		MAG_AG_DEP,
		NR_DDT,
		DATA_DDT,
		RAG_SOCIALE,
		COD_CLIENTE,
		LOCALITA,
		PROVINCIA,
		NAZIONE,
		LOCALITA_CONSEGNA,
		PROVINCIA_CONSEGNA,
		NAZIONE_CONSEGNA,
		PORTO,
		MEZZO_SPEDIZIONE,
		NR_COLLI,
		PESO_NETTO,
		PESO_LORDO
GO	

SELECT * FROM BOLLE_PER_TIPOLOGIA WHERE DATA_DDT >= '2026/03/01' ORDER BY DATA_DDT,NR_DDT,ARTICOLI
