
-- VISTA SLOW_MOVING

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SLOW_MOVING]'))
	DROP VIEW [dbo].[SLOW_MOVING]
GO

CREATE VIEW [dbo].[SLOW_MOVING]
AS

SELECT 
	CODMAG,
	CODART,
	DESART,
	CODFOR,
	DESFOR,
	SUM(GIACEN) AS GIACEN,
	MIN(DATCAR) AS DATA_CARICO_PIU_VECCHIA,
	MAX(DATCAR) AS DATA_CARICO_PIU_RECENTE,
	SUM(GG_GIACENZA_PER_CARICHI) / 365 AS GIACENZA_MEDIA_PONDERATA_ANNUALE,
	COALESCE(PR.ART_ULPCAR,0) AS PREZZO_ULT_CAR,
	COALESCE(PR.ART_ULPCAR,0) * SUM(GIACEN) AS VALORE_ULT_CAR,
	SUM(CARICHI) AS TOT_QTA_CARICATA,
	SUM(SCARICHI) AS TOT_QTA_SCARICATA,
	CASE WHEN (SUM(GG_GIACENZA_PER_CARICHI) / 365) > 0 THEN SUM(SCARICHI) / (SUM(GG_GIACENZA_PER_CARICHI) / 365) ELSE 999 END AS INDICE_ROTAZIONE_ANNUALE
FROM (
	SELECT
		*,
		(SELECT TOP 1 MOV_DESART FROM U_MAG_MO WHERE MOV_LEGAME = MAIN.MOV_LEGAME AND MOV_CODMAG = MAIN.CODMAG ORDER BY MOV_DTREGI) AS DESART,
		(SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_LEGAME = MAIN.MOV_LEGAME AND MOV_CODMAG = MAIN.CODMAG ORDER BY MOV_DTREGI) AS CODFOR,
		(SELECT TOP 1 MOV_DESFOR FROM U_MAG_MO WHERE MOV_LEGAME = MAIN.MOV_LEGAME AND MOV_CODMAG = MAIN.CODMAG ORDER BY MOV_DTREGI) AS DESFOR,
		CASE WHEN GIACEN > 0 THEN DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),GETDATE()) ELSE DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),CONVERT(DATETIME,DATSCA,111))+1 END AS GG_GIACENZA,
		CASE WHEN GIACEN > 0 THEN DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),GETDATE()) ELSE DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),CONVERT(DATETIME,DATSCA,111))+1 END * CARICHI AS GG_GIACENZA_PER_CARICHI
	FROM (
		SELECT 
			MOV_LEGAME,
			MOV_CODMAG AS CODMAG,
			MOV_ANAART AS CODART,
			SUM(CASE MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END * MOV_QTAMOV) AS GIACEN,
			SUM(CASE MOV_SEGNO WHEN '+' THEN MOV_QTAMOV ELSE 0 END) AS CARICHI,
			SUM(CASE MOV_SEGNO WHEN '-' THEN MOV_QTAMOV ELSE 0 END) AS SCARICHI,
			--SUBSTRING(MIN(MOV_DTREGI),9,2) + '/' + SUBSTRING(MIN(MOV_DTREGI),6,2) + '/' + SUBSTRING(MIN(MOV_DTREGI),1,4) AS DATCAR,
			--SUBSTRING(MAX(MOV_DTREGI),9,2) + '/' + SUBSTRING(MAX(MOV_DTREGI),6,2) + '/' + SUBSTRING(MAX(MOV_DTREGI),1,4) AS DATSCA
			MIN(MOV_DTREGI) AS DATCAR,
			MAX(MOV_DTREGI) AS DATSCA
		FROM U_MAG_MO
		GROUP BY MOV_LEGAME,MOV_CODMAG,MOV_ANAART
		) AS MAIN
	WHERE
		--(GIACEN > 0 OR DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),GETDATE()) BETWEEN 0 AND 365)
		DATEDIFF(DD,CONVERT(DATETIME,DATCAR,111),GETDATE()) BETWEEN 0 AND 365 --AND GIACEN >= 0
	) AS MAIN_EXT
LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MAIN_EXT.CODART
GROUP BY
	MAIN_EXT.CODMAG,
	MAIN_EXT.CODART,
	MAIN_EXT.DESART,
	MAIN_EXT.CODFOR,
	MAIN_EXT.DESFOR,
	PR.ART_ULPCAR