
-- VISTA SLOW_MOVING_GIACENZE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[SLOW_MOVING_GIACENZE]'))
	DROP VIEW [dbo].[SLOW_MOVING_GIACENZE]
GO

CREATE VIEW [dbo].[SLOW_MOVING_GIACENZE]
AS

SELECT 
	CODMAG,
	CODART,
	DESART,
	CODFOR,
	DESFOR,
	SUM(GIACEN) AS GIACEN,
	MIN(DATCAR) AS DATA_CARICO_PIU_VECCHIA,
	MAX(DATCAR) AS DATA_CARICO_PIU_RECENTE,
	(SUM(GG_GIACENZA_PER_GIACEN) / SUM(GIACEN)) AS GG_GIACENZA_MEDIA_PONDERATA,
	COALESCE(PR.ART_ULPCAR,0) AS PREZZO_ULT_CAR,
	COALESCE(PR.ART_ULPCAR,0) * SUM(GIACEN) AS VALORE_ULT_CAR
FROM (
	SELECT 
		MAG_CODMAG AS CODMAG,
		MAG_ANAART AS CODART,
		MAG_DESART AS DESART,
		MAG_FORNIT AS CODFOR,
		MAG_DESFOR AS DESFOR,
		MAG_GIACEN AS GIACEN,
		SUBSTRING(MAG_DATAGG,9,2) + '/' + SUBSTRING(MAG_DATAGG,6,2) + '/' + SUBSTRING(MAG_DATAGG,1,4) AS DATCAR,
		DATEDIFF(DD,(CONVERT(DATETIME,MAG_DATAGG,111)),GETDATE()) AS GG_GIACENZA,
		DATEDIFF(DD,(CONVERT(DATETIME,MAG_DATAGG,111)),GETDATE()) * MAG_GIACEN AS GG_GIACENZA_PER_GIACEN
	FROM U_MAG_GG
	WHERE
		MAG_GIACEN > 0
	) AS MAIN
LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = MAIN.CODART
GROUP BY 
	MAIN.CODMAG,
	MAIN.CODART,
	MAIN.DESART,
	MAIN.CODFOR,
	MAIN.DESFOR,
	PR.ART_ULPCAR

