
-- VISTA DDT_BLOCCATI_NON_FATTURATI_CON_DETTAGLI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[DDT_BLOCCATI_NON_FATTURATI_CON_DETTAGLI]'))
	DROP VIEW [dbo].[DDT_BLOCCATI_NON_FATTURATI_CON_DETTAGLI]
GO
CREATE VIEW [dbo].[DDT_BLOCCATI_NON_FATTURATI_CON_DETTAGLI]  
AS
	SELECT
		TT.ORD_CODCLI AS CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_NUMORD AS NUM_DDT,
		TT.ORD_DATORD AS DATA_DDT,
		TT.ORD_CAUS AS COD_CAUSALE,
		COALESCE(P_TOP.DESCRI,'') AS DESCR_CAUSALE,
		TT.ORD_TIPOLOGIA AS COD_TIPOLOGIA,
		COALESCE(P_TPO.DESCRI,'') AS DESCR_TIPOLOGIA,
		TT.ORD_VALORE AS IMPORTO_TOT,
		COALESCE(OC.ORD_DDTLCKADV,0) AS BLOCCO_DDT_ADV,
		COALESCE(OC.ORD_DDTLCKSER,0) AS BLOCCO_DDT_SERVICE,
		DD.ORS_NUMORC AS NUM_ORD,
		DD.ORS_DATORC AS DATA_ORD,
		DD.ORD_CODART AS COD_ARTICOLO,
		DD.ORD_DESART AS DESCR_ARTICOLO,
		COALESCE(FAM.DESCRI,'') AS DESCR_FAMIGLIA,
		COALESCE(SFA.DESCRI,'') AS DESCR_SOTTOFAMIGLIA,
		ORD_QTAORD AS QTA,
		CAST((CASE DD.ORD_PUBBLI WHEN 'O' THEN 0 ELSE DD.ORD_PRZNET * TT.ORD_CAMBIO END) AS NUMERIC(19,6)) AS EURO_PRNETTO,
		PR.ART_ULPCAR AS ULT_PREZZO_ACQUISTO,
		TT.ORD_DSNAZC AS NAZIONE_DESTINAZIONE,
		COALESCE(P_STA.DESCRI,'') AS NAZIONE_CLIENTE,
		DD.ORD_CCODET AS CENTRO_COSTO,
		COALESCE(CC.CON_DESCR,'') AS DESCR_CENTRO_COSTO
	FROM U_BOL_TT AS TT
	LEFT OUTER JOIN U_BOL_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO AND ORD_CODART <> ''
	LEFT OUTER JOIN U_ART_PR AS PR ON DD.ORD_CODART = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_AN AS AN ON DD.ORD_CODART = AN.ART_CODPRI
	LEFT OUTER JOIN PARA AS FAM ON FAM.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS SFA ON SFA.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,9)
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS P_TPO ON P_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN U_ORD_TT AS OC ON OC.ORD_NUMORD = DD.ORS_NUMORC AND OC.ORD_DATORD = DD.ORS_DATORC
	LEFT OUTER JOIN U_CLI_AN AS CL ON CL.CLI_CODCLI = TT.ORD_CODCLI
	LEFT OUTER JOIN PARA AS P_STA ON P_STA.CODICE = 'STA'+CL.CLI_NAZION
	LEFT OUTER JOIN CCOSTO AS CC ON CC.CON_ANNO = OC.ORD_ANNO AND CC.CON_CONTO = DD.ORD_CCODET
	WHERE
		TT.ORD_FORNI = 0 AND 
		TT.ORD_FLBOL = 'S' AND 
		SUBSTRING(P_TOP.LIBERA,2,1) = 'V' AND
		TT.ORD_NUMORD+TT.ORD_DATORD NOT IN (SELECT ORS_NUMDDT+ORS_DATDDT FROM U_FAT_DD)

GO

SELECT * FROM DDT_BLOCCATI_NON_FATTURATI_CON_DETTAGLI ORDER BY DATA_DDT DESC