
-- VISTA ANAGRAFICA_ARTICOLI_PER_CODICI_DOGANALI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_CARDIOLINE]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_CARDIOLINE]
GO
CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_CARDIOLINE] 
AS
	SELECT
		PR.ART_CODPRI AS CODICE_ARTICOLO
		,PR.ART_DESCR AS DESCRIZIONE_STANDARD
		,COALESCE(DL_010.DESCRI,PR.ART_DESCR) AS DESCRIZIONE_ITALIANO
		,COALESCE(DL_008.DESCRI,PR.ART_DESCR) AS DESCRIZIONE_INGLESE
		,PR.ART_CODCTL AS REV
		,PR.ART_MAGA AS CODICE_MAG
		,PR.ART_DESEST AS ESTENSIONE
		,PR.ART_DESRID AS RIDOTTA_REF
		,PR.ART_CODMAT AS TIPO_PRODOTTO
		,COALESCE(P_MAT.DESCRI,'') AS TIPO_PRODOTTO_DESCRIZIONE
		,PR.ART_OBSOL AS OBSOLETO
		,PR.ART_UNIMIS AS UM_ACQUISTO
		,PR.ART_UMMAGA AS UM_MAGAZZINO_VENDITA
		,PR.ART_CODIVA AS CODICE_IVA
		,PR.ART_QTACON AS QTA_IN_CONFEZIONI
		,PR.ART_PRZVEN AS LISTINO_ITALIA
		,PR.ART_PRZVE2 AS LISTINO_INTERNATIONAL
		,PR.ART_PRZCOS AS PREZZO_COSTO_STANDARD
		,PR.ART_ULPCAR AS PREZZO_COSTO_ULTIMO_CARICO
		,PR.ART_PRZVE5 AS PREZZO_IN_BUNDLE
		,AN.ART_ARTSIMI AS CODICE_ARTICOLO_SIMILE
		,COALESCE(PRS.ART_DESCR,'') AS CODICE_ARTICOLO_SIMILE_DESCRIZIONE
		,PR.ART_CLDOG AS CLASSE_DOGANALE
		,COALESCE(P_DOG.DESCRI,'') AS CLASSE_DOGANALE_DESCRIZIONE
		,AN.ART_SERVINTRA AS SERVIZI_INTRASTAT
		,COALESCE(P_SEI.DESCRI,'') AS SERVIZI_INTRASTAT_DESCRIZIONE
		,AN.ART_CGEACQ AS CONTO_CONTABILE_ACQUISTI
		,COALESCE(CONTI_1.CON_DESCR,'') AS CONTO_CONTABILE_ACQUISTI_DESCRIZIONE
		,AN.ART_CCOACQ AS CENTRO_DI_COSTO_ACQUISTI
		,COALESCE(CCOSTO_1.CON_DESCR,'') AS CENTRO_DI_COSTO_ACQUISTI_DESCRIZIONE
		,PR.ART_CGE AS CONTO_CONTABILE_VENDITE
		,COALESCE(CONTI_2.CON_DESCR,'') AS CONTO_CONTABILE_VENDITE_DESCRIZIONE
		,PR.ART_CCO AS CENTRO_DI_COSTO_VENDITE
		,COALESCE(CCOSTO_2.CON_DESCR,'') AS CENTRO_DI_COSTO_VENDITE_DESCRIZIONE
		,PR.ART_TIPART AS ARTICOLO_DI_PRODUZIONE_ACQUISTO_CONTOLAVORO
		,AN.ART_DSADOG AS STAMPA_DESCRIZIONE_ARTICOLO_IN_COMMENTO_CLASSI_DOG
		,PR.ART_TIPOPR AS TIPO_PRODUZIONE
		,PR.ART_NONMOV AS NON_MOVIMENTA_MAGAZZINO
		,AN.ART_NONVAL AS NON_VISUALIZZA_NEL_SIT
		,AN.ART_NOLISLCK AS SVINCOLA_DA_LISTINO_OBBLIGATORIO
		,PR.ART_LINEA AS LINEA_PRODOTTO
		,COALESCE(P_REP.DESCRI,'') AS LINEA_PRODOTTO_DESCRIZIONE
		,PR.ART_CODIMB AS TIPO_PRELIEVO
		,COALESCE(P_IMB.DESCRI,'') AS TIPO_PRELIEVO_DESCRIZIONE
		,AN.ART_CODTSN AS TIPO_SERIAL_NUMBER
		,COALESCE(P_TSN.DESCRI,'') AS TIPO_SERIAL_NUMBER_DESCRIZIONE
		,AN.ART_TIPSCA AS TIPO_SCADENZA
		,COALESCE(P_TSC.DESCRI,'') AS TIPO_SCADENZA_DESCRIZIONE
		,AN.ART_NGGSCA AS NR_GG_SCADENZA_DEFAULT
		,AN.ART_NGSAVV AS NR_GG_AVVISO_PRIMA_SCADENZA
		,PR.ART_SCORMI AS SCORTA_MINIMA
		,PR.ART_SCORMA AS SCORTA_MASSIMA
		,PR.ART_PESOUM AS PESO_KG
		,PR.ART_LOTMIN AS LOTTO_MINIMO
		,PR.ART_CODCTL AS CODICE_REVISIONE
		,AN.ART_CATPROV	AS CATEGORIA_PROVVIGIONE
		,COALESCE(P_CAP.DESCRI,'') AS CATEGORIA_PROVVIGIONE_DESCRIZIONE
		,PR.ART_PROVVI AS PROVVIGIONE
		,PR.ART_SC1 AS PRIMO_SCONTO
		,PR.ART_TIPO AS NATURA_PRODOTTO
		,COALESCE(P_NAP.DESCRI,'') AS NATURA_PRODOTTO_DESCRIZIONE
		,AN.ART_SCOMAGG AS CATEGORIA_SCONTI
		,COALESCE(P_CSA.DESCRI,'') AS CATEGORIA_SCONTI_DESCRIZIONE
		,PR.ART_PUBBLI AS ARTICOLO_PUBBLICITARIO
		,AN.ART_NOPROV AS NON_CALCOLARE_PROVVIGIONI
		,AN.ART_CODDCA AS MOD_DICH_CONF_ACCETTAZIONE
		,COALESCE(P_MDCA.DESCRI,'') AS MOD_DICH_CONF_ACCETTAZIONE_DESCRIZIONE
		,AN.ART_CODDCP AS MOD_DICH_CONF_PRODUZIONE
		,COALESCE(P_MDCP.DESCRI,'') AS MOD_DICH_CONF_PRODUZIONE_DESCRIZIONE
		,SUBSTRING(AN.ART_CODGMI,1,3) AS GRUPPO
		,COALESCE(CCODGRU.DESCRI,'') AS GRUPPO_DESCRIZIONE
		,SUBSTRING(AN.ART_CODGMI,4,3) AS FAMIGLIA
		,COALESCE(CCODFAM.DESCRI,'') AS FAMIGLIA_DESCRIZIONE
		,SUBSTRING(AN.ART_CODGMI,7,3) AS SOTTOFAMIGLIA
		,COALESCE(CCODMERC.DESCRI,'') AS SOTTOFAMIGLIA_DESCRIZIONE
		,AN.ART_CODGMI AS CODICE_COMPLETO
		,COALESCE(P_GMI.DESCRI,'') AS CODICE_COMPLETO_DESCRIZIONE
		,PR.ART_SERIE AS COD_TIPO_FATTELETTR
		,COALESCE(P_SER.DESCRI,'') AS COD_TIPO_FATTELETTR_DESCRIZIONE
		,PR.ART_CATBEN AS CODVALORE_FATTELETTR
		,PR.ART_CATMER AS CATEGORIA_MERCEOLOGICA
		,COALESCE(P_MER.DESCRI,'') AS CATEGORIA_MERCEOLOGICA_DESCRIZIONE
		,PR.ART_BARFOR AS CODICE_BARRE_FORNITORE
		,PR.ART_BARCLI AS CODICE_UDI_CARDIOLINE
		,AN.ART_LDTMST AS GG_LEAD_TIME_STANDARD
		,AN.ART_MAGCLES AS MAG_CONTO_LAVORO_ESTERNO
		,PR.ART_CODF1 AS FORNITORE1
		,COALESCE(FO1.FOR_RAGSOC,'') AS FORNITORE1_DESCRIZIONE
		,PR.ART_NOTA1 AS COD_ART_FONITORE1
		,PR.ART_PRZCO1 AS COSTO_FORNITORE1
		,COALESCE(FO1.FOR_VALUTA,'') AS VALUTA_FORNITORE1
		,AN.ART_LDTM1 AS GG_LEAD_TIME_FORNITORE1
		,PR.ART_CODF2 AS FORNITORE2
		,COALESCE(FO2.FOR_RAGSOC,'') AS FORNITORE2_DESCRIZIONE
		,PR.ART_NOTA2 AS COD_ART_FONITORE2
		,PR.ART_PRZCO2 AS COSTO_FORNITORE2
		,COALESCE(FO2.FOR_VALUTA,'') AS VALUTA_FORNITORE2
		,AN.ART_LDTM2 AS GG_LEAD_TIME_FORNITORE2
		,PR.ART_CODF3 AS FORNITORE3
		,COALESCE(FO3.FOR_RAGSOC,'') AS FORNITORE3_DESCRIZIONE
		,PR.ART_NOTA3 AS COD_ART_FONITORE3
		,PR.ART_PRZCO3 AS COSTO_FORNITORE3
		,COALESCE(FO3.FOR_VALUTA,'') AS VALUTA_FORNITORE3
		,AN.ART_LDTM3 AS GG_LEAD_TIME_FORNITORE3
		,PR.ART_CODF4 AS FORNITORE4
		,COALESCE(FO4.FOR_RAGSOC,'') AS FORNITORE4_DESCRIZIONE
		,PR.ART_NOTA4 AS COD_ART_FONITORE4
		,PR.ART_PRZCO4 AS COSTO_FORNITORE4
		,COALESCE(FO4.FOR_VALUTA,'') AS VALUTA_FORNITORE4
		,AN.ART_LDTM4 AS GG_LEAD_TIME_FORNITORE4
		,PR.ART_CODF5 AS FORNITORE5
		,COALESCE(FO5.FOR_RAGSOC,'') AS FORNITORE5_DESCRIZIONE
		,PR.ART_NOTA5 AS COD_ART_FONITORE5
		,PR.ART_PRZCO5 AS COSTO_FORNITORE5
		,COALESCE(FO5.FOR_VALUTA,'') AS VALUTA_FORNITORE5
		,AN.ART_LDTM5 AS GG_LEAD_TIME_FORNITORE5
		,AN.ART_ECOMM AS PRODOTTO_ECOMMERCE
		,AN.ART_SCORMIECO AS SCORTA_MINIMA_ECOMMERCE
		,AN.ART_PRZVENWEB AS PREZZO_VENDITA_WEB
		,AN.ART_NONWEB AS NON_PUBBLICARE_ARTICOLO
		,PR.ART_NOTE AS NOTE_ARTICOLO
		,PR.ART_NOTE1 AS NOTE_PRODUTTIVE
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN U_ART_PR AS PRS ON PRS.ART_CODPRI = AN.ART_ARTSIMI
	LEFT OUTER JOIN DESLINGUE AS DL_010 ON DL_010.TIPODES = 'ARTICOLO' AND DL_010.LINGUA = '010' AND DL_010.CODICE = PR.ART_CODPRI
	LEFT OUTER JOIN DESLINGUE AS DL_008 ON DL_008.TIPODES = 'ARTICOLO' AND DL_008.LINGUA = '008' AND DL_008.CODICE = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS P_MAT ON P_MAT.CODICE = 'MAT'+PR.ART_CODMAT
	LEFT OUTER JOIN PARA AS P_DOG ON P_DOG.CODICE = 'DOG'+PR.ART_CLDOG
	LEFT OUTER JOIN PARA AS P_SEI ON P_SEI.CODICE = 'SEI'+AN.ART_SERVINTRA
	LEFT OUTER JOIN CONTI AS CONTI_1 ON CONTI_1.CON_CONTO = AN.ART_CGEACQ AND CONTI_1.CON_ANNO = SUBSTRING(CONVERT(VARCHAR, GETDATE(), 111),1,4)
	LEFT OUTER JOIN CCOSTO AS CCOSTO_1 ON CCOSTO_1.CON_CONTO = AN.ART_CCOACQ AND CCOSTO_1.CON_ANNO = SUBSTRING(CONVERT(VARCHAR, GETDATE(), 111),1,4)
	LEFT OUTER JOIN CONTI AS CONTI_2 ON CONTI_2.CON_CONTO = PR.ART_CGE AND CONTI_2.CON_ANNO = SUBSTRING(CONVERT(VARCHAR, GETDATE(), 111),1,4)
	LEFT OUTER JOIN CCOSTO AS CCOSTO_2 ON CCOSTO_2.CON_CONTO = PR.ART_CCO AND CCOSTO_2.CON_ANNO = SUBSTRING(CONVERT(VARCHAR, GETDATE(), 111),1,4)
	LEFT OUTER JOIN PARA AS P_REP ON P_REP.CODICE = 'REP'+PR.ART_LINEA
	LEFT OUTER JOIN PARA AS P_IMB ON P_IMB.CODICE = 'IMB'+PR.ART_CODIMB
	LEFT OUTER JOIN PARA AS P_TSN ON P_TSN.CODICE = 'TSN'+AN.ART_CODTSN
	LEFT OUTER JOIN PARA AS P_TSC ON P_TSC.CODICE = 'TSC'+AN.ART_TIPSCA
	LEFT OUTER JOIN PARA AS P_CAP ON P_CAP.CODICE = 'CAP'+AN.ART_CATPROV
	LEFT OUTER JOIN PARA AS P_NAP ON P_NAP.CODICE = 'NAP'+PR.ART_TIPO
	LEFT OUTER JOIN PARA AS P_CSA ON P_CSA.CODICE = 'CSA'+AN.ART_SCOMAGG
	LEFT OUTER JOIN PARA AS P_MDCA ON P_MDCA.CODICE = 'MDCA'+AN.ART_CODDCA
	LEFT OUTER JOIN PARA AS P_MDCP ON P_MDCA.CODICE = 'MDCP'+AN.ART_CODDCP
	LEFT OUTER JOIN PARA AS CCODGRU ON CCODGRU.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS CCODFAM ON CCODFAM.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS CCODMERC ON CCODMERC.CODICE = 'GMI'+AN.ART_CODGMI
	LEFT OUTER JOIN PARA AS P_GMI ON P_GMI.CODICE = 'GMI'+AN.ART_CODGMI
	LEFT OUTER JOIN PARA AS P_SER ON P_SER.CODICE = 'SER'+PR.ART_SERIE
	LEFT OUTER JOIN PARA AS P_MER ON P_MER.CODICE = 'MER'+PR.ART_CATMER
	LEFT OUTER JOIN U_FOR_AN AS FO1 ON FO1.FOR_CODCLI = PR.ART_CODF1
	LEFT OUTER JOIN U_FOR_AN AS FO2 ON FO2.FOR_CODCLI = PR.ART_CODF2
	LEFT OUTER JOIN U_FOR_AN AS FO3 ON FO3.FOR_CODCLI = PR.ART_CODF3
	LEFT OUTER JOIN U_FOR_AN AS FO4 ON FO4.FOR_CODCLI = PR.ART_CODF4
	LEFT OUTER JOIN U_FOR_AN AS FO5 ON FO5.FOR_CODCLI = PR.ART_CODF5

GO