
-- VISTA ANAGRAFICA_ARTICOLI_RIDOTTA
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA]
GO

/*
•	Codice articolo
•	Descrizione
•	Gruppo merceologico
•	Famiglia merceologica
•	Sottofamiglia/classe merceologica
•	Costo standard
•	Costo ultimo acquisto
•	Prezzo di vendita ITA
•	Prezzo di vendita INTL
*/

CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_RIDOTTA] 
AS
	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		COALESCE(DL_010.DESCRI,PR.ART_DESCR) AS DESCRIZIONE_ITALIANO,
		COALESCE(DL_008.DESCRI,PR.ART_DESCR) AS DESCRIZIONE_INGLESE,
		SUBSTRING(AN.ART_CODGMI,1,3) AS GRUPPO,
		COALESCE(CCODGRU.DESCRI,'') AS DESGRUPPO,
		SUBSTRING(AN.ART_CODGMI,1,6) AS FAMIGLIA,
		COALESCE(CCODFAM.DESCRI,'') AS DESFAMIGLIA,
		AN.ART_CODGMI AS SOTTOFAMIGLIA,
		COALESCE(CCODMERC.DESCRI,'') AS DESSOTTOFAMIGLIA,
		PR.ART_PRZCOS AS PREZZO_COSTO_STANDARD,
		PR.ART_ULPCAR AS PREZZO_COSTO_ULTIMO_CARICO,
		PR.ART_PRZVEN AS LISTINO_ITALIA,
		PR.ART_PRZVE2 AS LISTINO_INTERNATIONAL
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS CCODGRU ON CCODGRU.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS CCODFAM ON CCODFAM.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS CCODMERC ON CCODMERC.CODICE = 'GMI'+AN.ART_CODGMI 
	LEFT OUTER JOIN DESLINGUE AS DL_010 ON DL_010.TIPODES = 'ARTICOLO' AND DL_010.LINGUA = '010' AND DL_010.CODICE = PR.ART_CODPRI
	LEFT OUTER JOIN DESLINGUE AS DL_008 ON DL_008.TIPODES = 'ARTICOLO' AND DL_008.LINGUA = '008' AND DL_008.CODICE = PR.ART_CODPRI
	WHERE 
		ART_OBSOL <> 'S'
		AND (AN.ART_NOLISLCK = 1 OR ((PR.ART_PRZVEN + PR.ART_PRZVE2) > 0))
GO

SELECT * FROM ANAGRAFICA_ARTICOLI_RIDOTTA ORDER BY COD_ARTICOLO
