

-- VISTA MAIL_CLIENTI_PER_NAZIONE_CANALE_VENDITA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[MAIL_CLIENTI_PER_NAZIONE_CANALE_VENDITA]'))
	DROP VIEW [dbo].[MAIL_CLIENTI_PER_NAZIONE_CANALE_VENDITA]
GO

CREATE VIEW [dbo].[MAIL_CLIENTI_PER_NAZIONE_CANALE_VENDITA]  
AS
SELECT
	CLI_NAZION AS COD_NAZIONE,
	COALESCE(PARA_STA.DESCRI,'') AS DES_NAZIONE,
	CLI_CODCLI AS COD_CLIENTE,
	CLI_RAGSOC AS RAG_SOCIALE,
	CLI_PARIVA AS PIVA,
	CLI_CANVEN AS COD_CANALE_VENDITA,
	COALESCE(PARA_CVE.DESCRI,'') AS DES_CANALE_VENDITA,
	CLI_EMAIL AS E_MAIL_PRINCIPALE,
	CAST(coalesce(stuff((select  '; ' + RTRIM(RIF.RIF_EMAIL)
                from U_RIF_CF as RIF
                where RIF.RIF_CLIFOR = 'C' AND RIF.RIF_CODCLI = CLI.CLI_CODCLI
                for xml path('')
            ),1,2,''),'') AS nvarchar(254)) AS RIFERIMENTI_EMAIL,

	CAST(coalesce(stuff((select  '; ' + RTRIM(E_MAIL)
                from (SELECT CODICE_CLI_FOR, SUBSTRING(INDIRIZZO_A,1,254) AS E_MAIL FROM MAIL_ADDRESS WHERE CLI_FOR = 'C' AND CODICE_CLI_FOR = CLI.CLI_CODCLI GROUP BY CODICE_CLI_FOR,SUBSTRING(INDIRIZZO_A,1,254))
				as GRE
                for xml path('')
            ),1,2,''),'') AS nvarchar(254)) AS GRUPPI_EMAIL_DOCUMENTI
FROM U_CLI_AN AS CLI
LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+CLI.CLI_NAZION
LEFT OUTER JOIN PARA AS PARA_CVE ON PARA_CVE.CODICE = 'CVE'+CLI.CLI_CANVEN
