
-- VISTA ANAGRAFICA_ARTICOLI_PER_UDI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGRAFICA_ARTICOLI_PER_UDI]'))
	DROP VIEW [dbo].[ANAGRAFICA_ARTICOLI_PER_UDI]
GO
CREATE VIEW [dbo].[ANAGRAFICA_ARTICOLI_PER_UDI] 
AS
	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		PR.ART_DESRID AS REF,
		PR.ART_UMMAGA AS UM_MAG,
		PR.ART_MAGA AS COD_MAG,
		PR.ART_LINEA AS COD_LINEA,
		COALESCE(P_LIN.DESCRI,'') AS DESCR_LINEA,
		PR.ART_PRZVEN AS LISTINO_ITALIA,
		PR.ART_PRZVE2 AS LISTINO_INTERNATIONAL,
		PR.ART_PRZCOS AS PREZZO_COSTO_STANDARD,
		PR.ART_ULPCAR AS PREZZO_COSTO_ULTIMO_CARICO,
		AN.ART_CODTSN AS COD_TIPO_SERIAL_NUMBER,
		COALESCE(P_TSN.DESCRI,'') AS DESCR_LINEA_TIPO_SERIAL_NUMBER,
		PR.ART_TIPART AS PRODUZIONE_ACQUISTO,
		PR.ART_TIPOPR AS TIPO_PRODUZIONE,
		AN.ART_CODGMI AS COD_GRUPPO_MERCEOLOGICO_INDUSTRIALE,
		COALESCE(P_GMI.DESCRI,'') AS DESCR_GRUPPO_MERCEOLOGICO_INDUSTRIALE,
		PR.ART_CATMER AS COD_CATEGORIA_MERCEOLOGICA,
		COALESCE(P_MER.DESCRI,'') AS DESCR_CATEGORIA_MERCEOLOGICA,
		PR.ART_SERIE AS COD_TIPO_FATT_ELETTRONICA,
		COALESCE(P_SER.DESCRI,'') AS DESCR_TIPO_FATT_ELETTRONICA,
		PR.ART_CATBEN AS COD_VALORE_FATT_ELETTRONICA,
		PR.ART_BARCLI AS CODICE_BARRE_CARDIOLINE,
		PR.ART_CODF1 AS COD_PRIMO_FORNITORE,
		COALESCE(FORN.FOR_RAGSOC,'') AS DESCR_PRIMO_FORNITORE
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS P_LIN ON P_LIN.CODICE = 'REP'+PR.ART_LINEA 
	LEFT OUTER JOIN PARA AS P_TSN ON P_TSN.CODICE = 'TSN'+AN.ART_CODTSN 
	LEFT OUTER JOIN PARA AS P_GMI ON P_GMI.CODICE = 'GMI'+AN.ART_CODGMI 
	LEFT OUTER JOIN PARA AS P_MER ON P_MER.CODICE = 'MER'+PR.ART_CATMER 
	LEFT OUTER JOIN PARA AS P_SER ON P_SER.CODICE = 'SER'+PR.ART_SERIE 
	LEFT OUTER JOIN U_FOR_AN AS FORN ON FORN.FOR_CODCLI = PR.ART_CODF1 
	WHERE 
		ART_OBSOL <> 'S'
GO

SELECT * FROM ANAGRAFICA_ARTICOLI_PER_UDI ORDER BY COD_ARTICOLO