/*
anno
canale_vendita
macroclasse_cliente
classe_cliente
cod_compl_canale_vendita
codice_cliente
ragione_sociale
indirizzo
regione
nazione
zona
deszona
subzona
centrcosto
centrcosto_descrizione
 codice gruppo 
 gruppo 
partita iva
cliente obsoleto
*/

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ANAGR_CLI_SINTETICA]'))
	DROP VIEW [dbo].[ANAGR_CLI_SINTETICA]
GO

CREATE VIEW [dbo].[ANAGR_CLI_SINTETICA]  
AS
	SELECT
		SUBSTRING(AN.CLI_DATNEW,1,4) AS ANNO_INSERIMENTO,
		AN.CLI_CODCLI AS CODICE,
		AN.CLI_RAGSOC AS RAG_SOCIALE,
		COALESCE(CVEN_1_3.DESCRI,'') AS CANALE_VENDITA,
		COALESCE(CVEN_1_6.DESCRI,'') AS MACROCLASSE_CLIENTE,
		COALESCE(CVEN.DESCRI,'') AS CLASSE_CLIENTE,
		AN.CLI_CANVEN AS COD_COMPL_CANALE_VENDITA,
		AN.CLI_INDIR AS INDIRIZZO,
		AN.CLI_LOCALI AS LOCALITA,
		AN.CLI_CAP AS CAP,
		AN.CLI_PROVIN AS PROVINCIA,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		AN.CLI_NAZION AS NAZIONE,
		COALESCE(CNAZION.DESCRI,'') AS DESNAZIONE,
		AN.CLI_ZONA AS ZONA,
		COALESCE(CZONA.DESCRI,'') AS DESZONA,
		AN.CLI_PROVIN AS PROVINCIA_SUBZONA,
		AN.CLI_CCOST1 AS BU,
		COALESCE(CC_AN.CON_DESCR,'') AS DESCR_BU,
		COALESCE(AN.CLI_APPPRO,'') AS COD_GRUPPO,
		COALESCE(GRUPPO.DESCRI,'') AS DESCR_GRUPPO,
		AN.CLI_PARIVA AS P_IVA,
		AN.CLI_OBSOL AS OBSOLETO
	FROM U_CLI_AN AS AN
	RIGHT OUTER JOIN U_ANA_CL AS CL ON CL.CLI_CODCLI = AN.CLI_CODCLI
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = AN.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN PARA AS GRUPPO ON GRUPPO.CODICE = 'APP'+AN.CLI_APPPRO
	LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+AN.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(AN.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(AN.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	LEFT OUTER JOIN PARA AS CZONA ON CZONA.CODICE = 'ZON'+AN.CLI_ZONA
	LEFT OUTER JOIN PARA AS CNAZION ON CNAZION.CODICE = 'STA'+AN.CLI_NAZION  
	LEFT OUTER JOIN CCOSTO AS CC_AN ON CC_AN.CON_CONTO = AN.CLI_CCOST1 AND CC_AN.CON_ANNO = CAST(YEAR(GETDATE()) AS VARCHAR(4))

GO

SELECT * FROM ANAGR_CLI_SINTETICA ORDER BY CODICE