
-- VISTA FATTURE_CONDIZIONI_PAGAMENTO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_CONDIZIONI_PAGAMENTO]'))
	DROP VIEW [dbo].[FATTURE_CONDIZIONI_PAGAMENTO]
GO

CREATE VIEW [dbo].[FATTURE_CONDIZIONI_PAGAMENTO]  
AS
	SELECT
		ORD_ANNO AS ANNO,
		ORD_TIPOLOGIA AS TIPOLOGIA,
		COALESCE(P_TPO.DESCRI,'') AS DESCRIZIONE_TIPOLOGIA,
		ORD_NUMORD AS NUM_FATTURA,
		ORD_DATORD AS DATA_FATTURA,
		ORD_CPA AS COD_CONDIZ_PAGAMENTO,
		COALESCE(P_CPA.DESCRI,'') AS DESCRIZIONE_CONDIZ_PAGAMENTO,
		CASE COALESCE(SUBSTRING(P_TOP.LIBERA,11,1),'')
			WHEN 'S' THEN -1
			ELSE 1
		END * (ORD_CAMBIO * ORD_VALORE) AS IMPORTO_EUR_CON_IVA,
		CASE COALESCE(SUBSTRING(P_TOP.LIBERA,11,1),'')
			WHEN 'S' THEN -1
			ELSE 1
		END * (ORD_CAMBIO * ORD_IMPONIB) AS IMPORTO_EUR_SENZA_IVA
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN PARA AS P_TPO ON P_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN PARA AS P_CPA ON P_CPA.CODICE = 'CPA'+TT.ORD_CPA
	LEFT OUTER JOIN PARA AS P_TOP ON P_TOP.CODICE = 'TOP'+TT.ORD_CAUS
GO
