
-- VISTA QUALIFICA_FORNITORI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[QUALIFICA_FORNITORI_RIEPILOGATA]'))
	DROP VIEW [dbo].[QUALIFICA_FORNITORI_RIEPILOGATA]
GO
CREATE VIEW [dbo].[QUALIFICA_FORNITORI_RIEPILOGATA]  
AS
	SELECT 
		COD_FORNITORE,
		RAG_SOCIALE,
		(SELECT FOR_NOTE FROM U_FOR_AN WHERE FOR_CODCLI = COD_FORNITORE) AS NOTE,
		LEAD_TIME_STANDARD_MEDIO,
		LEAD_TIME_EFFETTIVO_MEDIO,
		COD_DIVISIONE,
		DESCR_DIVISIONE,
		STRATEGICO,
		OBSOLETO,
		CRITICO,
		COD_TIPOLOGIA,
		DESCR_TIPOLOGIA,
		COD_TIPO_QUALIFICA,
		DESCR_TIPO_QUALIFICA,
		COD_TIPO_CONTRATTO,
		DESCR_TIPO_CONTRATTO,
		SCADENZA_CONTRATTO,
		COD_CLASSE_RISCHIO,
		DESCR_CLASSE_RISCHIO
	FROM (

		SELECT
			COD_FORNITORE,
			RAG_SOCIALE,
			CASE WHEN SUM(CASE WHEN LEAD_TIME_STANDARD > 0 THEN 1 ELSE 0 END) > 0 
				THEN CAST(ROUND(SUM(CASE WHEN LEAD_TIME_STANDARD > 0 THEN LEAD_TIME_STANDARD ELSE 0 END) / SUM(CASE WHEN LEAD_TIME_STANDARD > 0 THEN 1 ELSE 0 END),0) AS INT)
				ELSE 0
			END AS LEAD_TIME_STANDARD_MEDIO,
			CASE WHEN SUM(CASE WHEN LEAD_TIME_EFFETTIVO > 0 THEN 1 ELSE 0 END) > 0 
				THEN CAST(ROUND(SUM(CASE WHEN LEAD_TIME_EFFETTIVO > 0 THEN LEAD_TIME_EFFETTIVO ELSE 0 END) / SUM(CASE WHEN LEAD_TIME_EFFETTIVO > 0 THEN 1 ELSE 0 END),0) AS INT)
				ELSE 0
			END AS LEAD_TIME_EFFETTIVO_MEDIO,
			COD_DIVISIONE,
			DESCR_DIVISIONE,
			STRATEGICO,
			OBSOLETO,
			CRITICO,
			COD_TIPOLOGIA,
			DESCR_TIPOLOGIA,
			COD_TIPO_QUALIFICA,
			DESCR_TIPO_QUALIFICA,
			COD_TIPO_CONTRATTO,
			DESCR_TIPO_CONTRATTO,
			SCADENZA_CONTRATTO,
			COD_CLASSE_RISCHIO,
			DESCR_CLASSE_RISCHIO

			FROM (

				SELECT
					FOR_AN.FOR_CODCLI AS COD_FORNITORE,
					FOR_AN.FOR_RAGSOC AS RAG_SOCIALE,
					FOR_AN.FOR_NOTE AS NOTE,
					COALESCE(ARTICOLI_FORNITORE.ART_CODPRI,'') AS COD_ARTICOLO,
					COALESCE(ARTICOLI_FORNITORE.ART_DESCR,'') AS DESCR_ARTICOLO,
					COALESCE(ARTICOLI_FORNITORE.PREZZO,0) AS PREZZO,
					FOR_AN.FOR_VALUTA AS VALUTA,
					COALESCE(ARTICOLI_FORNITORE.LEAD_TIME_STD,0) AS LEAD_TIME_STANDARD,
					COALESCE(ARTICOLI_FORNITORE.LEAD_TIME,0) AS LEAD_TIME_EFFETTIVO,
					FOR_AN.FOR_DIVISIONE AS COD_DIVISIONE,
					COALESCE(PARA_DIF.DESCRI,'') AS DESCR_DIVISIONE,
					CASE FOR_STRATEGICO WHEN 1 THEN 'SI' ELSE '' END AS STRATEGICO,
					CASE FOR_OBSOL WHEN 'S' THEN 'SI' ELSE '' END AS OBSOLETO,
					CASE FOR_CRITICO WHEN 1 THEN 'SI' ELSE '' END AS CRITICO,
					FOR_AN.FOR_TIPOLOGIA AS COD_TIPOLOGIA,
					COALESCE(PARA_QUF.DESCRI,'') AS DESCR_TIPOLOGIA,
					FOR_AN.FOR_TIPOQUALIF AS COD_TIPO_QUALIFICA,
					COALESCE(PARA_TQF.DESCRI,'') AS DESCR_TIPO_QUALIFICA,
					FOR_AN.FOR_TIPOCONTR AS COD_TIPO_CONTRATTO,
					COALESCE(PARA_TCF.DESCRI,'') AS DESCR_TIPO_CONTRATTO,
					DBO.RIBALTA2(FOR_AN.FOR_SCADCONTR) AS SCADENZA_CONTRATTO,
					FOR_AN.FOR_CLRISCHIO AS COD_CLASSE_RISCHIO,
					COALESCE(PARA_CRF.DESCRI,'') AS DESCR_CLASSE_RISCHIO
				FROM U_FOR_AN AS FOR_AN
				LEFT OUTER JOIN (
						SELECT * FROM (
							SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF1 AS FORNIT,ART_PRZCO1 AS PREZZO, ART_LDTMST AS LEAD_TIME_STD, ART_LDTM1 AS LEAD_TIME, '1' AS NR_FORN FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF1 <> ''
							UNION
							SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF2 AS FORNIT,ART_PRZCO2 AS PREZZO, ART_LDTMST AS LEAD_TIME_STD, ART_LDTM2 AS LEAD_TIME, '2' AS NR_FORN FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF2 <> ''
							UNION
							SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF3 AS FORNIT,ART_PRZCO3 AS PREZZO, ART_LDTMST AS LEAD_TIME_STD, ART_LDTM3 AS LEAD_TIME, '3' AS NR_FORN FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF3 <> ''
							UNION
							SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF4 AS FORNIT,ART_PRZCO4 AS PREZZO, ART_LDTMST AS LEAD_TIME_STD, ART_LDTM4 AS LEAD_TIME, '4' AS NR_FORN FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF4 <> ''
							UNION
							SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF5 AS FORNIT,ART_PRZCO5 AS PREZZO, ART_LDTMST AS LEAD_TIME_STD, ART_LDTM5 AS LEAD_TIME, '5' AS NR_FORN FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF5 <> ''
						) AS ELEN_ARTICOLI_FORNITORE) AS ARTICOLI_FORNITORE
					ON ARTICOLI_FORNITORE.FORNIT = FOR_AN.FOR_CODCLI
				LEFT OUTER JOIN PARA AS PARA_DIF ON PARA_DIF.CODICE = 'DIF'+FOR_AN.FOR_DIVISIONE
				LEFT OUTER JOIN PARA AS PARA_QUF ON PARA_QUF.CODICE = 'QUF'+FOR_AN.FOR_TIPOLOGIA
				LEFT OUTER JOIN PARA AS PARA_TQF ON PARA_TQF.CODICE = 'TQF'+FOR_AN.FOR_TIPOQUALIF
				LEFT OUTER JOIN PARA AS PARA_TCF ON PARA_TCF.CODICE = 'TCF'+FOR_AN.FOR_TIPOCONTR
				LEFT OUTER JOIN PARA AS PARA_CRF ON PARA_CRF.CODICE = 'CRF'+FOR_AN.FOR_CLRISCHIO
				) AS MAIN
		GROUP BY 
			COD_FORNITORE,
			RAG_SOCIALE,
			COD_DIVISIONE,
			DESCR_DIVISIONE,
			STRATEGICO,
			OBSOLETO,
			CRITICO,
			COD_TIPOLOGIA,
			DESCR_TIPOLOGIA,
			COD_TIPO_QUALIFICA,
			DESCR_TIPO_QUALIFICA,
			COD_TIPO_CONTRATTO,
			DESCR_TIPO_CONTRATTO,
			SCADENZA_CONTRATTO,
			COD_CLASSE_RISCHIO,
			DESCR_CLASSE_RISCHIO
		) AS RIEP
GO

SELECT * FROM QUALIFICA_FORNITORI_RIEPILOGATA ORDER BY RAG_SOCIALE