
-- VISTA ELENCO_ORDINI_APERTI

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ELENCO_ORDINI_APERTI]'))
	DROP VIEW [dbo].[ELENCO_ORDINI_APERTI]
GO

CREATE VIEW [dbo].[ELENCO_ORDINI_APERTI]  
AS	
	SELECT 
		TT.ORD_NUMORD AS NUMORD,
		TT.ORD_DATORD AS DATORD,
		TT.ORD_DTCONS AS DATA_CONS,
		COALESCE((SELECT TOP 1 SUBSTRING(VALORE_SUCC,1,10) FROM LOG_EVENTI AS LE LEFT OUTER JOIN UTENTIXRUOLI AS UR ON UR.USERID = LE.COD_USER WHERE UR.RUOLO IN ('LOG','PROD') AND LE.TIPO_EVENTO = 'ORDINI' AND (LE.GRUPPO_EVENTO = 'ORDINE '+RTRIM(TT.ORD_NUMORD)+' DEL '+TT.ORD_DATORD+' MODIFICATO' OR LE.GRUPPO_EVENTO = 'ORDINE '+RTRIM(TT.ORD_NUMORD)+' DEL '+DBO.RIBALTA2(TT.ORD_DATORD)+' MODIFICATO') ORDER BY DATA_EVENTO+ORA_EVENTO DESC),'') AS ULTDATCON,
		TT.ORD_CODCLI AS CODCLI,
		TT.ORD_RAGSOC AS RAGSOC,
		TT.ORD_CAUS AS COD_CAUS,
		COALESCE(PA_TOP.DESCRI,'') AS DES_CAUS,
		TT.ORD_TIPOLOGIA AS COD_TIP,
		COALESCE(PA_TPO.DESCRI,'') AS DES_TIP,
		TT.ORD_MEMO,
		TT.ORD_NOTEEVA AS NOTE_SPED,
		TT.ORD_NOTEEV2 AS NOTE_TESTATA,
		TT.ORD_MOTSCA AS COD_MOTSCA,
		COALESCE(PA_TPO.DESCRI,'') AS DES_MOTSCA,
		TT.ORD_CAMBIO * TT.ORD_IMPONIB AS TOT_IMPONIB_EUR,
		TT.ORD_CAMBIO * TT.ORD_IMPOSTA AS TOT_IMPOSTA_EUR,
		TT.ORD_CAMBIO * TT.ORD_VALORE AS TOT_IMPORTO_EUR,
		CASE ORD_CHIUSO
			WHEN 1 THEN 0
			ELSE (SELECT SUM(CASE WHEN ((ORD_QTAORD - ORD_QTAEV) > 0 AND ORD_CHIUSO = 0) THEN (ORD_QTAORD - ORD_QTAEV) ELSE 0 END * ORD_PRZNET) AS VALRES_EUR FROM U_ORD_DD WHERE DAGGANCIO = TT.TAGGANCIO AND ORD_DESART <> '*** COMMENTO ***' AND ORD_CODART <> '')
		END * TT.ORD_CAMBIO AS VAL_RESIDUO_EUR,
		TT.REG_CODOPE AS REG_CODOPE,
		TT.REG_NOMOPE AS REG_NOMOPE,
		TT.REG_DATREG AS REG_DATREG,
		TT.REG_ORAREG AS REG_ORAREG,
		TT.MOD_CODOPE AS MOD_CODOPE,
		TT.MOD_NOMOPE AS MOD_NOMOPE,
		TT.MOD_DATREG AS MOD_DATREG,
		TT.MOD_ORAREG AS MOD_ORAREG
	FROM U_ORD_TT AS TT
	LEFT OUTER JOIN PARA AS PA_TOP ON PA_TOP.CODICE = 'TOP'+TT.ORD_CAUS
	LEFT OUTER JOIN PARA AS PA_TPO ON PA_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN PARA AS PA_MSC ON PA_MSC.CODICE = 'MSC'+TT.ORD_MOTSCA
	WHERE TT.ORD_CHIUSO = 0
GO

--SELECT * FROM ELENCO_ORDINI_APERTI ORDER BY DATORD, NUMORD