
-- VISTA GIACENZE_RAGGR_SLOW_MOVING

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GIACENZE_RAGGR_SLOW_MOVING]'))
	DROP VIEW [dbo].[GIACENZE_RAGGR_SLOW_MOVING]
GO

CREATE VIEW [dbo].[GIACENZE_RAGGR_SLOW_MOVING]  
AS
	SELECT
		CODMAG,
		CODART,
		DESART,
		UM,
		SUM(GIACEN) AS GIACEN,
		SUM(QTAIMP) AS QTAIMP,
		PRZSTD,
		PRZULT,
		PRZMEP,
		LINEA,
		DESLIN,
		CODGMI,
		DESGMI,
		DESGMI_1_3,
		DESGMI_1_6,
		CODREV,
		CONVERT(VARCHAR,MAX(CAST(DBO.RIBALTA2(DATCAR) AS datetime)), 111) AS DATULTCAR,
		(SELECT TOP 1 MOV_DTREGI FROM U_MAG_MO WHERE MOV_CODMAG = MAIN2.CODMAG AND MOV_ANAART = MAIN2.CODART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' ORDER BY MOV_DTREGI DESC) AS DATULTCAR_ART_MAG,
		(SELECT COALESCE(SUM(MOV_QTAMOV),0) AS QTASCAR FROM U_MAG_MO WHERE MOV_CODMAG = MAIN2.CODMAG AND MOV_ANAART = MAIN2.CODART AND MOV_DTREGI > CONVERT(varchar, DATEADD(YEAR, -2, GETDATE()), 111) AND MOV_DOCMOD = 0 AND MOV_SEGNO = '-') AS QTASCAR_LAST2Y,
		(SELECT TOP 1 MOV_DTREGI FROM U_MAG_MO WHERE MOV_CODMAG = MAIN2.CODMAG AND MOV_ANAART = MAIN2.CODART AND MOV_DOCMOD = 0 ORDER BY MOV_DTREGI DESC) AS DATULTMOV_ART_MAG
	FROM (
		SELECT
			MAG_DATAGG AS DATCAR,
			MAG_ORACAR AS ORACAR,
			MAG_CODMAG AS CODMAG,
			MAG_ANAART AS CODART,
			ART_DESCR AS DESART,
			ART_UMMAGA AS UM,
			MAG_SERIAL AS SERIAL,
			MAG_GIACEN AS GIACEN,
			MAG_QTAIMP AS QTAIMP,
			ART_PRZCOS AS PRZSTD,
			ART_CODGMI AS CODGMI,
			DESGMI_1_6 AS DESGMI,
			MAG_CODCTL AS CODREV,
			ULT_PREACQ AS PRZULT,
			MEP_PREACQ AS PRZMEP,
			ART_LINEA AS LINEA,
			DESLIN,
			DESGMI_1_3,
			DESGMI_1_6,
			MAG_GIACEN	* ULT_PREACQ AS VALULT,
			MAG_PRZCON AS PRZEFF,
			MAG_GIACEN	* MAG_PRZCON AS VALEFF,
			MPF_CODCLI,
			MPF_DESCLI, 
			MPF_NUMDOC, 
			MPF_DTDOCU
			FROM (
				SELECT
					GG.MAG_LEGAME,
					GG.MAG_DATAGG,
					GG.MAG_ORACAR,
					GG.MAG_CODMAG,
					MG.DESCRI,
					GG.MAG_ANAART,
					PR.ART_DESCR,
					PR.ART_UMMAGA,
					PR.ART_PRZCOS,
					PR.ART_LINEA,
					PR.ART_CODCTL,
					COALESCE(LN.DESCRI,'') AS DESLIN,
					GG.MAG_GIACEN,
					GG.MAG_QTAIMP,
					GG.MAG_SERIAL,
					GG.MAG_PRZCON,
					GG.MAG_FORNIT,
					GG.MAG_DTSCAD,
					AN.ART_CODGMI,
					COALESCE(GM.DESCRI,'') AS DESGMI,
					COALESCE(GM_1_3.DESCRI,'') AS DESGMI_1_3,
					COALESCE(GM_1_6.DESCRI,'') AS DESGMI_1_6,
					COALESCE(PR.ART_ULPCAR,0) AS ULT_PREACQ,
					COALESCE((SELECT TOP 1 MOV_FORNIT FROM U_MAG_MO WHERE MOV_ANAART = GG.MAG_ANAART AND MOV_DOCMOD = 0 AND MOV_SEGNO = '+' AND MOV_PREACQ > 0 ORDER BY MOV_DTREGI DESC, MOV_ORAMOV DESC),'') AS ULT_FORNIT,
					COALESCE(
						(SELECT
							CASE WHEN SOMMA_QTA > 0 THEN SOMMA_QTA_PER_PREZZO / SOMMA_QTA ELSE 0 END AS PREZZO_MEDIO_PONDERATO_GIACENZE
						 FROM (
							SELECT 
								COALESCE(SUM(CASE WHEN (MAG_GIACEN > 0 AND MAG_PRZCON > 0) THEN MAG_GIACEN * MAG_PRZCON ELSE 0 END),0) AS SOMMA_QTA_PER_PREZZO, 
								COALESCE(SUM(CASE WHEN (MAG_GIACEN > 0 AND MAG_PRZCON > 0) THEN MAG_GIACEN ELSE 0 END),0) AS SOMMA_QTA FROM (
									SELECT MAG_GIACEN,MAG_PRZCON FROM U_MAG_GG WHERE MAG_ANAART = GG.MAG_ANAART AND MAG_PRZCON > 0 
								) AS MAIN
							) AS T1),0) AS MEP_PREACQ,
					COALESCE(MV.MOV_VALUTA,'') AS MAG_VALUTA, 
					COALESCE(VV.VVA_CHANGE,1) AS MAG_CHANGE,
					GG.MAG_CODCTL,
					COALESCE(MC.MOV_CODCLI,'') AS MPF_CODCLI,
					COALESCE(MC.MOV_DESCLI,'') AS MPF_DESCLI, 
					COALESCE(MC.MOV_NUMDOC,'') AS MPF_NUMDOC, 
					COALESCE(MC.MOV_DTDOCU,'') AS MPF_DTDOCU
				FROM U_MAG_GG AS GG
				LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = GG.MAG_ANAART
				LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
				LEFT OUTER JOIN PARA AS GM ON GM.CODICE = 'GMI'+AN.ART_CODGMI
				LEFT OUTER JOIN PARA AS GM_1_3 ON GM_1_3.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
				LEFT OUTER JOIN PARA AS GM_1_6 ON GM_1_6.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
				LEFT OUTER JOIN PARA AS MG ON MG.CODICE = 'MAG'+GG.MAG_CODMAG
				LEFT OUTER JOIN PARA AS LN ON LN.CODICE = 'REP'+PR.ART_LINEA
				--OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_DTREGI = GG.MAG_DATAGG AND MOV_LEGAME = GG.MAG_LEGAME ORDER BY MOV_DTREGI) AS MV 
				OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_VALUTA, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_SEGNO = '+' AND MOV_DTREGI <= GG.MAG_DATAGG AND MOV_LEGAME = GG.MAG_LEGAME ORDER BY MOV_DTREGI,MOV_ORAMOV) AS MV  -- ERASMO - 18/05/2023
				OUTER APPLY (SELECT TOP 1 * FROM U_VVA_CH WHERE VVA_CODVAL = MV.MOV_VALUTA AND VVA_DATA <= (CASE WHEN MV.MOV_DTDOCU = '' THEN MV.MOV_DTREGI ELSE MV.MOV_DTDOCU END) ORDER BY VVA_DATA DESC) AS VV
				OUTER APPLY (SELECT TOP 1 MOV_LEGAME, MOV_DTREGI, MOV_CODCLI, MOV_DESCLI, MOV_NUMDOC, MOV_DTDOCU FROM U_MAG_MO WHERE MOV_CODMAG = 'MPF' AND MOV_TOP <> 'CF' AND MOV_SEGNO = '-' AND MOV_LEGAME = GG.MAG_LEGAME AND MOV_LEGSYS = GG.MAG_LEGSYS ORDER BY MOV_DTREGI) AS MC 
				WHERE GG.MAG_GIACEN <> 0
		) AS MAIN
	) AS MAIN2
	GROUP BY 
		CODMAG,
		CODART,
		DESART,
		UM,
		PRZSTD,
		PRZULT,
		PRZMEP,
		LINEA,
		DESLIN,
		CODGMI,
		DESGMI,
		DESGMI_1_3,
		DESGMI_1_6,
		CODREV

GO

