-- VISTA CLASSIFICAZIONE_ARTICOLI
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CLASSIFICAZIONE_ARTICOLI]'))
	DROP VIEW [dbo].[CLASSIFICAZIONE_ARTICOLI]
GO
CREATE VIEW [dbo].[CLASSIFICAZIONE_ARTICOLI]  
AS
	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCRIZIONE,
		PR.ART_TIPART AS TIPO_ARTICOLO,
		PR.ART_TIPOPR AS TIPO_PRODUZIONE,
		PR.ART_NONMOV AS NON_MOVIMENTA_MAG,
		AN.ART_NONVAL AS NON_VISUALIZZA_NEL_SIT,
		PR.ART_LINEA AS LINEA_PROD,
		COALESCE(PARA_REP.DESCRI,'') AS DESCR_LINEA_PROD,
		AN.ART_CODTSN AS TIPO_SN,
		COALESCE(PARA_TSN.DESCRI,'') AS DESCR_TIPO_SN,
		SUBSTRING(AN.ART_CODGMI,1,3) AS GRUPPO,
		COALESCE(PARA_GMI_1_3.DESCRI,'') AS DESCR_GRUPPO,
		SUBSTRING(AN.ART_CODGMI,4,3) AS FAMIGLIA,
		COALESCE(PARA_GMI_1_6.DESCRI,'') AS DESCR_FAMIGLIA,
		SUBSTRING(AN.ART_CODGMI,7,3) AS SOTTOFAMIGLIA,
		COALESCE(PARA_GMI_1_9.DESCRI,'') AS DESCR_SOTTOFAMIGLIA,
		PR.ART_CATMER AS CATEG_MERCEOLOG,
		COALESCE(PARA_MER.DESCRI,'') AS DESCR_CATEG_MERCEOLOG
	FROM U_ART_PR AS PR
	LEFT OUTER JOIN U_ART_AN AS AN ON PR.ART_CODPRI = AN.ART_CODPRI
	LEFT OUTER JOIN PARA AS PARA_REP ON PARA_REP.CODICE = 'REP'+PR.ART_LINEA
	LEFT OUTER JOIN PARA AS PARA_TSN ON PARA_TSN.CODICE = 'TSN'+AN.ART_CODTSN
	LEFT OUTER JOIN PARA AS PARA_GMI_1_3 ON PARA_GMI_1_3.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,3)
	LEFT OUTER JOIN PARA AS PARA_GMI_1_6 ON PARA_GMI_1_6.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,6)
	LEFT OUTER JOIN PARA AS PARA_GMI_1_9 ON PARA_GMI_1_9.CODICE = 'GMI'+SUBSTRING(AN.ART_CODGMI,1,9)
	LEFT OUTER JOIN PARA AS PARA_MER ON PARA_MER.CODICE = 'MER'+PR.ART_CATMER

GO

SELECT * FROM CLASSIFICAZIONE_ARTICOLI ORDER BY COD_ARTICOLO