-- VISTA ORDINATO CON DESTINAZIONE

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_CON_DESTINAZIONE]'))
	DROP VIEW [dbo].[ORDINATO_CON_DESTINAZIONE]
GO

CREATE VIEW [dbo].[ORDINATO_CON_DESTINAZIONE]  
AS
	SELECT 
		TT.ORD_CODCLI AS COD_CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_DATORD AS DATA_ORDINE,
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_RIFERI AS RIFERIMENTO,
		CLI.CLI_ZONA AS ZONA,
		P1.DESCRI AS DESC_ZONA,
		CLI.CLI_NAZION AS NAZIONE,
		P2.DESCRI AS DESC_NAZIONE,
		DD.ORD_CODART AS CODICE_ARTICOLO,
		DD.ORD_DESART  AS DESCR_ARTICOLO,
		DD.ORD_UM AS UM,
		DD.ORD_QTAORD AS QTA,
		DD.ORD_PRZNET AS PREZZO,
		DD.ORD_VALORE AS VALORE,
		DD.ORD_QTAEV AS QTA_EVASA,
		DD.ORD_CHIUSO AS CHIUSO,
		RTRIM(TT.ORD_RAGC) AS DESTINAZIONE_RAG_SOCIALE,
		RTRIM(TT.ORD_INDC) AS DESTINAZIONE_INDIRIZZO,
		RTRIM(TT.ORD_CAPC) AS DESTINAZIONE_CAP,
		RTRIM(TT.ORD_LOCC) AS DESTINAZIONE_LOCALITA,
		RTRIM(TT.ORD_PROC) AS DESTINAZIONE_PROVINCIA,
		CASE TT.ORD_DSNAZC WHEN '' THEN P2.DESCRI ELSE TT.ORD_DSNAZC END AS DESTINAZIONE_NAZIONE
	FROM U_ORD_DD AS DD
	LEFT OUTER JOIN U_ORD_TT AS TT ON TT.TAGGANCIO = DD.DAGGANCIO
	LEFT OUTER JOIN U_CLI_AN AS CLI	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS P1 ON 'ZON'+CLI.CLI_ZONA = P1.CODICE
	LEFT OUTER JOIN PARA AS P2 ON 'STA'+CLI.CLI_NAZION = P2.CODICE
	LEFT OUTER JOIN PARA AS P3 ON 'PRO'+CLI.CLI_PROVIN = P3.CODICE
	WHERE ORD_QTAORD<>0 AND ORD_DESART <> '*** COMMENTO ***'
GO



