
/****** Object:  View [dbo].[LETTERE_INTENTO_FORNITORI]    Script Date: 13/03/2017 15:01:16 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[LETTERE_INTENTO_FORNITORI]'))
	DROP VIEW [dbo].[LETTERE_INTENTO_FORNITORI]
GO
CREATE VIEW [dbo].[LETTERE_INTENTO_FORNITORI]  
AS

SELECT 
	FOR_RAGSOC,
	FOR_PARIVA,
	FOR_INDIR,
	FOR_CAP,
	FOR_LOCALI,
	FOR_CLIES AS PROT,
	for_dtcles,
	CASE FOR_INTDUE WHEN 'XX' THEN FOR_ANNOPE ELSE '' END AS ANNO_PLAFOND,
	CASE FOR_INTDUE WHEN 'XX' THEN for_IMPINT ELSE 0 END AS IMPORTO_PLAFOND
FROM U_FOR_AN
WHERE FOR_CLIES<>''


GO


