
-- VISTA QUALIFICA_FORNITORI_X_GRUPPO_MERC
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[QUALIFICA_FORNITORI_X_GRUPPO_MERC]'))
	DROP VIEW [dbo].[QUALIFICA_FORNITORI_X_GRUPPO_MERC]
GO
CREATE VIEW [dbo].[QUALIFICA_FORNITORI_X_GRUPPO_MERC]  
AS
	SELECT
		COD_FORNITORE,
		RAG_SOCIALE,
		STATO,
		DATA_QUALIFICA,
		DICHIARAZ_CONF,
		CE,
		LTA,
		ISO1,
		ISO2,
		ISO3,
		TIPOLOGIA_FORNITORE,
		STRATEGICO,
		CRITICO,
		PAESE,
		CLASSE_MERCEOLOGICA FROM (
		SELECT
			FOR_AN.FOR_CODCLI AS COD_FORNITORE,
			FOR_AN.FOR_RAGSOC AS RAG_SOCIALE,
			CASE FOR_OBSOL WHEN 'S' THEN 'OBSOLETO' ELSE 'ATTIVO' END AS STATO,
			'' AS DATA_QUALIFICA,
			'' AS DICHIARAZ_CONF,
			'' AS CE,
			'' AS LTA,
			'' AS ISO1,
			'' AS ISO2,
			'' AS ISO3,
			CASE FOR_TIPOQUALIF WHEN 'MED' THEN 'MEDICALE' WHEN 'IS1' THEN 'MEDICALE' ELSE 'NON MEDICALE' END AS TIPOLOGIA_FORNITORE,
			CASE FOR_STRATEGICO WHEN 1 THEN 'SI' ELSE 'NO' END AS STRATEGICO,
			CASE FOR_CRITICO WHEN 1 THEN 'SI' ELSE 'NO' END AS CRITICO,
			FOR_NAZION AS PAESE,
			ARTICOLI_FORNITORE.ART_CODPRI,
			COALESCE(ARTICOLI_FORNITORE.ART_CODGMI,'') AS CODGMI,
			COALESCE(GMI.DESCRI,'') AS CLASSE_MERCEOLOGICA
		FROM U_FOR_AN AS FOR_AN
		LEFT OUTER JOIN (
				SELECT * FROM (
					SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF1 AS FORNIT,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF1 <> ''
					UNION
					SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF2 AS FORNIT,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF2 <> ''
					UNION
					SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF3 AS FORNIT,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF3 <> ''
					UNION
					SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF4 AS FORNIT,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF4 <> ''
					UNION
					SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODF5 AS FORNIT,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI AND ART_CODF5 <> ''
					UNION
					SELECT ORD_CODART AS ART_CODPRI,ART_DESCR,ORS_CODCLI AS FORNIT,ART_CODGMI FROM U_BFO_DD AS BD
						LEFT OUTER JOIN (SELECT U_ART_PR.ART_CODPRI,ART_DESCR,ART_CODGMI FROM U_ART_PR,U_ART_AN WHERE U_ART_PR.ART_CODPRI = U_ART_AN.ART_CODPRI ) AS AA ON AA.ART_CODPRI = BD.ORD_CODART
				) AS ELEN_ARTICOLI_FORNITORE) AS ARTICOLI_FORNITORE
			ON ARTICOLI_FORNITORE.FORNIT = FOR_AN.FOR_CODCLI
		LEFT OUTER JOIN PARA AS GMI ON GMI.CODICE = 'GMI'+ARTICOLI_FORNITORE.ART_CODGMI
	) AS MAIN
	GROUP BY
		COD_FORNITORE,
		RAG_SOCIALE,
		STATO,
		DATA_QUALIFICA,
		DICHIARAZ_CONF,
		CE,
		LTA,
		ISO1,
		ISO2,
		ISO3,
		TIPOLOGIA_FORNITORE,
		STRATEGICO,
		CRITICO,
		PAESE,
		CLASSE_MERCEOLOGICA
	
GO

SELECT * FROM QUALIFICA_FORNITORI_X_GRUPPO_MERC ORDER BY RAG_SOCIALE