
-- VISTA USCITA_MATERIALE_PER_DATA_UM

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[USCITA_MATERIALE_PER_DATA_UM]'))
	DROP VIEW [dbo].[USCITA_MATERIALE_PER_DATA_UM]
GO

CREATE VIEW [dbo].[USCITA_MATERIALE_PER_DATA_UM]  
AS

	SELECT
		MOV_DTREGI AS DATA,
		MOV_UM AS UM,
		SUM(MOV_QTAMOV) AS QUANTITA
	FROM U_MAG_MO
	WHERE MOV_TOP = 'VK'
	GROUP BY MOV_DTREGI,MOV_UM

GO

SELECT * FROM USCITA_MATERIALE_PER_DATA_UM WHERE DATA = '2021/05/31' ORDER BY DATA,UM