
-- CAMPI NECESSARI: TUTTI QUELLI VISIBILI IN SITUAZIONE GIACENZE MAG. TRANNE DATA ULT. VEND.

-- VISTA ARTICOLI_MOVIMENTATI_DAL_01012023
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ARTICOLI_MOVIMENTATI_DAL_01012023]'))
	DROP VIEW [dbo].[ARTICOLI_MOVIMENTATI_DAL_01012023]
GO
CREATE VIEW [dbo].[ARTICOLI_MOVIMENTATI_DAL_01012023]  
AS


SELECT * FROM (
	SELECT
		PR.ART_CODPRI AS COD_ARTICOLO,
		PR.ART_DESCR AS DESCR_ARTICOLO,
		PR.ART_CODCTL AS COD_REV,
		PR.ART_UMMAGA AS UM,
		PR.ART_NONMOV AS NON_MOVIMENTA_MAG,
		--dbo.ribalta2(ULT_MO.MOV_DTREGI) AS DATA_ULT_MOVIMENTO,
		--COALESCE(dbo.ribalta2(ULT_MO.MOV_DTREGI),'NON MOVIMENTATO DAL 01/01/2023') AS DATA_ULT_MOVIMENTO,
		CASE 
			WHEN ULT_MO.MOV_DTREGI IS NULL THEN 'NON MOVIMENTATO DAL 01/01/2023'
			ELSE CAST(dbo.ribalta2(ULT_MO.MOV_DTREGI) AS VARCHAR(50))
		END AS DATA_ULT_MOVIMENTO,
		--COALESCE((SELECT TOP 1 DBO.RIBALTA2(MOV_DTREGI) FROM U_MAG_MO WHERE MOV_DTREGI >= '2023/01/01' AND MOV_DOCMOD = 0 AND MOV_ANAART = PR.ART_CODPRI ORDER BY MOV_DTREGI,MOV_ORAMOV),'MAI MOVIMENTATO DAL 01/01/2023') AS DATA_ULT_MOVIMENTO,
		COALESCE(GIAC.MAG_CODMAG,'') AS COD_MAG,
		COALESCE(GIAC.MAG_GIACEN,0) AS GIACENZA_MAG,
		COALESCE(GIAC.MAG_QTAIMP,0) AS QTA_IMP,
		PR.ART_LINEA AS LINEA_PRODOTTO,
		COALESCE(LN.DESCRI,'') AS DESCR_LINEA,
		AN.ART_CODGMI AS COD_GRUPPO_MERC_IND,
		COALESCE(GM.DESCRI,'') AS DESCR_GRUPPO_MERC_IND,
		PR.ART_ULPCAR AS PRZ_COSTO_ULTIMO_CARICO,
		COALESCE(GIAC.MAG_GIACEN,0) * PR.ART_ULPCAR AS VAL_COSTO_ULTIMO_CARICO,
		PR.ART_PRZCOS AS PRZ_COSTO_STANDARD,
		COALESCE(GIAC.MAG_GIACEN,0) * PR.ART_PRZCOS AS VAL_COSTO_STANDARD,
		COALESCE(GIAC.MAG_VALACQ,0) AS VAL_COSTO_EFFETTIVO_GIAC_IN_VALUTA,
		PR.ART_CSTCAT AS COD_SOTTOCAT_SOTTOFAM,
		PR.ART_DSTCAT AS DESCR_SOTTOCAT_SOTTOFAM
	FROM U_ART_PR AS PR
	OUTER APPLY (SELECT TOP 1 MOV_DTREGI FROM U_MAG_MO WHERE MOV_DTREGI >= '2023/01/01' AND MOV_DOCMOD = 0 AND MOV_ANAART = PR.ART_CODPRI ORDER BY MOV_DTREGI,MOV_ORAMOV) AS ULT_MO
	LEFT OUTER JOIN (SELECT MAG_CODMAG,MAG_ANAART,SUM(MAG_GIACEN) AS MAG_GIACEN,SUM(MAG_QTAIMP) AS MAG_QTAIMP,SUM(MAG_GIACEN*MAG_PRZCON) AS MAG_VALACQ FROM U_MAG_GG WHERE MAG_DATAGG <> '' GROUP BY MAG_CODMAG,MAG_ANAART) AS GIAC ON GIAC.MAG_ANAART = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS LN ON LN.CODICE = 'REP'+PR.ART_LINEA
	LEFT OUTER JOIN U_ART_AN AS AN ON AN.ART_CODPRI = PR.ART_CODPRI
	LEFT OUTER JOIN PARA AS GM ON GM.CODICE = 'GMI'+AN.ART_CODGMI
) AS MAIN



GO

SELECT * FROM ARTICOLI_MOVIMENTATI_DAL_01012023 ORDER BY COD_ARTICOLO


