-- VISTA ORDINI_FORNITORI_NON_EVASI_CON_DATA_CONS_MODIF

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINI_FORNITORI_NON_EVASI_CON_DATA_CONS_MODIF]'))
	DROP VIEW [dbo].[ORDINI_FORNITORI_NON_EVASI_CON_DATA_CONS_MODIF]
GO

CREATE VIEW [dbo].[ORDINI_FORNITORI_NON_EVASI_CON_DATA_CONS_MODIF]  
AS

	SELECT * FROM (
		SELECT 	
			CODICE_FORNITORE,
			FORNITORE,
			NUM_ORDINE,
			DATA_ORDINE,
			CODICE_ARTICOLO,
			DESCRIZIONE_ARTICOLO,
			UM,
			QTA_ORDINATA,
			CENTRO_COSTO,
			DESCRIZIONE_CENTRO_COSTO,
			DATA_CONSEGNA,
			(SELECT TOP 1 VALORE_PREC FROM LOG_EVENTI 
			 WHERE TIPO_EVENTO='ORDFOR' AND CAMPO_MODIFICATO='DATA CONSEGNA' 
			 --AND DATA_EVENTO = convert(varchar, DATEADD(day, -<<_GIORNI_PRECEDENTI>>, GETDATE()), 111) 
			 AND DESCRIZIONE LIKE 'ARTICOLO ' + RTRIM(CODICE_ARTICOLO) + ' (%'
			 AND VALORE_SUCC = DATA_CONSEGNA
			 AND NUM_ORDINE=SUBSTRING(GRUPPO_EVENTO,18,6)
			 ORDER BY DATA_EVENTO+ORA_EVENTO DESC
			) AS DATA_CONSEGNA_PRECEDENTE,
			VALORE
		FROM (
			SELECT T1.*,CCO.CON_DESCR AS DESCRIZIONE_CENTRO_COSTO FROM (
			SELECT
				TT.ORD_CODCLI AS CODICE_FORNITORE,
				TT.ORD_RAGSOC AS FORNITORE,
				TT.ORD_NUMORD AS NUM_ORDINE,
				SUBSTRING(TT.ORD_DATORD,9,2)+'/'+SUBSTRING(TT.ORD_DATORD,6,2)+'/'+SUBSTRING(TT.ORD_DATORD,1,4) AS DATA_ORDINE,
				DD.ORD_CCODET AS CENTRO_COSTO,
				DD.ORD_CODART AS CODICE_ARTICOLO,
				DD.ORD_DESART AS DESCRIZIONE_ARTICOLO,
				SUBSTRING(DD.ORD_DATCON,9,2)+'/'+SUBSTRING(DD.ORD_DATCON,6,2)+'/'+SUBSTRING(DD.ORD_DATCON,1,4) AS DATA_CONSEGNA,
				DD.ORD_UM AS UM,
				DD.ORD_QTAORD AS QTA_ORDINATA,
				DD.ORD_VALORE AS VALORE
			FROM U_ORF_TT AS TT
			LEFT OUTER JOIN U_ORF_DD AS DD
			ON TT.TAGGANCIO=DD.DAGGANCIO
			WHERE 
				DD.ORD_QTAORD>0
				AND DD.ORD_CHIUSO=0 
				AND TT.ORD_CHIUSO=0
			) AS T1
			LEFT OUTER JOIN (SELECT DISTINCT CON_CONTO, CON_DESCR FROM  CCOSTO) AS CCO
			ON T1.CENTRO_COSTO = CON_CONTO
			WHERE 
				--T1.CODICE_FORNITORE <> (SELECT TOP 1 AZI_CODCLI FROM U_AZI_AN)
				T1.CODICE_ARTICOLO NOT LIKE '.%'
			) AS MAIN
		WHERE NUM_ORDINE+' DEL '+DBO.RIBALTA2(DATA_ORDINE) IN (SELECT SUBSTRING(GRUPPO_EVENTO,18,21) AS NUMORD FROM LOG_EVENTI WHERE TIPO_EVENTO='ORDFOR' AND CAMPO_MODIFICATO='DATA CONSEGNA' AND DESCRIZIONE NOT LIKE 'ARTICOLO .%' )
		--GROUP BY CENTRO_COSTO,DESCRIZIONE_CENTRO_COSTO,CODICE_FORNITORE,FORNITORE,NUM_ORDINE,DATA_ORDINE_RIBALTATA,DATA_ORDINE,DATA_CONSEGNA_RIBALTATA,DATA_CONSEGNA
		) AS MAIN2
	WHERE DATA_CONSEGNA_PRECEDENTE <> ''
