
-- VISTA CLIENTI_ANALITICA

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTI_ANALITICA]'))
	DROP VIEW [dbo].[CLIENTI_ANALITICA]
GO

CREATE VIEW [dbo].[CLIENTI_ANALITICA]  
AS
	SELECT
		CLI.CLI_CODCLI AS CODICE_CLIENTE,
		CLI.CLI_RAGSOC AS RAGIONE_SOCIALE,	
		CLI.CLI_NAZION AS CODICE_NAZIONE,
		CLI.CLI_PARIVA AS PIVA,
		CLI.CLI_CODFIS AS CFISC,
		CLI.CLI_IVACEE AS PIVA_CEE,
		CLI.CLI_TELEFO AS TELEFONO,
		CLI.CLI_EMAIL AS EMAIL,
		CLI.CLI_INDIR AS INDIRIZZO,
		NAZ.DESCRI AS NAZIONE,
		CLI.CLI_LOCALI AS LOCALITA,
		CLI.CLI_PROVIN AS PROVINCIA,
		COALESCE(REGIONI.REGIONE,'') AS REGIONE,
		CLI.CLI_ZONA AS ZONA,
		COALESCE(CZONA.DESCRI,'') AS DESZONA,
		CLI.CLI_CCOST1 AS CENTRCOSTO,
		COALESCE(CC.CON_DESCR,'') AS BU,
		(SELECT COUNT(*) FROM U_OFF_TT WHERE ORD_ANNO='2014' AND ORD_CODCLI=CLI_CODCLI) AS NR_PREVENTIVI_ANNO_PREC,
		(SELECT COUNT(*) FROM U_ORD_TT WHERE ORD_ANNO='2014' AND ORD_CODCLI=CLI_CODCLI) AS NR_ORDINI_ANNO_PREC,
		(SELECT COUNT(*) FROM U_BOL_TT WHERE ORD_ANNO='2014' AND ORD_CODCLI=CLI_CODCLI) AS NR_BOLLE_ANNO_PREC,
		(SELECT COUNT(*) FROM U_FAT_TT WHERE ORD_ANNO='2014' AND ORD_CODCLI=CLI_CODCLI) AS NR_FATTURE_ANNO_PREC
	FROM U_CLI_AN AS CLI
	LEFT OUTER JOIN (SELECT DISTINCT CON_CONTO, CON_DESCR FROM CCOSTO) AS CC
	ON CLI.CLI_CCOST1 = CC.CON_CONTO 
	LEFT OUTER JOIN PARA AS NAZ
	ON NAZ.CODICE = 'STA'+CLI.CLI_NAZION  
	LEFT OUTER JOIN PARA AS CVEN
	ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN  
	LEFT OUTER JOIN PARA AS CZONA
	ON CZONA.CODICE = 'ZON'+CLI.CLI_ZONA  
	LEFT OUTER JOIN PROVINCE 
	ON PROVINCE.SIGLA = CLI.CLI_PROVIN
	LEFT OUTER JOIN REGIONI ON 
	REGIONI.CODICE = PROVINCE.REGIONE
	WHERE CLI_OBSOL=''

GO


