
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PART_FOR_ESCL_SCAD]'))
	DROP VIEW [dbo].[PART_FOR_ESCL_SCAD]
GO

CREATE VIEW [dbo].[PART_FOR_ESCL_SCAD]  
AS

	SELECT
		PAR_CODCLI AS CODICE,
		PAR_RAGSOC AS RAG_SOC,
		PAR_NREG AS N_REG,
		PAR_DTREG AS DATA_REG,
		PAR_TIPFAT AS COD_TOP,
		PAR_NUMFAT AS N_FAT,
		PAR_DTFAT AS DATA_FAT,
		PAR_TMOV AS DA_AV,
		PAR_FATT AS IMPORTO
	FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_NOPART = 1

GO


SELECT * FROM PART_FOR_ESCL_SCAD ORDER BY RAG_SOC,DATA_REG,N_REG