
-- VISTA ORDINATO_SINTETICO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ORDINATO_SINTETICO]'))
	DROP VIEW [dbo].[ORDINATO_SINTETICO]
GO

CREATE VIEW [dbo].[ORDINATO_SINTETICO]
AS

	SELECT
		SUBSTRING(TT.ORD_DATORD,1,4) AS ANNO,
		SUBSTRING(TT.ORD_DATORD,6,2) AS MESE,
		TT.ORD_NUMORD AS NUM_ORDINE,
		TT.ORD_CODCLI AS COD_CLIENTE,
		TT.ORD_RAGSOC AS RAG_SOCIALE,
		TT.ORD_INDIRI AS INDIRIZZO,
		TT.ORD_LOCALI AS LOCALITA,
		TT.ORD_CAP AS CAP,
		TT.ORD_PROVIN AS PROVINCIA,
		COALESCE(CNAZION.DESCRI,'') AS NAZIONE,
		T2.ORD_IDSDI AS ID_FATT_ELETTR_SDI,
		DD.ORD_CODART AS COD_ARTICOLO,
		DD.ORD_DESART AS DESCR_ARTICOLO,
		DD.ORD_QTAORD AS QTA_ORDINATA,
		DD.ORD_PREZZO AS PREZZO_UNITARIO,
		CASE WHEN DD.ORD_PUBBLI = '' THEN DD.ORD_PRZNET ELSE 0 END AS PREZZO_NETTO_UNITARIO,
		TT.ORD_VALUTA,
		CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET ELSE 0 END AS PREZZO_NETTO_UNITARIO_EURO,
		CASE WHEN DD.ORD_PUBBLI = '' THEN TT.ORD_CAMBIO*DD.ORD_PRZNET*DD.ORD_QTAORD ELSE 0 END AS IMPORTO_EURO,
		DD.ORD_SEQUEN AS NR_RIGA,
		TT.ORD_PARIVA AS P_IVA,
		CLI.CLI_EMAIL AS E_MAIL,
		CLI.CLI_APPPRO AS GRUPPO,
		COALESCE(CGRUPPO.DESCRI,'') AS DESCR_GRUPPO,
		TT.ORD_CIG AS CIG,
		DD.ORD_IVA AS COD_IVA
	FROM U_ORD_TT AS TT
	LEFT OUTER JOIN U_ORD_T2 AS T2 ON TT.TAGGANCIO = T2.TAGGANCIO
	LEFT OUTER JOIN U_ORD_DD AS DD ON DD.DAGGANCIO = TT.TAGGANCIO
	LEFT OUTER JOIN U_CLI_AN AS CLI ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS CNAZION ON CNAZION.CODICE = 'STA'+CLI.CLI_NAZION 
	LEFT OUTER JOIN PARA AS CGRUPPO ON CGRUPPO.CODICE = 'APP'+CLI.CLI_APPPRO 
	WHERE ORD_DESART <> '*** COMMENTO ***'

GO

SELECT * FROM ORDINATO_SINTETICO WHERE ANNO = '2025' ORDER BY ANNO,MESE,NUM_ORDINE,NR_RIGA