
/****** Object:  View [dbo].[FATTURATO_PER_CONTO_CONTABILE]    Script Date: 14/10/2020 10:32:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURATO_PER_CONTO_CONTABILE]'))
	DROP VIEW [dbo].[FATTURATO_PER_CONTO_CONTABILE]
GO
CREATE VIEW [dbo].[FATTURATO_PER_CONTO_CONTABILE]  
AS
	SELECT
		SUBSTRING(IND.MOV_DTDOC,1,4) AS Anno,
		SUBSTRING(IND.MOV_DTDOC,6,2) AS Mese,
		IND.MOV_DTDOC AS Data_documento,
		IND.MOV_NPROT AS Nr_Fattura,
		IND.MOV_NPROT AS Nr_Protocollo_IVA,
		IND.MOV_TOP AS Tipo_Operazione,
		IND.MOV_DTREG AS Data_Registrazione,
		COALESCE(TT.ORD_TIPOLOGIA,'') AS Tipo_ordine,
		COALESCE(PA_TPO.DESCRI,'') AS Descrizione_tipo_ordine,
		COALESCE(CVEN_1_3.DESCRI,'') AS Descrizione_Canale_di_vendita,
		COALESCE(CVEN_1_6.DESCRI,'') AS Descrizione_Macroclasse_Cliente,
		COALESCE(CVEN.DESCRI,'') AS Descrizione_Classe_Cliente,
		COALESCE(TT.ORD_CODCLI,'') AS Codice_Cliente,
		COALESCE(TT.ORD_RAGSOC,'') AS Ragione_Sociale,
		COALESCE(REGIONI.REGIONE,'') AS Regione,
		COALESCE(NAZIONI.DESCRI,'') AS Nazione,
		COALESCE(CZONA.DESCRI,'') AS Descrizione_Zona,
		COALESCE(CLI.CLI_PROVIN,'') AS Subzona,
		COALESCE(MOV.MOV_CONTO,'') AS Conto_contabile,
		COALESCE(CONTI.CON_DESCR,'') AS Descrizione_Conto_contabile,
		IND.MOV_VALUTA AS Valuta,
		CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE 0 END AS Importo_DARE,
		CASE MOV.MOV_TMOV WHEN 'A' THEN COALESCE(MOV.MOV_IMP,0) ELSE 0 END AS Importo_AVERE,
		COALESCE(MOV.MOV_IMPOST,0) AS Importo_Imposta,
		COALESCE(MOV.MOV_IVA,'') AS Codice_IVA,
		COALESCE(PA_IVA.DESCRI,'') AS Descrizione_Codice_IVA,
		COALESCE(MOV.MOV_CCO,'') AS Centro_di_costo,
		IND.MOV_CAMBIO AS Cambio,
		CASE MOV.MOV_TMOV WHEN 'D' THEN COALESCE(MOV.MOV_IMP,0) ELSE 0 END * IND.MOV_CAMBIO AS Importo_DARE_EUR,
		CASE MOV.MOV_TMOV WHEN 'A' THEN COALESCE(MOV.MOV_IMP,0) ELSE 0 END * IND.MOV_CAMBIO AS Importo_AVERE_EUR,
		COALESCE(MOV.MOV_IMPOST,0) * IND.MOV_CAMBIO AS Importo_Imposta_EUR
	FROM INDICE AS IND
	LEFT OUTER JOIN MOV_CONT AS MOV ON MOV.MOV_ANNO = IND.MOV_ANNO AND MOV.MOV_NUMPRO = IND.MOV_NUMPRO AND MOV.MOV_CONTO <> IND.MOV_CONTO
	LEFT OUTER JOIN CONTI ON CONTI.CON_ANNO = MOV.MOV_ANNO AND CONTI.CON_CONTO = MOV.MOV_CONTO
	LEFT OUTER JOIN U_FAT_TT AS TT ON TT.ORD_NUMORD = IND.MOV_NPROT AND TT.ORD_DATORD = IND.MOV_DTDOC AND TT.ORD_CODCLI = SUBSTRING(IND.MOV_CONTO,5,10)
	LEFT OUTER JOIN PARA AS PA_TPO ON PA_TPO.CODICE = 'TPO'+TT.ORD_TIPOLOGIA
	LEFT OUTER JOIN U_CLI_AN AS CLI	ON TT.ORD_CODCLI = CLI.CLI_CODCLI 
	LEFT OUTER JOIN PARA AS CVEN ON CVEN.CODICE = 'CVE'+CLI.CLI_CANVEN AND LEN(RTRIM(CVEN.CODICE)) = 3+9
	LEFT OUTER JOIN PARA AS CVEN_1_3 ON CVEN_1_3.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,3) AND LEN(RTRIM(CVEN_1_3.CODICE)) = 3+3
	LEFT OUTER JOIN PARA AS CVEN_1_6 ON CVEN_1_6.CODICE = 'CVE'+SUBSTRING(CLI.CLI_CANVEN,1,6) AND LEN(RTRIM(CVEN_1_6.CODICE)) = 3+6
	LEFT OUTER JOIN PARA AS CZONA ON CZONA.CODICE = 'ZON'+CLI.CLI_ZONA 
	LEFT OUTER JOIN PROVINCE ON PROVINCE.SIGLA = TT.ORD_PROVIN
	LEFT OUTER JOIN REGIONI ON REGIONI.CODICE = PROVINCE.REGIONE
	LEFT OUTER JOIN PARA AS NAZIONI ON NAZIONI.CODICE = 'STA'+CLI.CLI_NAZION
	LEFT OUTER JOIN PARA AS PA_IVA ON PA_IVA.CODICE = 'IVA'+MOV.MOV_IVA
	WHERE 
		IND.MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C') AND 
		CONTI.CON_TIPOCO <> 'I'
GO

SELECT * FROM FATTURATO_PER_CONTO_CONTABILE WHERE ANNO = 2020