-- VISTA ECONOMICI_PER_CENTRO_COSTO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ECONOMICI_PER_CENTRO_COSTO]'))
	DROP VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO]
GO

CREATE VIEW [dbo].[ECONOMICI_PER_CENTRO_COSTO]  
AS

SELECT 
	ECO.MOV_ANNO AS ANNO,
	ECO.MOV_CONTO AS CONTO,
	CONECO.CON_DESCR AS DESCR_CONTO,
	ECO.MOV_CCO AS CENTRO_COSTO,
	SUM(CASE WHEN MOV_TMOV='D' THEN ECO.MOV_IMP ELSE -1 * ECO.MOV_IMP END) AS IMPORTO
FROM MOV_CONT AS ECO
LEFT OUTER JOIN CONTI AS CONECO
ON ECO.MOV_CONTO=CONECO.CON_CONTO AND ECO.MOV_ANNO=CONECO.CON_ANNO
GROUP BY ECO.MOV_ANNO,ECO.MOV_CONTO,CONECO.CON_DESCR,ECO.MOV_CCO 


GO