SELECT * FROM INDICE WHERE MOV_ANNO = '2022' ORDER BY MOV_DTREG


SELECT MOV_NUMPRO AS MOV_NUMP,* FROM INDICE WHERE MOV_ANNO = '2022' AND MOV_DTREG = '2022/10/19'
SELECT MOV_NUMPRO AS MOV_NUMP,* FROM MOV_CONT WHERE MOV_ANNO = '2022' AND MOV_DTREG = '2022/10/19' ORDER BY MOV_NUMPRO,MOV_SEQUEN

