
SELECT CLI_RA,* FROM U_CLI_AN





SELECT T_RA,T_NETTO,T_NORA,T_NORAENPA,ORD_VALORE,* FROM U_FAT_TT WHERE ORD_ANNO = '2022' ORDER BY ORD_DATORD DESC




SELECT * FROM U_FAT_DD WHERE DAGGANCIO = '6000036134' ORDER BY ORD_SEQUEN

SELECT MOV_NUMPRO,* FROM INDICE WHERE MOV_ANNO = '2022' AND MOV_DTREG = '2022/10/31'
SELECT MOV_CONTO,MOV_IMP,MOV_TMOV,* FROM MOV_CONT WHERE MOV_NUMPRO = '_6GO0N043R   ' ORDER BY MOV_SEQUEN

SELECT * FROM PARA WHERE CODICE LIKE 'RIA004%'

SELECT COGERA,* FROM NEWPARA

SELECT * FROM U_FAT_TT ORDER BY TAGGANCIO DESC

SELECT CLI_CORDA,* FROM U_ANA_CL


select ORD_ANNO,* from u_fat_tt where ord_codsoc = '01' and ord_anno = '2022' and ord_numord = '000397' order by ord_datord,ord_numord


SELECT * FROM MOV_CONT WHERE MOV_TOP = '0011'

SELECT * FROM MOV_CONT WHERE MOV_CONTO = '1.3.1.349'


SELECT FOR_CONPAG,* FROM U_FOR_AN

SELECT * FROM COND_PAGAMENTO

SELECT * FROM GILDatiBase