exec sp_who2 'sviluppo'

SELECT TOP 1 OPERATORE,DESCRI, OPERAZIONE, PID FROM LOG_USER WHERE SPID = '55' ORDER BY DATA DESC, ORA DESC

SELECT * FROM LOG_USER ORDER BY DATA DESC, ORA  DESC



SELECT COUNT(*) AS CONTA_COMMENTI_UGUALI FROM LOG_USER


SELECT TOP 1 OPERATORE,DESCRI, OPERAZIONE, PID FROM LOG_USER WHERE SPID = '53' ORDER BY DATA DESC, ORA DESC
SELECT TOP 1 OPERATORE,DESCRI, OPERAZIONE, PID FROM LOG_USER WHERE SPID = '55' ORDER BY DATA DESC, ORA DESC

SELECT * FROM LOG_USER  ORDER BY DATA DESC, ORA DESC

SELECT OPERATORE AS OPE,DESCRI, OPERAZIONE, PID, DATA FROM LOG_USER  WHERE OPERATORE = 'SER' AND DATA = '2023/05/22' ORDER BY DATA DESC, ORA DESC



SELECT * FROM LOG_USER

SELECT OPERATORE, DESCRI, OPERAZIONE, PID 
FROM LOG_USER
WHERE DATA = '2023/05/23'
AND OPERATORE = 'SER'
AND OPERAZIONE = 'Annunciato'
ORDER BY DATA DESC, ORA DESC


	SELECT OPERATORE, DESCRI, OPERAZIONE, PID 
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERATORE = '.F.'
	AND OPERAZIONE = 'Annunciato'
	ORDER BY DATA DESC, ORA DESC



	SELECT OPERATORE, DESCRI, OPERAZIONE, PID 
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERATORE = 'ERCOLI'   
	ORDER BY DATA DESC, ORA DESC

	SELECT OPERATORE, DESCRI, OPERAZIONE, PID 
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERATORE = 'ANTONIAZZI'   
	ORDER BY DATA DESC, ORA DESC


	SELECT OPERATORE, DATA, PID ,OPERAZIONE
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERAZIONE = 'Annunciato'  
	AND OPERATORE = 'ERCOLI'   
 	GROUP BY OPERATORE, DATA, PID, OPERAZIONE
  	ORDER BY OPERATORE, DATA, PID, OPERAZIONE 

		SELECT OPERATORE, DATA, PID ,OPERAZIONE
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERAZIONE = 'Congedato'  
	AND OPERATORE = 'ERCOLI'   
 	GROUP BY OPERATORE, DATA, PID, OPERAZIONE
  	ORDER BY OPERATORE, DATA, PID, OPERAZIONE 

	exec sp_who2 'sviluppo'

	SELECT OPERATORE, OPERAZIONE, PID, SPID 
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERATORE = 'SER'
	AND OPERAZIONE = 'Annunciato'
 	GROUP BY OPERATORE, DATA, PID, SPID, OPERAZIONE
  	ORDER BY OPERATORE, DATA, PID, SPID, OPERAZIONE 

	SELECT OPERATORE, OPERAZIONE, PID, SPID
	FROM LOG_USER
	WHERE DATA = '2023/05/23'
	AND OPERATORE = 'SER'
	AND OPERAZIONE = 'Congedato'
 	GROUP BY OPERATORE, DATA, PID, SPID, OPERAZIONE
  	ORDER BY OPERATORE, DATA, PID, SPID, OPERAZIONE 


	exec sp_who2 'sviluppo'

	SELECT TOP 1 * FROM LOG_USER WHERE O3 ORDER BY DATA+ORA DESC
	--DELETE LOG_USER



	SELECT * FROM LOG_USER ORDER BY DATA+ORA DESC