
if exists(select * from sys.columns where name = 'ORD_ORELAV' and object_id = object_id(N'[dbo].[VENDITE_DT]'))
BEGIN
	--ALTER TABLE VENDITE_DT DROP CONSTRAINT DF_VENDITE_DT_ORD_ORELAV_PREFIX
	ALTER TABLE VENDITE_DT DROP COLUMN ORD_ORELAV
END

if exists(select * from sys.columns where name = 'ORD_ORAPARSEDE' and object_id = object_id(N'[dbo].[VENDITE_DT]'))
BEGIN
	ALTER TABLE VENDITE_DT DROP CONSTRAINT DF_VENDITE_DT_ORD_ORAPARSEDE
	ALTER TABLE VENDITE_DT DROP COLUMN ORD_ORAPARSEDE
END

ALTER TABLE [DBO].[VENDITE_DT] ADD 
	ORD_ORELAV [Numeric](5,2)   NULL, 
	ORD_ORAPARSEDE varchar (8) COLLATE Latin1_General_CI_AS not NULL CONSTRAINT [DF_VENDITE_DT_ORD_ORAPARSEDE] DEFAULT ('')
GO