SELECT * FROM PART_FOR WHERE PAR_ANNO = '2023' AND PAR_CODCLI = '3.1.1.149' ORDER BY PAR_NUMPRO,PAR_NPROG

SELECT * FROM PART_FOR WHERE PAR_ANNO = '2023' AND PAR_RAGSOC = 'STUDIO LEGALE ARGENTO' ORDER BY PAR_NUMPRO,PAR_NPROG


SELECT * FROM CONTI WHERE CON_ANNO = '2023' ORDER BY CON_CONTO


	
	SELECT 
		PART.* ,
		COALESCE(CPA.DESCRI,'')  AS DESCPA ,
		CASE WHEN COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'') IN ('S','F','A') THEN 'FAT' ELSE 'PAG' END AS FLAG_NATURA,
		COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'') AS FLAG_NOTAC_TOP ,
		CASE WHEN PAR_NPART IN (SELECT DISTINCT PAR_NPART
									FROM PART_FOR AS PART 
									LEFT OUTER JOIN PARA AS PARTOP
									ON 'TOP'+PART.PAR_TIPFAT = PARTOP.CODICE
									WHERE PAR_CODSOC='01'
										AND PAR_CODCLI='3.1.1.149'
										--AND PAR_DTREG BETWEEN '2023/04/01' AND '2023/04/30' 
										AND PAR_NPART IN (SELECT PAR_NPART FROM PART_FOR WHERE PAR_CODSOC='01' AND PAR_DTREG BETWEEN '2023/04/01' AND '2023/04/30') 
										AND PAR_NPROG<>100 
										AND COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'') IN ('S','F','A') AND COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'') <> 'S') THEN 'OK'
			
			WHEN PAR_NPART IN (SELECT DISTINCT PAR_NPART FROM
								(SELECT PAR_NPART, COUNT(*) AS CONTA_RIGHE_PARTITA FROM PART_FOR AS PART 
									WHERE PAR_CODSOC='01' AND PAR_CODCLI='3.1.1.149'
										AND PAR_NPART IN (SELECT PAR_NPART FROM PART_FOR WHERE PAR_CODSOC='01' AND PAR_DTREG BETWEEN '2023/04/01' AND '2023/04/30') 
										AND PAR_NPROG<>100 GROUP BY PAR_NPART) AS TMP_PART WHERE CONTA_RIGHE_PARTITA >= 2) THEN 'OK'
			
			ELSE 'KO'
		END AS LEGATA,
		COALESCE((SELECT TOP 1 MOV_DESMOV FROM MOV_CONT WHERE MOV_NUMPRO = PART.PAR_NUMPRO AND MOV_CONTO = PART.PAR_CODCLI),'') AS MOV_DESMOV,
		COALESCE((SELECT TOP 1 MOV_NPROT FROM MOV_CONT WHERE MOV_NUMPRO = PART.PAR_NUMPRO AND MOV_CONTO = PART.PAR_CODCLI),'') AS MOV_NPROT
	FROM PART_FOR AS PART 
	LEFT OUTER JOIN PARA AS CPA
		ON 'CPA'+PART.PAR_CODPAG = CPA.CODICE 
	LEFT OUTER JOIN PARA AS PARTOP
		ON 'TOP'+PART.PAR_TIPFAT = PARTOP.CODICE
	WHERE PAR_CODSOC = '01' and PAR_NPROG <> 100 and PAR_CODCLI = '3.1.1.149' and PAR_NPART IN (SELECT PAR_NPART FROM PART_FOR WHERE PAR_CODSOC='01' AND PAR_DTREG BETWEEN '2023/04/01' AND '2023/04/30')
	ORDER BY LEGATA DESC, PAR_NPART DESC,FLAG_NATURA ,PAR_NUMFAT DESC,PAR_DTFAT DESC, PAR_DTREG DESC


