
SELECT CINDINS,CNOTE,* FROM IMPIANTI_TT ORDER BY CCODSCHE
SELECT CDITTACAL,* FROM IMPIANTI_DD ORDER BY CCODSCHE,TIPO_COMPONENTE
SELECT CCODLIS,* FROM IMPIANTI_TE ORDER BY CCODSCHE,TIPO_COMPONENTE



SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA.BIANCHI' ORDER BY CCODSCHE
SELECT * FROM IMPIANTI_DD  WHERE CCODSCHE = 'AGNA.BIANCHI'ORDER BY CCODSCHE,TIPO_COMPONENTE
SELECT CCODLIS,* FROM IMPIANTI_TE  WHERE CCODSCHE = 'AGNA.BIANCHI' ORDER BY CCODSCHE,TIPO_COMPONENTE

SELECT * FROM IMPIANTI_TT WHERE  ID_PMKEY = '7502' ORDER BY CCODSCHE
SELECT * FROM IMPIANTI_DD  WHERE ID_PMKEY = '7502' ORDER BY CCODSCHE,TIPO_COMPONENTE
SELECT CCODLIS,* FROM IMPIANTI_TE  WHERE ID_PMKEY = '7502' ORDER BY CCODSCHE,TIPO_COMPONENTE

select * from IMPIANTI_DD where ID_PMKEY = '7502' order by TIPO_COMPONENTE,ID_PMKEY









  SELECT * FROM IMPIANTI_DD ORDER BY CCODSCHE,TIPO_COMPONENTE,ID_RIGO 

  SELECT TIPO_COMPONENTE AS TIPO_COMPONENTE_,ID_PMKEY,CCODSCHE AS CCODSCHE_,CDITTABRU,CMODBRU,CDITTACAL,CMODCAL,CMATCAL,* FROM IMPIANTI_DD WHERE CDITTABRU = '' OR CMODBRU = '' AND TIPO_COMPONENTE = '002' ORDER BY CCODSCHE,TIPO_COMPONENTE,ID_RIGO 

  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA.ARENA' ORDER BY CCODSCHE


  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA.C.EUROPA' ORDER BY CCODSCHE
  SELECT DT_ULT_MAN,CMODCAL,CMATCAL,CDITTACAL,CDITTABRU,CMODBRU,CMATBRU,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.C.EUROPA' ORDER BY TIPO_COMPONENTE,CCODSCHE
  SELECT * FROM IMPIANTI_TE WHERE CCODSCHE = 'AGNA.C.EUROPA' ORDER BY CCODSCHE

  UPDATE IMPIANTI_DD SET CMODCAL = 'HOVAL' WHERE ID_PMKEY = '7356' AND TIPO_COMPONENTE = '002'
  UPDATE IMPIANTI_DD SET CDITTACAL = 'HOVAL' WHERE ID_PMKEY = '7356' AND TIPO_COMPONENTE = '002'

  SELECT * FROM AQ_SCHEDE WHERE CCODSCHE = 'AGNA.C.EUROPA' ORDER BY CCODSCHE
  SELECT * FROM AQ_SCHEDEBRU WHERE CCODSCHE = 'AGNA.C.EUROPA' ORDER BY CCODSCHE


  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE
  SELECT CMODCAL,CMATCAL,CDITTACAL,CDITTABRU,CMODBRU,CMATBRU,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY TIPO_COMPONENTE,CCODSCHE
  SELECT * FROM IMPIANTI_TE WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE

  
  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AAAAAAAAAAA' ORDER BY CCODSCHE
  SELECT CMODCAL,CMATCAL,CDITTACAL,CDITTABRU,CMODBRU,CMATBRU,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AAAAAAAAAAA' ORDER BY TIPO_COMPONENTE,CCODSCHE
  SELECT * FROM IMPIANTI_TE WHERE CCODSCHE = 'AAAAAAAAAAA' ORDER BY CCODSCHE
  SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'AAAAAAAAAAA' ORDER BY CCODSCHE
 

 SELECT * FROM IMPIANTI_CO WHERE id_pmkey = '_6FS135DO0' ORDER BY id_pmkey
 select * from IMPIANTI_CO where id_pmkey = '_6FT036Y6E' and id_pmcontr = '1957'
 


  --UPDATE IMPIANTI_TT SET ID_PMKEY = '_6FS0VKONQ' WHERE CCODSCHE = 'AAAAAAAAAAA' 
  --UPDATE IMPIANTI_DD SET ID_PMKEY = '_6FS0VKONQ' WHERE CCODSCHE = 'AAAAAAAAAAA' 
  --UPDATE IMPIANTI_TE SET ID_PMKEY = '_6FS0VKONQ' WHERE CCODSCHE = 'AAAAAAAAAAA'
  --UPDATE IMPIANTI_TE SET ID_PMKEY = '_6FS15706M' WHERE CCODSCHE = 'AAAAAAAAAAA'
  --DELETE IMPIANTI_CO WHERE ID_UNIQUE = '834EC6AB-7BBD-40BA-B144-CDE7E50DCC5B' 

   SELECT * FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.BRUNO'
   SELECT * FROM IMPIANTI_CO WHERE  ID_PMCONTR = '      7800'     

   select CONTR.*,SCHE.CINIZCONTR,SCHE.CSCADCONTR,SCHE.DT_DISDETT from IMPIANTI_CO AS CONTR INNER JOIN IMPIANTI_DD AS SCHE ON SCHE.ID_PMKEY = CONTR.ID_PMKEY where CONTR.ID_PMKEY = '7940' order by ID_PMKEY

   select * from IMPIANTI_CO where ID_PMKEY = '7940' order by ID_PMKEY


   SELECT [CT Logical],* FROM IMPIANTI_TT
   --UPDATE IMPIANTI_TT SET [CT Logical] = 0



  SELECT * FROM AQ_SCHEDE WHERE CCODSCHE = 'AGNA.ARENA' ORDER BY CCODSCHE
  SELECT * FROM AQ_SCHEDEBRU WHERE ID_PMKEY = '7718' ORDER BY CCODSCHE

  
  SELECT TIPO_COMPONENTE AS TIPO_COMPONENTE_,ID_PMKEY,CCODSCHE AS CCODSCHE_,CDITTABRU,CMODBRU,CDITTACAL,CMODCAL,CMATCAL,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.ARENA' ORDER BY CCODSCHE,TIPO_COMPONENTE,ID_RIGO 
  

  SELECT * FROM AQ_SCHEDEBRU

  SELECT ID_PMKEY,CCODSCHE AS CCODSCHE_,CDITTABRU,CMODBRU,TIPO_BRU,POT_MIN,POT_MAX,POT_MIN_MC,POT_MAX_MC,POT_REAL_MC,POT_REAL_KG,POT_MIN_KW,POT_MAX_KW,* FROM AQ_SCHEDEBRU 
  WHERE (TIPO_BRU <> '' OR POT_MIN <> 0 OR POT_MAX <> 0 OR POT_MIN_MC <> 0 OR POT_MAX_MC <> 0 OR POT_REAL_MC <> 0 OR POT_REAL_KG <> 0 OR POT_MIN_KW <> 0 OR POT_MAX_KW <> 0)  ORDER BY CCODSCHE,ID_RIGO
  
  SELECT ID_PMKEY,CCODSCHE AS CCODSCHE_,CDITTABRU,CMODBRU,TIPO_BRU,POT_MIN,POT_MAX,POT_MIN_MC,POT_MAX_MC,POT_REAL_MC,POT_REAL_KG,POT_MIN_KW,POT_MAX_KW,* FROM AQ_SCHEDEBRU 
  WHERE (TIPO_BRU = '' OR POT_MIN = 0 OR POT_MAX = 0 OR POT_MIN_MC = 0 OR POT_MAX_MC = 0 OR POT_REAL_MC = 0 OR POT_REAL_KG = 0 OR POT_MIN_KW = 0 OR POT_MAX_KW = 0)  ORDER BY CCODSCHE,ID_RIGO
  
  

  SELECT * FROM IMPIANTI_DD WHERE TIPO_COMPONENTE = '002'   

  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'CREM.OGLIARI' 
  SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'CREM.OGLIARI' ORDER BY TIPO_COMPONENTE,ID_RIGO 


  
  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'TREV.POSSENTI       ' 
  SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'TREV.POSSENTI       ' ORDER BY TIPO_COMPONENTE,ID_RIGO 
         
   
  SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'ZANI.ALKAN          ' 
  SELECT ID_PMKEY,* FROM IMPIANTI_DD WHERE CCODSCHE = 'ZANI.ALKAN          ' ORDER BY TIPO_COMPONENTE,ID_RIGO 
 
  SELECT * FROM IMPIANTI_DD WHERE CCODSCHE = 'CERR.LANZA          ' ORDER BY TIPO_COMPONENTE,ID_RIGO        
  --UPDATE IMPIANTI_DD SET LINKINTE = 'XCWCECCEWD' WHERE CCODSCHE = 'CERR.LANZA          '                     

SELECT CZONAINS,CINDINS,CLOCINS,CRAGSOC,* FROM IMPIANTI_TT

SELECT SELEZI,DT_ULT_MAN,CMODBRU,* FROM IMPIANTI_DD

SELECT * FROM VENDITE_TT WHERE TAGGANCIO = '1000000095'
SELECT * FROM IMPIANTI_DD WHERE LINKINTE =  '1000000095'

SELECT ORD_INTCLOSE,* FROM VENDITE_DT

DELETE VENDITE_TT WHERE TAGGANCIO = '1000000093'
DELETE VENDITE_DD WHERE DAGGANCIO = '1000000093'
DELETE VENDITE_DT WHERE DAGGANCIO = '1000000093'	   
  SELECT ID_RIGO,* FROM IMPIANTI_TT WHERE CCODSCHE = 'ZANI.ALKAN' 



SELECT * FROM VENDITE_TT ORDER BY TAGGANCIO DESC
SELECT * FROM VENDITE_TT WHERE TAGGANCIO = '1000000092'   
SELECT ORD_DETT_INT,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000092'
SELECT ORDD_DTINIINT,ORD_INTCLOSE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000092'	

  
SELECT * FROM VENDITE_TT WHERE TAGGANCIO = '1000000094'   
SELECT ORD_DETT_INT,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000094'
SELECT ORD_INTCLOSE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000094'
UPDATE VENDITE_DD SET ORD_DETT_INT = 1 WHERE DAGGANCIO = '1000000094'
	
                                                                                    
            
			
			
SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA' order by CCODSCHE

SELECT * FROM IMPIANTI_TT WHERE CCODSCHE like 'AGNA%' order by CCODSCHE
                                                                           
																		   
																		   
																		   
																		   
select * from IMPIANTI_RI  order by ric_codice
select * from IMPIANTI_RI where 1=1 order by ric_codice

SELECT * FROM note_com

select  substring(ric_note,1,200) as ric_note_r,dbo.ribalta2(ric_data) as ric_data_r,* from IMPIANTI_RI order by ric_codice        


SELECT CNOTE,* FROM IMPIANTI_TT WHERE CCODSCHE = 'AGNA.BRUNO' order by CCODSCHE
SELECT STATO_CONTATTO,* FROM IMPIANTI_DD WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY TIPO_COMPONENTE,ID_RIGO      
--UPDATE IMPIANTI_DD SET STATO_CONTATTO  = '' WHERE ID_UNIQUE = '5170FF53-E420-4037-89A3-D8573925583F'                
  
  
SELECT CSCADCONTR,* FROM IMPIANTI_CO WHERE CCODSCHE = 'AGNA.BRUNO' ORDER BY CCODSCHE
DELETE IMPIANTI_CO WHERE ID_UNIQUE = 'CCC16EC8-2B2E-4D56-A889-040CE9A35ADA'
DELETE IMPIANTI_CO WHERE ID_UNIQUE = 'AA402DA7-DBEC-43A6-BC50-0E22DF085597'
DELETE IMPIANTI_CO WHERE ID_UNIQUE = '0688B604-DBD1-459A-96DB-843BCAE8806A'
                                                   	   

SELECT LINKINTE,STATO_CONTATTO,* FROM IMPIANTI_DD WHERE LINKINTE <> '' ORDER BY TIPO_COMPONENTE,ID_RIGO    

SELECT CNOTE,* FROM IMPIANTI_DD WHERE CCODSCHE = 'CARA.MACCHI' order by CCODSCHE

SELECT CNOTE,CINDINS,* FROM IMPIANTI_TT WHERE CCODSCHE = 'CARA.MACCHI' order by CCODSCHE