

SELECT ORD_TIPOLOGIA,ORD_NUMORD,ORD_DATORD,* FROM VENDITE_TT ORDER BY TAGGANCIO DESC
SELECT ORD_DETT_INT,ORS_DATORD,ORS_DATORC,MOV_DATORD,* FROM VENDITE_DD ORDER BY DAGGANCIO DESC
SELECT * FROM VENDITE_DT ORDER BY DAGGANCIO DESC

SELECT ORD_CHIUSO,* FROM U_OFF_TT ORDER BY ORD_NUMORD DESC


SELECT ORD_NOTE_INTERVENTI,ORD_ORAINIINT,ORD_ORAFININT,ORD_TIPOLOGIA,ORD_NUMORD,ORD_DATORD,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000234' ORDER BY TAGGANCIO DESC
SELECT ORD_NOTE_INTERVENTI,ORD_ORAINIINT,ORD_ORAFININT,ORD_TIPOLOGIA,ORD_NUMORD,ORD_DATORD,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000235' ORDER BY TAGGANCIO DESC

SELECT ORD_DETT_INT,ORD_CODART,ORD_UM,ORD_IVA,ORD_DESART,ORD_DES2,ORD_QTAORD,ORD_CODMAT,ORD_DESMAT ,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000234' ORDER BY ORD_SEQUEN
SELECT ORD_DETT_INT,ORD_CODART,ORD_UM,ORD_IVA,ORD_DESART,ORD_DES2,ORD_QTAORD,ORD_CODMAT,ORD_DESMAT ,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000235' ORDER BY ORD_SEQUEN

SELECT ORD_PREZZO,ORD_PRZNET,ORD_VALATT,ORD_VALINC,ORD_VALPRE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000234' ORDER BY DAGGANCIO DESC
SELECT ORD_PREZZO,ORD_PRZNET,ORD_VALATT,ORD_VALINC,ORD_VALPRE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000235' ORDER BY DAGGANCIO DESC


SELECT ORD_NUMORD,ORD_DATORD,TIPRENDO,ORD_RIFERI,ORD_TIPOLOGIA,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000234' ORDER BY TAGGANCIO DESC
SELECT ORD_DETT_INT,ORD_CODART,ORD_UM,ORD_IVA,ORD_DESART,ORD_DES2,ORD_QTAORD,ORD_CODMAT,ORD_DESMAT ,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000234' ORDER BY DAGGANCIO DESC
SELECT ORD_NUMORD,ORD_DATORD,ORD_PREZZO,ORD_PRZNET,ORD_VALATT,ORD_VALINC,ORD_VALPRE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000234' ORDER BY DAGGANCIO DESC

SELECT ORD_NUMORD,ORD_DATORD,TIPRENDO,ORD_RIFERI,ORD_TIPOLOGIA,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000235' ORDER BY TAGGANCIO DESC
SELECT ORD_DETT_INT,ORD_CODART,ORD_UM,ORD_IVA,ORD_DESART,ORD_DES2,ORD_QTAORD,ORD_CODMAT,ORD_DESMAT ,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000235' ORDER BY DAGGANCIO DESC
SELECT ORD_NUMORD,ORD_DATORD,ORD_PREZZO,ORD_PRZNET,ORD_VALATT,ORD_VALINC,ORD_VALPRE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000235' ORDER BY DAGGANCIO DESC





--UPDATE VENDITE_TT SET ORD_CCODLIS = 0
--UPDATE VENDITE_TT SET ORD_CCODLIS = -25 WHERE TAGGANCIO = '1000000108'

UPDATE VENDITE_DD SET ORD_DETT_INT = 0 WHERE ID_UNIQUE = '768064ED-3908-494B-B1DE-4CA70F08C5C9'
UPDATE VENDITE_DD SET ORD_DETT_INT = 0 WHERE ID_UNIQUE = '0578DE03-F83B-4A58-9637-9201160FC0EB'

UPDATE VENDITE_DT SET ORD_PREZZO = 0, ORD_PRZNET = 0, ORD_VALATT = 0, ORD_VALPRE = 0 WHERE ID_UNIQUE = '692F0B68-D1E4-4231-945C-6523AEB1D481'


SELECT ORD_CHIUSO,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000184'
SELECT * FROM VENDITE_DD WHERE DAGGANCIO = '1000000184'
DELETE FROM VENDITE_TT WHERE TAGGANCIO = '1000000222'
DELETE FROM VENDITE_DD WHERE DAGGANCIO = '1000000222'
DELETE FROM VENDITE_DT WHERE DAGGANCIO = '1000000222'

SELECT TIPRENDO,* FROM U_OFF_TT ORDER BY TAGGANCIO DESC
SELECT * FROM U_OFF_TT WHERE TAGGANCIO = '6000009673'
SELECT ORD_NOTE, * FROM U_OFF_DD WHERE DAGGANCIO = '6000009673' ORDER BY ORD_SEQUEN


SELECT ORD_RIFERI,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000208'
SELECT ORD_CODSYS,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000208'