SELECT * FROM VENDITE_TT
	
SELECT * FROM VENDITE_DT ORDER BY DAGGANCIO DESC


SELECT CCODCLI,* FROM IMPIANTI_TT
SELECT LINKINTE,DT_ULT_MAN,* FROM IMPIANTI_DD

SELECT LINKINTE,* FROM IMPIANTI_DD WHERE LINKINTE = '_6H0137Z06'


SELECT ORD_TIPOLOGIA,ORD_VALORE,* FROM VENDITE_TT ORDER BY TAGGANCIO DESC
SELECT * FROM VENDITE_DT ORDER BY DAGGANCIO DESC
SELECT * FROM VENDITE_DD ORDER BY DAGGANCIO DESC


SELECT ORD_TIPOLOGIA,ORD_VALORE,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000159'
SELECT ORD_ORELAV,ORD_PRZNET,ORD_VALATT,ORD_VALPRE,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000159'
SELECT ORD_NOTE,ORD_DETT_INT,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000159'
	
SELECT LINKINTE,* FROM IMPIANTI_DD WHERE LINKINTE = '_6H0137Z06'
select * from IMPIANTI_DD where id_pmkey = '_6H0137Z06'

SELECT LINKINTE,ORD_CHIUSO,* FROM VENDITE_TT WHERE LINKINTE = '_6H0138CVY'

UPDATE VENDITE_TT SET LINKINTE = '_6H0137Z06',TIPO_MANU_PROGR = '001'  WHERE TAGGANCIO = '1000000159'


UPDATE VENDITE_DD SET ORD_PREZZO = 0,ORD_QTAORD = 0, ORD_PRZNET = 0,ORD_VALORE = 0   WHERE ID_UNIQUE = '2C1A6B7B-C417-46D2-A552-73B788B1203C'
UPDATE VENDITE_DD SET ORD_PREZZO = 0,ORD_QTAORD = 0, ORD_PRZNET = 0,ORD_VALORE = 0   WHERE ID_UNIQUE = '0831B9D4-3240-4874-B224-9EADE5BE4A60'




--UPDATE VENDITE_DD SET ORD_DETT_INT = 1 WHERE DAGGANCIO = '1000000145'	


select VENDITE_TT.*, coalesce(para_top.libera,SPACE(2)) as libera, coalesce(para_age.descri,'') as desage from VENDITE_TT left outer join para as para_top on para_top.codice = 'TOP'+ord_caus left outer join para as para_age on para_age.codice = 'AGE'+ord_age where ord_codsoc = '01' and ord_datord >= '2022/11/01' and ord_datord <= '2022/11/30'order by SUBSTRING(para_top.libera,61,1), ord_anno, ord_numord



SELECT * FROM VENDITE_DD WHERE DAGGANCIO = '1000000152' order by ord_sequen
select * from VENDITE_DD where daggancio = '1000000152' order by ord_sequen
		
		
		
SELECT * FROM IMPIANTI_TT WHERE CCODSCHE = 'TREZS.LE VELE'
SELECT LINKINTE,DT_ULT_MAN,DT_ULT_MAN_ORD,FL_DT_MAN_ORD,* FROM IMPIANTI_DD WHERE CCODSCHE = 'TREZS.LE VELE' ORDER BY CCODSCHE

SELECT * FROM IMPIANTI_TE


UPDATE VENDITE_DD SET ORD_DETT_INT = 1 WHERE ID_UNIQUE = '86475EFE-2122-4485-828E-5792ED6ECB60'
--UPDATE IMPIANTI_DD SET DT_ULT_MAN = '2021/04/30' WHERE ID_UNIQUE = 'D19E2677-DD0E-41AC-A25F-52981FE80641'
--UPDATE IMPIANTI_DD SET DT_ULT_MAN_ORD = '2021/05/25' WHERE ID_UNIQUE = '068FB4A0-99B1-4D69-B2CC-6F6BC8306D9F'


SELECT DT_ULT_MAN,DT_ULT_MAN_ORD,FL_DT_MAN_ORD,* FROM IMPIANTI_DD ORDER BY CCODSCHE

SELECT LINKINTE,DT_ULT_MAN,DT_ULT_MAN_ORD,FL_DT_MAN_ORD,* FROM IMPIANTI_DD WHERE FL_DT_MAN_ORD  <> '' ORDER BY CCODSCHE
				
		
		
SELECT LINKINTE,ORD_CHIUSO,ORD_INTCLOSE,* FROM VENDITE_TT WHERE LINKINTE = '_6H0137Z06'

--UPDATE VENDITE_TT SET ORD_INTCLOSE = 0 WHERE LINKINTE = '_6JB0T5HGA'



SELECT * FROM IMPIANTI_LG

--DELETE IMPIANTI_LG WHERE LOG_CODLIS = ''



SELECT LINKINTE,ORD_CHIUSO,ORD_INTCLOSE,* FROM VENDITE_TT ORDER BY TAGGANCIO DESC

SELECT LINKINTE,ORD_CHIUSO,ORD_INTCLOSE,* FROM VENDITE_TT WHERE TAGGANCIO = '1000000272'
SELECT ORD_SEQUE as sequen,ORD_ATTIVITA,* FROM VENDITE_DT WHERE DAGGANCIO = '1000000272' ORDER BY ORD_SEQUE
SELECT ORD_SEQUEN as sequen,ORD_DETT_INT,* FROM VENDITE_DD WHERE DAGGANCIO = '1000000272' ORDER BY ORD_SEQUEN

SELECT LINKINTE,ORD_CHIUSO,ORD_INTCLOSE,* FROM VENDITE_TT WHERE LINKINTE = '_6JB0T5HGA'