
SELECT * FROM ANAGRAFE

SELECT * FROM [DATI FISCALI]

SELECT * FROM [DATI MAGAZZINO]

SELECT * FROM CONTRO_PARTITE

SELECT * FROM COND_PAGAMENTO

SELECT * FROM BANCHE




SELECT * FROM ANAGRAFE WHERE Codice = '000007'




SELECT * FROM PianoConti WHERE TITOLO LIKE '#%' 


SELECT * FROM TestateGiornale ORDER BY Esercizio, IDregistrazione

SELECT * FROM MovimentiGiornale

SELECT * FROM MovimentiGiornale where CodiceANA = '000007'
SELECT * FROM MovimentiGiornale order by CodicePC

SELECT * FROM MovimentiGiornale where CodiceANA = '000007'

SELECT * FROM MOV_CONT

SELECT * FROM CONTI WHERE CON_CONTO = '1.3.1.7'

SELECT * FROM PART_CLI
SELECT * FROM PART_FOR