SELECT MOV_ANNO,MOV_NDOC,MOV_DTDOC,MOV_IMPOST FROM MOV_CONT WHERE MOV_IMPOST < 0  

SELECT MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN,MOV_NREGIS,MOV_DTREG,MOV_NPROT,MOV_NDOC,MOV_DTDOC,MOV_CONTO,MOV_TOP,MOV_IMPOST FROM MOV_CONT WHERE  MOV_IMPOST < 0  ORDER BY MOV_NUMPRO,MOV_SEQUEN 

SELECT MOV_ANNO,MOV_NUMPRO,MOV_SEQUEN,MOV_NREGIS,MOV_DTREG,MOV_NPROT,MOV_NDOC,MOV_DTDOC,MOV_CONTO,MOV_TOP,MOV_IMPOST FROM MOV_CONT WHERE MOV_NPROT = '2731' ORDER BY MOV_NUMPRO,MOV_SEQUEN 