
	SELECT 'VENDITE' AS TIPO, YTOD.*,OGGI.* FROM (SELECT 
		COALESCE(SUM(PAR_TOTIM*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPO_DA_INIZIO_ANNO,
		COALESCE(SUM(PAR_TIMPOS*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPOS_DA_INIZIO_ANNO
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_TOTIM AS PAR_TOTIM,
		PA.PAR_TIMPOS AS PAR_TIMPOS,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA, 
		COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'')  AS FLAG_NOTACRED 
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG = '100'
		AND PA.PAR_DTREG BETWEEN '2013/06/01'  AND  '2013/06/30' ) AS T1
	WHERE FLAG_NATURA = 'S' ) AS YTOD
	LEFT OUTER JOIN (SELECT 
		COALESCE(SUM(PAR_TOTIM*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPO_OGGI,
		COALESCE(SUM(PAR_TIMPOS*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPOS_OGGI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_TOTIM AS PAR_TOTIM,
		PA.PAR_TIMPOS AS PAR_TIMPOS,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA, 
		COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'')  AS FLAG_NOTACRED 
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG = '100'
		AND PA.PAR_DTREG ='2013/06/25' ) AS T2
	WHERE FLAG_NATURA = 'S' ) AS OGGI
	ON 1=1
	UNION
	SELECT 'ACQUISTI' AS TIPO, YTOD.*,OGGI.* FROM (SELECT 
		COALESCE(SUM(PAR_TOTIM*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPO_DA_INIZIO_ANNO,
		COALESCE(SUM(PAR_TIMPOS*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPOS_DA_INIZIO_ANNO
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_TOTIM AS PAR_TOTIM,
		PA.PAR_TIMPOS AS PAR_TIMPOS,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA, 
		COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'')  AS FLAG_NOTACRED 
	FROM PART_FOR AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG = '100'
		AND PA.PAR_DTREG BETWEEN '2013/06/01' AND '2013/06/30' ) AS T1
	WHERE FLAG_NATURA = 'S' ) AS YTOD
	LEFT OUTER JOIN (SELECT 
		COALESCE(SUM(PAR_TOTIM*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPO_OGGI,
		COALESCE(SUM(PAR_TIMPOS*(CASE WHEN FLAG_NOTACRED='S' THEN -1 ELSE 1 END)),0) AS IMPOS_OGGI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_TOTIM AS PAR_TOTIM,
		PA.PAR_TIMPOS AS PAR_TIMPOS,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA, 
		COALESCE(SUBSTRING(PARTOP.LIBERA,11,1),'')  AS FLAG_NOTACRED 
	FROM PART_FOR AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG = '100'
		AND PA.PAR_DTREG ='2013/06/30' ) AS T2
	WHERE FLAG_NATURA = 'S' ) AS OGGI
	ON 1=1


