
DECLARE @VECCHIO_CODICE_IVA_21_PERCENTO VARCHAR(6)
SET @VECCHIO_CODICE_IVA_21_PERCENTO = 'IVA021'
DECLARE @DATA_FINE_VALIDITA_VECCHIO_CODICE VARCHAR(10)
SET @DATA_FINE_VALIDITA_VECCHIO_CODICE = '2013/09/30'

DECLARE @NUOVO_CODICE_IVA_22_PERCENTO VARCHAR(6)
SET @NUOVO_CODICE_IVA_22_PERCENTO = 'IVA022'
DECLARE @DATA_INIZIO_VALIDITA_NUOVO_CODICE VARCHAR(10)
SET @DATA_INIZIO_VALIDITA_NUOVO_CODICE = '2013/10/01'

--################################################################################################################################
-- INSERIMENTO NUOVO CODICE IVA
DELETE FROM PARA WHERE CODICE = @NUOVO_CODICE_IVA_22_PERCENTO

INSERT INTO PARA (CODICE, DESCRI, LIBERA)
	SELECT
		@NUOVO_CODICE_IVA_22_PERCENTO AS CODICE,
		'IVA 22%' AS DESCRI,
		'022' + COALESCE((SELECT SUBSTRING(LIBERA,4,200) FROM PARA WHERE CODICE = @VECCHIO_CODICE_IVA_21_PERCENTO),'') AS LIBERA


--################################################################################################################################
-- AGGIORNAMENTO IVA DI DEFAULT IN PARAMETRI AZIENDALI
UPDATE U_AZI_AN SET AZI_IVA = SUBSTRING(@NUOVO_CODICE_IVA_22_PERCENTO,4,3)


--################################################################################################################################
-- AGGIORNAMENTO TABELLA IVADEFAULT
DELETE FROM IVADEFAULT WHERE CODIVA = SUBSTRING(@NUOVO_CODICE_IVA_22_PERCENTO,4,3)

INSERT INTO IVADEFAULT (CODIVA, DESIVA, ALIQUOTA, DATADA, DATAAL)
	SELECT 
		SUBSTRING(@NUOVO_CODICE_IVA_22_PERCENTO,4,3) AS CODIVA,
		COALESCE(RTRIM(DESCRI),'') AS DESIVA,
		COALESCE(SUBSTRING(LIBERA,1,3),'') AS ALIQUOTA,
		@DATA_INIZIO_VALIDITA_NUOVO_CODICE AS DATADA,
		'2999/12/31' AS DATAAL
	FROM PARA
	WHERE CODICE = @NUOVO_CODICE_IVA_22_PERCENTO

UPDATE IVADEFAULT SET DATAAL = @DATA_FINE_VALIDITA_VECCHIO_CODICE WHERE CODIVA = SUBSTRING(@VECCHIO_CODICE_IVA_21_PERCENTO,4,3)


--################################################################################################################################
-- VISUALIZZAZIONE RISULTATI
SELECT AZI_IVA,* FROM U_AZI_AN
SELECT * FROM PARA WHERE CODICE = @NUOVO_CODICE_IVA_22_PERCENTO
SELECT * FROM IVADEFAULT ORDER BY DATADA DESC