/* Dichiaro le variabili */
DECLARE @PUB_CODSOC AS VARCHAR(2)
DECLARE @_V_DATA_DAL AS VARCHAR(10)
DECLARE @_V_DATA_AL AS VARCHAR(10)
DECLARE @_V_FATTURE_CLI_FOR AS VARCHAR(1)

/* Inizializzo le variabili */
SET @PUB_CODSOC ='01'
SET @_V_DATA_DAL ='2014/01/01'
SET @_V_DATA_AL ='2014/12/31'
SET @_V_FATTURE_CLI_FOR ='F'

	SELECT 
		FORN.FOR_CODCLI AS CODFOR,
		FORN.FOR_RAGSOC AS RAGSOC,
		FORN.FOR_ESTNAZ AS NAZIONE_COD_UNICO,
		FORN.FOR_INDIR AS INDIRIZZO_ESTERO,
		FORN.for_LOCALI AS LOCALITA_ESTERA,
		FORN.for_codfis AS CODICE_FISCALE,
		FORN.for_ivacee AS PIVA_ESTERA,
		MOV_CONT.id_unique,			
		MOV_SOC,
		MOV_ANNO,
		MOV_CONTO,
		CONTI.CON_TIPOCO,
		CONTI.CON_DESCR,
		MOV_NREGIS, 
		MOV_DTREG,
		MOV_NDOC, 
		MOV_DTDOC,
	    MOV_TOP,
		SUBSTRING(PARA1.LIBERA,12,1) AS TOP_CLI_FOR,
		MOV_IMP,
		MOV_TMOV,
		MOV_VALUTA,
		MOV_CAMBIO,
		MOV_IVA,
		MOV_MODPAG,
		SUBSTRING(PARA3.LIBERA,1,100) AS CPA_MOD_PAG,
		MOV_NUMPRO,	
		MOV_CONTABILITA_PREVISIONALE
	FROM MOV_CONT 
	LEFT OUTER JOIN U_FOR_AN AS FORN
	ON MOV_CONTO=(SELECT RTRIM(LTRIM(SUBSTRING( LIBERA, CHARINDEX ( 'GRUPPO CLI' ,LIBERA )+LEN('GRUPPO CLI'),CHARINDEX ( 'GRUPPO FOR' ,LIBERA )-(CHARINDEX ( 'GRUPPO CLI' ,LIBERA )+LEN('GRUPPO CLI'))))) AS GRUPPO_FOR  FROM PARA WHERE CODICE ='GENEX')+FORN.FOR_CODCLI
	LEFT OUTER JOIN PARA AS PARA1
	ON 'TOP'+MOV_CONT.MOV_TOP = PARA1.CODICE
	LEFT OUTER JOIN PARA AS PARA2
	ON 'IVA'+MOV_CONT.MOV_IVA = PARA2.CODICE
	LEFT OUTER JOIN PARA AS PARA3
	ON 'CPA'+MOV_CONT.MOV_MODPAG = PARA3.CODICE
	LEFT OUTER JOIN CONTI AS CONTI
	ON MOV_CONTO=CONTI.CON_CONTO 
	WHERE MOV_SOC=@PUB_CODSOC
	AND MOV_DTREG BETWEEN @_V_DATA_DAL AND @_V_DATA_AL
	AND MOV_TOP <> 'CHI' 
	AND MOV_CONTABILITA_PREVISIONALE<>'P'
	AND SUBSTRING(PARA1.LIBERA,12,1)=@_V_FATTURE_CLI_FOR
	AND SUBSTRING(PARA1.LIBERA,2,1)='S'
	AND CONTI.CON_TIPOCO='F'
	AND CONTI.CON_ANNO=MOV_ANNO
	AND MOV_CONTO LIKE (SELECT RTRIM(LTRIM(SUBSTRING( LIBERA, CHARINDEX ( 'GRUPPO CLI' ,LIBERA )+LEN('GRUPPO CLI'),CHARINDEX ( 'GRUPPO FOR' ,LIBERA )-(CHARINDEX ( 'GRUPPO CLI' ,LIBERA )+LEN('GRUPPO CLI'))))) AS GRUPPO_FOR  FROM PARA WHERE CODICE ='GENEX')+'%'
	AND FORN.FOR_ESTNAZ IN (SELECT CODICE FROM NAZIONI_UNICO WHERE  BLACK='X') 
	ORDER BY MOV_CONTO,MOV_DTREG
