--SELECT * FROM CONTI WHERE CON_ANNO = '2017' ORDER BY CON_CONTO

DELETE FROM CONTI  WHERE CON_ANNO = '2017' 
DELETE FROM CCOSTO  WHERE CON_ANNO = '2017' 

--SELECT * FROM PARA WHERE CODICE LIKE '%NUMBOL%' ORDER BY CODICE

DELETE FROM PARA WHERE CODICE LIKE '%NUMFAT2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFVS2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFEL2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFAD2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMNCR2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFAP2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMOFF2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMORD2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMORF2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMBOL2017%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMBOE2017%' 

DELETE FROM PARA WHERE LIBERA LIKE '%APERTO   2017           EUR%' 


