SELECT * FROM VISTA_SCADENZE where CLI_FOR='C' AND PAR_TMOV='D' AND FLAG_FAT_PAG=0 

SELECT * FROM 


--- CASH IN - CLIENTI FATTURATO
SELECT 
	ANNO,
	MESE,
	SUM(IMPORTO) AS IMPORTO
FROM VISTA_SCADENZE
WHERE 
	PAR_CODCLI NOT LIKE '0701%'
	AND CLI_FOR='C'
	AND PAR_TMOV='D'
	AND ANNO='2014'
GROUP BY ANNO,MESE
ORDER BY ANNO,MESE

--- CASH IN - CLIENTI SCADERE INCASSATO
SELECT 
	ANNO,
	MESE,
	SUM(IMPORTO) AS IMPORTO
FROM VISTA_SCADENZE
WHERE 
	CLI_FOR='C'
	AND FLAG_FAT_PAG=0 
	AND PAR_TMOV='A'
	AND ((FLAG_RIBA=1 AND FLAG_SCADUTO=1) OR (FLAG_RIBA=0))
	AND ANNO='2014'
GROUP BY ANNO,MESE
ORDER BY ANNO,MESE


--- CASH IN - CLIENTI A SCADERE INCASSATO
SELECT 
	ANNO,
	MESE,
	SUM(IMPORTO) AS IMPORTO
FROM VISTA_SCADENZE
WHERE 
	CLI_FOR='C'
	AND FLAG_FAT_PAG=0 
	AND PAR_TMOV='A'
	AND ((FLAG_RIBA=1 AND FLAG_SCADUTO=1) OR (FLAG_RIBA=0))
	AND ANNO='2014'
GROUP BY ANNO,MESE
ORDER BY ANNO,MESE



SELECT * FROM U_ORD_DD

