
/*** ORDINI CLIENTI ***/
SELECT * FROM (
	SELECT
		COUNT(*) AS QUANTI_ORDINI_PR, 
		COALESCE(SUM(ORD_VALORE),0) AS OC_PR_VALOR ,
		COALESCE(SUM(ORD_QTANR),0) AS OC_PR_QTANR,
		COALESCE(SUM(ORD_QTAKG),0) AS OC_PR_QTAKG,
		COALESCE(SUM(ORD_QTAMC),0) AS OC_PR_QTAMC,
		COALESCE(SUM(ORD_QTAMQ),0) AS OC_PR_QTAMQ,
		COALESCE(SUM(ORD_QTAML),0) AS OC_PR_QTAML 
	FROM(
		SELECT
			TT.ORD_NUMORD,
			TT.ORD_DATORD,
			TT.TAGGANCIO,
			SUM(DD.ORD_VALORE) AS ORD_VALORE,
			SUM(CASE ORD_UM
					WHEN 'NR' THEN DD.ORD_QTAORD
					ELSE DD.ORD_NUMBOB
				END) AS ORD_QTANR,
			SUM(DD.ORD_QTAKG) AS ORD_QTAKG,
			SUM(DD.ORD_QTAMC) AS ORD_QTAMC,
			SUM(DD.ORD_QTAMQ) AS ORD_QTAMQ,
			SUM(DD.ORD_QTAML) AS ORD_QTAML 
		FROM U_ORD_TT AS TT
		LEFT OUTER JOIN U_ORD_DD AS DD
		ON TT.TAGGANCIO=DD.DAGGANCIO AND DD.ORD_CODART <>'' AND DD.ORD_DESART<>'*** COMMENTO ***'
		WHERE ORD_DATORD >= '2013/01/01' AND  ORD_DATORD <= '2013/06/21'
		GROUP BY TT.ORD_NUMORD, TT.ORD_DATORD, TT.TAGGANCIO) AS T1
	) AS Q1
	CROSS JOIN (
	SELECT
		COUNT(*) AS QUANTI_ORDINI_GG, 
		COALESCE(SUM(ORD_VALORE),0) AS OC_GG_VALOR ,
		COALESCE(SUM(ORD_QTANR),0) AS OC_GG_QTANR,
		COALESCE(SUM(ORD_QTAKG),0) AS OC_GG_QTAKG,
		COALESCE(SUM(ORD_QTAMC),0) AS OC_GG_QTAMC,
		COALESCE(SUM(ORD_QTAMQ),0) AS OC_GG_QTAMQ,
		COALESCE(SUM(ORD_QTAML),0) AS OC_GG_QTAML 
	FROM(
		SELECT
			TT.ORD_NUMORD,
			TT.ORD_DATORD,
			TT.TAGGANCIO,
			SUM(DD.ORD_VALORE) AS ORD_VALORE,
			SUM(CASE ORD_UM
					WHEN 'NR' THEN DD.ORD_QTAORD
					ELSE DD.ORD_NUMBOB
				END) AS ORD_QTANR,
			SUM(DD.ORD_QTAKG) AS ORD_QTAKG,
			SUM(DD.ORD_QTAMC) AS ORD_QTAMC,
			SUM(DD.ORD_QTAMQ) AS ORD_QTAMQ,
			SUM(DD.ORD_QTAML) AS ORD_QTAML 
		FROM U_ORD_TT AS TT
		LEFT OUTER JOIN U_ORD_DD AS DD
		ON TT.TAGGANCIO=DD.DAGGANCIO AND DD.ORD_CODART <>'' AND DD.ORD_DESART<>'*** COMMENTO ***'
		WHERE TT.ORD_DATORD = '2013/06/21'
		GROUP BY TT.ORD_NUMORD, TT.ORD_DATORD, TT.TAGGANCIO) AS T2
	) AS Q2


/*** PRODUZIONE ***/
SELECT 
	SUBSTRING(PARA_MAIN.LIBERA,1,1) AS PROGRESS_FASE_LAVORAZ,
	SUBSTRING(PARA_MAIN.CODICE,4,6) AS FASE_LAVORAZ,
	PARA_MAIN.DESCRI AS DESCR_FASE_LAVORAZ,
	COALESCE(TOT_AVANZAMENTI_PROD_PR,0) AS  TOT_AVANZAMENTI_PROD_PR,
	COALESCE(PROD_PR_QTANR,0) AS PROD_PR_QTANR,
	COALESCE(PROD_PR_QTAKG,0) AS PROD_PR_QTAKG,
	COALESCE(PROD_PR_QTAMC,0) AS PROD_PR_QTAMC,
	COALESCE(PROD_PR_QTAMQ,0) AS PROD_PR_QTAMQ,
	COALESCE(PROD_PR_QTAML,0) AS PROD_PR_QTAML,
	COALESCE(TOT_AVANZAMENTI_PROD_GG,0) AS  TOT_AVANZAMENTI_PROD_GG,
	COALESCE(PROD_GG_QTANR,0) AS PROD_GG_QTANR,
	COALESCE(PROD_GG_QTAKG,0) AS PROD_GG_QTAKG,
	COALESCE(PROD_GG_QTAMC,0) AS PROD_GG_QTAMC,
	COALESCE(PROD_GG_QTAMQ,0) AS PROD_GG_QTAMQ,
	COALESCE(PROD_GG_QTAML,0) AS PROD_GG_QTAML 
FROM PARA AS PARA_MAIN
LEFT OUTER JOIN (
	SELECT * FROM (
		SELECT 
			PROGR_LAV AS PROGRESS_FASE_LAVORAZ,
			FASELA AS FASE_LAVORAZ,
			DESFASELA AS DESCR_FASE_LAVORAZ,
			COUNT(*) AS TOT_AVANZAMENTI_PROD_PR, 
			COALESCE(SUM(QTANRPROD),0) AS PROD_PR_QTANR,
			COALESCE(SUM(QTAKGPROD),0) AS PROD_PR_QTAKG,
			COALESCE(SUM(QTAMCPROD),0) AS PROD_PR_QTAMC,
			COALESCE(SUM(QTAMQPROD),0) AS PROD_PR_QTAMQ,
			COALESCE(SUM(QTAMLPROD),0) AS PROD_PR_QTAML 
		FROM (
			SELECT 
				PC.DATAVA AS GIORNO, 
				SUBSTRING(PC.DATAVA,1,7) AS MESE, 
				SUBSTRING(PC.DATAVA,1,4) AS ANNO, 
				SUBSTRING(PARA1.LIBERA,1,2) AS PROGR_LAV, 
				PC.FASELA, 
				PARA1.DESCRI AS DESFASELA, 
				PC.CODART, 
				PR.ART_DESCR AS DESART, 
				CASE PR.ART_GRUPRD WHEN '' THEN COALESCE(SUBSTRING(PARA2.CODICE,4,16),SUBSTRING(PARA3.CODICE,4,16),'') ELSE PR.ART_GRUPRD END AS GRUPRD, 
				PR.ART_LINEA AS LINEA, 
				COALESCE(PARA4.DESCRI,'') AS DESLINEA, 
				PR.ART_UMMAGA AS UM, 
				COALESCE(PARA5.DESCRI,'') AS DESUM, 
				PC.QTAPROD, 
				CASE PC.UM
					WHEN 'NR' THEN PC.QTAPROD
					ELSE PC.QTANRPROD
				END AS QTANRPROD,
				PC.QTAMCPROD, 
				PC.QTAMQPROD, 
				PC.QTAMLPROD, 
				PC.QTAKGPROD 
				FROM ( 
					SELECT 
						FASELA,	
						CODART, 
						UM, 
						DATAVA, 
						SUM(QTAPROD) AS QTAPROD, 
						SUM(QTANRPROD) AS QTANRPROD, 
						SUM(QTAMCPROD) AS QTAMCPROD, 
						SUM(QTAMQPROD) AS QTAMQPROD, 
						SUM(QTAMLPROD) AS QTAMLPROD, 
						SUM(QTAKGPROD) AS QTAKGPROD
					FROM PROD_CARICHI 
					WHERE DATAVA between '2013/01/01' AND '2013/06/21' and IDPRG <> '' 
					GROUP BY 
						FASELA, 
						CODART, 
						UM, 
						DATAVA
					) AS PC
			LEFT OUTER JOIN PARA AS PARA1 ON PARA1.CODICE = 'FAL'+PC.FASELA
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = PC.CODART 
			LEFT OUTER JOIN U_ART_AN AS AN ON PR.ART_CODPRI = AN.ART_CODPRI 
			LEFT OUTER JOIN PARA AS PARA2 ON SUBSTRING(PARA2.CODICE,1,3) = 'PRD' AND PARA2.LIBERA = AN.ART_TIPOG AND PARA2.DESIVA = CAST(PR.ART_SPESSO AS VARCHAR(5))
			LEFT OUTER JOIN PARA AS PARA3 ON SUBSTRING(PARA3.CODICE,1,3) = 'PRD' AND PARA3.LIBERA = AN.ART_TIPON AND PARA3.DESIVA = CAST(PR.ART_SPESSO AS VARCHAR(5))
			LEFT OUTER JOIN PARA AS PARA4 ON PARA4.CODICE = 'REP'+PR.ART_LINEA 
			LEFT OUTER JOIN PARA AS PARA5 ON PARA5.CODICE = 'UMI'+PR.ART_UMMAGA 
			) AS TABELLA1
			GROUP BY PROGR_LAV, FASELA, DESFASELA
		) AS TQ1
	) AS Q1
ON Q1.PROGRESS_FASE_LAVORAZ = SUBSTRING(PARA_MAIN.LIBERA,1,1) AND Q1.FASE_LAVORAZ = SUBSTRING(PARA_MAIN.CODICE,4,6)

LEFT OUTER JOIN (
	SELECT * FROM (
		SELECT 
			PROGR_LAV AS PROGRESS_FASE_LAVORAZ,
			FASELA AS FASE_LAVORAZ,
			DESFASELA AS DESCR_FASE_LAVORAZ,
			COUNT(*) AS TOT_AVANZAMENTI_PROD_GG, 
			COALESCE(SUM(QTANRPROD),0) AS PROD_GG_QTANR,
			COALESCE(SUM(QTAKGPROD),0) AS PROD_GG_QTAKG,
			COALESCE(SUM(QTAMCPROD),0) AS PROD_GG_QTAMC,
			COALESCE(SUM(QTAMQPROD),0) AS PROD_GG_QTAMQ,
			COALESCE(SUM(QTAMLPROD),0) AS PROD_GG_QTAML 
		FROM (
			SELECT 
				PC.DATAVA AS GIORNO, 
				SUBSTRING(PC.DATAVA,1,7) AS MESE, 
				SUBSTRING(PC.DATAVA,1,4) AS ANNO, 
				SUBSTRING(PARA1.LIBERA,1,2) AS PROGR_LAV, 
				PC.FASELA, 
				PARA1.DESCRI AS DESFASELA, 
				PC.CODART, 
				PR.ART_DESCR AS DESART, 
				CASE PR.ART_GRUPRD WHEN '' THEN COALESCE(SUBSTRING(PARA2.CODICE,4,16),SUBSTRING(PARA3.CODICE,4,16),'') ELSE PR.ART_GRUPRD END AS GRUPRD, 
				PR.ART_LINEA AS LINEA, 
				COALESCE(PARA4.DESCRI,'') AS DESLINEA, 
				PR.ART_UMMAGA AS UM, 
				COALESCE(PARA5.DESCRI,'') AS DESUM, 
				PC.QTAPROD, 
				CASE PC.UM
					WHEN 'NR' THEN PC.QTAPROD
					ELSE PC.QTANRPROD
				END AS QTANRPROD,
				PC.QTAMCPROD, 
				PC.QTAMQPROD, 
				PC.QTAMLPROD, 
				PC.QTAKGPROD 
				FROM ( 
					SELECT 
						FASELA,	
						CODART, 
						UM, 
						DATAVA, 
						SUM(QTAPROD) AS QTAPROD, 
						SUM(QTANRPROD) AS QTANRPROD, 
						SUM(QTAMCPROD) AS QTAMCPROD, 
						SUM(QTAMQPROD) AS QTAMQPROD, 
						SUM(QTAMLPROD) AS QTAMLPROD, 
						SUM(QTAKGPROD) AS QTAKGPROD
					FROM PROD_CARICHI 
					WHERE DATAVA = '2013/06/21' and IDPRG <> '' 
					GROUP BY 
						FASELA, 
						CODART, 
						UM, 
						DATAVA
					) AS PC
			LEFT OUTER JOIN PARA AS PARA1 ON PARA1.CODICE = 'FAL'+PC.FASELA
			LEFT OUTER JOIN U_ART_PR AS PR ON PR.ART_CODPRI = PC.CODART 
			LEFT OUTER JOIN U_ART_AN AS AN ON PR.ART_CODPRI = AN.ART_CODPRI 
			LEFT OUTER JOIN PARA AS PARA2 ON SUBSTRING(PARA2.CODICE,1,3) = 'PRD' AND PARA2.LIBERA = AN.ART_TIPOG AND PARA2.DESIVA = CAST(PR.ART_SPESSO AS VARCHAR(5))
			LEFT OUTER JOIN PARA AS PARA3 ON SUBSTRING(PARA3.CODICE,1,3) = 'PRD' AND PARA3.LIBERA = AN.ART_TIPON AND PARA3.DESIVA = CAST(PR.ART_SPESSO AS VARCHAR(5))
			LEFT OUTER JOIN PARA AS PARA4 ON PARA4.CODICE = 'REP'+PR.ART_LINEA 
			LEFT OUTER JOIN PARA AS PARA5 ON PARA5.CODICE = 'UMI'+PR.ART_UMMAGA 
			) AS TABELLA2
			GROUP BY PROGR_LAV, FASELA, DESFASELA
		) AS TQ2
	) AS Q2
ON Q2.PROGRESS_FASE_LAVORAZ = SUBSTRING(PARA_MAIN.LIBERA,1,1) AND Q2.FASE_LAVORAZ = SUBSTRING(PARA_MAIN.CODICE,4,6)

WHERE 
	PARA_MAIN.CODICE LIKE 'FAL%' AND
	SUBSTRING(PARA_MAIN.LIBERA,1,1) <> ''
ORDER BY 
	PROGRESS_FASE_LAVORAZ






