
-- ALLARGAMENTO CAMPO CODICE OPERATORE A 20 CARATTERI
ALTER TABLE [dbo].[L_BOL_TT    ] ALTER COLUMN REG_CODOPE VARCHAR(20) COLLATE Latin1_General_CI_AS NULL

-- ALLARGAMENTO CAMPO DESCRIZIONE OPERATORE A 50 CARATTERI
ALTER TABLE [dbo].[RES_OPER] ALTER COLUMN DESCRI     VARCHAR(50) COLLATE Latin1_General_CI_AS NULL


