SELECT LIVELLO_MENU,* FROM TBL_MENU ORDER BY  MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='clienti'    ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='fornitori'  ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='consulenza' ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='magazzino'  ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='produzione' ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='contabilit' ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='statistich' ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='gestioneparametri' ORDER BY  LIVELLO_MENU,ORDINE
SELECT * FROM TBL_MENU WHERE MENU='opzioni'    ORDER BY  LIVELLO_MENU,ORDINE





SELECT * FROM TBL_MENU WHERE  comando like '%.NAM.%' ORDER BY MENU,ORDINE

SELECT * FROM TBL_MENU WHERE utenti like '%.SER.%' ORDER BY MENU,ORDINE

SELECT LIVELLO_MENU,* FROM TBL_MENU WHERE LIVELLO_MENU=0 ORDER BY  MENU,ORDINE

SELECT * FROM TBL_MENU WHERE MENU=?_NomeMenu and utenti like '%.SER.%'ORDER BY ORDINE 

SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='gestioneclienti' and utenti like '%.SER.%'ORDER BY ORDINE 
SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='gestionefornitori' and utenti like '%.SER.%'ORDER BY ORDINE 
SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='gestionetrasporti' and utenti like '%.SER.%'ORDER BY ORDINE 




SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='gestionecontatti' and utenti like '%.SER.%'ORDER BY ORDINE 
SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='gestionecontatti1' and utenti like '%.SER.%'ORDER BY ORDINE 
SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE LABEL='Gestione fidelizzazione clienti' and utenti like '%.SER.%'ORDER BY ORDINE 


SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='GESTIONELISTINI' ORDER BY ORDINE
SELECT LIVELLO_MENU, * FROM TBL_MENU WHERE MENU='GESTIONELISTINI9' ORDER BY ORDINE
                  