
select * from SCHEDULER  
delete scheduler

insert into SCHEDULER (	CODICE,
			ID_FUNZIONE,
			FUNZIONE,
			DESCRI,
			PROGRAMMA,
			PERIDAL,
			PERIAL,
			STATO,
			GO_EMAIL,
			LU_TIME1,
			LU_TIME2,
			LU_TIME3,
			LU_TIME4)
		values ('0000000010',
			'_SYS123456',
			'TEST PROGRAMMA BATCH',
			'PRIMA PROVA PER GESTIRE UN PROGRAMMA CHE CREA UNA EMAIL',
			'PROGRAMMA-00010',
			'2013/01/01',
			'2013/12/31',
			'ATTIVO',
			'SI',
			'11:11:11',
			'',
			'',
			'')

insert into SCHEDULER (	CODICE,
			ID_FUNZIONE,
			FUNZIONE,
			DESCRI,
			PROGRAMMA,
			PERIDAL,
			PERIAL,
			STATO,
			GO_EMAIL,
			LU_TIME1,
			LU_TIME2,
			LU_TIME3,
			LU_TIME4)
		values ('0000000020',
			'_SYS000000',
			'TEST PROGRAMMA BATCH',
			'PRIMA PROVA PER GESTIRE UN PROGRAMMA CHE CREA UNA EMAIL',
			'PROGRAMMA-00020',
			'2013/01/01',
			'2013/12/31',
			'ATTIVO',
			'SI',
			'11:11:11',
			'',
			'',
			'')


insert into SCHEDULER (	CODICE,
			ID_FUNZIONE,
			FUNZIONE,
			DESCRI,
			PROGRAMMA,
			PERIDAL,
			PERIAL,
			STATO,
			GO_EMAIL,
			VE_TIME1,
			VE_TIME2,
			VE_TIME3,
			VE_TIME4)
		values ('0000000030',
			'_SYS000001',
			'TEST PROGRAMMA BATCH',
			'PRIMA PROVA PER GESTIRE UN PROGRAMMA CHE CREA UNA EMAIL',
			'PROGRAMMA-00030',
			'2013/01/01',
			'2013/12/31',
			'ATTIVO',
			'SI',
			'16:00:01',
			'',
			'',
			'')