
SELECT TIPRENDO,ORD_NUMORD AS NUMORD,* FROM U_ORD_TT WHERE ORD_ANNO = '2014' ORDER BY ORD_NUMORD DESC 

SELECT TIPRENDO,ORD_NUMORD AS NUMORD,* FROM U_BOL_TT WHERE ORD_ANNO = '2014' ORDER BY ORD_NUMORD DESC 

SELECT TIPRENDO,ORD_NUMORD AS NUMORD,ORD_RAGSOC,* FROM U_FAT_TT WHERE ORD_ANNO = '2014' ORDER BY ORD_NUMORD DESC 

SELECT * FROM SCADENZE ORDER BY TIPRENDO DESC

SELECT * FROM U_BOL_DD WHERE DAGGANCIO = '3007007173'

