/* SOMMA IL VALORE DELLE RIGHE DEGLI ORDINI A FORNITORE IN ESENZIONE IVA NEL PERIODO INDICATO RAGRUPPANDO PER CODICE FORNITORE */	
	
	SELECT 
	    ORS_CODCLI,
		SUM(ORD_VALORE) 
	FROM U_FAT_DD 
	LEFT OUTER JOIN PARA AS PARA
	ON 'IVA'+U_FAT_DD.ORD_IVA = PARA.CODICE
	WHERE 
		ORS_CODCLI = '10001800' AND
		ORS_DATORD BETWEEN '2014/01/01' AND '2014/12/31'
		AND PARA.ivaesente = 1
    GROUP BY ORS_CODCLI
	ORDER BY ORS_CODCLI


/* SOMMA IL VALORE DELLE RIGHE DEGLI ORDINI A FORNITORE IN ESENZIONE IVA NEL PERIODO INDICATO RAGRUPPANDO PER CODICE FORNITORE+IVA*/	
	

	SELECT 
	    ORS_CODCLI,
		ORD_IVA,
		SUM(ORD_VALORE) AS ORD_VALORE
	FROM U_FAT_DD 
	LEFT OUTER JOIN PARA AS PARA
	ON 'IVA'+U_FAT_DD.ORD_IVA = PARA.CODICE
	WHERE 
		ORS_CODCLI = '10001800' AND
        ORD_IVA = 'S10' AND
		ORS_DATORD BETWEEN '2014/01/01' AND '2014/12/31'
		AND PARA.ivaesente = 1 
	GROUP BY ORS_CODCLI,ORD_IVA
	ORDER BY ORS_CODCLI,ORD_IVA
