--SELECT * FROM CONTI WHERE CON_ANNO = '2017' ORDER BY CON_CONTO

DELETE FROM CONTI  WHERE CON_ANNO = '2018' 
DELETE FROM CCOSTO  WHERE CON_ANNO = '2018' 

--SELECT * FROM PARA WHERE CODICE LIKE '%NUMBOL%' ORDER BY CODICE

DELETE FROM PARA WHERE CODICE LIKE '%NUMFAT2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFVS2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFEL2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFAD2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMNCR2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMFAP2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMOFF2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMORD2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMORF2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMBOL2018%' 
DELETE FROM PARA WHERE CODICE LIKE '%NUMBOE2018%' 

DELETE FROM PARA WHERE LIBERA LIKE '%APERTO   2018           EUR%' 


