SELECT ord_ccosto,ORD_CONCON,* FROM U_FAT_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_FAT_DD ORDER BY DAGGANCIO DESC

SELECT ord_ccosto,ORD_CONCON,* FROM U_BOL_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_BOL_DD ORDER BY DAGGANCIO DESC

SELECT ord_ccosto,ORD_CONCON,* FROM U_FAT_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_FAT_DD ORDER BY DAGGANCIO DESC

SELECT ord_ccosto,ORD_CONCON,* FROM U_FAP_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_FAP_DD ORDER BY DAGGANCIO DESC


SELECT ord_ccosto,ORD_CONCON,* FROM U_ORF_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_ORF_DD ORDER BY DAGGANCIO DESC

SELECT ord_ccosto,ORD_CONCON,* FROM U_BFO_TT ORDER BY TAGGANCIO DESC
SELECT ord_ccodet,ORD_CONDET,* FROM U_BFO_DD ORDER BY DAGGANCIO DESC