SELECT	DISTINCT IVA.IVA_CODCLI,
		IVA.IVA_RAGSOC,
		COALESCE(CLI.CLI_ESTDOM,'') AS NAZIONE
FROM U_IVA_CL AS IVA
LEFT OUTER JOIN U_CLI_AN AS CLI
ON  IVA.IVA_CODCLI=CLI.CLI_CODCLI
LEFT OUTER JOIN NAZIONI_UNICO AS NAZ
ON CLI.CLI_ESTDOM = NAZ.CODICE
WHERE COALESCE(NAZ.BLACK,'')=''
ORDER BY IVA_RAGSOC

SELECT	DISTINCT IVA.IVF_CODCLI,
		IVA.IVF_RAGSOC,
		COALESCE(FFF.FOR_ESTDOM,'') AS NAZIONE
FROM U_IVF_CL AS IVA
LEFT OUTER JOIN U_FOR_AN AS FFF
ON  IVA.IVF_CODCLI=FFF.FOR_CODCLI
LEFT OUTER JOIN NAZIONI_UNICO AS NAZ
ON FFF.FOR_ESTDOM = NAZ.CODICE
WHERE COALESCE(NAZ.BLACK,'')=''
ORDER BY IVF_RAGSOC


	SELECT DISTINCT SUBSTRING(CODICE,4,3) AS CODICE, DESCRI AS DESCRI
	FROM PARA 
	WHERE CODICE LIKE 'IVA%' 
	ORDER BY CODICE 

SELECT * FROM NAZIONI_UNICO


SELECT SUBSTRING(LIBERA,110,1) FROM PARA 

UPDATE PARA SET LIBERA=SUBSTRING(LIBERA,1,109)+'S'+SUBSTRING(LIBERA,111,LEN(LIBERA)) WHERE CODICE LIKE 'IVA%'


	SELECT DISTINCT SUBSTRING(CODICE,4,3) AS CODICE, DESCRI AS DESCRI, SUBSTRING(LIBERA,110,1) AS SELEZIONE
	FROM PARA 
	WHERE CODICE LIKE 'IVA%' 
	ORDER BY CODICE 
		


		SELECT IVA_CODIVA FROM U_IVA_CL WHERE IVA_ANNO='2012'




	SELECT * FROM U_IVA_CL WHERE IVA_ANNO='2012' order by iva_chiave

	select top 1  from mov_cont  