DELETE FROM U_IVA_FE WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'
--SELECT * FROM U_IVA_FE WHERE IVA_ANNO='2016' AND IVA_CODFOR='0000015'


INSERT INTO U_IVA_FE
(IVA_CODSOC,IVA_ANNO,IVA_CODFOR,IVA_DESFOR,IVA_PLAFOND) 
SELECT FOR_CODSOC,'2016',FOR_CODCLI,FOR_RAGSOC,for_IMPINT 
FROM U_FOR_AN 
WHERE  for_IMPINT<>0
--AND FOR_CODCLI='0000015'


UPDATE U_IVA_FE 
SET IVA_GENNAI = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='01' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016' 
--AND IVA_CODFOR='0000015'



UPDATE U_IVA_FE 
SET IVA_FEBBRA = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='02' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'


UPDATE U_IVA_FE 
SET IVA_MARZO = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='03' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'


UPDATE U_IVA_FE 
SET IVA_APRILE = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='04' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'


UPDATE U_IVA_FE 
SET IVA_MAGGIO = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='05' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_GIUGNO = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='06' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_LUGLIO = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='07' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_AGOSTO = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='08' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_SETTEM = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='09' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_OTTOBR = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='10' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_NOVEMB = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='11' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'

UPDATE U_IVA_FE 
SET IVA_DICEMB = COALESCE((SELECT SUM(IVF_IMPONI * (CASE WHEN  IVF_FATNOT='N' THEN -1 ELSE 1 END))
FROM U_IVF_CL 
WHERE IVF_CODIVA='34' AND IVF_MESE='12' AND IVF_ANNO='2016' AND IVF_CODCLI=IVA_CODFOR
GROUP BY IVF_CODCLI,IVF_RAGSOC,IVF_CODIVA,IVF_MESE,IVF_ANNO),0)
WHERE IVA_ANNO='2016'
--AND IVA_CODFOR='0000015'


UPDATE U_IVA_FE SET 
IVA_01RESI=IVA_PLAFOND-IVA_GENNAI

UPDATE U_IVA_FE SET 
IVA_02RESI=IVA_01RESI-IVA_FEBBRA

UPDATE U_IVA_FE SET 
IVA_03RESI=IVA_02RESI-IVA_MARZO

UPDATE U_IVA_FE SET 
IVA_04RESI=IVA_03RESI-IVA_APRILE

UPDATE U_IVA_FE SET 
IVA_05RESI=IVA_04RESI-IVA_MAGGIO

UPDATE U_IVA_FE SET 
IVA_06RESI=IVA_05RESI-IVA_GIUGNO

UPDATE U_IVA_FE SET 
IVA_07RESI=IVA_06RESI-IVA_LUGLIO

UPDATE U_IVA_FE SET 
IVA_08RESI=IVA_07RESI-IVA_AGOSTO

UPDATE U_IVA_FE SET 
IVA_09RESI=IVA_08RESI-IVA_SETTEM

UPDATE U_IVA_FE SET 
IVA_10RESI=IVA_09RESI-IVA_OTTOBR

UPDATE U_IVA_FE SET 
IVA_11RESI=IVA_10RESI-IVA_NOVEMB

UPDATE U_IVA_FE SET 
IVA_12RESI=IVA_11RESI-IVA_DICEMB

