
	SELECT 'RICEVUTE' AS TIPO, YTOD.*,OGGI.* FROM (SELECT 
		COALESCE(SUM(PAR_FATT),0) AS RICEVUTE_INSOLUTI_PROGRESSIVI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_FATT AS PAR_FATT,
		COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG <> '100'
		AND PA.PAR_DTREG BETWEEN '2012/01/01'  AND  '2013/06/30' ) AS T1
	WHERE FLAG_RIBA = 'S' ) AS YTOD
	LEFT OUTER JOIN (SELECT 
		COALESCE(SUM(PAR_FATT),0) AS RICEVUTE_INSOLUTI_OGGI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_FATT AS PAR_FATT,
		COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA 
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG <> '100'
		AND PA.PAR_DTREG ='2013/06/30' ) AS T2
	WHERE FLAG_RIBA = 'S' ) AS OGGI
	ON 1=1
	UNION
	SELECT 'INSOLUTI' AS TIPO, YTOD.*,OGGI.* FROM (SELECT 
		COALESCE(SUM(PAR_FATT),0) AS RICEVUTE_INSOLUTI_PROGRESSIVI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_FATT AS PAR_FATT,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG <> '100'
		AND PA.PAR_DTREG BETWEEN '2012/01/01' AND '2013/06/30' ) AS T1
	WHERE FLAG_NATURA = 'I' ) AS YTOD
	LEFT OUTER JOIN (SELECT 
		COALESCE(SUM(PAR_FATT),0) AS RICEVUTE_INSOLUTI_OGGI
	FROM ( SELECT 
		PA.PAR_TIPFAT,
		PA.PAR_FATT AS PAR_FATT,
		COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA
	FROM PART_CLI AS PA
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
	WHERE PA.PAR_NPROG <> '100'
		AND PA.PAR_DTREG ='2013/06/30' ) AS T2
	WHERE FLAG_NATURA = 'I' ) AS OGGI
	ON 1=1


