
SELECT COUNT(*) AS CONTA FROM U_MAG_MO

SELECT COUNT(*) AS CONTA FROM U_MAG_MO WHERE MOV_LEGAME+MOV_CODMAG+MOV_ANAART IN (
select MOV_LEGAME+MOV_CODMAG+MOV_ANAART from (
	SELECT MOV_LEGAME, MOV_CODMAG, MOV_ANAART, SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1 * MOV_QTAMOV END) AS SALDO FROM U_MAG_MO
	--WHERE MOV_CODMAG = 'MPF' AND MOV_DTREGI <= '2015/01/31'
	WHERE MOV_DTREGI <= '2015/01/31'
	GROUP BY MOV_LEGAME, MOV_CODMAG, MOV_ANAART
	) as main
WHERE SALDO = 0)
--ORDER BY MOV_CODMAG,MOV_ANAART

SELECT COUNT(*) AS CONTA FROM U_MAG_MO WHERE MOV_CODMAG+MOV_ANAART IN (
select MOV_CODMAG+MOV_ANAART from (
	SELECT MOV_CODMAG, MOV_ANAART, SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1 * MOV_QTAMOV END) AS SALDO FROM U_MAG_MO
	GROUP BY MOV_CODMAG, MOV_ANAART
	) as main
WHERE SALDO = 0)
ORDER BY MOV_CODMAG,MOV_ANAART

-- RECORD DA ANNULLARE 


select MOV_LEGAME,MOV_CODMAG,MOV_ANAART from (
	SELECT MOV_LEGAME, MOV_CODMAG, MOV_ANAART, SUM(CASE WHEN MOV_SEGNO = '+' THEN MOV_QTAMOV ELSE -1 * MOV_QTAMOV END) AS SALDO FROM U_MAG_MO
	--WHERE MOV_CODMAG = 'MPF' AND MOV_DTREGI <= '2015/01/31'
	WHERE MOV_DTREGI <= '2015/01/31'
	GROUP BY MOV_LEGAME, MOV_CODMAG, MOV_ANAART
	) as main
WHERE SALDO = 0