SELECT 
mov_cont.id_unique,
MOV_SOC,
MOV_ANNO,
MOV_CONTO,
CONTI.CON_TIPOCO,
CONTI.CON_DESCR,
MOV_NREGIS,
MOV_DTREG,
MOV_NDOC,
MOV_DTDOC,
MOV_TOP,
SUBSTRING(PARA.LIBERA,24,1) AS TOP_INTRA,
SUBSTRING(PARA1.LIBERA,12,1) AS TOP_CLI_FOR,
MOV_IMP,
MOV_TMOV,
MOV_VALUTA,
MOV_CAMBIO,
MOV_IVA,
PARA2.BENI_SERVIZI AS FLG_BENI_SERVIZI,
MOV_MODPAG,
SUBSTRING(PARA3.LIBERA,1,100) AS CPA_MOD_PAG,
MOV_PESO,
MOV_TISPE,
MOV_PORTO,
MOV_CLDOG,
MOV_SERV_INTRA,
MOV_IMPEUR_INTRA,
MOV_IMPVAL_INTRA,
MOV_IMPSTAT_INTRA,
MOV_NAZIONE_INTRA,
MOV_STATO_INTRA_PROV,
MOV_PARTITA_IVA_INTRA,
MOV_QTA_INTRA,
MOV_COND_CONS_INTRA,
MOV_MEZZI_TRASP_INTRA,
MOV_NAZIONE_INTRA,
MOV_PROVIN_DESTI_INTRA,
MOV_UNITA_SUPPL_INTRA,
MOV_CONTABILITA_PREVISIONALE
FROM MOV_CONT AS MOV_CONT 
LEFT OUTER JOIN PARA AS PARA
ON 'TOP'+MOV_CONT.MOV_TOP = PARA.CODICE
LEFT OUTER JOIN PARA AS PARA1
ON 'TOP'+MOV_CONT.MOV_TOP = PARA1.CODICE
LEFT OUTER JOIN PARA AS PARA2
ON 'IVA'+MOV_CONT.MOV_IVA = PARA2.CODICE
LEFT OUTER JOIN PARA AS PARA3
ON 'CPA'+MOV_CONT.MOV_MODPAG = PARA3.CODICE
LEFT OUTER JOIN CONTI AS CONTI
ON MOV_CONTO=CONTI.CON_CONTO
WHERE MOV_SOC='01'
AND MOV_DTREG BETWEEN '2014/01/01' AND '2014/01/31'
AND MOV_TOP <> 'CHI'
AND MOV_CONTABILITA_PREVISIONALE<>'P'
AND SUBSTRING(PARA.LIBERA,24,1)='S'
AND SUBSTRING(PARA1.LIBERA,12,1)='F'
AND CONTI.CON_TIPOCO='X'
AND CONTI.CON_ANNO=MOV_ANNO
ORDER BY TOP_CLI_FOR,FLG_BENI_SERVIZI,MOV_CONTO,MOV_DTREG
