
SELECT 'CLI:'+ RTRIM(substring(MOV_CONTO,5,10))+' N.F:'+RTRIM(MOV_CONT.MOV_NPROT)+' DEL '+MOV_CONT.MOV_DTDOC 
AS NEW_DESMOV,
mov_top,mov_numpro,MOV_DESMOV,MOV_NPROT,* FROM MOV_CONT AS MOV_CONT 
WHERE MOV_ANNO = '2013' AND
MOV_DESMOV NOT LIKE '%N.F:'+ RTRIM(MOV_NPROT)  +'%' AND 
MOV_SEQUEN = 10 AND 
MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) AS COD FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C')
ORDER BY MOV_CONT.mov_numpro,MOV_CONT.MOV_SEQUEN

--update mov_cont set mov_desmov = 'CLI:0036900 N.F:000017 DEL 2013/01/08' where id_unique = 'D39EF161-9F1F-4F91-B852-B1FABEB4CCB5'

/*
UPDATE MOV_CONT SET MOV_DESMOV = 'CLI:'+ RTRIM(substring(MOV_CONTO,5,10))+' N.F:'+RTRIM(MOV_NPROT)+' DEL '+MOV_DTDOC 
	WHERE MOV_ANNO = '2013' AND
	MOV_DESMOV NOT LIKE '%N.F:'+ RTRIM(MOV_NPROT)  +'%' AND 
	MOV_SEQUEN = 10 AND 
	MOV_TOP IN (SELECT SUBSTRING(CODICE,4,3) AS COD FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) = 'S' AND SUBSTRING(LIBERA,12,1) = 'C')
*/