
SELECT *, QUANTE_VOLTE_UTILIZZATO_IN_DOCUMENTI + QUANTE_VOLTE_UTILIZZATO_IN_CGE AS TOTALE_VOLTE_UTILIZZATO FROM (
	select
		SUBSTRING(PARA.CODICE,4,3) AS CODICE,
		RTRIM(DESCRI) AS DESCRIZIONE,
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_OFF_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_ORD_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_BOL_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_FAT_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_FAP_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_ORF_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) +
		(SELECT COUNT(ORD_CPA) AS CONTA FROM U_BFO_TT WHERE ORD_CPA = SUBSTRING(PARA.CODICE,4,3)) AS QUANTE_VOLTE_UTILIZZATO_IN_DOCUMENTI,
		(SELECT COUNT(*) AS CONTA FROM (SELECT MOV_MODPAG,MOV_NUMPRO FROM MOV_CONT WHERE MOV_MODPAG = SUBSTRING(PARA.CODICE,4,3) GROUP BY MOV_MODPAG,MOV_NUMPRO) AS T1) AS QUANTE_VOLTE_UTILIZZATO_IN_CGE
	from para WHERE CODICE LIKE 'CPA%' 
	) AS MAIN
ORDER BY TOTALE_VOLTE_UTILIZZATO

/*
select * from para WHERE CODICE LIKE 'CPA%' 
AND SUBSTRING(CODICE,4,3) NOT IN (
	SELECT ORD_CPA FROM U_OFF_TT
	UNION
	SELECT ORD_CPA FROM U_ORD_TT
	UNION
	SELECT ORD_CPA FROM U_BOL_TT
	UNION
	SELECT ORD_CPA FROM U_FAT_TT
	UNION
	SELECT ORD_CPA FROM U_FAP_TT
	UNION
	SELECT ORD_CPA FROM U_ORF_TT
	UNION
	SELECT ORD_CPA FROM U_BFO_TT) 
AND SUBSTRING(CODICE,4,3) NOT IN (SELECT MOV_MODPAG FROM MOV_CONT WHERE MOV_MODPAG <> '')
ORDER BY CODICE
*/

