SELECT * FROM U_CLI_AN WHERE CLI_CODCLI = '010010008    '
SELECT CLI_ZONA,CLI_NAZION,CLI_CODIVA,CLI_CONPAG,CLI_VALUTA,CLI_CANVEN,CLI_CCOST1, * FROM U_CLI_AN WHERE CLI_CODCLI = '010010008    '

UPDATE U_CLI_AN SET CLI_ZONA = '',  CLI_NAZION = '' , CLI_CODIVA = '' , CLI_CONPAG = '' , CLI_VALUTA = '' , CLI_CANVEN = '' , CLI_CCOST1 = '' WHERE CLI_CODCLI = '010010008    '
UPDATE U_CLI_AN SET CLI_ZONA = 'EEU',  CLI_NAZION = 'ITA' , CLI_CODIVA = '22' , CLI_CONPAG = '107' , CLI_VALUTA = 'EUR' , CLI_CANVEN = 'B2C' , CLI_CCOST1 = 'ADV' WHERE CLI_CODCLI = '010010008    '





UPDATE U_CLI_AN SET CLI_ZONA = '',  CLI_NAZION = '' , CLI_CODIVA = '' , CLI_CONPAG = '' , CLI_VALUTA = '' , CLI_CANVEN = '' , CLI_CCOST1 = '' WHERE CLI_CODCLI = '100199868    '
UPDATE U_CLI_AN SET CLI_ZONA = 'EEU',  CLI_NAZION = 'ITA' , CLI_CODIVA = '22' , CLI_CONPAG = '107' , CLI_VALUTA = 'EUR' , CLI_CANVEN = 'B2C' , CLI_CCOST1 = 'ADV' WHERE CLI_CODCLI = '100199868    '
 

select * from u_ord_tt where ord_numord = '000364' and ord_anno = '2015'
select ORD_CCODET,* from u_ord_dd where daggancio = '6000011642'
update u_ord_dd set ORD_CCODET = '' where id_unique = '92EE3E22-6963-4C6E-892D-F4978DAD0874'
update u_ord_dd set ORD_CCODET = 'ITAPL' where id_unique = '92EE3E22-6963-4C6E-892D-F4978DAD0874'


select ORD_FLBOL,ORD_LASTUSE ,* from u_ord_tt

select ORD_FLBOL,TIPRENDO ,* from u_ord_tt
select ORD_FLBOL,TIPRENDO ,* from u_off_tt
select ORS_CPA ,TIPRENDO,ORS_CODCLI,ORS_RAGSOC,* from u_off_DD
