SELECT * FROM PIANOP_TT
SELECT * FROM PIANOP_DD
SELECT * FROM PIANOP_MO
SELECT * FROM PIANOP_P1
SELECT * FROM PIANOP_P2
SELECT * FROM PIANOP_SA
SELECT * FROM U_CCO_TT
SELECT * FROM U_CCO_DD

DELETE FROM PIANOP_TT
DELETE FROM PIANOP_DD
DELETE FROM PIANOP_MO
DELETE FROM PIANOP_P1
DELETE FROM PIANOP_P2
DELETE FROM PIANOP_SA

DELETE FROM U_CCO_TT
DELETE FROM U_CCO_DD
