SELECT * FROM PART_FOR

UPDATE PART_FOR SET PAR_CONTABILITA_PREVISIONALE  = '' 
UPDATE PART_FOR SET PAR_CODACQ   = '' 
UPDATE PART_FOR SET PAR_TIPOCONTRATTO   = '' 
UPDATE PART_FOR SET PAR_FORMAPAGAMENTO  = '' 
UPDATE PART_FOR SET PAR_GRADOIMPORTANZA  = '' 
UPDATE PART_FOR SET PAR_COSATRATTA   = '' 
UPDATE PART_FOR SET PAR_PRIPAGA  = '' 
UPDATE PART_FOR SET MOV_NUCOM  = '' 

