SELECT MOV_UM,* FROM U_MAG_MO WHERE MOV_ANAART = '01.001.0001'


--SISTEMA UM (art_unimis)/CODICE MAGAZZINO (art_maga) PER GLI ARTICOLI 01.001/01.002/01.004/ SU U_MAG_MO  

SELECT * FROM U_MAG_GG WHERE MAG_ANAART = '01.001.0001'

SELECT MOV_UM,MOV_CODMAG,mov_fornit,mov_desfor,* FROM U_MAG_MO 
WHERE MOV_UM <> (SELECT ART_UNIMIS FROM U_ART_PR WHERE MOV_ANAART =ART_CODPRI)
AND SUBSTRING(MOV_CODART,1,6)  IN ('01.001','01.002','01.004')


SELECT MOV_CODMAG,mov_fornit,mov_desfor,* FROM U_MAG_MO 
WHERE MOV_CODMAG <> (SELECT ART_MAGA FROM U_ART_PR WHERE MOV_ANAART =ART_CODPRI)
AND SUBSTRING(MOV_CODART,1,6)  IN ('01.001','01.002','01.004')



UPDATE U_MAG_MO SET MOV_UM = (SELECT ART_UNIMIS FROM U_ART_PR WHERE MOV_ANAART = ART_CODPRI)
WHERE MOV_UM <> (SELECT ART_UNIMIS FROM U_ART_PR WHERE MOV_ANAART =ART_CODPRI)
AND SUBSTRING(MOV_CODART,1,6)  IN ('01.001','01.002','01.004')


UPDATE U_MAG_MO SET MOV_CODMAG = (SELECT ART_MAGA FROM U_ART_PR WHERE MOV_ANAART = ART_CODPRI) 
WHERE MOV_CODMAG <> (SELECT ART_MAGA FROM U_ART_PR WHERE MOV_ANAART =ART_CODPRI)
AND SUBSTRING(MOV_CODART,1,6)  IN ('01.001','01.002','01.004')