SELECT * FROM U_MAG_GG WHERE MAG_DATAGG > '2012/08/24' AND MAG_CODMAG = 'SEDE'

SELECT * FROM U_MAG_MO WHERE MOV_DTREGI > '2012/08/24' AND MOV_CODMAG = 'SEDE' AND MOV_ANAART <> '.'



SELECT * FROM U_MAG_MO 
WHERE MOV_DTREGI > '2012/08/24' 
	AND MOV_CODMAG = 'SEDE' 
	AND MOV_ANAART <> '.'
	AND MOV_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_MAGA <>'SEDE')


UPDATE U_MAG_MO SET MOV_CODMAG = (SELECT ART_MAGA FROM U_ART_PR WHERE MOV_ANAART = ART_CODPRI)
WHERE MOV_DTREGI > '2012/08/24' 
	AND MOV_CODMAG = 'SEDE' 
	AND MOV_ANAART <> '.'
	AND MOV_CODART IN (SELECT ART_CODPRI FROM U_ART_PR WHERE ART_MAGA <>'SEDE')
