
SELECT FATTURATO.*,TOT.QTATOT,TOT.VALORETOT
FROM (SELECT 
	RICAVI.ORS_NUMORD AS NR_FATTURA,
	RICAVI.ORS_DATORD AS DATA_FATTURA,
	RICAVI.ORD_CODART AS CODART, 
	RICAVI.ORD_UM AS UM_VEN,
	ART.ART_DESCR AS DESCRI,
	ART.ART_BASADE AS BASE_ADESIVO,
	ART.ART_TIPART AS ART_TIPART,
	SUM(ORD_QTAORD) AS QTA_VEN,
	SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS PREZZO,
	SUM(ORD_VALORE) AS VALORE
FROM (SELECT ORS_NUMORD,
			 ORS_DATORD,
			ORD_CODART,
			ORD_UM,
			ORD_QTAORD,
			ORD_VALORE 
		FROM U_FAT_DD 
		WHERE ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31'
			AND ORD_QTAORD>0 
			AND ORD_VALORE>0 
			AND ORD_CODART NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT ) 
			AND RTRIM(ORD_CODART)<>'.'
			AND ORD_DESART NOT LIKE '%POLIECO%') AS RICAVI
LEFT OUTER JOIN U_ART_PR AS ART
ON RICAVI.ORD_CODART = ART.ART_CODPRI 
GROUP BY  RICAVI.ORD_CODART,RICAVI.ORD_UM,ART.ART_DESCR,ART.ART_BASADE, ART.ART_TIPART, RICAVI.ORS_NUMORD, RICAVI.ORS_DATORD ) AS FATTURATO
LEFT OUTER JOIN (SELECT 
			ORD_CODART,
			SUM(ORD_QTAORD) AS QTATOT,
			SUM(ORD_VALORE) AS VALORETOT			 
		FROM U_FAT_DD 
		WHERE ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31'
			AND ORD_QTAORD>0 
			AND ORD_VALORE>0 
			AND ORD_CODART NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT )
			AND RTRIM(ORD_CODART)<>'.'
			AND ORD_DESART NOT LIKE '%POLIECO%'
		GROUP BY ORD_CODART) AS TOT
ON FATTURATO.CODART = TOT.ORD_CODART 
ORDER BY  CODART,ART_TIPART,DATA_FATTURA,NR_FATTURA




