--- banche cliente non presenti in archivio banche

SELECT * FROM (
SELECT CLI_BAE,COALESCE(BAN_DESBAN,'---NON PRESENTE---') AS DESCRIZIONE,CLI_CODCLI,CLI_RAGSOC 
FROM U_CLI_AN AS CLI
LEFT OUTER JOIN U_BAN_AN AS BAN
ON CLI.CLI_BAE=BAN.BAN_CODBAN
WHERE CLI_BAE<>'') AS T1
WHERE DESCRIZIONE='---NON PRESENTE---'



--- banche NON UTILIZZATE DAI CLIENTI E NON DI PRESENTAZIONE EFFETTI

SELECT * FROM (
SELECT BAN_CODBAN,BAN_DESBAN,COALESCE(CLI_CODCLI,'') AS CLI_CODCLI ,COALESCE(CLI_RAGSOC,'') AS CLI_RAGSOC 
FROM U_BAN_AN AS BAN
LEFT OUTER JOIN U_CLI_AN AS CLI
ON CLI.CLI_BAE=BAN.BAN_CODBAN
WHERE BAN_PRESE<>'S' ) AS T1
WHERE CLI_CODCLI='' AND BAN_CODBAN<>''


DELETE  FROM U_BAN_AN 
WHERE BAN_CODBAN IN (
SELECT BAN_CODBAN FROM (
SELECT BAN_CODBAN,BAN_DESBAN,COALESCE(CLI_CODCLI,'') AS CLI_CODCLI ,COALESCE(CLI_RAGSOC,'') AS CLI_RAGSOC 
FROM U_BAN_AN AS BAN
LEFT OUTER JOIN U_CLI_AN AS CLI
ON CLI.CLI_BAE=BAN.BAN_CODBAN
WHERE BAN_PRESE<>'S' ) AS T1
WHERE CLI_CODCLI='' AND BAN_CODBAN<>'' )


--- banche UTILIZZATE DAI CLIENTI E DI PRESENTAZIONE EFFETTI


SELECT * FROM (
SELECT BAN_CODBAN,BAN_DESBAN,BAN_PRESE AS BANCA_PRES_RIBA,COALESCE(CLI_CODCLI,'') AS CLI_CODCLI ,COALESCE(CLI_RAGSOC,'') AS CLI_RAGSOC 
FROM U_BAN_AN AS BAN
LEFT OUTER JOIN U_CLI_AN AS CLI
ON CLI.CLI_BAE=BAN.BAN_CODBAN ) AS T1
WHERE CLI_CODCLI<>'' AND BAN_CODBAN<>''
ORDER BY BAN_DESBAN


