
/* ELABORA TUTTO IL PIANO DEI CONTI AZZERANDO I SALDI DARE / AVERE , RICREA I SALDI DEL MESE DA MOV_CONT*/ 


SELECT 
		CON_CONTO,
		CON_DESCR,
		COALESCE(T1.CON_DA01,0) AS CON_DA01,
		COALESCE(T1.CON_AV01,0) AS CON_AV01,
		COALESCE(T1.CON_DA02,0) AS CON_DA02,
		COALESCE(T1.CON_AV02,0) AS CON_AV02,
		COALESCE(T1.CON_DA03,0) AS CON_DA03,
		COALESCE(T1.CON_AV03,0) AS CON_AV03,
		COALESCE(T1.CON_DA04,0) AS CON_DA04,
		COALESCE(T1.CON_AV04,0) AS CON_AV04,
		COALESCE(T1.CON_DA05,0) AS CON_DA05,
		COALESCE(T1.CON_AV05,0) AS CON_AV05,
		COALESCE(T1.CON_DA06,0) AS CON_DA06,
		COALESCE(T1.CON_AV06,0) AS CON_AV06,
		COALESCE(T1.CON_DA07,0) AS CON_DA07,
		COALESCE(T1.CON_AV07,0) AS CON_AV07,
		COALESCE(T1.CON_DA08,0) AS CON_DA08,
		COALESCE(T1.CON_AV08,0) AS CON_AV08,
		COALESCE(T1.CON_DA09,0) AS CON_DA09,
		COALESCE(T1.CON_AV09,0) AS CON_AV09,
		COALESCE(T1.CON_DA10,0) AS CON_DA10,
		COALESCE(T1.CON_AV10,0) AS CON_AV10,
		COALESCE(T1.CON_DA11,0) AS CON_DA11,
		COALESCE(T1.CON_AV11,0) AS CON_AV11,
		COALESCE(T1.CON_DA12,0) AS CON_DA12,
		COALESCE(T1.CON_AV12,0) AS CON_AV12,
		
		COALESCE(T1.CON_DA01,0)+COALESCE(T1.CON_DA02,0)+COALESCE(T1.CON_DA03,0)+COALESCE(T1.CON_DA04,0)+COALESCE(T1.CON_DA05,0)+COALESCE(T1.CON_DA06,0)+COALESCE(T1.CON_DA07,0)+COALESCE(T1.CON_DA08,0)+COALESCE(T1.CON_DA09,0)+COALESCE(T1.CON_DA10,0)+COALESCE(T1.CON_DA11,0)+COALESCE(T1.CON_DA12,0) AS CON_IMP_D,
		COALESCE(T1.CON_AV01,0)+COALESCE(T1.CON_AV02,0)+COALESCE(T1.CON_AV03,0)+COALESCE(T1.CON_AV04,0)+COALESCE(T1.CON_AV05,0)+COALESCE(T1.CON_AV06,0)+COALESCE(T1.CON_AV07,0)+COALESCE(T1.CON_AV08,0)+COALESCE(T1.CON_AV09,0)+COALESCE(T1.CON_AV10,0)+COALESCE(T1.CON_AV11,0)+COALESCE(T1.CON_AV12,0) AS CON_IMP_A


		FROM CONTI

		LEFT OUTER JOIN (SELECT MOV_ANNO,MOV_CONTO,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '01' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA01,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '01' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV01,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '02' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA02,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '02' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV02,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '03' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA03,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '03' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV03,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '04' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA04,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '04' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV04,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '05' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA05,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '05' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV05,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '06' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA06,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '06' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV06,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '07' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA07,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '07' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV07,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '08' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA08,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '08' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV08,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '09' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA09,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '09' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV09,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '10' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA10,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '10' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV10,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '11' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA11,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '11' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV11,
					 SUM(CAST(CASE WHEN MOV_TMOV='D' AND SUBSTRING(MOV_DTREG,6,2) = '12' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_DA12,
					 SUM(CAST(CASE WHEN MOV_TMOV='A' AND SUBSTRING(MOV_DTREG,6,2) = '12' THEN MOV_IMP ELSE 0 END AS NUMERIC(27,10))) AS CON_AV12


					 FROM MOV_CONT WHERE MOV_ANNO='2012' GROUP BY MOV_ANNO,MOV_CONTO) AS T1
				 ON T1.MOV_CONTO = CONTI.CON_CONTO

WHERE CON_ANNO='2012'
ORDER BY CON_CONTO




/* ELABORA MOV_CONT PER OTTENERE IL SALDO A LIVELLO DI CONTO CONTABILE SOMMANDO TUTTI I DARE E TUTTI GLI AVERE*/
/* ATTIVITA' PASSIVITA' SALDO*/


SELECT 
		MOV_ANNO,MOV_CONTO,
        SUM(MOV_IMP_D) AS MOV_IMP_D,
		SUM(MOV_IMP_A) AS MOV_IMP_A,
		SUM(MOV_IMP_D-MOV_IMP_A) AS MOV_IMP_SALDO 
		FROM (SELECT MOV_ANNO,MOV_CONTO,
				CASE WHEN MOV_TMOV='D' THEN MOV_IMP ELSE 0 END AS MOV_IMP_D,
				CASE WHEN MOV_TMOV='A' THEN MOV_IMP ELSE 0 END AS MOV_IMP_A
				FROM MOV_CONT
				WHERE LEN(MOV_CONTO)>5
				AND MOV_CONTO>='01' AND MOV_CONTO<'30'
				AND MOV_SOC='01'
		AND MOV_ANNO='2012') AS T1

GROUP BY MOV_ANNO,MOV_CONTO
ORDER BY MOV_CONTO




 
/* RAGGRUPPA I CONTI PATRIMONIALI PER CONTO SOMMANDO I MESI CONTABILI DARE-AVERE*/
/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

		CON_CONTO,CON_DESCR,
		SUM(CON_IMP_D) AS CON_IMP_D,SUM(CON_IMP_A) AS CON_IMP_A, 
		SUM(CON_DA01) AS CON_DA01,SUM(CON_AV01) AS CON_AV01,
		SUM(CON_DA02) AS CON_DA02,SUM(CON_AV02) AS CON_AV02,
		SUM(CON_DA03) AS CON_DA03,SUM(CON_AV03) AS CON_AV03,
		SUM(CON_DA04) AS CON_DA04,SUM(CON_AV04) AS CON_AV04,
		SUM(CON_DA05) AS CON_DA05,SUM(CON_AV05) AS CON_AV05,
		SUM(CON_DA06) AS CON_DA06,SUM(CON_AV06) AS CON_AV06,
		SUM(CON_DA07) AS CON_DA07,SUM(CON_AV07) AS CON_AV07,
		SUM(CON_DA08) AS CON_DA08,SUM(CON_AV08) AS CON_AV08,
		SUM(CON_DA09) AS CON_DA09,SUM(CON_AV09) AS CON_AV09,
		SUM(CON_DA10) AS CON_DA10,SUM(CON_AV10) AS CON_AV10,
		SUM(CON_DA11) AS CON_DA11,SUM(CON_AV11) AS CON_AV11,
		SUM(CON_DA12) AS CON_DA12,SUM(CON_AV12) AS CON_AV12


		FROM (SELECT CON_CONTO,CON_DESCR,

			CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,
			CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A, 
			CASE WHEN CON_DA01>CON_AV01 THEN CON_DA01-CON_AV01 ELSE 0 END AS CON_DA01,
			CASE WHEN CON_DA01<CON_AV01 THEN CON_AV01-CON_DA01 ELSE 0 END AS CON_AV01, 
			CASE WHEN CON_DA02>CON_AV02 THEN CON_DA02-CON_AV02 ELSE 0 END AS CON_DA02,
			CASE WHEN CON_DA02<CON_AV02 THEN CON_AV02-CON_DA02 ELSE 0 END AS CON_AV02, 
			CASE WHEN CON_DA03>CON_AV03 THEN CON_DA03-CON_AV03 ELSE 0 END AS CON_DA03,
			CASE WHEN CON_DA03<CON_AV03 THEN CON_AV03-CON_DA03 ELSE 0 END AS CON_AV03, 
			CASE WHEN CON_DA04>CON_AV04 THEN CON_DA04-CON_AV04 ELSE 0 END AS CON_DA04,
			CASE WHEN CON_DA04<CON_AV04 THEN CON_AV04-CON_DA04 ELSE 0 END AS CON_AV04, 
			CASE WHEN CON_DA05>CON_AV05 THEN CON_DA05-CON_AV05 ELSE 0 END AS CON_DA05,
			CASE WHEN CON_DA05<CON_AV05 THEN CON_AV05-CON_DA05 ELSE 0 END AS CON_AV05, 
			CASE WHEN CON_DA06>CON_AV06 THEN CON_DA06-CON_AV06 ELSE 0 END AS CON_DA06,
			CASE WHEN CON_DA06<CON_AV06 THEN CON_AV06-CON_DA06 ELSE 0 END AS CON_AV06, 
			CASE WHEN CON_DA07>CON_AV07 THEN CON_DA07-CON_AV07 ELSE 0 END AS CON_DA07,
			CASE WHEN CON_DA07<CON_AV07 THEN CON_AV07-CON_DA07 ELSE 0 END AS CON_AV07, 
			CASE WHEN CON_DA08>CON_AV08 THEN CON_DA08-CON_AV08 ELSE 0 END AS CON_DA08,
			CASE WHEN CON_DA08<CON_AV08 THEN CON_AV08-CON_DA08 ELSE 0 END AS CON_AV08, 
			CASE WHEN CON_DA09>CON_AV09 THEN CON_DA09-CON_AV09 ELSE 0 END AS CON_DA09,
			CASE WHEN CON_DA09<CON_AV09 THEN CON_AV09-CON_DA09 ELSE 0 END AS CON_AV09, 
			CASE WHEN CON_DA10>CON_AV10 THEN CON_DA10-CON_AV10 ELSE 0 END AS CON_DA10,
			CASE WHEN CON_DA10<CON_AV10 THEN CON_AV10-CON_DA10 ELSE 0 END AS CON_AV10, 
			CASE WHEN CON_DA11>CON_AV11 THEN CON_DA11-CON_AV11 ELSE 0 END AS CON_DA11,
			CASE WHEN CON_DA11<CON_AV11 THEN CON_AV11-CON_DA11 ELSE 0 END AS CON_AV11, 
			CASE WHEN CON_DA12>CON_AV12 THEN CON_DA12-CON_AV12 ELSE 0 END AS CON_DA12,
			CASE WHEN CON_DA12<CON_AV12 THEN CON_AV12-CON_DA12 ELSE 0 END AS CON_AV12 



FROM CONTI
WHERE LEN(CON_CONTO)>5
AND CON_IMP_D<>CON_IMP_A
AND CON_CONTO>='01' AND CON_CONTO<'30'
AND CON_SOC='01'
AND CON_ANNO='2012') AS T1
GROUP BY CON_CONTO,CON_DESCR
ORDER BY CON_CONTO



