SELECT 
	ARTV.ART_CODPRI AS CODART,
	ARTV.ART_UNIMIS AS UM_VEN,
	RICAVI_MEDI.QTA AS QTA_VENDUTA,
	RICAVI_MEDI.VALORE AS FATTURATO,
	RICAVI_MEDI.RICAVO AS RICAVO_MEDIO 
FROM U_ART_PR AS ARTV
LEFT OUTER JOIN ( SELECT 
					ORD_CODART AS CODART, 
					SUM(ORD_QTAORD) AS QTA,
					SUM(ORD_VALORE) AS VALORE, 
					SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS RICAVO 
				FROM (SELECT ORD_CODART,ORD_QTAORD,ORD_VALORE 
						FROM U_FAT_DD 
						WHERE ORD_QTAORD>0 
						AND ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31' ) AS RICAVI GROUP BY ORD_CODART ) AS RICAVI_MEDI
ON ARTV.ART_CODPRI = RICAVI_MEDI.CODART 
WHERE ARTV.ART_CODPRI IN (SELECT DISTINCT DIS_GRUPPO FROM U_DIS_DD) 
AND RICAVI_MEDI.VALORE IS NOT NULL