
SELECT 
	CODART,
	UM,
	SUM(QTA*COSTO_UNITARIO) AS COSTO
FROM (SELECT 
	CODART,
	UM,
	COD_COMPONENTE,
	QTA,
	CASE 
		WHEN COSTO_DA_ULTIMA_BOLLA_DI_CARICO >0 
		THEN COSTO_DA_ULTIMA_BOLLA_DI_CARICO
		ELSE COSTO_COMPONENTE_DA_ANAGRAFICA_ARTICOLI
		END AS COSTO_UNITARIO,
	COSTO_DISTINTA_DA_ANAGRAFICA_ARTICOLI 
FROM ( SELECT 
	DIS_GRUPPO AS CODART,
	'KG' AS UM,
	DIS_CODART AS COD_COMPONENTE, 
	DIS_QTA AS QTA,
    COALESCE((SELECT TOP 1 ORD_VALORE/ORD_QTAORD 	 
				FROM U_BFO_DD 
				WHERE ORD_CODART=DIS.DIS_CODART AND ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31' 
				ORDER BY ORS_DATORD DESC ),0) AS COSTO_DA_ULTIMA_BOLLA_DI_CARICO ,
	COALESCE(ART.ART_PRZCO1  ,0) COSTO_COMPONENTE_DA_ANAGRAFICA_ARTICOLI,
	ARTG.ART_PRZCO1 AS COSTO_DISTINTA_DA_ANAGRAFICA_ARTICOLI
FROM U_DIS_DD AS DIS
LEFT OUTER JOIN U_ART_PR AS ART
ON DIS.DIS_CODART = ART.ART_CODPRI 
INNER JOIN U_ART_PR AS ARTG
ON DIS.DIS_GRUPPO = ARTG.ART_CODPRI 
WHERE DIS.DIS_UM <>'NR' AND DIS.DIS_UM <>'ML'
) AS COSTI_COMPONENTI ) AS COSTI
WHERE CODART='A 0025' 
GROUP BY CODART,UM

