
SELECT * FROM U_DIS_TT WHERE SUBSTRING(TAGGANCIO,1,1)='_'
SELECT * FROM U_DIS_DD WHERE SUBSTRING(DAGGANCIO,1,1)='_'


DELETE FROM U_DIS_TT WHERE SUBSTRING(TAGGANCIO,1,1)='_'
DELETE FROM U_DIS_DD WHERE SUBSTRING(DAGGANCIO,1,1)='_'

