SELECT * FROM U_PRD_D1
SELECT * FROM U_PRD_D2
SELECT * FROM U_PRD_D3
SELECT * FROM U_PRD_D4
SELECT * FROM U_PRD_D5
SELECT * FROM U_PRD_DR
--SELECT * FROM U_PRD_HY

DELETE U_PRD_D1
DELETE U_PRD_D2
DELETE U_PRD_D3
DELETE U_PRD_D4
DELETE U_PRD_D5
DELETE U_PRD_DR
--DELETE U_PRD_HY


