
--- ORDINI 
SELECT	
	ORD_DATORD,
	COUNT(*) AS QUANTI_ORDINI, 
	SUM(ORD_VALORE) AS AQ_OC_VALOR ,
	SUM(ORD_QTANR) AS AQ_OC_QTANR,
	SUM(ORD_QTAKG) AS AQ_OC_QTAKG,
	SUM(ORD_QTAMC) AS AQ_OC_QTAMC,
	SUM(ORD_QTAMQ) AS AQ_OC_QTAMQ,
	SUM(ORD_QTAML) AS AQ_OC_QTAML 
FROM(
	SELECT
		TT.ORD_NUMORD,
		TT.ORD_DATORD,
		TT.TAGGANCIO,
		SUM(DD.ORD_VALORE) AS ORD_VALORE,
		SUM(DD.ORD_NUMBOB) AS ORD_QTANR,
		SUM(DD.ORD_QTAKG) AS ORD_QTAKG,
		SUM(DD.ORD_QTAMC) AS ORD_QTAMC,
		SUM(DD.ORD_QTAMQ) AS ORD_QTAMQ,
		SUM(DD.ORD_QTAML) AS ORD_QTAML 
	FROM U_ORD_TT AS TT
	LEFT OUTER JOIN U_ORD_DD AS DD
	ON TT.TAGGANCIO=DD.DAGGANCIO AND DD.ORD_CODART <>'' AND DD.ORD_DESART<>'*** COMMENTO ***'
	GROUP BY TT.ORD_NUMORD, TT.ORD_DATORD, TT.TAGGANCIO) AS T1
WHERE ORD_DATORD='2012/03/29'
GROUP BY ORD_DATORD
ORDER BY ORD_DATORD 


-- DDT

SELECT	
	ORD_DATORD,
	COUNT(*) AS QUANTI_DDT, 
	SUM(ORD_VALORE) AS AQ_DT_VALOR ,
	SUM(ORD_QTANR) AS AQ_DT_QTANR,
	SUM(ORD_QTAKG) AS AQ_DT_QTAKG,
	SUM(ORD_QTAMC) AS AQ_DT_QTAMC,
	SUM(ORD_QTAMQ) AS AQ_DT_QTAMQ,
	SUM(ORD_QTAML) AS AQ_DT_QTAML 
FROM(
	SELECT 
		ORD_NUMORD,
		ORD_DATORD,
		TT.ORD_VALORE ,
		SUM(ORD_NUMBOB) AS ORD_QTANR,
		SUM(ORD_QTAKG) AS ORD_QTAKG,
		SUM(ORD_QTAMC) AS ORD_QTAMC,
		SUM(ORD_QTAMQ) AS ORD_QTAMQ,
		SUM(ORD_QTAML) AS ORD_QTAML 
	FROM U_BOL_TT AS TT
	LEFT OUTER JOIN U_BOL_DD AS DD
	ON TT.TAGGANCIO=DD.DAGGANCIO AND ORD_CODART <>'' AND ORD_DESART<>'*** COMMENTO ***'
	GROUP BY ORD_DATORD,TAGGANCIO ,ORD_NUMORD,TT.ORD_VALORE ) AS T1
WHERE ORD_DATORD='2012/03/29'
GROUP BY ORD_DATORD
ORDER BY ORD_DATORD 


--- FATTURE 
SELECT	
	ORD_DATORD,
	COUNT(*) AS QUANTE_FATTURE, 
	SUM(ORD_VALORE) AS AQ_FC_VALOR ,
	SUM(ORD_QTANR) AS AQ_FC_QTANR,
	SUM(ORD_QTAKG) AS AQ_FC_QTAKG,
	SUM(ORD_QTAMC) AS AQ_FC_QTAMC,
	SUM(ORD_QTAMQ) AS AQ_FC_QTAMQ,
	SUM(ORD_QTAML) AS AQ_FC_QTAML 
FROM(
	SELECT 
		ORD_NUMORD,
		ORD_DATORD,
		TT.ORD_VALORE ,
		SUM(ORD_NUMBOB) AS ORD_QTANR,
		SUM(ORD_QTAKG) AS ORD_QTAKG,
		SUM(ORD_QTAMC) AS ORD_QTAMC,
		SUM(ORD_QTAMQ) AS ORD_QTAMQ,
		SUM(ORD_QTAML) AS ORD_QTAML 
	FROM U_FAT_TT AS TT
	LEFT OUTER JOIN U_FAT_DD AS DD
	ON TT.TAGGANCIO=DD.DAGGANCIO AND ORD_CODART <>'' AND ORD_DESART<>'*** COMMENTO ***'
	GROUP BY ORD_DATORD,TAGGANCIO ,ORD_NUMORD,TT.ORD_VALORE ) AS T1
WHERE ORD_DATORD='2012/03/29'
GROUP BY ORD_DATORD
ORDER BY ORD_DATORD 
