 
-- SOLO DIFFERENZE DI N.RIGHE TRA MOVIMENTI CONTABILI (INDICE) E RICEVUTE BANCARIE (U_RIC_TT)
SELECT MOV_NPROT,MOV_CONTO,TOT_MOV_IMP,TOT_RIC_TRANC,CONTA_IND,CONTA_RIC FROM ( 
      SELECT * FROM (
      SELECT MOV_NPROT,SUM(MOV_IMP) AS TOT_MOV_IMP,MOV_CONTO, COUNT(*) AS CONTA_IND FROM INDICE WHERE MOV_ANNO = '2012' AND MOV_TOP = 'CRB'
      GROUP BY MOV_NPROT,MOV_CONTO) AS T_IND
      LEFT OUTER JOIN 
      (
            SELECT RIC_NFATT, '10102' + U_RIC_TT.RIC_CODCLI AS RIC_CONTO, SUM(RIC_TRANC) AS TOT_RIC_TRANC, COUNT(*) AS CONTA_RIC FROM U_RIC_TT
            GROUP BY RIC_NFATT,'10102' + U_RIC_TT.RIC_CODCLI) AS T_RIC 
      ON T_IND.MOV_NPROT = T_RIC.RIC_NFATT AND T_IND.MOV_CONTO = T_RIC.RIC_CONTO 
      ) AS T_CONFRONTO
WHERE CONTA_IND <> CONTA_RIC

-- 
-- SOLO DIFFERENZE DI VALORE TRA MOVIMENTI CONTABILI (INDICE) E RICEVUTE BANCARIE (U_RIC_TT) SU_RIC_TRANC 
SELECT MOV_NPROT,MOV_CONTO,TOT_MOV_IMP,TOT_RIC_TRANC,CONTA_IND,CONTA_RIC FROM ( 
      SELECT * FROM (
      SELECT MOV_NPROT,SUM(MOV_IMP) AS TOT_MOV_IMP,MOV_CONTO, COUNT(*) AS CONTA_IND FROM INDICE WHERE MOV_ANNO = '2012' AND MOV_TOP = 'CRB'
      GROUP BY MOV_NPROT,MOV_CONTO) AS T_IND
      LEFT OUTER JOIN 
      (
            SELECT RIC_NFATT, '10102' + U_RIC_TT.RIC_CODCLI AS RIC_CONTO, SUM(RIC_TRANC) AS TOT_RIC_TRANC, COUNT(*) AS CONTA_RIC FROM U_RIC_TT
            GROUP BY RIC_NFATT,'10102' + U_RIC_TT.RIC_CODCLI) AS T_RIC 
      ON T_IND.MOV_NPROT = T_RIC.RIC_NFATT AND T_IND.MOV_CONTO = T_RIC.RIC_CONTO 
      ) AS T_CONFRONTO
WHERE TOT_MOV_IMP <> TOT_RIC_TRANC

-- TUTTO
SELECT MOV_NPROT,MOV_CONTO,TOT_MOV_IMP,TOT_RIC_TRANC,CONTA_IND,CONTA_RIC FROM ( 
      SELECT * FROM (
      SELECT MOV_NPROT,SUM(MOV_IMP) AS TOT_MOV_IMP,MOV_CONTO, COUNT(*) AS CONTA_IND FROM INDICE WHERE MOV_ANNO = '2012' AND MOV_TOP = 'CRB'
      GROUP BY MOV_NPROT,MOV_CONTO) AS T_IND
      LEFT OUTER JOIN 
      (
            SELECT RIC_NFATT, '10102' + U_RIC_TT.RIC_CODCLI AS RIC_CONTO, SUM(RIC_TRANC) AS TOT_RIC_TRANC, COUNT(*) AS CONTA_RIC FROM U_RIC_TT
            GROUP BY RIC_NFATT,'10102' + U_RIC_TT.RIC_CODCLI) AS T_RIC 
      ON T_IND.MOV_NPROT = T_RIC.RIC_NFATT AND T_IND.MOV_CONTO = T_RIC.RIC_CONTO 
      ) AS T_CONFRONTO
