SELECT DARE-AVERE FROM
(SELECT 
	SUM(CON_IMP_D) AS DARE ,
	SUM(CON_IMP_A) AS AVERE 
FROM CONTI
WHERE CON_ANNO = '2010'
AND LEN(CON_CONTO)>4
AND CON_CONTO>='01' AND CON_CONTO<'30') AS D_A

SELECT 
	SUM(CON_IMP_D) AS DARE ,
	SUM(CON_IMP_A) AS AVERE ,
	SUM(CON_IMP_D-CON_IMP_A) AS SALDO
FROM CONTI
WHERE CON_ANNO = '2010'
AND LEN(CON_CONTO)>4
AND CON_CONTO>='01' AND CON_CONTO<'30'



SELECT 
	CON_CONTO,
	CON_IMP_D AS DARE ,
	CON_IMP_A AS AVERE ,
	CON_IMP_D-CON_IMP_A AS SALDO
FROM CONTI
WHERE CON_ANNO = '2010'
AND LEN(CON_CONTO)=4
AND CON_CONTO>='01' AND CON_CONTO<'30'


SELECT 
	SUM(CON_IMP_D) AS DARE ,
	SUM(CON_IMP_A) AS AVERE ,
	SUM(CON_IMP_D-CON_IMP_A) AS SALDO
FROM CONTI
WHERE CON_ANNO = '2010'
AND LEN(CON_CONTO)=4
AND CON_CONTO>='01' AND CON_CONTO<'30'