/*
SELECT 
	MC.MOV_NREGIS,
	MC.MOV_ANNO,
	MC.MOV_CONTO,
	CO.CON_DESCR,
	MC.MOV_TOP,
	SUBSTRING(PT.LIBERA,2,1) AS FATTURA,
	MC.MOV_TMOV,
	PC.SOLOIMPIVA AS SOLOIMPIVA,
	MC.MOV_IMP,
	MC.MOV_IMPOST,
	MC.MOV_MODPAG,
	MC.MOV_IVA 
FROM MOV_CONT AS MC
LEFT OUTER JOIN CONTI AS CO
ON MC.MOV_CONTO=CO.CON_CONTO AND CO.CON_ANNO='2012'
LEFT OUTER JOIN PARA AS PT
ON 'TOP'+MC.MOV_TOP=PT.CODICE 
LEFT OUTER JOIN PARA AS PC
ON 'CPA'+MC.MOV_MODPAG=PC.CODICE 
WHERE SUBSTRING(MC.MOV_CONTO,1,4)='2110'
	AND MC.MOV_ANNO='2012'
	AND SUBSTRING(PT.LIBERA,2,1)='S'
	AND PC.SOLOIMPIVA='IVA'
ORDER BY MC.MOV_NREGIS


*/


SELECT 
	MC.MOV_NREGIS,
	MC.MOV_ANNO,
	MC.MOV_CONTO,
	CO.CON_DESCR,
	MC.MOV_TOP,
	SUBSTRING(PT.LIBERA,2,1) AS FATTURA,
	MC.MOV_TMOV,
	PC.SOLOIMPIVA AS SOLOIMPIVA,
	MC.MOV_IMP,
	MC.MOV_IMPOST,
	MC.MOV_MODPAG,
	MC.MOV_IVA 
FROM MOV_CONT AS MC
LEFT OUTER JOIN CONTI AS CO
ON MC.MOV_CONTO=CO.CON_CONTO AND CO.CON_ANNO='2012'
LEFT OUTER JOIN PARA AS PT
ON 'TOP'+MC.MOV_TOP=PT.CODICE 
LEFT OUTER JOIN PARA AS PC
ON 'CPA'+MC.MOV_MODPAG=PC.CODICE 
WHERE SUBSTRING(MC.MOV_CONTO,1,4)='1010'
	AND MC.MOV_ANNO='2012'
	AND SUBSTRING(PT.LIBERA,2,1)='S'
	AND PC.SOLOIMPIVA='IVA'
	AND PC.CODICE='CPA510'
ORDER BY MC.MOV_NREGIS


/*
SELECT * FROM PART_CLI*/