
SELECT 
	MOV.CODART,
	ART.ART_UNIMIS AS UM,
	COALESCE(RICAVI_MEDI.UM_VEN,ART.ART_UMMAGA) AS UM_VEN,
	MOV.GIACENZA,
	MOV.QTA_CARICO,
	MOV.VALACQ,
	COALESCE(RICAVI_MEDI.RICAVO,0) AS RICAVO_MEDIO,
	CASE WHEN QTA_CARICO >0 THEN VALACQ/QTA_CARICO ELSE 0 END AS COSTO_MEDIO,
	COALESCE((SELECT TOP 1 ORD_PRZNET	 
				FROM U_BFO_DD 
				WHERE ORD_CODART=MOV.CODART 
						AND ORS_DATORD < '2012/12/31' 
						AND ORD_QTAORD>0
						AND ORD_VALORE>0
				ORDER BY ORS_DATORD DESC ),0) AS COSTO_DA_ULTIMA_BOLLA_DI_CARICO 
FROM (SELECT CODART,GIACENZA,QTA_CARICO,VALACQ FROM (SELECT 
										MOV_ANAART AS CODART,
										SUM((CASE WHEN MOV_SEGNO = '+' THEN 1 ELSE -1 END) *  MOV_QTAMOV ) AS GIACENZA, 
										SUM(CASE WHEN MOV_SEGNO = '+' AND MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31' THEN MOV_QTAMOV ELSE 0 END) AS QTA_CARICO ,
										SUM(CASE WHEN MOV_SEGNO = '+' AND MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31' THEN MOV_VALACQ ELSE 0 END) AS VALACQ 
									FROM U_MAG_MO
									WHERE MOV_QTAMOV<>0 
										AND (MOV_SEGNO ='+' OR MOV_SEGNO='-') 
										AND	MOV_ANAART<>'.' 
										AND MOV_ANAART NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT)
									GROUP BY MOV_ANAART) AS T1 WHERE  GIACENZA <> 0 ) AS MOV 
LEFT OUTER JOIN (SELECT 
					ORD_CODART AS CODART, 
					ORD_UM AS UM_VEN,
					SUM(ORD_QTAORD) AS QTA,
					SUM(ORD_VALORE) AS VALORE, 
					SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS RICAVO 
				FROM (SELECT ORD_CODART,ORD_UM,ORD_QTAORD,ORD_VALORE 
						FROM U_FAT_DD 
						WHERE ORD_QTAORD>0 
							AND ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31') AS RICAVI
				GROUP BY ORD_CODART,ORD_UM  ) AS RICAVI_MEDI
ON MOV.CODART = RICAVI_MEDI.CODART 
LEFT OUTER JOIN U_ART_PR AS ART
ON MOV.CODART = ART.ART_CODPRI





