
	SELECT 
		COSTI_MEDI.CODART,
		COSTI_MEDI.DESCRI,
		COSTI_MEDI.BASE_ADESIVO,
		COSTI_MEDI.UM_ACQ,
		COSTI_MEDI.COSTO_MEDIO AS COSTO_MEDIO ,
		COSTI_MEDI.UM_VEN,
		COALESCE(RICAVI_MEDI.QTA,0) AS QTA_VENDUTA,
		COALESCE(RICAVI_MEDI.VALORE,0) AS FATTURATO,
		COALESCE(RICAVI_MEDI.RICAVO,0) AS RICAVO_MEDIO 
	FROM ( SELECT 
		CODART,
		DESCRI,
		BASE_ADESIVO,
		UM_ACQ,
		UM_VEN,
		SUM(QTA*COSTO_UNITARIO) AS COSTO_MEDIO
	FROM (SELECT 
		CODART,
		DESCRI,
		BASE_ADESIVO,
		UM_ACQ,
		UM_VEN,
		COD_COMPONENTE,
		QTA,
		COSTO_DA_ULTIMA_BOLLA_DI_CARICO AS COSTO_UNITARIO,
		COSTO_DISTINTA_DA_ANAGRAFICA_ARTICOLI 
	FROM ( SELECT 
		DIS_GRUPPO AS CODART,
		ARTG.ART_DESCR AS DESCRI,
		ARTG.ART_BASADE AS BASE_ADESIVO,
		'KG' AS UM_ACQ,
		ARTG.ART_UMMAGA AS UM_VEN,
		DIS_CODART AS COD_COMPONENTE, 
		DIS_QTA AS QTA,
	    COALESCE((SELECT TOP 1 ORD_VALORE/ORD_QTAORD 	 
					FROM U_BFO_DD 
					WHERE ORD_CODART=DIS.DIS_CODART 
							AND ORS_DATORD < '2012/12/31' 
							AND ORD_QTAORD>0
							AND ORD_VALORE>0
					ORDER BY ORS_DATORD DESC ),0) AS COSTO_DA_ULTIMA_BOLLA_DI_CARICO ,
		COALESCE(ART.ART_PRZCO1  ,0) AS COSTO_COMPONENTE_DA_ANAGRAFICA_ARTICOLI,
		ARTG.ART_PRZCO1 AS COSTO_DISTINTA_DA_ANAGRAFICA_ARTICOLI
	FROM U_DIS_DD AS DIS
	LEFT OUTER JOIN U_ART_PR AS ART
	ON DIS.DIS_CODART = ART.ART_CODPRI 
	INNER JOIN U_ART_PR AS ARTG
	ON DIS.DIS_GRUPPO = ARTG.ART_CODPRI 
	WHERE DIS.DIS_UM <>'NR' AND DIS.DIS_UM <>'ML' AND DIS.DIS_GRUPPO='A 0025') AS COSTI_COMPONENTI ) AS COSTI
	GROUP BY CODART,BASE_ADESIVO,DESCRI,UM_ACQ,UM_VEN 
	 ) AS COSTI_MEDI
	LEFT OUTER JOIN (SELECT 
						ORD_CODART AS CODART, 
						SUM(ORD_QTAORD) AS QTA,
						SUM(ORD_VALORE) AS VALORE, 
						SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS RICAVO 
					FROM (SELECT ORD_CODART,ORD_QTAORD,ORD_VALORE 
							FROM U_FAT_DD 
							WHERE ORD_QTAORD>0 
								AND ORS_DATORD BETWEEN '1900/01/01' AND '2012/12/31') AS RICAVI
					GROUP BY ORD_CODART ) AS RICAVI_MEDI
	ON COSTI_MEDI.CODART = RICAVI_MEDI.CODART 
	ORDER BY COSTI_MEDI.CODART