	SELECT 
		COSTI_MEDI.CODART,
		COSTI_MEDI.DESCRI,
		COSTI_MEDI.BASE_ADESIVO,
		COSTI_MEDI.UM_ACQ,
		COSTI_MEDI.COSTO AS COSTO_MEDIO ,
		COSTI_MEDI.UM_VEN,
		COALESCE(RICAVI_MEDI.VALORE_PRODUZIONE,0) AS VALORE_PRODUZIONE,
		CASE WHEN COALESCE(RICAVI_MEDI.QTA,0) >0 THEN COALESCE(RICAVI_MEDI.VALORE_PRODUZIONE,0) / COALESCE(RICAVI_MEDI.QTA,0) ELSE 0 END AS COSTO_PRODUZIONE,
		COALESCE(RICAVI_MEDI.QTA,0) AS QTA_VENDUTA,
		COALESCE(RICAVI_MEDI.VALORE,0) AS FATTURATO,
		COALESCE(RICAVI_MEDI.RICAVO,0) AS RICAVO_MEDIO,
		COALESCE((SELECT SUM(ORD_QTAORD) AS QTATOTM 
		FROM U_ORD_DD
		WHERE ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31'
			AND ORD_CODART=COSTI_MEDI.CODART
			AND ORD_QTAORD>0),0) AS QTATOT 
	FROM ( SELECT 
		CODART,
		DESCRI,
		BASE_ADESIVO,
		UM_ACQ,
		UM_VEN,
		SUM(QTA*COSTO_UNITARIO) AS COSTO
	FROM ( SELECT 
		CODART,
		DESCRI,
		BASE_ADESIVO,
		UM_ACQ,
		UM_VEN,
		COD_COMPONENTE,
		QTA,
		COSTO_MEDIO_MAGAZZINO AS COSTO_UNITARIO 
	FROM ( SELECT 
		DIS_GRUPPO AS CODART,
		ARTG.ART_DESCR AS DESCRI,
		ARTG.ART_BASADE AS BASE_ADESIVO,
		'KG' AS UM_ACQ,
		ARTG.ART_UMMAGA AS UM_VEN,
		DIS_CODART AS COD_COMPONENTE, 
		DIS_QTA AS QTA,
		COALESCE((SELECT AVG(CASE WHEN MOV_QTAMOV > 0 THEN MOV_VALACQ/MOV_QTAMOV ELSE 0 END) AS COSTO_MEDIO
				FROM U_MAG_MO
				WHERE MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31'
					AND MOV_ANAART=DIS.DIS_CODART 
					AND MOV_SEGNO='+'
					AND MOV_QTAMOV<>0
					AND MOV_VALACQ<>0),0) AS COSTO_MEDIO_MAGAZZINO 
	FROM U_DIS_DD AS DIS
	LEFT OUTER JOIN U_ART_PR AS ART
	ON DIS.DIS_CODART = ART.ART_CODPRI 
	INNER JOIN U_ART_PR AS ARTG
	ON DIS.DIS_GRUPPO = ARTG.ART_CODPRI 
	WHERE DIS.DIS_UM <>'NR' AND DIS.DIS_UM <>'ML'
--		 AND DIS.DIS_GRUPPO='A 0025'
		) AS COSTI_COMPONENTI ) AS COSTI
	GROUP BY CODART,BASE_ADESIVO,DESCRI,UM_ACQ,UM_VEN 
	 ) AS COSTI_MEDI
	LEFT OUTER JOIN (SELECT 
						ORD_CODART AS CODART, 
						SUM(ORD_QTAORD) AS QTA,
						SUM(ORD_VALORE) AS VALORE, 
						SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS RICAVO ,
						SUM(COSTO_PRODUZIONE*ORD_QTAORD) AS VALORE_PRODUZIONE 
					FROM (SELECT ORD_CODART,ORD_MAGA,ORD_QTAORD,ORD_VALORE , COALESCE((SELECT SUM(COSTO) AS COSTO FROM COSTI_PRODUZIONE WHERE STATO_LAV=ORD_MAGA GROUP BY STATO_LAV),0) AS COSTO_PRODUZIONE
							FROM U_FAT_DD 
							WHERE ORD_QTAORD>0 
								AND ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31') AS RICAVI
					GROUP BY ORD_CODART ) AS RICAVI_MEDI
	ON COSTI_MEDI.CODART = RICAVI_MEDI.CODART 
	ORDER BY COSTI_MEDI.CODART

