SELECT 
	SPACE(3) AS SELEZIONE, 
	PR.ART_CODPRI,
	PR.ART_DESCR,
	PR.ART_CODPRI,
	PR.ART_DESCR ,
	PR.ART_GRUPRD
FROM U_ART_PR AS PR 
LEFT OUTER JOIN U_ART_AN AS AN
ON AN.ART_CODPRI = PR.ART_CODPRI
WHERE PR.ART_CODMAT = '008' 
	AND (AN.ART_TIPOG <> '' 
	OR AN.ART_TIPON <> '' )
	AND LEN(LTRIM(RTRIM(PR.ART_CODPRI))) = 15 
	AND SUBSTRING(PR.ART_CODPRI,1,1) <> '#' 
	AND SUBSTRING(PR.ART_CODPRI,1,1) <> '*' 
	AND PR.ART_CODPRI NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT)
ORDER BY PR.ART_CODPRI 

