SELECT MOV_SYSPAG,* FROM INDICE WHERE MOV_NREGIS = '151       '
SELECT MOV_NUMPRO,* FROM MOV_CONT WHERE MOV_NREGIS = '151       '

SELECT MOV_SYSPAG,* FROM MOV_CONT WHERE  MOV_NUMPRO = '_3DX0XBIU1'
select GPP_SYSPAG,* from u_gpp_mo WHERE GPP_PAGATO = 'S'


UPDATE INDICE SET MOV_SYSPAG = '1234567890' where MOV_NUMPRO = '_3DX0XBIU1'
UPDATE MOV_CONT SET MOV_SYSPAG = '1234567890' where MOV_NUMPRO = '_3DX0XBIU1'
UPDATE u_gpp_mo SET GPP_SYSPAG = '1234567890' where GPP_PAGATO = 'S'

SELECT * FROM U_GPP_MO WHERE GPP_SYSPAG = '1234567890' ORDER BY GPP_MATRI

UPDATE u_gpp_mo SET GPP_SYSPAG = '' 
UPDATE u_gpp_mo SET GPP_PAGATO = '' 