
-------------------------------------------
--- ACCESSO PER ARTICOLO 
-------------------------------------------

--- (1) QUERY PER TROVARE GLI ARTICOLI CON GIACENZA NEGATIVA
--- ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * FROM (
SELECT 
	MOV_CODSOC AS MOV_CODSOC,
	MOV_ANAART AS MOV_ANAART,
	MOV_DESART AS MOV_DESART,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
FROM U_MAG_MO
WHERE MOV_TOP <> 'M++' AND MOV_TOP <> 'M--' AND MOV_DOCMOD = 0
GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC
WHERE MOV_QTAMOV <0 AND MOV_ANAART = 'TEST-GIAC'
ORDER BY MOV_ANAART


SELECT MOV_DTREGI,MOV_ORAMOV,MOV_QTAMOV,* from U_MAG_MO WHERE MOV_ANAART = 'TEST-GIAC'  ORDER BY MOV_DTREGI,MOV_ORAMOV

SELECT * from U_MAG_GG WHERE MAG_ANAART = 'TEST-GIAC'  ORDER BY MAG_ANAART
SELECT MAG_ANAART,* from U_MAG_GG ORDER BY MAG_ANAART

SELECT ART_SPESSO,ART_MAGA,* FROM U_ART_PR

SELECT * from U_MAG_GG WHERE MAG_GIACEN < 0  ORDER BY MAG_ANAART

DELETE from U_MAG_GG WHERE MAG_GIACEN < 0  

SELECT mov_legsys,* FROM U_MAG_MO WHERE (MOV_TOP = 'M++' or MOV_TOP = '001') and mov_codmat = '008'
order by mov_dtregi,mov_oramov

SELECT mov_legsys,count(*) as  conta_mov FROM U_MAG_MO WHERE (MOV_TOP = 'M++' or MOV_TOP = '001') and mov_codmat = '008'
and mov_docmod = 0
group by mov_legsys order by conta_mov desc
