
SELECT 
	T1.CODART,
	ART.ART_DESCR AS DESCRI,
	ART.ART_TIPART AS ART_TIPART,
	T1.UM,
	GIACENZA
FROM (SELECT MOV_ANAART AS CODART,MOV_UM AS UM,
	SUM((CASE WHEN MOV_SEGNO = '+' THEN 1 ELSE -1 END) *  MOV_QTAMOV ) AS GIACENZA 
FROM U_MAG_MO
WHERE MOV_QTAMOV<>0
AND MOV_ANAART NOT IN (SELECT DIT_GRUPPO FROM U_DIS_TT)
			AND RTRIM(MOV_ANAART)<>'.'
GROUP BY MOV_ANAART,MOV_UM) AS T1
LEFT OUTER JOIN U_ART_PR AS ART 
ON T1.CODART = ART.ART_CODPRI
WHERE GIACENZA <> 0 AND ART.ART_TIPART='P'
ORDER BY CODART
