SELECT 
	CODMAG,
	PARMAG.DESCRI AS DESMAG,
	CODART,
	ART.ART_DESCR AS DESCRI,
	ART.ART_BASADE AS BASE_ADESIVO,
	GIACENZA,
	COALESCE(CPROD.COSTO,0) AS COSTO_PROD
FROM (SELECT 
	MOV_CODMAG AS CODMAG,
	MOV_ANAART AS CODART,
	SUM((CASE WHEN MOV_SEGNO = '+' THEN 1 ELSE -1 END) *  MOV_QTAMOV ) AS GIACENZA 
FROM U_MAG_MO
WHERE MOV_QTAMOV<>0 AND (MOV_SEGNO ='+' OR MOV_SEGNO='-') 
AND	RTRIM(MOV_ANAART)<>'.'
GROUP BY MOV_ANAART,MOV_CODMAG 
) AS T1
LEFT OUTER JOIN U_ART_PR AS ART 
ON T1.CODART = ART.ART_CODPRI
LEFT OUTER JOIN PARA AS PARMAG
ON 'MAG'+RTRIM(T1.CODMAG) = PARMAG.CODICE
LEFT OUTER JOIN (SELECT STATO_LAV,SUM(COSTO) AS COSTO FROM COSTI_PRODUZIONE GROUP BY STATO_LAV) AS CPROD
ON T1.CODMAG = CPROD.STATO_LAV
WHERE GIACENZA <> 0 
ORDER BY CODART,CODMAG




SELECT COUNT(*) AS CONTA
FROM U_MAG_MO
WHERE MOV_QTAMOV<>0
AND	RTRIM(MOV_ANAART)<>'.'
AND (MOV_SEGNO ='+' OR MOV_SEGNO='-')
AND MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31'

