
-- NOTE:
-- 1) il campo VALORE è calcolato come somma di (MAG_GIACEN x MAG_PRZCON) calcolato su ogni singola riga di giacenza
--
-- 2) è possibile aggiungere qualunque campo di U_ART_PR nella select più esterna
-- indicandolo con il prefisso ART. (ad esempio ART.ART_LINEA, ART.ART_DESEST ecc...)

-- 3) CATEGORIA_ARTICOLO (VEDI MENU_ART000 --> DATI VARI --> TIPO PRODOTTO --> campo CATEGORIA)
--  BO = BOBINE 
--  AD = ADESIVI
--  MA = MANDRINI
--  PE = PEDANE
--  PA = PANNELLI
--  CG = CARTA GREZZA
--  CI = CARTA IMPREGNATA

SELECT * FROM (
SELECT 
	CASE 
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='1' THEN  'BO'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='2' THEN  'AD'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='3' THEN  'MA'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='4' THEN  'SC'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='5' THEN  'PE'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='6' THEN  'PA'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='7' THEN  'CG'
		WHEN COALESCE(SUBSTRING(MAT.LIBERA,1,1),'')='8' THEN  'CI'
		ELSE ART.ART_CODCAT
	END AS CATEGORIA_ARTICOLO,
	CASE 
		WHEN AAN.ART_TIPOG <>'' THEN 'G'
		WHEN AAN.ART_TIPON <>'' THEN 'N'
		ELSE 'X' 
	END AS TIPO_GN,
	AAN.art_tipog AS TIPO_G, 
	AAN.art_tipon AS TIPO_N,
	ART.ART_CODCOL,
	COALESCE(COL.DESCRI,'')  AS COLORE, 
	CASE 
		WHEN AAN.ART_TIPOG <>'' AND COALESCE(TIG.DESIVA,'')<>'' THEN COALESCE(TIG.DESIVA,'')
		WHEN AAN.ART_TIPOG <>'' AND COALESCE(TIG.DESIVA,'')='' THEN COALESCE(TIG.DESCRI,'')
		WHEN AAN.ART_TIPON <>'' AND COALESCE(TIN.DESIVA,'')<>'' THEN COALESCE(TIN.DESIVA,'')
		WHEN AAN.ART_TIPON <>'' AND COALESCE(TIN.DESIVA,'')='' THEN COALESCE(TIN.DESCRI,'')
		ELSE '' 
	END AS GRUPPO_PRODUTTIVO, 
	AAN.art_scelta AS SCELTA,
	GIA.MAG_CODMAG,
	ART.ART_CODPRI,
	ART.ART_DESCR,
	ART.ART_SPESSO,
	ART.ART_ALTEZZ,
	ART.ART_LUNGHE,	
	ART.ART_PRZCOS,
	ART.ART_PRZVEN,
	ART.ART_UNIMIS,
	GIA.MAG_GIACEN,
	GIA.VALORE,
	GIA.MAG_QTAIMP,
	CAST((0.00) AS NUMERIC (17,6)) AS MAG_QTAKG,
	CAST((0.00) AS NUMERIC (17,6)) AS MAG_QTAMQ,
	CAST((0.00) AS NUMERIC (17,6)) AS MAG_QTAML,
	CAST((0.00) AS NUMERIC (17,6)) AS MAG_QTAMC,
	CAST((0.00) AS NUMERIC (17,6)) AS MAG_QTANR,
	CAST((0.00) AS NUMERIC (17,6)) AS PRZ_MEDIO_MQ,
	CAST((0.00) AS NUMERIC (17,6)) AS PRZ_MEDIO_MC 
FROM ( SELECT 
		MAG_CODMAG,
		MAG_ANAART,
		SUM(MAG_GIACEN) AS MAG_GIACEN,
		SUM(MAG_GIACEN*MAG_PRZCON) AS VALORE,
		SUM(MAG_QTAIMP) AS MAG_QTAIMP
	FROM U_MAG_GG
    WHERE MAG_DATAGG <= '2012/08/14'
	GROUP BY MAG_CODMAG,MAG_ANAART) AS GIA 
LEFT OUTER JOIN U_ART_PR AS ART
ON GIA.MAG_ANAART = ART.ART_CODPRI
LEFT OUTER JOIN U_ART_AN AS AAN
ON ART.ART_CODSOC = AAN.ART_CODSOC AND ART.ART_CODPRI = AAN.ART_CODPRI 
LEFT OUTER JOIN PARA AS MAT
ON 'MAT'+ART.ART_CODMAT  = MAT.CODICE 
LEFT OUTER JOIN PARA AS COL
ON 'COL'+ART.ART_CODCOL  = COL.CODICE 
LEFT OUTER JOIN PARA AS TIG
ON 'TIG'+AAN.ART_TIPOG  = TIG.CODICE 
LEFT OUTER JOIN PARA AS TIN
ON 'TNO'+AAN.ART_TIPON  = TIN.CODICE 
WHERE 'PRD'+GIA.MAG_ANAART NOT IN (SELECT CODICE FROM PARA WHERE SUBSTRING(CODICE,1,3)='PRD') ) AS T1
WHERE CATEGORIA_ARTICOLO='PA'
ORDER BY MAG_CODMAG,ART_CODPRI

