
-------------------------------------------
--- ACCESSO PER ARTICOLO 
-------------------------------------------

--- (1) QUERY PER TROVARE GLI ARTICOLI CON GIACENZA NEGATIVA
--- ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * FROM (
SELECT 
	MOV_ANAART AS CODART,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
FROM U_MAG_MO
WHERE MOV_TOP <> 'M++' AND MOV_TOP <> 'M--' AND MOV_DOCMOD = 0
GROUP BY MOV_ANAART ) AS GIAC
WHERE MOV_QTAMOV <0
ORDER BY CODART

--- (2) QUERY PER TROVARE I MOVIMENTI DEGLI ARTICOLI OTTENUTI DALLA QUERY (1)
--- SEMPRE ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * 
FROM U_MAG_MO 
WHERE MOV_TOP <> 'M++' AND MOV_DOCMOD = 0
	AND  MOV_ANAART IN (
		SELECT CODART  FROM (
			SELECT 
				MOV_ANAART AS CODART,
				SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
			FROM U_MAG_MO
			WHERE MOV_TOP <> 'M++' AND MOV_DOCMOD = 0 
			GROUP BY MOV_ANAART) AS GIAC
			WHERE MOV_QTAMOV <0 ) 
ORDER BY MOV_ANAART,MOV_DTREGI,MOV_ORAMOV


-- 617.2740
-------------------------------------------
--- ACCESSO PER ARTICOLO + CODICE MAGAZZINO
-------------------------------------------

--- (1) QUERY PER TROVARE GLI ARTICOLI CON GIACENZA NEGATIVA
--- ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * FROM (
SELECT 
	MOV_ANAART AS CODART,
	MOV_CODMAG AS CODMAG,
	SUM(MOV_AQ_OC_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS AQ_OC_QTA
FROM U_MAG_MO
WHERE MOV_TOP <> 'M++'
GROUP BY MOV_ANAART,MOV_CODMAG ) AS GIAC
WHERE AQ_OC_QTA <0

--- (2) QUERY PER TROVARE I MOVIMENTI DEGLI ARTICOLI OTTENUTI DALLA QUERY (1)
--- SEMPRE ESCLUDENDO I MOVIMENTI DI CARICO FITTIZIO M++

SELECT * 
FROM U_MAG_MO 
WHERE MOV_TOP <> 'M++' 
	AND  MOV_ANAART IN (
		SELECT CODART  FROM (
			SELECT 
				MOV_ANAART AS CODART,
				MOV_CODMAG AS CODMAG,
				SUM(MOV_AQ_OC_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS AQ_OC_QTA
			FROM U_MAG_MO
			WHERE MOV_TOP <> 'M++'
			GROUP BY MOV_ANAART,MOV_CODMAG ) AS GIAC
			WHERE AQ_OC_QTA <0) 
ORDER BY MOV_DTDOCU,MOV_ORAMOV
