
/**** GRUPPO LISTINI PER TIPO GREZZO ****/
SELECT 
	SUBSTRING(TIG.CODICE,4,1) AS TIPO_GREZZO,
	SUBSTRING(GLI.CODICE,4,2) AS GRUPPO_LISTINO,
	GLI.DESCRI  
	FROM PARA AS TIG 
	LEFT OUTER JOIN PARA AS GLI
	ON LTRIM(TIG.LIBERA) = SUBSTRING(GLI.CODICE,4,2) 
WHERE 
	TIG.CODICE LIKE 'TIG%' 
	AND GLI.CODICE LIKE 'GLI%'

/**** GRUPPO LISTINI PER TIPO NOBILITATO ****/
SELECT 
	SUBSTRING(TIG.CODICE,4,1) AS TIPO_NOBILITATO,
	SUBSTRING(GLI.CODICE,4,2) AS GRUPPO_LISTINO,
	GLI.DESCRI  
	FROM PARA AS TIG 
	LEFT OUTER JOIN PARA AS GLI
	ON LTRIM(TIG.LIBERA) = SUBSTRING(GLI.CODICE,4,2) 
WHERE 
	TIG.CODICE LIKE 'TNO%' 
	AND GLI.CODICE LIKE 'GLI%'