IF EXISTS (SELECT name FROM sys.indexes
            WHERE name = N'CARICHI')
    DROP INDEX CARICHI ON U_MAG_MO;
GO

CREATE INDEX CARICHI ON U_MAG_MO ( MOV_DTDOCU,MOV_SEGNO,MOV_QTAMOV,MOV_VALACQ ) 


GO