/*
DELETE FROM L_BOL_TT
DELETE FROM L_BOL_DD ORDER BY LOG_TIPLOG
DELETE FROM L_BOL_LE
*/

SELECT * FROM L_BOL_TT

SELECT ORD_SEQUEN,* FROM L_BOL_DD WHERE LOG_DATLOG = '2009/10/29' AND LOG_ORALOG = '16:23:05' ORDER BY ORD_SEQUEN,log_tiplog

SELECT * FROM L_BOL_LE
