SELECT * FROM U_DIS_TT ORDER BY TAGGANCIO DESC
SELECT * FROM U_DIS_DD ORDER BY DAGGANCIO DESC

DELETE FROM U_DIS_TT WHERE TAGGANCIO <> '7000000227'
DELETE FROM U_DIS_DD WHERE DAGGANCIO <> '7000000227'