SELECT DIS_GRUPPO,DIS_CODART,DIS_TIPO,DIS_CODART,DIS_COSTO,DIS_QTA,DIS_COSLAI,DIS_COSLAE,DIS_COSMAT,DIS_COSATR,* FROM U_DIS_DD ORDER BY DIS_GRUPPO
SELECT DIT_GRUPPO,DIT_COSTO,DIT_COSLAI,DIT_COSLAE,DIT_COSMAT,DIT_COSATR,* FROM U_DIS_TT  ORDER BY DIT_GRUPPO

SELECT DIS_GRUPPO,DIS_CODART,DIS_TIPO,DIS_CODART,DIS_COSTO,DIS_QTA,DIS_COSLAI,DIS_COSLAE,DIS_COSMAT,DIS_COSATR,* FROM U_DIS_DD WHERE DAGGANCIO = '6000000062' ORDER BY DAGGANCIO
SELECT DIT_GRUPPO,DIT_COSTO,DIT_COSLAI,DIT_COSLAE,DIT_COSMAT,DIT_COSATR,* FROM U_DIS_TT  WHERE TAGGANCIO = '6000000062' ORDER BY TAGGANCIO



SELECT DIS_GRUPPO,DIS_TIPO,DIS_CODART,DIS_COSTO,DIS_QTA,DIS_COSLAI,DIS_COSLAE,DIS_COSMAT,DIS_COSATR,* FROM U_DIS_DD WHERE DIS_GRUPPO = 'M_1'
SELECT DIT_GRUPPO,DIT_COSTO,DIT_COSLAI,DIT_COSLAE,DIT_COSMAT,DIT_COSATR,* FROM U_DIS_TT  WHERE DIT_GRUPPO = 'M_1'