SELECT MAG_FILA_X,MAG_PIAN_X,MAG_UBIC_X,MAG_CODMAG,MAG_CODART,MAG_PRZCON,MAG_GIACEN,MAG_QTAMQ,MAG_QTAKG,MAG_QTAML,MAG_QTAIMP,MAG_NUMIDE,MAG_LEGSYS,MAG_LEGAME,MAG_UNIQUE,* FROM U_MAG_GG ORDER BY MAG_CODART
SELECT MOV_FILA_X,MOV_PIAN_X,MOV_UBIC_X,MOV_CODMAG,MOV_ORAMOV,MOV_CODART,MOV_ANAART,MOV_TOP,MOV_PREACQ,MOV_PREVEN,MOV_QTAMOV,MOV_QTAMQ,MOV_QTAKG,MOV_QTAML,MOV_LEGAME,MOV_LEGSYS,MOV_NUMIDE,MOV_UNIQUE,mov_tipart,* FROM U_MAG_MO ORDER BY MOV_CODART,MOV_ORAMOV

SELECT ORD_SEQUEN,ORD_QTAORD,ORD_QTAMQ,ORD_QTAKG,ORD_QTAML,ORD_LEGSYS,ORD_CODSYS,* FROM U_BOL_DD ORDER BY ORD_SEQUEN

SELECT ORD_LEGSYS,ORD_CODSYS,ORD_LEGASY,* FROM U_BFO_DD

SELECT  SUM(MOV_QTAMOV) AS SALDO_PIU
FROM U_MAG_MO
where MOV_SEGNO = '+'

SELECT  SUM(MOV_QTAMOV) AS SALDO_MENO
FROM U_MAG_MO
where MOV_SEGNO = '-'



SELECT MOV_NRLINT,MOV_CODMAT,MOV_DATSCA,MOV_NUMORF,MOV_CODART,MOV_ANAART,MOV_NRLINT,MOV_TOP,MOV_PREACQ,MOV_QTAMOV,MOV_QTAMQ,MOV_QTAKG,MOV_QTAML,MOV_LEGAME,MOV_LEGSYS,MOV_NUMIDE,MOV_UNIQUE,mov_tipart,* FROM U_MAG_MO WHERE MOV_LEGSYS = '_37P0CQBF9'

SELECT LEG_QUANTI,LEG_PRZCON,LEG_SYSBOL,LEG_SYSMAG,LEG_UNIQUE,* FROM U_BOL_LE
SELECT * FROM U_BOL_TT

SELECT * FROM L_BOL_TT
SELECT * FROM L_BOL_DD
SELECT * FROM L_BOL_LE

select * from para where codice LIKE 'NUMBOB%' ORDER BY CODICE
SELECT * FROM U_ART_PR

SELECT ORD_LEGSYS,ORD_CODSYS,* FROM U_ORF_DD

SELECT ORD_LEGSYS,ORD_CODSYS,ORD_LEGASY,* FROM U_BFO_DD
SELECT * FROM U_BFO_LE

UPDATE U_MAG_GG SET MAG_QTAIMP = 0 WHERE id_unique = 'F3E34991-06DA-4134-B411-761AFA6E0D09'
UPDATE U_MAG_MO SET MOV_LEGSYS = '_37P0EE5AW' WHERE id_unique = 'FC925410-E734-4677-801A-02206BEEBD41'

DELETE FROM U_MAG_MO WHERE id_unique = '7169223C-485F-49A5-8B00-4880ED2E130C'
DELETE FROM U_MAG_MO WHERE id_unique = '2B666FC8-31B9-43CC-8DA1-A1A7AB2BA53C'

DELETE FROM U_MAG_GG WHERE id_unique = 'ECB3F348-205F-48A8-8C01-EF3C3FD443CC'

UPDATE U_BOL_DD SET ORD_LEGSYS  = '_37P0FRXVJ' WHERE id_unique = 'C9560C35-15C5-4C24-BD54-6A723A468BA7'

UPDATE U_BOL_DD SET ORD_QTAORD = 100 WHERE id_unique = 'C9560C35-15C5-4C24-BD54-6A723A468BA7'
UPDATE U_BOL_DD SET ORD_QTAMQ  = 100 WHERE id_unique = 'C9560C35-15C5-4C24-BD54-6A723A468BA7'
UPDATE U_BOL_DD SET ORD_QTAKG  = 31 WHERE id_unique   = 'C9560C35-15C5-4C24-BD54-6A723A468BA7'
UPDATE U_BOL_DD SET ORD_QTAML  = 100 WHERE id_unique = 'C9560C35-15C5-4C24-BD54-6A723A468BA7'