SELECT * FROM UTENTIXRUOLI
SELECT * FROM ORGANIGRAMMA
SELECT * FROM AUTORIZZAZIONI
SELECT * from PARA where codice LIKE  'RUO%'


DELETE FROM UTENTIXRUOLI
DELETE FROM ORGANIGRAMMA
DELETE FROM AUTORIZZAZIONI
DELETE from PARA where codice LIKE  'RUO%'



