SELECT PAR_TIPFAT,par_tipodo,PAR_nprog,PAR_DTREG,PAR_DTFAT,PAR_DTSCAD,PAR_CODPAG,* FROM PART_CLI WHERE PAR_CODCLI = '1030000000167' ORDER BY PAR_NPART,PAR_NPROG
SELECT PAR_NPART,PAR_TIPFAT,par_tipodo,PAR_nprog,PAR_DTREG,PAR_DTFAT,PAR_DTSCAD,PAR_CODPAG,PAR_NUMFAT,* FROM PART_CLI WHERE PAR_CODCLI = '1030000000816' ORDER BY PAR_NPART,PAR_NPROG
select * from saldi_cli ORDER BY PAR_NPART

DELETE SALDI_CLI
DELETE SALDI_FOR
