SELECT ORD_VALORE,* FROM U_BOL_TT ORDER BY TAGGANCIO
SELECT ORD_NOTE,ORD_DESART,* FROM U_BOL_DD ORDER BY DAGGANCIO

SELECT ORD_EVAFOR,* FROM U_ORD_TT ORDER BY TAGGANCIO
SELECT ORD_DAPROD,ORD_DARIV,ORD_PRODOT,ORD_INPROD,ORD_TIPSOG,ORD_SALCON,ORD_QTAORD,ORD_QTAEV,ORD_QTADEV,ORD_CHIUSO,* FROM U_ORD_DD ORDER BY DAGGANCIO

