SELECT * FROM U_FAT_DD ORDER BY DAGGANCIO DESC
SELECT ORD_ALTEZZ,ORD_LUNGHE,ORD_NUMBOE,ORD_NUMBOD,ORD_QTAKG,ORD_QTAKGE,* FROM U_ORD_DD ORDER BY DAGGANCIO DESC
SELECT ORD_ALTEZZ,ORD_LUNGHE,ORD_QTAKG,ORD_QTAKGI,ORD_QTAKGE,* FROM U_BOL_DD ORDER BY DAGGANCIO DESC
SELECT ORD_ALTEZZ,ORD_LUNGHE,ORD_QTAKG,ORD_QTAKGI,ORD_QTAKGE,* FROM U_FAT_DD ORDER BY DAGGANCIO DESC
