/*** FORNITORI ***/
SELECT FO.FOR_RAGSOC AS RAGSOC,T2.*,AC3.FLAG,AC3.SALDO FROM ( 
SELECT 
	PAR_CODCLI AS CODFOR,
	PAR_NPART AS NPART,
	PAR_DTSCAD AS DTSCAD, 
	SUM(DARE) AS NDARE,
	SUM(AVERE) AS NAVERE,
	SUM(DARE)-SUM(AVERE) AS NSALDO
FROM (
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	PAR_DTSCAD, 
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_FOR
WHERE PAR_NPROG <> '100' ) AS T1
GROUP BY PAR_CODCLI,PAR_NPART,PAR_DTSCAD) AS T2
LEFT OUTER JOIN U_FOR_AN AS FO
ON SUBSTRING(T2.CODFOR,5,len(T2.CODFOR))=FO.FOR_CODCLI 
LEFT OUTER JOIN (
SELECT *, CASE WHEN SALDO=0 THEN 'CHIUSA' ELSE 'APERTA' END AS FLAG FROM ( 
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO
FROM (
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_FOR
WHERE PAR_NPROG <> '100' ) AS AC1
GROUP BY PAR_CODCLI,PAR_NPART) AS AC2 ) AS AC3
ON  T2.CODFOR=AC3.PAR_CODCLI
WHERE T2.CODFOR='1010200000010'  AND T2.NPART =  75387
ORDER BY CODFOR,NPART,DTSCAD 





/*

SELECT *, CASE WHEN SALDO=0 THEN 'CHIUSA' ELSE 'APERTA' END AS FLAG FROM ( 
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO
FROM (
SELECT 
	PAR_CODCLI,
	PAR_NPART,
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_FOR
WHERE PAR_NPROG <> '100' ) AS AC1
GROUP BY PAR_CODCLI,PAR_NPART) AS AC2 
ORDER BY PAR_CODCLI,PAR_NPART


*/














