select  MOV_TOP,MOV_NREGIS,MOV_NUMPRO,MOV_IMP,* from mov_cont where mov_top = 'VEN' ORDER BY MOV_NUMPRO

select  MOV_NUMPRO,MOV_CONTO,MOV_TOP,MOV_NREGIS,MOV_NPROT,MOV_IMP,* from mov_cont where mov_top = 'VEN' AND LEN(MOV_CONTO) <> 13 AND MOV_IMPOST <> 0 AND MOV_CONTO <> '6010101' ORDER BY MOV_NUMPRO
    
select MOV_TOP,MOV_NREGIS,MOV_NUMPRO,MOV_IMP,* from mov_cont where mov_nregis = '279047'

select  MOV_NUMPRO,MOV_CONTO,MOV_TOP,MOV_NREGIS,MOV_NPROT,MOV_IMP,* from mov_cont where mov_top = 'VEN' AND LEN(MOV_CONTO) <> 13 AND MOV_IMPOST <> 0 AND MOV_CONTO <> '6010101' ORDER BY MOV_NUMPRO

select  MOV_NPROT,MOV_DTDOC,MOV_CONTO,MOV_TOP,MOV_NREGIS,MOV_IMP,* from mov_cont where mov_top = 'VEN' AND LEN(MOV_CONTO) <> 13 AND MOV_IMPOST <> 0 ORDER BY MOV_NPROT

select  MOV_NPROT,MOV_DTDOC,MOV_CONTO,MOV_TOP,MOV_NREGIS,MOV_IMP,* from mov_cont where mov_top = 'VEN' AND LEN(MOV_CONTO) = 13  ORDER BY MOV_NPROT



