SELECT FPR_QTAUCA,* FROM U_FOR_PR ORDER BY FPR_CODART
SELECT MOV_CODMAG,MOV_CODART,MOV_TOP,MOV_QTAMOV,* FROM U_MAG_MO ORDER BY MOV_CODART
SELECT MAG_CODMAG,MAG_CODART,MAG_GIACEN,MAG_QTAIMP,* FROM U_MAG_AN ORDER BY MAG_CODART
SELECT MAG_CODMAG,MAG_CODART,MAG_GIACEN,MAG_QTAIMP,* FROM U_MAG_GG ORDER BY MAG_CODART



SELECT * FROM U_VEN_CL ORDER BY VEN_CODART
SELECT * FROM U_BFO_DD
