SELECT  ART_CODPRI,
		ROUND((ART_PESOUM * ROUND((ART_SPESSO / 1000),3)),5) AS KG_DA_MQ
FROM ( SELECT 
	ART.ART_CODPRI,
	CASE WHEN GRP.ART_SPESSO =0 THEN 10 ELSE COALESCE(GRP.ART_SPESSO,10) END AS ART_SPESSO,
	CASE WHEN GRP.ART_PESOUM =0 THEN 0.922 ELSE COALESCE(GRP.ART_PESOUM,0.922) END AS ART_PESOUM 
FROM U_ART_PR AS ART
LEFT OUTER JOIN U_ART_PR AS GRP
ON GRP.ART_CODPRI=ART.ART_GRUPRD
WHERE ART.ART_CODPRI IN (SELECT DIT_GRUPPO FROM U_DIS_TT) ) AS CONV

