	SELECT TOP 1 ART_CODCAT,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_ALTEZZ,ART_LUNGHE , 1/(ART_ALTEZZ*ART_LUNGHE/1000000) AS  SUPERFICIE
	FROM U_ART_PR 
	WHERE ART_CODCAT = 'CI' AND ART_CODCOL='U12'
	AND ART_ALTEZZ IN (SELECT CLA.LIBERA+10 AS LARGHEZZA
		FROM U_ART_PR AS PR
		LEFT OUTER JOIN U_ART_AN AS AN
		ON AN.ART_CODPRI=PR.ART_CODPRI
		LEFT OUTER JOIN PARA AS CLA
		ON 'CLA'+SUBSTRING(PR.ART_CODPRI,4,2) = CLA.CODICE
		LEFT OUTER JOIN PARA AS CLU
		ON 'CLU'+SUBSTRING(PR.ART_CODPRI,6,2) = CLU.CODICE
		WHERE PR.ART_CODPRI ='I50A4B3U12U12C1' ) 
	AND ART_LUNGHE IN (SELECT CLU.LIBERA+10 AS LUNGHEZZA 
		FROM U_ART_PR AS PR
		LEFT OUTER JOIN U_ART_AN AS AN
		ON AN.ART_CODPRI=PR.ART_CODPRI
		LEFT OUTER JOIN PARA AS CLA
		ON 'CLA'+SUBSTRING(PR.ART_CODPRI,4,2) = CLA.CODICE
		LEFT OUTER JOIN PARA AS CLU
		ON 'CLU'+SUBSTRING(PR.ART_CODPRI,6,2) = CLU.CODICE
		WHERE PR.ART_CODPRI ='I50A4B3U12U12C1' ) 
	ORDER BY ART_CODPRI


SELECT ART_CODCAT,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_ALTEZZ,ART_LUNGHE , 1/(ART_ALTEZZ*ART_LUNGHE/1000000) AS  SUPERFICIE
FROM U_ART_PR WHERE ART_CODCAT = 'CI' AND ART_CODCOL='U12'