/* IMPOSTA GLI ORDINI CLIENTE COME "NON IN PRODUZIONE" */
UPDATE U_ORD_DD SET ORD_INPROD = 0


/* CANCELLA TABELLE PRODUZIONE */
DELETE FROM U_PRD_D1
DELETE FROM U_PRD_D2
DELETE FROM U_PRD_D3
DELETE FROM U_PRD_D4
DELETE FROM U_PRD_D5
DELETE FROM U_PRD_DR


----UPDATE U_MAG_GG SET MAG_PRENOT = 0 WHERE MAG_CODART>'AM 514.68110043'
--UPDATE U_MAG_GG SET MAG_PRENOT = 0 WHERE MAG_LUNGHE<8000 
 

UPDATE U_MAG_GG SET MAG_PRENOT = 0


/* CANCELLA TABELLE MAGAZZINO PER PRODUZIONE */
DELETE FROM U_MAG_AN
DELETE FROM U_MAG_AR
DELETE FROM U_MAG_CA
DELETE FROM U_MAG_CL
DELETE FROM U_MAG_CP
DELETE FROM U_MAG_DA
DELETE FROM U_MAG_DF
DELETE FROM U_MAG_DM
DELETE FROM U_MAG_DM 
DELETE FROM U_MAG_GG
DELETE FROM U_MAG_GS
DELETE FROM U_MAG_IN
DELETE FROM U_MAG_MA
DELETE FROM U_MAG_MF
DELETE FROM U_MAG_MO
DELETE FROM U_MAG_MS
DELETE FROM U_MAG_PR
DELETE FROM U_MAG_RI
DELETE FROM U_MAG_SA
DELETE FROM U_MAG_SS


