/***************************************************
FATTURE TOTALI EMESSE AL NETTO DELLE NOTE DI CREDITO
***************************************************/
SELECT SUM(DARE-AVERE) AS FATTURATO_TOTALE FROM (
SELECT *,
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_CLI 
WHERE PAR_NPROG<>100 
	AND (PAR_TIPFAT='CF1' OR PAR_TIPFAT='VEN' OR PAR_TIPFAT='CN1' )
	AND PAR_DTFAT BETWEEN '2012/01/01' AND '2012/04/15' 
) AS PC



/***************************************************
FATTURE EMESSE CON CPA NON-RIBA
(AL NETTO DELLE NOTE DI CREDITO) 
***************************************************/
SELECT SUM(DARE-AVERE) AS FATTURATO_NO_RIBA FROM (
	SELECT 	PA.PAR_TIPFAT  AS TIPOOPE ,
			COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA ,
			COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA_TOP ,
			COALESCE(SUBSTRING(PAR.LIBERA,10,1),'')  AS FLAG_RIBA,
			PA.* ,
			CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
			CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
	FROM PART_CLI AS PA 
	LEFT OUTER JOIN PARA AS PAR
	ON PAR.CODICE='CPA'+PA.PAR_CODPAG 
	LEFT OUTER JOIN PARA AS PARTOP
	ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT 
	WHERE PAR_NPROG<>100
		AND (PAR_TIPFAT='CF1' OR PAR_TIPFAT='VEN' OR PAR_TIPFAT='CN1') 
		AND PAR_DTFAT BETWEEN '2012/01/01' AND '2012/04/15' 
 ) AS PC 
WHERE FLAG_RIBA <>'X'



/***************************************************
TOTALE RICEVUTE BANCARIE EMESSE
***************************************************/
SELECT SUM(PAR_FATT) AS RICEVUTE_EMESSE FROM (
   		SELECT 	COALESCE(CL.CLI_RAGSOC,PA.PAR_RAGSOC) AS CLI_RAGSOC,
   				COALESCE(CL.CLI_CAP,'') AS CLI_CAP,
   				COALESCE(CL.CLI_INDIR,'') AS CLI_INDIR,
   				COALESCE(CL.CLI_LOCALI,'') AS CLI_LOCALI,
   				COALESCE(CL.CLI_AGE,'') AS CLI_AGE,
   				COALESCE(CL.CLI_AGE,'') AS AGENTE,
				PA.PAR_TIPFAT  AS TIPOOPE ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA_TOP ,
				COALESCE(SUBSTRING(PAR.LIBERA,10,1),'')  AS FLAG_RIBA,
   				PA.* 
   		FROM PART_CLI AS PA 
   		LEFT OUTER JOIN U_CLI_AN AS CL 	
   		ON SUBSTRING(PA.PAR_CODCLI,6,LEN(PA.PAR_CODCLI))=CL.CLI_CODCLI 
   		LEFT OUTER JOIN PARA AS PAR
   		ON PAR.CODICE='CPA'+PA.PAR_CODPAG 
   		LEFT OUTER JOIN PARA AS PARTOP
   		ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
   		WHERE PAR_CODSOC = '01'
	        AND PAR_NPROG <> 100 
			AND PAR_DTFAT BETWEEN '2012/01/01' AND '2012/04/15' 
 ) AS PC 
WHERE FLAG_RIBA_TOP ='S' 




/***************************************************
TOTALE INSOLUTI RICEVUTI
***************************************************/
SELECT SUM(PAR_FATT) AS INSOLUTI_RICEVUTI FROM (
   		SELECT 	COALESCE(CL.CLI_RAGSOC,PA.PAR_RAGSOC) AS CLI_RAGSOC,
   				COALESCE(CL.CLI_CAP,'') AS CLI_CAP,
   				COALESCE(CL.CLI_INDIR,'') AS CLI_INDIR,
   				COALESCE(CL.CLI_LOCALI,'') AS CLI_LOCALI,
   				COALESCE(CL.CLI_AGE,'') AS CLI_AGE,
   				COALESCE(CL.CLI_AGE,'') AS AGENTE,
				PA.PAR_TIPFAT  AS TIPOOPE ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA_TOP ,
				COALESCE(SUBSTRING(PAR.LIBERA,10,1),'')  AS FLAG_RIBA,
   				PA.* 
   		FROM PART_CLI AS PA 
   		LEFT OUTER JOIN U_CLI_AN AS CL 	
   		ON SUBSTRING(PA.PAR_CODCLI,6,LEN(PA.PAR_CODCLI))=CL.CLI_CODCLI 
   		LEFT OUTER JOIN PARA AS PAR
   		ON PAR.CODICE='CPA'+PA.PAR_CODPAG 
   		LEFT OUTER JOIN PARA AS PARTOP
   		ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
   		WHERE PAR_CODSOC = '01'
	        AND PAR_NPROG <> 100 
			AND PAR_DTFAT BETWEEN '2012/01/01' AND '2012/04/15' 
 ) AS PC 
WHERE FLAG_NATURA='I' 




/***************************************************
TOTALE ALTRI PAGAMENTI
***************************************************/
SELECT SUM(PAR_FATT) AS ALTRI_PAGAMENTI FROM (
   		SELECT 	COALESCE(CL.CLI_RAGSOC,PA.PAR_RAGSOC) AS CLI_RAGSOC,
   				COALESCE(CL.CLI_CAP,'') AS CLI_CAP,
   				COALESCE(CL.CLI_INDIR,'') AS CLI_INDIR,
   				COALESCE(CL.CLI_LOCALI,'') AS CLI_LOCALI,
   				COALESCE(CL.CLI_AGE,'') AS CLI_AGE,
   				COALESCE(CL.CLI_AGE,'') AS AGENTE,
				PA.PAR_TIPFAT  AS TIPOOPE ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,2,1),'')  AS FLAG_NATURA ,
				COALESCE(SUBSTRING(PARTOP.LIBERA,10,1),'')  AS FLAG_RIBA_TOP ,
				COALESCE(SUBSTRING(PAR.LIBERA,10,1),'')  AS FLAG_RIBA,
   				PA.* 
   		FROM PART_CLI AS PA 
   		LEFT OUTER JOIN U_CLI_AN AS CL 	
   		ON SUBSTRING(PA.PAR_CODCLI,6,LEN(PA.PAR_CODCLI))=CL.CLI_CODCLI 
   		LEFT OUTER JOIN PARA AS PAR
   		ON PAR.CODICE='CPA'+PA.PAR_CODPAG 
   		LEFT OUTER JOIN PARA AS PARTOP
   		ON PARTOP.CODICE='TOP'+PA.PAR_TIPFAT  
   		WHERE PAR_CODSOC = '01'
	        AND PAR_NPROG <> 100 
			AND PAR_DTFAT BETWEEN '2012/01/01' AND '2012/04/15' 
 ) AS PC 
WHERE FLAG_NATURA='P' AND FLAG_RIBA_TOP <>'S'



---SELECT * FROM PART_CLI WHERE LTRIM(LEN(PAR_DTSCAD))<10

-- CORREZIONE PARTITA ESTERA CON CONTO ITALIA
--SELECT * FROM PART_CLI WHERE PAR_NPART=120998
--UPDATE  PART_CLI SET PAR_CODCLI='1010300001959' WHERE PAR_NPART=120998