DELETE FROM U_MAG_GG WHERE MAG_GIACEN < 0
	
--TUTTE LE GIACENZE NEGATIVE PRESENTI IN DDT

SELECT * FROM (
	SELECT 
		MOV_CODSOC AS MOV_CODSOC,
		MOV_ANAART AS MOV_ANAART,
		MOV_DESART AS MOV_DESART,
		SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
	FROM U_MAG_MO
	WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')
	GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC 
	ORDER BY MOV_ANAART


--TUTTE LE GIACENZE NEGATIVE PRESENTI IN DDT A PARTIRE 

SELECT * FROM (
	SELECT 
		MOV_CODSOC AS MOV_CODSOC,
		MOV_ANAART AS MOV_ANAART,
		MOV_DESART AS MOV_DESART,
		SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
	FROM U_MAG_MO
	WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')
	GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC 
	ORDER BY MOV_ANAART



-- SINGOLO ARTICOLO

	SELECT * FROM (
		SELECT 
			MOV_CODSOC AS MOV_CODSOC,
			MOV_ANAART AS MOV_ANAART,
			MOV_DESART AS MOV_DESART,
			SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV,
			SUM(MOV_QTANR * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTANR
		FROM U_MAG_MO
		WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')  AND MOV_ANAART = '135A2B300000001'
		GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC 
		ORDER BY MOV_ANAART

--DETTAGLI DEL SINGOLO ARTICOLO

	SELECT 	ID_UNIQUE,MOV_CODMAG,MOV_CODART,MOV_QTAMOV,MOV_QTANR FROM U_MAG_MO
		WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')  AND MOV_ANAART = '135A2B300000001'
		ORDER BY MOV_ANAART

--TUTTI I DETTAGLI

	SELECT 	ID_UNIQUE,MOV_CODMAG,MOV_CODART,MOV_QTAMOV,MOV_QTANR FROM U_MAG_MO
		WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')   
		ORDER BY MOV_ANAART







SELECT * FROM (
	SELECT 
		MOV_CODSOC AS MOV_CODSOC,
		MOV_ANAART AS MOV_ANAART,
		MOV_DESART AS MOV_DESART,
		SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV,
		COUNT(*) AS NRECORDS
	FROM U_MAG_MO
	WHERE MOV_TOP = 'M++' AND MOV_DOCMOD = 0 AND MOV_ANAART IN (SELECT MOV_ANAART FROM U_MAG_MO WHERE MOV_TOP = '001')
	GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC 
	ORDER BY NRECORDS DESC,MOV_ANAART