SELECT * FROM RDA_TT ORDER BY NUMERO DESC
SELECT * FROM RDA_DD  

DELETE FROM RDA_TT WHERE TAGGANCIO <> '_3JA0IPJSR'

DELETE FROM RDA_DD WHERE DAGGANCIO <> '_3JA0IPJSR'

UPDATE RDA_TT SET numero    = '000999' WHERE TAGGANCIO = '_3JA0IPJSR'
