DELETE U_AGE_AN
DELETE U_CLI_AN
DELETE U_FOR_AN
DELETE U_BAN_AN
DELETE U_LOC_AN
DELETE U_ART_PR
DELETE U_ORD_TT
DELETE U_ORD_DD
DELETE U_ORF_TT
DELETE U_ORF_DD
DELETE U_BOL_TT
DELETE U_BOL_DD
DELETE U_FAT_TT
DELETE U_FAT_DD

DELETE CONTI
DELETE INDICE
DELETE MOV_CONT
DELETE PART_CLI
DELETE PART_FOR
DELETE CCOSTO
DELETE MOV_CCO



DELETE U_IVA_CL
DELETE U_IVF_CL
DELETE U_IVA_TO
DELETE U_IVA_CO
DELETE U_IVA_CR


DELETE U_PRD_D1
DELETE U_PRD_D2
DELETE U_PRD_D3
DELETE U_PRD_D4
DELETE U_PRD_D5
DELETE U_PRD_DR
DELETE U_PRD_HY


DELETE FROM CLIENTIC
DELETE FROM COMMESSA_DP
DELETE FROM COMMESSA_DC
DELETE FROM COMMESSA_TT
DELETE FROM TIMESHT
DELETE FROM FATTURABILE_R
DELETE FROM FATTURABILE_A
DELETE FROM FATTURABILE_P
DELETE FROM FATTURABILE_S
DELETE FROM FATTURABILE_X
DELETE FROM PIANIFIC_COMM
DELETE FROM TIPOORA
DELETE FROM DETTORA
DELETE FROM BUDGET_PREV
DELETE FROM BUDGET_CONS



DELETE FROM RISUMANA

DELETE FROM BUDGETPC
DELETE FROM AULA

DELETE FROM FATTURABILE


DELETE FROM U_MAG_AN
DELETE FROM U_MAG_AR
DELETE FROM U_MAG_CA
DELETE FROM U_MAG_CL
DELETE FROM U_MAG_CP
DELETE FROM U_MAG_DA
DELETE FROM U_MAG_DF
DELETE FROM U_MAG_DM
DELETE FROM U_MAG_DM 
DELETE FROM U_MAG_GG
DELETE FROM U_MAG_GS
DELETE FROM U_MAG_IN
DELETE FROM U_MAG_MA
DELETE FROM U_MAG_MF
DELETE FROM U_MAG_MO
DELETE FROM U_MAG_MS
DELETE FROM U_MAG_PR
DELETE FROM U_MAG_RI
DELETE FROM U_MAG_SA
DELETE FROM U_MAG_SS

DELETE FROM U_BFO_TT
DELETE FROM U_BFO_DD
DELETE FROM U_BFO_LE
DELETE FROM U_BFO_DL

DELETE FROM U_ORD_TT
DELETE FROM U_ORD_DD

DELETE FROM U_ORF_TT
DELETE FROM U_ORF_DD

DELETE FROM U_BOL_TT
DELETE FROM U_BOL_DD
DELETE FROM U_BOL_LE
DELETE FROM U_BOL_RE


DELETE FROM U_VEN_CL

DELETE FROM U_FOR_PR

DELETE FROM U_FAB_CL

DELETE FROM U_AVA_CO
DELETE FROM U_AVA_MQ
DELETE FROM U_AVA_RI
DELETE FROM U_AVA_SM
DELETE FROM U_AVA_SP
DELETE FROM U_AVA_TG

DELETE FROM U_PRG_CL
DELETE FROM U_PRG_DL
DELETE FROM U_PRG_DO
DELETE FROM U_PRG_LT
DELETE FROM U_PRG_RA
DELETE FROM U_PRG_RI
DELETE FROM U_PRG_RR
DELETE FROM U_PRG_RT
DELETE FROM U_PRG_SM
DELETE FROM U_PRG_SP
DELETE FROM U_PRG_TG

DELETE FROM U_PRO_IM


DELETE U_STC_AN










