	
SELECT * FROM U_MAG_GG


	SELECT MAG_GIACEN,MAG_LEGSYS,MAG_LEGAME,* FROM U_MAG_GG 
	WHERE   MAG_DATAGG BETWEEN '2012/01/01' AND '2012/12/31'  AND
			MAG_DATAGG <> ''	AND 
			MAG_ANAART = 'TEST-GIAC2'


	SELECT  MOV_GIANEG,MOV_QTAMOV,MOV_DTREGI,MOV_ORAMOV,MOV_TOP,MOV_SEGNO,MOV_NUMDOC,MOV_LEGSYS,MOV_LEGAME,mov_fornit,* FROM U_MAG_MO
	WHERE   MOV_DTREGI BETWEEN '2012/01/01' AND '2012/12/31'  AND
			MOV_DTREGI <> ''	AND 
			MOV_ANAART = 'TEST-GIAC2'
	ORDER BY MOV_DTREGI,MOV_ORAMOV

	SELECT MOV_DTREGI,MOV_ORAMOV,* FROM U_MAG_MO	WHERE  MOV_ANAART = 'TEST-GIAC2' ORDER BY MOV_DTREGI,MOV_ORAMOV 


UPDATE U_MAG_MO SET MOV_GIANEG = 0 WHERE ID_UNIQUE = 'E5FAA68C-3B56-41DA-9937-C36235E06506'

DELETE FROM U_MAG_GG WHERE 	MAG_ANAART = 'TEST-GIAC'
DELETE FROM U_MAG_GG WHERE 	MAG_ANAART = 'TEST-GIAC1'



DELETE FROM U_MAG_MO WHERE 	MOV_ANAART = 'TEST-GIAC'
DELETE FROM U_MAG_MO WHERE 	MOV_ANAART = 'TEST-GIAC1'

DELETE FROM U_MAG_GG WHERE 	MAG_ANAART = 'TEST-GIAC2'
DELETE FROM U_MAG_MO WHERE 	MOV_ANAART = 'TEST-GIAC2'
