SELECT 
	PAR_RAGSOC,
	PAR_CODCLI,
	PAR_NPART,
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO,
	CASE WHEN (SUM(DARE)-SUM(AVERE))=0 THEN 'CHIUSA' ELSE 'APERTA' END AS FLAG 
FROM (
SELECT 
	PAR_RAGSOC,
	PAR_CODCLI,
	PAR_NPART,
	CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
	CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_CLI 
WHERE PAR_NPROG <> '100' ) AS AC
--- per cercare una partitia specifica
--- WHERE PAR_CODCLI ='2110100000052' AND PAR_NPART=101535
GROUP BY PAR_CODCLI,PAR_RAGSOC,PAR_NPART 
UNION (
SELECT 
	'   TOTALE' AS PAR_RAGSOC,
	'0000000000000' AS PAR_CODCLI,
	0 AS PAR_NPART,
	SUM(DARE) AS DARE,
	SUM(AVERE) AS AVERE,
	SUM(DARE)-SUM(AVERE) AS SALDO,
	'' AS FLAG
FROM (
SELECT 
		PAR_RAGSOC,
		PAR_CODCLI,
		PAR_NPART,
		CASE WHEN  PAR_TMOV = 'D' THEN PAR_FATT ELSE 0 END AS DARE,
		CASE WHEN  PAR_TMOV = 'A' THEN PAR_FATT ELSE 0 END AS AVERE
FROM PART_CLI 
WHERE PAR_NPROG <> '100' ) AS AC1 ) 
ORDER BY PAR_RAGSOC, PAR_CODCLI, PAR_NPART
	
