
SELECT CLI_01DAL,CLI_01AL,CLI_01GG,* FROM U_CLI_AN
SELECT CLI_BDAL,CLI_BAL,CLI_GG1,* FROM U_CLI_AN
       


UPDATE U_CLI_AN SET  CLI_01DAL = ''
UPDATE U_CLI_AN SET  CLI_02DAL = ''
UPDATE U_CLI_AN SET  CLI_03DAL = ''
UPDATE U_CLI_AN SET  CLI_04DAL = ''
UPDATE U_CLI_AN SET  CLI_05DAL = ''
UPDATE U_CLI_AN SET  CLI_06DAL = ''
UPDATE U_CLI_AN SET  CLI_07DAL = ''
UPDATE U_CLI_AN SET  CLI_BDAL  = ''
UPDATE U_CLI_AN SET  CLI_09DAL = ''
UPDATE U_CLI_AN SET  CLI_10DAL = ''
UPDATE U_CLI_AN SET  CLI_11DAL = ''
UPDATE U_CLI_AN SET  CLI_B2DAL = ''

UPDATE U_CLI_AN SET  CLI_01AL = ''
UPDATE U_CLI_AN SET  CLI_02AL = ''
UPDATE U_CLI_AN SET  CLI_03AL = ''
UPDATE U_CLI_AN SET  CLI_04AL = ''
UPDATE U_CLI_AN SET  CLI_05AL = ''
UPDATE U_CLI_AN SET  CLI_06AL = ''
UPDATE U_CLI_AN SET  CLI_07AL = ''
UPDATE U_CLI_AN SET  CLI_BAL  = ''
UPDATE U_CLI_AN SET  CLI_09AL = ''
UPDATE U_CLI_AN SET  CLI_10AL = ''
UPDATE U_CLI_AN SET  CLI_11AL = ''
UPDATE U_CLI_AN SET  CLI_B2AL = ''

UPDATE U_CLI_AN SET  CLI_01GG = ''
UPDATE U_CLI_AN SET  CLI_02GG = ''
UPDATE U_CLI_AN SET  CLI_03GG = ''
UPDATE U_CLI_AN SET  CLI_04GG = ''
UPDATE U_CLI_AN SET  CLI_05GG = ''
UPDATE U_CLI_AN SET  CLI_06GG = ''
UPDATE U_CLI_AN SET  CLI_07GG = ''
UPDATE U_CLI_AN SET  CLI_GG1  = ''
UPDATE U_CLI_AN SET  CLI_09GG = ''
UPDATE U_CLI_AN SET  CLI_10GG = ''
UPDATE U_CLI_AN SET  CLI_11GG = ''
UPDATE U_CLI_AN SET  CLI_GG2  = ''
