
SELECT CLI_VALUTA,* FROM U_CLI_AN WHERE CLI_VALUTA = ''
UPDATE U_CLI_AN SET CLI_VALUTA = 'EUR' where CLI_VALUTA = ''


SELECT FOR_VALUTA,* FROM U_FOR_AN WHERE FOR_VALUTA = ''
UPDATE U_FOR_AN SET FOR_VALUTA = 'EUR' where FOR_VALUTA = ''

SELECT ORD_VALUTA , ORD_DATORD,ORD_NUMORD,* FROM U_FAT_TT WHERE ORD_VALUTA <> 'EUR'
SELECT ORD_VALUTA , ORD_DATORD,ORD_NUMORD,* FROM U_BOL_TT WHERE ORD_VALUTA <> 'EUR'
SELECT ORD_VALUTA , ORD_DATORD,ORD_NUMORD,* FROM U_ORD_TT WHERE ORD_VALUTA <> 'EUR'


UPDATE U_BOL_TT SET ORD_VALUTA = 'EUR' where ORD_VALUTA = 'ITL'




UPDATE U_ORD_TT SET ORD_VALUTA = 'EUR' where ORD_VALUTA = 'ITL'




