
--CODICE NAZIONE INESISTENTE
SELECT CLI_NAZION,* FROM U_CLI_AN WHERE CLI_NAZION = ''
UPDATE U_CLI_AN SET CLI_NAZION = 'IT'  WHERE CLI_NAZION = ''
SELECT ORD_CODNAZ,* FROM U_FAT_TT WHERE ORD_CODNAZ = ''
UPDATE U_FAT_TT SET ORD_CODNAZ = 'IT'  WHERE ORD_CODNAZ = ''

--CODICE NAZIONE ITA
SELECT CLI_NAZION,* FROM U_CLI_AN WHERE CLI_NAZION = 'ITA'
UPDATE U_CLI_AN SET CLI_NAZION = 'IT'  WHERE CLI_NAZION = 'ITA'
SELECT ORD_CODNAZ,* FROM U_FAT_TT WHERE ORD_CODNAZ = 'ITA'
UPDATE U_FAT_TT SET ORD_CODNAZ = 'IT'  WHERE ORD_CODNAZ = 'ITA'

--VERIFICA E AGGIORNA NAZIONE PER ALCUNI CLIENTI SU U_FAT_TT
SELECT ORD_CODNAZ,ORD_CODCLI,ORD_RAGSOC,* FROM U_FAT_TT WHERE ORD_NUMORD = '000220'
UPDATE U_FAT_TT SET ORD_CODNAZ = 'EL'  WHERE ID_UNIQUE = 'DD0AD6B2-C478-452C-9FF2-F131E65BF1B5'

SELECT ORD_CODNAZ,ORD_CODCLI,ORD_RAGSOC,* FROM U_FAT_TT WHERE ORD_NUMORD = '000221'
UPDATE U_FAT_TT SET ORD_CODNAZ = 'EL'  WHERE ID_UNIQUE = 'E7EACEA9-7C29-4891-BD99-AAEB7EE39A7B'

SELECT ORD_CODNAZ,ORD_CODCLI,ORD_RAGSOC,* FROM U_FAT_TT WHERE ORD_NUMORD = '000301'
UPDATE U_FAT_TT SET ORD_CODNAZ = 'EL'  WHERE ID_UNIQUE = 'E5026919-CED7-47FF-AD1B-F660CD9A6A8E'

SELECT ORD_CODNAZ,ORD_CODCLI,ORD_RAGSOC,* FROM U_FAT_TT WHERE ORD_NUMORD = '000302'
UPDATE U_FAT_TT SET ORD_CODNAZ = 'SK'  WHERE ID_UNIQUE = '102ED87C-FF26-42BF-9278-788F04F957FD'