
SELECT T_MOV.ARTICOLO, U_ART_PR.ART_DESCR AS DESCRIZIONE, T_MOV.SALDO_MOVIMENTI, T_MOV.VALORE_ACQUISTO 
FROM
	(SELECT 
		MOV_ANAART AS ARTICOLO,
		SUM(CASE MOV_SEGNO WHEN '+' THEN MOV_QTAMOV ELSE (-1 * mov_qtamov) END) AS SALDO_MOVIMENTI, 
		ROUND(SUM(CASE MOV_SEGNO WHEN '+' THEN (ROUND(MOV_QTAMOV*MOV_PREACQ,2)) ELSE (-1 * (ROUND(MOV_QTAMOV*MOV_PREACQ,2))) END),2) AS VALORE_ACQUISTO, 
		COUNT(*) AS TOT_MOV 
	from u_mag_mo 
	where 
		mov_codmag = 'SEDE' and 
		mov_dtregi >= '2000/01/01' and 
		mov_dtregi <= '2011/08/31'
	GROUP BY MOV_ANAART) AS T_MOV

	LEFT OUTER JOIN U_ART_PR ON T_MOV.ARTICOLO = U_ART_PR.ART_CODPRI

ORDER BY ARTICOLO
