

SELECT	FATTURATO.*,
		COALESCE(TOT.QTATOT,0) AS QTATOT,
		COALESCE(TOT.VALORETOT,0) AS VALORETOT,
		COALESCE((SELECT TOP 1 ORD_VALORE/ORD_QTAORD 	 
					FROM U_BFO_DD 
					WHERE ORD_CODART=FATTURATO.CODART 
							AND ORS_DATORD < '2012/12/31' 
							AND ORD_QTAORD>0
							AND ORD_VALORE>0
					ORDER BY ORS_DATORD DESC ),0) AS COSTO_DA_ULTIMA_BOLLA_DI_CARICO ,
		COALESCE((SELECT AVG(CASE WHEN MOV_QTAMOV > 0 THEN MOV_VALACQ/MOV_QTAMOV ELSE 0 END) AS COSTO_MEDIO
				FROM U_MAG_MO
				WHERE MOV_DTDOCU BETWEEN '2012/01/01' AND '2012/12/31'
					AND MOV_ANAART=FATTURATO.CODART 
					AND MOV_SEGNO='+'
					AND MOV_QTAMOV<>0
					AND MOV_VALACQ<>0),0) AS COSTO_MEDIO_MAGAZZINO 
FROM (SELECT 
	RICAVI.ORS_NUMORD AS NR_FATTURA,
	RICAVI.ORS_DATORD AS DATA_FATTURA,
	RICAVI.ORD_CODART AS CODART, 
	RICAVI.ORD_UM AS UM_VEN,
	ART.ART_DESCR AS DESCRI,
	ART.ART_BASADE AS BASE_ADESIVO,
	ART.ART_TIPART AS ART_TIPART,
	SUM(ORD_QTAORD) AS QTA_VEN,
	SUM(ORD_VALORE) / SUM(ORD_QTAORD) AS PREZZO,
	SUM(ORD_VALORE) AS VALORE
FROM (SELECT ORS_NUMORD,
			 ORS_DATORD,
			ORD_CODART,
			ORD_UM,
			ORD_QTAORD,
			ORD_VALORE 
		FROM U_FAT_DD 
		WHERE ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31'
			AND ORD_QTAORD>0 
			AND ORD_VALORE>0 
			AND RTRIM(ORD_CODART) <> '.'
			AND ORD_DESART NOT LIKE '%POLIECO%') AS RICAVI
LEFT OUTER JOIN U_ART_PR AS ART
ON RICAVI.ORD_CODART = ART.ART_CODPRI 
GROUP BY  RICAVI.ORD_CODART,RICAVI.ORD_UM,ART.ART_DESCR,ART.ART_BASADE, ART.ART_TIPART ,RICAVI.ORS_NUMORD, RICAVI.ORS_DATORD ) AS FATTURATO
LEFT OUTER JOIN (SELECT 
			ORD_CODART,
			SUM(ORD_QTAORD) AS QTATOT,
			SUM(ORD_VALORE) AS VALORETOT			 
		FROM U_FAT_DD 
		WHERE ORS_DATORD BETWEEN '2012/01/01' AND '2012/12/31'
			AND ORD_QTAORD>0 
			AND ORD_VALORE>0 
			AND  RTRIM(ORD_CODART) <> '.'
		GROUP BY ORD_CODART) AS TOT
ON FATTURATO.CODART = TOT.ORD_CODART 
ORDER BY  CODART,DATA_FATTURA,NR_FATTURA
