/*  BILANCIO TOTALE PATRIMONIALI */

SELECT 

      SUM(CON_IMP_D) AS DARE,
      SUM(CON_IMP_A) AS AVERE, 
      SUM(CON_IMP_D) -SUM(CON_IMP_A) AS SALDO FROM (

SELECT 

      CON_CONTO,
      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,
      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI
WHERE LEN(CON_CONTO)>5
AND CON_IMP_D<>CON_IMP_A
AND CON_CONTO>='01' AND CON_CONTO<'30'
AND CON_SOC='01'
AND CON_ANNO='2012') AS T1

 
/*  BILANCIO TOTALE ECONOMICI */

SELECT 

      SUM(CON_IMP_D) AS DARE,
      SUM(CON_IMP_A) AS AVERE, 
      SUM(CON_IMP_D) -SUM(CON_IMP_A) AS SALDO FROM (

SELECT 

      CON_CONTO,
      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,
      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI
WHERE LEN(CON_CONTO)>5
AND CON_IMP_D<>CON_IMP_A
AND CON_CONTO>='01' AND CON_CONTO>'29'
AND CON_SOC='01'
AND CON_ANNO='2012') AS T1


 

 

SELECT 
      SUM(CON_IMP_D) AS DARE,
      SUM(CON_IMP_A) AS AVERE ,
      SUM(CON_IMP_D) -SUM(CON_IMP_A) AS SALDO 
FROM CONTI
WHERE LEN(CON_CONTO)>5
AND CON_IMP_D<>CON_IMP_A
AND SUBSTRING(CON_CONTO,1,4)='1010' 
AND CON_SOC='01'
AND CON_ANNO='2012'

 

 

 

/* DETTAGLIO SOLO PATRIMONIALI CONTI ELEMENTARI*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+CON_CONTO,

      CON_DESCR,

      SUM(CON_IMP_D) AS DARE,

      SUM(CON_IMP_A) AS AVERE, 

      SUM(CON_IMP_D) -SUM(CON_IMP_A) AS SALDO FROM (

SELECT 

      CON_CONTO,

      CON_DESCR,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='01' AND CON_CONTO<'30'

AND CON_SOC='01'

AND CON_ANNO='2012') AS T1

GROUP BY CON_CONTO,CON_DESCR

ORDER BY CON_CONTO

 

 

 

/* DETTAGLIO SOLO ECONOMICI CONTI ELEMENTARI*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+CON_CONTO,

      CON_DESCR,

      SUM(CON_IMP_D) AS DARE,

      SUM(CON_IMP_A) AS AVERE, 

      SUM(CON_IMP_D) -SUM(CON_IMP_A) AS SALDO FROM (

SELECT 

      CON_CONTO,

      CON_DESCR,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='30'

AND CON_SOC='01'

AND CON_ANNO='2012') AS T1

GROUP BY CON_CONTO,CON_DESCR

ORDER BY CON_CONTO

 

 

 

/* DETTAGLIO SOLO PATRIMONIALI CONTI GRUPPO XXXX*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+GRUPPO,

      SUM(CON_IMP_D) AS CON_IMP_D,

      SUM(CON_IMP_A) AS CON_IMP_A,

      SUM(CON_IMP_D) - SUM(CON_IMP_A) AS SALDO

FROM (

SELECT 

      SUBSTRING(CON_CONTO,1,4) AS GRUPPO,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI 

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='01' AND CON_CONTO<'30'

AND CON_SOC='01'

AND CON_ANNO='2012' 

) AS T1

GROUP BY GRUPPO

ORDER BY GRUPPO

 

 

/* DETTAGLIO SOLO ECONOMICI CONTI GRUPPO XXXX*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+GRUPPO,

      SUM(CON_IMP_D) AS CON_IMP_D,

      SUM(CON_IMP_A) AS CON_IMP_A,

      SUM(CON_IMP_D) - SUM(CON_IMP_A) AS SALDO

FROM (

SELECT 

      SUBSTRING(CON_CONTO,1,4) AS GRUPPO,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI 

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='30'

AND CON_SOC='01'

AND CON_ANNO='2012' 

) AS T1

GROUP BY GRUPPO

ORDER BY GRUPPO

 

 

 

 

/* DETTAGLIO SOLO PATRIMONIALI CONTI MASTRO XX*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+GRUPPO,

      SUM(CON_IMP_D) AS CON_IMP_D,

      SUM(CON_IMP_A) AS CON_IMP_A,

      SUM(CON_IMP_D) - SUM(CON_IMP_A) AS SALDO

FROM (

SELECT 

      SUBSTRING(CON_CONTO,1,2) AS GRUPPO,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI 

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='01' AND CON_CONTO<'30'

AND CON_SOC='01'

AND CON_ANNO='2012' 

) AS T1

GROUP BY GRUPPO

ORDER BY GRUPPO

 

 

/* DETTAGLIO SOLO ECONOMICI CONTI MASTRO XX*/

/* ATTIVITA' PASSIVITA' SALDO*/

SELECT 

      'C.'+GRUPPO,

      SUM(CON_IMP_D) AS CON_IMP_D,

      SUM(CON_IMP_A) AS CON_IMP_A,

      SUM(CON_IMP_D) - SUM(CON_IMP_A) AS SALDO

FROM (

SELECT 

      SUBSTRING(CON_CONTO,1,2) AS GRUPPO,

      CASE WHEN CON_IMP_D>CON_IMP_A THEN CON_IMP_D-CON_IMP_A ELSE 0 END AS CON_IMP_D,

      CASE WHEN CON_IMP_D<CON_IMP_A THEN CON_IMP_A-CON_IMP_D ELSE 0 END AS CON_IMP_A 

FROM CONTI 

WHERE LEN(CON_CONTO)>4

AND CON_IMP_D<>CON_IMP_A

AND CON_CONTO>='30' 

AND CON_SOC='01'

AND CON_ANNO='2012' 

) AS T1

GROUP BY GRUPPO

ORDER BY GRUPPO

