
SELECT * FROM (
SELECT 
	MOV_CODSOC AS MOV_CODSOC,
	MOV_ANAART AS MOV_ANAART,
	MOV_DESART AS MOV_DESART,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
FROM U_MAG_MO

GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC
WHERE MOV_ANAART = '108A1B3U12U12A1'
ORDER BY MOV_ANAART

SELECT MOV_DTREGI,MOV_ORAMOV,MOV_QTAMOV,* FROM U_MAG_MO WHERE MOV_CODMAT = '008' AND MOV_DOCMOD = 0 AND MOV_TOP = 'M++' AND MOV_DTREGI > '2012/08/23' ORDER BY MOV_DTREGI,MOV_ORAMOV





SELECT * FROM (
SELECT 
	MOV_CODSOC AS MOV_CODSOC,
	MOV_ANAART AS MOV_ANAART,
	MOV_DESART AS MOV_DESART,
	SUM(MOV_QTAMOV * CASE  MOV_SEGNO WHEN '+' THEN 1 ELSE -1 END ) AS MOV_QTAMOV
FROM U_MAG_MO
GROUP BY MOV_CODSOC,MOV_ANAART,MOV_DESART ) AS GIAC
WHERE MOV_ANAART = '118A1B300000001'
ORDER BY MOV_ANAART



SELECT * FROM (
SELECT 
	MAG_CODSOC AS MAG_CODSOC,
	MAG_ANAART AS MAG_ANAART,
	MAG_DESART AS MAG_DESART,
	SUM(MAG_GIACEN ) AS MAG_GIACEN
FROM U_MAG_GG
GROUP BY MAG_CODSOC,MAG_ANAART,MAG_DESART ) AS GIAC
WHERE MAG_ANAART = '118A1B300000001'
ORDER BY MAG_ANAART


--ORD_CODART = '118A1B300000001' AND


SELECT * FROM (
SELECT 
	ORD_CODART AS ORD_CODART,
	ORD_DESART AS ORD_DESART,
	ORS_DATORD AS ORS_DATORD,
	SUM(ORD_QTAORD ) AS ORD_QTAORD
FROM U_BOL_DD
GROUP BY ORD_CODART,ORD_DESART,ORS_DATORD ) AS GIAC
WHERE ORD_DESART <> '*** COMMENTO ***' AND ORS_DATORD > '2012/08/23'
ORDER BY ORD_CODART


SELECT ORS_DATORD,* FROM U_BOL_DD

