/********************************************************************
Popola_PARAMETRI_GESTIONE_ADR_GAS
*********************************************************************
********************************************************************/

-- PARAMETRO TIPO IMBALLO
DELETE FROM PARA WHERE CODICE LIKE 'IMB%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('IMBBB','BOMBOLA','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('IMBPP','PACCO','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('IMBBD','BIDONE','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('IMBSB','FUSTO','')
SELECT * FROM PARA WHERE CODICE LIKE 'IMB%' ORDER BY CODICE


-- PARAMETRO CODICE ADR
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('ADR1001','UN 1001 ACETILENE, DISCIOLTO,2.1, (B/D)','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('ADR1066','UN 1066 AZOTO, COMPRESSO,2.2, (E)','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('ADR1072','UN 1072 OSSIGENO, COMPRESSO,2.2 (5.1), (E)','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('ADR1956','UN 1956 GAS COMPRESSO, N.A.S., 2.2, (E)','')
SELECT * FROM PARA WHERE CODICE LIKE 'ADR%' ORDER BY CODICE
