/********************************************************************
Popola_PARAMETRI_GESTIONE_SPESE_TRASPORTO_GAS
*********************************************************************
********************************************************************/

-- PARAMETRO PORTO ASSEGNATO
DELETE FROM PARA WHERE CODICE = 'PORPAS'
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('PORPAS','PORTO ASSEGNATO','ARTICOLO_CALCOLO_SPESE_TRASPORTO_FISSE_GAS:SPTRASFIS')
SELECT * FROM PARA WHERE CODICE LIKE 'POR%' ORDER BY CODICE

-- PARAMETRO PER QUOTA FISSA HMF
DELETE FROM PARA WHERE CODICE = 'HMFHMF'
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('HMFHMF','SPESE HMF FISSE PER TRASPORTO BOMBOLE GAS','ARTICOLO_CALCOLO_SPESE_TRASPORTO_FISSE_GAS_HMF:SPTRASHMF')
SELECT * FROM PARA WHERE CODICE LIKE 'HMF%' ORDER BY CODICE

-- PARAMETRO PER QUOTE VARIABILI STANDARD E QUOTE VARIABILI HMF
DELETE FROM PARA WHERE CODICE LIKE 'FTR%'
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('FTRBB','BOMBOLE NON SOGGETTE AD HMF','ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS:SPTRASVB')
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('FTRBH','BOMBOLE SOGGETTE AD HMF','ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS:SPTRASVB;ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS_HMF:SPTRASVBH')
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('FTRPB','PACCHI NON SOGGETTE AD HMF','ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS:SPTRASVP')
INSERT INTO PARA (CODICE,DESCRI,ITALIANO) VALUES ('FTRPH','PACCHI SOGGETTE AD HMF','ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS:SPTRASVP;ARTICOLO_CALCOLO_SPESE_TRASPORTO_VARIABILI_GAS_HMF:SPTRASVPH')
SELECT * FROM PARA WHERE CODICE LIKE 'FTR%' ORDER BY CODICE


-- ARTICOLI TUTTE LE PER SPESE DI TRASPORTO CONFIGURATE
DELETE FROM U_ART_PR WHERE ART_CODPRI LIKE 'SPTRAS%'
DELETE FROM U_ART_AN WHERE ART_CODPRI LIKE 'SPTRAS%'

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASFIS','QUOTA TRASPORTO FISSA','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',15.00,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASFIS',0,'')

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASHMF','QUOTA HMF FISSA','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',10.00,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASHMF',0,'')

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASVB','QUOTA TRASPORTO VARIABILE BOMBOLE','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',2.00,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASVB',0,'')

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASVBH','QUOTA HMF VARIABILE BOMBOLE','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',1.50,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASVBH',0,'')

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASVP','QUOTA TRASPORTO VARIABILE PACCHI','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',8.00,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASVP',0,'')

INSERT INTO U_ART_PR (ART_CODSOC,ART_CODPRI,ART_DESCR,ART_UNIMIS,ART_LINEA,ART_CODIVA,ART_MAGA,ART_GRUPPO,ART_CGE,ART_CODVAL,ART_CATMER,ART_DESMER,ART_CODMAT,ART_TIPART,ART_DISBAS,ART_RIPCOM,ART_UMMAGA,ART_DESMAT,ART_SPESSO,ART_ALTEZZ,ART_LUNGHE,ART_CODCAT,ART_DESCAT,ART_PRZVEN,ART_NONMOV)
	VALUES ('01','SPTRASVPH','QUOTA HMF VARIABILE PACCHI','NR','','22','SEDE','','','EUR','','','001','A','','','NR','',0,0,0,'','',6.00,1)
INSERT INTO U_ART_AN (ART_CODSOC,ART_CODPRI,ART_QTANRC,ART_SCELTA)
	VALUES ('01','SPTRASVPH',0,'')


SELECT * FROM U_ART_PR WHERE ART_CODPRI LIKE 'SPTRAS%' ORDER BY ART_CODPRI
SELECT * FROM U_ART_AN WHERE ART_CODPRI LIKE 'SPTRAS%' ORDER BY ART_CODPRI


UPDATE U_ART_AN SET ART_FAMTRA = ''