SELECT ORD_DATORD,ORD_CHIUSO,ORD_FLBOL,ORD_CAMBIO,ORD_VALUTA,ORD_AGE,ORD_CPA,ORD_FLBOL, * FROM U_BOL_TT

--UPDATE U_BOL_TT SET ORD_FLBOL = '' 
DELETE FROM U_FAT_TT
DELETE FROM U_FAT_DD
DELETE FROM FATTURABILE_MDB
DELETE U_MAG_GG
DELETE U_MAG_MO
DELETE STORICO_SCHEDE_SDS
DELETE PROD_PACKING
DELETE PROD_PACKING_DB
DELETE PRODUZIONE
DELETE PROD_ORDINI
DELETE PROD_AVANZA
DELETE PROD_CARICHI
DELETE PROD_IMPEGNI
DELETE PROD_DISIMPEGNI


SELECT * FROM CONTRMDB


--UPDATE FATTURABILE_MDB SET MDB_FATTUR = 0 

SELECT * FROM SCHEDE_SDS
SELECT * FROM STORICO_SCHEDE_SDS
SELECT * FROM FATTURABILE_MDB


--DELETE FROM SCHEDE_SDS
--DELETE FROM STORICO_SCHEDE_SDS
--DELETE FROM FATTURABILE_MDB


SELECT ORD_VALUTA,ORD_AGE,ORD_CPA,* FROM U_FAT_TT
SELECT * FROM U_FAT_DD


select ors_codcli as codcli ,* from CONTRMDB_DD where ord_codmag = '000188' and ors_codloc = '' and ord_codmdb = 'I1001L' and ord_salcon = 'X' order by ors_codcli,ors_codloc,ord_codmdb

SELECT MOV_LEGAME,MOV_UNIQUE,* FROM U_MAG_MO -- WHERE MOV_UNIQUE = '_52D0ZOLZH'
SELECT MAG_LEGAME,MAG_UNIQUE,* FROM U_MAG_GG

SELECT * FROM FATTURABILE_MDB

UPDATE FATTURABILE_MDB SET MDB_FATTUR = 1 WHERE mdb_codmag = '000190' and mdb_annomm = '2018/01' and mdb_codmdb = 'I1001L    '
UPDATE FATTURABILE_MDB SET MDB_FATTUR = 1 WHERE MDB_SYSRIGA  = '_52Y02ZH42'