-- VISTA FATTURE_FOR_DA_SALDARE_O_SALDATE_ULTIMO_ANNO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[FATTURE_FOR_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]'))
	DROP VIEW [dbo].[FATTURE_FOR_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
GO

CREATE VIEW [dbo].[FATTURE_FOR_DA_SALDARE_O_SALDATE_ULTIMO_ANNO]
AS

	SELECT 
		SUBSTRING(RIGHE_PART.PAR_CODCLI,5,10) AS COD_CLIENTE,
		RIGHE_PART.PAR_RAGSOC AS RAG_SOCIALE,
		RIGHE_PART.PAR_NUMFAT AS NUM_FATTURA,
		dbo.ribalta2(RIGHE_PART.PAR_DTFAT) AS DATA_FATTURA,
		CASE
			WHEN COALESCE(NOTA_CRED.PAR_NPROT,'') <> '' THEN RTRIM(NOTA_CRED.PAR_NPROT) + ' del ' + dbo.ribalta2(NOTA_CRED.PAR_DTFAT)
			ELSE ''
		END AS NOTA_CRED,
		COALESCE(PARA_CPA.DESCRI,'') AS COND_PAGAMENTO,
		dbo.ribalta2(RIGHE_PART.PAR_DTSCAD) AS DATA_SCADENZA,
		RIGHE_PART.PAR_DESMOV AS DESCRIZIONE_FATT,
		CAST(ROUND(COALESCE(FAF_TT.ORD_IMPONIB*FAF_TT.ORD_CAMBIO,0),2) AS NUMERIC(19,2)) AS IMPONIBILE_TOT_FATTURA,
		CAST(ROUND(COALESCE(FAF_TT.ORD_IMPOSTA*FAF_TT.ORD_CAMBIO,0),2) AS NUMERIC(19,2)) AS IMPOSTA_TOT_FATTURA,
		CAST(ROUND(FAF_TT.ORD_IMPONIB*FAF_TT.ORD_CAMBIO + FAF_TT.ORD_IMPOSTA*FAF_TT.ORD_CAMBIO,2) AS NUMERIC(19,2)) AS TOT_FATTURA,
		CAST(ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS NUMERIC(19,2)) AS IMPORTO_SCAD_PAG,
		CAST(ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) - ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) AS NUMERIC(19,2)) AS RESIDUO_SCAD_PAG,
		CASE
			WHEN ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) = ROUND(FAF_TOT.IMPORTO_TOTALE,2) THEN 'CHIUSA'
			ELSE 'APERTA'
		END AS STATO,
		CASE
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0
				THEN dbo.ribalta2(COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN dbo.ribalta2(COALESCE(PAG_ULT.PAR_DTREG,''))
			ELSE ''
		END AS DATA_PAGAMENTO,
		CASE
			WHEN ROUND(COALESCE(PAG_SCA.IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,'')) <> '' 
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_SCA.PAR_DTREG,COALESCE(PAG_ULT.PAR_DTREG,''))) AS datetime))
			WHEN ROUND(COALESCE(PAG_ULT.ULT_IMPORTO_SCAD_PAG,0),2) > 0 AND COALESCE(PAG_ULT.PAR_DTREG,'') <> ''
				THEN DATEDIFF(DAY, cast(DBO.RIBALTA2(RIGHE_PART.PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(COALESCE(PAG_ULT.PAR_DTREG,'')) AS datetime))
			ELSE 0
		END AS NR_GIORNI_RITARDO
		--COALESCE(FAF_DD.ORD_CCODET,'') AS COD_CENTRO_COSTO,
		--COALESCE(CCOSTO.CON_DESCR,'') AS DESCR_CENTRO_COSTO,
		--ROUND(RIGHE_PART.PAR_FATT*RIGHE_PART.PAR_CAMBIO,2) AS IMPORTO_SCAD,
		--ROUND(FAF_TOT.IMPORTO_TOTALE,2) AS IMPORTO_TOTALE,
		--ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) AS IMPORTO_TOTALE_PAG,
		--COALESCE(U_FOR_AN.FOR_NAZION,'') AS NAZIONE_FORN,
		--COALESCE(PARA_STA.DESCRI,'') AS DESCR_NAZIONE_FORN,
		--COALESCE(U_FOR_AN.FOR_ZONA,'') AS AREA_GEOGRAFICA_FORN,
		--COALESCE(PARA_ZON.DESCRI,'') AS DESCR_AREA_GEOGRAFICA_FORN,
		--COALESCE(PAG_SCA.NR_GIORNI_RITARDO_MEDI_PONDERATI,0) AS NR_GIORNI_RITARDO_MEDI_PONDERATI
	FROM PART_FOR AS RIGHE_PART
		LEFT OUTER JOIN PARA AS PARA_TOP ON PARA_TOP.CODICE = 'TOP'+RIGHE_PART.PAR_TIPFAT
		LEFT OUTER JOIN PARA AS PARA_CPA ON PARA_CPA.CODICE = 'CPA'+RIGHE_PART.PAR_CODPAG
		INNER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'A' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) <> 'S')  GROUP BY PAR_CODCLI, PAR_NPART) AS FAF_TOT ON FAF_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND FAF_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END) AS IMPORTO_TOTALE_PAG FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART) AS PAG_TOT ON PAG_TOT.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_TOT.PAR_NPART = RIGHE_PART.PAR_NPART
		LEFT OUTER JOIN (SELECT PAR_CODCLI, PAR_NPART, PAR_DTSCAD, COALESCE(MAX(PAR_DTREG),'') AS PAR_DTREG, SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END) AS IMPORTO_SCAD_PAG, CASE WHEN SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END) <> 0 THEN (SUM(PAR_FATT * PAR_CAMBIO * CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO*CASE WHEN PAR_TMOV = 'D' THEN 1 ELSE -1 END)) ELSE 0 END AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) GROUP BY PAR_CODCLI, PAR_NPART, PAR_DTSCAD) AS PAG_SCA ON PAG_SCA.PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAG_SCA.PAR_NPART = RIGHE_PART.PAR_NPART AND PAG_SCA.PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD
		OUTER APPLY (SELECT TOP 1 PAR_CODCLI, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS ULT_IMPORTO_SCAD_PAG FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND ((SUBSTRING(LIBERA,2,1) NOT IN ('S','F','A')) OR (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S'))) AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS PAG_ULT
		LEFT OUTER JOIN (SELECT DISTINCT ORD_CCODET, ORS_NUMORD, ORS_DATORD, ORS_DATOR2 FROM U_FAF_DD WHERE ORD_DESART <> '*** COMMENTO ***') AS FAF_DD ON FAF_DD.ORS_NUMORD = RIGHE_PART.PAR_NUMFAT AND FAF_DD.ORS_DATOR2 = RIGHE_PART.PAR_DTFAT
		RIGHT OUTER JOIN U_FAF_TT AS FAF_TT ON FAF_TT.ORD_NUMORD = RIGHE_PART.PAR_NUMFAT AND FAF_TT.ORD_DATOR2 = RIGHE_PART.PAR_DTFAT
		LEFT OUTER JOIN CCOSTO ON CCOSTO.CON_ANNO = SUBSTRING(FAF_DD.ORS_DATORD,1,4) AND CCOSTO.CON_CONTO = FAF_DD.ORD_CCODET
		LEFT OUTER JOIN U_FOR_AN ON U_FOR_AN.FOR_CODCLI = FAF_TT.ORD_CODCLI
		LEFT OUTER JOIN PARA AS PARA_STA ON PARA_STA.CODICE = 'STA'+U_FOR_AN.FOR_NAZION
		--LEFT OUTER JOIN PARA AS PARA_ZON ON PARA_ZON.CODICE = 'ZON'+U_FOR_AN.FOR_ZONA
		--OUTER APPLY (SELECT (SUM(PAR_FATT * PAR_CAMBIO * DATEDIFF(DAY, cast(DBO.RIBALTA2(PAR_DTSCAD) AS datetime), cast(DBO.RIBALTA2(PAR_DTREG) AS datetime))) / SUM(PAR_FATT*PAR_CAMBIO)) AS NR_GIORNI_RITARDO_MEDI_PONDERATI FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TMOV = 'A' AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART AND PAR_DTSCAD = RIGHE_PART.PAR_DTSCAD) AS MEDIA_PAG
		OUTER APPLY (SELECT TOP 1 PAR_TIPFAT, PAR_NPROT, PAR_DTFAT, PAR_NPART, PAR_DTSCAD, PAR_DTREG, PAR_FATT*PAR_CAMBIO AS NOTA_CREDITO_SCAD FROM PART_FOR WHERE PAR_NPROG <> 100 AND PAR_TIPFAT IN (SELECT SUBSTRING(CODICE,4,3) FROM PARA WHERE CODICE LIKE 'TOP%' AND (SUBSTRING(LIBERA,2,1) IN ('S','F','A') AND SUBSTRING(LIBERA,11,1) = 'S')) AND PAR_CODCLI = RIGHE_PART.PAR_CODCLI AND PAR_NPART = RIGHE_PART.PAR_NPART ORDER BY PAR_DTREG DESC) AS NOTA_CRED
	WHERE
		RIGHE_PART.PAR_NPROG <> 100 
		AND (RIGHE_PART.PAR_TMOV = 'A' AND COALESCE(SUBSTRING(PARA_TOP.LIBERA,2,1),'') IN ('S','F','A') AND SUBSTRING(PARA_TOP.LIBERA,11,1) <> 'S')
		AND (ROUND(COALESCE(PAG_TOT.IMPORTO_TOTALE_PAG,0),2) <> ROUND(FAF_TOT.IMPORTO_TOTALE,2) OR RIGHE_PART.PAR_DTFAT >= convert(varchar, DATEADD(day, - 365, GETDATE()), 111))
		--AND RIGHE_PART.PAR_DTSCAD < convert(varchar, GETDATE(), 111)

GO

SELECT * FROM FATTURE_FOR_DA_SALDARE_O_SALDATE_ULTIMO_ANNO ORDER BY DATA_FATTURA,NUM_FATTURA,RAG_SOCIALE