


SELECT MOV_TOP,MOV_ANNO AS MOV_ANN,MOV_DTREG AS MOV_DTRE,* FROM MOV_CONT WHERE mov_conto = '30310066900' and mov_dtreg between '2001/05/01' and '2015/12/31' order by mov_soc,mov_anno,mov_conto,mov_dtreg,mov_nregis


SELECT MOV_TOP,MOV_ANNO AS MOV_ANN,MOV_DTREG AS MOV_DTRE,* FROM MOV_CONT WHERE MOV_ANNO <> SUBSTRING(MOV_DTREG,1,4) AND MOV_TOP = 'CHI' order by mov_soc,mov_anno,mov_conto,mov_dtreg,mov_nregis


SELECT MOV_TOP,MOV_ANNO AS MOV_ANN,MOV_DTREG AS MOV_DTRE,* FROM MOV_CONT WHERE MOV_TOP = 'CHI' order by mov_soc,mov_anno,mov_conto,mov_dtreg,mov_nregis

SELECT * FROM PART_FOR WHERE PAR_ANNO <> SUBSTRING(PAR_DTREG,1,4) AND PAR_TIPFAT = 'CHI' 


--UPDATE MOV_CONT SET MOV_ANNO = SUBSTRING(MOV_DTREG,1,4) WHERE MOV_DTREG <> '' AND MOV_ANNO <> SUBSTRING(MOV_DTREG,1,4) 
--UPDATE INDICE SET MOV_ANNO = SUBSTRING(MOV_DTREG,1,4) WHERE MOV_DTREG <> '' AND MOV_ANNO <> SUBSTRING(MOV_DTREG,1,4) 
