
CREATE TABLE #CANALE (CODICE1 VARCHAR(3), DESCRI1 VARCHAR(50))
CREATE TABLE #SETTORE (CODICE2 VARCHAR(3), DESCRI2 VARCHAR(50))
CREATE TABLE #TIPOLOGIA (CODICE3 VARCHAR(3), DESCRI3 VARCHAR(50))


INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('DIS','DISTRIBUTORE')
INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('INS','INSTALLATORE')
INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('OEM','OEM')
INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('RIV','RIVENDITORE')
INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('UTE','UTENTE FINALE')
INSERT INTO #CANALE (CODICE1,DESCRI1) VALUES ('IMP','IMPIANTISTA')


INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('AGR','AGRICOLTURA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('ALI','ALIMENTARE')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('ALL','ALLEVAMENTO')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('CHI','CHIMICO FARMACEUTICO')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('COM','COMMERCIALE')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('FON','FONDERIA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('HOR','HORECA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('HVA','HVAC')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('MEC','MECCANICA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('SAN','SANITÀ')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('SPO','SPORT')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('STA','STAMPAGGIO MAT. PLASTICHE')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('PUB','PUBBLICA AMMINISTRAZIONE')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('DID','DIDATTICA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('CHM','CHIMICO')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('IND','INDUSTRIA GENERICA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('AER','AERONAUTICA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('IDR','IDRAULICA')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('ALE','ELETTRICO')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('ASP','ASPIRAZIONE')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('GDO','GDO')
INSERT INTO #SETTORE (CODICE2,DESCRI2) VALUES ('GDS','GDS')


INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('FLO','FLORICOLTURA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('ORT','ORTICOLTURA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('BEV','BEVANDE')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SEC','SECCO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('FRE','FRESCO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SUR','SURGELATO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SUI','SUINI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('POL','AVICOLI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('HOT','HOTEL')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('RIS','RISTORANTE')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('BAR','BAR')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('MEN','MENSA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('PAL','PALESTRA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('EST','ESTETICO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('PAR','PARRUCCHIERE')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('FAR','FARMACIA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('OSP','OSPEDALE/CLINICA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('LAB','LABORATORIO ANALISI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('UNI','UNIVERSITÀ')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SCU','SCUOLA ')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SCP','SCUOLA PRIVATA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('INS','INSACCATI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('BOV','BOVINI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('OVI','OVINI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('FIE','FIERA/CONGRESSO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('CIN','CINEMA/TEATRO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('MUS','MUSEO')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('MAN','MANIFATTURA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('SUP','SUPERMARKET')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('UFF','UFFICI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('IMP','IMPIANTI')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('ASS','ASSISTENZA')
INSERT INTO #TIPOLOGIA (CODICE3,DESCRI3) VALUES ('PRI','PICCOLA RIVENDITA')


DELETE FROM PARA WHERE CODICE LIKE 'CVE%'
INSERT INTO PARA (CODICE,DESCRI)
select 'CVE'+CODICE1 AS CODICE, DESCRI1 AS DESCRI from #CANALE
order by CODICE1

INSERT INTO PARA (CODICE,DESCRI)
select 'CVE'+CODICE1+CODICE2 AS CODICE, DESCRI1+' - '+DESCRI2 AS DESCRI from #CANALE
LEFT OUTER JOIN #SETTORE ON 1=1
order by CODICE1,CODICE2

INSERT INTO PARA (CODICE,DESCRI)
select 'CVE'+CODICE1+CODICE2+CODICE3 AS CODICE, DESCRI1+' - '+DESCRI2+' - '+DESCRI3 AS DESCRI from #CANALE
LEFT OUTER JOIN #SETTORE ON 1=1
LEFT OUTER JOIN #TIPOLOGIA ON 1=1
order by CODICE1,CODICE2,CODICE3

DROP TABLE #CANALE
DROP TABLE #SETTORE
DROP TABLE #TIPOLOGIA