/********************************************************************/
/* POPOLAMENTO PARAMETRI PER CAMPI PER GESTIONE CANALE VENDITA */
/********************************************************************/
-- Campo DIVISIONE
DELETE FROM PARA WHERE CODICE LIKE 'CVE%'
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CVECUF','UTENTE FINALE','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CVECIM','IMPIANTISTA','')
INSERT INTO PARA (CODICE,DESCRI,LIBERA) VALUES ('CVECRI','RIVENDITORE','')





SELECT * FROM PARA WHERE CODICE LIKE 'CVE%' ORDER BY LIBERA

