
UPDATE U_AZI_PB SET AZI_ESCLFORMBLBX = 'MENU_STBILAN;MENU_CASHFLOW_FINANCE;MENU_CONTROLLO_GESTIONE;MENU_BIL000;MENU_ANABIL;MENU_BILCOAN;MENU_STBISECO;MENU_STBILANC;MENU_BILNOSOL;MENU_STBICCOSECO'

SELECT AZI_ESCLFORMBLBX FROM U_AZI_PB