
/********************************************************************
 TABELLA DESLINGUE: INSERIMENTO DESCRIZIONI IN LINGUA PER ARTICOLI
*********************************************************************
********************************************************************/

delete deslingue where tipodes = 'ARTICOLO' 
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB10B-E1000','Electronic controller for 1 Radiant Strip Tub-One, with remote sensor, reset button, 2 temperature levels, clock.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB10B-E1100','Electronic controller for 2 Radiant Strips Tub-One, with remote sensor, reset button, 2 temperature levels.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB13B-E1000','Electronic controller for 2 Radiant Tubes Ray-Red, with remote sensor, reset buttons, 2 temperature levels.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB13B-E1001','Electronic controller for 2 Radiant Strips Tub-One, with remote sensor, reset button, 2 temperature levels, clock.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB13B-E1100','Electronic controller for 2 Tub One, with sensor, reset switch  with two temp levels and clock','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB13B-E1101','Electronic controller for 4 Radiant Tubes Ray-Red, with remote sensor, reset buttons, 2 temperature levels.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KB15B-E1001','Electronic controller for 1 Radiant Tube Ray-Red, with remote sensor, reset button','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KH111E1/A','Electronic controller for 2 Radiant Tubes Ray-Red, with remote sensor, reset buttons ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','1KH112E1/A','BASE DUCT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.915','BASE DUCT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.939','Horizontal and vertical adjustable flaps air diffuser for duct,  600x600 mm,  for FPA109-FPA159-TA159-TC109','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.942','Horizontal and vertical adjustable flaps air diffuser for duct,  1150x600 mm, for TA209-TC209','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.943','FLOATER SWITCH WITH DELAYER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.103','WATER INLET SOLENOID VALVE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.106','WATER RECIRCULATING PUMP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.121','DISPLAY SCP964/AP (8 BUTTONS) ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.122','PRINTED CIRCUIT (INSIDE MAIN E-BOARD) SCP964/AP ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.123','FAN MOTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.126','FAN MOTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.127','FAN PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.128','ANTI VIBRATION RUBBER MOUNT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.129','TUBE FOR RUBBER MOUNT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.130','AIR CONVEYOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.151','AIR CONVEYOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.152','WATER RECIRCULATING PUMP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.153','FAN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.155','WATER INLET SOLENOID VALVE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.156','4 POLES SCREENED CABLE (INTERNAL)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.159','FEMALE CABLE FOR FAN MOTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.160','FAN RELAY','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.161','RELAY CONNECTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.162','4 POLES SCREENED CABLE (EXTERNAL)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.172','PRINTED CIRCUIT (INTERNAL) SCP964/AE FOR BUS SYSTEM','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.174','TANK ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.101','COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.102','WATER DIFFUSION STRAP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.103','WATER DISTRIBUTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.112','BACK PANEL INTERNAL SUPPORT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.117','FLEXIBLE HOSE FOR WATER DISTRIBUTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.145','4 ways roof  air diffuser with horizontal adjustable flaps,  for duct 600x600 mm, for FPA109-FPA159-TA159-TC109','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.153','WATER DISTRIBUTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.156','6 ways roof  hexagonal air diffuser with horizontal adjustable flaps, for duct 1150x600 mm , for TA209-TA309SD-TC209                               ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.158','PORTAGOMMA PER POMPA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.162','PUMP SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.175','FLEXIBLE HOSE FOR WATER DISTRIBUTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.190','WATER DISTRIBUTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.191','SIDE PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.104 ','FRONT PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.105','WINTER COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.106','PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.110','CORNER COLUMN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.117','TANK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.120','COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.121','WINTER COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.122','WINTER COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.123','PUMP SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.125','SIDE PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.151','COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.152','TANK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.153','CENTRAL COLUMN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.155','MAIN ELECTRICAL BOARD (SCP964)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C108.100','MAIN ELECTRICAL BOARD (SCP964)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C109.100','TANK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C200.002','WATER DISTRIBUTION PLATE ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C200.005','WATER DIFFUSION STRAP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C200.006','FRONT WATER DISTRIBUTION PLATE ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C200.007','SIDE PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.001','CORNER COLUMN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.007','FRONT PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.009','FRONT COLUMN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.010','SIDE PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.012','PUMP/ELECTRIC SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.013','FRONT PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.014','COMPLETE BACK PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.045','DRAIN CLOSURE SILICON GASKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C400.004','WATER DISCHARGE TUBE Ø60-L.1200','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C400.013','2m corrugated tube for water discharge displacement','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C400.019','Winter cover for  FPA 109 and FPA159','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C431.001','Winter cover for TA 159 and TC 109','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C431.002','Winter cover for  TA 209 and TC209','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C431.006','FLOATER SWITCH','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C500.000','COMPLETE VENTILATION GROUP (WITHOUT AIR CONVEYOR)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C500.005','COMPLETE VENTILATION GROUP (WITHOUT AIR CONVEYOR)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C500.007','Air flow detector for an automatic drive of  air extraction fans','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C500.020','MAIN ELECTRICAL BOARD (SCRE50)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.000','MAIN ELECTRICAL BOARD (SCRE50)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.001','MAIN SWITCH BOARD (EXTERNAL)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.002','SHORT CABLE FOR DISPLAY CONNECTION (INTERNAL)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.003','LONG CABLE FOR DISPLAY CONNECTION (EXTERNAL)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.004','Network board with temperature and humidity probe, for one or groups of coolers','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.033','Digital main board, to be placed in a main switch board','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.050','MODBUS module to connect to an existing BUS system','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.051','Digital main board with computer connection gateway and management software','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.052','Computer connection gateway and management software to complete the general electronic control board C600.050','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C600.053','FAN','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C700.004','COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C800.000','COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C800.001','Ø160 double 90° right bend ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR1.DH','Ø160 double 90° left bend ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR1.SH','Ø160 extra 180° bend','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR1.TH','Ø250 double 45° right bend for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.D45HC','Ø250 single 45° right bend for RCF 80/100/150/200/300 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.D45HMC','Ø250 double 90° right bend for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.DHC','Ø250 single 90° right bend for RCF 80/100/150/200/300 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.DHMC','Ø250 double 45° left bend for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.S45HC','Ø250 single 45° left bend for RCF 80/100/150/200/300 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.S45HMC','Ø250 double 90° left bend for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.SHC','Ø250 single 90° left bend for RCF 80/100/150/200/300 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.SHMC','Ø250 extra 180° bend','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','CR2.THC','Eliturbo Air Mixer 2000 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M ','Eliturbo Air Mixer 2000 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M.R ','Eliturbo Air Mixer 2000 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M.V ','Eliturbo Air Mixer 2000 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M55','Eliturbo Air Mixer 2000 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M55.R','Eliturbo Air Mixer 2000 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2M55.V','Eliturbo Air Mixer 2000 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2MUS','Eliturbo Air Mixer 2000 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T','Eliturbo Air Mixer 2000 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T.R','Eliturbo Air Mixer 2000 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T.V','Eliturbo Air Mixer 2000 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T55','Eliturbo Air Mixer 2000 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T55.R','Eliturbo Air Mixer 2000 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2T55.V','Eliturbo Air Mixer 2000 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E2TUS','Eliturbo Air Mixer 2002 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M ','Eliturbo Air Mixer 2002 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M.R','Eliturbo Air Mixer 2002 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M.V','Eliturbo Air Mixer 2002 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M55','Eliturbo Air Mixer 2002 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M55.R','Eliturbo Air Mixer 2002 single-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3M55.V','Eliturbo Air Mixer 2002 single-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3MUS','Eliturbo Air Mixer 2002 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T','Eliturbo Air Mixer 2002 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T.R','Eliturbo Air Mixer 2002 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T.V','Eliturbo Air Mixer 2002 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T55','Eliturbo Air Mixer 2002 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T55.R','Eliturbo Air Mixer 2002 three-phase IP55','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3T55.V','Eliturbo Air Mixer 2002 three-phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','E3TUS','Air extraction fan','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','EPA100','Air extraction fan','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','EPA150','Air extraction fan','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','ETA100','Air extraction fan','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','ETA150','Air extraction fan','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','ETA200','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','FPA 109 ','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','FPA 159 ','Double pipe connecting radiant section between Ø 300 and Ø 250 only for RCF 300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','JR32.1H','Electrical resistance kit for RCF80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','KARTIC2','Electrical resistance kit for RCF150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','KARTIC3','Long external Kit for combustion group, RCF 35/50, lenght 1000mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','KX1.L','Long external Kit for combustion group, RCF 80/100, lenght 1000mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','KX2.L','Long external Kit for combustion group, RCF 150/200/300, lenght 1000mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','KX3.L','Lead flashing  20/35°, Ø 170 mm.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M0540806','Flashing for flat roof, Ø 170 mm.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M0540919','Set 2 flue pipes, 1.000 mm length,  Ø 100 mm.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M5990536','Set 2 flue elbows, 90°, Ø 100 mm.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M5990537','Set 2 flue elbows, 45°, Ø 100 mm.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M5990538','Roof coaxial chimney  (2 x Ø 100)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M5990558','Wall coaxial chimney  (2 x Ø 100)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','M5990583','WATER INLET PIPE-FITTING','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC300.003','GRILL BLOCK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC400.010','WATER DISCHARGE TUBE CLAMP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC400.033','PRINTED CIRCUIT (INSIDE MAIN E-BOARD) SCRE50','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.000','TEMPERATURE/HUMIDITY PROBE SCPH02 (`08) ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.003','EVO display - automatic functions electronic controller','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.004','Router ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.008','ECO display - manual functions electronic controller','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.018','SWITCH ON ELECTRONIC BOARD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.029','MOTOR CONDENSATOR - µF.25','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.042','FAN RELAY','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.065','DRAIN SYSTEM','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC800.000','WATER RECIRCULATING PUMP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC800.002','GAS FLEXIBLE JOINT Ø 1"','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MC101.108','Ø160 double pipe radiant strip,  2 meters lenght','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR1.2H','Ø160 double pipe 90° T radiant section','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR1.TH','Ø250 double pipe radiant strip of 1 meter for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.1HC','Ø250 single pipe radiant strip of 1 meter for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.1HMC','Ø250 double pipe radiant strip of 2 meters for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.2HC','Ø250 single pipe radiant strip of 2 meters for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.2HMC','Ø250 double pipe radiant strip of 4 meters for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.4HC','Ø250 single pipe radiant strip of 4 meters for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.4HMC','Ø250 double pipe 90° T radiant section for RCF 80/100/150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.THC','Ø 250 double pipe Y connecting radiant strip between double and single pipe sections ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR2.YHMC','Ø300 double pipe radiant strip of 4 meters only for RCF 300 (the first three sections of the line)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MR3.4H','Complete burner box Ø 101 for RAY 2E(L) - 3E(L) - 3E/9 - 4E ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.101/C','Complete burner box Ø 76 for RAY 1E/EL - 2ES/SL   ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.102/C','Burner neck D. 103 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.104','Burner neck D. 77 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.106','Stainless steel clamp D. 101','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.107','Stainless steel clamp D. 76','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.108','INTERFERENCES SUPPRESSION FILTER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.110','BURNER (TORCH)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.138','GAS VALVE - DUNGS *not is production anymore, contact us','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.204','GAS VALVE - SIT 822 NOVA 0822.113 - NATURAL GAS ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.205','Gas valve','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.207','FLANGE 1/2" 90° - GAS VALVE SIT 822 NOVA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.208','CONNECTOR / CABLE FOR GAS VALVE SIT 822','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.209','FLANGE 3/4" 90° - GAS VALVE SIT 822 NOVA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.211','Burner (torch)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.215','Gas nozzle - All diamiters (specify Ray-Red model)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.251...262','GAS NOZZLE LPG - Ø 5,30','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.259','GAS NOZZLE LPG - Ø 6,50','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.260','Ignition/ionization electrodes (sparking-plug)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.301','AIR PRESSURE SWITCH','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.305','FLAME CONTROLLER CM 31','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.315','Signal lamp green','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.325','Signal lamp orange','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.326','Signal lamp red + button ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.328','Fuse holder F2001 6A 250V','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.340','Fuse 5 x 20 2A. / F','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.342','Plug 3 poles','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.361','Socket 3 poles','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.362','Plug 7 poles','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.363','Socket 7 poles','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.364','Electical cabling for Ray for cm31','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R101.395','Complete flue exhaust fan Ø101 EBM for R2E(L) - 3E(L) - 3E/9 - 4E','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.105/C','Complete flue exhaust fan Ø76 EBM for R1E/EL - 2ES/SL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.106/C','Complete flue exhaust fan Ø101 MORO for R2E(L) - 3E(L) - 3E/9 - 4E','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.108/C','Complete flue exhaust fan Ø76 MORO for R1E/EL - 2ES/SL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.109/C','Diaphragm D. 31 for R1E, R1EL EBM / MORO extracteur','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.150','Diaphragm D. 41 for R1E extracteur AACO','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.151','Diaphragm D. 45 for R2ES, R2ES/L, R2E, R2E/L EBM / MORO extracteur','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.152','Diaphragm D. 51 for R3E/L EBM / MORO extracteur','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.153','Diaphragm D. 57 for R3E9 EBM / MORO extracteur','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R102.154','Reflector 850x2050 mm – for “R2E, R3E, R3E/9, R4E”','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R103.102','Reflector 620x1580 mm – for “ R1E, R2ES”','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R103.116','Reflector 580x2950 mm – for “R1EL, R2ESL, R2EL, R3EL”','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R103.130','Terminal bend D. 101 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.102/R','Terminal bend D. 76 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.106/R','Neck D. 101 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.140','Neck D. 76 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.141','Pipe D. 76,1 X 4500 painted','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.150/R','Pipe D. 101,6 X 6000 painted','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.151/R','Pipe D. 101,6 L.6000 th. 2,9 + Stainless steel pipe D. 76,1 th. 2','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.152/R','Pipe D. 101,6 X 2000 painted','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.153/R','Pipe D. 76,1 X 3000 painted','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.154/R','Pipe D. 101,6 X 4000 painted','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.170/R','Stainless steel pipe D. 76,1 X 1000 th. 2','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.180.L','STAINLEES STEEL LENGTH 1000MM - COMBUSTION CHAMBER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R104.186','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R1E','Gas fired radiant tube - linear model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R1EL','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R2E','Gas fired radiant tube - linear model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R2EL','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R2ES','Gas fired radiant tube - linear model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R2ESL','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R3E','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R3E9','Gas fired radiant tube - linear model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R3EL','Gas fired radiant tube - U model','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','R4E','Wall gasket  Ø 100 mm.  Int.. , Ø 165  mm.  Ext. , EPDM rubber ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RA101.102','Adjustable lead flashing, with adjustable cover  0°/35°, gasket and stainless steel collar  210','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RA101.103','External combustion group 100 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF100.09','External combustion group two stages 100 kW - 80kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF100.2S','External combustion group two stages 100 kW - 80kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF100.2S.CI','External combustion group 150 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF150.09','External combustion group 200 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF200.09','External combustion group two stages 200 kW - 150kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF200.2S','External combustion group two stages 200 kW - 150kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF200.2S.CI','External combustion group 300 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF300S','External combustion group 300 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF300S.CI','External combustion group 35 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF35.09','External combustion group 50 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF50.09','External combustion group 80 kW','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RCF80.09','Speed controller - single phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVM 14','Speed controller - single phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVM 3.5','Speed controller - single phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVM 6','Speed controller - single phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVM 9','Speed controller - three phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVT 14','Speed controller - three phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVT 2','Speed controller - three phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVT 4','Speed controller - three phase','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','RVT 7','INFRA-ONE BUS System, black bulb sensor for 1 Tub One','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SCGSPTC/C','Electronic controller for 1 Tub One, two stages, with sensor, reset switch  with two temp levels and clock','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SCP015V104','Electronic controller for 1 Tub One, two stages, with sensor, reset switch  with two temp levels and clock','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SCP015V105','Ø250 double pipe radiant strip for 30° vertical movement for RCF 80/100/150/200/300  A','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.30HAC','Ø250 double pipe radiant strip for 30° vertical movement for RCF 80/100/150/200/300  C','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.30HCC','Ø250 double pipe radiant strip for 45° vertical movement for RCF 80/100/150/200/300  A','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.45HAC','Ø250 double pipe radiant strip for 45° vertical movement for RCF 80/100/150/200/300  C','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.45HCC','Ø250 single pipe radiant strip for 45° vertical movement for RCF 80/100/150/200/300  A','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.45HMAC','Ø250 single pipe radiant strip for 45° vertical movement for RCF 80/100/150/200/300  C','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','SV2.45HMCC','Terminal chimney  Ø 150 mm , for roof or wall','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.146','Flue pipe, 1.000 mm length,  Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.220','Flue pipe, 500 mm length,  Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.221','Terminal chimney  Ø 100 mm , for roof or wall','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.223','Flue pipe with plug for combustion analysis, 250 mm. length, Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.225','Roof flue pipe,  1.000 mm length,  Ø 100 mm., for connection with  flashing and terminal chimney ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.226','Flue elbow  90°, Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.230','Flue elbow  45°, Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.231','T  pipe   90° , Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.232','Vertical condense discharger,  Ø 100 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.233','Flue pipe with plug for combustion analysis, 250 mm. length, Ø 150 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.333','Flue pipe, 1.000 mm length,  Ø 150 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T   101.334','90° Roof Kit for RCF 80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T 101.358','90° Roof Kit for  RCF 150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T 101.359','RED SILICON CARTRIDGE H.T. 280 ml.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.101','INSULATIONS L. 2000 - 3Pcs.( 1on top + 2 on the sides)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.102','HINGE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.105','BURNER SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.114','BURNER SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.115','RADIANT SECTION SIDE PANEL - 2000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.123','RADIANT SECTION SIDE PANEL - 1000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.124','FAN COCHLEA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.126','FAN COCHLEA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.128','RADIANT SECTION SIDE PANEL - 300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.129','OMEGA ELECTRICAL SUPPORT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.132','COMPLETE BY-PASS','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.138','THREADED CONNECTION 1/2" - FOR GAS VALVE DUNGS','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.139','GAS VALVE KROMS. CG_120R01-DT2WF1 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.140','FLANGE 3/4" DIR. - GAS VALVE DUNGS MB... 407 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.141','FLANGE 1/2" 90° - GAS VALVE DUNGS','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.142','FEMALE BRACKET ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.149','FLAME CONTROLLER CM 32 PR ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.150','START UP TRANSFORMER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.151','POST VENTILATION TIMER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.160','HEAT RELAY - 2.2 ÷ 3.2 A - SIEMENS 3RU11 16-1DBO - ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.162','AIR BRAKE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.165','MALE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.170','FEMALE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.171','STEEL BAR TO LINK TUBES','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.172','COLLAR / RING  Ø 160 - TO SUPPORT THE TUBE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.173','INSULATION L. 2000 ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.197','Stainless steel isolated double wall pipe Ø250,  1 mt lenght','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.200','Stainless steel isolated double wall pipe Ø250,  0,5 mt lenght','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.201','Stainless steel isolated double wall pipe Ø250,  0,250 mt lenght','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.202','Stainless steel isolated double wall 45° elbow Ø250','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.203','Exiting male junction Ø250','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.207 ','Entering male junction Ø250','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.208','RADIANT SECTION SIDE PANEL - 4000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.210','RADIANT SECTION SIDE PANEL - 400','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.211','RADIANT SECTION SIDE PANEL - 300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.212','RADIANT SECTION SIDE PANEL - 1000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.213','RADIANT SECTION SIDE PANEL - 700','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.214','RADIANT SECTION SIDE PANEL - 2000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.215','Flues ducts lenght 1000, Ø 100mm ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.220','Flues ducts lenght 500, Ø 100mm , for RCF80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.221','Flues 90° bend, Ø 100mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.230','Flues 45° bend, Ø 100mm, for RCF80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.231','Black spray paint can','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.235','GAS VALVE KROMS. CG 225.R01.DT2 - SINGLE STAGE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.241','FLANGE CONNECTION 3/4" - ATTACHMENT GAS VALVE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.245','Grey silicon cartridge for sealing the burner on the wall','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.273','EXHAUST FAN ENGINE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.277','EXHAUST FAN ENGINE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.278','EXHAUST FAN VENTILATOR - LG -( STANDARD )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.283','EXHAUST FAN VENTILATOR - LG -( STANDARD )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.284','ENGINE CONTACTOR - 5,5 kW - SIEMENS 3RT1017 1AP01  ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.291','HEAT RELAY - 2,8 ÷ 4 A - SIEMENS 3RU 1116 1EBO','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.292','HEAT RELAY - 7 ÷ 10 A - SIEMENS 3RU1116-1JB0','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.293','KIT SUBSTITUTION GAS VALVE DUNGS TO GAS VALVE SIT 822','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.296','GAS VALVE SUPPORT BRACKET 1" 1/4','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.305','FAN COCHLEA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.321','DETECTION + START UP COMPLETE GROUP','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.323','PRE-NOZZLE Ø 1/2.10,5 - NATURAL GAS','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.324','BURNER SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.325','PRE-NOZZLE Ø 1/2.9,5 - LPG','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.327','Flues ducts lenght 1000, Ø 150mm for RCF 150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.334','Flues 90° bend, Ø 150mm, for RCF150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.336','STAINLESS STEEL RAIN COVER FOR FLUE DISCHARGE Ø 150','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.337','COLLAR / RING  Ø 250 - TO SUPPORT THE TUBE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.356','Stainless steel isolated double wall 90° elbow Ø250','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.364','COMPLETE ENGINE (IMPRELLER + FLANGE)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.370','GAS VALVE DUNGS MB_ZRLDE 407 - TWO STAGE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.372','GAS VALVE KROMS. CG 225.R01-ZT2 - TWO STAGE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.374','Extensible stainless steel isolated double wall pipe Ø250,  500-300 mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.375','STAINLESS STEEL RAIN COVER FOR FLUE DISCHARGE Ø 100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.385','DETECTION + START UP COMPLETE GROUP - (DIVIDED)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.390','INTERMEDIATE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.403','FLANGED DUCT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.405','BURNER (TORCH) ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.407','Flues oblique flute terminal, Ø 100mm, for RCF 80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.411','Flues oblique flute terminal, Ø 150mm, for RCF 150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.412','ELECTRIC BOARD METAL COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.450','45° Roof Kit for RCF 80/100','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.460','45° Roof Kit for  RCF 150/200/300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.465','Kit for heating shielding,  2000mm x 700mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.473','BURNER (TORCH)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.503','FLANGED DUCT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.508','FLAME CONTROLLER DMN 32','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.550','EXHAUST FAN VENTILATOR - RD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.560','EXHAUST FAN VENTILATOR - RD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.561','HTSG SYSTEM CONNECTION - Ø 160','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.630','BLACK PAINTED PIPE Ø 250 - 4000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.700','BLACK PAINTED PIPE Ø 250 - 2000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.701','HTSG SYSTEM - Ø 250','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T101.703','GAS FLEXIBLE JOINT Ø 3/4"','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T108.108','LOCK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T108.109','NOZZLE TUBE - F. 1/8"','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T108.121','NOZZLE TUBE - D.12 - NATURAL GAS','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T108.121.M','GAS FLEXIBLE JOINT Ø 1/2"','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T108.127','BLACK PAINTED FINAL BEND 180° - ( x INT.320 )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.007','BLACK PAINTED PIPE Ø 300 x 4000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.012','NON PAINTED PIPE  Ø 300 x 4000','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.012/G','HTSG SYSTEM - Ø 300','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.015','BLACK PAINTED FINAL BEND 180° - ( x INT.320 )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.017','BLACK PAINTED BEND Ø250 / 90° - R.570 ( x INT. 320 )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.018','BLACK PAINTED BEND Ø250 / 90° - R.250 ( x INT.320 )','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T200.019','DUCT BRACKET / FLANGE ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.000','MALE BRACKET - 320 - 09','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.003','COLLAR / RING  Ø 300 - TO SUPPORT THE TUBE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.004','SINGLE TUBE SYSTEM MALE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.007','SINGLE TUBE SYSTEM FEMALE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.008','SINGLE TUBE SYSTEM INTERMEDIATE BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.009','STAINLESS STEEL TUBE FOR CUMBUSTION CHAMBER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.010','FLANGED DUCT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.011','STAINLEES STEEL LENGTH 2000MM - 1ST SECTION','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.013','ELECTRIC BOARD METAL COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.022','FLANGED CONNECTION 1/2" - FOR GAS VALVE SIT 822 NOVA','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.025','RIGHT DOOR - (WITH HOLES FOR LOCK)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.031','LEFT DOOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.032','TOP PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.033','LOWER PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.034','LEFT SIDE PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.035','RIGHT SIDE PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.036','REAR PANEL - (WALL SIDE)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.037','BURNER HOLDER PERFORATED PLATE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.039','RIGHT DOOR - (WITH HOLES FOR LOCK)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.040','LEFT DOOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.041','TOP PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.042','LOWER PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.043','LEFT SIDE PANEL - GAS VALVE SIDE ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.044','RIGHT SIDE PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.045','REAR PANEL - (WALL SIDE)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.046','TOP PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.049','BLIND SIDE PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.050','SIDE PANEL - WITH HOLE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.051','DOOR ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.052','LOWER PANEL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.053','REAR PANEL - (WALL SIDE)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.054','GAS VALVE SUPPORT BRACKET FOR RCF300S','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T300.061','GAS FLEXIBLE JOINT Ø 1"1/4','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T400.001','FLAME CONTROLLER ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.000','ELECTRODES KIT','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.001','ACTUATOR AIR DUMPER BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.002','GAS VALVE DUNGS MB_DLE 407 - SINGLE STAGE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.003','GAS VALVE - SIT 822 NOVA - LPG','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.004','FLANGE 3/4" DIR.-GAS VALVE KROMS. CG_120R01-DT2','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.005','START UP CABLING FOR BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.011','DETECTION CABLING FOR BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.012','BURNER AIR PRESSOSTAT BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.013','BURNER FLANGE GASKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.014','GAS VALVE DUNGS MD …412  - TWO STAGE BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.015','START UP TRANSFORMER BTG28P','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T500.016','INFRA-ONE BUS System, main controller for 30 Tub One maximum, with external sensor and software','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T600.001','INFRA-ONE BUS System, remote controller for 1 Tub One ','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','T600.002','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA 159 ','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA 209 ','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA309SDS','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TC 109','Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TC 209','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','FPA109H  ','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','FPA159H    ','HEALTH COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C800.001H','HEALTH COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.240H','HEALTH COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C800.000H','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA159H     ','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA209H       ','FAN PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C700.013','FAN Ø555','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C700.012','COMPLETE VENTILATION GROUP (WITHOUT AIR CONVEYOR)','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C500.056','DRAIN SUPPORT + GASKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.101','SLAVE PRINTED CIRCUIT - SCP015V153/A','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC600.059','DISPLAY SCRE10A','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C104.160','SPEED VARIATOR – 3 A.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.107','PLC MODULE','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.104','WATER RECIRCULATION PUMP + FILTER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','MAC800.007','RECIRCULATION PUMP SUPPORT BRACKET','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.197','SPEED VARIATOR – 6 A.','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C102.138','TANK','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C200.038','BASE DUCT - TA209 - 300X590X1185mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.900','BASE DUCT ADAPTER - TA209 - from 590X1185mm to 600X1150mm','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.951','WATER DISTRIBUTOR - TA209-2SD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.250','FRONT PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.235','SIDE PROTECTION GRILL','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.234','COOLING PAD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.240','CORNER COLUMN - TA209-2SD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.236','CENTRAL COLUMN - TA209-2SD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.233','FAN MOUNTING PANEL - TA209-2SD','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C101.231','WINTER COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C431.011','FAN Ø555','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C700.011','RECIRCULATION PUMP FILTER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C300.185','HOSE CONNECTOR','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C103.183','WINTER COVER','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','C431.005','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TC109H','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TC209H','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA309H','Health Evaporative cooler','')
insert into deslingue (iddesling,tipodes,lingua,codice,descri,desest) values ('_'+RIGHT(NEWID(),9),'ARTICOLO','008','TA209-2SDH','','')



select * from deslingue where tipodes = 'ARTICOLO' ORDER BY CODICE
