
UPDATE PARA SET DISATTIVO = 1 WHERE CODICE LIKE 'LNG%' AND CODICE NOT IN ('LNG008','LNG010')
UPDATE U_CLI_AN SET CLI_LINGUA = '010' WHERE CLI_LINGUA = '' AND CLI_NAZION = 'ITA'
UPDATE U_CLI_AN SET CLI_LINGUA = '008' WHERE CLI_LINGUA = '' AND CLI_NAZION <> 'ITA'