
/*UPDATE U_ORD_DD
SET ORD_QTAEV= ( SELECT ORD_QTAEV FROM QTA_DA_AGGIORNARE WHERE ORD_LEGSYS=LEGSYS )
WHERE ORD_LEGSYS IN (SELECT LEGSYS FROM QTA_DA_AGGIORNARE)
*/

SELECT TAGGANCIO, ORD_NUMORD, ORD_DATORD, ORD_CHIUSO 
FROM U_ORD_TT 
WHERE ORD_CHIUSO=0
AND TAGGANCIO IN (SELECT DAGGANCIO FROM U_ORD_DD WHERE ORD_QTAORD=ORD_QTAEV AND ORD_CHIUSO=0)
ORDER BY ORD_DATORD,ORD_NUMORD


UPDATE U_ORD_DD SET ORD_CHIUSO=1
WHERE ORD_QTAORD=ORD_QTAEV AND ORD_CHIUSO=0 


SELECT 
	ORD_LEGSYS,
	ORS_NUMORD,
	ORS_DATORD,
	ORS_CODCLI,
	ORS_RAGSOC,
	ORD_CODART,
	ORD_DATCON,
	ORD_QTAORD,
	ORD_QTAEV,
	ORD_CHIUSO
FROM U_ORD_DD WHERE ORD_QTAORD=ORD_QTAEV AND ORD_CHIUSO=0
ORDER BY ORS_DATORD,ORS_NUMORD


SELECT ORD_DATORD,ORD_NUMORD,ORD_CODCLI,ORD_RAGSOC,* FROM U_ORD_TT
WHERE TAGGANCIO IN (
SELECT DAGGANCIO FROM (
SELECT DISTINCT DAGGANCIO, ORS_DATORD,ORS_NUMORD , ORD_CHIUSO
FROM U_ORD_DD WHERE ORD_QTAORD=ORD_QTAEV AND ORD_QTAORD<>0 
AND ORD_CHIUSO=1) AS T1 )
AND ORD_CHIUSO=0
ORDER BY ORD_DATORD,ORD_NUMORD 

UPDATE U_ORD_TT 
SET ORD_CHIUSO=1 

SELECT * FROM U_ORD_TT
WHERE TAGGANCIO IN  (
SELECT DAGGANCIO FROM (
SELECT COUNT(*) AS CONTA, DAGGANCIO, ORS_DATORD,ORS_NUMORD  FROM  (
SELECT DISTINCT DAGGANCIO, ORS_DATORD,ORS_NUMORD , ORD_CHIUSO
FROM U_ORD_DD WHERE ORD_QTAORD<>0 ) AS T1
GROUP BY  DAGGANCIO, ORS_DATORD,ORS_NUMORD  ) AS T1
WHERE CONTA=1 ) 
AND TAGGANCIO NOT IN (SELECT DAGGANCIO FROM U_ORD_DD WHERE ORD_QTAORD<>0 AND ORD_CHIUSO=0)
AND ORD_CHIUSO=0



