-- 5000000215
SELECT * FROM U_ORD_TT ORDER BY TAGGANCIO DESC

-- 5000005125
SELECT * FROM U_BOL_TT ORDER BY TAGGANCIO DESC


SELECT DISTINCT ORS_NUMORD,ORS_DATORD,ORS_CODCLI,ORS_RAGSOC
FROM U_ORD_DD
WHERE ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
AND DAGGANCIO <= '5000000215'
ORDER BY ORS_DATORD,ORS_NUMORD



SELECT * FROM(
SELECT 
	NEW.ORD_LEGSYS,
	NEW.ORS_NUMORD,
	NEW.ORS_DATORD,
	NEW.ORS_CODCLI,
	NEW.ORS_RAGSOC,
	NEW.ORD_CODART,
	NEW.ORD_QTAORD AS ORDINATA,
	COALESCE(OLD.ORD_QTAEV,0) AS EVASA_VECCHIO,
	NEW.ORD_QTAEV AS EVASA_NUOVO_SBAGLIATO,
	NEW.ORD_QTAORD - NEW.ORD_QTAEV AS DA_EVADERE_NUOVO_SBAGLIATO,
	COALESCE(OLD.ORD_QTAEV,0)+ NEW.ORD_QTAEV AS EVASA_EFFETTIVA,
	NEW.ORD_QTAORD - (COALESCE(OLD.ORD_QTAEV,0) + NEW.ORD_QTAEV ) AS DA_EVADERE_EFFETTIVO
FROM U_ORD_DD AS NEW
LEFT OUTER JOIN GLCABLAGGI_TEST.DBO.U_ORD_DD AS OLD
ON NEW.ORS_NUMORD=OLD.ORS_NUMORD 
	AND NEW.ORS_DATORD=OLD.ORS_DATORD
	AND NEW.ORD_CODART=OLD.ORD_CODART
	AND NEW.ORD_DATCON=OLD.ORD_DATCON
WHERE NEW.ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
AND NEW.DAGGANCIO <= '5000000215' ) AS T1
WHERE NOT (EVASA_VECCHIO =0 AND EVASA_NUOVO_SBAGLIATO = ORDINATA)
ORDER BY ORS_DATORD,ORS_NUMORD




SELECT * FROM (
SELECT ORS_NUMORD,ORS_DATORD,ORD_CODART,ORD_DATCON, COUNT(*) AS CONTA 
FROM U_ORD_DD
WHERE ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
AND DAGGANCIO <= '5000000215'
GROUP BY ORS_NUMORD,ORS_DATORD,ORD_CODART,ORD_DATCON) AS T1
WHERE CONTA >1













SELECT 
	ORD_LEGSYS,
	ORS_NUMORD,
	ORS_DATORD,
	ORS_CODCLI,
	ORS_RAGSOC,
	ORD_CODART,
	ORD_DATCON,
	ORD_QTAORD,
	(SELECT DA_SOSTITUIRE FROM (
		SELECT *,
		CASE WHEN  EVASA_EFFETTIVA>ORDINATA THEN ORDINATA ELSE EVASA_EFFETTIVA END AS DA_SOSTITUIRE FROM(
		SELECT 
			NEW.ORD_LEGSYS,
			NEW.ORS_NUMORD,
			NEW.ORS_DATORD,
			NEW.ORS_CODCLI,
			NEW.ORS_RAGSOC,
			NEW.ORD_CODART,
			NEW.ORD_QTAORD AS ORDINATA,
			COALESCE(OLD.ORD_QTAEV,0) AS EVASA_VECCHIO,
			NEW.ORD_QTAEV AS EVASA_NUOVO_SBAGLIATO,
			NEW.ORD_QTAORD - NEW.ORD_QTAEV AS DA_EVADERE_NUOVO_SBAGLIATO,
			COALESCE(OLD.ORD_QTAEV,0)+ NEW.ORD_QTAEV AS EVASA_EFFETTIVA,
			NEW.ORD_QTAORD - (COALESCE(OLD.ORD_QTAEV,0) + NEW.ORD_QTAEV ) AS DA_EVADERE_EFFETTIVO
		FROM U_ORD_DD AS NEW
		LEFT OUTER JOIN GLCABLAGGI_TEST.DBO.U_ORD_DD AS OLD
		ON NEW.ORS_NUMORD=OLD.ORS_NUMORD 
			AND NEW.ORS_DATORD=OLD.ORS_DATORD
			AND NEW.ORD_CODART=OLD.ORD_CODART
			AND NEW.ORD_DATCON=OLD.ORD_DATCON
		WHERE NEW.ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
		AND NEW.DAGGANCIO <= '5000000215' ) AS T1
		WHERE NOT (EVASA_VECCHIO =0 AND EVASA_NUOVO_SBAGLIATO = ORDINATA) AND T1.ORD_LEGSYS=DD.ORD_LEGSYS )AS T2   ) AS ORD_QTAEV
FROM U_ORD_DD AS DD
WHERE ORD_LEGSYS IN (SELECT ORD_LEGSYS FROM(
SELECT 
	NEW.ORD_LEGSYS,
	NEW.ORS_NUMORD,
	NEW.ORS_DATORD,
	NEW.ORS_CODCLI,
	NEW.ORS_RAGSOC,
	NEW.ORD_CODART,
	NEW.ORD_QTAORD AS ORDINATA,
	COALESCE(OLD.ORD_QTAEV,0) AS EVASA_VECCHIO,
	NEW.ORD_QTAEV AS EVASA_NUOVO_SBAGLIATO,
	NEW.ORD_QTAORD - NEW.ORD_QTAEV AS DA_EVADERE_NUOVO_SBAGLIATO,
	COALESCE(OLD.ORD_QTAEV,0)+ NEW.ORD_QTAEV AS EVASA_EFFETTIVA,
	NEW.ORD_QTAORD - (COALESCE(OLD.ORD_QTAEV,0) + NEW.ORD_QTAEV ) AS DA_EVADERE_EFFETTIVO
FROM U_ORD_DD AS NEW
LEFT OUTER JOIN GLCABLAGGI_TEST.DBO.U_ORD_DD AS OLD
ON NEW.ORS_NUMORD=OLD.ORS_NUMORD 
	AND NEW.ORS_DATORD=OLD.ORS_DATORD
	AND NEW.ORD_CODART=OLD.ORD_CODART
	AND NEW.ORD_DATCON=OLD.ORD_DATCON
WHERE NEW.ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
AND NEW.DAGGANCIO <= '5000000215' ) AS T1
WHERE NOT (EVASA_VECCHIO =0 AND EVASA_NUOVO_SBAGLIATO = ORDINATA) )
ORDER BY  ORS_DATORD,ORS_NUMORD





