  


/****** Oggetto:  View [dbo].[QTA_DA_AGGIORNARE]    Data script: 01/20/2011 08:42:57 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[QTA_DA_AGGIORNARE]'))
DROP VIEW [dbo].[QTA_DA_AGGIORNARE]

GO

CREATE VIEW [dbo].[QTA_DA_AGGIORNARE]
AS


SELECT ORD_LEGSYS AS LEGSYS,ORD_QTAEV FROM 
(SELECT 
	ORD_LEGSYS,
	ORS_NUMORD,
	ORS_DATORD,
	ORS_CODCLI,
	ORS_RAGSOC,
	ORD_CODART,
	ORD_DATCON,
	ORD_QTAORD,
	(SELECT DA_SOSTITUIRE FROM (
		SELECT *,
		CASE WHEN  EVASA_EFFETTIVA>ORDINATA THEN ORDINATA ELSE EVASA_EFFETTIVA END AS DA_SOSTITUIRE FROM(
		SELECT 
			NEW.ORD_LEGSYS,
			NEW.ORS_NUMORD,
			NEW.ORS_DATORD,
			NEW.ORS_CODCLI,
			NEW.ORS_RAGSOC,
			NEW.ORD_CODART,
			NEW.ORD_QTAORD AS ORDINATA,
			COALESCE(OLD.ORD_QTAEV,0) AS EVASA_VECCHIO,
			NEW.ORD_QTAEV AS EVASA_NUOVO_SBAGLIATO,
			NEW.ORD_QTAORD - NEW.ORD_QTAEV AS DA_EVADERE_NUOVO_SBAGLIATO,
			COALESCE(OLD.ORD_QTAEV,0)+ NEW.ORD_QTAEV AS EVASA_EFFETTIVA,
			NEW.ORD_QTAORD - (COALESCE(OLD.ORD_QTAEV,0) + NEW.ORD_QTAEV ) AS DA_EVADERE_EFFETTIVO
		FROM U_ORD_DD AS NEW
		LEFT OUTER JOIN GLCABLAGGI_TEST.DBO.U_ORD_DD AS OLD
		ON NEW.ORS_NUMORD=OLD.ORS_NUMORD 
			AND NEW.ORS_DATORD=OLD.ORS_DATORD
			AND NEW.ORD_CODART=OLD.ORD_CODART
			AND NEW.ORD_DATCON=OLD.ORD_DATCON
		WHERE NEW.ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
		AND NEW.DAGGANCIO <= '5000000215' ) AS T1
		WHERE NOT (EVASA_VECCHIO =0 AND EVASA_NUOVO_SBAGLIATO = ORDINATA) AND T1.ORD_LEGSYS=DD.ORD_LEGSYS )AS T2   ) AS ORD_QTAEV
FROM U_ORD_DD AS DD
WHERE ORD_LEGSYS IN (SELECT ORD_LEGSYS FROM(
SELECT 
	NEW.ORD_LEGSYS,
	NEW.ORS_NUMORD,
	NEW.ORS_DATORD,
	NEW.ORS_CODCLI,
	NEW.ORS_RAGSOC,
	NEW.ORD_CODART,
	NEW.ORD_QTAORD AS ORDINATA,
	COALESCE(OLD.ORD_QTAEV,0) AS EVASA_VECCHIO,
	NEW.ORD_QTAEV AS EVASA_NUOVO_SBAGLIATO,
	NEW.ORD_QTAORD - NEW.ORD_QTAEV AS DA_EVADERE_NUOVO_SBAGLIATO,
	COALESCE(OLD.ORD_QTAEV,0)+ NEW.ORD_QTAEV AS EVASA_EFFETTIVA,
	NEW.ORD_QTAORD - (COALESCE(OLD.ORD_QTAEV,0) + NEW.ORD_QTAEV ) AS DA_EVADERE_EFFETTIVO
FROM U_ORD_DD AS NEW
LEFT OUTER JOIN GLCABLAGGI_TEST.DBO.U_ORD_DD AS OLD
ON NEW.ORS_NUMORD=OLD.ORS_NUMORD 
	AND NEW.ORS_DATORD=OLD.ORS_DATORD
	AND NEW.ORD_CODART=OLD.ORD_CODART
	AND NEW.ORD_DATCON=OLD.ORD_DATCON
WHERE NEW.ORD_LEGSYS IN (SELECT DISTINCT ORD_LEGSYS FROM U_BOL_DD WHERE DAGGANCIO > '5000005125')
AND NEW.DAGGANCIO <= '5000000215' ) AS T1
WHERE NOT (EVASA_VECCHIO =0 AND EVASA_NUOVO_SBAGLIATO = ORDINATA) ) ) AS T3


GO



